Define unified interface for Cairo compilation in `compiler` crate
starkware-libs/cairo pull request #1118
Opened 2022-11-28 11:04 UTC by mkaput

This PR tries to make a proper _self-containing_ library out of the `compiler` crate, enabling users to call the compiler with a high-level API that does not depend on other crates from this project. Thanks to this change, the Package Manager only depends on the `compiler` crate and `compile` function and `ProjectConfig` struct from it, and thus it does not have to think about databases and other implementation details.

The design around `CompileProjectConfig` would definitely need more iterations in subsequent PRs, but I did this that way because I couldn't find any easy and non-invasive way to support compilation of single Cairo file only by declaring `ProjectConfig` (the part where `setup_*` functions are preparing stub `lib.cairo` module directly in `RootDatabase` is tricky to be precise).

2022-11-29 08:30 UTC, ilyalesokhin-starkware requested changes
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1118)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[`crates/compiler/src/diagnostics.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1118#-NI1UX0-AYJHEQxyRzp7:-NI1UX009IpN9aE85qzP:bvk7d9b) ([raw file](https://github.com/starkware-libs/cairo/blob/a9a40e4420b37050e5850e1c1ca5a724be19b918/crates/compiler/src/diagnostics.rs#L12)):*
> ```XML
> use crate::db::RootDatabase;
> 
> /// Check if there are diagnostics and prints them to stderr
> ```

fix comment.



_Code quote:_
```XML
 if there are diagnostics and prints them to stderr
```


<!-- Sent from Reviewable.io -->

2022-11-29 10:13 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1118)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/compiler/src/diagnostics.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1118#-NI1UX0-AYJHEQxyRzp7:-NI1sBwz7hPwoeR1DlnU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a9a40e4420b37050e5850e1c1ca5a724be19b918/crates/compiler/src/diagnostics.rs#L12)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

fix comment.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-30 08:58 UTC, ilyalesokhin-starkware requested changes
> Reviewed 2 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1118)* status: 2 of 12 files reviewed, 2 unresolved discussions (waiting on @mkaput and @spapinistarkware)

___
*[`crates/compiler/src/diagnostics.rs` line 12 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1118#-NI6k4hX7I65c9_rrw1f:-NI6k4hX7I65c9_rrw1g:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e23697c3753f1d90ca4e9edd0741ab6fc1416c9b/crates/compiler/src/diagnostics.rs#L12)):*
> ```XML
> use crate::db::RootDatabase;
> 
> /// Checks if there are diagnostics and reports them to provided callback, stringified.
> ```





_Suggestion:_
```XML
the provided callback as strings.
```
___
*[`crates/compiler/src/lib.rs` line 19 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1118#-NI6kJKG0JvAajX-6BCS:-NI6kJKG0JvAajX-6BCT:box9vc0) ([raw file](https://github.com/starkware-libs/cairo/blob/e23697c3753f1d90ca4e9edd0741ab6fc1416c9b/crates/compiler/src/lib.rs#L19)):*
> ```XML
> 
> pub struct CompileArgs<'c> {
>     pub compile: CompileProjectConfig,
> ```

please rename to project_config or something more descriptive.

also, maybe the interface should just be Vec<CrateID>?

and the caller should setup the project?



_Suggestion:_
```XML
project_config
```


<!-- Sent from Reviewable.io -->

2022-11-30 09:16 UTC, spapinistarkware requested changes
> Reviewed 2 of 6 files at r3, 5 of 10 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1118)* status: all files reviewed, 4 unresolved discussions (waiting on @mkaput)

___
*[`crates/compiler/src/lib.rs` line 40 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1118#-NI6o2kM9NwmQURBRHlb:-NI6o2kM9NwmQURBRHlc:b-sukilg) ([raw file](https://github.com/starkware-libs/cairo/blob/e23697c3753f1d90ca4e9edd0741ab6fc1416c9b/crates/compiler/src/lib.rs#L40)):*
> ```XML
> 
> pub fn compile(args: CompileArgs<'_>) -> Result<SierraProgram> {
>     let mut db = RootDatabase::default();
> ```

why not init_db?



_Code quote:_
```XML
ootDatabase::default();
```
___
*[`crates/compiler/src/lib.rs` line 44 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1118#-NI6oAzTBqUYsKwXQvO_:-NI6oAzTBqUYsKwXQvOa:b-tor8xb) ([raw file](https://github.com/starkware-libs/cairo/blob/e23697c3753f1d90ca4e9edd0741ab6fc1416c9b/crates/compiler/src/lib.rs#L44)):*
> ```XML
> }
> 
> pub fn compile_with_db(
> ```

Why isnt this a method of CompilerDatabase (which could be a wrapper instead of an alias)?


<!-- Sent from Reviewable.io -->

2022-11-30 11:29 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1118)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware, @mkaput, and @spapinistarkware)

___
*[`crates/compiler/src/diagnostics.rs` line 12 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1118#-NI6k4hX7I65c9_rrw1f:-NI77D23EwkkV2CUFaPR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e23697c3753f1d90ca4e9edd0741ab6fc1416c9b/crates/compiler/src/diagnostics.rs#L12)):*
> ```XML
> use crate::db::RootDatabase;
> 
> /// Checks if there are diagnostics and reports them to provided callback, stringified.
> ```

Done.
___
*[`crates/compiler/src/lib.rs` line 19 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1118#-NI6kJKG0JvAajX-6BCS:-NI7AYRbDK6ekA9RrKQh:bx3r78l) ([raw file](https://github.com/starkware-libs/cairo/blob/e23697c3753f1d90ca4e9edd0741ab6fc1416c9b/crates/compiler/src/lib.rs#L19)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

please rename to project_config or something more descriptive.

also, maybe the interface should just be Vec<CrateID>?

and the caller should setup the project?
</blockquote></details>

Renamed to `setup`. 

The problem here is that setup operation does some hacks with the database internally if you pass a path to bare `*.cairo` file, which I am unable to represent with a `ProjectConfig` without making **a lot** of changes. I wanted to defer doing this to separate PRs, possibly done on your side.
___
*[`crates/compiler/src/lib.rs` line 40 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1118#-NI6o2kM9NwmQURBRHlb:-NI7At4p2Fmfo6ct6ng9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e23697c3753f1d90ca4e9edd0741ab6fc1416c9b/crates/compiler/src/lib.rs#L40)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

why not init_db?
</blockquote></details>

Done.
___
*[`crates/compiler/src/lib.rs` line 44 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1118#-NI6oAzTBqUYsKwXQvO_:-NI7Au1n0jcXJmIiGKN3:b-vowmtj) ([raw file](https://github.com/starkware-libs/cairo/blob/e23697c3753f1d90ca4e9edd0741ab6fc1416c9b/crates/compiler/src/lib.rs#L44)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why isnt this a method of CompilerDatabase (which could be a wrapper instead of an alias)?
</blockquote></details>

Partially done but doesn't work yet due to problem with setups


<!-- Sent from Reviewable.io -->

2022-11-30 11:46 UTC, ilyalesokhin-starkware reviewed
> Reviewed 1 of 6 files at r3, 2 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1118)* status: 7 of 13 files reviewed, 2 unresolved discussions (waiting on @mkaput and @spapinistarkware)

___
*[`crates/compiler/src/diagnostics.rs` line 12 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1118#-NI6k4hX7I65c9_rrw1f:-NI7M5NQ0isWTI1FcNDf:b-ylrcea) ([raw file](https://github.com/starkware-libs/cairo/blob/e23697c3753f1d90ca4e9edd0741ab6fc1416c9b/crates/compiler/src/diagnostics.rs#L12)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why did you remove this file?


<!-- Sent from Reviewable.io -->

2022-11-30 12:08 UTC, ilyalesokhin-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1118)* status: 7 of 13 files reviewed, 2 unresolved discussions (waiting on @mkaput and @spapinistarkware)

___
*[`tests/examples_test.rs` line 26 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1118#-NI7Qlq9CbEnU9KUQd8e:-NI7Qlq9CbEnU9KUQd8f:bvkz208) ([raw file](https://github.com/starkware-libs/cairo/blob/5dcfcaa001dafae518b9c14a955fc76a671ad061/tests/examples_test.rs#L26)):*
> ```XML
>     path.push(format!("{name}.cairo"));
> 
>     todo!("not working")
> ```

How are you planning to fix this?

even if we remove the single-file compilation, we need to support compiling things from the db.



_Code quote:_
```XML
todo!("not working")
```


<!-- Sent from Reviewable.io -->

2022-11-30 12:08 UTC, ilyalesokhin-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1118)* status: 7 of 13 files reviewed, 2 unresolved discussions (waiting on @mkaput and @spapinistarkware)

___
*[`tests/examples_test.rs` line 26 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1118#-NI7Qlq9CbEnU9KUQd8e:-NI7QxC07qdwe90iq7H9:b6kj8xb) ([raw file](https://github.com/starkware-libs/cairo/blob/5dcfcaa001dafae518b9c14a955fc76a671ad061/tests/examples_test.rs#L26)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

How are you planning to fix this?

even if we remove the single-file compilation, we need to support compiling things from the db.
</blockquote></details>

Maybe we need to API,

one that gets crate_ids and used by the compiler
and another one that gets project configs and calls the first one?


<!-- Sent from Reviewable.io -->

2022-11-30 12:35 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1118)* status: 7 of 13 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/compiler/src/diagnostics.rs` line 12 at r5](https://reviewable.io/reviews/starkware-libs/cairo/1118#-NI6k4hX7I65c9_rrw1f:-NI7X3g14h8d8NbegBR5:b-apbvon) ([raw file](https://github.com/starkware-libs/cairo/blob/e23697c3753f1d90ca4e9edd0741ab6fc1416c9b/crates/compiler/src/diagnostics.rs#L12)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why did you remove this file?
</blockquote></details>

It was moved to `CompilerDatabase::check_diagnostics`. But that's not good design either


<!-- Sent from Reviewable.io -->

2022-11-30 15:28 UTC, spapinistarkware reviewed
> Reviewed 2 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1118)* status: 7 of 13 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @mkaput)

___
*[`crates/compiler/src/lib.rs` line 97 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1118#-NI88k8l4H8rbuHDhhs_:-NI88k8l4H8rbuHDhhsa:b6hh0lz) ([raw file](https://github.com/starkware-libs/cairo/blob/5dcfcaa001dafae518b9c14a955fc76a671ad061/crates/compiler/src/lib.rs#L97)):*
> ```XML
>     ///
>     /// Returns `true` if diagnostics were found.
>     pub fn check_diagnostics(&mut self) -> bool {
> ```

Why did it move?


<!-- Sent from Reviewable.io -->

2022-12-01 11:00 UTC, mkaput reviewed
I have removed all refactorings that tried to deduplicate code. I'm leaving this up to you, because I am sure I wouldn't be able to make the code & review cycle in this area before going offline.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1118#-:-NICKueIApIfFTlUwMpy:bt1zc5s)* status: 5 of 13 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/compiler/src/lib.rs` line 97 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1118#-NI88k8l4H8rbuHDhhs_:-NICKsO8-1j-oxJ6jZV8:bpfrtip) ([raw file](https://github.com/starkware-libs/cairo/blob/5dcfcaa001dafae518b9c14a955fc76a671ad061/crates/compiler/src/lib.rs#L97)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why did it move?
</blockquote></details>

Reverted back this change
___
*[`tests/examples_test.rs` line 26 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1118#-NI7Qlq9CbEnU9KUQd8e:-NICKr5s5SFArU-15XHI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5dcfcaa001dafae518b9c14a955fc76a671ad061/tests/examples_test.rs#L26)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Maybe we need to API,

one that gets crate_ids and used by the compiler
and another one that gets project configs and calls the first one?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-01 11:20 UTC, spapinistarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 8 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1118#-:-NICPk_rExo9QVdb9mm0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2022-12-01 11:37 UTC, ilyalesokhin-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 6 files at r3, 3 of 5 files at r5, 1 of 8 files at r6, 6 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1118#-:-NICTYFj30gkI_agrkJM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2022-12-01 11:42 UTC, merged