Update contract syntax.
starkware-libs/cairo pull request #1359
Opened 2022-12-15 17:06 UTC by ilyalesokhin-starkware

2022-12-18 07:17 UTC, orizi requested changes
> Reviewed 12 of 14 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1359)* status: 14 of 15 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/starknet/src/contract.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJZ3YNv5nLNqK1BPRLu:-NJZ3YNv5nLNqK1BPRLv:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/44aad3237a05209e2ffb89221412d69300c96148/crates/starknet/src/contract.rs#L65)):*
> ```XML
> }
> 
> pub fn get_external_functions(
> ```

doc



_Code quote:_
```XML
get_external_functions
```
___
*[`crates/starknet/src/contract.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJZ3qVE7AQnHp7DRWL1:-NJZ3qVE7AQnHp7DRWL2:b-lpjn2o) ([raw file](https://github.com/starkware-libs/cairo/blob/44aad3237a05209e2ffb89221412d69300c96148/crates/starknet/src/contract.rs#L75)):*
> ```XML
>         .module_items(module_id)
>         .to_option()
>         .with_context(|| "Failed to get module items.")?
> ```

is there any bad user code that may cause this?



_Code quote:_
```XML
Failed to get module items.
```
___
*[`crates/starknet/src/contract.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJZ3ujM2mSv8vh6j20R:-NJZ3ujM2mSv8vh6j20S:b-lpjn2o) ([raw file](https://github.com/starkware-libs/cairo/blob/44aad3237a05209e2ffb89221412d69300c96148/crates/starknet/src/contract.rs#L82)):*
> ```XML
>             .module_free_functions(ModuleId::Submodule(*external_module_id))
>             .to_option()
>             .with_context(|| "Failed to get module items.")?),
> ```

is there any bad user code that may cause this?



_Code quote:_
```XML
            .with_context(|| "Failed to get module items.")?),
```
___
*[`crates/starknet/src/contract.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJZ3fPBEal1REEjWKah:-NJZ3fPBEal1REEjWKai:b-nlutic) ([raw file](https://github.com/starkware-libs/cairo/blob/44aad3237a05209e2ffb89221412d69300c96148/crates/starknet/src/contract.rs#L83)):*
> ```XML
>             .to_option()
>             .with_context(|| "Failed to get module items.")?),
>         _ => anyhow::bail!("Failed to get the wrappers module."),
> ```

maybe?



_Suggestion:_
```XML
        _ => anyhow::bail!("Failed to get the entry points module."),
```
___
*[`crates/starknet/src/plugin.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJZ4FHSCMQ-96B9TAWW:-NJZ4FHSCMQ-96B9TAWX:b-9ckrcw) ([raw file](https://github.com/starkware-libs/cairo/blob/44aad3237a05209e2ffb89221412d69300c96148/crates/starknet/src/plugin.rs#L13)):*
> ```XML
> use crate::contract::starknet_keccak;
> 
> pub static WRAPPER_PREFIX: &str = "__wrapper_";
> ```

this is no longer used.



_Code quote:_
```XML
pub static WRAPPER_PREFIX: &str = "__wrapper_";
```
___
*[`crates/starknet/src/plugin_test.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJZ4hTU4uYoJa7j_uDb:-NJZ4hTU4uYoJa7j_uDc:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/44aad3237a05209e2ffb89221412d69300c96148/crates/starknet/src/plugin_test.rs#L49)):*
> ```XML
> 
> parser_test!(test_diagnostics, ["src/plugin_test_data/diagnostics",], test_expand_contract);
> parser_test!(test_wrapper_expansion, ["src/plugin_test_data/contract",], test_expand_contract);
> ```





_Suggestion:_
```XML
parser_test!(test_diagnostics, ["src/plugin_test_data/diagnostics",], test_expand_contract);
parser_test!(test_wrapper_expansion, ["src/plugin_test_data/contract",], test_expand_contract);
parser_test!(test_storage_expansion, ["src/plugin_test_data/storage",], test_expand_contract);
```
___
*[`crates/starknet/test_data/test_contract.cairo` line 13 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJZ4zG30uDKXSJJuqx3:-NJZ4zG30uDKXSJJuqx4:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/44aad3237a05209e2ffb89221412d69300c96148/crates/starknet/test_data/test_contract.cairo#L13)):*
> ```Cairo
> 
> 
> // # TODO(ilya): Convert to new format.
> ```





_Suggestion:_
```Cairo
// TODO(ilya): Convert to new format.
```


<!-- Sent from Reviewable.io -->

2022-12-18 07:22 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1359)* status: 10 of 15 files reviewed, 7 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/starknet/src/contract.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJZ3YNv5nLNqK1BPRLu:-NJZ5gF98yFK6GNDpIts:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/44aad3237a05209e2ffb89221412d69300c96148/crates/starknet/src/contract.rs#L65)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.



_Code quote:_
```XML
get_external_functions
```
___
*[`crates/starknet/src/contract.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJZ3qVE7AQnHp7DRWL1:-NJZ5h0H2y8Ii-asFXZR:bezajjq) ([raw file](https://github.com/starkware-libs/cairo/blob/44aad3237a05209e2ffb89221412d69300c96148/crates/starknet/src/contract.rs#L75)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is there any bad user code that may cause this?
</blockquote></details>

I don't think so
___
*[`crates/starknet/src/contract.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJZ3ujM2mSv8vh6j20R:-NJZ5lZcDncK3xXqH5cs:b-wtpjt4) ([raw file](https://github.com/starkware-libs/cairo/blob/44aad3237a05209e2ffb89221412d69300c96148/crates/starknet/src/contract.rs#L82)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is there any bad user code that may cause this?
</blockquote></details>

I don't think so.
___
*[`crates/starknet/src/contract.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJZ3fPBEal1REEjWKah:-NJZ5ppa1Ky2SokGtiKY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/44aad3237a05209e2ffb89221412d69300c96148/crates/starknet/src/contract.rs#L83)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe?
</blockquote></details>

Done.
___
*[`crates/starknet/src/plugin.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJZ4FHSCMQ-96B9TAWW:-NJZ5vcW-0-2ddhYzTAW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/44aad3237a05209e2ffb89221412d69300c96148/crates/starknet/src/plugin.rs#L13)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is no longer used.
</blockquote></details>

Done.
___
*[`crates/starknet/src/plugin_test.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJZ4hTU4uYoJa7j_uDb:-NJZ61XZ8AaeBLE0EVjU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/44aad3237a05209e2ffb89221412d69300c96148/crates/starknet/src/plugin_test.rs#L49)):*
> ```XML
> 
> parser_test!(test_diagnostics, ["src/plugin_test_data/diagnostics",], test_expand_contract);
> parser_test!(test_wrapper_expansion, ["src/plugin_test_data/contract",], test_expand_contract);
> ```

Done.
___
*[`crates/starknet/test_data/test_contract.cairo` line 13 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJZ4zG30uDKXSJJuqx3:-NJZ5UrM8x7r_vks9Wf5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/44aad3237a05209e2ffb89221412d69300c96148/crates/starknet/test_data/test_contract.cairo#L13)):*
> ```Cairo
> 
> 
> // # TODO(ilya): Convert to new format.
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-12-18 12:55 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 14 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1359#-:-NJ_IVq8AuVszpS-9W0_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2022-12-18 15:41 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1359#-:-NJ_tWif1B3k4828S-lQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2022-12-18 23:04 UTC, yuvalsw requested changes
> Reviewed 6 of 14 files at r1, 1 of 3 files at r2, 3 of 4 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1359)* status: all files reviewed, 20 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/defs/src/db.rs` line 137 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJb34Le3nnO3JUqvbyV:-NJb34Le3nnO3JUqvbyW:bw0ajua) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/defs/src/db.rs#L137)):*
> ```XML
>                     // This is an inline module, we return the file where the inline module was
>                     // defined. It can be either the file of the parent module
>                     // or a plugin-generated virtual file.
> ```

the code line below doesn't reflect that. You use the parent's file anyway.



_Code quote:_
```XML
or a plugin-generated virtual file.
```
___
*[`crates/defs/src/db.rs` line 237 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJb5Ch97HrZPUSHQI2u:-NJb5Ch97HrZPUSHQI2v:b-fbwr1v) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/defs/src/db.rs#L237)):*
> ```XML
>         ModuleId::Submodule(submodule_id) => {
>             let item_module_ast =
>                 &db.module_data(submodule_id.module(db))?.submodules[submodule_id];
> ```

I don't understand this logic. Previously it made sense as you looked for this module among the submodules of the parent. Now you look for this module among the submodule of this module.



_Code quote:_
```XML
            let item_module_ast =

                &db.module_data(submodule_id.module(db))?.submodules[submodule_id];
```
___
*[`crates/defs/src/db.rs` line 241 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJb6-CV1HrlXjYqPLot:-NJb6-CV1HrlXjYqPLou:bbh2to1) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/defs/src/db.rs#L241)):*
> ```XML
>             match item_module_ast.body(syntax_db) {
>                 MaybeModuleBody::Some(body) => body.items(syntax_db),
>                 MaybeModuleBody::None(_) => file_syntax.items(syntax_db),
> ```

not sure if directly related to this PR, but do we verify that we don't define 2 modules with the same files in different location?
Here there is no defence against this. If there are 2 "mod bla;" in 2 different files, module_data for both would work and return the same data.



_Code quote:_
```XML
file_syntax.items(syntax_db),
```
___
*[`crates/defs/src/db.rs` line 267 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJb73bL2jkM2PIzxH1M:-NJb73bL2jkM2PIzxH1N:bf0a315) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/defs/src/db.rs#L267)):*
> ```XML
>                     content: Arc::new(content),
>                 }));
>                 // TODO(ilya): Consider using non-virtual submodules for plugin-generated content.
> ```

is this still relevant?
___
*[`crates/semantic/src/resolve_path.rs` line 352 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJb914R0tW6s2b6Cq96:-NJb914R0tW6s2b6Cq97:bpd9k7o) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/semantic/src/resolve_path.rs#L352)):*
> ```XML
>                 }
>                 ModuleId::Submodule(submodule_id) => {
>                     self.db.lookup_intern_submodule(submodule_id).0.0
> ```

Isn't this submodule_id.module(db)?
If not - can you please doc what is each of the .0?



_Code quote:_
```XML
.0.0
```
___
*[`crates/starknet/src/contract.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbAec51MWUqBZplHyI:-NJbAec51MWUqBZplHyJ:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/contract.rs#L17)):*
> ```XML
> /// Represents a declaration of a contract.
> pub struct ContractDeclaration {
>     /// The id of the inline module that defines the contract
> ```





_Suggestion:_
```XML
/// The id of the inline module that defines the contract.
```
___
*[`crates/starknet/src/contract.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbAy7A5wTQm6YW1K2z:-NJbAy7B5WlJDcRjq4ZF:b-jwjg5z) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/contract.rs#L40)):*
> ```XML
> /// Finds the inline modules annotated as contracts in the given create_ids and
> /// returns the corresponding ContractDeclarations.
> pub fn find_contracts(db: &dyn SemanticGroup, create_ids: &[CrateId]) -> Vec<ContractDeclaration> {
> ```

Also in the comment



_Suggestion:_
```XML
crate_ids
```
___
*[`crates/starknet/src/contract.rs` line 52 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbN6S0D2mPTOB9sOMt:-NJbN6S0D2mPTOB9sOMu:b-pznl48) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/contract.rs#L52)):*
> ```XML
>                 if let ModuleId::Submodule(submodule_id) = module_id {
>                     if let Ok(attrs) = db.module_attributes(module_id) {
>                         if let [attr] = attrs.as_slice() {
> ```

This assumes there is only one attribute. Is this intentional?



_Code quote:_
```XML
if let [attr] = attrs.as_slice() {
```
___
*[`crates/starknet/src/contract.rs` line 65 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbNGHU8QWTzhQC3NcY:-NJbNGHU8QWTzhQC3NcZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/contract.rs#L65)):*
> ```XML
> }
> 
> /// Returns the list of external function for a given contract.
> ```





_Suggestion:_
```XML
urns the list of external functions for a given contract
```
___
*[`crates/starknet/src/contract.rs` line 71 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbOYwy-9-uFy0zkYCn:-NJbOYwy-9-uFy0zkYCo:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/contract.rs#L71)):*
> ```XML
> ) -> anyhow::Result<Vec<FreeFunctionId>> {
>     // The wrappers are currently in the parent module.
>     let module_id = contract.submodule_id.module(db.upcast());
> ```





_Suggestion:_
```XML
parent_module_id
```
___
*[`crates/starknet/src/contract.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbP20wEE1B-VR1DYqW:-NJbP20wEE1B-VR1DYqX:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/contract.rs#L84)):*
> ```XML
>             .to_option()
>             .with_context(|| "Failed to get module items.")?),
>         _ => anyhow::bail!("Failed to get the entry points module."),
> ```





_Suggestion:_
```XML
        Some(submodule) => Ok(db
            .module_free_functions(submodule)
            .to_option()
            .with_context(|| "Failed to get module items.")?),
        _ => anyhow::bail!("Failed to get the entry points module."),
```
___
*[`crates/starknet/src/contract_test.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbQkpI7jBjShxu_ACn:-NJbQkpI7jBjShxu_ACo:bxn1vro) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/contract_test.rs#L36)):*
> ```XML
>     assert_eq!(
>         format!(
>             "{:?}",
> ```

why do you compare the string and not the set of names?
If we change the order which we don't guarantee, it would fail this way. I think it is also more robust and readable to compare sets.



_Code quote:_
```XML
 "{:?}"
```
___
*[`crates/starknet/src/contract_test.rs` line 38 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbQQvDAUccS7rT1 [...]

2022-12-19 06:53 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1359)* status: all files reviewed, 20 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/defs/src/db.rs` line 137 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJb34Le3nnO3JUqvbyV:-NJd8SBpAwms89LiKmBs:b-fs1ef0) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/defs/src/db.rs#L137)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

the code line below doesn't reflect that. You use the parent's file anyway.
</blockquote></details>

Right :(, great catch!


<!-- Sent from Reviewable.io -->

2022-12-19 07:52 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1359)* status: 6 of 19 files reviewed, 12 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/defs/src/db.rs` line 237 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJb5Ch97HrZPUSHQI2u:-NJdIHMl6sSwc9vX9TJB:bul4st7) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/defs/src/db.rs#L237)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I don't understand this logic. Previously it made sense as you looked for this module among the submodules of the parent. Now you look for this module among the submodule of this module.
</blockquote></details>

submodule_id.module(db) is the parent module...



_Code quote:_
```XML
submodule_id.module(db)
```
___
*[`crates/defs/src/db.rs` line 241 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJb6-CV1HrlXjYqPLot:-NJdIUsq570P5tD-NSXk:b1qo73x) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/defs/src/db.rs#L241)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

not sure if directly related to this PR, but do we verify that we don't define 2 modules with the same files in different location?
Here there is no defence against this. If there are 2 "mod bla;" in 2 different files, module_data for both would work and return the same data.
</blockquote></details>

We don't verify that.
___
*[`crates/defs/src/db.rs` line 267 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJb73bL2jkM2PIzxH1M:-NJdMbDJ7BGlsKThLveB:borl9f1) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/defs/src/db.rs#L267)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

is this still relevant?
</blockquote></details>

I don't know, removed it just in case.
___
*[`crates/starknet/src/contract.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbAec51MWUqBZplHyI:-NJdJYb9AhNxrmt4Ih6L:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/contract.rs#L17)):*
> ```XML
> /// Represents a declaration of a contract.
> pub struct ContractDeclaration {
>     /// The id of the inline module that defines the contract
> ```

done.
___
*[`crates/starknet/src/contract.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbAy7A5wTQm6YW1K2z:-NJdJdyY7GWyKf7QvxUz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/contract.rs#L40)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Also in the comment
</blockquote></details>

Done.
___
*[`crates/starknet/src/contract.rs` line 52 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbN6S0D2mPTOB9sOMt:-NJdGJ7E8j3PDtDbcPUM:b2nign6) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/contract.rs#L52)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This assumes there is only one attribute. Is this intentional?
</blockquote></details>

yes



_Code quote (from crates/semantic/src/resolve_path.rs):_
```XML
  self.db.lookup_intern_submodule(submodule_id)
```
___
*[`crates/starknet/src/contract.rs` line 65 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbNGHU8QWTzhQC3NcY:-NJdJiD5CJUIkgXgP7kh:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/contract.rs#L65)):*
> ```XML
> }
> 
> /// Returns the list of external function for a given contract.
> ```

done



_Code quote:_
```XML
t of external function for a given contra
```
___
*[`crates/starknet/src/contract.rs` line 71 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbOYwy-9-uFy0zkYCn:-NJdJmaV9Pp8heH87r5H:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/contract.rs#L71)):*
> ```XML
> ) -> anyhow::Result<Vec<FreeFunctionId>> {
>     // The wrappers are currently in the parent module.
>     let module_id = contract.submodule_id.module(db.upcast());
> ```

Done.
___
*[`crates/starknet/src/contract.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbP20wEE1B-VR1DYqW:-NJdKM3Q0coSlorEZpJh:b7khsnr) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/contract.rs#L84)):*
> ```XML
>             .to_option()
>             .with_context(|| "Failed to get module items.")?),
>         _ => anyhow::bail!("Failed to get the entry points module."),
> ```

it gives:
^^^^^^^^^^^^^ expected struct `SubmoduleId`, found enum `ModuleItemId`

The type of submodules is not know in your code.
___
*[`crates/starknet/src/contract_test.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbQkpI7jBjShxu_ACn:-NJdL4AsEkfxF8tq8U4w:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/contract_test.rs#L36)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why do you compare the string and not the set of names?
If we change the order which we don't guarantee, it would fail this way. I think it is also more robust and readable to compare sets.
</blockquote></details>

done.
___
*[`crates/starknet/src/contract_test.rs` line 38 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbQQvDAUccS7rT1h6Z:-NJdKxxg0TiQJm8kIS8D:bsag5gz) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/contract_test.rs#L38)):*
> ```XML
>             "{:?}",
>             get_external_functions(db, &contracts[0])
>                 .unwrap()
> ```

We use unwrap in lots of tests, and I don't have something more indicative then get_external_functions failed.



_Code quote:_
```XML
get_external_functions
```
___
*[`crates/starknet/src/contract_test.rs` line 41 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbQa3t8y9fcyo21_YC:-NJdKwhD0DKT3zXjbWQo:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/contract_test.rs#L41)):*
> ```XML
>                 .into_iter()
>                 .map(|func_id| func_id.name(db))
>                 .collect::<Vec<_>>()
> ```

done.
___
*[`crates/starknet/src/plugin.rs` line 56 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbRak770BvyVZkCqx6:-NJdLOrPAv8UfqpaH-Ef:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/plugin.rs#L56)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

You can put the to_string here to avoid doing it twice (once here below and once (hidden, I think) in generate_entry_point_wrapper). Pass &str as argument to generate_entry_point_wrapper.
</blockquote></details>

Done.
___
*[`crates/starknet/src/plugin.rs` line 128 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbS6F1B9qHtzSnneRY:-NJdLRm43sor1fgAPxt4:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/plugin.rs#L128)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

typo
</blockquote></details>

done.
___
*[`crates/starknet/src/plugin.rs` line 187 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbRzpo2zcrF3iv8My_:-NJdLa9x2CiDKxQRAm_p:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/plugin.rs#L187)):*
> ```XML
> 
>     let function_name = [...]

2022-12-19 08:12 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1359)* status: 6 of 19 files reviewed, 9 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/defs/src/db.rs` line 137 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJb34Le3nnO3JUqvbyV:-NJdRCUVB7hgEYHP251u:b-sqbm1) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/defs/src/db.rs#L137)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Right :(, great catch!
</blockquote></details>

Fixed here:
https://reviewable.io/reviews/starkware-libs/cairo/1387

Not sure why those PRs got mixed up :(


<!-- Sent from Reviewable.io -->

2022-12-19 08:16 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1359)* status: 6 of 19 files reviewed, 8 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/starknet/src/contract.rs` line 52 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbN6S0D2mPTOB9sOMt:-NJdRf3n4OUvI73gbYq2:b-cmonm5) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/contract.rs#L52)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

yes
</blockquote></details>

I changed it to "any" to be consistent with other places in the code.

But I personally feel that this is worse :(.


<!-- Sent from Reviewable.io -->

2022-12-19 08:17 UTC, orizi approved these changes
> Reviewed 11 of 13 files at r5, 2 of 2 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1359)* status: all files reviewed, 8 unresolved discussions (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2022-12-19 08:59 UTC, yuvalsw approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 13 files at r5, 2 of 2 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1359#-:-NJdawuK8Gi0tPGlqmSv:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/defs/src/db.rs` line 137 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJb34Le3nnO3JUqvbyV:-NJdXhPM1grGwCmDvfpO:b-1sm9od) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/defs/src/db.rs#L137)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Fixed here:
https://reviewable.io/reviews/starkware-libs/cairo/1387

Not sure why those PRs got mixed up :(

</blockquote></details>

OK, dismiss this once the other PR is merged.
___
*[`crates/defs/src/db.rs` line 241 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJb6-CV1HrlXjYqPLot:-NJdZCkK4vbXi8EEdKfg:bei0bv8) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/defs/src/db.rs#L241)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

We don't verify that.
</blockquote></details>

Can you please add to Monday or a TODO somewhere?
___
*[`crates/starknet/src/contract.rs` line 52 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbN6S0D2mPTOB9sOMt:-NJdZabD0sRuGLETyVPu:bjhsn6q) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/contract.rs#L52)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I changed it to "any" to be consistent with other places in the code.

But I personally feel that this is worse :(.
</blockquote></details>

I think it should be OK to have multiple attributes of multiple plugins that can act one after the other.
But let's discuss separately...
___
*[`crates/starknet/src/contract.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbP20wEE1B-VR1DYqW:-NJd_6GI4lbbabyJRzPH:bng9047) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/contract.rs#L84)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it gives:
^^^^^^^^^^^^^ expected struct `SubmoduleId`, found enum `ModuleItemId`

The type of submodules is not know in your code.
</blockquote></details>

Oh, I missed that these are different enums. 
___
*[`crates/starknet/src/contract.rs` line 38 at r7](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJdZTryCcT3gLRm-Hrt:-NJdZTryCcT3gLRm-Hru:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f5e874ed4f468964bbf4b925c11478ed92378581/crates/starknet/src/contract.rs#L38)):*
> ```XML
> }
> 
> /// Finds the inline modules annotated as contracts in the given create_ids and
> ```





_Suggestion:_
```XML
crate_ids
```
___
*[`crates/starknet/src/contract_test.rs` line 41 at r7](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJd_Xml7qihq8JWU3jC:-NJd_Xml7qihq8JWU3jD:bshlsas) ([raw file](https://github.com/starkware-libs/cairo/blob/f5e874ed4f468964bbf4b925c11478ed92378581/crates/starknet/src/contract_test.rs#L41)):*
> ```XML
>             .map(|func_id| func_id.name(db))
>             .collect_vec(),
>         vec!["ep1", "ep2"]
> ```

Can you make it a set so that order doesn't affect it?


<!-- Sent from Reviewable.io -->

2022-12-19 09:00 UTC, ilyalesokhin-starkware commented
*[`crates/defs/src/db.rs` line 241 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJb6-CV1HrlXjYqPLot:-NJdbICE9BLkMONUSe56:b-sol1rl) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/defs/src/db.rs#L241)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can you please add to Monday or a TODO somewhere?
</blockquote></details>

I think we have the same behavior as rust.


<!-- Sent from Reviewable.io -->

2022-12-19 09:04 UTC, yuvalsw approved these changes
This is a big PR with many changes. Please elaborate more in the description

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1359#-:-NJdc2OL6P02okCU21vz:b-9ghdey)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2022-12-19 09:34 UTC, orizi approved these changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1359)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)



<!-- Sent from Reviewable.io -->

2022-12-19 09:34 UTC, yuvalsw approved these changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1359)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2022-12-19 09:37 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1359)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/defs/src/db.rs` line 137 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJb34Le3nnO3JUqvbyV:-NJdirzKCWz6ZstMuLPU:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/defs/src/db.rs#L137)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

OK, dismiss this once the other PR is merged.
</blockquote></details>

done.
___
*[`crates/starknet/src/contract.rs` line 52 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJbN6S0D2mPTOB9sOMt:-NJdixcf2AHiGa5L_ogW:b-w03gvq) ([raw file](https://github.com/starkware-libs/cairo/blob/6c1d2c2170c51de30c221a101cedbe4cf58e1cf8/crates/starknet/src/contract.rs#L52)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think it should be OK to have multiple attributes of multiple plugins that can act one after the other.
But let's discuss separately...
</blockquote></details>

I think that compilation should fail if there is an unexpected attribute. But Shahar agrees with you.
___
*[`crates/starknet/src/contract_test.rs` line 41 at r7](https://reviewable.io/reviews/starkware-libs/cairo/1359#-NJd_Xml7qihq8JWU3jC:-NJdjChc6Raeu7F1ZMXC:bwtcw7c) ([raw file](https://github.com/starkware-libs/cairo/blob/f5e874ed4f468964bbf4b925c11478ed92378581/crates/starknet/src/contract_test.rs#L41)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can you make it a set so that order doesn't affect it?
</blockquote></details>

We have many places where we return vectors.

also
ModuleData.free_functions is a OrderedHashMap.


<!-- Sent from Reviewable.io -->

2022-12-19 11:37 UTC, yuvalsw approved these changes
> Reviewed 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1359)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2022-12-19 11:47 UTC, orizi approved these changes
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1359)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2022-12-19 11:49 UTC, merged