add WideMul
starkware-libs/cairo pull request #1447
Opened 2022-12-22 14:51 UTC by zuphitf

2022-12-22 15:57 UTC, orizi requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: all files reviewed, 9 unresolved discussions (waiting on @dorimedini-starkware and @zuphitf)

___
*[`corelib/test.cairo` line 85 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuSEr0-E6Ch4xbQS5V:-NJuSEr0-E6Ch4xbQS5W:bkmsk1s) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/corelib/test.cairo#L85)):*
> ```Cairo
> func max_u128() -> u128 {
>     0xffffffffffffffffffffffffffffffff_u128
> }
> ```

delete and add as a const in function - unless you plan to add this in other tests.



_Code quote:_
```Cairo
func max_u128() -> u128 {
    0xffffffffffffffffffffffffffffffff_u128
}
```
___
*[`corelib/test.cairo` line 205 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuSWno5QIg7E1bCFIK:-NJuSWno5QIg7E1bCFIL:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/corelib/test.cairo#L205)):*
> ```Cairo
>         'max_u128 * max_u128'
>     );
>     assert(
> ```





_Suggestion:_
```Cairo
// TODO(orizi): Use u256 literals when supported.
#[test]
func test_u256_operators() {
    let max_u128 = 0xffffffffffffffffffffffffffffffff_u128;
    assert(as_u256(1_u128, 1_u128) + as_u256(3_u128, 2_u128) == as_u256(4_u128, 3_u128), 'no OF');
    assert(
        as_u256(1_u128, pow_2_127()) + as_u256(3_u128, pow_2_127()) == as_u256(5_u128, 0_u128),
        'basic OF'
    );
    assert(as_u256(4_u128, 3_u128) - as_u256(1_u128, 1_u128) == as_u256(3_u128, 2_u128), 'no UF');
    assert(
        as_u256(5_u128, 0_u128) - as_u256(1_u128, pow_2_127()) == as_u256(3_u128, pow_2_127()),
        'basic UF'
    );
    assert(
        as_u256(4_u128, 3_u128) * as_u256(0_u128, 1_u128) == as_u256(4_u128, 3_u128), 'mul by 1'
    );
    assert(
        as_u256(4_u128, 3_u128) * as_u256(0_u128, 2_u128) == as_u256(8_u128, 6_u128), 'mul by 2'
    );
    assert(
        as_u256(0_u128, pow_2_127()) * as_u256(0_u128, 2_u128) == as_u256(1_u128, 0_u128),
        'basic mul OF'
    );
    assert(
        as_u256(0_u128, max_u128)
            * as_u256(
                0_u128, max_u128
            ) == as_u256(0xfffffffffffffffffffffffffffffffe_u128, 1_u128),
        'max_u128 * max_u128'
    );
    assert(
        as_u256(0_u128, max_u128) * as_u256(0_u128, 1_u128) == as_u256(0_u128, max_u128),
        'max_u128 * 1'
    );
    assert(
        as_u256(0_u128, 1_u128) * as_u256(0_u128, max_u128) == as_u256(0_u128, max_u128),
        '1 * max_u128'
    );
    assert(
```
___
*[`crates/sierra/src/simulation/core.rs` line 351 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuSo8o-yNtoI39VzAw:-NJuSo8o-yNtoI39VzAx:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/crates/sierra/src/simulation/core.rs#L351)):*
> ```XML
>                             CoreValue::Uint128(
>                                 (result.clone() / u128_limit.clone()).try_into().unwrap(),
>                             ),
> ```





_Suggestion:_
```XML
                ) => {
                    let result = BigInt::from(lhs) * BigInt::from(rhs);
                    let u128_limit = BigInt::from(u128::MAX) + BigInt::from(1);
                    Ok((
                        vec![
                            CoreValue::RangeCheck,
                            CoreValue::Uint128(
                                (result.clone() / u128_limit.clone()).to_u128().unwrap(),
                            ),
                            CoreValue::Uint128((result % u128_limit).to_u128().unwrap()),
                        ],
                        0,
                    ))
```
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuTx1tBgakLCLPUQuW:-NJuTx1tBgakLCLPUQuX:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/crates/sierra_to_casm/src/invocations/uint128.rs#L249)):*
> ```XML
>             let u64_limit = casm_builder.add_var(ResOperand::Immediate(BigInt::from(u64::MAX) + 1));
>             let u128_limit =
>                 casm_builder.add_var(ResOperand::Immediate(BigInt::from(u128::MAX) + 1));
> ```





_Suggestion:_
```XML
                casm_builder.add_var(ResOperand::Immediate(BigInt::from(u64::MAX)));
            let u64_limit = casm_builder.add_var(ResOperand::Immediate(BigInt::from(u64::MAX) + 1));
            let u128_limit =
                casm_builder.add_var(ResOperand::Immediate(BigInt::from(u128::MAX) + 1));
            let u64_upper_limit_fix = casm_builder.add_var(ResOperand::Immediate(BigInt::from(u128::MAX) - BigInt::from(u64::MAX)));
            let range_check = casm_builder.add_var(range_check);
```
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 258 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuULhnCCzSa-YRW37G:-NJuULhnCCzSa-YRW37H:bgxinsl) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/crates/sierra_to_casm/src/invocations/uint128.rs#L258)):*
> ```XML
>                 tempvar a1;
>                 tempvar b0;
>                 tempvar b1;
> ```

unless you optimize locations - tempvar just before usage.



_Code quote:_
```XML
                tempvar a0;
                tempvar a1;
                tempvar b0;
                tempvar b1;
                tempvar a0_b0;
                tempvar a0_b1;
                tempvar a1_b0;
                tempvar a1_b1;
```
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 277 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuUUfZE2oa7k39PQ56:-NJuUUfZE2oa7k39PQ57:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/crates/sierra_to_casm/src/invocations/uint128.rs#L277)):*
> ```XML
>                 tempvar max_u64;
>                 tempvar max_u64_minus_a0;
>                 tempvar max_u64_minus_a1;
> ```





_Suggestion:_
```XML
                // Verify that a0, b0, b0, b1 < 2**64 by constraining {var} + 2**128 - 2**64 < 2**128.
                tempvar fixed_a0;
                assert fixed_a0 = a0 + u64_upper_limit_fix;
                assert *(range_check++) = fixed_a0;
                tempvar fixed_a1;
                assert fixed_a1 = a1 + u64_upper_limit_fix;
                assert *(range_check++) = fixed_a1;
                tempvar fixed_b0;
                assert fixed_b0 = b0 + u64_upper_limit_fix;
                assert *(range_check++) = fixed_b0;
                tempvar fixed_b1;
                assert fixed_b1 = b1 + u64_upper_limit_fix;
                assert *(range_check++) = fixed_b1;
                // We now have: 0 <= a0, a1, b0, b1 < 2**64.
```
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 327 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuWLqO7o1AKmGX57sG:-NJuWLqO7o1AKmGX57sH:bss74mx) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/crates/sierra_to_casm/src/invocations/uint128.rs#L327)):*
> ```XML
>                 assert a1_b0 = shifted_a1_b0_top + a1_b0_bottom;
>                 // Note that a0_b1_top, a1_b0_bottom are range checked for 128 bits and then shifted
>                 // 64 bits, so those are within 192 bits range. Adding the 128 bits range-checked
> ```

note this does also mean that you cannot rely on these numbers to actually be 64 bit numbers.
(as there are numbers smaller than 2**128 such that x1*2**64 + y1 = x2*2**64 + y2:
x1=1, y1=1 vs x2=0, y2=2**64+1

you CAN assume the top words are smaller than 2**64 (since the original is 2**128 sized)



_Code quote:_
```XML
                // Note that a0_b1_top, a1_b0_bottom are range checked for 128 bits and then shifted
                // 64 bits, so those a [...]

2022-12-25 10:30 UTC, dorimedini-starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: all files reviewed, 10 unresolved discussions (waiting on @zuphitf)

___
*[`corelib/test.cairo` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NK7lTAWC7a84I0VtfiB:-NK7lTAWC7a84I0VtfiC:b-xxwxze) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/corelib/test.cairo#L80)):*
> ```Cairo
>     assert((2_u128 & 2_u128) == 2_u128, '2 & 2 == 2');
>     assert((2_u128 & 3_u128) == 2_u128, '2 & 3 == 2');
>     assert((3_u128 ^ 6_u128) == 5_u128, '3 ^ 6 == 5');
> ```

consider also adding panic test cases (overflow cases)


<!-- Sent from Reviewable.io -->

2022-12-25 10:32 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: all files reviewed, 11 unresolved discussions (waiting on @zuphitf)

___
*[`corelib/test.cairo` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NK7piEu3oHMOQdt0t_S:-NK7piEu3oHMOQdt0t_T:b-bifv46) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/corelib/test.cairo#L83)):*
> ```Cairo
> }
> 
> func max_u128() -> u128 {
> ```

these tests look like u256_mul tests; where do you test the result of a "wide mul" between two u128s?


<!-- Sent from Reviewable.io -->

2022-12-25 12:46 UTC, zuphitf reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: 4 of 8 files reviewed, 11 unresolved discussions (waiting on @dorimedini-starkware and @orizi)

___
*[`corelib/test.cairo` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NK7lTAWC7a84I0VtfiB:-NK8I7js3brnFl8kyANY:bne5w8r) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/corelib/test.cairo#L80)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

consider also adding panic test cases (overflow cases)
</blockquote></details>

WideMul for 128 bit integers should never fail
___
*[`corelib/test.cairo` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NK7piEu3oHMOQdt0t_S:-NK8IG3wED1AE3Ktf3Km:bpcdgkn) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/corelib/test.cairo#L83)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

these tests look like u256_mul tests; where do you test the result of a "wide mul" between two u128s?
</blockquote></details>

It's wired to `u128_wide_mul` behind the scenes. Additional details are best from @orizi 
___
*[`corelib/test.cairo` line 85 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuSEr0-E6Ch4xbQS5V:-NJudZxO-BnuJE-BoEnd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/corelib/test.cairo#L85)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

delete and add as a const in function - unless you plan to add this in other tests.
</blockquote></details>

Done.
___
*[`corelib/test.cairo` line 205 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuSWno5QIg7E1bCFIK:-NJudf2w4pBswTuh7ikm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/corelib/test.cairo#L205)):*
> ```Cairo
>         'max_u128 * max_u128'
>     );
>     assert(
> ```

Done.
___
*[`crates/sierra/src/simulation/core.rs` line 351 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuSo8o-yNtoI39VzAw:-NK8BX4l9QUwNy4XEH5n:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/crates/sierra/src/simulation/core.rs#L351)):*
> ```XML
>                             CoreValue::Uint128(
>                                 (result.clone() / u128_limit.clone()).try_into().unwrap(),
>                             ),
> ```

Done.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuTx1tBgakLCLPUQuW:-NK7hR7D1Yp-VaqPN2tO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/crates/sierra_to_casm/src/invocations/uint128.rs#L249)):*
> ```XML
>             let u64_limit = casm_builder.add_var(ResOperand::Immediate(BigInt::from(u64::MAX) + 1));
>             let u128_limit =
>                 casm_builder.add_var(ResOperand::Immediate(BigInt::from(u128::MAX) + 1));
> ```

Done.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 258 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuULhnCCzSa-YRW37G:-NK7blse4GXWuOjlwU-S:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/crates/sierra_to_casm/src/invocations/uint128.rs#L258)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

unless you optimize locations - tempvar just before usage.
</blockquote></details>

Done.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 277 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuUUfZE2oa7k39PQ56:-NK7j_Br30vt8UDoAcTK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/crates/sierra_to_casm/src/invocations/uint128.rs#L277)):*
> ```XML
>                 tempvar max_u64;
>                 tempvar max_u64_minus_a0;
>                 tempvar max_u64_minus_a1;
> ```

Done.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 327 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuWLqO7o1AKmGX57sG:-NK7nmVx381E1NITuglM:b-chvnqj) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/crates/sierra_to_casm/src/invocations/uint128.rs#L327)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

note this does also mean that you cannot rely on these numbers to actually be 64 bit numbers.
(as there are numbers smaller than 2**128 such that x1*2**64 + y1 = x2*2**64 + y2:
x1=1, y1=1 vs x2=0, y2=2**64+1

you CAN assume the top words are smaller than 2**64 (since the original is 2**128 sized)
</blockquote></details>

Right, fixing this. Also removing the 64-bit range checks for a1, b1 for the exact same arguments.

(should we now range-check a, b at some point or is it guaranteed they're legal 128 bit uints?)
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 352 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuY-bSCzi7Hz0pOpKC:-NK83qtJEDiJvigD1CYt:b-5i8xnw) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/crates/sierra_to_casm/src/invocations/uint128.rs#L352)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you don't know there's no overflow when recalculating `lower_uint128_with_overflow`
</blockquote></details>

What do you mean? add another range check for the `overflow` var?
(technically I think 2 bits are enough here, but we already have the 64bit fixer and this should do the job)
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 361 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuYEn_D6ubeF3T360J:-NK8BGDu8tqAmc5QjQYO:b-vb2r4) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/crates/sierra_to_casm/src/invocations/uint128.rs#L361)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is this required?
</blockquote></details>

Seemed like a good sanity check. I can remove it if you have strong feelings about its existence.


<!-- Sent from Reviewable.io -->

2022-12-25 13:03 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: 1 of 8 files reviewed, 10 unresolved discussions (waiting on @orizi and @zuphitf)

___
*[`corelib/test.cairo` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NK7lTAWC7a84I0VtfiB:-NK8KN7o0AwLGp40EuTX:batn5fo) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/corelib/test.cairo#L80)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

WideMul for 128 bit integers should never fail
</blockquote></details>

I meant multiplying two u256s may fail
but now that I TAL, why are these extra u256-multiplication tests needed?
And how did the existing tests work?
I think you aren't testing your code, you're testing the `func u128_wide_mul` function defined [here](https://github.com/starkware-libs/cairo2/blob/main/corelib/integer.cairo#L42). Do Ori's TODO there (delete the Cairo1 implementation and mark it `extern`) to use yours


<!-- Sent from Reviewable.io -->

2022-12-25 13:07 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 4 files at r2, 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: 7 of 8 files reviewed, 10 unresolved discussions (waiting on @orizi and @zuphitf)



<!-- Sent from Reviewable.io -->

2022-12-25 13:08 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: 7 of 8 files reviewed, 11 unresolved discussions (waiting on @orizi and @zuphitf)

___
*[`crates/sierra/src/extensions/modules/uint128.rs` line 148 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NK8OMCR5O2tbhpnUmVy:-NK8OMCR5O2tbhpnUmVz:bvnnq67) ([raw file](https://github.com/starkware-libs/cairo/blob/a5417f0325fb694bd0f18b01ac37f91f605e082c/crates/sierra/src/extensions/modules/uint128.rs#L148)):*
> ```XML
>                     },
>                     OutputVarInfo {
>                         ty: ty.clone(),
> ```

shouldn't you be returning `(upper, lower)`? This looks like `(lower, upper)`



_Suggestion:_
```XML
                    OutputVarInfo {
                        ty: ty.clone(),
                        ref_info: OutputVarReferenceInfo::NewTempVar { idx: Some(0) },
                    },
                    OutputVarInfo {
                        ty,
                        ref_info: OutputVarReferenceInfo::NewTempVar { idx: Some(1) },
                    },
```


<!-- Sent from Reviewable.io -->

2022-12-25 13:08 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: all files reviewed, 11 unresolved discussions (waiting on @orizi and @zuphitf)



<!-- Sent from Reviewable.io -->

2022-12-25 13:28 UTC, orizi requested changes
> Reviewed 1 of 4 files at r2, 4 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @zuphitf)

___
*[`corelib/test.cairo` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NK7piEu3oHMOQdt0t_S:-NK8NUTe2omK2YtPN0tC:b-pb9bue) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/corelib/test.cairo#L83)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

It's wired to `u128_wide_mul` behind the scenes. Additional details are best from @orizi 
</blockquote></details>

indeed
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 327 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuWLqO7o1AKmGX57sG:-NK8SwnS8B0eOIkR-OPD:b-wflq1c) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/crates/sierra_to_casm/src/invocations/uint128.rs#L327)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

Right, fixing this. Also removing the 64-bit range checks for a1, b1 for the exact same arguments.

(should we now range-check a, b at some point or is it guaranteed they're legal 128 bit uints?)
</blockquote></details>

the existence of the comment it self was good - just be more exact.
we are promised by sierra construction that a and b are legal u128s.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 352 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuY-bSCzi7Hz0pOpKC:-NK8PCEG01iomFC1zQhg:bvlej05) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/crates/sierra_to_casm/src/invocations/uint128.rs#L352)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

What do you mean? add another range check for the `overflow` var?
(technically I think 2 bits are enough here, but we already have the 64bit fixer and this should do the job)
</blockquote></details>

i mean - somehow prove you do not overflow.

if this fixes it - add comment explaining it.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 361 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuYEn_D6ubeF3T360J:-NK8OcQ7-O_11nFKkPyY:b2it1vz) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/crates/sierra_to_casm/src/invocations/uint128.rs#L361)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

Seemed like a good sanity check. I can remove it if you have strong feelings about its existence.
</blockquote></details>

we don't do any extra commands - sanity checks should be at the rust level - not the cairo level.


<!-- Sent from Reviewable.io -->

2022-12-25 13:30 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: all files reviewed, 5 unresolved discussions (waiting on @zuphitf)



<!-- Sent from Reviewable.io -->

2022-12-25 13:42 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: all files reviewed, 8 unresolved discussions (waiting on @zuphitf)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 169 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NK8VU4N-5csNr1aiRBM:-NK8VU4N-5csNr1aiRBN:bl7x465) ([raw file](https://github.com/starkware-libs/cairo/blob/a5417f0325fb694bd0f18b01ac37f91f605e082c/crates/sierra_to_casm/src/invocations/uint128.rs#L169)):*
> ```XML
>             let mut casm_builder = CasmBuilder::default();
>             let u64_upper_fixer = casm_builder
>                 .add_var(ResOperand::Immediate(BigInt::from(u128::MAX) - BigInt::from(u64::MAX)));
> ```

after rebase:
(the consts - add just before usage)



_Suggestion:_
```XML
            let mut casm_builder = CasmBuilder::default();
            let range_check = casm_builder.add_var(range_check);
            let a = casm_builder.add_var(ResOperand::Deref(a));
            let b = casm_builder.add_var(ResOperand::Deref(b));

            casm_build_extend! {casm_builder,
                tempvar a0;
                tempvar a1;
                tempvar b0;
                tempvar b1;
                const u64_limit = u64::MAX as u128 + 1;
                const u128_limit = BigInt::from(u128::MAX) + 1;
                const u64_upper_fixer = u128::MAX - u64::MAX as u128;

                // Breaks a and b to 64bit halves:
                hint DivMod { lhs: a, rhs: u64_limit } into { quotient: a1, remainder: a0 }; // a = a1 * 2**64 + a0.
                hint DivMod { lhs: b, rhs: u64_limit } into { quotient: b1, remainder: b0 }; // b = b1 * 2**64 + b0.
```
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 188 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NK8VIHf86FCOyI9rHoH:-NK8VIHf86FCOyI9rHoI:bat9vrh) ([raw file](https://github.com/starkware-libs/cairo/blob/a5417f0325fb694bd0f18b01ac37f91f605e082c/crates/sierra_to_casm/src/invocations/uint128.rs#L188)):*
> ```XML
> 
>                 // Verify that a0, a1, b0, b1 in [0, 2**128).
>                 assert *(range_check++) = a0;
> ```

after rebase:



_Suggestion:_
```XML
                // Verify that a0, a1, b0, b1 in [0, 2**128).
                assert a0 = *(range_check++);
                assert a1 = *(range_check++);
                assert b0 = *(range_check++);
                assert b1 = *(range_check++);
```
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 196 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NK8W6o38I-NT0WQu-WY:-NK8W6o38I-NT0WQu-WZ:bypvb9p) ([raw file](https://github.com/starkware-libs/cairo/blob/a5417f0325fb694bd0f18b01ac37f91f605e082c/crates/sierra_to_casm/src/invocations/uint128.rs#L196)):*
> ```XML
>                 tempvar fixed_a0;
>                 tempvar fixed_b0;
>                 assert fixed_a0 = a0 + u64_upper_fixer;
> ```

after rebase



_Suggestion:_
```XML
                tempvar fixed_a0 = a0 + u64_upper_fixer;
                assert *(range_check++) = fixed_a0;
                tempvar fixed_b0 = b0 + u64_upper_fixer;
                assert *(range_check++) = fixed_b0;
```


<!-- Sent from Reviewable.io -->

2022-12-25 16:21 UTC, zuphitf reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: 2 of 8 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @orizi)

___
*[`corelib/test.cairo` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NK7lTAWC7a84I0VtfiB:-NK8kijN6U4TIzC1K-OS:b2qzn5n) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/corelib/test.cairo#L80)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I meant multiplying two u256s may fail
but now that I TAL, why are these extra u256-multiplication tests needed?
And how did the existing tests work?
I think you aren't testing your code, you're testing the `func u128_wide_mul` function defined [here](https://github.com/starkware-libs/cairo2/blob/main/corelib/integer.cairo#L42). Do Ori's TODO there (delete the Cairo1 implementation and mark it `extern`) to use yours
</blockquote></details>

We're good. Upper words are always 0 in those tests and it's already extern.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 327 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuWLqO7o1AKmGX57sG:-NK8tSZJ0BOLSX62rRi7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/crates/sierra_to_casm/src/invocations/uint128.rs#L327)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the existence of the comment it self was good - just be more exact.
we are promised by sierra construction that a and b are legal u128s.
</blockquote></details>

Done.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 352 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuY-bSCzi7Hz0pOpKC:-NK8tXiH5qa7ESf2Q98A:b1i8ime) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/crates/sierra_to_casm/src/invocations/uint128.rs#L352)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i mean - somehow prove you do not overflow.

if this fixes it - add comment explaining it.
</blockquote></details>

I'm assuming that by "overflow" you mean that `overflow * u128_limit` wraps around (otherwise not sure what we're discussing here).
Fixed + documenting according to this.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 361 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuYEn_D6ubeF3T360J:-NK8rLCj4gSSVNhHl8kp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/crates/sierra_to_casm/src/invocations/uint128.rs#L361)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we don't do any extra commands - sanity checks should be at the rust level - not the cairo level.
</blockquote></details>

Done.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 169 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NK8VU4N-5csNr1aiRBM:-NK92cA36lLSEoIPGe6Y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a5417f0325fb694bd0f18b01ac37f91f605e082c/crates/sierra_to_casm/src/invocations/uint128.rs#L169)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

after rebase:
(the consts - add just before usage)
</blockquote></details>

Done.
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 188 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NK8VIHf86FCOyI9rHoH:-NK90K7b9ybD3wIOGWXT:b5thhxi) ([raw file](https://github.com/starkware-libs/cairo/blob/a5417f0325fb694bd0f18b01ac37f91f605e082c/crates/sierra_to_casm/src/invocations/uint128.rs#L188)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

after rebase:
</blockquote></details>

you sure? I just switched it to be like that, being same as everywhere else now (+ errors if I try to change back the order)
___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 196 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NK8W6o38I-NT0WQu-WY:-NK8o9SF0kiu1sjBS5v-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a5417f0325fb694bd0f18b01ac37f91f605e082c/crates/sierra_to_casm/src/invocations/uint128.rs#L196)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

after rebase
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-25 16:47 UTC, orizi requested changes
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: all files reviewed, 2 unresolved discussions (waiting on @zuphitf)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 352 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuY-bSCzi7Hz0pOpKC:-NK99iNIETfKXg2OM-zg:bt3mp8u) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/crates/sierra_to_casm/src/invocations/uint128.rs#L352)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

I'm assuming that by "overflow" you mean that `overflow * u128_limit` wraps around (otherwise not sure what we're discussing here).
Fixed + documenting according to this.
</blockquote></details>

i mean the calculation checking that the divmod hint is not lying to you does not overflow over felt.


<!-- Sent from Reviewable.io -->

2022-12-25 16:47 UTC, orizi reviewed
Generally looks good now - but i need more people to go over this.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447#-:-NK9Abu44uxsATzQYErX:bt91u99)* status: all files reviewed, 2 unresolved discussions (waiting on @zuphitf)



<!-- Sent from Reviewable.io -->

2022-12-25 22:16 UTC, dorimedini-starkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: all files reviewed, 2 unresolved discussions (waiting on @zuphitf)



<!-- Sent from Reviewable.io -->

2022-12-26 08:56 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447#-:-NKCdNbV0tUDX4DWuAEc:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @zuphitf)



<!-- Sent from Reviewable.io -->

2022-12-26 08:57 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: all files reviewed, 3 unresolved discussions (waiting on @zuphitf)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NKCdPA_2mypus2tPz1J:-NKCdPA_2mypus2tPz1K:b-3b6q4o) (no related file):*
there's an improvement to remove many actions here - but we'll do it in another pr.

___


<!-- Sent from Reviewable.io -->

2022-12-26 09:21 UTC, zuphitf reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 352 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NJuY-bSCzi7Hz0pOpKC:-NKCj5LcBn4iC4vTY4zd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d02ff19c7237163b154afff36f5e077f5767a5d4/crates/sierra_to_casm/src/invocations/uint128.rs#L352)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i mean the calculation checking that the divmod hint is not lying to you does not overflow over felt.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-26 09:22 UTC, orizi approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)



<!-- Sent from Reviewable.io -->

2022-12-26 09:22 UTC, orizi approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/sierra/src/extensions/modules/uint128.rs` line 148 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NK8OMCR5O2tbhpnUmVy:-NKCjRfj7NZeAp4vzP94:bsanhjy) ([raw file](https://github.com/starkware-libs/cairo/blob/a5417f0325fb694bd0f18b01ac37f91f605e082c/crates/sierra/src/extensions/modules/uint128.rs#L148)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

shouldn't you be returning `(upper, lower)`? This looks like `(lower, upper)`
</blockquote></details>

i agree.


<!-- Sent from Reviewable.io -->

2022-12-26 09:36 UTC, zuphitf reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @orizi)

___
*[`crates/sierra/src/extensions/modules/uint128.rs` line 148 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NK8OMCR5O2tbhpnUmVy:-NKCltV90LgxkTlfR8pN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a5417f0325fb694bd0f18b01ac37f91f605e082c/crates/sierra/src/extensions/modules/uint128.rs#L148)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i agree.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-26 09:45 UTC, orizi reviewed
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/sierra_to_casm/src/invocations/uint128.rs` line 238 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1447#-NKCobZg026vUD4Hpng9:-NKCobZg026vUD4HpngA:bqr9e6v) ([raw file](https://github.com/starkware-libs/cairo/blob/70f02630f752eb0fe2a5b6e43518db6c55486816/crates/sierra_to_casm/src/invocations/uint128.rs#L238)):*
> ```XML
>                 // 64 bits, so those are within 192 bits range. Adding the 64 bits range-checked
>                 // a0_b1_bottom and a1_b0_bottom is guaranteed to leave the result within a felt's
>                 // range with no overflow. Asserting the result equals the 128 bits a0_b1, a1_b0
> ```

better - less confusing.



_Suggestion:_
```XML
                // a0_b1_bottom and a1_b0_bottom is guaranteed to leave the result within a felt's
                // range with no wrap-around. Asserting the result equals the 128 bits a0_b1, a1_b0
```


<!-- Sent from Reviewable.io -->

2022-12-26 10:01 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447#-:-NKCsJtK9E9EXYUgYIsS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)



<!-- Sent from Reviewable.io -->

2022-12-26 10:02 UTC, orizi approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)



<!-- Sent from Reviewable.io -->

2022-12-26 10:06 UTC, orizi approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1447)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)



<!-- Sent from Reviewable.io -->

2022-12-26 10:09 UTC, merged