Add dispatcher skeleton.
starkware-libs/cairo pull request #1509
Opened 2022-12-27 12:19 UTC by ilyalesokhin-starkware

2022-12-27 12:36 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509#-:-NKI_TudAmsAl6CUZhkM:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKI_GbHAVvWhlEIVMyk:-NKI_GbHAVvWhlEIVMyl:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cfc9d94d7922e9d0c676520a7fc85610510f1d1d/crates/starknet/src/plugin.rs#L22)):*
> ```XML
> use crate::contract::starknet_keccak;
> 
> pub static ABI_ATTR: &str = "abi";
> ```





_Suggestion:_
```XML
const
```
___
*[`crates/starknet/src/plugin.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKI_AX6-J4-7eF0QQHv:-NKI_AX6-J4-7eF0QQHw:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cfc9d94d7922e9d0c676520a7fc85610510f1d1d/crates/starknet/src/plugin.rs#L45)):*
> ```XML
>         diag: &dyn std::any::Any,
>     ) -> Option<PluginMappedDiagnostic> {
>         let Some(diag) = diag.downcast_ref::<SemanticDiagnostic>() else {return None;};
> ```





_Suggestion:_
```XML
        let Some(diag) = diag.downcast_ref::<SemanticDiagnostic>() else { return None; };
```


<!-- Sent from Reviewable.io -->

2022-12-27 12:42 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/starknet/src/plugin.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKI_GbHAVvWhlEIVMyk:-NKIaiDx8qvzTvCVPCcw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cfc9d94d7922e9d0c676520a7fc85610510f1d1d/crates/starknet/src/plugin.rs#L22)):*
> ```XML
> use crate::contract::starknet_keccak;
> 
> pub static ABI_ATTR: &str = "abi";
> ```

Done.
___
*[`crates/starknet/src/plugin.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKI_AX6-J4-7eF0QQHv:-NKIaoNI4cpLWejbCKQ2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cfc9d94d7922e9d0c676520a7fc85610510f1d1d/crates/starknet/src/plugin.rs#L45)):*
> ```XML
>         diag: &dyn std::any::Any,
>     ) -> Option<PluginMappedDiagnostic> {
>         let Some(diag) = diag.downcast_ref::<SemanticDiagnostic>() else {return None;};
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-12-27 13:19 UTC, orizi approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2022-12-28 15:54 UTC, yuvalsw requested changes
> Reviewed 10 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: 10 of 11 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/starknet.cairo` line 16 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOMdzC7Mylp_iplRRT:-NKOMdzC7Mylp_iplRRU:b-a7sph8) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/corelib/starknet.cairo#L16)):*
> ```Cairo
> extern fn call_contract_syscall(
>     address: ContractAddress, calldata: Array::<felt>
> ) -> Result::<Array::<felt>, (felt, Array::<felt>)> implicits(GasBuiltin, System) nopanic;
> ```

consider creating a type for it. Or at least for (felt, Array::<felt>)



_Code quote:_
```Cairo
Result::<Array::<felt>, (felt, Array::<felt>)>
```
___
*[`crates/cairo-starknet/src/plugin.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOOvHf-tIdmw5tY4RD:-NKOOvHf-tIdmw5tY4RE:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L39)):*
> ```XML
> 
> #[derive(Debug, PartialEq, Eq)]
> pub struct PatchMapper {
> ```

doc
___
*[`crates/cairo-starknet/src/plugin.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOQEp906x7GD3CdZuY:-NKOQEp906x7GD3CdZuZ:byxo6yc) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L97)):*
> ```XML
> impl SemanticPlugin for StarkNetPlugin {}
> 
> /// If the module is annotated with CONTRACT_ATTR, generate the relevant contract logic.
> ```

unrelated, fix



_Code quote:_
```XML
If the module is annotated with CONTRACT_ATTR, generate the relevant contract logic.
```
___
*[`crates/cairo-starknet/test_data/test_contract.cairo` line 2 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOR2Z5Ea1ysHAeGQg7:-NKOR2Z5Ea1ysHAeGQg8:b66vl4h) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/test_data/test_contract.cairo#L2)):*
> ```Cairo
> #[abi]
> trait IContract {
> ```

This can/should be in another test as we generate an ABI trait from the contract, so here we'll have 2 ABI traits.



_Code quote:_
```Cairo
#[abi]
trait IContract {
    fn foo();
}
```
___
*[`crates/cairo-starknet/src/plugin_test_data/dispatcher` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOQY1C0igBepg11aVZ:-NKOQY1C0igBepg11aV_:b-u5fpo4) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin_test_data/dispatcher#L14)):*
> ```
> //! > generated_cairo_code
> mod IContractDispatcher {
>     fn get_something(contract_address: ContractAddress, ref arg: felt, num: felt) -> felt {
> ```

I think we only support refs in the beginning, so you might beed to add Contract address in the end, or as a ref (with a TODO to fix).



_Code quote:_
```
contract_address: ContractAddress, ref arg
```
___
*[`crates/cairo-starknet/src/plugin_test_data/dispatcher` line 16 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOQiPHBbryUyd8CIjX:-NKOQiPHBbryUyd8CIjY:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin_test_data/dispatcher#L16)):*
> ```
>     fn get_something(contract_address: ContractAddress, ref arg: felt, num: felt) -> felt {
>         let calldata = array_new::<felt>();
>         // TODO: encode calldata.
> ```





_Suggestion:_
```
TODO(ilya):
```
___
*[`crates/cairo-starknet/src/plugin_test_data/dispatcher` line 25 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOQxBeDE_r7H5A5T8l:-NKOQxBeDE_r7H5A5T8m:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin_test_data/dispatcher#L25)):*
> ```
>                 panic(err_data)
>         } };
>     // TODO: decode ret_data.
> ```





_Suggestion:_
```
 TODO(ilya): deco
```


<!-- Sent from Reviewable.io -->

2022-12-28 21:55 UTC, orizi reviewed
> Reviewed 10 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: 10 of 11 files reviewed, all discussions resolved

___
*[`crates/cairo-starknet/src/plugin.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKPSrcf5uFrWnUaNFhY:-NKPSrcg48B2tKNitR3S:bfq64r9) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L39)):*
> ```XML
> 
> #[derive(Debug, PartialEq, Eq)]
> pub struct PatchMapper {
> ```

do this - as it isn't really clear what is the aim of this class (non-blocking since OOO)


<!-- Sent from Reviewable.io -->

2022-12-28 21:56 UTC, orizi approved these changes
> Reviewed 1 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2022-12-29 07:11 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-starknet/src/plugin.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKPSrcf5uFrWnUaNFhY:-NKRi5CzEzfnybHiBYPE:bipcdqp) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L39)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do this - as it isn't really clear what is the aim of this class (non-blocking since OOO)
</blockquote></details>

do this?


<!-- Sent from Reviewable.io -->

2022-12-29 08:50 UTC, yuvalsw requested changes
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: all files reviewed, 12 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-starknet/src/plugin.rs` line 123 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKS-FLz4uR5jndMz4A-:-NKS-FLz4uR5jndMz4A0:bl429fo) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L123)):*
> ```XML
>                 // Todo(ilya): Handle attributes
> 
>                 let declaration = func.declaration(db);
> ```

can this be inlined?
___
*[`crates/cairo-starknet/src/plugin.rs` line 136 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKS1ZF54LHLQVYWF0qE:-NKS1ZF54LHLQVYWF0qF:bi8imh6) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L136)):*
> ```XML
>                         [
>                             RewriteNode::Text("contract_address: ContractAddress".to_string()),
>                             RewriteNode::Text(", ".to_string()),
> ```

This is going to be formatted anyway, I think you can give up the space which would be a redundant trivium in the tree.



_Code quote:_
```XML
", "
```
___
*[`crates/cairo-starknet/src/plugin.rs` line 149 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKS2_T1-QqwIrxUDnwq:-NKS2_T1-QqwIrxUDnwr:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L149)):*
> ```XML
>                                 contract_address, calldata) {
>                             Result::Ok(ret_data) => ret_data,
>                             Result::Err((reason, ret_data)) => {
> ```





_Suggestion:_
```XML
_
```
___
*[`crates/cairo-starknet/src/plugin.rs` line 156 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKS2xP0DxpPPXan4Pts:-NKS2xP0DxpPPXan4Ptt:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L156)):*
> ```XML
>                             }
>                        };
>                        // TODO: decode ret_data.
> ```





_Suggestion:_
```XML
 // TODO: decode ret_data and return it.
```
___
*[`crates/cairo-starknet/src/plugin.rs` line 163 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKS3KSa74lJJOKBBfVp:-NKS3KSa74lJJOKBBfVq:b-1a4vce) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L163)):*
> ```XML
>     }
> 
>     builder.add_str(" }");
> ```

Can't you do something like:
"mod {}Dispatcher {{$node}}" and use interpolate_patched so that you can see the mod clearer?



_Code quote:_
```XML
 builder.add_str(" }");
```


<!-- Sent from Reviewable.io -->

2022-12-29 08:53 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-starknet/src/plugin.rs` line 136 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKS1ZF54LHLQVYWF0qE:-NKS4Vz0DqfVHS-mGpQi:b-281c2c) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L136)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This is going to be formatted anyway, I think you can give up the space which would be a redundant trivium in the tree.
</blockquote></details>

Where is it going to be formatted?


<!-- Sent from Reviewable.io -->

2022-12-29 08:55 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: all files reviewed, 12 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-starknet/src/plugin.rs` line 136 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKS1ZF54LHLQVYWF0qE:-NKS4jkj1OCZ-ia5nzMo:b-qm3ubm) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L136)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Where is it going to be formatted?
</blockquote></details>

Wherever it's going to show. Currently - I guess nowhere? Later - maybe in the IDE on hover if we want.
But now that I think about it - it does show once, to us - in tests, and for it it might be worth the extra trivium in the green tree :)


<!-- Sent from Reviewable.io -->

2022-12-29 08:56 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-starknet/src/plugin.rs` line 163 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKS3KSa74lJJOKBBfVp:-NKS4fy9E9m7oyuXqbK1:b-txj3e9) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L163)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can't you do something like:
"mod {}Dispatcher {{$node}}" and use interpolate_patched so that you can see the mod clearer?
</blockquote></details>

Not sure

you want something like


 builder.interpolate_patched(format!(
                    indoc! {"
                        mod dispatcher {{
                            {generacted_code}
                        }}
                    "}),
                   node_list
                );

i feel that it is more cubersome.


<!-- Sent from Reviewable.io -->

2022-12-29 08:57 UTC, ilyalesokhin-starkware commented
*[`corelib/starknet.cairo` line 16 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOMdzC7Mylp_iplRRT:-NKS5ROt-f5T9d23mkUx:bcxa3a7) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/corelib/starknet.cairo#L16)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

consider creating a type for it. Or at least for (felt, Array::<felt>)
</blockquote></details>

do you have an example for that?


<!-- Sent from Reviewable.io -->

2022-12-29 08:58 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-starknet/src/plugin_test_data/dispatcher` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOQY1C0igBepg11aVZ:-NKS5aIS3IPersbIr8Ne:b6p04lt) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin_test_data/dispatcher#L14)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think we only support refs in the beginning, so you might beed to add Contract address in the end, or as a ref (with a TODO to fix).
</blockquote></details>

Maybe we shouldn't support refs in contract entry points?


<!-- Sent from Reviewable.io -->

2022-12-29 09:18 UTC, yuvalsw requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: all files reviewed, 12 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/starknet.cairo` line 16 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOMdzC7Mylp_iplRRT:-NKS9EAh6VJXf4dHmcnB:bydjvhq) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/corelib/starknet.cairo#L16)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

do you have an example for that?
</blockquote></details>

You now even have type aliases...
`type SyscallResult = Result::<Array::<felt>, (felt, Array::<felt>)>;`

Or, similar to JumpNzResult (then you can add readable names like success and failure):
`enum JumpNzResult<T> { Zero: (), NonZero: NonZero::<T>, }`

Or:
`type SyscallFailure = (felt, Array::<felt>);`
and
`Result::<Array::<felt>, SyscallFailure>`
___
*[`crates/cairo-starknet/src/plugin.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKPSrcf5uFrWnUaNFhY:-NKS96l70YMyizzzn8Bj:b-ksls9j) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L39)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

do this?
</blockquote></details>

I guess he wanted to comment on my "doc" comment.
___
*[`crates/cairo-starknet/src/plugin.rs` line 163 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKS3KSa74lJJOKBBfVp:-NKS8Vgp9Mi0OJQ3fr8r:b-e1ncxg) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L163)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Not sure

you want something like


 builder.interpolate_patched(format!(
                    indoc! {"
                        mod dispatcher {{
                            {generacted_code}
                        }}
                    "}),
                   node_list
                );

i feel that it is more cubersome.

</blockquote></details>

I think that if I have the lbrace and rbrace together in one place, it makes it clearer.
___
*[`crates/cairo-starknet/src/plugin_test_data/dispatcher` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOQY1C0igBepg11aVZ:-NKS8rI98G7FLwbUJBo0:b-f8tv0) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin_test_data/dispatcher#L14)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Maybe we shouldn't support refs in contract entry points?
</blockquote></details>

This might be a working workaround until we support refs not in the beginning. But we do plan to support it.


<!-- Sent from Reviewable.io -->

2022-12-29 09:25 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-starknet/src/plugin_test_data/dispatcher` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOQY1C0igBepg11aVZ:-NKSBgyCBb1wCHjxWWNn:b-iuc8y9) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin_test_data/dispatcher#L14)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This might be a working workaround until we support refs not in the beginning. But we do plan to support it.
</blockquote></details>

When did we decide on it?


<!-- Sent from Reviewable.io -->

2022-12-29 09:25 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-starknet/test_data/test_contract.cairo` line 2 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOR2Z5Ea1ysHAeGQg7:-NKSBqYW8x3l4z1ImBcy:bv5i5b3) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/test_data/test_contract.cairo#L2)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This can/should be in another test as we generate an ABI trait from the contract, so here we'll have 2 ABI traits.
</blockquote></details>

Im planing on using it in this contract.


<!-- Sent from Reviewable.io -->

2022-12-29 09:26 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-starknet/test_data/test_contract.cairo` line 2 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOR2Z5Ea1ysHAeGQg7:-NKSBuWjAHgXl8ONGrWY:b-lzjj9r) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/test_data/test_contract.cairo#L2)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Im planing on using it in this contract.
</blockquote></details>

e.g.

 TestContract is going to call a contract that implements IContract.


<!-- Sent from Reviewable.io -->

2022-12-29 09:26 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: all files reviewed, 12 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-starknet/src/plugin.rs` line 163 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKS3KSa74lJJOKBBfVp:-NKSC4jY6v0PF1XPo03F:b-n7lpnw) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L163)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think that if I have the lbrace and rbrace together in one place, it makes it clearer.
</blockquote></details>

I disagree.


<!-- Sent from Reviewable.io -->

2022-12-29 09:27 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: all files reviewed, 12 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-starknet/src/plugin.rs` line 123 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKS-FLz4uR5jndMz4A-:-NKSC9iW32RIf_9H4AAX:bg7n3z3) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L123)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

can this be inlined?
</blockquote></details>

I'm going to use it in the next PR.
but ok.
___
*[`crates/cairo-starknet/src/plugin.rs` line 136 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKS1ZF54LHLQVYWF0qE:-NKSC8Ju6kWvo68J8fTs:b-x4gta) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L136)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Wherever it's going to show. Currently - I guess nowhere? Later - maybe in the IDE on hover if we want.
But now that I think about it - it does show once, to us - in tests, and for it it might be worth the extra trivium in the green tree :)
</blockquote></details>

so this is resolved, right?


<!-- Sent from Reviewable.io -->

2022-12-29 09:41 UTC, ilyalesokhin-starkware commented
*[`corelib/starknet.cairo` line 16 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOMdzC7Mylp_iplRRT:-NKSDqX1Ev-wu8ikS2Ve:bwb0woy) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/corelib/starknet.cairo#L16)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

You now even have type aliases...
`type SyscallResult = Result::<Array::<felt>, (felt, Array::<felt>)>;`

Or, similar to JumpNzResult (then you can add readable names like success and failure):
`enum JumpNzResult<T> { Zero: (), NonZero: NonZero::<T>, }`

Or:
`type SyscallFailure = (felt, Array::<felt>);`
and
`Result::<Array::<felt>, SyscallFailure>`
</blockquote></details>

It is used only once so I'm not sure what is the benefit, but ok.


<!-- Sent from Reviewable.io -->

2022-12-29 09:58 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: 5 of 11 files reviewed, 7 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-starknet/src/plugin.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOOvHf-tIdmw5tY4RD:-NKSFDrwB4W5V2MysfJq:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L39)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doc
</blockquote></details>

done
___
*[`crates/cairo-starknet/src/plugin.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOQEp906x7GD3CdZuY:-NKSFPye6vEhaeQGupH_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L97)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

unrelated, fix
</blockquote></details>

Done.
___
*[`crates/cairo-starknet/src/plugin.rs` line 149 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKS2_T1-QqwIrxUDnwq:-NKSHp4z7_WqfKQMYP2u:bxkmy85) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L149)):*
> ```XML
>                                 contract_address, calldata) {
>                             Result::Ok(ret_data) => ret_data,
>                             Result::Err((reason, ret_data)) => {
> ```

why not give it a name?
___
*[`crates/cairo-starknet/src/plugin.rs` line 156 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKS2xP0DxpPPXan4Pts:-NKSHua90Y7ttryF3qAf:b-oq12r3) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L156)):*
>  decode ret_data and return it.
done


<!-- Sent from Reviewable.io -->

2022-12-29 10:41 UTC, orizi approved these changes
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: all files reviewed, 7 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-starknet/src/plugin.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKPSrcf5uFrWnUaNFhY:-NKSSVu-0QVyLSmP-cOM:b-rc0m0y) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L39)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I guess he wanted to comment on my "doc" comment.
</blockquote></details>

This is reviewable, so I didn't see it, just missed a c in doc..


<!-- Sent from Reviewable.io -->

2022-12-29 12:28 UTC, yuvalsw requested changes
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-starknet/src/plugin.rs` line 149 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKS2_T1-QqwIrxUDnwq:-NKSpGFGANfIDWVcvqMF:brou7h3) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L149)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why not give it a name?
</blockquote></details>

It's ok to give it a name, if you use it. If you don't, it's misleading. What do you intend to do with it? Add it to err_data?
___
*[`crates/cairo-starknet/src/plugin.rs` line 177 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKSpXs559IkacG9hq0f:-NKSpXs559IkacG9hq0g:b-u992g6) ([raw file](https://github.com/starkware-libs/cairo/blob/224e412ee8d598473d4c975ffccfd30468eab9ad/crates/cairo-starknet/src/plugin.rs#L177)):*
> ```XML
> }
> 
> /// If the trait is annotated with ABI_ATTR, generate the relevant dispatcher logic.
> ```

this was actually true, revert it.



_Code quote:_
```XML
the trait is annotated with ABI_ATTR, generate the relevant dispatcher logic
```
___
*[`crates/cairo-starknet/test_data/test_contract.cairo` line 2 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOR2Z5Ea1ysHAeGQg7:-NKSqUM66YRUKGARa2zh:bca2ofj) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/test_data/test_contract.cairo#L2)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

e.g.

 TestContract is going to call a contract that implements IContract.
</blockquote></details>

Ah, OK, it's a different ABI from the one created by the contract.
Maybe rename to IERC20/IAnotherABI/IAnotherContract?
___
*[`crates/cairo-starknet/src/plugin_test_data/dispatcher` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOQY1C0igBepg11aVZ:-NKSpi7q6KFmucOZCXAG:b-pnioad) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin_test_data/dispatcher#L14)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

When did we decide on it?
</blockquote></details>

Not sure we had a formal discussion, but there is a TODO in the code and it makes sense (I am talking about in Cairo1).
Anyway, for now you should resolve it somehow:
1. change it to ref with a TODO.
2. don't allow refs in entry points.
3. add it in the end. (This is the worst option IMO)


<!-- Sent from Reviewable.io -->

2022-12-29 12:31 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-starknet/src/plugin.rs` line 149 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKS2_T1-QqwIrxUDnwq:-NKSrN5u4KJtOGMMbTIP:b2nign6) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin.rs#L149)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

It's ok to give it a name, if you use it. If you don't, it's misleading. What do you intend to do with it? Add it to err_data?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2022-12-29 12:51 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-starknet/test_data/test_contract.cairo` line 2 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOR2Z5Ea1ysHAeGQg7:-NKStySJ5eX4c_G3tMoH:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/test_data/test_contract.cairo#L2)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Ah, OK, it's a different ABI from the one created by the contract.
Maybe rename to IERC20/IAnotherABI/IAnotherContract?
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2022-12-29 12:53 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-starknet/src/plugin_test_data/dispatcher` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKOQY1C0igBepg11aVZ:-NKSwNZu86pkHRGjF9eH:b-knv1ek) ([raw file](https://github.com/starkware-libs/cairo/blob/a6e0e4330c4fb8199a6186baa821598bbca4825a/crates/cairo-starknet/src/plugin_test_data/dispatcher#L14)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Not sure we had a formal discussion, but there is a TODO in the code and it makes sense (I am talking about in Cairo1).
Anyway, for now you should resolve it somehow:
1. change it to ref with a TODO.
2. don't allow refs in entry points.
3. add it in the end. (This is the worst option IMO)
</blockquote></details>

added a todo.



_Code quote (from crates/cairo-starknet/src/plugin.rs):_
```XML
/// If the module is annotated with CONTRACT_ATTR, generate the relevant contract logic.
```


<!-- Sent from Reviewable.io -->

2022-12-29 12:55 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-starknet/src/plugin.rs` line 177 at r4](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKSpXs559IkacG9hq0f:-NKSwproBoxKlYMxyy4C:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/224e412ee8d598473d4c975ffccfd30468eab9ad/crates/cairo-starknet/src/plugin.rs#L177)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

this was actually true, revert it.
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2022-12-29 12:56 UTC, yuvalsw requested changes
> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, 1 of 1 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`crates/cairo-starknet/src/plugin.rs` line 122 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKSwwal-R4kW68Cd_US:-NKSwwal-R4kW68Cd_UT:b-h9npij) ([raw file](https://github.com/starkware-libs/cairo/blob/413f373919701da83615f6fc645225cfa278727e/crates/cairo-starknet/src/plugin.rs#L122)):*
> ```XML
>         match item_ast {
>             ast::TraitItem::Function(func) => {
>                 // TODO(ilya): Decide how to handle ref args.
> ```

But for now, you should explicitly not allow it. It's better than generating wrong code.



_Code quote:_
```XML
Decide how to handle ref args.
```
___
*[`crates/cairo-starknet/src/plugin.rs` line 158 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKSwZ5vCaFX7Sqef1Pj:-NKSwZ5vCaFX7Sqef1Pk:bs1tash) ([raw file](https://github.com/starkware-libs/cairo/blob/413f373919701da83615f6fc645225cfa278727e/crates/cairo-starknet/src/plugin.rs#L158)):*
> ```XML
>                 builder.add_modified(RewriteNode::Modified(ModifiedNode {
>                     children: vec![
>                         RewriteNode::from_ast(&func.attributes(db)),
> ```

remove the #[abi] attr?



_Code quote:_
```XML
&func.attributes(db)
```


<!-- Sent from Reviewable.io -->

2022-12-29 13:02 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-starknet/src/plugin.rs` line 122 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKSwwal-R4kW68Cd_US:-NKSyUhxBEyD2Zwrc5A1:b-dpfeu2) ([raw file](https://github.com/starkware-libs/cairo/blob/413f373919701da83615f6fc645225cfa278727e/crates/cairo-starknet/src/plugin.rs#L122)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

But for now, you should explicitly not allow it. It's better than generating wrong code.
</blockquote></details>

how is it wrong?


<!-- Sent from Reviewable.io -->

2022-12-29 13:02 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-starknet/src/plugin.rs` line 158 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKSwZ5vCaFX7Sqef1Pj:-NKSyZ072CfhbdGCIYMb:bunnxiq) ([raw file](https://github.com/starkware-libs/cairo/blob/413f373919701da83615f6fc645225cfa278727e/crates/cairo-starknet/src/plugin.rs#L158)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

remove the #[abi] attr?
</blockquote></details>

There is not #[abi] on the functions.


<!-- Sent from Reviewable.io -->

2022-12-29 13:03 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-starknet/src/plugin.rs` line 122 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKSwwal-R4kW68Cd_US:-NKSygSkDRnuEbyOSq7Z:b2gvniu) ([raw file](https://github.com/starkware-libs/cairo/blob/413f373919701da83615f6fc645225cfa278727e/crates/cairo-starknet/src/plugin.rs#L122)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

how is it wrong?
</blockquote></details>

how you worried becuase the semantic does not give an error?

it is a bug in the sematic in that case.


<!-- Sent from Reviewable.io -->

2022-12-29 13:07 UTC, yuvalsw requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-starknet/src/plugin.rs` line 122 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKSwwal-R4kW68Cd_US:-NKSzMli24Tl9JFep_mz:b-qf62mh) ([raw file](https://github.com/starkware-libs/cairo/blob/413f373919701da83615f6fc645225cfa278727e/crates/cairo-starknet/src/plugin.rs#L122)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

how you worried becuase the semantic does not give an error?

it is a bug in the sematic in that case.
</blockquote></details>

I am not sure we are talking about the same thing. Let's discuss f2f.


<!-- Sent from Reviewable.io -->

2022-12-29 17:10 UTC, yuvalsw requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-starknet/src/plugin.rs` line 167 at r12](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKTnwDS4UOfWvRCiDm-:-NKTnwDS4UOfWvRCiDm0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b2a8e23b6b1219f93c0966fd2e04106d70bcc226/crates/cairo-starknet/src/plugin.rs#L167)):*
> ```XML
>     builder.add_modified(RewriteNode::Modified(ModifiedNode {
>         children: vec![
>             RewriteNode::Text(format!("mod {}Dispatcher {{\n", trait_ast.name(db).text(db))),
> ```





_Suggestion:_
```XML
    builder.interpolate_patched(
        formatdoc!("mod {}Dispatcher {{$body$}}", trait_ast.name(db).text(db))
        HashMap::from([(
            "body".to_string(), RewriteNode::Modified(ModifiedNode { children: functions })),
        ]),
    }));
```


<!-- Sent from Reviewable.io -->

2022-12-29 17:35 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-starknet/src/plugin.rs` line 167 at r12](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKTnwDS4UOfWvRCiDm-:-NKTupWb77I7PTCrX-my:b-vjtcrh) ([raw file](https://github.com/starkware-libs/cairo/blob/b2a8e23b6b1219f93c0966fd2e04106d70bcc226/crates/cairo-starknet/src/plugin.rs#L167)):*
> ```XML
>     builder.add_modified(RewriteNode::Modified(ModifiedNode {
>         children: vec![
>             RewriteNode::Text(format!("mod {}Dispatcher {{\n", trait_ast.name(db).text(db))),
> ```

feels less readable to me, but ok.


<!-- Sent from Reviewable.io -->

2023-01-01 08:39 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-starknet/src/plugin.rs` line 122 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKSwwal-R4kW68Cd_US:-NKgMjoK365JRduCi1bT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/413f373919701da83615f6fc645225cfa278727e/crates/cairo-starknet/src/plugin.rs#L122)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I am not sure we are talking about the same thing. Let's discuss f2f.
</blockquote></details>

Done.
___
*[`crates/cairo-starknet/src/plugin.rs` line 139 at r13](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKgTtmi7xRlo8wrUW_F:-NKgTtmi7xRlo8wrUW_G:b-e4tc27) ([raw file](https://github.com/starkware-libs/cairo/blob/9911f043e413dbcb37d4b0ba706da4b64ef99c8a/crates/cairo-starknet/src/plugin.rs#L139)):*
> ```XML
>                 if has_ref_params {
>                     continue;
>                 }
> ```

I'm not sure this is the correct behavior it mean, that the use will get function not exist in this case.



_Code quote:_
```XML
                if has_ref_params {
                    continue;
                }
```


<!-- Sent from Reviewable.io -->

2023-01-01 14:10 UTC, yuvalsw requested changes
> Reviewed 1 of 2 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-starknet/src/plugin.rs` line 134 at r13](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKhdAI-BV7H7Y_U7ONv:-NKhdAI-BV7H7Y_U7ONw:b-skcy3j) ([raw file](https://github.com/starkware-libs/cairo/blob/9911f043e413dbcb37d4b0ba706da4b64ef99c8a/crates/cairo-starknet/src/plugin.rs#L134)):*
> ```XML
>                                 .to_string(),
>                             stable_ptr: param.modifiers(db).stable_ptr().untyped(),
>                         })
> ```

break;
___
*[`crates/cairo-starknet/src/plugin.rs` line 139 at r13](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKgTtmi7xRlo8wrUW_F:-NKhdczkBcEgFiht4kmy:byhhp1i) ([raw file](https://github.com/starkware-libs/cairo/blob/9911f043e413dbcb37d4b0ba706da4b64ef99c8a/crates/cairo-starknet/src/plugin.rs#L139)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm not sure this is the correct behavior it mean, that the use will get function not exist in this case.
</blockquote></details>

not sure what you mean. Can you clarify?
Anyway - if you are unsure, this looks OK for now, you can submit it this way and add a todo.
___
*[`crates/cairo-starknet/src/plugin.rs` line 189 at r13](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKhe0Du3PLk-dgWjP5Q:-NKhe0Du3PLk-dgWjP5R:bsi8oi9) ([raw file](https://github.com/starkware-libs/cairo/blob/9911f043e413dbcb37d4b0ba706da4b64ef99c8a/crates/cairo-starknet/src/plugin.rs#L189)):*
> ```XML
>         &formatdoc!(
>             "mod {}Dispatcher {{
>                         $body$}}",
> ```

line break after body?



_Code quote:_
```XML
   $body$}}
```
___
*[`crates/cairo-starknet/src/plugin_test_data/dispatcher` line 62 at r13](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKheh9oEn67QiK5BH_y:-NKheh9oEn67QiK5BH_z:bpm9ay9) ([raw file](https://github.com/starkware-libs/cairo/blob/9911f043e413dbcb37d4b0ba706da4b64ef99c8a/crates/cairo-starknet/src/plugin_test_data/dispatcher#L62)):*
> ```
> 
> //! > expected_diagnostics
> error: `ref` parameters are not supported in the ABI of a contract.
> ```

please add another ref param and make sure this diagnostic appears only once for the first one.


<!-- Sent from Reviewable.io -->

2023-01-01 14:13 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-starknet/src/plugin.rs` line 189 at r13](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKhe0Du3PLk-dgWjP5Q:-NKhfPUr0Oj4wn21-tnR:b-xyia3k) ([raw file](https://github.com/starkware-libs/cairo/blob/9911f043e413dbcb37d4b0ba706da4b64ef99c8a/crates/cairo-starknet/src/plugin.rs#L189)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

line break after body?
</blockquote></details>

the problem is that $body$ ends with a line break.


<!-- Sent from Reviewable.io -->

2023-01-01 14:13 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: all files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-starknet/src/plugin_test_data/dispatcher` line 62 at r13](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKheh9oEn67QiK5BH_y:-NKhfUbE81rFyC8qP7_Y:btkjpoj) ([raw file](https://github.com/starkware-libs/cairo/blob/9911f043e413dbcb37d4b0ba706da4b64ef99c8a/crates/cairo-starknet/src/plugin_test_data/dispatcher#L62)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please add another ref param and make sure this diagnostic appears only once for the first one.
</blockquote></details>

it appers more then once, that's what we do in the rest of the compiler.


<!-- Sent from Reviewable.io -->

2023-01-01 14:20 UTC, yuvalsw requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-starknet/src/plugin.rs` line 189 at r13](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKhe0Du3PLk-dgWjP5Q:-NKhgqXWCZ1njBQ_uJLy:b4661le) ([raw file](https://github.com/starkware-libs/cairo/blob/9911f043e413dbcb37d4b0ba706da4b64ef99c8a/crates/cairo-starknet/src/plugin.rs#L189)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

the problem is that $body$ ends with a line break.
</blockquote></details>

ah, ok, this will be fixed in my pr when we format it.
resolving for now.
___
*[`crates/cairo-starknet/src/plugin_test_data/dispatcher` line 62 at r13](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKheh9oEn67QiK5BH_y:-NKhh2AW9-Na5RrHoxHv:bv0yhth) ([raw file](https://github.com/starkware-libs/cairo/blob/9911f043e413dbcb37d4b0ba706da4b64ef99c8a/crates/cairo-starknet/src/plugin_test_data/dispatcher#L62)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it appers more then once, that's what we do in the rest of the compiler.
</blockquote></details>

I don't follow. I want to make sure the 'break' from my other comment does what it supposed to.


<!-- Sent from Reviewable.io -->

2023-01-01 14:23 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-starknet/src/plugin_test_data/dispatcher` line 62 at r13](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKheh9oEn67QiK5BH_y:-NKhhiUE8PSkT3bUEfgM:b-wtkxg2) ([raw file](https://github.com/starkware-libs/cairo/blob/9911f043e413dbcb37d4b0ba706da4b64ef99c8a/crates/cairo-starknet/src/plugin_test_data/dispatcher#L62)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I don't follow. I want to make sure the 'break' from my other comment does what it supposed to.
</blockquote></details>

there shouldn't be a break there.


<!-- Sent from Reviewable.io -->

2023-01-01 14:23 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-starknet/src/plugin.rs` line 134 at r13](https://reviewable.io/reviews/starkware-libs/cairo/1509#-NKhdAI-BV7H7Y_U7ONv:-NKhhnD17v8ERz_OW1HX:bhet9b5) ([raw file](https://github.com/starkware-libs/cairo/blob/9911f043e413dbcb37d4b0ba706da4b64ef99c8a/crates/cairo-starknet/src/plugin.rs#L134)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

break;
</blockquote></details>

this is inconsistent with the reset of the compiler.


<!-- Sent from Reviewable.io -->

2023-01-01 15:05 UTC, yuvalsw approved these changes
> Reviewed 2 of 4 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2023-01-01 15:05 UTC, yuvalsw approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1509#-:-NKhrQ554Gmj1L9yzQ7V:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2023-01-01 15:05 UTC, merged