Support inlining of simple functions.
starkware-libs/cairo pull request #1702
Opened 2023-01-09 09:08 UTC by ilyalesokhin-starkware

2023-01-09 09:12 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLKnEc-1Qczjf8qasl9:-NLKnEc0CH_W5OyRZpDB:b-3iiw59) ([raw file](https://github.com/starkware-libs/cairo/blob/d9030932a0d5c8005fa874c79bb8a5b4c9e55484/crates/cairo-lang-lowering/src/lower/inline.rs#L97)):*
> ```XML
>                 StructuredBlockEnd::Callsite(returns.to_vec())
>             }
>             _ => panic!("Unexpected block end."),
> ```

should I use diagnostics here?



_Code quote:_
```XML
  _ => panic!("Unexpected block end."),
```


<!-- Sent from Reviewable.io -->

2023-01-09 10:02 UTC, orizi requested changes
> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLKnEc-1Qczjf8qasl9:-NLKxAJg9F651gmk7UiL:bmnus3a) ([raw file](https://github.com/starkware-libs/cairo/blob/d9030932a0d5c8005fa874c79bb8a5b4c9e55484/crates/cairo-lang-lowering/src/lower/inline.rs#L97)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

should I use diagnostics here?
</blockquote></details>

you need to somehow validate that you don't inline bad functions,
either here - or somewhere where you decide to inline this.
___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLKxZXtCVOlZBN5zMvM:-NLKxZXtCVOlZBN5zMvN:beqhj9m) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L96)):*
> ```XML
>         let end = match &block.end {
>             StructuredBlockEnd::Callsite(_) => block.end.clone(),
>             StructuredBlockEnd::Return { refs: _, returns } if block_id == root_block_id => {
> ```

don't you need to rename the variables here as well?



_Code quote:_
```XML
            StructuredBlockEnd::Callsite(_) => block.end.clone(),
            StructuredBlockEnd::Return { refs: _, returns } if block_id == root_block_id => {
                StructuredBlockEnd::Callsite(returns.to_vec())
            }
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 533 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLKxfvK5yxxqRx98eho:-NLKxfvK5yxxqRx98ehp:b32vlc) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/mod.rs#L533)):*
> ```XML
>             let var = match block_result {
>                 CallBlockResult::Callsite { pushes: _, maybe_output: Some(var) } => var,
>                 _ => panic!("unexpected block reculst."),
> ```

?



_Suggestion:_
```XML
                _ => panic!("unexpected block result."),
```
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLKyGF6CNcPuQbhXAuC:-NLKyGF6CNcPuQbhXAuD:b-s2xqf5) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-semantic/src/items/functions.rs#L52)):*
> ```XML
> 
>     /// Returns the ExternFunctionId if this is an extern function. Otherwise returns none.
>     pub fn try_get_free_function_id(
> ```

why is this only for extern funcs?
also - if it is just for externs - rename to something that reflects this.



_Code quote:_
```XML
    pub fn try_get_free_function_id(
```


<!-- Sent from Reviewable.io -->

2023-01-09 10:57 UTC, spapinistarkware requested changes
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 504 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLL9zSk5jPHT22YtI80:-NLL9zSk5jPHT22YtI81:b-h7f94x) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/mod.rs#L504)):*
> ```XML
>     let expr_ty = if may_panic { get_panic_ty(ctx.db.upcast(), expr.ty) } else { expr.ty };
> 
>     // The following is relevant only to free functions.
> ```

The lowering should be done in a separate phase, no in the main lowering phase.
1. To reduce complexity from this phase.
2. To not crash on cycles, and even allow them when inlining (kind of loop unrolling),


<!-- Sent from Reviewable.io -->

2023-01-09 11:24 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 3 of 5 files reviewed, 9 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLFOPP0B4sdLo3VU5w:-NLLFOPP0B4sdLo3VU5x:b-d86oe7) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L17)):*
> ```XML
> 
>     let mut renamed_vars = HashMap::new();
>     let mut rename_var = |old_var_id: &VariableId| match renamed_vars.entry(*old_var_id) {
> ```

Instead o matching, you can do



_Suggestion:_
```XML
renamed_vars.entry(*old_var_id).or_insert_with(
```
___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLFj1nEimHJcktyS3X:-NLLFj1nEimHJcktyS3Y:b5ocgm8) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L21)):*
> ```XML
>         Entry::Vacant(e) => {
>             let new_var_id = ctx.variables.alloc(lowered.variables[*old_var_id].clone());
>             e.insert(new_var_id);
> ```

Use `ctx.new_var()`



_Code quote:_
```XML
            let new_var_id = ctx.variables.alloc(lowered.variables[*old_var_id].clone());
            e.insert(new_var_id);
            new_var_id
```
___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLFz3CAY0eYEWthDN_:-NLLFz3CAY0eYEWthDNa:b5nuqyr) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L32)):*
> ```XML
>         let mut statements = vec![];
>         for stmt in &block.statements {
>             statements.push(match stmt {
> ```

Please move to a separate line.



_Suggestion:_
```XML
let stmt = 
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 516 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLGVxGDMqj_gBrUmw8:-NLLGVxGDMqj_gBrUmw9:bscsox1) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/mod.rs#L516)):*
> ```XML
>             let lowered = ctx
>                 .db
>                 .free_function_lowered_structured(free_function_id)
> ```

This could potentially cause cycles. See above.



_Code quote:_
```XML
ree_function_lowered_structured
```


<!-- Sent from Reviewable.io -->

2023-01-09 11:25 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 3 of 5 files reviewed, 10 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLGdYADJti5jnIJ3xU:-NLLGdYADJti5jnIJ3xV:b4hg3bq) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L95)):*
> ```XML
> 
>         let end = match &block.end {
>             StructuredBlockEnd::Callsite(_) => block.end.clone(),
> ```

This should not be possible at the root block. You can panic.



_Code quote:_
```XML
StructuredBlockEnd::Callsite(_) 
```


<!-- Sent from Reviewable.io -->

2023-01-09 11:25 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLGdYADJti5jnIJ3xU:-NLLGkQy0Pdev0DN00iE:ba51rea) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L95)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This should not be possible at the root block. You can panic.
</blockquote></details>

It happes when you are doing

#[inline]
fn bar() -> felt {
    1
}


<!-- Sent from Reviewable.io -->

2023-01-09 11:30 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 1 of 6 files reviewed, 9 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLGdYADJti5jnIJ3xU:-NLLHpFK9Xp_gv7NoxgJ:bumm3ne) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L95)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It happes when you are doing

#[inline]
fn bar() -> felt {
    1
}
</blockquote></details>

:( I thought I fixed this. It was causing a bug in sierra....


<!-- Sent from Reviewable.io -->

2023-01-09 11:32 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 1 of 6 files reviewed, 9 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLKxZXtCVOlZBN5zMvM:-NLLGvDbEwbb4EJ--l4D:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L96)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

don't you need to rename the variables here as well?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 533 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLKxfvK5yxxqRx98eho:-NLL5v2fBpN9SDO8C9uQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/mod.rs#L533)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.



_Code quote:_
```XML
      CallBlockResult::Callsite { pushes: _, maybe_output: Some(var) } => var,
```
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLKyGF6CNcPuQbhXAuC:-NLL5o7PCo2ig77daqgT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-semantic/src/items/functions.rs#L52)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is this only for extern funcs?
also - if it is just for externs - rename to something that reflects this.
</blockquote></details>

Done.



_Code quote:_
```XML
n try_get_free_function_id
```


<!-- Sent from Reviewable.io -->

2023-01-09 11:36 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLFj1nEimHJcktyS3X:-NLLJJhI1woO7C8AQZDU:b-azmd96) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L21)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Use `ctx.new_var()`
</blockquote></details>

isnt it wasteful to do the type_info lookup again?


<!-- Sent from Reviewable.io -->

2023-01-09 11:37 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 1 of 6 files reviewed, 9 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLFOPP0B4sdLo3VU5w:-NLLJ7S4DRyBBLOqfjaP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L17)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Instead o matching, you can do
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-09 11:39 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLFj1nEimHJcktyS3X:-NLLK0zb4HaNPKfndANY:b-e12yw5) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L21)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

isnt it wasteful to do the type_info lookup again?
</blockquote></details>

+ new_var borrows ctx.


<!-- Sent from Reviewable.io -->

2023-01-09 11:49 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 516 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLGVxGDMqj_gBrUmw8:-NLLMJIJ8AR_XoRgB6By:b-sbsnva) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/mod.rs#L516)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This could potentially cause cycles. See above.
</blockquote></details>

only if you put #[inline] in the wrong place.


<!-- Sent from Reviewable.io -->

2023-01-09 11:50 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 1 of 6 files reviewed, 9 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 516 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLGVxGDMqj_gBrUmw8:-NLLMRQe-Ja70prnQqyj:bfmw4xo) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/mod.rs#L516)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

only if you put #[inline] in the wrong place.
</blockquote></details>

And you would crash the compiler, yes.


<!-- Sent from Reviewable.io -->

2023-01-09 11:50 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 1 of 6 files reviewed, 9 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLFOPP0B4sdLo3VU5w:-NLLMYBW9Zrv-aU_gQKV:bu4d1oj) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L17)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

IS it?


<!-- Sent from Reviewable.io -->

2023-01-09 11:53 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 516 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLGVxGDMqj_gBrUmw8:-NLLNGcuCBwUfsvQ7G-O:bjf968t) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/mod.rs#L516)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

And you would crash the compiler, yes.
</blockquote></details>

I think we are ok with that.


<!-- Sent from Reviewable.io -->

2023-01-09 11:54 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 516 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLGVxGDMqj_gBrUmw8:-NLLNJ476HRjxOH9e4zJ:b-jkw9fz) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/mod.rs#L516)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think we are ok with that.
</blockquote></details>

you can also crash it with a wrong extern decleration


<!-- Sent from Reviewable.io -->

2023-01-09 12:04 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 1 of 6 files reviewed, 9 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLKnEc-1Qczjf8qasl9:-NLLLzWS3QwlbnM10l7u:bet3ezk) ([raw file](https://github.com/starkware-libs/cairo/blob/d9030932a0d5c8005fa874c79bb8a5b4c9e55484/crates/cairo-lang-lowering/src/lower/inline.rs#L97)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you need to somehow validate that you don't inline bad functions,
either here - or somewhere where you decide to inline this.
</blockquote></details>

we have the #[inline] attribute.


<!-- Sent from Reviewable.io -->

2023-01-09 12:10 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 504 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLL9zSk5jPHT22YtI80:-NLLQo7B16Dq6AJ8L8gE:b-s73ga2) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/mod.rs#L504)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

The lowering should be done in a separate phase, no in the main lowering phase.
1. To reduce complexity from this phase.
2. To not crash on cycles, and even allow them when inlining (kind of loop unrolling),
</blockquote></details>

Are you suggesting a phase that only goes over things looking for 
StatementCall
?


<!-- Sent from Reviewable.io -->

2023-01-09 12:11 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 1 of 6 files reviewed, 9 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 504 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLL9zSk5jPHT22YtI80:-NLLRCt61pyV9qYKdkD8:bg4qd2h) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/mod.rs#L504)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Are you suggesting a phase that only goes over things looking for 
StatementCall
?
</blockquote></details>

it wouldn't automatically solve the cycle issue, as I want to inline function after inling was applied to them.


<!-- Sent from Reviewable.io -->

2023-01-09 12:16 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 1 of 6 files reviewed, 9 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLFOPP0B4sdLo3VU5w:-NLLSVntEYVm1JKl5vlS:bpgk5t8) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L17)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

IS it?
</blockquote></details>

wasn't pushed :(
___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLFz3CAY0eYEWthDN_:-NLLSSKD0csaYufDwU4P:b-6h6xlt) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L32)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Please move to a separate line.
</blockquote></details>

moved the inner logic to a function.


<!-- Sent from Reviewable.io -->

2023-01-09 12:17 UTC, orizi requested changes
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 2 of 6 files reviewed, 9 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 54 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLIxtOE3lMEMooZZmr:-NLLIxtOE3lMEMooZZms:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b30b3e4b359436a9a8a5997b33055819fc1bbfde/crates/cairo-lang-lowering/src/diagnostic.rs#L54)):*
> ```XML
> 
>             LoweringDiagnosticKind::InliningFailed { reason } => {
>                 format!("Inlining faild: {reason}")
> ```





_Suggestion:_
```XML
                format!("Inlining failed: {reason}")
```
___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLKnEc-1Qczjf8qasl9:-NLLSQKeAnOgI1ueZ_69:b-o45b5f) ([raw file](https://github.com/starkware-libs/cairo/blob/d9030932a0d5c8005fa874c79bb8a5b4c9e55484/crates/cairo-lang-lowering/src/lower/inline.rs#L97)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

we have the #[inline] attribute.
</blockquote></details>

this comes back to the other discussion.
___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 113 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLSabUCgMGWYHeWQeO:-NLLSabUCgMGWYHeWQeP:b-9i5nt0) ([raw file](https://github.com/starkware-libs/cairo/blob/b30b3e4b359436a9a8a5997b33055819fc1bbfde/crates/cairo-lang-lowering/src/lower/inline.rs#L113)):*
> ```XML
>                     )));
>                 }
>                 if !refs.is_empty() {
> ```

you can add diagnostics for it - so please do (especially since there's no reason for users not to directly use #[inline])



_Code quote:_
```XML
                }
                if !refs.is_empty() {
                    panic!("Can't inline funcitons with refs.")
                }
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 516 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLGVxGDMqj_gBrUmw8:-NLLPmKI2hMTg0YQE2wV:bo2g9yt) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/mod.rs#L516)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

you can also crash it with a wrong extern decleration
</blockquote></details>

we are not really ok with it - we want to fix both.
if you have a plan on how to fix it here - add a todo.
note that we already have an option to read


<!-- Sent from Reviewable.io -->

2023-01-09 12:43 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLFj1nEimHJcktyS3X:-NLLXGDX8lb2FjPwyN-I:b-mgqdih) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L21)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

ctx.variables.alloc 
works

 ctx.new_var(lowered.variables[*old_var_id].ty
gives an error

--- first borrow occurs due to use of `*ctx` in closure

</blockquote></details>

MAke rename_var accept ctx as a parameter. Right now, your rename_var borrows ctx.variables. You don't use it in anymore in the body, but it's not the best pattern, since it prevents you from passing ctx to subfunction, if you wanted to split your code to functions, for example.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 504 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLL9zSk5jPHT22YtI80:-NLLY44sAc0IfnvwUttH:be4xfk8) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/mod.rs#L504)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it wouldn't automatically solve the cycle issue, as I want to inline function after inling was applied to them.
</blockquote></details>

1. Yes.
2. I don;t agree that this is what you want. IMO you want the functions before inlining. It's a lot more easier to analyze(). It prevents cycles (logical as well). It allows you to do weird inlining choices (e.g. depth 5 for all functions, so the f inlined in g might not be the same as root f).


<!-- Sent from Reviewable.io -->

2023-01-09 12:48 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 2 of 6 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLGdYADJti5jnIJ3xU:-NLLZmHq-cAsaQ8NK6WI:b-7i2q7m) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L95)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

:( I thought I fixed this. It was causing a bug in sierra....
</blockquote></details>

I don't understand how this can work. It doesn't make sense.


<!-- Sent from Reviewable.io -->

2023-01-09 13:11 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLFj1nEimHJcktyS3X:-NLLe5b7-GvS4ifrPO7X:b-qnp4zj) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L21)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

MAke rename_var accept ctx as a parameter. Right now, your rename_var borrows ctx.variables. You don't use it in anymore in the body, but it's not the best pattern, since it prevents you from passing ctx to subfunction, if you wanted to split your code to functions, for example.
</blockquote></details>

it would make it a lot more cumbersome to use in maps :(


<!-- Sent from Reviewable.io -->

2023-01-09 13:23 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 516 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLGVxGDMqj_gBrUmw8:-NLLgoZV3W47B3ZNIhVD:b8li15p) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/mod.rs#L516)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we are not really ok with it - we want to fix both.
if you have a plan on how to fix it here - add a todo.
note that we already have an option to read
</blockquote></details>

what is "an option to read"?


<!-- Sent from Reviewable.io -->

2023-01-09 13:26 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLGdYADJti5jnIJ3xU:-NLLhXHl9DH0PAvCH-da:bo374zy) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L95)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't understand how this can work. It doesn't make sense.
</blockquote></details>

can you elaborate?


<!-- Sent from Reviewable.io -->

2023-01-09 13:54 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLFj1nEimHJcktyS3X:-NLLnXSWB0Qa-kE3LF0a:b-rxn05w) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L21)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it would make it a lot more cumbersome to use in maps :(
</blockquote></details>

It would be more correct. You are borrowing ctx in this object, and it is unavailable inthe body. Which is weird IMO. also, it will make my life ahrder when changing the new_var().


<!-- Sent from Reviewable.io -->

2023-01-09 13:54 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLGdYADJti5jnIJ3xU:-NLLnq0273K5gwY9x-FL:b26le2h) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L95)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you elaborate?
</blockquote></details>

Nvm, I fixed it in my PR


<!-- Sent from Reviewable.io -->

2023-01-09 15:32 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 54 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLIxtOE3lMEMooZZmr:-NLLdo0FEpQpGP3X273T:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b30b3e4b359436a9a8a5997b33055819fc1bbfde/crates/cairo-lang-lowering/src/diagnostic.rs#L54)):*
> ```XML
> 
>             LoweringDiagnosticKind::InliningFailed { reason } => {
>                 format!("Inlining faild: {reason}")
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-01-10 17:12 UTC, orizi reviewed
> Reviewed 1 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)



<!-- Sent from Reviewable.io -->

2023-01-10 17:16 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLFj1nEimHJcktyS3X:-NLRfpg25KGvB5MWzO3P:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/inline.rs#L21)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It would be more correct. You are borrowing ctx in this object, and it is unavailable inthe body. Which is weird IMO. also, it will make my life ahrder when changing the new_var().
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 504 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLL9zSk5jPHT22YtI80:-NLRfntC8aut3dJe_wE5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/mod.rs#L504)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

1. Yes.
2. I don;t agree that this is what you want. IMO you want the functions before inlining. It's a lot more easier to analyze(). It prevents cycles (logical as well). It allows you to do weird inlining choices (e.g. depth 5 for all functions, so the f inlined in g might not be the same as root f).
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 516 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLLGVxGDMqj_gBrUmw8:-NLRfloJ7-xiQX5NMt9N:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/22f6fd4e776ace968b8bb0a90365b81182087e87/crates/cairo-lang-lowering/src/lower/mod.rs#L516)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

probably some dropped words - it is sensible for a user to try to add inline functions (unlike extern for example)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-10 19:50 UTC, orizi requested changes
> Reviewed 2 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 21 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLSDZmG17xYoIFAIZdt:-NLSDZmG17xYoIFAIZdu:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/458ce6e59a7ffbd305158e5b1f2eaa4702952dfc/crates/cairo-lang-lowering/src/lower/inline.rs#L21)):*
> ```XML
> 
> // A rewritter that inlines functions annotated with #[inline].
> pub struct FunctionInlinerRewritter<'db> {
> ```





_Suggestion:_
```XML
// A rewriter that inlines functions annotated with #[inline].
pub struct FunctionInlinerRewriter<'db> {
```


<!-- Sent from Reviewable.io -->

2023-01-11 12:58 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 21 at r6](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLSDZmG17xYoIFAIZdt:-NLVCe9x-yr9NOgZ1NNQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/458ce6e59a7ffbd305158e5b1f2eaa4702952dfc/crates/cairo-lang-lowering/src/lower/inline.rs#L21)):*
> ```XML
> 
> // A rewritter that inlines functions annotated with #[inline].
> pub struct FunctionInlinerRewritter<'db> {
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-01-11 13:19 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 19 at r8](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLVyxvmCiFXBdrCoIW6:-NLVyxvmCiFXBdrCoIW7:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/dd391d6a1d2bb1a1f649eae17b77c2c423995764/crates/cairo-lang-lowering/src/lower/inline.rs#L19)):*
> ```XML
> };
> 
> // TODO(ilya): Add Rewritter trait.
> ```





_Suggestion:_
```XML
// TODO(ilya): Add Rewriter trait.

// A rewriter that inlines functions annotated with #[inline].
pub struct FunctionInlinerRewriter<'db> {
    // The LoweringContext were we are building the new blocks.
    ctx: LoweringContext<'db>,
}
```


<!-- Sent from Reviewable.io -->

2023-01-11 13:50 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 19 at r8](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLVyxvmCiFXBdrCoIW6:-NLW53Te-H4id6XPmxG6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dd391d6a1d2bb1a1f649eae17b77c2c423995764/crates/cairo-lang-lowering/src/lower/inline.rs#L19)):*
> ```XML
> };
> 
> // TODO(ilya): Add Rewritter trait.
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-01-12 11:21 UTC, orizi reviewed
> Reviewed 2 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)



<!-- Sent from Reviewable.io -->

2023-01-13 20:35 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 4 files at r7, 5 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702#-:-NLgq5mY9h_0vKXb-XvH:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)



<!-- Sent from Reviewable.io -->

2023-01-15 07:29 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 62 at r12](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLoJssbEQqNQz3FrZly:-NLoJssbEQqNQz3FrZlz:bkffswq) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac4932e2f57bb5d864f2e6dc95def3184c19ea6/crates/cairo-lang-lowering/src/lower/inline.rs#L62)):*
> ```XML
>     }
> 
>     /// Inlines a function and returns the StructuredBlock that needs to be called.
> ```

BlockId to the StructuredBlock?
___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 70 at r12](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLoK8mNDnpEQ32uX2Sv:-NLoK8mNDnpEQ32uX2Sw:b-aw26pm) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac4932e2f57bb5d864f2e6dc95def3184c19ea6/crates/cairo-lang-lowering/src/lower/inline.rs#L70)):*
> ```XML
>         let root_block_id = lowered.root?;
> 
>         if !lowered.blocks[root_block_id].initial_refs.is_empty() {
> ```

1. Why don't we support this?
2. This check isn't equivalent to "no ref arguments"
3. arguments -> params
4. initial_regs includes implicits. We don't support that too?


<!-- Sent from Reviewable.io -->

2023-01-15 07:36 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 70 at r12](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLoK8mNDnpEQ32uX2Sv:-NLoLbWZ898QfSO25oE-:brgawes) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac4932e2f57bb5d864f2e6dc95def3184c19ea6/crates/cairo-lang-lowering/src/lower/inline.rs#L70)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

1. Why don't we support this?
2. This check isn't equivalent to "no ref arguments"
3. arguments -> params
4. initial_regs includes implicits. We don't support that too?
</blockquote></details>

1. it would make the PR larger.
2. why not?
3. ok
4.  in this PR we don't support that.


<!-- Sent from Reviewable.io -->

2023-01-15 07:37 UTC, spapinistarkware requested changes
> Reviewed 1 of 4 files at r7, 1 of 5 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/test.rs` line 78 at r12](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLoMAek7C6oXcJOOcB2:-NLoMAek7C6oXcJOOcB3:b-mzn9a) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac4932e2f57bb5d864f2e6dc95def3184c19ea6/crates/cairo-lang-lowering/src/test.rs#L78)):*
> ```XML
> }
> 
> fn test_function_inlining(
> ```

Shouldn't this test sit in another rust file, maybe under the inline module? inline_test.rs?
___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 85 at r12](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLoKVRu31l6Z8nSIrWx:-NLoKVRu31l6Z8nSIrWy:b-5xn5xa) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac4932e2f57bb5d864f2e6dc95def3184c19ea6/crates/cairo-lang-lowering/src/lower/inline.rs#L85)):*
> ```XML
>             let mut statements = vec![];
> 
>             let new_block = {
> ```

Why all this code is inside the code block? Can you move it outisde?
___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 108 at r12](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLoKug13wltYAhLHJzL:-NLoKug13wltYAhLHJzM:b-cs7jng) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac4932e2f57bb5d864f2e6dc95def3184c19ea6/crates/cairo-lang-lowering/src/lower/inline.rs#L108)):*
> ```XML
>                             ));
>                         }
>                         if !refs.is_empty() {
> ```

Again, note that this includes implicits. Are we sure that's what we want?
___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 109 at r12](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLoKnwe-b1b0e5hGzC1:-NLoKnwe-b1b0e5hGzC2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac4932e2f57bb5d864f2e6dc95def3184c19ea6/crates/cairo-lang-lowering/src/lower/inline.rs#L109)):*
> ```XML
>                         }
>                         if !refs.is_empty() {
>                             panic!("Can't inline funcitons with refs.")
> ```





_Suggestion:_
```XML
functions
```
___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 190 at r12](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLoLKV1DVGsCWQeWZeX:-NLoLKV1DVGsCWQeWZeY:b-fk6r7z) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac4932e2f57bb5d864f2e6dc95def3184c19ea6/crates/cairo-lang-lowering/src/lower/inline.rs#L190)):*
> ```XML
> {
>     if !stmt.ref_updates.is_empty() {
>         panic!("Cannot inline code with ref updates.")
> ```

Is this just temporary?


<!-- Sent from Reviewable.io -->

2023-01-15 07:38 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 108 at r12](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLoKug13wltYAhLHJzL:-NLoMP-U7GgyTjq6u2jp:b2nign6) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac4932e2f57bb5d864f2e6dc95def3184c19ea6/crates/cairo-lang-lowering/src/lower/inline.rs#L108)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Again, note that this includes implicits. Are we sure that's what we want?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2023-01-15 07:39 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 190 at r12](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLoLKV1DVGsCWQeWZeX:-NLoMX9rDULdWqLQxNkr:b2nign6) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac4932e2f57bb5d864f2e6dc95def3184c19ea6/crates/cairo-lang-lowering/src/lower/inline.rs#L190)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Is this just temporary?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2023-01-15 07:39 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 70 at r12](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLoK8mNDnpEQ32uX2Sv:-NLoMKf47-bxiAafQzy7:bqt1zv2) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac4932e2f57bb5d864f2e6dc95def3184c19ea6/crates/cairo-lang-lowering/src/lower/inline.rs#L70)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

1. it would make the PR larger.
2. why not?
3. ok
4.  in this PR we don't support that.
</blockquote></details>

2. because of implicits.
3. But if it's only temporary, than np.


<!-- Sent from Reviewable.io -->

2023-01-15 07:41 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/test.rs` line 78 at r12](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLoMAek7C6oXcJOOcB2:-NLoMx7UEJvDmNdfM2YN:b-n5ksmp) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac4932e2f57bb5d864f2e6dc95def3184c19ea6/crates/cairo-lang-lowering/src/test.rs#L78)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Shouldn't this test sit in another rust file, maybe under the inline module? inline_test.rs?
</blockquote></details>

I'm hoping this could be merged with the other lowering test.


<!-- Sent from Reviewable.io -->

2023-01-15 07:45 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 62 at r12](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLoJssbEQqNQz3FrZly:-NLoNk7U3zhu9Z7KWj3K:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac4932e2f57bb5d864f2e6dc95def3184c19ea6/crates/cairo-lang-lowering/src/lower/inline.rs#L62)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

BlockId to the StructuredBlock?
</blockquote></details>

done.
___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 85 at r12](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLoKVRu31l6Z8nSIrWx:-NLoNZxR17jCLVeOkLcB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac4932e2f57bb5d864f2e6dc95def3184c19ea6/crates/cairo-lang-lowering/src/lower/inline.rs#L85)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why all this code is inside the code block? Can you move it outisde?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/inline.rs` line 109 at r12](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLoKnwe-b1b0e5hGzC1:-NLoNa-_63HimouHEWtG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac4932e2f57bb5d864f2e6dc95def3184c19ea6/crates/cairo-lang-lowering/src/lower/inline.rs#L109)):*
> ```XML
>                         }
>                         if !refs.is_empty() {
>                             panic!("Can't inline funcitons with refs.")
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-01-15 08:45 UTC, spapinistarkware reviewed
> Reviewed 1 of 3 files at r9, 2 of 5 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/test.rs` line 78 at r12](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLoMAek7C6oXcJOOcB2:-NLo_jAK-A8OasiBLZw4:bttm8yd) ([raw file](https://github.com/starkware-libs/cairo/blob/9ac4932e2f57bb5d864f2e6dc95def3184c19ea6/crates/cairo-lang-lowering/src/test.rs#L78)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm hoping this could be merged with the other lowering test.
</blockquote></details>

Right now, it's a bit confusing as this test has a different code than the other tests. One might think that it is part of the same phase.


<!-- Sent from Reviewable.io -->

2023-01-16 14:22 UTC, orizi requested changes
> Reviewed 10 of 10 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 148 at r14](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLuwf0p9fKAr94ZPuVG:-NLuwf0p9fKAr94ZPuVH:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f97e724d5dc31a2590181d9f82378b0a9a9e1e6f/crates/cairo-lang-lowering/src/inline/mod.rs#L148)):*
> ```XML
> pub struct FunctionInlinerRewriter<'db> {
>     // The LoweringContext were we are building the new blocks.
>     ctx: LoweringContext<'db>,
> ```





_Suggestion:_
```XML
/// A rewriter that inlines functions annotated with #[inline].
pub struct FunctionInlinerRewriter<'db> {
    /// The LoweringContext were we are building the new blocks.
    ctx: LoweringContext<'db>,

    /// A Queue of structured blocks on which we want to apply the FunctionInlinerRewriter.
    block_queue: VecDeque<FlatBlock>,

    flat_blocks: FlatBlocks,
}
```


<!-- Sent from Reviewable.io -->

2023-01-16 14:29 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 203 at r14](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLuy_Tz55SgjE-baYfT:-NLuy_U-3w4Ut7hx3fSm:b-8m8yee) ([raw file](https://github.com/starkware-libs/cairo/blob/f97e724d5dc31a2590181d9f82378b0a9a9e1e6f/crates/cairo-lang-lowering/src/inline/mod.rs#L203)):*
> ```XML
>             lowered.blocks[root_block_id].inputs.iter().cloned(),
>             inputs.iter().cloned()
>         ));
> ```

@spapinistarkware 
is it ok to make different variable
in    lowered.blocks[root_block_id].inputs to the same variable?

e.g.

 lowered.blocks[root_block_id].inputs = [1, 2]
inputs = [1,1]



_Code quote:_
```XML
        // The input variables need to be renamed to match the inputs to the function call.
        let mut renamed_vars = HashMap::<VariableId, VariableId>::from_iter(izip!(
            lowered.blocks[root_block_id].inputs.iter().cloned(),
            inputs.iter().cloned()
        ));
```


<!-- Sent from Reviewable.io -->

2023-01-17 05:46 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 148 at r14](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLuwf0p9fKAr94ZPuVG:-NLyEEPVEZgEfuRaSuv5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f97e724d5dc31a2590181d9f82378b0a9a9e1e6f/crates/cairo-lang-lowering/src/inline/mod.rs#L148)):*
> ```XML
> pub struct FunctionInlinerRewriter<'db> {
>     // The LoweringContext were we are building the new blocks.
>     ctx: LoweringContext<'db>,
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-01-17 07:24 UTC, orizi approved these changes
> Reviewed 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)



<!-- Sent from Reviewable.io -->

2023-01-17 08:35 UTC, spapinistarkware requested changes
> Reviewed 1 of 10 files at r14.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: all files reviewed, 8 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 149 at r15](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLymiO138FWscRu1nsA:-NLymiO138FWscRu1nsB:b-nn8jut) ([raw file](https://github.com/starkware-libs/cairo/blob/fd3c844ab89e0bb59b6a1ab49124c4f451816052/crates/cairo-lang-lowering/src/inline/mod.rs#L149)):*
> ```XML
>     /// The LoweringContext were we are building the new blocks.
>     ctx: LoweringContext<'db>,
> ```

Remove empty lines here
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 177 at r15](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLyn4vt8Ri8IL1rVwWK:-NLyn4vt8Ri8IL1rVwWL:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fd3c844ab89e0bb59b6a1ab49124c4f451816052/crates/cairo-lang-lowering/src/inline/mod.rs#L177)):*
> ```XML
>     }
> 
>     /// Enqueue the block for processing and return the block_id that this
> ```





_Suggestion:_
```XML
Enqueues
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 177 at r15](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLyn7SSE5CI1KuZ-kC7:-NLyn7SSE5CI1KuZ-kC8:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fd3c844ab89e0bb59b6a1ab49124c4f451816052/crates/cairo-lang-lowering/src/inline/mod.rs#L177)):*
> ```XML
>     }
> 
>     /// Enqueue the block for processing and return the block_id that this
> ```





_Suggestion:_
```XML
returns
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 233 at r15](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLyoefO2rkI76jsg_20:-NLyoefO2rkI76jsg_21:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fd3c844ab89e0bb59b6a1ab49124c4f451816052/crates/cairo-lang-lowering/src/inline/mod.rs#L233)):*
> ```XML
>             let inputs = if block_id == root_block_id {
>                 // If this is the root block we need to delete the inputs as they are
>                 // taken from the caller rather then created in this block.
> ```





_Suggestion:_
```XML
than
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 246 at r15](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLypJURCqUgdqHX90QD:-NLypJURCqUgdqHX90QE:buomwgm) ([raw file](https://github.com/starkware-libs/cairo/blob/fd3c844ab89e0bb59b6a1ab49124c4f451816052/crates/cairo-lang-lowering/src/inline/mod.rs#L246)):*
> ```XML
>     }
> 
>     fn apply(
> ```

MAke this the first function in the impl



_Code quote:_
```XML
fn apply(
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 252 at r15](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLyrS320y9kb7c2QT9C:-NLyrS320y9kb7c2QT9D:b-xkx9xv) ([raw file](https://github.com/starkware-libs/cairo/blob/fd3c844ab89e0bb59b6a1ab49124c4f451816052/crates/cairo-lang-lowering/src/inline/mod.rs#L252)):*
> ```XML
>         let orig_root = flat_lower.root?;
>         let mut rewriter = Self {
>             ctx: lowering_info.ctx()?,
> ```

It's weird passing the builder to apply() and building here.
Can you build outside and pass ctx?



_Code quote:_
```XML
lowering_info.ctx()
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 289 at r15](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLyp8gd04bjtcYFFQXa:-NLyp8gd04bjtcYFFQXb:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fd3c844ab89e0bb59b6a1ab49124c4f451816052/crates/cairo-lang-lowering/src/inline/mod.rs#L289)):*
> ```XML
>     flat_lower: &FlatLowered,
> ) -> Maybe<FlatLowered> {
>     let lowering_info = LoweringContextBuilder::new(db, function_id)?;
> ```





_Suggestion:_
```XML
lowering_builder
```


<!-- Sent from Reviewable.io -->

2023-01-17 09:00 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 203 at r14](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLuy_Tz55SgjE-baYfT:-NLyxHfS0ahbIo6IKUQc:b2nhswy) ([raw file](https://github.com/starkware-libs/cairo/blob/f97e724d5dc31a2590181d9f82378b0a9a9e1e6f/crates/cairo-lang-lowering/src/inline/mod.rs#L203)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

@spapinistarkware 
is it ok to make different variable
in    lowered.blocks[root_block_id].inputs to the same variable?

e.g.

 lowered.blocks[root_block_id].inputs = [1, 2]
inputs = [1,1]

</blockquote></details>

Yes


<!-- Sent from Reviewable.io -->

2023-01-17 09:00 UTC, spapinistarkware reviewed
> Reviewed 6 of 10 files at r14, 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2023-01-17 09:05 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 149 at r15](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLymiO138FWscRu1nsA:-NLyxbYy9l7FJwMIgWro:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/fd3c844ab89e0bb59b6a1ab49124c4f451816052/crates/cairo-lang-lowering/src/inline/mod.rs#L149)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Remove empty lines here
</blockquote></details>

done



_Code quote:_
```XML
ingContext<'db>
```
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 177 at r15](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLyn4vt8Ri8IL1rVwWK:-NLyy3Y6AB_AuB8oAL00:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/fd3c844ab89e0bb59b6a1ab49124c4f451816052/crates/cairo-lang-lowering/src/inline/mod.rs#L177)):*
> ```XML
>     }
> 
>     /// Enqueue the block for processing and return the block_id that this
> ```

done
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 177 at r15](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLyn7SSE5CI1KuZ-kC7:-NLyy6d8EPmE1w_EWWDb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fd3c844ab89e0bb59b6a1ab49124c4f451816052/crates/cairo-lang-lowering/src/inline/mod.rs#L177)):*
> ```XML
>     }
> 
>     /// Enqueue the block for processing and return the block_id that this
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 252 at r15](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLyrS320y9kb7c2QT9C:-NLyyDP-30Kf98RU6OwY:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/fd3c844ab89e0bb59b6a1ab49124c4f451816052/crates/cairo-lang-lowering/src/inline/mod.rs#L252)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It's weird passing the builder to apply() and building here.
Can you build outside and pass ctx?
</blockquote></details>

done.
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 289 at r15](https://reviewable.io/reviews/starkware-libs/cairo/1702#-NLyp8gd04bjtcYFFQXa:-NLyyJMd72iZFAXDRkeQ:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/fd3c844ab89e0bb59b6a1ab49124c4f451816052/crates/cairo-lang-lowering/src/inline/mod.rs#L289)):*
> ```XML
>     flat_lower: &FlatLowered,
> ) -> Maybe<FlatLowered> {
>     let lowering_info = LoweringContextBuilder::new(db, function_id)?;
> ```

done.



_Code quote:_
```XML
    let lowering_info = LoweringContextBuilder::new(db, function_id)?;
```


<!-- Sent from Reviewable.io -->

2023-01-17 09:08 UTC, spapinistarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1702#-:-NLyz2riEmTqPl8Xw3P0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2023-01-17 09:10 UTC, merged