Remove borrow checking from main lowering phase
starkware-libs/cairo pull request #1740
Opened 2023-01-11 15:05 UTC by spapinistarkware

2023-01-12 08:19 UTC, orizi requested changes
> Reviewed 53 of 53 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1740)* status: all files reviewed, 17 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLWdwXh85WTXMh3UQDY:-NLWdwXh85WTXMh3UQDZ:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/objects.rs#L74)):*
> ```XML
> 
> #[derive(Clone, Debug, Default, PartialEq, Eq)]
> pub struct Remapping {
> ```

doc



_Code quote:_
```XML
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Remapping {
    pub remapping: OrderedHashMap<VariableId, VariableId>,
}
```
___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLWe5Sh5L2b6wndIPxF:-NLWe5Si7xoCxBI8QNoV:b4ujw6o) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/context.rs#L182)):*
> ```XML
>         scope: &mut BlockScope,
>     ) -> LoweringResult<VariableId> {
>         // TODO: Fix loweringflow error propagation from inner blocks.
> ```

assign.
also where did this error come from?



_Code quote:_
```XML
        // TODO: Fix loweringflow error propagation from inner blocks.
```
___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZuJUD4uJuLbnjwBI1:-NLZuJUD4uJuLbnjwBI2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/context.rs#L183)):*
> ```XML
>     ) -> LoweringResult<VariableId> {
>         // TODO: Fix loweringflow error propagation from inner blocks.
>         let concrete_variants = ctx.db.concrete_enum_variants(self.concrete_enum_id).unwrap();
> ```





_Suggestion:_
```XML
       let concrete_variants = ctx.db.concrete_enum_variants(self.concrete_enum_id).map_err(LoweringFlowError::Failed)?;
```
___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 243 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZubPa8W_0liD3AAJq:-NLZubPa8W_0liD3AAJr:b9iuu0j) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/context.rs#L243)):*
> ```XML
>     Return(VariableId),
> }
> impl LoweringFlowError {
> ```

make sure you use it everywhere which is required.



_Code quote:_
```XML
impl LoweringFlowError {
    pub fn unreachable(&self) -> bool {
```
___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZzNQr7ldZYU4qE2_b:-NLZzNQr7ldZYU4qE2_c:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/context.rs#L244)):*
> ```XML
> }
> impl LoweringFlowError {
>     pub fn unreachable(&self) -> bool {
> ```





_Suggestion:_
```XML
is_unreachable
```
___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZufAV-tmT4Q-WhSQD:-NLZufAV-tmT4Q-WhSQE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/context.rs#L247)):*
> ```XML
>         match self {
>             LoweringFlowError::Failed(_) => false,
>             LoweringFlowError::Unreachable => true,
> ```





_Suggestion:_
```XML
        match self {
            LoweringFlowError::Failed(_) => false,
            LoweringFlowError::Unreachable | LoweringFlowError::Panic(_) | LoweringFlowError::Return(_) => true,
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZvE70DkYWNzzoW4C_:-NLZvE70DkYWNzzoW4Ca:bo6xqqe) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/mod.rs#L54)):*
> ```XML
>         signature.params.iter().cloned().map(semantic::Variable::Param).collect();
> 
>     let implicits_ref = &implicits;
> ```

is this var required?



_Code quote:_
```XML
    let implicits_ref = &implicits;
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZvsxF9-9HRMTcoUtD:-NLZvsxF9-9HRMTcoUtE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/mod.rs#L115)):*
> ```XML
>     for (i, stmt_id) in expr_block.statements.iter().enumerate() {
>         let stmt = &ctx.function_def.statements[*stmt_id];
>         let err = if let Err(err) = lower_statement(ctx, &mut scope, stmt) {
> ```





_Suggestion:_
```XML
        let Err(err) = lower_statement(ctx, &mut scope, stmt) { err } else { continue; };
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 284 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZwOx9-bPPBWtJ5ZMD:-NLZwOxACrgL82mXs2qj:b-bmhdac) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/mod.rs#L284)):*
> ```XML
>             log::trace!("Lowering a variable: {:?}", expr.debug(&ctx.expr_formatter));
>             Ok(LoweredExpr::AtVariable(
>                 scope.get_semantic(expr.var).expect("Semantic variable not defined."),
> ```

consider adding info about why this cant happen



_Code quote:_
```XML
                scope.get_semantic(expr.var).expect("Semantic variable not defined."),
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 417 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZwdxA8zqMp8Xw7ghm:-NLZwdxA8zqMp8Xw7ghn:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/mod.rs#L417)):*
> ```XML
> 
>     let (implicit_outputs, ref_outputs, res) =
>         perform_function_call(ctx, scope, expr.function, inputs, ref_tys, expr_ty)?;
> ```





_Suggestion:_
```XML
    let (implicit_outputs, ref_outputs, res) =
        perform_function_call(ctx, scope, expr.function, inputs, ref_tys, expr.ty)?;
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 495 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZwt5qEI4YDfxQ8eYK:-NLZwt5qEI4YDfxQ8eYL:b32wk0) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/mod.rs#L495)):*
> ```XML
>             // TODO(spapini): Convert to a diagnostic.
>             let enum_pattern = extract_matches!(&arm.pattern, semantic::Pattern::EnumVariant);
>             // TODO(spapini): Convert to a diagnostic.
> ```

do



_Code quote:_
```XML
            // TODO(spapini): Convert to a diagnostic.
            let enum_pattern = extract_matches!(&arm.pattern, semantic::Pattern::EnumVariant);
            // TODO(spapini): Convert to a diagnostic.
            assert_eq!(&enum_pattern.variant, concrete_variant, "Wrong variant");
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 547 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZx1Wz6WHPwuBD0uar:-NLZx1Wz6WHPwuBD0uas:b32wk0) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/mod.rs#L547)):*
> ```XML
>                 input_tys.into_iter().map(|ty| subscope.add_input(ctx, ty)).collect();
>             // TODO(spapini): Convert to a diagnostic.
>             let enum_pattern = extract_matches!(&arm.pattern, semantic::Pattern::EnumVariant);
> ```

do



_Code quote:_
```XML
            // TODO(spapini): Convert to a diagnost [...]

2023-01-12 09:54 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1740)* status: 26 of 53 files reviewed, 17 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLWdwXh85WTXMh3UQDY:-NL_DvLPDM7o0x00xymM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/objects.rs#L74)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLWe5Sh5L2b6wndIPxF:-NL_MIJNBuNRjX1hHpME:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/context.rs#L182)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

assign.
also where did this error come from?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZuJUD4uJuLbnjwBI1:-NL_E13oC4zHgrQoQpHF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/context.rs#L183)):*
> ```XML
>     ) -> LoweringResult<VariableId> {
>         // TODO: Fix loweringflow error propagation from inner blocks.
>         let concrete_variants = ctx.db.concrete_enum_variants(self.concrete_enum_id).unwrap();
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 243 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZubPa8W_0liD3AAJq:-NL_E7434sX75HRBS3GU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/context.rs#L243)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

make sure you use it everywhere which is required.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZzNQr7ldZYU4qE2_b:-NL_E7KP-WNC0KnG5CMk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/context.rs#L244)):*
> ```XML
> }
> impl LoweringFlowError {
>     pub fn unreachable(&self) -> bool {
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZufAV-tmT4Q-WhSQD:-NL_EDQt3S04LNVXgyM6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/context.rs#L247)):*
> ```XML
>         match self {
>             LoweringFlowError::Failed(_) => false,
>             LoweringFlowError::Unreachable => true,
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZvE70DkYWNzzoW4C_:-NL_EIO13_Jc-ns6d_-_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/mod.rs#L54)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this var required?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZvsxF9-9HRMTcoUtD:-NL_EaKRE0R31wrgp9pd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/mod.rs#L115)):*
> ```XML
>     for (i, stmt_id) in expr_block.statements.iter().enumerate() {
>         let stmt = &ctx.function_def.statements[*stmt_id];
>         let err = if let Err(err) = lower_statement(ctx, &mut scope, stmt) {
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 284 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZwOx9-bPPBWtJ5ZMD:-NL_Ejyf7JX1aye49hm4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/mod.rs#L284)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider adding info about why this cant happen
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 417 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZwdxA8zqMp8Xw7ghm:-NL_Enhr5RqWLnrBX3tU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/mod.rs#L417)):*
> ```XML
> 
>     let (implicit_outputs, ref_outputs, res) =
>         perform_function_call(ctx, scope, expr.function, inputs, ref_tys, expr_ty)?;
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 495 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZwt5qEI4YDfxQ8eYK:-NL_FcBm32pBPSIDZH5n:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/mod.rs#L495)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do
</blockquote></details>

Done.



_Code quote:_
```XML
                        // This assert is ok.
                        assert_eq!(arm_inputs.len(), 1);
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 547 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZx1Wz6WHPwuBD0uar:-NL_Fi1FCIeoWw58R73k:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/mod.rs#L547)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZyIdl1EsLoJN3s19C:-NL_M1aH5RYZhYUQx6Nf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/scope.rs#L47)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc members
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 242 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZzHBC31qTy4LrRmfC:-NL_M1sO351dXxw3tpM4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/scope.rs#L242)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 300 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLZzlh1CBSCGyqExEX3:-NL_M2NHECLJyvuhTLML:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/lower/scope.rs#L300)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do or assign
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/arm_pattern_destructure` line 670 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_-Gak8iRqEadGOJGS:-NL_M78HAw8RtzAx_rev:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/test_data/arm_pattern_destructure#L670)):*
> ```
>   (v3: test::MyEnum) <- MyEnum::a(v2)
> End:
>   Callsite(v3 ->v28)
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 90 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_0375Cyy5a0NeaqOm:-NL_MHGRAEecOrD7h639:b-896fix) ([r [...]

2023-01-12 10:02 UTC, orizi reviewed
> Reviewed 7 of 27 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1740)* status: 33 of 53 files reviewed, all discussions resolved (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-01-12 12:16 UTC, yuvalsw requested changes
> Reviewed 26 of 53 files at r1, 23 of 27 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1740)* status: 52 of 53 files reviewed, 23 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/fmt.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_Krvl0qDhLJ_WNco1:-NL_Krvl0qDhLJ_WNco2:bmychaw) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/fmt.rs#L84)):*
> ```XML
>                     write!(f, " ->")?;
>                     var_b.fmt(f, ctx)?;
>                     if remapping.peek().is_some() {
> ```

same for flat below.



_Suggestion:_
```XML
                let mut remapping = remapping.remapping.iter().peekable();
                while let Some((src, dst)) = remapping.next() {
                    src.fmt(f, ctx)?;
                    write!(f, " -> ")?;
                    dst.fmt(f, ctx)?;
                    if remapping.peek().is_some() {
                        write!(f, ", ")?;
                    }
                }
                write!(f, ")")?;
                return Ok(());
```
___
*[`crates/cairo-lang-lowering/src/fmt.rs` line 160 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_L8_QDUo4ZX3NXXfY:-NL_L8_QDUo4ZX3NXXfZ:b-t05hg1) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/fmt.rs#L160)):*
> ```XML
>             FlatBlockEnd::Callsite(remapping) => {
>                 write!(f, "  Callsite(")?;
>                 let mut remapping = remapping.remapping.iter().peekable();
> ```

consider uniting with the previous fmt function



_Code quote:_
```XML
                write!(f, "  Callsite(")?;
                let mut remapping = remapping.remapping.iter().peekable();
                while let Some((var_a, var_b)) = remapping.next() {
                    var_a.fmt(f, ctx)?;
                    write!(f, " ->")?;
                    var_b.fmt(f, ctx)?;
                    if remapping.peek().is_some() {
                        write!(f, ", ")?;
                    }
                }
                write!(f, ")")?;
                return Ok(());
```
___
*[`crates/cairo-lang-lowering/src/objects.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_Hjlw6aQJWfoolqr-:-NL_Hjlw6aQJWfoolqr0:b5evftc) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/objects.rs#L74)):*
> ```XML
> 
> #[derive(Clone, Debug, Default, PartialEq, Eq)]
> pub struct Remapping {
> ```

VariableRemapping? VarRemapping?



_Code quote:_
```XML
Remapping
```
___
*[`crates/cairo-lang-lowering/src/objects.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_LVXX6lAE6paAK_wp:-NL_LVXX6lAE6paAK_wq:b33ngnq) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/objects.rs#L75)):*
> ```XML
> #[derive(Clone, Debug, Default, PartialEq, Eq)]
> pub struct Remapping {
>     pub remapping: OrderedHashMap<VariableId, VariableId>,
> ```

instead of always doing remapping.remapping.iter(), can you please impl .iter() for remapping?



_Code quote (from crates/cairo-lang-lowering/src/borrow_check/mod.rs):_
```XML
remapping.remapping.iter
```
___
*[`crates/cairo-lang-lowering/src/objects.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_KXEO8gjvYj8HQu3P:-NL_KXEO8gjvYj8HQu3Q:b-jlmcj6) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/objects.rs#L81)):*
> ```XML
> #[derive(Clone, Debug, PartialEq, Eq)]
> pub enum StructuredBlockEnd {
>     /// This block returns to the call-site, outputting variables to the call-site.
> ```

update



_Code quote:_
```XML
outputting variables to the call-site.
```
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 124 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_WB7cCNl2wUKANqdu:-NL_WB7cCNl2wUKANqdv:b-446z7o) ([raw file](https://github.com/starkware-libs/cairo/blob/d65fda95276a84eb03d1a607191be02692a300a8/crates/cairo-lang-lowering/src/lower/scope.rs#L124)):*
> ```XML
>         var: VariableId,
>     ) {
>         if self.semantics.insert(semantic_var_id, var).is_some() {
> ```

do the same for implicits



_Code quote:_
```XML
        if self.semantics.insert(semantic_var_id, var).is_some() {
            self.changed_semantic.insert(semantic_var_id);
        }
```
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 230 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_YBH2A86a8CUMmH1I:-NL_YBH2A86a8CUMmH1J:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d65fda95276a84eb03d1a607191be02692a300a8/crates/cairo-lang-lowering/src/lower/scope.rs#L230)):*
> ```XML
> 
>     /// Seals a block. This is meant to end a block when not all the information is necessarily
>     /// known yet, e.g. where is the callsite and what are the remapping we need to perform.
> ```





_Suggestion:_
```XML
 e.g. where the callsite is and what is the remapping we need to perform.
```
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 265 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_ip0x-L3WN7UV-DZQ:-NL_ip0x-L3WN7UV-DZR:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d65fda95276a84eb03d1a607191be02692a300a8/crates/cairo-lang-lowering/src/lower/scope.rs#L265)):*
> ```XML
> 
> /// Remapping of lowered variables with more semantic information regarding what is the semantic
> /// role fo the lowered variables.
> ```





_Suggestion:_
```XML
of the lowered variabl
```
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 273 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_jMFr7-F2qN2NImCJ:-NL_jMFr7-F2qN2NImCK:b-m487wv) ([raw file](https://github.com/starkware-libs/cairo/blob/d65fda95276a84eb03d1a607191be02692a300a8/crates/cairo-lang-lowering/src/lower/scope.rs#L273)):*
> ```XML
> }
> 
> /// A sealed BlockScope, ready to be merged with sibling blocks to end a the block.
> ```

rename BlockScope -> BlockBuilder?
rename BlockSealed -> SealedBlockBuilder?
Or find better names.

Also change BlockScopeEnd to something with "intention"



_Code quote:_
```XML
BlockScope
```
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 276 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_k21LA8FrztnDi7Be:-NL_k21LA8FrztnDi7Bf:b82fs3y) ([raw file](https://github.com/starkware-libs/cairo/blob/d65fda95276a84eb03d1a607191be02692a300a8/crates/cairo-lang-lowering/src/lower/scope.rs#L276)):*
> ```XML
> #[allow(clippy::large_enum_variant)]
> pub enum BlockSealed {
>     GotoCallsite { scope: BlockScope, expr: Option<VariableId> },
> ```

Doc variants.
doc why option for expr.
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 280 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_kJA59RGj9GV8KKtg:-NL_kJA59RGj9GV8KKth:b-jkqydb) ([raw file](https://github.com/starkware-libs/cairo/blob/d65fda95276a84eb03d1a607191be02692a300a8/crates/cairo-lang-lowering/src/lower/scope.rs#L280)):*
> ```XML
> }
> impl BlockSealed {
>     /// Given the extra information needed, ends a sealed block.
> ```

returns the final StructuredBlock



_Code quote:_
```XML
ends a sealed block
```
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 284 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_kUao8vu30fE83-L5:-NL_kUao8vu30fE83-L6:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d65fda95276a84eb03d1a607191be02692a300a8/crates/cairo-lang-lowering/src/lower/scope.rs#L284)):*
> ```XML
>         self,
>         ctx: &mut LoweringContext<'_>,
>         total_remapping: &SemanticRemapping,
> ```





_Sugg [...]

2023-01-12 13:03 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1740)* status: 39 of 53 files reviewed, 6 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_KXEO8gjvYj8HQu3P:-NLa35TD-jq6CUUpJupP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9e2b92151dab0e43901f0d137c8345b379ed2f8a/crates/cairo-lang-lowering/src/objects.rs#L81)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

update
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 124 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_WB7cCNl2wUKANqdu:-NL_ugMzE6Zm0qhd151H:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d65fda95276a84eb03d1a607191be02692a300a8/crates/cairo-lang-lowering/src/lower/scope.rs#L124)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

do the same for implicits
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 290 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_lzVPCOZhxSI-hbYI:-NL_wyJN--OJde5PUmCc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d65fda95276a84eb03d1a607191be02692a300a8/crates/cairo-lang-lowering/src/lower/scope.rs#L290)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

change to expect, this should not be possible after semantic phase.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 335 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_p8cl87dIK5mf6H4x:-NLa38-D-LkNBDxVe4yt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d65fda95276a84eb03d1a607191be02692a300a8/crates/cairo-lang-lowering/src/lower/scope.rs#L335)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

remove?u
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 382 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_pbDh0kFpTHZ3ek5Z:-NLa1JB_8vl0gPUF7mwt:b30kxbr) ([raw file](https://github.com/starkware-libs/cairo/blob/d65fda95276a84eb03d1a607191be02692a300a8/crates/cairo-lang-lowering/src/lower/scope.rs#L382)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

consider checking if reachables > 0 bfeore match and return early in that case
</blockquote></details>

Noted. It's not just an early return, I need to make MergedBlocks as well.
___
*[`crates/cairo-lang-sierra-generator/src/utils.rs` line 265 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_sS9t38sJE9OUapKj:-NLa1UcgAUR262ABCqlC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d65fda95276a84eb03d1a607191be02692a300a8/crates/cairo-lang-sierra-generator/src/utils.rs#L265)):*
> ```XML
> }
> 
> /// Gets the output variables from a statement call, including branching statements.
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-01-13 20:42 UTC, orizi requested changes
> Reviewed 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1740)* status: all files reviewed, 7 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLgrOra1qf-SE7U8JON:-NLgrOra1qf-SE7U8JOO:b-wkc3g0) (no related file):*
still requires an optimization to make sure we dont create worse code for now.

___
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLgqZHkCpzAzsOxRnh3:-NLgqZHl85oQaM1KzXcT:bqsp5tq) ([raw file](https://github.com/starkware-libs/cairo/blob/7f86a074e456152c2bc10bc045075f8b61d53240/crates/cairo-lang-lowering/src/lower/scope.rs#L100)):*
> ```XML
>         if let Some(old) = self.implicits.insert(ty, var) {
>             if old == var {
>                 return;
> ```

consider



_Suggestion:_
```XML
        if self.implicits.insert(ty, var) == Some(var) {
            return;
        }
```
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 126 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLgquS-33cytaBN_Jx-:-NLgquS-33cytaBN_Jx0:b-skt7ya) ([raw file](https://github.com/starkware-libs/cairo/blob/7f86a074e456152c2bc10bc045075f8b61d53240/crates/cairo-lang-lowering/src/lower/scope.rs#L126)):*
> ```XML
>         var: VariableId,
>     ) {
>         if let Some(old) = self.semantics.insert(semantic_var_id, var) {
> ```

consider again



_Suggestion:_
```XML
        if let self.semantics.insert(semantic_var_id, var) == Some(var) {
            return;
        }
```


<!-- Sent from Reviewable.io -->

2023-01-15 15:00 UTC, yuvalsw requested changes
> Reviewed 1 of 53 files at r1, 3 of 27 files at r2, 2 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1740)* status: all files reviewed, 16 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 200 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLpc8Yu4xvLJtRBUT8X:-NLpc8Yv4dQNprnQOpRc:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d65fda95276a84eb03d1a607191be02692a300a8/crates/cairo-lang-lowering/src/lower/context.rs#L200)):*
> ```XML
>                     subscope.put_implicit(ctx, *ty, var);
>                 }
>                 // Bind the ref variables.
> ```





_Suggestion:_
```XML
/ Bind the ref parameters.
```
___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLpf5lZ8HuGd5wWKQl6:-NLpf5lZ8HuGd5wWKQl7:b-ocsj1f) ([raw file](https://github.com/starkware-libs/cairo/blob/d65fda95276a84eb03d1a607191be02692a300a8/crates/cairo-lang-lowering/src/lower/context.rs#L244)):*
> ```XML
>     Failed(DiagnosticAdded),
>     /// The current computation is unreachable.
>     Unreachable,
> ```

consider renaming
___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 259 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLpfCBD4uTmj6tGCj4a:-NLpfCBD4uTmj6tGCj4b:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d65fda95276a84eb03d1a607191be02692a300a8/crates/cairo-lang-lowering/src/lower/context.rs#L259)):*
> ```XML
> }
> 
> /// Converts a lowering flow error the appropriate block scope end, if possible.
> ```





_Suggestion:_
```XML
error to the 
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLphCi23U9ZW08klibQ:-NLphCi23U9ZW08klibR:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d65fda95276a84eb03d1a607191be02692a300a8/crates/cairo-lang-lowering/src/lower/mod.rs#L55)):*
> ```XML
>         signature.params.iter().cloned().map(semantic::Variable::Param).collect();
> 
>     let lowering_info = LoweringContextBuilder::new(db, free_function_id)?;
> ```





_Suggestion:_
```XML
lowering_builder
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLpipTM3nrBclizsOo7:-NLpipTM3nrBclizsOo8:b-fn82ct) ([raw file](https://github.com/starkware-libs/cairo/blob/d65fda95276a84eb03d1a607191be02692a300a8/crates/cairo-lang-lowering/src/lower/mod.rs#L79)):*
> ```XML
>     }
>     scope.bind_refs();
>     let maybe_sealed_block = lower_block(&mut ctx, scope, semantic_block);
> ```

move into if
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 282 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLpkxX5-YlakI58_uZe:-NLpkxX5-YlakI58_uZf:b-tz5xpd) ([raw file](https://github.com/starkware-libs/cairo/blob/7f86a074e456152c2bc10bc045075f8b61d53240/crates/cairo-lang-lowering/src/lower/mod.rs#L282)):*
> ```XML
>                 scope
>                     .get_semantic(expr.var)
>                     .expect("Use of undefined variable cannot happen after semantic phase."),
> ```

consider moving into get_semantic
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 819 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLpswDXC5usgTWgnwtL:-NLpswDXC5usgTWgnwtM:bkh34ss) ([raw file](https://github.com/starkware-libs/cairo/blob/7f86a074e456152c2bc10bc045075f8b61d53240/crates/cairo-lang-lowering/src/lower/mod.rs#L819)):*
> ```XML
>     let value = subscope_ok.add_input(ctx, ok_variant.ty);
>     let sealed_block_ok = subscope_ok.goto_callsite(Some(value));
>     let merged = merge_sealed(ctx, scope, vec![sealed_block_ok]);
> ```

add err block here.



_Code quote:_
```XML
ec![sealed_block_ok]);
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 823 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLpsl9-46xkIVaLhNJW:-NLpsl9-46xkIVaLhNJX:b-mself3) ([raw file](https://github.com/starkware-libs/cairo/blob/7f86a074e456152c2bc10bc045075f8b61d53240/crates/cairo-lang-lowering/src/lower/mod.rs#L823)):*
> ```XML
> 
>     let mut subscope_err = scope.subscope_with_bound_refs();
>     let value = subscope_err.add_input(ctx, err_variant.ty);
> ```

or inline



_Suggestion:_
```XML
err_value
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 871 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLpuXUj8anTOI2cpl4x:-NLpuXUj8anTOI2cpl4y:b-zvov3) ([raw file](https://github.com/starkware-libs/cairo/blob/7f86a074e456152c2bc10bc045075f8b61d53240/crates/cairo-lang-lowering/src/lower/mod.rs#L871)):*
> ```XML
>         .add(ctx, &mut subscope_err);
>     let block = subscope_err.ret(ctx, err_res).map_err(LoweringFlowError::Failed)?;
>     let block_err = ctx.blocks.alloc(block);
> ```

same - add to merge_sealed


<!-- Sent from Reviewable.io -->

2023-01-15 15:36 UTC, yuvalsw requested changes
> Reviewed 12 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1740)* status: all files reviewed, 17 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/fmt.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLpwzFm8KRfpqUuDKSv:-NLpwzFn2T23EYQ54Jt_:b-aa1sit) ([raw file](https://github.com/starkware-libs/cairo/blob/7f86a074e456152c2bc10bc045075f8b61d53240/crates/cairo-lang-lowering/src/fmt.rs#L93)):*
> ```XML
>         let outputs: Vec<VariableId> = match &self {
>             StructuredBlockEnd::Callsite(remapping) => {
>                 return write!(f, "  Callsite({:?})", remapping.debug(ctx));
> ```

2 spaces - intentional?
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 382 at r2](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NL_pbDh0kFpTHZ3ek5Z:-NLq2PZT9tcdxeG-zP15:b-67w93f) ([raw file](https://github.com/starkware-libs/cairo/blob/d65fda95276a84eb03d1a607191be02692a300a8/crates/cairo-lang-lowering/src/lower/scope.rs#L382)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Noted. It's not just an early return, I need to make MergedBlocks as well.
</blockquote></details>

I meant something like:
```
    if n_reachable_blocks == 0 {
        return MergedBlocks { expr: Err(LoweringFlowError::Unreachable), blocks: Vec![] };
    }
    let expr = Ok(match semantic_remapping.expr {
        Some(var) => LoweredExpr::AtVariable(var),
        None => LoweredExpr::Tuple(vec![]),
    });
    MergedBlocks { expr, blocks }

```
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 103 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLpzcPa-0k_MHOOq_Nl:-NLpzcPa-0k_MHOOq_Nm:b-kkps3v) ([raw file](https://github.com/starkware-libs/cairo/blob/7f86a074e456152c2bc10bc045075f8b61d53240/crates/cairo-lang-lowering/src/lower/scope.rs#L103)):*
> ```XML
>             }
>         }
>         self.changed_implicits.insert(ty);
> ```

same as below - this should be inside the if.
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 131 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLpyXuA943yLxzRusUB:-NLpyXuA943yLxzRusUC:bpujnxl) ([raw file](https://github.com/starkware-libs/cairo/blob/7f86a074e456152c2bc10bc045075f8b61d53240/crates/cairo-lang-lowering/src/lower/scope.rs#L131)):*
> ```XML
>             }
>         }
>         self.changed_semantic.insert(semantic_var_id);
> ```

this should go into the if. Otherwise it happens even when insert didn't return some.
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 262 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLpzvf337pVd_cY2u2w:-NLpzvf47oPpeYeXeNP1:buvfsa7) ([raw file](https://github.com/starkware-libs/cairo/blob/7f86a074e456152c2bc10bc045075f8b61d53240/crates/cairo-lang-lowering/src/lower/scope.rs#L262)):*
> ```XML
> /// Describes how a block ends, with possibly partial information regarding callsite and remapping.
> /// Used for sealing a block.
> pub enum BlockEndIntent {
> ```

please explain in the comment what "intent" means here and how it is different than the final/actual block end



_Code quote:_
```XML
Intent
```
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 278 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLq-BoR4y1hja7h098X:-NLq-BoR4y1hja7h098Y:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7f86a074e456152c2bc10bc045075f8b61d53240/crates/cairo-lang-lowering/src/lower/scope.rs#L278)):*
> ```XML
> }
> 
> /// A sealed BlockBuilder, ready to be merged with sibling blocks to end a the block.
> ```





_Suggestion:_
```XML
o end the block.
```
___
*[`crates/cairo-lang-lowering/src/lower/scope.rs` line 337 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLq0D3Z3uu14s6HWids:-NLq0D3Z3uu14s6HWidt:b-yftv3d) ([raw file](https://github.com/starkware-libs/cairo/blob/7f86a074e456152c2bc10bc045075f8b61d53240/crates/cairo-lang-lowering/src/lower/scope.rs#L337)):*
> ```XML
> 
>     // Remap Variables from all blocks.
>     for sealed_subblock in &sealed_blocks {
> ```

either
sealed_subblock and sealed_subblocks,
or
sealed_block and sealed_blocks



_Code quote:_
```XML
sealed_subblock in &sealed_blocks
```


<!-- Sent from Reviewable.io -->

2023-01-15 15:39 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1740)* status: all files reviewed, 18 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 394 at r3](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLq3zzE9HJdFuFLm9a2:-NLq3zzE9HJdFuFLm9a3:ba8jee5) ([raw file](https://github.com/starkware-libs/cairo/blob/7f86a074e456152c2bc10bc045075f8b61d53240/crates/cairo-lang-lowering/src/lower/mod.rs#L394)):*
> ```XML
>                     // TODO(yuval): This is a temporary measure as there is a problem when a match
>                     // arm returns(moves) a variable that was passed to the
>                     // libfunc call in the match as a reference. To fix it, we
> ```

Try removing this and see if the relevant test cases are now optimized without errors.
"Test match on libfunc call that uses the refs of the libfunc in one of the arms."
"Test extern function enum calling without optimization (no optimization with ref params)."
If so - workaround can be removed (in a separate PR, but worth already knowing if this works or not).



_Code quote:_
```XML
            if let Ok(refs) = ctx.db.extern_function_declaration_refs(extern_function_id) {
                if !refs.is_empty() {
                    // Don't optimize in case the extern function has ref parameters.
                    //
                    // TODO(yuval): This is a temporary measure as there is a problem when a match
                    // arm returns(moves) a variable that was passed to the
                    // libfunc call in the match as a reference. To fix it, we
                    // need: to ensure that if one arm uses a variable, all arms either use it or
                    // drop it (all refs must be passed to all arms as inputs). Then, if a var that
                    // was passed to the libfunc as a ref parameter is returned by one of the arms,
                    // it must be rebound to do that (today it is returned as the same var id).
                    return Ok(LoweredExpr::AtVariable(lowered_expr.var(ctx, scope)?));
                }
            }
```


<!-- Sent from Reviewable.io -->

2023-01-16 14:07 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 12 of 21 files at r4, 22 of 22 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1740#-:-NLuttLZ4Y7RCWfLNKeE:bnfp4nl)* status: all files reviewed, 9 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-01-16 14:35 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1740)* status: 53 of 54 files reviewed, 9 unresolved discussions (waiting on @orizi and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLgrOra1qf-SE7U8JON:-NLv-OuFDjN9EzlSKATq:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

still requires an optimization to make sure we dont create worse code for now.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2023-01-16 14:36 UTC, spapinistarkware reviewed
> Reviewed 4 of 53 files at r1, 12 of 27 files at r2, 3 of 14 files at r3, 12 of 21 files at r4, 6 of 22 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1740)* status: all files reviewed, 9 unresolved discussions (waiting on @orizi and @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-01-17 09:15 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1740)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/objects.rs` line 76 at r7](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLvAb_T7ABO-b5b_Msl:-NLz-2JfDxrhQlGLhImV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d4c5bb7ccb098409ee037cf24d229f9bd607fcd5/crates/cairo-lang-lowering/src/objects.rs#L76)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think this is less intuitive.
You could have OrderedHashMap<VariableId, Vec<VariableId>>  from old_var to multiple new_vars.

If you insist for some reason to keep it that way, fix the comment as it says "to new ids".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-17 09:19 UTC, orizi approved these changes
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1740)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-01-17 09:50 UTC, orizi approved these changes
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1740)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-01-17 10:01 UTC, yuvalsw approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 4 files at r8, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1740#-:-NLzABS80YArLmF7OLjV:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 222 at r9](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLz9YO99Sw__ZhU4fmj:-NLz9YO99Sw__ZhU4fmk:b66vgt8) ([raw file](https://github.com/starkware-libs/cairo/blob/1b299f9a2f165105bdcf2b225b468b5fde2336d7/crates/cairo-lang-lowering/src/inline/mod.rs#L222)):*
> ```XML
>         function_id: FunctionWithBodyId,
>         inputs: &[VariableId],
>         outputs: &[VariableId],
> ```

update comment accordingly
___
*[`crates/cairo-lang-lowering/src/test_data/tests` line 417 at r9](https://reviewable.io/reviews/starkware-libs/cairo/1740#-NLzA0Br4BWlyWYYZVFE:-NLzA0Br4BWlyWYYZVFF:bc9wxij) ([raw file](https://github.com/starkware-libs/cairo/blob/1b299f9a2f165105bdcf2b225b468b5fde2336d7/crates/cairo-lang-lowering/src/test_data/tests#L417)):*
> ```
> //! > ==========================================================================
> 
> //! > Test passing same argument as two ref params. TODO(spapini): Make this a semantic diagnostic.
> ```

this is part of the test name now. Move to a comments section


<!-- Sent from Reviewable.io -->

2023-01-17 10:13 UTC, orizi approved these changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1740)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)



<!-- Sent from Reviewable.io -->

2023-01-17 10:14 UTC, spapinistarkware reviewed
> Reviewed 16 of 22 files at r6, 3 of 4 files at r8, 2 of 4 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1740)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)



<!-- Sent from Reviewable.io -->

2023-01-17 10:14 UTC, merged

2023-01-17 10:15 UTC, yuvalsw reviewed
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/1740)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->