Maciektr/formatter
starkware-libs/cairo pull request #2008
Opened 2023-01-31 23:09 UTC by maciektr

2023-02-06 09:18 UTC, mkaput requested changes
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2008)* status: 5 of 7 files reviewed, 12 unresolved discussions (waiting on @gilbens-starkware, @maciektr, and @spapinistarkware)

___
*[`crates/cairo-lang-formatter/Cargo.toml` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_mBOt4V3o0AVhcY2B:-NN_mBOt4V3o0AVhcY2C:b8ro1vy) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/Cargo.toml#L27)):*
> ```TOML
> cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "1.0.0-alpha.2" }
> cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.0.0-alpha.2" }
> ignore = "0.4.20"
> ```

Please declare `ignore` version in workspace `Cargo.toml`, and only use this form in crates manifests:



_Suggestion:_
```TOML
ignore.workspace = true
```
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_o9Yg48G0Txuyd_N_:-NN_o9Yg48G0Txuyd_Na:b-2a7l9u) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L17)):*
> ```XML
> use crate::{get_formatted_file, FormatterConfig};
> 
> const CAIRO_FILE_EXTENSION: &str = "cairo";
> ```

Sounds like a good candidate to make `pub` in `cairo_lang_filesystem` what do you think @spapinistarkware ?
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_oPmf9SRf-LJM8HfT:-NN_oPmf9SRf-LJM8HfU:br4qlc5) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L18)):*
> ```XML
> 
> const CAIRO_FILE_EXTENSION: &str = "cairo";
> const CAIRO_FILE_GLOB: &str = "*.cairo";
> ```

could we replace this constant with a call to `format!("*.{CAIRO_FILE_EXTENSION}")`?



_Code quote:_
```XML
CAIRO_FILE_GLOB
```
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_oGL05Jr5l9YDcwAm:-NN_oGL05Jr5l9YDcwAn:b4mhaek) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L19)):*
> ```XML
> const CAIRO_FILE_EXTENSION: &str = "cairo";
> const CAIRO_FILE_GLOB: &str = "*.cairo";
> const CAIRO_FMT_IGNORE: &str = ".cairofmtignore";
> ```

I think this could be `pub` from `lib.rs` of this crate?
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_tQoO5rl1x-Hq5vFl:-NN_tQoP1SdDyzrNCT3C:b-vwji6i) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L26)):*
> ```XML
> }
> 
> fn write_diff(diff: &FileDiff, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
> ```

It is common to put `use std::fmt`:



_Suggestion:_
```XML
fn write_diff(diff: &FileDiff, f: &mut fmt::Formatter<'_>) -> fmt::Result {
```
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_uokSArCLVCP4VwqD:-NN_uokSArCLVCP4VwqE:b-v3lfdl) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L26)):*
> ```XML
> }
> 
> fn write_diff(diff: &FileDiff, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
> ```

I rather would inline `write_diff` into `impl Display` and use following `impl Debug`:
```rust
write!(f, "FileDiff(\n")?;
Display::fmt(self, f)?;
write!(f, ")")?;
Ok(())
```
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_uYzzEBUo_fyHapvb:-NN_uZ--5U_4rr2wGIFV:b4hxj2o) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L52)):*
> ```XML
> 
> #[derive(Debug)]
> pub enum FormatResult {
> ```

`Result` is a little misleading, it sounds like this is `Result<T>`. Maybe let's call this `FormatOutcome` ?
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_wV1C2ooZYnGcm46J:-NN_wV1C2ooZYnGcm46K:b-ojygxb) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L60)):*
> ```XML
> 
> pub trait FormattableInput {
>     fn to_file_id(&self, db: &dyn FilesGroup) -> Result<FileId>;
> ```

This looks to never fail?
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_tD_p07korsIa6R1v:-NN_tD_p07korsIa6R1w:b-tva54s) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L61)):*
> ```XML
> pub trait FormattableInput {
>     fn to_file_id(&self, db: &dyn FilesGroup) -> Result<FileId>;
>     fn overwrite_content(&self, _content: String) -> Result<()> {
> ```

I'm not sure not doing anything is a sane default?



_Suggestion:_
```XML
    fn overwrite_content(&self, _content: String) -> Result<()>;
```
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_w_ZHANRRkQb2npXM:-NN_w_ZHANRRkQb2npXN:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L118)):*
> ```XML
>             bail!("Unable to read from input.");
>         }
>     };
> ```





_Suggestion:_
```XML
    let original_text = db.file_content(file_id).context("Unable to read from input.")?;
```
___
*[`crates/cairo-lang-formatter/src/lib.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_szJx1iG_ttO7Cc7Q:-NN_szJx1iG_ttO7Cc7R:bsnm997) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/lib.rs#L17)):*
> ```XML
> 
> pub use crate::cairo_formatter::{CairoFormatter, FormatResult, StdinFmt};
> use crate::formatter::Formatter;
> ```

Hmm, it's now pretty ambiguous what CairoFormatter is and what Formatter is. Perhaps `Formatter` could be renamed to `FormatterImpl`? It looks to be private thingy



_Code quote:_
```XML
pub use crate::cairo_formatter::{CairoFormatter, FormatResult, StdinFmt};
use crate::formatter::Formatter;
```
___
*[`crates/cairo-lang-formatter/src/bin/cli.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_txUJ96Jqq7m4FiYD:-NN_txUJ96Jqq7m4FiYE:by6jlhu) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/bin/cli.rs#L171)):*
> ```XML
>     );
> 
>     let mut all_correct = true;
> ```

It would be more idiomatic to write

```rust
let all_correct = if args.files.len() == 1 && args.files[0] == "-" {
```


<!-- Sent from Reviewable.io -->

2023-02-06 09:22 UTC, mkaput requested changes
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2008)* status: all files reviewed, 14 unresolved discussions (waiting on @gilbens-starkware, @maciektr, and @spapinistarkware)

___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NNa0dr3C7Wle11wClGn:-NNa0dr3C7Wle11wClGo:b-jorhi8) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L133)):*
> ```XML
> }
> 
> pub struct CairoFormatter {
> ```

derive Debug?
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NNa0R5361xdBhIZR1b3:-NNa0R5361xdBhIZR1b4:b4wm5s8) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L173)):*
> ```XML
>     pub fn format_in_place(&self, input: &dyn FormattableInput) -> Result<FormatResult> {
>         match format_input(input, &self.formatter_config)? {
>             (FormatResult::DiffFound, FormattedFileContent::Changed(diff)) => {
> ```

Why do you need separate FormatResult and content enums? Couldn't these two be just merged?


<!-- Sent from Reviewable.io -->

2023-02-06 09:48 UTC, maciektr reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2008)* status: all files reviewed, 13 unresolved discussions (waiting on @gilbens-starkware, @mkaput, and @spapinistarkware)

___
*[`crates/cairo-lang-formatter/Cargo.toml` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_mBOt4V3o0AVhcY2B:-NNa1MdBEY9v2qqiFMuG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/Cargo.toml#L27)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Please declare `ignore` version in workspace `Cargo.toml`, and only use this form in crates manifests:
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_oPmf9SRf-LJM8HfT:-NNa1Y4I38wghJ0XFjbW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L18)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

could we replace this constant with a call to `format!("*.{CAIRO_FILE_EXTENSION}")`?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_tQoO5rl1x-Hq5vFl:-NNa21NEA5xmFjaj1yHs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L26)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

It is common to put `use std::fmt`:
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_uokSArCLVCP4VwqD:-NNa21dcEyOQjtNUn90W:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L26)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I rather would inline `write_diff` into `impl Display` and use following `impl Debug`:
```rust
write!(f, "FileDiff(\n")?;
Display::fmt(self, f)?;
write!(f, ")")?;
Ok(())
```
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_uYzzEBUo_fyHapvb:-NNa29Bf5WzxW1YQ5rL4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L52)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

`Result` is a little misleading, it sounds like this is `Result<T>`. Maybe let's call this `FormatOutcome` ?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_tD_p07korsIa6R1v:-NNa6dAT2cFa8iLm4-Tf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L61)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I'm not sure not doing anything is a sane default?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NNa0dr3C7Wle11wClGn:-NNa2h4KEyFd6hn4X7E5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L133)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

derive Debug?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/bin/cli.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_txUJ96Jqq7m4FiYD:-NNa3r0t-SedtphDbMgH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/bin/cli.rs#L171)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

It would be more idiomatic to write

```rust
let all_correct = if args.files.len() == 1 && args.files[0] == "-" {
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-06 09:58 UTC, mkaput reviewed
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2008)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware, @maciektr, and @spapinistarkware)

___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 146 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NNa8xwj0GMBCULoBozi:-NNa8xwj0GMBCULoBozj:b9m92i7) ([raw file](https://github.com/starkware-libs/cairo/blob/8b07f1e22491f2e382f9fb54253fcffb15e5ff5b/crates/cairo-lang-formatter/src/cairo_formatter.rs#L146)):*
> ```XML
>         let mut types_builder = TypesBuilder::new();
>         types_builder
>             .add(CAIRO_FILE_EXTENSION, format!("*.{CAIRO_FILE_EXTENSION}").as_str())
> ```

doesn't this work?



_Suggestion:_
```XML
&format!("*.{CAIRO_FILE_EXTENSION}")
```


<!-- Sent from Reviewable.io -->

2023-02-06 10:27 UTC, maciektr reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2008)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware, @mkaput, and @spapinistarkware)

___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NNa0R5361xdBhIZR1b3:-NNaG4Ob8otG8GsSP3sf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L173)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Why do you need separate FormatResult and content enums? Couldn't these two be just merged?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-06 10:45 UTC, maciektr commented
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_wV1C2ooZYnGcm46J:-NNaHsEg6WbcBNItNQpC:bkdf1bo) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L60)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

This looks to never fail?
</blockquote></details>

https://github.com/starkware-libs/cairo/blob/3948b37a90884ca6b54a98a8f5291a394e54b264/crates/cairo-lang-formatter/src/cairo_formatter.rs#L83


<!-- Sent from Reviewable.io -->

2023-02-07 07:57 UTC, mkaput requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2008)* status: all files reviewed, 3 unresolved discussions (waiting on @maciektr)

___
*[`crates/cairo-lang-formatter/src/bin/cli.rs` line 147 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NNergL8B5V0zsJCxgLI:-NNergL8B5V0zsJCxgLJ:b-4qz8a4) ([raw file](https://github.com/starkware-libs/cairo/blob/d8b1a8fb663e4d1ca1b41c12d70ca7a49bd2ce5e/crates/cairo-lang-formatter/src/bin/cli.rs#L147)):*
> ```XML
>         match fmt.format_to_string(&StdinFmt) {
>             Ok((_, text)) => {
>                 println!("{text}");
> ```

You can add a method `FormatOutcome::into_output_text(self)` and thus avoid returning tuples from `fmt.format_to_string` and cloning outcome internals within them



_Code quote:_
```XML
        match fmt.format_to_string(&StdinFmt) {
            Ok((_, text)) => {
                println!("{text}");
```


<!-- Sent from Reviewable.io -->

2023-02-08 08:22 UTC, mkaput reviewed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2008)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr)



<!-- Sent from Reviewable.io -->

2023-02-08 13:21 UTC, maciektr commented
*[`crates/cairo-lang-formatter/src/lib.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_szJx1iG_ttO7Cc7Q:-NNlAmjADq6NBG7Z9qd5:b-i9stdt) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/lib.rs#L17)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Hmm, it's now pretty ambiguous what CairoFormatter is and what Formatter is. Perhaps `Formatter` could be renamed to `FormatterImpl`? It looks to be private thingy
</blockquote></details>

I do agree it is confusing, I would love to hear opinion from @gilbens-starkware or @spapinistarkware before renaming it though. 


<!-- Sent from Reviewable.io -->

2023-02-09 07:40 UTC, mkaput requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2008)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware, @maciektr, and @spapinistarkware)

___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NNp5PRh1EyGWDBoc2_k:-NNp5PRh1EyGWDBoc2_l:b-fhiefz) ([raw file](https://github.com/starkware-libs/cairo/blob/a688e6a9a4f1f5fcad866284cd10bbb8a268ecef/crates/cairo-lang-formatter/src/cairo_formatter.rs#L49)):*
> ```XML
> pub struct FileDiffColoredDisplay {
>     diff: FileDiff,
> }
> ```

I think this should take a reference to FileDiff instead of moving it in and requiring `clone` during construction.



_Suggestion:_
```XML
pub struct FileDiffColoredDisplay<'a> {
    diff: &'a FileDiff,
}
```
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 52 at r6](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NNp6LdxELnCeJoDWsYM:-NNp6LdxELnCeJoDWsYN:b-cnvqao) ([raw file](https://github.com/starkware-libs/cairo/blob/a688e6a9a4f1f5fcad866284cd10bbb8a268ecef/crates/cairo-lang-formatter/src/cairo_formatter.rs#L52)):*
> ```XML
> 
> impl FileDiffColoredDisplay {
>     pub fn new(diff: FileDiff) -> Self {
> ```

I wouldn't make this public, `FileDiff::display_colored` is, and there should be one way to get this done in the API.
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 68 at r6](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NNp67c-4rF0WBip1ZgU:-NNp67c-4rF0WBip1ZgV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a688e6a9a4f1f5fcad866284cd10bbb8a268ecef/crates/cairo-lang-formatter/src/cairo_formatter.rs#L68)):*
> ```XML
> impl Debug for FileDiffColoredDisplay {
>     fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
>         writeln!(f, "FileDiffWithColors({:?})", self.diff)
> ```





_Suggestion:_
```XML
FileDiffColoredDisplay
```


<!-- Sent from Reviewable.io -->

2023-02-09 08:24 UTC, maciektr reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2008)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware, @mkaput, and @spapinistarkware)

___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NNp5PRh1EyGWDBoc2_k:-NNpGZM-8xwCPXtoZg6b:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a688e6a9a4f1f5fcad866284cd10bbb8a268ecef/crates/cairo-lang-formatter/src/cairo_formatter.rs#L49)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I think this should take a reference to FileDiff instead of moving it in and requiring `clone` during construction.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 52 at r6](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NNp6LdxELnCeJoDWsYM:-NNpG0e5Din_uTxa41uD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a688e6a9a4f1f5fcad866284cd10bbb8a268ecef/crates/cairo-lang-formatter/src/cairo_formatter.rs#L52)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I wouldn't make this public, `FileDiff::display_colored` is, and there should be one way to get this done in the API.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 68 at r6](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NNp67c-4rF0WBip1ZgU:-NNpFzwt83Gvb7dHUskm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a688e6a9a4f1f5fcad866284cd10bbb8a268ecef/crates/cairo-lang-formatter/src/cairo_formatter.rs#L68)):*
> ```XML
> impl Debug for FileDiffColoredDisplay {
>     fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
>         writeln!(f, "FileDiffWithColors({:?})", self.diff)
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-02-09 08:37 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2008)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @mkaput)

___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_o9Yg48G0Txuyd_N_:-NNpHygT7a3LNOkhITRe:b-cstnkg) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L17)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Sounds like a good candidate to make `pub` in `cairo_lang_filesystem` what do you think @spapinistarkware ?
</blockquote></details>

I agree
___
*[`crates/cairo-lang-formatter/src/lib.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_szJx1iG_ttO7Cc7Q:-NNpIeqr9T3Lnmu1y2x0:b-vtuqu3) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/lib.rs#L17)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

I do agree it is confusing, I would love to hear opinion from @gilbens-starkware or @spapinistarkware before renaming it though. 
</blockquote></details>

How about `Formatter -> SyntaxFormatter`?


<!-- Sent from Reviewable.io -->

2023-02-09 08:59 UTC, mkaput requested changes
> Reviewed 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2008)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @maciektr)

___
*[`crates/cairo-lang-formatter/src/lib.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_szJx1iG_ttO7Cc7Q:-NNpOWfqBu5zguC30jHC:b-oxyohd) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/lib.rs#L17)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

How about `Formatter -> SyntaxFormatter`?
</blockquote></details>

I'm not sure, `Syntax` word does not bring any specific meaning instead of resolving ambiguities in naming :/
___
*[`crates/cairo-lang-formatter/src/bin/cli.rs` line 54 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NNpOOY23dag2lUvTJ-r:-NNpOOY23dag2lUvTJ-s:b-haymqu) ([raw file](https://github.com/starkware-libs/cairo/blob/383d021e0b0844078d2d1dcf654575399ade4f31/crates/cairo-lang-formatter/src/bin/cli.rs#L54)):*
> ```XML
> }
> 
> struct PathFormatter<'t> {
> ```

This needs simplification which I have discussed with @maciektr in the office.


<!-- Sent from Reviewable.io -->

2023-02-09 09:42 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2008)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @maciektr)

___
*[`crates/cairo-lang-formatter/src/lib.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_szJx1iG_ttO7Cc7Q:-NNpYPFN81t2pGVskVvx:b-wueu9u) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/lib.rs#L17)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I'm not sure, `Syntax` word does not bring any specific meaning instead of resolving ambiguities in naming :/
</blockquote></details>

I'm ok with FormatterImpl


<!-- Sent from Reviewable.io -->

2023-02-09 12:53 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2008)* status: all files reviewed, 3 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-formatter/src/lib.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_szJx1iG_ttO7Cc7Q:-NNqEFXWCItzmTNmkeUF:b6k8ysd) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/lib.rs#L17)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I'm ok with FormatterImpl
</blockquote></details>

Me too.


<!-- Sent from Reviewable.io -->

2023-02-09 16:24 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2008)* status: 5 of 11 files reviewed, 4 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 20 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NNqzXqI6b5TCfow26SD:-NNqzXqI6b5TCfow26SE:b-d9c7tf) ([raw file](https://github.com/starkware-libs/cairo/blob/383d021e0b0844078d2d1dcf654575399ade4f31/crates/cairo-lang-formatter/src/cairo_formatter.rs#L20)):*
> ```XML
> 
> #[derive(Clone)]
> pub struct FileDiff {
> ```

doc the structs in this file.



_Code quote:_
```XML
pub struct FileDiff {
```


<!-- Sent from Reviewable.io -->

2023-02-10 07:22 UTC, mkaput approved these changes
> Reviewed 4 of 4 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2008)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr)



<!-- Sent from Reviewable.io -->

2023-02-10 07:23 UTC, mkaput approved these changes
Please address @orizi commend and <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2008#-:-NNuC7l54e8ul6YwYzJJ:beczdkm)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr)



<!-- Sent from Reviewable.io -->

2023-02-10 08:22 UTC, maciektr reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2008)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_o9Yg48G0Txuyd_N_:-NNqeDuY-Um1X4VLRs5S:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/cairo_formatter.rs#L17)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I agree
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 20 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NNqzXqI6b5TCfow26SD:-NNuPLeeElhTs-mFy-5X:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/383d021e0b0844078d2d1dcf654575399ade4f31/crates/cairo-lang-formatter/src/cairo_formatter.rs#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc the structs in this file.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/lib.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NN_szJx1iG_ttO7Cc7Q:-NNqeCtq-fZgrTD0vvnY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/acc15feefc5c36b379b62e4c0e0a975b7a9aee6d/crates/cairo-lang-formatter/src/lib.rs#L17)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Me too.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/bin/cli.rs` line 54 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NNpOOY23dag2lUvTJ-r:-NNqeuyZ7djczpfvj4TI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/383d021e0b0844078d2d1dcf654575399ade4f31/crates/cairo-lang-formatter/src/bin/cli.rs#L54)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

This needs simplification which I have discussed with @maciektr in the office.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-10 08:23 UTC, mkaput approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2008)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2023-02-10 08:23 UTC, mkaput approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2008)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2023-02-10 13:11 UTC, maciektr commented
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 35 at r12](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NNvPDF_0ZhPe70hl7f5:-NNvRntJETDLDwvxMp69:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3aeadb4803db37afbefea90bfd7a1e7a6256e9eb/crates/cairo-lang-formatter/src/cairo_formatter.rs#L35)):*
> ```XML
> impl Display for FileDiff {
>     fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
>         let patch = create_patch(&self.original, &self.formatted);
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-02-10 13:11 UTC, maciektr commented
*[`crates/cairo-lang-formatter/src/cairo_formatter.rs` line 43 at r12](https://reviewable.io/reviews/starkware-libs/cairo/2008#-NNvPMnM0EVmFnMJ3aww:-NNvRqoMA9w6oCPh0nD4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3aeadb4803db37afbefea90bfd7a1e7a6256e9eb/crates/cairo-lang-formatter/src/cairo_formatter.rs#L43)):*
> ```XML
>     fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
>         writeln!(f, "FileDiff(")?;
>         Display::fmt(self, f)?;
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-02-10 13:39 UTC, mkaput approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2008)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)



<!-- Sent from Reviewable.io -->

2023-02-10 13:39 UTC, merged