Introduce `DiagnosticsError` and `ensure_diagnostics`
starkware-libs/cairo pull request #2012
Opened 2023-02-01 13:53 UTC by mkaput

This allows catching the `Compilation failed.` error in more machine-friendly way, by using `anyhow::Error::downcast_ref` function.

---

**Stack**:
- #1999
- #1993

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2023-02-01 13:54 UTC, mkaput commented
FYI, I am currently thinking of rewriting this logic with a more scalable builder-style object. Will land in next PR if I will come up with something worthy.

2023-02-01 16:01 UTC, orizi requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2012)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2012#-NNChaxJ9XXYobtxTKW9:-NNChaxJ9XXYobtxTKWA:b-2pfjt5) ([raw file](https://github.com/starkware-libs/cairo/blob/8bcaebe14bb2ea8e4795859801d149fd0f4ef5af/crates/cairo-lang-compiler/src/diagnostics.rs#L17)):*
> ```XML
> 
> #[derive(Error, Debug, Eq, PartialEq)]
> #[non_exhaustive]
> ```

why is this required?



_Code quote:_
```XML
#[non_exhaustive]
```


<!-- Sent from Reviewable.io -->

2023-02-02 07:15 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2012)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2012#-NNChaxJ9XXYobtxTKW9:-NNFySruAOIb0Y7wPh5Z:bju1sxw) ([raw file](https://github.com/starkware-libs/cairo/blob/b8a02e454e231123301ad41d8a02476b896e3c7e/crates/cairo-lang-compiler/src/diagnostics.rs#L17)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is this required?
</blockquote></details>

I thought that we may have new variants pop up in the future, and I didn't want to let users downstream assume that there's only one here. But now I have no idea what may be added here... Perhaps this should be a ZST


<!-- Sent from Reviewable.io -->

2023-02-02 07:18 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2012)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2012#-NNChaxJ9XXYobtxTKW9:-NNFzLg5DkKyAIXzWxZR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b8a02e454e231123301ad41d8a02476b896e3c7e/crates/cairo-lang-compiler/src/diagnostics.rs#L17)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I thought that we may have new variants pop up in the future, and I didn't want to let users downstream assume that there's only one here. But now I have no idea what may be added here... Perhaps this should be a ZST
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-02 07:25 UTC, orizi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2012)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @mkaput)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2012#-NNChaxJ9XXYobtxTKW9:-NNG-paoCydzpa82noRC:b-urs01h) ([raw file](https://github.com/starkware-libs/cairo/blob/b8a02e454e231123301ad41d8a02476b896e3c7e/crates/cairo-lang-compiler/src/diagnostics.rs#L17)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

the enum is good IMO - i  just didn't understand why would the `non_exhaustive` should be added


<!-- Sent from Reviewable.io -->

2023-02-02 08:12 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2012)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-compiler/src/diagnostics.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2012#-NNChaxJ9XXYobtxTKW9:-NNGAL5ZDYAjbvkbi2tu:b33xq1s) ([raw file](https://github.com/starkware-libs/cairo/blob/b8a02e454e231123301ad41d8a02476b896e3c7e/crates/cairo-lang-compiler/src/diagnostics.rs#L17)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the enum is good IMO - i  just didn't understand why would the `non_exhaustive` should be added
</blockquote></details>

I just don't see any sense of having a single-variant exhaustive enum (i.e. exhaustive == one guaranteed to never have more variants added)


<!-- Sent from Reviewable.io -->

2023-02-02 13:43 UTC, orizi submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2012#-:-NNHMahA9GmcZOk9u12t:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2023-02-03 07:02 UTC, mkaput reviewed
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2012)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2023-02-03 07:15 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2012#-:-NNL7Kb3BXzMh4ApCO22:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2023-02-03 07:38 UTC, merged