format plugin test outputs
starkware-libs/cairo pull request #2235
Opened 2023-02-21 19:40 UTC by tarrencev

quality of life improvement. i noticed some places the code blocks are awkwardly formatted to preserve output formatting, for example here: https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-starknet/src/plugin/dispatcher.rs#L113

this removes the tradeoff between code and test output readability

2023-02-23 06:47 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2235)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @tarrencev)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract` line 110 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2235#-NOx0aCf29yomO8GkK0A:-NOx0aCg4TaPLLiDvkDJ:b-dlpape) ([raw file](https://github.com/starkware-libs/cairo/blob/cf01011e5b3c7cdbe50e1bb7efc6352331a40818/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract#L110)):*
> ```
>             };
>             if !array::ArrayTrait::is_empty(
>                 @data
> ```

I think it's misbehaving.



_Code quote:_
```
@data
```


<!-- Sent from Reviewable.io -->

2023-02-23 12:50 UTC, tarrencev commented
> 
> 
> > *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2235)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @tarrencev)
> 
> ___
> *[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract` line 110 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2235#-NOx0aCf29yomO8GkK0A:-NOx0aCg4TaPLLiDvkDJ:b-dlpape) ([raw file](https://github.com/starkware-libs/cairo/blob/cf01011e5b3c7cdbe50e1bb7efc6352331a40818/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contract#L110)):*
> > ```
> >             };
> >             if !array::ArrayTrait::is_empty(
> >                 @data
> > ```
> 
> I think it's misbehaving.
> 
> 
> 
> _Code quote:_
> ```
> @data
> ```
> 
> 
> <!-- Sent from Reviewable.io -->
> 

hm i think this should be addressed in cairo-lang-formatter?

2023-02-27 10:16 UTC, spapinistarkware reviewed
I'm not 100% sure about this PR. Keeping the output exactly like it comes out of the plugin is useful, for example, when trying to improve its formatting:) In the long term, we want the plugin to output formatted code, but that's not possible now due to error remapping.
Also, the test outputs are pretty readable.

Does the test_data formatting bother you in any way?

> Reviewed 3 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2235#-:-NPHMKdLEewBl4U_KXPk:brm5owm)* status: 3 of 9 files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2023-02-27 11:27 UTC, tarrencev commented
> I'm not 100% sure about this PR. Keeping the output exactly like it comes out of the plugin is useful, for example, when trying to improve its formatting:) In the long term, we want the plugin to output formatted code, but that's not possible now due to error remapping.
> Also, the test outputs are pretty readable.
> 
> Does the test_data formatting bother you in any way?
> 
> > Reviewed 3 of 9 files at r1, all commit messages.
> > *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2235#-:-NPHMKdLEewBl4U_KXPk:brm5owm)* status: 3 of 9 files reviewed, 1 unresolved discussion
> 
> 
> 
> <!-- Sent from Reviewable.io -->
> 

Ok no problem. I found that outputting formatted code is tricky in some cases with dojo, resulting in hard to read implementations, and formatting it was a simple solution that might be useful here too.

Imo the generator shouldn't be concerned with the formatting, since we already have the formatter for that, and should focus on implementation readability.

Anyways happy to close it out if it is not useful here

2023-02-27 11:27 UTC, closed without merging