Added validation that all merges would be recompilable.
starkware-libs/cairo pull request #2292
Opened 2023-02-27 10:50 UTC by orizi

* Added bookkeeping that of jumps, so we'd be able to find an LCA of
merges (as the divergence point).
* Removed all Unused PartialEq, Eq - so we would not accidentally
compare using these.
* Compared var references one by one - checking that they are either:
- On continuous stack.
- On local.
- On where generated prior to divergence.

---

**Stack**:
- #2288
- #2273
- #2272
- #2271

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2023-02-28 08:42 UTC, ilyalesokhin-starkware requested changes
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2292)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPMAwXYBuSr0ghHPFI9:-NPMAwXZ2q1TvMYRHRPC:bc9r8sk) ([raw file](https://github.com/starkware-libs/cairo/blob/44c99c0db47df13e9325e7c58d108346e6f9f155/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L162)):*
> ```XML
>                     return Err(AnnotationError::InconsistentFunctionId { statement_idx });
>                 }
> ```

why waws this removed?



_Code quote:_
```XML
                if expected_annotations.function_id != annotations.function_id {
                    return Err(AnnotationError::InconsistentFunctionId { statement_idx });
                }
```


<!-- Sent from Reviewable.io -->

2023-02-28 08:49 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPMCLiO7LBgNtEUnGV-:-NPMCLiO7LBgNtEUnGV0:bx8js5e) ([raw file](https://github.com/starkware-libs/cairo/blob/bd3097f46b0b80f4b1e4b704a30185ce1b8edeb0/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L195)):*
> ```XML
>             .iter()
>             .zip(expected.jump_path.iter())
>             .rfind(|(s1, s2)| s1 == s2)
> ```

why rfind?

isn't it possible that they diverged before this point and the became equal again?

don't you want to find the first place where they are different?



_Code quote:_
```XML
 .rfind(|(s1, s2)| s1 == s2)
```


<!-- Sent from Reviewable.io -->

2023-02-28 08:49 UTC, ilyalesokhin-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2292)* status: 1 of 8 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 199 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPMBg8M-cx4Ofwczj8K:-NPMBg8M-cx4Ofwczj8L:b-acim30) ([raw file](https://github.com/starkware-libs/cairo/blob/bd3097f46b0b80f4b1e4b704a30185ce1b8edeb0/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L199)):*
> ```XML
>             .or(actual.environment.ap_tracking_base);
>         // The variable generation at the divergence point itself - only such variables can be
>         // available.
> ```

I don't understand the comment.



_Code quote:_
```XML
        // The variable generation at the divergence point itself - only such variables can be
        // available.
```


<!-- Sent from Reviewable.io -->

2023-02-28 08:50 UTC, ilyalesokhin-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2292)* status: 1 of 8 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 222 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPMCr5VA9ZP7t7umVGa:-NPMCr5VA9ZP7t7umVGb:b13hmha) ([raw file](https://github.com/starkware-libs/cairo/blob/bd3097f46b0b80f4b1e4b704a30185ce1b8edeb0/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L222)):*
> ```XML
>                     || max_known_generation.is_none()
>                     || *generation > max_known_generation.unwrap())
>             {
> ```

document.



_Code quote:_
```XML
            if stack_idx.is_none()
                && (expression.cells.is_empty() || !expression.can_apply_unknown())
                && (*generation != expected_ref.generation
                    || max_known_generation.is_none()
                    || *generation > max_known_generation.unwrap())
            {
```


<!-- Sent from Reviewable.io -->

2023-02-28 08:54 UTC, ilyalesokhin-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2292)* status: 1 of 8 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPMDb6MEaIni1bV7DG9:-NPMDb6MEaIni1bV7DGA:b13hmha) ([raw file](https://github.com/starkware-libs/cairo/blob/bd3097f46b0b80f4b1e4b704a30185ce1b8edeb0/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L120)):*
> ```XML
>         branch_signature: &BranchSignature,
>         prev_env: &Environment,
>         param_ref: ParamRef,
> ```

document.



_Code quote:_
```XML
    param_ref: ParamRef,
```


<!-- Sent from Reviewable.io -->

2023-02-28 11:55 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2292)* status: 1 of 8 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 162 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPMAwXYBuSr0ghHPFI9:-NPMoGni1vYP6WBNg2Io:b-ofbo7z) ([raw file](https://github.com/starkware-libs/cairo/blob/f75e27e5af17dd4344ef6c5ecf828250179efa4c/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L162)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why waws this removed?
</blockquote></details>

it wasn't - it was just moved down - moving back up.
___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPMCLiO7LBgNtEUnGV-:-NPMobQo96PujWIT_Zhc:b7o1enz) ([raw file](https://github.com/starkware-libs/cairo/blob/7229b292be90fedee989d18c53199d163e7839bf/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L195)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why rfind?

isn't it possible that they diverged before this point and the became equal again?

don't you want to find the first place where they are different?
</blockquote></details>

it actually isn't possible - since if they had at any point the same statement in the stack - everything previous would have had to be the exact same (since it would have been the just stack of the previous statement).

added some comment.
___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 199 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPMBg8M-cx4Ofwczj8K:-NPMp9yl6K3IG1ThGPHx:b-no9x65) ([raw file](https://github.com/starkware-libs/cairo/blob/7229b292be90fedee989d18c53199d163e7839bf/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L199)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't understand the comment.
</blockquote></details>

rephrased
___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 222 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPMCr5VA9ZP7t7umVGa:-NPMrCij0cvZLL8jHWAJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7229b292be90fedee989d18c53199d163e7839bf/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L222)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

document.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPMDb6MEaIni1bV7DG9:-NPMrclE7YBsaSxu9Qb0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7229b292be90fedee989d18c53199d163e7839bf/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs#L120)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

document.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-28 14:45 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 344 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPNTzl-5u06MiWDjwcy:-NPNTzl-5u06MiWDjwcz:b-8g2vee) ([raw file](https://github.com/starkware-libs/cairo/blob/cff671dc25ee3bdbf8b7cf07c76c47c953408777/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L344)):*
> ```XML
>             None
>         } else if matches!(annotations.environment.ap_tracking, ApChange::Unknown) {
>             // Ap tracking was just enabled - the new destination is the base.
> ```

Why was ap tracking enabled?



_Code quote:_
```XML
 // Ap tracking was just enabled - the new destination is the base.
```


<!-- Sent from Reviewable.io -->

2023-02-28 14:45 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 348 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPNU53d-t28VpCeCoGw:-NPNU53d-t28VpCeCoGx:byuurpp) ([raw file](https://github.com/starkware-libs/cairo/blob/cff671dc25ee3bdbf8b7cf07c76c47c953408777/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L348)):*
> ```XML
>         } else {
>             // Was previously enabled but still is - keeping the same base.
>             annotations.environment.ap_tracking_base
> ```

why allow this?



_Code quote:_
```XML
            // Was previously enabled but still is - keeping the same base.
            annotations.environment.ap_tracking_base
```


<!-- Sent from Reviewable.io -->

2023-02-28 14:53 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 215 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPNVrjS2yXPlDH9ewL8:-NPNVrjT-f01J2-KYLaL:bt8z3fc) ([raw file](https://github.com/starkware-libs/cairo/blob/cff671dc25ee3bdbf8b7cf07c76c47c953408777/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L215)):*
> ```XML
>                     ..annotations
>                 };
>                 if invocation.branches.len() > 1 {
> ```

can you use  branching_libfunc, i.e. decide that its a branch in a consistent manner.



_Suggestion:_
```XML
 branching_libfunc
```


<!-- Sent from Reviewable.io -->

2023-02-28 14:55 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPNVzv0-qWa4-08SMiL:-NPNVzv0-qWa4-08SMiM:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cff671dc25ee3bdbf8b7cf07c76c47c953408777/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L92)):*
> ```XML
>     pub convergence_allowed: bool,
>     pub environment: Environment,
>     /// A path of jumps to the current statement from some ap-change base.
> ```





_Suggestion:_
```XML
 /// A path of jumps to the current statement from some ap-change base.
 /// The path includes all the statement indices with branching libfuncs starting from ap-change base.
```


<!-- Sent from Reviewable.io -->

2023-02-28 15:19 UTC, ilyalesokhin-starkware reviewed
Can you add tests? 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2292#-:-NPNanjgBg6XdqI-f4Of:b-howir7)* status: 2 of 8 files reviewed, 7 unresolved discussions (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2023-02-28 15:28 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2292)* status: 2 of 8 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPNVzv0-qWa4-08SMiL:-NPNcAj2A9Sum7jn5XIe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cff671dc25ee3bdbf8b7cf07c76c47c953408777/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L92)):*
> ```XML
>     pub convergence_allowed: bool,
>     pub environment: Environment,
>     /// A path of jumps to the current statement from some ap-change base.
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 205 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPNZ9oU3g9yyDpQJoIM:-NPNcUFG7pKD2k0OyWkb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cff671dc25ee3bdbf8b7cf07c76c47c953408777/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L205)):*
> ```XML
>         // considered available at the merge, since only older varialble may be ap-aligned to match
>         // in both branches.
>         let max_known_generation = divergance_point.map(|idx| {
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 227 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPNTQicAe0S7dQVVm0C:-NPNcYPNBBx6sTEhw4Gu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cff671dc25ee3bdbf8b7cf07c76c47c953408777/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L227)):*
> ```XML
>             // If the variable is not on stack.
>             if stack_idx.is_none()
>                 // And is either empty, or somewhat ap-dependen.
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 344 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPNTzl-5u06MiWDjwcy:-NPNa4zl5m4qtTKHV1lu:b-g2ubgg) ([raw file](https://github.com/starkware-libs/cairo/blob/cff671dc25ee3bdbf8b7cf07c76c47c953408777/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L344)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why was ap tracking enabled?
</blockquote></details>

that is the meaning of the encapsulating ifs
___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 348 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPNU53d-t28VpCeCoGw:-NPNa8r246Efvs4xITzf:b-llvf2l) ([raw file](https://github.com/starkware-libs/cairo/blob/cff671dc25ee3bdbf8b7cf07c76c47c953408777/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L348)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why allow this?
</blockquote></details>

same issue we discussed when i added the `enable-ap-tracking` libfunc
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler.rs` line 215 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPNVrjS2yXPlDH9ewL8:-NPNbw_M5niJBQ3SM85l:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cff671dc25ee3bdbf8b7cf07c76c47c953408777/crates/cairo-lang-sierra-to-casm/src/compiler.rs#L215)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you use  branching_libfunc, i.e. decide that its a branch in a consistent manner.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-28 15:39 UTC, orizi reviewed
added test that fails do to merge out of the broken stack area.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2292#-:-NPNfKse6oKbBggSSHzb:b-iooihb)* status: 2 of 8 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2023-02-28 15:53 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 344 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPNTzl-5u06MiWDjwcy:-NPNiQcj6GRyW6ojPInF:b5gmfxr) ([raw file](https://github.com/starkware-libs/cairo/blob/cff671dc25ee3bdbf8b7cf07c76c47c953408777/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L344)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

that is the meaning of the encapsulating ifs
</blockquote></details>

Why does
 matches!(annotations.environment.ap_tracking, ApChange::Unknown)
mean that "Ap tracking was enabled"?



_Code quote:_
```XML
 matches!(annotations.environment.ap_tracking, ApChange::Unknown)
```


<!-- Sent from Reviewable.io -->

2023-02-28 15:54 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2292)* status: 2 of 8 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 344 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPNTzl-5u06MiWDjwcy:-NPNieRI8BekLlW3eV-H:b-tclhyj) ([raw file](https://github.com/starkware-libs/cairo/blob/cff671dc25ee3bdbf8b7cf07c76c47c953408777/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L344)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why does
 matches!(annotations.environment.ap_tracking, ApChange::Unknown)
mean that "Ap tracking was enabled"?
</blockquote></details>

because it is inside an else - of an if that check if the current state is unknown.


<!-- Sent from Reviewable.io -->

2023-02-28 15:55 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 348 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPNU53d-t28VpCeCoGw:-NPNj75CE-1TFZk1JrEO:b5qhqbs) ([raw file](https://github.com/starkware-libs/cairo/blob/cff671dc25ee3bdbf8b7cf07c76c47c953408777/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L348)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

same issue we discussed when i added the `enable-ap-tracking` libfunc
</blockquote></details>


I think you didn't answer:
https://github.com/starkware-libs/cairo/pull/2271#pullrequestreview-1316885707


<!-- Sent from Reviewable.io -->

2023-02-28 16:04 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2292)* status: 2 of 8 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 348 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPNU53d-t28VpCeCoGw:-NPNl7QE2G1-nNa7TAAT:b2k45f0) ([raw file](https://github.com/starkware-libs/cairo/blob/cff671dc25ee3bdbf8b7cf07c76c47c953408777/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L348)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>


I think you didn't answer:
https://github.com/starkware-libs/cairo/pull/2271#pullrequestreview-1316885707
</blockquote></details>

only i did - and i must remain consistent - otherwise it wouldn't work


<!-- Sent from Reviewable.io -->

2023-02-28 16:05 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 344 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPNlG-j8pAvLklkpjO5:-NPNlG-j8pAvLklkpjO6:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/cff671dc25ee3bdbf8b7cf07c76c47c953408777/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L344)):*
> ```XML
>             None
>         } else if matches!(annotations.environment.ap_tracking, ApChange::Unknown) {
>             // Ap tracking was just enabled - the new destination is the base.
> ```





_Suggestion:_
```XML
 // Ap tracking was changed from unknown to know; this means that ap tracking was just enabled - the new destination is the base.
```


<!-- Sent from Reviewable.io -->

2023-02-28 16:07 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 348 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPNU53d-t28VpCeCoGw:-NPNlqIhDIq-xt7zbyie:b-thn6l8) ([raw file](https://github.com/starkware-libs/cairo/blob/cff671dc25ee3bdbf8b7cf07c76c47c953408777/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L348)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

only i did - and i must remain consistent - otherwise it wouldn't work
</blockquote></details>

ok, the github interface is confusing :(


<!-- Sent from Reviewable.io -->

2023-02-28 16:08 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/environment/mod.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPNm6TbBX-tDbCWPYwt:-NPNm6TbBX-tDbCWPYwu:b-xweatm) ([raw file](https://github.com/starkware-libs/cairo/blob/5e2d5eeaec5172167de01d585b0b039565cafa0b/crates/cairo-lang-sierra-to-casm/src/environment/mod.rs#L38)):*
> ```XML
>     pub frame_state: FrameState,
>     pub gas_wallet: GasWallet,
>     /// The generation of the currently created variables.
> ```

I think we use the term references in sierra_to_casm



_Code quote:_
```XML
variables
```


<!-- Sent from Reviewable.io -->

2023-02-28 16:15 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2292)* status: 2 of 8 files reviewed, 8 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/annotations.rs` line 344 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPNlG-j8pAvLklkpjO5:-NPNnM5YBidUl9ReoJ4Z:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cff671dc25ee3bdbf8b7cf07c76c47c953408777/crates/cairo-lang-sierra-to-casm/src/annotations.rs#L344)):*
> ```XML
>             None
>         } else if matches!(annotations.environment.ap_tracking, ApChange::Unknown) {
>             // Ap tracking was just enabled - the new destination is the base.
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/environment/mod.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPNm6TbBX-tDbCWPYwt:-NPNnSfeD6rzyZvZxHIi:b-bw2gyr) ([raw file](https://github.com/starkware-libs/cairo/blob/5e2d5eeaec5172167de01d585b0b039565cafa0b/crates/cairo-lang-sierra-to-casm/src/environment/mod.rs#L38)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think we use the term references in sierra_to_casm
</blockquote></details>

but it is about the variables created - `references` always exists - there's no proper terminology here i think - as this is a newly tracked concept :\


<!-- Sent from Reviewable.io -->

2023-03-01 08:10 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/compiler_test.rs` line 512 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPRD5Y6BzI1GBpoXymf:-NPRD5Y6BzI1GBpoXymg:bc1k6m6) ([raw file](https://github.com/starkware-libs/cairo/blob/6a5e051c0ac81454c8acf111696945df1ced7be4/crates/cairo-lang-sierra-to-casm/src/compiler_test.rs#L512)):*
> ```XML
>                 branch_align() -> ();
>                 store_temp_felt([2]) -> ([2]);
>                 // Breaking the stack so it can't be tracked.
> ```

why is   store_temp_felt breaking the stack?



_Code quote:_
```XML
 // Breaking the stack so it can't be tracked.
```


<!-- Sent from Reviewable.io -->

2023-03-01 08:10 UTC, ilyalesokhin-starkware requested changes
> Reviewed 2 of 8 files at r1, 1 of 3 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2292)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler_test.rs` line 549 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPRDGWs9JpRalJkKSwp:-NPRDGWs9JpRalJkKSwq:b-56nlo1) ([raw file](https://github.com/starkware-libs/cairo/blob/6a5e051c0ac81454c8acf111696945df1ced7be4/crates/cairo-lang-sierra-to-casm/src/compiler_test.rs#L549)):*
> ```XML
> 
>                 test_program@0([1]: felt) -> ();
>             "}, "#8: Inconsistent ap tracking base.";
> ```

can you give more details?



_Code quote:_
```XML
8: Inconsistent ap tracking base.
```


<!-- Sent from Reviewable.io -->

2023-03-01 09:39 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2292)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/compiler_test.rs` line 512 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPRD5Y6BzI1GBpoXymf:-NPRXCJM8pKKQ-QUHI8Z:b-bn5zp5) ([raw file](https://github.com/starkware-libs/cairo/blob/6a5e051c0ac81454c8acf111696945df1ced7be4/crates/cairo-lang-sierra-to-casm/src/compiler_test.rs#L512)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why is   store_temp_felt breaking the stack?
</blockquote></details>

it is the store + the drop.
___
*[`crates/cairo-lang-sierra-to-casm/src/compiler_test.rs` line 549 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2292#-NPRDGWs9JpRalJkKSwp:-NPRXdF352ni-QYW2pue:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6a5e051c0ac81454c8acf111696945df1ced7be4/crates/cairo-lang-sierra-to-casm/src/compiler_test.rs#L549)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you give more details?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-01 11:35 UTC, ilyalesokhin-starkware approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2292)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2023-03-01 11:45 UTC, merged