Using span in syscalls and entry points.
starkware-libs/cairo pull request #2510
Opened 2023-03-15 19:45 UTC by orizi

2023-03-15 20:32 UTC, liorgold2 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2510)* status: 0 of 31 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/interoperability.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2510#-NQaxl2kBTHvcV0xp9gU:-NQaxl2kBTHvcV0xp9gV:brchxss) ([raw file](https://github.com/starkware-libs/cairo/blob/18f10bf8aba64488f16b48e2d4ff423e2768b4cf/crates/cairo-lang-sierra/src/extensions/modules/starknet/interoperability.rs#L147)):*
> ```XML
>         context: &dyn SignatureSpecializationContext,
>     ) -> Result<Vec<crate::ids::ConcreteTypeId>, SpecializationError> {
>         Ok(vec![felt252_span_ty(context)?])
> ```

@spapinistarkware suggested that the return values will be array and not span, since the returning function does not need it anymore anyway (and it's possible you'll want to take the result and extend it).
I'm fine with both option.

Anyway, this only applies to return values from external functions, not to arguments (call data).


<!-- Sent from Reviewable.io -->

2023-03-15 20:35 UTC, liorgold2 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2510)* status: 0 of 31 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/interoperability.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2510#-NQaxl2kBTHvcV0xp9gU:-NQaydwEAD19-2spgk_T:b-6q6e7h) ([raw file](https://github.com/starkware-libs/cairo/blob/18f10bf8aba64488f16b48e2d4ff423e2768b4cf/crates/cairo-lang-sierra/src/extensions/modules/starknet/interoperability.rs#L147)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

@spapinistarkware suggested that the return values will be array and not span, since the returning function does not need it anymore anyway (and it's possible you'll want to take the result and extend it).
I'm fine with both option.

Anyway, this only applies to return values from external functions, not to arguments (call data).
</blockquote></details>

To put here more context, if you have an array and you want to call another contract, it doesn't make sense that the array will be destructed. But this argument doesn't hold for return values, where it seems it's ok to take ownership of the array.


<!-- Sent from Reviewable.io -->

2023-03-15 20:36 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2510)* status: 0 of 31 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/interoperability.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2510#-NQaxl2kBTHvcV0xp9gU:-NQaymJBEOUhZA3iN7sH:bhtdfhj) ([raw file](https://github.com/starkware-libs/cairo/blob/18f10bf8aba64488f16b48e2d4ff423e2768b4cf/crates/cairo-lang-sierra/src/extensions/modules/starknet/interoperability.rs#L147)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

To put here more context, if you have an array and you want to call another contract, it doesn't make sense that the array will be destructed. But this argument doesn't hold for return values, where it seems it's ok to take ownership of the array.
</blockquote></details>

is there an option where the caller would return some span from a different resource? (be it one of the inputs, or some constant) - an array blocks this.
if we already moved - this makes sense to calldata as well.


<!-- Sent from Reviewable.io -->

2023-03-16 06:49 UTC, spapinistarkware requested changes
See inline comments

2023-03-16 06:49 UTC, spapinistarkware commented on corelib/src/starknet/syscalls.cairo
> +) -> SyscallResult<Span<felt252>> implicits(GasBuiltin, System) nopanic;
I think the return type should be Array. The called contract has no use for it, so it might as well give its ownership

2023-03-16 07:33 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2510)* status: 1 of 31 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`corelib/src/starknet/syscalls.cairo` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2510#-NQan_qNkismMAmQvQEq-r1-12:-NQdKEAE5FtDGrG8c21K:bl5itbz) ([raw file](https://github.com/starkware-libs/cairo/blob/18f10bf8aba64488f16b48e2d4ff423e2768b4cf/corelib/src/starknet/syscalls.cairo#L12)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think the return type should be Array. The called contract has no use for it, so it might as well give its ownership
</blockquote></details>

my issue with it is that it makes us `have to` have an actual array there - but generally we don't actually need it - it can be a constant array from a data segment, or a subarray of an array the entrypoint received


<!-- Sent from Reviewable.io -->

2023-03-16 08:47 UTC, spapinistarkware reviewed
> Reviewed 2 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2510)* status: 3 of 31 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/test.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2510#-NQdaULbAHx-fQ3mN4i8:-NQdaULbAHx-fQ3mN4i9:b-sl5zdk) ([raw file](https://github.com/starkware-libs/cairo/blob/527999d156535ec812e15ef1faf629dc0ea76c67/crates/cairo-lang-sierra/src/extensions/test.rs#L321)):*
> ```XML
> #[test_case("storage_read_syscall", vec![] => Ok(()); "storage_read_syscall")]
> #[test_case("storage_write_syscall", vec![] => Ok(()); "storage_write_syscall")]
> #[test_case("call_contract_syscall", vec![] => Ok(()); "call_contract_syscall")]
> ```

Why is this removed?


<!-- Sent from Reviewable.io -->

2023-03-16 08:48 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2510)* status: 3 of 31 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/test.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2510#-NQdaULbAHx-fQ3mN4i8:-NQdafnC7vs2Ny9IQ1x8:b-quwor1) ([raw file](https://github.com/starkware-libs/cairo/blob/527999d156535ec812e15ef1faf629dc0ea76c67/crates/cairo-lang-sierra/src/extensions/test.rs#L321)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why is this removed?
</blockquote></details>

this is an uninteresting test - and it just fails since i need to register all related classes - which becomes quite a lot once we have a span depending on a snapshot of an array.


<!-- Sent from Reviewable.io -->

2023-03-16 08:52 UTC, spapinistarkware requested changes
> Reviewed 13 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2510)* status: 15 of 31 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/raw_output` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2510#-NQdbcyT6lhGY9GuL4ph:-NQdbcyT6lhGY9GuL4pi:b-1f2van) ([raw file](https://github.com/starkware-libs/cairo/blob/18f10bf8aba64488f16b48e2d4ff423e2768b4cf/crates/cairo-lang-starknet/src/plugin/plugin_test_data/raw_output#L72)):*
> ```
> 
> //! > expected_diagnostics
> error: Plugin diagnostic: `raw_output` functions must return `Span::<felt252>`.
> ```

Fix this?


<!-- Sent from Reviewable.io -->

2023-03-16 08:53 UTC, spapinistarkware reviewed
> Reviewed 1 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2510)* status: 16 of 31 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)



<!-- Sent from Reviewable.io -->

2023-03-16 08:53 UTC, spapinistarkware reviewed
> Reviewed 15 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2510)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)



<!-- Sent from Reviewable.io -->

2023-03-16 09:01 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2510)* status: 30 of 31 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/raw_output` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2510#-NQdbcyT6lhGY9GuL4ph:-NQddcFqB8flNEP-YSAL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/18f10bf8aba64488f16b48e2d4ff423e2768b4cf/crates/cairo-lang-starknet/src/plugin/plugin_test_data/raw_output#L72)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Fix this?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-16 09:05 UTC, spapinistarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2510#-:-NQdeiw7-NKd-cLnPILf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2023-03-16 09:15 UTC, orizi reviewed
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2510)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2023-03-16 09:38 UTC, merged