Added "logging" section to vscode-readme
starkware-libs/cairo pull request #2578
Opened 2023-03-21 16:49 UTC by yuvalsw

2023-03-25 14:33 UTC, spapinistarkware requested changes
See inline comments

2023-03-25 14:33 UTC, spapinistarkware commented on vscode-cairo/README.md
> +   "RUST_LOG": "debug,salsa=off,minilp=off"
Is this the place to add the CARGO_MANIFEST thingy to make debug from vscode work? If so, maybe write it as well?

2023-03-26 10:26 UTC, spapinistarkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2578)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-03-26 11:00 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2578)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`vscode-cairo/README.md` line 57 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2578#-NR43kr4uYj-sBz6w5yH-r1-57:-NRSWv5L1SlFfl41Y6PQ:bsmd4l2) ([raw file](https://github.com/starkware-libs/cairo/blob/744e30eab66ba8e03fda8415192919c1037a96fe/vscode-cairo/README.md#L57)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Is this the place to add the CARGO_MANIFEST thingy to make debug from vscode work? If so, maybe write it as well?
</blockquote></details>

Yes. Done


<!-- Sent from Reviewable.io -->

2023-03-26 12:23 UTC, spapinistarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2578#-:-NRSrqyZ6ctIvrqUYzZO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-03-26 16:51 UTC, merged