Added PartialEq derive option.
starkware-libs/cairo pull request #2580
Opened 2023-03-22 06:05 UTC by orizi

**Stack**:
- #2579
- #2577
- #2574
- #2573

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2023-03-25 14:34 UTC, spapinistarkware requested changes
See inline comments

2023-03-25 14:34 UTC, spapinistarkware commented on crates/cairo-lang-plugins/src/derive.rs
> +                        fn ne(lhs: {name}, rhs: {name}) -> bool {{
inline?

2023-03-25 14:34 UTC, spapinistarkware commented on crates/cairo-lang-plugins/src/derive.rs
> +            }).join("\n         & ")}
Why not use early returns for now?

2023-03-26 07:36 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2580)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/cairo-lang-plugins/src/derive.rs` line 175 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2580#-NR6uxE5zKdW7qt88aS8-r1-175:-NRRp3pHBGYwHGefCT9J:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1c0f09eb56ee2e2c133bff92052430f113a96283/crates/cairo-lang-plugins/src/derive.rs#L175)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

inline?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/derive.rs` line 207 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2580#-NR6uxE5zKdW7qt88aS8-r1-207:-NRRqAKRAj6YT5sfVIqT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1c0f09eb56ee2e2c133bff92052430f113a96283/crates/cairo-lang-plugins/src/derive.rs#L207)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why not use early returns for now?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-26 08:48 UTC, spapinistarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2580#-:-NRS5jvD18cZvwDuTTJP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2023-03-26 15:17 UTC, merged