Add dict entry operation.
starkware-libs/cairo pull request #2678
Opened 2023-04-02 06:49 UTC by gilbens-starkware

2023-04-02 09:44 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NS0La_S6GmDi_Y440uN:-NS0La_S6GmDi_Y440uO:b7plj9a) (no related file):*
update according to f2f discussions.

___


<!-- Sent from Reviewable.io -->

2023-04-03 14:56 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NS0La_S6GmDi_Y440uN:-NS6bTn17Wf5P2wesEWY:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

update according to f2f discussions.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2023-04-04 11:01 UTC, orizi requested changes
> Reviewed 1 of 13 files at r1, 1 of 2 files at r2, 9 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: 11 of 15 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`corelib/src/dict.cairo` line 13 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSAtrIQ1tu91XHl2d2q:-NSAtrIQ1tu91XHl2d2r:b-uer4ja) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/corelib/src/dict.cairo#L13)):*
> ```Cairo
> extern fn felt252_dict_read<T>(ref dict: Felt252Dict<T>, key: felt252) -> T nopanic;
> 
> extern fn felt252_dict_entry_new<T>(
> ```

this feels more like a `get` than a `new` to me - but ask around.



_Code quote:_
```Cairo
felt252_dict_entry_new
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 297 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSAuk52Dc814gMQ1orb:-NSAuk52Dc814gMQ1orc:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L297)):*
> ```XML
>                 OutputVarInfo {
>                     ty: dict_entry_ty,
>                     ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
> ```





_Suggestion:_
```XML
 OutputVarReferenceInfo::Deferred(DeferredOutputKind::AddConst),
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 327 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSAuoIw2DyX1UiuCgcf:-NSAuoIw2DyX1UiuCgcg:b66c88m) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L327)):*
> ```XML
>                 ty: dict_ty,
>                 ref_info: OutputVarReferenceInfo::SameAsParam { param_idx: 0 },
>             }],
> ```

and accept add const for the dict type.



_Suggestion:_
```XML
        Ok(LibfuncSignature::new_non_branch_ex(
            vec![dict_entry_ty, ty],
            vec![OutputVarInfo {
                ty: dict_ty,
                ref_info: OutputVarReferenceInfo::SameAsParam { param_idx: 0 },
            }],
            SierraApChange::Known { new_vars_only: true },
        ))
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 887 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSAv86G-mDTQOfPL2HR:-NSAv86G-mDTQOfPL2HS:b7mnv53) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L887)):*
> ```XML
>         hint Felt252DictRead {dict_ptr: dict_ptr, key: key} into {value_dst: value};
>         assert key = *(dict_ptr++);
>         assert value = *(dict_ptr++);
> ```

and return it - no need to actually read.



_Suggestion:_
```XML
let prev_value = *(dict_ptr++);
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 889 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSAv5MK5VdfV5hbpvaw:-NSAv5MK5VdfV5hbpvax:b-c24u2t) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L889)):*
> ```XML
>         assert value = *(dict_ptr++);
>         // The new value will be written in the entry finalize;
>         // TODO
> ```

nothing to TODO.



_Code quote:_
```XML
        // TODO
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 928 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSAvHtrAVNBZIpqTHud:-NSAvHtrAVNBZIpqTHue:b3is68m) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L928)):*
> ```XML
>     add_input_variables! {casm_builder, deref dict_entry; };
>     casm_build_extend! {casm_builder,
>         hint Felt252DictEntryClear { dict_ptr: dict_entry } into {};
> ```

i think you must actually write the 0 - and not allow the hint manager to do it itself - but i need to think about it.



_Code quote:_
```XML
    casm_build_extend! {casm_builder,
        hint Felt252DictEntryClear { dict_ptr: dict_entry } into {};
        ap += 0;
    };
```


<!-- Sent from Reviewable.io -->

2023-04-04 12:52 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: 11 of 15 files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 546 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSBJfKf9dxOqTqDQQe5:-NSBJfKf9dxOqTqDQQe6:bpghs3e) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/tests/e2e_test_data/libfuncs/felt252_dict#L546)):*
> ```
> dict_tracker = __dict_manager.get_tracker(memory[fp + -5])
> dict_tracker.current_ptr += 3
> memory[ap + 0] = dict_tracker.data[memory[fp + -4]]
> ```

Please run this code in the playground, with these hints to make sure they work.



_Code quote:_
```
dict_tracker = __dict_manager.get_tracker(memory[fp + -5])
dict_tracker.current_ptr += 3
memory[ap + 0] = dict_tracker.data[memory[fp + -4]]
```


<!-- Sent from Reviewable.io -->

2023-04-04 12:52 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: 11 of 15 files reviewed, 9 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 537 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSBJsFq2jdKSoqSqVVK:-NSBJsFq2jdKSoqSqVVL:byp18fd) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/tests/e2e_test_data/libfuncs/felt252_dict#L537)):*
> ```
> 
> //! > cairo
> fn foo(ref dict: Felt252Dict::<felt252>, key: felt252, value: felt252) {
> ```

Remove



_Code quote:_
```
, value: felt252
```


<!-- Sent from Reviewable.io -->

2023-04-04 12:57 UTC, liorgold2 requested changes
> Reviewed 1 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: 12 of 15 files reviewed, 12 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 527 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSBKlNbErgoaJ8NXF1U:-NSBKlNbErgoaJ8NXF1V:bta5tjo) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/tests/e2e_test_data/libfuncs/felt252_dict#L527)):*
> ```
> test::foo@0([0]: RangeCheck, [1]: SegmentArena, [2]: GasBuiltin, [3]: Felt252Dict<felt252>) -> (RangeCheck, SegmentArena, GasBuiltin, SquashedFelt252Dict<felt252>);
> 
> //! > ==========================================================================
> ```

dict_entry_clear is missing
___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 527 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSBKqb90Sc3RxPPha90:-NSBKqb90Sc3RxPPha91:bbulznw) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/tests/e2e_test_data/libfuncs/felt252_dict#L527)):*
> ```
> test::foo@0([0]: RangeCheck, [1]: SegmentArena, [2]: GasBuiltin, [3]: Felt252Dict<felt252>) -> (RangeCheck, SegmentArena, GasBuiltin, SquashedFelt252Dict<felt252>);
> 
> //! > ==========================================================================
> ```

Can you add a test where you have two dict entries in a row (new, finalize, new, finalize)?
___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 597 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSBKZHh14wcnvRxLisf:-NSBKZHh14wcnvRxLisg:b-9a53hf) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/tests/e2e_test_data/libfuncs/felt252_dict#L597)):*
> ```
> //! > cairo
> fn foo(dict: Felt252Dict::<felt252>, key: felt252, value: felt252) {
>     let (entry, value) = felt252_dict_entry_new(dict, key);
> ```

I don't think this is a good test case for this kind of tests.


<!-- Sent from Reviewable.io -->

2023-04-15 21:52 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: 3 of 18 files reviewed, 14 unresolved discussions (waiting on @liorgold2 and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NS0La_S6GmDi_Y440uN:-NT5sTOh1F6Yl5FWdQO7:b-o55si0) (no related file):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Change target branch. 

___
___
*[`corelib/src/dict.cairo` line 13 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSAtrIQ1tu91XHl2d2q:-NSZfU5T6DoynrwsJcsh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/corelib/src/dict.cairo#L13)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this feels more like a `get` than a `new` to me - but ask around.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 298 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSBfFuL4qOxB-Eq8HcQ:-NS_kUtBDTgVXLx4TipE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/crates/cairo-lang-casm/src/hints/mod.rs#L298)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

should be part of casm code.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 504 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSBfNnYBDi3A1qeG_I5:-NSZjvXdDHlrszQG1D3O:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/crates/cairo-lang-runner/src/casm_run/mod.rs#L504)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

should be part of casm.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 297 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSAuk52Dc814gMQ1orb:-NSZk6kTDV3k3ju0ybri:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L297)):*
> ```XML
>                 OutputVarInfo {
>                     ty: dict_entry_ty,
>                     ref_info: OutputVarReferenceInfo::Deferred(DeferredOutputKind::Generic),
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 327 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSAuoIw2DyX1UiuCgcf:-NSZnGsv9_T8mqjNcfG8:b-4hcw2d) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L327)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and accept add const for the dict type.
</blockquote></details>

Done.
But I think you meant this to be for the new entry libfunc?
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 887 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSAv86G-mDTQOfPL2HR:-NSZnzUPAVAa5x9LHsB1:bduh77o) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L887)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and return it - no need to actually read.
</blockquote></details>

Why let? I want to partially write the prev_value to the new access.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 889 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSAv5MK5VdfV5hbpvaw:-NSZo-P86qBzzL13vqPz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L889)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

nothing to TODO.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 928 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSAvHtrAVNBZIpqTHud:-NSZo5Lh-HWQzs21jUSG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L928)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think you must actually write the 0 - and not allow the hint manager to do it itself - but i need to think about it.
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 527 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSBKlNbErgoaJ8NXF1U:-NS_kIBg185Zfe8rtIZj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/tests/e2e_test_data/libfuncs/felt252_dict#L527)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

dict_entry_clear is missing
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 527 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSBKqb90Sc3RxPPha90:-NT5tjdh5TZcCzzfkZlh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/tests/e2e_test_data/libfuncs/felt252_dict#L527)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Can you add a test where you have two dict entries in a row (new, finalize, new, finalize)?
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 537 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSBJsFq2jdKSoqSqVVK:-NS_kObF3TjUhyL8u3po:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/tests/e2e_test_data/libfuncs/felt252_dict#L537)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 546 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSBJfKf9dxOqTqDQQe5:-NS_kPht5tWiFVLXNB8L:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/tests/e2e_test_data/libfuncs/felt252_dict#L546)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Please run this code in the playground, with these hints to make sure they work.
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 597 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSBKZHh14wcnvRxLisf:-NT5tpPx6i1Dopa9wM5_:b-n0u7tq) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/tests/e2e_test_data/libfuncs/felt252_dict#L597)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I don't think this is a good test case for this kind of tests.
</blockquote></details>

Why not? The casm and Sierra won't be tested anywhere else.


<!-- Sent from Reviewable.io -->

2023-04-15 22:03 UTC, orizi requested changes
> Reviewed 5 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: 8 of 18 files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 884 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NT5w-xW-iXmUJ5g0gZR:-NT5w-xW-iXmUJ5g0gZS:b-7cw2b6) ([raw file](https://github.com/starkware-libs/cairo/blob/ef679177ac028d689e28e5f29adf0797210268c5/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L884)):*
> ```XML
>     add_input_variables! {casm_builder, buffer(2) dict_ptr; deref key; };
>     casm_build_extend! {casm_builder,
>         tempvar prev_value;
> ```

you should not read the value - just make it available - so write directly to the `dict_ptr` in the hint,
and return `let` of it instead of asserting.



_Code quote:_
```XML
        tempvar prev_value;
```


<!-- Sent from Reviewable.io -->

2023-04-15 22:04 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: 8 of 18 files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 327 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSAuoIw2DyX1UiuCgcf:-NT5wXBK-_7PQboony7f:boavv5u) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L327)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
But I think you meant this to be for the new entry libfunc?
</blockquote></details>

yes - but i don;t understand the question.


<!-- Sent from Reviewable.io -->

2023-04-16 05:12 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: 7 of 18 files reviewed, 9 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 887 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSAv86G-mDTQOfPL2HR:-NT7TE9k9Lwb4oZqZLth:b-ispre5) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L887)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Why let? I want to partially write the prev_value to the new access.
</blockquote></details>

No need, it would be validates if you use it.
The prover would still have to write some value that makes sense there 


<!-- Sent from Reviewable.io -->

2023-04-16 12:33 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: 3 of 18 files reviewed, 9 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 327 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSAuoIw2DyX1UiuCgcf:-NT8x8NiD0BkeaUDoK_X:bb7llm6) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L327)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

yes - but i don;t understand the question.
</blockquote></details>

nvm.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 887 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSAv86G-mDTQOfPL2HR:-NT8x1KVBkq9wu3JEjII:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L887)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

No need, it would be validates if you use it.
The prover would still have to write some value that makes sense there 
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 884 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NT5w-xW-iXmUJ5g0gZR:-NT8x0MB03rCJ31cEdvK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ef679177ac028d689e28e5f29adf0797210268c5/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L884)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you should not read the value - just make it available - so write directly to the `dict_ptr` in the hint,
and return `let` of it instead of asserting.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-16 14:06 UTC, orizi reviewed
> Reviewed 13 of 17 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: 14 of 18 files reviewed, 6 unresolved discussions (waiting on @liorgold2)



<!-- Sent from Reviewable.io -->

2023-04-16 15:09 UTC, orizi reviewed
> Reviewed 3 of 17 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: 17 of 18 files reviewed, 6 unresolved discussions (waiting on @liorgold2)



<!-- Sent from Reviewable.io -->

2023-04-16 21:51 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: 17 of 18 files reviewed, 9 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 524 at r7](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTB1VpR4yrUrp5uJKdn:-NTB1VpR4yrUrp5uJKdo:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/45d1b82aeab7d1d71cb5b3a943f23405575cc4a6/tests/e2e_test_data/libfuncs/felt252_dict#L524)):*
> ```
> 
> //! > cairo
> fn foo(dict: Felt252Dict::<felt252>, key: felt252) -> Felt252DictEntry::<felt252> {
> ```

.



_Suggestion:_
```
fn foo(dict: Felt252Dict::<felt252>, key: felt252) -> (Felt252DictEntry::<felt252>, felt252) {
    felt252_dict_entry_get(dict, key)
}
```
___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 567 at r7](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTB1ejtCZ6-fynUREVF:-NTB1ejtCZ6-fynUREVG:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/45d1b82aeab7d1d71cb5b3a943f23405575cc4a6/tests/e2e_test_data/libfuncs/felt252_dict#L567)):*
> ```
> 
> //! > cairo
> fn foo(entry: Felt252DictEntry::<felt252>, value: felt252) -> Felt252Dict::<felt252> {
> ```

.



_Suggestion:_
```
fn foo(entry: Felt252DictEntry::<felt252>, value: felt252) -> Felt252Dict::<felt252> {
    felt252_dict_entry_finalize(entry, value)
}
```
___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 608 at r7](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTB1kNQ7BPXqZBSN34B:-NTB1kNQ7BPXqZBSN34C:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/45d1b82aeab7d1d71cb5b3a943f23405575cc4a6/tests/e2e_test_data/libfuncs/felt252_dict#L608)):*
> ```
> 
> //! > cairo
> fn foo(dict: Felt252Dict::<felt252>, key: felt252, value: felt252) -> Felt252Dict::<felt252> {
> ```

.



_Suggestion:_
```
fn foo(dict: Felt252Dict::<felt252>, k1: felt252, v1: felt252, k2: felt252, v2: felt252) -> (Felt252Dict::<felt252>, felt252, felt252) {
    let (entry, old1) = felt252_dict_entry_get(dict, k1);
    let dict = felt252_dict_entry_finalize(entry, v1);
    let (entry, old2) = felt252_dict_entry_get(dict, k2);
    let dict = felt252_dict_entry_finalize(entry, v2);
    (dict, old1, old2)
}
```


<!-- Sent from Reviewable.io -->

2023-04-17 07:38 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: 14 of 22 files reviewed, 9 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 524 at r7](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTB1VpR4yrUrp5uJKdn:-NTD8V6d6IlI9pRgcvEj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/45d1b82aeab7d1d71cb5b3a943f23405575cc4a6/tests/e2e_test_data/libfuncs/felt252_dict#L524)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 567 at r7](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTB1ejtCZ6-fynUREVF:-NTD8VzP2C5ZVspFLVR2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/45d1b82aeab7d1d71cb5b3a943f23405575cc4a6/tests/e2e_test_data/libfuncs/felt252_dict#L567)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 608 at r7](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTB1kNQ7BPXqZBSN34B:-NTD8X-f-sX1tKqes6iE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/45d1b82aeab7d1d71cb5b3a943f23405575cc4a6/tests/e2e_test_data/libfuncs/felt252_dict#L608)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-17 08:15 UTC, orizi requested changes
> Reviewed 7 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: 21 of 22 files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware and @liorgold2)

___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 74 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTDGs0X38k5gH0bTTUv:-NTDGs0X38k5gH0bTTUw:bea18rp) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/tests/e2e_test_data/libfuncs/felt252_dict#L74)):*
> ```
> //! > ==========================================================================
> 
> //! > felt252_dict_write libfunc
> ```

is this from the next pr by mistake?


<!-- Sent from Reviewable.io -->

2023-04-17 09:05 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: 21 of 22 files reviewed, 8 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 74 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTDGs0X38k5gH0bTTUv:-NTDSVcM2nr_IkM2_lkI:b-9if036) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/tests/e2e_test_data/libfuncs/felt252_dict#L74)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this from the next pr by mistake?
</blockquote></details>

Indeed, done.


<!-- Sent from Reviewable.io -->

2023-04-17 09:17 UTC, orizi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: 21 of 22 files reviewed, 7 unresolved discussions (waiting on @liorgold2)



<!-- Sent from Reviewable.io -->

2023-04-20 15:27 UTC, liorgold2 requested changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 597 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NSBKZHh14wcnvRxLisf:-NTUFPNLED9E5HfeV5FQ:blbh9ap) ([raw file](https://github.com/starkware-libs/cairo/blob/02215725485420a3db207d8e1fd642d14e1e4151/tests/e2e_test_data/libfuncs/felt252_dict#L597)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Why not? The casm and Sierra won't be tested anywhere else.
</blockquote></details>

I was referring to the fact that squash dict was in the output. This is now resolved.
___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 575 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTUF89tDLg9llqkjkfe:-NTUF75T6E5WQT0O1YVY:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/14c91c21e9420483c865715377b7bb81b72e8673/tests/e2e_test_data/libfuncs/felt252_dict#L575)):*
> ```
> %{
> dict_tracker = __dict_manager.get_tracker(memory[fp + -4])
> dict_tracker.data[memory[memory[fp + -4] -3]] = memory[fp + -3]
> ```

.



_Suggestion:_
```
dict_tracker.data[memory[memory[fp + -4] - 3]] = memory[fp + -3]
```
___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 644 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTUGOKl9k41mlIR9Zxh:-NTUGOKl9k41mlIR9Zxi:bk8jg8r) ([raw file](https://github.com/starkware-libs/cairo/blob/14c91c21e9420483c865715377b7bb81b72e8673/tests/e2e_test_data/libfuncs/felt252_dict#L644)):*
> ```
> //! > function_costs
> test::foo: OrderedHashMap({Const: 13880})
> ```

I tried to compute this myself but didn't get this number. Can you check it?



_Code quote:_
```
13880
```


<!-- Sent from Reviewable.io -->

2023-04-20 15:39 UTC, liorgold2 requested changes
> Reviewed 1 of 17 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: all files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 299 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTUJZwUCtsyWW1kNTPL:-NTUJZwUCtsyWW1kNTPM:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/14c91c21e9420483c865715377b7bb81b72e8673/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L299)):*
> ```XML
>                     allow_const: false,
>                 },
>                 ParamSignature {
> ```

.



_Suggestion:_
```XML
ParamSignature::new()
```


<!-- Sent from Reviewable.io -->

2023-04-20 15:46 UTC, liorgold2 requested changes
> Reviewed 1 of 12 files at r3, 3 of 17 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: all files reviewed, 9 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 349 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTUJso802N1OeEBQLqJ:-NTUJso802N1OeEBQLqK:brhumzt) ([raw file](https://github.com/starkware-libs/cairo/blob/14c91c21e9420483c865715377b7bb81b72e8673/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L349)):*
> ```XML
>                     allow_const: false,
>                 },
>                 ParamSignature {
> ```

Same here.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 867 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTUKYfQ3eb2Sm4qZJgx:-NTUKYfQ3eb2Sm4qZJgy:b-2uc5ym) ([raw file](https://github.com/starkware-libs/cairo/blob/14c91c21e9420483c865715377b7bb81b72e8673/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L867)):*
> ```XML
> }
> 
> /// Handles instruction for creating a new dict entry.
> ```

Same below.



_Suggestion:_
```XML
/// Builds instructions for creating a new dict entry.
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 878 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTUKilT5JLaY9ZEwJI4:-NTUKilT5JLaY9ZEwJI5:btvotfk) ([raw file](https://github.com/starkware-libs/cairo/blob/14c91c21e9420483c865715377b7bb81b72e8673/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L878)):*
> ```XML
>         assert key = *(dict_ptr++);
>         let prev_value = *(dict_ptr++);
>         // The new value will be written in the entry finalize;
> ```

(or: `in felt252_dict_entry_finalize()`)



_Suggestion:_
```XML
       // The new value will be written in the entry finalization.
```


<!-- Sent from Reviewable.io -->

2023-04-20 15:48 UTC, liorgold2 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: all files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 644 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTUGOKl9k41mlIR9Zxh:-NTULEyy9iCswXKeugg7:bvmkkzn) ([raw file](https://github.com/starkware-libs/cairo/blob/14c91c21e9420483c865715377b7bb81b72e8673/tests/e2e_test_data/libfuncs/felt252_dict#L644)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I tried to compute this myself but didn't get this number. Can you check it?
</blockquote></details>

Never mind, I now see it's not rebased.
This is the computation: `(5200 + 6 * 70 + 900 + 1 * 70) * 2 + 700 = 13880`.


<!-- Sent from Reviewable.io -->

2023-04-20 15:50 UTC, liorgold2 reviewed
> Reviewed 4 of 17 files at r6, 2 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: all files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware and @orizi)



<!-- Sent from Reviewable.io -->

2023-04-20 15:51 UTC, liorgold2 reviewed
> Reviewed 1 of 17 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: all files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware and @orizi)



<!-- Sent from Reviewable.io -->

2023-04-20 15:54 UTC, liorgold2 requested changes
> Reviewed 2 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: all files reviewed, 9 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/traits.cairo` line 117 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTUM_Kp6hkpVhQuGYHl:-NTUM_KqAsNw5twJf695:b-lz8xgg) ([raw file](https://github.com/starkware-libs/cairo/blob/14c91c21e9420483c865715377b7bb81b72e8673/corelib/src/traits.cairo#L117)):*
> ```Cairo
> }
> 
> /// Trait for default values of value in a dict. Should be logically equivalent to 0.
> ```

Explain more.
`Trait for default values` - this is not true. The trait is for values, not default values.
`Should be logically equivalent to 0` is not a good description of the property we're trying to capture here.

Also, separate the general description of the trait and the details with a blank line.


<!-- Sent from Reviewable.io -->

2023-04-20 15:56 UTC, liorgold2 requested changes
> Reviewed 1 of 17 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: all files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/test/dict_test.cairo` line 72 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTUNDlP7uMitqg21Qj8:-NTUNDlQ8kfwKmhl2W_3:b-6zav72) ([raw file](https://github.com/starkware-libs/cairo/blob/14c91c21e9420483c865715377b7bb81b72e8673/corelib/src/test/dict_test.cairo#L72)):*
> ```Cairo
> 
> #[test]
> fn test_dict_entry_destruct() {
> ```

Document this test, specifically mentioning that you're testing the destruction of the dict entry before finalization.


<!-- Sent from Reviewable.io -->

2023-04-20 16:14 UTC, orizi approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: all files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2023-04-23 12:03 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: 2 of 22 files reviewed, 8 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`corelib/src/traits.cairo` line 117 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTUM_Kp6hkpVhQuGYHl:-NThJ3ibADdB94bMn_Ls:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/14c91c21e9420483c865715377b7bb81b72e8673/corelib/src/traits.cairo#L117)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Explain more.
`Trait for default values` - this is not true. The trait is for values, not default values.
`Should be logically equivalent to 0` is not a good description of the property we're trying to capture here.

Also, separate the general description of the trait and the details with a blank line.
</blockquote></details>

Done.
___
*[`corelib/src/test/dict_test.cairo` line 72 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTUNDlP7uMitqg21Qj8:-NThJ4dK5ItdNO2zpoMn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/14c91c21e9420483c865715377b7bb81b72e8673/corelib/src/test/dict_test.cairo#L72)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Document this test, specifically mentioning that you're testing the destruction of the dict entry before finalization.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 299 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTUJZwUCtsyWW1kNTPL:-NThdRqn8oMf_rebaW3t:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/14c91c21e9420483c865715377b7bb81b72e8673/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L299)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 315 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTUJfvO6xPChEYNSWBO:-NThdTTI9P9XpiwZGMEW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/14c91c21e9420483c865715377b7bb81b72e8673/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L315)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This is wrong.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs` line 349 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTUJso802N1OeEBQLqJ:-NThdkPs3SOzvp32LxmP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/14c91c21e9420483c865715377b7bb81b72e8673/crates/cairo-lang-sierra/src/extensions/modules/felt252_dict.rs#L349)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 867 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTUKYfQ3eb2Sm4qZJgx:-NThhDe8-0rbu1WaTsCP:b1nj3n3) ([raw file](https://github.com/starkware-libs/cairo/blob/14c91c21e9420483c865715377b7bb81b72e8673/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L867)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Same below.
</blockquote></details>

Done, but this convention is all over the sierra_to_casm crate.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 878 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTUKilT5JLaY9ZEwJI4:-NThhM8M4RPuLe1VnOmk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/14c91c21e9420483c865715377b7bb81b72e8673/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L878)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

(or: `in felt252_dict_entry_finalize()`)
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/felt252_dict` line 575 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTUF89tDLg9llqkjkfe:-NThhYox6MfUONCdoS-x:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/14c91c21e9420483c865715377b7bb81b72e8673/tests/e2e_test_data/libfuncs/felt252_dict#L575)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-23 14:41 UTC, orizi reviewed
> Reviewed 17 of 20 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: 20 of 22 files reviewed, 8 unresolved discussions (waiting on @liorgold2)



<!-- Sent from Reviewable.io -->

2023-04-23 14:42 UTC, orizi approved these changes
> Reviewed 2 of 20 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: all files reviewed, 8 unresolved discussions (waiting on @liorgold2)



<!-- Sent from Reviewable.io -->

2023-04-23 21:32 UTC, liorgold2 requested changes
> Reviewed 11 of 20 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`corelib/src/lib.cairo` line 225 at r11](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTk0saf1xkPgbe2rfde:-NTk0saf1xkPgbe2rfdf:b1ukhu1) ([raw file](https://github.com/starkware-libs/cairo/blob/8d327ba6b5363697974630802837e5357b1cbcfd/corelib/src/lib.cairo#L225)):*
> ```Cairo
> use dict::Felt252DictTrait;
> use dict::Felt252DictEntry;
> use dict::felt252_dict_entry_get;
> ```

Should we put the two functions here? I guess no one will use them directly, right?
Same question for the type. People can always use it with `dict::`.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs` line 878 at r9](https://reviewable.io/reviews/starkware-libs/cairo/2678#-NTUKilT5JLaY9ZEwJI4:-NTk-5IS6-Ffed_019rF:b40tics) ([raw file](https://github.com/starkware-libs/cairo/blob/14c91c21e9420483c865715377b7bb81b72e8673/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L878)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Fix the `;` as well.


<!-- Sent from Reviewable.io -->

2023-04-23 21:33 UTC, liorgold2 reviewed
> Reviewed 1 of 20 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2023-04-24 09:02 UTC, liorgold2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2678#-:-NTmUvwS5HPc-qR4EisK:bnfp4nl)* status: 20 of 22 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)



<!-- Sent from Reviewable.io -->

2023-04-24 09:11 UTC, merged