Types docs.
starkware-libs/cairo pull request #2686
Opened 2023-04-02 11:58 UTC by gilbens-starkware

2023-04-02 12:32 UTC, gilbens-starkware reviewed
Not yet ready.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2686#-:-NS0x5Kt8GxRr1ixDR1A:b-ylxbez)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @spapinistarkware and @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-04-02 13:27 UTC, gilbens-starkware reviewed
Ready.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2686#-:-NS18QVm3roUmGrygOQJ:byotcgg)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @spapinistarkware and @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-04-02 13:54 UTC, spapinistarkware requested changes
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2686)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`docs/reference/src/boolean.adoc` line 25 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1Ecqa3r8AwafBmLhN:-NS1Ecqa3r8AwafBmLhO:b-gsr217) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/boolean.adoc#L25)):*
> ```AsciiDoc
> === Logical not ===
> // Not logical table
> |===
> ```

Consider not specifying the truth tables.
___
*[`docs/reference/src/integer.adoc` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1Ej6Z6XUyQ7IQ6uuF:-NS1Ej6Z6XUyQ7IQ6uuG:b-8xm3lx) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/integer.adoc#L4)):*
> ```AsciiDoc
> // Cairo compiler integers
> The Cairo compiler uses the following integer types:
> ```

Mention usize
___
*[`docs/reference/src/integer.adoc` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1EohP5YJUt9q9D6Op:-NS1EohQD0b7VroGEXUO:b3jdb27) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/integer.adoc#L18)):*
> ```AsciiDoc
> == Integer creation
> 
> All integers except the `u256` can be created by using the integer literal using the appropriate suffix. The `u256` type is only supported by casting from other types.
> ```

Mention that this is temporary


<!-- Sent from Reviewable.io -->

2023-04-02 13:55 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2686)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`docs/reference/src/types.adoc` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1EyFe9-i3eitMxzQe:-NS1EyFe9-i3eitMxzQf:bqzian2) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/types.adoc#L24)):*
> ```AsciiDoc
> * Pointer types:
> ** Box
> // should we add snapshot and ref in here?
> ```

snapshot - yes. ref - no.


<!-- Sent from Reviewable.io -->

2023-04-02 13:55 UTC, spapinistarkware reviewed
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2686)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-04-02 14:26 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2686)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`docs/reference/src/boolean.adoc` line 25 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1Ecqa3r8AwafBmLhN:-NS1FPuo0ogjDGyMQ6Vy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/boolean.adoc#L25)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider not specifying the truth tables.
</blockquote></details>

Done.
___
*[`docs/reference/src/integer.adoc` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1Ej6Z6XUyQ7IQ6uuF:-NS1Lc3k8epu_cNBvUED:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/integer.adoc#L4)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Mention usize
</blockquote></details>

Done.
___
*[`docs/reference/src/integer.adoc` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1EohP5YJUt9q9D6Op:-NS1LbUY6xbD7snF2OES:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/integer.adoc#L18)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Mention that this is temporary
</blockquote></details>

Done.
___
*[`docs/reference/src/types.adoc` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1EyFe9-i3eitMxzQe:-NS1M9SS5jer2gy5jp20:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/types.adoc#L24)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

snapshot - yes. ref - no.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-02 14:35 UTC, spapinistarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2686#-:-NS1O869-tIwoXKKJcQk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-04-02 15:53 UTC, yuvalsw requested changes
> Reviewed 3 of 3 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2686)* status: all files reviewed, 24 unresolved discussions (waiting on @gilbens-starkware)

___
*[`docs/reference/src/boolean.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1BLFH8sW6oCG2XanM:-NS1BLFH8sW6oCG2XanN:btviitw) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/boolean.adoc#L3)):*
> ```AsciiDoc
> = Boolean
> 
> The Boolean type in Cairo represents a logical value of either true or false. The Boolean type is used to represent the result of a logical expression. 
> ```

I think "in Cairo" is redundant.



_Suggestion:_
```AsciiDoc
The boolean type represents a logical value of either true or false
```
___
*[`docs/reference/src/boolean.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1BZoZBlHDj9LilBH6:-NS1BZoZBlHDj9LilBH7:b-x41dg) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/boolean.adoc#L3)):*
> ```AsciiDoc
> = Boolean
> 
> The Boolean type in Cairo represents a logical value of either true or false. The Boolean type is used to represent the result of a logical expression. 
> ```

Isn't this redundant too?



_Code quote:_
```AsciiDoc
The Boolean type is used to represent the result of a logical expression.·
```
___
*[`docs/reference/src/boolean.adoc` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1BlbW6Xq7NJnGwaQF:-NS1BlbW6Xq7NJnGwaQG:b-ricyu0) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/boolean.adoc#L5)):*
> ```AsciiDoc
> The Boolean type in Cairo represents a logical value of either true or false. The Boolean type is used to represent the result of a logical expression. 
> 
> The Boolean type is represented by the keyword `bool`. Values of this type are created using the keywrods `true` and `false`.
> ```

suggestion. If not - at least s/Boolean/boolean/.



_Suggestion:_
```AsciiDoc
It is represented by the keyword `bool`
```
___
*[`docs/reference/src/boolean.adoc` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1BuuR4l8I-kQswQGF:-NS1BuuR4l8I-kQswQGG:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/boolean.adoc#L5)):*
> ```AsciiDoc
> The Boolean type in Cairo represents a logical value of either true or false. The Boolean type is used to represent the result of a logical expression. 
> 
> The Boolean type is represented by the keyword `bool`. Values of this type are created using the keywrods `true` and `false`.
> ```





_Suggestion:_
```AsciiDoc
words
```
___
*[`docs/reference/src/boolean.adoc` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1BxAx2tmlblh_4hDc:-NS1BxAx2tmlblh_4hDd:b-1kbyv3) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/boolean.adoc#L5)):*
> ```AsciiDoc
> The Boolean type in Cairo represents a logical value of either true or false. The Boolean type is used to represent the result of a logical expression. 
> 
> The Boolean type is represented by the keyword `bool`. Values of this type are created using the keywrods `true` and `false`.
> ```

please mention the keyword `bool` in the example below. For example in one of the let x/y.
___
*[`docs/reference/src/boolean.adoc` line 15 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1CJ14BQ0Kb4pgjCla:-NS1CJ14BQ0Kb4pgjClb:bfbffx6) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/boolean.adoc#L15)):*
> ```AsciiDoc
>     let z1 = x | y; // w is true
>     let z2 = x & y; // z is false
>     let z3 = !x; // z is false
> ```

w/z in the comments should be z1-z4.
Anyway - I think the bitwise operations should go in a different section of this page, not immediately here.



_Code quote:_
```AsciiDoc
    let z1 = x | y; // w is true
    let z2 = x & y; // z is false
    let z3 = !x; // z is false
    let z4 = x ^ y; // z is true
```
___
*[`docs/reference/src/boolean.adoc` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1CqsV5S7P14V-Pnhs:-NS1CqsV5S7P14V-Pnht:b-99ibgy) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/boolean.adoc#L21)):*
> ```AsciiDoc
> 
> == Operators ==
> The following operators are defined for the Boolean type:
> ```

Do we really want to give here the tables of boolean operators? It's not specific to Cairo. We can just mention what operator each character represents.
Also - remember that this should probably mention ||, && eventually.

If you end up leaving the tables - can you make the first row a "title"?



_Suggestion:_
```AsciiDoc
he following operators are defined for the boolean type:
```
___
*[`docs/reference/src/felt252dict.adoc` line 0 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1HMIW3f0M2b4E8hNR:-NS1HMIW3f0M2b4E8hNS:b2od5qx) ([raw file](https://github.com/starkware-libs/cairo/blob/445638d758e8250b381a51a51704e48ca90754cf/docs/reference/src/felt252dict.adoc#L0)):*
Please add a TODO.
___
*[`docs/reference/src/integer.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1Dtvv5kT1sFaeVmDU:-NS1Dtvv5kT1sFaeVmDV:baswlng) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/integer.adoc#L3)):*
> ```AsciiDoc
> = Integers
> // Cairo compiler integers
> The Cairo compiler uses the following integer types:
> ```

this doesn't show for some reason.
Is there any reason to leave the comments?

Also, I suggest "Cairo uses the ..."



_Code quote:_
```AsciiDoc
he Cairo compiler uses the following integer types:
```
___
*[`docs/reference/src/integer.adoc` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1Dpq0-92Y18wyp8F3:-NS1Dpq0-92Y18wyp8F4:b-hfpv1m) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/integer.adoc#L5)):*
> ```AsciiDoc
> The Cairo compiler uses the following integer types:
> 
> // Integers table
> ```

remove?



_Code quote:_
```AsciiDoc
// Integers table
```
___
*[`docs/reference/src/integer.adoc` line 16 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1EAm64PrYZofgMJ7w:-NS1EAm64PrYZofgMJ7x:b-rkhi0f) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/integer.adoc#L16)):*
> ```AsciiDoc
> |===
> 
> == Integer creation
> ```

in all this PR - capital letters in headings.



_Code quote:_
```AsciiDoc
creation
```
___
*[`docs/reference/src/integer.adoc` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1EOK--BhViW14Tiwj:-NS1EOK--BhViW14Tiwk:b-3qnc53) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/integer.adoc#L18)):*
> ```AsciiDoc
> == Integer creation
> 
> All integers except the `u256` can be created by using the integer literal using the appropriate suffix. The `u256` type is only supported by casting from other types.
> ```

suggestion



_Suggestion:_
```AsciiDoc
All integer types except `u256` can be created as literals using the appropriate suffix. 
```
___
*[`docs/reference/src/integer.adoc` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1EdVV8CaWegZCD3TB:-NS1EdVV8CaWegZCD3TC:bqn5oqr) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/integer.adoc#L18)):*
> ```AsciiDoc
> == Integer creation
> 
> All integers except the `u256` can be created by using the integer lite [...]

2023-04-03 06:21 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2686)* status: all files reviewed, 14 unresolved discussions (waiting on @yuvalsw)

___
*[`docs/reference/src/boolean.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1BZoZBlHDj9LilBH6:-NS4evaJD1QKyTP_gvX-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/boolean.adoc#L3)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Isn't this redundant too?
</blockquote></details>

Done.
___
*[`docs/reference/src/boolean.adoc` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1BxAx2tmlblh_4hDc:-NS4f3h15oBRMXdS5SxN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/boolean.adoc#L5)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please mention the keyword `bool` in the example below. For example in one of the let x/y.
</blockquote></details>

Done.
___
*[`docs/reference/src/boolean.adoc` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1CqsV5S7P14V-Pnhs:-NS4fQYZ08pHAmZwlPxf:b-r20obg) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/boolean.adoc#L21)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Do we really want to give here the tables of boolean operators? It's not specific to Cairo. We can just mention what operator each character represents.
Also - remember that this should probably mention ||, && eventually.

If you end up leaving the tables - can you make the first row a "title"?

</blockquote></details>

Isn't this exactly that? It's just mention what operation each symbol represents + an example.
Changed it to title. 
___
*[`docs/reference/src/felt252dict.adoc` line  at r2](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1HMIW3f0M2b4E8hNR:-NS4gKeU67bRQjH7kv4e:bpn19cf) ([raw file](https://github.com/starkware-libs/cairo/blob/445638d758e8250b381a51a51704e48ca90754cf/docs/reference/src/felt252dict.adoc#L)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Please add a TODO.
</blockquote></details>

Removed the file, it was added by mistake,
___
*[`docs/reference/src/integer.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1Dtvv5kT1sFaeVmDU:-NS4gc943I-JlCtIzuY2:b-4jyk13) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/integer.adoc#L3)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

this doesn't show for some reason.
Is there any reason to leave the comments?

Also, I suggest "Cairo uses the ..."
</blockquote></details>

It does for me, anyway, removed the comments, maybe now you'll see it?
___
*[`docs/reference/src/integer.adoc` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1Dpq0-92Y18wyp8F3:-NS4gko2DkeLssj8B-78:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/integer.adoc#L5)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

remove?
</blockquote></details>

Done.
___
*[`docs/reference/src/integer.adoc` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1EohP5YJUt9q9D6Op:-NS4hOxRCx51hSqovnqL:bi48hdl) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/integer.adoc#L18)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I would just say "currently". IIUC we decided not to mention future stuff here.
</blockquote></details>

Agree, changed
___
*[`docs/reference/src/integer.adoc` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1EdVV8CaWegZCD3TB:-NS4hYvz63-glSTbHLPg:b-1n5oy4) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/integer.adoc#L18)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

You can build it - it's a user defined type.
```
let x = u256 {high: 1_u128, low: 2_u128}
```
</blockquote></details>

Changed casting to construction, question is which way we want to endorse, the struct constructor or the function?
___
*[`docs/reference/src/integer.adoc` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1FS-uDD7KvZt3yKxI:-NS4igah6l420K0F1yiQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/integer.adoc#L37)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

maybe?
</blockquote></details>

Done.
___
*[`docs/reference/src/integer.adoc` line 16 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1LW934MPFo1BppWAR:-NS4gsSCDLp5_pJepqKo:bufq0pr) ([raw file](https://github.com/starkware-libs/cairo/blob/18625a6fcac6eaa2e246dcb6b886b7dbf4fa674c/docs/reference/src/integer.adoc#L16)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Suggestion.
Also - why not mention with the rest of the types? What are the min/max values?
</blockquote></details>

I think we shouldn't commit to these values, maybe it'll be "machine" dependent (machine as in casm vs llvm)
___
*[`docs/reference/src/integer.adoc` line 20 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1Lp265ZyPifeKe1EQ:-NS4iS4wBLCtyWjQ16wq:b-bvxm04) ([raw file](https://github.com/starkware-libs/cairo/blob/18625a6fcac6eaa2e246dcb6b886b7dbf4fa674c/docs/reference/src/integer.adoc#L20)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

usize too?
</blockquote></details>

usize is an alias to u32, it supports it all.
___
*[`docs/reference/src/integer.adoc` line 53 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1LwIaAhtHnNbbsAXJ:-NS4jKw27KshsjC8-llK:b-hud9rn) ([raw file](https://github.com/starkware-libs/cairo/blob/18625a6fcac6eaa2e246dcb6b886b7dbf4fa674c/docs/reference/src/integer.adoc#L53)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think we decided not to mention things that will be supported in the future.
</blockquote></details>

These are all supported.
___
*[`docs/reference/src/types.adoc` line 6 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1Gd8SBQWlB_D8bMIs:-NS4jzd_DSfPCEe5hqHv:bmkxuw9) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/types.adoc#L6)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

1. please wrap all types with ``
2. Please add TODOs to add links.
</blockquote></details>

Not sure about 2, what do we define as type? Is Array a type or just describes the container?


<!-- Sent from Reviewable.io -->

2023-04-03 10:49 UTC, yuvalsw requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2686)* status: all files reviewed, 12 unresolved discussions (waiting on @gilbens-starkware)

___
*[`docs/reference/src/boolean.adoc` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1CqsV5S7P14V-Pnhs:-NS5fhNI5CT75qQDu-lb:b-1fn5yo) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/boolean.adoc#L21)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Isn't this exactly that? It's just mention what operation each symbol represents + an example.
Changed it to title. 
</blockquote></details>

Yes, I wrote it before you removed the truth tables.
___
*[`docs/reference/src/boolean.adoc` line 13 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS5fvV_DGpRQFP7sodo:-NS5fvV_DGpRQFP7sodp:baz7ax5) ([raw file](https://github.com/starkware-libs/cairo/blob/228285d148d4bfbf717f3ad53ef6bf6cb5a0a6a2/docs/reference/src/boolean.adoc#L13)):*
> ```AsciiDoc
> |===
> |Operator|Description|Example
> |`\|`|Logical OR|`x \| y`
> ```

aren't those called bitwise OR/AND?



_Code quote:_
```AsciiDoc
|`\|`|Logical OR|`x \| y`
|`&`|Logical AND|`x & y`
```
___
*[`docs/reference/src/boolean.adoc` line 15 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS5i3mQ34XirzJo0XZQ:-NS5i3mQ34XirzJo0XZR:b-fxq5uv) ([raw file](https://github.com/starkware-libs/cairo/blob/228285d148d4bfbf717f3ad53ef6bf6cb5a0a6a2/docs/reference/src/boolean.adoc#L15)):*
> ```AsciiDoc
> |`\|`|Logical OR|`x \| y`
> |`&`|Logical AND|`x & y`
> |`!`|Logical NOT|`!x`
> ```

isn't bitwise xor supported?
___
*[`docs/reference/src/boolean.adoc` line 28 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS5f_n71LDDzVembfz2:-NS5f_n71LDDzVembfz3:bbu7ofh) ([raw file](https://github.com/starkware-libs/cairo/blob/228285d148d4bfbf717f3ad53ef6bf6cb5a0a6a2/docs/reference/src/boolean.adoc#L28)):*
> ```AsciiDoc
>     let z1 = x | y; // z1 is true
>     let z2 = x & y; // z2 is false
>     let z3 = !x; // z3 is false
> ```

please align with the other comments.



_Code quote:_
```AsciiDoc
 // z3 is false
```
___
*[`docs/reference/src/integer.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1Dtvv5kT1sFaeVmDU:-NS5gF2I69lUuv9POSfl:b-1yhnz3) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/integer.adoc#L3)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

It does for me, anyway, removed the comments, maybe now you'll see it?
</blockquote></details>

Still doesn't show for me. What if you add a blank line after the heading?
___
*[`docs/reference/src/integer.adoc` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1EdVV8CaWegZCD3TB:-NS5h3AK8mjRJg2SC9DR:b3bnhu5) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/integer.adoc#L18)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Changed casting to construction, question is which way we want to endorse, the struct constructor or the function?
</blockquote></details>

I am not sure, but anyway we should support _u256.
___
*[`docs/reference/src/integer.adoc` line 16 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1LW934MPFo1BppWAR:-NS5gY2d-UFKUFaBCqd-:b-t3dyod) ([raw file](https://github.com/starkware-libs/cairo/blob/18625a6fcac6eaa2e246dcb6b886b7dbf4fa674c/docs/reference/src/integer.adoc#L16)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

I think we shouldn't commit to these values, maybe it'll be "machine" dependent (machine as in casm vs llvm)
</blockquote></details>

OK. But isn't it important to mention what it is today? People should know if they can put 256 in it or not...

What about the suggestion? "also" and "in addition" have the same meaning. And I think "compiler" is not a must here (but up to you).
___
*[`docs/reference/src/integer.adoc` line 30 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS5hfd9-tdGxLfvnL9H:-NS5hfd9-tdGxLfvnL9I:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/228285d148d4bfbf717f3ad53ef6bf6cb5a0a6a2/docs/reference/src/integer.adoc#L30)):*
> ```AsciiDoc
> 
> == Integer Operations
> Currently, all integer types but `u256` support the operations in following table.
> ```





_Suggestion:_
```AsciiDoc
ns in the following ta
```
___
*[`docs/reference/src/types.adoc` line 2 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS5iDA42W13Jreqm6FJ:-NS5iDA42W13Jreqm6FK:b4h0ily) ([raw file](https://github.com/starkware-libs/cairo/blob/228285d148d4bfbf717f3ad53ef6bf6cb5a0a6a2/docs/reference/src/types.adoc#L2)):*
> ```AsciiDoc
> = Types
> Cairo is strongly-typed and offers a variety of types to represent a variety of types to represent
> ```

repetition



_Code quote:_
```AsciiDoc
 and offers a variety of types to represent a variety of types to represent
```
___
*[`docs/reference/src/types.adoc` line 11 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS5iXBlBg72f0wjxERY:-NS5iXBlBg72f0wjxERZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/228285d148d4bfbf717f3ad53ef6bf6cb5a0a6a2/docs/reference/src/types.adoc#L11)):*
> ```AsciiDoc
> *** `felt252`
> *** link:integer.adoc[Integers]
> ** Never type.
> ```





_Suggestion:_
```AsciiDoc
ever type
```
___
*[`docs/reference/src/types.adoc` line 16 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS5i_WU7YHtUQZsfQTm:-NS5i_WU7YHtUQZsfQTn:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/228285d148d4bfbf717f3ad53ef6bf6cb5a0a6a2/docs/reference/src/types.adoc#L16)):*
> ```AsciiDoc
> ** Tuple
> ** `Array`
> ** `felt252Dict`
> ```





_Suggestion:_
```AsciiDoc
`Felt252Dict
```
___
*[`docs/reference/src/types.adoc` line 19 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS5inV14tEM7APsITxZ:-NS5inV14tEM7APsITx_:bdcycct) ([raw file](https://github.com/starkware-libs/cairo/blob/228285d148d4bfbf717f3ad53ef6bf6cb5a0a6a2/docs/reference/src/types.adoc#L19)):*
> ```AsciiDoc
> * Pointer types:
> ** `Box`
> ** `snapshot`
> ```

remove ``, it's not a syntax



_Code quote:_
```AsciiDoc
`snapshot`
```


<!-- Sent from Reviewable.io -->

2023-04-03 12:00 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2686)* status: all files reviewed, 7 unresolved discussions (waiting on @yuvalsw)

___
*[`docs/reference/src/boolean.adoc` line 13 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS5fvV_DGpRQFP7sodo:-NS5m15j2AmYUpuprBXQ:bxlbcas) ([raw file](https://github.com/starkware-libs/cairo/blob/228285d148d4bfbf717f3ad53ef6bf6cb5a0a6a2/docs/reference/src/boolean.adoc#L13)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

aren't those called bitwise OR/AND?
</blockquote></details>

Under the hood yes, but they are referred to as logical and/or in 2 of the 3 languages I checked for reference. && and || are called lazy logical operators in rust and conditional logical operators in c#, in c++ it is indeed called bitwise and logical operators. I tried to remain similar to rust, but I won't object if we decide to change it.
___
*[`docs/reference/src/boolean.adoc` line 15 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS5i3mQ34XirzJo0XZQ:-NS5opp_AnCVEmw_8qLh:b-s1bt18) ([raw file](https://github.com/starkware-libs/cairo/blob/228285d148d4bfbf717f3ad53ef6bf6cb5a0a6a2/docs/reference/src/boolean.adoc#L15)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

isn't bitwise xor supported?
</blockquote></details>

Yes, added.
___
*[`docs/reference/src/integer.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1Dtvv5kT1sFaeVmDU:-NS5rWrW8QtiJmVyNz33:bot30hc) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/integer.adoc#L3)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Still doesn't show for me. What if you add a blank line after the heading?
</blockquote></details>

Looks the same in vscode, but I see the difference in asciidoclive,
___
*[`docs/reference/src/integer.adoc` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1EdVV8CaWegZCD3TB:-NS5p5UV80LbN4Zc43od:b-i53nnr) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/integer.adoc#L18)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I am not sure, but anyway we should support _u256.
</blockquote></details>

Not sure that we should, it is cost much more than any other integer type, anyway i'll leave the `as_u256` for now.
___
*[`docs/reference/src/integer.adoc` line 16 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1LW934MPFo1BppWAR:-NS5yt693G_y38mROMFG:blp5fu) ([raw file](https://github.com/starkware-libs/cairo/blob/18625a6fcac6eaa2e246dcb6b886b7dbf4fa674c/docs/reference/src/integer.adoc#L16)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

OK. But isn't it important to mention what it is today? People should know if they can put 256 in it or not...

What about the suggestion? "also" and "in addition" have the same meaning. And I think "compiler" is not a must here (but up to you).
</blockquote></details>

Changed it to include usize with all the other types.
___
*[`docs/reference/src/types.adoc` line 2 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS5iDA42W13Jreqm6FJ:-NS5w7va6dKpQbpbphVZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/228285d148d4bfbf717f3ad53ef6bf6cb5a0a6a2/docs/reference/src/types.adoc#L2)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

repetition
</blockquote></details>

Done.
___
*[`docs/reference/src/types.adoc` line 16 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS5i_WU7YHtUQZsfQTm:-NS5wG7_8vv8dqjMMroI:bcooqjd) ([raw file](https://github.com/starkware-libs/cairo/blob/228285d148d4bfbf717f3ad53ef6bf6cb5a0a6a2/docs/reference/src/types.adoc#L16)):*
> ```AsciiDoc
> ** Tuple
> ** `Array`
> ** `felt252Dict`
> ```

I think it should be either lower case since it is the name of the type, or `Dict`/`Dictionary`, wdyt?


<!-- Sent from Reviewable.io -->

2023-04-03 14:51 UTC, yuvalsw requested changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2686)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware)

___
*[`docs/reference/src/boolean.adoc` line 13 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS5fvV_DGpRQFP7sodo:-NS6ZuOZ6FT1lqe2s3lX:b-og5z3v) ([raw file](https://github.com/starkware-libs/cairo/blob/228285d148d4bfbf717f3ad53ef6bf6cb5a0a6a2/docs/reference/src/boolean.adoc#L13)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Under the hood yes, but they are referred to as logical and/or in 2 of the 3 languages I checked for reference. && and || are called lazy logical operators in rust and conditional logical operators in c#, in c++ it is indeed called bitwise and logical operators. I tried to remain similar to rust, but I won't object if we decide to change it.
</blockquote></details>

In the integer doc you use "bitwise".
Please ask for another opinion and LMK. Anyway - be consistent.
___
*[`docs/reference/src/integer.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1Dtvv5kT1sFaeVmDU:-NS6_Alw4ZkTbm3RUfPT:br3velh) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/integer.adoc#L3)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Looks the same in vscode, but I see the difference in asciidoclive,
</blockquote></details>

Still. Please see in github:
https://github.com/starkware-libs/cairo/blob/975aa2ae2cd491f636e2535b79fa2ad81945058f/docs/reference/src/integer.adoc
___
*[`docs/reference/src/integer.adoc` line 16 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1LW934MPFo1BppWAR:-NS6_MrX7HlMwL6IYTNs:b-osv11n) ([raw file](https://github.com/starkware-libs/cairo/blob/18625a6fcac6eaa2e246dcb6b886b7dbf4fa674c/docs/reference/src/integer.adoc#L16)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Changed it to include usize with all the other types.
</blockquote></details>

You actually convinced me not to put it there. But I thought we should mention something about it's current behavior. Please ask for another opinion on this too.
___
*[`docs/reference/src/types.adoc` line 16 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS5i_WU7YHtUQZsfQTm:-NS6aD-82wqrrBQ9KU4P:b-878ws6) ([raw file](https://github.com/starkware-libs/cairo/blob/228285d148d4bfbf717f3ad53ef6bf6cb5a0a6a2/docs/reference/src/types.adoc#L16)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

I think it should be either lower case since it is the name of the type, or `Dict`/`Dictionary`, wdyt?
</blockquote></details>

the name of the type is `Felt252Dict`.
If you choose so, I am also OK with writing "Dictionary" here, with a link to the relevant doc.


<!-- Sent from Reviewable.io -->

2023-04-04 08:57 UTC, yuvalsw reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2686)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2023-04-04 10:51 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2686)* status: all files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`docs/reference/src/boolean.adoc` line 13 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS5fvV_DGpRQFP7sodo:-NS6dWs29cGmZe9Dr1jf:bd5sex8) ([raw file](https://github.com/starkware-libs/cairo/blob/228285d148d4bfbf717f3ad53ef6bf6cb5a0a6a2/docs/reference/src/boolean.adoc#L13)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

In the integer doc you use "bitwise".
Please ask for another opinion and LMK. Anyway - be consistent.
</blockquote></details>

Changed to And/Or as discussed.
___
*[`docs/reference/src/integer.adoc` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1Dtvv5kT1sFaeVmDU:-NSA9LJBEGckZSkCckax:bc32dnj) ([raw file](https://github.com/starkware-libs/cairo/blob/09cd80e0d7f3a951f3e723fe6ba667cafa983806/docs/reference/src/integer.adoc#L3)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Still. Please see in github:
https://github.com/starkware-libs/cairo/blob/975aa2ae2cd491f636e2535b79fa2ad81945058f/docs/reference/src/integer.adoc
</blockquote></details>

Now it seems right.
___
*[`docs/reference/src/integer.adoc` line 16 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2686#-NS1LW934MPFo1BppWAR:-NSAsv0q7GIvyo5TIKBn:byblzjj) ([raw file](https://github.com/starkware-libs/cairo/blob/18625a6fcac6eaa2e246dcb6b886b7dbf4fa674c/docs/reference/src/integer.adoc#L16)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

You actually convinced me not to put it there. But I thought we should mention something about it's current behavior. Please ask for another opinion on this too.
</blockquote></details>

Changed it to some hybrid version.


<!-- Sent from Reviewable.io -->

2023-04-04 14:14 UTC, merged