Added Straknet contracts documentation
starkware-libs/cairo pull request #2687
Opened 2023-04-02 12:07 UTC by yuvalsw

2023-04-02 12:28 UTC, ilyalesokhin-starkware commented
*[`docs/reference/src/contracts.adoc` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS0vznt2cxCNaREMSjg:-NS0vznt2cxCNaREMSjh:bq2caaz) ([raw file](https://github.com/starkware-libs/cairo/blob/be59b5ec641c49b43d7161f74ff906533d4b8063/docs/reference/src/contracts.adoc#L36)):*
> ```AsciiDoc
> In a contract, you can define a struct named `Storage`. The members of this struct are the storage variables.
> 
> The storage variables may be of any Cairo type, including structs, arrays, and tuples, or mappings (TODO(yg)).
> ```

We support types that can be serialized and legacy mapping.



_Code quote:_
```AsciiDoc
The storage variables may be of any Cairo type, including structs, arrays, and tuples, or mappings (TODO(yg)).
```


<!-- Sent from Reviewable.io -->

2023-04-02 12:31 UTC, ilyalesokhin-starkware commented
*[`docs/reference/src/contracts.adoc` line 55 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS0wNG-35RyRCVuOhSt:-NS0wNG-35RyRCVuOhSu:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/be59b5ec641c49b43d7161f74ff906533d4b8063/docs/reference/src/contracts.adoc#L55)):*
> ```AsciiDoc
> - `#[constructor]` function is called when the contract is deployed. There may be only one such function. If it is not defined, the contract is deployed with all storage variables default-initialized.
> - `#[l1_handler]` functions are called when the contract receives a message from L1.
> - `#[event]` functions are signals to the Starknet Operating System. They can be called by the contract itself or by another contract.
> ```





_Suggestion:_
```AsciiDoc
#[event]` functions raise an event on Starknet. They can be called by the contract itself.
```


<!-- Sent from Reviewable.io -->

2023-04-02 12:34 UTC, ilyalesokhin-starkware commented
*[`docs/reference/src/contracts.adoc` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS0xASZ79A2WWIfZ4LO:-NS0xASZ79A2WWIfZ4LP:b-rqs2oz) ([raw file](https://github.com/starkware-libs/cairo/blob/be59b5ec641c49b43d7161f74ff906533d4b8063/docs/reference/src/contracts.adoc#L82)):*
> ```AsciiDoc
> === Using the ABI/Dispatcher
> 
> For each ABI, a dispatcher is automatically created and exported. That is, for every contract you implement or ABI you manually add.
> ```

What does exported mean?



_Suggestion:_
```AsciiDoc
For each ABI, A ContractDispatcher and LibraryDispatcher are automatically created.
```


<!-- Sent from Reviewable.io -->

2023-04-02 12:35 UTC, ilyalesokhin-starkware commented
*[`docs/reference/src/contracts.adoc` line 108 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS0xgOaDoJTGiDK-HxI:-NS0xgOaDoJTGiDK-HxJ:bqgz5rz) ([raw file](https://github.com/starkware-libs/cairo/blob/be59b5ec641c49b43d7161f74ff906533d4b8063/docs/reference/src/contracts.adoc#L108)):*
> ```AsciiDoc
> This will run the other contract's logic in its context, and may, for example, change its state.
> 
> You can also use another contract's function as a library function. This means the function's logic will be executed from the caller contract's context, and not from the callee contract's context. That is, it may not affect the other contract's storage in any way. This can be done in the following way:
> ```

there is no 'callee' context. the argument is a class_hash not a contract address.



_Code quote:_
```AsciiDoc
and not from the callee contract's context.
```


<!-- Sent from Reviewable.io -->

2023-04-02 12:36 UTC, ilyalesokhin-starkware commented
*[`docs/reference/src/contracts.adoc` line 130 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS0xqKJ6AJUkYT6gMoL:-NS0xqKJ6AJUkYT6gMoM:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/be59b5ec641c49b43d7161f74ff906533d4b8063/docs/reference/src/contracts.adoc#L130)):*
> ```AsciiDoc
> ----
> 
> Where `0x1234` is the address of the other contract.
> ```





_Suggestion:_
```AsciiDoc
is the class_hash of the invoked class.
```


<!-- Sent from Reviewable.io -->

2023-04-02 12:44 UTC, ilyalesokhin-starkware commented
*[`docs/reference/src/contracts.adoc` line 136 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS0zoE5CO-bltjoRGnR:-NS0zoE5CO-bltjoRGnS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/be59b5ec641c49b43d7161f74ff906533d4b8063/docs/reference/src/contracts.adoc#L136)):*
> ```AsciiDoc
> Another way to call another contract is to use the `starknet::call_contract_syscall` system call. It's not recommended to use the system call directly as it's lower level and more complex. Prefer using the dispatcher as described above.
> 
> To directly call another contract using `starknet::call_contract_syscall` you can do the following, but the result is the serialized return value of the function which you need to deserialize yourself. You also need to compute the selector of the function you want to call, which is the keccak hash of the function name - in this case `keccak("foo")`.
> ```





_Suggestion:_
```AsciiDoc
starknet_keccak
```


<!-- Sent from Reviewable.io -->

2023-04-02 13:40 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2687)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`docs/reference/src/contracts.adoc` line 24 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1BdlW9mkz-g0arfE7:-NS1BdlW9mkz-g0arfE8:bza4nj) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L24)):*
> ```AsciiDoc
> A contract is a normal module, with added attributes.
> 
> The main attribute is the `#[contract]` attribute that makes the starknet plugin read the module as a contract.
> ```

Keep lines under 100 chars


<!-- Sent from Reviewable.io -->

2023-04-02 13:41 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2687)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`docs/reference/src/contracts.adoc` line 24 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1BkSMB2GkPjZN2gDd:-NS1BkSMB2GkPjZN2gDe:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L24)):*
> ```AsciiDoc
> A contract is a normal module, with added attributes.
> 
> The main attribute is the `#[contract]` attribute that makes the starknet plugin read the module as a contract.
> ```

?



_Suggestion:_
```AsciiDoc
treat
```
___
*[`docs/reference/src/contracts.adoc` line 33 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1Bqxx7tjmKRhi965d:-NS1Bqxx7tjmKRhi965e:b-lg5agm) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L33)):*
> ```AsciiDoc
> 
> Transactions invoked on such contracts may modify this state, in a way defined by the contract.
> ```

Do you need all these paragraphs breakers? I think that's a documentation anti-pattern.


<!-- Sent from Reviewable.io -->

2023-04-02 13:43 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2687)* status: 0 of 1 files reviewed, 11 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`docs/reference/src/contracts.adoc` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS0vznt2cxCNaREMSjg:-NS1C6Z62mQhQGVZdXSO:bqls3i2) ([raw file](https://github.com/starkware-libs/cairo/blob/be59b5ec641c49b43d7161f74ff906533d4b8063/docs/reference/src/contracts.adoc#L36)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

We support types that can be serialized and legacy mapping.
</blockquote></details>

Actually, types that implement the StorageAccess trait, right?
___
*[`docs/reference/src/contracts.adoc` line 32 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1ByDuEqWUFxo-hDVO:-NS1ByDuEqWUFxo-hDVP:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L32)):*
> ```AsciiDoc
> storage”.
> 
> Transactions invoked on such contracts may modify this state, in a way defined by the contract.
> ```

.
___
*[`docs/reference/src/contracts.adoc` line 41 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1CEB10HUeiGJ6irSC:-NS1CEB10HUeiGJ6irSD:b-gjlby0) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L41)):*
> ```AsciiDoc
> automatically created by the Starknet plugin.
> 
> For example, for the storage member `x` above, access is done using `x::read()` and `x::write(value)`.
> ```

I'd like to have a complete minimal example here of using storage vars.


<!-- Sent from Reviewable.io -->

2023-04-02 13:50 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2687)* status: 0 of 1 files reviewed, 16 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`docs/reference/src/contracts.adoc` line 55 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1CbigDOAzPLfA5leQ:-NS1CbigDOAzPLfA5leR:b-dlkbqp) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L55)):*
> ```AsciiDoc
> - `#[constructor]` function is called when the contract is deployed. There may be only one such function. If it is not defined, the contract is deployed with all storage variables default-initialized.
> - `#[l1_handler]` functions are called when the contract receives a message from L1.
> - `#[event]` functions are signals to the Starknet Operating System. They can be called by the contract itself or by another contract.
> ```

I'm not sure if these should appear near the others, as it's not really user code. It's just a way to introduce a kind of an event.



_Code quote:_
```AsciiDoc
`#[event]`
```
___
*[`docs/reference/src/contracts.adoc` line 57 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1CUv57lkfdSlCDdPF:-NS1CUv57lkfdSlCDdPG:b31gsou) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L57)):*
> ```AsciiDoc
> - `#[event]` functions are signals to the Starknet Operating System. They can be called by the contract itself or by another contract.
> - Functions without any of the above attributes are private functions, and may only be called by other functions in the same contract.
> ```

Examples for each of these.
___
*[`docs/reference/src/contracts.adoc` line 60 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1Co-ICIP0YH84gsAP:-NS1Co-ICIP0YH84gsAQ:b-f737dj) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L60)):*
> ```AsciiDoc
> == ABI
> 
> Each contract has an ABI (Application Binary Interface) that defines the functions that can be called on it.
> ```

Not just functions. Types, events, etc...
___
*[`docs/reference/src/contracts.adoc` line 64 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1D-c9-x-h9LVlAG9Q:-NS1D-c9-x-h9LVlAG9R:b44bll5) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L64)):*
> ```AsciiDoc
> The Starknet plugin generates an ABI for each defined contract.
> 
> You can also write an ABI manually, for contract that are not implemented in your code.
> ```

Right now this seems a bit out of place.
Also, there seems to be a small abuse of notation. The ABI generated by the plugin is more of a json, or something that the user doesn't see.

I think this should be a part of the "Calling other contracts" section.
___
*[`docs/reference/src/contracts.adoc` line 108 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1DoCB0E4uZM1OgVWb:-NS1DoCC9LcyPXoNORCs:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L108)):*
> ```AsciiDoc
> This will run the other contract's logic in its context, and may, for example, change its state.
> 
> You can also use another contract's function as a library function. This means the function's logic will be executed from the caller contract's context, and not from the callee contract's context. That is, it may not affect the other contract's storage in any way. This can be done in the following way:
> ```




<!-- Sent from Reviewable.io -->

2023-04-02 15:29 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2687)* status: 0 of 1 files reviewed, 14 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`docs/reference/src/contracts.adoc` line 36 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS0vznt2cxCNaREMSjg:-NS1Y48R1t8RrYZFzQjg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/be59b5ec641c49b43d7161f74ff906533d4b8063/docs/reference/src/contracts.adoc#L36)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Actually, types that implement the StorageAccess trait, right?
</blockquote></details>

Done.
___
*[`docs/reference/src/contracts.adoc` line 55 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS0wNG-35RyRCVuOhSt:-NS1OwUd3vwWt8N-ztoY:b-vo0qmj) ([raw file](https://github.com/starkware-libs/cairo/blob/be59b5ec641c49b43d7161f74ff906533d4b8063/docs/reference/src/contracts.adoc#L55)):*
> ```AsciiDoc
> - `#[constructor]` function is called when the contract is deployed. There may be only one such function. If it is not defined, the contract is deployed with all storage variables default-initialized.
> - `#[l1_handler]` functions are called when the contract receives a message from L1.
> - `#[event]` functions are signals to the Starknet Operating System. They can be called by the contract itself or by another contract.
> ```

done partially. Why remove " or by another contract."?
___
*[`docs/reference/src/contracts.adoc` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS0xASZ79A2WWIfZ4LO:-NS1QeaODm9MdrCvAMjW:b-66pl33) ([raw file](https://github.com/starkware-libs/cairo/blob/be59b5ec641c49b43d7161f74ff906533d4b8063/docs/reference/src/contracts.adoc#L82)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What does exported mean?
</blockquote></details>

That they can be used/imported.
Later when we have 'pub' it may be even more relevant.
___
*[`docs/reference/src/contracts.adoc` line 108 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS0xgOaDoJTGiDK-HxI:-NS1Y9cDElGLiK_7lb3h:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/be59b5ec641c49b43d7161f74ff906533d4b8063/docs/reference/src/contracts.adoc#L108)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

there is no 'callee' context. the argument is a class_hash not a contract address.
</blockquote></details>

Done.
___
*[`docs/reference/src/contracts.adoc` line 130 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS0xqKJ6AJUkYT6gMoL:-NS1T-h-0FXUZtWJY11J:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/be59b5ec641c49b43d7161f74ff906533d4b8063/docs/reference/src/contracts.adoc#L130)):*
> ```AsciiDoc
> ----
> 
> Where `0x1234` is the address of the other contract.
> ```

Done.
___
*[`docs/reference/src/contracts.adoc` line 136 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS0zoE5CO-bltjoRGnR:-NS1T5dVAsjvZpDauS-l:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/be59b5ec641c49b43d7161f74ff906533d4b8063/docs/reference/src/contracts.adoc#L136)):*
> ```AsciiDoc
> Another way to call another contract is to use the `starknet::call_contract_syscall` system call. It's not recommended to use the system call directly as it's lower level and more complex. Prefer using the dispatcher as described above.
> 
> To directly call another contract using `starknet::call_contract_syscall` you can do the following, but the result is the serialized return value of the function which you need to deserialize yourself. You also need to compute the selector of the function you want to call, which is the keccak hash of the function name - in this case `keccak("foo")`.
> ```

Done.
___
*[`docs/reference/src/contracts.adoc` line 24 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1BdlW9mkz-g0arfE7:-NS1NX0gD5umfCZiYOeW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L24)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Keep lines under 100 chars
</blockquote></details>

Done.
___
*[`docs/reference/src/contracts.adoc` line 33 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1Bqxx7tjmKRhi965d:-NS1O9kSEet6rxvzZk_c:bmyyxwo) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L33)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Do you need all these paragraphs breakers? I think that's a documentation anti-pattern.
</blockquote></details>

I removed some. I think that if everything is together it's heavier to read. Also harder to find something if you look particularly for it as a reference.
___
*[`docs/reference/src/contracts.adoc` line 41 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1CEB10HUeiGJ6irSC:-NS1OeIQCFNxUWBfJLPV:bv2mjl5) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L41)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I'd like to have a complete minimal example here of using storage vars.
</blockquote></details>

Added to the first example. LMK if it works for you.
___
*[`docs/reference/src/contracts.adoc` line 55 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1CbigDOAzPLfA5leQ:-NS1P1OlAHLUZaeLSVVm:bktdzy6) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L55)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I'm not sure if these should appear near the others, as it's not really user code. It's just a way to introduce a kind of an event.
</blockquote></details>

I'm not sure I follow.
___
*[`docs/reference/src/contracts.adoc` line 57 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1CUv57lkfdSlCDdPF:-NS1_a_O4cJTW1Zos8ri:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L57)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Examples for each of these.
</blockquote></details>

Done.
___
*[`docs/reference/src/contracts.adoc` line 60 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1Co-ICIP0YH84gsAP:-NS1PblB-wuHmTDTM1-L:b-bavysz) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L60)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Not just functions. Types, events, etc...
</blockquote></details>

Do we support associated types?
___
*[`docs/reference/src/contracts.adoc` line 64 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1D-c9-x-h9LVlAG9Q:-NS1PzMp5kLE3budfo5s:bf91itb) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L64)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Right now this seems a bit out of place.
Also, there seems to be a small abuse of notation. The ABI generated by the plugin is more of a json, or something that the user doesn't see.

I think this should be a part of the "Calling other contracts" section.
</blockquote></details>

I think it's better here as it refers directly to the ABI. It would be strange to talk about ABIs, then have a primary heading, and immediately mention something else about ABI.

If you don't agree, @ilya [...]

2023-04-03 05:08 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2687)* status: 0 of 1 files reviewed, 17 unresolved discussions (waiting on @ilyalesokhin-starkware and @yuvalsw)

___
*[`docs/reference/src/contracts.adoc` line 55 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1CbigDOAzPLfA5leQ:-NS4UZ919JrztiHH0Io6:b-r8zaw) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L55)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I'm not sure I follow.
</blockquote></details>

Event functions are always empty, right? It's not really a function.
It's just a way to introduce an event type. (And I think it won't be a function in the future either)
It should be its own section like Storage.
___
*[`docs/reference/src/contracts.adoc` line 60 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1Co-ICIP0YH84gsAP:-NS4V3r2Adc4b8K_BNzC:b-livljh) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L60)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Do we support associated types?
</blockquote></details>

I think there is confusion about what an ABI is, let's discuss this f2f.
___
*[`docs/reference/src/contracts.adoc` line 64 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1D-c9-x-h9LVlAG9Q:-NS4VHvE7gJ0jtgLZ-P8:b-yatr66) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L64)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think it's better here as it refers directly to the ABI. It would be strange to talk about ABIs, then have a primary heading, and immediately mention something else about ABI.

If you don't agree, @ilyalesokhin-starkware , can you help us decide with your opinion?
</blockquote></details>

Let's discuss f2f.
___
*[`docs/reference/src/contracts.adoc` line 39 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS4Tc_y81t5IB6-Sk76:-NS4Tc_y81t5IB6-Sk77:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9f2d9b55ee89f410eaab8f90632c2cd18de07aa4/docs/reference/src/contracts.adoc#L39)):*
> ```AsciiDoc
> In a contract, you can define a struct named `Storage`. The members of this struct are the storage
> variables.
> The storage variables may be of any Cairo type that implements the StorageAccess, and legacy
> ```





_Suggestion:_
```AsciiDoc
torageAccess trait, a
```
___
*[`docs/reference/src/contracts.adoc` line 47 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS4Tooe9L5_SrW1SUMa:-NS4Tooe9L5_SrW1SUMb:b-umg4pt) ([raw file](https://github.com/starkware-libs/cairo/blob/9f2d9b55ee89f410eaab8f90632c2cd18de07aa4/docs/reference/src/contracts.adoc#L47)):*
> ```AsciiDoc
> `x::write(value)`.
> 
> Defining a legacy mapping storage member is done using the `LegacyMap` "type" that is expanded by
> ```

I suggest removing the quotes here. It is a type.



_Suggestion:_
```AsciiDoc
type
```
___
*[`docs/reference/src/contracts.adoc` line 47 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS4U2SR3s6KU6L0HT79:-NS4U2SR3s6KU6L0HT7A:beagntr) ([raw file](https://github.com/starkware-libs/cairo/blob/9f2d9b55ee89f410eaab8f90632c2cd18de07aa4/docs/reference/src/contracts.adoc#L47)):*
> ```AsciiDoc
> `x::write(value)`.
> 
> Defining a legacy mapping storage member is done using the `LegacyMap` "type" that is expanded by
> ```

It's not clera why 'legacy' is used here. Either remove the work legacy, or explain it.
___
*[`docs/reference/src/contracts.adoc` line 48 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS4U8Or22yA-vetjfZy:-NS4U8Or22yA-vetjfZz:b-7kcqvs) ([raw file](https://github.com/starkware-libs/cairo/blob/9f2d9b55ee89f410eaab8f90632c2cd18de07aa4/docs/reference/src/contracts.adoc#L48)):*
> ```AsciiDoc
> 
> Defining a legacy mapping storage member is done using the `LegacyMap` "type" that is expanded by
> the Starknet plugin.
> ```

Consider mentioning that key and value can be any serializable type.
___
*[`docs/reference/src/contracts.adoc` line 54 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS4UKESEjY2oSl71hXK:-NS4UKESEjY2oSl71hXL:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9f2d9b55ee89f410eaab8f90632c2cd18de07aa4/docs/reference/src/contracts.adoc#L54)):*
> ```AsciiDoc
> `m::write(key, value)`.
> 
> When a contract is deployed, all its storage cells are initialized to zero. In particular, all
> ```





_Suggestion:_
```AsciiDoc
d, all of its sto
```
___
*[`docs/reference/src/contracts.adoc` line 55 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS4UM0R3b3f3YWfHIF4:-NS4UM0R3b3f3YWfHIF5:b-igmwac) ([raw file](https://github.com/starkware-libs/cairo/blob/9f2d9b55ee89f410eaab8f90632c2cd18de07aa4/docs/reference/src/contracts.adoc#L55)):*
> ```AsciiDoc
> 
> When a contract is deployed, all its storage cells are initialized to zero. In particular, all
> storage variables are initially zero.
> ```

It is ill defined right now. This should say something like: "deserialized from zeroes".
___
*[`docs/reference/src/contracts.adoc` line 212 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS4Vwep2Ott5wuHAgmQ:-NS4Vwep2Ott5wuHAgmR:begnjxq) ([raw file](https://github.com/starkware-libs/cairo/blob/9f2d9b55ee89f410eaab8f90632c2cd18de07aa4/docs/reference/src/contracts.adoc#L212)):*
> ```AsciiDoc
> mod MySecondContract {
>     #[external]
>     fn syscall_call_another_contract(address: starknet::ContractAddress, selector: felt252, calldata: Array<felt252>) -> Span::<felt252> {
> ```

Line too long, I think here it's even more important, since it's visible:)


<!-- Sent from Reviewable.io -->

2023-04-03 09:50 UTC, ilyalesokhin-starkware commented
*[`docs/reference/src/contracts.adoc` line 48 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS4U8Or22yA-vetjfZy:-NS5WYtG0fK51lu0coG7:bys7rsd) ([raw file](https://github.com/starkware-libs/cairo/blob/9f2d9b55ee89f410eaab8f90632c2cd18de07aa4/docs/reference/src/contracts.adoc#L48)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider mentioning that key and value can be any serializable type.
</blockquote></details>

the key needs to implement LegacyHash.



_Code quote:_
```AsciiDoc
 a storage member is done using the `::read()` and 
```


<!-- Sent from Reviewable.io -->

2023-04-03 09:51 UTC, ilyalesokhin-starkware commented
*[`docs/reference/src/contracts.adoc` line 55 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS0wNG-35RyRCVuOhSt:-NS5WhOn3BJmP63EI7cI:b2u4td5) ([raw file](https://github.com/starkware-libs/cairo/blob/be59b5ec641c49b43d7161f74ff906533d4b8063/docs/reference/src/contracts.adoc#L55)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

done partially. Why remove " or by another contract."?
</blockquote></details>

A contract shouldn't be able to call an event that is defined in another contract.


<!-- Sent from Reviewable.io -->

2023-04-03 09:52 UTC, ilyalesokhin-starkware commented
*[`docs/reference/src/contracts.adoc` line 55 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1CbigDOAzPLfA5leQ:-NS5WsPT6KKAtgVSrhJh:b-r68ylh) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L55)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Event functions are always empty, right? It's not really a function.
It's just a way to introduce an event type. (And I think it won't be a function in the future either)
It should be its own section like Storage.
</blockquote></details>

event shouldn't be under Entry points.


<!-- Sent from Reviewable.io -->

2023-04-03 09:53 UTC, ilyalesokhin-starkware commented
*[`docs/reference/src/contracts.adoc` line 171 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS5XGV548EdFhVLfCnm:-NS5XGV548EdFhVLfCnn:b-tkblmm) ([raw file](https://github.com/starkware-libs/cairo/blob/9f2d9b55ee89f410eaab8f90632c2cd18de07aa4/docs/reference/src/contracts.adoc#L171)):*
> ```AsciiDoc
> You can also use another contract's function as a library function. This means the function's logic
> will be executed from the caller contract's context.
> That is, it may not affect the other contract's storage in any way. This can be done using the
> ```

there is no other contract.



_Code quote:_
```AsciiDoc
it may not affect the other contract's storage in any way.
```


<!-- Sent from Reviewable.io -->

2023-04-03 09:53 UTC, ilyalesokhin-starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2687)* status: 0 of 1 files reviewed, 17 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`docs/reference/src/contracts.adoc` line 62 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS0wwopDTi02pkA95vZ:-NS0wwopDTi02pkA95v_:ba0mucx) ([raw file](https://github.com/starkware-libs/cairo/blob/be59b5ec641c49b43d7161f74ff906533d4b8063/docs/reference/src/contracts.adoc#L62)):*
> ```AsciiDoc
> Each contract has an ABI (Application Binary Interface) that defines the functions that can be called on it.
> 
> The Starknet plugin generates an ABI for each defined contract.
> ```

describe where the generated ABI is located.



_Code quote:_
```AsciiDoc
The Starknet plugin generates an ABI for each defined contract.
```
___
*[`docs/reference/src/contracts.adoc` line 134 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS0zSuf4O3Tfpd0uE2-:-NS0zSuf4O3Tfpd0uE20:b-r3bdad) ([raw file](https://github.com/starkware-libs/cairo/blob/be59b5ec641c49b43d7161f74ff906533d4b8063/docs/reference/src/contracts.adoc#L134)):*
> ```AsciiDoc
> === Using system calls
> 
> Another way to call another contract is to use the `starknet::call_contract_syscall` system call. It's not recommended to use the system call directly as it's lower level and more complex. Prefer using the dispatcher as described above.
> ```

The Dispatcher above is a high-level syntax for the low-level system calls.

The 



_Code quote:_
```AsciiDoc
Another way to call another contract is to use the `starknet::call_contract_syscall` system call. It's not recommended to use the system call directly as it's lower level and more complex. Prefer using the dispatcher as described above.

To directly call another contract using `starknet::call_contract_syscall` you can do the following, but the result is the serialized return value of the function which you need to deserialize yourself. You also need to compute the selector of the function you want to call, which is the keccak hash of the function name - in this case `keccak("foo")`.
```


<!-- Sent from Reviewable.io -->

2023-04-03 10:12 UTC, ilyalesokhin-starkware commented
*[`docs/reference/src/contracts.adoc` line 25 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS5_LBa32jNj4Gkq3XZ:-NS5_LBa32jNj4Gkq3X_:b-r7rtsh) ([raw file](https://github.com/starkware-libs/cairo/blob/9f2d9b55ee89f410eaab8f90632c2cd18de07aa4/docs/reference/src/contracts.adoc#L25)):*
> ```AsciiDoc
> ----
> 
> A contract is a normal module, with added attributes.
> ```

I don’t think we should say that a contract is "a normal module” it is just the syntax that we picked.



_Suggestion:_
```AsciiDoc
A contract is written as an inline module with specific attributes.
```


<!-- Sent from Reviewable.io -->

2023-04-03 12:41 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2687)* status: 0 of 1 files reviewed, 16 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`docs/reference/src/contracts.adoc` line 55 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS0wNG-35RyRCVuOhSt:-NS5rQU-CUtT539RDX1w:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/be59b5ec641c49b43d7161f74ff906533d4b8063/docs/reference/src/contracts.adoc#L55)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

A contract shouldn't be able to call an event that is defined in another contract.
</blockquote></details>

Done.
___
*[`docs/reference/src/contracts.adoc` line 62 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS0wwopDTi02pkA95vZ:-NS67QeQ98l_CGLCxNsP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/be59b5ec641c49b43d7161f74ff906533d4b8063/docs/reference/src/contracts.adoc#L62)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

describe where the generated ABI is located.
</blockquote></details>

Done.



_Code quote:_
```AsciiDoc
 plugin generates an ABI for each defined contr
```
___
*[`docs/reference/src/contracts.adoc` line 134 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS0zSuf4O3Tfpd0uE2-:-NS5sLp2EpkI88Kgundm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/be59b5ec641c49b43d7161f74ff906533d4b8063/docs/reference/src/contracts.adoc#L134)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The Dispatcher above is a high-level syntax for the low-level system calls.

The 
</blockquote></details>

Done.
___
*[`docs/reference/src/contracts.adoc` line 55 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1CbigDOAzPLfA5leQ:-NS5rR2p2uxSA-9ZO9ZH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L55)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

event shouldn't be under Entry points.
</blockquote></details>

Done.
___
*[`docs/reference/src/contracts.adoc` line 60 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1Co-ICIP0YH84gsAP:-NS63XQMDeGMtwnVUdKH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L60)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think there is confusion about what an ABI is, let's discuss this f2f.
</blockquote></details>

Done.



_Code quote:_
```AsciiDoc
Application Binary Interface) 
```
___
*[`docs/reference/src/contracts.adoc` line 64 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS1D-c9-x-h9LVlAG9Q:-NS65SJe1h5taThBEgZ8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1bbc753ae65905d552d3d927de0a1d02658a5298/docs/reference/src/contracts.adoc#L64)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Let's discuss f2f.
</blockquote></details>

Done.
___
*[`docs/reference/src/contracts.adoc` line 25 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS5_LBa32jNj4Gkq3XZ:-NS5nJBmBaKHRtdy27_j:b-sw3k1e) ([raw file](https://github.com/starkware-libs/cairo/blob/9f2d9b55ee89f410eaab8f90632c2cd18de07aa4/docs/reference/src/contracts.adoc#L25)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don’t think we should say that a contract is "a normal module” it is just the syntax that we picked.
</blockquote></details>

Done. Do you also suggest to remove the second sentence?
___
*[`docs/reference/src/contracts.adoc` line 39 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS4Tc_y81t5IB6-Sk76:-NS5nTKn2y3uUjeKk6MV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9f2d9b55ee89f410eaab8f90632c2cd18de07aa4/docs/reference/src/contracts.adoc#L39)):*
> ```AsciiDoc
> In a contract, you can define a struct named `Storage`. The members of this struct are the storage
> variables.
> The storage variables may be of any Cairo type that implements the StorageAccess, and legacy
> ```

Done.
___
*[`docs/reference/src/contracts.adoc` line 47 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS4Tooe9L5_SrW1SUMa:-NS5nWMn-lvpoT-qq1L6:b7tz7i5) ([raw file](https://github.com/starkware-libs/cairo/blob/9f2d9b55ee89f410eaab8f90632c2cd18de07aa4/docs/reference/src/contracts.adoc#L47)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I suggest removing the quotes here. It is a type.
</blockquote></details>

It's not, it's interpreted by the starknet plugin.
___
*[`docs/reference/src/contracts.adoc` line 47 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS4U2SR3s6KU6L0HT79:-NS5ocWgCck0D5OjQZaq:b-6g12ac) ([raw file](https://github.com/starkware-libs/cairo/blob/9f2d9b55ee89f410eaab8f90632c2cd18de07aa4/docs/reference/src/contracts.adoc#L47)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It's not clera why 'legacy' is used here. Either remove the work legacy, or explain it.
</blockquote></details>

We only support legacy mappings (pedersen based) currently. I don't want to omit it but I'm not sure I also want to elaborate.
___
*[`docs/reference/src/contracts.adoc` line 54 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS4UKESEjY2oSl71hXK:-NS5q6yW52ZURBKvOKJv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9f2d9b55ee89f410eaab8f90632c2cd18de07aa4/docs/reference/src/contracts.adoc#L54)):*
> ```AsciiDoc
> `m::write(key, value)`.
> 
> When a contract is deployed, all its storage cells are initialized to zero. In particular, all
> ```

Done.



_Code quote:_
```AsciiDoc
ll its storage cells
```
___
*[`docs/reference/src/contracts.adoc` line 55 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS4UM0R3b3f3YWfHIF4:-NS5qSWR7sMKXX1Fy9Fd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9f2d9b55ee89f410eaab8f90632c2cd18de07aa4/docs/reference/src/contracts.adoc#L55)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It is ill defined right now. This should say something like: "deserialized from zeroes".
</blockquote></details>

Done.
___
*[`docs/reference/src/contracts.adoc` line 171 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS5XGV548EdFhVLfCnm:-NS5rp2t3zfG7HmbjbWj:bxfudft) ([raw file](https://github.com/starkware-libs/cairo/blob/9f2d9b55ee89f410eaab8f90632c2cd18de07aa4/docs/reference/src/contracts.adoc#L171)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

there is no other contract.
</blockquote></details>

There is the contract that defined the function. isn't there?
___
*[`docs/reference/src/contracts.adoc` line 212 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS4Vwep2Ott5wuHAgmQ:-NS62tlk7AXJB_scF0ub:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9f2d9b55ee89f410eaab8f90632c2cd18de07aa4/docs/reference/src/contracts.adoc#L212)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Line too long, I think here it's even more important, since it's visible:)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-03 12:45 UTC, spapinistarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2687#-:-NS68hmE-gIVJUWWL2B_:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2023-04-04 07:11 UTC, ilyalesokhin-starkware commented
*[`docs/reference/src/contracts.adoc` line 25 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS5_LBa32jNj4Gkq3XZ:-NSA5gmv2fPjfHDFSFAz:ba155k1) ([raw file](https://github.com/starkware-libs/cairo/blob/9f2d9b55ee89f410eaab8f90632c2cd18de07aa4/docs/reference/src/contracts.adoc#L25)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Done. Do you also suggest to remove the second sentence?
</blockquote></details>

no, it was a mistake.



_Code quote:_
```AsciiDoc
The main attribute is the `#[contract]` attribute that makes the starknet plugin treat the module as
a contract.
```


<!-- Sent from Reviewable.io -->

2023-04-04 07:15 UTC, ilyalesokhin-starkware commented
*[`docs/reference/src/contracts.adoc` line 132 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NSA6dq-8s9IVnJxfExJ:-NSA6dq-8s9IVnJxfExK:bsf66rb) ([raw file](https://github.com/starkware-libs/cairo/blob/1927eacdd85e2b6e73f29525e91f536ed9c1f6cf/docs/reference/src/contracts.adoc#L132)):*
> ```AsciiDoc
> 
> The Starknet plugin generates a contract interface for each defined contract.
> It is a trait that can be found in `<contract_name>::__abi`.
> ```

I don't think there is `__`.
https://github.com/starkware-libs/cairo/blob/68dabaa1e2ce1525f496cac1e453a1db17a3c5a7/crates/cairo-lang-starknet/src/plugin/contract.rs#L233



_Suggestion:_
```AsciiDoc
<contract_name>::abi
```


<!-- Sent from Reviewable.io -->

2023-04-04 07:20 UTC, ilyalesokhin-starkware commented
*[`docs/reference/src/contracts.adoc` line 215 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NSA7QEa0sBevoi-K7VY:-NSA7QEa0sBevoi-K7VZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1927eacdd85e2b6e73f29525e91f536ed9c1f6cf/docs/reference/src/contracts.adoc#L215)):*
> ```AsciiDoc
> The dispatcher above is the high-level syntax for the low-level system calls.
> Thus, it's not recommended to use the system call directly as it's lower level and more complex.
> Always prefer using the dispatcher as described above.
> ```





_Suggestion:_
```AsciiDoc
The system call can be used directly if want to have customize error handling or more
control over the serialization and deserialization of the call data and returned data.
```


<!-- Sent from Reviewable.io -->

2023-04-04 09:37 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2687)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`docs/reference/src/contracts.adoc` line 171 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NS5XGV548EdFhVLfCnm:-NSAb3y8EIczzJPqCyam:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9f2d9b55ee89f410eaab8f90632c2cd18de07aa4/docs/reference/src/contracts.adoc#L171)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it is a contract_class it has not state.


it like saying that in c++ when you call a static function you are changing your own state rather than the state of the called class.
</blockquote></details>

Done.



_Code quote:_
```AsciiDoc
t is, it may not affect the other contract's storage in any way.
```
___
*[`docs/reference/src/contracts.adoc` line 132 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NSA6dq-8s9IVnJxfExJ:-NSAa6Kp1tE1aaa_FVyk:bl9hmgz) ([raw file](https://github.com/starkware-libs/cairo/blob/1927eacdd85e2b6e73f29525e91f536ed9c1f6cf/docs/reference/src/contracts.adoc#L132)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't think there is `__`.
https://github.com/starkware-libs/cairo/blob/68dabaa1e2ce1525f496cac1e453a1db17a3c5a7/crates/cairo-lang-starknet/src/plugin/contract.rs#L233
</blockquote></details>

There is.
___
*[`docs/reference/src/contracts.adoc` line 215 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NSA7QEa0sBevoi-K7VY:-NSAc8_U8948_43VBeZi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1927eacdd85e2b6e73f29525e91f536ed9c1f6cf/docs/reference/src/contracts.adoc#L215)):*
> ```AsciiDoc
> The dispatcher above is the high-level syntax for the low-level system calls.
> Thus, it's not recommended to use the system call directly as it's lower level and more complex.
> Always prefer using the dispatcher as described above.
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-04-04 10:50 UTC, ilyalesokhin-starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2687)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`docs/reference/src/contracts.adoc` line 132 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NSA6dq-8s9IVnJxfExJ:-NSAszc30rFWKeBHNEci:b-ibxw0u) ([raw file](https://github.com/starkware-libs/cairo/blob/1927eacdd85e2b6e73f29525e91f536ed9c1f6cf/docs/reference/src/contracts.adoc#L132)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

There is.
</blockquote></details>

Ok, 

why does it have `__`?


<!-- Sent from Reviewable.io -->

2023-04-04 10:51 UTC, ilyalesokhin-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2687#-:-NSAtADEEdUiYz0BR01V:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware and @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-04-04 13:26 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2687)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`docs/reference/src/contracts.adoc` line 132 at r5](https://reviewable.io/reviews/starkware-libs/cairo/2687#-NSA6dq-8s9IVnJxfExJ:-NSBRR1j5vm-jHVeb_-G:bon0ep3) ([raw file](https://github.com/starkware-libs/cairo/blob/1927eacdd85e2b6e73f29525e91f536ed9c1f6cf/docs/reference/src/contracts.adoc#L132)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Ok, 

why does it have `__`?
</blockquote></details>

I guess to not forbid the users from using it. We can separately discuss changing it.


<!-- Sent from Reviewable.io -->

2023-04-04 13:36 UTC, merged