feat: integer_casting
starkware-libs/cairo pull request #2938
Opened 2023-04-25 23:36 UTC by hemantjoestar

An attempt at what was suggested by
https://twitter.com/PapiniShahar/status/1650939873480548365

2023-04-27 21:26 UTC, spapinistarkware requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2938)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @hemantjoestar)

___
*[`corelib/src/test/integer_test.cairo` line 684 at r1](https://reviewable.io/reviews/starkware-libs/cairo/2938#-NU3aDlB9tqXpFhbxKCn:-NU3aDlCE-a8foz-DT8s:b-4cs1my) ([raw file](https://github.com/starkware-libs/cairo/blob/c97e98bd9370dd14e0076909ef69d2373a38af24/corelib/src/test/integer_test.cairo#L684)):*
> ```Cairo
> }
> #[test]
> fn should_pass_between_u8_u16() {
> ```

This test can use a single generic function:
```
fn my_test<A, B, impl BIA: BoundedInt<A>, impl BIB: BoundedInt<B>, impl IAB: Into<A,B>,
impl IBA: TryInto<B,A>>{...}
```

And then call while inferering all the impls.


<!-- Sent from Reviewable.io -->

2023-04-28 17:10 UTC, hemantjoestar commented
Implemented suggested changes

2023-04-28 17:12 UTC, hemantjoestar commented on corelib/src/test/integer_test.cairo
> +fn cast_must_pass<A,
Implemented suggested changes

2023-04-29 05:16 UTC, spapinistarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2938#-:-NUARGnf8zeCirp1I6B9:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @hemantjoestar)



<!-- Sent from Reviewable.io -->

2023-04-29 05:17 UTC, spapinistarkware commented
Looks good. Please resolve conflicts and make sure cairo-fmt passes.

2023-04-30 02:55 UTC, hemantjoestar commented
Before merging ran cairo_fmt.sh locally, but couldn't get the bool line to wrap. `--check` flag too doesn't through any error

2023-04-30 07:07 UTC, merged