Span as owning type
starkware-libs/cairo pull request #2987
Opened 2023-04-30 15:03 UTC by spapinistarkware

2023-04-30 15:03 UTC, spapinistarkware commented
Current dependencies on/for this PR:
* main
  * **PR #2987** <a href="https://app.graphite.dev/github/pr/starkware-libs/cairo/2987" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/cairo/2987?utm_source=stack-comment).

2023-05-01 06:35 UTC, ilyalesokhin-starkware commented
does it make sense to call it span if it is an owning type?





<!-- Sent from Reviewable.io -->

2023-05-01 06:37 UTC, ilyalesokhin-starkware commented
*[`corelib/src/lib.cairo` line 340 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUL0qSbA0sdsm9UELVA:-NUL0qSbA0sdsm9UELVB:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/d004d29d3a3c36f436c531a6c68ff15406f4a11d/corelib/src/lib.cairo#L340)):*
> ```Cairo
> use zeroable::NonZero;
> 
> // #[cfg(test)]
> ```

revert



_Code quote:_
```Cairo
// #[cfg(test)]
```


<!-- Sent from Reviewable.io -->

2023-05-01 06:39 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/test_data/match` line 72 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUL1M-70LIihziHnbFr:-NUL1M-70LIihziHnbFs:b31stb4) ([raw file](https://github.com/starkware-libs/cairo/blob/d004d29d3a3c36f436c531a6c68ff15406f4a11d/crates/cairo-lang-lowering/src/test_data/match#L72)):*
> ```
> //! > semantic_diagnostics
> error: Identifier not found.
>  --> lib.cairo:1:12
> ```

please fix test.



_Code quote:_
```
error: Identifier not found.
 --> lib.cairo:1:12
use array::array_get;
           ^*******^
```


<!-- Sent from Reviewable.io -->

2023-05-01 06:43 UTC, ilyalesokhin-starkware reviewed
> Reviewed 15 of 73 files at r1, 10 of 43 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 25 of 73 files reviewed, 2 unresolved discussions (waiting on @liorgold2, @orizi, and @spapinistarkware)



<!-- Sent from Reviewable.io -->

2023-05-01 09:01 UTC, spapinistarkware reviewed
I think it does. As an english word, it doesnt say anything about not owning the value.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987#-:-NULO9CtEyjmVLU7OVs_:b-2allr8)* status: 23 of 73 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @orizi)

___
*[`corelib/src/lib.cairo` line 340 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUL0qSbA0sdsm9UELVA:-NULXmC10WR_I_IeX6xx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d004d29d3a3c36f436c531a6c68ff15406f4a11d/corelib/src/lib.cairo#L340)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/test_data/match` line 72 at r2](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUL1M-70LIihziHnbFr:-NULXnK68owdvtJgKah5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d004d29d3a3c36f436c531a6c68ff15406f4a11d/crates/cairo-lang-lowering/src/test_data/match#L72)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

please fix test.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-01 10:19 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 112 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NULoe_zAnkf492oz29g:-NULoea-5wSkn-V3wiUJ:b-5e4rid) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L112)):*
> ```XML
>                     }],
>                     ap_change: SierraApChange::Known { new_vars_only: false },
>                 },
> ```

Consider not returning the span if it is empty.



_Code quote:_
```XML
                BranchSignature {
                    vars: vec![OutputVarInfo {
                        ty: span_ty,
                        ref_info: OutputVarReferenceInfo::SameAsParam { param_idx: 0 },
                    }],
                    ap_change: SierraApChange::Known { new_vars_only: false },
                },
```


<!-- Sent from Reviewable.io -->

2023-05-01 10:22 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-starknet/src/plugin/entry_point.rs` line 160 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NULpTKBCH7jtUuVSq17:-NULpTKBCH7jtUuVSq18:b-umsfnm) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-starknet/src/plugin/entry_point.rs#L160)):*
> ```XML
>     Ok(RewriteNode::interpolate_patched(
>         format!(
>             "fn $function_name$(mut data: Span::<@felt252>) -> Span::<@felt252> {{
> ```

why snapshot?



_Code quote:_
```XML
@felt252
```


<!-- Sent from Reviewable.io -->

2023-05-01 10:24 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NULpoP23nXNcFZwvAPw:-NULpoP23nXNcFZwvAPx:b-umsfnm) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-starknet/src/plugin/utils.rs#L36)):*
> ```XML
> }
> 
> /// Returns true if type_ast is `Span::<@felt252>`.
> ```

why snapshot?



_Code quote:_
```XML
@felt252
```


<!-- Sent from Reviewable.io -->

2023-05-01 11:06 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 23 of 73 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NULyGfc4aMEYoThWbJc:-NULyGfc4aMEYoThWbJd:b5101ts) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L107)):*
> ```XML
>                 // Empty.
>                 BranchSignature {
>                     vars: vec![OutputVarInfo {
> ```

I think we shouldn't return the span in this case.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 153 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NULyObH1_T40q_FjdMa:-NULyObH1_T40q_FjdMb:brhumzt) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L153)):*
> ```XML
>                 // Empty.
>                 BranchSignature {
>                     vars: vec![OutputVarInfo {
> ```

Same here.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 181 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NULywSe06OcPHoPGBPS:-NULywSe06OcPHoPGBPT:bds0i2x) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L181)):*
> ```XML
>         let index_type = context.get_concrete_type(SpanIndexType::id(), &[])?;
>         let param_signatures = vec![
>             ParamSignature::new(range_check_type.clone()),
> ```

`.with_allow_add_const()`?


<!-- Sent from Reviewable.io -->

2023-05-01 11:08 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 23 of 73 files reviewed, 8 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 186 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NULzjop2Lt94vceMTO8:-NULzjop2Lt94vceMTO9:b-oophso) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L186)):*
> ```XML
>         ];
>         let branch_signatures = vec![
>             // First (success) branch returns rc, span and element; failure branch does not return
> ```

Split comment between branches.
E.g., `// Success.`, `// Failure.`, don't think we need to document the return values since the types are easy to read, but we can with e.g., `// Range-check.`


<!-- Sent from Reviewable.io -->

2023-05-01 11:09 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 23 of 73 files reviewed, 10 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 234 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUM-A_l-0oh_ogS6L_3:-NUM-A_l-0oh_ogS6L_4:b-rgy3na) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L234)):*
> ```XML
>         let param_signatures = vec![
>             ParamSignature::new(range_check_type.clone()),
>             ParamSignature::new(span_type.clone()),
> ```

What happens to the elements outside the slice? If they are dropped it's not good.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 241 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUM-4A78RoEzV94B2zA:-NUM-4A78RoEzV94B2zB:brhumzt) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L241)):*
> ```XML
>         ];
>         let branch_signatures = vec![
>             // First (success) branch returns rc, span and the slice snapshot; failure branch does
> ```

Same here.


<!-- Sent from Reviewable.io -->

2023-05-01 11:10 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 23 of 73 files reviewed, 11 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 169 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUM-LPsCuJ9SEZg3FHw:-NUM-LPsCuJ9SEZg3FHx:bvg17jq) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L169)):*
> ```XML
> #[derive(Default)]
> pub struct SpanGetLibfuncWrapped {}
> impl SignatureAndTypeGenericLibfunc for SpanGetLibfuncWrapped {
> ```

Where do we check duplicatablity in this libfunc? I guess it's better to have it here.


<!-- Sent from Reviewable.io -->

2023-05-01 12:06 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 23 of 73 files reviewed, 12 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 277 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUMC5Uu3pkbR02AslHe:-NUMC5Uu3pkbR02AslHf:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L277)):*
> ```XML
> pub struct SnapshotAsSpanLibfuncWrapped {}
> impl SignatureAndTypeGenericLibfunc for SnapshotAsSpanLibfuncWrapped {
>     const STR_ID: &'static str = "snapshot_span_as_span";
> ```

.



_Suggestion:_
```XML
snapshot_span_to_span
```


<!-- Sent from Reviewable.io -->

2023-05-01 12:06 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 23 of 73 files reviewed, 13 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 273 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUMCCrL39jAO2dmGcUh:-NUMCBi211w-W1EEuLTX:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L273)):*
> ```XML
> pub type SpanSliceLibfunc = WrapSignatureAndTypeGenericLibfunc<SpanSliceLibfuncWrapped>;
> 
> /// Libfunc for converting a span snapshot to a span of snapshots.
> ```

.



_Suggestion:_
```XML
/// Libfunc for converting a snapshot of span (@Span<T>) to a span of snapshots (Span<@T>).
```


<!-- Sent from Reviewable.io -->

2023-05-01 12:10 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 23 of 73 files reviewed, 14 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 289 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUMD87y--sWUo1KjA3Q:-NUMD87y--sWUo1KjA3R:b25zqsq) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L289)):*
> ```XML
>         let span_snapshot_ty = context.get_wrapped_concrete_type(SpanType::id(), snapshot_ty)?;
>         Ok(LibfuncSignature::new_non_branch_ex(
>             vec![ParamSignature::new(snapshot_span_ty)],
> ```

Consider (`allow_all` doesn't exist, but you can easily add it)



_Suggestion:_
```XML
vec![ParamSignature::new(snapshot_span_ty).allow_all()],
```


<!-- Sent from Reviewable.io -->

2023-05-01 12:11 UTC, liorgold2 requested changes
> Reviewed 1 of 73 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 24 of 73 files reviewed, 15 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 284 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUMDO_jD2t3UXSnBfg8:-NUMDO_kCeCc3u36X-Ot:b-iquxfj) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L284)):*
> ```XML
>         ty: ConcreteTypeId,
>     ) -> Result<LibfuncSignature, SpecializationError> {
>         let span_ty = context.get_wrapped_concrete_type(SpanType::id(), ty.clone())?;
> ```

Add `span_ty()`



_Code quote:_
```XML
context.get_wrapped_concrete_type(SpanType::id(), ty.clone())?
```


<!-- Sent from Reviewable.io -->

2023-05-01 12:22 UTC, liorgold2 requested changes
> Reviewed 1 of 43 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 24 of 73 files reviewed, 19 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUMEDDN0EIfDJMMdNFd:-NUMEDDN0EIfDJMMdNFe:b7xusds) ([raw file](https://github.com/starkware-libs/cairo/blob/07cc5fd4d6891a74ae66fa0a40f93247723148e4/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L47)):*
> ```XML
>         PopFront(ArrayPopFrontLibfunc),
>         Get(ArrayGetLibfunc),
>         Slice(ArraySliceLibfunc),
> ```

What did this function (Slice) used do?
___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 153 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUMEkAn4PhvWRhxr5MY:-NUMEixz7uA-LxPLqmFZ:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L153)):*
> ```XML
> pub type ArrayPopFrontLibfunc = WrapSignatureAndTypeGenericLibfunc<ArrayPopFrontLibfuncWrapped>;
> 
> /// Libfunc for converting an array to a span.
> ```

.



_Suggestion:_
```XML
/// Libfunc for converting an array (Array<T>) to a span (Span<T>).
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 167 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUMEsWH1bHTDSTDfpV3:-NUMEsWIE1W9G4sjAsIe:b-5txp65) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L167)):*
> ```XML
>         let span_ty = context.get_wrapped_concrete_type(SpanType::id(), ty)?;
>         Ok(LibfuncSignature::new_non_branch_ex(
>             vec![ParamSignature::new(arr_ty)],
> ```

`allow_all` (see comment in another file).
___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 178 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUMF3tiCn-XRC4k1BxK:-NUMF3tjAdia-z2CRYtW:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L178)):*
> ```XML
> pub type ArrayToSpanLibfunc = WrapSignatureAndTypeGenericLibfunc<ArrayToSpanLibfuncWrapped>;
> 
> /// Libfunc for converting an array snapshot to a span.
> ```

.



_Suggestion:_
```XML
/// Libfunc for converting a snapshot of array (@Array<T>) to a span of snapshots (Span<@T>)).
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 289 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUMD87y--sWUo1KjA3Q:-NUMFX3K-RcdUKOzuppJ:b-qlewxf) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L289)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Consider (`allow_all` doesn't exist, but you can easily add it)
</blockquote></details>

Actually I suggest to extract the code below to a utility function like `reinterpret_cast_signature()` which only gets the input and output types.



_Code quote:_
```XML
        Ok(LibfuncSignature::new_non_branch_ex(
            vec![ParamSignature::new(snapshot_span_ty)],
            vec![OutputVarInfo {
                ty: span_snapshot_ty,
                ref_info: OutputVarReferenceInfo::SameAsParam { param_idx: 0 },
            }],
            SierraApChange::Known { new_vars_only: true },
        ))
```


<!-- Sent from Reviewable.io -->

2023-05-01 12:23 UTC, liorgold2 reviewed
> Reviewed 1 of 73 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 25 of 73 files reviewed, 19 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)



<!-- Sent from Reviewable.io -->

2023-05-01 15:09 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 19 of 76 files reviewed, 19 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, and @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUMEDDN0EIfDJMMdNFd:-NUMVdz68vLrd57zEDWC:b7clr05) ([raw file](https://github.com/starkware-libs/cairo/blob/07cc5fd4d6891a74ae66fa0a40f93247723148e4/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L47)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

What did this function (Slice) used do?
</blockquote></details>

Get a span of a subarray.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 153 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUMEkAn4PhvWRhxr5MY:-NUMVtUwCBqotow6KdOX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L153)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 167 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUMEsWH1bHTDSTDfpV3:-NUMmakx32fAZdeUmx_b:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L167)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

`allow_all` (see comment in another file).
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 178 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUMF3tiCn-XRC4k1BxK:-NUMW9V7Bdv41CBcHwfI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L178)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NULyGfc4aMEYoThWbJc:-NUMXbJ28ct30cwe7JXd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L107)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I think we shouldn't return the span in this case.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 153 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NULyObH1_T40q_FjdMa:-NUMXabZCaxdbyfwW6Bz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L153)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 169 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUM-LPsCuJ9SEZg3FHw:-NUMXldJ1NvvrhkHV4xR:b-yw0hs7) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L169)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Where do we check duplicatablity in this libfunc? I guess it's better to have it here.
</blockquote></details>

We don't need duplicability, since this function consumes the span.
```
extern fn span_get<T>(span: Span<T>, index: usize) -> Option<Box<T>>
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 181 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NULywSe06OcPHoPGBPS:-NUMY52w8whkRSBZjJj2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L181)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

`.with_allow_add_const()`?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 186 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NULzjop2Lt94vceMTO8:-NUMYg7Y9J5DcVMweTxe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L186)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Split comment between branches.
E.g., `// Success.`, `// Failure.`, don't think we need to document the return values since the types are easy to read, but we can with e.g., `// Range-check.`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 234 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUM-A_l-0oh_ogS6L_3:-NUMjKyk6ytDcQuNMmre:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L234)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

What happens to the elements outside the slice? If they are dropped it's not good.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 241 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUM-4A78RoEzV94B2zA:-NUMjLEG7MTecMjwDkLZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L241)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 273 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUMCCrL39jAO2dmGcUh:-NUMjQzS8neCtfREadWl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L273)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 277 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUMC5Uu3pkbR02AslHe:-NUMjXPH48SuSo-3HS-S:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L277)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 284 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUMDO_jD2t3UXSnBfg8:-NUMkanjEBqWAAcVuoOg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L284)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add `span_ty()`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 289 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUMD87y--sWUo1KjA3Q:-NUMm08s6O4JTpOJJcgq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L289)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Actually I suggest to extract the code below to a utility function like `reinterpret_cast_signature()` which only gets the input and output types.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/pl [...]

2023-05-01 18:09 UTC, liorgold2 requested changes
> Reviewed 3 of 35 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 22 of 76 files reviewed, 12 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`corelib/src/span.cairo` line 10 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNUUhb8dC7bWw60Q1C:-NUNUUhb8dC7bWw60Q1D:bnu01hr) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/corelib/src/span.cairo#L10)):*
> ```Cairo
> impl SpanDrop<T, impl TDrop: Drop<T>> of Drop<Span<T>>;
> 
> extern fn span_pop_front<T>(span: Span<T>) -> Option<(Span<T>, Box<T>)> nopanic;
> ```

```
/// If the input span is non-empty, returns the span without the first element and a box with the first element. Otherwise, returns `None`.
```

Similarly for `pop_back`.
___
*[`corelib/src/span.cairo` line 36 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNUzksEizlNbaNcNo1:-NUNUzksEizlNbaNcNo2:bs0uewd) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/corelib/src/span.cairo#L36)):*
> ```Cairo
> impl SpanImpl<T> of SpanTrait<T> {
>     #[inline(always)]
>     fn pop_front(ref self: Span<T>) -> Option<T> {
> ```

Do we want the default behavior to be that `self` is `ref` here? It'll generate unnecessary code.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUMEDDN0EIfDJMMdNFd:-NUNO3hB0OotwHI-CqJ0:b5g4q2c) ([raw file](https://github.com/starkware-libs/cairo/blob/07cc5fd4d6891a74ae66fa0a40f93247723148e4/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L47)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Get a span of a subarray.
</blockquote></details>

I meant - in terms of ownership.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 186 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NULzjop2Lt94vceMTO8:-NUNQGhj5qfhpnXbVWrT:b-d7jpsj) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L186)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not pushed/not here.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 62 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNQh6T5eDHt7yktmYt:-NUNQh6T5eDHt7yktmYu:b-o6j9aw) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L62)):*
> ```XML
>     ) -> Result<LibfuncSignature, SpecializationError> {
>         let span_ty = get_span_ty(context, ty)?;
>         let snapshot_span_ty = snapshot_ty(context, span_ty)?;
> ```

In `get` the parameter is `Span<@T>`, here it is `@Span<T>`. Is there a reason? It's confusing.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 274 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNTaGR2TYQuPtlV6Hk:-NUNTaGR2TYQuPtlV6Hl:b-86895w) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L274)):*
> ```XML
> #[derive(Default)]
> pub struct SnapshotAsSpanLibfuncWrapped {}
> impl SignatureAndTypeGenericLibfunc for SnapshotAsSpanLibfuncWrapped {
> ```

And all other relevant places.



_Suggestion:_
```XML
SnapshotToSpanLibfuncWrapped
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/utils.rs` line 7 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNTqyw-wnR4LjvqZiP:-NUNTqyw-wnR4LjvqZiQ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/crates/cairo-lang-sierra/src/extensions/modules/utils.rs#L7)):*
> ```XML
> use crate::ids::ConcreteTypeId;
> 
> /// Returns a libfunc signature that casts from one type to another.
> ```





_Suggestion:_
```XML
/// Returns a libfunc signature that casts from one type to another without changing the internal representation.
/// The implementation must be the identity function (no CASM output).
```


<!-- Sent from Reviewable.io -->

2023-05-01 18:16 UTC, liorgold2 requested changes
> Reviewed 1 of 43 files at r2, 1 of 35 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 24 of 76 files reviewed, 15 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`corelib/src/span.cairo` line 32 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNVsxWBXYV7GwqOphz:-NUNVsxWBXYV7GwqOpi-:b-dbda7w) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/corelib/src/span.cairo#L32)):*
> ```Cairo
>     fn len(self: @Span<T>) -> usize;
>     fn is_empty(self: @Span<T>) -> bool;
>     fn span(self: @Span<T>) -> Span<@T>;
> ```

This is weird. Why is it called `span()`?
___
*[`corelib/src/span.cairo` line 89 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNWOCR9iy4ISUBq5qi:-NUNWOCR9iy4ISUBq5qj:b-57hk6q) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/corelib/src/span.cairo#L89)):*
> ```Cairo
>     #[inline(always)]
>     fn index(self: @Span<T>, index: usize) -> T {
>         *span_at(self.span(), index).unbox()
> ```

I think getting `@Span<T>` in `span_get` will make more sense. This is an example.
___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 66 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNWqdM7636tx2rXoaH:-NUNWqdM7636tx2rXoaI:b-qn2ns8) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/crates/cairo-lang-starknet/test_data/account.cairo#L66)):*
> ```Cairo
>     #[external]
>     #[raw_output]
>     fn __execute__(mut calls: Array<Call>) -> Span<@felt252> {
> ```

Why did it change?


<!-- Sent from Reviewable.io -->

2023-05-01 18:19 UTC, liorgold2 requested changes
> Reviewed 2 of 35 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 26 of 76 files reviewed, 17 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs_lists/testnet_v0.1.0.json` line 11 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNX1Jl2_nI_JW2uL-T:-NUNX1Jl2_nI_JW2uL-U:b-19t0tr) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/crates/cairo-lang-starknet/src/allowed_libfuncs_lists/testnet_v0.1.0.json#L11)):*
> ```JSON
>         "span_get",
>         "span_len",
>         "span_slice",
> ```

Remove functions that were not here before (except for the mandatory ones, such as `snapshot_array_as_span`).
___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs_lists/testnet_v0.1.0.json` line 13 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNXOWy9mw3DbvhxsEm:-NUNXOWy9mw3DbvhxsEn:ba3dfmt) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/crates/cairo-lang-starknet/src/allowed_libfuncs_lists/testnet_v0.1.0.json#L13)):*
> ```JSON
>         "span_slice",
>         "span_pop_front",
>         "span_pop_back",
> ```

Remove.


<!-- Sent from Reviewable.io -->

2023-05-01 18:36 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 26 of 76 files reviewed, 17 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNaUri3RtGiL8A1OQa:-NUNaUri3RtGiL8A1OQb:b-zefse) (no related file):*
I see `casm` files did change. Why?

___


<!-- Sent from Reviewable.io -->

2023-05-01 18:59 UTC, liorgold2 requested changes
> Reviewed 1 of 73 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 27 of 76 files reviewed, 18 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/mod.rs` line 89 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNfau889WP10DIshxi:-NUNfau889WP10DIshxj:bfwwz67) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/crates/cairo-lang-sierra/src/extensions/modules/starknet/mod.rs#L89)):*
> ```XML
>     context: &dyn SignatureSpecializationContext,
> ) -> Result<ConcreteTypeId, SpecializationError> {
>     context.get_wrapped_concrete_type(
> ```

Use the `span_ty` function.


<!-- Sent from Reviewable.io -->

2023-05-07 08:46 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 27 of 76 files reviewed, 18 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, @orizi, @span, and @t)

___
*[`corelib/src/span.cairo` line 36 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNUzksEizlNbaNcNo1:-NUpNLyJ6C5BHu0v8l8x:b-c1l01e) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/corelib/src/span.cairo#L36)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Do we want the default behavior to be that `self` is `ref` here? It'll generate unnecessary code.
</blockquote></details>

It's a quality of life function. Perhaps we want to add another pop_front version without it. Do you have name suggestions?
___
*[`corelib/src/span.cairo` line 89 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNWOCR9iy4ISUBq5qi:-NUpNbRj2-HBdHFpKZ7h:buysri3) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/corelib/src/span.cairo#L89)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I think getting `@Span<T>` in `span_get` will make more sense. This is an example.
</blockquote></details>

What will you do when you have Span<@T>? It doesn't make sense to convert it to @Span<T>, since there might never have been any Span<T>.


<!-- Sent from Reviewable.io -->

2023-05-07 08:47 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 27 of 76 files reviewed, 18 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, @orizi, @span, and @t)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/array.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUMEDDN0EIfDJMMdNFd:-NUpO4Au1rB0KsGOmndn:b-auhuhf) ([raw file](https://github.com/starkware-libs/cairo/blob/07cc5fd4d6891a74ae66fa0a40f93247723148e4/crates/cairo-lang-sierra/src/extensions/modules/array.rs#L47)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I meant - in terms of ownership.
</blockquote></details>

Get a non owning span


<!-- Sent from Reviewable.io -->

2023-05-07 09:00 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 27 of 76 files reviewed, 18 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, @orizi, @span, and @t)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 62 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNQh6T5eDHt7yktmYt:-NUpOOBW4yVe1b4jRXuh:b-dgvodq) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L62)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

In `get` the parameter is `Span<@T>`, here it is `@Span<T>`. Is there a reason? It's confusing.
</blockquote></details>

There is a reason, yes.
You can get len on any non owned span, so it should get @Span<T>
get() is more restrictive than it. You need a copyable T. This it is hard to express that (like we discussed with impl generic param on extern function), I resorted to get Enforce T to be copy by just getting `@T`, which is copyable.

Since `Span<@T>` is copyable, there is no need to get a snapshot in this function.


<!-- Sent from Reviewable.io -->

2023-05-18 06:44 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/2987)* status: 27 of 76 files reviewed, 18 unresolved discussions (waiting on @ilyalesokhin-starkware, @liorgold2, @orizi, @span, and @t)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNaUri3RtGiL8A1OQa:-NVhaHuE4eoz18Jx_ERr:bfgh834) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I see `casm` files did change. Why?
</blockquote></details>

Some inlinings happened at index(). I added inline(never), should be ok now.

___
___
*[`corelib/src/span.cairo` line 10 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNUUhb8dC7bWw60Q1C:-NVhaZfB8GUpMoAf7HCS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/corelib/src/span.cairo#L10)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

```
/// If the input span is non-empty, returns the span without the first element and a box with the first element. Otherwise, returns `None`.
```

Similarly for `pop_back`.
</blockquote></details>

Done.
___
*[`corelib/src/span.cairo` line 32 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNVsxWBXYV7GwqOphz:-NVhWb8O-R5bMaawld2_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/corelib/src/span.cairo#L32)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This is weird. Why is it called `span()`?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 186 at r3](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NULzjop2Lt94vceMTO8:-NVhWqVX4ZpbeCrHnh8T:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ed03fd00fecb8275c5b31a6ac2b801b5a76fef19/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L186)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Not pushed/not here.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/span.rs` line 274 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNTaGR2TYQuPtlV6Hk:-NVhWvmEAF--CnMJsQSS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/crates/cairo-lang-sierra/src/extensions/modules/span.rs#L274)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

And all other relevant places.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/utils.rs` line 7 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNTqyw-wnR4LjvqZiP:-NVhX8AX251f9FG7CCeX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/crates/cairo-lang-sierra/src/extensions/modules/utils.rs#L7)):*
> ```XML
> use crate::ids::ConcreteTypeId;
> 
> /// Returns a libfunc signature that casts from one type to another.
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/mod.rs` line 89 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNfau889WP10DIshxi:-NVhXWU_-UwcXDosoWMb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/crates/cairo-lang-sierra/src/extensions/modules/starknet/mod.rs#L89)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Use the `span_ty` function.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs_lists/testnet_v0.1.0.json` line 11 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNX1Jl2_nI_JW2uL-T:-NVhY31k3ObeNBJPA--L:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/crates/cairo-lang-starknet/src/allowed_libfuncs_lists/testnet_v0.1.0.json#L11)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Remove functions that were not here before (except for the mandatory ones, such as `snapshot_array_as_span`).
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/allowed_libfuncs_lists/testnet_v0.1.0.json` line 13 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNXOWy9mw3DbvhxsEm:-NVhY3JmBnWBLkwoOGbZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/crates/cairo-lang-starknet/src/allowed_libfuncs_lists/testnet_v0.1.0.json#L13)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/test_data/account.cairo` line 66 at r4](https://reviewable.io/reviews/starkware-libs/cairo/2987#-NUNWqdM7636tx2rXoaH:-NVhYA659OnYWWJcLyRD:b-60qoya) ([raw file](https://github.com/starkware-libs/cairo/blob/e9fc2320c1b8e18d0cf0f1002c4515516a1620c1/crates/cairo-lang-starknet/test_data/account.cairo#L66)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Why did it change?
</blockquote></details>

This was the easiest change. The new Span<@T> is equivalent to the old Span<T>. So, this only changed syntactically, not semantically.


<!-- Sent from Reviewable.io -->

2024-08-20 14:09 UTC, closed without merging