Added u512_divmod_by_u256.
starkware-libs/cairo pull request #3112
Opened 2023-05-10 08:01 UTC by orizi

**Stack**:
- #3141
- #3125
- #3112 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/3112)

2023-05-10 16:11 UTC, yuvalsw requested changes
> Reviewed 13 of 16 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3112)* status: all files reviewed, 25 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/integer.cairo` line 1120 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4XoS9EeZ12xjPcg2p:-NV4XoS9EeZ12xjPcg2q:b-vw6bcs) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/corelib/src/integer.cairo#L1120)):*
> ```Cairo
> }
> 
> extern fn u512_safe_divmod_by_u256(
> ```

please doc both. For the first - mostly the return types. For the second - what it does. I also think the order should be the other way around as the user function is the interface that should be used, but I don't feel strongly about it.
___
*[`corelib/src/test/integer_test.cairo` line 708 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4ZSMQ03hsvlI2M581:-NV4ZSMQ03hsvlI2M582:bjycoim) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/corelib/src/test/integer_test.cairo#L708)):*
> ```Cairo
> 
> #[test]
> fn test_u512_safe_div_rem_by_u256() {
> ```

same as in the previous PR - I suggest to change the error messages to have != instead of ==.
___
*[`corelib/src/test/integer_test.cairo` line 721 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4ZA_3-ZQ-S30ZERZP:-NV4ZA_3-ZQ-S30ZERZQ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/corelib/src/test/integer_test.cairo#L721)):*
> ```Cairo
>     assert(r == 0, '0 % 1 == 0');
>     let (q, r) = u512_safe_div_rem_by_u256(one, u256_as_non_zero(1));
>     assert(q == one, '1 / 1 == 0');
> ```





_Suggestion:_
```Cairo
assert(q == one, '1 / 1 == 1');
```
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4_Kou6dzHYJuMlLLj:-NV4_KovE0JfPsYQ1aT6:bwz6bwr) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-casm/src/hints/mod.rs#L142)):*
> ```XML
>     },
>     /// Divides dividend (represented by 4 128bit limbs) by divisor (represented by 2 128bit
>     /// limbs). Returns the quotient (represented by 4 128bit limbs) and remainder (represented
> ```

Worth noting that limb0 is the least-significant
___
*[`crates/cairo-lang-sierra/src/extensions/modules/int/unsigned512.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4dJdr5uUVSbBJvfcL:-NV4dJdr5uUVSbBJvfcM:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra/src/extensions/modules/int/unsigned512.rs#L19)):*
> ```XML
> define_libfunc_hierarchy! {
>     pub enum Uint512Libfunc {
>         DivModU256(Uint521DivmodU256Libfunc),
> ```





_Suggestion:_
```XML
(Uint512DivmodU256Libfunc
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/int/unsigned512.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4eS8QCLN4rhNcQOgl:-NV4eS8QCLN4rhNcQOgm:b19b8ag) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra/src/extensions/modules/int/unsigned512.rs#L54)):*
> ```XML
>                 OutputVarInfo {
>                     ty: guarantee_ty.clone(),
>                     ref_info: OutputVarReferenceInfo::SimpleDerefs,
> ```

export to a var and clone 4 times
___
*[`crates/cairo-lang-sierra/src/extensions/modules/int/unsigned512.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4euJG6izjO1tZgOfR:-NV4euJG6izjO1tZgOfS:b-23yo1i) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra/src/extensions/modules/int/unsigned512.rs#L76)):*
> ```XML
> 
> /// Helper for u512 type def.
> fn get_u512_type(
> ```

please move to crates/cairo-lang-sierra/src/extensions/modules/mod.rs
___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 556 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4hLbH3OD51t4ac8YL:-NV4hLbH3OD51t4ac8YM:bqjqf2o) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L556)):*
> ```XML
> fn u512_libfunc_cost(libfunc: &Uint512Concrete) -> Vec<ConstCost> {
>     match libfunc {
>         Uint512Concrete::DivModU256(_) => vec![ConstCost { steps: 51, holes: 0, range_checks: 14 }],
> ```

I count 15 range checks
(But as Written in another comment, I think there is one RC missing, so maybe a total of 16)
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4gnujEbgrYNuYOXiV:-NV4gnujEbgrYNuYOXiW:b-t59le1) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L22)):*
> ```XML
> 
> /// Generates casm instructions for `u512_safe_divmod_by_u256()`.
> fn build_u512_divmod_by_u256(
> ```

add "safe"
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4hF637pK3IhU0gOWF:-NV4hF637pK3IhU0gOWG:bfbfr1n) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L32)):*
> ```XML
>     let mut casm_builder = CasmBuilder::default();
>     add_input_variables! {casm_builder,
>         buffer(16) range_check;
> ```

I count 15, so it should be 14 here.
(But as Written in another comment, I think there is one RC missing, so maybe a total of 16 and here should be 15)
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4hd0o433rEezzpGix:-NV4hd0o433rEezzpGiy:b8l4j5c) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L45)):*
> ```XML
>         const one = 1;
>         const i16_upper_limiter = u128::MAX - i16::MAX as u128;
>         const i16_lower_limiter = -BigInt::from(i16::MIN);
> ```

Suggestion:
s/limiter/limit/
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4i84x6NPn5ygDFJ7D:-NV4i84y93sX9aTAh2ks:b-v70tvi) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L47)):*
> ```XML
>         const i16_lower_limiter = -BigInt::from(i16::MIN);
>         const u128_bound_minus_u64_bound = u128::MAX - u64::MAX as u128;
>         const u128_limit = (BigInt::from(u128::MAX) + 1) as BigInt;
> ```

I suggest consistent naming (other consistent namings are also OK)

Or another suggestion for u128_limit/u128_bound: exp128.



_Suggestion:_
```XML
        const u128_bound_minus_i16_upper_bound = u128::MAX - i16::MAX as u128;
        const i16_lower_bound = -BigInt::from(i16::MIN);
        const u128_bound_minus_u64_bound = u128::MAX - u64::MAX as u128;
        const u128_bound = (BigInt::from(u128::MAX) + 1) as BigInt;
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4j6taCl0oAeDEdDJN:-NV4j6taCl0oAeDEdDJO:b-u7y1rz) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L87)):*
> ```XML
>         tempvar diff1 = divisor1 - remainder1;
>         tempvar diff0  [...]

2023-05-11 09:03 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3112)* status: all files reviewed, 15 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`corelib/src/integer.cairo` line 1120 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4XoS9EeZ12xjPcg2p:-NV90g2Z0OmiD_O1KgT6:b-896fjb) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/corelib/src/integer.cairo#L1120)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please doc both. For the first - mostly the return types. For the second - what it does. I also think the order should be the other way around as the user function is the interface that should be used, but I don't feel strongly about it.
</blockquote></details>

Done 
___
*[`crates/cairo-lang-sierra/src/extensions/modules/int/unsigned512.rs` line 54 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4eS8QCLN4rhNcQOgl:-NV91i8PCKQXWXYkpacK:b-yodiy3) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra/src/extensions/modules/int/unsigned512.rs#L54)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

export to a var and clone 4 times
</blockquote></details>

not clonable - and rather not do this at this pr.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/int/unsigned512.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4euJG6izjO1tZgOfR:-NV91myp4ylaCMjGZibJ:boapzwu) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra/src/extensions/modules/int/unsigned512.rs#L76)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please move to crates/cairo-lang-sierra/src/extensions/modules/mod.rs
</blockquote></details>

i rather do that only if and when it actually is used out of file.
___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 556 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4hLbH3OD51t4ac8YL:-NV8v5Hj8-kjyX-hIOht:b-ky9ity) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L556)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I count 15 range checks
(But as Written in another comment, I think there is one RC missing, so maybe a total of 16)
</blockquote></details>

it is automatically counted - you probably counted 2 branches.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4hF637pK3IhU0gOWF:-NV8vEEq9O_0vtUSoj2z:b-7ropln) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L32)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I count 15, so it should be 14 here.
(But as Written in another comment, I think there is one RC missing, so maybe a total of 16 and here should be 15)
</blockquote></details>

ditto
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4hd0o433rEezzpGix:-NV8vI_VExaRkbGv60DD:b-c25r4j) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L45)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Suggestion:
s/limiter/limit/
</blockquote></details>

it isn't a limit - it is a limiter to be used by the range check.
but done with the next suggestion.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4j6taCl0oAeDEdDJN:-NV8zeDaDDAJ21CW9LoS:b-kjfq6z) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L87)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

compute this only after the jump
</blockquote></details>

we do not  remove cost from just a single side of the branch, as it requires alignments later.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4jNyUDd8Igg-uR9yk:-NV8zT4m21bCEAajg_j6:bwh0pnx) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L96)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why is it divided to 3 `casm_build_extend`s?
</blockquote></details>

just preventing max macro resolve depth. (since the macro is unwrapped recursively)
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV5BiZiAA7IQ5y2kZf0:-NV8vU196Jm6RICKhomh:bsxwdf9) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L97)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why do you need ap+= here but not in other places?
</blockquote></details>

since we allocate a lot of values filled by hints and don't have enough instructions that do not allocate variables to cover it up.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV5IeU47awQBSiJWZBg:-NV8vegQ8y-dhNiwGX06:bvs6611) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L116)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

You don't assert the equality in limbs 0,1,2.
</blockquote></details>

i make sure the leftover is small until the last limb - so yes i do.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV5JND22WVyM414Zu9Q:-NV8vqp917PxNn6Lflsf:b-v53wyr) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L149)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

You don't *know* this. This is what you expect and thus it's sufficient to assert this.
Am I missing something?
</blockquote></details>

we `know` it is so for any valid calculation - so there's no need to validate it.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV5I1Qg8nUu9XAXmlFD:-NV8xgwU0W0blMaUWwLk:b-t92u63) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L154)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think you missed q1d1_high in that case.
</blockquote></details>

good catch - though i should add it to everything.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 182 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV5MhPI8pZ1w91AYdme:-NV8wS_IA2oyXfSm_Tn4:b-nmcrtr) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L182)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Are you sure this shoul [...]

2023-05-11 10:20 UTC, yuvalsw requested changes
> Reviewed 8 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3112)* status: 15 of 16 files reviewed, 10 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/integer.cairo` line 1120 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV9AQLg-Wza4dh0bNZ-:-NV9AQLhDLXX8AORxUHo:b-pv8cqu) ([raw file](https://github.com/starkware-libs/cairo/blob/c4fac5f2ac4980a5f34e8fb3e369953b164fdb26/corelib/src/integer.cairo#L1120)):*
> ```Cairo
> }
> 
> /// Calculates division and remainder of a u512 by a non-zero u256.
> ```

or "quotient and remainder".

Same below.



_Suggestion:_
```Cairo
Calculates division with remainder
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/int/unsigned512.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4euJG6izjO1tZgOfR:-NV9BPpy31414xtBd-Oi:bzbnbkq) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra/src/extensions/modules/int/unsigned512.rs#L76)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i rather do that only if and when it actually is used out of file.
</blockquote></details>

I see your point, but it's a bit strange that we have the exact same function for 256 and they are in different places.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV5BiZiAA7IQ5y2kZf0:-NV9Ci_MEgRxx7srd00J:bnxtnap) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L97)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

since we allocate a lot of values filled by hints and don't have enough instructions that do not allocate variables to cover it up.
</blockquote></details>

WDYM by "cover it up"?
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV5I1Qg8nUu9XAXmlFD:-NV9DXeg1GLD5tMp5LGc:b-b04kkf) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L154)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

good catch - though i should add it to everything.
</blockquote></details>

You don't need to add it in the case d1 is zero as q1d1 would be 0.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 178 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV5OywT3peSWE5TyPja:-NV9ItiW6QLoAXZu4wud:byup2ee) ([raw file](https://github.com/starkware-libs/cairo/blob/8039dd609d5cdbdf7b6c532b4b8599b1c6bbd4fc/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L178)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

all was rangechecked right after the hint.
</blockquote></details>

quotient2/quotient3 were rangechecked. divisor0/divisor1 (inputs) weren't. Actually I am not sure - don't we also need to range check the inputs anyway to make sure they are u128?
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 44 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV9C3oa8i-vEdNpPXvx:-NV9C3oa8i-vEdNpPXvy:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c4fac5f2ac4980a5f34e8fb3e369953b164fdb26/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L44)):*
> ```XML
>         const zero = 0;
>         const one = 1;
>         const u128_bound_minus_i64_upper_bound = u128::MAX - i16::MAX as u128;
> ```





_Suggestion:_
```XML
nst u128_bound_minus_i16_upper_bound = u128:
```
___
*[`tests/e2e_test_data/libfuncs/u512` line 3 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4fYcy8OBVb6E1aDG5:-NV9JFVw-jgp_s8GbLon:boof3vr) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/tests/e2e_test_data/libfuncs/u512#L3)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

remove
</blockquote></details>

Still there.
___
*[`tests/e2e_test_data/libfuncs/u512` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4fm8HAAG_XFxNqK4P:-NV9JWv-CHN7WtgsG7cz:boof3vr) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/tests/e2e_test_data/libfuncs/u512#L10)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

"::" needed?
</blockquote></details>

Still there.


<!-- Sent from Reviewable.io -->

2023-05-11 10:32 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3112)* status: 15 of 16 files reviewed, 7 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV5BiZiAA7IQ5y2kZf0:-NV9LaB1E1LdZCfKf2_z:b-ht5hik) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L97)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

WDYM by "cover it up"?
</blockquote></details>

the builder automatically uses commands that allow for `ap++` but do not need it for allocating a new var to allocate space on `ap` without a special `ap += *` command.
this time we just do not have enough space.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV5I1Qg8nUu9XAXmlFD:-NV9LzBP4O4eL_hYwL-4:b27z6t2) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L154)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

You don't need to add it in the case d1 is zero as q1d1 would be 0.
</blockquote></details>

true - but again - all optimisations that do not improve all branches are ignored.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 178 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV5OywT3peSWE5TyPja:-NV9M8gfDGrOilOnnelV:b-e65ttq) ([raw file](https://github.com/starkware-libs/cairo/blob/8039dd609d5cdbdf7b6c532b4b8599b1c6bbd4fc/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L178)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

quotient2/quotient3 were rangechecked. divisor0/divisor1 (inputs) weren't. Actually I am not sure - don't we also need to range check the inputs anyway to make sure they are u128?
</blockquote></details>

they are "range checked" due to the type system.
___
*[`tests/e2e_test_data/libfuncs/u512` line 3 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NV4fYcy8OBVb6E1aDG5:-NV9KtZE-kaNSzH2CVhk:b-d6lph7) ([raw file](https://github.com/starkware-libs/cairo/blob/cdd31272999ce17e642352a3055462e9a2afc910/tests/e2e_test_data/libfuncs/u512#L3)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Still there.
</blockquote></details>

probably something about updating during test running.
Done


<!-- Sent from Reviewable.io -->

2023-05-15 09:16 UTC, yuvalsw approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3112#-:-NVTgWWg6sSspidPTBOp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs` line 150 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3112#-NVTc2RxAj3xk6nFnL7k:-NVTc2RxAj3xk6nFnL7l:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d87659a87b25c11acf16a9fd2c20720db8826da1/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned512.rs#L150)):*
> ```XML
>         // So we know that quotient3 or divisor1 are 0.
>         // We also know that quotient2*divisor1 and quotient3*divisor0 are smaller than 2**128.
>         // Therefore the smaller of each pair must be smaller than 2**64, and if we check this we can avoid wraparound on the prime.
> ```





_Suggestion:_
```XML
        // We know that limb4 and limb5 should be 0.
        // Therfore quotient3 or divisor1 should also be 0.
        // We also know that quotient2*divisor1 and quotient3*divisor0 should be smaller than 2**128.
        // Therefore the smaller of each pair must be smaller than 2**64.
        // So by checking this we can avoid wraparound on the prime.
```


<!-- Sent from Reviewable.io -->

2023-05-15 09:43 UTC, merged