Cairo-LS: Add fallback corelib path config key
starkware-libs/cairo pull request #3235
Opened 2023-05-24 09:51 UTC by maciektr

- Add configuration option for providing corelib path (if other ways of corelib detection fail)
- Add option to disable Scarb based resolution
- Run standalone Cairo-LS for non Scarb projects if provided explicitly in config

2023-05-24 14:17 UTC, mkaput requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3235)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 274 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3235#-NWCpzULBVFkOfEkXH0Y:-NWCpzULBVFkOfEkXH0Z:b-6uk8r1) ([raw file](https://github.com/starkware-libs/cairo/blob/040a3cb6a9ec77c90c4592915178d20cd9735bcc/crates/cairo-lang-language-server/src/lib.rs#L274)):*
> ```XML
>                 if let Some(Value::String(value)) = value_vec.get(0) {
>                     if !value.is_empty() {
>                         let root_path: PathBuf = value.into();
> ```

Would it be possible to re-use the logic from detect_corelib? Seems like what is needed is to just add a possibility to parameterize it with `root_path`
___
*[`vscode-cairo/src/extension.ts` line 222 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3235#-NWCqcngD4MZ83P4RuQh:-NWCqcngD4MZ83P4RuQi:b62yi9l) ([raw file](https://github.com/starkware-libs/cairo/blob/040a3cb6a9ec77c90c4592915178d20cd9735bcc/vscode-cairo/src/extension.ts#L222)):*
> ```XML
>     return false;
>   }
>   if (fs.existsSync(path + "/Scarb.toml")) {
> ```

Couldn't this function be async?


<!-- Sent from Reviewable.io -->

2023-05-25 07:37 UTC, maciektr reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3235)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 274 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3235#-NWCpzULBVFkOfEkXH0Y:-NWEaS6y0ktVO0a5gMw5:byil4p) ([raw file](https://github.com/starkware-libs/cairo/blob/040a3cb6a9ec77c90c4592915178d20cd9735bcc/crates/cairo-lang-language-server/src/lib.rs#L274)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Would it be possible to re-use the logic from detect_corelib? Seems like what is needed is to just add a possibility to parameterize it with `root_path`
</blockquote></details>

Well, I thought about this, but I believe I propose a slightly different logic than the one used in corelib detection from the filesystem crate.  
I think that we should not search higher in the directory tree than the path provided by the user and we should allow calling the directory a different name than "corelib". This boils down to three cases:

- User provides a path to a directory than contains `/corelib/src`,  only without the suffix
- User provides a path to a directory that contains the `/src`, the directory itself is called with an arbitrary name
- User provides a path to a directory that does not contain either `/corelib` nor `/src`

We could use the logic from the filesystem crate for the first case only, which made me think it is not actually worth it. 
Please let me know if I should change it anyway. 
___
*[`vscode-cairo/src/extension.ts` line 222 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3235#-NWCqcngD4MZ83P4RuQh:-NWGpmou3Ry5CE1BB0ue:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/040a3cb6a9ec77c90c4592915178d20cd9735bcc/vscode-cairo/src/extension.ts#L222)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Couldn't this function be async?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-25 07:55 UTC, mkaput approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3235)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 274 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3235#-NWCpzULBVFkOfEkXH0Y:-NWGtrYd2QXjqDHn-l_p:b65hcrm) ([raw file](https://github.com/starkware-libs/cairo/blob/040a3cb6a9ec77c90c4592915178d20cd9735bcc/crates/cairo-lang-language-server/src/lib.rs#L274)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Well, I thought about this, but I believe I propose a slightly different logic than the one used in corelib detection from the filesystem crate.  
I think that we should not search higher in the directory tree than the path provided by the user and we should allow calling the directory a different name than "corelib". This boils down to three cases:

- User provides a path to a directory than contains `/corelib/src`,  only without the suffix
- User provides a path to a directory that contains the `/src`, the directory itself is called with an arbitrary name
- User provides a path to a directory that does not contain either `/corelib` nor `/src`

We could use the logic from the filesystem crate for the first case only, which made me think it is not actually worth it. 
Please let me know if I should change it anyway. 
</blockquote></details>

Oh, your observations are very correct! I overlooked that. Let's leave this as-is.


<!-- Sent from Reviewable.io -->

2023-05-25 07:55 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>, waiting for @orizi 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3235#-:-NWGtzse9Hzy-LHniPax:b-ppxld0)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2023-05-28 07:55 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3235)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 263 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3235#-NWWLDrX20_x0CPeO6cZ:-NWWLDrX20_x0CPeO6c_:b-e30tvm) ([raw file](https://github.com/starkware-libs/cairo/blob/e468757152f47c3f632132eb28df63163b6ad1cb/crates/cairo-lang-language-server/src/lib.rs#L263)):*
> ```XML
>     }
> 
>     async fn get_corelib_fallback_path(&self) -> Option<PathBuf> {
> ```

this seems like duplication of the functionality in `crates/cairo-lang-filesystem/src/detect.rs`

+ doc this function.



_Code quote:_
```XML
get_corelib_fallback_path
```


<!-- Sent from Reviewable.io -->

2023-05-28 07:55 UTC, orizi reviewed
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3235)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr)



<!-- Sent from Reviewable.io -->

2023-05-28 20:14 UTC, maciektr commented
*[`crates/cairo-lang-language-server/src/lib.rs` line 263 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3235#-NWWLDrX20_x0CPeO6cZ:-NWYnUIHEgHef_WF3x9U:bfw3gcs) ([raw file](https://github.com/starkware-libs/cairo/blob/e468757152f47c3f632132eb28df63163b6ad1cb/crates/cairo-lang-language-server/src/lib.rs#L263)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this seems like duplication of the functionality in `crates/cairo-lang-filesystem/src/detect.rs`

+ doc this function.
</blockquote></details>

I have added the docs, thanks! To your first point, I have left a more comprehensive explanation below. Would you mind letting me know if you agree with the points made there? Pasting it below for easier reference. 

Well, I thought about this, but I believe I propose a slightly different logic than the one used in corelib detection from the filesystem crate.  
I think that we should not search higher in the directory tree than the path provided by the user and we should allow calling the directory a different name than "corelib". This boils down to three cases:

-   User provides a path to a directory than contains `/corelib/src`, only without the suffix
-   User provides a path to a directory that contains the `/src`, the directory itself is called with an arbitrary name
-   User provides a path to a directory that does not contain either `/corelib` nor `/src`

We could use the logic from the filesystem crate for the first case only, which made me think it is not actually worth it.  


<!-- Sent from Reviewable.io -->

2023-05-29 04:13 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3235#-:-NW_hS-g1I1fF9kn8sj5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)



<!-- Sent from Reviewable.io -->

2023-05-29 04:45 UTC, merged