Cheatcode function
starkware-libs/cairo pull request #3488
Opened 2023-06-22 17:38 UTC by piotmag769

This PR is meant to introduce the `cheatcode` function. Cairo users can implement their own cheatcodes by injecting custom `CairoHintProcessor`. It will help Protostar to get rid of Cairo fork.

The print cheatcode implementation is just for testing, to be removed when merging.

2023-06-22 18:11 UTC, piotmag769 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: 0 of 8 files reviewed, all discussions resolved

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/starknet/testing.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYZHZBy0wRch1MeEvVp:-NYZHZBy0wRch1MeEvVq:b-z7d3ta) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-sierra-to-casm/src/invocations/starknet/testing.rs#L130)):*
> ```XML
>                 [input_start, input_end],
>                 [output_start, output_end],
>             );
> ```

Tried using `casm_build_extend!` here but I would have to modify the macro definition for it to work - it treats `selector` as an input argument
```rust
            casm_build_extend! {casm_builder,
                tempvar output_start;
                tempvar output_end;
                hint StarknetHint::Cheatcode {
                    selector: selector,
                    input_start: input_start,
                    input_end: input_end
                } into {
                    output_start: output_start,
                    output_end: output_end
                };
                ap += 2;
            };
```



_Code quote:_
```XML
            casm_builder.add_hint(
                |[input_start, input_end], [output_start, output_end]| StarknetHint::Cheatcode {
                    selector: BigIntAsHex { value: c.selector.clone() },
                    input_start,
                    input_end,
                    output_start,
                    output_end,
                },
                [input_start, input_end],
                [output_start, output_end],
            );
```


<!-- Sent from Reviewable.io -->

2023-06-22 18:26 UTC, orizi requested changes
> Reviewed 5 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @piotmag769)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 709 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYZJLADD-g6oVR7xi6P:-NYZJLADD-g6oVR7xi6Q:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-casm/src/hints/mod.rs#L709)):*
> ```XML
>         match self {
>             StarknetHint::Cheatcode { .. } => {
>                 write!(f, "cheatcode")
> ```





_Suggestion:_
```XML
raise NotImplemented
```
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 391 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYZLFUV0twc_m88uhkr:-NYZLFUV0twc_m88uhks:bu4vurb) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-runner/src/casm_run/mod.rs#L391)):*
> ```XML
>                 }
>             }
>             StarknetHint::Cheatcode {
> ```

Are you planning to add some sort of hook here?
if so add  a TODO to make the plan more explicit.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 407 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYZLUWd3IkMOasiRxb9:-NYZLUWd3IkMOasiRxbA:b-wspn1d) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-runner/src/casm_run/mod.rs#L407)):*
> ```XML
>                             let (base, offset) = extract_buffer(value);
>                             get_ptr(vm, base, &offset)
>                         };
> ```

maybe a non-print example?
just one of the other setter cheatcodes instead?
e.g. set_signature? (just replacing its implementation with this)
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/starknet/testing.rs` line 130 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYZHZBy0wRch1MeEvVp:-NYZJmGK4vixA_uTdo0f:b-eb3fym) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-sierra-to-casm/src/invocations/starknet/testing.rs#L130)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Tried using `casm_build_extend!` here but I would have to modify the macro definition for it to work - it treats `selector` as an input argument
```rust
            casm_build_extend! {casm_builder,
                tempvar output_start;
                tempvar output_end;
                hint StarknetHint::Cheatcode {
                    selector: selector,
                    input_start: input_start,
                    input_end: input_end
                } into {
                    output_start: output_start,
                    output_end: output_end
                };
                ap += 2;
            };
```
</blockquote></details>

generally - we do not use non CASM options in hints.
But it is sensible to allow it.
(allowing it through the macro should be pretty easy, but let leave it for now)
___
*[`crates/cairo-lang-starknet/cairo_level_tests/cheatcode_tests.cairo` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYZLnPGEXTFhNWyHS8-:-NYZLnPGEXTFhNWyHS80:bqxtkqn) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-starknet/cairo_level_tests/cheatcode_tests.cairo#L14)):*
> ```Cairo
> 
>     assert(1 == 1, '');
> }
> ```

this tests nothing - but you can actually implement set_block_number with the cheatcode.



_Code quote:_
```Cairo
#[test]
#[available_gas(300000)]
fn test_set_block_number() {
    let mut data = ArrayTrait::new();
    data.append(42);

    let r = cheatcode::<'print'>(data.span());

    assert(1 == 1, '');
}
```


<!-- Sent from Reviewable.io -->

2023-06-22 22:47 UTC, piotmag769 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @orizi and @piotmag769)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 709 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYZJLADD-g6oVR7xi6P:-NYZOiIi5tsdLNca7IQz:b-1wap6v) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-casm/src/hints/mod.rs#L709)):*
> ```XML
>         match self {
>             StarknetHint::Cheatcode { .. } => {
>                 write!(f, "cheatcode")
> ```

Will do before merging - otherwise there is an error when running `./scripts/starknet_test.sh`
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 391 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYZLFUV0twc_m88uhkr:-NYZNuQd3SRWb8jS6qeZ:bvcw182) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-runner/src/casm_run/mod.rs#L391)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Are you planning to add some sort of hook here?
if so add  a TODO to make the plan more explicit.
</blockquote></details>

I would leave it as it is (maybe without the example cheatcode) . There is already a way to inject a custom `CairoHintProcessor` afaik, it should be enough.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 407 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYZLUWd3IkMOasiRxb9:-NYZPQB83SCZvNfK360v:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-runner/src/casm_run/mod.rs#L407)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe a non-print example?
just one of the other setter cheatcodes instead?
e.g. set_signature? (just replacing its implementation with this)
</blockquote></details>

Done
___
*[`crates/cairo-lang-starknet/cairo_level_tests/cheatcode_tests.cairo` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYZLnPGEXTFhNWyHS8-:-NYZPvt9AzEc_4k8-e2e:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-starknet/cairo_level_tests/cheatcode_tests.cairo#L14)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this tests nothing - but you can actually implement set_block_number with the cheatcode.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-25 05:11 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @piotmag769)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 709 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYZJLADD-g6oVR7xi6P:-NYfsRTj66OgyfFOJEhS:b4y3r8l) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-casm/src/hints/mod.rs#L709)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Will do before merging - otherwise there is an error when running `./scripts/starknet_test.sh`
</blockquote></details>

That is the python hints - this shouldn't affect this repo.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 407 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYZLUWd3IkMOasiRxb9:-NYkxUCK71yJZvzu5UDr:bgeey4y) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-runner/src/casm_run/mod.rs#L407)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Done
</blockquote></details>

and replace the high level implementation of set_block_number with this.


<!-- Sent from Reviewable.io -->

2023-06-25 13:55 UTC, piotmag769 reviewed
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: 1 of 8 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 709 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYZJLADD-g6oVR7xi6P:-NYmcqCh5zoLsrKiJ5S_:b57bl2e) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-casm/src/hints/mod.rs#L709)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

That is the python hints - this shouldn't affect this repo.
</blockquote></details>

Misunderstanding, done.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 407 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYZLUWd3IkMOasiRxb9:-NYmfK110XtQZJ5z3SeO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-runner/src/casm_run/mod.rs#L407)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and replace the high level implementation of set_block_number with this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-25 14:05 UTC, orizi requested changes
> Reviewed 5 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmrdSg6eK7MCEj3PD8:-NYmrdSg6eK7MCEj3PD9:ba5frw1) (no related file):*
@yuvalsw added for 2nd eye.
@ilyalesokhin-starkware - for making sure deleting the hint is fine.

___


<!-- Sent from Reviewable.io -->

2023-06-25 14:05 UTC, orizi requested changes
> Reviewed 2 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed, 2 unresolved discussions (waiting on @piotmag769)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/testing.rs` line 196 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmrurh5dYF-mwXSPnR:-NYmrurh5dYF-mwXSPnS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8d3158df3a8f95d0211bae608b603a2bc85fec87/crates/cairo-lang-sierra/src/extensions/modules/starknet/testing.rs#L196)):*
> ```XML
> }
> 
> /// Libfunc for creating a constant felt252.
> ```





_Suggestion:_
```XML
/// Libfunc for a general cheatcode.
```


<!-- Sent from Reviewable.io -->

2023-06-25 14:06 UTC, orizi reviewed
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed, 2 unresolved discussions (waiting on @piotmag769)



<!-- Sent from Reviewable.io -->

2023-06-25 14:07 UTC, ilyalesokhin-starkware commented
why is it called `cheatcode`?





<!-- Sent from Reviewable.io -->

2023-06-25 14:08 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 707 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmsZQO6YsVji3x8lgF:-NYmsZQO6YsVji3x8lgG:b-40i7sa) ([raw file](https://github.com/starkware-libs/cairo/blob/8d3158df3a8f95d0211bae608b603a2bc85fec87/crates/cairo-lang-casm/src/hints/mod.rs#L707)):*
> ```XML
>         match self {
>             StarknetHint::Cheatcode { .. } => {
>                 write!(f, "raise NotImplementedError")
> ```

Shouldn't the compilation fail here?


<!-- Sent from Reviewable.io -->

2023-06-25 14:16 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @piotmag769)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 707 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmsZQO6YsVji3x8lgF:-NYmuDl1ESdMnO_yFrPJ:bsmfqrg) ([raw file](https://github.com/starkware-libs/cairo/blob/8d3158df3a8f95d0211bae608b603a2bc85fec87/crates/cairo-lang-casm/src/hints/mod.rs#L707)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Shouldn't the compilation fail here?
</blockquote></details>

do you mean panic?
this shouldn't actually be in any generated printed casm.


<!-- Sent from Reviewable.io -->

2023-06-25 14:50 UTC, yuvalsw requested changes
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed, 9 unresolved discussions (waiting on @ilyalesokhin-starkware and @piotmag769)

___
*[`corelib/src/starknet/testing.cairo` line 24 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYn-wNa8qbU5h5fAVLM:-NYn-wNa8qbU5h5fAVLN:b-wbl1ry) ([raw file](https://github.com/starkware-libs/cairo/blob/8d3158df3a8f95d0211bae608b603a2bc85fec87/corelib/src/starknet/testing.cairo#L24)):*
> ```Cairo
> ) -> Span<felt252> implicits() nopanic;
> 
> fn set_block_number(block_number: u64) {
> ```

please document.
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 709 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmsuerAb-8s-LmzuLQ:-NYmsuerAb-8s-LmzuLR:bn9olp6) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-casm/src/hints/mod.rs#L709)):*
> ```XML
>         match self {
>             StarknetHint::Cheatcode { .. } => {
>                 write!(f, "cheatcode")
> ```

Please use the same format as others, and also print the selector.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 397 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmtBf395B57YQjC_65:-NYmtBf395B57YQjC_66:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-runner/src/casm_run/mod.rs#L397)):*
> ```XML
>                 output_start: _,
>                 output_end: _,
>             } => {
> ```





_Suggestion:_
```XML
            StarknetHint::Cheatcode {
                selector,
                input_start,
                input_end,
                ..
            } => {
```
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 425 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmuSJqCavzKTMepgrz:-NYmuSJqCavzKTMepgs-:bec1nja) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-runner/src/casm_run/mod.rs#L425)):*
> ```XML
>                         }
>                     }
>                     _ => Err(HintError::CustomHint(Box::from("Unknown hint")))?,
> ```

Please print the unknown selector.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 425 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmyf3zAZ1IXTcyA7dD:-NYmyf3zAZ1IXTcyA7dE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e003c22dc401dd65ecb438c7fb981e1761acbe21/crates/cairo-lang-runner/src/casm_run/mod.rs#L425)):*
> ```XML
>                         }
> 
>                         self.starknet_state.exec_info.block_info.block_number = input[0].clone();
> ```





_Suggestion:_
```XML
                        match &input[..] {
                            [input] => {
                                    self.starknet_state.exec_info.block_info.block_number = input.clone();
                                }
                            _ => {
                                return Err(HintError::CustomHint(Box::from(
                                    "set_block_number cheatcode invalid args: pass span of an array \
                                    with exactly one element",
                                )));
                        }
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/testing.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmvW9B4D7HZM4dItbm:-NYmvW9B4D7HZM4dItbn:bs3uf56) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-sierra/src/extensions/modules/starknet/testing.rs#L213)):*
> ```XML
>         &self,
>         context: &dyn SignatureSpecializationContext,
>         _args: &[GenericArg],
> ```

Please verify args is empty.


<!-- Sent from Reviewable.io -->

2023-06-25 14:58 UTC, ilyalesokhin-starkware reviewed
> Reviewed 3 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed, 8 unresolved discussions (waiting on @piotmag769)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 707 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmsZQO6YsVji3x8lgF:-NYn2odh9s5OHmNgAIoE:b-pxm31g) ([raw file](https://github.com/starkware-libs/cairo/blob/8d3158df3a8f95d0211bae608b603a2bc85fec87/crates/cairo-lang-casm/src/hints/mod.rs#L707)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do you mean panic?
this shouldn't actually be in any generated printed casm.
</blockquote></details>

Is it hard to return a failure here?

I guess we have an issue with the Display using pythonic hint in general, but it is beyond this PR,

Changed to non-blocking.


<!-- Sent from Reviewable.io -->

2023-06-25 16:28 UTC, piotmag769 reviewed
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed, 6 unresolved discussions (waiting on @orizi, @piotmag769, and @yuvalsw)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 709 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmsuerAb-8s-LmzuLQ:-NYnGLCG9AiLoiOPdwU0:bsqxz9p) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-casm/src/hints/mod.rs#L709)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Please use the same format as others, and also print the selector.
</blockquote></details>

I was asked by @orizi to do it the way it is done now.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 425 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmuSJqCavzKTMepgrz:-NYnHHtl3nDHGwSZRV58:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-runner/src/casm_run/mod.rs#L425)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Please print the unknown selector.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 425 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmyf3zAZ1IXTcyA7dD:-NYnJZI1CLsp0qbv2OD2:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/e003c22dc401dd65ecb438c7fb981e1761acbe21/crates/cairo-lang-runner/src/casm_run/mod.rs#L425)):*
> ```XML
>                         }
> 
>                         self.starknet_state.exec_info.block_info.block_number = input[0].clone();
> ```

Done
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/testing.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmvW9B4D7HZM4dItbm:-NYnFqz7AiRJIcq6UWbo:b-39s9wi) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-sierra/src/extensions/modules/starknet/testing.rs#L213)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Please verify args is empty.
</blockquote></details>

It is not empty, there is always a `selector` generic arg there. We just don't use it here since the signature will always be the same. I can pass an empty array to this function (it is called in `specialize`) and assert that it is empty if that suits you better, but I don't see how it is beneficial.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/testing.rs` line 196 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmrurh5dYF-mwXSPnR:-NYnHInb0nHcj5hEllbL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8d3158df3a8f95d0211bae608b603a2bc85fec87/crates/cairo-lang-sierra/src/extensions/modules/starknet/testing.rs#L196)):*
> ```XML
> }
> 
> /// Libfunc for creating a constant felt252.
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-06-25 16:54 UTC, piotmag769 reviewed
It is a name used by Protostar that originally comes from Foundry. It is called this way since some cheatcodes allow you to illegally (that's where "cheat" comes from) modify the state of a blockchain for testing purposes

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488#-:-NYnQ5YiC4KNVtx18bb-:br1dm32)* status: all files reviewed, 6 unresolved discussions (waiting on @orizi, @piotmag769, and @yuvalsw)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 709 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmsuerAb-8s-LmzuLQ:-NYnOMse9P8xrd-Olghu:b-fmxelz) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-casm/src/hints/mod.rs#L709)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

I was asked by @orizi to do it the way it is done now.
</blockquote></details>

Oh wait, you are looking at the r1 revision, look at the latest one. 
Also now I noticed: I think there is a mistake in Display implementation of PopLog, `raise NotImplemented` is not a valid python instruction - https://docs.python.org/3/library/constants.html#NotImplemented. Should I correct it?


<!-- Sent from Reviewable.io -->

2023-06-26 06:25 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @piotmag769 and @yuvalsw)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 709 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmsuerAb-8s-LmzuLQ:-NYqGrUE5-GI370RdyWf:bf5o58n) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-casm/src/hints/mod.rs#L709)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Oh wait, you are looking at the r1 revision, look at the latest one. 
Also now I noticed: I think there is a mistake in Display implementation of PopLog, `raise NotImplemented` is not a valid python instruction - https://docs.python.org/3/library/constants.html#NotImplemented. Should I correct it?
</blockquote></details>

Would be appreciated - I mostly cared that if someone writes code that is not runnable in python - an error would occur soon (and not just after we try to access the value not provided by the hint)
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 407 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqMTft4k89wE7m05QA:-NYqMTft4k89wE7m05QB:b-vs9nbj) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdc03fa6d1cd6c22c70f5677e5aea117b9c9490/crates/cairo-lang-runner/src/casm_run/mod.rs#L407)):*
> ```XML
>                             input.push(value.into_owned());
>                             curr += 1;
>                         }
> ```

`extract_relocatable` assuming https://reviewable.io/reviews/starkware-libs/cairo/3503 was merged.
otherwise - just the moving out of the match, and the `vm_get_range` usage.



_Suggestion:_
```XML
                let input_start = extract_relocatable(vm, input_start)?;
                let input_end = extract_relocatable(vm, input_end)?;
                let inputs = vm_get_range(vm, input_start, input_end)?;
                match selector {
                    "set_block_number" => {
```


<!-- Sent from Reviewable.io -->

2023-06-26 07:53 UTC, piotmag769 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware, @mkaput, @orizi, and @yuvalsw)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 709 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmsuerAb-8s-LmzuLQ:-NYqWL9b9f4hW4OxRVpv:b-nqeyi2) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-casm/src/hints/mod.rs#L709)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Would be appreciated - I mostly cared that if someone writes code that is not runnable in python - an error would occur soon (and not just after we try to access the value not provided by the hint)
</blockquote></details>

Unfortunately correcting it makes the starknet tests fail - there must be a bug in the logic behind python hints, but that's out of the scope of this PR
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 407 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqMTft4k89wE7m05QA:-NYqX1NG3cjjlorV2J45:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdc03fa6d1cd6c22c70f5677e5aea117b9c9490/crates/cairo-lang-runner/src/casm_run/mod.rs#L407)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

`extract_relocatable` assuming https://reviewable.io/reviews/starkware-libs/cairo/3503 was merged.
otherwise - just the moving out of the match, and the `vm_get_range` usage.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-26 07:54 UTC, mkaput requested changes
> Reviewed 1 of 8 files at r1, 4 of 7 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed, 10 unresolved discussions (waiting on @orizi, @piotmag769, and @yuvalsw)

___
*[`corelib/src/starknet/testing.cairo` line 23 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqdliT0ONUCEW5LS0P:-NYqdliT0ONUCEW5LS0Q:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/33208df49164a7f4236dd6c9059759f0b3f8b641/corelib/src/starknet/testing.cairo#L23)):*
> ```Cairo
> // general cheatcode function used to simplify implementation of starknet testing functions
> // external users of the cairo crates can also implement their own cheatcodes
> // by injecting custom CairoHintProcessor
> ```





_Suggestion:_
```Cairo
// A general cheatcode function used to simplify implementation of Starknet testing functions.
// External users of the cairo crates can also implement their own cheatcodes
// by injecting custom `CairoHintProcessor`.
```
___
*[`corelib/src/starknet/testing.cairo` line 24 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqe3oYDyzIkXF-1Lsn:-NYqe3oYDyzIkXF-1Lso:b-7hx2tm) ([raw file](https://github.com/starkware-libs/cairo/blob/33208df49164a7f4236dd6c9059759f0b3f8b641/corelib/src/starknet/testing.cairo#L24)):*
> ```Cairo
> // external users of the cairo crates can also implement their own cheatcodes
> // by injecting custom CairoHintProcessor
> extern fn cheatcode<const selector: felt252>(
> ```

You have placed this function in `starknet::testing` module, while technically this is Starknet independent? Shouldn't be it place in `core::testing` module instead?
___
*[`corelib/src/starknet/testing.cairo` line 28 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqeEiA5U1O3rxPI-Ya:-NYqeEiA5U1O3rxPI-Yb:b6okpof) ([raw file](https://github.com/starkware-libs/cairo/blob/33208df49164a7f4236dd6c9059759f0b3f8b641/corelib/src/starknet/testing.cairo#L28)):*
> ```Cairo
> ) -> Span<felt252> implicits() nopanic;
> 
> // set_block_number high level implementation using general cheatcode function
> ```

This doc comment does not say what does this function do
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqecmDEBAELw85LelK:-NYqecmDEBAELw85LelL:botn2yu) ([raw file](https://github.com/starkware-libs/cairo/blob/33208df49164a7f4236dd6c9059759f0b3f8b641/crates/cairo-lang-casm/src/hints/mod.rs#L53)):*
> ```XML
>     #[codec(index = 1)]
>     SetBlockTimestamp { value: ResOperand },
>     #[codec(index = 2)]
> ```

isn't changing indices a breaking change in runtime? shouldn't you just skip `SetBlockNumber / 2`?
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 394 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqfhK748FqTk7N8dv6:-NYqfhK748FqTk7N8dv7:byccbmz) ([raw file](https://github.com/starkware-libs/cairo/blob/33208df49164a7f4236dd6c9059759f0b3f8b641/crates/cairo-lang-runner/src/casm_run/mod.rs#L394)):*
> ```XML
>                 })?;
>                 match selector {
>                     "set_block_number" => {
> ```

nit, consider extracting this match to a separate function for readability
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/testing.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmvW9B4D7HZM4dItbm:-NYqfx6X93G4WQ7FWqR-:bi3oxmr) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-sierra/src/extensions/modules/starknet/testing.rs#L213)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

It is not empty, there is always a `selector` generic arg there. We just don't use it here since the signature will always be the same. I can pass an empty array to this function (it is called in `specialize`) and assert that it is empty if that suits you better, but I don't see how it is beneficial.
</blockquote></details>

I think you should definitely assert that it is non-empty then. Assertions are always beneficial. In this case, they guard you early from bugs that can happen when you forget to synchronize two pieces of code.


<!-- Sent from Reviewable.io -->

2023-06-26 08:58 UTC, orizi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed, 10 unresolved discussions (waiting on @piotmag769 and @yuvalsw)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/testing.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmvW9B4D7HZM4dItbm:-NYquvpCAMzDGiVNauwq:b48akc9) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-sierra/src/extensions/modules/starknet/testing.rs#L213)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I think you should definitely assert that it is non-empty then. Assertions are always beneficial. In this case, they guard you early from bugs that can happen when you forget to synchronize two pieces of code.
</blockquote></details>

do note that it is checked in the wrapping function (20 lines down) - but checking here won't hurt.


<!-- Sent from Reviewable.io -->

2023-06-26 08:58 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed, 10 unresolved discussions (waiting on @piotmag769 and @yuvalsw)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/testing.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmvW9B4D7HZM4dItbm:-NYqvB0cBqd8mJzYe0ny:by8yj3m) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-sierra/src/extensions/modules/starknet/testing.rs#L213)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do note that it is checked in the wrapping function (20 lines down) - but checking here won't hurt.
</blockquote></details>

also - `specialize` isn't the only actual place that calls it - otherwise it wouldn't have existed.


<!-- Sent from Reviewable.io -->

2023-06-26 09:20 UTC, piotmag769 reviewed
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed, 10 unresolved discussions (waiting on @mkaput, @orizi, and @yuvalsw)

___
*[`corelib/src/starknet/testing.cairo` line 23 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqdliT0ONUCEW5LS0P:-NYqy0izB_vt3XIVmaVD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/33208df49164a7f4236dd6c9059759f0b3f8b641/corelib/src/starknet/testing.cairo#L23)):*
> ```Cairo
> // general cheatcode function used to simplify implementation of starknet testing functions
> // external users of the cairo crates can also implement their own cheatcodes
> // by injecting custom CairoHintProcessor
> ```

Done.
___
*[`corelib/src/starknet/testing.cairo` line 24 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqe3oYDyzIkXF-1Lsn:-NYqy2dK5YgsbFaUFoVx:b-89ex7r) ([raw file](https://github.com/starkware-libs/cairo/blob/33208df49164a7f4236dd6c9059759f0b3f8b641/corelib/src/starknet/testing.cairo#L24)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

You have placed this function in `starknet::testing` module, while technically this is Starknet independent? Shouldn't be it place in `core::testing` module instead?
</blockquote></details>

Not sure, vast majority of the cheatcodes will use starknet state, it is even declared as `StarknetHint`
___
*[`corelib/src/starknet/testing.cairo` line 28 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqeEiA5U1O3rxPI-Ya:-NYqyOggEtMSQkU2fwic:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/33208df49164a7f4236dd6c9059759f0b3f8b641/corelib/src/starknet/testing.cairo#L28)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

This doc comment does not say what does this function do
</blockquote></details>

Done.
___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqecmDEBAELw85LelK:-NYqgxwo-co5sMd604y3:b-t2vf30) ([raw file](https://github.com/starkware-libs/cairo/blob/33208df49164a7f4236dd6c9059759f0b3f8b641/crates/cairo-lang-casm/src/hints/mod.rs#L53)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

isn't changing indices a breaking change in runtime? shouldn't you just skip `SetBlockNumber / 2`?
</blockquote></details>

No idea. Is it true @orizi ?
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 394 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqfhK748FqTk7N8dv6:-NYqydNL5RtrxDFS-wp9:bw9t0cw) ([raw file](https://github.com/starkware-libs/cairo/blob/33208df49164a7f4236dd6c9059759f0b3f8b641/crates/cairo-lang-runner/src/casm_run/mod.rs#L394)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

nit, consider extracting this match to a separate function for readability
</blockquote></details>

I would leave it for now, can be done when implementing new cheatcodes which is out of scope of this PR.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/testing.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmvW9B4D7HZM4dItbm:-NYqhCLH8OJ26WQ4Ga6w:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-sierra/src/extensions/modules/starknet/testing.rs#L213)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I think you should definitely assert that it is non-empty then. Assertions are always beneficial. In this case, they guard you early from bugs that can happen when you forget to synchronize two pieces of code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-26 09:21 UTC, piotmag769 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: 6 of 8 files reviewed, 10 unresolved discussions (waiting on @mkaput, @orizi, and @yuvalsw)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/testing.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmvW9B4D7HZM4dItbm:-NYr-VkbDy325eeyMvT8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-sierra/src/extensions/modules/starknet/testing.rs#L213)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-26 09:25 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488#-:-NYr0KkA1s4beBJ_OaLo:bnfp4nl)* status: all files reviewed, 9 unresolved discussions (waiting on @mkaput and @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-06-26 09:36 UTC, yuvalsw approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r4, 2 of 2 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488#-:-NYr30C00gCcF4uh26zS:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @mkaput and @orizi)



<!-- Sent from Reviewable.io -->

2023-06-26 09:43 UTC, mkaput requested changes
> Reviewed 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @piotmag769)

___
*[`corelib/src/starknet/testing.cairo` line 24 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqe3oYDyzIkXF-1Lsn:-NYr4JwIEHuCzPyWyQJn:b-ytsqgb) ([raw file](https://github.com/starkware-libs/cairo/blob/33208df49164a7f4236dd6c9059759f0b3f8b641/corelib/src/starknet/testing.cairo#L24)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Not sure, vast majority of the cheatcodes will use starknet state, it is even declared as `StarknetHint`
</blockquote></details>

Do we expect having pure-Cairo cheatcodes?


<!-- Sent from Reviewable.io -->

2023-06-26 10:05 UTC, orizi approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed, 2 unresolved discussions (waiting on @piotmag769)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 709 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYmsuerAb-8s-LmzuLQ:-NYr9OFLCHuFoZg-Oto_:b4k966r) ([raw file](https://github.com/starkware-libs/cairo/blob/a9ffaf170adffc4b546137322f18d7e5eb89abbf/crates/cairo-lang-casm/src/hints/mod.rs#L709)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Unfortunately correcting it makes the starknet tests fail - there must be a bug in the logic behind python hints, but that's out of the scope of this PR
</blockquote></details>

yeah - there's a PR merged to `dev-v2.0.0` taking care of it.
ignore PopLog for the time being.


<!-- Sent from Reviewable.io -->

2023-06-26 10:07 UTC, mkaput approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/starknet/testing.cairo` line 24 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqe3oYDyzIkXF-1Lsn:-NYr9iWZ9l21S61M2z4Z:b-4f7h84) ([raw file](https://github.com/starkware-libs/cairo/blob/33208df49164a7f4236dd6c9059759f0b3f8b641/corelib/src/starknet/testing.cairo#L24)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Do we expect having pure-Cairo cheatcodes?
</blockquote></details>

Discussed this privately: we concluded with @piotmag769 that when we will find a need for starknet-agnostic cheatcode (which is non-trivial due to having to maintain the state under the hood), we can deprecate this one


<!-- Sent from Reviewable.io -->

2023-06-26 10:12 UTC, orizi approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqecmDEBAELw85LelK:-NYrAyeXBTQszmjye9BA:b-fdnyfw) ([raw file](https://github.com/starkware-libs/cairo/blob/33208df49164a7f4236dd6c9059759f0b3f8b641/crates/cairo-lang-casm/src/hints/mod.rs#L53)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

No idea. Is it true @orizi ?
</blockquote></details>

this is used by full node - and they should be able to handle changes - so we should be fine.
Still making sure @dan-starkware ?


<!-- Sent from Reviewable.io -->

2023-06-26 10:13 UTC, orizi approved these changes
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)



<!-- Sent from Reviewable.io -->

2023-06-26 10:48 UTC, orizi reviewed
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @dan-starkware)



<!-- Sent from Reviewable.io -->

2023-06-26 10:59 UTC, yair-starkware commented
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqecmDEBAELw85LelK:-NYrKHLhBkeWg16AgAbi:bedmrq7) ([raw file](https://github.com/starkware-libs/cairo/blob/33208df49164a7f4236dd6c9059759f0b3f8b641/crates/cairo-lang-casm/src/hints/mod.rs#L53)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is used by full node - and they should be able to handle changes - so we should be fine.
Still making sure @dan-starkware ?
</blockquote></details>

We store the casms in storage, so removing variants / modifying the indices requires us to implement storage migration.
If possible, please avoid doing so.
@dan-starkware - can we still get away with resyncing?


<!-- Sent from Reviewable.io -->

2023-06-26 11:01 UTC, piotmag769 reviewed
> Reviewed 2 of 2 files at r8, 1 of 1 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqecmDEBAELw85LelK:-NYrMGLQ7uIgg5wZJ_y4:b-jqs9re) ([raw file](https://github.com/starkware-libs/cairo/blob/33208df49164a7f4236dd6c9059759f0b3f8b641/crates/cairo-lang-casm/src/hints/mod.rs#L53)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

We store the casms in storage, so removing variants / modifying the indices requires us to implement storage migration.
If possible, please avoid doing so.
@dan-starkware - can we still get away with resyncing?


</blockquote></details>

I can revert @yair-starkware 


<!-- Sent from Reviewable.io -->

2023-06-26 11:08 UTC, orizi approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqecmDEBAELw85LelK:-NYrNsC-3ZWhpGTXZ-0H:b-f9mf20) ([raw file](https://github.com/starkware-libs/cairo/blob/33208df49164a7f4236dd6c9059759f0b3f8b641/crates/cairo-lang-casm/src/hints/mod.rs#L53)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

I can revert @yair-starkware 
</blockquote></details>

does the fact these are indices that should never appear in the db affect anything?


<!-- Sent from Reviewable.io -->

2023-06-26 11:09 UTC, yair-starkware commented
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqecmDEBAELw85LelK:-NYrO4c_1nWBoFUFN1XL:b-hhmjvu) ([raw file](https://github.com/starkware-libs/cairo/blob/33208df49164a7f4236dd6c9059759f0b3f8b641/crates/cairo-lang-casm/src/hints/mod.rs#L53)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

does the fact these are indices that should never appear in the db affect anything?
</blockquote></details>

WDYM never appear in the db? They are part of the encoding


<!-- Sent from Reviewable.io -->

2023-06-26 11:11 UTC, orizi approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqecmDEBAELw85LelK:-NYrO_Aj3Z1J2-YJ5sBC:bgm6v0n) ([raw file](https://github.com/starkware-libs/cairo/blob/33208df49164a7f4236dd6c9059759f0b3f8b641/crates/cairo-lang-casm/src/hints/mod.rs#L53)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

WDYM never appear in the db? They are part of the encoding
</blockquote></details>

the actual values - the changed values would never be part of valid CASM code.


<!-- Sent from Reviewable.io -->

2023-06-26 11:28 UTC, yair-starkware commented
*[`crates/cairo-lang-casm/src/hints/mod.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3488#-NYqecmDEBAELw85LelK:-NYrSCqg71-f2hpSMIVt:b7nk339) ([raw file](https://github.com/starkware-libs/cairo/blob/33208df49164a7f4236dd6c9059759f0b3f8b641/crates/cairo-lang-casm/src/hints/mod.rs#L53)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the actual values - the changed values would never be part of valid CASM code.
</blockquote></details>

Discussed with Ori - these variants are for tests.
Ok to modify them.
Thanks for checking with us.


<!-- Sent from Reviewable.io -->

2023-06-26 11:31 UTC, piotmag769 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)



<!-- Sent from Reviewable.io -->

2023-06-26 11:32 UTC, orizi approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3488)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)



<!-- Sent from Reviewable.io -->

2023-06-26 11:40 UTC, merged