feat:serde for Result enum
starkware-libs/cairo pull request #3560
Opened 2023-07-02 10:52 UTC by PhilippeR26

The Enum `Option` implements serialize/deserialize. So it can be used in Starknet contract function signatures.
Unfortunately, it's not implemented in `Result` Enum, that is at least as useful as `Option`.
This PR propose to implement serialize/deserialize in the Enum `Result`.
It has been made in accordance with @enitrat comment in Discord : https://discord.com/channels/793094838509764618/1065544063245365288/1124678948157141062
> Result::Ok((value))  would become [0,value] and Result::Err(value) would become [1,value]

So such code become possible in Cairo : 
```rust
fn test6(self: @ContractState, val1: u16) -> Result<u16, u16> {
    if val1 < 100 {
        return Result::Err(14);
    }
    Result::Ok(val1)
}

fn test8(self: @ContractState, inp: Result<Order, u16>) -> u16 {
    match inp {
        Result::Ok(x) => {
            return x.p2;
        },
        Result::Err(y) => {
            return y;
        }
    }
}
```
Several tests have been made with Starknet.js/Starknet-devnet, with success :
```typescript
const res10 = await myTestContract.call("test6", [90], { parseRequest: false, parseResponse: false });
// result is : [ '0x1', '0xe' ]
const res11 = await myTestContract.call("test6", [110], { parseRequest: false, parseResponse: false });
// result is : [ '0x0', '0x6e' ]
const res14 = await myTestContract.call("test8", [0,92,93], { parseRequest: false, parseResponse: false });
// result is : [ '0x5d' ]
const res15 = await myTestContract.call("test8", [1,112], { parseRequest: false, parseResponse: false });
// result is : [ '0x70' ]
```

2023-07-12 12:47 UTC, orizi requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3560)* status: all files reviewed, 1 unresolved discussion (waiting on @PhilippeR26)

___
*[`corelib/src/result.cairo` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3560#-N_97f3G4QcwWmT1dp4j:-N_97f3G4QcwWmT1dp4k:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1f69921fa125d5c9dc2ca09ab2fe5479763f59e2/corelib/src/result.cairo#L38)):*
> ```Cairo
>                 Option::None(())
>             }
>         }
> ```





_Suggestion:_
```Cairo
        let variant = *serialized.pop_front()?;
        if variant == 0 {
            Option::Some(Result::Ok(Serde::<R>::deserialize(ref serialized)?))
        } else if variant == 1 {
            Option::Some(Result::Err(Serde::<E>::deserialize(ref serialized)?))
        } else {
            Option::None
        }
```


<!-- Sent from Reviewable.io -->

2023-07-12 13:37 UTC, PhilippeR26 commented
> > Reviewed 1 of 1 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3560)_ status: all files reviewed, 1 unresolved discussion (waiting on @PhilippeR26)
> 
> _[`corelib/src/result.cairo` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3560#-N_97f3G4QcwWmT1dp4j:-N_97f3G4QcwWmT1dp4k:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1f69921fa125d5c9dc2ca09ab2fe5479763f59e2/corelib/src/result.cairo#L38)):_
> 
> > ```cairo
> >                 Option::None(())
> >             }
> >         }
> > ```
> 
> _Suggestion:_
> 
> ```cairo
>         let variant = *serialized.pop_front()?;
>         if variant == 0 {
>             Option::Some(Result::Ok(Serde::<R>::deserialize(ref serialized)?))
>         } else if variant == 1 {
>             Option::Some(Result::Err(Serde::<E>::deserialize(ref serialized)?))
>         } else {
>             Option::None
>         }
> ```

Your proposal is not handling the case where .pop_front() returns Option::None.
Is it OK for you?

2023-07-12 13:47 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3560)* status: all files reviewed, 1 unresolved discussion (waiting on @PhilippeR26)

___
*[`corelib/src/result.cairo` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3560#-N_97f3G4QcwWmT1dp4j:-N_9LnhH67DCN1YZJi1g:b-px76j2) ([raw file](https://github.com/starkware-libs/cairo/blob/1f69921fa125d5c9dc2ca09ab2fe5479763f59e2/corelib/src/result.cairo#L38)):*
<details><summary><i>Previously, PhilippeR26 (Philippe ROSTAN) wrote…</i></summary><blockquote>

@orizi 
Your proposal is not handling the case where .pop_front() returns Option::None.
Is it OK for you?

</blockquote></details>

it does - the `?` returns the None.


<!-- Sent from Reviewable.io -->

2023-07-12 14:42 UTC, PhilippeR26 commented
OK. 
Implemented.

2023-07-12 14:56 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3560#-:-N_9aemhElRJSVOCM8oD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PhilippeR26)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3560#-N_9ag1-AxrsnZnHLUhe:-N_9ag1-AxrsnZnHLUhf:b-uuj1x0) (no related file):*
@gilbens-starkware for 2nd eye.

___


<!-- Sent from Reviewable.io -->

2023-07-13 06:37 UTC, gilbens-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3560#-:-N_CvtctEXJOQKvEjj3U:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PhilippeR26)



<!-- Sent from Reviewable.io -->

2023-07-13 07:22 UTC, gilbens-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3560)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PhilippeR26)

___
*[`corelib/src/result.cairo` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3560#-N_D7A5x4SIINbJQuG9x:-N_D7A5x4SIINbJQuG9y:b-sp4hnz) ([raw file](https://github.com/starkware-libs/cairo/blob/324e189e7962a109d9acd6f82e8ff59d565bc42b/corelib/src/result.cairo#L11)):*
> ```Cairo
> 
> impl ResultSerde<
>     R, E, impl RSerde: Serde<R>, impl ESerde: Serde<E>, impl RDrop: Drop<R>, impl EDrop: Drop<E>> of Serde<Result<R,E>> {
> ```

Please run the Cairo formatter.


<!-- Sent from Reviewable.io -->

2023-07-13 07:24 UTC, gilbens-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3560)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PhilippeR26)

___
*[`corelib/src/result.cairo` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3560#-N_D7A5x4SIINbJQuG9x:-N_D7iNK6JwqSmZ7KzD6:bsgu0lt) ([raw file](https://github.com/starkware-libs/cairo/blob/324e189e7962a109d9acd6f82e8ff59d565bc42b/corelib/src/result.cairo#L11)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Please run the Cairo formatter.
</blockquote></details>

(./scripts/cairo_fmt.sh)


<!-- Sent from Reviewable.io -->

2023-07-13 07:31 UTC, PhilippeR26 commented
cairo formatter executed.

2023-07-13 07:32 UTC, gilbens-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3560#-:-N_D9buvCzkbxbm89Cs2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PhilippeR26)



<!-- Sent from Reviewable.io -->

2023-07-13 07:50 UTC, merged