Added cast for signed integers.
starkware-libs/cairo pull request #3623
Opened 2023-07-06 14:36 UTC by orizi

**Stack**:
- #3622
- #3621
- #3620
- #3619
- #3618
- #3617
- #3616
- #3615
- #3614
- #3489

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2023-07-26 07:28 UTC, spapinistarkware submitted a review, later dismissed
> Reviewed 5 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NaG4xgx-LCONhcRXVat:-NaG4xgx-LCONhcRXVau:b-93duhy) ([raw file](https://github.com/starkware-libs/cairo/blob/80a90ef43958c87d5ca7620c037fd88a9db13356/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L59)):*
> ```XML
>     let lower_limit: BigInt = upper_limit.clone() - range_size.clone();
>     let rc_bound = two.pow(128_usize);
>     let range_check = if !can_underflow {
> ```

This looks like a case for 2 different functions to me (can_underflow or not). Generally, a flag that determines behavior might point to need to separate to functions.
I also think it makes sense to add a third function, for overflow or not, and perhaps share code between these function by making extracting a function.


<!-- Sent from Reviewable.io -->

2023-08-20 12:28 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 31 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcHuey-E7bA5k1GJRmB:-NcHuey-E7bA5k1GJRmC:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L31)):*
> ```XML
> }
> impl IntTypeInfo {
>     /// Does this type fit into the other type.
> ```

.



_Suggestion:_
```XML
    /// Returns true if this type fits into the other type.
```


<!-- Sent from Reviewable.io -->

2023-08-20 12:29 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcHuuMu7JggftlRZptS:-NcHuuMu7JggftlRZptT:b94l16k) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L33)):*
> ```XML
>     /// Does this type fit into the other type.
>     fn upcast_valid(&self, to: &IntTypeInfo) -> bool {
>         // If both has the same sign support, the destination must be at least as large.
> ```

Move comment into the body (one line below)
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcHuqwu82s1DI8NKEzv:-NcHuqwu82s1DI8NKEzw:b-816h6l) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L36)):*
> ```XML
>         if self.signed == to.signed {
>             self.nbits <= to.nbits
>         // If the type is unsigned and the other is signed, the destination must be larger.
> ```

Same.


<!-- Sent from Reviewable.io -->

2023-08-20 12:31 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 2 of 7 files reviewed, 5 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcHvH8eEdyTRJu6N_JG:-NcHvH8eEdyTRJu6N_JH:b-64kb4q) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L34)):*
> ```XML
>     fn upcast_valid(&self, to: &IntTypeInfo) -> bool {
>         // If both has the same sign support, the destination must be at least as large.
>         if self.signed == to.signed {
> ```

Consider writing it with `match (self.signed, to.signed) { ... }`


<!-- Sent from Reviewable.io -->

2023-08-20 12:35 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 2 of 7 files reviewed, 6 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 119 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcHwCW_Aj_8ierJtAyx:-NcHwCW_Aj_8ierJtAyy:b-ppec8w) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L119)):*
> ```XML
>         let from_info = get_int_info(context, from_ty.clone())?;
>         let to_info = get_int_info(context, to_ty.clone())?;
>         if from_info.upcast_valid(&to_info) {
> ```

This is wrong. The condition for downcast is not the opposite of upcast.


<!-- Sent from Reviewable.io -->

2023-08-20 12:49 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 2 of 7 files reviewed, 7 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 170 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcHzZVs4NcZ7SyiojEM:-NcHzZVs4NcZ7SyiojEN:b-2uc5ym) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L170)):*
> ```XML
> }
> 
> /// Validates the `value` is smaller than `bound`.
> ```

Same below.



_Suggestion:_
```XML
/// Validates that `value` is smaller than `bound`.
```


<!-- Sent from Reviewable.io -->

2023-08-20 12:54 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 2 of 7 files reviewed, 8 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 94 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcI-_c154TrHsJrJ7dl:-NcI-_c154TrHsJrJ7dm:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L94)):*
> ```XML
>     value: Var,
>     range_check: Var,
>     value_limit: &BigInt,
> ```

.



_Suggestion:_
```XML
upper_bound: &BigInt,
```


<!-- Sent from Reviewable.io -->

2023-08-20 12:54 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 2 of 7 files reviewed, 9 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 101 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcI-igZ5hle5WSjFpNU:-NcI-igZ5hle5WSjFpNV:bw7ffw0) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L101)):*
> ```XML
>         tempvar is_valid;
>         const value_limit_imm = value_limit.clone();
>         hint TestLessThan {lhs: value, rhs: value_limit_imm} into {dst: is_valid};
> ```

Does this work if `value < 0`?


<!-- Sent from Reviewable.io -->

2023-08-20 12:54 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 2 of 7 files reviewed, 9 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 101 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcI-igZ5hle5WSjFpNU:-NcI-mWI0YcVrIV5z5MI:bwe4nxx) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L101)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Does this work if `value < 0`?
</blockquote></details>

Add a test


<!-- Sent from Reviewable.io -->

2023-08-20 13:11 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 2 of 7 files reviewed, 10 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 125 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcI3QZQ0sPvnY8ATlIU:-NcI3QZQ0sPvnY8ATlIV:b2fk8b5) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L125)):*
> ```XML
>         tempvar is_valid;
>         const to_range_size = to_values.size.clone();
>         hint TestLessThan {lhs: canonical_value, rhs: to_range_size} into {dst: is_valid};
> ```

Can you compare to 2**128 instead of `range_size`? Then you won't need to pass range_size to this function.


<!-- Sent from Reviewable.io -->

2023-08-20 13:19 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 2 of 7 files reviewed, 11 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 154 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcI5UpY3xDRmbrdWyvp:-NcI5UpY3xDRmbrdWyvq:bm47x4i) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L154)):*
> ```XML
>         const rc_bound_imm = (BigInt::from(u128::MAX) + 1) as BigInt;
>         tempvar is_overflow;
>         hint TestLessThan {lhs: value, rhs: rc_bound_imm} into {dst: is_overflow};
> ```

I think this should be `canonical_value`


<!-- Sent from Reviewable.io -->

2023-08-20 13:23 UTC, liorgold2 requested changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 3 of 7 files reviewed, 11 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 119 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcHwCW_Aj_8ierJtAyx:-NcI6D8fC0AufNtQAqqT:b-6yz6qj) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L119)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This is wrong. The condition for downcast is not the opposite of upcast.
</blockquote></details>

Remove `if`?


<!-- Sent from Reviewable.io -->

2023-08-20 13:23 UTC, liorgold2 reviewed
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 3 of 7 files reviewed, 11 unresolved discussions (waiting on @orizi and @spapinistarkware)



<!-- Sent from Reviewable.io -->

2023-08-20 13:27 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 3 of 7 files reviewed, 12 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-ap-change/src/core_libfunc_ap_change.rs` line 100 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcI6iku7h7InCRg9swW:-NcI6ikv8jsRE1vlVAfJ:b-jyhzw8) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra-ap-change/src/core_libfunc_ap_change.rs#L100)):*
> ```XML
>         CoreConcreteLibfunc::Cast(libfunc) => match libfunc {
>             CastConcreteLibfunc::Downcast(libfunc) => {
>                 let can_underflow = libfunc.from_info.signed;
> ```

I suggest using the same conditions that you have in `invocations/...`.
You can also extract this code to a function that returns an enum with three variants and match on the enum here (or put a copy of the variant in the function signature struct).

You can also have a fourth variant for trivial downcast (==upcast).


<!-- Sent from Reviewable.io -->

2023-08-24 13:38 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 0 of 7 files reviewed, 12 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 31 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcHuey-E7bA5k1GJRmB:-NcalgJ858ZbN_fBcuPb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L31)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcHuuMu7JggftlRZptS:-NcanUyXETVW2xQdMNQN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L33)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Move comment into the body (one line below)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcHvH8eEdyTRJu6N_JG:-NcanVYuBw6VkyUSfS_V:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L34)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Consider writing it with `match (self.signed, to.signed) { ... }`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcHuqwu82s1DI8NKEzv:-NcanWSx5WCRy7O0Hktv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L36)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Same.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 119 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcHwCW_Aj_8ierJtAyx:-NcapLaO7nd3u86QpDGx:b-ifp2ka) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L119)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Remove `if`?
</blockquote></details>

we blocked it before - but we can allow it (as we allowed it as identity before).
Done.
___
*[`crates/cairo-lang-sierra-ap-change/src/core_libfunc_ap_change.rs` line 100 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcI6iku7h7InCRg9swW:-NcaqzWsCxLrvfN_B9AB:belzq6y) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra-ap-change/src/core_libfunc_ap_change.rs#L100)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I suggest using the same conditions that you have in `invocations/...`.
You can also extract this code to a function that returns an enum with three variants and match on the enum here (or put a copy of the variant in the function signature struct).

You can also have a fourth variant for trivial downcast (==upcast).
</blockquote></details>

Added a fifth one as well:
The forth variant improvement can only happen in a major sierra update, as the current upcast supported the identity option.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 94 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcI-_c154TrHsJrJ7dl:-Ncaqa5o5uOrJ9WSTLvB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L94)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 101 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcI-igZ5hle5WSjFpNU:-NcbBJLG95oLtdy3XXnb:br2a4m2) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L101)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add a test
</blockquote></details>

how can we get such a value? this is the overflow only test:
so can't be signed to signed, and can't be signed to unsigned.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 125 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcI3QZQ0sPvnY8ATlIU:-NcbDUuo4ua7_5ZKOMD9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L125)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Can you compare to 2**128 instead of `range_size`? Then you won't need to pass range_size to this function.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 154 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcI5UpY3xDRmbrdWyvp:-NcbEEey2AhKmrfEtkdg:b5t5cgz) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L154)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I think this should be `canonical_value`
</blockquote></details>

it needs to be `value` as this relies on negative values being large.
Added comment.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 170 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcHzZVs4NcZ7SyiojEM:-NcbEeMF0OvnJUJK2snl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L170)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Same below.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-01 10:26 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 0 of 7 files reviewed, 13 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 42 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfejnPi1LR2chzu5QmD:-NfejnPi1LR2chzu5QmE:b-erlazo) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L42)):*
> ```XML
>     /// Returns the cast type.
>     pub fn cast_type(&self, to: &IntTypeInfo) -> CastType {
>         match (self.signed, to.signed) {
> ```

Restructure as follows:
```
match (self.signed, to.signed) {
    (false, false) => {
         CastType { overflow_above: self.nbits >= to.nbits, overflow_below: false }
    }
    (false, true) => ...
    (true, false) => ...
    (true, true) => ...
    ...
}
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 45 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfehyxV7AqwfFqlLXJ1:-NfehyxV7AqwfFqlLXJ2:b-1t7gah) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L45)):*
> ```XML
>             // The cast is trivial, but requires special handling due to backwards compatibility,
>             // handled as if it can overflow above.
>             (false, false) if self.nbits == to.nbits => {
> ```

Add a TODO or a task to remove this when we move to a new major sierra version.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfeiEcG3l6XeSiXDR8R:-NfeiEcG3l6XeSiXDR8S:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L49)):*
> ```XML
>             }
>             // If both has the same sign support, if the destination is at least as large, no
>             // overflow is possible.
> ```





_Suggestion:_
```XML
            // If both have the same sign support and the destination is at least as large, no
            // overflow is possible.
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 59 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfejNxP445Em3njGQDi:-NfejNxP445Em3njGQDj:bbw21mm) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L59)):*
> ```XML
>             }
>             // Signed to same size or larger unsigned may only overflow below.
>             (true, false) if self.nbits <= to.nbits => {
> ```

For example, i16 -> u15



_Suggestion:_
```XML
(true, false) if self.nbits <= to.nbits + 1 => {
```


<!-- Sent from Reviewable.io -->

2023-10-01 10:26 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 0 of 7 files reviewed, 14 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 70 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfelYv64ICngsO844pe:-NfelYv64ICngsO844pf:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L70)):*
> ```XML
>     }
> 
>     /// Returns true if this type can be participate in downcasts.
> ```

.



_Suggestion:_
```XML
/// Returns true if this type can participate in downcasts.
```


<!-- Sent from Reviewable.io -->

2023-10-01 10:30 UTC, liorgold2 requested changes
> Reviewed 1 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 1 of 7 files reviewed, 14 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 114 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfelwlZ6ofXUDUqKzle:-NfelwlZ6ofXUDUqKzlf:bi4o4t5) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L114)):*
> ```XML
>         let to_info = get_int_info(context, to_ty.clone())?;
>         let cast_type = from_info.cast_type(&to_info);
>         if cast_type.overflow_above || cast_type.overflow_below {
> ```

Won't the exception above imply that you can't upcast a type to itself? (e.g., u64->u64)


<!-- Sent from Reviewable.io -->

2023-10-01 10:33 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 1 of 7 files reviewed, 15 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 50 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfenBBSENixNdUik1j2:-NfenBBSENixNdUik1j3:bqyrw3e) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L50)):*
> ```XML
>     match libfunc.from_info.cast_type(&libfunc.to_info) {
>         CastType { overflow_above: false, overflow_below: false } => {
>             // In the upcast case, we know the value is valid, and we don't need to do anything.
> ```

Extract to function like the others.


<!-- Sent from Reviewable.io -->

2023-10-01 10:51 UTC, liorgold2 requested changes
> Reviewed 1 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 2 of 7 files reviewed, 13 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 101 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcI-igZ5hle5WSjFpNU:-Nfeo0CQB0zWfwFtxQI4:bs12gya) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L101)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

how can we get such a value? this is the overflow only test:
so can't be signed to signed, and can't be signed to unsigned.
</blockquote></details>

Can't we simply fix it instead of this explanation (which assumes more than we need to)?
E.g., `value_limit_imm - 1 - value < some bound` - like we do in other places.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 154 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcI5UpY3xDRmbrdWyvp:-NfeqURY0SlPSQbIQ81B:bc4hklg) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L154)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it needs to be `value` as this relies on negative values being large.
Added comment.
</blockquote></details>

I don't understand why `canonical_value` will not work (it assumes less).
Also, the comment seems to be wrong - if the value is negative this is an overflow below.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 119 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfeokKk1sI20FXN7G80:-NfeokKk1sI20FXN7G81:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L119)):*
> ```XML
>         // Note `value` is non-negative as it must be unsigned:
>         // Signed to signed would go the `both` or `upcast` cases.
>         // Signed to unsigned would go the `both` case.
> ```





_Suggestion:_
```XML
        // Signed to signed would go the `both` or `upcast` cases.
        // Signed to unsigned would go the `both` or `overflow_below` case.
```


<!-- Sent from Reviewable.io -->

2023-10-01 11:13 UTC, liorgold2 requested changes
> Reviewed 2 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 4 of 7 files reviewed, 13 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 151 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-Nfew9ra66k3GS0GTunk:-Nfew9rb8b2r5zHSPtRT:br9dbta) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L151)):*
> ```XML
>                     CastType { overflow_above: false, overflow_below: true } => vec![
>                         // Overflow below test is more expensive for casting into signed types.
>                         (ConstCost::steps(2 + i32::from(libfunc.to_info.signed))
> ```

It seems `signed=true` can't happen. Consider replacing the computation with an assert.



_Code quote:_
```XML
i32::from(libfunc.to_info.signed)
```


<!-- Sent from Reviewable.io -->

2023-10-01 11:14 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 4 of 7 files reviewed, 14 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 54 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfewcRi8JDvwfDT7OSD:-NfewcRi8JDvwfDT7OSE:bwulo58) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L54)):*
> ```XML
>             let success = vec![
>                 ReferenceExpression::from_cell(range_check.clone()),
>                 ReferenceExpression::from_cell(value.clone()),
> ```

Consider changing the libfunc signature to return "SameAsParam" in this case.


<!-- Sent from Reviewable.io -->

2023-10-01 11:15 UTC, liorgold2 reviewed
> Reviewed 1 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 5 of 7 files reviewed, 14 unresolved discussions (waiting on @orizi and @spapinistarkware)



<!-- Sent from Reviewable.io -->

2023-10-01 13:16 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 5 of 7 files reviewed, 14 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 42 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfejnPi1LR2chzu5QmD:-NffCHT34cj8fgZUk9EC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L42)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Restructure as follows:
```
match (self.signed, to.signed) {
    (false, false) => {
         CastType { overflow_above: self.nbits >= to.nbits, overflow_below: false }
    }
    (false, true) => ...
    (true, false) => ...
    (true, true) => ...
    ...
}
```
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 45 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfehyxV7AqwfFqlLXJ1:-Nff8l6O1k9nuGNUOLNn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L45)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add a TODO or a task to remove this when we move to a new major sierra version.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfeiEcG3l6XeSiXDR8R:-Nff9S5a83JrurdP04lO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L49)):*
> ```XML
>             }
>             // If both has the same sign support, if the destination is at least as large, no
>             // overflow is possible.
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 59 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfejNxP445Em3njGQDi:-NffBoey0b1iLPmB6FnD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L59)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

For example, i16 -> u15
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 70 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfelYv64ICngsO844pe:-NffBnecCGlI7dCFv8Y-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L70)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 114 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfelwlZ6ofXUDUqKzle:-NffCUh2BRhR_0q1z296:b-vs6xew) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L114)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Won't the exception above imply that you can't upcast a type to itself? (e.g., u64->u64)
</blockquote></details>

indeed - fixing.
___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 151 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-Nfew9ra66k3GS0GTunk:-NffFOqLD_O38Bm-8EDB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L151)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

It seems `signed=true` can't happen. Consider replacing the computation with an assert.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 101 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcI-igZ5hle5WSjFpNU:-NffMFgoARLBwbQyYslh:bsy68f9) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L101)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Can't we simply fix it instead of this explanation (which assumes more than we need to)?
E.g., `value_limit_imm - 1 - value < some bound` - like we do in other places.
</blockquote></details>

I don't understand the suggestion.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 154 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcI5UpY3xDRmbrdWyvp:-NffKMjD9LjX0WrGQD-U:b-7zbx1r) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L154)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I don't understand why `canonical_value` will not work (it assumes less).
Also, the comment seems to be wrong - if the value is negative this is an overflow below.
</blockquote></details>

canonical value would work as well - was confused - but i don't find what exactly is assumed less.
Done anyway.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 50 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfenBBSENixNdUik1j2:-NffGtnQBF7bCiAe98cv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L50)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Extract to function like the others.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 54 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfewcRi8JDvwfDT7OSD:-NffGyJ3D86Y8KDwpau2:b-b1v8d2) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L54)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Consider changing the libfunc signature to return "SameAsParam" in this case.
</blockquote></details>

this would be more efficient - but i don't think this is actually required - as the caller should just actually not call this function, so i'd rather reduce how complex this is.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 119 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfeokKk1sI20FXN7G80:-NffHZQD4HSyndBfc0Iw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L119)):*
> ```XML
>         // Note `value` is non-negative as it must be unsigned:
>         // Signed to signed would go the `both` or `upcast` cases.
>         // Signed to unsigned would go the `both` case.
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-10-02 06:45 UTC, liorgold2 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 1 of 7 files reviewed, 15 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/integer.cairo` line 1621 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-Nfj7JOG1m5T29UCmzO8:-Nfj7JOG1m5T29UCmzO9:b94vg8x) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/corelib/src/integer.cairo#L1621)):*
> ```Cairo
> // Marks `FromType` as downcastable to `ToType`.
> // Do not add user code implementing this trait.
> trait Downcastable<FromType, ToType>;
> ```

Can't we say that Downcastable is on one type (just the requirement <= 128bit)?
Alternatively, add another trait for this requirement and use it to define `Downcastable` in a generic way.


<!-- Sent from Reviewable.io -->

2023-10-02 06:47 UTC, liorgold2 requested changes
> Reviewed 1 of 7 files at r5, 1 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 3 of 7 files reviewed, 15 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 150 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-Nfj8-5OEPSHqnCoyUPp:-Nfj8-5PD0FWGhGALUmp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L150)):*
> ```XML
>                     ],
>                     CastType { overflow_above: false, overflow_below: true } => {
>                         assert!(
> ```





_Suggestion:_
```XML
                        // Assert that the target type is unsigned. Otherwise, the cost below is wrong.
                        assert!(
```


<!-- Sent from Reviewable.io -->

2023-10-02 06:52 UTC, liorgold2 requested changes
> Reviewed 1 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 4 of 7 files reviewed, 12 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 154 at r4](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NcI5UpY3xDRmbrdWyvp:-Nfj8qfSBJFTNt1V96l0:b1hbf38) ([raw file](https://github.com/starkware-libs/cairo/blob/461974c084c10e4946446d8d90f0ef755c9cd9a0/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L154)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

canonical value would work as well - was confused - but i don't find what exactly is assumed less.
Done anyway.
</blockquote></details>

(Theoretically, if you wanted to support a generic type `<LOWER_BOUND, UPPER_BOUND>` then using `canonical_value` will work while `value` will not.)

Resolved
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 54 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfewcRi8JDvwfDT7OSD:-Nfj8Ug3Es4aLA89v3QE:b2nhll9) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L54)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this would be more efficient - but i don't think this is actually required - as the caller should just actually not call this function, so i'd rather reduce how complex this is.
</blockquote></details>

Ok.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 97 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-Nfj8Ggj2e_FLWjT1Rmt:-Nfj8Ggj2e_FLWjT1Rmu:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L97)):*
> ```XML
> 
> /// Builds Casm instructions for [CastConcreteLibfunc::Downcast] for a trivial casee where no
> /// overflow is possible.
> ```





_Suggestion:_
```XML
/// Builds Casm instructions for [CastConcreteLibfunc::Downcast] for a trivial case where no
/// overflow is possible.
```


<!-- Sent from Reviewable.io -->

2023-10-02 06:54 UTC, liorgold2 reviewed
> Reviewed 1 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 5 of 7 files reviewed, 12 unresolved discussions (waiting on @orizi and @spapinistarkware)



<!-- Sent from Reviewable.io -->

2023-10-02 07:13 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 5 of 7 files reviewed, 16 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/test/integer_test.cairo` line 935 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfjAJoTELqR3z5C7UfT:-NfjAJoUAwxILIGJosRy:b-ws6np0) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/corelib/src/test/integer_test.cairo#L935)):*
> ```Cairo
> 
> /// Checks if `b` is out of range of `A`.
> fn is_out_of_range<A, B, impl DropA: Drop<A>, impl IBA: TryInto<B, A>>(b: B) -> bool {
> ```

Can you use the `+` syntax for anon impls? Same below.
___
*[`corelib/src/test/integer_test.cairo` line 959 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfjAX_iB7I2rQ_uFoic:-NfjAX_j4PPZ_GgbZzyp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/corelib/src/test/integer_test.cairo#L959)):*
> ```Cairo
> 
> /// Check that casting between two types is valid.
> /// Typically the most extreme possible values are provided for the test.
> ```





_Suggestion:_
```Cairo
/// Checks that casting between two types is valid.
/// Typically the most extreme possible values are provided for the test.
```
___
*[`corelib/src/test/integer_test.cairo` line 1086 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfjAmwBEdpQjedysGUL:-NfjAmwBEdpQjedysGUM:b-mnj850) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/corelib/src/test/integer_test.cairo#L1086)):*
> ```Cairo
>     assert(is_out_of_range::<u64, i128>(0x10000000000000000), 'large i128 in u64 range');
> 
>     assert(cast_valid::<i8, u8>(0, 0, 0x7f, 0x7f), 'i8 to_and_fro u8');
> ```

Same in other places.



_Suggestion:_
```Cairo
i8 to_and_from u8
```
___
*[`corelib/src/test/integer_test.cairo` line 1087 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfjDubrE8W7b4AaPeCe:-NfjDubrE8W7b4AaPeCf:bux8sen) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/corelib/src/test/integer_test.cairo#L1087)):*
> ```Cairo
> 
>     assert(cast_valid::<i8, u8>(0, 0, 0x7f, 0x7f), 'i8 to_and_fro u8');
>     assert(is_out_of_range::<i8, u8>(0x80), 'large u8 in i8 range');
> ```

Is it possible to include the two `is_out_of_range` inside `cast_valid`? (by adding and subtracting 1 to the min and max values)


<!-- Sent from Reviewable.io -->

2023-10-02 07:16 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 5 of 7 files reviewed, 17 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/test/integer_test.cairo` line 1060 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfjEYjz2G_VXUa5cfQk:-NfjEYjz2G_VXUa5cfQl:b-wkc7bm) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/corelib/src/test/integer_test.cairo#L1060)):*
> ```Cairo
> 
>     assert(cast_subtype_valid::<u8, i16>(0xff, 0xff), 'u8 to_and_fro i16');
>     assert(is_out_of_range::<u8, i16>(0x100), 'large i16 in u8 range');
> ```

What about `-1 : i16` to `u8`? Is it tested?


<!-- Sent from Reviewable.io -->

2023-10-02 07:17 UTC, liorgold2 reviewed
> Reviewed 1 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 6 of 7 files reviewed, 17 unresolved discussions (waiting on @orizi and @spapinistarkware)



<!-- Sent from Reviewable.io -->

2023-10-02 07:25 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 6 of 7 files reviewed, 18 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 70 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfelYv64ICngsO844pe:-NfjGMLQ-nrYlqYtglPl:b-75ce6f) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L70)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet :)
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 47 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfjGrNEDQ2qIR5FLAEU:-NfjGrNFAuHTkM4oV0Ug:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L47)):*
> ```XML
>                 // Overflow below is never possible, as the minimum value of both types is 0.
>                 // Overflow above is possible if `self` has strictly more bits than the `to`.
>                 // We use `>=` instead of `>` to provide backwards compatibility with the case
> ```





_Suggestion:_
```XML
                // We use `>=` instead of `>` to provide backward compatibility with the case
```


<!-- Sent from Reviewable.io -->

2023-10-02 07:26 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 6 of 7 files reviewed, 19 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 48 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfjGvTT-ydvqmg8x4po:-NfjGvTT-ydvqmg8x4pp:b7b35yo) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L48)):*
> ```XML
>                 // Overflow above is possible if `self` has strictly more bits than the `to`.
>                 // We use `>=` instead of `>` to provide backwards compatibility with the case
>                 // casting from a type to itself. TODO(orizi): Remove this backwards
> ```

Move TODO to a separate line (did the autoformatter do it?)



_Code quote:_
```XML
TODO(orizi): Remove this backwards
```


<!-- Sent from Reviewable.io -->

2023-10-02 10:12 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 6 of 7 files reviewed, 18 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`corelib/src/integer.cairo` line 1621 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-Nfj7JOG1m5T29UCmzO8:-NfjGeMfBGLFHg8LGg1E:b-b03vbo) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/corelib/src/integer.cairo#L1621)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Can't we say that Downcastable is on one type (just the requirement <= 128bit)?
Alternatively, add another trait for this requirement and use it to define `Downcastable` in a generic way.
</blockquote></details>

Can't work since TryInto<T, T> already exists :\.
___
*[`corelib/src/test/integer_test.cairo` line 935 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfjAJoTELqR3z5C7UfT:-NfjHIyA3c6G341hWicK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/corelib/src/test/integer_test.cairo#L935)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Can you use the `+` syntax for anon impls? Same below.
</blockquote></details>

Done.
___
*[`corelib/src/test/integer_test.cairo` line 959 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfjAX_iB7I2rQ_uFoic:-NfjHPshAs6fAfDo8GzR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/corelib/src/test/integer_test.cairo#L959)):*
> ```Cairo
> 
> /// Check that casting between two types is valid.
> /// Typically the most extreme possible values are provided for the test.
> ```

Done.
___
*[`corelib/src/test/integer_test.cairo` line 1060 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfjEYjz2G_VXUa5cfQk:-NfjO29SEk6mjjDLGaMy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/corelib/src/test/integer_test.cairo#L1060)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

What about `-1 : i16` to `u8`? Is it tested?
</blockquote></details>

Done.
___
*[`corelib/src/test/integer_test.cairo` line 1086 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfjAmwBEdpQjedysGUL:-NfjOI7l7xs3-KyI0t_-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/corelib/src/test/integer_test.cairo#L1086)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Same in other places.
</blockquote></details>

Done.
___
*[`corelib/src/test/integer_test.cairo` line 1087 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfjDubrE8W7b4AaPeCe:-NfjOJY_2J6i88aaKhdM:b-csic0p) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/corelib/src/test/integer_test.cairo#L1087)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Is it possible to include the two `is_out_of_range` inside `cast_valid`? (by adding and subtracting 1 to the min and max values)
</blockquote></details>

this will only be possible if we also add it as an overflow above overflow below test.
trying.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 70 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfelYv64ICngsO844pe:-NfjPBrU0rpmz2Zndub2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L70)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Not yet :)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 47 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfjGrNEDQ2qIR5FLAEU:-NfjOts8A9ZjaIFO4oOq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L47)):*
> ```XML
>                 // Overflow below is never possible, as the minimum value of both types is 0.
>                 // Overflow above is possible if `self` has strictly more bits than the `to`.
>                 // We use `>=` instead of `>` to provide backwards compatibility with the case
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 48 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfjGvTT-ydvqmg8x4po:-NfjP0ioEtHR78iddVGt:bu884rq) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L48)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Move TODO to a separate line (did the autoformatter do it?)
</blockquote></details>

indeed the fmt.
___
*[`crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs` line 150 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-Nfj8-5OEPSHqnCoyUPp:-NfjGTrBA4tq7X5w4XjD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L150)):*
> ```XML
>                     ],
>                     CastType { overflow_above: false, overflow_below: true } => {
>                         assert!(
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 97 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-Nfj8Ggj2e_FLWjT1Rmt:-NfjFy5V49NbNzABMuUY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L97)):*
> ```XML
> 
> /// Builds Casm instructions for [CastConcreteLibfunc::Downcast] for a trivial casee where no
> /// overflow is possible.
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-10-02 10:58 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 2 of 7 files reviewed, 20 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 114 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfelwlZ6ofXUDUqKzle:-Nfk0WAl54aAhxoGbg0V:b-jy0rdi) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L114)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

indeed - fixing.
</blockquote></details>

Is it tested?
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 121 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-Nfk0iJGDr3w8y0PgDup:-Nfk0iJGDr3w8y0PgDuq:b-w32c0f) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L121)):*
> ```XML
>         if cast_type.overflow_above || cast_type.overflow_below {
>             // Finding if the detected possible overflow is not actually possible, but a backwards
>             // compatibilty based one. TODO(orizi): Remove this check after the
> ```

Move TODO to a separate line.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 121 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-Nfk0mfC0UNTGxMB5UCY:-Nfk0mfC0UNTGxMB5UCZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L121)):*
> ```XML
>         if cast_type.overflow_above || cast_type.overflow_below {
>             // Finding if the detected possible overflow is not actually possible, but a backwards
>             // compatibilty based one. TODO(orizi): Remove this check after the
> ```





_Suggestion:_
```XML
            // Finding if the detected possible overflow is not actually possible, but a backward
            // compatibility based one. TODO(orizi): Remove this check after the
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 123 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-Nfk0wgAEalPY0jfEtet:-Nfk0wgAEalPY0jfEteu:b92qt0r) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L123)):*
> ```XML
>             // compatibilty based one. TODO(orizi): Remove this check after the
>             // backwards compatibility is removed at next major sierra version.
>             if from_info.signed || to_info.signed || from_info.nbits != to_info.nbits {
> ```

Another option is `let same_type = from_info == to_info` and `if (cast_type.overflow_above || cast_type.overflow_below) && !same_type {`



_Suggestion:_
```XML
            let backward_compatibility_exception = !from_info.signed && !to_info.signed && from_info.nbits == to_info.nbits;
            if !backward_compatibility_exception {
```


<!-- Sent from Reviewable.io -->

2023-10-02 10:59 UTC, liorgold2 reviewed
> Reviewed 1 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 2 of 7 files reviewed, 19 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 121 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-Nfk0iJGDr3w8y0PgDup:-Nfk1aBtBdABnGqZAWGl:b-tatwal) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L121)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Move TODO to a separate line.
</blockquote></details>

Never mind.


<!-- Sent from Reviewable.io -->

2023-10-02 11:41 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 2 of 7 files reviewed, 18 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 114 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfelwlZ6ofXUDUqKzle:-Nfk8KkQ3FgIszdmObcB:bu67jgd) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L114)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Is it tested?
</blockquote></details>

it is - which confuses me on how this did not fail.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 121 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-Nfk0mfC0UNTGxMB5UCY:-Nfk8ls12n21WW2Mm4KK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L121)):*
> ```XML
>         if cast_type.overflow_above || cast_type.overflow_below {
>             // Finding if the detected possible overflow is not actually possible, but a backwards
>             // compatibilty based one. TODO(orizi): Remove this check after the
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 123 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-Nfk0wgAEalPY0jfEtet:-Nfk9NbTDhqY2jBbWyDn:b-hhplln) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L123)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Another option is `let same_type = from_info == to_info` and `if (cast_type.overflow_above || cast_type.overflow_below) && !same_type {`
</blockquote></details>

since the comment in needed anyway, and after the shortened version - i don't think the extra var is needed.


<!-- Sent from Reviewable.io -->

2023-10-02 11:56 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 2 of 7 files reviewed, 18 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 114 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfelwlZ6ofXUDUqKzle:-NfkDqkxA6tVkVmhLWHN:b-5i7osj) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L114)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it is - which confuses me on how this did not fail.
</blockquote></details>

oh - got confused with downcast test - added one for upcast.


<!-- Sent from Reviewable.io -->

2023-10-02 14:12 UTC, liorgold2 requested changes
> Reviewed 1 of 5 files at r8, 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 2 of 7 files reviewed, 12 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 114 at r6](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfelwlZ6ofXUDUqKzle:-NfkiZYn66DWvIaReF-M:b-zcjvte) ([raw file](https://github.com/starkware-libs/cairo/blob/360fc87b34327820204863b754b4c79e958f7faf/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L114)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

oh - got confused with downcast test - added one for upcast.
</blockquote></details>

Thanks
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 48 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfjGvTT-ydvqmg8x4po:-NfkhnOFAQ8AfIkCBwAX:b-90pnmz) ([raw file](https://github.com/starkware-libs/cairo/blob/58c40d6f02090ef0112e02deaac26d5c27f8b8c4/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L48)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

indeed the fmt.
</blockquote></details>

Move TODO to a separate line.
If needed add a blank line between. Seems weird that the formatter is intervening this way.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 121 at r9](https://reviewable.io/reviews/starkware-libs/cairo/3623#-Nfkibhp-VLxzSrGobSc:-Nfkibhp-VLxzSrGobSd:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/97e3500b4b43a7ae503970feacdd5f4c69b194b2/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L121)):*
> ```XML
>         if cast_type.overflow_above || cast_type.overflow_below {
>             // Finding if the detected possible overflow is not actually possible, but a backward
>             // compatibility based one (as smae type can have no overflow).
> ```





_Suggestion:_
```XML
           // compatibility based one (as same type can have no overflow).
```


<!-- Sent from Reviewable.io -->

2023-10-02 14:14 UTC, liorgold2 reviewed
> Reviewed 2 of 5 files at r8, 1 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 5 of 7 files reviewed, 9 unresolved discussions (waiting on @orizi and @spapinistarkware)



<!-- Sent from Reviewable.io -->

2023-10-03 06:16 UTC, liorgold2 requested changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 5 of 7 files reviewed, 8 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 56 at r10](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfoAMpC3ssNPqCztQXg:-NfoAMpC3ssNPqCztQXh:brnevg1) ([raw file](https://github.com/starkware-libs/cairo/blob/45ad990e6ff940872d832e1996f90a4cbffe7685/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L56)):*
> ```XML
>         }
>         CastType { overflow_above: false, overflow_below: true } => {
>             add_downcast_overflow_below(&mut casm_builder, value, range_check, &to_values.min)
> ```

Add an assert that from type is unsigned. Add an assumption to the documentation of `add_downcast_overflow_below`.


<!-- Sent from Reviewable.io -->

2023-10-03 06:40 UTC, liorgold2 requested changes
> Reviewed 1 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 6 of 7 files reviewed, 8 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/test/integer_test.cairo` line 940 at r10](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfoCprqB38r7G_EKCSD:-NfoCprqB38r7G_EKCSE:bhzkbgk) ([raw file](https://github.com/starkware-libs/cairo/blob/45ad990e6ff940872d832e1996f90a4cbffe7685/corelib/src/test/integer_test.cairo#L940)):*
> ```Cairo
> }
> 
> /// Checks if `a` is trivially castable to `B` and that `b` is castable to `A`, with the same value.
> ```

Fix documentation.
___
*[`corelib/src/test/integer_test.cairo` line 967 at r10](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfoEajA-tPppdi50PvK:-NfoEajA-tPppdi50PvL:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/45ad990e6ff940872d832e1996f90a4cbffe7685/corelib/src/test/integer_test.cairo#L967)):*
> ```Cairo
>     OfAOnly,
>     OfBOnly,
> }
> ```





_Suggestion:_
```Cairo
/// Describes the type of bound (min/max) in a cast.
///
/// For example, in a `u8 -> u16` cast, the lower bound is equal, and the upper bound
/// of `A` is inside `B`.
#[derive(Drop)]
enum BoundConfig {
    /// The two bounds have the same value.
    Equal,
    /// The bound of A is inside the domain of B.
    AInsideB,
    /// The bound of B is inside the domain of A.
    BInsideA,
}
```
___
*[`corelib/src/test/integer_test.cairo` line 969 at r10](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfoCxeR7EL5b6JFuQ5e:-NfoCxeR7EL5b6JFuQ5f:b70q33a) ([raw file](https://github.com/starkware-libs/cairo/blob/45ad990e6ff940872d832e1996f90a4cbffe7685/corelib/src/test/integer_test.cairo#L969)):*
> ```Cairo
> }
> 
> /// Checks that casting from `A` to `B` are valid around the bounds.
> ```

or "as-intended"



_Suggestion:_
```Cairo
/// Checks that castings from `A` to `B` are correct around the bounds.
```


<!-- Sent from Reviewable.io -->

2023-10-03 07:55 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 5 of 7 files reviewed, 8 unresolved discussions (waiting on @liorgold2 and @spapinistarkware)

___
*[`corelib/src/test/integer_test.cairo` line 940 at r10](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfoCprqB38r7G_EKCSD:-NfoKZyiAvBVAR8kzFx2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/45ad990e6ff940872d832e1996f90a4cbffe7685/corelib/src/test/integer_test.cairo#L940)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Fix documentation.
</blockquote></details>

Done.
___
*[`corelib/src/test/integer_test.cairo` line 967 at r10](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfoEajA-tPppdi50PvK:-NfoRqhpAP5YLOalWQ64:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/45ad990e6ff940872d832e1996f90a4cbffe7685/corelib/src/test/integer_test.cairo#L967)):*
> ```Cairo
>     OfAOnly,
>     OfBOnly,
> }
> ```

Done.
___
*[`corelib/src/test/integer_test.cairo` line 969 at r10](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfoCxeR7EL5b6JFuQ5e:-NfoRrMD1dPdI03Gqd-g:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/45ad990e6ff940872d832e1996f90a4cbffe7685/corelib/src/test/integer_test.cairo#L969)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

or "as-intended"
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs` line 56 at r10](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfoAMpC3ssNPqCztQXg:-NfoRtL8EIFzG4eSII4u:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/45ad990e6ff940872d832e1996f90a4cbffe7685/crates/cairo-lang-sierra-to-casm/src/invocations/casts.rs#L56)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add an assert that from type is unsigned. Add an assumption to the documentation of `add_downcast_overflow_below`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-04 10:56 UTC, liorgold2 reviewed
> Reviewed 1 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: 6 of 7 files reviewed, 7 unresolved discussions (waiting on @spapinistarkware)



<!-- Sent from Reviewable.io -->

2023-10-04 14:17 UTC, liorgold2 requested changes
> Reviewed 1 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`corelib/src/test/integer_test.cairo` line 1013 at r11](https://reviewable.io/reviews/starkware-libs/cairo/3623#-NfuWqlS3Yrcg4xniERL:-NfuWqlT3YBYbynRj6xl:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/18d46f14788bbfe6ebddcfd56c7244a7fb54c379/corelib/src/test/integer_test.cairo#L1013)):*
> ```Cairo
> 
> /// Checks that castings from `SubType` to `SuperType` are correct around the bounds, where
> /// `SubType` is strictly contained in `SuperType`.
> ```





_Suggestion:_
```Cairo
/// `SubType` is strictly contained (in both bounds) in `SuperType`.
```


<!-- Sent from Reviewable.io -->

2023-10-04 14:18 UTC, liorgold2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Dismissed @spapinistarkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623#-:-Nfv2MNbBqIuoYe9vjPo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2023-10-10 08:56 UTC, orizi reviewed
> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3623)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2023-10-10 09:13 UTC, merged