no_std-support
starkware-libs/cairo pull request #3771
Opened 2023-07-25 10:21 UTC by LucasLvy

2023-07-25 22:01 UTC, tdelabro requested changes

2023-07-25 22:01 UTC, tdelabro commented on crates/cairo-lang-casm-contract-class/Cargo.toml
> +    "serde/std",
itertools has a `use_std` feature

2023-07-25 22:01 UTC, tdelabro commented on crates/cairo-lang-casm-contract-class/src/lib.rs
> +use serde::{Deserialize, Serialize};
Everything serde related could be behind a feature flag

2023-07-25 22:01 UTC, tdelabro commented on crates/cairo-lang-casm/Cargo.toml
> +std = ["cairo-lang-utils/std"]
also `thiserror-no-std/std`, `parity-scale-codec?/std`, `cairo-lang-utils/std`

2023-07-25 22:01 UTC, tdelabro commented on crates/cairo-lang-runner/Cargo.toml
> -salsa.workspace = true
It was unused?

2023-07-25 22:01 UTC, tdelabro commented on crates/cairo-lang-utils/Cargo.toml
> +std = [
`parity-scale-codec?/std`

2023-07-25 22:01 UTC, tdelabro commented on crates/cairo-lang-utils/Cargo.toml
> -env_logger = ["dep:env_logger", "dep:time", "dep:log"]
`schemars = ["std", "dep:shemars"]`

2023-07-25 22:01 UTC, tdelabro commented on crates/cairo-lang-vm-utils/src/lib.rs
> +
You did the whole copy pasting again?

2023-07-25 22:01 UTC, tdelabro commented on ensure_no_std/Cargo.toml
> +cairo-lang-casm-contract-class = { path = "../crates/cairo-lang-casm-contract-class", default-features = false }
You can add the  `features = ["serde"]` and any other feature that exists and should be supported in `no_std`

2023-07-26 09:32 UTC, LucasLvy commented on crates/cairo-lang-runner/Cargo.toml
> -salsa.workspace = true
apparently as everything still works

2023-07-26 09:32 UTC, LucasLvy commented on crates/cairo-lang-vm-utils/src/lib.rs
> +
yes

2023-07-26 14:44 UTC, tdelabro requested changes
When a crate does not aim to build in `no_std`. It should import the deps defined in the workspace with `default-features = false`, using `features = ["std"]`. 
So it can benefit from those potential additional features

2023-07-26 14:44 UTC, tdelabro commented on .github/workflows/ci.yml
> +          - nextest run -p cairo-lang-casm-contract-class --no-default-features --features serde
Is all this really required?
Can't you just do a run with no_std + supported features and another with all features including std?

2023-07-26 14:44 UTC, tdelabro commented on crates/cairo-lang-casm/src/operand.rs
> +
remove empty line

2023-07-26 14:44 UTC, tdelabro commented on crates/cairo-lang-project/Cargo.toml
> +serde = { workspace = true, optional = true }
it should also be imported with "std" feature, as this crate does not aim to compile in `no_std`.

2023-07-26 14:44 UTC, tdelabro commented on crates/cairo-lang-filesystem/Cargo.toml
> +serde = { workspace = true, optional = true }
It should also be imported with feature `std`.

2023-07-26 14:44 UTC, tdelabro commented on crates/cairo-lang-runner/Cargo.toml
>  cairo-felt.workspace = true
features = std

2023-07-26 14:44 UTC, tdelabro commented on crates/cairo-lang-runner/Cargo.toml
>  num-traits.workspace = true
For all those too feature = "std"

2023-07-27 08:33 UTC, orizi submitted a review, later dismissed
> Reviewed 16 of 59 files at r1, 6 of 51 files at r2, 5 of 31 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3771)* status: 27 of 98 files reviewed, 15 unresolved discussions (waiting on @LucasLvy, @spapinistarkware, and @tdelabro)

___
*[`.gitignore` line 11 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3771#-NaLSawW4xqAn4wHzSdR:-NaLSawW4xqAn4wHzSdS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3142b5ffba7b7e2204776661dbb44e6787a1a54c/.gitignore#L11)):*
> ```ignore
> # so it is kept out of the workspace meaning it produce it's own target and Cairo.lock files
> ensure_no_std/target
> ensure_no_std/Cargo.lock
> ```





_Suggestion:_
```ignore
# This crate has to be built with nightly and specific target.
# so it is kept out of the workspace meaning it produce it's own target and Cairo.lock files
ensure_no_std/target
ensure_no_std/Cargo.lock
```


<!-- Sent from Reviewable.io -->

2023-07-27 08:46 UTC, LucasLvy reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3771)* status: 26 of 98 files reviewed, 15 unresolved discussions (waiting on @orizi, @spapinistarkware, and @tdelabro)

___
*[`.gitignore` line 11 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3771#-NaLSawW4xqAn4wHzSdR:-NaLWY7C0PC8D8Qa2z3Y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3142b5ffba7b7e2204776661dbb44e6787a1a54c/.gitignore#L11)):*
> ```ignore
> # so it is kept out of the workspace meaning it produce it's own target and Cairo.lock files
> ensure_no_std/target
> ensure_no_std/Cargo.lock
> ```

Done.
___
*[`.github/workflows/ci.yml` line 61 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3771#gh-1275068476:-NaLWYvT9G93WRWoK7bP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/afee58b48e9d3b244bcb56c1b9ef5631abf65795/.github/workflows/ci.yml#L61)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

Is all this really required?
Can't you just do a run with no_std + supported features and another with all features including std?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-casm/Cargo.toml` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3771#gh-1274151008:-NaLWZFvAGad7W8ySuNk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/45a7ee8868529e3bf836d2eef90e4042aac4d358/crates/cairo-lang-casm/Cargo.toml#L34)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

also `thiserror-no-std/std`, `parity-scale-codec?/std`, `cairo-lang-utils/std`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-casm/src/operand.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3771#gh-1275072816:-NaLWZZh3PrDVIiPxNiY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/afee58b48e9d3b244bcb56c1b9ef5631abf65795/crates/cairo-lang-casm/src/operand.rs#L77)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.
___
*[`crates/cairo-lang-casm-contract-class/Cargo.toml` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3771#gh-1274149078:-NaLW_-zBSvrUgRhIK-H:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/45a7ee8868529e3bf836d2eef90e4042aac4d358/crates/cairo-lang-casm-contract-class/Cargo.toml#L21)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

itertools has a `use_std` feature
</blockquote></details>

Done.
___
*[`crates/cairo-lang-casm-contract-class/src/lib.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3771#gh-1274149748:-NaLW_E07oOWY34dOvnp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/45a7ee8868529e3bf836d2eef90e4042aac4d358/crates/cairo-lang-casm-contract-class/src/lib.rs#L12)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

Everything serde related could be behind a feature flag
</blockquote></details>

Done.
___
*[`crates/cairo-lang-filesystem/Cargo.toml` line 14 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3771#gh-1275079160:-NaLW_TS5A5j3rpi7ydb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/afee58b48e9d3b244bcb56c1b9ef5631abf65795/crates/cairo-lang-filesystem/Cargo.toml#L14)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

It should also be imported with feature `std`.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-project/Cargo.toml` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3771#gh-1275077122:-NaLW_mkE173Ibn2g6DZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/afee58b48e9d3b244bcb56c1b9ef5631abf65795/crates/cairo-lang-project/Cargo.toml#L12)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

it should also be imported with "std" feature, as this crate does not aim to compile in `no_std`.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/Cargo.toml` line 15 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3771#gh-1275080551:-NaLWaFT9s7ZoINC8SIc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/afee58b48e9d3b244bcb56c1b9ef5631abf65795/crates/cairo-lang-runner/Cargo.toml#L15)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

features = std
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/Cargo.toml` line 44 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3771#gh-1275081081:-NaLWaU0-Ty6B0lr_Kgs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/afee58b48e9d3b244bcb56c1b9ef5631abf65795/crates/cairo-lang-runner/Cargo.toml#L44)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

For all those too feature = "std"
</blockquote></details>

Done.
___
*[`crates/cairo-lang-utils/Cargo.toml` line 0 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3771#gh-1274157565:-NaLWame7JlD-tpZYzzk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/45a7ee8868529e3bf836d2eef90e4042aac4d358/crates/cairo-lang-utils/Cargo.toml#L0)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)*

`schemars = ["std", "dep:shemars"]`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-utils/Cargo.toml` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3771#gh-1274157037:-NaLWbCoCiRjuAROxPpH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/45a7ee8868529e3bf836d2eef90e4042aac4d358/crates/cairo-lang-utils/Cargo.toml#L38)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

`parity-scale-codec?/std`
</blockquote></details>

Done.
___
*[`ensure_no_std/Cargo.toml` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3771#gh-1274161962:-NaLWbwa5gJxAvjefJFm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/45a7ee8868529e3bf836d2eef90e4042aac4d358/ensure_no_std/Cargo.toml#L12)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

You can add the  `features = ["serde"]` and any other feature that exists and should be supported in `no_std`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-08 14:26 UTC, tdelabro commented
@orizi @spapinistarkware 
Do you plan to merge this one? Like, if @LucasLvy rebase it tomorrow. Will you review and merge it?

2023-11-29 09:17 UTC, closed without merging