Syntax and semantic support for string literals
starkware-libs/cairo pull request #3791
Opened 2023-07-30 16:47 UTC by yuvalsw

2023-07-31 07:26 UTC, orizi requested changes
> Reviewed 4 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: 4 of 33 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`corelib/src/string.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Naep9Hl-ixx0qOrEIUt:-Naep9Hm-_SBFlVqWbI6:b-u1v8u4) ([raw file](https://github.com/starkware-libs/cairo/blob/14dbc7c5e89d40e00450057ac7aa6f2a5591d380/corelib/src/string.cairo#L3)):*
> ```Cairo
> // TODO(yuval): implement real string representation.
> /// Temporary Struct to represent a String.
> struct String {}
> ```

I don't know whether if we are going to ever add actual non-byte array strings.
rather not even have a placeholder in this case. 



_Code quote:_
```Cairo
// TODO(yuval): implement real string representation.
/// Temporary Struct to represent a String.
struct String {}
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/illegal_string_escapes` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3791#-NaepqLo7Ks86XvLR8lE:-NaepqLo7Ks86XvLR8lF:bbpe3ei) ([raw file](https://github.com/starkware-libs/cairo/blob/14dbc7c5e89d40e00450057ac7aa6f2a5591d380/crates/cairo-lang-parser/src/parser_test_data/illegal_string_escapes#L48)):*
> ```
> 
> //! > expected_diagnostics
> error: Strings can only include ASCII characters.
> ```

mostly since i don't want to refer to Strings directly yet.



_Suggestion:_
```
String literals 
```


<!-- Sent from Reviewable.io -->

2023-07-31 07:28 UTC, orizi requested changes
> Reviewed 2 of 33 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: 6 of 33 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1832 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Naeq3lkEoZ0wACmmTY3:-Naeq3lkEoZ0wACmmTY4:b-97jxdc) ([raw file](https://github.com/starkware-libs/cairo/blob/14dbc7c5e89d40e00450057ac7aa6f2a5591d380/crates/cairo-lang-runner/src/casm_run/mod.rs#L1832)):*
> ```XML
>             )?;
>         }
>         // TODO(yuval): support printing strings.
> ```

this isn't actually relevant for here - this would be a different hint in any case.



_Code quote:_
```XML
        // TODO(yuval): support printing strings.
```


<!-- Sent from Reviewable.io -->

2023-07-31 08:49 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: 4 of 33 files reviewed, 3 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-parser/src/parser_test_data/illegal_string_escapes` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3791#-NaepqLo7Ks86XvLR8lE:-Naf7LcCA_UJVD1LQ2jD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/14dbc7c5e89d40e00450057ac7aa6f2a5591d380/crates/cairo-lang-parser/src/parser_test_data/illegal_string_escapes#L48)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

mostly since i don't want to refer to Strings directly yet.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1832 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Naeq3lkEoZ0wACmmTY3:-Naf6jCbAP2_-_Ed3h19:b-fy85ij) ([raw file](https://github.com/starkware-libs/cairo/blob/14dbc7c5e89d40e00450057ac7aa6f2a5591d380/crates/cairo-lang-runner/src/casm_run/mod.rs#L1832)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this isn't actually relevant for here - this would be a different hint in any case.
</blockquote></details>

It doesn't say it should be in the same hint. Where do you want this TODO if not here?
___
*[`corelib/src/string.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Naep9Hl-ixx0qOrEIUt:-Naey0U7CN6GMIhekiCH:biykgdu) ([raw file](https://github.com/starkware-libs/cairo/blob/14dbc7c5e89d40e00450057ac7aa6f2a5591d380/corelib/src/string.cairo#L3)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I don't know whether if we are going to ever add actual non-byte array strings.
rather not even have a placeholder in this case. 
</blockquote></details>

Haha
This was from before I added ByteArray. Removing.


<!-- Sent from Reviewable.io -->

2023-07-31 13:11 UTC, orizi requested changes
> Reviewed 12 of 33 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: 18 of 33 files reviewed, 5 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 89 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Nag2md93D__vkcVkQJ3:-Nag2md93D__vkcVkQJ4:bz7wdzz) ([raw file](https://github.com/starkware-libs/cairo/blob/36f7f4bcac4134475c811a05fe9dba61e6e864c5/crates/cairo-lang-lowering/src/diagnostic.rs#L89)):*
> ```XML
>                 .into()
>             }
>             LoweringDiagnosticKind::UnsupportedString => "Strings are not yet supported.".into(),
> ```

it is byte array and not string?
___
*[`crates/cairo-lang-parser/src/lexer.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Nag3INH-1Xu8CC268U8:-Nag3INH-1Xu8CC268U9:bsgvnv4) ([raw file](https://github.com/starkware-libs/cairo/blob/36f7f4bcac4134475c811a05fe9dba61e6e864c5/crates/cairo-lang-parser/src/lexer.rs#L185)):*
> ```XML
> 
>         TokenKind::String
>     }
> ```

merge fns.



_Code quote:_
```XML
    /// Takes a short string.
    fn take_token_short_string(&mut self) -> TokenKind {
        self.take();
        let mut escaped = false;
        while let Some(token) = self.peek() {
            self.take();
            match token {
                _ if escaped => escaped = false,
                '\\' => escaped = true,
                '\'' => {
                    break;
                }
                _ => {}
            };
        }

        // Parse _type suffix.
        if self.peek() == Some('_') {
            self.take_while(|c| c.is_ascii_alphanumeric() || c == '_');
        }
        TokenKind::ShortString
    }

    /// Takes a string.
    fn take_token_string(&mut self) -> TokenKind {
        self.take();
        let mut escaped = false;
        while let Some(token) = self.peek() {
            self.take();
            match token {
                _ if escaped => escaped = false,
                '\\' => escaped = true,
                '"' => {
                    break;
                }
                _ => {}
            };
        }

        TokenKind::String
    }
```
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 213 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Nag3cE4C6g2tFpvBcoq:-Nag3cE4C6g2tFpvBcor:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/36f7f4bcac4134475c811a05fe9dba61e6e864c5/crates/cairo-lang-plugins/src/plugins/config.rs#L213)):*
> ```XML
>                     diagnostics.push(PluginDiagnostic {
>                         stable_ptr: value_stable_ptr.untyped(),
>                         message: "Expected a string or a short string.".into(),
> ```





_Suggestion:_
```XML
  message: "Expected a string or a short string literal.".into(),
```
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1832 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Naeq3lkEoZ0wACmmTY3:-Nag3gft5YOhhVESpcYR:b-q8dpia) ([raw file](https://github.com/starkware-libs/cairo/blob/14dbc7c5e89d40e00450057ac7aa6f2a5591d380/crates/cairo-lang-runner/src/casm_run/mod.rs#L1832)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

It doesn't say it should be in the same hint. Where do you want this TODO if not here?
</blockquote></details>

i think having it in a random place is worse than not having it at all.


<!-- Sent from Reviewable.io -->

2023-07-31 14:36 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: 18 of 33 files reviewed, 5 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/diagnostic.rs` line 89 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Nag2md93D__vkcVkQJ3:-NagM9f-Dn_nqZXlQz0s:bvqefht) ([raw file](https://github.com/starkware-libs/cairo/blob/36f7f4bcac4134475c811a05fe9dba61e6e864c5/crates/cairo-lang-lowering/src/diagnostic.rs#L89)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it is byte array and not string?
</blockquote></details>

Forgot to remove. It's supported now :)
___
*[`crates/cairo-lang-parser/src/lexer.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Nag3INH-1Xu8CC268U8:-NagMW2x8PG0Ny1V3mIH:bt4u0jp) ([raw file](https://github.com/starkware-libs/cairo/blob/36f7f4bcac4134475c811a05fe9dba61e6e864c5/crates/cairo-lang-parser/src/lexer.rs#L185)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

merge fns.
</blockquote></details>

It will only complicate things (you need to remember whether you're in a string or a short string) and you'll need parameters for the token kind and the relevant character. Also the suffix part is irrelevant for strings.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 213 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Nag3cE4C6g2tFpvBcoq:-NagNA0Y1pMDS2fk57-k:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/36f7f4bcac4134475c811a05fe9dba61e6e864c5/crates/cairo-lang-plugins/src/plugins/config.rs#L213)):*
> ```XML
>                     diagnostics.push(PluginDiagnostic {
>                         stable_ptr: value_stable_ptr.untyped(),
>                         message: "Expected a string or a short string.".into(),
> ```

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1832 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Naeq3lkEoZ0wACmmTY3:-NagNHLF5s7Fmr4xVQyz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/14dbc7c5e89d40e00450057ac7aa6f2a5591d380/crates/cairo-lang-runner/src/casm_run/mod.rs#L1832)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think having it in a random place is worse than not having it at all.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-01 06:51 UTC, orizi requested changes
> Reviewed 5 of 33 files at r1, 1 of 3 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: 24 of 33 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware and @yuvalsw)

___
*[`crates/cairo-lang-syntax/src/node/ast_ext.rs` line 135 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Najr-fQ8ZR0Fqw50Fxb:-Najr-fQ8ZR0Fqw50Fxc:b-ga4r1h) ([raw file](https://github.com/starkware-libs/cairo/blob/231c6897f2588a352eb3d3b0ee7cb3c81040de2c/crates/cairo-lang-syntax/src/node/ast_ext.rs#L135)):*
> ```XML
>         }
> 
>         Some(text)
> ```

is this mergable with the other string_value function?



_Code quote:_
```XML
    pub fn string_value(&self, db: &dyn SyntaxGroup) -> Option<String> {
        let text = self.text(db);

        let text = text.as_str();
        let text = if text.starts_with('"') && text.ends_with('"') {
            let (_, text) = text.split_once('"').unwrap();
            let (text, _) = text.rsplit_once('"').unwrap();
            text
        } else {
            unreachable!();
        };

        let text = unescape(text).ok()?;

        if !text.is_ascii() {
            return None;
        }

        Some(text)
```


<!-- Sent from Reviewable.io -->

2023-08-01 11:03 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: 24 of 33 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-syntax/src/node/ast_ext.rs` line 135 at r3](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Najr-fQ8ZR0Fqw50Fxb:-Nakl6wo6MfynAApbT5C:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/231c6897f2588a352eb3d3b0ee7cb3c81040de2c/crates/cairo-lang-syntax/src/node/ast_ext.rs#L135)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is this mergable with the other string_value function?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-01 15:12 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: 24 of 33 files reviewed, 2 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-parser/src/lexer.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Nag3INH-1Xu8CC268U8:-NaldsabCPbZo3WsckHT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/36f7f4bcac4134475c811a05fe9dba61e6e864c5/crates/cairo-lang-parser/src/lexer.rs#L185)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

    fn take_token_short_string(&mut self) -> TokenKind {
          self.take_token_string_helper('\'');       
        // Parse _type suffix.
        if self.peek() == Some('_') {
            self.take_while(|c| c.is_ascii_alphanumeric() || c == '_');
        }
        TokenKind::ShortString
    }

    fn take_token_string(&mut self) -> TokenKind {
          self.take_token_string_helper('"');
          TokenKind::String
    }

    fn take_token_string_helper(&mut self, end: char) {
        self.take();
        let mut escaped = false;
        while let Some(token) = self.peek() {
            self.take();
            match token {
                _ if escaped => escaped = false,
                '\\' => escaped = true,
                _ if token == end => break,
                _ => {}
            };
        }
    }

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-01 15:23 UTC, orizi reviewed
> Reviewed 5 of 33 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: 29 of 33 files reviewed, all discussions resolved (waiting on @spapinistarkware)



<!-- Sent from Reviewable.io -->

2023-08-02 11:28 UTC, spapinistarkware requested changes
> Reviewed 13 of 33 files at r1, 2 of 3 files at r2, 5 of 6 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: 28 of 33 files reviewed, 7 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 605 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Naq-ENf1Cr9NY2jVrDe:-Naq-ENf1Cr9NY2jVrDf:bjamfy9) ([raw file](https://github.com/starkware-libs/cairo/blob/3d8396b88d1809b0f40d99be2aafd2162c13bcf5/crates/cairo-lang-lowering/src/lower/mod.rs#L605)):*
> ```XML
>     let num_chunks = expr.value.len() / 31;
>     let chunks_start_indices = 0..num_chunks;
>     let chunks = chunks_start_indices.map(|chunk_start_index| {
> ```

consider using slice.chunks()
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1392 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Napkjc62-HQkvR9-gbr:-Napkjc62-HQkvR9-gbs:bys5iz) ([raw file](https://github.com/starkware-libs/cairo/blob/3d8396b88d1809b0f40d99be2aafd2162c13bcf5/crates/cairo-lang-parser/src/parser.rs#L1392)):*
> ```XML
>             .into(),
>             SyntaxKind::TerminalShortString => self.take::<TerminalShortString>().into(),
>             SyntaxKind::TerminalString => self.take::<TerminalString>().into(),
> ```

I think this is a bit premature
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1867 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3791#-NapkUcd7zPkzfW-NaZv:-NapkUcd7zPkzfW-NaZw:bqjbgw5) ([raw file](https://github.com/starkware-libs/cairo/blob/3d8396b88d1809b0f40d99be2aafd2162c13bcf5/crates/cairo-lang-parser/src/parser.rs#L1867)):*
> ```XML
>             .into(),
>             SyntaxKind::TerminalShortString => self.take::<TerminalShortString>().into(),
>             SyntaxKind::TerminalString => self.take::<TerminalString>().into(),
> ```

Why? Don;t think this is necessary
___
*[`crates/cairo-lang-parser/src/validation.rs` line 132 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Naplgt82Kq7MthTvaRG:-Naplgt82Kq7MthTvaRH:b-vk7x1j) ([raw file](https://github.com/starkware-libs/cairo/blob/3d8396b88d1809b0f40d99be2aafd2162c13bcf5/crates/cairo-lang-parser/src/validation.rs#L132)):*
> ```XML
>         // NOTE: This is a very paranoid case, but let's try to recover anyway here instead of
>         //   panicking.
>         return Err(diagnostics.add(ParserDiagnostic {
> ```

I don't think this can actually happen. Panicking here is ok.
___
*[`crates/cairo-lang-parser/src/validation.rs` line 160 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3791#-NapmkwJ-HbqfCsRlgg_:-NapmkwJ-HbqfCsRlgga:ba3ouw) ([raw file](https://github.com/starkware-libs/cairo/blob/3d8396b88d1809b0f40d99be2aafd2162c13bcf5/crates/cairo-lang-parser/src/validation.rs#L160)):*
> ```XML
> }
> 
> /// Validate that the string literal is valid, after it is consumed by the parser.
> ```

Validates
___
*[`crates/cairo-lang-parser/src/validation.rs` line 182 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Napn-xg6I-WD7wEHuH2:-Napn-xg6I-WD7wEHuH3:b-5z5w1z) ([raw file](https://github.com/starkware-libs/cairo/blob/3d8396b88d1809b0f40d99be2aafd2162c13bcf5/crates/cairo-lang-parser/src/validation.rs#L182)):*
> ```XML
>         text
>     } else {
>         // NOTE: This is a very paranoid case, but let's try to recover anyway here instead of
> ```

This is not a paranoid case. It actually happens for unterminated strings.
___
*[`crates/cairo-lang-test-runner/src/test_config.rs` line 154 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Napk4sSDMLqc7-V3i_f:-Napk4sSDMLqc7-V3i_g:b506dj5) ([raw file](https://github.com/starkware-libs/cairo/blob/3d8396b88d1809b0f40d99be2aafd2162c13bcf5/crates/cairo-lang-test-runner/src/test_config.rs#L154)):*
> ```XML
>                 Some(literal.numeric_value(db).unwrap_or_default().into())
>             }
>             // TODO(yuval): support string panics.
> ```

Not here IMO.


<!-- Sent from Reviewable.io -->

2023-08-02 12:15 UTC, spapinistarkware requested changes
> Reviewed 4 of 33 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: 30 of 33 files reviewed, 9 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 574 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Naq9ULR3_OECc4tMlE0:-Naq9ULR3_OECc4tMlE1:bgk0f6b) ([raw file](https://github.com/starkware-libs/cairo/blob/3d8396b88d1809b0f40d99be2aafd2162c13bcf5/crates/cairo-lang-lowering/src/lower/mod.rs#L574)):*
> ```XML
>     let u32_ty = get_core_ty_by_name(ctx.db.upcast(), "u32".into(), vec![]);
>     let felt252_ty = core_felt252_ty(ctx.db.upcast());
> ```

This function is kinda long and a bit hard to read. I suggest breaking into small functions
___
*[`crates/cairo-lang-semantic/src/expr/test.rs` line 92 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Naq9y6x7BkYK-rwy87C:-Naq9y6x7BkYK-rwy87D:b-aw3ff5) ([raw file](https://github.com/starkware-libs/cairo/blob/3d8396b88d1809b0f40d99be2aafd2162c13bcf5/crates/cairo-lang-semantic/src/expr/test.rs#L92)):*
> ```XML
> 
> #[test_case("\"hello\"")]
> fn test_expr_string_literal(expr_text: &str) {
> ```

We dont want to add tests here. This fiel is using the old mechanism, and its really hard to fix the tests here


<!-- Sent from Reviewable.io -->

2023-08-02 12:19 UTC, spapinistarkware reviewed
> Reviewed 5 of 33 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: 30 of 33 files reviewed, 9 unresolved discussions (waiting on @orizi and @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-08-02 14:55 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: 30 of 35 files reviewed, 6 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 574 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Naq9ULR3_OECc4tMlE0:-NaqjbI0AHblPQY8xn38:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3d8396b88d1809b0f40d99be2aafd2162c13bcf5/crates/cairo-lang-lowering/src/lower/mod.rs#L574)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This function is kinda long and a bit hard to read. I suggest breaking into small functions
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1392 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Napkjc62-HQkvR9-gbr:-NaqNmBF3fYxBj28AGnY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3d8396b88d1809b0f40d99be2aafd2162c13bcf5/crates/cairo-lang-parser/src/parser.rs#L1392)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think this is a bit premature
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 1867 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3791#-NapkUcd7zPkzfW-NaZv:-NaqNqaCDsKC1y-iOx-M:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3d8396b88d1809b0f40d99be2aafd2162c13bcf5/crates/cairo-lang-parser/src/parser.rs#L1867)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why? Don;t think this is necessary
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/validation.rs` line 132 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Naplgt82Kq7MthTvaRG:-NaqWu4I2P_1uZsuqAzk:b-7yzpio) ([raw file](https://github.com/starkware-libs/cairo/blob/3d8396b88d1809b0f40d99be2aafd2162c13bcf5/crates/cairo-lang-parser/src/validation.rs#L132)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't think this can actually happen. Panicking here is ok.
</blockquote></details>

This (and the other comments) is old code. But fixed anyway.
___
*[`crates/cairo-lang-parser/src/validation.rs` line 182 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Napn-xg6I-WD7wEHuH2:-NaqWr7uDtAe700bCY7V:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3d8396b88d1809b0f40d99be2aafd2162c13bcf5/crates/cairo-lang-parser/src/validation.rs#L182)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This is not a paranoid case. It actually happens for unterminated strings.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test.rs` line 92 at r5](https://reviewable.io/reviews/starkware-libs/cairo/3791#-Naq9y6x7BkYK-rwy87C:-NaqXsqH3cjRcv4TQSfd:b-j3ugvl) ([raw file](https://github.com/starkware-libs/cairo/blob/3d8396b88d1809b0f40d99be2aafd2162c13bcf5/crates/cairo-lang-semantic/src/expr/test.rs#L92)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

We dont want to add tests here. This fiel is using the old mechanism, and its really hard to fix the tests here
</blockquote></details>

All other semantic tests only test diagnostics.
This is a copy of the above test.
There should be a separate work of having good semantic tests (then it would be easy to convert this one with the above one), but not in this PR.
If it already exists and I am missing something, please let me know.


<!-- Sent from Reviewable.io -->

2023-08-03 05:48 UTC, spapinistarkware requested changes
> Reviewed 1 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: 28 of 36 files reviewed, 12 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 588 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3791#-NatvG9-D_RPbFoqrvLe:-NatvG9-D_RPbFoqrvLf:b88965s) ([raw file](https://github.com/starkware-libs/cairo/blob/da8168c51c0cba65246295016602dc7e6fbe4a5e/crates/cairo-lang-lowering/src/lower/mod.rs#L588)):*
> ```XML
>         )));
> 
>     // Build an empty data array
> ```

Remove the comment. It's in the name of the function you are calling.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 592 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3791#-NatvJkY-o9L43iY4HN0:-NatvJkY-o9L43iY4HN1:bb73xfv) ([raw file](https://github.com/starkware-libs/cairo/blob/da8168c51c0cba65246295016602dc7e6fbe4a5e/crates/cairo-lang-lowering/src/lower/mod.rs#L592)):*
> ```XML
>         build_empty_data_array(ctx, builder, expr, data_array_new_function, data_array_ty);
> 
>     // Add all chunks to the data array.
> ```

Same
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 603 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3791#-NatvLpT2E6YtLSR8p_H:-NatvLpT2E6YtLSR8p_I:bb73xfv) ([raw file](https://github.com/starkware-libs/cairo/blob/da8168c51c0cba65246295016602dc7e6fbe4a5e/crates/cairo-lang-lowering/src/lower/mod.rs#L603)):*
> ```XML
>     );
> 
>     // Add pending word.
> ```

Same
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 606 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3791#-NatvNkg4a2wP9t8YIrQ:-NatvNkhC8lN6An-G-bv:bdyllja) ([raw file](https://github.com/starkware-libs/cairo/blob/da8168c51c0cba65246295016602dc7e6fbe4a5e/crates/cairo-lang-lowering/src/lower/mod.rs#L606)):*
> ```XML
>     let (pending_word_usage, pending_word_len_usage) = add_pending_word(ctx, builder, expr);
> 
>     // Create the ByteArray struct
> ```

End with "."
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 617 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3791#-NatvTTBASmGjijNmtlQ:-NatvTTBASmGjijNmtlR:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/da8168c51c0cba65246295016602dc7e6fbe4a5e/crates/cairo-lang-lowering/src/lower/mod.rs#L617)):*
> ```XML
> }
> 
> /// Helper function to emit lowering statements to build an empty data array.
> ```





_Suggestion:_
```XML
Emits
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 636 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3791#-NatvY675p8K_8qwFgqC:-NatvY675p8K_8qwFgqD:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/da8168c51c0cba65246295016602dc7e6fbe4a5e/crates/cairo-lang-lowering/src/lower/mod.rs#L636)):*
> ```XML
> }
> 
> /// Helper function to emit lowering statements to add 31-byte words to the given data array.
> ```





_Suggestion:_
```XML
Emits
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 646 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3791#-NatvwlD0uiVrrxUaulQ:-NatvwlD0uiVrrxUaulR:buk70uj) ([raw file](https://github.com/starkware-libs/cairo/blob/da8168c51c0cba65246295016602dc7e6fbe4a5e/crates/cairo-lang-lowering/src/lower/mod.rs#L646)):*
> ```XML
>     data_array_ty: semantic::TypeId,
> ) {
>     for chunk in expr.value.as_bytes().chunks_exact(31) {
> ```

The chunks_exact() iterator can give you the "pending word" by calling .remainder(). It might be more elegany to return it from this function.


<!-- Sent from Reviewable.io -->

2023-08-03 05:58 UTC, spapinistarkware reviewed
> Reviewed 1 of 6 files at r3, 1 of 3 files at r6, 4 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: 33 of 36 files reviewed, 8 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/validation.rs` line 149 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3791#-NatxBpHBTKNEKIx-XeU:-NatxBpI2NNBBdjtYz3L:b-qbrehf) ([raw file](https://github.com/starkware-libs/cairo/blob/da8168c51c0cba65246295016602dc7e6fbe4a5e/crates/cairo-lang-parser/src/validation.rs#L149)):*
> ```XML
>     file_id: FileId,
> ) -> Maybe<()> {
>     validate_any_string(
> ```

Now you are allowing "blabla"_suffix
Is tis your intention?


<!-- Sent from Reviewable.io -->

2023-08-03 05:59 UTC, spapinistarkware reviewed
> Reviewed 1 of 3 files at r6, 1 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: 35 of 36 files reviewed, 8 unresolved discussions (waiting on @orizi and @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-08-03 09:25 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: 35 of 36 files reviewed, 7 unresolved discussions (waiting on @orizi and @spapinistarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 588 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3791#-NatvG9-D_RPbFoqrvLe:-NauaktIAq23wh9witBl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/da8168c51c0cba65246295016602dc7e6fbe4a5e/crates/cairo-lang-lowering/src/lower/mod.rs#L588)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Remove the comment. It's in the name of the function you are calling.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 592 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3791#-NatvJkY-o9L43iY4HN0:-NaualC-7W_4rLgaYqxi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/da8168c51c0cba65246295016602dc7e6fbe4a5e/crates/cairo-lang-lowering/src/lower/mod.rs#L592)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 603 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3791#-NatvLpT2E6YtLSR8p_H:-Naualh3DIcGY9koQpgX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/da8168c51c0cba65246295016602dc7e6fbe4a5e/crates/cairo-lang-lowering/src/lower/mod.rs#L603)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 606 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3791#-NatvNkg4a2wP9t8YIrQ:-NauarnM5FPbW28dg9qM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/da8168c51c0cba65246295016602dc7e6fbe4a5e/crates/cairo-lang-lowering/src/lower/mod.rs#L606)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

End with "."
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 617 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3791#-NatvTTBASmGjijNmtlQ:-NauasaA1z3Ft-7GuEsA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/da8168c51c0cba65246295016602dc7e6fbe4a5e/crates/cairo-lang-lowering/src/lower/mod.rs#L617)):*
> ```XML
> }
> 
> /// Helper function to emit lowering statements to build an empty data array.
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 636 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3791#-NatvY675p8K_8qwFgqC:-NauaswTEIhcH7fBX8wX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/da8168c51c0cba65246295016602dc7e6fbe4a5e/crates/cairo-lang-lowering/src/lower/mod.rs#L636)):*
> ```XML
> }
> 
> /// Helper function to emit lowering statements to add 31-byte words to the given data array.
> ```

Done.
___
*[`crates/cairo-lang-parser/src/validation.rs` line 149 at r7](https://reviewable.io/reviews/starkware-libs/cairo/3791#-NatxBpHBTKNEKIx-XeU:-Naua-Ik48Mbsp4P_5cm:b-rn5xzi) ([raw file](https://github.com/starkware-libs/cairo/blob/da8168c51c0cba65246295016602dc7e6fbe4a5e/crates/cairo-lang-parser/src/validation.rs#L149)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Now you are allowing "blabla"_suffix
Is tis your intention?
</blockquote></details>

This is not allowed in the literal level. It can't be parsed that way, the same way a string must start with a `"`, which is why we don't need to check it here again.


<!-- Sent from Reviewable.io -->

2023-08-08 11:04 UTC, spapinistarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791#-:-NbJoUzvByYhA1BFsosk:bnfp4nl)* status: 34 of 36 files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2023-08-08 11:04 UTC, spapinistarkware reviewed
> Reviewed 1 of 7 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-08-08 11:05 UTC, spapinistarkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-08-13 07:24 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, 2 of 3 files at r6, 3 of 7 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791#-:-Nbhm8iWDG3IzNriQcbU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-08-13 14:40 UTC, orizi reviewed
> Reviewed 2 of 2 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-08-13 21:40 UTC, orizi approved these changes
> Reviewed 23 of 23 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-08-13 21:42 UTC, orizi approved these changes
> Reviewed 1 of 33 files at r1, 1 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3791)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-08-14 09:20 UTC, merged