feat: selector!
starkware-libs/cairo pull request #3811
Opened 2023-08-01 11:44 UTC by milancermak

This PR adds a new `selector` macro which computes function selectors at compile time:

```rust
let endpoint = selector!('transfer_from');
```

It prevents the need for hardcoding the selectors as unreadable constants or passing them as arguments, both of which are error prone. This feature request comes up regularly in the community - just today on Discord or last week on Telegram - so I think it's a valuable addition to the repo.

There's currently one issue with the implementation - due to a circular dependency, I had to copy-paste the `starknet_keccak` fn directly into `selector.rs`. Can't think of a good way how to fix it.

Also, I do recognize that the macro is only valuable in the context of Starknet and irrelevant for Cairo.

I'm happy to address both of these concerns with some guidance 🙏 

Lastly, the `inline_macros` tests are not run (IDK why they are disabled), but I've added tests cases for this new macro which ought to verify it's working correctly.

2023-08-01 11:47 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3811)* status: 0 of 5 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3811#-NakuwAjEk0rGpvAoPbH:-NakuwAjEk0rGpvAoPbI:b-nj8uu1) (no related file):*
> Also, I do recognize that the macro is only valuable in the context of Starknet and irrelevant for Cairo.

If this macro is only enabled whenever starknet plugin is, then in Scarb I can make this macro only available if you depend on the `starknet` package. That would naturally work in the future when we move `core::starknet` module to the independent `starknet` package/

___


<!-- Sent from Reviewable.io -->

2023-08-02 05:08 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3811)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @milancermak and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3811#-NaodDjv5MqKM2zJW8sK:-NaodDjv5MqKM2zJW8sL:bu9q8vu) (no related file):*
I'm gonna do a small refactor to make inline macros plugin-able (today/tomorrow). this should probably wait for it.

___


<!-- Sent from Reviewable.io -->

2023-08-08 08:40 UTC, milancermak commented
@orizi just checking - is the refactor done yet? if so, which PR was it? anything I need to do here?

2023-08-09 07:08 UTC, gaetbout commented
🙏 
![image](https://github.com/starkware-libs/cairo/assets/16206518/501e1b0e-11f0-41b5-9d68-fa0f7f708d6c)

2023-08-09 12:38 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3811)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @milancermak and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3811#-NaodDjv5MqKM2zJW8sK:-NbPIVIm4gSDXDYt43vy:b-6dz3mr) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I'm gonna do a small refactor to make inline macros plugin-able (today/tomorrow). this should probably wait for it.
</blockquote></details>

https://reviewable.io/reviews/starkware-libs/cairo/3873

___


<!-- Sent from Reviewable.io -->

2023-08-16 05:44 UTC, orizi reviewed
https://reviewable.io/reviews/starkware-libs/cairo/3912 instead of this PR.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3811#-:-Nbwroo682_KqFmqbwxy:b-5kosy0)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @milancermak and @mkaput)



<!-- Sent from Reviewable.io -->

2023-08-16 08:45 UTC, milancermak commented
Nice! Closing in favor of #3912

2023-08-16 08:45 UTC, closed without merging