Changed enum derive store implementation.
starkware-libs/cairo pull request #3817
Opened 2023-08-01 16:00 UTC by orizi

2023-08-01 16:33 UTC, LucasLvy requested changes

2023-08-01 16:33 UTC, LucasLvy commented on crates/cairo-lang-starknet/src/plugin/plugin_test_data/user_defined_types
> +    }
```suggestion
    #[derive(Drop, Serde, starknet::Store, Default)]
    enum EnumWithDefault {
        A: u8,
        #[default]
        B: u16,
        C: u32,
    }
```
I think it should derive default also

2023-08-01 16:33 UTC, LucasLvy commented on crates/cairo-lang-starknet/src/plugin/plugin_test_data/user_defined_types
> +    }
```suggestion
    #[derive(Drop, Serde, starknet::Store, Default)]
    enum EnumWithDefault {
        A: u8,
        #[default]
        B: u16,
        C: u32,
    }
```

2023-08-01 17:24 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3817)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @LucasLvy, and @spapinistarkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/user_defined_types` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3817#gh-1280858424:-Nam76n_7WnqE48mVind:bjivsyg) ([raw file](https://github.com/starkware-libs/cairo/blob/7726a55507ede9e9c21458874a719eec3f578ec3/crates/cairo-lang-starknet/src/plugin/plugin_test_data/user_defined_types#L32)):*
<details><summary><i>Previously, LucasLvy (Lucas @ StarkWare) wrote…</i></summary><blockquote>

```suggestion
    #[derive(Drop, Serde, starknet::Store, Default)]
    enum EnumWithDefault {
        A: u8,
        #[default]
        B: u16,
        C: u32,
    }
```
I think it should derive default also
</blockquote></details>

that can happen only after `Default` derive exists.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/user_defined_types` line 79 at r1](https://reviewable.io/reviews/starkware-libs/cairo/3817#gh-1280858797:-Nam7D-k2kgbaROnaQ_o:bjivsyg) ([raw file](https://github.com/starkware-libs/cairo/blob/7726a55507ede9e9c21458874a719eec3f578ec3/crates/cairo-lang-starknet/src/plugin/plugin_test_data/user_defined_types#L79)):*
<details><summary><i>Previously, LucasLvy (Lucas @ StarkWare) wrote…</i></summary><blockquote>

```suggestion
    #[derive(Drop, Serde, starknet::Store, Default)]
    enum EnumWithDefault {
        A: u8,
        #[default]
        B: u16,
        C: u32,
    }
```
</blockquote></details>

that can happen only after `Default` derive exists.


<!-- Sent from Reviewable.io -->

2023-08-01 19:01 UTC, LucasLvy approved these changes

2023-08-02 10:14 UTC, spapinistarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3817#-:-NapjMxL8xNt5S8GkRdj:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp and @LucasLvy)



<!-- Sent from Reviewable.io -->

2023-08-02 10:18 UTC, orizi reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3817)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp and @LucasLvy)



<!-- Sent from Reviewable.io -->

2023-08-02 10:25 UTC, LucasLvy approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3817#-:-Napm06Q3202IZenuGgu:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp)



<!-- Sent from Reviewable.io -->

2023-08-02 10:42 UTC, merged