Fixing snippets view fn without external
starkware-libs/cairo pull request #3857
Opened 2023-08-07 17:43 UTC by gaetbout

There was an extra `#[external]`existing from before in the snippets which is now removed

2023-08-07 17:43 UTC, gaetbout commented
@OriStarkware 🙏

2023-08-09 08:32 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3857#-:-NbOQ9f75Bm8HDiXU356:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gaetbout)



<!-- Sent from Reviewable.io -->

2023-08-09 08:32 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3857)* status: all files reviewed, 1 unresolved discussion (waiting on @gaetbout)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/3857#-NbOQAT7E-2_Jlg_AafM:-NbOQAT7E-2_Jlg_AafN:b-3qvl3k) (no related file):*
@yuvalsw for 2nd eye

___


<!-- Sent from Reviewable.io -->

2023-08-09 08:32 UTC, orizi approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3857)* status: all files reviewed, 1 unresolved discussion (waiting on @gaetbout)



<!-- Sent from Reviewable.io -->

2023-08-09 12:25 UTC, yuvalsw approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/3857#-:-NbPFdjc9-luKKYFFNX-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gaetbout)



<!-- Sent from Reviewable.io -->

2023-08-09 12:33 UTC, merged