Test-runner:  separate build run, make compiled tests serializable
starkware-libs/cairo pull request #4015
Opened 2023-09-06 07:07 UTC by maciektr

2023-09-06 08:02 UTC, mkaput requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4015)* status: all files reviewed, 3 unresolved discussions (waiting on @maciektr)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NddV43-EqSeX-jddWgF:-NddV43-EqSeX-jddWgG:bqlct1p) (no related file):*
nit, can you please write a rationale for these changes in PR description? It's not obvious why we are doing this.

___
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NddVcdzDaXJvXkDcqJa:-NddVcdzDaXJvXkDcqJb:b-ckwgy) ([raw file](https://github.com/starkware-libs/cairo/blob/7ff4abde11bca0e37b2f5088a5c75e37c17f569b/crates/cairo-lang-test-runner/src/lib.rs#L88)):*
> ```XML
> }
> 
> pub struct TestCompilationRunner {
> ```

This seems to be more self-descriptive to me. Wdyt? Otherwise, can you please document this struct?



_Suggestion:_
```XML
PrecompiledTestRunner
```
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NddVIlEA06h-i-Xh4Bx:-NddVIlEA06h-i-Xh4By:bx2r7fm) ([raw file](https://github.com/starkware-libs/cairo/blob/7ff4abde11bca0e37b2f5088a5c75e37c17f569b/crates/cairo-lang-test-runner/src/lib.rs#L92)):*
> ```XML
>     pub filter: String,
>     pub include_ignored: bool,
>     pub ignored: bool,
> ```

Seems like we'd like to have a separate struct with these, like `TestRunConfig` perhaps? The same fields are present in TestRunner.



_Code quote:_
```XML
    pub filter: String,
    pub include_ignored: bool,
    pub ignored: bool,
```


<!-- Sent from Reviewable.io -->

2023-09-06 08:03 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4015)* status: all files reviewed, 4 unresolved discussions (waiting on @maciektr)

___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 296 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NddW0_-7kLq0lsMiX9Z:-NddW0_-7kLq0lsMiX9_:b-3r2l7w) ([raw file](https://github.com/starkware-libs/cairo/blob/7ff4abde11bca0e37b2f5088a5c75e37c17f569b/crates/cairo-lang-test-runner/src/lib.rs#L296)):*
> ```XML
>     sierra_program: Program,
>     function_set_costs: OrderedHashMap<FunctionId, OrderedHashMap<CostTokenType, i32>>,
>     contracts_info: OrderedHashMap<Felt252, ContractInfo>,
> ```

Don't we want to have these public, so that we'll be able to construct this struct from a canonical test artefact (shared with Foundry) when we'll have one developed?



_Suggestion:_
```XML
    pub named_tests: Vec<(String, TestConfig)>,
    pub sierra_program: Program,
    pub function_set_costs: OrderedHashMap<FunctionId, OrderedHashMap<CostTokenType, i32>>,
    pub contracts_info: OrderedHashMap<Felt252, ContractInfo>,
```


<!-- Sent from Reviewable.io -->

2023-09-06 09:44 UTC, maciektr reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4015)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @maciektr, @mkaput, and @orizi)

___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NddVcdzDaXJvXkDcqJa:-Nddj-7_COqvGqL4ExQA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7ff4abde11bca0e37b2f5088a5c75e37c17f569b/crates/cairo-lang-test-runner/src/lib.rs#L88)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

This seems to be more self-descriptive to me. Wdyt? Otherwise, can you please document this struct?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NddVIlEA06h-i-Xh4Bx:-NddrYVPC5mJ1SD7fO7w:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7ff4abde11bca0e37b2f5088a5c75e37c17f569b/crates/cairo-lang-test-runner/src/lib.rs#L92)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Seems like we'd like to have a separate struct with these, like `TestRunConfig` perhaps? The same fields are present in TestRunner.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 296 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NddW0_-7kLq0lsMiX9Z:-Nddj51O4hIninQ8mR3Y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7ff4abde11bca0e37b2f5088a5c75e37c17f569b/crates/cairo-lang-test-runner/src/lib.rs#L296)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Don't we want to have these public, so that we'll be able to construct this struct from a canonical test artefact (shared with Foundry) when we'll have one developed?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-06 10:25 UTC, orizi requested changes
> Reviewed 1 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4015)* status: all files reviewed, 7 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NddVcdzDaXJvXkDcqJa:-Nde0Nhr7b9sakv5x2UQ:b-6mcr08) ([raw file](https://github.com/starkware-libs/cairo/blob/7ff4abde11bca0e37b2f5088a5c75e37c17f569b/crates/cairo-lang-test-runner/src/lib.rs#L88)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

hmmm - not sure about this name - maybe just CompiledTestRunner?
this is for compilation and pre-compilation, so having the `pre` always sounds weird to me.
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4015#-Nde01T6EB52CdCNLx4K:-Nde01T6EB52CdCNLx4L:b7vn9th) ([raw file](https://github.com/starkware-libs/cairo/blob/84b07c80f903d59f258405cc03b49961eda6f846/crates/cairo-lang-test-runner/src/lib.rs#L75)):*
> ```XML
> }
> 
> pub struct PrecompiledTestRunner {
> ```

doc.
doc the other one while at it.
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 211 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4015#-Nde0FVtCrTheA8ZnRyr:-Nde0FVtCrTheA8ZnRys:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/84b07c80f903d59f258405cc03b49961eda6f846/crates/cairo-lang-test-runner/src/lib.rs#L211)):*
> ```XML
> }
> 
> pub fn compile_test_prepared_db(
> ```

doc
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 289 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4015#-Nde0gnB6MK8VkPVK-ob:-Nde0gnB6MK8VkPVK-oc:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/84b07c80f903d59f258405cc03b49961eda6f846/crates/cairo-lang-test-runner/src/lib.rs#L289)):*
> ```XML
> }
> 
> pub fn filter_test_cases(
> ```

doc


<!-- Sent from Reviewable.io -->

2023-09-06 10:37 UTC, mkaput requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4015)* status: all files reviewed, 5 unresolved discussions (waiting on @maciektr and @orizi)

___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NddVcdzDaXJvXkDcqJa:-Nde30X2-pSFqu2uO0sk:b-jemymo) ([raw file](https://github.com/starkware-libs/cairo/blob/7ff4abde11bca0e37b2f5088a5c75e37c17f569b/crates/cairo-lang-test-runner/src/lib.rs#L88)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

hmmm - not sure about this name - maybe just CompiledTestRunner?
this is for compilation and pre-compilation, so having the `pre` always sounds weird to me.
</blockquote></details>

right, let's drop `pre`


<!-- Sent from Reviewable.io -->

2023-09-06 10:44 UTC, maciektr reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4015)* status: all files reviewed, 4 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NddVcdzDaXJvXkDcqJa:-Nde2Qc51LZWNXevbChk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7ff4abde11bca0e37b2f5088a5c75e37c17f569b/crates/cairo-lang-test-runner/src/lib.rs#L88)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

hmmm - not sure about this name - maybe just CompiledTestRunner?
this is for compilation and pre-compilation, so having the `pre` always sounds weird to me.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4015#-Nde01T6EB52CdCNLx4K:-Nde4saP4mNtqcpaay1V:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/84b07c80f903d59f258405cc03b49961eda6f846/crates/cairo-lang-test-runner/src/lib.rs#L75)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc.
doc the other one while at it.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 211 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4015#-Nde0FVtCrTheA8ZnRyr:-Nde2vh_ANHRJeTYlQKr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/84b07c80f903d59f258405cc03b49961eda6f846/crates/cairo-lang-test-runner/src/lib.rs#L211)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 289 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4015#-Nde0gnB6MK8VkPVK-ob:-Nde4t_T8Fh9LBTpJPjo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/84b07c80f903d59f258405cc03b49961eda6f846/crates/cairo-lang-test-runner/src/lib.rs#L289)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-06 11:18 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 6 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4015#-:-NdeCeHZ88T9Xn9OXS57:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2023-09-06 11:18 UTC, orizi approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4015)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2023-09-07 17:43 UTC, maciektr commented
Hi @orizi !

Would you mind taking another look? 
I have realized we cannot simply add `derive Serialize` everywhere, as HashMap keys are not serialized to strings here :/





<!-- Sent from Reviewable.io -->

2023-09-08 06:31 UTC, mkaput requested changes
> Reviewed 3 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4015)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @maciektr and @orizi)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 307 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NdnUAsC1xVyvW-NT8vx:-NdnUAsC1xVyvW-NT8vy:bcby48a) ([raw file](https://github.com/starkware-libs/cairo/blob/5d4034e9e24249d72a5d5e612389d5f7157fcec5/crates/cairo-lang-starknet/src/contract.rs#L307)):*
> ```XML
> pub struct IntermediateContractInfo {
>     /// Sierra function of the constructor.
>     pub constructor: Option<FunctionId>,
> ```

Didn't we want to use LongIDs here?
___
*[`crates/cairo-lang-starknet/src/contract.rs` line 312 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NdnOxIx0eFpAnOOSdhu:-NdnOxIx0eFpAnOOSdhv:bc37nq1) ([raw file](https://github.com/starkware-libs/cairo/blob/5d4034e9e24249d72a5d5e612389d5f7157fcec5/crates/cairo-lang-starknet/src/contract.rs#L312)):*
> ```XML
>     /// Sierra functions of the l1 handler functions.
>     pub l1_handlers: Vec<(Felt252, FunctionId)>,
> }
> ```

Use the following pattern instead: https://github.com/starkware-libs/cairo/blob/94ea2a3184a01e8c84dc67c863937cecb33917ea/crates/cairo-lang-filesystem/src/cfg.rs#L44-L75, i.e. create same named struct in a submodule `serde_ext` (using from/into is fine in this instance, no need to manually do this).

Reason: serde uses structure name in error messages
___
*[`crates/cairo-lang-test-runner/test_data/cairo_project.toml` line 2 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NdnQ1zo9sFQBGazSX7M:-NdnQ1zo9sFQBGazSX7N:b32wd3) ([raw file](https://github.com/starkware-libs/cairo/blob/5d4034e9e24249d72a5d5e612389d5f7157fcec5/crates/cairo-lang-test-runner/test_data/cairo_project.toml#L2)):*
> ```TOML
> [crate_roots]
> contracts = "."
> ```

\n


<!-- Sent from Reviewable.io -->

2023-09-08 06:32 UTC, mkaput requested changes
> Reviewed 4 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4015)* status: all files reviewed, 5 unresolved discussions (waiting on @maciektr and @orizi)

___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 307 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NdnUWeI5i_ceq8FbnIs:-NdnUWeI5i_ceq8FbnIt:b-27298d) ([raw file](https://github.com/starkware-libs/cairo/blob/5d4034e9e24249d72a5d5e612389d5f7157fcec5/crates/cairo-lang-test-runner/src/lib.rs#L307)):*
> ```XML
> pub struct IntermediateTestCompilation {
>     pub contracts_info: Vec<(Felt252, IntermediateContractInfo)>,
>     pub function_set_costs: Vec<(FunctionId, OrderedHashMap<CostTokenType, i32>)>,
> ```

LongID?
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 310 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NdnUO5Y45t9ZX4mBpbx:-NdnUO5Y45t9ZX4mBpby:b95vqvc) ([raw file](https://github.com/starkware-libs/cairo/blob/5d4034e9e24249d72a5d5e612389d5f7157fcec5/crates/cairo-lang-test-runner/src/lib.rs#L310)):*
> ```XML
>     pub named_tests: Vec<(String, TestConfig)>,
>     pub sierra_program: Program,
> }
> ```

same here re: submodule pattern


<!-- Sent from Reviewable.io -->

2023-09-08 08:05 UTC, maciektr commented
*[`crates/cairo-lang-starknet/src/contract.rs` line 312 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NdnOxIx0eFpAnOOSdhu:-NdnnQ2v4lupn30qBHu3:b32vjw) ([raw file](https://github.com/starkware-libs/cairo/blob/5d4034e9e24249d72a5d5e612389d5f7157fcec5/crates/cairo-lang-starknet/src/contract.rs#L312)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Use the following pattern instead: https://github.com/starkware-libs/cairo/blob/94ea2a3184a01e8c84dc67c863937cecb33917ea/crates/cairo-lang-filesystem/src/cfg.rs#L44-L75, i.e. create same named struct in a submodule `serde_ext` (using from/into is fine in this instance, no need to manually do this).

Reason: serde uses structure name in error messages
</blockquote></details>

<3


<!-- Sent from Reviewable.io -->

2023-09-08 08:42 UTC, maciektr reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4015)* status: 6 of 9 files reviewed, 5 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 310 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NdnUO5Y45t9ZX4mBpbx:-NdnnaqvD1XmHeJbWtRu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5d4034e9e24249d72a5d5e612389d5f7157fcec5/crates/cairo-lang-test-runner/src/lib.rs#L310)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

same here re: submodule pattern
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-runner/test_data/cairo_project.toml` line 2 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NdnQ1zo9sFQBGazSX7M:-NdnnfeaDLPzgPgLLh0H:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5d4034e9e24249d72a5d5e612389d5f7157fcec5/crates/cairo-lang-test-runner/test_data/cairo_project.toml#L2)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

\n
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-08 09:19 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4015#-:-Ndo4g2r6odlEJ3WGb4D:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2023-09-08 10:10 UTC, orizi requested changes
> Reviewed 1 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4015)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr)

___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 303 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NdoGJX3EiOaubTCJsm7:-NdoGJX3EiOaubTCJsm8:b-gd035l) ([raw file](https://github.com/starkware-libs/cairo/blob/95844b61234a8c506e25d907c80694f9a14431cf/crates/cairo-lang-test-runner/src/lib.rs#L303)):*
> ```XML
> }
> 
> mod serde_ext {
> ```

doc what is this, and everything inside.
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 533 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NdoFsZvARr3yaantmnp:-NdoFsZvARr3yaantmnq:bcq0c55) ([raw file](https://github.com/starkware-libs/cairo/blob/95844b61234a8c506e25d907c80694f9a14431cf/crates/cairo-lang-test-runner/src/lib.rs#L533)):*
> ```XML
> 
> #[test]
> #[cfg(test)]
> ```

separate to another file for tests only.

mod test;


<!-- Sent from Reviewable.io -->

2023-09-08 10:40 UTC, maciektr reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4015)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 303 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NdoGJX3EiOaubTCJsm7:-NdoNKDf4OlvGXorv3Pk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/95844b61234a8c506e25d907c80694f9a14431cf/crates/cairo-lang-test-runner/src/lib.rs#L303)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc what is this, and everything inside.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 533 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NdoFsZvARr3yaantmnp:-NdoM8pP0RTx3Z-c8YxR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/95844b61234a8c506e25d907c80694f9a14431cf/crates/cairo-lang-test-runner/src/lib.rs#L533)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

separate to another file for tests only.

mod test;
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-10 05:33 UTC, orizi requested changes
> Reviewed 1 of 6 files at r1, 1 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4015)* status: 7 of 10 files reviewed, 3 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-starknet/src/contract.rs` line 341 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NdxXifz1ezrc0XuPCej:-NdxXifz1ezrc0XuPCek:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a1cbba6eaee1c75a501106ff3c68fe552c029714/crates/cairo-lang-starknet/src/contract.rs#L341)):*
> ```XML
>         }
>     }
> }
> ```





_Suggestion:_
```XML
/// Sierra information of a contract.
#[derive(Clone, Serialize, Deserialize, PartialEq, Debug)]
pub struct ContractInfo {
    /// Sierra function of the constructor.
    pub constructor: Option<FunctionId>,
    /// Sierra functions of the external functions.
    #[serde(
        serialize_with = "serialize_entry_points",
        deserialize_with = "deserialize_entry_points"
    )]
    pub externals: OrderedHashMap<Felt252, FunctionId>,
    /// Sierra functions of the l1 handler functions.
    #[serde(
        serialize_with = "serialize_entry_points",
        deserialize_with = "deserialize_entry_points"
    )]
    pub l1_handlers: OrderedHashMap<Felt252, FunctionId>,
}

fn serialize_big_uint<S>(v: &OrderedHashMap<Felt252, FunctionId>, serializer: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
{
    serializer.serialize(v.iter().map(|(ext_id, sierra_id)|(ext_id.clone(), sierra_id.clone())).collect_vec())
}

fn deserialize_big_uint<'a, D>(deserializer: D) -> Result<OrderedHashMap<Felt252, FunctionId>, D::Error>
where
    D: Deserializer<'a>,
{
    Ok(Vec<(Felt252, FunctionId)>::deserialize(deserializer)?.into_iter().collect())
}
```


<!-- Sent from Reviewable.io -->

2023-09-10 05:47 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4015)* status: 7 of 10 files reviewed, 3 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 298 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NdxcFqG2Tnfa_Gvrio0:-NdxcFqG2Tnfa_Gvrio1:bs5c9w6) ([raw file](https://github.com/starkware-libs/cairo/blob/a1cbba6eaee1c75a501106ff3c68fe552c029714/crates/cairo-lang-test-runner/src/lib.rs#L298)):*
> ```XML
> /// Compiled test cases.
> #[derive(Clone, Serialize, Deserialize)]
> #[serde(from = "serde_ext::TestCompilation", into = "serde_ext::TestCompilation")]
> ```

i'm confused - OrderedHashMap has serde.


<!-- Sent from Reviewable.io -->

2023-09-10 09:56 UTC, maciektr commented
*[`crates/cairo-lang-test-runner/src/lib.rs` line 298 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NdxcFqG2Tnfa_Gvrio0:-NdyVpcM84cTv6EXO3_S:b-3mkv5i) ([raw file](https://github.com/starkware-libs/cairo/blob/a1cbba6eaee1c75a501106ff3c68fe552c029714/crates/cairo-lang-test-runner/src/lib.rs#L298)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i'm confused - OrderedHashMap has serde.
</blockquote></details>

Yes, but it may fail in runtime 
https://docs.rs/serde_json/latest/serde_json/fn.to_string.html
For 
```
#[test]
fn serde() {
    let x = OrderedHashMap::from_iter(vec![
        (FunctionId::from(0), OrderedHashMap::from_iter(vec![(CostTokenType::Const, 1)])),
        (FunctionId::from(1), OrderedHashMap::from_iter(vec![(CostTokenType::Const, 2)])),
    ]);
    println!("{}", serde_json::to_string(&x).unwrap());
}
```
I get 
```
called `Result::unwrap()` on an `Err` value: Error("key must be a string", line: 0, column: 0)
thread 'serde' panicked at 'called `Result::unwrap()` on an `Err` value: Error("key must be a string", line: 0, column: 0)', crates/cairo-lang-test-runner/src/lib.rs:546:46

```


<!-- Sent from Reviewable.io -->

2023-09-10 10:03 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4015)* status: 7 of 10 files reviewed, 3 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-test-runner/src/lib.rs` line 298 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4015#-NdxcFqG2Tnfa_Gvrio0:-NdyXL9u5O4NuuYbkYeT:b-klsbos) ([raw file](https://github.com/starkware-libs/cairo/blob/a1cbba6eaee1c75a501106ff3c68fe552c029714/crates/cairo-lang-test-runner/src/lib.rs#L298)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Yes, but it may fail in runtime 
https://docs.rs/serde_json/latest/serde_json/fn.to_string.html
For 
```
#[test]
fn serde() {
    let x = OrderedHashMap::from_iter(vec![
        (FunctionId::from(0), OrderedHashMap::from_iter(vec![(CostTokenType::Const, 1)])),
        (FunctionId::from(1), OrderedHashMap::from_iter(vec![(CostTokenType::Const, 2)])),
    ]);
    println!("{}", serde_json::to_string(&x).unwrap());
}
```
I get 
```
called `Result::unwrap()` on an `Err` value: Error("key must be a string", line: 0, column: 0)
thread 'serde' panicked at 'called `Result::unwrap()` on an `Err` value: Error("key must be a string", line: 0, column: 0)', crates/cairo-lang-test-runner/src/lib.rs:546:46

```
</blockquote></details>

oh right -
in any case do something like:
```
/// Sierra information of a contract.
#[derive(Clone, Serialize, Deserialize, PartialEq, Debug)]
pub struct ContractInfo {
    /// Sierra function of the constructor.
    pub constructor: Option<FunctionId\>,
    /// Sierra functions of the external functions.
    #[serde(
        serialize\_with = "serialize\_entry\_points",
        deserialize\_with = "deserialize\_entry\_points"
    )]
    pub externals: OrderedHashMap<Felt252, FunctionId>,
    /// Sierra functions of the l1 handler functions.
    #\[serde(
        serialize\_with = "serialize\_entry\_points",
        deserialize\_with = "deserialize\_entry\_points"
    )\]
    pub l1\_handlers: OrderedHashMap<Felt252, FunctionId>,
}

fn serialize\_big\_uint<S\>(v: &OrderedHashMap<Felt252, FunctionId>, serializer: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
{
    serializer.serialize(v.iter().map(|(ext\_id, sierra\_id)|(ext\_id.clone(), sierra\_id.clone())).collect\_vec())
}

fn deserialize\_big\_uint<'a, D>(deserializer: D) -> Result<OrderedHashMap<Felt252, FunctionId>, D::Error>
where
    D: Deserializer<'a>,
{
    Ok(Vec<(Felt252, FunctionId)>::deserialize(deserializer)?.into\_iter().collect())
}
```


<!-- Sent from Reviewable.io -->

2023-09-12 07:41 UTC, maciektr commented
*[`crates/cairo-lang-starknet/src/contract.rs` line 298 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4015#-Ne54MHe5TEZIxZzlTU9:-Ne7KaGD-IHBeRtfhvcZ:b-y4ucnh) ([raw file](https://github.com/starkware-libs/cairo/blob/cebd80403f50ed8b08c54067471eaded6bb3f16a/crates/cairo-lang-starknet/src/contract.rs#L298)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I think you can do all of these with two generic functions, one for serialization, and one for deserialization.
serialize_ordered_hashmap_vec, deserialize...
And call it for all three instances.
</blockquote></details>

Yes, indeed, sorry!


<!-- Sent from Reviewable.io -->

2023-09-12 07:45 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4015#-:-Ne7LWXY0nYlJk5xTWJq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)



<!-- Sent from Reviewable.io -->

2023-09-12 09:14 UTC, mkaput approved these changes
> Reviewed 3 of 3 files at r6, 1 of 3 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4015)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciektr)



<!-- Sent from Reviewable.io -->

2023-09-12 09:20 UTC, merged