Handle single-file crate roots in project config
starkware-libs/cairo pull request #4016
Opened 2023-09-06 07:11 UTC by maciektr

2023-09-06 08:07 UTC, mkaput reviewed
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4016)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4016#-NddWRQq6XB3q05Ywhcg:-NddWRQrEcEMqoAKIPp5:bvgcv70) (no related file):*
nit, can you please write a rationale in PR description?

___
___
*[`crates/cairo-lang-compiler/src/db.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4016#-NddWZAmA99EZdBL8Mnh:-NddWZAn2apivnjABvXn:b-kl8g4c) ([raw file](https://github.com/starkware-libs/cairo/blob/1e20dc720fc0957dd4ceea84af32eca67130fc1e/crates/cairo-lang-compiler/src/db.rs#L148)):*
> ```XML
> 
>         if let Some(config) = self.project_config.clone() {
>             update_crate_roots_from_project_config(&mut db, *config.clone())?;
> ```

good catch!
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 354 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4016#-NddWfaU61gjU3H-ktv5:-NddWfaVBLpAX17p_Rw6:bnfvqta) ([raw file](https://github.com/starkware-libs/cairo/blob/1e20dc720fc0957dd4ceea84af32eca67130fc1e/crates/cairo-lang-language-server/src/lib.rs#L354)):*
> ```XML
>                         "Error loading project config from {} directory: {err}",
>                         path.display()
>                     );
> ```

Shouldn't this emit an error log?



_Code quote:_
```XML
                    eprintln!(
                        "Error loading project config from {} directory: {err}",
                        path.display()
                    );
```


<!-- Sent from Reviewable.io -->

2023-09-06 10:46 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4016)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-compiler/src/project.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4016#-Nde57J23CnH1jJ4_D-u:-Nde57J23CnH1jJ4_D-v:b-rhhz1k) ([raw file](https://github.com/starkware-libs/cairo/blob/c89fd3596b484fc8076458737bf4d5743df77930/crates/cairo-lang-compiler/src/project.rs#L59)):*
> ```XML
> pub fn update_crate_roots_from_project_config(
>     db: &mut dyn SemanticGroup,
>     config: ProjectConfig,
> ```

add to project config in some way the bool saying this is a single file config.
pointing to a dir or a file is not enough IMO.
___
*[`crates/cairo-lang-compiler/src/project.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4016#-Nde4ydn627rA8sA7GIG:-Nde4ydn627rA8sA7GIH:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/c89fd3596b484fc8076458737bf4d5743df77930/crates/cairo-lang-compiler/src/project.rs#L83)):*
> ```XML
> }
> 
> pub fn fake_module_main_file(db: &mut dyn SemanticGroup, crate_id: CrateId, file_stem: String) {
> ```

doc


<!-- Sent from Reviewable.io -->

2023-09-06 15:35 UTC, maciektr commented
*[`crates/cairo-lang-compiler/src/project.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4016#-Nde57J23CnH1jJ4_D-u:-Ndf7NYP7sMmAmEoPLli:bd2s2nb) ([raw file](https://github.com/starkware-libs/cairo/blob/c89fd3596b484fc8076458737bf4d5743df77930/crates/cairo-lang-compiler/src/project.rs#L59)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add to project config in some way the bool saying this is a single file config.
pointing to a dir or a file is not enough IMO.
</blockquote></details>

Hi!

What do you think about following notation?

Crate roots: 
```
crate_name = <path>
crate_name = { path = <path> }
```
vs
Crate entrypoints: 
```
crate_name = { entrypoint = <path> }
``` 


<!-- Sent from Reviewable.io -->

2023-09-06 16:05 UTC, maciektr reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4016)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-compiler/src/project.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4016#-Nde4ydn627rA8sA7GIG:-NdepJidDbbypK6Purhb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c89fd3596b484fc8076458737bf4d5743df77930/crates/cairo-lang-compiler/src/project.rs#L83)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 354 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4016#-NddWfaU61gjU3H-ktv5:-NdepEgu6kQnaEuPsS6-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1e20dc720fc0957dd4ceea84af32eca67130fc1e/crates/cairo-lang-language-server/src/lib.rs#L354)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Shouldn't this emit an error log?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-07 06:58 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4016)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-compiler/src/project.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4016#-Nde57J23CnH1jJ4_D-u:-NdiPfHoC17XWf3G24_H:b-qnkp46) ([raw file](https://github.com/starkware-libs/cairo/blob/c89fd3596b484fc8076458737bf4d5743df77930/crates/cairo-lang-compiler/src/project.rs#L59)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Hi!

What do you think about following notation?

Crate roots: 
```
crate_name = <path>
crate_name = { path = <path> }
```
vs
Crate entrypoints: 
```
crate_name = { entrypoint = <path> }
```
</blockquote></details>

what does entrypoint mean in this instance?
___
*[`crates/cairo-lang-compiler/src/project.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4016#-Nde4ydn627rA8sA7GIG:-NdiQYci9HVmxsR8qXqL:bt6a2m7) ([raw file](https://github.com/starkware-libs/cairo/blob/c89fd3596b484fc8076458737bf4d5743df77930/crates/cairo-lang-compiler/src/project.rs#L83)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is what way is this lib fake?
maybe `virtual_wrapper_lib`?


<!-- Sent from Reviewable.io -->

2023-09-07 17:53 UTC, maciektr commented
*[`crates/cairo-lang-compiler/src/project.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4016#-Nde57J23CnH1jJ4_D-u:-NdklETS0juOHryNOZr1:bcfl6m1) ([raw file](https://github.com/starkware-libs/cairo/blob/c89fd3596b484fc8076458737bf4d5743df77930/crates/cairo-lang-compiler/src/project.rs#L59)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what does entrypoint mean in this instance?
</blockquote></details>

I thought about "crate entrypoint" as opposed to "crate root". If you think that adding some bool is clearer, I will be happy to change that :) I am just not sure if we should accept either directory when flag is set to false, and a file when flag is set to true in a single variable (`path = `) :thinking: 


<!-- Sent from Reviewable.io -->

2023-09-07 17:53 UTC, maciektr reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4016)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-compiler/src/project.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4016#-Nde4ydn627rA8sA7GIG:-Ndkl6jMEJzynmlkqgb_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c89fd3596b484fc8076458737bf4d5743df77930/crates/cairo-lang-compiler/src/project.rs#L83)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Is what way is this lib fake?
maybe `virtual_wrapper_lib`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-08 06:35 UTC, mkaput requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4016)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-compiler/src/project.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4016#-Nde57J23CnH1jJ4_D-u:-NdnUk3hEOkk8KwxcGsQ:bky0uwm) ([raw file](https://github.com/starkware-libs/cairo/blob/c89fd3596b484fc8076458737bf4d5743df77930/crates/cairo-lang-compiler/src/project.rs#L59)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

I thought about "crate entrypoint" as opposed to "crate root". If you think that adding some bool is clearer, I will be happy to change that :) I am just not sure if we should accept either directory when flag is set to false, and a file when flag is set to true in a single variable (`path = `) :thinking:
</blockquote></details>

I believe you meant `entrypoint == source_path` and `path == source_root` from Cargo's&Scarb's nomenclatures, aren't you? Maybe let's stick with these?


<!-- Sent from Reviewable.io -->

2023-09-08 06:39 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4016)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @maciektr and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4016#-NdnVcn_A6cuKPBgQNjo:-NdnVcn_A6cuKPBgQNjp:b-r5a0qi) (no related file):*
It's not clear to me, is it possible to have the following directory structure?

```
Scarb.toml/cairo_project.toml -> points source_path = "src/main.cairo"
src/
    main.cairo
    module_a.cairo
    module_a/
        something...
```

When `main.cairo` has the following

```
mod module_a;
```

By injecting `lib.cairo`, I have an impression this might not be possible....

___


<!-- Sent from Reviewable.io -->

2023-09-08 08:55 UTC, maciektr commented
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

It's not clear to me, is it possible to have the following directory structure?

```
Scarb.toml/cairo_project.toml -> points source_path = "src/main.cairo"
src/
    main.cairo
    module_a.cairo
    module_a/
        something...
```

When `main.cairo` has the following

```
mod module_a;
```

By injecting `lib.cairo`, I have an impression this might not be possible....
</blockquote></details>

No, you would need to have following structure instead
```
```
Scarb.toml/cairo_project.toml -> points source_path = "src/main.cairo"
src/
    main.cairo
    main/
        module_a.cairo
        module_a/
            something...
```
Which is ok for the testing use case (not sure about the use defined source-paths).
```





<!-- Sent from Reviewable.io -->

2023-09-08 08:57 UTC, maciektr commented
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

No, you would need to have following structure instead
```
```
Scarb.toml/cairo_project.toml -> points source_path = "src/main.cairo"
src/
    main.cairo
    main/
        module_a.cairo
        module_a/
            something...
```
Which is ok for the testing use case (not sure about the use defined source-paths).
```

</blockquote></details>

```
Scarb.toml/cairo_project.toml -> points source_path = "src/main.cairo"
src/
    main.cairo
    main/
        module_a.cairo
        module_a/
            something...
```




<!-- Sent from Reviewable.io -->

2023-09-08 09:20 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4016)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4016#-NdnVcn_A6cuKPBgQNjo:-Ndo4ozt4ZV3tzdKmOOE:b-k718dm) (no related file):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

```
Scarb.toml/cairo_project.toml -> points source_path = "src/main.cairo"
src/
    main.cairo
    main/
        module_a.cairo
        module_a/
            something...
```
</blockquote></details>

Yeah, that's something that I don't kinda like, especially as it differs from Rust here! But I don't want to be the sole decision-maker what variant we should pursue. @orizi wdyt?

___


<!-- Sent from Reviewable.io -->

2023-09-08 10:13 UTC, orizi requested changes
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4016)* status: all files reviewed, 4 unresolved discussions (waiting on @maciektr)

___
*[`crates/cairo-lang-compiler/src/project.rs` line 92 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4016#-NdoGgZEAovY-W61bT2e:-NdoGgZEAovY-W61bT2f:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fd61006aedea8229c5948af1d0abc480126e7085/crates/cairo-lang-compiler/src/project.rs#L92)):*
> ```XML
> /// This approach allows compiling crates that do not define `lib.cairo` file.
> /// For example, single file crates can be created this way.
> /// The real module entrypoint is defined as `mod` statement in created lib file.
> ```





_Suggestion:_
```XML
/// Generates a wraaper lib file for the given crate.
///
/// This approach allows compiling crates that do not define `lib.cairo` file.
/// For example, single file crates can be created this way.
/// The actual single file module is defined as `mod` item in created lib file.
```
___
*[`crates/cairo-lang-project/src/lib.rs` line 23 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4016#-NdoGvbSC2drKjzQc8VV:-NdoGvbSC2drKjzQc8VW:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/fd61006aedea8229c5948af1d0abc480126e7085/crates/cairo-lang-project/src/lib.rs#L23)):*
> ```XML
> 
> #[derive(thiserror::Error, Debug)]
> pub enum CrateRootError {
> ```

doc


<!-- Sent from Reviewable.io -->

2023-09-08 10:17 UTC, mkaput reviewed
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4016)* status: all files reviewed, 4 unresolved discussions (waiting on @maciektr and @orizi)



<!-- Sent from Reviewable.io -->

2023-09-08 10:32 UTC, maciektr reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4016)* status: all files reviewed, 4 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-compiler/src/project.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4016#-Nde57J23CnH1jJ4_D-u:-NdoLLuf5CzH_EnLIzeZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c89fd3596b484fc8076458737bf4d5743df77930/crates/cairo-lang-compiler/src/project.rs#L59)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I believe you meant `entrypoint == source_path` and `path == source_root` from Cargo's&Scarb's nomenclatures, aren't you? Maybe let's stick with these?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-compiler/src/project.rs` line 92 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4016#-NdoGgZEAovY-W61bT2e:-NdoKqXo0r_OgcdlEt-o:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fd61006aedea8229c5948af1d0abc480126e7085/crates/cairo-lang-compiler/src/project.rs#L92)):*
> ```XML
> /// This approach allows compiling crates that do not define `lib.cairo` file.
> /// For example, single file crates can be created this way.
> /// The real module entrypoint is defined as `mod` statement in created lib file.
> ```

Done.
___
*[`crates/cairo-lang-project/src/lib.rs` line 23 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4016#-NdoGvbSC2drKjzQc8VV:-NdoLK7g8gtjI59ROCDz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fd61006aedea8229c5948af1d0abc480126e7085/crates/cairo-lang-project/src/lib.rs#L23)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-08 11:09 UTC, mkaput requested changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4016)* status: all files reviewed, 4 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4016#-NdnVcn_A6cuKPBgQNjo:-NdoTh8Y5aFrXxr0Tyfc:b-cn6b86) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Yeah, that's something that I don't kinda like, especially as it differs from Rust here! But I don't want to be the sole decision-maker what variant we should pursue. @orizi wdyt?
</blockquote></details>

Yeah, that has exploded in Scarb IMHO: https://github.com/software-mansion/scarb/pull/628/files#r1319674807

___


<!-- Sent from Reviewable.io -->

2023-09-08 13:21 UTC, maciektr commented
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Yeah, that has exploded in Scarb IMHO: https://github.com/software-mansion/scarb/pull/628/files#r1319674807
</blockquote></details>

Hi @orizi !

We've had some discussions offline regarding the last comment from Marek here. 
Are you sure that "pointing to a dir or a file is not enough"? 
We still need to make this distinction somewhere, introducing it here would make the public project config api clearer from user perspective.  




<!-- Sent from Reviewable.io -->

2023-09-09 12:57 UTC, maciektr commented
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Hi @orizi !

We've had some discussions offline regarding the last comment from Marek here. 
Are you sure that "pointing to a dir or a file is not enough"? 
We still need to make this distinction somewhere, introducing it here would make the public project config api clearer from user perspective.
</blockquote></details>

Maybe instead of `mod <file_name>;` we should just copy contents of the file into virtual lib? :thinking: 




<!-- Sent from Reviewable.io -->

2023-09-10 05:18 UTC, orizi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4016)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4016#-NdnVcn_A6cuKPBgQNjo:-NdxW-7k9NOVBxyTeE3N:b-2ytkj3) (no related file):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Maybe instead of `mod <file_name>;` we should just copy contents of the file into virtual lib? :thinking:
</blockquote></details>

copy would be bad - as it would create bad compilation diagnostics (these would point to the wrong file) - wrapper is still probably better.

___


<!-- Sent from Reviewable.io -->

2023-09-10 05:18 UTC, orizi approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4016)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2023-09-10 05:18 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4016)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2023-09-12 08:05 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4016)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4016#-NdnVcn_A6cuKPBgQNjo:-Ne7PGiF8Y1XVvwVEoZc:b9vsckt) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

copy would be bad - as it would create bad compilation diagnostics (these would point to the wrong file) - wrapper is still probably better.
</blockquote></details>

Why can't we just allow the root of a module tree to be named arbitrarily, and just assume `lib.cairo` is the default in case one provides a directory as a path? I think we are constantly trying to work around this requirement, which seems to be an artificial limitation to my eyes (especially as it is not present in Rust).

Assuming we lift this `lib.cairo` requirement -- what would be still _not enough_ in this API:

```toml
[crate_roots]
file_source_path = "sources/a/main.cairo"
directory_source_root = "sources/b"
```

Ignoring aesthetics here. I know this looks very bad, but we're talking about low-level APIs. 99% of users will not touch this, as Scarb will be abstracting this away for them.

___


<!-- Sent from Reviewable.io -->

2023-09-12 10:04 UTC, orizi reviewed
> Reviewed 1 of 1 files at r2, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4016)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr)



<!-- Sent from Reviewable.io -->

2023-09-18 20:33 UTC, maciektr commented
After some offline discussions we have decided to close this PR as no longer needed.

2023-09-18 20:33 UTC, closed without merging