feat: add FeltOneable trait, Nullable deref_or, inline common functions
starkware-libs/cairo pull request #4037
Opened 2023-09-08 14:50 UTC by enitrat

- Adds <felt252,felt252> TryInto and Into implementations - required for generic traits that might require T to implement then
- Inlines common simple functions from the core library
- Adds Felt252Oneable impl
- Adds a NullableDroppableTrait to implement the `deref_or` method

Closes #3854

2023-09-25 03:11 UTC, enitrat commented
Hi @orizi @yuvalsw would it be possible to have a review on this?

Also, what's a good rule to follow when inlining functions? My rule of thumb depended on an arbitrary number of lines / complexity of the function (which is why most one-liner `into`, `try_into` fns have been inlined) but I would like to know what you think about it

2023-09-25 18:21 UTC, orizi requested changes
Generally, don't add inline for single line no side effect extern function calls, as these will be auto inlined mostly.
Regarding Onable - it is an internal trait, don't add things into it. Instead we may add One and Zero traits matching the corresponding rust ones.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4037#-:-NfCYxPo-gIjVQ1Z9pOy:bm1jrc8)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @enitrat)

___
*[`corelib/src/integer.cairo` line 1463 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4037#-NfCZYuo41fif4qXLuGm:-NfCZYup2uZ1iq8O0ZWM:b-m5w6xs) ([raw file](https://github.com/starkware-libs/cairo/blob/578367c82a1394e13912b4834fd1b96bb8a29cf9/corelib/src/integer.cairo#L1463)):*
> ```Cairo
> }
> 
> impl Felt252IntoFelt252 of Into<felt252, felt252> {
> ```

I believe there already is a T into T impl, this would cause duplicated impl.


<!-- Sent from Reviewable.io -->

2023-09-26 04:34 UTC, enitrat commented
> Generally, don't add inline for single line no side effect extern function calls, as these will be auto inlined mostly.

Does that mean a function like

```rust
    fn try_into(self: felt252) -> Option<u16> {
        u16_try_from_felt252(self)
    }
```

will be inlined automatically?

> Regarding Onable - it is an internal trait, don't add things into it. Instead we may add One and Zero traits matching the corresponding rust ones.

Not sure I understood that - do I need to remove something related to Oneable in my PR?

2023-09-28 13:49 UTC, yuvalsw requested changes
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4037)* status: all files reviewed, 3 unresolved discussions (waiting on @enitrat)

___
*[`corelib/src/nullable.cairo` line 21 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4037#-NfR1U_C3_4rzZNUVPEw:-NfR1U_DAsIeYRgczRiC:bpodcv6) ([raw file](https://github.com/starkware-libs/cairo/blob/8e8a0d11730b48cf425ed28f45ec7c0990dc34d8/corelib/src/nullable.cairo#L21)):*
> ```Cairo
>     fn deref_or<impl TDrop: Drop<T>>(self: Nullable<T>, default: T) -> T;
>     fn new(value: T) -> Nullable<T>;
> }
> ```

While you are here, please remove and use #[generate_trait] on the impl. Thanks!



_Code quote:_
```Cairo
trait NullableTrait<T> {
    fn deref(self: Nullable<T>) -> T;
    fn deref_or<impl TDrop: Drop<T>>(self: Nullable<T>, default: T) -> T;
    fn new(value: T) -> Nullable<T>;
}
```
___
*[`corelib/src/nullable.cairo` line 31 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4037#-NfR1cFgCvxlkOjB2swJ:-NfR1cFgCvxlkOjB2swK:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8e8a0d11730b48cf425ed28f45ec7c0990dc34d8/corelib/src/nullable.cairo#L31)):*
> ```Cairo
>     }
> 
>     fn deref_or<impl TDrop: Drop<T>>(self: Nullable<T>, default: T) -> T {
> ```





_Suggestion:_
```Cairo
+Drop<T>
```


<!-- Sent from Reviewable.io -->

2023-09-28 14:07 UTC, orizi reviewed
it is - and yes - probably revert all you have done there.
as you added another impl Onable for felt - which we don't want, and added inlines, which are not relevant.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4037#-:-NfR68HjDZx097OMm0se:b-ta3jto)* status: all files reviewed, 3 unresolved discussions (waiting on @enitrat)



<!-- Sent from Reviewable.io -->

2023-09-30 11:30 UTC, enitrat commented
> as you added another impl Onable for felt

I wasn't able to find the implementation of Oneable<felt252>. Where is it exactly?

2023-10-01 10:14 UTC, orizi reviewed
It didn't exist - and `Onable` is an internal trait - i'd rather not have any additional impls for it if we encourage usage of a `One` and `Zero` traits instead.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4037#-:-NfeieIuDQCrgwRIiD_P:b-t3yixj)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @enitrat and @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-10-01 11:06 UTC, yuvalsw approved these changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4037)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)



<!-- Sent from Reviewable.io -->

2023-10-03 04:27 UTC, enitrat commented
> It didn't exist - and Onable is an internal trait - i'd rather not have any additional impls for it if we encourage usage of a One and Zero traits instead.

I think there's a misunderstanding here - are you talking about `Oneable` (not `Onable`), which is not an internal trait an is defined in `math.cairo` ? https://github.com/starkware-libs/cairo/blob/8977d3b343752b333dbc98797e89f7abc5ed8442/corelib/src/math.cairo#L91-L101 

I think the `One` and `Zero` traits you're mentioning are actually `Oneable` and `Zeroable` - and the change in my PR is the implementation of `Oneable<felt252>`, similar to `Zeroable<felt252>` implemented here https://github.com/starkware-libs/cairo/blob/8977d3b343752b333dbc98797e89f7abc5ed8442/corelib/src/zeroable.cairo#L12-L24

2023-10-04 12:07 UTC, orizi reviewed
`Oneable` **is** an internal trait defined in math - it was added only for the implementation of `inv_mod` for secp.
We want to have other traits similar to rust for `One` and `Zero` - which would not be internal.
therefore i don't want to add addtional impls for traits i do not want to extend.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4037#-:-Nfu_2rM9G-uc2iZFioR:b-h26pyr)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enitrat)



<!-- Sent from Reviewable.io -->

2023-10-10 02:18 UTC, enitrat commented
Required changes have been applied. This PR now only implements the `deref_or` method on `Nullable`.

2023-10-10 08:59 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4037#-:-NgNnvBo87HzBrdJLsc0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enitrat)



<!-- Sent from Reviewable.io -->

2023-10-10 09:09 UTC, merged