Added anonymous impl.
starkware-libs/cairo pull request #4051
Opened 2023-09-11 13:46 UTC by orizi

2023-09-11 16:00 UTC, yuvalsw requested changes
> Reviewed 42 of 42 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4051)* status: all files reviewed, 22 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/math.cairo` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3_35NBrlJV9mFOQty:-Ne3_35NBrlJV9mFOQtz:bv11fs1) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/corelib/src/math.cairo#L55)):*
> ```Cairo
>     impl TZeroableImpl: Zeroable<T>,
>     impl TOneableImpl: Oneable<T>,
>     impl TTryIntoNonZeroImpl: TryInto<T, NonZero<T>>,
> ```

most here can be anon



_Code quote:_
```Cairo
    impl TAddImpl: Add<T>,
    impl TSubImpl: Sub<T>,
    impl TMulImpl: Mul<T>,
    impl TDivRemImpl: DivRem<T>,
    impl TZeroableImpl: Zeroable<T>,
    impl TOneableImpl: Oneable<T>,
    impl TTryIntoNonZeroImpl: TryInto<T, NonZero<T>>,
```
___
*[`corelib/src/starknet/secp256_trait.cairo` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3__1e2aovZUXW08y8:-Ne3__1e2aovZUXW08y9:bb7d4y9) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/corelib/src/starknet/secp256_trait.cairo#L53)):*
> ```Cairo
>     +Drop<Secp256Point>,
>     impl Secp256Impl: Secp256Trait<Secp256Point>,
>     impl Secp256PointImpl: Secp256PointTrait<Secp256Point>
> ```

anon
___
*[`corelib/src/starknet/secp256_trait.cairo` line 98 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3_kRA4lOLAuVJI13A:-Ne3_kRA4lOLAuVJI13B:b-q5siny) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/corelib/src/starknet/secp256_trait.cairo#L98)):*
> ```Cairo
>     +Drop<Secp256Point>,
>     impl Secp256Impl: Secp256Trait<Secp256Point>,
>     impl Secp256PointImpl: Secp256PointTrait<Secp256Point>
> ```

anons. Also below.



_Code quote:_
```Cairo
    impl Secp256Impl: Secp256Trait<Secp256Point>,
    impl Secp256PointImpl: Secp256PointTrait<Secp256Point>
```
___
*[`crates/cairo-lang-defs/src/ids.rs` line 523 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3epIv-_isE3TaqeCJ:-Ne3epIv-_isE3TaqeCK:b-28o7aq) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-defs/src/ids.rs#L523)):*
> ```XML
>         Some(name_green.identifier(db))
>     }
>     pub fn name_for_debug(&self, db: &dyn SyntaxGroup) -> SmolStr {
> ```

suggestion
+doc



_Suggestion:_
```XML
fn debug_name(&self,
```
___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3gNov9DQc5vflJ3q_:-Ne3gNov9DQc5vflJ3qa:b-5kzgmx) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-formatter/src/node_properties.rs#L48)):*
> ```XML
>                 if grandparent_kind(db, self) == Some(SyntaxKind::GenericParamImplAnonymous) =>
>             {
>                 true
> ```

I am missing something. there should be a space before the +, and this is also what I see in the cairo files...
___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3ggY073kl0JRs3o7e:-Ne3ggY073kl0JRs3o7f:b-rzayke) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-formatter/src/node_properties.rs#L108)):*
> ```XML
>                     grandparent_kind(db, self),
>                     Some(SyntaxKind::GenericParamImplAnonymous)
>                 ) =>
> ```

consistent with above.



_Suggestion:_
```XML
                if grandparent_kind(db, self) == Some(SyntaxKind::GenericParamImplAnonymous) =>
```
___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 432 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3hKeb2vvJZB-1iljA:-Ne3hKeb2vvJZB-1iljB:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-formatter/src/node_properties.rs#L432)):*
> ```XML
>                 }
>                 SyntaxKind::TerminalPlus
>                     if parent_kind(db, self) != Some(SyntaxKind::GenericParamImplAnonymous) =>
> ```





_Suggestion:_
```XML
 if grandparent_kind(db, self) != Some(Syn
```
___
*[`crates/cairo-lang-plugins/src/plugins/generate_trait.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3k_FH72JE_IE0JRcS:-Ne3k_FI3F4DYT8p9HtG:b-3316oz) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-plugins/src/plugins/generate_trait.rs#L108)):*
> ```XML
>                             .map(|name| name.text(db))
>                             .unwrap_or_else(|| "_".into());
>                         trait_generic_arg_name.text(db) == impl_generic_param_name
> ```

Can you please add an example of generate_trait with an anon impl generic param?
___
*[`crates/cairo-lang-plugins/src/plugins/derive/mod.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3mCtf8WC6dAesvhtv:-Ne3mCtf8WC6dAesvhtw:b-octfoo) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-plugins/src/plugins/derive/mod.rs#L90)):*
> ```XML
>         if let OptionWrappedGenericParamList::WrappedGenericParamList(gens) = generic_params {
>             for param in gens.generic_params(db).elements(db) {
>                 ordered.push(param.name(db).map(|n| n.text(db)).unwrap_or_else(|| "_".into()));
> ```

you do this at least twice for ast::GenericParam. Consider adding a .name() or .debug_name() that returns a string.



_Code quote:_
```XML
param.name(db).map(|n| n.text(db)).unwrap_or_else(|| "_".into()
```
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3wya-8lIbnGK3MAqP:-Ne3wya-8lIbnGK3MAqQ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-semantic/src/items/generics.rs#L309)):*
> ```XML
>             panic!("generic_impl_param_trait() called on a non impl generic param.")
>         }
>     };
> ```





_Suggestion:_
```XML
    let trait_path_syntax = generic_param_syntax.trait_path(syntax_db).expect("generic_impl_param_trait() called on a non impl generic param.");
```
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 388 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3xXTg5p19QKhHBPg_:-Ne3xXTg5p19QKhHBPga:b-wr5xms) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-semantic/src/items/generics.rs#L388)):*
> ```XML
>             let path_syntax = syntax.trait_path(db.upcast());
>             impl_generic_param_semantic(resolver, diagnostics, path_syntax, id)
>         }
> ```

consider uniting



_Suggestion:_
```XML
        ast::GenericParam::ImplNamed(syntax) | ast::GenericParam::ImplAnonymous(syntax) => {
            let path_syntax = param_syntax.trait_path(db.upcast()).unwrap();
            impl_generic_param_semantic(resolver, diagnostics, path_syntax, id)
        }
```
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 395 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3xwb35xgwxB-98EZ4:-Ne3xwb35xgwxB-98EZ5:b-brk7az) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-semantic/src/items/generics.rs#L395)):*
> ```XML
> fn impl_generic_param_semantic(
>     resolver: &mut Resolver<'_>,
>     diagnostics: &mut SemanticDiagnostics,
> ```

diagnostics is usually first (if not db)
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 396 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3y5FZ9JtQPyvKmxz6:- [...]

2023-09-11 18:57 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4051)* status: all files reviewed, 21 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`corelib/src/math.cairo` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3_35NBrlJV9mFOQty:-Ne4QyM-8vABPE1V0xvc:b9m5fhi) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/corelib/src/math.cairo#L55)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

most here can be anon
</blockquote></details>

i know it can be done - but i don't want to do it all in one PR - changing the simple ones i knew was not going to be called directly was enough for the  proof of concept.
___
*[`crates/cairo-lang-defs/src/ids.rs` line 523 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3epIv-_isE3TaqeCJ:-Ne4U0O81PkNp6WNklgp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-defs/src/ids.rs#L523)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

suggestion
+doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3gNov9DQc5vflJ3q_:-Ne4RDjWAiV2KBxBnsTp:bsjr059) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-formatter/src/node_properties.rs#L48)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I am missing something. there should be a space before the +, and this is also what I see in the cairo files...
</blockquote></details>

the formatter adds a space because of the breakpoint due to the , - + would cause another space.
___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3ggY073kl0JRs3o7e:-Ne4TPBB3x31IglKgVum:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-formatter/src/node_properties.rs#L108)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

consistent with above.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 432 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3hKeb2vvJZB-1iljA:-Ne4RRnTDxlFuB8CC0Xr:b-uf9or5) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-formatter/src/node_properties.rs#L432)):*
> ```XML
>                 }
>                 SyntaxKind::TerminalPlus
>                     if parent_kind(db, self) != Some(SyntaxKind::GenericParamImplAnonymous) =>
> ```

everything around this point is Terminal based.
gil will make this more aligned  -but current impl is the correct one.
___
*[`crates/cairo-lang-plugins/src/plugins/generate_trait.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3k_FH72JE_IE0JRcS:-Ne4U25Z4vJ3Bso-F0JO:bnez9ej) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-plugins/src/plugins/generate_trait.rs#L108)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can you please add an example of generate_trait with an anon impl generic param?
</blockquote></details>

reverted this - way more complex.
___
*[`crates/cairo-lang-plugins/src/plugins/derive/mod.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3mCtf8WC6dAesvhtv:-Ne4U7ASBRFpSHopGRSt:bjkz6iw) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-plugins/src/plugins/derive/mod.rs#L90)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

you do this at least twice for ast::GenericParam. Consider adding a .name() or .debug_name() that returns a string.
</blockquote></details>

i do this only twice - once as a rewritenode, and once as a string.
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3wya-8lIbnGK3MAqP:-Ne4UWCv08994xBoGstX:bfmfw4o) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-semantic/src/items/generics.rs#L309)):*
> ```XML
>             panic!("generic_impl_param_trait() called on a non impl generic param.")
>         }
>     };
> ```

i don't want to unite this for the general case - i'm ok with uniting it just for starknet.
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 388 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3xXTg5p19QKhHBPg_:-Ne4UPu_7eYhKFsfNdPd:b-xci9qk) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-semantic/src/items/generics.rs#L388)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

consider uniting
</blockquote></details>

different types - can't work.
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 395 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3xwb35xgwxB-98EZ4:-Ne4Ufl88tVn1NeaNI7H:bl2jkw) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-semantic/src/items/generics.rs#L395)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

diagnostics is usually first (if not db)
</blockquote></details>

matched ordering of the caller function - if we should change - this is a larger change.
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 396 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3y5FZ9JtQPyvKmxz6:-Ne4V1ea9fsTbg73NVSJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-semantic/src/items/generics.rs#L396)):*
> ```XML
>     resolver: &mut Resolver<'_>,
>     diagnostics: &mut SemanticDiagnostics,
>     path_syntax: ast::ExprPath,
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 853 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3o6BT589FqC8LWnXq:-Ne4VT4qBuqmVTJFAAik:b-ifbbub) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-semantic/src/resolve/mod.rs#L853)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

can you add a test for this case?
I don't think this can happen as for it to happen it has to be first added by name, which it doesn't have.
If this is true, maybe this should just be an unwrap.
If there is such a case that I miss, I would like to see how the diagnostics looks like.
</blockquote></details>

yes - this obviously can't happen - this is the ordered arguments part.
removing this entirely.
___
*[`crates/cairo-lang-starknet/src/plugin/embeddable.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3s6uCEd9LNxJQwwEU:-Ne4ajBe7Zx2ADLXpqoH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-starknet/src/plugin/embeddable.rs#L70)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

is there a test of embeddable with anon impl generic param?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/utils.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3p_jU3_3nWFAbVxTu:-Ne4XbZ7BqdMo69GiZAT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-starknet/src/plugin/utils.rs#L94)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

complete sentence.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starkn [...]

2023-09-12 07:27 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4051)* status: 33 of 42 files reviewed, 21 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`corelib/src/math.cairo` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3_35NBrlJV9mFOQty:-Ne7HCDH9woi8BkASKxB:be3z41h) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/corelib/src/math.cairo#L55)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i know it can be done - but i don't want to do it all in one PR - changing the simple ones i knew was not going to be called directly was enough for the  proof of concept.
</blockquote></details>

at following PR.
___
*[`corelib/src/starknet/secp256_trait.cairo` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3__1e2aovZUXW08y8:-Ne7HFfD2j2_OPwsAbJy:be3z41h) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/corelib/src/starknet/secp256_trait.cairo#L53)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

anon
</blockquote></details>

at following PR.
___
*[`corelib/src/starknet/secp256_trait.cairo` line 98 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3_kRA4lOLAuVJI13A:-Ne7HHhjEaao1uc4kctJ:be3z41h) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/corelib/src/starknet/secp256_trait.cairo#L98)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

anons. Also below.
</blockquote></details>

at following PR.
___
*[`tests/bug_samples/issue3119.cairo` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3bL-Y9pEzoDXqMdv-:-Ne7HKS39VGm65OzRP9n:be3z41h) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/tests/bug_samples/issue3119.cairo#L2)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

anons
</blockquote></details>

at following PR.


<!-- Sent from Reviewable.io -->

2023-09-12 07:28 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4051)* status: 33 of 42 files reviewed, 21 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`tests/bug_samples/issue2995.cairo` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3bEqa25jPg7zemWXh:-Ne7Hdj7DQ2vqtagV7pu:be3z41h) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/tests/bug_samples/issue2995.cairo#L8)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

anon
</blockquote></details>

at following PR.


<!-- Sent from Reviewable.io -->

2023-09-12 09:12 UTC, yuvalsw requested changes
> Reviewed 8 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4051)* status: all files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3gNov9DQc5vflJ3q_:-Ne7V_7130eILW39-bS7:b7q1iuz) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-formatter/src/node_properties.rs#L48)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the formatter adds a space because of the breakpoint due to the , - + would cause another space.
</blockquote></details>

Talked with Gil. OK for now, may need to change later.
___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 432 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3hKeb2vvJZB-1iljA:-Ne7Y7ENCGYKbnEI537m:b-krcfjh) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-formatter/src/node_properties.rs#L432)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

everything around this point is Terminal based.
gil will make this more aligned  -but current impl is the correct one.
</blockquote></details>

Sorry, the problem is in the previous one, not here. GenericParamImplAnonymous is the parent and not the grandparent of +.
___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 46 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne7Y0qm-ceCWui01R2W:-Ne7Y0qm-ceCWui01R2X:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8fbf2f7ddf7575ca471c7e00d7860e00c774b598/crates/cairo-lang-formatter/src/node_properties.rs#L46)):*
> ```XML
>             }
>             SyntaxKind::TokenPlus
>                 if grandparent_kind(db, self) == Some(SyntaxKind::GenericParamImplAnonymous) =>
> ```





_Suggestion:_
```XML
if parent_kind(db, self) == 
```
___
*[`crates/cairo-lang-plugins/src/plugins/generate_trait.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne7ZT4L2811FeERdbmx:-Ne7ZT4L2811FeERdbmy:b-vfdjvi) ([raw file](https://github.com/starkware-libs/cairo/blob/8fbf2f7ddf7575ca471c7e00d7860e00c774b598/crates/cairo-lang-plugins/src/plugins/generate_trait.rs#L109)):*
> ```XML
>                             ast::GenericParam::Const(param) => param.name(db),
>                             ast::GenericParam::ImplNamed(param) => param.name(db),
>                             ast::GenericParam::ImplAnonymous(_) => return false,
> ```

this would add diagnostic: "Generated trait must have generic args matching the impl's generic params.".
need some other diag like "generate_trait does not support anonymous impl generic params"



_Code quote:_
```XML
return false,
```
___
*[`crates/cairo-lang-plugins/src/plugins/generate_trait.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne7Zqz0EQlSXPS8g0fr:-Ne7Zqz0EQlSXPS8g0fs:b-3qnc53) ([raw file](https://github.com/starkware-libs/cairo/blob/8fbf2f7ddf7575ca471c7e00d7860e00c774b598/crates/cairo-lang-plugins/src/plugins/generate_trait.rs#L110)):*
> ```XML
>                             ast::GenericParam::ImplNamed(param) => param.name(db),
>                             ast::GenericParam::ImplAnonymous(_) => return false,
>                         };
> ```

suggestion



_Suggestion:_
```XML
                        if matches!(impl_generic_param, ast::GenericParam::ImplAnonymous(_)) {return false;}
                        let impl_generic_param_name = impl_generic_param.name(db).unwrap();
                        };
```
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3wya-8lIbnGK3MAqP:-Ne7aDja9vX6c0zWqWeB:bda21kt) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-semantic/src/items/generics.rs#L309)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't want to unite this for the general case - i'm ok with uniting it just for starknet.
</blockquote></details>

not sure how starknet is related. You added a trait_path method that does exactly this match, so you can use it.
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 388 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3xXTg5p19QKhHBPg_:-Ne7aWlh0-zu72SBZ2k3:b-i10h1a) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-semantic/src/items/generics.rs#L388)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

different types - can't work.
</blockquote></details>

it can. just change `syntax` in my suggestion to `_`. Note I am using param_syntax in the arm body.
___
*[`crates/cairo-lang-starknet/src/plugin/embeddable.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3s6uCEd9LNxJQwwEU:-Ne7eUahCeMEY0Y-kryt:b-irwhab) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-starknet/src/plugin/embeddable.rs#L70)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

where?
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/generics.adoc` line 100 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3auBj6ceK8SVD-DFd:-Ne7eJPl1vlGdeIJbhoz:b8ewz07) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/docs/reference/src/components/cairo/modules/language_constructs/pages/generics.adoc#L100)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is already related to the previous paragraph as well - concrete suggestions?
</blockquote></details>

added in a separate comment.
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/generics.adoc` line 115 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne7cEYA2nAa-_SFizRI:-Ne7cEYA2nAa-_SFizRJ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8fbf2f7ddf7575ca471c7e00d7860e00c774b598/docs/reference/src/components/cairo/modules/language_constructs/pages/generics.adoc#L115)):*
> ```AsciiDoc
> ----
> 
> === Const Generic Parameters
> ```





_Suggestion:_
```AsciiDoc
Even if the impl generic parameter name is not used in the item body,
the fact that it was specified as a generic parameter can be used to apply
some restrictions to the generic types used by the item.
For example, `foo` from the above example can't have a concrete form in which `T` is `u128`
as there is no impl of `MulTrait` for `u128`.

In this case, you can also use anonymous impl generic parameters:
[source,rust]
----
fn foo<T, +MyTrait<T>>(x: T) -> T {
    MyTrait::mul(x)
}
----

Note that in many cases generic arguments can be inferred and thus can be omitted from the
use of the item.

=== Const Generic Parameters
```


<!-- Sent from Reviewable.io -->

2023-09-12 09:44 UTC, gilbens-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 30 of 42 files at r1, 8 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4051#-:-Ne7lktyBggtP9I35070:bnfp4nl)* status: all files reviewed, 10 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3gNov9DQc5vflJ3q_:-Ne7HN6V2IOXy8_XRDYB:b-m6ijb1) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-formatter/src/node_properties.rs#L48)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the formatter adds a space because of the breakpoint due to the , - + would cause another space.
</blockquote></details>

And there shouldn't be a space if it's the first element in the list.
___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 432 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3hKeb2vvJZB-1iljA:-Ne7lWo82EUn41GELfaA:b-n30wma) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-formatter/src/node_properties.rs#L432)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Sorry, the problem is in the previous one, not here. GenericParamImplAnonymous is the parent and not the grandparent of +.
</blockquote></details>

It's the parent of the terminal, grandparent of the token.


<!-- Sent from Reviewable.io -->

2023-09-12 10:02 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4051)* status: all files reviewed, 6 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-formatter/src/node_properties.rs` line 46 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne7Y0qm-ceCWui01R2W:-Ne7lZG_-MHMcQiSX8N0:b-ik6321) ([raw file](https://github.com/starkware-libs/cairo/blob/8fbf2f7ddf7575ca471c7e00d7860e00c774b598/crates/cairo-lang-formatter/src/node_properties.rs#L46)):*
> ```XML
>             }
>             SyntaxKind::TokenPlus
>                 if grandparent_kind(db, self) == Some(SyntaxKind::GenericParamImplAnonymous) =>
> ```

needs to be the grandparent.
___
*[`crates/cairo-lang-plugins/src/plugins/generate_trait.rs` line 109 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne7ZT4L2811FeERdbmx:-Ne7mntD-gVb9RDKdWJs:b88zcpv) ([raw file](https://github.com/starkware-libs/cairo/blob/8fbf2f7ddf7575ca471c7e00d7860e00c774b598/crates/cairo-lang-plugins/src/plugins/generate_trait.rs#L109)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

this would add diagnostic: "Generated trait must have generic args matching the impl's generic params.".
need some other diag like "generate_trait does not support anonymous impl generic params"
</blockquote></details>

but it already does not match.
added a todo for general support.
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3wya-8lIbnGK3MAqP:-Ne7nb9o9fN3_oTmmZ9z:bppqdez) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-semantic/src/items/generics.rs#L309)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

not sure how starknet is related. You added a trait_path method that does exactly this match, so you can use it.
</blockquote></details>

it was only in the starknet plugin utils.
___
*[`crates/cairo-lang-semantic/src/items/generics.rs` line 388 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3xXTg5p19QKhHBPg_:-Ne7nedjAOZWE2Hq7fuX:b-v2sq8l) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-semantic/src/items/generics.rs#L388)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

it can. just change `syntax` in my suggestion to `_`. Note I am using param_syntax in the arm body.
</blockquote></details>

again only in the starknet plugin context.
___
*[`crates/cairo-lang-starknet/src/plugin/embeddable.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne3s6uCEd9LNxJQwwEU:-Ne7oYNc-WJ_Pnw0Vd--:blxh2tw) ([raw file](https://github.com/starkware-libs/cairo/blob/e55209565654bea0c3bf51cf4bf4bb7c640fa202/crates/cairo-lang-starknet/src/plugin/embeddable.rs#L70)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

where?
</blockquote></details>

test_contract.cairo
___
*[`docs/reference/src/components/cairo/modules/language_constructs/pages/generics.adoc` line 115 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4051#-Ne7cEYA2nAa-_SFizRI:-Ne7p00rBimaJGyTrmkO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8fbf2f7ddf7575ca471c7e00d7860e00c774b598/docs/reference/src/components/cairo/modules/language_constructs/pages/generics.adoc#L115)):*
> ```AsciiDoc
> ----
> 
> === Const Generic Parameters
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-09-12 15:31 UTC, yuvalsw approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4051#-:-Ne909C35Aou0hr3MwdO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2023-09-12 15:44 UTC, merged