Changed bytes31 casts to use libfunc upcast.
starkware-libs/cairo pull request #4098
Opened 2023-09-20 07:40 UTC by orizi

Changes the `upcast` libfunc which is already allowed. #should_audit

2023-10-01 11:26 UTC, liorgold2 requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4098)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @orizi and @yuvalsw)

___
*[`tests/e2e_test_data/libfuncs/bytes31` line 155 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4098#-NfezE5LC2gA0inzaIVr:-NfezE5LC2gA0inzaIVs:bh33jos) ([raw file](https://github.com/starkware-libs/cairo/blob/3720f758906bc86da68b633906fae3584b4e0c79/tests/e2e_test_data/libfuncs/bytes31#L155)):*
> ```
> //! > ==========================================================================
> 
> //! > upcast<u8, bytes31>
> ```

I think one is enough.


<!-- Sent from Reviewable.io -->

2023-10-01 11:26 UTC, liorgold2 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4098)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-10-01 13:30 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4098)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @liorgold2 and @yuvalsw)

___
*[`tests/e2e_test_data/libfuncs/bytes31` line 155 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4098#-NfezE5LC2gA0inzaIVr:-NffQnML9mLb_t8pQGmG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3720f758906bc86da68b633906fae3584b4e0c79/tests/e2e_test_data/libfuncs/bytes31#L155)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I think one is enough.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-01 21:05 UTC, liorgold2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4098#-:-Nfh2qCOAX3LQBAIj2WX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-10-02 14:15 UTC, liorgold2 approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4098)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-10-10 09:36 UTC, merged