Add dep_component! macros.
starkware-libs/cairo pull request #4271
Opened 2023-10-17 13:12 UTC by gilbens-starkware

2023-10-17 13:25 UTC, orizi requested changes
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4271)* status: 14 of 16 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/inline_macros/mod.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgxllT72R790vpiY8Ix:-NgxllT72R790vpiY8Iy:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/07ceaed0e9db2f32e69b5fc1b4b5cd6f45c9f1cb/crates/cairo-lang-semantic/src/inline_macros/mod.rs#L52)):*
> ```XML
> }
> 
> pub fn try_extract_unnamed_arg(db: &dyn SyntaxGroup, arg_ast: &ast::Arg) -> Option<ast::Expr> {
> ```

doc
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgxlrC4EsU0G9XZZzgm:-NgxlrC4EsU0G9XZZzgn:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/07ceaed0e9db2f32e69b5fc1b4b5cd6f45c9f1cb/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L40)):*
> ```XML
> }
> 
> fn dep_component_generate_code_helper(
> ```

doc
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgxlwIDEsdEO-VWHzXo:-NgxlwIDEsdEO-VWHzXp:b32wk0) ([raw file](https://github.com/starkware-libs/cairo/blob/07ceaed0e9db2f32e69b5fc1b4b5cd6f45c9f1cb/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L66)):*
> ```XML
>         (try_extract_unnamed_arg(db, contract_arg), try_extract_unnamed_arg(db, component_arg))
>     else {
>         todo!();
> ```

do
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Ngxm8UwCxYpeIzPnMck:-Ngxm8UwCxYpeIzPnMcl:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/07ceaed0e9db2f32e69b5fc1b4b5cd6f45c9f1cb/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L99)):*
> ```XML
>         ]
>         .into(),
>     ));
> ```





_Suggestion:_
```XML
    let let_part = if is_mut { "let mut" } else { "let" };
    let maybe_mut = if is_mut { "_mut" } else { "" };
    let maybe_ref = if is_mut { "ref " } else { "" };
    builder.add_modified(RewriteNode::interpolate_patched(&format!(
        "
            {{
                {let_part} __get_dep_component_macro_temp_contract__ = \
         HasComponent::get_contract{maybe_mut}({maybe_ref}$contract_path$);
                $component_path$::HasComponent::get_component{maybe_mut}({maybe_ref}\
         __get_dep_component_macro_temp_contract__)
            }}
            "),
        &[
            ("contract_path".to_string(), RewriteNode::new_trimmed(contract_path.as_syntax_node())),
            (
                "component_path".to_string(),
                RewriteNode::new_trimmed(component_path.as_syntax_node()),
            ),
        ]
        .into(),
    ));
```


<!-- Sent from Reviewable.io -->

2023-10-17 13:45 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4271#-:-NgxsTT736qxHUtcB37E:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2023-10-17 16:47 UTC, yuvalsw requested changes
> Reviewed 4 of 16 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4271)* status: all files reviewed, 17 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/inline_macros/mod.rs` line 52 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyOCwy5I1G01N1pMS2:-NgyOCwz0tOQU66gqumg:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-semantic/src/inline_macros/mod.rs#L52)):*
> ```XML
> }
> 
> /// Gets the syntax of an argument, and extracting the value if it is unnamed.
> ```





_Suggestion:_
```XML
 argument, and extracs the value 
```
___
*[`crates/cairo-lang-starknet/cairo_level_tests/components/mintable.cairo` line 29 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyOVrA9poPNLKOrhY8:-NgyOVrA9poPNLKOrhY9:bq7v4u6) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/cairo_level_tests/components/mintable.cairo#L29)):*
> ```Cairo
>             assert(!account.is_zero(), 'ERC20: mint to the 0 address');
>             dep_component!(self, ownable_comp).validate_ownership();
>             let mut erc20_component = dep_component_mut!(self, erc20_comp);
> ```

should we enforce `ref` here like in arguments to function calls?



_Code quote:_
```Cairo
(self
```
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyP27a7Csqa9pN6xDs:-NgyP27a7Csqa9pN6xDt:b2ni2nk) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L9)):*
> ```XML
> use cairo_lang_syntax::node::{ast, TypedSyntaxNode};
> 
> /// Macro for expanding a selector to a string literal.
> ```

fix
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 25 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyPG5UENJMvODbaIJL:-NgyPG5UENJMvODbaIJM:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L25)):*
> ```XML
> }
> 
> #[derive(Debug, Default)]
> ```

doc
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyPHoP3iWMh_YxJADm:-NgyPHoP3iWMh_YxJADn:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L40)):*
> ```XML
> }
> 
> /// An helper function for the code generation of both `DepComponentMacro` and
> ```





_Suggestion:_
```XML
 A helper function fo
```
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 50 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyPcaF73Kxx5ze7CJn:-NgyPcaF73Kxx5ze7CJo:b-7jpcs9) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L50)):*
> ```XML
>         args.args(db)
>     } else {
>         return unsupported_bracket_diagnostic(db, syntax);
> ```

in a separate PR - but this should say what types are supported.



_Code quote:_
```XML
unsupported_bracket_diagnostic
```
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 58 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyPo5s67YzegkJU4N9:-NgyPo5s67YzegkJU4NA:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L58)):*
> ```XML
>             stable_ptr: syntax.stable_ptr().untyped(),
>             message: format!(
>                 "`{}` macro must have exactly two unnamed argument.",
> ```





_Suggestion:_
```XML
two unnamed arguments.",
```
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 65 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyQzs2255Tz7imv0-n:-NgyQzs2255Tz7imv0-o:b-xoudoe) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L65)):*
> ```XML
>     };
> 
>     let (Some(contract_path), Some(component_path)) =
> ```

suggest to rename to `component_module_arg`



_Code quote:_
```XML
component_path
```
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 71 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyPzF13F3Q2Dax6kUY:-NgyPzF13F3Q2Dax6kUZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L71)):*
> ```XML
>             stable_ptr: syntax.stable_ptr().untyped(),
>             message: format!(
>                 "`{}` macro must have exactly two unnamed argument.",
> ```





_Suggestion:_
```XML
`{}` macro arguments must be unnamed
```
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyQPixAv7MLThXhAua:-NgyQPixAv7MLThXhAub:b7w49sh) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L76)):*
> ```XML
>         }];
>         return InlinePluginResult { code: None, diagnostics };
>     };
> ```

then below use contract_arg.value(db), component_arg.value(db)



_Suggestion:_
```XML
    let [ast::ArgClause::Unnamed(contract_arg), ast::ArgClause::Unnamed(component_arg)] = arguments.as_slice() else {
        let diagnostics = vec![PluginDiagnostic {
            stable_ptr: syntax.stable_ptr().untyped(),
            message: format!(
                "`{}` macro must have exactly two unnamed arguments.",
                if is_mut { DepComponentMutMacro::NAME } else { DepComponentMacro::NAME }
            ),
        }];
        return InlinePluginResult { code: None, diagnostics };
    };
```
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyRE22CNQ0MWU7iFFk:-NgyRE22CNQ0MWU7iFFl:b2ojf19) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L82)):*
> ```XML
>     let maybe_mut = if is_mut { "_mut" } else { "" };
>     let maybe_ref1 = if is_mut { "ref " } else { "@" };
>     let maybe_ref2 = if is_mut { "ref " } else { "" };
> ```

Plus better names for maybe_ref1, maybe_ref2.

Another option (may be also clearer) is to have the whole text constant for each one of the options.
For the non mut variant, it will also let you write it in a single line, avoiding defining a variable that pollutes the scope.



_Suggestion:_
```XML
    let (let_part, maybe_mut, maybe_ref1, maybe_ref2) = if is_mut { 9"let mut", "_mut", "ref ", "ref ") } else { ("let", "", "@", "") };
```
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 90 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyTWerERCD0OZr3vMQ:-NgyTWerERCD0OZr3vMR:b9w3hha) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L90)):*
> ```XML
>          HasComponent::get_contract{maybe_mut}({maybe_ref1}$contract_path$);
>                 $component_path$::HasComponent::get_component{maybe_mut}({maybe_ref2}\
>          __get_dep_component_macro_temp_contract__)
> ```

Prefer to be as explicit as possible in generated code, unless it causes trouble. In this c [...]

2023-10-18 10:32 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4271)* status: 18 of 21 files reviewed, 10 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/inline_macros/mod.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgxllT72R790vpiY8Ix:-Ngxs0z76hGpiF66N928:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/07ceaed0e9db2f32e69b5fc1b4b5cd6f45c9f1cb/crates/cairo-lang-semantic/src/inline_macros/mod.rs#L52)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/components/mintable.cairo` line 29 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyOVrA9poPNLKOrhY8:-Nh119p01RDqPrEKuCUR:b-b5ngu8) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/cairo_level_tests/components/mintable.cairo#L29)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

should we enforce `ref` here like in arguments to function calls?
</blockquote></details>

On the one hand, yes, it is similar to a function call.
On the other hand, it kind of beats the purpose of a macro being a shortcut.
Sent it in compiler dev.
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgxlrC4EsU0G9XZZzgm:-Ngxrf45ACOk2v8FbYQA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/07ceaed0e9db2f32e69b5fc1b4b5cd6f45c9f1cb/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L40)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgxlwIDEsdEO-VWHzXo:-NgxregI6i0H4ACp8Obg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/07ceaed0e9db2f32e69b5fc1b4b5cd6f45c9f1cb/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L66)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Ngxm8UwCxYpeIzPnMck:-NgxreK-4bfMl8IelGBc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/07ceaed0e9db2f32e69b5fc1b4b5cd6f45c9f1cb/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L99)):*
> ```XML
>         ]
>         .into(),
>     ));
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyP27a7Csqa9pN6xDs:-Nh10Xpq7LVsIDkyt8o1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L9)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

fix
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 25 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyPG5UENJMvODbaIJL:-Nh10YmI7TNsUvbA1_oB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L25)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyQPixAv7MLThXhAua:-Nh0uD3-0-PpS2zoShVq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L76)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

then below use contract_arg.value(db), component_arg.value(db)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 90 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyTWerERCD0OZr3vMQ:-Nh0vTWN38gbStvC4N4l:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L90)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Prefer to be as explicit as possible in generated code, unless it causes trouble. In this case, to avoid conflicts in the case someone decides to try something weird with HasComponent trait.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 105 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyTfEP7H_OykRr4B7c:-Nh0vbF86sYDKfEInLOU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L105)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

not always mut...
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 5677 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyWrOHEUeW7xq5rR4k:-Nh0wGJ97eYtHuSFt-Sz:b3461tv) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L5677)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I don't find the expansions below - maybe it doesn't expand inline macros?
</blockquote></details>

It doesn't, similar to the `selector!`macro.
Maybe it should be changed but not in this pr.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 5683 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyVDnV6QELnIQIdUVn:-Nh0wZzyDsVba7VW34a0:bzdm75x) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L5683)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

is it easy to remove the "or constant"?
</blockquote></details>

Easy yes, but it will remove it from everywhere else. It's raised from `resolve_expr_path`.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 5688 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyVMth30lzI8CmDS_q:-Nh0yY7v016aWs21qGpi:b-a0v4ic) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L5688)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

this is not a good error. Try to improve it if possible.
</blockquote></details>

It's not the `self` that is not found, it's the identifier in the generated code. That'a an inherent problem with mapping diagnostics from generated code. Maybe we should extend the diagnostics mappings to not only map locations but also map diagnostic kinds. 
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 5711 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyVovM6xOaSp_nbB2x:-Nh1-P_eBoXxORaIz2Pa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L5711)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

error pointing to generated code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-18 10:53 UTC, orizi reviewed
> Reviewed 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4271)* status: 19 of 21 files reviewed, 10 unresolved discussions (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-10-18 12:36 UTC, yuvalsw commented
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 5677 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyWrOHEUeW7xq5rR4k:-Nh1m4yPETUYYo9Xab8p:bc0aljw) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L5677)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

It doesn't, similar to the `selector!`macro.
Maybe it should be changed but not in this pr.
</blockquote></details>

OK, please add a TODO and do it soon, as otherwise this test doesn't have much merit (or at least the valid `dep_component!` call).


<!-- Sent from Reviewable.io -->

2023-10-18 12:42 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4271)* status: 16 of 21 files reviewed, 10 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 5677 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyWrOHEUeW7xq5rR4k:-Nh1nnfm2kPY1JxHwysD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L5677)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

OK, please add a TODO and do it soon, as otherwise this test doesn't have much merit (or at least the valid `dep_component!` call).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-18 20:51 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4271)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 73 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Nh1pXbG4jClUg9UKpS5:-Nh3YMIlBx1MY_3jkSOR:b-ws78lc) ([raw file](https://github.com/starkware-libs/cairo/blob/2090bebfd303904ad5bd7685be16884e69fcc4eb/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L73)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

use `compute_mutability` (need to move it from semantic), to also avoid invalid combinations like "ref ref"/"ref mut mut ref".
</blockquote></details>

Where do you suggest to move it to? It's semantic data.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 5711 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyVovM6xOaSp_nbB2x:-Nh1qgsI1klGV2loG8XO:b-pcrm5d) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L5711)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Let's also add `: ContractState` or `: @ContractState` in the generated code - again, to be more explicit. Maybe it will eliminate this error or would make it clearer.
</blockquote></details>

I can add it, but the TContractState state already eliminated the error.


<!-- Sent from Reviewable.io -->

2023-10-19 07:52 UTC, yuvalsw requested changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4271)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 73 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Nh1pXbG4jClUg9UKpS5:-Nh5sMaT5BLX1-tB1rIP:bmzc6qe) ([raw file](https://github.com/starkware-libs/cairo/blob/2090bebfd303904ad5bd7685be16884e69fcc4eb/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L73)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Where do you suggest to move it to? It's semantic data.
</blockquote></details>

Ah, NM, then maybe just assert there is only 1?
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 5688 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyVMth30lzI8CmDS_q:-Nh5tTXM3KLZIvhXS0PO:bl7508y) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L5688)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't think there is - but this isnt too bad since this still points to the actual issue - which *is* that this isn't a valid identifier.
</blockquote></details>

`self` is a valid identifier... the generated code is `self::HasComponent::<TContractState>::get_component` in which HasComponent is not valid and this is linked to the original code `self`.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 5711 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyVovM6xOaSp_nbB2x:-Nh5uUS89VWJL5RVyjxx:b-4xfuei) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L5711)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

I can add it, but the TContractState state already eliminated the error.
</blockquote></details>

ah, good news. IMO still add it. Let's make the inference work less which, if doesn't increase consistency, definitely doesn't reduce it. Less chance to discover change of behavior in the future for which we might have to break something to fix. (this is a general thing about generated code - be as explicit as possible).


<!-- Sent from Reviewable.io -->

2023-10-19 09:07 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4271)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 5688 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyVMth30lzI8CmDS_q:-Nh6AbtJ-0z4E6fdOWM2:b35vvc) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L5688)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

`self` is a valid identifier... the generated code is `self::HasComponent::<TContractState>::get_component` in which HasComponent is not valid and this is linked to the original code `self`.
</blockquote></details>

Thought you were talking about the previous diag.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 5711 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyVovM6xOaSp_nbB2x:-Nh6AmmG5dvGYCokb3WA:blufvfh) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L5711)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

ah, good news. IMO still add it. Let's make the inference work less which, if doesn't increase consistency, definitely doesn't reduce it. Less chance to discover change of behavior in the future for which we might have to break something to fix. (this is a general thing about generated code - be as explicit as possible).
</blockquote></details>

It means it will assume the name of the generic argument.
If we don't have to, I'd rather not have it. (Especially since the error on that case will point to generated code)


<!-- Sent from Reviewable.io -->

2023-10-19 09:32 UTC, yuvalsw commented
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 5711 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyVovM6xOaSp_nbB2x:-Nh6DrH-52f7U4tzw1UH:bhhvdna) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L5711)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

That's a good point, I won't add it for now.
</blockquote></details>

Arghh that's right. I thought we verify the name is TContractState. This is true for embeddable_as but not for other impls, or free functions.
This also means we need to remove the `::<TContractState>` in HasComponent that eliminated this error :/

It takes me back to the option of having the name of the impl in the inline macro, and not the name of the component module. `HasComponent::<TContractState>` was the second best option after using the impl name. But because we didn't have it, I settled for it. As we see we can't really do it, and we wouldn't want a third parameter in the macro, I bring back this option to the table. Maybe it's good anyway to have more clarity/explicitness in this case which is not very common and might be confusing?

Now thinking about it, another argument for having the impl name and not the module name:
If one uses a module name for which we don't have an impl in context, there would probably be a strange error. If they use an impl name that doesn't exist, it would probably say (correctly) "Identifier not found".

WDYT?

(anyway probably worth checking this errors with the simplest usecase possible, in the expand tests)


<!-- Sent from Reviewable.io -->

2023-10-19 09:55 UTC, yuvalsw requested changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4271)* status: all files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 74 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Nh6LfiuCI1XmXetIwhD:-Nh6LfiuCI1XmXetIwhE:bgiafa3) ([raw file](https://github.com/starkware-libs/cairo/blob/662ceeff4697a5fbc728684750c9d36194a257f7/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L74)):*
> ```XML
>         } else {
>             let diagnostics = vec![PluginDiagnostic {
>                 stable_ptr: contract_arg.stable_ptr().untyped(),
> ```

1. I see you changed here but for some reason the diag still points to the whole expr (maybe this is what's pointed by the patch?
2. If we can point to something partial - better to point specifically to the modifiers.
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 82 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Nh6JPc2---4LOGHBLxp:-Nh6JPc2---4LOGHBLxq:b-2rtjld) ([raw file](https://github.com/starkware-libs/cairo/blob/662ceeff4697a5fbc728684750c9d36194a257f7/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L82)):*
> ```XML
>             return InlinePluginResult { code: None, diagnostics };
>         }
>     }
> ```

I think this should work (maybe need minor & fixes)



_Suggestion:_
```XML
    if is_mut {
        // Verify the first element has  only a `ref` modifier.
        let contract_arg_modifiers = macro_args.elements(db)[0].modifiers(db).elements(db);
        if !matches!(&contract_arg_modifiers[..], &[ast::Modifier::Ref(_)])
            let diagnostics = vec![PluginDiagnostic {
                stable_ptr: contract_arg.stable_ptr().untyped(),
                message: format!(
                    "The first argument of `{}` macro must have only a `ref` modifier.",
                    DepComponentMutMacro::NAME
                ),
            }];
            return InlinePluginResult { code: None, diagnostics };
        }
    }
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 6393 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Nh6L-M_734bpRWUcMo5:-Nh6L-M_734bpRWUcMo6:be187dd) ([raw file](https://github.com/starkware-libs/cairo/blob/662ceeff4697a5fbc728684750c9d36194a257f7/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L6393)):*
> ```
>             ^*************************************************^
> 
> error: Inline macro `dep_component_mut` failed.
> ```

probably also out of scope of this PR, but I think this diag is not necessary if we already produce diags in the macro.



_Code quote:_
```
ne macro `dep_component_mut` failed.
```


<!-- Sent from Reviewable.io -->

2023-10-19 13:52 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4271)* status: 11 of 22 files reviewed, 5 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 5711 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4271#-NgyVovM6xOaSp_nbB2x:-Nh7BCoB85b1FJzfdGkr:b-ek70jv) ([raw file](https://github.com/starkware-libs/cairo/blob/8cb5e968097a914fa069f3801a79bc478f7ebdc0/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L5711)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Arghh that's right. I thought we verify the name is TContractState. This is true for embeddable_as but not for other impls, or free functions.
This also means we need to remove the `::<TContractState>` in HasComponent that eliminated this error :/

It takes me back to the option of having the name of the impl in the inline macro, and not the name of the component module. `HasComponent::<TContractState>` was the second best option after using the impl name. But because we didn't have it, I settled for it. As we see we can't really do it, and we wouldn't want a third parameter in the macro, I bring back this option to the table. Maybe it's good anyway to have more clarity/explicitness in this case which is not very common and might be confusing?

Now thinking about it, another argument for having the impl name and not the module name:
If one uses a module name for which we don't have an impl in context, there would probably be a strange error. If they use an impl name that doesn't exist, it would probably say (correctly) "Identifier not found".

WDYT?

(anyway probably worth checking this errors with the simplest usecase possible, in the expand tests)
</blockquote></details>

Changed back to accepting the impl name.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 6393 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Nh6L-M_734bpRWUcMo5:-Nh7BKab46RF8sGAxEpn:b-krm8zt) ([raw file](https://github.com/starkware-libs/cairo/blob/662ceeff4697a5fbc728684750c9d36194a257f7/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L6393)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

probably also out of scope of this PR, but I think this diag is not necessary if we already produce diags in the macro.
</blockquote></details>

Agree, noted for a future fix.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 5722 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Nh7CG-118Nkb8c1Rl4q:-Nh7CG-118Nkb8c1Rl4r:b4frww7) ([raw file](https://github.com/starkware-libs/cairo/blob/5bec9c7c94defba59ff1dcec559a833a2c1a36e0/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L5722)):*
> ```
> error: Invalid path.
>  --> lib.cairo[get_dep_component_inline_macro]:4:41
>                 super::NotHasComponent::get_component(__get_get_dep_component_macro_temp_contract__)
> ```

This points to the generated code, but I think the "Invalid path" is fine in this case, wdyt?
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 74 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Nh6LfiuCI1XmXetIwhD:-Nh7BU0IDeC7BOh4-WcA:bo92oay) ([raw file](https://github.com/starkware-libs/cairo/blob/662ceeff4697a5fbc728684750c9d36194a257f7/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L74)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

1. I see you changed here but for some reason the diag still points to the whole expr (maybe this is what's pointed by the patch?
2. If we can point to something partial - better to point specifically to the modifiers.
</blockquote></details>

I know, I am not sure why is this, I'll look into it later.
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 82 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Nh6JPc2---4LOGHBLxp:-Nh7Br9r9clN_ZlDnfvq:b-iw651k) ([raw file](https://github.com/starkware-libs/cairo/blob/662ceeff4697a5fbc728684750c9d36194a257f7/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L82)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think this should work (maybe need minor & fixes)
</blockquote></details>

Changed to `let else`.


<!-- Sent from Reviewable.io -->

2023-10-19 14:18 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4271)* status: all files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/components/mintable.cairo` line 29 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Nh7EF_UCIkbo2nDluDw:-Nh7FsfUCN01zaOmYg4S:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5bec9c7c94defba59ff1dcec559a833a2c1a36e0/crates/cairo-lang-starknet/cairo_level_tests/components/mintable.cairo#L29)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

change to impl name.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 5689 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Nh7C9HA7URGENzxyppG:-Nh7GumT7o9lAZJe1aI9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5bec9c7c94defba59ff1dcec559a833a2c1a36e0/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L5689)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please add one with a non existing:
get_dep_component!(self, NonExisitingImpl).foo1();
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 5725 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Nh7DgoA-suCAM3EHic8:-Nh7GyZi1weTz4Sx-jPO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5bec9c7c94defba59ff1dcec559a833a2c1a36e0/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L5725)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

same here. Clear but not ideal as it points to generated code.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 82 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Nh6JPc2---4LOGHBLxp:-Nh7GNVS-B04laUMqSI4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/662ceeff4697a5fbc728684750c9d36194a257f7/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L82)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I mostly wanted to remove the `<[_; 1]>::try_from` - is it necessary?
And I suggested `if !matches` as `let else` looks weird with no variable introduced by it.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/inline_macros/get_dep_component.rs` line 93 at r12](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Nh7Esh86sjp9rN9GYcU:-Nh7Gg5iBcdiFlFyBGAK:b-26flp) ([raw file](https://github.com/starkware-libs/cairo/blob/681379ec1dc405d6dd0dab0e1012d293700e6a17/crates/cairo-lang-starknet/src/inline_macros/get_dep_component.rs#L93)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

this should change to use the impl. also change the name of the arg from module to impl.
</blockquote></details>

Changed the name, already changed it to use the impl.


<!-- Sent from Reviewable.io -->

2023-10-19 15:14 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4271)* status: all files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 5689 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Nh7RuIW8OYpc1p9-z6P:-Nh7V2507RRPUl_reZMt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/de070baa40604dced3a4352275b86ddd6b6da55d/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L5689)):*
> ```
>             let not_contract_state: felt252 = 0;
>             get_dep_component!(not_contract_state, Comp1).foo1();
>             get_dep_component!(not_contract_state, NonExistingImpl).foo1();
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 5743 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Nh7SyW47WiNjavPCdnp:-Nh7Uk9D4ipReU4m7SNj:blt37xf) ([raw file](https://github.com/starkware-libs/cairo/blob/de070baa40604dced3a4352275b86ddd6b6da55d/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L5743)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

where did this come from? Why is it added now?
According to the "Comp1" I guess it's from the first or the third, but which one? and mainly - why only one of them?
</blockquote></details>

From the first, it was added because I removed the `::<TContractState>::` from the generated code.
Not sure why only one of them, trying to check.
___
*[`crates/cairo-lang-starknet/src/inline_macros/get_dep_component.rs` line 89 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Nh7Q3mV47kgCoxNCm2b:-Nh7V2JI5Mp09ADZ3TUg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/de070baa40604dced3a4352275b86ddd6b6da55d/crates/cairo-lang-starknet/src/inline_macros/get_dep_component.rs#L89)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

double get
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-22 06:54 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4271)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 5743 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Nh7SyW47WiNjavPCdnp:-NhL8W-l6LlAFIKMvqYH:b-d3wgt1) ([raw file](https://github.com/starkware-libs/cairo/blob/de070baa40604dced3a4352275b86ddd6b6da55d/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L5743)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

From the first, it was added because I removed the `::<TContractState>::` from the generated code.
Not sure why only one of them, trying to check.
</blockquote></details>

In the third case it fails to earlier because of the `Expected variable or constant, found impl`, it doesn't get to the failed inference.
___
*[`crates/cairo-lang-starknet/src/inline_macros/dep_component.rs` line 74 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Nh6LfiuCI1XmXetIwhD:-NhL8tK0E_eKZjBXNEUL:b-xsrsv0) ([raw file](https://github.com/starkware-libs/cairo/blob/662ceeff4697a5fbc728684750c9d36194a257f7/crates/cairo-lang-starknet/src/inline_macros/dep_component.rs#L74)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

I know, I am not sure why is this, I'll look into it later.
</blockquote></details>

That's really weird, not sure why it's not working, I'll todo it for now if that's fine with you.
About the pointing to the modifiers, I choose not to since it's the same error if there are no modifiers to point to, and I prefer not to split these cases.


<!-- Sent from Reviewable.io -->

2023-10-22 08:15 UTC, yuvalsw approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4271)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics` line 5743 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4271#-Nh7SyW47WiNjavPCdnp:-NhLRk1o5wA8TCbmkps7:bmm47dg) ([raw file](https://github.com/starkware-libs/cairo/blob/de070baa40604dced3a4352275b86ddd6b6da55d/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/diagnostics#L5743)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

In the third case it fails to earlier because of the `Expected variable or constant, found impl`, it doesn't get to the failed inference.
</blockquote></details>

As discussed f2f, add a TODO to resolve it. We should not insert missing expr to the inference system.


<!-- Sent from Reviewable.io -->

2023-10-22 08:15 UTC, yuvalsw approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4271#-:-NhLRyAADwxKE_2HupXx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2023-10-22 08:51 UTC, merged