Skip attributes with no related item.
starkware-libs/cairo pull request #4296
Opened 2023-10-24 13:18 UTC by gilbens-starkware

2023-10-24 14:47 UTC, orizi requested changes
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test.rs` line 199 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhX7_O11ZCEi8ldxtEd:-NhX7_O11ZCEi8ldxtEe:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test.rs#L199)):*
> ```XML
> 
>     },
>     test_partial_parser_tree_with_trivia
> ```





_Suggestion:_
```XML
        path: "path",
        path_compat: "path_compat",
        attribute_errors: "attribute_errors",
    },
    test_partial_parser_tree_with_trivia
```
___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 667 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhX8Ms864xLxBfpLaLK:-NhX8Ms864xLxBfpLaLL:b-uktzcm) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L667)):*
> ```XML
>     // An enum of all nodes that can be skipped while parsing.
>     .add_enum(EnumBuilder::new("SkippedNodeInner")
>         .node_with_explicit_kind("AttributeList", "AttributeList")
> ```

maybe we should have all the skipped types under the inner?
also - if you add the inner type to prevent the recursive enum - doc it here.



_Code quote:_
```XML
        .node_with_explicit_kind("AttributeList", "AttributeList")
```


<!-- Sent from Reviewable.io -->

2023-10-25 15:38 UTC, yuvalsw requested changes
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: all files reviewed, 18 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Nhazx_50c8vPeW44_UG:-Nhazx_50c8vPeW44_UH:bjqt0gg) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser.rs#L267)):*
> ```XML
>                 if has_attrs {
>                     Ok(self.skip_node_and_return_missing::<Item>(
>                         SkippedNode::new_green(self.db, attributes.into()),
> ```

better if you can spare this by accepting "impl Into<SkippedNode>" as the parameter, and add the `SkippedNode::new_green` in the function



_Code quote:_
```XML
SkippedNode::new_green
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2189 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Nhb0NWpCDRGFwElCTFF:-Nhb0NWpCDRGFwElCTFG:bvs2ay0) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser.rs#L2189)):*
> ```XML
> 
>     /// Skips a node. A skipped node is a node which is not expected where it is found. Skipping
>     /// this node means reporting an error, appending it to the current trivia, and continuing the
> ```

Please also add this part (about appending to the trivia) to the `skip_token` doc.



_Suggestion:_
```XML
, appending the node to the current trivia as skipped, and c
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2191 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Nhb2u-457oaiDyL0Ut1:-Nhb2u-457oaiDyL0Ut2:b-u687h0) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser.rs#L2191)):*
> ```XML
>     /// this node means reporting an error, appending it to the current trivia, and continuing the
>     /// compilation as if it wasn't there.
>     fn skip_node(&mut self, node_to_skip: SkippedNodeGreen, diagnostic_kind: ParserDiagnosticKind) {
> ```

Also please clarify this in the doc - as opposed to `skip_token`, here the node to skip is already fully taken/consumed.



_Suggestion:_
```XML
fn skip_taken_node(
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2193 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Nhb0ot6-tKoovzLuRQ8:-Nhb0ot6-tKoovzLuRQ9:bfq6hc1) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser.rs#L2193)):*
> ```XML
>     fn skip_node(&mut self, node_to_skip: SkippedNodeGreen, diagnostic_kind: ParserDiagnosticKind) {
>         // Add to pending trivia.
>         self.pending_trivia.push(node_to_skip.into());
> ```

could the pending trivia be nonempty? Could it contain skipped tokens/nodes? I think that if we had trivia, it should have been attached to something inside the current node we are skipping.
I am not saying this means this/any code should change, but I think it's worth to thoroughly cover all the cases and document what's possible and why. This may float potential issues we haven't thought of (which I hope there aren't), e.g. a skipped token appearing twice in the tree, duplicate diagnostics etc.

For all the edge cases that come up from this thinking, try to add a test.

A simple test case is a trivia and then a skipped node:
mod a {
    // comment
    #[attr]
}

And a skipped token before a skipped node:
mod a {
    $
    #[attr]
}

Or after (not sure what's supposed to happen here):
mod a {
    #[attr]
    $
}

Assuming the '$' above is skipped, maybe also have:
mod a {
    #[attr]
    $
    #[attr]
}
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2193 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbHytjAdOnpbhJmQJ5:-NhbHytjAdOnpbhJmQJ6:bau8cku) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser.rs#L2193)):*
> ```XML
>     fn skip_node(&mut self, node_to_skip: SkippedNodeGreen, diagnostic_kind: ParserDiagnosticKind) {
>         // Add to pending trivia.
>         self.pending_trivia.push(node_to_skip.into());
> ```

Why did you do it in a different order than in `append\_skipped\_token\_to\_pending\_trivia`?
If there is no good reason, better for both to be in the same logical order for ease of reading.



_Code quote:_
```XML
        // Add to pending trivia.
        self.pending_trivia.push(node_to_skip.into());
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2202 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbHezs6WUepmUBjxrY:-NhbHezs6WUepmUBjxrZ:b-uja0r5) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser.rs#L2202)):*
> ```XML
>             span: TextSpan { start: diag_start, end: diag_end },
>             leading_trivia_start: orig_offset,
>             trailing_trivia_end: diag_end,
> ```

As in `append\_skipped\_token\_to\_pending\_trivia`, I think you should add here the width of the trailing trivia. IIRC it was added to correctly merge skip diagnostics (this way we can see that 2 consecutive ones are "touching").
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 0 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbU0Lu4wgIgxBJNyre:-NhbU0Lu4wgIgxBJNyrf:b-oxde00) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L0)):*
In all the tests - where are the "skipped" diagnostics for the orphan attributes?
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbMVHLC6bBVkKKYEAq:-NhbMVHLC6bBVkKKYEAr:b-18f107) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L55)):*
> ```
> 
> //! > ignored_kinds
> Attribute
> ```

Same in the impl item test below.



_Suggestion:_
```
//! > top_level_kind
TraitBody

//! > ignored_kinds
Attribute
TerminalLBrace
TerminalEndOfFile
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 58 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbR8B02kjSEGVZFV-H:-NhbR8B02kjSEGVZFV-I:b-jfslob) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L58)):*
> ```
> 
> //! > expected_diagnostics
> error: Missing tokens. Expected an item after attributes.
> ```

This used to be "Expected a trait item ...". Can we get it back?
Same in the impl.



_Code quote:_
```
Expected an item after attributes.
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 231 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbRxw66xMNJsvNi0kT:-NhbRxw66xMNJsvNi0kU:b-hf41gt) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L231)):*
> ```
> //! > ==========================================================================
> 
> //! > Test repeated attributed literals.
> ```

can you please rephrase?



_Code quote:_
```
Test repeated attributed literals.
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 245 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbSOZvDHlIzxPZI9xu [...]

2023-10-26 22:12 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: 2 of 10 files reviewed, 15 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Nhazx_50c8vPeW44_UG:-NhfFhAp71ve-zYir-8f:bv4ak0w) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser.rs#L267)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

better if you can spare this by accepting "impl Into<SkippedNode>" as the parameter, and add the `SkippedNode::new_green` in the function
</blockquote></details>

Not sure I understand, what will be the type of the node passed to the function? `AttributeList`?
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2191 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Nhb2u-457oaiDyL0Ut1:-NhfIK2560Fl8Scq7KkK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser.rs#L2191)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Also please clarify this in the doc - as opposed to `skip_token`, here the node to skip is already fully taken/consumed.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2193 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbHytjAdOnpbhJmQJ5:-Nhha8NJDzuYeW_QBnMU:b-vududg) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser.rs#L2193)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why did you do it in a different order than in `append\_skipped\_token\_to\_pending\_trivia`?
If there is no good reason, better for both to be in the same logical order for ease of reading.
</blockquote></details>

No reason, guess that I flipped the order in one of the edits.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2202 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbHezs6WUepmUBjxrY:-NhhsWJB8Cj1D50e25g6:bw3q8ct) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser.rs#L2202)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

As in `append\_skipped\_token\_to\_pending\_trivia`, I think you should add here the width of the trailing trivia. IIRC it was added to correctly merge skip diagnostics (this way we can see that 2 consecutive ones are "touching").
</blockquote></details>

I got a small problem with it crossing the EOF, checking.
___
*[`crates/cairo-lang-parser/src/parser_test.rs` line 199 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhX7_O11ZCEi8ldxtEd:-NhfAqXXCrxx4GLNchlN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test.rs#L199)):*
> ```XML
> 
>     },
>     test_partial_parser_tree_with_trivia
> ```

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 55 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbMVHLC6bBVkKKYEAq:-NhfNVQh8CZrX-sqN6yP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L55)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Same in the impl item test below.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 58 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbR8B02kjSEGVZFV-H:-NhfNjdT-_XY91YFOodF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L58)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This used to be "Expected a trait item ...". Can we get it back?
Same in the impl.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 231 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbRxw66xMNJsvNi0kT:-NhfO4b37_T3SKnvTRMJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L231)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

can you please rephrase?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 245 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbSOZvDHlIzxPZI9xu:-NhfOEa_EyYzcWBrlX9E:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L245)):*
> ```
> 
> //! > ignored_kinds
> FunctionDeclaration
> ```

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 344 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbTKw70V45NLvoguUQ:-NhfQ8N57Rm7Tzi4xZyS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L344)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

same as above, reduce to only the necessary part of the tree.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line  at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbU0Lu4wgIgxBJNyre:-NhfArS_3ZTel9Os0HKE:bpw58lp) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

In all the tests - where are the "skipped" diagnostics for the orphan attributes?
</blockquote></details>

The passed diagnostic is to the skip function is "Missing item", I think it's what the user need to know, do we want two diagnostics?
___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhayXsq6dEXn4wyvjXJ:-NhheDdw2XJNfBlbAK_I:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L13)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Then define TriviumSkippedNode below, and SkippedNodeInner can become SkippedNode (if indeed required as Ori commented).
</blockquote></details>

Done.
___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 665 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhazBNo1d1Q1TMtUvPz:-NhheH2Z9KVNfyBkY1vA:bwqtpqm) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L665)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Please comment that it's OK to add kinds here later as needed. Theoretically we could add now all types, but didn't do it to avoid unnecessary code + possible confusion.
</blockquote></details>

Done.
I don't want to add all nodes now without something that will generate it/test all nodes are there since if it will be manual there is a big chance it won't be maintaine [...]

2023-10-27 02:01 UTC, orizi reviewed
> Reviewed 2 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: 4 of 10 files reviewed, 13 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-10-29 08:21 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: 4 of 10 files reviewed, 13 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 2193 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Nhb0ot6-tKoovzLuRQ8:-NhuWUetBGmfggjXKW48:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser.rs#L2193)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

could the pending trivia be nonempty? Could it contain skipped tokens/nodes? I think that if we had trivia, it should have been attached to something inside the current node we are skipping.
I am not saying this means this/any code should change, but I think it's worth to thoroughly cover all the cases and document what's possible and why. This may float potential issues we haven't thought of (which I hope there aren't), e.g. a skipped token appearing twice in the tree, duplicate diagnostics etc.

For all the edge cases that come up from this thinking, try to add a test.

A simple test case is a trivia and then a skipped node:
mod a {
    // comment
    #[attr]
}

And a skipped token before a skipped node:
mod a {
    $
    #[attr]
}

Or after (not sure what's supposed to happen here):
mod a {
    #[attr]
    $
}

Assuming the '$' above is skipped, maybe also have:
mod a {
    #[attr]
    $
    #[attr]
}
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-29 12:04 UTC, yuvalsw requested changes
> Reviewed 7 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: 9 of 10 files reviewed, 16 unresolved discussions (waiting on @gilbens-starkware and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhujUAT9OozFlD9aAnq:-NhujUAT9OozFlD9aAnr:b-uls5vx) (no related file):*
I think you need to add a semantic test with an inline module with attrs without item, and then some diagnostic after the inline module, to see that it points to the right locations.

___
___
*[`crates/cairo-lang-parser/src/parser.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Nhazx_50c8vPeW44_UG:-NhvHcNh41eu34ofXHpl:bze6w13) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser.rs#L267)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Not sure I understand, what will be the type of the node passed to the function? `AttributeList`?
</blockquote></details>

`impl Into<SkippedNodeGreen>` (which is currently only AttributeListGreen). I think it could work.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2193 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Nhb0ot6-tKoovzLuRQ8:-NhvJXvl3pcogk7reOvt:b-ghi8cy) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser.rs#L2193)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you elaborate?
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2417 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhuczcIA81CSuCsn8E0:-NhuczcIA81CSuCsn8E1:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/bb63d7434c8ab5e5ff0a2685a6bb7b623a6a4a86/crates/cairo-lang-parser/src/parser.rs#L2417)):*
> ```XML
>     let node = db.lookup_intern_green(green_id);
>     if node.kind == SyntaxKind::Trivia {
>         println!("trivia width: {:?}", node.width());
> ```

remove
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2426 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhudOy5-FkJWDazhCU4:-NhudOy5-FkJWDazhCU5:bz4f86y) ([raw file](https://github.com/starkware-libs/cairo/blob/bb63d7434c8ab5e5ff0a2685a6bb7b623a6a4a86/crates/cairo-lang-parser/src/parser.rs#L2426)):*
> ```XML
>                 leading_trivia_width(db, *child)
>             } else {
>                 TextWidth::default()
> ```

is this case possible? If so, please doc how.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2433 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhudvLJ06O3NBSuM-oI:-NhudvLJ06O3NBSuM-oJ:bn0ocwy) ([raw file](https://github.com/starkware-libs/cairo/blob/bb63d7434c8ab5e5ff0a2685a6bb7b623a6a4a86/crates/cairo-lang-parser/src/parser.rs#L2433)):*
> ```XML
> 
> /// The width of the trailing trivia, traversing the tree to the bottom right node.
> pub fn trailing_trivia_width(db: &dyn SyntaxGroup, green_id: GreenId) -> TextWidth {
> ```

same comments as in leading
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2433 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhueCI68WFUgtAHgeGz:-NhueCI68WFUgtAHgeH-:b-akg5r1) ([raw file](https://github.com/starkware-libs/cairo/blob/bb63d7434c8ab5e5ff0a2685a6bb7b623a6a4a86/crates/cairo-lang-parser/src/parser.rs#L2433)):*
> ```XML
> 
> /// The width of the trailing trivia, traversing the tree to the bottom right node.
> pub fn trailing_trivia_width(db: &dyn SyntaxGroup, green_id: GreenId) -> TextWidth {
> ```

can you unite this function with a callback parameter for first/last child?
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhujMRL-NGKCkuAxs_r:-NhujMRM0-we_2YpUrEo:br8bi21) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L39)):*
> ```
>         └── trailing_trivia (kind: Trivia) []
> 
> //! > ==========================================================================
> ```

where are all the tests gone?
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line  at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbU0Lu4wgIgxBJNyre:-NhugrGv6s6aNdW7UBBj:b-2e0h0b) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

The passed diagnostic is to the skip function is "Missing item", I think it's what the user need to know, do we want two diagnostics?
</blockquote></details>

I think so.
1. I think this is what we do for missing tokens in skip_token_and_return_missing, so we may want to be consistent.
2. The skipped tokens diagnostic is mainly informative - there is a missing item (this is the missing diag), but I (the compiler/parser) ignored/skipped the attributes in order to keep parsing the rest of the file.

I am not locked on this, so if you don't agree please let's discuss.
___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 665 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhazBNo1d1Q1TMtUvPz:-Nhuj0y49dead2njTjoX:b-cwy8s8) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L665)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
I don't want to add all nodes now without something that will generate it/test all nodes are there since if it will be manual there is a big chance it won't be maintained. If I'll add such test it'll be in a separate PR.
</blockquote></details>

No, this is completely fine. Just resonated my request.
___
*[`crates/cairo-lang-syntax-codegen/src/cairo_spec.rs` line 665 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhuinXY9NMpQfMbpK2_:-NhuinXY9NMpQfMbpK2a:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/bb63d7434c8ab5e5ff0a2685a6bb7b623a6a4a86/crates/cairo-lang-syntax-codegen/src/cairo_spec.rs#L665)):*
> ```XML
>     .add_struct(StructBuilder::new("TriviumSkippedNode")
>     .node("node", "SkippedNode")
>     )
> ```





_Suggestion:_
```XML
    .add_struct(StructBuilder::new("TriviumSkippedNode")
        .node("node", "SkippedNode")
    )
```


<!-- Sent from Reviewable.io -->

2023-10-29 14:48 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: 9 of 10 files reviewed, 16 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Nhazx_50c8vPeW44_UG:-NhvtOFx0BCVp9EiRZKK:b65ik6v) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser.rs#L267)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

`impl Into<SkippedNodeGreen>` (which is currently only AttributeListGreen). I think it could work.
</blockquote></details>

Yes, that's the impl, but the node that'll be turned into `SkippedNodeGreen`, a generic type?


<!-- Sent from Reviewable.io -->

2023-10-30 14:36 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: 9 of 10 files reviewed, 14 unresolved discussions (waiting on @orizi and @yuvalsw)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhujUAT9OozFlD9aAnq:-Ni0-yZX0n6qolN5fkkO:b-896fix) (no related file):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think you need to add a semantic test with an inline module with attrs without item, and then some diagnostic after the inline module, to see that it points to the right locations.
</blockquote></details>

Done.

___
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2193 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Nhb0ot6-tKoovzLuRQ8:-Ni-yVS0-ikAM8AXYFVn:bqns0i8) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser.rs#L2193)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can you elaborate?
</blockquote></details>

Wrong push, see below.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2426 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhudOy5-FkJWDazhCU4:-Ni-ySyL3vefWI1uTrxx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bb63d7434c8ab5e5ff0a2685a6bb7b623a6a4a86/crates/cairo-lang-parser/src/parser.rs#L2426)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

is this case possible? If so, please doc how.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2433 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhudvLJ06O3NBSuM-oI:-Ni-yTdN4_KPurbdqw-H:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bb63d7434c8ab5e5ff0a2685a6bb7b623a6a4a86/crates/cairo-lang-parser/src/parser.rs#L2433)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

same comments as in leading
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2433 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhueCI68WFUgtAHgeGz:-Ni-yU2e6Eb4_BFc3NT8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bb63d7434c8ab5e5ff0a2685a6bb7b623a6a4a86/crates/cairo-lang-parser/src/parser.rs#L2433)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

can you unite this function with a callback parameter for first/last child?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhujMRL-NGKCkuAxs_r:-Ni-kXG9BYJ6JMBNxvg1:b787me2) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L39)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

where are all the tests gone?
</blockquote></details>

Accidentally pushed a WIP version when I debugged.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line  at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbU0Lu4wgIgxBJNyre:-Ni-jhPj60E30bNPFck0:b61k5rj) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think so.
1. I think this is what we do for missing tokens in skip_token_and_return_missing, so we may want to be consistent.
2. The skipped tokens diagnostic is mainly informative - there is a missing item (this is the missing diag), but I (the compiler/parser) ignored/skipped the attributes in order to keep parsing the rest of the file.

I am not locked on this, so if you don't agree please let's discuss.
</blockquote></details>

I don't really like it since the skip tokens diagnostics also mentions what was expected, it is good when we skip because the token is not expected at this point, it is not that good when the something is missing.
I made this change, let me know what you think.


<!-- Sent from Reviewable.io -->

2023-10-30 20:24 UTC, yuvalsw requested changes
> Reviewed 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: 10 of 11 files reviewed, 26 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 2196 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni1FObc21ygB60We1eS:-Ni1FObd9aW3SHvt8aMB:b-g17136) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser.rs#L2196)):*
> ```XML
>     /// error, appending the node to the current trivia as skipped, and continuing the
>     /// compilation as if it wasn't there.
>     fn skip_taken_node(
> ```

haven't reviewed this function yet, will review tomorrow. Posting the rest for now.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2434 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni07Wae9A5aWX4ZeJmE:-Ni07Waf-YZVBvTw4YGF:b-k32yuy) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser.rs#L2434)):*
> ```XML
> /// The width of the trailing trivia, traversing the tree to the bottom right node.
> pub fn trailing_trivia_width(db: &dyn SyntaxGroup, green_id: GreenId) -> TextWidth {
>     get_trivia_width(db, green_id, |children| children.last())
> ```

I think this should work



_Suggestion:_
```XML
id, Vec::last)
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2437 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni087Ab42Q7PXOmp84H:-Ni087Ab42Q7PXOmp84I:b1xwtkx) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser.rs#L2437)):*
> ```XML
> }
> 
> pub fn get_trivia_width(
> ```

doc, specifically node_selector.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2452 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni08gm9-n32lLTfTnAr:-Ni08gm9-n32lLTfTnAs:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser.rs#L2452)):*
> ```XML
>                 get_trivia_width(db, *child, node_selector)
>             } else {
>                 unreachable!("Only tokens should have no children.")
> ```





_Suggestion:_
```XML
unreachable!("Only tokens should have no children.");
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 245 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbSOZvDHlIzxPZI9xu:-Ni1CHT41YyToxzKZGAD:bl54fdk) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L245)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Add top level kind to be `FunctionWithBody` and `ExprPath` to ignored kinds.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 330 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbTEskB0HKH2LvV9V7:-Ni1CUZBDs7KzZbk30Hy:bocxtjq) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L330)):*
> ```
> //! > ==========================================================================
> 
> //! > Test skipped inside a module.
> ```

I don't see the change.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line  at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbU0Lu4wgIgxBJNyre:-Ni1BNH53m_vpOvbJbqm:bjoc6q2) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

I don't really like it since the skip tokens diagnostics also mentions what was expected, it is good when we skip because the token is not expected at this point, it is not that good when the something is missing.
I made this change, let me know what you think.
</blockquote></details>

Let's think about it f2f.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 293 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni1CqNq5--n4T_KOlUo:-Ni1CqNq5--n4T_KOlUp:bi0wdo8) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L293)):*
> ```
>     ^****^
> 
> //! > expected_tree
> ```

I don't see the skipped node here.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 313 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni1CyBv4fhyurndDQSe:-Ni1CyBv4fhyurndDQSf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L313)):*
> ```
> 
> //! > cairo_code
> mod mod1{
> ```





_Suggestion:_
```
1 {
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 340 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni1D4VW8tzTVTVt23lm:-Ni1D4VW8tzTVTVt23ln:bkjl4vb) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L340)):*
> ```
> //! > expected_tree
> └── Top level kind: ModuleBody
>     ├── lbrace (kind: TerminalLBrace)
> ```

can ignore
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 368 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni1D9YR471Udw6tnX-t:-Ni1D9YR471Udw6tnX-u:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L368)):*
> ```
> 
> //! > cairo_code
> mod mod1{
> ```





_Suggestion:_
```
od1 {
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 395 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni1DCoj-U3NF06NZplz:-Ni1DCoj-U3NF06NZpm-:bkjl4vb) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L395)):*
> ```
> //! > expected_tree
> └── Top level kind: ModuleBody
>     ├── lbrace (kind: TerminalLBrace)
> ```

can ignore
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 454 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni1DJWMAZawhTGKiMOF:-Ni1DJWMAZawhTGKiMOG:bkjl4vb) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L454)):*
> ```
> //! > expected_tree
> └── Top level kind: ModuleBody
>     ├── lbrace (kind: TerminalLBrace)
> ```

can ignore
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 475 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni1DggVDRAJ_4u1gd0l:-Ni1DggVDRAJ_4u1gd0m:b-fdtruu) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L475)):*
> ```
>         │   └── child #3 (kind:  [...]

2023-10-30 22:41 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: 10 of 11 files reviewed, 26 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 513 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni1E3VSDhN7g9FAqwr4:-Ni1iw4jBN7Rrlth2xBT:bwpgm63) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L513)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

It would be good if the 2 skipped diags would be merged. Why don't they?
</blockquote></details>

The kind wasn't exactly the same, as I haven't added "or an attribute", which is debatable (another attribute is valid after the skipped attribute, but at some point we'll need an item.
Changed it, but we should be aware that diagnostics spanning more than one line are bad.


<!-- Sent from Reviewable.io -->

2023-10-31 08:59 UTC, yuvalsw requested changes
> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: 9 of 11 files reviewed, 29 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 2208 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni3xAmJ-9xfYNmDKVzI:-Ni3xAmJ-9xfYNmDKVzJ:bo9jyxs) ([raw file](https://github.com/starkware-libs/cairo/blob/3e742018bc7cbe09b706bbdc94d9fbc56a248874/crates/cairo-lang-parser/src/parser.rs#L2208)):*
> ```XML
>         // Remove the node width, as it was already taken, and fix for the last token not being
>         // considered in the current offset.
>         let orig_offset =
> ```

It's not orig_offset



_Code quote:_
```XML
orig_offset
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2209 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni3wcs10dA8B6BJY9F7:-Ni3wcs10dA8B6BJY9F8:blunj0v) ([raw file](https://github.com/starkware-libs/cairo/blob/3e742018bc7cbe09b706bbdc94d9fbc56a248874/crates/cairo-lang-parser/src/parser.rs#L2209)):*
> ```XML
>         // considered in the current offset.
>         let orig_offset =
>             self.offset.add_width(self.current_width).sub_width(node_to_skip.0.width(self.db));
> ```

this is calculated twice.



_Code quote:_
```XML
node_to_skip.0.width(self.db)
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2217 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni3wqu09oUl-qU7DFVg:-Ni3wqu09oUl-qU7DFVh:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3e742018bc7cbe09b706bbdc94d9fbc56a248874/crates/cairo-lang-parser/src/parser.rs#L2217)):*
> ```XML
>         let diag_start = orig_offset.add_width(node_leading_trivia_width);
>         // Position of the node before the trailing trivia.
>         let diag_end = diag_start.add_width(width_without_trivia);
> ```





_Suggestion:_
```XML
    
        // Position of the node after the leading trivia.
        let diag_start = orig_offset.add_width(node_leading_trivia_width);
        // Position of the node before the trailing trivia.
        let diag_end = orig_offset.add_width(node_to_skip.0.width(self.db) - node_trailing_trivia_width);
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 130 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni3tnZP657RBMrEcXxy:-Ni3tnZP657RBMrEcXxz:b54zkon) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L130)):*
> ```
>  --> dummy_file.cairo:3:5
>     3
>     ^
> ```

why is this gone?



_Code quote:_
```
error: Skipped tokens. Expected: impl item or an attribute.
 --> dummy_file.cairo:3:5
    3
    ^
```
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 228 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni3twrvE8n-Z9KBK2Ii:-Ni3twrvE8n-Z9KBK2Ij:bji9y6k) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L228)):*
> ```
> ^****^
> 
> error: Skipped tokens. Expected: Const/Module/Use/FreeFunction/ExternFunction/ExternType/Trait/Impl/Struct/Enum/TypeAlias/InlineMacro or an attribute.
> ```

and this
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 513 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni1E3VSDhN7g9FAqwr4:-Ni3uLs39rI6tsHUzxbd:b-f4g2cx) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L513)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

The kind wasn't exactly the same, as I haven't added "or an attribute", which is debatable (another attribute is valid after the skipped attribute, but at some point we'll need an item.
Changed it, but we should be aware that diagnostics spanning more than one line are bad.
</blockquote></details>

We need to fix multi line diags. But I don't see the skipped diags being merged.


<!-- Sent from Reviewable.io -->

2023-10-31 11:50 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: 7 of 11 files reviewed, 25 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 267 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Nhazx_50c8vPeW44_UG:-Ni47PAiDGvMiQa15o3Y:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser.rs#L267)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Yes, that's the impl, but the node that'll be turned into `SkippedNodeGreen`, a generic type?
</blockquote></details>

Done
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2202 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbHezs6WUepmUBjxrY:-Ni48a124JKQuzAnUzaZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser.rs#L2202)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

I got a small problem with it crossing the EOF, checking.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2434 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni07Wae9A5aWX4ZeJmE:-Ni4VdLxCd5uRD7qxPNm:b5yj3t6) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser.rs#L2434)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think this should work
</blockquote></details>

`last` is a method of slice, and it doesn't have a a literal type (the impl declaration is `impl<T> [T]`), so I can't really access it.
I tried making a type alias `type SliceType<T> = [T]' just out of curiosity, but I got some weird errors, which I think are because each function should have only one function pointer but I haven't tried to fully understand it.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2437 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni087Ab42Q7PXOmp84H:-Ni495HP2Pe4BIoyY_fb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser.rs#L2437)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doc, specifically node_selector.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2208 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni3xAmJ-9xfYNmDKVzI:-Ni47fA17b1aXWwCYtwB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3e742018bc7cbe09b706bbdc94d9fbc56a248874/crates/cairo-lang-parser/src/parser.rs#L2208)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

It's not orig_offset
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2209 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni3wcs10dA8B6BJY9F7:-Ni41SfaABnTN-9W2pjJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3e742018bc7cbe09b706bbdc94d9fbc56a248874/crates/cairo-lang-parser/src/parser.rs#L2209)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

this is calculated twice.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2217 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni3wqu09oUl-qU7DFVg:-Ni481AsEsCJPoPG3dF-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3e742018bc7cbe09b706bbdc94d9fbc56a248874/crates/cairo-lang-parser/src/parser.rs#L2217)):*
> ```XML
>         let diag_start = orig_offset.add_width(node_leading_trivia_width);
>         // Position of the node before the trailing trivia.
>         let diag_end = diag_start.add_width(width_without_trivia);
> ```

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 245 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbSOZvDHlIzxPZI9xu:-Ni4G-0T9Cuzytq9AY-z:b-ckc4gd) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L245)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Add top level kind to be `FunctionWithBody` and `ExprPath` to ignored kinds.
</blockquote></details>

I'm not sure which test you are referring to.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line  at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbU0Lu4wgIgxBJNyre:-Ni4We_H7aCyapHmQDf9:b-27qqdg) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Let's think about it f2f.
</blockquote></details>

Returned to just `Missing` as discussed.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 130 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni3tnZP657RBMrEcXxy:-Ni4BRg1CMh4zWRqPote:b9z8wdl) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L130)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why is this gone?
</blockquote></details>

It's merged, that's the biggest problem with the multiline diags, I think that now with skipped nodes we should prioritise fixing it.
Should be easy once we'll decide on the format. 
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 228 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni3twrvE8n-Z9KBK2Ii:-Ni4BsDX2fKb9BEbZSkV:b-816h6l) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L228)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

and this
</blockquote></details>

Same.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 293 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni1CqNq5--n4T_KOlUo:-Ni4DjjoCOP6yF1N3IB9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L293)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I don't see the skipped node here.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 340 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni1D4VW8tzTVTVt23lm:-Ni49yqFBK3iYoMGUNVo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L340)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

can ignore
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 395 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni1DCoj-U3NF06NZplz:-Ni49zHb3dcCobC3nKaa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L395)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

can ignore
</blockquote></det [...]

2023-10-31 13:35 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: all files reviewed, 11 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 2238 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni4bI5G1G1G5YJiqAbQ:-Ni4rpSO1tSWoAqeJKnK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a2917b15c691974693dc7156af8ff39c260ccd66/crates/cairo-lang-parser/src/parser.rs#L2238)):*
> ```XML
> 
>     /// Skips a given SkippedNode, reports the given diagnostic, and a diagnostic for the skipped
>     /// node, and returns missing kind of the expected node.
> ```

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/full_trees/test1` line 41 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni4iYTlDwMnNd8Spbgk:-Ni4rzV62MH0wMqJwAI6:b73vup8) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/full_trees/test1#L41)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

The previous pointer was better, pointing to after the attribute. Why did it change?
</blockquote></details>

Because it was not raised from the skipping function, if it's the diagnostic raised from the skipping then it should point to the skipped part, no?
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 245 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NhbSOZvDHlIzxPZI9xu:-Ni4wW8Z3Kzfyk1XjN0N:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cbdad815732122039fc8197317ec01701a83f0f2/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L245)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

If you go to the revision I wrote it on originally (r1 in this case), you can see. Here I meant "Test attributes with skipeed braced element in between.",
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 340 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni1D4VW8tzTVTVt23lm:-Ni4uR_f4xHhY4Izlxlg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L340)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I still see it.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 395 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni1DCoj-U3NF06NZplz:-Ni4vB5BDtdL6qhh_4NE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L395)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I still see it
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 454 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni1DJWMAZawhTGKiMOF:-Ni4vGQU4jzCW-2-XOS3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L454)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I still see it
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 517 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni1EBC_0GDPgMa9ta_y:-Ni4vLLB6jW5GI7jH21O:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L517)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I still see it.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 577 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni1ERW46JZu-lOS1ty0:-Ni4vPvb72MDpdsDvbu7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L577)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I still see it
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 651 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni1EgPfDsJ5YoLuW1hC:-Ni4vQqO3UgfrBJC9S6h:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L651)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I still see it
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 290 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni4jmk08RcGNv51Z3xC:-Ni4uA7m2Ya31_Ox_1M4:b-n7amxm) ([raw file](https://github.com/starkware-libs/cairo/blob/a2917b15c691974693dc7156af8ff39c260ccd66/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L290)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

can ignore
</blockquote></details>

It'll hide the first attribute.
___
*[`crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors` line 660 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni4mFFM0N2GWcfPsAWc:-Ni4wL9D9UtA8aLtucov:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a2917b15c691974693dc7156af8ff39c260ccd66/crates/cairo-lang-parser/src/parser_test_data/partial_trees_with_trivia/attribute_errors#L660)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Maybe don't ignore this so we at least see which attr it is. It doesn't save a lot of test anyway.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-01 08:08 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test_data/full_trees/test1` line 41 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni4iYTlDwMnNd8Spbgk:-Ni8tEdZ8RZ_TFLM5co9:b-zebm3s) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/full_trees/test1#L41)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I don't follow. Also - it was ok before your PR, now it's not. The missing tokens diag should point to after the attr, where it's missing.
</blockquote></details>

I changed the behaviour to point at the node.
Anyway, added a flag to support both options.


<!-- Sent from Reviewable.io -->

2023-11-01 08:49 UTC, yuvalsw requested changes
> Reviewed 4 of 4 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: all files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 2216 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni8zSKNE4K-pCoaCKDU:-Ni8zSKNE4K-pCoaCKDV:b9pha9v) ([raw file](https://github.com/starkware-libs/cairo/blob/ca3b62287e0a88db9f5ad0acfe51fa04928a5e5a/crates/cairo-lang-parser/src/parser.rs#L2216)):*
> ```XML
>         
>         // Remove the node width, as it was already taken, and fix for the last token not being
>         // considered in the current offset.
> ```

fix/split the comment.



_Code quote:_
```XML
        // Remove the node width, as it was already taken, and fix for the last token not being
        // considered in the current offset.
```
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2221 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni8zrfP1nbQxBgIFDpE:-Ni8zrfP1nbQxBgIFDpF:b-pb44rm) ([raw file](https://github.com/starkware-libs/cairo/blob/ca3b62287e0a88db9f5ad0acfe51fa04928a5e5a/crates/cairo-lang-parser/src/parser.rs#L2221)):*
> ```XML
>         let diag_end = end_of_node_offset.sub_width(node_trailing_trivia_width);
>         let diag_start = if diagnostic_pointing_at_node {
>             let node_leading_trivia_width = leading_trivia_width(self.db, trivium_green.0);
> ```

inline
___
*[`crates/cairo-lang-parser/src/parser_test_data/full_trees/test1` line 41 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni4iYTlDwMnNd8Spbgk:-Ni90wzU73TP8-gb-clB:b-izwowe) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/full_trees/test1#L41)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

I changed the behaviour to point at the node.
Anyway, added a flag to support both options.
</blockquote></details>

when should this flag be true?


<!-- Sent from Reviewable.io -->

2023-11-01 09:31 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: all files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 2216 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni8zSKNE4K-pCoaCKDU:-Ni9Cry38dWGTdRyKhoz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ca3b62287e0a88db9f5ad0acfe51fa04928a5e5a/crates/cairo-lang-parser/src/parser.rs#L2216)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

fix/split the comment.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser_test_data/full_trees/test1` line 41 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni4iYTlDwMnNd8Spbgk:-Ni9BgTt0dJoBXOqAKHX:bmbdb6i) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/full_trees/test1#L41)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

when should this flag be true?
</blockquote></details>

If we the diagnostic kind indicates that the node was skipped, but we don't report what is missing. I can remove it if you think so.


<!-- Sent from Reviewable.io -->

2023-11-01 10:06 UTC, yuvalsw requested changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-parser/src/parser_test_data/full_trees/test1` line 41 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni4iYTlDwMnNd8Spbgk:-Ni9LJ0OEOlM8QVqfBQq:b-ylhi16) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/full_trees/test1#L41)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

If we the diagnostic kind indicates that the node was skipped, but we don't report what is missing. I can remove it if you think so.
</blockquote></details>

Yes, let's remove it. I don't know if we'll have such a case


<!-- Sent from Reviewable.io -->

2023-11-01 11:14 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser_test_data/full_trees/test1` line 41 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4296#-Ni4iYTlDwMnNd8Spbgk:-Ni9_zGW8pDCt1vxaUS5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/56736b03f75deb8b92c089c3cb0a82576ac4fca5/crates/cairo-lang-parser/src/parser_test_data/full_trees/test1#L41)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Yes, let's remove it. I don't know if we'll have such a case
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-01 14:01 UTC, yuvalsw requested changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 2197 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NiAAW05-kIcE3lkXECZ:-NiAAW05-kIcE3lkXEC_:b-c4y6ew) ([raw file](https://github.com/starkware-libs/cairo/blob/be987490db11d2e4cc25dcf4e8029757dbc79878/crates/cairo-lang-parser/src/parser.rs#L2197)):*
> ```XML
>     /// reporting an error, appending the node to the current trivia as skipped, and continuing
>     /// the compilation as if it wasn't there. The diagnostic can either point to the node, or
>     /// after it, depending on `diagnostic_pointing_at_node`.
> ```

Same for `skip_taken_node_and_return_missing`



_Suggestion:_
```XML
    /// Skips the given node which is a variant of `SkippedNode` and is already taken. A skipped
    /// node is a node which is not expected where it is found. Skipping this node means
    /// reporting the given error (pointing to right after the node), appending the node to the current trivia as skipped, and continuing
    /// the compilation as if it wasn't there. 
```


<!-- Sent from Reviewable.io -->

2023-11-01 14:48 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-parser/src/parser.rs` line 2197 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4296#-NiAAW05-kIcE3lkXECZ:-NiAL5sU9s9peqV2aNZl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/be987490db11d2e4cc25dcf4e8029757dbc79878/crates/cairo-lang-parser/src/parser.rs#L2197)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Same for `skip_taken_node_and_return_missing`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-01 15:59 UTC, yuvalsw approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2023-11-01 15:59 UTC, yuvalsw approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296#-:-NiAbA9S-lkszOt91P_s:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2023-11-02 07:42 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4296#-:-NiDyyDUDn8U8KFtlAD0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2023-11-02 07:57 UTC, merged