Moved corelib to be new prelude based.
starkware-libs/cairo pull request #4306
Opened 2023-10-25 19:53 UTC by orizi

**Stack**:
- #4305
- #4304
- #4303
- #4301
- #4300
- #4299

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2023-10-29 13:20 UTC, yuvalsw requested changes
> Reviewed 80 of 82 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4306)* status: all files reviewed, 15 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/byte_array.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvTniDAWgCxTM2xhjb:-NhvTniDAWgCxTM2xhjc:b-p9rbqx) ([raw file](https://github.com/starkware-libs/cairo/blob/0b93e73002e1e0b25845c68631455bb3bfeb6011/corelib/src/byte_array.cairo#L1)):*
> ```Cairo
> use core::array::{ArrayTrait, SpanTrait};
> ```

is there any way to make sure you haven't missed any usage of a path without core:: (mainly in fully qualified functions, traits etc.)?
___
*[`corelib/src/panics.cairo` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvUbro7MHjQoKWSWRJ:-NhvUbro7MHjQoKWSWRK:b9fx839) ([raw file](https://github.com/starkware-libs/cairo/blob/0b93e73002e1e0b25845c68631455bb3bfeb6011/corelib/src/panics.cairo#L10)):*
> ```Cairo
> }
> 
> extern fn panic(data: Array<felt252>) -> core::never;
> ```

don't we want never in the prelude?



_Code quote:_
```Cairo
core::never
```
___
*[`corelib/src/poseidon.cairo` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvUh329LBd74npxrtz:-NhvUh329LBd74npxru-:b-njs0cl) ([raw file](https://github.com/starkware-libs/cairo/blob/0b93e73002e1e0b25845c68631455bb3bfeb6011/corelib/src/poseidon.cairo#L2)):*
> ```Cairo
> use core::array::Span;
> use core::array::SpanTrait;
> ```

merge.



_Code quote:_
```Cairo
use core::array::Span;
use core::array::SpanTrait;
```
___
*[`corelib/src/result.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvUm4p5R97UcIxHz_l:-NhvUm4p5R97UcIxHz_m:bl9wj5g) ([raw file](https://github.com/starkware-libs/cairo/blob/0b93e73002e1e0b25845c68631455bb3bfeb6011/corelib/src/result.cairo#L1)):*
> ```Cairo
> use core::array::ArrayTrait;
> ```

merge with third.
___
*[`corelib/src/serde.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvUoJdCDl96hZWMgH3:-NhvUoJdCDl96hZWMgH4:b-7mt60d) ([raw file](https://github.com/starkware-libs/cairo/blob/0b93e73002e1e0b25845c68631455bb3bfeb6011/corelib/src/serde.cairo#L1)):*
> ```Cairo
> use core::array::ArrayTrait;
> ```

merge
___
*[`corelib/src/starknet/eth_address.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvVW5EAP6D8HX71biA:-NhvVW5EAP6D8HX71biB:b-r3xbyc) ([raw file](https://github.com/starkware-libs/cairo/blob/0b93e73002e1e0b25845c68631455bb3bfeb6011/corelib/src/starknet/eth_address.cairo#L1)):*
> ```Cairo
> use core::debug::PrintTrait;
> ```

consider removing + fully qualify in the usage.
___
*[`corelib/src/starknet/eth_signature.cairo` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvVgYY6K4CVBzXbSdu:-NhvVgYY6K4CVBzXbSdv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0b93e73002e1e0b25845c68631455bb3bfeb6011/corelib/src/starknet/eth_signature.cairo#L2)):*
> ```Cairo
> use core::option::OptionTrait;
> use starknet::{
> ```





_Suggestion:_
```Cairo
core::starknet::{
```
___
*[`corelib/src/starknet/info.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvVtLeCm3oPhnfk17r:-NhvVtLeCm3oPhnfk17s:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0b93e73002e1e0b25845c68631455bb3bfeb6011/corelib/src/starknet/info.cairo#L1)):*
> ```Cairo
> use starknet::{
> ```





_Suggestion:_
```Cairo
core::starknet::{
```
___
*[`corelib/src/starknet/secp256_trait.cairo` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvVzVxEj_UpGnT80tp:-NhvVzVxEj_UpGnT80tq:bx0isym) ([raw file](https://github.com/starkware-libs/cairo/blob/0b93e73002e1e0b25845c68631455bb3bfeb6011/corelib/src/starknet/secp256_trait.cairo#L4)):*
> ```Cairo
> use core::math::{u256_mul_mod_n, inv_mod};
> use core::option::OptionTrait;
> use starknet::{eth_address::U256IntoEthAddress, EthAddress, SyscallResult, SyscallResultTrait};
> ```

I guess you didn't prefix starknet with core:: as it's not going to remain there. But I think that as long as it is there, we should be consistent and future proof.

There are more occurrences I didn't comment on.



_Suggestion:_
```Cairo
core::starknet
```
___
*[`corelib/src/starknet/testing.cairo` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvWSYB-dMcAuy7ftiz:-NhvWSYB-dMcAuy7ftj-:b-7mt60d) ([raw file](https://github.com/starkware-libs/cairo/blob/0b93e73002e1e0b25845c68631455bb3bfeb6011/corelib/src/starknet/testing.cairo#L2)):*
> ```Cairo
> use starknet::ContractAddress;
> use core::array::ArrayTrait;
> ```

merge
___
*[`corelib/src/starknet/testing.cairo` line 76 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvWY5e3sg5QbI-0uhA:-NhvWY5e3sg5QbI-0uhB:b-y94hal) ([raw file](https://github.com/starkware-libs/cairo/blob/0b93e73002e1e0b25845c68631455bb3bfeb6011/corelib/src/starknet/testing.cairo#L76)):*
> ```Cairo
> fn pop_log_raw(address: ContractAddress) -> Option<(Span<felt252>, Span<felt252>)> {
>     let mut log = cheatcode::<'pop_log'>(array![address.into()].span());
>     Option::Some((Serde::deserialize(ref log)?, Serde::deserialize(ref log)?,))
> ```

no need to add use core::serde::Serde?
___
*[`corelib/src/test/secp256r1_test.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvXCij6Cy4MhTH-f1L:-NhvXCij6Cy4MhTH-f1M:b-5m6cyk) ([raw file](https://github.com/starkware-libs/cairo/blob/0b93e73002e1e0b25845c68631455bb3bfeb6011/corelib/src/test/secp256r1_test.cairo#L1)):*
> ```Cairo
> use starknet::{secp256r1::Secp256r1Impl, SyscallResultTrait};
> ```

move to third, or even consider merging all 3 lines.



_Code quote:_
```Cairo
secp256r1::Secp256r1Impl
```
___
*[`crates/cairo-lang-plugins/src/plugins/derive/hash.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvYVsuD1BqkZtDYVjc:-NhvYVsuD1BqkZtDYVjd:bolc0cq) ([raw file](https://github.com/starkware-libs/cairo/blob/0b93e73002e1e0b25845c68631455bb3bfeb6011/crates/cairo-lang-plugins/src/plugins/derive/hash.rs#L50)):*
> ```XML
>     );
>     let impl_additional_generics = info.generics.format_generics_with_trait_params_only(|t| {
>         vec![format!("+core::hash::Hash<{t}, __State, __SHashState>"), format!("+Drop<{t}>")]
> ```

how is this related? / why is this needed?



_Code quote:_
```XML
 __State, __SHashState
```
___
*[`crates/cairo-lang-plugins/src/plugins/derive/serde.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvYyRa4ldwh_CfmqV_:-NhvYyRa4ldwh_CfmqVa:bvia932) ([raw file](https://github.com/starkware-libs/cairo/blob/529a7e6461df84b505833b157512135dc180913e/crates/cairo-lang-plugins/src/plugins/derive/serde.rs#L87)):*
> ```XML
>             }}
>             fn deserialize(ref serialized: array::Span<felt252>) -> Option<{full_typename}> {{
>                 {deserialize_body}
> ```

Better have as explicit code as possible in generated code (e.g. if Array/Serde are also defined locally). In the whole file, I'd change to core::array::... / core::serde::...



_Code quote:_
```XML
                    variants.iter().enumerate().map(|(idx, variant)| {
                    format!(
                        "{ty}::{variant}(x) => {{ serde::Serde::serialize(@{idx}, ref output); \
                        serde::Serde::serialize(x, ref output); }},",
                        variant=variant.name,
                    )
                }).join("\n    ")}
            }
            TypeVariantInfo::Struct(members) => members
                .iter()
                .map(|member| {
                    format!(
                        "serde::Serde::serialize(self.{member}, ref output)",
                        member = member.name
                    )
                })
                .join(";\n"),
            TypeVariantInfo::Extern => {
                result.diagnostics.push(unsupported_for_extern_diagnostic(st [...]

2023-10-29 15:35 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4306)* status: 73 of 83 files reviewed, 15 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/byte_array.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvTniDAWgCxTM2xhjb:-NhvoPi9E33VccK62OQj:btmqwrj) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/byte_array.cairo#L1)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

is there any way to make sure you haven't missed any usage of a path without core:: (mainly in fully qualified functions, traits etc.)?
</blockquote></details>

any one i missed generates diagnostics.
___
*[`corelib/src/panics.cairo` line 10 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvUbro7MHjQoKWSWRJ:-NhvoZ0c7eWvBXNDr9lq:b-qxm5bc) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/panics.cairo#L10)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

don't we want never in the prelude?
</blockquote></details>

i don't think so.
___
*[`corelib/src/poseidon.cairo` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvUh329LBd74npxrtz:-Nhvod5f1itv4KMLUPmk:b-fduwkt) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/poseidon.cairo#L2)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

merge.
</blockquote></details>

not for this PR.
___
*[`corelib/src/result.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvUm4p5R97UcIxHz_l:-NhvofnT0dmqAsn0zsVr:bcz4agc) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/result.cairo#L1)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

merge with third.
</blockquote></details>

rather not do cosmetics in this PR.
___
*[`corelib/src/serde.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvUoJdCDl96hZWMgH3:-NhvpdYlC4WFfnMaB0JA:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/serde.cairo#L1)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

merge
</blockquote></details>

.
___
*[`corelib/src/starknet/eth_address.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvVW5EAP6D8HX71biA:-Nhvon6g2WRV9Fk8rxUL:by3fb0j) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/starknet/eth_address.cairo#L1)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

consider removing + fully qualify in the usage.
</blockquote></details>

currently not removing - as this may cause breakages - it is an another discussion.
___
*[`corelib/src/starknet/eth_signature.cairo` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvVgYY6K4CVBzXbSdu:-Nhvovk051Oy7CFE_UnS:b-d4sv51) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/starknet/eth_signature.cairo#L2)):*
> ```Cairo
> use core::option::OptionTrait;
> use starknet::{
> ```

starknet should in the end be a whole different library - i generally prefer to use the fact that it is in the prelude.
___
*[`corelib/src/starknet/info.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvVtLeCm3oPhnfk17r:-Nhvp3efEVcLAUe9hdAs:b-7ropln) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/starknet/info.cairo#L1)):*
> ```Cairo
> use starknet::{
> ```

ditto
___
*[`corelib/src/starknet/secp256_trait.cairo` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvVzVxEj_UpGnT80tp:-Nhvp5Bf3f5b5cdyaQOr:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/starknet/secp256_trait.cairo#L4)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I guess you didn't prefix starknet with core:: as it's not going to remain there. But I think that as long as it is there, we should be consistent and future proof.

There are more occurrences I didn't comment on.
</blockquote></details>

.
___
*[`corelib/src/starknet/testing.cairo` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvWSYB-dMcAuy7ftiz:-Nhvp6ir-_Aqo_r1UP5p:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/starknet/testing.cairo#L2)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

merge
</blockquote></details>

.
___
*[`corelib/src/starknet/testing.cairo` line 76 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvWY5e3sg5QbI-0uhA:-Nhvp8-f-KXg87tRDTwV:bebkgj8) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/starknet/testing.cairo#L76)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

no need to add use core::serde::Serde?
</blockquote></details>

it is in the prelude which is unavoidable.
___
*[`corelib/src/test/secp256r1_test.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvXCij6Cy4MhTH-f1L:-NhvpDHe5vgSe8K9IfiM:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/test/secp256r1_test.cairo#L1)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

move to third, or even consider merging all 3 lines.
</blockquote></details>

.
___
*[`crates/cairo-lang-plugins/src/plugins/derive/hash.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvYVsuD1BqkZtDYVjc:-NhvpEShCQ-B_7DhnMjp:b-1h413q) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/crates/cairo-lang-plugins/src/plugins/derive/hash.rs#L50)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

how is this related? / why is this needed?
</blockquote></details>

the `Hash` qualification was required, so just shortened the line.
___
*[`crates/cairo-lang-plugins/src/plugins/derive/serde.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvYyRa4ldwh_CfmqV_:-Nhw3_elAMj4_JIlgoqb:bpvynjy) ([raw file](https://github.com/starkware-libs/cairo/blob/3e4abcf126229cedde35c6319fbab0d9efb0f241/crates/cairo-lang-plugins/src/plugins/derive/serde.rs#L87)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Better have as explicit code as possible in generated code (e.g. if Array/Serde are also defined locally). In the whole file, I'd change to core::array::... / core::serde::...
</blockquote></details>

unless we decide `Serde` is removed from Prelude (which is a valid decision) prelude is unavoidable, so have the code a little bit shorter is a little nicer.
___
*[`tests/bug_samples/issue3863.cairo` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-Nhv_Qvo4MjyeLuZur1-:-Nhw3Ny1DeLHZiPkH8OJ:b-jg2prg) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/tests/bug_samples/issue3863.cairo#L2)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

can remove.
</blockquote></details>

removed in one of the following PRs.


<!-- Sent from Reviewable.io -->

2023-10-30 09:52 UTC, yuvalsw requested changes
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4306)* status: all files reviewed, 6 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/byte_array.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvTniDAWgCxTM2xhjb:-Nhzx8vU7T72d4A2GZiT:b-ov9me6) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/byte_array.cairo#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

any one i missed generates diagnostics.
</blockquote></details>

Not if it's in the prelude.
I thought you want to prefix everything in the core with the full path, so that it will not need to change, no matter what changes we do in the prelude in the future. 
___
*[`corelib/src/starknet/eth_address.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvVW5EAP6D8HX71biA:-NhzxyVcBqr-ujYSTsDu:b-gcrnb1) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/starknet/eth_address.cairo#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

currently not removing - as this may cause breakages - it is an another discussion.
</blockquote></details>

It should not break. But anyway - ok in another PR (also ok to leave it)
___
*[`corelib/src/starknet/eth_signature.cairo` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvVgYY6K4CVBzXbSdu:-NhzyJ9P58vKLNpSZrjv:btkss6j) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/starknet/eth_signature.cairo#L2)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

starknet should in the end be a whole different library - i generally prefer to use the fact that it is in the prelude.
</blockquote></details>

Copying from my other comment to unite the discussion here:
I guess you didn't prefix starknet with core:: as it's not going to remain there. But I think that as long as it is there, we should be consistent and future proof.
___
*[`corelib/src/starknet/testing.cairo` line 76 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvWY5e3sg5QbI-0uhA:-NhzyV8bEAeQhxDVLwp_:b-oasf26) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/starknet/testing.cairo#L76)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it is in the prelude which is unavoidable.
</blockquote></details>

Again, I thought you wanted to prefix everything so that it keeps working no matter what changes we do in the prelude in the future.
___
*[`crates/cairo-lang-plugins/src/plugins/derive/hash.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvYVsuD1BqkZtDYVjc:-Nhzz1j2BKKkxgycbdkL:b-fnxyqz) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/crates/cairo-lang-plugins/src/plugins/derive/hash.rs#L50)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the `Hash` qualification was required, so just shortened the line.
</blockquote></details>

I quoted " __State, __SHashState". Why did you suddenly needed to add them?
___
*[`crates/cairo-lang-plugins/src/plugins/derive/serde.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvYyRa4ldwh_CfmqV_:-NhzzKRa1Kpemv0I9k8J:b-25xqlj) ([raw file](https://github.com/starkware-libs/cairo/blob/3e4abcf126229cedde35c6319fbab0d9efb0f241/crates/cairo-lang-plugins/src/plugins/derive/serde.rs#L87)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

unless we decide `Serde` is removed from Prelude (which is a valid decision) prelude is unavoidable, so have the code a little bit shorter is a little nicer.
</blockquote></details>

Same as other comment - I like it being future proof (as in future proof to whatever changes in the prelude we may make)


<!-- Sent from Reviewable.io -->

2023-10-30 14:18 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4306)* status: 82 of 83 files reviewed, 5 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/byte_array.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvTniDAWgCxTM2xhjb:-Ni-wYm1-6ZrNBjIV6KS:b-ubym5t) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/byte_array.cairo#L1)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Not if it's in the prelude.
I thought you want to prefix everything in the core with the full path, so that it will not need to change, no matter what changes we do in the prelude in the future.
</blockquote></details>

if it is in the prelude it is fine - that is the definition.
i don't think i understand.
___
*[`corelib/src/starknet/eth_signature.cairo` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvVgYY6K4CVBzXbSdu:-Ni-whhz0IXUIICO_b7j:b-iym0lr) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/starknet/eth_signature.cairo#L2)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Copying from my other comment to unite the discussion here:
I guess you didn't prefix starknet with core:: as it's not going to remain there. But I think that as long as it is there, we should be consistent and future proof.
</blockquote></details>

the this is anti-future proof if it should get out - we control the prelude.


<!-- Sent from Reviewable.io -->

2023-10-31 09:53 UTC, yuvalsw reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4306)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2023-11-01 07:01 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4306)* status: 79 of 83 files reviewed, 5 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/starknet/testing.cairo` line 76 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvWY5e3sg5QbI-0uhA:-Ni8fCbK7Vo7CYa_aPcD:bxmhkpd) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/starknet/testing.cairo#L76)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Again, I thought you wanted to prefix everything so that it keeps working no matter what changes we do in the prelude in the future.
</blockquote></details>

since we control both, this is an easy edit in the future (and when we actually have `pub` everything will be much easier)
___
*[`crates/cairo-lang-plugins/src/plugins/derive/hash.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvYVsuD1BqkZtDYVjc:-Ni8fWzNCLBBrMOyb7ui:bw4nqbe) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/crates/cairo-lang-plugins/src/plugins/derive/hash.rs#L50)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I quoted " __State, __SHashState". Why did you suddenly needed to add them?
</blockquote></details>

oh - the previous one was just entirely wrong.
will do in an unrelated PR.
___
*[`crates/cairo-lang-plugins/src/plugins/derive/serde.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvYyRa4ldwh_CfmqV_:-Ni8fkcv-s3Y6TKwKOGX:by5qv20) ([raw file](https://github.com/starkware-libs/cairo/blob/3e4abcf126229cedde35c6319fbab0d9efb0f241/crates/cairo-lang-plugins/src/plugins/derive/serde.rs#L87)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Same as other comment - I like it being future proof (as in future proof to whatever changes in the prelude we may make)
</blockquote></details>

this will require additional refactoring to actually fully not require `Serde` being available, so rather not for now.


<!-- Sent from Reviewable.io -->

2023-11-01 09:35 UTC, yuvalsw requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4306)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/byte_array.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvTniDAWgCxTM2xhjb:-Ni97egZ5xo9FA7OECiV:bg383et) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/byte_array.cairo#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if it is in the prelude it is fine - that is the definition.
i don't think i understand.
</blockquote></details>

I am talking about making the corelib future proof for prelude changes.
___
*[`crates/cairo-lang-plugins/src/plugins/derive/hash.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvYVsuD1BqkZtDYVjc:-Ni98CaO6ldFvBphXmDw:b-wiyrod) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/crates/cairo-lang-plugins/src/plugins/derive/hash.rs#L50)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

oh - the previous one was just entirely wrong.
will do in an unrelated PR.
</blockquote></details>

I still see it here. Please point to the other PR and LMK which one should be based on the other
___
*[`crates/cairo-lang-plugins/src/plugins/derive/serde.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvYyRa4ldwh_CfmqV_:-Ni98lPHDonjtD5m6YZq:b-fr0a7b) ([raw file](https://github.com/starkware-libs/cairo/blob/3e4abcf126229cedde35c6319fbab0d9efb0f241/crates/cairo-lang-plugins/src/plugins/derive/serde.rs#L87)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this will require additional refactoring to actually fully not require `Serde` being available, so rather not for now.
</blockquote></details>

This is actually more important than that (I forgot it from the first comment to the second). According to the order of resolution of paths, you first look for local items. That is, if someone defines a module named array/serde, the generated code would use it. Even worse, if it has the "right" content, it would not fail but use its functions/methods, changing the behavior. We need to enforce the generated code to use the corelib code.


<!-- Sent from Reviewable.io -->

2023-11-01 10:37 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4306)* status: all files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/byte_array.cairo` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvTniDAWgCxTM2xhjb:-Ni9K2WE8NbvPfjMmsDX:b-gnefsp) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/corelib/src/byte_array.cairo#L1)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I am talking about making the corelib future proof for prelude changes.
</blockquote></details>

so no way to fully test it - beside fully removing the prelude, which for some types wouldn't make sense.
for example - even in the corelib - i don't want to write `core::integer::u8`.
In anycase - the corelib itself is a good testament for if a prelude update is good IMO, so using these is fine. 
___
*[`crates/cairo-lang-plugins/src/plugins/derive/hash.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvYVsuD1BqkZtDYVjc:-Ni9Nbyy04iAPqZ-CJK7:b-6dykg5) ([raw file](https://github.com/starkware-libs/cairo/blob/f5dc8f9a0c66b989a2b5541d05898e780a343420/crates/cairo-lang-plugins/src/plugins/derive/hash.rs#L50)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I still see it here. Please point to the other PR and LMK which one should be based on the other
</blockquote></details>

https://reviewable.io/reviews/starkware-libs/cairo/4333
___
*[`crates/cairo-lang-plugins/src/plugins/derive/serde.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4306#-NhvYyRa4ldwh_CfmqV_:-Ni9KnhZ9UvFZYbaX7LG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3e4abcf126229cedde35c6319fbab0d9efb0f241/crates/cairo-lang-plugins/src/plugins/derive/serde.rs#L87)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This is actually more important than that (I forgot it from the first comment to the second). According to the order of resolution of paths, you first look for local items. That is, if someone defines a module named array/serde, the generated code would use it. Even worse, if it has the "right" content, it would not fail but use its functions/methods, changing the behavior. We need to enforce the generated code to use the corelib code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-01 14:21 UTC, yuvalsw approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 34 of 34 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4306#-:-NiAFcANDjytw-o9Z4-z:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2023-11-01 16:00 UTC, yuvalsw approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4306)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2023-11-01 16:52 UTC, merged