Made format, print and println support complex format strings.
starkware-libs/cairo pull request #4347
Opened 2023-11-02 12:40 UTC by orizi

**Stack**:
- #4346
- #4345

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2023-11-02 17:36 UTC, yuvalsw requested changes
> Reviewed 3 of 6 files at r1, 1 of 24 files at r2, 21 of 21 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4347)* status: 25 of 27 files reviewed, 27 unresolved discussions (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiG5t_O2j13kLPmUyu4:-NiG5t_O2j13kLPmUyu5:b-4r3ojz) (no related file):*
yet to review the inline macro modules (format/print)

___
___
*[`corelib/src/test/fmt_test.cairo` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFi28b8nCJg1f0VG_n:-NiFi28b8nCJg1f0VG_o:bhyoiah) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/corelib/src/test/fmt_test.cairo#L9)):*
> ```Cairo
>     assert(format!("no_format") == "no_format", 'no args bad formatting');
>     assert(format!("{}{}", 12_usize, 14_u32) == "1214", 'two args bad formatting');
>     assert(format!("{}{1}", 12_usize, 14_u32) == "1214", 'possitional mix bad formatting');
> ```

please also add



_Suggestion:_
```Cairo
assert(format!("{}{1}", 12_usize, 14_u32) == "1214", 'possitional mix bad formatting');
assert(format!("{0}{0}", 12_usize) == "1212", 'something');
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/inline_macros` line 141 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFivt64zEdbspnXwPU:-NiFivt64zEdbspnXwPV:b-blpzkr) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/crates/cairo-lang-semantic/src/expr/test_data/inline_macros#L141)):*
> ```
> //! > ==========================================================================
> 
> //! > Test bad format! macros
> ```

please add out of range positional argument, and {ba} for ba that doesn't exist.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/inline_macros` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFgcy-2A_X70fb7KA0:-NiFgcy-2A_X70fb7KA1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/crates/cairo-lang-semantic/src/expr/test_data/inline_macros#L174)):*
> ```
>           ^
> 
> error: Plugin diagnostic: Argument must be a string literal.
> ```





_Suggestion:_
```
tic: First argument mu
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/inline_macros` line 179 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFgjKLELGI7EDhbUpA:-NiFgjKLELGI7EDhbUpB:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/crates/cairo-lang-semantic/src/expr/test_data/inline_macros#L179)):*
> ```
>            ^^
> 
> error: Plugin diagnostic: Unused argument.
> ```





_Suggestion:_
```
tic: Expected 1 argument after format string, found 2.
```
___
*[`crates/cairo-lang-semantic/src/expr/test_data/inline_macros` line 184 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFguUp4HOWlY2KXsJT:-NiFguUp4HOWlY2KXsJU:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/crates/cairo-lang-semantic/src/expr/test_data/inline_macros#L184)):*
> ```
>                      ^
> 
> error: Plugin diagnostic: More format specifiers than arguments.
> ```





_Suggestion:_
```
ugin diagnostic: Expected 2 arguments after format string, found 1
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/formatted.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFjExL8_SWiLYuuxBC:-NiFjExL8_SWiLYuuxBD:bg515h6) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/crates/cairo-lang-semantic/src/inline_macros/formatted.rs#L11)):*
> ```XML
> use super::{try_extract_unnamed_arg, unsupported_bracket_diagnostic};
> 
> /// Information about a formatted string macro.
> ```

Similarly change below all "formatted string macro" - it's not clear



_Suggestion:_
```XML
 Information about a macro that is based on a format string.
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/formatted.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFpoRF9vfc4a9J325g:-NiFpoRF9vfc4a9J325h:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/crates/cairo-lang-semantic/src/inline_macros/formatted.rs#L12)):*
> ```XML
> 
> /// Information about a formatted string macro.
> pub struct FormattedInfo {
> ```

?



_Suggestion:_
```XML
FormattingInfo
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/formatted.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFjLF01mU7OLeJn9FB:-NiFjLF01mU7OLeJn9FC:bw2k2xo) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/crates/cairo-lang-semantic/src/inline_macros/formatted.rs#L13)):*
> ```XML
> /// Information about a formatted string macro.
> pub struct FormattedInfo {
>     /// The formatter to add the formatted string into.
> ```

The formatter will have more roles later.



_Suggestion:_
```XML
/// The relevant formatter.
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/formatted.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFoRBp7WFPjYP1uXEZ:-NiFoRBp7WFPjYP1uXE_:burxzv5) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/crates/cairo-lang-semantic/src/inline_macros/formatted.rs#L33)):*
> ```XML
>         if !matches!(
>             arguments,
>             ast::WrappedArgList::ParenthesizedArgList(_) | ast::WrappedArgList::BracedArgList(_)
> ```

why support braces?



_Code quote:_
```XML
 ast::WrappedArgList::BracedArgList(_)
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/formatted.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFocWE95wqbi1f7uO6:-NiFocWE95wqbi1f7uO7:b-lx5kyj) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/crates/cairo-lang-semantic/src/inline_macros/formatted.rs#L39)):*
> ```XML
>         // `unwrap` is ok because the above `matches` condition ensures it's not None (unless the
>         // pattern contains the `Missing` variant).
>         let macro_arg_list = arguments.arg_list(db).unwrap();
> ```

better do `let x = ast::WrappedArgList::ParenthesizedArgList(_) = ... else {}` and use x, rather than match and then unwrap. (the macro does it as it needs to support unknown number of variants in the or pattern)
___
*[`crates/cairo-lang-semantic/src/inline_macros/formatted.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiG5cFUC6D2ClSAHlCG:-NiG5cFUC6D2ClSAHlCH:b5759hg) ([raw file](https://github.com/starkware-libs/cairo/blob/f9fa261059b07cc76c87862a07a616b32c05f2fb/crates/cairo-lang-semantic/src/inline_macros/formatted.rs#L14)):*
> ```XML
> pub struct FormattedInfo {
>     /// The formatter to add the formatted string into.
>     pub formatter: RewriteNode,
> ```

It confused me as initially I tried to understand how it's the formatter (as in the Formatter struct).



_Suggestion:_
```XML
pub formatter_var_name: RewriteNode,
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/formatted.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFs-cFDyqlQAMqAhzc:-NiFs-cFDyqlQAMqAhzd:b-k4y21i) ([raw file](https://github.com/starkware-libs/cairo/blob/f9fa261059b07cc76c87862a07a616b32c05f2fb/crates/cairo-lang-semantic/src/inline_macros/formatted.rs#L50)):*
> ```XML
>                 }]);
>             };
>             (RewriteNode::new_trimmed(formatter.as_syntax_node()), without_formatter)
> ```

I don't understand this logic and don't see any case where this function is called with None for the defined_formatter.
Also, with it, I don't why `without_formatter` is called that way. How can the formatter be provided by the arguments?
If there is a specific macro that should use it in the future (write?) than it should extract the first arg [...]

2023-11-03 20:34 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4347)* status: 21 of 28 files reviewed, 25 unresolved discussions (waiting on @yuvalsw)

___
*[`corelib/src/test/fmt_test.cairo` line 9 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFi28b8nCJg1f0VG_n:-NiKN0PD9fD-IRoN5CZZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/corelib/src/test/fmt_test.cairo#L9)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please also add
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/inline_macros` line 141 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFivt64zEdbspnXwPU:-NiKRSIuEeMj69VID14f:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/crates/cairo-lang-semantic/src/expr/test_data/inline_macros#L141)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please add out of range positional argument, and {ba} for ba that doesn't exist.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/inline_macros` line 174 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFgcy-2A_X70fb7KA0:-NiKRU170AXl4DFrzmgY:b-g6ddyz) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/crates/cairo-lang-semantic/src/expr/test_data/inline_macros#L174)):*
> ```
>           ^
> 
> error: Plugin diagnostic: Argument must be a string literal.
> ```

it points to the variable, no need for the name, as it would make the wrapping error not correct.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/inline_macros` line 179 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFgjKLELGI7EDhbUpA:-NiLj1C01rSD-_sfgKXI:byal1e9) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/crates/cairo-lang-semantic/src/expr/test_data/inline_macros#L179)):*
> ```
>            ^^
> 
> error: Plugin diagnostic: Unused argument.
> ```

it is unused - pointing at the missing variable itself is both easier and clearer.
___
*[`crates/cairo-lang-semantic/src/expr/test_data/inline_macros` line 184 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFguUp4HOWlY2KXsJT:-NiLj8I2ElXXsBO9zn-U:bw72ju3) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/crates/cairo-lang-semantic/src/expr/test_data/inline_macros#L184)):*
> ```
>                      ^
> 
> error: Plugin diagnostic: More format specifiers than arguments.
> ```

Clear enough that way IMO - and required much
___
*[`crates/cairo-lang-semantic/src/inline_macros/formatted.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFjExL8_SWiLYuuxBC:-NiLlSvMDqAf4Rg_Aied:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/crates/cairo-lang-semantic/src/inline_macros/formatted.rs#L11)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Similarly change below all "formatted string macro" - it's not clear
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/inline_macros/formatted.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFpoRF9vfc4a9J325g:-NiLlTOY8DbIsbG3F_X3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/crates/cairo-lang-semantic/src/inline_macros/formatted.rs#L12)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/inline_macros/formatted.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFjLF01mU7OLeJn9FB:-NiLlV1m3ODFecd2DcL7:b7d2efj) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/crates/cairo-lang-semantic/src/inline_macros/formatted.rs#L13)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

The formatter will have more roles later.
</blockquote></details>

role changed
___
*[`crates/cairo-lang-semantic/src/inline_macros/formatted.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFoRBp7WFPjYP1uXEZ:-NiLltQH4C4yHaDBozVY:b-rya0h6) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/crates/cairo-lang-semantic/src/inline_macros/formatted.rs#L33)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why support braces?
</blockquote></details>

like rust - allows easy multi-lining.
___
*[`crates/cairo-lang-semantic/src/inline_macros/formatted.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFocWE95wqbi1f7uO6:-NiLpdn17BTpgiTRXpfX:b-al0wup) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/crates/cairo-lang-semantic/src/inline_macros/formatted.rs#L39)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

better do `let x = ast::WrappedArgList::ParenthesizedArgList(_) = ... else {}` and use x, rather than match and then unwrap. (the macro does it as it needs to support unknown number of variants in the or pattern)
</blockquote></details>

true if we support only one.
___
*[`crates/cairo-lang-semantic/src/inline_macros/formatted.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiG5cFUC6D2ClSAHlCG:-NiLlbvVEyR5brLz5ElI:b-fjgm8a) ([raw file](https://github.com/starkware-libs/cairo/blob/f9fa261059b07cc76c87862a07a616b32c05f2fb/crates/cairo-lang-semantic/src/inline_macros/formatted.rs#L14)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

It confused me as initially I tried to understand how it's the formatter (as in the Formatter struct).
</blockquote></details>

adding `node`.
___
*[`crates/cairo-lang-semantic/src/inline_macros/formatted.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFs-cFDyqlQAMqAhzc:-NiLm5A-4JPTqY8C8trE:b-3kg2r4) ([raw file](https://github.com/starkware-libs/cairo/blob/f9fa261059b07cc76c87862a07a616b32c05f2fb/crates/cairo-lang-semantic/src/inline_macros/formatted.rs#L50)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I don't understand this logic and don't see any case where this function is called with None for the defined_formatter.
Also, with it, I don't why `without_formatter` is called that way. How can the formatter be provided by the arguments?
If there is a specific macro that should use it in the future (write?) than it should extract the first argument outside of this function. And this function would get a list of arguments (format string + args). This is also relevant e.g. for `assert!` in which the first arg is a condition, and then the rest are format string + args.
</blockquote></details>

changed - now it is ALWAYS none - as it is for write macro.
___
*[`crates/cairo-lang-semantic/src/inline_macros/formatted.rs` line 78 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFvIw23atYm0aNzsq4:-NiLmTIBAKk8idaoESVe:b-rlkps9) ([raw file](https://github.com/starkware-libs/cairo/blob/f9fa261059b07cc76c87862a07a616b32c05f2fb/crates/cairo-lang-semantic/src/inline_macros/formatted.rs#L78)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Consider instead: (one diag instead of many )
You can also adjust if you want to point at the first and not on all. Actually, if you want that, you can stop extracting in the first named arg.
</blockquote></details>

i want to get all the diagnostics - much clearer than getting just the first one in the general case.
___
*[`crates/cairo-lang-semantic/src/inline_macros/formatted.rs` line 85 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFxDIm0HY-N298fZCj:-NiLmkF-08sv-UcpKnL-:b-896fix) ( [...]

2023-11-05 14:35 UTC, gilbens-starkware requested changes
> Reviewed 3 of 7 files at r5, 3 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4347)* status: all files reviewed, 32 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/inline_macros` line 380 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiUelDOClTmUXGwCeYP:-NiUelDOClTmUXGwCeYQ:b-hqjzub) ([raw file](https://github.com/starkware-libs/cairo/blob/cffc7815ed3e5fedb14a3b4f8bb9ad05d5dd7a68/crates/cairo-lang-semantic/src/expr/test_data/inline_macros#L380)):*
> ```
> 
>    // Bad brackets.
>    format!["{}", ba];
> ```

Add TODO to improve diagnostic (it points to 'write!`). 
___
*[`crates/cairo-lang-semantic/src/inline_macros/format.rs` line 35 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiUgBVh7qWU2MdUDkTa:-NiUgBVh7qWU2MdUDkTb:b-i3btcp) ([raw file](https://github.com/starkware-libs/cairo/blob/cffc7815ed3e5fedb14a3b4f8bb9ad05d5dd7a68/crates/cairo-lang-semantic/src/inline_macros/format.rs#L35)):*
> ```XML
>                     }}
>                 ",
>                 f = "__formatter_for_format_macro_",
> ```

Same in print.



_Suggestion:_
```XML
__formatter_for_format_macro__
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/formatted.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFoRBp7WFPjYP1uXEZ:-NiUhYsQDIj-eQcgNZKH:b-vmemwn) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/crates/cairo-lang-semantic/src/inline_macros/formatted.rs#L33)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

like rust - allows easy multi-lining.
</blockquote></details>

Rust also supports brackets.
___
*[`crates/cairo-lang-semantic/src/inline_macros/formatted.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiG5cFUC6D2ClSAHlCG:-NiU_ijl1eQJkimyFiDo:b-pcaohg) ([raw file](https://github.com/starkware-libs/cairo/blob/f9fa261059b07cc76c87862a07a616b32c05f2fb/crates/cairo-lang-semantic/src/inline_macros/formatted.rs#L14)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

adding `node`.
</blockquote></details>

Consider `formatter_arg_node`.
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 13 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiUMmGX1zIfSRjMwUsb:-NiUMmGX1zIfSRjMwUsc:brejra4) ([raw file](https://github.com/starkware-libs/cairo/blob/cffc7815ed3e5fedb14a3b4f8bb9ad05d5dd7a68/crates/cairo-lang-semantic/src/inline_macros/write.rs#L13)):*
> ```XML
> use super::{try_extract_unnamed_arg, unsupported_bracket_diagnostic};
> 
> /// Macro for printing.
> ```

Same below



_Suggestion:_
```XML
/// Macro for writing into a formatter.
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 89 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiUdsjoDrbUKCswW3ya:-NiUdsjoDrbUKCswW3yb:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/cffc7815ed3e5fedb14a3b4f8bb9ad05d5dd7a68/crates/cairo-lang-semantic/src/inline_macros/write.rs#L89)):*
> ```XML
> impl FormattingInfo {
>     /// Extracts the arguments from a formatted string macro.
>     /// `defined_formatter` should be provided if it is defined outside.
> ```

remove



_Code quote:_
```XML
/// `defined_formatter` should be provided if it is defined outside.
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 105 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiUiurg1F5AqN_c4-Uy:-NiUiurg1F5AqN_c4-Uz:bm4dtl9) ([raw file](https://github.com/starkware-libs/cairo/blob/cffc7815ed3e5fedb14a3b4f8bb9ad05d5dd7a68/crates/cairo-lang-semantic/src/inline_macros/write.rs#L105)):*
> ```XML
>         let macro_arg_list = arguments.arg_list(db).unwrap();
>         let macro_arg_list_elements = macro_arg_list.elements(db);
>         let Some((formatter, without_formatter)) = macro_arg_list_elements.split_first() else {
> ```

To be consistent with the splitting below.



_Suggestion:_
```XML
(formatter_arg, without_formatter_args)
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 198 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiUmjQSDzTNL5CR2-Lz:-NiUmjQSDzTNL5CR2-M-:b-v9m3o) ([raw file](https://github.com/starkware-libs/cairo/blob/cffc7815ed3e5fedb14a3b4f8bb9ad05d5dd7a68/crates/cairo-lang-semantic/src/inline_macros/write.rs#L198)):*
> ```XML
>                     diagnostics.push(PluginDiagnostic {
>                         stable_ptr: self.format_string_arg.as_syntax_node().stable_ptr(),
>                         message: "Invalid format string: expected `}` or variable name."
> ```

Add a test for it, for example `write!("{x{}}", x);`



_Code quote:_
```XML
message: "Invalid format string: expected `}` or variable name."
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 290 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiUqsSN4JzlxDEkZwl0:-NiUqsSN4JzlxDEkZwl1:b6risfs) ([raw file](https://github.com/starkware-libs/cairo/blob/cffc7815ed3e5fedb14a3b4f8bb9ad05d5dd7a68/crates/cairo-lang-semantic/src/inline_macros/write.rs#L290)):*
> ```XML
>     }
> 
>     /// Appends a formatted argument to the formatter, flushing the pending bytes if necessary.
> ```

Doc that it only opens the match on the result, and it is closed in the main loop.


<!-- Sent from Reviewable.io -->

2023-11-05 15:13 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4347)* status: all files reviewed, 29 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/inline_macros/formatted.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiFoRBp7WFPjYP1uXEZ:-NiUyUZA0C2UIfvHlxCs:b9j796p) ([raw file](https://github.com/starkware-libs/cairo/blob/121ab1fa4c5e4fb56899c9147ee51fbfa1c5259b/crates/cairo-lang-semantic/src/inline_macros/formatted.rs#L33)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Rust also supports brackets.
</blockquote></details>

leaving only ( ) for now.
___
*[`crates/cairo-lang-semantic/src/inline_macros/formatted.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiG5cFUC6D2ClSAHlCG:-NiUyJk09l-Fz3qhNtYP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f9fa261059b07cc76c87862a07a616b32c05f2fb/crates/cairo-lang-semantic/src/inline_macros/formatted.rs#L14)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Consider `formatter_arg_node`.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 13 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiUMmGX1zIfSRjMwUsb:-NiUww6c76_G4xBMGjV8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cffc7815ed3e5fedb14a3b4f8bb9ad05d5dd7a68/crates/cairo-lang-semantic/src/inline_macros/write.rs#L13)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Same below
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 89 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiUdsjoDrbUKCswW3ya:-NiUyLzFEq9agM3DsC5T:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cffc7815ed3e5fedb14a3b4f8bb9ad05d5dd7a68/crates/cairo-lang-semantic/src/inline_macros/write.rs#L89)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 198 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiUmjQSDzTNL5CR2-Lz:-NiV-Bp_99fHreVYd_LQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cffc7815ed3e5fedb14a3b4f8bb9ad05d5dd7a68/crates/cairo-lang-semantic/src/inline_macros/write.rs#L198)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Add a test for it, for example `write!("{x{}}", x);`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/inline_macros/write.rs` line 290 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4347#-NiUqsSN4JzlxDEkZwl0:-NiV-hUc-aV7JqUQkHI3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cffc7815ed3e5fedb14a3b4f8bb9ad05d5dd7a68/crates/cairo-lang-semantic/src/inline_macros/write.rs#L290)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Doc that it only opens the match on the result, and it is closed in the main loop.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-05 15:27 UTC, gilbens-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4347#-:-NiV4oeu4V20iY6Xp4qo:bnfp4nl)* status: all files reviewed, 25 unresolved discussions (waiting on @orizi and @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-11-05 15:32 UTC, gilbens-starkware approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4347)* status: all files reviewed, 25 unresolved discussions (waiting on @orizi and @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-11-05 15:43 UTC, gilbens-starkware approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4347)* status: all files reviewed, 25 unresolved discussions (waiting on @orizi and @yuvalsw)



<!-- Sent from Reviewable.io -->

2023-11-05 15:53 UTC, merged