Added Store impl for ByteArray.
starkware-libs/cairo pull request #4596
Opened 2023-12-18 12:51 UTC by orizi

2023-12-19 09:01 UTC, gilbens-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @ArielElp, @liorgold2, and @orizi)

___
*[`corelib/src/integer.cairo` line 313 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm0CIRJDNI0G8CxpNHP:-Nm0CIRK5ynwuK-nvlvy:b-x9o9w) ([raw file](https://github.com/starkware-libs/cairo/blob/901a9db6e5c65ef339aed0590a6438d6b454ffbf/corelib/src/integer.cairo#L313)):*
> ```Cairo
> }
> 
> pub(crate) extern fn u8_overflowing_add(
> ```

Consider exposing also the `sub` for completeness.



_Code quote:_
```Cairo
pub(crate) 
```
___
*[`corelib/src/starknet/storage_access.cairo` line 679 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm0IZDaDY-3HFyccfOZ:-Nm0IZDaDY-3HFyccfO_:by5aw6b) ([raw file](https://github.com/starkware-libs/cairo/blob/901a9db6e5c65ef339aed0590a6438d6b454ffbf/corelib/src/starknet/storage_access.cairo#L679)):*
> ```Cairo
>     #[inline(always)]
>     fn size() -> u8 {
>         1
> ```

Shouldn't it include all the fragments of the array?



_Code quote:_
```Cairo
  1
```
___
*[`corelib/src/starknet/storage_access.cairo` line 696 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm0IJK02Er8ONeLscXE:-Nm0IJK02Er8ONeLscXF:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/901a9db6e5c65ef339aed0590a6438d6b454ffbf/corelib/src/starknet/storage_access.cairo#L696)):*
> ```Cairo
>         match starknet::syscalls::storage_read_syscall(address_domain, address)?.try_into() {
>         Option::Some(x) => x,
>         Option::None => { return starknet::SyscallResult::Err(array!['Invalid length']); },
> ```





_Suggestion:_
```Cairo
SyscallResult::Err(array!['Invalid length']); 
```
___
*[`corelib/src/starknet/storage_access.cairo` line 756 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm0FXTT9riejz_4m5N8:-Nm0FXTT9riejz_4m5N9:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/901a9db6e5c65ef339aed0590a6438d6b454ffbf/corelib/src/starknet/storage_access.cairo#L756)):*
> ```Cairo
>     let mut index_in_chunk = 0_u8;
>     loop {
>         let value = match full_words.pop_front() {
> ```





_Suggestion:_
```Cairo
let cur_value
```
___
*[`corelib/src/starknet/storage_access.cairo` line 768 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm0F4hiAGIALzj1y8cn:-Nm0F4hiAGIALzj1y8co:b-6vffv2) ([raw file](https://github.com/starkware-libs/cairo/blob/901a9db6e5c65ef339aed0590a6438d6b454ffbf/corelib/src/starknet/storage_access.cairo#L768)):*
> ```Cairo
>             Result::Err(err) => { break Result::Err(err); },
>         };
>         index_in_chunk = match core::integer::u8_overflowing_add(index_in_chunk, 1) {
> ```

Doc somewhere that there are 255 values in a chunk.



_Code quote:_
```Cairo
 index_in_chunk = match core::integer::u8_overflowing_add(index_in_chunk, 1) 
```


<!-- Sent from Reviewable.io -->

2023-12-19 09:40 UTC, gilbens-starkware reviewed
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @ArielElp, @liorgold2, and @orizi)

___
*[`corelib/src/starknet/storage_access.cairo` line 699 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm0R7f7-U3mBMbKKXSl:-Nm0R7f7-U3mBMbKKXSm:bafe0px) ([raw file](https://github.com/starkware-libs/cairo/blob/901a9db6e5c65ef339aed0590a6438d6b454ffbf/corelib/src/starknet/storage_access.cairo#L699)):*
> ```Cairo
>     };
>     let (mut remaining_full_words, pending_word_len) = core::DivRem::div_rem(
>         len, 31_usize.try_into().unwrap()
> ```

From `bytes_31.cairo`



_Suggestion:_
```Cairo
BYTES_IN_BYTES31
```


<!-- Sent from Reviewable.io -->

2023-12-19 09:55 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @liorgold2)

___
*[`corelib/src/integer.cairo` line 313 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm0CIRJDNI0G8CxpNHP:-Nm0Qwgz0-hFQnUeYrL_:b-1hfbyd) ([raw file](https://github.com/starkware-libs/cairo/blob/901a9db6e5c65ef339aed0590a6438d6b454ffbf/corelib/src/integer.cairo#L313)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Consider exposing also the `sub` for completeness.
</blockquote></details>

i currently add it in an ad-hoc needed basic - this will only be exported with a proper trait - so rather not add other things i would later remove.
___
*[`corelib/src/starknet/storage_access.cairo` line 679 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm0IZDaDY-3HFyccfOZ:-Nm0R6Ld-o4ls_72gF12:b-f0lt9q) ([raw file](https://github.com/starkware-libs/cairo/blob/901a9db6e5c65ef339aed0590a6438d6b454ffbf/corelib/src/starknet/storage_access.cairo#L679)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Shouldn't it include all the fragments of the array?
</blockquote></details>

definitely not  - this is the amount of data in the current stream of felts.
___
*[`corelib/src/starknet/storage_access.cairo` line 696 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm0IJK02Er8ONeLscXE:-Nm0RMlU6g3ZlO3tqjg_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/901a9db6e5c65ef339aed0590a6438d6b454ffbf/corelib/src/starknet/storage_access.cairo#L696)):*
> ```Cairo
>         match starknet::syscalls::storage_read_syscall(address_domain, address)?.try_into() {
>         Option::Some(x) => x,
>         Option::None => { return starknet::SyscallResult::Err(array!['Invalid length']); },
> ```

Done.
___
*[`corelib/src/starknet/storage_access.cairo` line 768 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm0F4hiAGIALzj1y8cn:-Nm0S5nE-ZOCNZ3hv1Pg:bqi7uel) ([raw file](https://github.com/starkware-libs/cairo/blob/901a9db6e5c65ef339aed0590a6438d6b454ffbf/corelib/src/starknet/storage_access.cairo#L768)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Doc somewhere that there are 255 values in a chunk.
</blockquote></details>

Adding - do note it is *256* though.


<!-- Sent from Reviewable.io -->

2023-12-20 10:55 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @orizi)

___
*[`corelib/src/starknet/storage_access.cairo` line 683 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm5rNMHEulD7Fsez8BO:-Nm5rNMHEulD7Fsez8BP:bgwfetd) ([raw file](https://github.com/starkware-libs/cairo/blob/b611d0a49d160b891f1e1c49bea8268554e6d367/corelib/src/starknet/storage_access.cairo#L683)):*
> ```Cairo
> }
> 
> /// Returns a pointer to the `chunk`'th chunk of the byte array at `address`.
> ```

Document the hash we're using.


<!-- Sent from Reviewable.io -->

2023-12-20 10:58 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @orizi)

___
*[`corelib/src/starknet/storage_access.cairo` line 683 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm5rNMHEulD7Fsez8BO:-Nm5rr13ENUqyP9Nd_kb:b69jxlw) ([raw file](https://github.com/starkware-libs/cairo/blob/b611d0a49d160b891f1e1c49bea8268554e6d367/corelib/src/starknet/storage_access.cairo#L683)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Document the hash we're using.
</blockquote></details>

Also, add something like: `address` is the storage address containing the length of the array. The data of the array is stored in chunks...
(I think this function is the one that deserves the documentation of how we store byte arrays)


<!-- Sent from Reviewable.io -->

2023-12-20 11:00 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @orizi)

___
*[`corelib/src/starknet/storage_access.cairo` line 684 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm5sHwp98UKRzvu7E-t:-Nm5sHwp98UKRzvu7E-u:bdw78ca) ([raw file](https://github.com/starkware-libs/cairo/blob/b611d0a49d160b891f1e1c49bea8268554e6d367/corelib/src/starknet/storage_access.cairo#L684)):*
> ```Cairo
> 
> /// Returns a pointer to the `chunk`'th chunk of the byte array at `address`.
> fn inner_byte_array_pointer(address: StorageAddress, chunk: usize) -> StorageBaseAddress {
> ```

Why not call the arg `address_domain` as you do in the other functions?
___
*[`corelib/src/starknet/storage_access.cairo` line 691 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm5sO94EzzawxZivhG0:-Nm5sO94EzzawxZivhG1:b-y2j1az) ([raw file](https://github.com/starkware-libs/cairo/blob/b611d0a49d160b891f1e1c49bea8268554e6d367/corelib/src/starknet/storage_access.cairo#L691)):*
> ```Cairo
> }
> 
> /// Reads a byte array from storage from domain `address_domain` and address `address`.
> ```

Add something like:
```
`address_domain` is the address containing the length of the array. See [inner_byte_array_pointer] for more details.
```


<!-- Sent from Reviewable.io -->

2023-12-20 11:01 UTC, liorgold2 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @orizi)

___
*[`corelib/src/starknet/storage_access.cairo` line 694 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm5sdoKATMWlBipGWY1:-Nm5sdoKATMWlBipGWY2:b-ygggbf) ([raw file](https://github.com/starkware-libs/cairo/blob/b611d0a49d160b891f1e1c49bea8268554e6d367/corelib/src/starknet/storage_access.cairo#L694)):*
> ```Cairo
> fn inner_read_byte_array(address_domain: u32, address: StorageAddress) -> SyscallResult<ByteArray> {
>     let len: usize =
>         match starknet::syscalls::storage_read_syscall(address_domain, address)?.try_into() {
> ```

(This formatting is weird) (nonblocking)


<!-- Sent from Reviewable.io -->

2023-12-20 11:01 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @orizi)

___
*[`corelib/src/starknet/storage_access.cairo` line 696 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm5spOk6YfKfTd7CrwN:-Nm5spOk6YfKfTd7CrwO:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/b611d0a49d160b891f1e1c49bea8268554e6d367/corelib/src/starknet/storage_access.cairo#L696)):*
> ```Cairo
>         match starknet::syscalls::storage_read_syscall(address_domain, address)?.try_into() {
>         Option::Some(x) => x,
>         Option::None => { return starknet::SyscallResult::Err(array!['Invalid length']); },
> ```

.



_Suggestion:_
```Cairo
Invalid ByteArray length
```


<!-- Sent from Reviewable.io -->

2023-12-20 11:04 UTC, liorgold2 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @orizi)

___
*[`corelib/src/starknet/storage_access.cairo` line 699 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm0R7f7-U3mBMbKKXSl:-Nm5tH6LAUqcj_udYdE0:b-u288fv) ([raw file](https://github.com/starkware-libs/cairo/blob/901a9db6e5c65ef339aed0590a6438d6b454ffbf/corelib/src/starknet/storage_access.cairo#L699)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

From `bytes_31.cairo`
</blockquote></details>

We need to support nonzero constants or be able to optimize this out.
(not part of this PR, nonblocking)


<!-- Sent from Reviewable.io -->

2023-12-20 11:07 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @orizi)

___
*[`corelib/src/starknet/storage_access.cairo` line 727 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm5uBiU59dwhNkNqrRG:-Nm5uBiU59dwhNkNqrRH:bnsb7y0) ([raw file](https://github.com/starkware-libs/cairo/blob/b611d0a49d160b891f1e1c49bea8268554e6d367/corelib/src/starknet/storage_access.cairo#L727)):*
> ```Cairo
>                 chunk += 1;
>                 chunk_base = inner_byte_array_pointer(address, chunk);
>                 x
> ```

`// x is zero in this case.`


<!-- Sent from Reviewable.io -->

2023-12-20 11:11 UTC, liorgold2 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @orizi)

___
*[`corelib/src/starknet/storage_access.cairo` line 684 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm5sHwp98UKRzvu7E-t:-Nm5v1S1DQCrtW1T8-6B:b18yfxu) ([raw file](https://github.com/starkware-libs/cairo/blob/b611d0a49d160b891f1e1c49bea8268554e6d367/corelib/src/starknet/storage_access.cairo#L684)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Why not call the arg `address_domain` as you do in the other functions?
</blockquote></details>

Sorry. Ignore.


<!-- Sent from Reviewable.io -->

2023-12-20 11:12 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @orizi)

___
*[`corelib/src/starknet/storage_access.cairo` line 725 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm5vH8O64IDlH6wkJQX:-Nm5vH8PCIkGK8shQ-Yd:bc4wglp) ([raw file](https://github.com/starkware-libs/cairo/blob/b611d0a49d160b891f1e1c49bea8268554e6d367/corelib/src/starknet/storage_access.cairo#L725)):*
> ```Cairo
>             Result::Ok(x) => x,
>             Result::Err(x) => {
>                 chunk += 1;
> ```

Isn't it more efficient to have `chuck: felt252`?


<!-- Sent from Reviewable.io -->

2023-12-20 11:14 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @orizi)

___
*[`corelib/src/starknet/storage_access.cairo` line 735 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm5voCU1g8K--lbmXUD:-Nm5voCU1g8K--lbmXUE:bvlvwgs) ([raw file](https://github.com/starkware-libs/cairo/blob/b611d0a49d160b891f1e1c49bea8268554e6d367/corelib/src/starknet/storage_access.cairo#L735)):*
> ```Cairo
>             match starknet::syscalls::storage_read_syscall(
>                 address_domain, storage_address_from_base_and_offset(chunk_base, index_in_chunk)
>             ) {
> ```

Use `?`?


<!-- Sent from Reviewable.io -->

2023-12-20 11:15 UTC, liorgold2 reviewed
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @orizi)



<!-- Sent from Reviewable.io -->

2023-12-20 14:04 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 1 of 3 files reviewed, 8 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @liorgold2)

___
*[`corelib/src/starknet/storage_access.cairo` line 683 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm5rNMHEulD7Fsez8BO:-Nm6WoMJ6oKmBOG_y1OH:bti972o) ([raw file](https://github.com/starkware-libs/cairo/blob/b611d0a49d160b891f1e1c49bea8268554e6d367/corelib/src/starknet/storage_access.cairo#L683)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Also, add something like: `address` is the storage address containing the length of the array. The data of the array is stored in chunks...
(I think this function is the one that deserves the documentation of how we store byte arrays)
</blockquote></details>

this is docced over the impl.
___
*[`corelib/src/starknet/storage_access.cairo` line 691 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm5sO94EzzawxZivhG0:-Nm6Vt1l3y3TLQznuJkl:bqlqkbp) ([raw file](https://github.com/starkware-libs/cairo/blob/b611d0a49d160b891f1e1c49bea8268554e6d367/corelib/src/starknet/storage_access.cairo#L691)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add something like:
```
`address_domain` is the address containing the length of the array. See [inner_byte_array_pointer] for more details.
```
</blockquote></details>

it the domain - but added doc.
___
*[`corelib/src/starknet/storage_access.cairo` line 696 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm5spOk6YfKfTd7CrwN:-Nm6VcO24wYlpPrx-Y9v:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b611d0a49d160b891f1e1c49bea8268554e6d367/corelib/src/starknet/storage_access.cairo#L696)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`corelib/src/starknet/storage_access.cairo` line 725 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm5vH8O64IDlH6wkJQX:-Nm6UZhq0UZlEwX3Ki-P:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b611d0a49d160b891f1e1c49bea8268554e6d367/corelib/src/starknet/storage_access.cairo#L725)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Isn't it more efficient to have `chuck: felt252`?
</blockquote></details>

Done.
___
*[`corelib/src/starknet/storage_access.cairo` line 727 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm5uBiU59dwhNkNqrRG:-Nm6VIOD3nxiZknse84p:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b611d0a49d160b891f1e1c49bea8268554e6d367/corelib/src/starknet/storage_access.cairo#L727)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

`// x is zero in this case.`
</blockquote></details>

Done.
___
*[`corelib/src/starknet/storage_access.cairo` line 735 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm5voCU1g8K--lbmXUD:-Nm6VZ8B9ZHLl9gXhYYO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b611d0a49d160b891f1e1c49bea8268554e6d367/corelib/src/starknet/storage_access.cairo#L735)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Use `?`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-21 15:19 UTC, gilbens-starkware reviewed
> Reviewed 1 of 3 files at r1, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 10 of 11 files reviewed, 8 unresolved discussions (waiting on @ArielElp, @liorgold2, and @orizi)

___
*[`corelib/src/starknet/storage_access.cairo` line 662 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmBwlWe5E7nZS3ABttl:-NmBwlWe5E7nZS3ABttm:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6be5930fb2f9035f73deca524bcafe21c037c430/corelib/src/starknet/storage_access.cairo#L662)):*
> ```Cairo
> ///   - The address storing the length of the array.
> ///   - The short string `ByteArray`.
> ///   - The chunk index.
> ```





_Suggestion:_
```Cairo
/// Store for a `ByteArray`.
/// The layout of a `ByteArray` in storage is as follows:
/// * Written in the storage is only the length in bytes.
/// * The actual data is stored in chunks of 256 `bytes31`s in another place in storage
///   determined by a hash over:
///   - The address storing the length of the array.
///   - The chunk index.
///   - The short string `ByteArray`.
```
___
*[`corelib/src/starknet/storage_access.cairo` line 739 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmBx73UCp-9zcCGd0Wn:-NmBx73UCp-9zcCGd0Wo:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6be5930fb2f9035f73deca524bcafe21c037c430/corelib/src/starknet/storage_access.cairo#L739)):*
> ```Cairo
>             Result::Err(_) => {
>                 // After reading 256 `byte31`s `index_in_chunk` will overflow and we move to the
>                 // next chunk.
> ```





_Suggestion:_
```Cairo
                // After reading 256 `bytes31`s `index_in_chunk` will overflow and we move to the
                // next chunk.
```


<!-- Sent from Reviewable.io -->

2023-12-24 10:08 UTC, gilbens-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596#-:-NmQI0QQ58cTHRENCZQ9:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @ArielElp and @liorgold2)



<!-- Sent from Reviewable.io -->

2023-12-24 22:52 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 10 of 14 files reviewed, 7 unresolved discussions (waiting on @ArielElp, @liorgold2, and @orizi)

___
*[`-- commits` line 7 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmT0oyiBhefVFMuvwXv):*
Rebase needed



_Code quote:_
```
New commits in r9 on 24/12/2023 at 17:52, probably rebased from r8:

- 48a1e41: Added proper jump and branch alignment validations.

  commit-id:d7d88701

  fixup! Added more basic validation when building program registry.
```


<!-- Sent from Reviewable.io -->

2023-12-26 15:54 UTC, liorgold2 requested changes
> Reviewed 8 of 8 files at r6, 1 of 3 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 13 of 14 files reviewed, 10 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @orizi)

___
*[`corelib/src/starknet/storage_access.cairo` line 656 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmaklyM1vkKvqQ_mY69:-NmaklyM1vkKvqQ_mY6A:b-te1ak2) ([raw file](https://github.com/starkware-libs/cairo/blob/0dbb044b681aaa189f2e2a81383066da26c4aee0/corelib/src/starknet/storage_access.cairo#L656)):*
> ```Cairo
> 
> /// Store for a `ByteArray`.
> /// The layout of a `ByteArray` in storage is as follows:
> ```

Add a blank line above.
___
*[`corelib/src/starknet/storage_access.cairo` line 657 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmakTSd6Abergo5IQHl:-NmakTSe0goMc7wlAYjW:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0dbb044b681aaa189f2e2a81383066da26c4aee0/corelib/src/starknet/storage_access.cairo#L657)):*
> ```Cairo
> /// Store for a `ByteArray`.
> /// The layout of a `ByteArray` in storage is as follows:
> /// * Written in the storage is only the length in bytes.
> ```





_Suggestion:_
```Cairo
/// * Only the length in bytes is stored in the original address where the byte array is logically stored.
```
___
*[`corelib/src/starknet/storage_access.cairo` line 659 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmakvmP2wFhFBc-VoKo:-NmakvmP2wFhFBc-VoKp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0dbb044b681aaa189f2e2a81383066da26c4aee0/corelib/src/starknet/storage_access.cairo#L659)):*
> ```Cairo
> /// * Written in the storage is only the length in bytes.
> /// * The actual data is stored in chunks of 256 `bytes31`s in another place in storage
> ///   determined by a hash over:
> ```





_Suggestion:_
```Cairo
/// * The actual data is stored in chunks of 256 `bytes31`s in another place in storage
///   determined by the hash of:
```
___
*[`corelib/src/starknet/storage_access.cairo` line 696 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmalCKBBPyh3tS19h50:-NmalCKBBPyh3tS19h51:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0dbb044b681aaa189f2e2a81383066da26c4aee0/corelib/src/starknet/storage_access.cairo#L696)):*
> ```Cairo
> /// * `address` - The address "containing" the ByteArray (but actually stores just the length).
> /// * `chunk` - The index of the chunk.
> /// * The short string `ByteArray` as the capacity.
> ```





_Suggestion:_
```Cairo
/// The pointer is the `Poseidon` hash of:
/// * `address` - The address "containing" the `ByteArray`.
/// * `chunk` - The index of the chunk.
/// * The short string `ByteArray` is used as the capacity argument of the sponge construction (domain separation).
```


<!-- Sent from Reviewable.io -->

2023-12-26 15:55 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 13 of 14 files reviewed, 10 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @orizi)

___
*[`corelib/src/starknet/storage_access.cairo` line 694 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmapZJkCsefLHmBh8D-:-NmapZJkCsefLHmBh8D0:bmyy6qx) ([raw file](https://github.com/starkware-libs/cairo/blob/0dbb044b681aaa189f2e2a81383066da26c4aee0/corelib/src/starknet/storage_access.cairo#L694)):*
> ```Cairo
> /// Returns a pointer to the `chunk`'th chunk of the byte array at `address`.
> /// The pointer is a `Poseidon` hash over:
> /// * `address` - The address "containing" the ByteArray (but actually stores just the length).
> ```

Actually, let's go with:



_Suggestion:_
```Cairo
/// * `address` - The address of the ByteArray (where the length is stored).
```


<!-- Sent from Reviewable.io -->

2023-12-26 16:00 UTC, liorgold2 reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 13 of 14 files reviewed, 7 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @orizi)

___
*[`corelib/src/starknet/storage_access.cairo` line 747 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmaqGLbAb2AQQTkOIUu:-NmaqGLbAb2AQQTkOIUv:b-hfwz8p) ([raw file](https://github.com/starkware-libs/cairo/blob/0dbb044b681aaa189f2e2a81383066da26c4aee0/corelib/src/starknet/storage_access.cairo#L747)):*
> ```Cairo
>     }?;
>     if pending_word_len != 0 {
>         result
> ```

Formatting is weird. Consider adding a variable to make it look better.


<!-- Sent from Reviewable.io -->

2023-12-26 16:03 UTC, liorgold2 requested changes
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: all files reviewed, 7 unresolved discussions (waiting on @ArielElp and @orizi)

___
*[`corelib/src/integer.cairo` line 313 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nm0CIRJDNI0G8CxpNHP:-Nmar22Y-x81OebWNn8h:b-yulfwu) ([raw file](https://github.com/starkware-libs/cairo/blob/901a9db6e5c65ef339aed0590a6438d6b454ffbf/corelib/src/integer.cairo#L313)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i currently add it in an ad-hoc needed basic - this will only be exported with a proper trait - so rather not add other things i would later remove.
</blockquote></details>

(another option is to repeat this `extern` where needed)
___
*[`crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo` line 128 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmarPSf1jc4aWPDt5x8:-NmarPSf1jc4aWPDt5x9:b-c2kwf1) ([raw file](https://github.com/starkware-libs/cairo/blob/0dbb044b681aaa189f2e2a81383066da26c4aee0/crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo#L128)):*
> ```Cairo
> 
>     assert!(test_contract::__external::set_data(serialized(x)).is_empty());
>     println!("write successful.");
> ```

Intended? If so `write` -> `Write`


<!-- Sent from Reviewable.io -->

2023-12-26 16:06 UTC, liorgold2 reviewed
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: all files reviewed, 7 unresolved discussions (waiting on @ArielElp and @orizi)



<!-- Sent from Reviewable.io -->

2023-12-26 16:10 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: all files reviewed, 8 unresolved discussions (waiting on @ArielElp and @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo` line 157 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nmas75HDXwmM2vTZ82p:-Nmas75HDXwmM2vTZ82q:b2xgb66) ([raw file](https://github.com/starkware-libs/cairo/blob/0dbb044b681aaa189f2e2a81383066da26c4aee0/crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo#L157)):*
> ```Cairo
>         @test_contract::__external::get_byte_arrays(serialized(())), @serialized(x), 'Wrong result'
>     );
> }
> ```

Add some lines that show the values in the storage by their actual keys. Something like:
```
let base_addr = 0x324387978432...;
assert!(storage_at(base_addr) == 0);
assert!(storage_at(base_addr + 1) == 15);
assert!(storage_at(base_addr + 2) == 36);
assert!(storage_at(base_addr + 3) == 16384);
assert!(storage_at(posiedon(base_addr + 3, 1, 'ByteArray')) == "bytes");
```


<!-- Sent from Reviewable.io -->

2023-12-26 19:14 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: all files reviewed, 7 unresolved discussions (waiting on @ArielElp and @liorgold2)

___
*[`corelib/src/starknet/storage_access.cairo` line 656 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmaklyM1vkKvqQ_mY69:-NmbPvZH7xQmOw9iuh0x:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0dbb044b681aaa189f2e2a81383066da26c4aee0/corelib/src/starknet/storage_access.cairo#L656)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add a blank line above.
</blockquote></details>

Done.
___
*[`corelib/src/starknet/storage_access.cairo` line 657 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmakTSd6Abergo5IQHl:-NmbQ6Oc-87TCKcGYJ82:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0dbb044b681aaa189f2e2a81383066da26c4aee0/corelib/src/starknet/storage_access.cairo#L657)):*
> ```Cairo
> /// Store for a `ByteArray`.
> /// The layout of a `ByteArray` in storage is as follows:
> /// * Written in the storage is only the length in bytes.
> ```

Done.
___
*[`corelib/src/starknet/storage_access.cairo` line 659 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmakvmP2wFhFBc-VoKo:-NmbQASK9n-_nx9MVgDW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0dbb044b681aaa189f2e2a81383066da26c4aee0/corelib/src/starknet/storage_access.cairo#L659)):*
> ```Cairo
> /// * Written in the storage is only the length in bytes.
> /// * The actual data is stored in chunks of 256 `bytes31`s in another place in storage
> ///   determined by a hash over:
> ```

Done.
___
*[`corelib/src/starknet/storage_access.cairo` line 694 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmapZJkCsefLHmBh8D-:-NmbQJfcE9iUF27m-bFT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0dbb044b681aaa189f2e2a81383066da26c4aee0/corelib/src/starknet/storage_access.cairo#L694)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Actually, let's go with:
</blockquote></details>

Done.
___
*[`corelib/src/starknet/storage_access.cairo` line 696 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmalCKBBPyh3tS19h50:-NmbQ_UmEFgSl_zTtHpr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0dbb044b681aaa189f2e2a81383066da26c4aee0/corelib/src/starknet/storage_access.cairo#L696)):*
> ```Cairo
> /// * `address` - The address "containing" the ByteArray (but actually stores just the length).
> /// * `chunk` - The index of the chunk.
> /// * The short string `ByteArray` as the capacity.
> ```

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo` line 128 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmarPSf1jc4aWPDt5x8:-NmbR8wc7C3iwF2gCMIM:brpmqc3) ([raw file](https://github.com/starkware-libs/cairo/blob/0dbb044b681aaa189f2e2a81383066da26c4aee0/crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo#L128)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Intended? If so `write` -> `Write`
</blockquote></details>

removed.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo` line 157 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4596#-Nmas75HDXwmM2vTZ82p:-NmbWgiW5DxePLZYruQ1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0dbb044b681aaa189f2e2a81383066da26c4aee0/crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo#L157)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add some lines that show the values in the storage by their actual keys. Something like:
```
let base_addr = 0x324387978432...;
assert!(storage_at(base_addr) == 0);
assert!(storage_at(base_addr + 1) == 15);
assert!(storage_at(base_addr + 2) == 36);
assert!(storage_at(base_addr + 3) == 16384);
assert!(storage_at(posiedon(base_addr + 3, 1, 'ByteArray')) == "bytes");
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-27 12:56 UTC, liorgold2 requested changes
> Reviewed 1 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @orizi)

___
*[`corelib/src/starknet/storage_access.cairo` line 694 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmapZJkCsefLHmBh8D-:-NmfL9qi-yFucX7GcXJl:b-11f1f2) ([raw file](https://github.com/starkware-libs/cairo/blob/0dbb044b681aaa189f2e2a81383066da26c4aee0/corelib/src/starknet/storage_access.cairo#L694)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done yet.


<!-- Sent from Reviewable.io -->

2023-12-27 12:57 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @ArielElp, @gilbens-starkware, and @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo` line 156 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmfLLHx-SCGVRGaclOO:-NmfLLHx-SCGVRGaclOP:b-o2q966) ([raw file](https://github.com/starkware-libs/cairo/blob/ca3d8967313c96cbaad6a9b6f2012e44ee4ebc24/crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo#L156)):*
> ```Cairo
>     );
>     // Making sure the lengths was saved correctly.
>     let base_address = starknet::storage_base_address_from_felt252(selector!("byte_arrays"));
> ```

Nice. Didn't know we had `selector!`.


<!-- Sent from Reviewable.io -->

2023-12-27 12:58 UTC, liorgold2 requested changes
> Reviewed 1 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: all files reviewed, 4 unresolved discussions (waiting on @ArielElp and @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo` line 161 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmfLVte6hOx2iyRm-1K:-NmfLVte6hOx2iyRm-1L:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/ca3d8967313c96cbaad6a9b6f2012e44ee4ebc24/crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo#L161)):*
> ```Cairo
>     assert!(starknet::Store::read_at_offset(0, base_address, 2).unwrap() == 36_usize);
>     assert!(starknet::Store::read_at_offset(0, base_address, 3).unwrap() == 16384_usize);
>     // Making sure the internal data was saved correctly.
> ```

.



_Suggestion:_
```Cairo
    // Make sure the internal data was saved correctly.
```


<!-- Sent from Reviewable.io -->

2023-12-27 13:21 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596)* status: 12 of 14 files reviewed, 4 unresolved discussions (waiting on @ArielElp and @liorgold2)

___
*[`corelib/src/starknet/storage_access.cairo` line 694 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmapZJkCsefLHmBh8D-:-NmfPx4rEjXbyNlwYebN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0dbb044b681aaa189f2e2a81383066da26c4aee0/corelib/src/starknet/storage_access.cairo#L694)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Not done yet.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo` line 155 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmfLHLEEnn6u_M8Ssz1:-NmfPmYf-PtVXbc2Ha22:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ca3d8967313c96cbaad6a9b6f2012e44ee4ebc24/crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo#L155)):*
> ```Cairo
>         @test_contract::__external::get_byte_arrays(serialized(())), @serialized(x), 'Wrong result'
>     );
>     // Making sure the lengths was saved correctly.
> ```

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo` line 156 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmfLLHx-SCGVRGaclOO:-NmfPmHbA4cjd7Wbc_QR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ca3d8967313c96cbaad6a9b6f2012e44ee4ebc24/crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo#L156)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Nice. Didn't know we had `selector!`.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo` line 161 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4596#-NmfLVte6hOx2iyRm-1K:-NmfPlwbDzLG4hRfHjfT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ca3d8967313c96cbaad6a9b6f2012e44ee4ebc24/crates/cairo-lang-starknet/cairo_level_tests/storage_access.cairo#L161)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-27 13:34 UTC, liorgold2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4596#-:-NmfTqlw5EpzY8gcqnho:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArielElp)



<!-- Sent from Reviewable.io -->

2023-12-27 13:42 UTC, merged