Added a basic profiler for CASM -> Sierra
starkware-libs/cairo pull request #4739
Opened 2024-01-04 16:41 UTC by yuvalsw

2024-01-04 19:31 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: 0 of 11 files reviewed, 9 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 305 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKw7lgBMFXBXwjgucU:-NnKw7lgBMFXBXwjgucV:b-eqyrz6) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-runner/src/lib.rs#L305)):*
> ```XML
>             self.casm_program.debug_info.sierra_statement_info.last().unwrap().code_offset;
>         let sierra_len = self.casm_program.debug_info.sierra_statement_info.len() - 1;
>         let base_offset = trace.last().unwrap().pc;
> ```

as the base is one instruction after the `ret`.
doc it.



_Suggestion:_
```XML
let base_offset = trace.last().unwrap().pc + 1;
```
___
*[`crates/cairo-lang-runner/src/lib.rs` line 307 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKvl164nWVlKPi3kJR:-NnKvl164nWVlKPi3kJS:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-runner/src/lib.rs#L307)):*
> ```XML
>         let base_offset = trace.last().unwrap().pc;
> 
>         println!("yg bytecode_size: {bytecode_size}");
> ```

remove
___
*[`crates/cairo-lang-runner/src/lib.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKwKNF5HGRhNKEwhQb:-NnKwKNF5HGRhNKEwhQc:b-w3fl08) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-runner/src/lib.rs#L321)):*
> ```XML
> 
>             pc_counts[original_pc] += 1;
>         }
> ```

map is better - as in a test we are probably not going over the vast majority of possible pcs.



_Suggestion:_
```XML
    let pc_counts: trace.iter().fold(OrderedHashMap::default(), |mut acc, step| {
        if step.pc >= base {
            *acc.entry(step.pc - base).or_insert(0) += 1;
        }
        acc
    });
```
___
*[`crates/cairo-lang-runner/src/lib.rs` line 336 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKwe7P-f1DnCL4u0K3:-NnKwe7P-f1DnCL4u0K4:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-runner/src/lib.rs#L336)):*
> ```XML
> 
>         let concrete_sierra_statements_weights: HashMap<StatementIdx, usize> =
>             sierra_weights.into_iter().enumerate().map(|(x, y)| (StatementIdx(x), y)).collect();
> ```





_Suggestion:_
```XML
        let sierra_statements_weights = v.casm_hotspots.into_iter().fold(
                    OrderedHashMap::default(),
                    |mut acc, (offset, value)| {
                        let idx = match self
                            .casm_program
                            .debug_info
                            .sierra_statement_info
                            .binary_search_by_key(&k, |x| x.code_offset)
                        {
                            Ok(idx) => idx,
                            Err(idx) => idx - 1,
                        };
                        *acc.entry(StatementIdx(k)).or_insert(0) += v;
                        acc
                    },
                );
```
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKuqrB-XzAeeoI2YRF:-NnKuqrB-XzAeeoI2YRG:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-runner/src/profiling.rs#L10)):*
> ```XML
> #[derive(Debug, Eq, PartialEq, Clone)]
> pub struct ProfilingInfo {
>     /// The number of steps in the trace that "belongs" to each sierra statement.
> ```





_Suggestion:_
```XML
    /// The number of steps in the trace that originated from a sierra statement.
```
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKuldp1G484mDxrdEL:-NnKuldp1G484mDxrdEM:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-runner/src/profiling.rs#L11)):*
> ```XML
> pub struct ProfilingInfo {
>     /// The number of steps in the trace that "belongs" to each sierra statement.
>     pub concrete_sierra_statements_weights: HashMap<StatementIdx, usize>,
> ```





_Suggestion:_
```XML
    pub sierra_statements_weights: HashMap<StatementIdx, usize>,
```
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 2140 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKvesf0Vnn18OGvubJ:-NnKvesf0Vnn18OGvubK:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-runner/src/casm_run/mod.rs#L2140)):*
> ```XML
> 
>     // let mut base_offset = 0;
>     // for inst in instructions {
> ```

revert
___
*[`crates/cairo-lang-sierra/src/program.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKvLqS-iE63ZwDHiwH:-NnKvLqS-iE63ZwDHiwI:bbo6h4m) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-sierra/src/program.rs#L291)):*
> ```XML
>         // there the generic name.
>         Some(self.concrete_name()?.split('<').next().unwrap().into())
>     }
> ```

shouldn't be here - this assumes things about the structure of the concrete libfuncs names - and nothgin is know about it here.

this is all DebugReplacer based.



_Code quote:_
```XML
    pub fn concrete_name(&self) -> Option<String> {
        match self {
            GenStatement::Invocation(invocation) => Some(format!("{}", invocation.libfunc_id)),
            GenStatement::Return(_) => None,
        }
    }
    pub fn generic_name(&self) -> Option<String> {
        // There must be a better way - e.g. get the long ID with a db from the short ID, and from
        // there the generic name.
        Some(self.concrete_name()?.split('<').next().unwrap().into())
    }
```
___
*[`examples/fib_loop.cairo` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKvbed6O-tNYaX5NRz:-NnKvbed6O-tNYaX5NS-:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/examples/fib_loop.cairo#L4)):*
> ```Cairo
>     fib(1, 1, 100000);
>     400
> }
> ```

revert



_Code quote:_
```Cairo
fn main() -> felt252 {
    fib(1, 1, 100000);
    400
}
```


<!-- Sent from Reviewable.io -->

2024-01-07 13:39 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: 0 of 11 files reviewed, 10 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 305 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKw7lgBMFXBXwjgucU:-NnLrM9J1oSFFwy_PEMt:b-57rl1t) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-runner/src/lib.rs#L305)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

as the base is one instruction after the `ret`.
doc it.
</blockquote></details>

Right, but for some reason the trace PCs are all off by 1.
___
*[`crates/cairo-lang-runner/src/lib.rs` line 307 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKvl164nWVlKPi3kJR:-NnXy5NN-rDI1weh9dCz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-runner/src/lib.rs#L307)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/lib.rs` line 317 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnY1N-bB2-DyN4cQKBH:-NnY1N-c7_rcescBzpcc:b6o4juh) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-runner/src/lib.rs#L317)):*
> ```XML
> 
>         for trace_entry in trace {
>             // TODO(yg): why are the trace's PCs off by 1?
> ```

@orizi  do you know why? Trace PC's are 1-based.



_Code quote:_
```XML
// TODO(yg): why are the trace's PCs off by 1?
```
___
*[`crates/cairo-lang-runner/src/lib.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKwKNF5HGRhNKEwhQb:-NnZ0L7w19Wy1DllBjHK:b-3gq8oo) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-runner/src/lib.rs#L321)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

map is better - as in a test we are probably not going over the vast majority of possible pcs.
</blockquote></details>

Re both comments:
There are trade offs.

On one hand, having a map may be faster as we don't use a lot of the PCs, especially on a test for a big code. On the other hand, map has worse constants than an array.

On one hand, the way I implemented is linear in the casm program length, while using a binary search is n*logn where n is the length of the casm program (both ways has a component linear in the trace length). On the other hand, if the trace is very sparse in the casm program and with using a map as suggested, the actual "n" is much smaller.

I implemented all 4 combinations (array + linear, array + binary search, map + linear, map + binary search) and ran it on 3 samples. Using a map was ~20 times slower than using an array. With an array, the linear and the binary search approaches turned out very similar, with a very small advantage to the binary search.
This is of course not representative and I didn't run it on examples where we only use a small part of the actual code.
___
*[`crates/cairo-lang-runner/src/lib.rs` line 336 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKwe7P-f1DnCL4u0K3:-NnZ3bLi1kM6Ab9k_nDh:b-sw6vd) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-runner/src/lib.rs#L336)):*
> ```XML
> 
>         let concrete_sierra_statements_weights: HashMap<StatementIdx, usize> =
>             sierra_weights.into_iter().enumerate().map(|(x, y)| (StatementIdx(x), y)).collect();
> ```

See response to other comment.
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKuqrB-XzAeeoI2YRF:-NnXyDv97jyFr-KdZAJR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-runner/src/profiling.rs#L10)):*
> ```XML
> #[derive(Debug, Eq, PartialEq, Clone)]
> pub struct ProfilingInfo {
>     /// The number of steps in the trace that "belongs" to each sierra statement.
> ```

Done.
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKuldp1G484mDxrdEL:-NnXyN5zEYvLOJYBn15Y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-runner/src/profiling.rs#L11)):*
> ```XML
> pub struct ProfilingInfo {
>     /// The number of steps in the trace that "belongs" to each sierra statement.
>     pub concrete_sierra_statements_weights: HashMap<StatementIdx, usize>,
> ```

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 2140 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKvesf0Vnn18OGvubJ:-NnXySnU5v7jgcsuOjrZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-runner/src/casm_run/mod.rs#L2140)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/program.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKvLqS-iE63ZwDHiwH:-NnXzfwi1OK1cnA4yn8p:bgqxzwu) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-sierra/src/program.rs#L291)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

shouldn't be here - this assumes things about the structure of the concrete libfuncs names - and nothgin is know about it here.

this is all DebugReplacer based.
</blockquote></details>

Moved to the profiling printer.
Note the TODO above. What's the right way to get the generic name? I can propagate the db into here, but it requires adding the db in many places in e.g. TestRunner, only for it. WDYT? 
___
*[`examples/fib_loop.cairo` line 4 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKvbed6O-tNYaX5NRz:-NnY0uJ32PCH5NFI26Wm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/examples/fib_loop.cairo#L4)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-07 14:21 UTC, orizi requested changes
> Reviewed 3 of 11 files at r1, 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: 4 of 11 files reviewed, 8 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/bin/cairo-run/src/main.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnZADQRCctIO7vhMDq1:-NnZADQRCctIO7vhMDq2:b-xvjx76) ([raw file](https://github.com/starkware-libs/cairo/blob/11cbfdaed8f77ecdf29b94fcccdaac3bf64f6e27/crates/bin/cairo-run/src/main.rs#L85)):*
> ```XML
> 
>     let profiling_printer = ProfilingInfoPrinter::new(sierra_program);
>     profiling_printer.print(&result.profiling_info);
> ```

this should be under a flag.



_Code quote:_
```XML
    let profiling_printer = ProfilingInfoPrinter::new(sierra_program);
    profiling_printer.print(&result.profiling_info);
```
___
*[`crates/cairo-lang-runner/src/lib.rs` line 317 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnY1N-bB2-DyN4cQKBH:-NnZI1qj1ZiaCAELquRt:bs7z8c7) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-runner/src/lib.rs#L317)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

@orizi  do you know why? Trace PC's are 1-based.
</blockquote></details>

wdym? they should be the location of `ret` + 1 based, and your code matches that.
___
*[`crates/cairo-lang-runner/src/lib.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKwKNF5HGRhNKEwhQb:-NnZH2Lz8lhINhPKow-_:b98gu8y) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-runner/src/lib.rs#L321)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Re both comments:
There are trade offs.

On one hand, having a map may be faster as we don't use a lot of the PCs, especially on a test for a big code. On the other hand, map has worse constants than an array.

On one hand, the way I implemented is linear in the casm program length, while using a binary search is n*logn where n is the length of the casm program (both ways has a component linear in the trace length). On the other hand, if the trace is very sparse in the casm program and with using a map as suggested, the actual "n" is much smaller.

I implemented all 4 combinations (array + linear, array + binary search, map + linear, map + binary search) and ran it on 3 samples. Using a map was ~20 times slower than using an array. With an array, the linear and the binary search approaches turned out very similar, with a very small advantage to the binary search.
This is of course not representative and I didn't run it on examples where we only use a small part of the actual code.
</blockquote></details>

the normal examples IMO are going to be exactly these where we do use only a small part of the code - the classic 80-20 rule.
___
*[`crates/cairo-lang-sierra/src/program.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKvLqS-iE63ZwDHiwH:-NnZHo3k73nHlBbdcO0y:b-42p5c1) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-sierra/src/program.rs#L291)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Moved to the profiling printer.
Note the TODO above. What's the right way to get the generic name? I can propagate the db into here, but it requires adding the db in many places in e.g. TestRunner, only for it. WDYT?
</blockquote></details>

the concrete name as well is not related to here.


<!-- Sent from Reviewable.io -->

2024-01-07 16:50 UTC, orizi requested changes
> Reviewed 1 of 7 files at r2, 1 of 2 files at r3, 2 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: 7 of 13 files reviewed, 7 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 311 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnZp2d4Cfy5Wohhyjaj:-NnZp2d56kL0QcYh8GaG:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/816bb05dd8e99f6f036bd9b0a2d5e9d28550de71/crates/cairo-lang-runner/src/lib.rs#L311)):*
> ```XML
>     }
> 
>     fn collect_profiling_info(&self, trace: &Vec<TraceEntry>) -> ProfilingInfo {
> ```

doc


<!-- Sent from Reviewable.io -->

2024-01-07 19:38 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: 7 of 13 files reviewed, 7 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 317 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnY1N-bB2-DyN4cQKBH:-Nn_PpXZ98igeGMOGqCO:b8qfgoc) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-runner/src/lib.rs#L317)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

wdym? they should be the location of `ret` + 1 based, and your code matches that.
</blockquote></details>

All the trace's PCs are off by one. The first one is 1.
If it were not off by one, I'd need to do a +1 in the base_offset computation, and I wouldn't need the -1 here.
___
*[`crates/cairo-lang-runner/src/lib.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKwKNF5HGRhNKEwhQb:-Nn_NoQ6DkTVvk-KMgVH:baclf6i) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-runner/src/lib.rs#L321)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the normal examples IMO are going to be exactly these where we do use only a small part of the code - the classic 80-20 rule.
</blockquote></details>

Ran more examples, more similar to what you describe. They indeed are more efficient with the map and the binary search. The only case where it's more efficient to have an array (still more efficient with binary search) is when the trace is very long (both if the code is short or long), but this is probably less common. We can consider in the future adding a setting to use this approach when needed, or decide automatically, based on heuristics.
___
*[`crates/cairo-lang-runner/src/lib.rs` line 311 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnZp2d4Cfy5Wohhyjaj:-Nn_PmmH-8KqQE5j1yBQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/816bb05dd8e99f6f036bd9b0a2d5e9d28550de71/crates/cairo-lang-runner/src/lib.rs#L311)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/program.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKvLqS-iE63ZwDHiwH:-Nn_PHav5ZMZgUMwnm01:b-2wv7ph) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-sierra/src/program.rs#L291)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the concrete name as well is not related to here.
</blockquote></details>

This doesn't answer my question.


<!-- Sent from Reviewable.io -->

2024-01-07 22:06 UTC, orizi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: 7 of 13 files reviewed, 6 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 317 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnY1N-bB2-DyN4cQKBH:-Nn_xOr81PeAgLQ3oG15:bsp9h61) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-runner/src/lib.rs#L317)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

All the trace's PCs are off by one. The first one is 1.
If it were not off by one, I'd need to do a +1 in the base_offset computation, and I wouldn't need the -1 here.
</blockquote></details>

it doesn't matter how many cells are before the location of `ret` - the base is + 1 of it, so we need to remove `last_pc + 1` from everything.


<!-- Sent from Reviewable.io -->

2024-01-07 22:19 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: 7 of 13 files reviewed, 5 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 367 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4739#-Nn_zWGbBDwRfwPLnqmc:-Nn_zWGbBDwRfwPLnqmd:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d521aab485da78ccc91c26988852a0aac26e8154/crates/cairo-lang-runner/src/lib.rs#L367)):*
> ```XML
> 
>                 *acc.entry(StatementIdx(idx)).or_insert(0) += count;
>                 acc
> ```





_Suggestion:_
```XML
                let real_pc = pc - base_offset;
                let idx = match self
                    .casm_program
                    .debug_info
                    .sierra_statement_info
                    .binary_search_by_key(&(real_pc + 1), |x| x.code_offset)
                {
                    Ok(idx) | Err(idx) => idx - 1,
                };

                *acc.entry(StatementIdx(idx)).or_insert(0) += count;
                acc
```
___
*[`crates/cairo-lang-sierra/src/program.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKvLqS-iE63ZwDHiwH:-Nna-CQv1b30dSw1uWOV:buddfsd) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-sierra/src/program.rs#L291)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This doesn't answer my question.
</blockquote></details>

you can get it from a program registry.
In any case this function still shouldn't be here.


<!-- Sent from Reviewable.io -->

2024-01-08 12:44 UTC, orizi requested changes
> Reviewed 7 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 367 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4739#-Nn_zWGbBDwRfwPLnqmc:-Nnd4A8mBsY8uXhQKUqF:b-d4418b) ([raw file](https://github.com/starkware-libs/cairo/blob/d521aab485da78ccc91c26988852a0aac26e8154/crates/cairo-lang-runner/src/lib.rs#L367)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

This won't work. real_pc + 1 can also appear multiple times, so the binary search might find another occurrence but the first.
</blockquote></details>

So use `partition_point` instead, despite being a little worse.
___
*[`crates/cairo-lang-sierra/src/program.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NnKvLqS-iE63ZwDHiwH:-Nnd5MNS0xNzLr_w447i:bey2mlz) ([raw file](https://github.com/starkware-libs/cairo/blob/ee92ecda941ce8eba42484d0f6dbf86d18d9df28/crates/cairo-lang-sierra/src/program.rs#L291)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Moved. But still - I would like to get the generic name correctly. I don't see a registry where I create the printer, e.g. in runner. As said, I can pass the db inside, but is this the right way?
</blockquote></details>

The sierra program registry can be built from any sierra program, it allows you to get information, such as the generic IDs of types and libfuncs 


<!-- Sent from Reviewable.io -->

2024-01-08 16:35 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: 6 of 15 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/lib.rs` line 367 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4739#-Nn_zWGbBDwRfwPLnqmc:-NndvGA29gJELTSR4o0o:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d521aab485da78ccc91c26988852a0aac26e8154/crates/cairo-lang-runner/src/lib.rs#L367)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

So use `partition_point` instead, despite being a little worse.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-08 18:34 UTC, orizi requested changes
> Reviewed 2 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: 8 of 15 files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/bin/cairo-run/src/main.rs` line 92 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NneKs242Coop9_RsE2_:-NneKs242Coop9_RsE2a:b18txbc) ([raw file](https://github.com/starkware-libs/cairo/blob/bc61ebe13d7b5d2eec35f5ccdc0cea7245e9fdb3/crates/bin/cairo-run/src/main.rs#L92)):*
> ```XML
>         match result.profiling_info {
>             Some(profiling_info) => {
>                 println!("Profiling info:\n{}", profiling_printer.print(&profiling_info));
> ```

profiling formatter instead and just print it as a structure directly.



_Code quote:_
```XML
 profiling_printer.print(&profiling_info));
```
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 27 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NneLOe_0cEQlwNLEywA:-NneLOe_0cEQlwNLEywB:b-3ev810) ([raw file](https://github.com/starkware-libs/cairo/blob/bc61ebe13d7b5d2eec35f5ccdc0cea7245e9fdb3/crates/cairo-lang-runner/src/profiling.rs#L27)):*
> ```XML
>     pub print_by_generic_libfunc: bool,
> }
> impl Default for ProfilingInfoPrinterParams {
> ```

rename Printer to Formatter and then just use it for printing directly.

impl Display for it.



_Code quote:_
```XML
/// Parameters controlling how the profiling info is printed by the `ProfilingInfoPrinter`.
pub struct ProfilingInfoPrinterParams {
    /// The minimal weight to print. Used for all printed stats. That is - the sum of the weights
    /// per statement may smaller than the sum of the weights per concrete libfunc, that may be
    /// smaller than the sum of the weights ber generic libfunc.
    pub min_weight: usize,
    pub print_by_concrete_libfunc: bool,
    pub print_by_generic_libfunc: bool,
}
impl Default for ProfilingInfoPrinterParams {
```
___
*[`crates/cairo-lang-runner/src/profiling_test.rs` line 27 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NneLVjoBcYxPoCzBd7M:-NneLVjoBcYxPoCzBd7N:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/bc61ebe13d7b5d2eec35f5ccdc0cea7245e9fdb3/crates/cairo-lang-runner/src/profiling_test.rs#L27)):*
> ```XML
>     let sierra_program = ProgramParser::new().parse(&sierra_code).unwrap();
> 
>     // let sierra_program_path = "enum_flow.cairo";
> ```

remove


<!-- Sent from Reviewable.io -->

2024-01-14 09:49 UTC, orizi requested changes
> Reviewed 1 of 9 files at r6, 4 of 5 files at r9, 1 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: 10 of 15 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-runner/src/profiling.rs` line 18 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4739#-No6MzE87vNMfMnJV9i-:-No6MzE87vNMfMnJV9i0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3b00bcd78937181d7bacce129da5744b54a0c8fc/crates/cairo-lang-runner/src/profiling.rs#L18)):*
> ```XML
> pub struct ProfilingInfo {
>     /// The number of steps in the trace that originated from each sierra statement.
>     pub sierra_statements_weights: HashMap<StatementIdx, usize>,
> ```





_Suggestion:_
```XML
    pub sierra_statements_weights: UnorderedHashMap<StatementIdx, usize>,
```


<!-- Sent from Reviewable.io -->

2024-01-14 09:49 UTC, orizi reviewed
> Reviewed 1 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: 11 of 15 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2024-01-14 09:58 UTC, orizi reviewed
> Reviewed 4 of 5 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2024-01-14 09:59 UTC, orizi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2024-01-14 09:59 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/bin/cairo-run/src/main.rs` line 92 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NneKs242Coop9_RsE2_:-No6IMUY1pmN3yCLCS1Z:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bc61ebe13d7b5d2eec35f5ccdc0cea7245e9fdb3/crates/bin/cairo-run/src/main.rs#L92)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

profiling formatter instead and just print it as a structure directly.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 27 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NneLOe_0cEQlwNLEywA:-No6IOmlBPqWfrT6DGoE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bc61ebe13d7b5d2eec35f5ccdc0cea7245e9fdb3/crates/cairo-lang-runner/src/profiling.rs#L27)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename Printer to Formatter and then just use it for printing directly.

impl Display for it.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 18 at r9](https://reviewable.io/reviews/starkware-libs/cairo/4739#-No6MzE87vNMfMnJV9i-:-No6POvKAeXBQ2bwmX5E:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3b00bcd78937181d7bacce129da5744b54a0c8fc/crates/cairo-lang-runner/src/profiling.rs#L18)):*
> ```XML
> pub struct ProfilingInfo {
>     /// The number of steps in the trace that originated from each sierra statement.
>     pub sierra_statements_weights: HashMap<StatementIdx, usize>,
> ```

Done.
___
*[`crates/cairo-lang-runner/src/profiling_test.rs` line 27 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4739#-NneLVjoBcYxPoCzBd7M:-No6ISz3AN2S9h-7jYGm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bc61ebe13d7b5d2eec35f5ccdc0cea7245e9fdb3/crates/cairo-lang-runner/src/profiling_test.rs#L27)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-14 10:00 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-runner/src/profiling.rs` line 117 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4739#-No6PRbZ5LZ_4J8UN50X:-No6PRbZ5LZ_4J8UN50Y:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/532f69a5164666b4b04ebd3b6ab2a28cc07bfcca/crates/cairo-lang-runner/src/profiling.rs#L117)):*
> ```XML
>         } else {
>             HashMap::new()
>         };
> ```

.



_Suggestion:_
```XML
                .iter()
                .map(|concrete_libfunc| (concrete_libfunc.long_id.to_string().into(), 0))
                .collect::<UnorderedHashMap<SmolStr, usize>>()
        } else {
            UnorderedHashMap::new()
        };

        let mut generic_libfuncs = if params.process_by_generic_libfunc {
            self.sierra_program
                .libfunc_declarations
                .iter()
                .map(|concrete_libfunc| (concrete_libfunc.long_id.generic_id.0.clone(), 0))
                .collect::<UnorderedHashMap<SmolStr, usize>>()
        } else {
            UnorderedHashMap::new()
        };
```


<!-- Sent from Reviewable.io -->

2024-01-14 10:12 UTC, orizi reviewed
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2024-01-14 11:25 UTC, orizi reviewed
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2024-01-15 11:44 UTC, yuvalsw commented
change target branch




<!-- Sent from Reviewable.io -->

2024-01-15 11:52 UTC, orizi reviewed
> Reviewed 1 of 4 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: 13 of 15 files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-01-15 13:26 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: 12 of 17 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/profiling.rs` line 117 at r11](https://reviewable.io/reviews/starkware-libs/cairo/4739#-No6PRbZ5LZ_4J8UN50X:-NoAwpkb2zgCgg5Hxs36:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/532f69a5164666b4b04ebd3b6ab2a28cc07bfcca/crates/cairo-lang-runner/src/profiling.rs#L117)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-15 13:31 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 5 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739#-:-NoCJXgVAE_V3C7tKmTG:bnfp4nl)* status: 15 of 17 files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-01-15 13:39 UTC, yuvalsw reviewed
> Reviewed 1 of 7 files at r2, 1 of 2 files at r3, 1 of 5 files at r10, 2 of 5 files at r16.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: 12 of 17 files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-01-15 13:41 UTC, orizi approved these changes
> Reviewed 5 of 5 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2024-01-15 13:41 UTC, yuvalsw reviewed
> Reviewed 5 of 5 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2024-01-15 14:17 UTC, orizi approved these changes
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4739)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2024-01-15 14:17 UTC, merged