build: cairo-lang-casm support no_std
starkware-libs/cairo pull request #4780
Opened 2024-01-10 16:36 UTC by tdelabro

In this PR:
- cairo-lang-casm can compile to no_std

2024-01-10 17:54 UTC, orizi requested changes
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4780)* status: all files reviewed, 1 unresolved discussion (waiting on @tdelabro)

___
*[`.github/workflows/ci.yml` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4780#-NnoUuaO1dtzDVvHdKgC:-NnoUuaO1dtzDVvHdKgD:b-8kwl9w) ([raw file](https://github.com/starkware-libs/cairo/blob/8a532f09d043f92fcc9e2de439f2bef23e5d7e84/.github/workflows/ci.yml#L56)):*
> ```YAML
>           - test --profile=ci-dev -p cairo-lang-test-runner
>           - test --profile=ci-dev -p cairo-lang-test-utils
>           - test --profile=ci-dev -p cairo-lang-utils --features=serde,parity-scale-codec,schemars,testing,env_logger
> ```

why add this and not just a regular build?



_Code quote:_
```YAML
 --features=serde,parity-scale-codec,schemars,testing,env_logger
```


<!-- Sent from Reviewable.io -->

2024-01-10 18:03 UTC, tdelabro reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4780)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`.github/workflows/ci.yml` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4780#-NnoUuaO1dtzDVvHdKgC:-NnoWsXi9STMu8n5htUt:b-n8yb1w) ([raw file](https://github.com/starkware-libs/cairo/blob/8a532f09d043f92fcc9e2de439f2bef23e5d7e84/.github/workflows/ci.yml#L56)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why add this and not just a regular build?
</blockquote></details>

If we just run the regular build some changes could have broken code behind a feature flag without us knowing.
My idea is that, because features in Rust only add code and never remove code, if this run passes, the one without any additional features should pass too.
Another option could be to run both, without additional features and with them.


<!-- Sent from Reviewable.io -->

2024-01-11 07:45 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4780)* status: all files reviewed, 1 unresolved discussion (waiting on @tdelabro)

___
*[`.github/workflows/ci.yml` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4780#-NnoUuaO1dtzDVvHdKgC:-NnrTj9x0ZUzRZdnZWh4:bdc9bq6) ([raw file](https://github.com/starkware-libs/cairo/blob/8a532f09d043f92fcc9e2de439f2bef23e5d7e84/.github/workflows/ci.yml#L56)):*
<details><summary><i>Previously, tdelabro (Timothée Delabrouille) wrote…</i></summary><blockquote>

If we just run the regular build some changes could have broken code behind a feature flag without us knowing.
My idea is that, because features in Rust only add code and never remove code, if this run passes, the one without any additional features should pass too.
Another option could be to run both, without additional features and with them.
</blockquote></details>

so what would happen with the release of the artifacts? would the resulting binaries not have all features?
or it would be fine since it is only mostly for binaries?


<!-- Sent from Reviewable.io -->

2024-01-11 12:58 UTC, tdelabro reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4780)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`.github/workflows/ci.yml` line 56 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4780#-NnoUuaO1dtzDVvHdKgC:-Nns_9B9BM3RsDlx6qRq:b-89jplf) ([raw file](https://github.com/starkware-libs/cairo/blob/8a532f09d043f92fcc9e2de439f2bef23e5d7e84/.github/workflows/ci.yml#L56)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so what would happen with the release of the artifacts? would the resulting binaries not have all features?
or it would be fine since it is only mostly for binaries?
</blockquote></details>

I'm not sure to understand your question.

The lib will be published in crates.io, and developers can use it with or without the extra features.

About our binaries, they will build with the features they add to their `Cargo.toml`.
Meaning they won't be compiling code that they don't need. If a binary doesn't ever use serde on the lib types, there is no need for it to event compiled with them.

 I'm not sure it makes for a smaller binary because Rust will strip unused symbols anyway. But it for sure reduces the amount of dependency to pull and compile, making the dependency tree simpler.


<!-- Sent from Reviewable.io -->

2024-01-11 13:04 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4780#-:-Nnsbvcn9cd_wd0yyOPE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tdelabro)



<!-- Sent from Reviewable.io -->

2024-01-11 17:41 UTC, merged