Merged `constrain_range` into `downcast`.
starkware-libs/cairo pull request #4813
Opened 2024-01-15 20:42 UTC by orizi

**Stack**:
- #4812
- #4785

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-01-16 12:01 UTC, liorgold2 requested changes
> Reviewed 1 of 27 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 2 of 27 files reviewed, 2 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 105 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoH8QwA2d7iOsFKue_A:-NoH8QwB4beQPWobGikO:b-y9usg2) ([raw file](https://github.com/starkware-libs/cairo/blob/f44a170da3107a26b1567ef053992a4b41413aef/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L105)):*
> ```XML
>             return Err(SpecializationError::UnsupportedGenericArg);
>         }
>         let from_range = Range::from_type(context, from_ty.clone())?;
> ```

Move this line above `to_range` and put a blank line after `to_range`.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/utils.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoH6n8L9NObMHM8Esmy:-NoH6n8L9NObMHM8Esmz:bbhupzt) ([raw file](https://github.com/starkware-libs/cairo/blob/f44a170da3107a26b1567ef053992a4b41413aef/crates/cairo-lang-sierra/src/extensions/modules/utils.rs#L94)):*
> ```XML
>     }
>     /// Returns true if this range can contain all possible values of a CASM cell.
>     pub fn is_felt252(&self) -> bool {
> ```

Rename function.


<!-- Sent from Reviewable.io -->

2024-01-16 12:02 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 2 of 27 files reviewed, 3 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 108 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoH8YFfDhu8g8NngJgb:-NoH8YFfDhu8g8NngJgc:b-ulcqyi) ([raw file](https://github.com/starkware-libs/cairo/blob/f44a170da3107a26b1567ef053992a4b41413aef/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L108)):*
> ```XML
>         let is_small_values_downcast = from_range.is_rc();
>         let is_felt252_valid_downcast =
>             from_range.is_felt252() && to_range.size() <= (Felt252::prime() % u128::MAX).into();
> ```

What is this number? Document.



_Code quote:_
```XML
(Felt252::prime() % u128::MAX).into()
```


<!-- Sent from Reviewable.io -->

2024-01-16 12:49 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 2 of 27 files reviewed, 3 unresolved discussions (waiting on @liorgold2 and @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 105 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoH8QwA2d7iOsFKue_A:-NoHHUU61CwSVUt-aO56:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f44a170da3107a26b1567ef053992a4b41413aef/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L105)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Move this line above `to_range` and put a blank line after `to_range`.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 108 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoH8YFfDhu8g8NngJgb:-NoHIvC29UDeSXkS6VGj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f44a170da3107a26b1567ef053992a4b41413aef/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L108)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

What is this number? Document.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/utils.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoH6n8L9NObMHM8Esmy:-NoHHj050MarkWAshpBG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f44a170da3107a26b1567ef053992a4b41413aef/crates/cairo-lang-sierra/src/extensions/modules/utils.rs#L94)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Rename function.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-16 13:06 UTC, liorgold2 requested changes
> Reviewed 6 of 27 files at r1, 1 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 6 of 27 files reviewed, 3 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 108 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoHM8Ge66R_vkgj4ZRC:-NoHM8Ge66R_vkgj4ZRD:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ae1099ae981e65f409421b341a1b52709d57bcac/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L108)):*
> ```XML
>         }
>         let is_small_values_downcast = from_range.is_small_range();
>         // Only allowing `prime % 2**128` for using `K=2` in the validate_under_limit function.
> ```





_Suggestion:_
```XML
        // Only allow `size <= prime % (2**128 - 1)` so that we can safely use `K=2` in `validate_under_limit`.
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 114 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoHN1u75JdGPJqanjPJ:-NoHN1u75JdGPJqanjPK:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ae1099ae981e65f409421b341a1b52709d57bcac/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L114)):*
> ```XML
>             return Err(SpecializationError::UnsupportedGenericArg);
>         }
>         // Not supporting an upcast that would always fail.
> ```





_Suggestion:_
```XML
        // Don't allow a downcast that would always fail (disjoint ranges).
```


<!-- Sent from Reviewable.io -->

2024-01-16 13:11 UTC, liorgold2 requested changes
> Reviewed 6 of 27 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 12 of 27 files reviewed, 4 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned.rs` line 195 at r4](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoHOOsj3rs8wWdKPJde:-NoHOOsj3rs8wWdKPJdf:b39lxex) ([raw file](https://github.com/starkware-libs/cairo/blob/ae1099ae981e65f409421b341a1b52709d57bcac/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned.rs#L195)):*
> ```XML
>         UintConcrete::ToFelt252(_) => misc::build_identity(builder),
>         UintConcrete::FromFelt252(_) => {
>             build_felt252_range_reduction(builder, &Range { lower: 0.into(), upper: LIMIT.into() })
> ```

Use `Range::half_open`.


<!-- Sent from Reviewable.io -->

2024-01-16 13:27 UTC, liorgold2 requested changes
> Reviewed 7 of 27 files at r1, 3 of 6 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 22 of 27 files reviewed, 4 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`tests/e2e_test_data/libfuncs/constrain_range` line 85 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoHRE9r56mLENcPzHiw:-NoHRE9r56mLENcPzHix:bti3ggr) ([raw file](https://github.com/starkware-libs/cairo/blob/712011501d3b01ccab7e3c22adb85776ee27f321/tests/e2e_test_data/libfuncs/constrain_range#L85)):*
> ```
> //! > ==========================================================================
> 
> //! > bounded_int<0,1>_from_felt
> ```

What does this test add on top of the previous one?
___
*[`tests/e2e_test_data/libfuncs/constrain_range` line 255 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoHRbPV-aiojMWX_8Yb:-NoHRbPV-aiojMWX_8Yc:b-dfjxqg) ([raw file](https://github.com/starkware-libs/cairo/blob/712011501d3b01ccab7e3c22adb85776ee27f321/tests/e2e_test_data/libfuncs/constrain_range#L255)):*
> ```
> //! > ==========================================================================
> 
> //! > downcast::<felt252, BoundedInt<0, 10633823966279327296825105735305134080>> libfunc
> ```

Maybe check with a shifted range instead?
Anyway, add a comment to the test explaining what you're testing here.

Also, missing tests with MIN > 0 and MIN < 0.


<!-- Sent from Reviewable.io -->

2024-01-16 13:31 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 22 of 27 files reviewed, 5 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`tests/e2e_test_data/libfuncs/constrain_range` line 1 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoHT5bj6bHnADk5INq3:-NoHT5bj6bHnADk5INq4:b6w1o51) ([raw file](https://github.com/starkware-libs/cairo/blob/712011501d3b01ccab7e3c22adb85776ee27f321/tests/e2e_test_data/libfuncs/constrain_range#L1)):*
> ```
> //! > downcast::<felt252, BoundedInt<0, 7>> libfunc
> ```

Rename file.


<!-- Sent from Reviewable.io -->

2024-01-16 13:36 UTC, liorgold2 requested changes
> Reviewed 1 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 23 of 27 files reviewed, 6 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 110 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoHTah94VdM_ICiYH85:-NoHTah94VdM_ICiYH86:b-7je6os) ([raw file](https://github.com/starkware-libs/cairo/blob/712011501d3b01ccab7e3c22adb85776ee27f321/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L110)):*
> ```XML
>         // Only allow `size <= prime % (2**128 - 1)` so that we can safely use `K=2` in
>         // `validate_under_limit`.
>         let is_felt252_valid_downcast = from_range.is_full_felt252_range()
> ```

I don't like this. `felt` should be handled differently, not like all BoundedInts with size >= prime.
Specifically the downcast `BoundedInt<-(P-1), 0>  ->  BoundedInt<0, 10>` should return `None`
on the value `-(P - 1) == 1`. We think, it returns `Ok(1)` in the current code.

Add a test in `integer_test.cairo`.


<!-- Sent from Reviewable.io -->

2024-01-16 14:44 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 21 of 30 files reviewed, 6 unresolved discussions (waiting on @liorgold2 and @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 110 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoHTah94VdM_ICiYH85:-NoHXlmO3t_LpPSeSOsK:b-xqju57) ([raw file](https://github.com/starkware-libs/cairo/blob/712011501d3b01ccab7e3c22adb85776ee27f321/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L110)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I don't like this. `felt` should be handled differently, not like all BoundedInts with size >= prime.
Specifically the downcast `BoundedInt<-(P-1), 0>  ->  BoundedInt<0, 10>` should return `None`
on the value `-(P - 1) == 1`. We think, it returns `Ok(1)` in the current code.

Add a test in `integer_test.cairo`.
</blockquote></details>

ok - just shrinking in-range instead of this support.
this would make it equivalent to `BoundedInt<-(P-1), 0> -> BoundedInt<0, 0>`.
added a test as well.
___
*[`tests/e2e_test_data/libfuncs/constrain_range` line 1 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoHT5bj6bHnADk5INq3:-NoHXb-52aJsZeNQkL6Y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/712011501d3b01ccab7e3c22adb85776ee27f321/tests/e2e_test_data/libfuncs/constrain_range#L1)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Rename file.
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/constrain_range` line 85 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoHRE9r56mLENcPzHiw:-NoHXbay9rq8GQs3Iw_R:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/712011501d3b01ccab7e3c22adb85776ee27f321/tests/e2e_test_data/libfuncs/constrain_range#L85)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

What does this test add on top of the previous one?
</blockquote></details>

Done.
___
*[`tests/e2e_test_data/libfuncs/constrain_range` line 255 at r5](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoHRbPV-aiojMWX_8Yb:-NoHXdXTEBE4TKgNaaIF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/712011501d3b01ccab7e3c22adb85776ee27f321/tests/e2e_test_data/libfuncs/constrain_range#L255)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Maybe check with a shifted range instead?
Anyway, add a comment to the test explaining what you're testing here.

Also, missing tests with MIN > 0 and MIN < 0.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-16 15:38 UTC, TomerStarkware approved these changes
> Reviewed 23 of 27 files at r1, 1 of 1 files at r2, 1 of 6 files at r4, 1 of 1 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: all files reviewed, 6 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 18 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoHusLD1hU_T3ux-kOz:-NoHusLE9d6YqGZFZ0_p:b-thawrg) ([raw file](https://github.com/starkware-libs/cairo/blob/4a65dc58a25272896afd8ad9f6e9b31e81d039e1/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L18)):*
> ```XML
> 
> /// Builds a libfunc that tries to convert a numeric value in the range
> /// in_range to out_range.
> ```

doc is wrong


<!-- Sent from Reviewable.io -->

2024-01-16 15:40 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: all files reviewed, 6 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 19 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoHvKm90loaaFSw6Zf9:-NoHvKm90loaaFSw6ZfA:b-235x1l) ([raw file](https://github.com/starkware-libs/cairo/blob/4a65dc58a25272896afd8ad9f6e9b31e81d039e1/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L19)):*
> ```XML
> /// Builds a libfunc that tries to convert a numeric value in the range
> /// in_range to out_range.
> /// Assumption: in_range.lower==out_range.lower==0.
> ```

doc refers to old variable with in_range


<!-- Sent from Reviewable.io -->

2024-01-16 15:44 UTC, TomerStarkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: all files reviewed, 6 unresolved discussions (waiting on @liorgold2)



<!-- Sent from Reviewable.io -->

2024-01-16 15:44 UTC, TomerStarkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: all files reviewed, 7 unresolved discussions (waiting on @liorgold2 and @orizi)



<!-- Sent from Reviewable.io -->

2024-01-17 13:39 UTC, TomerStarkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 28 of 30 files reviewed, 7 unresolved discussions (waiting on @liorgold2 and @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 35 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoMcrRDBKsuEYe4oX7b:-NoMcrRDBKsuEYe4oX7c:b-1u5v6m) ([raw file](https://github.com/starkware-libs/cairo/blob/24504ddf58d76a8423278f417006161644176480/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L35)):*
> ```XML
> ) -> Result<CompiledInvocation, InvocationError> {
>     // This also works for other values, that are bound by range check size, just suboptimal.
>     // `i128` is using this non-optimal implementation.
> ```

will not work for  BoundedInt<0,21267647932558654593650211470610268161> =  BoundedInt<0,prime%((1<<128)-2)>
compiler crush.
Maybe extract the check for validate_under_limit here as well


<!-- Sent from Reviewable.io -->

2024-01-18 12:54 UTC, TomerStarkware approved these changes
> Reviewed 1 of 7 files at r7, 12 of 12 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: all files reviewed, 6 unresolved discussions (waiting on @liorgold2)



<!-- Sent from Reviewable.io -->

2024-01-18 15:51 UTC, liorgold2 reviewed
> Reviewed 1 of 7 files at r7, 7 of 12 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 29 of 32 files reviewed, 5 unresolved discussions (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-01-18 16:24 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 29 of 32 files reviewed, 6 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`corelib/src/test/integer_test.cairo` line 1857 at r12](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoSJ9Gq6JkItP1E5TrI:-NoSJ9Gq6JkItP1E5TrJ:br0tm4q) ([raw file](https://github.com/starkware-libs/cairo/blob/8adf428d09f0bb18b22b6ac6415c04afd05fe5db/corelib/src/test/integer_test.cairo#L1857)):*
> ```Cairo
>     #[test]
>     fn test_special_casts() {
>         let x: BoundedInt<-1, -1> = downcast(-1_felt252).unwrap();
> ```

1. Check that as-is if you cancel intersect it will still pass.
2. Change test to `-0x80..11..00` (which is equivalent to 1 - a valid `u8` value).
3. Check that it fails if intersect is cancelled.


<!-- Sent from Reviewable.io -->

2024-01-18 16:27 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 29 of 32 files reviewed, 8 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`corelib/src/test/integer_test.cairo` line 1859 at r12](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoSOG_VA23_jtSAYi5U:-NoSOG_VA23_jtSAYi5V:baqv91c) ([raw file](https://github.com/starkware-libs/cairo/blob/8adf428d09f0bb18b22b6ac6415c04afd05fe5db/corelib/src/test/integer_test.cairo#L1859)):*
> ```Cairo
>         let x: BoundedInt<-1, -1> = downcast(-1_felt252).unwrap();
>         // Full prime range, but only contains `0` if intersected with `u8`.
>         let x: BoundedInt<-0x800000000000011000000000000000000000000000000000000000000000000, 0> =
> ```

Use type alias: say, `MinusPToZero`.


<!-- Sent from Reviewable.io -->

2024-01-18 16:43 UTC, liorgold2 requested changes
> Reviewed 1 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 29 of 32 files reviewed, 9 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/test.rs` line 303 at r12](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoSRnUsDWbCHXEX2IYY:-NoSRnUsDWbCHXEX2IYZ:bq9ei3g) ([raw file](https://github.com/starkware-libs/cairo/blob/8adf428d09f0bb18b22b6ac6415c04afd05fe5db/crates/cairo-lang-sierra/src/extensions/test.rs#L303)):*
> ```XML
> #[test_case("enum_snapshot_match", vec![type_arg("NonDupEnum")] => Ok(());
>             "enum_snapshot_match<NonDupEnum>")]
> #[test_case("downcast", vec![type_arg("BoundedInt0_10"), type_arg("BoundedInt0_3")]
> ```

Review changes in this file. Remove those unnecessary, and add more interesting (failing) ones. E.g., `felt -> [0, 2**129]` or `[0, 2**129] -> [0, 10]`


<!-- Sent from Reviewable.io -->

2024-01-18 16:56 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 29 of 32 files reviewed, 10 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 102 at r12](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoSUaap7PLTs-EIcN3U:-NoSUaap7PLTs-EIcN3V:b1hfzef) ([raw file](https://github.com/starkware-libs/cairo/blob/8adf428d09f0bb18b22b6ac6415c04afd05fe5db/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L102)):*
> ```XML
>         let to_range: Range = Range::from_type(context, to_ty.clone())?;
>         let from_range = Range::from_type(context, from_ty.clone())?;
>         // Shrinking the range of the destination type by the range of the source type.
> ```

Add something like
```
// This is necessary for example in the case `[0, PRIME) -> i8`.
// In this case `PRIME - 1` is a valid value in `from_range` and it is equivalent
// to `-1` in the field. Yet, we must make sure `PRIME - 1` is not downcasted to `-1`.
// By reducing `to_range`, we get a cast `[0, PRIME) -> u8` where `-1` is not
// in the output range.
```


<!-- Sent from Reviewable.io -->

2024-01-18 16:59 UTC, liorgold2 reviewed
> Reviewed 1 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 29 of 32 files reviewed, 9 unresolved discussions (waiting on @orizi and @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-01-18 19:57 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 29 of 32 files reviewed, 9 unresolved discussions (waiting on @liorgold2 and @TomerStarkware)

___
*[`corelib/src/test/integer_test.cairo` line 1857 at r12](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoSJ9Gq6JkItP1E5TrI:-NoT4MQeEahy4vzsKgfr:b-ji93xj) ([raw file](https://github.com/starkware-libs/cairo/blob/8adf428d09f0bb18b22b6ac6415c04afd05fe5db/corelib/src/test/integer_test.cairo#L1857)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

1. Check that as-is if you cancel intersect it will still pass.
2. Change test to `-0x80..11..00` (which is equivalent to 1 - a valid `u8` value).
3. Check that it fails if intersect is cancelled.
</blockquote></details>

1. Done
2. Done
3. Done
___
*[`corelib/src/test/integer_test.cairo` line 1859 at r12](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoSOG_VA23_jtSAYi5U:-NoT4IBZ637VZmleibpk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8adf428d09f0bb18b22b6ac6415c04afd05fe5db/corelib/src/test/integer_test.cairo#L1859)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Use type alias: say, `MinusPToZero`.
</blockquote></details>

Done.
___
*[`corelib/src/test/integer_test.cairo` line 1864 at r12](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoSNz3r15Lk1C7Unlo2:-NoT4Lol7OKtsSxuOZJK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8adf428d09f0bb18b22b6ac6415c04afd05fe5db/corelib/src/test/integer_test.cairo#L1864)):*
> ```Cairo
>         );
>         let x: Option<u8> = downcast(x);
>         assert!(x.is_none())
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/test.rs` line 303 at r12](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoSRnUsDWbCHXEX2IYY:-NoT7-uf71rekj15ref7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8adf428d09f0bb18b22b6ac6415c04afd05fe5db/crates/cairo-lang-sierra/src/extensions/test.rs#L303)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Review changes in this file. Remove those unnecessary, and add more interesting (failing) ones. E.g., `felt -> [0, 2**129]` or `[0, 2**129] -> [0, 10]`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 102 at r12](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NoSUaap7PLTs-EIcN3U:-NoT7cz36wp656sTR7VX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8adf428d09f0bb18b22b6ac6415c04afd05fe5db/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L102)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add something like
```
// This is necessary for example in the case `[0, PRIME) -> i8`.
// In this case `PRIME - 1` is a valid value in `from_range` and it is equivalent
// to `-1` in the field. Yet, we must make sure `PRIME - 1` is not downcasted to `-1`.
// By reducing `to_range`, we get a cast `[0, PRIME) -> u8` where `-1` is not
// in the output range.
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-20 19:10 UTC, liorgold2 requested changes
> Reviewed 1 of 7 files at r7, 1 of 1 files at r10, 1 of 3 files at r11, 2 of 2 files at r12, 3 of 4 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: all files reviewed, 13 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/test/integer_test.cairo` line 1863 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocAyUY09ccDO0qsu7y:-NocAyUY09ccDO0qsu7z:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/corelib/src/test/integer_test.cairo#L1863)):*
> ```Cairo
>         BoundedInt<0xffffffffffffffffffffffffffffffff, 0xffffffffffffffffffffffffffffffff>;
> 
>     /// Is `value` the equivalent value of `expected` in `T` type.
> ```





_Suggestion:_
```Cairo
/// Is `value` the equivalent value (as `felt252`) of `expected` in `T` type.
```
___
*[`corelib/src/test/integer_test.cairo` line 1878 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocBK-nELi82KPvMhxs:-NocBK-nELi82KPvMhxt:bl94jli) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/corelib/src/test/integer_test.cairo#L1878)):*
> ```Cairo
>     #[test]
>     fn test_felt252_downcasts() {
>         assert!(!felt252_downcast_valid::<BoundedInt<0, 0>>(1));
> ```

This can be one of two - either `None` or `Some` of a wrong value. In either case, be specific. E.g., assert it's `None` (e.g., add `felt252_downcast_invalid`).



_Code quote:_
```Cairo
!felt252_downcast_valid
```
___
*[`corelib/src/test/integer_test.cairo` line 1912 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocCC_u4-usYMBbSxN0:-NocCC_u4-usYMBbSxN1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/corelib/src/test/integer_test.cairo#L1912)):*
> ```Cairo
>         let zero = downcast::<felt252, BoundedInt<0, 0>>(0).unwrap();
>         assert!(downcast::<OneMinusPToZero, u8>(upcast(zero)) == Option::Some(0));
>         let minus_p = downcast::<felt252, OneMinusPOnly>(1).unwrap();
> ```





_Suggestion:_
```Cairo
one_minus_p
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 120 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocD_mO3dnGBEOi-0g8:-NocD_mO3dnGBEOi-0g9:b-z3xqck) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L120)):*
> ```XML
>         }
>         let is_small_values_downcast = from_range.is_small_range();
>         // Only allow `size < prime % u128::MAX` so that we can safely use `K=2` in
> ```

Are you sure it's `<` and not `<=`? (but maybe it's better to be on the safe side anyway)
___
*[`crates/cairo-lang-sierra/src/extensions/modules/utils.rs` line 107 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocEQOoCZmYCxwpSXY8:-NocEQOoCZmYCxwpSXY9:b-jjuj1t) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/crates/cairo-lang-sierra/src/extensions/modules/utils.rs#L107)):*
> ```XML
>     /// Returns the intersection of `self` and `other`.
>     pub fn intersection(&self, other: &Self) -> Self {
>         Self::half_open(
> ```

What happens if `self=[0, 10)` and `other=[20, 30)`?
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 20 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocF-ed9xYseZUKqxI0:-NocF-ed9xYseZUKqxI1:b-cssucc) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L20)):*
> ```XML
> /// Assumption: out_range.size() <= 2**128.
> ///
> /// Note: Usage is preferable where: `out_range.size()` <= `prime` % u128::MAX.
> ```

Note that here it still says `<=`.



_Suggestion:_
```XML
Note: Usage is preferable where: `out_range.size() <= prime % u128::MAX`
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 28 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocF7CF9G-QErEQC-EC:-NocF7CF9G-QErEQC-ED:b38bg8k) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L28)):*
> ```XML
> /// So the `A <= B` condition is satisfied.
> /// For smaller `out_range.size()` `A` will be almost u128::MAX and `B` will be smaller than
> /// necessary.
> ```

I tried to edit the paragraph, but I don't understand it's purpose so I stopped in the middle.
What are you trying to say here?
Does this belong to the documentation of the function, or should it be implementation comment inside the function?



_Suggestion:_
```XML
/// Note that for `size == prime % u128::MAX` we get (with K=1)
///     * `limit = prime - size`
///     * `A = limit % u128::MAX = 0`
///     * `B = limit / u128::MAX ≈ 2**123 + 17*2**64`
/// So the `A <= B` condition is satisfied.
/// For smaller `out_range.size()`, `A` will be almost u128::MAX and `B` will be smaller than
/// necessary.
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 45 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocGYI6EL3Q9B1eGmh6:-NocGYI6EL3Q9B1eGmh7:b-xdeme5) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L45)):*
> ```XML
>     builder: CompiledInvocationBuilder<'_>,
>     out_range: &Range,
>     optimal_range: bool,
> ```

Document this param.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 50 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocGd_O8Xt5LJSlmDM2:-NocGd_O8Xt5LJSlmDM3:bcss7lt) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L50)):*
> ```XML
>     if optimal_range {
>         assert!(out_range.size() < (&prime % u128::MAX));
>     }
> ```

Don't you need to check `out_range.size() <= 2**128` in the else branch?
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 82 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocGq587BNETyeS4YXy:-NocGq587BNETyeS4YXz:bp8xmj) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L82)):*
> ```XML
>     validate_under_limit::<2>(
>         &mut casm_builder,
>         &(prime - out_range.size()),
> ```

Maybe add an assert that `out_range.size() > 0`?


<!-- Sent from Reviewable.io -->

2024-01-20 19:18 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: all files reviewed, 14 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 49 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocIkz_BQF5ywpg3Wz7:-NocIkz_BQF5ywpg3Wz8:b-5eyojk) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L49)):*
> ```XML
>     let prime: BigInt = Felt252::prime().into();
>     if optimal_range {
>         assert!(out_range.size() < (&prime % u128::MAX));
> ```

Does this function work for larger values (`prime % u128::MAX` up to `2**128`)? (that is, with `K=2`)


<!-- Sent from Reviewable.io -->

2024-01-20 19:24 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: all files reviewed, 15 unresolved discussions (waiting on @orizi)

___
*[`tests/e2e_test_data/libfuncs/felt252_downcast` line 163 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocJP-95wcDMPLUF4RB:-NocJP-95wcDMPLUF4RC:bl5uuuu) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/tests/e2e_test_data/libfuncs/felt252_downcast#L163)):*
> ```
> //! > ==========================================================================
> 
> //! > downcast::<felt252, BoundedInt<0, 10633823966279327296825105735305134079>> libfunc
> ```

Why the change from 10633823966279327296825105735305134080 to 10633823966279327296825105735305134079?


<!-- Sent from Reviewable.io -->

2024-01-20 20:29 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: all files reviewed, 14 unresolved discussions (waiting on @liorgold2)

___
*[`corelib/src/test/integer_test.cairo` line 1878 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocBK-nELi82KPvMhxs:-NocXr7M1VV9IOOIzzr9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/corelib/src/test/integer_test.cairo#L1878)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This can be one of two - either `None` or `Some` of a wrong value. In either case, be specific. E.g., assert it's `None` (e.g., add `felt252_downcast_invalid`).
</blockquote></details>

Done.
___
*[`corelib/src/test/integer_test.cairo` line 1912 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocCC_u4-usYMBbSxN0:-NocXxPP6Vt20ZjJDfey:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/corelib/src/test/integer_test.cairo#L1912)):*
> ```Cairo
>         let zero = downcast::<felt252, BoundedInt<0, 0>>(0).unwrap();
>         assert!(downcast::<OneMinusPToZero, u8>(upcast(zero)) == Option::Some(0));
>         let minus_p = downcast::<felt252, OneMinusPOnly>(1).unwrap();
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/casts.rs` line 120 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocD_mO3dnGBEOi-0g8:-NocOY_X96qxzpnl2ocG:b-um8jp6) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/crates/cairo-lang-sierra/src/extensions/modules/casts.rs#L120)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Are you sure it's `<` and not `<=`? (but maybe it's better to be on the safe side anyway)
</blockquote></details>

yes - for == you can use K==1.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/utils.rs` line 107 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocEQOoCZmYCxwpSXY8:-NocPY7x8pWmGAV_MYeY:bxknhu1) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/crates/cairo-lang-sierra/src/extensions/modules/utils.rs#L107)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

What happens if `self=[0, 10)` and `other=[20, 30)`?
</blockquote></details>

made `is_empty` support this case, and `size` crash on the empty case.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 20 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocF-ed9xYseZUKqxI0:-NocQEb_0Zz6udqvZcIq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L20)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Note that here it still says `<=`.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 28 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocF7CF9G-QErEQC-EC:-NocRTrv2TyhrTE_Lec8:b-j8m7n3) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L28)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I tried to edit the paragraph, but I don't understand it's purpose so I stopped in the middle.
What are you trying to say here?
Does this belong to the documentation of the function, or should it be implementation comment inside the function?
</blockquote></details>

this is still about the cases where it is optimal to use the function.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 45 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocGYI6EL3Q9B1eGmh6:-NocRSJqDVoVJFRCbbjf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L45)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Document this param.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 49 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocIkz_BQF5ywpg3Wz7:-NocQRzN37N6biLmeEdk:b-wj54mu) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L49)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Does this function work for larger values (`prime % u128::MAX` up to `2**128`)? (that is, with `K=2`)
</blockquote></details>

not for all - but the `validate_under_limit` function check if it would work already.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 50 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocGd_O8Xt5LJSlmDM2:-NocQkiGAJn1NI3MZqV3:b-ra39lx) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L50)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Don't you need to check `out_range.size() <= 2**128` in the else branch?
</blockquote></details>

adding validation.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 82 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocGq587BNETyeS4YXy:-NocSQ0c4jO3TFMXqcs6:b-eie6or) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L82)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Maybe add an assert that `out_range.size() > 0`?
</blockquote></details>

this is now invalid generally.
___
*[`tests/e2e_test_data/libfuncs/felt252_downcast` line 163 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocJP-95wcDMPLUF4RB:-NocSbZU63SFv7FTOrcW:b-p2vxll) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/tests/e2e_test_data/libfuncs/felt252_downcast#L163)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Why the change from 10633823966279327296825105735305134080 to 10633823966279327296825105735305134079?
</blockquote></details>

the previous range was suboptimal - and should have used the K==1 variant.


<!-- Sent from Reviewable.io -->

2024-01-20 20:30 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 30 of 33 files reviewed, 14 unresolved discussions (waiting on @liorgold2 and @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/utils.rs` line 107 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocEQOoCZmYCxwpSXY8:-NocZEy2EGoM_dLZv04H:biwc80a) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/crates/cairo-lang-sierra/src/extensions/modules/utils.rs#L107)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

made `is_empty` support this case, and `size` crash on the empty case.
</blockquote></details>

nm - no crash - but testing empty on downcast.


<!-- Sent from Reviewable.io -->

2024-01-20 22:47 UTC, TomerStarkware approved these changes
> Reviewed 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: all files reviewed, 14 unresolved discussions (waiting on @liorgold2)



<!-- Sent from Reviewable.io -->

2024-01-21 08:04 UTC, TomerStarkware approved these changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: all files reviewed, 14 unresolved discussions (waiting on @liorgold2)



<!-- Sent from Reviewable.io -->

2024-01-21 11:37 UTC, liorgold2 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 33 of 34 files reviewed, 15 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`corelib/src/test/integer_test.cairo` line 1881 at r17](https://reviewable.io/reviews/starkware-libs/cairo/4813#-Nofnpv08jPVzphUr0up:-Nofnpv08jPVzphUr0uq:b7ljfi8) ([raw file](https://github.com/starkware-libs/cairo/blob/dc59fbb11eb5c62df14aea80f7cc972ee950aaff/corelib/src/test/integer_test.cairo#L1881)):*
> ```Cairo
>             Option::Some(v) => {
>                 // Just as a drop for `v`.
>                 upcast::<_, felt252>(v);
> ```

Won't `downcast_invalid<T, S, +Drop<T>>` work?


<!-- Sent from Reviewable.io -->

2024-01-21 11:37 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 33 of 34 files reviewed, 15 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`corelib/src/test/integer_test.cairo` line 1881 at r17](https://reviewable.io/reviews/starkware-libs/cairo/4813#-Nofnpv08jPVzphUr0up:-Nofnym_6tjgT1lC43G4:b-2vrpu9) ([raw file](https://github.com/starkware-libs/cairo/blob/dc59fbb11eb5c62df14aea80f7cc972ee950aaff/corelib/src/test/integer_test.cairo#L1881)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Won't `downcast_invalid<T, S, +Drop<T>>` work?
</blockquote></details>

(sorry, `Drop<S>`)


<!-- Sent from Reviewable.io -->

2024-01-21 11:40 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 33 of 34 files reviewed, 15 unresolved discussions (waiting on @liorgold2 and @TomerStarkware)

___
*[`corelib/src/test/integer_test.cairo` line 1881 at r17](https://reviewable.io/reviews/starkware-libs/cairo/4813#-Nofnpv08jPVzphUr0up:-NofoNQz7TZ8wfTecuXk:b-2p23ce) ([raw file](https://github.com/starkware-libs/cairo/blob/dc59fbb11eb5c62df14aea80f7cc972ee950aaff/corelib/src/test/integer_test.cairo#L1881)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

(sorry, `Drop<S>`)
</blockquote></details>

no - as i'd need to implement it per any BoundedInt specifically - as a generic implementation of `const` generic params is not supported.


<!-- Sent from Reviewable.io -->

2024-01-21 11:59 UTC, liorgold2 requested changes
> Reviewed 2 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 33 of 34 files reviewed, 11 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/utils.rs` line 107 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocEQOoCZmYCxwpSXY8:-NofoABxEdHN0QIM9iry:b-g8sf40) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/crates/cairo-lang-sierra/src/extensions/modules/utils.rs#L107)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

nm - no crash - but testing empty on downcast.
</blockquote></details>

I think I prefer `intersection` to return `Maybe<Self>`.
You could also return `[x, x)` for an arbitrary `x` but I find this less explicit.
I don't like having invalid ranges.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 19 at r17](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NofpDGY6nGvRp_Rhr_5:-NofpDGY6nGvRp_Rhr_6:b-fdxg4q) ([raw file](https://github.com/starkware-libs/cairo/blob/dc59fbb11eb5c62df14aea80f7cc972ee950aaff/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L19)):*
> ```XML
> /// Builds a libfunc that tries to convert a numeric value in the felt252 range to `out_range`.
> /// If `optimal_range` is true will only work for ranges smaller than `prime` % u128::MAX.
> /// Assumption: out_range.size() <= 2**128.
> ```

(without the blank lines it appears as one paragraph in the HTML doc)



_Suggestion:_
```XML
/// Builds a libfunc that tries to convert a numeric value in the felt252 range to `out_range`.
///
/// If `optimal_range` is true, the function will fail for ranges larger than `prime` % u128::MAX.
///
/// Assumption: out_range.size() <= 2**128.
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 46 at r17](https://reviewable.io/reviews/starkware-libs/cairo/4813#-Nofpe00-pWhNxE0E_pV:-Nofpe00-pWhNxE0E_pW:b-ji74if) ([raw file](https://github.com/starkware-libs/cairo/blob/dc59fbb11eb5c62df14aea80f7cc972ee950aaff/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L46)):*
> ```XML
>     builder: CompiledInvocationBuilder<'_>,
>     out_range: &Range,
>     optimal_range: bool,
> ```

(or `verify_optimal_range`)



_Suggestion:_
```XML
check_optimal_range
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 53 at r17](https://reviewable.io/reviews/starkware-libs/cairo/4813#-Nofp4vo0uEjv0GELOAe:-Nofp4vo0uEjv0GELOAf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/dc59fbb11eb5c62df14aea80f7cc972ee950aaff/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L53)):*
> ```XML
>     }
>     assert!(out_range.is_small_range(), "Algorithm only works for small target ranges.");
>     assert!(!out_range.is_empty(), "Algorithm doesn't work for empty target ranges.");
> ```





_Suggestion:_
```XML
    if optimal_range {
        assert!(out_range.size() < (&prime % u128::MAX), "build_felt252_range_reduction is suboptimal for this range.");
    }
    assert!(out_range.is_small_range(), "build_felt252_range_reduction only works for small target ranges.");
    assert!(!out_range.is_empty(), "build_felt252_range_reduction doesn't work for empty target ranges.");
```


<!-- Sent from Reviewable.io -->

2024-01-21 12:00 UTC, liorgold2 reviewed
> Reviewed 1 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 33 of 34 files reviewed, 11 unresolved discussions (waiting on @orizi and @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-01-21 12:12 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 33 of 34 files reviewed, 11 unresolved discussions (waiting on @liorgold2 and @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/utils.rs` line 107 at r14](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NocEQOoCZmYCxwpSXY8:-NoftAQHBtYNQwKZ1wM2:bxty3cs) ([raw file](https://github.com/starkware-libs/cairo/blob/6527adcb10e07d4fe2db368bef6bd9ad693afd8e/crates/cairo-lang-sierra/src/extensions/modules/utils.rs#L107)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I think I prefer `intersection` to return `Maybe<Self>`.
You could also return `[x, x)` for an arbitrary `x` but I find this less explicit.
I don't like having invalid ranges.
</blockquote></details>

it is a valid empty range - but adding.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 19 at r17](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NofpDGY6nGvRp_Rhr_5:-NofuPwc9CehO-dL_V95:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dc59fbb11eb5c62df14aea80f7cc972ee950aaff/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L19)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

(without the blank lines it appears as one paragraph in the HTML doc)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 46 at r17](https://reviewable.io/reviews/starkware-libs/cairo/4813#-Nofpe00-pWhNxE0E_pV:-Nofu9L23gYI6xLebWgN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dc59fbb11eb5c62df14aea80f7cc972ee950aaff/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L46)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

(or `verify_optimal_range`)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 53 at r17](https://reviewable.io/reviews/starkware-libs/cairo/4813#-Nofp4vo0uEjv0GELOAe:-Nofu3Ki2k6lbjKzkcTm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dc59fbb11eb5c62df14aea80f7cc972ee950aaff/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L53)):*
> ```XML
>     }
>     assert!(out_range.is_small_range(), "Algorithm only works for small target ranges.");
>     assert!(!out_range.is_empty(), "Algorithm doesn't work for empty target ranges.");
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-01-22 09:35 UTC, liorgold2 reviewed
> Reviewed 1 of 7 files at r7, 1 of 1 files at r17, 2 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 33 of 34 files reviewed, 7 unresolved discussions (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-01-22 10:47 UTC, liorgold2 reviewed
> Reviewed 1 of 12 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 33 of 34 files reviewed, 6 unresolved discussions (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-01-22 11:54 UTC, liorgold2 reviewed
> Reviewed 1 of 12 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 33 of 34 files reviewed, 5 unresolved discussions (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-01-22 12:04 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 33 of 34 files reviewed, 8 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 25 at r19](https://reviewable.io/reviews/starkware-libs/cairo/4813#-Nol2FsGAGMayXIkUn7r:-Nol2FsGAGMayXIkUn7s:btkzm9n) ([raw file](https://github.com/starkware-libs/cairo/blob/75f3d0145d22a3b82c45ab39a03249ac10372c9a/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L25)):*
> ```XML
> ///
> /// Note: Usage is preferable where: `out_range.size() < prime % u128::MAX`.
> /// Since when `2**128 >= out_range.size() >= prime % u128::MAX` we can use `validate_under_limit`
> ```

```
The function doesn't generate optimal code in the range `prime % u128::MAX <= out_range.size() <= 2**128` since in such a case `K=1` can be used in `validate_under_limit`.
```
Remove the rest of the paragraph.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 93 at r19](https://reviewable.io/reviews/starkware-libs/cairo/4813#-Nol2juF8y9xNMNSVK47:-Nol2juF8y9xNMNSVK48:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/75f3d0145d22a3b82c45ab39a03249ac10372c9a/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L93)):*
> ```XML
>     };
> 
>     // asserts that `value - out_range.upper < prime - out_range.size()`
> ```





_Suggestion:_
```XML
// Assert that `value - out_range.upper < prime - out_range.size()`.
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 95 at r19](https://reviewable.io/reviews/starkware-libs/cairo/4813#-Nol2dUv5q529ZGK0lpT:-Nol2dUv5q529ZGK0lpU:b-9cq8do) ([raw file](https://github.com/starkware-libs/cairo/blob/75f3d0145d22a3b82c45ab39a03249ac10372c9a/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L95)):*
> ```XML
>     // asserts that `value - out_range.upper < prime - out_range.size()`
>     let auxiliary_vars: [_; 5] = std::array::from_fn(|_| casm_builder.alloc_var(false));
>     validate_under_limit::<2>(
> ```

Add a comment with a proof that K=2 works.


<!-- Sent from Reviewable.io -->

2024-01-22 12:07 UTC, liorgold2 reviewed
> Reviewed 2 of 12 files at r9, 1 of 3 files at r18.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: all files reviewed, 6 unresolved discussions (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-01-22 12:28 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: all files reviewed, 6 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 25 at r19](https://reviewable.io/reviews/starkware-libs/cairo/4813#-Nol2FsGAGMayXIkUn7r:-Nol7ZSn4Rnd98iBBZe-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/75f3d0145d22a3b82c45ab39a03249ac10372c9a/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L25)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

```
The function doesn't generate optimal code in the range `prime % u128::MAX <= out_range.size() <= 2**128` since in such a case `K=1` can be used in `validate_under_limit`.
```
Remove the rest of the paragraph.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 93 at r19](https://reviewable.io/reviews/starkware-libs/cairo/4813#-Nol2juF8y9xNMNSVK47:-Nol7g7r2CM4f_pAO-pY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/75f3d0145d22a3b82c45ab39a03249ac10372c9a/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L93)):*
> ```XML
>     };
> 
>     // asserts that `value - out_range.upper < prime - out_range.size()`
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 95 at r19](https://reviewable.io/reviews/starkware-libs/cairo/4813#-Nol2dUv5q529ZGK0lpT:-Nol85R-41ikC9aeSbKd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/75f3d0145d22a3b82c45ab39a03249ac10372c9a/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L95)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add a comment with a proof that K=2 works.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-22 13:16 UTC, liorgold2 reviewed
> Reviewed 4 of 5 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 33 of 34 files reviewed, 1 unresolved discussion (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-01-22 14:09 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 33 of 34 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 80 at r20](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NolUuil0Z76ArweNF2L:-NolUuil0Z76ArweNF2M:bpsrbrb) ([raw file](https://github.com/starkware-libs/cairo/blob/09ed530e71249ccb9f99c0008a1f2d31f545fdaf/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L80)):*
> ```XML
>     //   `out_range.size() == prime % u128::MAX - 1 - x` we get:
>     //     * limit = prime - size
>     //     * A = limit % (u128::MAX - 1) = 2**123 + 17*2**64 + x
> ```

Are you sure that the numbers here are correct? Shouldn't it be `2**124 + 17 * 2**65 + 1 + x`?



_Code quote:_
```XML
A = limit % (u128::MAX - 1) = 2**123 + 17*2**64 + x
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 84 at r20](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NolJTAk9Rn2o5vz_ubb:-NolJTAk9Rn2o5vz_ubc:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/09ed530e71249ccb9f99c0008a1f2d31f545fdaf/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L84)):*
> ```XML
>     // Since `x < prime % u128::MAX - 1 < u128::MAX - 1` so the `A <= B` condition is satisfied.
>     // The other cases would work if `validate_under_limit` assertions pass (the only such case
>     // currently called is the felt252 to i128 cast).
> ```





_Suggestion:_
```XML
    // `validate_under_limit` is guaranteed to work with `K=2` for `out_range.size() < prime % u128::MAX`:
    // Let `x` be such that `out_range.size() == prime % u128::MAX - 1 - x`.
    // We have:
    //   * `0 <= x < prime % u128::MAX - 1`,
    //   * `limit = prime - size`,
    //   * `A = limit % (u128::MAX - 1) = 2**123 + 17*2**64 + x`,
    //   * `B = limit / (u128::MAX - 1) = 2**123 + 17*2**64 + 1 + x / (u128::MAX - 1)`.
    // Since `x < prime % u128::MAX - 1 < u128::MAX - 1` so the `A <= B` condition is satisfied.
    // The other cases would work if `validate_under_limit` assertions pass (the only such case
    // currently called is the felt252 to i128 cast).
```


<!-- Sent from Reviewable.io -->

2024-01-22 14:43 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 33 of 34 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 80 at r20](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NolUuil0Z76ArweNF2L:-NolbcDS7-UlAHBDYysn:b85v05o) ([raw file](https://github.com/starkware-libs/cairo/blob/09ed530e71249ccb9f99c0008a1f2d31f545fdaf/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L80)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Are you sure that the numbers here are correct? Shouldn't it be `2**124 + 17 * 2**65 + 1 + x`?
</blockquote></details>

that is what the calculation gives.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 84 at r20](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NolJTAk9Rn2o5vz_ubb:-Nolc04nAUX9K8eonSaW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/09ed530e71249ccb9f99c0008a1f2d31f545fdaf/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L84)):*
> ```XML
>     // Since `x < prime % u128::MAX - 1 < u128::MAX - 1` so the `A <= B` condition is satisfied.
>     // The other cases would work if `validate_under_limit` assertions pass (the only such case
>     // currently called is the felt252 to i128 cast).
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-01-22 15:00 UTC, liorgold2 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 33 of 34 files reviewed, 1 unresolved discussion (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-01-22 15:01 UTC, liorgold2 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: 33 of 34 files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs` line 80 at r20](https://reviewable.io/reviews/starkware-libs/cairo/4813#-NolUuil0Z76ArweNF2L:-Nolfw5R25oTyXqjUggB:b-h2rk6h) ([raw file](https://github.com/starkware-libs/cairo/blob/09ed530e71249ccb9f99c0008a1f2d31f545fdaf/crates/cairo-lang-sierra-to-casm/src/invocations/range_reduction.rs#L80)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

that is what the calculation gives.
</blockquote></details>

I'm missing something, but you can merge - we'll review it in the audit tomorrow.


<!-- Sent from Reviewable.io -->

2024-01-22 15:01 UTC, liorgold2 approved these changes
> Reviewed 1 of 1 files at r21.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-01-22 15:01 UTC, liorgold2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4813#-:-NolgBc91Ow-uPXkfMEF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-01-22 15:11 UTC, merged