Extract CfgSet from crate config in ConfigPlugin
starkware-libs/cairo pull request #4831
Opened 2024-01-18 07:26 UTC by szymmis

There is an ongoing process of supporting dev dependencies in Scarb. 
Currently, when a project is compiled with the test config, all deps are compiled as such as well. This results in the compilation of tests within those dependencies. Apart from slowing down the overall compilation process (stdlib tests are compiled unnecessarily), it is also a problem for dev dependencies. Test suites within dev dependencies may rely on other dev dependencies, which are not propagated when the package is used in the root project.

This PR introduces an extra parameter to the `MacroPlugin::generate_code` function.
This allows the passage of additional metadata to each node within macro plugins. Specifically, crate configuration is used to determine `CfgSet` for each node, rather than uniformly applying `db.cfg_set()` to all nodes. To achieve that `CrateSettings` struct was expanded with a new property: `cfg_set`.

Adding `CfgSet` prop to hashable `CrateSettings` would not be possible without changing implementation of the `CfgSet` itself, so now it is using `Vec` instead of `OrderedHashSet` thanks to the @murek suggestion.

This change allows setting "test" config to the root crate and "lib" for every other crate for example, which will result in compiling tests in the root crate only.

2024-01-18 08:20 UTC, orizi requested changes
> Reviewed 10 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4831)* status: 10 of 17 files reviewed, 2 unresolved discussions (waiting on @mkaput and @szymmis)

___
*[`crates/cairo-lang-defs/src/plugin.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4831#-NoQbfPs1NiSpR5dcc-8:-NoQbfPt9NF7cFG5OjAq:bqpd3fb) ([raw file](https://github.com/starkware-libs/cairo/blob/74f3bf8662cf2a65a48a811e2978262ed27a2ba6/crates/cairo-lang-defs/src/plugin.rs#L79)):*
> ```XML
> }
> 
> pub struct MacroPluginMetadata {
> ```

doc, including members.
___
*[`crates/cairo-lang-filesystem/src/cfg.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4831#-NoQdDte97l1nNa_dw-s:-NoQdDte97l1nNa_dw-t:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/74f3bf8662cf2a65a48a811e2978262ed27a2ba6/crates/cairo-lang-filesystem/src/cfg.rs#L82)):*
> ```XML
> /// This allows expressing, for example, the `feature` option that Rust/Cargo does.
> #[derive(Clone, Default, Eq, Hash, PartialEq, Serialize, Deserialize)]
> pub struct CfgSet(Vec<Cfg>);
> ```





_Suggestion:_
```XML
pub struct CfgSet(BTreeSet<Cfg>);
```


<!-- Sent from Reviewable.io -->

2024-01-18 10:08 UTC, mkaput requested changes
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4831)* status: all files reviewed, 3 unresolved discussions (waiting on @szymmis)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4831#-NoR1JJe2HyUroZLBPYy:-NoR1JJf0UJZL0mk2YGp:b-crouou) ([raw file](https://github.com/starkware-libs/cairo/blob/74f3bf8662cf2a65a48a811e2978262ed27a2ba6/crates/cairo-lang-plugins/src/plugins/config.rs#L37)):*
> ```XML
>             .as_ref()
>             .and_then(|cfg| cfg.settings.cfg_set.as_ref())
>             .unwrap_or(db_cfg_set.as_ref());
> ```

I think it would make more sense to do this merging outside of plugins, wherever `MacroPluginMetadata` is created


<!-- Sent from Reviewable.io -->

2024-01-18 12:48 UTC, szymmis reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4831)* status: 6 of 17 files reviewed, 3 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-defs/src/plugin.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4831#-NoQbfPs1NiSpR5dcc-8:-NoRWxZbCs9Y28TKbIBI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/74f3bf8662cf2a65a48a811e2978262ed27a2ba6/crates/cairo-lang-defs/src/plugin.rs#L79)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc, including members.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-filesystem/src/cfg.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4831#-NoQdDte97l1nNa_dw-s:-NoRVg0YAvFY_CIQKrU7:b-sdkq50) ([raw file](https://github.com/starkware-libs/cairo/blob/74f3bf8662cf2a65a48a811e2978262ed27a2ba6/crates/cairo-lang-filesystem/src/cfg.rs#L82)):*
> ```XML
> /// This allows expressing, for example, the `feature` option that Rust/Cargo does.
> #[derive(Clone, Default, Eq, Hash, PartialEq, Serialize, Deserialize)]
> pub struct CfgSet(Vec<Cfg>);
> ```

Seems like BTreeSet cannot be used instead of Vec because the ordering is messed up. 
For example when serializing and deserializing the set in `cfg::tests::serde` or comparing the sets after merging them in `cairo_lang_filesystem::db_test::test_cfgs`.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4831#-NoR1JJe2HyUroZLBPYy:-NoRX09g19d9vWqGnU1k:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/74f3bf8662cf2a65a48a811e2978262ed27a2ba6/crates/cairo-lang-plugins/src/plugins/config.rs#L37)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I think it would make more sense to do this merging outside of plugins, wherever `MacroPluginMetadata` is created
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-18 12:52 UTC, orizi requested changes
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4831)* status: all files reviewed, 3 unresolved discussions (waiting on @mkaput and @szymmis)

___
*[`crates/cairo-lang-defs/src/plugin.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4831#-NoRbgZm-cYG8l1oAKwH:-NoRbgZm-cYG8l1oAKwI:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/af835c8a5678233b292901a951a90b83fc9ad957/crates/cairo-lang-defs/src/plugin.rs#L80)):*
> ```XML
> 
> /// A structure containing additional info about
> /// the current module item on which macro plugin operates.
> ```





_Suggestion:_
```XML
/// A structure containing additional info about the current module item on which macro plugin
/// operates.
```
___
*[`crates/cairo-lang-filesystem/src/cfg.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4831#-NoQdDte97l1nNa_dw-s:-NoRc5mFEFqfUq_w91V2:b-g2xyt1) ([raw file](https://github.com/starkware-libs/cairo/blob/74f3bf8662cf2a65a48a811e2978262ed27a2ba6/crates/cairo-lang-filesystem/src/cfg.rs#L82)):*
<details><summary><i>Previously, szymmis (Szymon Miśtal) wrote…</i></summary><blockquote>

Seems like BTreeSet cannot be used instead of Vec because the ordering is messed up. 
For example when serializing and deserializing the set in `cfg::tests::serde` or comparing the sets after merging them in `cairo_lang_filesystem::db_test::test_cfgs`.
</blockquote></details>

So separate it to a serialization struct and a work struct - this is not good.


<!-- Sent from Reviewable.io -->

2024-01-19 07:39 UTC, szymmis reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4831)* status: 15 of 17 files reviewed, 3 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-defs/src/plugin.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/cairo/4831#-NoRbgZm-cYG8l1oAKwH:-NoVdqHqCIYrDpKScso7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/af835c8a5678233b292901a951a90b83fc9ad957/crates/cairo-lang-defs/src/plugin.rs#L80)):*
> ```XML
> 
> /// A structure containing additional info about
> /// the current module item on which macro plugin operates.
> ```

Done.
___
*[`crates/cairo-lang-filesystem/src/cfg.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4831#-NoQdDte97l1nNa_dw-s:-NoVdr314T83lLW_zXcx:bhbcgio) ([raw file](https://github.com/starkware-libs/cairo/blob/74f3bf8662cf2a65a48a811e2978262ed27a2ba6/crates/cairo-lang-filesystem/src/cfg.rs#L82)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

So separate it to a serialization struct and a work struct - this is not good.
</blockquote></details>

Done. I must have misunderstood something when I was messing around with it before because it is working very nice now. No need to separate it in any kind, simple swap to BTreeSet was enough. Thanks for the suggestion.


<!-- Sent from Reviewable.io -->

2024-01-19 07:51 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 17 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4831#-:-NoVh1dD4gSt5KhWmnrV:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2024-01-19 07:51 UTC, orizi approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4831)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2024-01-19 09:40 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 10 of 11 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4831#-:-NoW50RI6yeZVjcVupyH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @szymmis)



<!-- Sent from Reviewable.io -->

2024-01-19 09:45 UTC, merged