changed plugins for serde and store of enums to use match, Note that …
starkware-libs/cairo pull request #4835
Opened 2024-01-18 10:59 UTC by TomerStarkware

…using match libfuncs is better for match of size >=8

2024-01-18 11:10 UTC, orizi requested changes
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4835)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4835#-NoRF3Cl8_yuvSG5ZSq1):*
change commit message.
Add the notes about the optimization to be only on the third line of the message.


<!-- Sent from Reviewable.io -->

2024-01-18 11:29 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4835)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4835#-NoRF3Cl8_yuvSG5ZSq1):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

change commit message.
Add the notes about the optimization to be only on the third line of the message.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-18 11:32 UTC, orizi reviewed
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4835)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-01-23 10:37 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4835#-:-NoptOWw7Q8ZZy-LHOLx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-01-23 10:42 UTC, merged