Add cairo functions basic profiling and change profiler tests accordingly.
starkware-libs/cairo pull request #4878
Opened 2024-01-22 17:24 UTC by gilbens-starkware

**Stack**:
- #4878 ⬅
- #4877
- #4876
- #4854
- #4853
- #4852

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-01-22 17:49 UTC, orizi requested changes
> Reviewed 4 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4878)* status: 4 of 9 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-runner/src/profiling.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NomH9HJA9KA5mXCKhv8:-NomH9HJA9KA5mXCKhv9:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/172da762c4b292b0069adf8270b819e01bd01508/crates/cairo-lang-runner/src/profiling.rs#L35)):*
> ```XML
>     pub cairo_functions_weights: Option<OrderedHashMap<String, usize>>,
>     // Weight (in steps in the relevant run) of return statements.
>     pub return_weight: usize,
> ```





_Suggestion:_
```XML
    pub sierra_statements_weights:
        OrderedHashMap<StatementIdx, (usize, GenStatement<StatementIdx>)>,
    /// Weight (in steps in the relevant run) of each concrete libfunc.
    pub concrete_libfuncs_weights: Option<OrderedHashMap<SmolStr, usize>>,
    /// Weight (in steps in the relevant run) of each generic libfunc.
    pub generic_libfuncs_weights: Option<OrderedHashMap<SmolStr, usize>>,
    /// Weight (in steps in the relevant run) of each high level function.
    pub cairo_functions_weights: Option<OrderedHashMap<String, usize>>,
    /// Weight (in steps in the relevant run) of return statements.
    pub return_weight: usize,
```
___
*[`crates/cairo-lang-runner/src/profiling_test_data/profiling` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NomHRf63iWW-sisIOHV:-NomHRf63iWW-sisIOHW:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/172da762c4b292b0069adf8270b819e01bd01508/crates/cairo-lang-runner/src/profiling_test_data/profiling#L53)):*
> ```
>   return: 6
> Weight by high level function:
>   function Unknown function: 18
> ```

?



_Code quote:_
```
  function Unknown function:
```
___
*[`crates/cairo-lang-runner/src/profiling_test_data/profiling` line 157 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NomHU9i6s7ETcrMg0By:-NomHU9i6s7ETcrMg0Bz:b32vmt) ([raw file](https://github.com/starkware-libs/cairo/blob/172da762c4b292b0069adf8270b819e01bd01508/crates/cairo-lang-runner/src/profiling_test_data/profiling#L157)):*
> ```
>   return: 9
> Weight by high level function:
>   function Unknown function: 106
> ```

??



_Code quote:_
```
  function Unknown function: 106
```


<!-- Sent from Reviewable.io -->

2024-01-23 09:39 UTC, yuvalsw requested changes
> Reviewed 5 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4878)* status: all files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-runner/src/profiling.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NopaeS_0CBGVF2qBevt:-NopaeS_0CBGVF2qBevu:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c42277c7d4f0915b62518a328d02c8eb564d0aeb/crates/cairo-lang-runner/src/profiling.rs#L32)):*
> ```XML
>     // Weight (in steps in the relevant run) of each generic libfunc.
>     pub generic_libfuncs_weights: Option<OrderedHashMap<SmolStr, usize>>,
>     // Weight (in steps in the relevant run) of each high level function.
> ```





_Suggestion:_
```XML
of each Cairo function.
```
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-Nopb5cFE8sbiCvRL5M9:-Nopb5cFE8sbiCvRL5MA:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/c42277c7d4f0915b62518a328d02c8eb564d0aeb/crates/cairo-lang-runner/src/profiling.rs#L58)):*
> ```XML
>         }
>         if let Some(cairo_functions_weights) = &self.cairo_functions_weights {
>             writeln!(f, "Weight by high level function:")?;
> ```





_Suggestion:_
```XML
Cairo
```
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NopbIe08Yn4HZIYxNHi:-NopbIe08Yn4HZIYxNHj:b-ixfbk1) ([raw file](https://github.com/starkware-libs/cairo/blob/c42277c7d4f0915b62518a328d02c8eb564d0aeb/crates/cairo-lang-runner/src/profiling.rs#L78)):*
> ```XML
>     pub process_by_concrete_libfunc: bool,
>     pub process_by_generic_libfunc: bool,
>     pub process_by_high_level_function: bool,
> ```

s/high level/Cairo/ everywhere. High-level might sound like a description for some subset of functions, while Cairo is very clear (and also shorter)
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NopbdlU0utalVuzCuxp:-NopbdlU0utalVuzCuxq:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/c42277c7d4f0915b62518a328d02c8eb564d0aeb/crates/cairo-lang-runner/src/profiling.rs#L94)):*
> ```XML
> pub struct ProfilingInfoProcessor {
>     sierra_program: Program,
>     statements_functions: HashMap<StatementIdx, String>,
> ```

doc
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NopfcHKEMj4CL81tzl2:-NopfcHKEMj4CL81tzl3:b-zdq5jn) ([raw file](https://github.com/starkware-libs/cairo/blob/c42277c7d4f0915b62518a328d02c8eb564d0aeb/crates/cairo-lang-runner/src/profiling.rs#L171)):*
> ```XML
>                             .statements_functions
>                             .get(statement_idx)
>                             .unwrap_or(&"Unknown function".to_string())
> ```

When there are no more such, should this panic?



_Suggestion:_
```XML
.unwrap_or("Unknown function")
```
___
*[`crates/cairo-lang-runner/src/profiling_test_data/profiling` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NomHRf63iWW-sisIOHV:-NopfQsz1uyynep77qbL:bbg71gt) ([raw file](https://github.com/starkware-libs/cairo/blob/c42277c7d4f0915b62518a328d02c8eb564d0aeb/crates/cairo-lang-runner/src/profiling_test_data/profiling#L53)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Blocking on this too
___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-Nopei7_B36rsheNkdLy:-Nopei7_B36rsheNkdLz:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c42277c7d4f0915b62518a328d02c8eb564d0aeb/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L94)):*
> ```XML
>     /// that contains it. (See [containing_function_identifier]). It is used for places with db
>     /// access such as the profiler.
>     // TODO(Gil): Add a db access to the profiler and remove this function.
> ```





_Suggestion:_
```XML
    /// Builds a map between the Sierra statement index and a string representation of the Cairo function
    /// that it was built from (see [containing_function_identifier]). It is used for places without db
    /// access such as the profiler.
    // TODO(Gil): Add a db access to the profiler and remove this function.
```
___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NopaJH94hao04RBTCSZ:-NopaJH94hao04RBTCS_:b-7juvf5) ([raw file](https://github.com/starkware-libs/cairo/blob/c42277c7d4f0915b62518a328d02c8eb564d0aeb/crates/cairo-lang-test-plugin/src/lib.rs#L147)):*
> ```XML
>     pub sierra_program: Program,
>     #[serde(skip)]
>     pub statements_functions: HashMap<StatementIdx, String>,
> ```

please doc.
Why is it skipped in serde?


<!-- Sent from Reviewable.io -->

2024-01-23 09:53 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4878)* status: all files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-runner/src/profiling_test_data/profiling` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NomHRf63iWW-sisIOHV:-NopjIwoB_Q06giIBHvV:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/c42277c7d4f0915b62518a328d02c8eb564d0aeb/crates/cairo-lang-runner/src/profiling_test_data/profiling#L53)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Blocking on this too
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2024-01-23 11:53 UTC, yuvalsw reviewed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4878)* status: all files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2024-01-23 12:47 UTC, orizi requested changes
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4878)* status: all files reviewed (commit messages unreviewed), 10 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 101 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NoqM0tA4bq_RgHQ7vzB:-NoqM0tA4bq_RgHQ7vzC:b-blz4bq) ([raw file](https://github.com/starkware-libs/cairo/blob/287f26ddd20b2539a7850ec21fa1928be343d763/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L101)):*
> ```XML
>             .iter_sorted()
>             .map(|(idx, location)| (*idx, containing_function_identifier(db, Some(*location))))
>             .collect()
> ```

aggregate



_Code quote:_
```XML
        self.locations
            .iter_sorted()
            .map(|(idx, location)| (*idx, containing_function_identifier(db, Some(*location))))
            .collect()
```


<!-- Sent from Reviewable.io -->

2024-01-23 13:30 UTC, yuvalsw reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4878)* status: all files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2024-01-23 14:49 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4878)* status: all files reviewed, 9 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-runner/src/profiling.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NopaeS_0CBGVF2qBevt:-NoqiTwQAyC9ej1vioJE:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6948dd334c4f11b1b18454497ce23dd0f1359b72/crates/cairo-lang-runner/src/profiling.rs#L32)):*
> ```XML
>     // Weight (in steps in the relevant run) of each generic libfunc.
>     pub generic_libfuncs_weights: Option<OrderedHashMap<SmolStr, usize>>,
>     // Weight (in steps in the relevant run) of each high level function.
> ```

Done.
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NopbIe08Yn4HZIYxNHi:-NoqiWzV9sxptpBzR5sL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6948dd334c4f11b1b18454497ce23dd0f1359b72/crates/cairo-lang-runner/src/profiling.rs#L78)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

s/high level/Cairo/ everywhere. High-level might sound like a description for some subset of functions, while Cairo is very clear (and also shorter)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NopbdlU0utalVuzCuxp:-NoqmVvHAcoYE-SBY7-o:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6948dd334c4f11b1b18454497ce23dd0f1359b72/crates/cairo-lang-runner/src/profiling.rs#L94)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NopfcHKEMj4CL81tzl2:-NoqijSS5IcFs7IrVOmT:b-stxbiy) ([raw file](https://github.com/starkware-libs/cairo/blob/6948dd334c4f11b1b18454497ce23dd0f1359b72/crates/cairo-lang-runner/src/profiling.rs#L171)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

When there are no more such, should this panic?
</blockquote></details>

The type returned by get is `&String` and not `&str` (one on heap and one on stack)
___
*[`crates/cairo-lang-runner/src/profiling_test_data/profiling` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NomHRf63iWW-sisIOHV:-NoqinxT2qaKJL9mkwfB:bqvx3kz) ([raw file](https://github.com/starkware-libs/cairo/blob/6948dd334c4f11b1b18454497ce23dd0f1359b72/crates/cairo-lang-runner/src/profiling_test_data/profiling#L53)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Some locations are still `None`, it is better now, but 
___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-Nopei7_B36rsheNkdLy:-Noqi1vvElAqibDl9wRz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6948dd334c4f11b1b18454497ce23dd0f1359b72/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L94)):*
> ```XML
>     /// that contains it. (See [containing_function_identifier]). It is used for places with db
>     /// access such as the profiler.
>     // TODO(Gil): Add a db access to the profiler and remove this function.
> ```

Done.
___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 101 at r3](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NoqM0tA4bq_RgHQ7vzB:-Noqi2jKBPPYxvZG3Jor:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/287f26ddd20b2539a7850ec21fa1928be343d763/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L101)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

aggregate
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NopaJH94hao04RBTCSZ:-Noqk4v_ElmnTC8vJQKJ:bto4n2d) ([raw file](https://github.com/starkware-libs/cairo/blob/6948dd334c4f11b1b18454497ce23dd0f1359b72/crates/cairo-lang-test-plugin/src/lib.rs#L147)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please doc.
Why is it skipped in serde?
</blockquote></details>

It was originally a mapping to the stable location, which cannot be serded as the values are obsolete without a db. As it is only used for profiling I think it can still be skipped.


<!-- Sent from Reviewable.io -->

2024-01-23 14:53 UTC, orizi requested changes
> Reviewed 1 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4878)* status: 7 of 9 files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)

___
*[`crates/cairo-lang-runner/src/profiling_test_data/profiling` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NomHRf63iWW-sisIOHV:-Noqo0LACoTe98OPziJc:b-xy0t6l) ([raw file](https://github.com/starkware-libs/cairo/blob/6948dd334c4f11b1b18454497ce23dd0f1359b72/crates/cairo-lang-runner/src/profiling_test_data/profiling#L53)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Some locations are still `None`, it is better now, but
</blockquote></details>

as adding TODOs to improve - unblocking here.
___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 147 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NoqnklCBRR3qWaZK8Gf:-NoqnklCBRR3qWaZK8Gg:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a5b36fe0c602e865c714bce724fb6aa872edb3f3/crates/cairo-lang-test-plugin/src/lib.rs#L147)):*
> ```XML
>     /// A map between sierra statement index and the string representation of the Cairo function
>     /// that generated it. (See `containing_function_identifier`.) Used only if the tests are
>     /// run with profiling.
> ```





_Suggestion:_
```XML
    /// A map between sierra statement index and the string representation of the Cairo function
    /// that generated it. (See `containing_function_identifier`.) Used only if the tests are
    /// running with profiling.
```


<!-- Sent from Reviewable.io -->

2024-01-23 14:55 UTC, orizi reviewed
> Reviewed 2 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4878)* status: all files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware and @yuvalsw)



<!-- Sent from Reviewable.io -->

2024-01-23 14:56 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4878)* status: 8 of 9 files reviewed, 8 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-runner/src/profiling_test_data/profiling` line 53 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NomHRf63iWW-sisIOHV:-NoqoSJ2ArLuuYQaItHf:b4wiai3) ([raw file](https://github.com/starkware-libs/cairo/blob/6948dd334c4f11b1b18454497ce23dd0f1359b72/crates/cairo-lang-runner/src/profiling_test_data/profiling#L53)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

as adding TODOs to improve - unblocking here.
</blockquote></details>

(cont.) but there are still some holes, added TODOs.


<!-- Sent from Reviewable.io -->

2024-01-23 15:28 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4878)* status: 7 of 9 files reviewed, 8 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NopaJH94hao04RBTCSZ:-NoqvDdhAfxcZPIhHFuL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6948dd334c4f11b1b18454497ce23dd0f1359b72/crates/cairo-lang-test-plugin/src/lib.rs#L147)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i agree - should be skipped as long as we don't decide on a stable format.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 147 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NoqnklCBRR3qWaZK8Gf:-NoqvtWf3iflgQhbJfXS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a5b36fe0c602e865c714bce724fb6aa872edb3f3/crates/cairo-lang-test-plugin/src/lib.rs#L147)):*
> ```XML
>     /// A map between sierra statement index and the string representation of the Cairo function
>     /// that generated it. (See `containing_function_identifier`.) Used only if the tests are
>     /// run with profiling.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-01-23 15:31 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4878#-:-NoqwfVs3fjndzYHUfDm:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2024-01-23 16:18 UTC, yuvalsw requested changes
> Reviewed 5 of 9 files at r3, 3 of 3 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4878)* status: all files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-runner/Cargo.toml` line 16 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4878#-Noqq8aU66bCPS_PWUMA:-Noqq8aU66bCPS_PWUMB:b-dfgglo) ([raw file](https://github.com/starkware-libs/cairo/blob/24ac6c7cbb7660bacf7254f69dbf41b8369f6d62/crates/cairo-lang-runner/Cargo.toml#L16)):*
> ```TOML
> cairo-felt.workspace = true
> cairo-lang-casm = { path = "../cairo-lang-casm", version = "2.5.0" }
> cairo-lang-compiler = { path = "../cairo-lang-compiler", version = "2.5.0" }
> ```

These are used only in tests. Please move to dev-deps.
If I missed something and they are needed in non-test, I an not sure if compiler and sierra-gen make sense as deps here. In this case, we might need to move the profiler to a separate crate?
___
*[`crates/cairo-lang-runner/Cargo.toml` line 35 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4878#-Nor5u2x08uhlUffP1ll:-Nor5u2x08uhlUffP1lm:b-p1r1zc) ([raw file](https://github.com/starkware-libs/cairo/blob/24ac6c7cbb7660bacf7254f69dbf41b8369f6d62/crates/cairo-lang-runner/Cargo.toml#L35)):*
> ```TOML
> 
> [dev-dependencies]
> cairo-lang-filesystem = { path = "../cairo-lang-filesystem" }
> ```

where is this used?
___
*[`crates/cairo-lang-runner/Cargo.toml` line 36 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NoqqN6EBO90JNCASqbp:-NoqqN6EBO90JNCASqbq:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/24ac6c7cbb7660bacf7254f69dbf41b8369f6d62/crates/cairo-lang-runner/Cargo.toml#L36)):*
> ```TOML
> [dev-dependencies]
> cairo-lang-filesystem = { path = "../cairo-lang-filesystem" }
> cairo-lang-semantic = { path = "../cairo-lang-semantic", features = ["testing",] }
> ```





_Suggestion:_
```TOML
"testing"]
```
___
*[`crates/cairo-lang-runner/src/profiling_test_data/profiling` line 252 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4878#-Nor4h9K5r7a30tHhic0:-Nor4h9K5r7a30tHhic1:bxban3o) ([raw file](https://github.com/starkware-libs/cairo/blob/c091ff0646a9fb212f6099be1e5f86cec29d9ce0/crates/cairo-lang-runner/src/profiling_test_data/profiling#L252)):*
> ```
>         n -= 1;
>     }
> ```

Why isn't it showing the diff from the sierra-based test?
remove blank line
___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 90 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NoqtpCt6HPf9NwhUism:-NoqtpCt6HPf9NwhUisn:bn5xtge) ([raw file](https://github.com/starkware-libs/cairo/blob/24ac6c7cbb7660bacf7254f69dbf41b8369f6d62/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L90)):*
> ```XML
>     }
>     /// Builds a map between the Sierra statement index and a string representation of the Cairo
>     /// function that it was built from (see [containing_function_identifier]). It is used for
> ```

Now I am not sure this is the best phrasing, but:
1. find the best phrasing in your opinion.
2. Use it everywhere (now you use different phrasings).



_Code quote:_
```XML
it was built from
```
___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 102 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NoqvhTF66jAbv3OZRsP:-NoqvhTF66jAbv3OZRsQ:b-3dqyaj) ([raw file](https://github.com/starkware-libs/cairo/blob/24ac6c7cbb7660bacf7254f69dbf41b8369f6d62/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L102)):*
> ```XML
>             |k| *k,
>             |s1: &String, s2| s1.to_string() + &containing_function_identifier(db, Some(*s2)),
>             &"".to_string(),
> ```

There is no aggregation, so s1 will always be empty.
I ll add a .map() function to UnorderedHashMap, please use it after I merge.



_Suggestion:_
```XML
        self.locations.aggregate_by(
            |k| *k,
            |s1, s2| &containing_function_identifier(db, Some(*s2)),
            &"".to_string(),
```
___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NopaJH94hao04RBTCSZ:-Noqwi686ik0pB9llvIo:bg9opgf) ([raw file](https://github.com/starkware-libs/cairo/blob/6948dd334c4f11b1b18454497ce23dd0f1359b72/crates/cairo-lang-test-plugin/src/lib.rs#L147)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK, then please add a TODO to consider adding it to serde if not removed and when we get to a stable format.
___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 147 at r6](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NoqnklCBRR3qWaZK8Gf:-NoqwLzgAT5nDXKfmNty:b-o9tdn9) ([raw file](https://github.com/starkware-libs/cairo/blob/a5b36fe0c602e865c714bce724fb6aa872edb3f3/crates/cairo-lang-test-plugin/src/lib.rs#L147)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

"are run" is actually correct. Also just "run" is OK.
___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 146 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4878#-Noqt-mTAzuYFKzSMDG2:-Noqt-mTAzuYFKzSMDG3:b-gjr8xf) ([raw file](https://github.com/starkware-libs/cairo/blob/24ac6c7cbb7660bacf7254f69dbf41b8369f6d62/crates/cairo-lang-test-plugin/src/lib.rs#L146)):*
> ```XML
>     pub sierra_program: Program,
>     /// A map between sierra statement index and the string representation of the Cairo function
>     /// that generated it. (See `containing_function_identifier`.) Used only if the tests are
> ```

Please copy the relevant sentence to here and other places you wrote "see containing_function_identifier". This demands jumping somewhere else, a bit confusing as it has more info, and not that long.

Another option is to have a struct CairoFunctionIdentifier or something similar, with a String member (or a vector of strings), use it here and elsewhere, and have this documentation on it.



_Code quote:_
```XML
See `containing_function_identifier`.
```


<!-- Sent from Reviewable.io -->

2024-01-23 18:51 UTC, orizi approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4878)* status: all files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2024-01-23 22:25 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4878)* status: all files reviewed, 7 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-runner/Cargo.toml` line 16 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4878#-Noqq8aU66bCPS_PWUMA:-NorQ3kD1hq6wIZBwNUt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/24ac6c7cbb7660bacf7254f69dbf41b8369f6d62/crates/cairo-lang-runner/Cargo.toml#L16)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

These are used only in tests. Please move to dev-deps.
If I missed something and they are needed in non-test, I an not sure if compiler and sierra-gen make sense as deps here. In this case, we might need to move the profiler to a separate crate?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/Cargo.toml` line 35 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4878#-Nor5u2x08uhlUffP1ll:-NorQRYw8TDSP8t68V8r:bss4a2b) ([raw file](https://github.com/starkware-libs/cairo/blob/24ac6c7cbb7660bacf7254f69dbf41b8369f6d62/crates/cairo-lang-runner/Cargo.toml#L35)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

where is this used?
</blockquote></details>

Removed.
___
*[`crates/cairo-lang-runner/src/profiling_test_data/profiling` line 252 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4878#-Nor4h9K5r7a30tHhic0:-NosNMfa1VAaq2UJmbs5:b-7qpexs) ([raw file](https://github.com/starkware-libs/cairo/blob/c091ff0646a9fb212f6099be1e5f86cec29d9ce0/crates/cairo-lang-runner/src/profiling_test_data/profiling#L252)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Why isn't it showing the diff from the sierra-based test?
remove blank line
</blockquote></details>

It is showing from r3 onwards.
___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 90 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NoqtpCt6HPf9NwhUism:-NosQ-PS8q1s6Jt56pWX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/24ac6c7cbb7660bacf7254f69dbf41b8369f6d62/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L90)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Now I am not sure this is the best phrasing, but:
1. find the best phrasing in your opinion.
2. Use it everywhere (now you use different phrasings).
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 102 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NoqvhTF66jAbv3OZRsP:-NosNp9vDcuKu8c-UW4L:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/24ac6c7cbb7660bacf7254f69dbf41b8369f6d62/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L102)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

There is no aggregation, so s1 will always be empty.
I ll add a .map() function to UnorderedHashMap, please use it after I merge.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NopaJH94hao04RBTCSZ:-NosOLSaC9JDIrhSZjjf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6948dd334c4f11b1b18454497ce23dd0f1359b72/crates/cairo-lang-test-plugin/src/lib.rs#L147)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

OK, then please add a TODO to consider adding it to serde if not removed and when we get to a stable format.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 146 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4878#-Noqt-mTAzuYFKzSMDG2:-NosP9px9TKMyBNFQWLJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/24ac6c7cbb7660bacf7254f69dbf41b8369f6d62/crates/cairo-lang-test-plugin/src/lib.rs#L146)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Please copy the relevant sentence to here and other places you wrote "see containing_function_identifier". This demands jumping somewhere else, a bit confusing as it has more info, and not that long.

Another option is to have a struct CairoFunctionIdentifier or something similar, with a String member (or a vector of strings), use it here and elsewhere, and have this documentation on it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-23 22:29 UTC, orizi approved these changes
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4878)* status: all files reviewed, 7 unresolved discussions (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2024-01-23 23:41 UTC, yuvalsw submitted a review, later dismissed
> Reviewed 1 of 2 files at r9, 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4878)* status: all files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-runner/Cargo.toml` line 16 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4878#-Noqq8aU66bCPS_PWUMA:-Nosd5eKD0_rMpYITM2K:b-v1j5of) ([raw file](https://github.com/starkware-libs/cairo/blob/24ac6c7cbb7660bacf7254f69dbf41b8369f6d62/crates/cairo-lang-runner/Cargo.toml#L16)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

same for sierra-gen
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 210 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NosgSP_0dqTV6g7Gn3s:-NosgSP_0dqTV6g7Gn3t:b-b8yuzn) ([raw file](https://github.com/starkware-libs/cairo/blob/51f147406c9b603a295712a8706fda61e6071d97/crates/cairo-lang-runner/src/profiling.rs#L210)):*
> ```XML
>                             .statements_functions
>                             .get(statement_idx)
>                             .unwrap_or(&"Unknown function".to_string())
> ```

Copying from an old comment that was lost:
When there are no more such, should this panic?
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 210 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NosgZrP0NiVYEVovcFA:-NosgZrP0NiVYEVovcFB:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/51f147406c9b603a295712a8706fda61e6071d97/crates/cairo-lang-runner/src/profiling.rs#L210)):*
> ```XML
>                             .statements_functions
>                             .get(statement_idx)
>                             .unwrap_or(&"Unknown function".to_string())
> ```





_Suggestion:_
```XML
.unwrap_or(&"unknown".to_string())
```
___
*[`crates/cairo-lang-runner/src/profiling_test_data/profiling` line 309 at r8](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NosdqS76ypN1Awfbg6C:-NosdqS76ypN1Awfbg6D:b-tck4ii) ([raw file](https://github.com/starkware-libs/cairo/blob/c091ff0646a9fb212f6099be1e5f86cec29d9ce0/crates/cairo-lang-runner/src/profiling_test_data/profiling#L309)):*
> ```
> Weight by Cairo function:
>   function lib.cairo::main: 17
>   function Unknown function: 9
> ```

please change to 



_Suggestion:_
```
function unknown
```
___
*[`crates/cairo-lang-runner/src/profiling_test_data/profiling` line 237 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NosggMiEwQ1hSVjHE5U:-NosggMiEwQ1hSVjHE5V:bs23fnm) ([raw file](https://github.com/starkware-libs/cairo/blob/51f147406c9b603a295712a8706fda61e6071d97/crates/cairo-lang-runner/src/profiling_test_data/profiling#L237)):*
> ```
> //! > Test profiling info of a program with a simple loop
> 
> //! > TODO(Gil): Fill all the `Unknown functions` in the cairo functions profiling.
> ```

I think this is better near the code that write "unknown". This way you also don't need to dup it.
___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 14 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NoseK38D2PRXZxLd97Q:-NoseK38D2PRXZxLd97R:bo51ury) ([raw file](https://github.com/starkware-libs/cairo/blob/51f147406c9b603a295712a8706fda61e6071d97/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L14)):*
> ```XML
> /// Returns an identifier of the function that contains the given [StableLocation]. It is composed
> /// of the file name, and the path (modules and impls) to the function in the file.
> // TODO(Gil): Extract this function into a trait for future compatibility with the trait functions.
> ```

this is not what I meant. I meant that we can add (Cairo) traits to the path alongside modules and impls, as in the future they may have implemented functions in them.
___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 99 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NoseBkuCieI-83duow5:-NoseBkuCieI-83duow6:bfmfj3j) ([raw file](https://github.com/starkware-libs/cairo/blob/51f147406c9b603a295712a8706fda61e6071d97/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L99)):*
> ```XML
>     ) -> UnorderedHashMap<StatementIdx, String> {
>         // The keys mapping function is the identity function, so no aggregation is done.
>         self.locations.aggregate_by(
> ```

please use .map() (https://github.com/starkware-libs/cairo/pull/4896) or add a TODO if you don't want to block until Thursday.


<!-- Sent from Reviewable.io -->

2024-01-24 07:57 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4878)* status: all files reviewed, 4 unresolved discussions (waiting on @yuvalsw)

___
*[`crates/cairo-lang-runner/Cargo.toml` line 16 at r7](https://reviewable.io/reviews/starkware-libs/cairo/4878#-Noqq8aU66bCPS_PWUMA:-NouR-ro368VxzGVYFnF:bvwxb58) ([raw file](https://github.com/starkware-libs/cairo/blob/24ac6c7cbb7660bacf7254f69dbf41b8369f6d62/crates/cairo-lang-runner/Cargo.toml#L16)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

same for sierra-gen
</blockquote></details>

There is a dep on test utils, but it's not related to this pr, will remove in another.
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 210 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NosgZrP0NiVYEVovcFA:-NouSG6zBm8uljGk_LhK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/51f147406c9b603a295712a8706fda61e6071d97/crates/cairo-lang-runner/src/profiling.rs#L210)):*
> ```XML
>                             .statements_functions
>                             .get(statement_idx)
>                             .unwrap_or(&"Unknown function".to_string())
> ```

Done.
___
*[`crates/cairo-lang-runner/src/profiling.rs` line 210 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NosgSP_0dqTV6g7Gn3s:-NouSHNJ6nH8ixMPMYxn:b-yaolhw) ([raw file](https://github.com/starkware-libs/cairo/blob/51f147406c9b603a295712a8706fda61e6071d97/crates/cairo-lang-runner/src/profiling.rs#L210)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Copying from an old comment that was lost:
When there are no more such, should this panic?
</blockquote></details>

Not sure, we can still provide good profiling without it.
___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 14 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NoseK38D2PRXZxLd97Q:-NouTDMp4K76blf-4H6U:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/51f147406c9b603a295712a8706fda61e6071d97/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L14)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

this is not what I meant. I meant that we can add (Cairo) traits to the path alongside modules and impls, as in the future they may have implemented functions in them.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 99 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NoseBkuCieI-83duow5:-NouTNay6BaQKojyt3SY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/51f147406c9b603a295712a8706fda61e6071d97/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L99)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please use .map() (https://github.com/starkware-libs/cairo/pull/4896) or add a TODO if you don't want to block until Thursday.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-24 09:08 UTC, orizi approved these changes
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4878)* status: all files reviewed, 4 unresolved discussions (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2024-01-24 10:10 UTC, merged

2024-01-25 06:07 UTC, yuvalsw reviewed
> Reviewed 2 of 3 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4878)* status: all files reviewed, 3 unresolved discussions

___
*[`crates/cairo-lang-runner/src/profiling.rs` line 210 at r10](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NosgSP_0dqTV6g7Gn3s:-NozDH0A7Y8QBTSPRNV2:bpocs60) ([raw file](https://github.com/starkware-libs/cairo/blob/51f147406c9b603a295712a8706fda61e6071d97/crates/cairo-lang-runner/src/profiling.rs#L210)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Not sure, we can still provide good profiling without it.
</blockquote></details>

I refer to it as an external tool. Should someone get unknown or panic?
___
*[`crates/cairo-lang-sierra-generator/src/statements_locations.rs` line 24 at r12](https://reviewable.io/reviews/starkware-libs/cairo/4878#-NozDiKD3_vjBDkS7vMp:-NozDiKD3_vjBDkS7vMq:bmtctc8) ([raw file](https://github.com/starkware-libs/cairo/blob/48783b10bb0a3511edc71278c842354c0647b10e/crates/cairo-lang-sierra-generator/src/statements_locations.rs#L24)):*
> ```XML
>             let mut syntax_node = location.syntax_node(db.upcast());
>             loop {
>                 // TODO(Gil): Extract this function into a trait of syntax kind to support future
> ```

Still not what I meant.


<!-- Sent from Reviewable.io -->