Relaxed solver equality to not fail on branch align mismatches.
starkware-libs/cairo pull request #4893
Opened 2024-01-23 14:37 UTC by orizi

Required since the linear solver pushes excess to earliest branch align.

2024-01-28 12:28 UTC, liorgold2 requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4893)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-gas/src/gas_info.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4893#-NpF0gCN1OawytS-S8bq:-NpF0gCN1OawytS-S8br:by06d8b) ([raw file](https://github.com/starkware-libs/cairo/blob/1539c09cd0bc569efab9102bc7142f332ba7b78d/crates/cairo-lang-sierra-gas/src/gas_info.rs#L65)):*
> ```XML
>     /// We allow branch align values to be different, as they do not affect generated code directly.
>     pub fn assert_eq_variables(&self, other: &GasInfo, program: &Program) {
>         let branch_align_id = program
> ```

Add type for readability (e.g., I guess it's Option, right?)
___
*[`crates/cairo-lang-sierra-gas/src/gas_info.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4893#-NpF18N79_i6Ig2yX3it:-NpF18N79_i6Ig2yX3iu:btqoz3s) ([raw file](https://github.com/starkware-libs/cairo/blob/1539c09cd0bc569efab9102bc7142f332ba7b78d/crates/cairo-lang-sierra-gas/src/gas_info.rs#L78)):*
> ```XML
>                     (program.get_statement(&idx), branch_align_id),
>                     (Some(Statement::Invocation(x)), Some(branch_align_id))
>                     if &x.libfunc_id == branch_align_id)
> ```

This is too confusing. IIUC you use the same variable name (`branch_align_id`) for two things in the same statement. It took me a while to understand how `&x.libfunc_id == branch_align_id` works type-wise.

Maybe:
```
matches!(program.get_statement(&idx), Some(Statement::Invocation(x)) if Some(x) == branch_align_id)
```



_Code quote:_
```XML
                && !matches!(
                    (program.get_statement(&idx), branch_align_id),
                    (Some(Statement::Invocation(x)), Some(branch_align_id))
                    if &x.libfunc_id == branch_align_id)
```


<!-- Sent from Reviewable.io -->

2024-01-28 12:28 UTC, liorgold2 reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4893)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-01-28 12:49 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4893)* status: all files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra-gas/src/gas_info.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4893#-NpF0gCN1OawytS-S8bq:-NpF4Cg94TEAcdc8lUsY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1539c09cd0bc569efab9102bc7142f332ba7b78d/crates/cairo-lang-sierra-gas/src/gas_info.rs#L65)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add type for readability (e.g., I guess it's Option, right?)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-gas/src/gas_info.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4893#-NpF18N79_i6Ig2yX3it:-NpF4WZG-NoKkDZC_TMQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1539c09cd0bc569efab9102bc7142f332ba7b78d/crates/cairo-lang-sierra-gas/src/gas_info.rs#L78)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This is too confusing. IIUC you use the same variable name (`branch_align_id`) for two things in the same statement. It took me a while to understand how `&x.libfunc_id == branch_align_id` works type-wise.

Maybe:
```
matches!(program.get_statement(&idx), Some(Statement::Invocation(x)) if Some(x) == branch_align_id)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-29 13:35 UTC, liorgold2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4893#-:-NpKQWnf9vTOeeqiyrzv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-01-29 14:17 UTC, merged