VSCode: Do not spawn LS process manually and use VSC idioms instead
starkware-libs/cairo pull request #4973
Opened 2024-02-01 11:58 UTC by mkaput

This change removes the logic which passes CairoLS stdout to extension's
logs. While this seems like a drawback, this logic was actually pretty
unidiomatic and required early branching in LS binary searching code.
CairoLS logs were printed by VSCode anyway in separate log channel.
This code will be cleaned up further in subsequent commits.

---

**Stack**:
- #5015
- #5014
- #5013
- #5012
- #5011
- #4976
- #4975
- #4974
- #4973 ⬅
- #4959
- #4935
- #4934

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/4973)

2024-02-07 17:31 UTC, Arcticae requested changes

2024-02-07 17:31 UTC, Arcticae commented on vscode-cairo/src/cairols.ts
> +  const isScarbEnabled = ctx.config.get<boolean>("enableScarb", false);
the defaults shouldn't be probably resolved here

2024-02-07 17:31 UTC, Arcticae commented on vscode-cairo/src/cairols.ts
> +    ctx.log.warn("note: set `cairo1.enableScarb` to `true` to enable it");
are 2 messages a little excessive?

2024-02-07 17:31 UTC, Arcticae commented on vscode-cairo/src/cairols.ts
> +    if (!command) {
let's flip the conditional here to say `if (command)` instead

2024-02-07 20:31 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4973)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @Arcticae and @orizi)

___
*[`vscode-cairo/src/cairols.ts` line 307 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4973#gh-1481839488:-Nq4EN5b6-FtB2MNRTLu:bm5kadb) ([raw file](https://github.com/starkware-libs/cairo/blob/4fdeba1fbd4548a99bf843b3cbd74d2f4af0b907/vscode-cairo/src/cairols.ts#L307)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

the defaults shouldn't be probably resolved here
</blockquote></details>

According to the docs:

```
@param defaultValue A value should be returned when no value could be found, is \`undefined\`.
```

I understand this as the value to use then the property is `undefined`, i.e. an alias for `??` operator; to make TS happy.

Proper default values are kept here: https://github.com/starkware-libs/cairo/blob/2789b60a15223b465841d88888d23c9c3e27946d/vscode-cairo/package.json#L59
___
*[`vscode-cairo/src/cairols.ts` line 313 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4973#gh-1481840303:-Nq4FUv22Piv2XGklX8_:b-jy8c90) ([raw file](https://github.com/starkware-libs/cairo/blob/4fdeba1fbd4548a99bf843b3cbd74d2f4af0b907/vscode-cairo/src/cairols.ts#L313)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

are 2 messages a little excessive?
</blockquote></details>

How would you see this to appear for the end user? I'm using Scarb's output conventions here because I like it, but I'm open for discussion.
___
*[`vscode-cairo/src/cairols.ts` line 332 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4973#gh-1481841972:-Nq4GF145dXOKjnrrr8P:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4fdeba1fbd4548a99bf843b3cbd74d2f4af0b907/vscode-cairo/src/cairols.ts#L332)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

let's flip the conditional here to say `if (command)` instead
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-08 10:40 UTC, mkaput commented
Closing pull request: commit has gone away

2024-02-08 10:43 UTC, Arcticae reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4973)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[`vscode-cairo/src/cairols.ts` line 313 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4973#gh-1481840303:-Nq7ICM7BHZc97sOBGzs:b5oia9) ([raw file](https://github.com/starkware-libs/cairo/blob/4fdeba1fbd4548a99bf843b3cbd74d2f4af0b907/vscode-cairo/src/cairols.ts#L313)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

How would you see this to appear for the end user? I'm using Scarb's output conventions here because I like it, but I'm open for discussion.
</blockquote></details>

This will produce 2 msgs and i wonder if fitting it into just one wouldn't be less confusing


<!-- Sent from Reviewable.io -->

2024-02-08 10:54 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4973)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae and @orizi)

___
*[`vscode-cairo/src/cairols.ts` line 313 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4973#gh-1481840303:-Nq7Lgam2-3YJEdRo8XT:b-m0pg26) ([raw file](https://github.com/starkware-libs/cairo/blob/4fdeba1fbd4548a99bf843b3cbd74d2f4af0b907/vscode-cairo/src/cairols.ts#L313)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

This will produce 2 msgs and i wonder if fitting it into just one wouldn't be less confusing
</blockquote></details>

discussed offline. we're leaving this as-is


<!-- Sent from Reviewable.io -->

2024-02-12 09:55 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4973#-:-NqRjXS30ZSr6OgP-k3w:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2024-02-12 10:00 UTC, merged