feat: add num::traits::ops::OverflowingAdd trait
starkware-libs/cairo pull request #4988
Opened 2024-02-04 11:45 UTC by enitrat

Adds a trait for overflowing add operations.

This is particularly useful when writing generic implementations that require wrapping or overflowing operations.
Once discussed and approved, I will also work on OverflowingSub, OverflowingMul traits, and later on on Wrapping traits.

2024-02-13 13:00 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4988#-:-NqXYZQM3hBUoVVNCdG-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)

___
*[`corelib/src/num/traits/ops/overflowing.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4988#-NqXXpy41RZ3M8cwwkqF:-NqXXpy41RZ3M8cwwkqG:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/79b0c592c1b498527008adb3e69511533a4d848a/corelib/src/num/traits/ops/overflowing.cairo#L3)):*
> ```Cairo
> /// Performs addition with a flag for overflow.
> pub trait OverflowingAdd<T> {
>     /// Returns a tuple of the sum along with a boolean indicating whether an arithmetic overflow would occur.
> ```





_Suggestion:_
```Cairo
    /// Returns a tuple of the sum along with a boolean indicating whether an arithmetic overflow
    /// would occur.
```


<!-- Sent from Reviewable.io -->

2024-02-13 13:01 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4988)* status: all files reviewed, 2 unresolved discussions (waiting on @enitrat)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/4988#-NqXYaPbBKwdHlyRvxHW:-NqXYaPbBKwdHlyRvxHX:b-uuj1x0) (no related file):*
@gilbens-starkware for 2nd eye.

___


<!-- Sent from Reviewable.io -->

2024-02-14 09:41 UTC, gilbens-starkware reviewed
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4988)* status: all files reviewed, 3 unresolved discussions (waiting on @enitrat)

___
*[`corelib/src/integer.cairo` line 2750 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4988#-NqaykNz5lCZ9OQ5ucZ6:-NqaykNz5lCZ9OQ5ucZ7:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/79b0c592c1b498527008adb3e69511533a4d848a/corelib/src/integer.cairo#L2750)):*
> ```Cairo
> // OverflowingAdd implementations
> 
> impl U8OverflowingAdd of core::num::traits::OverflowingAdd<u8> {
> ```





_Suggestion:_
```Cairo
// OverflowingAdd implementations
impl U8OverflowingAdd of core::num::traits::OverflowingAdd<u8> {
```


<!-- Sent from Reviewable.io -->

2024-02-16 11:20 UTC, enitrat reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4988)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/num/traits/ops/overflowing.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/4988#-NqXXpy41RZ3M8cwwkqF:-NqldQbnAkgerXml62LO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/79b0c592c1b498527008adb3e69511533a4d848a/corelib/src/num/traits/ops/overflowing.cairo#L3)):*
> ```Cairo
> /// Performs addition with a flag for overflow.
> pub trait OverflowingAdd<T> {
>     /// Returns a tuple of the sum along with a boolean indicating whether an arithmetic overflow would occur.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-02-16 13:34 UTC, orizi reviewed
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4988)* status: all files reviewed, 1 unresolved discussion (waiting on @enitrat)



<!-- Sent from Reviewable.io -->

2024-02-19 09:35 UTC, orizi approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4988)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @enitrat)



<!-- Sent from Reviewable.io -->

2024-02-19 09:39 UTC, gilbens-starkware approved these changes
> Reviewed 2 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/4988)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @enitrat)



<!-- Sent from Reviewable.io -->

2024-02-19 09:44 UTC, merged