LS: Move LS-specific dependencies out of workspace Cargo.toml
starkware-libs/cairo pull request #5059
Opened 2024-02-13 12:35 UTC by mkaput

The language server is going to be maintained by a separate team from
now on, so it makes sense to give this new team a freedom to manage
their specific deps without influencing other crates. The more shared
deps, like `anyhow` or `serde` have not been moved, though they may be
in the future.

2024-02-13 15:19 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5059)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-language-server/Cargo.toml` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5059#-NqXUNWJ6iudK8eSvAQ5:-NqY2Djf7qa5T4d_g0b6:b-z3jp6y) ([raw file](https://github.com/starkware-libs/cairo/blob/7f7934702d3208f6cc3d144d6025ec241fa24034/crates/cairo-lang-language-server/Cargo.toml#L29)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why not in the workspace?
</blockquote></details>

no other crate in this repository depends on it and I doubt any will need to in any future


<!-- Sent from Reviewable.io -->

2024-02-13 15:59 UTC, orizi requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5059)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-language-server/Cargo.toml` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5059#-NqXUNWJ6iudK8eSvAQ5:-NqYBDCKEbj5cyoGAGJS:b1dg9cg) ([raw file](https://github.com/starkware-libs/cairo/blob/7f7934702d3208f6cc3d144d6025ec241fa24034/crates/cairo-lang-language-server/Cargo.toml#L29)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

But I can put it back if you feel it'd be worth it
</blockquote></details>

Still rather have versions there for everything that has any chance of reuse.


<!-- Sent from Reviewable.io -->

2024-02-15 15:18 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5059)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-language-server/Cargo.toml` line 29 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5059#-NqXUNWJ6iudK8eSvAQ5:-NqhLH570rV8ItdG_KNG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7f7934702d3208f6cc3d144d6025ec241fa24034/crates/cairo-lang-language-server/Cargo.toml#L29)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Still rather have versions there for everything that has any chance of reuse.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-15 16:36 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5059#-:-NqhbzvFEsCdKUV8s_qk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2024-02-15 20:30 UTC, merged