feat(lsp): add code action for unused variable
starkware-libs/cairo pull request #5151
Opened 2024-02-27 15:31 UTC by LucasLvy

When an unused variable diagnostic is generated it's possible to use a code action to prefix it with an `_`

2024-02-28 07:41 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5151)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @LucasLvy and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 858 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5151#-NrieDSXEjlsgkdx6rCe:-NrieDSXEjlsgkdx6rCf:bk3qzq3) ([raw file](https://github.com/starkware-libs/cairo/blob/6ca91593321169726bad74cddefe21328a995128/crates/cairo-lang-language-server/src/lib.rs#L858)):*
> ```XML
>             for diagnostic in params.context.diagnostics.iter() {
>                 let action = match diagnostic.message.as_str() {
>                     "Unused variable. Consider ignoring by prefixing with `_`." => unused_variable(
> ```

every code action that is diagnostic based should probably be extracted to some constant (to prevent changes of the diagnostic disabling the action.



_Code quote:_
```XML
                    "Unused variable. Consider ignoring by prefixing with `_`." 
```


<!-- Sent from Reviewable.io -->

2024-02-29 08:00 UTC, mkaput approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5151)* status: all files reviewed, 2 unresolved discussions (waiting on @LucasLvy and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 858 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5151#-NrieDSXEjlsgkdx6rCe:-Nrnra1e8mQ_RoG5SPvn:b-751gl6) ([raw file](https://github.com/starkware-libs/cairo/blob/6ca91593321169726bad74cddefe21328a995128/crates/cairo-lang-language-server/src/lib.rs#L858)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

inserting error codes into the strings? in general sounds good - should be added as a preliminary PR to this one in any case
</blockquote></details>

yep, like this: 
![image.png](https://files.reviewableusercontent.io/images/reviewable/3450050/ZsO2e3r_0PpnjbyeNixXuT1L/image.png)

But I slightly disagree that we should pause this PR waiting for these codes to happen because I'm afraid this code will rot.


<!-- Sent from Reviewable.io -->

2024-02-29 14:16 UTC, LucasLvy commented
I’m at eth Denver rn so won’t be very active here but I’ll try to add the error code soon, I’m thinking about changing a bit the ˋget_diagnostics` function and fill the field ˋcodeˋ of the lsp diagnostic object

2024-03-01 07:07 UTC, mkaput commented
@LucasLvy I've talked to @orizi offline about these error codes, and we think it'd be the most optimal if I add a support for error codes in the compiler proper. I'm jumping into this right now.

This way, the LS would still stay with doing pattern matching on a prefix, but instead of matching the entire message, it will just match the error code.

2024-03-02 20:48 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5151)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @LucasLvy and @mkaput)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5151#-Ns-utg0AY-SsxirtxD1:-Ns-utg0AY-SsxirtxD2:brh6oye) ([raw file](https://github.com/starkware-libs/cairo/blob/82f2306cb042ee73a12974d0fbaae19287744fea/crates/cairo-lang-diagnostics/src/diagnostics.rs#L48)):*
> ```XML
>     // TODO(spapini): Add a way to inspect the diagnostic programmatically, e.g, downcast.
> }
> impl_downcast!(DiagnosticEntry assoc DbType where DbType: Upcast<dyn FilesGroup> + ?Sized);
> ```

why is all this required?
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1537 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5151#-Ns-v4zy4tpGRvD5Ek2B:-Ns-v4zy4tpGRvD5Ek2C:b-aflr8e) ([raw file](https://github.com/starkware-libs/cairo/blob/82f2306cb042ee73a12974d0fbaae19287744fea/crates/cairo-lang-language-server/src/lib.rs#L1537)):*
> ```XML
>             }
>         }
>         let diagnostic: &&T = diagnostic.borrow();
> ```

what is this?


<!-- Sent from Reviewable.io -->

2024-03-02 20:49 UTC, LucasLvy commented
This is still wip don’t bother reviewing it yet

2024-03-05 14:26 UTC, orizi reviewed
doesn't work that way - please either close the PR or stop updating - as i don't want it in my attention list.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5151#-:-NsE-IwZ-8vwQKPOqS_z:b-tyc3my)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @LucasLvy and @mkaput)



<!-- Sent from Reviewable.io -->

2024-03-05 14:34 UTC, closed without merging