LS: Partially revert #5214, remove error code book
starkware-libs/cairo pull request #5224
Opened 2024-03-08 11:29 UTC by mkaput

2024-03-08 12:32 UTC, LucasLvy requested changes

2024-03-08 12:32 UTC, LucasLvy commented on crates/cairo-lang-language-server/src/lib.rs
> +    if code == error_code!(E0001).as_str() {
I'd rather `match` here but not very important

2024-03-08 12:32 UTC, LucasLvy commented on crates/cairo-lang-language-server/src/lib.rs
> +        debug!("diagnostic code is missing");
```suggestion
        error!("diagnostic code is missing");
```

2024-03-08 12:32 UTC, LucasLvy commented on crates/cairo-lang-language-server/src/lib.rs
> +        debug!("diagnostic code is not a string: `{code:?}`");
```suggestion
        error!("diagnostic code is not a string: `{code:?}`");
```

2024-03-08 12:32 UTC, LucasLvy commented on crates/cairo-lang-language-server/src/lib.rs
> +        debug!("diagnostic code is not a string: `{code:?}`");
I'd consider this as an error because we are the one sending the error codes with the diagnostic.

2024-03-08 12:32 UTC, LucasLvy commented on crates/cairo-lang-language-server/src/lib.rs
> +        debug!("diagnostic code is missing");
I'd consider this as an error because we are the one sending the error codes with the diagnostic.

2024-03-08 13:56 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5224)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @LucasLvy and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 963 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5224#gh-1517657622:-NsTLL88--XB0QKGKFwt:b4bcmyz) ([raw file](https://github.com/starkware-libs/cairo/blob/2e19a664430a03b24d47797c0a0edb10ea99bb0a/crates/cairo-lang-language-server/src/lib.rs#L963)):*
<details><summary><i>Previously, LucasLvy (Lucas @ StarkWare) wrote…</i></summary><blockquote>

I'd consider this as an error because we are the one sending the error codes with the diagnostic.
</blockquote></details>

This could be an error if all diagnostics had an error code, which is not true.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 968 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5224#gh-1517657804:-NsTL-Pq6L6KSht2qfgl:b5rdt0s) ([raw file](https://github.com/starkware-libs/cairo/blob/2e19a664430a03b24d47797c0a0edb10ea99bb0a/crates/cairo-lang-language-server/src/lib.rs#L968)):*
<details><summary><i>Previously, LucasLvy (Lucas @ StarkWare) wrote…</i></summary><blockquote>

I'd consider this as an error because we are the one sending the error codes with the diagnostic.
</blockquote></details>

I don't know the exact API semantics. Are you sure this endpoint won't be triggered for diagnostics coming from other language servers, for example? If you don't know I can research this deeper.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 974 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5224#gh-1517657393:-NsTKWt41rPTYfjg1Aqa:bzasfmm) ([raw file](https://github.com/starkware-libs/cairo/blob/2e19a664430a03b24d47797c0a0edb10ea99bb0a/crates/cairo-lang-language-server/src/lib.rs#L974)):*
<details><summary><i>Previously, LucasLvy (Lucas @ StarkWare) wrote…</i></summary><blockquote>

I'd rather `match` here but not very important
</blockquote></details>

I wish I could do that, but unfortunately I have no idea how to express `error_code!(...).as_str()` as a Rust pattern. I can only do the following here, which is uglier imho:

```rust
match code {
    c if c == error_code!(E0001).as_str()
}
```


alternatively I might ditch `error_code!` entirely from here, it's actually not a big benefit :thinking: 

```rust
match code {
     "E0001" => ...
}
```

wdyt?


<!-- Sent from Reviewable.io -->

2024-03-08 14:49 UTC, LucasLvy requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5224)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 963 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5224#gh-1517657622:-NsTXYY_0nlK04lWIEsL:b72hcy9) ([raw file](https://github.com/starkware-libs/cairo/blob/2e19a664430a03b24d47797c0a0edb10ea99bb0a/crates/cairo-lang-language-server/src/lib.rs#L963)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

This could be an error if all diagnostics had an error code, which is not true.
</blockquote></details>

I don't know i still think that it should be logged as an error as we are probably the only who know that we want to keep 1 error code for some time
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 968 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5224#gh-1517657804:-NsTXDs0440TZ7AZjSFI:b-1cjtw3) ([raw file](https://github.com/starkware-libs/cairo/blob/2e19a664430a03b24d47797c0a0edb10ea99bb0a/crates/cairo-lang-language-server/src/lib.rs#L968)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I don't know the exact API semantics. Are you sure this endpoint won't be triggered for diagnostics coming from other language servers, for example? If you don't know I can research this deeper.
</blockquote></details>

I guess it could, but it would still be an error imo, we only treat diagnostic that comply with our "spec". WDYT ?
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 974 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5224#gh-1517657393:-NsTX5h673-tJqx-V6ex:b-sla1vl) ([raw file](https://github.com/starkware-libs/cairo/blob/2e19a664430a03b24d47797c0a0edb10ea99bb0a/crates/cairo-lang-language-server/src/lib.rs#L974)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I wish I could do that, but unfortunately I have no idea how to express `error_code!(...).as_str()` as a Rust pattern. I can only do the following here, which is uglier imho:

```rust
match code {
    c if c == error_code!(E0001).as_str()
}
```


alternatively I might ditch `error_code!` entirely from here, it's actually not a big benefit :thinking: 

```rust
match code {
     "E0001" => ...
}
```

wdyt?
</blockquote></details>

yes matching on the string seems good not sure what error code is bringing here.


<!-- Sent from Reviewable.io -->

2024-03-08 15:51 UTC, orizi requested changes
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5224)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @LucasLvy and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 956 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5224#-NsTkX-r241PSgdBJSEe:-NsTkX-r241PSgdBJSEf:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/2e19a664430a03b24d47797c0a0edb10ea99bb0a/crates/cairo-lang-language-server/src/lib.rs#L956)):*
> ```XML
> }
> 
> fn get_code_actions_for_diagnostic(
> ```

doc
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 974 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5224#gh-1517657393:-NsTk_o30Z11lXKTSxPL:b-oeyit) ([raw file](https://github.com/starkware-libs/cairo/blob/2e19a664430a03b24d47797c0a0edb10ea99bb0a/crates/cairo-lang-language-server/src/lib.rs#L974)):*
<details><summary><i>Previously, LucasLvy (Lucas @ StarkWare) wrote…</i></summary><blockquote>

yes matching on the string seems good not sure what error code is bringing here.
</blockquote></details>

matching does not work yet not directly on literals - it works only on nightly with a feature, and also requires a const block:
`const { some_const_calc() }`


<!-- Sent from Reviewable.io -->

2024-03-08 16:56 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5224)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @LucasLvy and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 956 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5224#-NsTkX-r241PSgdBJSEe:-NsTyn7v2ab5qApvE8rX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2e19a664430a03b24d47797c0a0edb10ea99bb0a/crates/cairo-lang-language-server/src/lib.rs#L956)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 974 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5224#gh-1517657393:-NsTz2Tt07o2fgDoAbT_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2e19a664430a03b24d47797c0a0edb10ea99bb0a/crates/cairo-lang-language-server/src/lib.rs#L974)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

matching does not work yet not directly on literals - it works only on nightly with a feature, and also requires a const block:
`const { some_const_calc() }`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-08 17:08 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5224)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @LucasLvy and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 963 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5224#gh-1517657622:-NsU1QXxEvoEAdkrlUap:bjbfau2) ([raw file](https://github.com/starkware-libs/cairo/blob/2e19a664430a03b24d47797c0a0edb10ea99bb0a/crates/cairo-lang-language-server/src/lib.rs#L963)):*
<details><summary><i>Previously, LucasLvy (Lucas @ StarkWare) wrote…</i></summary><blockquote>

I don't know i still think that it should be logged as an error as we are probably the only who know that we want to keep 1 error code for some time
</blockquote></details>

Same as in the other thread: without first ensuring this is our diagnostic I don't think we should `error!` here.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 968 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5224#gh-1517657804:-NsTzi3N0SknVlXOIlQo:bgdv32t) ([raw file](https://github.com/starkware-libs/cairo/blob/2e19a664430a03b24d47797c0a0edb10ea99bb0a/crates/cairo-lang-language-server/src/lib.rs#L968)):*
<details><summary><i>Previously, LucasLvy (Lucas @ StarkWare) wrote…</i></summary><blockquote>

I guess it could, but it would still be an error imo, we only treat diagnostic that comply with our "spec". WDYT ?
</blockquote></details>

As far as I understand comments, to be fully sure this is our diagnostic we would have to set the `source` field. And the protocol is not saying that we [only get ours diagnostics as input](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeAction). So I believe doing `error!` will be very noisy in LS logs (`debug!` is not printed in default mode)


<!-- Sent from Reviewable.io -->

2024-03-11 10:44 UTC, orizi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5224)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @LucasLvy)



<!-- Sent from Reviewable.io -->

2024-03-12 09:21 UTC, LucasLvy requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5224)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 963 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5224#gh-1517657622:-NslxqNN47Qlh6Fab7vb:b4g37cn) ([raw file](https://github.com/starkware-libs/cairo/blob/2e19a664430a03b24d47797c0a0edb10ea99bb0a/crates/cairo-lang-language-server/src/lib.rs#L963)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Same as in the other thread: without first ensuring this is our diagnostic I don't think we should `error!` here.
</blockquote></details>

Don't you think it's an error if we receive other lsps diagnostics ?


<!-- Sent from Reviewable.io -->

2024-03-12 09:31 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5224)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @LucasLvy and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 963 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5224#gh-1517657622:-NslzeyaCk0z3NCeM-5b:b7bp0wa) ([raw file](https://github.com/starkware-libs/cairo/blob/2e19a664430a03b24d47797c0a0edb10ea99bb0a/crates/cairo-lang-language-server/src/lib.rs#L963)):*
<details><summary><i>Previously, LucasLvy (Lucas @ StarkWare) wrote…</i></summary><blockquote>

Don't you think it's an error if we receive other lsps diagnostics ?
</blockquote></details>

I do not think it's an error. The protocol does not forbid this to happen and there is a sensible use-case for this behaviour (which we are not interested in); hence I'm ignoring this situation here.


<!-- Sent from Reviewable.io -->

2024-03-12 09:34 UTC, orizi approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5224)* status: all files reviewed, 3 unresolved discussions (waiting on @LucasLvy)



<!-- Sent from Reviewable.io -->

2024-03-12 10:05 UTC, LucasLvy approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5224#-:-Nsm6p9l6O_A0vQUurJs:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2024-03-12 10:13 UTC, merged