feat(lsp): show rust doc when hovering over things
starkware-libs/cairo pull request #5225
Opened 2024-03-08 14:37 UTC by LucasLvy

This is what would be displayed for `check_ecdsa_signature` if the doc was properly formatted for rust
```cairo
pub fn check_ecdsa_signature(message_hash: felt252, public_key: felt252, signature_r:felt252, signature_s: felt252) -> bool
```

 ---

 Checks if (signature_r, signature_s) is a valid ECDSA signature for the given public_key on the given message.

 Note: the verification algorithm implemented by this function slightly deviates from the standard ECDSA.                                                                            
 
 While this does not allow to create valid signatures if one does not possess the private key,
 it means that the signature algorithm used should be modified accordingly.
 Namely, it should check that r, s < stark_curve::ORDER.

 Arguments:

 - message_hash - the signed message.
 - public_key - the public key corresponding to the key with which the message was signed.
 - signature_r - the r component of the ECDSA signature.
 - signature_s - the s component of the ECDSA signature.

 Returns:
 true if the signature is valid and false otherwise.

2024-03-08 15:21 UTC, LucasLvy commented
what's displayed for `then_some`

![Screenshot 2024-03-08 at 16 19 42](https://github.com/starkware-libs/cairo/assets/70894690/432fd153-b844-479b-a1e9-e7d7706cfb25)

And for `check_ecdsa_signature` (if it started with `///` instead of `//`)
![Screenshot 2024-03-08 at 16 21 01](https://github.com/starkware-libs/cairo/assets/70894690/3f94d2b6-7106-4230-a3d3-c735812a8354)

2024-03-08 15:54 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @LucasLvy and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1686 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5225#-NsTl7XA1CdiP91ofsR0:-NsTl7XA1CdiP91ofsR1:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/b5336a98f651e238a6750785ab42f5e54afae6dc/crates/cairo-lang-language-server/src/lib.rs#L1686)):*
> ```XML
>     }
> }
> ```

doc


<!-- Sent from Reviewable.io -->

2024-03-08 16:09 UTC, LucasLvy reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1686 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5225#-NsTl7XA1CdiP91ofsR0:-NsToutU8-Vg31lgE0mb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b5336a98f651e238a6750785ab42f5e54afae6dc/crates/cairo-lang-language-server/src/lib.rs#L1686)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-08 16:28 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @LucasLvy and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1700 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5225#-NsTt2Qr-YpqQ-OQBvH6:-NsTt2QsEVRH_NJOxaHD:bk38tnu) ([raw file](https://github.com/starkware-libs/cairo/blob/934cd26501ea98b5e96a63f88d97a584d88c7da2/crates/cairo-lang-language-server/src/lib.rs#L1700)):*
> ```XML
> pub fn get_definition_location(
>     db: &RootDatabase,
>     uri: Url,
> ```

Can't you accept file id instead of uri? You seem to extract it twice.


<!-- Sent from Reviewable.io -->

2024-03-08 16:42 UTC, LucasLvy reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1700 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5225#-NsTt2Qr-YpqQ-OQBvH6:-NsTwPFfCnscB439Myeg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/934cd26501ea98b5e96a63f88d97a584d88c7da2/crates/cairo-lang-language-server/src/lib.rs#L1700)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Can't you accept file id instead of uri? You seem to extract it twice.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-08 16:46 UTC, LucasLvy reviewed
Also i'd love to get read of the other hints because i don't think they provide any useful information but maybe i'm missing something ? I think this approach could be enough for everything, even for imports etc

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225#-:-NsTx5hg95kg5IuXnebY:b-qwneys)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)



<!-- Sent from Reviewable.io -->

2024-03-08 17:16 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @LucasLvy and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1483 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5225#-NsU3-rj5ukSzAbsLv-i:-NsU3-rj5ukSzAbsLv-j:bgzyl2s) ([raw file](https://github.com/starkware-libs/cairo/blob/fc5527c5ecdbfab3436714d478c5bcaebcc83d62/crates/cairo-lang-language-server/src/lib.rs#L1483)):*
> ```XML
>             // add new line to have a proper formatting.
>             doc += "\n";
>         }
> ```

I think the logic for obtaining documentation should be a query in the semantic model in the compiler rather then polluting LS logic



_Code quote:_
```XML
    // Get its parent to get the trivia.
    if let Some(parent_node) = node.parent() {
        let mut is_cairo_string = false;
        // Get the trivia and remove the node text.
        let lines = if let Some(split) = parent_node.get_text(db.upcast()).rsplit_once('\n') {
            split.0.to_string()
        } else {
            "".to_string()
        };
        let mut doc = "".to_string();
        for line in lines.lines() {
            // Skip everything else than doc
            if !line.trim_start().starts_with("///") {
                continue;
            }
            // Remove the leading whitespaces and `///`
            let line = line.trim().trim_start_matches("///").trim_start().to_string();
            // If we reach ``` it means that we either begin a code section or end a code section.
            if line.starts_with("```") {
                // If is_cairo_string is true it means that we end the code block so append the code
                // in a cairo formatted string.
                hints.push(if is_cairo_string {
                    MarkedString::from_language_code("cairo".to_owned(), doc)
                } else {
                    // else append a regular string.
                    MarkedString::from_markdown(doc)
                });
                // Switch the variable to properly format the following block.
                is_cairo_string = !is_cairo_string;
                // reset the string to start the next block.
                doc = "".to_string();
                continue;
            }
            // Append the current block string.
            doc += line.as_str();
            // add new line to have a proper formatting.
            doc += "\n";
        }
```


<!-- Sent from Reviewable.io -->

2024-03-08 18:58 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @LucasLvy and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 869 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5225#-NsUQBrE5i2RFo26nsUo:-NsUQBrE5i2RFo26nsUp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fc5527c5ecdbfab3436714d478c5bcaebcc83d62/crates/cairo-lang-language-server/src/lib.rs#L869)):*
> ```XML
>             let file_uri = params.text_document_position_params.text_document.uri;
>             let file_id = file(db, file_uri.clone());
>             let position = params.text_document_position_params.position;
> ```





_Suggestion:_
```XML
            let file_id = file(db, file_uri);
            let position = params.text_document_position_params.position;
```


<!-- Sent from Reviewable.io -->

2024-03-12 07:49 UTC, mkaput requested changes
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @LucasLvy and @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 107 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5225#-NslbplEA0yhGuv1YZyz:-Nslb5tR4zz7Ui9-9Z0D:b-7p34oq) ([raw file](https://github.com/starkware-libs/cairo/blob/894a38c10ad33ef2f88adfcac42d3a728ef59869/crates/cairo-lang-defs/src/db.rs#L107)):*
> ```XML
>     fn documentation(&self, item_id: LookupItemId) -> String;
>     /// Gets the the definition + documentation above.
>     fn documentation_with_definition(&self, item_id: LookupItemId) -> (String, String);
> ```

Querying `documentation` and `definition` as separate queries would be same thing in terms of performance, and that setup would allow getting `definition` without even touching documentation logic. Could you drop the documentation part from this query?
___
*[`crates/cairo-lang-defs/src/db.rs` line 107 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5225#-NslcV6V2FIdWS_KGxf3:-NslcV6V2FIdWS_KGxf4:boo35zy) ([raw file](https://github.com/starkware-libs/cairo/blob/894a38c10ad33ef2f88adfcac42d3a728ef59869/crates/cairo-lang-defs/src/db.rs#L107)):*
> ```XML
>     fn documentation(&self, item_id: LookupItemId) -> String;
>     /// Gets the the definition + documentation above.
>     fn documentation_with_definition(&self, item_id: LookupItemId) -> (String, String);
> ```

I think we'd like to have some unit-style tests for these queries, that will also focus on edge cases, aren't we @orizi?
___
*[`crates/cairo-lang-defs/src/db.rs` line 309 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5225#-Nslbs5q4aERf1pl-QzC:-Nslbs5q4aERf1pl-QzD:b-fwrz1h) ([raw file](https://github.com/starkware-libs/cairo/blob/894a38c10ad33ef2f88adfcac42d3a728ef59869/crates/cairo-lang-defs/src/db.rs#L309)):*
> ```XML
>         item_id.stable_location(db).syntax_node(db).get_text_without_trivia(db.upcast());
>     // Remove the function implementation if it's a function.
>     let definition = if let Some(index) = definition.find('{') {
> ```

The following snippets bust this implementation as I understand things:

```rust
const FOO = { 52 };
```

```rust
#[macro(x = { 2 })]
fn foo() {}
```

You must traverse the AST here, and cut out function/module bodies subtrees manually, to make this correct.


<!-- Sent from Reviewable.io -->

2024-03-12 09:35 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @LucasLvy)

___
*[`crates/cairo-lang-defs/src/db.rs` line 288 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5225#-Nsm-znu8kBS--vmSbDf:-Nsm-znu8kBS--vmSbDg:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/894a38c10ad33ef2f88adfcac42d3a728ef59869/crates/cairo-lang-defs/src/db.rs#L288)):*
> ```XML
> }
> 
> fn documentation(db: &dyn DefsGroup, item_id: LookupItemId) -> String {
> ```

doc


<!-- Sent from Reviewable.io -->

2024-03-12 09:36 UTC, LucasLvy reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 309 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5225#-Nslbs5q4aERf1pl-QzC:-Nslyz0b1NlNGuzsUSWN:b-euqplq) ([raw file](https://github.com/starkware-libs/cairo/blob/894a38c10ad33ef2f88adfcac42d3a728ef59869/crates/cairo-lang-defs/src/db.rs#L309)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

The following snippets bust this implementation as I understand things:

```rust
const FOO = { 52 };
```

```rust
#[macro(x = { 2 })]
fn foo() {}
```

You must traverse the AST here, and cut out function/module bodies subtrees manually, to make this correct.
</blockquote></details>

2nd one is easy to fix, can have something for the constant case also. Never really worked with the tree so i'm not sure how "better" it is but i have a feeling that i'd need to have one case per node type which wouldn't be so much better. WDYT ?


<!-- Sent from Reviewable.io -->

2024-03-12 09:39 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @LucasLvy and @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 309 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5225#-Nslbs5q4aERf1pl-QzC:-Nsm0szLCOkmTylqOmcy:b-nmqmjl) ([raw file](https://github.com/starkware-libs/cairo/blob/894a38c10ad33ef2f88adfcac42d3a728ef59869/crates/cairo-lang-defs/src/db.rs#L309)):*
<details><summary><i>Previously, LucasLvy (Lucas @ StarkWare) wrote…</i></summary><blockquote>

2nd one is easy to fix, can have something for the constant case also. Never really worked with the tree so i'm not sure how "better" it is but i have a feeling that i'd need to have one case per node type which wouldn't be so much better. WDYT ?
</blockquote></details>

let's discuss this offline


<!-- Sent from Reviewable.io -->

2024-03-12 10:09 UTC, mkaput reviewed
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: all files reviewed, 5 unresolved discussions (waiting on @LucasLvy)



<!-- Sent from Reviewable.io -->

2024-03-12 17:07 UTC, mkaput requested changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: all files reviewed, 5 unresolved discussions (waiting on @LucasLvy)

___
*[`crates/cairo-lang-defs/src/db.rs` line 106 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5225#-NsncJ9vANdaXMCDkCfA:-NsncJ9vANdaXMCDkCfB:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4f6a269770c1b8b8942a61a72fc02ba6d65fd61c/crates/cairo-lang-defs/src/db.rs#L106)):*
> ```XML
> 
>     /// Gets the documentation above an item definition.
>     fn get_item_documentation(&self, item_id: LookupItemId) -> String;
> ```





_Suggestion:_
```XML
Option<String>
```
___
*[`crates/cairo-lang-defs/src/db.rs` line 108 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5225#-Nsnc801CtJA-8vtrlMa:-Nsnc801CtJA-8vtrlMb:bjuerj8) ([raw file](https://github.com/starkware-libs/cairo/blob/4f6a269770c1b8b8942a61a72fc02ba6d65fd61c/crates/cairo-lang-defs/src/db.rs#L108)):*
> ```XML
>     fn get_item_documentation(&self, item_id: LookupItemId) -> String;
>     /// Gets the the definition + documentation above.
>     fn get_item_definition(&self, item_id: LookupItemId) -> String;
> ```

perhaps let's use `Option` to use `None` as "this item does not have definition"?



_Suggestion:_
```XML
Option<String>
```


<!-- Sent from Reviewable.io -->

2024-03-13 09:45 UTC, LucasLvy reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: all files reviewed, 5 unresolved discussions (waiting on @mkaput)

___
*[`crates/cairo-lang-defs/src/db.rs` line 108 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5225#-Nsnc801CtJA-8vtrlMa:-NsrBRhG53kUrUVHZrme:b-q8rd30) ([raw file](https://github.com/starkware-libs/cairo/blob/4f6a269770c1b8b8942a61a72fc02ba6d65fd61c/crates/cairo-lang-defs/src/db.rs#L108)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

perhaps let's use `Option` to use `None` as "this item does not have definition"?
</blockquote></details>

I don't see a good reason to do that, if there's no documentation it'll display
```
definition
---

```
which is fine, if we return `None` we then either need to propagate (which we don't want because we still want to display the definition, or use `if let Some` which is equivalent to returning the empty string imo


<!-- Sent from Reviewable.io -->

2024-03-13 09:45 UTC, LucasLvy reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: all files reviewed, 5 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 288 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5225#-Nsm-znu8kBS--vmSbDf:-NsrBuTnAyoJ5AvOGwPO:b5osl15) ([raw file](https://github.com/starkware-libs/cairo/blob/894a38c10ad33ef2f88adfcac42d3a728ef59869/crates/cairo-lang-defs/src/db.rs#L288)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

the doc is in the trait. Should i copy paste it here also?


<!-- Sent from Reviewable.io -->

2024-03-13 10:16 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: all files reviewed, 5 unresolved discussions (waiting on @LucasLvy and @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 108 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5225#-Nsnc801CtJA-8vtrlMa:-NsrIcTX7oDXkLXba73Q:brpx1kc) ([raw file](https://github.com/starkware-libs/cairo/blob/4f6a269770c1b8b8942a61a72fc02ba6d65fd61c/crates/cairo-lang-defs/src/db.rs#L108)):*
<details><summary><i>Previously, LucasLvy (Lucas @ StarkWare) wrote…</i></summary><blockquote>

I don't see a good reason to do that, if there's no documentation it'll display
```
definition
---

```
which is fine, if we return `None` we then either need to propagate (which we don't want because we still want to display the definition, or use `if let Some` which is equivalent to returning the empty string imo
</blockquote></details>

Technically, there's a difference between

```rust
fn foo() {}
```

and 

```rust
///
fn foo() {}
```

IMO The compiler code should differentiate these (you might not want to display empty pop-up if there is no documentation hypothetically), while LS can simply do `.unwrap_or_default()`. Though to my taste, I'd skip the `---` separator in this scenario.


<!-- Sent from Reviewable.io -->

2024-03-13 12:41 UTC, orizi approved these changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: all files reviewed, 3 unresolved discussions (waiting on @LucasLvy and @mkaput)

___
*[`crates/cairo-lang-defs/src/db.rs` line 107 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5225#-NslcV6V2FIdWS_KGxf3:-Nsrozm3AwYnvcEyoozq:b-eyu0l0) ([raw file](https://github.com/starkware-libs/cairo/blob/894a38c10ad33ef2f88adfcac42d3a728ef59869/crates/cairo-lang-defs/src/db.rs#L107)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I think we'd like to have some unit-style tests for these queries, that will also focus on edge cases, aren't we @orizi?
</blockquote></details>

Definitely.


<!-- Sent from Reviewable.io -->

2024-03-13 13:07 UTC, LucasLvy reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: all files reviewed, 3 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-defs/src/db.rs` line 107 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5225#-NslcV6V2FIdWS_KGxf3:-NsrtuNX3gWR03VR6TRj:b-3e283o) ([raw file](https://github.com/starkware-libs/cairo/blob/894a38c10ad33ef2f88adfcac42d3a728ef59869/crates/cairo-lang-defs/src/db.rs#L107)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Definitely.
</blockquote></details>

I won't have time for that, so feel free to close this pr or take it over


<!-- Sent from Reviewable.io -->

2024-03-14 13:03 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: all files reviewed, 1 unresolved discussion (waiting on @LucasLvy and @mkaput)

___
*[`crates/cairo-lang-defs/src/db.rs` line 107 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5225#-NslcV6V2FIdWS_KGxf3:-Nsx2qqi2x1zKdoOIWNP:bl2ei4k) ([raw file](https://github.com/starkware-libs/cairo/blob/894a38c10ad33ef2f88adfcac42d3a728ef59869/crates/cairo-lang-defs/src/db.rs#L107)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Leaving decision to @orizi
</blockquote></details>

Fine with a Todo here, but should be done soon


<!-- Sent from Reviewable.io -->

2024-03-15 11:30 UTC, mkaput approved these changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: all files reviewed, 1 unresolved discussion (waiting on @LucasLvy and @orizi)



<!-- Sent from Reviewable.io -->

2024-03-17 19:06 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: all files reviewed, 1 unresolved discussion (waiting on @LucasLvy)

___
*[`crates/cairo-lang-defs/src/db.rs` line 109 at r10](https://reviewable.io/reviews/starkware-libs/cairo/5225#-NtCnhuRCiJYy-zQQYDE:-NtCnhuRCiJYy-zQQYDF:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/edfa6b81b48477e2248ef50c378ab7d669c14e76/crates/cairo-lang-defs/src/db.rs#L109)):*
> ```XML
>     fn get_item_documentation(&self, item_id: LookupItemId) -> Option<String>;
>     // TODO: test that
>     /// Gets the the definition of an item.
> ```





_Suggestion:_
```XML
    // TODO(assignee): Add tests.
    /// Gets the documentation above an item definition.
    fn get_item_documentation(&self, item_id: LookupItemId) -> Option<String>;
    // TODO(assignee): Add tests.
    /// Gets the the definition of an item.
```


<!-- Sent from Reviewable.io -->

2024-03-18 11:27 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225#-:-NtGJ7qYCKxm4xrvlvkx:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @LucasLvy)

___
*[`crates/cairo-lang-defs/src/db.rs` line 105 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5225#-NtGIhAK-bIUNG1-e6xD:-NtGIhAK-bIUNG1-e6xE:bb7lc4s) ([raw file](https://github.com/starkware-libs/cairo/blob/c1009eaa7457a77fec995c679b2c818cc2a56bcd/crates/cairo-lang-defs/src/db.rs#L105)):*
> ```XML
>     fn module_dir(&self, module_id: ModuleId) -> Maybe<Directory>;
> 
>     // TODO(Marek): test that
> ```

nit 



_Suggestion:_
```XML
mkaput
```
___
*[`crates/cairo-lang-defs/src/db.rs` line 108 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5225#-NtGIkbOCZoAJ3SnSBJw:-NtGIkbOCZoAJ3SnSBJx:b2ni8l0) ([raw file](https://github.com/starkware-libs/cairo/blob/c1009eaa7457a77fec995c679b2c818cc2a56bcd/crates/cairo-lang-defs/src/db.rs#L108)):*
> ```XML
>     /// Gets the documentation above an item definition.
>     fn get_item_documentation(&self, item_id: LookupItemId) -> Option<String>;
>     // TODO(Marek): test that
> ```

nit



_Suggestion:_
```XML
mkaput
```
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 1443 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5225#-NtGIuqJCugqrxyS-Jbo:-NtGIuqJCugqrxyS-Jbp:b-b1ts18) ([raw file](https://github.com/starkware-libs/cairo/blob/c1009eaa7457a77fec995c679b2c818cc2a56bcd/crates/cairo-lang-language-server/src/lib.rs#L1443)):*
> ```XML
> }
> 
> // TODO: test this
> ```

nit, this particular function won't be probably tested _per se_, but we'd rather focus on testing LSP commands


<!-- Sent from Reviewable.io -->

2024-03-18 14:25 UTC, mkaput approved these changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: all files reviewed, 1 unresolved discussion (waiting on @LucasLvy and @orizi)



<!-- Sent from Reviewable.io -->

2024-03-18 15:24 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: all files reviewed, 1 unresolved discussion (waiting on @LucasLvy)

___
*[`crates/cairo-lang-defs/src/db.rs` line 109 at r10](https://reviewable.io/reviews/starkware-libs/cairo/5225#-NtCnhuRCiJYy-zQQYDE:-NtH9LCbE479XUC7cM3B:bc4bty4) ([raw file](https://github.com/starkware-libs/cairo/blob/edfa6b81b48477e2248ef50c378ab7d669c14e76/crates/cairo-lang-defs/src/db.rs#L109)):*
> ```XML
>     fn get_item_documentation(&self, item_id: LookupItemId) -> Option<String>;
>     // TODO: test that
>     /// Gets the the definition of an item.
> ```

Not resolved yet.


<!-- Sent from Reviewable.io -->

2024-03-18 15:28 UTC, mkaput approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: all files reviewed, 1 unresolved discussion (waiting on @LucasLvy and @orizi)



<!-- Sent from Reviewable.io -->

2024-03-18 15:29 UTC, orizi approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5225)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LucasLvy)



<!-- Sent from Reviewable.io -->

2024-03-18 15:40 UTC, merged