added syscall for sha256
starkware-libs/cairo pull request #5348
Opened 2024-04-01 11:58 UTC by TomerStarkware

2024-04-01 12:11 UTC, orizi requested changes
> Reviewed 7 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: 7 of 18 files reviewed, 5 unresolved discussions (waiting on @TomerStarkware)

___
*[`corelib/src/sha256.cairo` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOYQpq0oR0E8Jkygyj:-NuOYQpq0oR0E8Jkygyk:bqkj2yq) ([raw file](https://github.com/starkware-libs/cairo/blob/f162159d82adee68ca5968e05db81f0ab468b80a/corelib/src/sha256.cairo#L22)):*
> ```Cairo
> 
> /// Appends `max(n,8)` zeros to the array and updates n.
> #[inline(always)]
> ```

remove.

Move helpers to the end.



_Code quote:_
```Cairo
#[inline(always)]
```
___
*[`corelib/src/sha256.cairo` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOYe2WCegTELqJFfBT:-NuOYe2WCegTELqJFfBU:b-xp2p3h) ([raw file](https://github.com/starkware-libs/cairo/blob/f162159d82adee68ca5968e05db81f0ab468b80a/corelib/src/sha256.cairo#L23)):*
> ```Cairo
> /// Appends `max(n,8)` zeros to the array and updates n.
> #[inline(always)]
> fn append_zero(ref arr: Array<u32>, ref n: felt252) {
> ```

n is always 0 at the end of the function.
remove the ref and the calcs.



_Code quote:_
```Cairo
fn append_zero(ref arr: Array<u32>, ref n: felt252) {
```
___
*[`corelib/src/sha256.cairo` line 120 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOZ92T8wWMIb0IIgWa:-NuOZ92T8wWMIb0IIgWb:bfi0hue) ([raw file](https://github.com/starkware-libs/cairo/blob/f162159d82adee68ca5968e05db81f0ab468b80a/corelib/src/sha256.cairo#L120)):*
> ```Cairo
> /// Computes the SHA-256 hash of the input array.
> /// use last_input_word when the number of bytes in the last input word is less than 4.
> pub fn sha256_cairo(
> ```

this name is meaningless.



_Code quote:_
```Cairo
sha256_cairo
```
___
*[`corelib/src/sha256.cairo` line 141 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOZCBkDWEbzKwQMzHw:-NuOZCBkDWEbzKwQMzHx:b-6c9myy) ([raw file](https://github.com/starkware-libs/cairo/blob/f162159d82adee68ca5968e05db81f0ab468b80a/corelib/src/sha256.cairo#L141)):*
> ```Cairo
> 
> /// Computes the SHA-256 hash of the input ByteArray.
> pub fn sha256_byte_array(arr: @ByteArray) -> [u32; 8] {
> ```

improve name.



_Code quote:_
```Cairo
sha256_byte_array(
```
___
*[`corelib/src/starknet/syscalls.cairo` line 107 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOZF2y3vcmn1DOW7mO:-NuOZF2y3vcmn1DOW7mP:b-oeazge) ([raw file](https://github.com/starkware-libs/cairo/blob/f162159d82adee68ca5968e05db81f0ab468b80a/corelib/src/starknet/syscalls.cairo#L107)):*
> ```Cairo
> pub extern fn sha256_chunk_syscall(
>     state: SHA256StateHandle, input: Span<u32>
> ) -> SyscallResult<sha256::SHA256StateHandle> implicits(GasBuiltin, System) nopanic;
> ```

empty line.


<!-- Sent from Reviewable.io -->

2024-04-01 12:56 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: 7 of 18 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/sha256.cairo` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOYe2WCegTELqJFfBT:-NuOexQL3of8UYRnGiTg:bvcc6ks) ([raw file](https://github.com/starkware-libs/cairo/blob/f162159d82adee68ca5968e05db81f0ab468b80a/corelib/src/sha256.cairo#L23)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

n is always 0 at the end of the function.
remove the ref and the calcs.
</blockquote></details>

n can be 14, I can change the function for more cases
___
*[`corelib/src/sha256.cairo` line 120 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOZ92T8wWMIb0IIgWa:-NuOfPUu0fklKj46Fs_N:b-n9tkhd) ([raw file](https://github.com/starkware-libs/cairo/blob/f162159d82adee68ca5968e05db81f0ab468b80a/corelib/src/sha256.cairo#L120)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this name is meaningless.
</blockquote></details>

changed
___
*[`corelib/src/sha256.cairo` line 141 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOZCBkDWEbzKwQMzHw:-NuOfQhC3OWdppfQEh1s:b-n9tkhd) ([raw file](https://github.com/starkware-libs/cairo/blob/f162159d82adee68ca5968e05db81f0ab468b80a/corelib/src/sha256.cairo#L141)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

improve name.
</blockquote></details>

changed
___
*[`corelib/src/starknet/syscalls.cairo` line 107 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOZF2y3vcmn1DOW7mO:-NuOfR_w8KmRoBszGHlH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f162159d82adee68ca5968e05db81f0ab468b80a/corelib/src/starknet/syscalls.cairo#L107)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

empty line.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-01 13:27 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: 7 of 18 files reviewed, 7 unresolved discussions (waiting on @TomerStarkware)

___
*[`corelib/src/sha256.cairo` line 7 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOm9Q2-z6wrKK4JrDB:-NuOm9Q2-z6wrKK4JrDC:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/corelib/src/sha256.cairo#L7)):*
> ```Cairo
> 
> impl DropSHA256StateHandle of Drop<SHA256StateHandle>;
> impl CopySHA256StateHandle of Copy<SHA256StateHandle>;
> ```





_Suggestion:_
```Cairo
/// A handle to the state of a SHA-256 hash.
#[derive(Copy, Drop)]
extern type SHA256StateHandle;
```
___
*[`corelib/src/sha256.cairo` line 13 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOmKIaAybDwiAdZfLY:-NuOmKIaAybDwiAdZfLZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/corelib/src/sha256.cairo#L13)):*
> ```Cairo
> 
> /// returns the state of a SHA-256 hash.
> pub extern fn sha256_state_handle_digest(state: SHA256StateHandle) -> Box<[u32; 8]> nopanic;
> ```





_Suggestion:_
```Cairo
/// Initializes a new SHA-256 state handle.
extern fn sha256_state_handle_init(state: Box<[u32; 8]>) -> SHA256StateHandle nopanic;

/// returns the state of a SHA-256 hash.
extern fn sha256_state_handle_digest(state: SHA256StateHandle) -> Box<[u32; 8]> nopanic;
```
___
*[`corelib/src/sha256.cairo` line 26 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOm-p0BuQCuzJlooSA:-NuOm-p0BuQCuzJlooSB:b-5k9oxy) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/corelib/src/sha256.cairo#L26)):*
> ```Cairo
> /// 3. Append the length of the array in bits as a 64-bit number.
> /// use last_input_word when the number of bytes in the last input word is less than 4.
> fn add_sha256_padding(ref arr: Array<u32>, last_input_word: u32, last_input_num_bytes: u32) {
> ```

move to end. (before `append_zeros`)

interface functions before helpers.
___
*[`corelib/src/sha256.cairo` line 51 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOpvZBAQKBSt_pI77_:-NuOpvZBAQKBSt_pI77a:bisuxvt) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/corelib/src/sha256.cairo#L51)):*
> ```Cairo
> 
> /// Computes the SHA-256 hash of the input array.
> /// use last_input_word when the number of bytes in the last input word is less than 4.
> ```

define the other parameters as well.



_Code quote:_
```Cairo
/// Computes the SHA-256 hash of the input array.
/// use last_input_word when the number of bytes in the last input word is less than 4.
```
___
*[`corelib/src/sha256.cairo` line 164 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOo5Bk6yHHr2gp8hOP:-NuOo5Bk6yHHr2gp8hOQ:b7amasz) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/corelib/src/sha256.cairo#L164)):*
> ```Cairo
>         },
>     }
> }
> ```

how will this be?



_Suggestion:_
```Cairo
fn append_zeros(ref arr: Array<u32>, count: felt252) {
    if count == 0 { return; }
    arr.append(0);
    if count == 1 { return; }
    arr.append(0);
    if count == 2 { return; }
    arr.append(0);
    if count == 3 { return; }
    arr.append(0);
    if count == 4 { return; }
    arr.append(0);
    if count == 5 { return; }
    arr.append(0);
    if count == 6 { return; }
    arr.append(0);
    if count == 7 { return; }
    arr.append(0);
    if count == 8 { return; }
    arr.append(0);
    if count == 9 { return; }
    arr.append(0);
    if count == 10 { return; }
    arr.append(0);
    if count == 11 { return; }
    arr.append(0);
    if count == 12 { return; }
    arr.append(0);
    if count == 13 { return; }
    arr.append(0);
    if count == 14 { return; }
    arr.append(0);
}
```


<!-- Sent from Reviewable.io -->

2024-04-01 13:28 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: 7 of 18 files reviewed, 8 unresolved discussions (waiting on @TomerStarkware)

___
*[`corelib/src/prelude/v2023_01.cairo` line 47 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOq6ra6kTHjtXc3F2l:-NuOq6ra6kTHjtXc3F2m:b15csb) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/corelib/src/prelude/v2023_01.cairo#L47)):*
> ```Cairo
> use core::internal;
> use core::keccak;
> use core::sha256;
> ```

remove.
no reason for this to be in prelude.



_Code quote:_
```Cairo
use core::sha256;
```


<!-- Sent from Reviewable.io -->

2024-04-01 13:28 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: 7 of 18 files reviewed, 9 unresolved discussions (waiting on @TomerStarkware)

___
*[`corelib/src/prelude/v2023_10.cairo` line 12 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOqCMd9L2DKhKY2kU7:-NuOqCMd9L2DKhKY2kU8:b-hfpv23) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/corelib/src/prelude/v2023_10.cairo#L12)):*
> ```Cairo
> pub use core::integer::{Bitwise, i128, i16, i32, i64, i8, u128, u16, u256, u32, u64, u8};
> pub use core::keccak;
> pub use core::sha256;
> ```

remove.


<!-- Sent from Reviewable.io -->

2024-04-01 13:31 UTC, orizi requested changes
> Reviewed 1 of 2 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: 9 of 18 files reviewed, 9 unresolved discussions (waiting on @TomerStarkware)

___
*[`corelib/src/test/sha256_test.cairo` line 6 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOqa57BUZJqEliPzA1:-NuOqa57BUZJqEliPzA2:boz7l58) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/corelib/src/test/sha256_test.cairo#L6)):*
> ```Cairo
> #[test]
> fn test_sha256_byte_array() {
>     let [a, _, _, _, _, _, _, _,] = sha256::compute_sha256_byte_array(@"a");
> ```

add a TODO to compare all values when PartialEq for fixed sized array is supported.


<!-- Sent from Reviewable.io -->

2024-04-01 13:36 UTC, orizi requested changes
> Reviewed 1 of 17 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: 11 of 18 files reviewed, 13 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 714 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOrLMr34jrgckr1YA2:-NuOrLMr34jrgckr1YA3:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/crates/cairo-lang-runner/src/casm_run/mod.rs#L714)):*
> ```XML
> 
>                 sha256_chunk(gas_counter, prev_state, data, exec_scopes, system_buffer)
>             }),
> ```





_Suggestion:_
```XML
            "SHA256Chunk" => execute_handle_helper(&mut |system_buffer, gas_counter| {
                sha256_chunk(
                    gas_counter,
                    system_buffer.next_fixed_size_arr(8)?,
                    system_buffer.next_arr()?,
                    exec_scopes,
                    system_buffer,
                )
            }),
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 164 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOrXxKD2DNyAsCNNFU:-NuOrXxKD2DNyAsCNNFV:bljob9k) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L164)):*
> ```XML
> }
> 
> /// Type representing the Bitwise builtin.
> ```

fix doc
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/starknet/mod.rs` line 126 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOrrGJA4YfH8b0N-20:-NuOrrGJA4YfH8b0N-21:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/crates/cairo-lang-sierra-to-casm/src/invocations/starknet/mod.rs#L126)):*
> ```XML
>     for (i, input_size) in input_sizes.iter().enumerate() {
>         let cells = &builder.refs[i + 2].expression.cells;
>         assert_eq!(cells.len(), *input_size as usize);
> ```

revert



_Code quote:_
```XML
        assert_eq!(cells.len(), *input_size as usize);
```
___
*[`crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/all.json` line 231 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOruuyAjqF2Ecqmln0:-NuOruuyAjqF2Ecqmln1:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/all.json#L231)):*
> ```JSON
>         "withdraw_gas_all"
>     ]
> }
> ```

revert


<!-- Sent from Reviewable.io -->

2024-04-01 14:16 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: 8 of 18 files reviewed, 12 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/sha256.cairo` line 7 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOm9Q2-z6wrKK4JrDB:-NuOtWLu47XmqRPbU0br:bpgut5o) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/corelib/src/sha256.cairo#L7)):*
> ```Cairo
> 
> impl DropSHA256StateHandle of Drop<SHA256StateHandle>;
> impl CopySHA256StateHandle of Copy<SHA256StateHandle>;
> ```

I need pub to use from syscall.cairo
___
*[`corelib/src/sha256.cairo` line 13 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOmKIaAybDwiAdZfLY:-NuOtamKAwRU6C9z50-J:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/corelib/src/sha256.cairo#L13)):*
> ```Cairo
> 
> /// returns the state of a SHA-256 hash.
> pub extern fn sha256_state_handle_digest(state: SHA256StateHandle) -> Box<[u32; 8]> nopanic;
> ```

Done.
___
*[`corelib/src/sha256.cairo` line 26 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOm-p0BuQCuzJlooSA:-NuOtwVM6kXiaJtsxwHe:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/corelib/src/sha256.cairo#L26)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move to end. (before `append_zeros`)

interface functions before helpers.
</blockquote></details>

Done.
___
*[`corelib/src/sha256.cairo` line 51 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOpvZBAQKBSt_pI77_:-NuOw4RW737yXz_NOiOz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/corelib/src/sha256.cairo#L51)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

define the other parameters as well.
</blockquote></details>

Done.
___
*[`corelib/src/sha256.cairo` line 164 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOo5Bk6yHHr2gp8hOP:-NuOwPJ04Ih14ixLLSsN:b-1ap4fg) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/corelib/src/sha256.cairo#L164)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

how will this be?
</blockquote></details>

Done. (~20 steps more expensive per call)
___
*[`corelib/src/test/sha256_test.cairo` line 6 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOqa57BUZJqEliPzA1:-NuOx1dx1SlDeRvi_DgZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/corelib/src/test/sha256_test.cairo#L6)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add a TODO to compare all values when PartialEq for fixed sized array is supported.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 714 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOrLMr34jrgckr1YA2:-NuOztxD7fxVWZALyYEA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/crates/cairo-lang-runner/src/casm_run/mod.rs#L714)):*
> ```XML
> 
>                 sha256_chunk(gas_counter, prev_state, data, exec_scopes, system_buffer)
>             }),
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 164 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOrXxKD2DNyAsCNNFU:-NuP-4PZA4q5xFyRxDGu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L164)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/starknet/mod.rs` line 126 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOrrGJA4YfH8b0N-20:-NuP-EGt9RR6DlHx9rqt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/crates/cairo-lang-sierra-to-casm/src/invocations/starknet/mod.rs#L126)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/all.json` line 231 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOruuyAjqF2Ecqmln0:-NuOzjol9wopvjv0CLZ7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists/all.json#L231)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.
___
*[`corelib/src/prelude/v2023_01.cairo` line 47 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOq6ra6kTHjtXc3F2l:-NuOwY0z4ASFHB6nD-rb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/corelib/src/prelude/v2023_01.cairo#L47)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove.
no reason for this to be in prelude.
</blockquote></details>

Done.
___
*[`corelib/src/prelude/v2023_10.cairo` line 12 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOqCMd9L2DKhKY2kU7:-NuOwZ0h2SYSIO2tADhV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/corelib/src/prelude/v2023_10.cairo#L12)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-01 14:48 UTC, orizi requested changes
> Reviewed 2 of 17 files at r1, 2 of 4 files at r5, 1 of 3 files at r6, 3 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: 16 of 18 files reviewed, 9 unresolved discussions (waiting on @TomerStarkware)

___
*[`corelib/src/sha256.cairo` line 7 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOm9Q2-z6wrKK4JrDB:-NuP6ITb1RoKKawf2VAZ:bw7x9zz) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/corelib/src/sha256.cairo#L7)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

I need pub to use from syscall.cairo
</blockquote></details>

you need `pub(crate)` for it.
___
*[`corelib/src/sha256.cairo` line 164 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOo5Bk6yHHr2gp8hOP:-NuP6bQuBzTU7HFp5BCd:ba8m0ds) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/corelib/src/sha256.cairo#L164)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

Done. (~20 steps more expensive per call)
</blockquote></details>

per call to what?
___
*[`corelib/src/sha256.cairo` line 28 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuP6SD6EXxvULaIEhTv:-NuP6SD6EXxvULaIEhTw:b-qaa3mn) ([raw file](https://github.com/starkware-libs/cairo/blob/d5e30765d4cecad954afe79015f87e09a4541982/corelib/src/sha256.cairo#L28)):*
> ```Cairo
>     ) -> [
>     u32
> ; 8] {
> ```

rebase over fmt fix.
___
*[`corelib/src/test/sha256_test.cairo` line 6 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuP6q_b7OvgesXm-YM_:-NuP6q_b7OvgesXm-YMa:b-agtnr5) ([raw file](https://github.com/starkware-libs/cairo/blob/d5e30765d4cecad954afe79015f87e09a4541982/corelib/src/test/sha256_test.cairo#L6)):*
> ```Cairo
> #[test]
> fn test_sha256_byte_array() {
>     // TODO(TomerStarkware): compare all values when PartialEq is implemented for fixed size array is supported.
> ```

line too long.
___
*[`corelib/src/test/sha256_test.cairo` line 8 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuP6o3n4EnXi-cOwVEj:-NuP6o3n4EnXi-cOwVEk:bgilazn) ([raw file](https://github.com/starkware-libs/cairo/blob/d5e30765d4cecad954afe79015f87e09a4541982/corelib/src/test/sha256_test.cairo#L8)):*
> ```Cairo
>     // TODO(TomerStarkware): compare all values when PartialEq is implemented for fixed size array is supported.
> 
>     let [a, _, _, _, _, _, _, _,] = core::sha256::compute_sha256_byte_array(@"a");
> ```

add use



_Code quote:_
```Cairo
compute_sha256_byte_array
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 176 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuP70F2CthK-UZABKPZ:-NuP70F2CthK-UZABKP_:boa6ky5) ([raw file](https://github.com/starkware-libs/cairo/blob/d5e30765d4cecad954afe79015f87e09a4541982/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L176)):*
> ```XML
> 
> /// Libfunc for the sha256_chunk system call.
> /// The input needs to be 16 bytes.
> ```

this does not sound correct.
also - describe both inputs.



_Code quote:_
```XML
/// The input needs to be 16 bytes.
```
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 188 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuP7FBN80DP0oM8e75s:-NuP7FBN80DP0oM8e75t:b1os0lc) ([raw file](https://github.com/starkware-libs/cairo/blob/d5e30765d4cecad954afe79015f87e09a4541982/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L188)):*
> ```XML
>             // input
>             context.get_concrete_type(SHA256StateHandleType::id(), &[])?,
>             u32_span_ty(context)?,
> ```

doc this var as well.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 225 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuP7Kkf5woGx57c5Ui-:-NuP7Kkf5woGx57c5Ui0:bag3wll) ([raw file](https://github.com/starkware-libs/cairo/blob/d5e30765d4cecad954afe79015f87e09a4541982/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L225)):*
> ```XML
>                         GenericArg::Type(context.get_concrete_type(Uint32Type::id(), &[])?),
>                     ],
>                 )?,
> ```

extract to func.



_Code quote:_
```XML
                context.get_concrete_type(
                    StructType::id(),
                    &[
                        GenericArg::UserType(UserTypeId::from_string("Tuple")),
                        GenericArg::Type(context.get_concrete_type(Uint32Type::id(), &[])?),
                        GenericArg::Type(context.get_concrete_type(Uint32Type::id(), &[])?),
                        GenericArg::Type(context.get_concrete_type(Uint32Type::id(), &[])?),
                        GenericArg::Type(context.get_concrete_type(Uint32Type::id(), &[])?),
                        GenericArg::Type(context.get_concrete_type(Uint32Type::id(), &[])?),
                        GenericArg::Type(context.get_concrete_type(Uint32Type::id(), &[])?),
                        GenericArg::Type(context.get_concrete_type(Uint32Type::id(), &[])?),
                        GenericArg::Type(context.get_concrete_type(Uint32Type::id(), &[])?),
                    ],
                )?,
```


<!-- Sent from Reviewable.io -->

2024-04-01 15:35 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: 9 of 18 files reviewed, 7 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/sha256.cairo` line 7 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOm9Q2-z6wrKK4JrDB:-NuPAR79DbRLhn9bR0XD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/corelib/src/sha256.cairo#L7)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you need `pub(crate)` for it.
</blockquote></details>

Done.
___
*[`corelib/src/sha256.cairo` line 164 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuOo5Bk6yHHr2gp8hOP:-NuPAVZk3ItZ2k9SLTxf:bmqvk8u) ([raw file](https://github.com/starkware-libs/cairo/blob/624afe2624fb0e77036b0e4f0a6705ae833a3157/corelib/src/sha256.cairo#L164)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

per call to what?
</blockquote></details>

sha256_padding
___
*[`corelib/src/sha256.cairo` line 28 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuP6SD6EXxvULaIEhTv:-NuPBEfyBwK3J4pFDZLw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d5e30765d4cecad954afe79015f87e09a4541982/corelib/src/sha256.cairo#L28)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rebase over fmt fix.
</blockquote></details>

Done.
___
*[`corelib/src/test/sha256_test.cairo` line 6 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuP6q_b7OvgesXm-YM_:-NuPAk9j8tjMR_LYN8vD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d5e30765d4cecad954afe79015f87e09a4541982/corelib/src/test/sha256_test.cairo#L6)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

line too long.
</blockquote></details>

Done.
___
*[`corelib/src/test/sha256_test.cairo` line 8 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuP6o3n4EnXi-cOwVEj:-NuPB-YB34D2dtTtwCOa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d5e30765d4cecad954afe79015f87e09a4541982/corelib/src/test/sha256_test.cairo#L8)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add use
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 176 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuP70F2CthK-UZABKPZ:-NuP9Iq-5gZe3_EI3ww2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d5e30765d4cecad954afe79015f87e09a4541982/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L176)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this does not sound correct.
also - describe both inputs.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 188 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuP7FBN80DP0oM8e75s:-NuP9P8p3hxG9Jkaso5V:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d5e30765d4cecad954afe79015f87e09a4541982/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L188)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc this var as well.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 225 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuP7Kkf5woGx57c5Ui-:-NuPAFkh0Z0fSGSiENS9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d5e30765d4cecad954afe79015f87e09a4541982/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L225)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

extract to func.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-01 15:46 UTC, orizi requested changes
> Reviewed 2 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: 17 of 18 files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 235 at r10](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuPKg24BvddqFjfu7kR:-NuPKg24BvddqFjfu7kS:b4e26at) ([raw file](https://github.com/starkware-libs/cairo/blob/2686b3acd30d49c3db8d8cf58df4d6c790c28724/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L235)):*
> ```XML
>     }
> }
> pub fn sha256_state_handle_unwrapped_type(
> ```

doc + empty line.


<!-- Sent from Reviewable.io -->

2024-04-01 15:47 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: 17 of 18 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/test/sha256_test.cairo` line 7 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuPFSL_0T_BLQHSVfr3:-NuPKSyG7fb3vcSpWRWJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c58fd71bef01d7e378cbfdf44acaa7ddf4d88b99/corelib/src/test/sha256_test.cairo#L7)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

make the line as long as possible, while not reaching 100 chars.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 709 at r9](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuPJ9n12n-JWtDBwynK:-NuPKRS57JuzdBomBZ1Z:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7fbbaab12b037e2e80042ed14809dfc153d9bf1d/crates/cairo-lang-runner/src/casm_run/mod.rs#L709)):*
> ```XML
>                 keccak(gas_counter, system_buffer.next_arr()?)
>             }),
>             "SHA256Block" => execute_handle_helper(&mut |system_buffer, gas_counter| {
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 190 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuPGFY884ZGzj7pnMK6:-NuPJ7VN0PwLGG6-J8re:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c58fd71bef01d7e378cbfdf44acaa7ddf4d88b99/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L190)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

helper function - put after usage.
no reason to be a member of anything.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 208 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuPFtfd6aAOT_8n89FF:-NuPIr7Q6hBaPkO-uS5m:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c58fd71bef01d7e378cbfdf44acaa7ddf4d88b99/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L208)):*
> ```XML
>     const STR_ID: &'static str = "sha256_chunk_syscall";
> 
>     fn input_tys(
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 214 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuPG0JtEug-fbX1lAAe:-NuPInp15QxGCUFhWnq9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c58fd71bef01d7e378cbfdf44acaa7ddf4d88b99/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L214)):*
> ```XML
>             // previous state
>             context.get_concrete_type(SHA256StateHandleType::id(), &[])?,
>             // input
> ```

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 212 at r9](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuPIt-t5dvFoj6COa1s:-NuPL-K1BBxWOiY_CUkT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7fbbaab12b037e2e80042ed14809dfc153d9bf1d/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L212)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

should either be a proper doc - or the name of the var.
if proper doc - should end in . and start with capital.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-01 15:48 UTC, orizi reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-04-01 15:50 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs` line 235 at r10](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuPKg24BvddqFjfu7kR:-NuPLYEwAGp1Ps16SCyN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2686b3acd30d49c3db8d8cf58df4d6c790c28724/crates/cairo-lang-sierra/src/extensions/modules/starknet/syscalls.rs#L235)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc + empty line.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-01 15:51 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348#-:-NuPLpFp9VcVxUfbSORx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-04-03 11:19 UTC, orizi requested changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 79 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuYfnvL6RSedAwvebuX:-NuYfnvL6RSedAwvebuY:becpq0q) ([raw file](https://github.com/starkware-libs/cairo/blob/097ef0a43b05c9e1cab49264d1fbaf7fe8b81b13/crates/cairo-lang-runner/src/casm_run/mod.rs#L79)):*
> ```XML
> 
> /// Helper object to allocate and track SHA256 states stack.
> struct SHA256ExecutionScope {
> ```

remove - and reuse the MemoryExecScope.


<!-- Sent from Reviewable.io -->

2024-04-03 11:48 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuYmWDh2gHbA88EQRRo:-NuYmWDh2gHbA88EQRRp:bydnu4) (no related file):*
@ilyalesokhin-starkware as well.

___


<!-- Sent from Reviewable.io -->

2024-04-03 12:04 UTC, ilyalesokhin-starkware commented
*[`corelib/src/sha256.cairo` line 67 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuYqDWsE2R1V5Ch2rsV:-NuYqDWsE2R1V5Ch2rsW:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/097ef0a43b05c9e1cab49264d1fbaf7fe8b81b13/corelib/src/sha256.cairo#L67)):*
> ```Cairo
>             + arr.at(len - 3).unwrap().into() * 0x10000,
>     };
>     compute_sha256_u32_array(word_arr, last, (len % 4).into())
> ```





_Suggestion:_
```Cairo
rem.into()
```


<!-- Sent from Reviewable.io -->

2024-04-03 12:06 UTC, ilyalesokhin-starkware commented
*[`corelib/src/sha256.cairo` line 99 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuYqdyoAoEznCt1Yztn:-NuYqdyp3XoMvTYM26H3:b-kf3o07) ([raw file](https://github.com/starkware-libs/cairo/blob/097ef0a43b05c9e1cab49264d1fbaf7fe8b81b13/corelib/src/sha256.cairo#L99)):*
> ```Cairo
> 
> /// Appends `count` zeros to the array.
> fn append_zeros(ref arr: Array<u32>, count: felt252) {
> ```

why not use a loop?



_Code quote:_
```Cairo
fn append_zeros(ref arr: Array<u32>, count: felt252) {
```


<!-- Sent from Reviewable.io -->

2024-04-03 12:08 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 596 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuYr2b-6j2ga_fneoy6:-NuYr2b-6j2ga_fneoy7:bqv3vjv) ([raw file](https://github.com/starkware-libs/cairo/blob/097ef0a43b05c9e1cab49264d1fbaf7fe8b81b13/crates/cairo-lang-runner/src/casm_run/mod.rs#L596)):*
> ```XML
> 
>     /// Returns the array of integer values pointed to by the next address in the buffer and
>     /// with a fixed size and advances the buffer by one. Will fail if the next value is not
> ```

what is next_value?



_Code quote:_
```XML
next value
```


<!-- Sent from Reviewable.io -->

2024-04-03 12:13 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 712 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuYrkS78ZrlG-U5DDRz:-NuYrkS78ZrlG-U5DDS-:bcydzvf) ([raw file](https://github.com/starkware-libs/cairo/blob/097ef0a43b05c9e1cab49264d1fbaf7fe8b81b13/crates/cairo-lang-runner/src/casm_run/mod.rs#L712)):*
> ```XML
>                 sha_256_process_block(
>                     gas_counter,
>                     system_buffer.next_fixed_size_arr(8)?,
> ```

don't you have another level of indirection here?



_Code quote:_
```XML
  system_buffer.next_fixed_size_arr(8)?,
```


<!-- Sent from Reviewable.io -->

2024-04-03 12:22 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1312 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuYu4dN1PMwKsiGiO9F:-NuYu4dO3zt8jCZ4TP-H:b96f5nq) ([raw file](https://github.com/starkware-libs/cairo/blob/097ef0a43b05c9e1cab49264d1fbaf7fe8b81b13/crates/cairo-lang-runner/src/casm_run/mod.rs#L1312)):*
> ```XML
>     )
>     .unwrap();
>     let mut state_as_words: [u32; 8] = prev_state
> ```

What is the endianness of the state?



_Code quote:_
```XML
state_as_words
```


<!-- Sent from Reviewable.io -->

2024-04-03 12:25 UTC, ilyalesokhin-starkware reviewed
> Reviewed 5 of 17 files at r1, 2 of 4 files at r5, 4 of 9 files at r9, 2 of 3 files at r10, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: all files reviewed, 6 unresolved discussions (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-04-03 12:51 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: 16 of 18 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/src/sha256.cairo` line 67 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuYqDWsE2R1V5Ch2rsV:-NuYymeqDvpdFkvjHDCJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/097ef0a43b05c9e1cab49264d1fbaf7fe8b81b13/corelib/src/sha256.cairo#L67)):*
> ```Cairo
>             + arr.at(len - 3).unwrap().into() * 0x10000,
>     };
>     compute_sha256_u32_array(word_arr, last, (len % 4).into())
> ```

Done.
___
*[`corelib/src/sha256.cairo` line 99 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuYqdyoAoEznCt1Yztn:-NuYyXPB7zTgswx7-4x9:b6ov7sa) ([raw file](https://github.com/starkware-libs/cairo/blob/097ef0a43b05c9e1cab49264d1fbaf7fe8b81b13/corelib/src/sha256.cairo#L99)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why not use a loop?
</blockquote></details>

more efficient (~128 per function call)
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 79 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuYfnvL6RSedAwvebuX:-NuYyo9J4-NPlgzTPEvJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/097ef0a43b05c9e1cab49264d1fbaf7fe8b81b13/crates/cairo-lang-runner/src/casm_run/mod.rs#L79)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove - and reuse the MemoryExecScope.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 596 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuYr2b-6j2ga_fneoy6:-NuYzDM9EuRXkWSd7SZ3:bw32b4o) ([raw file](https://github.com/starkware-libs/cairo/blob/097ef0a43b05c9e1cab49264d1fbaf7fe8b81b13/crates/cairo-lang-runner/src/casm_run/mod.rs#L596)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what is next_value?
</blockquote></details>

the pointer we read was supposed to be the address
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 712 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuYrkS78ZrlG-U5DDRz:-NuYzRzt2cCad-DpdiMf:bogfg42) ([raw file](https://github.com/starkware-libs/cairo/blob/097ef0a43b05c9e1cab49264d1fbaf7fe8b81b13/crates/cairo-lang-runner/src/casm_run/mod.rs#L712)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

don't you have another level of indirection here?
</blockquote></details>

what do you mean by indirection?
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1312 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuYu4dN1PMwKsiGiO9F:-NuYzbfv9JImCo5PINCs:b-ptd3k3) ([raw file](https://github.com/starkware-libs/cairo/blob/097ef0a43b05c9e1cab49264d1fbaf7fe8b81b13/crates/cairo-lang-runner/src/casm_run/mod.rs#L1312)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What is the endianness of the state?
</blockquote></details>

big-endian (this is true for all sha256) 


<!-- Sent from Reviewable.io -->

2024-04-03 12:59 UTC, ilyalesokhin-starkware commented
*[`corelib/src/sha256.cairo` line 99 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuYqdyoAoEznCt1Yztn:-NuZ1d3k3ITVOEkE2QEx:bqs2bbu) ([raw file](https://github.com/starkware-libs/cairo/blob/097ef0a43b05c9e1cab49264d1fbaf7fe8b81b13/corelib/src/sha256.cairo#L99)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

more efficient (~128 per function call)
</blockquote></details>

Maybe unroll it 4 or 8 times instead of 16?


<!-- Sent from Reviewable.io -->

2024-04-03 13:00 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 712 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuYrkS78ZrlG-U5DDRz:-NuZ1vy118KGh9qfJek6:b-f65cfk) ([raw file](https://github.com/starkware-libs/cairo/blob/097ef0a43b05c9e1cab49264d1fbaf7fe8b81b13/crates/cairo-lang-runner/src/casm_run/mod.rs#L712)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

what do you mean by indirection?
</blockquote></details>

I think then name is confusing, you are not reading a fixed size array.
you are reading a box of a fixed size array


<!-- Sent from Reviewable.io -->

2024-04-03 13:04 UTC, ilyalesokhin-starkware reviewed
> Reviewed 1 of 17 files at r1, 2 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: 16 of 18 files reviewed, 4 unresolved discussions (waiting on @orizi and @TomerStarkware)

___
*[`corelib/src/sha256.cairo` line 99 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuYqdyoAoEznCt1Yztn:-NuZ2sgODbd-7vr1q1Ld:b7vcu8i) ([raw file](https://github.com/starkware-libs/cairo/blob/097ef0a43b05c9e1cab49264d1fbaf7fe8b81b13/corelib/src/sha256.cairo#L99)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Maybe unroll it 4 or 8 times instead of 16?
</blockquote></details>

I guess we can optimze it later


<!-- Sent from Reviewable.io -->

2024-04-03 13:12 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: 16 of 18 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`corelib/src/sha256.cairo` line 99 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuYqdyoAoEznCt1Yztn:-NuZ4dUt0N0su40GhPNX:b-advdbg) ([raw file](https://github.com/starkware-libs/cairo/blob/097ef0a43b05c9e1cab49264d1fbaf7fe8b81b13/corelib/src/sha256.cairo#L99)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I guess we can optimze it later
</blockquote></details>

so leave it as is?
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 712 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuYrkS78ZrlG-U5DDRz:-NuZ4IY3DO4Ggn9fDNQH:bvpbscc) ([raw file](https://github.com/starkware-libs/cairo/blob/097ef0a43b05c9e1cab49264d1fbaf7fe8b81b13/crates/cairo-lang-runner/src/casm_run/mod.rs#L712)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think then name is confusing, you are not reading a fixed size array.
you are reading a box of a fixed size array
</blockquote></details>

changed to next_fixed_size_arr_pointer 


<!-- Sent from Reviewable.io -->

2024-04-03 13:19 UTC, ilyalesokhin-starkware commented
*[`corelib/src/sha256.cairo` line 99 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuYqdyoAoEznCt1Yztn:-NuZ6Jbn3gVPgdGkwE2R:b2nign6) ([raw file](https://github.com/starkware-libs/cairo/blob/097ef0a43b05c9e1cab49264d1fbaf7fe8b81b13/corelib/src/sha256.cairo#L99)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

so leave it as is?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2024-04-03 13:20 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: 16 of 18 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1637 at r15](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuZ69ST9vouvhqd-8kn:-NuZ69ST9vouvhqd-8ko:brcat3f) ([raw file](https://github.com/starkware-libs/cairo/blob/2150be3e9d12525dc6492dc966f67ed567c56460/crates/cairo-lang-runner/src/casm_run/mod.rs#L1637)):*
> ```XML
>     }
>     exec_scopes.get_mut_ref::<MemoryExecScope>(NAME)
> }
> ```

instead - just extract a function for allocating a buffer of a certain size,
returning its beginning - as you do exactly that in both cases.



_Code quote:_
```XML
/// Returns the `MemoryExecScope` managing the pointers.
/// The first call to this function will create the scope, and subsequent calls will return it.
fn get_memory_exec_scope<'s>(
    exec_scopes: &'s mut ExecutionScopes,
    vm: &mut VirtualMachine,
) -> Result<&'s mut MemoryExecScope, HintError> {
    const NAME: &str = "memory_exec_scope";
    if exec_scopes.get_ref::<MemoryExecScope>(NAME).is_err() {
        exec_scopes.assign_or_update_variable(
            NAME,
            Box::new(MemoryExecScope { next_address: vm.add_memory_segment() }),
        );
    }
    exec_scopes.get_mut_ref::<MemoryExecScope>(NAME)
}
```


<!-- Sent from Reviewable.io -->

2024-04-03 14:23 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: 16 of 18 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1637 at r15](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuZ69ST9vouvhqd-8kn:-NuZKvxXDV-D74_wPs_o:bb7f2mf) ([raw file](https://github.com/starkware-libs/cairo/blob/2150be3e9d12525dc6492dc966f67ed567c56460/crates/cairo-lang-runner/src/casm_run/mod.rs#L1637)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

instead - just extract a function for allocating a buffer of a certain size,
returning its beginning - as you do exactly that in both cases.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-04-03 14:44 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: 17 of 18 files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1638 at r16](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuZPRkp-Nv1NvFcR6Iy:-NuZPRkp-Nv1NvFcR6Iz:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/e727a7187ccc41b721c750e467908495c467e4ce/crates/cairo-lang-runner/src/casm_run/mod.rs#L1638)):*
> ```XML
>     let next_address = scope.next_address;
>     scope.next_address += size;
>     Ok(next_address)
> ```

.



_Suggestion:_
```XML
    let updated = scope.next_address + size;
    Ok(std::mem::replace(&mut scope.next_address, updated))
```


<!-- Sent from Reviewable.io -->

2024-04-03 14:55 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5348)* status: 17 of 18 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1623 at r16](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuZOv37E1jrYd6lHUXA:-NuZR4HP898nWZNTu5Yf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e727a7187ccc41b721c750e467908495c467e4ce/crates/cairo-lang-runner/src/casm_run/mod.rs#L1623)):*
> ```XML
> /// Returns the `MemoryExecScope` managing the pointers.
> /// The first call to this function will create the scope, and subsequent calls will return it.
> fn get_memory_pointer(
> ```

Done.
___
*[`crates/cairo-lang-runner/src/casm_run/mod.rs` line 1638 at r16](https://reviewable.io/reviews/starkware-libs/cairo/5348#-NuZPRkp-Nv1NvFcR6Iy:-NuZRHYd0eRQPk2gMy4D:b-clztij) ([raw file](https://github.com/starkware-libs/cairo/blob/e727a7187ccc41b721c750e467908495c467e4ce/crates/cairo-lang-runner/src/casm_run/mod.rs#L1638)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done, but + does return result


<!-- Sent from Reviewable.io -->

2024-04-04 07:51 UTC, merged