Added support for more ranges for div-rem.
starkware-libs/cairo pull request #5389
Opened 2024-04-09 18:06 UTC by orizi

**Stack**:
- #5388
- #5387

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-04-10 06:25 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 236 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5389#-Nv5fYEW2NE-9gmh5i0Q:-Nv5fYEW2NE-9gmh5i0R:b-yw357q) ([raw file](https://github.com/starkware-libs/cairo/blob/86989602732187fb701f9860e4174c3cc064beb4/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L236)):*
> ```XML
>         let q_max = (&lhs.upper - 1) / &rhs.lower;
>         let u128_limit = BigInt::one().shl(128);
>         if q_max > u128_limit || rhs.upper > u128_limit || lhs.upper > u128_limit {
> ```

Where are those limitations coming from?



_Code quote:_
```XML
rhs.upper > u128_limit || lhs.upper > u128_limit
```


<!-- Sent from Reviewable.io -->

2024-04-10 06:34 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 236 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5389#-Nv5fYEW2NE-9gmh5i0Q:-Nv5haOaAwn1pu9b9FPF:bjlv9rd) ([raw file](https://github.com/starkware-libs/cairo/blob/86989602732187fb701f9860e4174c3cc064beb4/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L236)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Where are those limitations coming from?
</blockquote></details>

is
BoundendInt<2, 2*129> impossible?


<!-- Sent from Reviewable.io -->

2024-04-10 09:54 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5389)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 236 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5389#-Nv5fYEW2NE-9gmh5i0Q:-Nv6GFnVBNybLii7dpST:b6vzi7i) ([raw file](https://github.com/starkware-libs/cairo/blob/86989602732187fb701f9860e4174c3cc064beb4/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L236)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is
BoundendInt<2, 2*129> impossible?
</blockquote></details>

removed the condition on the lhs.


<!-- Sent from Reviewable.io -->

2024-04-10 14:33 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5389#-Nv7QP357osBU9yraeE7:-Nv7QP357osBU9yraeE8:b-uxsmqo) ([raw file](https://github.com/starkware-libs/cairo/blob/fb05129048bccd1b53c758f2c0b42a62518e60c5/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L95)):*
> ```XML
>         BoundedIntDivRemAlgorithm::KnownSmallRhs => {
>             // For this case `q < q_max <= 2**128` and `b < rhs.upper` therefore
>             // `q * b < 2**128 * rhs.upper < prime`.
> ```

maybe you should rename a and b to lhs and rhs?



_Code quote:_
```XML
            // For this case `q < q_max <= 2**128` and `b < rhs.upper` therefore
            // `q * b < 2**128 * rhs.upper < prime`.
```


<!-- Sent from Reviewable.io -->

2024-04-10 14:35 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5389#-Nv7Qezf0aTPp5jZxhVR:-Nv7Qezf0aTPp5jZxhVS:b1p4pop) ([raw file](https://github.com/starkware-libs/cairo/blob/fb05129048bccd1b53c758f2c0b42a62518e60c5/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L95)):*
> ```XML
>         BoundedIntDivRemAlgorithm::KnownSmallRhs => {
>             // For this case `q < q_max <= 2**128` and `b < rhs.upper` therefore
>             // `q * b < 2**128 * rhs.upper < prime`.
> ```

don't you need
q * b + lhs.upper -  1  < prime 
?



_Code quote:_
```XML
q * b < 2**128 * rhs.upper < prime
```


<!-- Sent from Reviewable.io -->

2024-04-10 15:22 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5389)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5389#-Nv7QP357osBU9yraeE7:-Nv7aVClEc6mWf6PGjai:b-917wmc) ([raw file](https://github.com/starkware-libs/cairo/blob/fb05129048bccd1b53c758f2c0b42a62518e60c5/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L95)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

maybe you should rename a and b to lhs and rhs?
</blockquote></details>

would be confusing with the ranges.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5389#-Nv7Qezf0aTPp5jZxhVR:-Nv7aYdB0nnkaUNEh89d:b-6c8sub) ([raw file](https://github.com/starkware-libs/cairo/blob/fb05129048bccd1b53c758f2c0b42a62518e60c5/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L95)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

don't you need
q * b + lhs.upper -  1  < prime 
?
</blockquote></details>

that is validated in the sierra declaration area - isn't it?


<!-- Sent from Reviewable.io -->

2024-04-14 07:49 UTC, ilyalesokhin-starkware commented
*[`corelib/src/test/integer_test.cairo` line 1955 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQ_GVf1FKT3ftT971V:-NvQ_GVf1FKT3ftT971W:bebr47a) ([raw file](https://github.com/starkware-libs/cairo/blob/00a2ad3b7b26deb942214199f8ec7e3eba0e933e/corelib/src/test/integer_test.cairo#L1955)):*
> ```Cairo
> 
>     trait IgnoreNext;
>     impl ImplIgnoreNext of IgnoreNext;
> ```

can you document that, I have no idea what that is.



_Code quote:_
```Cairo
    trait IgnoreNext;
    impl ImplIgnoreNext of IgnoreNext;
```


<!-- Sent from Reviewable.io -->

2024-04-14 07:59 UTC, ilyalesokhin-starkware reviewed
> Reviewed 4 of 8 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5389)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-04-14 08:05 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQctuJ5VKkfDvgfFWe:-NvQctuJ5VKkfDvgfFWf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/00a2ad3b7b26deb942214199f8ec7e3eba0e933e/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L94)):*
> ```XML
>     match alg {
>         BoundedIntDivRemAlgorithm::KnownSmallRhs => {
>             // For this case `q < q_max <= 2**128` and `b < rhs.upper` therefore
> ```





_Suggestion:_
```XML
q <= q_max < 2**128
```


<!-- Sent from Reviewable.io -->

2024-04-14 08:07 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5389#-Nv7Qezf0aTPp5jZxhVR:-NvQd6SZA_fGKLKNaF4t:b-ajdinw) ([raw file](https://github.com/starkware-libs/cairo/blob/4fccb64c765f63ffddf148405369884b72c728ef/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L95)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

that is validated in the sierra declaration area - isn't it?
</blockquote></details>

The comment as is does not seem to be enough.
it works because:


q * b + r < 2**128 * (rhs.upper-1) +  2**128 <  2**128 * rhs.upper  < prime


<!-- Sent from Reviewable.io -->

2024-04-14 08:09 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 137 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQdss_1vB-m-4EGLR9:-NvQdss_1vB-m-4EGLRA:b-utylyo) ([raw file](https://github.com/starkware-libs/cairo/blob/00a2ad3b7b26deb942214199f8ec7e3eba0e933e/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L137)):*
> ```XML
>     }
>     casm_build_extend! {casm_builder,
>         // Check that `a = q * b + r`. Both hands are in the range [0, q_max * rhs.upper).
> ```

Where is this checked? above the comment?



_Code quote:_
```XML
     // Check that `a = q * b + r`. Both hands are in the range [0, q_max * rhs.upper).
```


<!-- Sent from Reviewable.io -->

2024-04-14 08:36 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5389)* status: 2 of 8 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/test/integer_test.cairo` line 1955 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQ_GVf1FKT3ftT971V:-NvQdJsPC2mNaaZX95D_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/00a2ad3b7b26deb942214199f8ec7e3eba0e933e/corelib/src/test/integer_test.cairo#L1955)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you document that, I have no idea what that is.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5389#-Nv7Qezf0aTPp5jZxhVR:-NvQjkPsDLml8kcWI1xq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4fccb64c765f63ffddf148405369884b72c728ef/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L95)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The comment as is does not seem to be enough.
it works because:


q * b + r < 2**128 * (rhs.upper-1) +  2**128 <  2**128 * rhs.upper  < prime
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQctuJ5VKkfDvgfFWe:-NvQdmww6xCBggVVX9Ua:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/00a2ad3b7b26deb942214199f8ec7e3eba0e933e/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L94)):*
> ```XML
>     match alg {
>         BoundedIntDivRemAlgorithm::KnownSmallRhs => {
>             // For this case `q < q_max <= 2**128` and `b < rhs.upper` therefore
> ```

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 137 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQdss_1vB-m-4EGLR9:-NvQfXOf7kVujeJC187J:bk3ag8w) ([raw file](https://github.com/starkware-libs/cairo/blob/00a2ad3b7b26deb942214199f8ec7e3eba0e933e/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L137)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Where is this checked? above the comment?
</blockquote></details>

updated doc.


<!-- Sent from Reviewable.io -->

2024-04-14 08:43 UTC, ilyalesokhin-starkware requested changes
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5389)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned.rs` line 144 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQlM-l9xb534EiXznA:-NvQlM-l9xb534EiXznB:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/00a2ad3b7b26deb942214199f8ec7e3eba0e933e/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned.rs#L144)):*
> ```XML
>         UintConcrete::Divmod(_) => bounded::build_div_rem(
>             builder,
>             &Range::half_open(0, LIMIT),
> ```





_Suggestion:_
```XML
Range::closed(0, LIMIT)
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQlTlsEDRDChtwAbXA:-NvQlTlsEDRDChtwAbXB:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/00a2ad3b7b26deb942214199f8ec7e3eba0e933e/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs#L27)):*
> ```XML
>         Uint128Concrete::Divmod(_) => bounded::build_div_rem(
>             builder,
>             &Range::half_open(0, u128::MAX),
> ```





_Suggestion:_
```XML
&Range::closed(0, u128::MAX),
```


<!-- Sent from Reviewable.io -->

2024-04-14 08:44 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 72 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQlwJd1GuY9o96X10A:-NvQlwJd1GuY9o96X10B:b-acim30) ([raw file](https://github.com/starkware-libs/cairo/blob/3cd9dc52c8815476cc17f41fc7ac714b93e87676/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L72)):*
> ```XML
>         hint DivMod { lhs: a, rhs: b } into { quotient: q, remainder: r };
>     };
>     // Adding under condition for divmod for u128 compatibility.
> ```

I don't understand the comment.



_Code quote:_
```XML
// Adding under condition for divmod for u128 compatibility.
```


<!-- Sent from Reviewable.io -->

2024-04-14 08:46 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 53 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQmBw-DiatXXcrzIAc:-NvQmBw-DiatXXcrzIAd:biu8085) ([raw file](https://github.com/starkware-libs/cairo/blob/3cd9dc52c8815476cc17f41fc7ac714b93e87676/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L53)):*
> ```XML
>     let mut casm_builder = CasmBuilder::default();
>     add_input_variables! {casm_builder,
>         buffer(2) range_check;
> ```

Is 2 really the worst case?



_Code quote:_
```XML
buffer(2)
```


<!-- Sent from Reviewable.io -->

2024-04-14 08:54 UTC, ilyalesokhin-starkware commented
*[`corelib/src/test/integer_test.cairo` line 1956 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQo2O15ErwV6BAZI2z:-NvQo2O15ErwV6BAZI3-:b-9exaak) ([raw file](https://github.com/starkware-libs/cairo/blob/3cd9dc52c8815476cc17f41fc7ac714b93e87676/corelib/src/test/integer_test.cairo#L1956)):*
> ```Cairo
>     /// A trait used for Sierra extern functions to ignore the following params in when actually
>     /// generating Sierra code, while still being able to use the parameters in high level cairo
>     /// code.
> ```

I still don't get it, but maybe we should do it in a separate PR



_Suggestion:_
```Cairo
    /// A trait used for Sierra extern functions to ignore the following params when actually
    /// generating Sierra code, while still being able to use the parameters in high level cairo
    /// code.
```


<!-- Sent from Reviewable.io -->

2024-04-14 08:56 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQoYx_AcL6TujJYJor:-NvQoYx_AcL6TujJYJos:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3cd9dc52c8815476cc17f41fc7ac714b93e87676/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L73)):*
> ```XML
>     };
>     // Adding under condition for divmod for u128 compatibility.
>     if !matches!(alg, BoundedIntDivRemAlgorithm::KnownSmallRhs) {
> ```





_Suggestion:_
```XML
if matches!(alg, BoundedIntDivRemAlgorithm::KnownSmallQuotient | BoundedIntDivRemAlgorithm::KnownSmallLhs) {
```


<!-- Sent from Reviewable.io -->

2024-04-14 08:57 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQoYx_AcL6TujJYJor:-NvQojDS1OB5-tLzbTmp:bcsmlim) ([raw file](https://github.com/starkware-libs/cairo/blob/3cd9dc52c8815476cc17f41fc7ac714b93e87676/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L73)):*
> ```XML
>     };
>     // Adding under condition for divmod for u128 compatibility.
>     if !matches!(alg, BoundedIntDivRemAlgorithm::KnownSmallRhs) {
> ```

Actually, you do the same checks in all algorithms, just in a different place? 
why?


<!-- Sent from Reviewable.io -->

2024-04-14 08:58 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 91 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQozTlERhjGvMlXAIY:-NvQozTlERhjGvMlXAIZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3cd9dc52c8815476cc17f41fc7ac714b93e87676/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L91)):*
> ```XML
>     }
> 
>     // Validating `q * (b + 1) < prime` and therefore `q * b + q < prime`.
> ```





_Suggestion:_
```XML
q * b + r < prime
```


<!-- Sent from Reviewable.io -->

2024-04-14 08:59 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 91 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQozTlERhjGvMlXAIY:-NvQp5Qw4QynmtSevJKT:b-9bnqbr) ([raw file](https://github.com/starkware-libs/cairo/blob/3cd9dc52c8815476cc17f41fc7ac714b93e87676/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L91)):*
> ```XML
>     }
> 
>     // Validating `q * (b + 1) < prime` and therefore `q * b + q < prime`.
> ```

actually this is not implied.

why do we care about `q * b + q < prime`?


<!-- Sent from Reviewable.io -->

2024-04-14 09:14 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5389)* status: 3 of 8 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQoYx_AcL6TujJYJor:-NvQpErK2x71Vh-oEzOt:b-pgpvh5) ([raw file](https://github.com/starkware-libs/cairo/blob/3cd9dc52c8815476cc17f41fc7ac714b93e87676/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L73)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Actually, you do the same checks in all algorithms, just in a different place? 
why?
</blockquote></details>

for u128 compatibility - this is a merge of 2 algorithms in one place.
the algorithm of u128_div_rem and the algorithm of u*_div_rem.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 91 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQozTlERhjGvMlXAIY:-NvQpa2q2Z4z49TmP7qS:bkb9jhv) ([raw file](https://github.com/starkware-libs/cairo/blob/3cd9dc52c8815476cc17f41fc7ac714b93e87676/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L91)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

actually this is not implied.

why do we care about `q * b + q < prime`?
</blockquote></details>

It isn't implied - fixing again.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned.rs` line 144 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQlM-l9xb534EiXznA:-NvQsOthE4QEPRQg9VDg:b-4s7byh) ([raw file](https://github.com/starkware-libs/cairo/blob/00a2ad3b7b26deb942214199f8ec7e3eba0e933e/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned.rs#L144)):*
> ```XML
>         UintConcrete::Divmod(_) => bounded::build_div_rem(
>             builder,
>             &Range::half_open(0, LIMIT),
> ```

why closed?
[0, 2^128)
[1, 2^128)
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQlTlsEDRDChtwAbXA:-NvQsZAkEAdazOR21q8-:b-7jl271) ([raw file](https://github.com/starkware-libs/cairo/blob/00a2ad3b7b26deb942214199f8ec7e3eba0e933e/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs#L27)):*
> ```XML
>         Uint128Concrete::Divmod(_) => bounded::build_div_rem(
>             builder,
>             &Range::half_open(0, u128::MAX),
> ```

same.


<!-- Sent from Reviewable.io -->

2024-04-14 09:21 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQoYx_AcL6TujJYJor:-NvQtaixEC0EK9E9FQ4x:b-r7kp2a) ([raw file](https://github.com/starkware-libs/cairo/blob/3cd9dc52c8815476cc17f41fc7ac714b93e87676/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L73)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

for u128 compatibility - this is a merge of 2 algorithms in one place.
the algorithm of u128_div_rem and the algorithm of u*_div_rem.
</blockquote></details>

Do you mean for backward compatabilty with the existing u128_div_rem libfunc? 


<!-- Sent from Reviewable.io -->

2024-04-14 09:23 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5389)* status: 3 of 8 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`corelib/src/test/integer_test.cairo` line 1956 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQo2O15ErwV6BAZI2z:-NvQskes8LYzwgVBtdoK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3cd9dc52c8815476cc17f41fc7ac714b93e87676/corelib/src/test/integer_test.cairo#L1956)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I still don't get it, but maybe we should do it in a separate PR
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 53 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQmBw-DiatXXcrzIAc:-NvQsllG4oi0v62O6wVT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3cd9dc52c8815476cc17f41fc7ac714b93e87676/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L53)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Is 2 really the worst case?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 72 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQlwJd1GuY9o96X10A:-NvQup1I1mtuD7NCUi61:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3cd9dc52c8815476cc17f41fc7ac714b93e87676/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L72)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't understand the comment.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQoYx_AcL6TujJYJor:-NvQun9j651OASjwkch9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3cd9dc52c8815476cc17f41fc7ac714b93e87676/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L73)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Do you mean for backward compatabilty with the existing u128_div_rem libfunc?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-14 09:25 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned.rs` line 144 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQlM-l9xb534EiXznA:-NvQvG3d8Bb7oUlFZAGT:bipge3c) ([raw file](https://github.com/starkware-libs/cairo/blob/00a2ad3b7b26deb942214199f8ec7e3eba0e933e/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned.rs#L144)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why closed?
[0, 2^128)
[1, 2^128)
</blockquote></details>

how do you store 2^128 in a u128?


<!-- Sent from Reviewable.io -->

2024-04-14 09:26 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQlTlsEDRDChtwAbXA:-NvQvMO69dZtLRIlxY7M:bfo514m) ([raw file](https://github.com/starkware-libs/cairo/blob/00a2ad3b7b26deb942214199f8ec7e3eba0e933e/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs#L27)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

same.
</blockquote></details>

u128::MAX = 2^128 -1, right?


<!-- Sent from Reviewable.io -->

2024-04-14 09:26 UTC, ilyalesokhin-starkware reviewed
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5389)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)



<!-- Sent from Reviewable.io -->

2024-04-14 09:28 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5389)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned.rs` line 144 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQlM-l9xb534EiXznA:-NvQvdL3AUXdCcC2PsHL:bvgsbum) ([raw file](https://github.com/starkware-libs/cairo/blob/00a2ad3b7b26deb942214199f8ec7e3eba0e933e/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned.rs#L144)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

how do you store 2^128 in a u128?
</blockquote></details>

the limit here is for smaller types - so it is half closed.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvQlTlsEDRDChtwAbXA:-NvQvjdu8qSU5ks6iyYe:bphutd7) ([raw file](https://github.com/starkware-libs/cairo/blob/00a2ad3b7b26deb942214199f8ec7e3eba0e933e/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs#L27)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

u128::MAX = 2^128 -1, right?
</blockquote></details>

good catch - fixing.


<!-- Sent from Reviewable.io -->

2024-04-14 10:31 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 101 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvR9JVJADb5Tl4xcQ-O:-NvR9JVJADb5Tl4xcQ-P:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/824c02e9fe5fd29611f8e61d2135da98ad88c4de/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L101)):*
> ```XML
>     match alg {
>         BoundedIntDivRemAlgorithm::KnownSmallRhs => {
>             // For this case `q + 1 < q_max + 1 <= 2**128` and `b < rhs.upper` therefore
> ```





_Suggestion:_
```XML
q + 1 <= q_max + 1 <= 2**128
```


<!-- Sent from Reviewable.io -->

2024-04-14 10:37 UTC, ilyalesokhin-starkware reviewed
> Reviewed 1 of 8 files at r1, 1 of 3 files at r4, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5389)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-04-14 10:50 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5389)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 101 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvR9JVJADb5Tl4xcQ-O:-NvRDZHU7d2aW3ZXgXHX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/824c02e9fe5fd29611f8e61d2135da98ad88c4de/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L101)):*
> ```XML
>     match alg {
>         BoundedIntDivRemAlgorithm::KnownSmallRhs => {
>             // For this case `q + 1 < q_max + 1 <= 2**128` and `b < rhs.upper` therefore
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-04-14 10:57 UTC, ilyalesokhin-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5389)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 121 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvRFGJW3UA9sArM2Sa4:-NvRFGJW3UA9sArM2Sa5:bwx3qbx) ([raw file](https://github.com/starkware-libs/cairo/blob/f4c531b127443f44f71e94eacce0db1c87278cb8/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L121)):*
> ```XML
>                 // Since we know that both `b` and `q` are less than 2**128, if we can show that
>                 // `b` or `q` is less than `lhs_upper_sqrt`, then we can show that
>                 // `(q + 1) * b <= (lhs_upper_sqrt + 1) * 2**128 < prime`.
> ```

what about the case where b < (lhs_upper_sqrt + 1)?



_Code quote:_
```XML
// `(q + 1) * b <= (lhs_upper_sqrt + 1) * 2**128 < prime`.
```


<!-- Sent from Reviewable.io -->

2024-04-14 11:02 UTC, ilyalesokhin-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5389)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 121 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvRFGJW3UA9sArM2Sa4:-NvRFzTM5q4tv5wN62Pc:bapdff) ([raw file](https://github.com/starkware-libs/cairo/blob/f4c531b127443f44f71e94eacce0db1c87278cb8/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L121)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what about the case where b < (lhs_upper_sqrt + 1)?
</blockquote></details>

(q + 1) * b <= 2**128 * b


<!-- Sent from Reviewable.io -->

2024-04-14 11:02 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 121 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvRFGJW3UA9sArM2Sa4:-NvRGMlDBGSGt8F4EMn1:b-e6kxdu) ([raw file](https://github.com/starkware-libs/cairo/blob/f4c531b127443f44f71e94eacce0db1c87278cb8/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L121)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

(q + 1) * b <= 2**128 * b
</blockquote></details>

I guess it works since q+1 <= 2**128, right?


<!-- Sent from Reviewable.io -->

2024-04-14 11:28 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5389)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 121 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvRFGJW3UA9sArM2Sa4:-NvRMEr00vnsAFWhunel:b-rvu2lx) ([raw file](https://github.com/starkware-libs/cairo/blob/f4c531b127443f44f71e94eacce0db1c87278cb8/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L121)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I guess it works since q+1 <= 2**128, right?
</blockquote></details>

Some further doc fixes - hope it is clear enough now.


<!-- Sent from Reviewable.io -->

2024-04-14 11:34 UTC, ilyalesokhin-starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5389)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 118 at r9](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvRNku14PFFxA3p27zG:-NvRNku14PFFxA3p27zH:bq20uhy) ([raw file](https://github.com/starkware-libs/cairo/blob/adb2930fbfed6d8cf63af13adc6ef3e5bdf7a5db/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L118)):*
> ```XML
>             let b_or_q_bound_rc_value = b_or_q_bound_rc_value.unwrap();
>             casm_build_extend! {casm_builder,
>                 // For this case we know that `(lhs_upper_sqrt + 1) * 2**128 < prime`.
> ```

You've removed the upper, right?



_Suggestion:_
```XML
lhs_sqrt + 1
```
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 126 at r9](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvRNfL0-DchwMuGS52k:-NvRNfL0-DchwMuGS52l:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/adb2930fbfed6d8cf63af13adc6ef3e5bdf7a5db/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L126)):*
> ```XML
>                 // min(q, b) * max(q, b) + max(q, b) == (min(q, b) + 1) * max(q, b)
>                 // ```
>                 // Since `b * q < lhs.upper` `min(b, q) <= sqrt(lhs.upper)`.
> ```





_Suggestion:_
```XML
Since `b * q < lhs.upper`, `min(b, q) <= sqrt(lhs.upper)`.
```


<!-- Sent from Reviewable.io -->

2024-04-14 11:44 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5389)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 118 at r9](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvRNku14PFFxA3p27zG:-NvRPlOp5xRINUb7V4ui:bc94wl7) ([raw file](https://github.com/starkware-libs/cairo/blob/adb2930fbfed6d8cf63af13adc6ef3e5bdf7a5db/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L118)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

You've removed the upper, right?
</blockquote></details>

it is still the upper bound.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 126 at r9](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvRNfL0-DchwMuGS52k:-NvRPu-lEHv_S6mEb8gI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/adb2930fbfed6d8cf63af13adc6ef3e5bdf7a5db/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L126)):*
> ```XML
>                 // min(q, b) * max(q, b) + max(q, b) == (min(q, b) + 1) * max(q, b)
>                 // ```
>                 // Since `b * q < lhs.upper` `min(b, q) <= sqrt(lhs.upper)`.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-04-14 11:47 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 118 at r9](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvRNku14PFFxA3p27zG:-NvRQb3_7gvLgBWPvPFs:bioy8n7) ([raw file](https://github.com/starkware-libs/cairo/blob/adb2930fbfed6d8cf63af13adc6ef3e5bdf7a5db/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L118)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it is still the upper bound.
</blockquote></details>

maybe
sqrt(lhs_upper)

Like below?


<!-- Sent from Reviewable.io -->

2024-04-14 11:47 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 118 at r9](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvRNku14PFFxA3p27zG:-NvRQiyODPWiUhySyVK8:b-nqu4cf) ([raw file](https://github.com/starkware-libs/cairo/blob/adb2930fbfed6d8cf63af13adc6ef3e5bdf7a5db/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L118)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

maybe
sqrt(lhs_upper)

Like below?
</blockquote></details>

sqrt(lhs.upper)


<!-- Sent from Reviewable.io -->

2024-04-14 11:48 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs` line 118 at r9](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvRNku14PFFxA3p27zG:-NvRQr3aDy52vj0Y1CbN:b-qvql2o) ([raw file](https://github.com/starkware-libs/cairo/blob/adb2930fbfed6d8cf63af13adc6ef3e5bdf7a5db/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs#L118)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

sqrt(lhs.upper)
</blockquote></details>

nvm, I see that you refer to a variable.


<!-- Sent from Reviewable.io -->

2024-04-14 11:48 UTC, ilyalesokhin-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5389#-:-NvRQzQT0n5hHyzY3fDX:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-04-14 11:49 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 252 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvRR5RT7ykLZrHAhRar:-NvRR5RT7ykLZrHAhRas:b-7wcwuj) ([raw file](https://github.com/starkware-libs/cairo/blob/3cd9dc52c8815476cc17f41fc7ac714b93e87676/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L252)):*
> ```XML
>         }
>         let mut r = lhs.upper.sqrt();
>         if &r * &r < lhs.upper {
> ```

Maybe you want to do this for lhs_max instead of lhs_upper?


<!-- Sent from Reviewable.io -->

2024-04-14 11:49 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 252 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5389#-NvRR5RT7ykLZrHAhRar:-NvRRFgAAo0n1Sqo6CZS:b2ni8w0) ([raw file](https://github.com/starkware-libs/cairo/blob/3cd9dc52c8815476cc17f41fc7ac714b93e87676/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L252)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Maybe you want to do this for lhs_max instead of lhs_upper?
</blockquote></details>

nvm


<!-- Sent from Reviewable.io -->

2024-04-14 12:09 UTC, merged