LS: Extract and syncify Scarb invoking logic
starkware-libs/cairo pull request #5399
Opened 2024-04-10 19:25 UTC by mkaput

This is the first PR in a series of changes which goal is to rewrite the
project model and its loading. The `ScarbService` struct is meant to
eventually go. After removing some async logic, clippy forced me to
rewrite some chunks of code that would be unnecessary.

---

**Stack**:
- #5399 ⬅
- #5398

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-04-10 19:29 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5399)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @maciektr and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5399#-Nv8U3j78SS7LdTrLFoc:-Nv8U3j83ipuIa1JJoIB:b-4936qp) (no related file):*
Blocking because I haven’t tested this yet

___


<!-- Sent from Reviewable.io -->

2024-04-10 19:52 UTC, maciektr commented
*[`crates/cairo-lang-language-server/src/lib.rs` line 493 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5399#-Nv8ZHxb9xuaIrvOsjNK:-Nv8ZHxb9xuaIrvOsjNL:b-udwwmd) ([raw file](https://github.com/starkware-libs/cairo/blob/38b22977763085a62ff7117054596c84d8695fe4/crates/cairo-lang-language-server/src/lib.rs#L493)):*
> ```XML
>         let corelib_fallback = self.get_corelib_fallback_path().await;
>         if self.scarb.is_scarb_project(file_path.clone()) {
>             if self.scarb.is_scarb_found() {
> ```

Please verify if it's possible to work on `corelib` package, with Cairo-LS, without Scarb installed, as I remember this has been an issue in the past. 


<!-- Sent from Reviewable.io -->

2024-04-10 19:58 UTC, maciektr approved these changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5399)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput and @orizi)



<!-- Sent from Reviewable.io -->

2024-04-11 06:14 UTC, orizi requested changes
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5399)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-language-server/src/server/notification_sender.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5399#-NvAmhZx7VTABjTbCShq:-NvAmhZx7VTABjTbCShr:b-62ntfd) ([raw file](https://github.com/starkware-libs/cairo/blob/a3a54e883a3d12ca270d4596e741d38dcf56ae7b/crates/cairo-lang-language-server/src/server/notification_sender.rs#L12)):*
> ```XML
> #[derive(Clone)]
> pub struct Notifier {
>     client: Client,
> ```

doc member
___
*[`crates/cairo-lang-language-server/src/toolchain/scarb.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5399#-NvAmXxREyJugNS1pGdY:-NvAmXxREyJugNS1pGdZ:bo2lbgv) ([raw file](https://github.com/starkware-libs/cairo/blob/a3a54e883a3d12ca270d4596e741d38dcf56ae7b/crates/cairo-lang-language-server/src/toolchain/scarb.rs#L20)):*
> ```XML
> /// This object is small and cheap to clone, so it can be passed around freely.
> #[derive(Clone)]
> pub struct ScarbToolchain {
> ```

doc all members and functions.
___
*[`crates/cairo-lang-language-server/src/toolchain/scarb.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5399#-NvAmRKS56_t2d3uzW7A:-NvAmRKS56_t2d3uzW7B:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a3a54e883a3d12ca270d4596e741d38dcf56ae7b/crates/cairo-lang-language-server/src/toolchain/scarb.rs#L28)):*
> ```XML
>     pub fn new(notifier: &Notifier) -> Self {
>         ScarbToolchain { scarb_path_cell: Default::default(), notifier: notifier.clone() }
>     }
> ```





_Suggestion:_
```XML
    scarb_path_cell: Arc<OnceLock<Option<PathBuf>>>,
    notifier: Notifier,
}
impl ScarbToolchain {
    pub fn new(notifier: &Notifier) -> Self {
        ScarbToolchain { scarb_path_cell: Default::default(), notifier: notifier.clone() }
    }
```


<!-- Sent from Reviewable.io -->

2024-04-12 09:30 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5399)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @maciektr and @orizi)

___
*[`crates/cairo-lang-language-server/src/server/notification_sender.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5399#-NvAmhZx7VTABjTbCShq:-NvGb1wU2QmJmXiFqov4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a3a54e883a3d12ca270d4596e741d38dcf56ae7b/crates/cairo-lang-language-server/src/server/notification_sender.rs#L12)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc member
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/toolchain/scarb.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5399#-NvAmXxREyJugNS1pGdY:-NvGaON92q9KPgTdhI1v:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a3a54e883a3d12ca270d4596e741d38dcf56ae7b/crates/cairo-lang-language-server/src/toolchain/scarb.rs#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc all members and functions.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/toolchain/scarb.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5399#-NvAmRKS56_t2d3uzW7A:-NvGZCQh-a644KWTrd3B:bjleo0d) ([raw file](https://github.com/starkware-libs/cairo/blob/a3a54e883a3d12ca270d4596e741d38dcf56ae7b/crates/cairo-lang-language-server/src/toolchain/scarb.rs#L28)):*
> ```XML
>     pub fn new(notifier: &Notifier) -> Self {
>         ScarbToolchain { scarb_path_cell: Default::default(), notifier: notifier.clone() }
>     }
> ```

I've been putting a separate line everywhere in the LS (as that's generally common in Rust codebases) so I would argue against changing this, but we're getting into the heavy nitpicking area. Do you want to me to remove these in entire LS codebase?


<!-- Sent from Reviewable.io -->

2024-04-12 10:52 UTC, orizi requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5399#-:-NvGw3Um6RK8e3NJ2Inl:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-language-server/src/toolchain/scarb.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5399#-NvAmRKS56_t2d3uzW7A:-NvGvfzLDTXiRUXp7-fT:bqq6peb) ([raw file](https://github.com/starkware-libs/cairo/blob/a3a54e883a3d12ca270d4596e741d38dcf56ae7b/crates/cairo-lang-language-server/src/toolchain/scarb.rs#L28)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I've been putting a separate line everywhere in the LS (as that's generally common in Rust codebases) so I would argue against changing this, but we're getting into the heavy nitpicking area. Do you want to me to remove these in entire LS codebase?
</blockquote></details>

For the type impl I find it better (not for traits) but fine.


<!-- Sent from Reviewable.io -->

2024-04-12 13:54 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5399)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 493 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5399#-Nv8ZHxb9xuaIrvOsjNK:-NvH_AHr0IhuPxhB4i97:bfvnio4) ([raw file](https://github.com/starkware-libs/cairo/blob/38b22977763085a62ff7117054596c84d8695fe4/crates/cairo-lang-language-server/src/lib.rs#L493)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Please verify if it's possible to work on `corelib` package, with Cairo-LS, without Scarb installed, as I remember this has been an issue in the past.
</blockquote></details>

I can confirm the following cases work:
1. Custom Scarb build
2. Custom LS build with `"cairo1.enableScarb": false` and `"cairo1.languageServerExtraEnv": { "SCARB": "..." }`
3. Custom LS build with `"cairo1.enableScarb": false` (this is the case you ask for).


<!-- Sent from Reviewable.io -->

2024-04-12 15:52 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5399#-:-NvI-_ol2rqaoMWKHHPf:bnfp4nl)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @maciektr)



<!-- Sent from Reviewable.io -->

2024-04-12 16:06 UTC, merged