LS: Rewrite project file searching
starkware-libs/cairo pull request #5415
Opened 2024-04-12 16:42 UTC by mkaput

The logic for looking for the project file is not encapsulated as a
`ProjectManifestPath` struct.

This change swaps the precedence, now `cairo_project.toml` will be
recognized before `Scarb.toml` in case both files exist. This reflects
the notion that `cairo_project.toml` is something "custom" and Cairo
lang developer oriented, while Scarb is meant for regular scenarios.

2024-04-12 21:21 UTC, maciektr commented
Well, I believe that some well established Cairo projects still include both in their codebase (see https://github.com/OpenZeppelin/cairo-contracts/tree/main/src for example). Wouldn't this cause issues for users, which want to open such project and don't have the corelib copied to their machines (apart from scarb dist)? 





<!-- Sent from Reviewable.io -->

2024-04-12 21:25 UTC, maciektr approved these changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5415)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-04-14 08:01 UTC, orizi approved these changes
> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5415)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2024-04-14 08:03 UTC, orizi requested changes
> Reviewed 4 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5415)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-language-server/src/project/project_manifest_path.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5415#-NvQcJUe7cvHgNgv8O7I:-NvQcJUf7qdU3qFuaWwt:bjwl44q) ([raw file](https://github.com/starkware-libs/cairo/blob/e88e03544c2432ae498f2ab712f42950f9f12b4b/crates/cairo-lang-language-server/src/project/project_manifest_path.rs#L65)):*
> ```XML
> }
> 
> #[cfg(test)]
> ```

in the rest of the project tests are always in their own file - with a renamed module to `original_test.rs`

please do this here as well.


<!-- Sent from Reviewable.io -->

2024-04-15 08:51 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5415)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5415#-NvVwHuF9H8tcjfqUNOP:-NvVwHuF9H8tcjfqUNOQ:bz7lsyd) (no related file):*
@maciektr I need to gather feedback because it actually surprised me how many active projects are running both:
- https://github.com/OilerNetwork/pitchlake_starknet/blob/35ae6899edbc72b6324be6a3334369cdea76b69d/cairo_project.toml#L2
- https://github.com/gizatechxyz/orion/blob/9c62277084487c05a7e99872cf70108c4cd41354/cairo_project.toml#L2
- https://github.com/Pi-Squared-Inc/proof-checker-public/blob/master/cairo/cairo_project.toml
- https://github.com/smartcontractkit/chainlink-starknet/blob/6cb98ec4421702f220e5646994f38c999ca3a006/contracts/src/cairo_project.toml#L2
- https://github.com/OpenZeppelin/cairo-contracts/tree/main/src
- [and possibly ~100ish more according to GH search](https://github.com/search?q=path%3A**%2Fcairo_project.toml+&type=code&ref=advsearch&p=2), at this point I didn't bother looking

I will ask some people for feedbacks and try to learn what precedence would be the best. Thanks for pointing this out!

___


<!-- Sent from Reviewable.io -->

2024-04-15 09:19 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5415)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-language-server/src/project/project_manifest_path.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5415#-NvQcJUe7cvHgNgv8O7I:-NvW-gnLAfM4-G3frZVV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e88e03544c2432ae498f2ab712f42950f9f12b4b/crates/cairo-lang-language-server/src/project/project_manifest_path.rs#L65)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

in the rest of the project tests are always in their own file - with a renamed module to `original_test.rs`

please do this here as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-15 10:27 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5415#-:-NvWI51K43Yfs_GNuvL3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2024-04-15 10:33 UTC, orizi approved these changes
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5415)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2024-04-15 15:49 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5415)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5415#-NvVwHuF9H8tcjfqUNOP:-NvXRYWYE_YH2gzjjvf9:b73z9cm) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

@maciektr I need to gather feedback because it actually surprised me how many active projects are running both:
- https://github.com/OilerNetwork/pitchlake_starknet/blob/35ae6899edbc72b6324be6a3334369cdea76b69d/cairo_project.toml#L2
- https://github.com/gizatechxyz/orion/blob/9c62277084487c05a7e99872cf70108c4cd41354/cairo_project.toml#L2
- https://github.com/Pi-Squared-Inc/proof-checker-public/blob/master/cairo/cairo_project.toml
- https://github.com/smartcontractkit/chainlink-starknet/blob/6cb98ec4421702f220e5646994f38c999ca3a006/contracts/src/cairo_project.toml#L2
- https://github.com/OpenZeppelin/cairo-contracts/tree/main/src
- [and possibly ~100ish more according to GH search](https://github.com/search?q=path%3A**%2Fcairo_project.toml+&type=code&ref=advsearch&p=2), at this point I didn't bother looking

I will ask some people for feedbacks and try to learn what precedence would be the best. Thanks for pointing this out!
</blockquote></details>

OZ does not use this file. As for the rest, the only feedback I got right now is that nobody bothered removing this file…

___


<!-- Sent from Reviewable.io -->

2024-04-17 14:11 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5415)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5415#-NvVwHuF9H8tcjfqUNOP:-NvgNsH8B-NsViCG8A2t:b-4or8kp) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

OZ does not use this file. As for the rest, the only feedback I got right now is that nobody bothered removing this file…
</blockquote></details>

We have discussed this offline:
1. We will change the precedence as this PR does.
2. I will submit a PR that will report a notification if conflict happens.

___


<!-- Sent from Reviewable.io -->

2024-04-17 14:19 UTC, merged