LS: Introduce `Config` and refactor logic around unmanaged `core` crate
starkware-libs/cairo pull request #5433
Opened 2024-04-17 13:23 UTC by mkaput

This change changes the model of pulling configuration properties from
the client. Previously, LS queried config every time it needed, forcing
the code around to be async, and adding (negligible) latency in
encompassing operations. The new model separates concerns, and now
actual configuration reading is sync and instant. This did not come with
a cost though, because the new implementation is longer, and it
requires cooperation with the accompanying language client extension.
Mind that this setup gracefully degrades if the client does not
cooperate: users can force reloading manually.

---

**Stack**:
- #5423
- #5415

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-04-17 14:24 UTC, orizi requested changes
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5433)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-language-server/src/project/backends/cairo_project/corelib.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5433#-NvgR-m4A9Wj-ZxxjDN5:-NvgR-m4A9Wj-ZxxjDN6:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/26acf20d253a5e98d5d9169c80e5cf5f3c2a6b89/crates/cairo-lang-language-server/src/project/backends/cairo_project/corelib.rs#L30)):*
> ```XML
> }
> 
> fn find_core_at_path(root_path: &Path) -> Option<PathBuf> {
> ```

doc


<!-- Sent from Reviewable.io -->

2024-04-17 14:24 UTC, orizi reviewed
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5433)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2024-04-18 06:48 UTC, orizi reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5433)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2024-04-18 08:26 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5433)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-language-server/src/project/backends/cairo_project/corelib.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5433#-NvgR-m4A9Wj-ZxxjDN5:-NvkG9zDA-gnoW7xVTMo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/26acf20d253a5e98d5d9169c80e5cf5f3c2a6b89/crates/cairo-lang-language-server/src/project/backends/cairo_project/corelib.rs#L30)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-18 08:55 UTC, merged