Collect functions with `executable` attribute into a debug info field
starkware-libs/cairo pull request #5440
Opened 2024-04-17 20:54 UTC by maciektr

2024-04-18 07:45 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-syntax/src/attribute/consts.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5440#-Nvk9bhn8MvcK9EHawo_:-Nvk9bhn8MvcK9EHawoa:b-hqmlpm) ([raw file](https://github.com/starkware-libs/cairo/blob/da783ff56f7d21725755a8144cce171f843571fa/crates/cairo-lang-syntax/src/attribute/consts.rs#L39)):*
> ```XML
> 
> /// An attribute to mark function as an executable function, meaning a program execution entrypoint.
> pub const EXECUTABLE_ATTR: &str = "executable";
> ```

is a user expected to actually write this attr?
or will it be auto generated by something?

if auto generated - make long and more explicit name.



_Code quote:_
```XML
/// An attribute to mark function as an executable function, meaning a program execution entrypoint.
pub const EXECUTABLE_ATTR: &str = "executable";
```


<!-- Sent from Reviewable.io -->

2024-04-18 08:57 UTC, mkaput requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: all files reviewed, 3 unresolved discussions (waiting on @maciektr and @orizi)

___
*[`crates/cairo-lang-sierra/src/debug_info.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NvkPjOXE6rVBEO36P7U:-NvkPjOXE6rVBEO36P7V:b-b8gxvx) ([raw file](https://github.com/starkware-libs/cairo/blob/da783ff56f7d21725755a8144cce171f843571fa/crates/cairo-lang-sierra/src/debug_info.rs#L41)):*
> ```XML
>     /// List of functions marked as executable.
>     #[serde(default, skip_serializing_if = "Vec::is_empty")]
>     pub executables: Vec<(Function, SmolStr)>,
> ```

We're iterating the structure of this field internally/offline.
___
*[`crates/cairo-lang-sierra-generator/src/executables.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NvkPznlE57ycHoOwh86:-NvkPznlE57ycHoOwh87:bdiruet) ([raw file](https://github.com/starkware-libs/cairo/blob/da783ff56f7d21725755a8144cce171f843571fa/crates/cairo-lang-sierra-generator/src/executables.rs#L61)):*
> ```XML
> fn parse_arg(db: &dyn SierraGenGroup, args: Vec<AttributeArg>) -> Option<SmolStr> {
>     args.first().map(|arg| {
>         assert!(matches!(arg.variant, AttributeArgVariant::Unnamed { .. }));
> ```

Emit a diagnostic instead of panicking the compiler.
___
*[`crates/cairo-lang-syntax/src/attribute/consts.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5440#-Nvk9bhn8MvcK9EHawo_:-NvkPJxPChdhnEtuxmSr:b-novwc2) ([raw file](https://github.com/starkware-libs/cairo/blob/da783ff56f7d21725755a8144cce171f843571fa/crates/cairo-lang-syntax/src/attribute/consts.rs#L39)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is a user expected to actually write this attr?
or will it be auto generated by something?

if auto generated - make long and more explicit name.
</blockquote></details>

I imagine rare cases where the user might want to write this manually; but in general, we expect macros to generate these. Say the `#[test]` macro will emit `#[executable("test")]`.


<!-- Sent from Reviewable.io -->

2024-04-18 09:00 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: all files reviewed, 3 unresolved discussions (waiting on @maciektr and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NvkQdAQ3r9iu2waS9QY:-NvkQdAQ3r9iu2waS9QZ:bvvs3fi) (no related file):*
Please add a validation pass somewhere during compilation that will validate arguments of this attribute. You can leave the assertions in `collect_executables` then.

The reason behind this is that we want to emit diagnostics for this attribute even if the toolchain does not call `collect_excecutables` after all.

___
___
*[`crates/cairo-lang-sierra-generator/src/executables.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NvkPznlE57ycHoOwh86:-NvkQ_4y9HiYVtf3kjWy:bf6j443) ([raw file](https://github.com/starkware-libs/cairo/blob/da783ff56f7d21725755a8144cce171f843571fa/crates/cairo-lang-sierra-generator/src/executables.rs#L61)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Emit a diagnostic instead of panicking the compiler.
</blockquote></details>

Retracting because I have a better idea.


<!-- Sent from Reviewable.io -->

2024-04-18 09:24 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: all files reviewed, 3 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-syntax/src/attribute/consts.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5440#-Nvk9bhn8MvcK9EHawo_:-NvkW99l23VNJORfBTVi:bfqi4d9) ([raw file](https://github.com/starkware-libs/cairo/blob/da783ff56f7d21725755a8144cce171f843571fa/crates/cairo-lang-syntax/src/attribute/consts.rs#L39)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I imagine rare cases where the user might want to write this manually; but in general, we expect macros to generate these. Say the `#[test]` macro will emit `#[executable("test")]`.
</blockquote></details>

so rename to something longer and more cumbersome - for example:
`execution_entrypoint`

if a test will create such a thing - won't compilation recreate a lot of functions?


<!-- Sent from Reviewable.io -->

2024-04-18 10:32 UTC, maciektr commented
*[`crates/cairo-lang-syntax/src/attribute/consts.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5440#-Nvk9bhn8MvcK9EHawo_:-NvkkRDJ6n4dWQfx2e3X:b3gpjw1) ([raw file](https://github.com/starkware-libs/cairo/blob/da783ff56f7d21725755a8144cce171f843571fa/crates/cairo-lang-syntax/src/attribute/consts.rs#L39)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so rename to something longer and more cumbersome - for example:
`execution_entrypoint`

if a test will create such a thing - won't compilation recreate a lot of functions?
</blockquote></details>

I wonder whether it would make sense, to use it for marking a main function in `cairo-run` :thinking: In that case, user would need to use it directly.


<!-- Sent from Reviewable.io -->

2024-04-18 11:19 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @maciektr and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NvkQdAQ3r9iu2waS9QY:-NvktyCd0jdG13nUl0z2:bgrjw3v) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Please add a validation pass somewhere during compilation that will validate arguments of this attribute. You can leave the assertions in `collect_executables` then.

The reason behind this is that we want to emit diagnostics for this attribute even if the toolchain does not call `collect_excecutables` after all.
</blockquote></details>

maybe we can (and should) just add all the 

___
___
*[`crates/cairo-lang-compiler/src/lib.rs` line 150 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NvkusDMCcQBECmm0JoV:-NvkusDMCcQBECmm0JoW:boa145e) ([raw file](https://github.com/starkware-libs/cairo/blob/ae04675d17452cb183bd74fb81f275f567ce0a44/crates/cairo-lang-compiler/src/lib.rs#L150)):*
> ```XML
> /// * `Err(anyhow::Error)` - Compilation failed.
> pub fn compile_prepared_db_program_artifact(
>     db: &mut RootDatabase,
> ```

i think maybe this function should just not exist.
and similarly to how we call `compile_contract_in_prepared_db` which is contract aware,
and `compile_test_prepared_db` in the test runner - we should call this with a list of the requested artifacts specifically - which would be in the executable list - being plugin based here feels like is going to be bad.



_Code quote:_
```XML
/// * `Ok(ProgramArtifact)` - The compiled program artifact with requested debug info.
/// * `Err(anyhow::Error)` - Compilation failed.
pub fn compile_prepared_db_program_artifact(
    db: &mut RootDatabase,
```


<!-- Sent from Reviewable.io -->

2024-04-18 12:28 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @maciektr and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NvkQdAQ3r9iu2waS9QY:-Nvl9xSZ8q3y-oQvNUfN:b-z72pm5) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

> maybe we can (and should) just add all the

could you elaborate please?
</blockquote></details>

the idea is - same as test plugin that knows what are the relevant functions (so it can fill the artifacts) and the starknet plugin, so can a run builtin - no need for new special attributes - as it logically per such build target in any case.

___


<!-- Sent from Reviewable.io -->

2024-04-18 13:24 UTC, maciektr commented
*[`crates/cairo-lang-compiler/src/lib.rs` line 150 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NvkusDMCcQBECmm0JoV:-NvlN1SfDmmu91S-6rea:b-1lo195) ([raw file](https://github.com/starkware-libs/cairo/blob/ae04675d17452cb183bd74fb81f275f567ce0a44/crates/cairo-lang-compiler/src/lib.rs#L150)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think maybe this function should just not exist.
and similarly to how we call `compile_contract_in_prepared_db` which is contract aware,
and `compile_test_prepared_db` in the test runner - we should call this with a list of the requested artifacts specifically - which would be in the executable list - being plugin based here feels like is going to be bad.
</blockquote></details>

Sorry, what do you mean by `list of the requested artifacts` :thinking: ? 
The artifact here is just `ProgramArtifact`. 


<!-- Sent from Reviewable.io -->

2024-04-18 13:39 UTC, maciektr commented
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the idea is - same as test plugin that knows what are the relevant functions (so it can fill the artifacts) and the starknet plugin, so can a run builtin - no need for new special attributes - as it logically per such build target in any case.
</blockquote></details>

Well, we would like to push for a generalization of the executable concept here, so that multiple tools (like cairo-run,  sncast-scripts, forge etc.) could rely on a single artifact format (sierra.json), without a need to define specialized targets for each tool in upstream (Scarb).  




<!-- Sent from Reviewable.io -->

2024-04-18 14:17 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @maciektr and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NvkQdAQ3r9iu2waS9QY:-NvlZIrsD230udAWyLX1:b8vmru0) (no related file):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Well, we would like to push for a generalization of the executable concept here, so that multiple tools (like cairo-run,  sncast-scripts, forge etc.) could rely on a single artifact format (sierra.json), without a need to define specialized targets for each tool in upstream (Scarb).
</blockquote></details>

but this means that things like tests would need to rewrite their code - we probably don't want that as well

___


<!-- Sent from Reviewable.io -->

2024-04-18 15:22 UTC, maciektr commented
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

but this means that things like tests would need to rewrite their code - we probably don't want that as well
</blockquote></details>

Hmm, I am not saying we will push for cairo-test rewrite, but rather that we have tools that are bound to be rewritten already (forge test collection) and would benefit from this. With Scarb procedural macros + executable tag combo, we can run forge tests compiled through Scarb without any additional artefacts -> just `sierra.json`, thus fully decoupling Forge from the Cairo compilation level. Rewriting cairo-run / sncast scripts to this would be not a lot more than a one-liner, while also providing additional advantages (namely, ability to run code compiled in release mode, without debug ids). 




<!-- Sent from Reviewable.io -->

2024-04-18 15:47 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @maciektr and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NvkQdAQ3r9iu2waS9QY:-NvlsHoL-rPP5RQ7F-ZE:bbiszrw) (no related file):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Hmm, I am not saying we will push for cairo-test rewrite, but rather that we have tools that are bound to be rewritten already (forge test collection) and would benefit from this. With Scarb procedural macros + executable tag combo, we can run forge tests compiled through Scarb without any additional artefacts -> just `sierra.json`, thus fully decoupling Forge from the Cairo compilation level. Rewriting cairo-run / sncast scripts to this would be not a lot more than a one-liner, while also providing additional advantages (namely, ability to run code compiled in release mode, without debug ids).
</blockquote></details>

i was not talking about rewriting the test-plugin - i was talking about all plugins requiring rewriting their code for this to capture it.
the artifacts are a good idea - but the artifacts should IMO be guided by the caller - instead of by annotation that will need to be added in all cases in the world, but would not make sense for any project that contains various such components.

in a project that contains both tests and run - should everything be compiled together and just the external runner should choose something from within? probably not - so there would be a compilation for testing, with its artifacts, and a different one for proof running, or starknet, or anything of that kind.

___


<!-- Sent from Reviewable.io -->

2024-04-19 09:02 UTC, maciektr commented
Ok, thanks so much for elaborating, it makes a lot more sense to me now!

> i was talking about all plugins requiring rewriting their code for this to capture it

Well, in case of Forge, which would be the biggest beneficiary of this flow,  we need to have a plugin that rewrites `test` attributes anyway, to move the compilation to Scarb (for full Cairo version <> Forge version decoupling). It would not be an issue there at all. 

> probably not - so there would be a compilation for testing, with its artifacts, and a different one for proof running, or starknet, or anything of that kind.

While it's of course true, that we should not push for a single artefact format for all use cases, I would still argue that there is a middle ground here. We would not want to have dedicated compilation targets, hardcoded into Scarb, for all possible tools that run Cairo (i.e. Forge/Cast/Dojo/etc) either. Some of them will naturally fall into +/- the same requirements category, i.e. finding a function in Sierra program and running it (which this proposition would enable).  




<!-- Sent from Reviewable.io -->

2024-04-19 14:54 UTC, maciektr commented
> the artifacts should IMO be guided by the caller - instead of by annotation that will need to be added in all cases in the world

Do you think that we should have some per build input here, so we can only collect executables with specific keys? :thinking: 




<!-- Sent from Reviewable.io -->

2024-04-24 09:26 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: 2 of 10 files reviewed, 4 unresolved discussions (waiting on @maciektr and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NvkQdAQ3r9iu2waS9QY:-NwEPjEU5gxBl4t3j94S:b-plvccn) (no related file):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

> the artifacts should IMO be guided by the caller - instead of by annotation that will need to be added in all cases in the world

Do you think that we should have some per build input here, so we can only collect executables with specific keys? :thinking:
</blockquote></details>

i think every build should have some sort of basic plugin - so the build would have some information about possibly required data.
no need for a catch all allowing attr `executable` just for test - just grabbing what is marked with `test`.
for proof - validate extra things on the called function (for example, return type must be `Drop`able) and finding the set of these functions (for a weird project with more than one)

___
___
*[`crates/cairo-lang-compiler/src/lib.rs` line 150 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NvkusDMCcQBECmm0JoV:-NwEP8Eg9BDYiDmxCRa7:b-3orywj) ([raw file](https://github.com/starkware-libs/cairo/blob/ae04675d17452cb183bd74fb81f275f567ce0a44/crates/cairo-lang-compiler/src/lib.rs#L150)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Sorry, what do you mean by `list of the requested artifacts` :thinking: ? 
The artifact here is just `ProgramArtifact`.
</blockquote></details>

this function by itself is already weird - it just tells us to drop *everything* into a file - which is not necessary in general.

if you want that i would assume you would want to actually extract the relevant data for testing or for running - so the set of test entrypoints to run, or the set of data required for running in proof mode.


<!-- Sent from Reviewable.io -->

2024-04-25 16:45 UTC, orizi requested changes
> Reviewed 1 of 6 files at r3, 5 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: 7 of 11 files reviewed, 3 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 156 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwL7uTYBnC98ay2P3MC:-NwL7uTZ43JIqsSBT_PX:be9n1l5) ([raw file](https://github.com/starkware-libs/cairo/blob/77c499d466459c6df5200da99fe7e0bb90cb5d80/crates/cairo-lang-compiler/src/lib.rs#L156)):*
> ```XML
>     let add_statements_functions = compiler_config.add_statements_functions;
>     let sierra_program_with_debug =
>         compile_prepared_db(db, main_crate_ids.clone(), compiler_config)?;
> ```

This can allow us to also collect only the relevant executable function and dependencies, probably vastly reducing the size of the file 


<!-- Sent from Reviewable.io -->

2024-04-26 08:51 UTC, maciektr commented
*[`crates/cairo-lang-sierra-generator/src/executables.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NvkPznlE57ycHoOwh86:-NwOaNXNBHmhEJ6G1gW2:bpgwvvw) ([raw file](https://github.com/starkware-libs/cairo/blob/da783ff56f7d21725755a8144cce171f843571fa/crates/cairo-lang-sierra-generator/src/executables.rs#L61)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Retracting because I have a better idea.
</blockquote></details>

No longer relevant. 


<!-- Sent from Reviewable.io -->

2024-04-26 08:51 UTC, maciektr commented
*[`crates/cairo-lang-sierra/src/debug_info.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NvkPjOXE6rVBEO36P7U:-NwOaTON3fA4hagL1PTU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/da783ff56f7d21725755a8144cce171f843571fa/crates/cairo-lang-sierra/src/debug_info.rs#L41)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

We're iterating the structure of this field internally/offline.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-26 14:21 UTC, maciektr reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: 7 of 11 files reviewed, 3 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 156 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwL7uTYBnC98ay2P3MC:-NwPm-LHB0PJZY1dZmq9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/77c499d466459c6df5200da99fe7e0bb90cb5d80/crates/cairo-lang-compiler/src/lib.rs#L156)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

This can allow us to also collect only the relevant executable function and dependencies, probably vastly reducing the size of the file
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-28 07:55 UTC, orizi requested changes
> Reviewed 1 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: 8 of 11 files reviewed, 6 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-sierra-generator/src/executables.rs` line 14 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwYeEHjCCX2t1i-JX7c:-NwYeEHjCCX2t1i-JX7d:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/3094e8513104b1216328fd8eee112ca90321aa33/crates/cairo-lang-sierra-generator/src/executables.rs#L14)):*
> ```XML
> use crate::db::SierraGenGroup;
> 
> pub fn find_executable_function_ids(
> ```

doc
___
*[`crates/cairo-lang-sierra-generator/src/executables.rs` line 60 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwYeMQ6Bzo9k4WB2-Yp:-NwYeMQ6Bzo9k4WB2-Yq:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/3094e8513104b1216328fd8eee112ca90321aa33/crates/cairo-lang-sierra-generator/src/executables.rs#L60)):*
> ```XML
> }
> 
> pub fn collect_executables(
> ```

doc
___
*[`crates/cairo-lang-sierra-generator/src/executables.rs` line 92 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwYexEi5fQKNP6I7Rba:-NwYexEi5fQKNP6I7Rbb:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3094e8513104b1216328fd8eee112ca90321aa33/crates/cairo-lang-sierra-generator/src/executables.rs#L92)):*
> ```XML
>                 }
>             }
>         }
> ```





_Suggestion:_
```XML
        for function in &sierra_program.funcs {
            let function_id = function.id.lookup_intern(db);
            let Some(found_attrs) = executable_function_ids.get(function_id) else {
                continue;
            }
            let full_path = function_id
                .function_with_body_id(db.upcast())
                .base_semantic_function(db.upcast())
                .full_path(db.upcast());

            for attr in found_attrs {
                result
                    .entry(attr.clone())
                    .or_default()
                    .push((full_path.clone(), function.id.clone()));
            }
        }
```


<!-- Sent from Reviewable.io -->

2024-04-29 07:57 UTC, maciektr reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: 8 of 11 files reviewed, 6 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/executables.rs` line 14 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwYeEHjCCX2t1i-JX7c:-Nwcqz9A2-dX6ieJ9wKA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3094e8513104b1216328fd8eee112ca90321aa33/crates/cairo-lang-sierra-generator/src/executables.rs#L14)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/executables.rs` line 60 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwYeMQ6Bzo9k4WB2-Yp:-Nwcqyq28XaVfD2OXvqf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3094e8513104b1216328fd8eee112ca90321aa33/crates/cairo-lang-sierra-generator/src/executables.rs#L60)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/executables.rs` line 92 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwYexEi5fQKNP6I7Rba:-NwcqyRU5vdgI9Wj1STB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3094e8513104b1216328fd8eee112ca90321aa33/crates/cairo-lang-sierra-generator/src/executables.rs#L92)):*
> ```XML
>                 }
>             }
>         }
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-04-29 10:54 UTC, mkaput requested changes
> Reviewed 1 of 3 files at r2, 1 of 6 files at r3, 6 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: 9 of 11 files reviewed, 5 unresolved discussions (waiting on @maciektr and @orizi)

___
*[`crates/cairo-lang-defs/src/plugin.rs` line 112 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwdTVFG9BxIq3Gv_m9F:-NwdTVFG9BxIq3Gv_m9G:b-kyljk3) ([raw file](https://github.com/starkware-libs/cairo/blob/2704f82389968232d884b91bfe575a50a0c55bcd/crates/cairo-lang-defs/src/plugin.rs#L112)):*
> ```XML
>     /// Must return a subset of `declared_attributes`.
>     /// This mechanism is optional.
>     fn executable_attributes(&self) -> IntoIter<String> {
> ```

It doesn't make sense to return `vec::IntoIter` here. Return an owned `Vec` (you'll boil down to the same thing). You could also return `impl Iterator<Item=String>`, but this trait is using in `dyn` context so this is impossible.


<!-- Sent from Reviewable.io -->

2024-04-29 11:06 UTC, maciektr commented
*[`crates/cairo-lang-defs/src/plugin.rs` line 112 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwdTVFG9BxIq3Gv_m9F:-NwdXFNZAdah_r2_gunr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2704f82389968232d884b91bfe575a50a0c55bcd/crates/cairo-lang-defs/src/plugin.rs#L112)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

It doesn't make sense to return `vec::IntoIter` here. Return an owned `Vec` (you'll boil down to the same thing). You could also return `impl Iterator<Item=String>`, but this trait is using in `dyn` context so this is impossible.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-29 12:06 UTC, mkaput requested changes
> Reviewed 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: all files reviewed, 5 unresolved discussions (waiting on @maciektr and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwdiUPY40BLEQGqW_Ab:-NwdiUPZ5MCHlzpSJUz7:bavgo84) (no related file):*
I am missing tests for this feature. Primarily, I'm interested in verifying the following aspects:
1. Executables are indeed collected and reflected in the artifact.
2. If they are found, dead code optimization & inlining do their job.

___
___
*[`crates/cairo-lang-sierra-generator/src/executables.rs` line 26 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwdjSyI2skJVOSOnOfV:-NwdjSyJ0vsHdiPOVwmX:blot2ab) ([raw file](https://github.com/starkware-libs/cairo/blob/45d312121dde92dbf646f9d5185a0569c11627bc/crates/cairo-lang-sierra-generator/src/executables.rs#L26)):*
> ```XML
>     db: &dyn SierraGenGroup,
>     main_crate_ids: Vec<CrateId>,
> ) -> HashMap<ConcreteFunctionWithBodyId, Vec<SmolStr>> {
> ```

FYI I'm afraid of the computational complexity of this function and the amount of memory allocations that are happening here (mostly via `Vec::new`), but it's good for the first iteration.


<!-- Sent from Reviewable.io -->

2024-04-30 14:48 UTC, orizi requested changes
> Reviewed 3 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 163 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwjTRIA5tdm3GSZlV-g:-NwjTRIA5tdm3GSZlV-h:b-h4ifyk) ([raw file](https://github.com/starkware-libs/cairo/blob/762b52f427c373fffecc60f5a26a74fa477813ca/crates/cairo-lang-compiler/src/lib.rs#L163)):*
> ```XML
>     let executable_functions = find_executable_function_ids(db, main_crate_ids.clone());
> 
>     let mut sierra_program_with_debug = if executable_functions.is_empty() {
> ```

does this actually make sense? isn't failing more logical?


<!-- Sent from Reviewable.io -->

2024-04-30 15:09 UTC, maciektr commented
*[`crates/cairo-lang-compiler/src/lib.rs` line 163 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwjTRIA5tdm3GSZlV-g:-NwjYOV0Dkos5DgF5I99:ba1ga76) ([raw file](https://github.com/starkware-libs/cairo/blob/762b52f427c373fffecc60f5a26a74fa477813ca/crates/cairo-lang-compiler/src/lib.rs#L163)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

does this actually make sense? isn't failing more logical?
</blockquote></details>

Hmm, why? You can have a simple Cairo build without any plugins. 


<!-- Sent from Reviewable.io -->

2024-04-30 15:16 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 163 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwjTRIA5tdm3GSZlV-g:-NwjZxcA6EEnYN-3fCJ-:bgw9ut6) ([raw file](https://github.com/starkware-libs/cairo/blob/762b52f427c373fffecc60f5a26a74fa477813ca/crates/cairo-lang-compiler/src/lib.rs#L163)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Hmm, why? You can have a simple Cairo build without any plugins.
</blockquote></details>

You can - but it is meaning less building without a particular target.


<!-- Sent from Reviewable.io -->

2024-04-30 15:46 UTC, maciektr commented
*[`crates/cairo-lang-compiler/src/lib.rs` line 163 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwjTRIA5tdm3GSZlV-g:-Nwj_RQsCvu37qljIP11:bd229hl) ([raw file](https://github.com/starkware-libs/cairo/blob/762b52f427c373fffecc60f5a26a74fa477813ca/crates/cairo-lang-compiler/src/lib.rs#L163)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

You can - but it is meaning less building without a particular target.
</blockquote></details>

I am not sure if I would call it meaning less. It's what we have now with the scarb lib target - it compiles Cairo to Sierra. It can be used for instance to run functions by name, it's what some tooling uses already, or even simply for debugging purposes. I don't think we are ready to abandon it completely now. 


<!-- Sent from Reviewable.io -->

2024-04-30 15:50 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 163 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwjTRIA5tdm3GSZlV-g:-NwjgQyT8wv1cRiHP6Dd:bbfq9lm) ([raw file](https://github.com/starkware-libs/cairo/blob/762b52f427c373fffecc60f5a26a74fa477813ca/crates/cairo-lang-compiler/src/lib.rs#L163)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

I am not sure if I would call it meaning less. It's what we have now with the scarb lib target - it compiles Cairo to Sierra. It can be used for instance to run functions by name, it's what some tooling uses already, or even simply for debugging purposes. I don't think we are ready to abandon it completely now.
</blockquote></details>

so at the very least it makes no sense without --replace-ids.

and should probably have a todo to deprecate.


<!-- Sent from Reviewable.io -->

2024-04-30 17:35 UTC, maciektr commented
*[`crates/cairo-lang-compiler/src/lib.rs` line 163 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwjTRIA5tdm3GSZlV-g:-Nwk3Zl94r51_p5qLu7_:b-tsh0f1) ([raw file](https://github.com/starkware-libs/cairo/blob/762b52f427c373fffecc60f5a26a74fa477813ca/crates/cairo-lang-compiler/src/lib.rs#L163)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so at the very least it makes no sense without --replace-ids.

and should probably have a todo to deprecate.
</blockquote></details>

Yes, logically you are probably right. I don't think it's worth to ban this specific configuration though, especially since we would really have to verify with community if there is any use case we are yet not aware of.   


<!-- Sent from Reviewable.io -->

2024-05-01 04:39 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @maciektr and @mkaput)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 163 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwjTRIA5tdm3GSZlV-g:-NwmRMms9mPKszq_Rjnz:byi88rx) ([raw file](https://github.com/starkware-libs/cairo/blob/762b52f427c373fffecc60f5a26a74fa477813ca/crates/cairo-lang-compiler/src/lib.rs#L163)):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

Yes, logically you are probably right. I don't think it's worth to ban this specific configuration though, especially since we would really have to verify with community if there is any use case we are yet not aware of.
</blockquote></details>

i don't see any way for this to be usable.
i'd rather add a failure anyway (as replace-ids is would keep the same meaning - and is always possible), so it is low risk as long as you give a proper error.


<!-- Sent from Reviewable.io -->

2024-05-06 06:31 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440#-:-NxBaQAR4f_9VQNp35PF:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr)



<!-- Sent from Reviewable.io -->

2024-05-06 11:55 UTC, orizi reviewed
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr)



<!-- Sent from Reviewable.io -->

2024-05-06 12:11 UTC, mkaput reviewed
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr)



<!-- Sent from Reviewable.io -->

2024-05-06 14:48 UTC, maciektr reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NvkQdAQ3r9iu2waS9QY:-NxDInR9Egn8KWb9c2j0:bel2era) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think every build should have some sort of basic plugin - so the build would have some information about possibly required data.
no need for a catch all allowing attr `executable` just for test - just grabbing what is marked with `test`.
for proof - validate extra things on the called function (for example, return type must be `Drop`able) and finding the set of these functions (for a weird project with more than one)
</blockquote></details>

@orizi What would you say, if for now we make it a warning on the Scarb side? 

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwdiUPY40BLEQGqW_Ab:-NxDIlIKC7qzCuOLgt98:b-896fix) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I am missing tests for this feature. Primarily, I'm interested in verifying the following aspects:
1. Executables are indeed collected and reflected in the artifact.
2. If they are found, dead code optimization & inlining do their job.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2024-05-06 15:29 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NvkQdAQ3r9iu2waS9QY:-NxDWTO-EpvQ628kdW6f:b-6o5nlz) (no related file):*
<details><summary><i>Previously, maciektr (maciektr) wrote…</i></summary><blockquote>

@orizi What would you say, if for now we make it a warning on the Scarb side?
</blockquote></details>

sounds great - just add a TODO here.

___


<!-- Sent from Reviewable.io -->

2024-05-06 15:50 UTC, maciektr commented
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

sounds great - just add a TODO here.
</blockquote></details>

Great, added!




<!-- Sent from Reviewable.io -->

2024-05-06 15:50 UTC, maciektr reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-compiler/src/lib.rs` line 163 at r8](https://reviewable.io/reviews/starkware-libs/cairo/5440#-NwjTRIA5tdm3GSZlV-g:-NxDaK8SBy8wP-qQmBdp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/762b52f427c373fffecc60f5a26a74fa477813ca/crates/cairo-lang-compiler/src/lib.rs#L163)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't see any way for this to be usable.
i'd rather add a failure anyway (as replace-ids is would keep the same meaning - and is always possible), so it is low risk as long as you give a proper error.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-06 15:59 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 5 files at r8, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5440#-:-NxDcV0e-FOLicS2YrjT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2024-05-06 16:30 UTC, merged