added consts in impls
starkware-libs/cairo pull request #5454
Opened 2024-04-21 11:46 UTC by TomerStarkware

2024-04-21 13:44 UTC, orizi requested changes
> Reviewed 4 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @TomerStarkware and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 1464 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-Nw-t6It0QZNQuuPe9cx:-Nw-t6It0QZNQuuPe9cy:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/db.rs#L1464)):*
> ```XML
>                 vec![db.impl_constant_def_resolver_data(id)]
>             }
>         },
> ```





_Suggestion:_
```XML
        LookupItemId::ImplItem(id) => match id {
            cairo_lang_defs::ids::ImplItemId::Function(id) => {
                vec![db.impl_function_resolver_data(id), db.impl_function_body_resolver_data(id)]
            }
            cairo_lang_defs::ids::ImplItemId::Type(id) => vec![db.impl_type_def_resolver_data(id)],
            cairo_lang_defs::ids::ImplItemId::Constant(id) => {
                vec![db.impl_constant_def_resolver_data(id)]
            }
        },
```


<!-- Sent from Reviewable.io -->

2024-04-24 12:51 UTC, mkaput approved these changes
> Reviewed 4 of 8 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware and @yuvalsw)



<!-- Sent from Reviewable.io -->

2024-04-24 13:43 UTC, yuvalsw requested changes
> Reviewed 8 of 8 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454)* status: all files reviewed, 17 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 464 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEm8EVAOVyRuAJpGZg:-NwEm8EVAOVyRuAJpGZh:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/db.rs#L464)):*
> ```XML
>     fn trait_constant_attributes(&self, trait_type_id: TraitConstantId) -> Maybe<Vec<Attribute>>;
> 
>     #[salsa::invoke(items::trt::trait_constant_type)]
> ```

doc
___
*[`crates/cairo-lang-semantic/src/db.rs` line 777 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEm_2i8ZtauYe1JCVr:-NwEm_2i8ZtauYe1JCVs:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/db.rs#L777)):*
> ```XML
>     // ================
> 
>     /// Returns the semantic diagnostics of an impl constant type.
> ```





_Suggestion:_
```XML
 an impl item constant.
```
___
*[`crates/cairo-lang-semantic/src/db.rs` line 782 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEmewhCbDFGNo4WjjW:-NwEmewhCbDFGNo4WjjX:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/db.rs#L782)):*
> ```XML
>         &self,
>         impl_type_def_id: ImplConstantDefId,
>     ) -> Diagnostics<SemanticDiagnostic>;
> ```





_Suggestion:_
```XML
    #[salsa::invoke(items::imp::impl_constant_def_semantic_diagnostics)]
    fn impl_constant_def_semantic_diagnostics(
        &self,
        impl_constant_def_id: ImplConstantDefId,
    ) -> Diagnostics<SemanticDiagnostic>;
```
___
*[`crates/cairo-lang-semantic/src/db.rs` line 790 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEmomO9jrpi-3u5hbC:-NwEmomO9jrpi-3u5hbD:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/db.rs#L790)):*
> ```XML
>         impl_constant_def_id: ImplConstantDefId,
>     ) -> Maybe<ConstValue>;
>     /// Returns the resolution resolved_items of an impl item type.
> ```





_Suggestion:_
```XML
lved_items of an impl item constant.
```
___
*[`crates/cairo-lang-semantic/src/db.rs` line 800 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEn0UB3GpOCYupy8tH:-NwEn0UB3GpOCYupy8tI:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/db.rs#L800)):*
> ```XML
>     fn impl_constant_def_trait_constant(
>         &self,
>         impl_type_def_id: ImplConstantDefId,
> ```





_Suggestion:_
```XML
impl_constant_def_id:
```
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEn_PM5kZBvUKZPVdu:-NwEn_PM5kZBvUKZPVdv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/items/constant.rs#L147)):*
> ```XML
> }
> 
> /// returns constant semantic data for the given Item_constant.
> ```





_Suggestion:_
```XML
// Returns constant semantic data for the given ItemConstant
```
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEoPnM7E1WxubGYRyC:-NwEoPnM7E1WxubGYRyD:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/items/constant.rs#L157)):*
> ```XML
>     let module_file_id = element_id.module_file_id(db.upcast());
>     let mut diagnostics: SemanticDiagnostics =
>         SemanticDiagnostics::new(element_id.module_file_id(db.upcast()).file_id(db.upcast())?);
> ```





_Suggestion:_
```XML
SemanticDiagnostics::new(module_file_id.file_id(db.upcast())?);
```
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEqS3xCVv7ogFbtSpZ:-NwEqS3xCVv7ogFbtSp_:b-6i6nog) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/items/constant.rs#L172)):*
> ```XML
>     };
>     resolver.data.allowed_features =
>         extract_allowed_features(db.upcast(), element_id, constant_ast, &mut diagnostics);
> ```

Question to both @TomerStarkware  and @orizi :
1. Is it possible (answer for both theoretically/practically) that the parent resolver data has some allowed features and thus this should be extended instead of overwritten?
2. If not, maybe it's something that should not be cloned in `clone_with_inference_id`?



_Code quote:_
```XML
    resolver.data.allowed_features =
        extract_allowed_features(db.upcast(), element_id, constant_ast, &mut diagnostics);
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1446 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEv9zkBFtKNtuTzahG:-NwEv9zl3s0ycc3nE5Ua:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/items/imp.rs#L1446)):*
> ```XML
> 
> /// Query implementation of [crate::db::SemanticGroup::impl_constant_def_constant_value].
> pub fn impl_constant_def_constant_value(
> ```





_Suggestion:_
```XML
impl_constant_def_value
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1454 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEvISm5UVyMghpRAcg:-NwEvISn6dGgH10lvT_z:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/items/imp.rs#L1454)):*
> ```XML
> 
> /// Cycle handling for [crate::db::SemanticGroup::impl_constant_def_constant_value].
> pub fn impl_constant_def_constant_value_cycle(
> ```





_Suggestion:_
```XML
impl_constant_def_value_cycle
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1461 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEv-qFB3FBYAFtHZT6:-NwEv-qFB3FBYAFtHZT7:bcjuyzs) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/items/imp.rs#L1461)):*
> ```XML
>     // Forwarding cycle handling to `priv_impl_constant_semantic_data` handler.
>     impl_constant_def_constant_value(db, *impl_constant_def_id)
> }
> ```

move, this is in the middle of the impl_type queries.



_Code quote:_
```XML
/// Query implementation of [crate::db::SemanticGroup::impl_constant_def_constant_value].
pub fn impl_constant_def_constant_value(
    db: &dyn SemanticGroup,
    impl_constant_def_id: ImplConstantDefId,
) -> Maybe<ConstValue> {
    Ok(db.priv_impl_constant_semantic_data(impl_constant_def_id)?.constant_data.const_value)
}

/// Cycle handling for [crate::db::SemanticGroup::impl_constant_def_constant_value].
pub fn impl_constant_def_constant_value_cycle(
    db: &dyn SemanticGroup,
    _cycle: &[String],
    impl_constant_def_id: &ImplConstantDefId,
) -> Maybe<ConstValue> {
    // Forwarding cycle handling to `priv_impl_constant_semantic_data` handler.
    impl_constant_def_constant_value(db, *impl_constant_def_id)
}
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1504 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEvpTyDTgclAsbHtYQ:-NwEvpTyDTgclAsbHtYR:b-3kbmxd) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/items/imp.rs#L1504)):*
> ```XML
>     constant_data: ConstantData,
>     trait_constant_id: Maybe<TraitConstantId>,
>     /// The diagnostics of the module type alias, including the ones for the type alias itself.
> ```

fix comment



_Code  [...]

2024-04-25 09:07 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454)* status: 3 of 8 files reviewed, 17 unresolved discussions (waiting on @mkaput, @TomerStarkware, and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEqS3xCVv7ogFbtSpZ:-NwJV1iG8K-gBpuzr4UF:b3j2sa1) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/items/constant.rs#L172)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Question to both @TomerStarkware  and @orizi :
1. Is it possible (answer for both theoretically/practically) that the parent resolver data has some allowed features and thus this should be extended instead of overwritten?
2. If not, maybe it's something that should not be cloned in `clone_with_inference_id`?
</blockquote></details>

1. possibly - if we properly read all and validates the features per parent - but not sure how.
2. when it is done  - the clone would likely be required.


<!-- Sent from Reviewable.io -->

2024-04-25 12:25 UTC, yuvalsw requested changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454)* status: all files reviewed, 6 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 781 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwK77Xm4lO_jXFl43od:-NwK77Xm4lO_jXFl43oe:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ce89c4374dfbf370c9fc3f5e531ac6397272e72e/crates/cairo-lang-semantic/src/db.rs#L781)):*
> ```XML
>     fn impl_constant_def_value(&self, impl_constant_def_id: ImplConstantDefId)
>     -> Maybe<ConstValue>;
>     /// Returns the resolution resolved_items of an impl item const.
> ```





_Suggestion:_
```XML
item constant.
```
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEqS3xCVv7ogFbtSpZ:-NwKAK6NEQ-BLmNOpbvm:bf809qh) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/items/constant.rs#L172)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

1. possibly - if we properly read all and validates the features per parent - but not sure how.
2. when it is done  - the clone would likely be required.
</blockquote></details>

I am not familiar with the allowed features thing, but according to `extract_allowed_features`, we concat all the allowed features of all the parents together with the allowed features of the item. So it seems to me like this works but not efficient. We clone from the parent and then overwrite, calculating all the parents again.

So again, I think we should take the parent's allowed_features from the clone and extend the current item using `extract_item_allowed_features` instead of `extract_item_allowed_features`.
Another (worse than the above, but better than the current) option is to overwrite here which is again, not efficient, but at least avoid the clone in clone_with_inference_id.
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 147 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwK7Fe53rL9Dae2GGnF:-NwK7Fe53rL9Dae2GGnG:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ce89c4374dfbf370c9fc3f5e531ac6397272e72e/crates/cairo-lang-semantic/src/items/constant.rs#L147)):*
> ```XML
> }
> 
> /// Returns constant semantic data for the given Item_constant.
> ```





_Suggestion:_
```XML
 given ItemConstant.
```
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 155 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwK7RzJ66NFqmZgrloJ:-NwK7RzJ66NFqmZgrloK:b-yw1oa5) ([raw file](https://github.com/starkware-libs/cairo/blob/ce89c4374dfbf370c9fc3f5e531ac6397272e72e/crates/cairo-lang-semantic/src/items/constant.rs#L155)):*
> ```XML
>     element_id: &impl LanguageElementId,
> ) -> Maybe<ConstantData> {
>     let module_file_id = element_id.module_file_id(db.upcast());
> ```

inline in the only use.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1461 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwKBzGL1k9rR7livHPU:-NwKBzGL1k9rR7livHPV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ce89c4374dfbf370c9fc3f5e531ac6397272e72e/crates/cairo-lang-semantic/src/items/imp.rs#L1461)):*
> ```XML
>     constant_data: ConstantData,
>     trait_constant_id: Maybe<TraitConstantId>,
>     /// The diagnostics of the impl constant, including the ones for the impl constant itself.
> ```





_Suggestion:_
```XML
 for the constant itse
```


<!-- Sent from Reviewable.io -->

2024-04-25 13:55 UTC, orizi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454)* status: all files reviewed, 6 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEqS3xCVv7ogFbtSpZ:-NwKWkI54_6aJcetsvOz:b-nlmkjr) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/items/constant.rs#L172)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I am not familiar with the allowed features thing, but according to `extract_allowed_features`, we concat all the allowed features of all the parents together with the allowed features of the item. So it seems to me like this works but not efficient. We clone from the parent and then overwrite, calculating all the parents again.

So again, I think we should take the parent's allowed_features from the clone and extend the current item using `extract_item_allowed_features` instead of `extract_item_allowed_features`.
Another (worse than the above, but better than the current) option is to overwrite here which is again, not efficient, but at least avoid the clone in clone_with_inference_id.
</blockquote></details>

We need to properly read the data in all stages (which we currently don't do, as  we need to handle various options, which i'm not sure we fully cover yet in the attributes side) - if we do it, cloning and extending would be the best.
I'd rather clone uselessly for now instead of moving it when changing to it in the future (this is currently almost always an empty vec, so i don't really care about the cloning performance of it).

In any case - i believe this is completely unrelated to this PR.


<!-- Sent from Reviewable.io -->

2024-04-25 14:45 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454)* status: all files reviewed, 6 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEqS3xCVv7ogFbtSpZ:-NwKhJUl6tihWLurouk1:b-c0izrj) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/items/constant.rs#L172)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

We need to properly read the data in all stages (which we currently don't do, as  we need to handle various options, which i'm not sure we fully cover yet in the attributes side) - if we do it, cloning and extending would be the best.
I'd rather clone uselessly for now instead of moving it when changing to it in the future (this is currently almost always an empty vec, so i don't really care about the cloning performance of it).

In any case - i believe this is completely unrelated to this PR.
</blockquote></details>

What's related to this PR is that here it overwrites the allowed feature. If the current logic works (it seem to) and you don't care about performance and prefer to leave the extra computations for the future, I am ok with it.
Maybe worth adding a TODO here noting that it's overwritten here.
Up to your (Ori+Tomer) judgement.
(unblocking)


<!-- Sent from Reviewable.io -->

2024-04-30 07:46 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454)* status: 2 of 8 files reviewed, 5 unresolved discussions (waiting on @mkaput, @orizi, and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 464 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEm8EVAOVyRuAJpGZg:-NwJ4rT44gBjXcZPpfhB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/db.rs#L464)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/db.rs` line 777 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEm_2i8ZtauYe1JCVr:-NwJ5GbS4AGDmIxqwkKw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/db.rs#L777)):*
> ```XML
>     // ================
> 
>     /// Returns the semantic diagnostics of an impl constant type.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/db.rs` line 782 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEmewhCbDFGNo4WjjW:-NwJ5R9X2RF7G_nkKt3m:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/db.rs#L782)):*
> ```XML
>         &self,
>         impl_type_def_id: ImplConstantDefId,
>     ) -> Diagnostics<SemanticDiagnostic>;
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/db.rs` line 790 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEmomO9jrpi-3u5hbC:-NwJ5XTeDRAsgrI1kJPI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/db.rs#L790)):*
> ```XML
>         impl_constant_def_id: ImplConstantDefId,
>     ) -> Maybe<ConstValue>;
>     /// Returns the resolution resolved_items of an impl item type.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/db.rs` line 800 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEn0UB3GpOCYupy8tH:-NwJ5e_69FbbxBDsPMZN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/db.rs#L800)):*
> ```XML
>     fn impl_constant_def_trait_constant(
>         &self,
>         impl_type_def_id: ImplConstantDefId,
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/db.rs` line 1464 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-Nw-t6It0QZNQuuPe9cx:-NwJ5msbCCvFj5hC0BW2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/db.rs#L1464)):*
> ```XML
>                 vec![db.impl_constant_def_resolver_data(id)]
>             }
>         },
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/db.rs` line 781 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwK77Xm4lO_jXFl43od:-NwhszxJA4pNgQ-JL2IC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ce89c4374dfbf370c9fc3f5e531ac6397272e72e/crates/cairo-lang-semantic/src/db.rs#L781)):*
> ```XML
>     fn impl_constant_def_value(&self, impl_constant_def_id: ImplConstantDefId)
>     -> Maybe<ConstValue>;
>     /// Returns the resolution resolved_items of an impl item const.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEn_PM5kZBvUKZPVdu:-NwJ5ysWDsAMfnzr6r1M:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/items/constant.rs#L147)):*
> ```XML
> }
> 
> /// returns constant semantic data for the given Item_constant.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEoPnM7E1WxubGYRyC:-NwJ67if4qkKXmbsQEdH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/items/constant.rs#L157)):*
> ```XML
>     let module_file_id = element_id.module_file_id(db.upcast());
>     let mut diagnostics: SemanticDiagnostics =
>         SemanticDiagnostics::new(element_id.module_file_id(db.upcast()).file_id(db.upcast())?);
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 147 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwK7Fe53rL9Dae2GGnF:-NwhsSwH2A819LdtRN0C:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ce89c4374dfbf370c9fc3f5e531ac6397272e72e/crates/cairo-lang-semantic/src/items/constant.rs#L147)):*
> ```XML
> }
> 
> /// Returns constant semantic data for the given Item_constant.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 155 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwK7RzJ66NFqmZgrloJ:-NwhsbYS30CdD8LwmGKM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ce89c4374dfbf370c9fc3f5e531ac6397272e72e/crates/cairo-lang-semantic/src/items/constant.rs#L155)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

inline in the only use.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1446 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEv9zkBFtKNtuTzahG:-NwJ7-Aa6OCzU-tIBTwk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/items/imp.rs#L1446)):*
> ```XML
> 
> /// Query implementation of [crate::db::SemanticGroup::impl_constant_def_constant_value].
> pub fn impl_constant_def_constant_value(
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1454 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEvISm5UVyMghpRAcg:-NwJ70326uuMfX0d_IQX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/items/imp.rs#L1454)):*
> ```XML
> 
> /// Cycle handling for [crate::db::SemanticGroup::impl_constant_def_constant_value].
> pub fn impl_constant_def_constant_value_cycle(
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1461 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEv-qFB3FBYAFtHZT6:-NwJ8hUU9zbNCZcm0hbs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/items/imp.rs#L1461)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

move, this is in the middle of the impl_type queries.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1504 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwEvpTyDTgclAsbHtYQ:-NwJ9Uui034i5wuxMNsS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/items/imp.rs#L1504)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

fix comment
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1658 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwFHtB74fHCKDDRA8Ga:-NwJA64WBKs6JiAQeBnR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/items/imp.rs#L1658)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

export to a var
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 1664 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NwFIH-W-_MUMlgiJDuF:-NwJByWyA4MjHhKtuzzJ:brrpiu1) ([raw file](https://github.com/starkware-libs/cairo/blob/539b0fe5c46e20d97bdfd752b9e71b556d62c0d9/crates/cairo-lang-semantic/src/items/imp.rs#L1664)):*
> ```XML
>         diagnostics.report_by_ptr(location_ptr [...]

2024-04-30 07:49 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454#-:-NwhynqG1QIkk8ilPHa1:bnfp4nl)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @mkaput and @yuvalsw)



<!-- Sent from Reviewable.io -->

2024-04-30 07:49 UTC, orizi approved these changes
> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454)* status: all files reviewed, 4 unresolved discussions (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2024-04-30 08:34 UTC, orizi approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454)* status: all files reviewed, 4 unresolved discussions (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2024-05-08 15:12 UTC, orizi requested changes
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454)* status: all files reviewed, 5 unresolved discussions (waiting on @TomerStarkware and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 221 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NxNkfAb5g1bKfoIUomd:-NxNkfAb5g1bKfoIUome:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/52702fbfa0b451636e5f20be633a3c0c4d651e5d/crates/cairo-lang-semantic/src/items/constant.rs#L221)):*
> ```XML
> }
> 
> // Cycle handling for constant_semantic_data_helper.
> ```





_Suggestion:_
```XML
/// Cycle handling for constant_semantic_data_helper.
```


<!-- Sent from Reviewable.io -->

2024-05-09 15:42 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454)* status: 2 of 27 files reviewed, 6 unresolved discussions (waiting on @mkaput, @TomerStarkware, and @yuvalsw)

___
*[`-- commits` line 1 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NxT0EjD768qZZO6wVLc):*
fix base


<!-- Sent from Reviewable.io -->

2024-05-12 09:03 UTC, orizi reviewed
> Reviewed 5 of 25 files at r7, 19 of 20 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454)* status: 26 of 27 files reviewed, 5 unresolved discussions (waiting on @TomerStarkware and @yuvalsw)



<!-- Sent from Reviewable.io -->

2024-05-12 09:18 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454)* status: 25 of 27 files reviewed, 5 unresolved discussions (waiting on @orizi and @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 221 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NxNkfAb5g1bKfoIUomd:-Nxg3cxM9JIXJtaBNloD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/52702fbfa0b451636e5f20be633a3c0c4d651e5d/crates/cairo-lang-semantic/src/items/constant.rs#L221)):*
> ```XML
> }
> 
> // Cycle handling for constant_semantic_data_helper.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-05-12 09:23 UTC, orizi approved these changes
> Reviewed 1 of 20 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454)* status: all files reviewed, 4 unresolved discussions (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2024-05-12 13:02 UTC, yuvalsw requested changes
> Reviewed 1 of 5 files at r6, 5 of 25 files at r7, 19 of 20 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 221 at r10](https://reviewable.io/reviews/starkware-libs/cairo/5454#-Nxgs2y37FANcy6QjRsA:-Nxgs2y37FANcy6QjRsB:b-r7qik5) ([raw file](https://github.com/starkware-libs/cairo/blob/1f0d34d9ca27f32f0b524db5543716afa758271a/crates/cairo-lang-semantic/src/items/constant.rs#L221)):*
> ```XML
> }
> 
> /// Cycle handling for constant_semantic_data_helper.
> ```

Helper for cycle handling of constants.



_Code quote:_
```XML
/// Cycle handling for constant_semantic_data_helper.
```
___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 242 at r10](https://reviewable.io/reviews/starkware-libs/cairo/5454#-NxgsWRF48hq-onh0DcK:-NxgsWRF48hq-onh0DcL:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1f0d34d9ca27f32f0b524db5543716afa758271a/crates/cairo-lang-semantic/src/items/constant.rs#L242)):*
> ```XML
>     let resolver_data = Arc::new(resolver.data);
> 
>     let diagnostic_add = diagnostics.report(constant_ast, SemanticDiagnosticKind::ConstCycle);
> ```





_Suggestion:_
```XML
diagnostic_added
```


<!-- Sent from Reviewable.io -->

2024-05-16 07:15 UTC, orizi approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-05-16 07:30 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454)* status: all files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`crates/cairo-lang-semantic/src/items/constant.rs` line 221 at r10](https://reviewable.io/reviews/starkware-libs/cairo/5454#-Nxgs2y37FANcy6QjRsA:-Ny-EiV7-P7R-HGdCY_7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1f0d34d9ca27f32f0b524db5543716afa758271a/crates/cairo-lang-semantic/src/items/constant.rs#L221)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Helper for cycle handling of constants.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-16 14:33 UTC, yuvalsw approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454#-:-Ny0ofQ68McQe4M8YJ4y:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-05-16 18:53 UTC, orizi approved these changes
> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5454)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-05-16 20:36 UTC, merged