better usage of `default` for `RootDatabaseBuilder` and `PluginSuite`
starkware-libs/cairo pull request #5537
Opened 2024-05-09 17:34 UTC by tcoratger

A better usage of `Default` implementation is made for the following structures:
- `RootDatabaseBuilder`
- `PluginSuite`

2024-05-09 19:02 UTC, mkaput requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5537)* status: all files reviewed, 1 unresolved discussion (waiting on @tcoratger)

___
*[`crates/cairo-lang-compiler/src/db.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5537#-NxTik1lCAKOe8HeXKd1:-NxTik1lCAKOe8HeXKd2:bdcqzlt) ([raw file](https://github.com/starkware-libs/cairo/blob/f10be78302e920cd0ae91af75bbbedaf3150ee75/crates/cairo-lang-compiler/src/db.rs#L80)):*
> ```XML
> }
> 
> #[derive(Clone, Debug, Default)]
> ```

This makes the builder constructible by the user, which we do not want to allow.


<!-- Sent from Reviewable.io -->

2024-05-09 19:10 UTC, tcoratger commented on crates/cairo-lang-compiler/src/db.rs
> +#[derive(Clone, Debug, Default)]
```suggestion
#[derive(Clone, Debug)]
```

2024-05-09 19:10 UTC, tcoratger commented on crates/cairo-lang-compiler/src/db.rs
> +            ..Default::default()
```suggestion
            project_config: None,
            cfg_set: None,
```

2024-05-09 19:10 UTC, tcoratger commented on crates/cairo-lang-compiler/src/db.rs
>              plugin_suite: get_default_plugin_suite(),
```suggestion
            plugin_suite: get_default_plugin_suite(),
            detect_corelib: false,
```

2024-05-09 19:11 UTC, tcoratger commented
> > Reviewed 2 of 2 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5537)_ status: all files reviewed, 1 unresolved discussion (waiting on @tcoratger)
> 
> _[`crates/cairo-lang-compiler/src/db.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5537#-NxTik1lCAKOe8HeXKd1:-NxTik1lCAKOe8HeXKd2:bdcqzlt) ([raw file](https://github.com/starkware-libs/cairo/blob/f10be78302e920cd0ae91af75bbbedaf3150ee75/crates/cairo-lang-compiler/src/db.rs#L80)):_
> 
> > ```
> > }
> > 
> > #[derive(Clone, Debug, Default)]
> > ```
> 
> This makes the builder constructible by the user, which we do not want to allow.

Oups yes you are right, just reverted it, I think we still can use the shortcut for `PluginSuite`, just more practical and less verbose IMO

2024-05-10 13:37 UTC, mkaput commented
@tcoratger use Reviewable for commenting on PRs in this repository please

2024-05-10 13:38 UTC, mkaput requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5537)* status: all files reviewed, 4 unresolved discussions (waiting on @tcoratger)

___
*[`crates/cairo-lang-semantic/src/inline_macros/mod.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5537#-NxXiNXWDJmnFIexpMNm:-NxXiNXWDJmnFIexpMNn:b-sf9tcu) ([raw file](https://github.com/starkware-libs/cairo/blob/6b361734c19c6510ea047785744496862b089d1d/crates/cairo-lang-semantic/src/inline_macros/mod.rs#L22)):*
> ```XML
> /// Gets the default plugin suite to load into the Cairo compiler.
> pub fn get_default_plugin_suite() -> PluginSuite {
>     let mut suite = PluginSuite { plugins: get_base_plugins(), ..Default::default() };
> ```

@orizi wdyt? I don't feel convinced to this change, but I don't want to bikeshed.


<!-- Sent from Reviewable.io -->

2024-05-10 13:57 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5537)* status: all files reviewed, 4 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-semantic/src/inline_macros/mod.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5537#-NxXiNXWDJmnFIexpMNm:-NxXmka7EDb0AYeITLGF:b-sy49qd) ([raw file](https://github.com/starkware-libs/cairo/blob/6b361734c19c6510ea047785744496862b089d1d/crates/cairo-lang-semantic/src/inline_macros/mod.rs#L22)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

@orizi wdyt? I don't feel convinced to this change, but I don't want to bikeshed.
</blockquote></details>

sounds ok.


<!-- Sent from Reviewable.io -->

2024-05-10 14:00 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5537#-:-NxXnSXg4BQATkKHz8q_:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-05-10 14:02 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5537#-:-NxXo0Ik0Jx1WVDcmR8b:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2024-05-10 14:15 UTC, merged