adding clap attributes to inputs
starkware-libs/cairo pull request #5598
Opened 2024-05-21 12:25 UTC by Tomer-StarkWare

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/5598)

2024-05-21 13:14 UTC, gilbens-starkware requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @orizi and @Tomer-StarkWare)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQH893As3UdIEvoehz:-NyQH894-hEbogbJwErE:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/96b94a92b009f7bc4f75be86516f7a5f68619ec2/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L21)):*
> ```XML
> 
> const NUM_OF_PROCESSORS: usize = 32;
> struct Args {
> ```

doc



_Code quote:_
```XML
struct Args {
```
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQHEuv9xUky4YL3OMi:-NyQHEuv9xUky4YL3OMj:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/96b94a92b009f7bc4f75be86516f7a5f68619ec2/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L136)):*
> ```XML
>         1. If fullnode_url is provided, it reads the contract classes from the fullnode.
>         2. If fullnode_url is not provided, it reads the contract classes from the input files.
>         
> ```


___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQHO5A8dWBOUr1o_xv:-NyQHO5A8dWBOUr1o_xw:bti6nn1) ([raw file](https://github.com/starkware-libs/cairo/blob/96b94a92b009f7bc4f75be86516f7a5f68619ec2/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L151)):*
> ```XML
>         .group(ArgGroup::new("fullnode").args(["fullnode-url"]).requires_all(["start-block", "end-block"]))
>         .group(ArgGroup::new("input").args(["fullnode-url", "input-files"]).required(true))
>         .group(ArgGroup::new("libfuncs").args(["allowed-libfuncs-list-name", "allowed-libfuncs-list-file"]));
> ```

break long lines.



_Code quote:_
```XML
        .arg(arg!(["input-files"] "The input files with declared classes info"))
        .arg(arg!(--"allowed-libfuncs-list-name" <String> "The allowed libfuncs list to use (default: most recent audited list)."))
        .arg(arg!(--"allowed-libfuncs-list-file" <File> "A file of the allowed libfuncs list to use."))
        .arg(arg!(--"override-version" <String> "Sierra version to override to prior to compilation."))
        .arg(arg!(--"max-bytecode-size" <usize> "The max bytecode size.").default_value("180000").value_parser(value_parser!(usize)))
        .arg(arg!(--"fullnode-url" <URL> "The url of the rpc server, if provided - Sierra classes would be read from it, and no input files should be provided."))
        .arg(arg!(--"start-block" <u64> "The start block of the declared Sierra classes to test.").value_parser(value_parser!(u64)))
        .arg(arg!(--"end-block" <u64> "The end block of the declared Sierra classes to test.").value_parser(value_parser!(u64)))
        .arg(arg!(--"class-info-output-file" <String> "The output file to write the Sierra classes into."))
        .group(ArgGroup::new("fullnode").args(["fullnode-url"]).requires_all(["start-block", "end-block"]))
        .group(ArgGroup::new("input").args(["fullnode-url", "input-files"]).required(true))
        .group(ArgGroup::new("libfuncs").args(["allowed-libfuncs-list-name", "allowed-libfuncs-list-file"]));
```


<!-- Sent from Reviewable.io -->

2024-05-21 13:14 UTC, orizi requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQHQ_kCrObP5e-NFob:-NyQHQ_kCrObP5e-NFoc:bgx9rae) ([raw file](https://github.com/starkware-libs/cairo/blob/96b94a92b009f7bc4f75be86516f7a5f68619ec2/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L54)):*
> ```XML
>                 .filter(|s| !s.is_empty())
>                 .collect(),
>             allowed_libfuncs_list_name: matches
> ```

keep same as before - as path args if possible.



_Code quote:_
```XML
            input_files: matches
                .get_one::<String>("input-files")
                .unwrap_or(&"".to_string())
                .split(' ')
                .map(|s| s.to_string())
                .filter(|s| !s.is_empty())
                .collect(),
            allowed_libfuncs_list_name: matches
```
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQGwnR1OwQEAyUM9t6:-NyQGwnR1OwQEAyUM9t7:b-vyizhn) ([raw file](https://github.com/starkware-libs/cairo/blob/96b94a92b009f7bc4f75be86516f7a5f68619ec2/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L152)):*
> ```XML
>         .group(ArgGroup::new("input").args(["fullnode-url", "input-files"]).required(true))
>         .group(ArgGroup::new("libfuncs").args(["allowed-libfuncs-list-name", "allowed-libfuncs-list-file"]));
>     let args: Args = res.get_matches().into();
> ```

Extract to function.



_Code quote:_
```XML
    let res = Command::new("cmd").about(formatdoc!(
        "
        Runs validation on existing contract classes to make sure they are still valid and compilable.

        Gets one of two different inputs:
        1. If fullnode_url is provided, it reads the contract classes from the fullnode.
        2. If fullnode_url is not provided, it reads the contract classes from the input files.

        Outputs one of two different outputs:
        1. If class_info_output_file is provided, it writes the classes to the file.
        2. If class_info_output_file is not provided, it returns the report of the runs over the processes of the classes."))
        .arg(arg!(["input-files"] "The input files with declared classes info"))
        .arg(arg!(--"allowed-libfuncs-list-name" <String> "The allowed libfuncs list to use (default: most recent audited list)."))
        .arg(arg!(--"allowed-libfuncs-list-file" <File> "A file of the allowed libfuncs list to use."))
        .arg(arg!(--"override-version" <String> "Sierra version to override to prior to compilation."))
        .arg(arg!(--"max-bytecode-size" <usize> "The max bytecode size.").default_value("180000").value_parser(value_parser!(usize)))
        .arg(arg!(--"fullnode-url" <URL> "The url of the rpc server, if provided - Sierra classes would be read from it, and no input files should be provided."))
        .arg(arg!(--"start-block" <u64> "The start block of the declared Sierra classes to test.").value_parser(value_parser!(u64)))
        .arg(arg!(--"end-block" <u64> "The end block of the declared Sierra classes to test.").value_parser(value_parser!(u64)))
        .arg(arg!(--"class-info-output-file" <String> "The output file to write the Sierra classes into."))
        .group(ArgGroup::new("fullnode").args(["fullnode-url"]).requires_all(["start-block", "end-block"]))
        .group(ArgGroup::new("input").args(["fullnode-url", "input-files"]).required(true))
        .group(ArgGroup::new("libfuncs").args(["allowed-libfuncs-list-name", "allowed-libfuncs-list-file"]));
    let args: Args = res.get_matches().into();
```


<!-- Sent from Reviewable.io -->

2024-05-21 14:35 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQH893As3UdIEvoehz:-NyQOwJA4MGMEv86myFg:bljlpt8) ([raw file](https://github.com/starkware-libs/cairo/blob/96b94a92b009f7bc4f75be86516f7a5f68619ec2/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L21)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

doc
</blockquote></details>

Not sure I understand what the comment is here
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQHEuv9xUky4YL3OMi:-NyQYu9tESLVS9UoK86D:bgjcl5q) ([raw file](https://github.com/starkware-libs/cairo/blob/96b94a92b009f7bc4f75be86516f7a5f68619ec2/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L136)):*
> ```XML
>         1. If fullnode_url is provided, it reads the contract classes from the fullnode.
>         2. If fullnode_url is not provided, it reads the contract classes from the input files.
>         
> ```

I am not sure about the comment here; I removed the blank line that was there.
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQHO5A8dWBOUr1o_xv:-NyQMvDH20apbc0g9_23:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/96b94a92b009f7bc4f75be86516f7a5f68619ec2/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L151)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

break long lines.
</blockquote></details>

Done.
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQGwnR1OwQEAyUM9t6:-NyQMZbI6oGhg8wHICii:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/96b94a92b009f7bc4f75be86516f7a5f68619ec2/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L152)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Extract to function.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-21 14:49 UTC, gilbens-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @orizi and @Tomer-StarkWare)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQH893As3UdIEvoehz:-NyQbqQM2CqS0QsXbhvP:b-7x9vjb) ([raw file](https://github.com/starkware-libs/cairo/blob/96b94a92b009f7bc4f75be86516f7a5f68619ec2/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L21)):*
<details><summary><i>Previously, Tomer-StarkWare wrote…</i></summary><blockquote>

Not sure I understand what the comment is here
</blockquote></details>

Add documentation of the struct, something like:
`/// The input args of the CLI tool.`
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQHEuv9xUky4YL3OMi:-NyQc5Q_9coIXDmwbr5R:b-c48pio) ([raw file](https://github.com/starkware-libs/cairo/blob/96b94a92b009f7bc4f75be86516f7a5f68619ec2/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L136)):*
<details><summary><i>Previously, Tomer-StarkWare wrote…</i></summary><blockquote>

I am not sure about the comment here; I removed the blank line that was there.
</blockquote></details>

I meant to remove the spaces that were in that line, but it works anyway.
But if you removed you didn't pushed.


<!-- Sent from Reviewable.io -->

2024-05-21 14:54 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQGwnR1OwQEAyUM9t6:-NyQc3Rt8hVixfhVGIob:b-x2ru9l) ([raw file](https://github.com/starkware-libs/cairo/blob/96b94a92b009f7bc4f75be86516f7a5f68619ec2/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L152)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no it isnt.
</blockquote></details>

Yes, that's right, I didn't publish the new PR since not all comments were handled; I marked it mainly to myself and published it to show that I was not stuck on it. From now on I'll publish the "Done" comments only with a new PR


<!-- Sent from Reviewable.io -->

2024-05-21 15:01 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQH893As3UdIEvoehz:-NyQdbyx9EeeMrTFLC8q:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/96b94a92b009f7bc4f75be86516f7a5f68619ec2/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L21)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Add documentation of the struct, something like:
`/// The input args of the CLI tool.`
</blockquote></details>

Done.
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQHQ_kCrObP5e-NFob:-NyQeznsBZ7rXq2a9UAs:b4xpwmq) ([raw file](https://github.com/starkware-libs/cairo/blob/96b94a92b009f7bc4f75be86516f7a5f68619ec2/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L54)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

keep same as before - as path args if possible.
</blockquote></details>

Not handled yet


<!-- Sent from Reviewable.io -->

2024-05-21 15:07 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQHQ_kCrObP5e-NFob:-NyQgHef-7wqNSiCRmNP:b4xusur) ([raw file](https://github.com/starkware-libs/cairo/blob/96b94a92b009f7bc4f75be86516f7a5f68619ec2/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L54)):*
<details><summary><i>Previously, Tomer-StarkWare wrote…</i></summary><blockquote>

Not handled yet
</blockquote></details>

so don't reply.
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQGwnR1OwQEAyUM9t6:-NyQgLe93GZj9h0gk64j:b4xusur) ([raw file](https://github.com/starkware-libs/cairo/blob/96b94a92b009f7bc4f75be86516f7a5f68619ec2/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L152)):*
<details><summary><i>Previously, Tomer-StarkWare wrote…</i></summary><blockquote>

Yes, that's right, I didn't publish the new PR since not all comments were handled; I marked it mainly to myself and published it to show that I was not stuck on it. From now on I'll publish the "Done" comments only with a new PR
</blockquote></details>

so don't reply.
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQgFu23HevS8c6N58j:-NyQgFu23HevS8c6N58k:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9cf6937e46bec24d6e1494fb870530b1bcf3951e/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L21)):*
> ```XML
> 
> const NUM_OF_PROCESSORS: usize = 32;
> /// The input args of the CLI tool.
> ```





_Suggestion:_
```XML
const NUM_OF_PROCESSORS: usize = 32;

/// The input args of the CLI tool.
```


<!-- Sent from Reviewable.io -->

2024-05-21 16:12 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQHQ_kCrObP5e-NFob:-NyQux1g3smyZpkka6lV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/96b94a92b009f7bc4f75be86516f7a5f68619ec2/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L54)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so don't reply.
</blockquote></details>

Done.
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQHEuv9xUky4YL3OMi:-NyQv5P5CnoIT63-0dX-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/96b94a92b009f7bc4f75be86516f7a5f68619ec2/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L136)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

I meant to remove the spaces that were in that line, but it works anyway.
But if you removed you didn't pushed.
</blockquote></details>

Done.
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQgFu23HevS8c6N58j:-NyQv-UdDAbUvoYmteCV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9cf6937e46bec24d6e1494fb870530b1bcf3951e/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L21)):*
> ```XML
> 
> const NUM_OF_PROCESSORS: usize = 32;
> /// The input args of the CLI tool.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-05-21 16:24 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @Tomer-StarkWare)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQxoPj2EMqgotMhSHO:-NyQxoPj2EMqgotMhSHP:bjrggy6) ([raw file](https://github.com/starkware-libs/cairo/blob/f6030257a5d7713c8e565adba1d87639b5828324/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L65)):*
> ```XML
>             start_block: matches.get_one::<u64>("start-block").copied(),
>             end_block: matches.get_one::<u64>("end-block").copied(),
>             class_info_output_file: matches
> ```

may I ask why are you mixing builder style here when existing code used derive one?


<!-- Sent from Reviewable.io -->

2024-05-21 16:29 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware, @mkaput, and @Tomer-StarkWare)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQxoPj2EMqgotMhSHO:-NyQyutK2b09m2a1nciq:blvaweu) ([raw file](https://github.com/starkware-libs/cairo/blob/f6030257a5d7713c8e565adba1d87639b5828324/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L65)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

may I ask why are you mixing builder style here when existing code used derive one?
</blockquote></details>

Agreed https://github.com/clap-rs/clap/blob/v3.1.14/examples/tutorial_derive/04_03_relations.rs - example on how to use arg groups in derive context.


<!-- Sent from Reviewable.io -->

2024-05-21 16:32 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @Tomer-StarkWare)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQxoPj2EMqgotMhSHO:-NyQzhZl8GmwY02Nfmvx:b-5bhpny) ([raw file](https://github.com/starkware-libs/cairo/blob/f6030257a5d7713c8e565adba1d87639b5828324/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L65)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Agreed https://github.com/clap-rs/clap/blob/v3.1.14/examples/tutorial_derive/04_03_relations.rs - example on how to use arg groups in derive context.
</blockquote></details>

TBH Clap docs happen to be lacking here. Scarb's arguments might be a better showcase of what's possible (because to me it looks like everything you've done here is possible)

https://github.com/software-mansion/scarb/blob/main/scarb/src/bin/scarb/args.rs


<!-- Sent from Reviewable.io -->

2024-05-21 16:34 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @mkaput, @orizi, and @Tomer-StarkWare)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQxoPj2EMqgotMhSHO:-NyR-9iJ9q1rl4ugXg5d:b-wjllao) ([raw file](https://github.com/starkware-libs/cairo/blob/f6030257a5d7713c8e565adba1d87639b5828324/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L65)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

TBH Clap docs happen to be lacking here. Scarb's arguments might be a better showcase of what's possible (because to me it looks like everything you've done here is possible)

https://github.com/software-mansion/scarb/blob/main/scarb/src/bin/scarb/args.rs
</blockquote></details>

My bad, I've seen somewhere that grouping is not supported in parser, maybe it was for an older version.


<!-- Sent from Reviewable.io -->

2024-05-22 10:58 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQGwnR1OwQEAyUM9t6:-NyUwx_v8hFI44Bsb4EK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/96b94a92b009f7bc4f75be86516f7a5f68619ec2/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L152)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

so don't reply.
</blockquote></details>

Done.
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyQxoPj2EMqgotMhSHO:-NyUwuiOBYljKArEb0ev:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f6030257a5d7713c8e565adba1d87639b5828324/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L65)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

My bad, I've seen somewhere that grouping is not supported in parser, maybe it was for an older version.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-22 11:00 UTC, gilbens-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598#-:-NyUxO8WCHUWUjQbVLxO:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-05-22 11:36 UTC, orizi requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: all files reviewed, 1 unresolved discussion (waiting on @Tomer-StarkWare)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 29 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyV4WlO3MNAGAxlDGcW:-NyV4WlO3MNAGAxlDGcX:b-5omp2f) ([raw file](https://github.com/starkware-libs/cairo/blob/047d4055212244fec60c586a29550e771f87feec/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L29)):*
> ```XML
> ///     1. If class_info_output_file is provided, it writes the classes to the file.
> ///     2. If class_info_output_file is not provided, it returns the report of the runs over the
> ///        processes of the classes.
> ```

and so on.



_Suggestion:_
```XML
/// Runs validation on existing contract classes to make sure they are still valid and
/// compilable.
///     Gets one of two different inputs:
///     1. If fullnode_url is provided, it reads the contract classes from the fullnode.
///     2. If fullnode_url is not provided, it reads the contract classes from the input files.
///     Outputs one of two different outputs:
///     1. If class_info_output_file is provided, it writes the classes to the file.
///     2. If class_info_output_file is not provided, it returns the report of the runs over the
///        processes of the classes.
```


<!-- Sent from Reviewable.io -->

2024-05-22 12:18 UTC, orizi requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: all files reviewed, 1 unresolved discussion (waiting on @Tomer-StarkWare)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 89 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyVDSez8B5VNM3TFUFK:-NyVDSez8B5VNM3TFUFL:b2nid92) ([raw file](https://github.com/starkware-libs/cairo/blob/d48f8b4c4e265cd9daa02db56d4f8f268b95405a/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L89)):*
> ```XML
>     #[arg(long, value_name = "class_info_output")]
>     class_info_output_file: Option<String>,
> }
> ```

try



_Suggestion:_
```XML
struct Args {
    /// The input files with declared classes info.
    #[arg(
        required_unless_present = "fullnode_url",
        conflicts_with = "fullnode_url",
        conflicts_with = "start_block",
        conflicts_with = "end_block"
    )]
    input_files: Vec<String>,
    /// The allowed libfuncs list to use (default: most recent audited list).
    #[arg(
        long,
        conflicts_with = "allowed_libfuncs_list_file"
    )]
    allowed_libfuncs_list_name: Option<String>,
    /// A file of the allowed libfuncs list to use.
    #[arg(
        long,
        conflicts_with = "allowed_libfuncs_list_name"
    )]
    allowed_libfuncs_list_file: Option<String>,
    /// Sierra version to override to prior to compilation.
    #[arg(long)]
    override_version: Option<String>,
    /// The max bytecode size.
    #[arg(long, default_value_t = 180000)]
    max_bytecode_size: usize,
    /// The url of the rpc server, if provided - Sierra classes would be read from it, and no input
    /// files should be provided.
    #[arg(
        long,
        requires_all = &["start-block", "end-block"],
        required_unless_present = "input-files",
        conflicts_with = "input-files"
    )]
    fullnode_url: Option<String>,
    /// The start block of the declared Sierra classes to test.
    #[arg(
        long,
        requires_all = &["fullnode-url", "end-block"]
    )]
    start_block: Option<u64>,
    /// The end block of the declared Sierra classes to test.
    #[arg(
        long,
        requires_all = &["fullnode-url", "start-block"]
    )]
    end_block: Option<u64>,
    /// The output file to write the Sierra classes into.
    #[arg(long)]
    class_info_output_file: Option<String>,
}
```


<!-- Sent from Reviewable.io -->

2024-05-22 12:25 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: all files reviewed, 3 unresolved discussions (waiting on @Tomer-StarkWare)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 21 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyV2CtY3W6_peyJvvn3:-NyV2CtY3W6_peyJvvn4:bc4bei) ([raw file](https://github.com/starkware-libs/cairo/blob/047d4055212244fec60c586a29550e771f87feec/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L21)):*
> ```XML
> const NUM_OF_PROCESSORS: usize = 32;
> 
> ///     Runs validation on existing contract classes to make sure they are still valid and
> ```

why is this indented so much?
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 57 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyV2MgT8S5mVcx4FJ2b:-NyV2MgU5yl0Rcno3Jh5:b-4b8jzm) ([raw file](https://github.com/starkware-libs/cairo/blob/047d4055212244fec60c586a29550e771f87feec/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L57)):*
> ```XML
>     allowed_libfuncs_list_file: Option<String>,
>     /// Sierra version to override to prior to compilation.
>     #[arg(long, value_name = "override_version")]
> ```

nit, you're inconsistent. sometimes you use `_`, sometimes `-`

I think the most popular convention is `OVERRIDE_VERSION`? But I don't want to enforce anything on you


<!-- Sent from Reviewable.io -->

2024-05-22 12:26 UTC, mkaput reviewed
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: all files reviewed, 3 unresolved discussions (waiting on @Tomer-StarkWare)



<!-- Sent from Reviewable.io -->

2024-05-22 12:33 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 57 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyV2MgT8S5mVcx4FJ2b:-NyVHRs9DsH0NT0niX-S:b9tyaol) ([raw file](https://github.com/starkware-libs/cairo/blob/047d4055212244fec60c586a29550e771f87feec/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L57)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

nit, you're inconsistent. sometimes you use `_`, sometimes `-`

I think the most popular convention is `OVERRIDE_VERSION`? But I don't want to enforce anything on you
</blockquote></details>

Thanks for the comment, fixed.
___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 89 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyVDSez8B5VNM3TFUFK:-NyVHOsk-g2ZjkH0Dk4P:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d48f8b4c4e265cd9daa02db56d4f8f268b95405a/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L89)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

try
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-22 12:40 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598#-:-NyVJPG6-c3_5F1ZyLmX:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput and @Tomer-StarkWare)



<!-- Sent from Reviewable.io -->

2024-05-22 12:45 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[`crates/bin/starknet-sierra-upgrade-validate/src/main.rs` line 21 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5598#-NyV2CtY3W6_peyJvvn3:-NyVKMt59UvLwtugIqZ3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/047d4055212244fec60c586a29550e771f87feec/crates/bin/starknet-sierra-upgrade-validate/src/main.rs#L21)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

why is this indented so much?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-22 13:06 UTC, mkaput approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)



<!-- Sent from Reviewable.io -->

2024-05-22 13:06 UTC, mkaput approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5598)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Tomer-StarkWare)



<!-- Sent from Reviewable.io -->

2024-05-22 13:16 UTC, merged