LS: Improve fixture format of hover tests
starkware-libs/cairo pull request #5779
Opened 2024-06-11 16:37 UTC by mkaput

1. Caret is not represented as inline marker instead of underline of
character afterward.
2. Added information about highlighted selection.
This will start becoming noticeable in subsequent PRs.

2024-06-11 18:18 UTC, orizi requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5779)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-language-server/tests/e2e/hover.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5779#-O-7WJ8V3bTj0EMFOikN:-O-7WJ8V3bTj0EMFOikO:bz5dch3) ([raw file](https://github.com/starkware-libs/cairo/blob/5cc2e5ea247ebdbf33c7cc1ff4e6a90d4f208744/crates/cairo-lang-language-server/tests/e2e/hover.rs#L46)):*
> ```XML
>     _args: &OrderedHashMap<String, String>,
> ) -> TestRunnerResult {
>     use lsp_types::*;
> ```

are there really that much to justify a *?


<!-- Sent from Reviewable.io -->

2024-06-12 05:07 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5779)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-language-server/tests/e2e/hover.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5779#-O-7WJ8V3bTj0EMFOikN:-O-9psqe1UYKARmRVPfe:bajhx6c) ([raw file](https://github.com/starkware-libs/cairo/blob/5cc2e5ea247ebdbf33c7cc1ff4e6a90d4f208744/crates/cairo-lang-language-server/tests/e2e/hover.rs#L46)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

are there really that much to justify a *?
</blockquote></details>

Indeed, not that much. I just muscle-memorized using `*`.

Done.


<!-- Sent from Reviewable.io -->

2024-06-12 11:10 UTC, orizi requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5779)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-language-server/tests/e2e/hover.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5779#-O-B8-r7Ca_gKNvepfJN:-O-B8-r7Ca_gKNvepfJO:b-ldgtph) ([raw file](https://github.com/starkware-libs/cairo/blob/84a3798b840e1e1e2b9db4bb460efdb25600d9ea/crates/cairo-lang-language-server/tests/e2e/hover.rs#L24)):*
> ```XML
> 
> fn caps(base: ClientCapabilities) -> ClientCapabilities {
>     use tower_lsp::lsp_types::*;
> ```

probably remove as well if already here.



_Code quote:_
```XML
    use tower_lsp::lsp_types::*;
```


<!-- Sent from Reviewable.io -->

2024-06-13 07:38 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5779)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-language-server/tests/e2e/hover.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5779#-O-B8-r7Ca_gKNvepfJN:-O-FXBvb5nA2rwiBEoHC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/84a3798b840e1e1e2b9db4bb460efdb25600d9ea/crates/cairo-lang-language-server/tests/e2e/hover.rs#L24)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

probably remove as well if already here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-13 07:49 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5779#-:-O-FZlk3EWV_fR8go0n9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2024-06-13 08:50 UTC, merged