TODO
starkware-libs/cairo pull request #5785
Opened 2024-06-12 16:52 UTC by liorgold2

2024-06-26 06:45 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5785)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 202 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5785#-O0I4lG04llKLvgEg99Q:-O0I4lG04llKLvgEg99R:bkig89g) ([raw file](https://github.com/starkware-libs/cairo/blob/8050965b1ebc7c3faf3d11793758cba0227439d6/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L202)):*
> ```XML
>         BoundedIntDivRemAlgorithm::try_new(&lhs_range, &rhs_range)
>             .ok_or(SpecializationError::UnsupportedGenericArg)?;
>         // TODO: Add a require that rhs_range.upper >= 2 (also assumed below).
> ```

seems to be done right under.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs` line 466 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5785#-O0I4qfXBso6QAtN12aI:-O0I4qfXBso6QAtN12aJ:b-w5634m) ([raw file](https://github.com/starkware-libs/cairo/blob/8050965b1ebc7c3faf3d11793758cba0227439d6/crates/cairo-lang-sierra/src/extensions/modules/bounded_int.rs#L466)):*
> ```XML
>             .ok_or(SpecializationError::UnsupportedGenericArg)?;
>         let prime: BigInt = Felt252::prime().to_bigint().unwrap();
>         // The following is not really necessary for this function. Once we support ranges
> ```

Discussed f2f - adding a block here is just an extra safety measure - can be removed in the future once these ranges actually exist.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5785#-O0I5BME3RhT17D81DM7:-O0I5BME3RhT17D81DM8:b-47cs80) ([raw file](https://github.com/starkware-libs/cairo/blob/8050965b1ebc7c3faf3d11793758cba0227439d6/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L145)):*
> ```XML
>                 droppable: false,
>                 storable: false,
>                 zero_sized: false, // TODO: Should be true?
> ```

it isn't storable - so shouldn't actually affect anything.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5785#-O0IA9LU7nyKsqB7uQgs:-O0IA9LU7nyKsqB7uQgt:bxfbwhn) ([raw file](https://github.com/starkware-libs/cairo/blob/8050965b1ebc7c3faf3d11793758cba0227439d6/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L217)):*
> ```XML
> 
> // Represents the action of adding two fields elements in the circuits builtin.
> // TODO: Can we share code between gates? (including inv?)
> ```

done.
https://reviewable.io/reviews/starkware-libs/cairo/5893
___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 1416 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5785#-O0IAG-R9TUFxMWo9JiG:-O0IAG-R9TUFxMWo9JiH:bberbdf) ([raw file](https://github.com/starkware-libs/cairo/blob/8050965b1ebc7c3faf3d11793758cba0227439d6/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L1416)):*
> ```XML
>                 .to_usize()
>                 .ok_or(SpecializationError::UnsupportedGenericArg)?;
>             // TODO: panic if idx is already in inputs.
> ```

done right under.
___
*[`crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs` line 510 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5785#-O0IAI5a8Nbk1DLKgkBh:-O0IAI5a8Nbk1DLKgkBi:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/8050965b1ebc7c3faf3d11793758cba0227439d6/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs#L510)):*
> ```XML
>         assert guarantee = *(rc96++);
>     }
>     // TODO: Check why the automatic cost verification is not working (?). Is it becaues rc96 is like
> ```

done.
___
*[`crates/cairo-lang-sierra-type-size/src/lib.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5785#-O0IALJG-EwExPBAQyPo:-O0IALJG-EwExPBAQyPp:b-afk3ft) ([raw file](https://github.com/starkware-libs/cairo/blob/8050965b1ebc7c3faf3d11793758cba0227439d6/crates/cairo-lang-sierra-type-size/src/lib.rs#L105)):*
> ```XML
>             | CoreTypeConcrete::Circuit(CircuitTypeConcrete::MulModGate(_))
>             | CoreTypeConcrete::Circuit(CircuitTypeConcrete::SubModGate(_)) => continue,
>             // TODO: What's the difference between using continue and setting their size to 0?
> ```

makes sure it is not storable.


<!-- Sent from Reviewable.io -->

2024-06-26 08:17 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5785)* status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5785#-O0IbX9I5B0keSkTzQqb:-O0IbX9I5B0keSkTzQqc:b-7rl0jd) ([raw file](https://github.com/starkware-libs/cairo/blob/8050965b1ebc7c3faf3d11793758cba0227439d6/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L135)):*
> ```XML
>             .to_usize()
>             .ok_or(SpecializationError::UnsupportedGenericArg)?;
>         // TODO: Refactor TypeInfo{...} into a function and use in the other 4 gates.
> ```

done.


<!-- Sent from Reviewable.io -->

2024-07-01 07:22 UTC, liorgold2 reviewed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5785)* status: all files reviewed, 9 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 1296 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5785#-O0h9z_L0sMm7BPVzrd5:-O0h9z_L0sMm7BPVzrd6:bfhcj3g) ([raw file](https://github.com/starkware-libs/cairo/blob/8050965b1ebc7c3faf3d11793758cba0227439d6/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L1296)):*
> ```XML
>     outputs_tuple_ty: &ConcreteTypeId,
> ) -> Result<CircuitInfo, SpecializationError> {
>     // TODO: Consider moving the validate_output_tuple logic here.
> ```

Is this done?


<!-- Sent from Reviewable.io -->

2024-07-01 07:25 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-sierra/src/extensions/modules/circuit.rs` line 1296 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5785#-O0h9z_L0sMm7BPVzrd5:-O0hArHiCNxEKtjrsHjM:b2nign6) ([raw file](https://github.com/starkware-libs/cairo/blob/8050965b1ebc7c3faf3d11793758cba0227439d6/crates/cairo-lang-sierra/src/extensions/modules/circuit.rs#L1296)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Is this done?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2026-07-05 08:45 UTC, closed without merging