Add compiler flag to disable inlining
starkware-libs/cairo pull request #5911
Opened 2024-06-28 08:12 UTC by javra

2024-06-28 08:40 UTC, orizi requested changes
> Reviewed 6 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @javra)

___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5911#-O0Szfep6SKDuR33-IKE:-O0Szfeq9XUIueTjqQGU:b-e01xor) ([raw file](https://github.com/starkware-libs/cairo/blob/1287ab6163b7d01e4a42646dfe8fbc27b019f67e/crates/cairo-lang-lowering/src/inline/mod.rs#L68)):*
> ```XML
>     )?;
> 
>     Ok(match config {
> ```

Move the query out of the match.
Ok(if db.optconfig().disable..() { matches!(config, Always(_)) } else .....


<!-- Sent from Reviewable.io -->

2024-06-28 08:47 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @javra and @orizi)

___
*[`crates/bin/cairo-compile/src/main.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5911#-O0T0AYY4cL-7gHPNzKr:-O0T0AYY4cL-7gHPNzKs:bduzp50) ([raw file](https://github.com/starkware-libs/cairo/blob/1287ab6163b7d01e4a42646dfe8fbc27b019f67e/crates/bin/cairo-compile/src/main.rs#L27)):*
> ```XML
>     /// Disables inlining functions
>     #[arg(short, long, default_value_t = false)]
>     disable_inlining: bool,
> ```

I don't feel this is a good representation of the property here:
1. It's negated.
2. I feel `true`/`false` may not be enough cases.

What do you think about using an enum here and in `CompilerConfig`? Say

```rust
#[derive(Copy, Clone, Debug, Default, PartialEq, Eq)]
enum IniliningStrategy {
    #[default]
    Default,
    Avoid, // Future case I can imagine, allow inline(always) but forbid others.
    Forbid
}
```


<!-- Sent from Reviewable.io -->

2024-06-28 08:48 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @javra and @orizi)

___
*[`crates/bin/cairo-compile/src/main.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5911#-O0T0AYY4cL-7gHPNzKr:-O0T1-hL0ty70oETZ7Be:brnmn1a) ([raw file](https://github.com/starkware-libs/cairo/blob/1287ab6163b7d01e4a42646dfe8fbc27b019f67e/crates/bin/cairo-compile/src/main.rs#L27)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I don't feel this is a good representation of the property here:
1. It's negated.
2. I feel `true`/`false` may not be enough cases.

What do you think about using an enum here and in `CompilerConfig`? Say

```rust
#[derive(Copy, Clone, Debug, Default, PartialEq, Eq)]
enum IniliningStrategy {
    #[default]
    Default,
    Avoid, // Future case I can imagine, allow inline(always) but forbid others.
    Forbid
}
```
</blockquote></details>

Oh, just noticed there's `InliningConfiguration` enum already in the codebase -- reuse it


<!-- Sent from Reviewable.io -->

2024-06-28 08:51 UTC, javra commented
> Oh, just noticed there's `InliningConfiguration` enum already in the codebase -- reuse it

Where? `git grep` doesn't find it...

2024-06-28 08:52 UTC, javra commented
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911)_ status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @javra and @orizi)
> 
> _[`crates/bin/cairo-compile/src/main.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5911#-O0T0AYY4cL-7gHPNzKr:-O0T0AYY4cL-7gHPNzKs:bduzp50) ([raw file](https://github.com/starkware-libs/cairo/blob/1287ab6163b7d01e4a42646dfe8fbc27b019f67e/crates/bin/cairo-compile/src/main.rs#L27)):_
> 
> > ```
> >     /// Disables inlining functions
> >     #[arg(short, long, default_value_t = false)]
> >     disable_inlining: bool,
> > ```
> 
> I don't feel this is a good representation of the property here:
> 
>     1. It's negated.
> 
>     2. I feel `true`/`false` may not be enough cases.
> 
> 
> What do you think about using an enum here and in `CompilerConfig`? Say
> 
> ```rust
> #[derive(Copy, Clone, Debug, Default, PartialEq, Eq)]
> enum IniliningStrategy {
>     #[default]
>     Default,
>     Avoid, // Future case I can imagine, allow inline(always) but forbid others.
>     Forbid
> }
> ```

Sounds good, like I said in the other discussions, I'd love an option that overrides even the local `inline(always)` annotations.

2024-06-28 09:03 UTC, javra commented
> Oh, just noticed there's `InliningConfiguration` enum already in the codebase -- reuse it

Do the same four options in `InlineConfiguration` make sense as global options as well though? How to reconcile the local vs the global ones then? :thinking:

2024-06-28 09:08 UTC, mkaput reviewed
@javra please use Reviewable in this repository for responding to comments, you can find the button in PR description :) 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911#-:-O0T5LYG05e0nJkXziCm:b40uu8d)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @javra and @orizi)



<!-- Sent from Reviewable.io -->

2024-06-28 11:10 UTC, javra reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-lowering/src/utils.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5911#-O0TWv279BX9_vbeNLnM:-O0TWv279BX9_vbeNLnN:be1mgbm) ([raw file](https://github.com/starkware-libs/cairo/blob/d8659b9a835ecf75892fa97578a5b15e83528764/crates/cairo-lang-lowering/src/utils.rs#L14)):*
> ```XML
> /// Options for the `inlining` arguments
> #[derive(Copy, Clone, Debug, Default, PartialEq, Eq, clap::ValueEnum)]
> pub enum InliningStrategy {
> ```

I put the enum in cairo-lang-lowering::utils, maybe cairo-lang-utils might be the better choice?


<!-- Sent from Reviewable.io -->

2024-06-28 12:43 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @javra and @orizi)

___
*[`crates/cairo-lang-lowering/src/utils.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5911#-O0TWv279BX9_vbeNLnM:-O0TrFwe9HbDEe1Aijr5:b-krboxw) ([raw file](https://github.com/starkware-libs/cairo/blob/d8659b9a835ecf75892fa97578a5b15e83528764/crates/cairo-lang-lowering/src/utils.rs#L14)):*
<details><summary><i>Previously, javra (Jakob von Raumer) wrote…</i></summary><blockquote>

I put the enum in cairo-lang-lowering::utils, maybe cairo-lang-utils might be the better choice?
</blockquote></details>

I think lowering is the good place, but using `clap` in lib-crates is not. 

It'd be best IMO to:

1. copy-paste this enum just with `clap::ValueEnum` to `cairo-compile`
2. add there the following:

```rust
impl From<crate::InliningStrategy> for cairo_lang_lowering::InliningStrategy {
...
}
```


<!-- Sent from Reviewable.io -->

2024-06-28 14:04 UTC, orizi requested changes
> Reviewed 5 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911)* status: 5 of 12 files reviewed, 4 unresolved discussions (waiting on @javra and @mkaput)

___
*[`crates/cairo-lang-lowering/Cargo.toml` line 19 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5911#-O0U8SjBECp3v2gwZ836:-O0U8SjBECp3v2gwZ837:b6xzyg3) ([raw file](https://github.com/starkware-libs/cairo/blob/17c2768ae6bd921127ce5288a174064475297be3/crates/cairo-lang-lowering/Cargo.toml#L19)):*
> ```TOML
> cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "~2.6.4" }
> cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.6.4" }
> clap.workspace = true
> ```

this shouldn't be a dependency of the lowering.
___
*[`crates/cairo-lang-lowering/src/utils.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5911#-O0TWv279BX9_vbeNLnM:-O0U8aDE7wMTahwy3pjw:b-4fwilw) ([raw file](https://github.com/starkware-libs/cairo/blob/d8659b9a835ecf75892fa97578a5b15e83528764/crates/cairo-lang-lowering/src/utils.rs#L14)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I think lowering is the good place, but using `clap` in lib-crates is not. 

It'd be best IMO to:

1. copy-paste this enum just with `clap::ValueEnum` to `cairo-compile`
2. add there the following:

```rust
impl From<crate::InliningStrategy> for cairo_lang_lowering::InliningStrategy {
...
}
```
</blockquote></details>

good suggestion.
___
*[`crates/cairo-lang-lowering/src/utils.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5911#-O0U8xaBCpcxiounilUa:-O0U8xaBCpcxiounilUb:b8g44v5) ([raw file](https://github.com/starkware-libs/cairo/blob/17c2768ae6bd921127ce5288a174064475297be3/crates/cairo-lang-lowering/src/utils.rs#L19)):*
> ```XML
>     /// Inline only in the case of a `inline(always)` annotation
>     Avoid,
>     /// Never inline
> ```

as discussed - this would cause the compiler to crash - so remove this as an option.

you can (in another PR) remove all `inline(always)` from the corelib (aside from 2 probably, and switch them with a simple `inline`.


<!-- Sent from Reviewable.io -->

2024-06-28 14:38 UTC, javra reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911)* status: 5 of 12 files reviewed, 4 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-lowering/src/utils.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/cairo/5911#-O0TWv279BX9_vbeNLnM:-O0UGMR-AljJuRJUx5mX:bfhfxul) ([raw file](https://github.com/starkware-libs/cairo/blob/d8659b9a835ecf75892fa97578a5b15e83528764/crates/cairo-lang-lowering/src/utils.rs#L14)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

good suggestion.
</blockquote></details>

Ah yes, that's a good solution :+1: 
___
*[`crates/cairo-lang-lowering/src/utils.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5911#-O0U8xaBCpcxiounilUa:-O0UGj-28-juGqInkRS2:b8uro3n) ([raw file](https://github.com/starkware-libs/cairo/blob/17c2768ae6bd921127ce5288a174064475297be3/crates/cairo-lang-lowering/src/utils.rs#L19)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

as discussed - this would cause the compiler to crash - so remove this as an option.

you can (in another PR) remove all `inline(always)` from the corelib (aside from 2 probably, and switch them with a simple `inline`.
</blockquote></details>

Thanks, can you point me towards which ones are the 2 I won't be able to remove?
___
*[`crates/cairo-lang-lowering/src/inline/mod.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5911#-O0Szfep6SKDuR33-IKE:-O0UG_FYAugY7GOGUtO8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1287ab6163b7d01e4a42646dfe8fbc27b019f67e/crates/cairo-lang-lowering/src/inline/mod.rs#L68)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Move the query out of the match.
Ok(if db.optconfig().disable..() { matches!(config, Always(_)) } else .....
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-28 14:55 UTC, javra reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911)* status: 3 of 12 files reviewed, 3 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-lowering/Cargo.toml` line 19 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5911#-O0U8SjBECp3v2gwZ836:-O0UL6oEDkVJRX1OXAUF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/17c2768ae6bd921127ce5288a174064475297be3/crates/cairo-lang-lowering/Cargo.toml#L19)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this shouldn't be a dependency of the lowering.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-30 08:24 UTC, orizi requested changes
> Reviewed 4 of 12 files at r2, 4 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911)* status: all files reviewed, 1 unresolved discussion (waiting on @javra)

___
*[`crates/cairo-lang-lowering/src/utils.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5911#-O0U8xaBCpcxiounilUa:-O0cEfTz49MaHzfWQJj7:b-splsis) ([raw file](https://github.com/starkware-libs/cairo/blob/17c2768ae6bd921127ce5288a174064475297be3/crates/cairo-lang-lowering/src/utils.rs#L19)):*
<details><summary><i>Previously, javra (Jakob von Raumer) wrote…</i></summary><blockquote>

Thanks, can you point me towards which ones are the 2 I won't be able to remove?
</blockquote></details>

IIRC - basically only `Option::unwrap` - but not for this PR in any case.


<!-- Sent from Reviewable.io -->

2024-07-01 07:20 UTC, javra reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/utils.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5911#-O0U8xaBCpcxiounilUa:-O0h9YEb6koUpyGCEaZz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/17c2768ae6bd921127ce5288a174064475297be3/crates/cairo-lang-lowering/src/utils.rs#L19)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

IIRC - basically only `Option::unwrap` - but not for this PR in any case.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-01 08:21 UTC, piotmag769 reviewed
Just making sure - you don't need this flag for tests compilation, do you?

> Reviewed 7 of 12 files at r2, 4 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911#-:-O0hNA5P5BBbYUeBaH-p:b-l41th5)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-07-01 08:23 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911#-:-O0hO0vx83erICybNeCC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @javra)



<!-- Sent from Reviewable.io -->

2024-07-01 09:11 UTC, javra reviewed
@piotmag769 Correct

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911#-:-O0hYm0U4oHWvwWQ0Q8m:b-tck9zq)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @javra)



<!-- Sent from Reviewable.io -->

2024-07-01 12:36 UTC, mkaput requested changes
> Reviewed 7 of 12 files at r2, 4 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911)* status: all files reviewed, 2 unresolved discussions (waiting on @javra)

___
*[`crates/bin/cairo-compile/src/main.rs` line 18 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5911#-O0iHVtt1HPmswmGwpuw:-O0iHVtu1B375Tkblr43:b-345iwb) ([raw file](https://github.com/starkware-libs/cairo/blob/dc152cef44ee4579269ff82d70f56927fd521cb3/crates/bin/cairo-compile/src/main.rs#L18)):*
> ```XML
>     /// Inline only in the case of a `inline(always)` annotation
>     Avoid,
> }
> ```

nitpick



_Suggestion:_
```XML
/// Options for the `inlining` arguments.
#[derive(Copy, Clone, Debug, Default, PartialEq, Eq, clap::ValueEnum)]
pub enum InliningStrategy {
    /// Do not override inlining strategy.
    #[default]
    Default,
    /// Inline only in the case of a `inline(always)` annotation.
    Avoid,
}
```
___
*[`crates/bin/cairo-compile/src/main.rs` line 44 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5911#-O0iHbIg7xIhHcYucViI:-O0iHbIg7xIhHcYucViJ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/dc152cef44ee4579269ff82d70f56927fd521cb3/crates/bin/cairo-compile/src/main.rs#L44)):*
> ```XML
>     #[arg(short, long, default_value_t = false)]
>     replace_ids: bool,
>     /// Overrides inlining behavior
> ```





_Suggestion:_
```XML
    /// Overrides inlining behavior.
```


<!-- Sent from Reviewable.io -->

2024-07-01 13:01 UTC, javra reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @mkaput, @orizi, and @piotmag769)

___
*[`crates/bin/cairo-compile/src/main.rs` line 18 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5911#-O0iHVtt1HPmswmGwpuw:-O0iNeE-CjtP5ZQt95ei:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dc152cef44ee4579269ff82d70f56927fd521cb3/crates/bin/cairo-compile/src/main.rs#L18)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

nitpick
</blockquote></details>

Done.
___
*[`crates/bin/cairo-compile/src/main.rs` line 44 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5911#-O0iHbIg7xIhHcYucViI:-O0iNexmCNNeHVQcpJFn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/dc152cef44ee4579269ff82d70f56927fd521cb3/crates/bin/cairo-compile/src/main.rs#L44)):*
> ```XML
>     #[arg(short, long, default_value_t = false)]
>     replace_ids: bool,
>     /// Overrides inlining behavior
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-07-01 13:04 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911#-:-O0iOTK07l3egFPy5J3R:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @javra)



<!-- Sent from Reviewable.io -->

2024-07-01 13:11 UTC, javra reviewed
> Reviewed 7 of 12 files at r2, 2 of 5 files at r4, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @javra)



<!-- Sent from Reviewable.io -->

2024-07-01 13:42 UTC, mkaput approved these changes
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @javra)



<!-- Sent from Reviewable.io -->

2024-07-01 14:37 UTC, orizi approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5911)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @javra)



<!-- Sent from Reviewable.io -->

2024-07-02 08:25 UTC, merged