Add option to include statements functions in artifacts from test compilation
starkware-libs/cairo pull request #5913
Opened 2024-06-28 17:01 UTC by piotmag769

Needed for Scarb to be able to produce the mappings in test artifacts as well (for purposes of `cairo-profiler`).

2024-06-29 13:14 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5913)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @maciektr and @piotmag769)

___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5913#-O0Z7SNo5tk1o0gLaa0a:-O0Z7SNo5tk1o0gLaa0b:b-cijyam) ([raw file](https://github.com/starkware-libs/cairo/blob/1f7d7c533c79b80bd291f988f17fb10a9ad85dc9/crates/cairo-lang-test-plugin/src/lib.rs#L50)):*
> ```XML
> /// Configuration for test compilation.
> pub struct TestCompilationConfig {
>     pub starknet: bool,
> ```

doc members.
___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5913#-O0Z7V3M0Bq4FgXHyeei:-O0Z7V3M0Bq4FgXHyeej:bljob9k) ([raw file](https://github.com/starkware-libs/cairo/blob/1f7d7c533c79b80bd291f988f17fb10a9ad85dc9/crates/cairo-lang-test-plugin/src/lib.rs#L58)):*
> ```XML
> /// # Arguments
> /// * `db` - Preloaded compilation database.
> /// * `starknet` - Add the starknet contracts to the compiled tests.
> ```

fix doc



_Code quote:_
```XML
/// * `starknet` - Add the starknet contracts to the compiled tests.
```


<!-- Sent from Reviewable.io -->

2024-07-01 08:33 UTC, piotmag769 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5913)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @maciektr and @orizi)

___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5913#-O0Z7SNo5tk1o0gLaa0a:-O0hPk08AZhIyobL90MW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1f7d7c533c79b80bd291f988f17fb10a9ad85dc9/crates/cairo-lang-test-plugin/src/lib.rs#L50)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc members.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-test-plugin/src/lib.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/cairo/5913#-O0Z7V3M0Bq4FgXHyeei:-O0hPkheBTJAxY2tAS5A:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1f7d7c533c79b80bd291f988f17fb10a9ad85dc9/crates/cairo-lang-test-plugin/src/lib.rs#L58)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-01 08:34 UTC, piotmag769 reviewed
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5913)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr and @orizi)



<!-- Sent from Reviewable.io -->

2024-07-01 08:36 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5913#-:-O0hR2tr4IrcG1gLNU27:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @maciektr)



<!-- Sent from Reviewable.io -->

2024-07-01 08:59 UTC, maciektr approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5913)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)



<!-- Sent from Reviewable.io -->

2024-07-01 09:40 UTC, merged