fixed loop capture of snapshoted variables
starkware-libs/cairo pull request #5934
Opened 2024-07-02 11:36 UTC by TomerStarkware

2024-07-02 16:21 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0oEuQx6SAoJJuC0IxY:-O0oEuQx6SAoJJuC0IxZ:bwtj5lw) (no related file):*
Add a test for point 4 at https://github.com/starkware-libs/cairo/issues/2816.

___


<!-- Sent from Reviewable.io -->

2024-07-02 16:21 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0oEuQx6SAoJJuC0IxY:-O0oF2AkDhrMBNoSYONh:b-hkabmw) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Add a test for point 4 at https://github.com/starkware-libs/cairo/issues/2816.
</blockquote></details>

https://github.com/starkware-libs/cairo/issues/2816#issuecomment-1532786354

___


<!-- Sent from Reviewable.io -->

2024-07-03 07:45 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: 20 of 22 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0oEuQx6SAoJJuC0IxY:-O0rYXNPDpz09v4X9Iph:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

https://github.com/starkware-libs/cairo/issues/2816#issuecomment-1532786354
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2024-07-03 08:18 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 306 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0rf5Pz3Xh2qAJRTXHZ:-O0rf5Q-9sDjN9z6x7K5:b-uhzazv) ([raw file](https://github.com/starkware-libs/cairo/blob/6e2321a019da27d72dcd0136c9180078b5a9c4b3/crates/cairo-lang-lowering/src/lower/context.rs#L306)):*
> ```XML
>                 type_id: exprs
>                     .first()
>                     .map_or(TypeLongId::Missing(skip_diagnostic()).intern(ctx.db), |expr| {
> ```

why skip_diagnostic?



_Code quote:_
```XML
skip_diagnostic())
```


<!-- Sent from Reviewable.io -->

2024-07-03 08:49 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: 20 of 22 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`tests/bug_samples/issue2816.cairo` line 2 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0rm8-313TE9lVfF0UQ:-O0rm8-313TE9lVfF0UR:bgjzn5j) ([raw file](https://github.com/starkware-libs/cairo/blob/6e2321a019da27d72dcd0136c9180078b5a9c4b3/tests/bug_samples/issue2816.cairo#L2)):*
> ```Cairo
> 
> fn contains<T,impl TPartialEq: PartialEq<T>,+Drop<T>,+Copy<T>>(ref self: Array<T>, item: T) -> bool {
> ```

do note that cairo fmt still fails.


<!-- Sent from Reviewable.io -->

2024-07-03 08:49 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: 20 of 22 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0oEuQx6SAoJJuC0IxY:-O0rmC5nDMOZyUAhdxUS:bkx75th) (no related file):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

as discussed f2f - some parts are still missing.

___


<!-- Sent from Reviewable.io -->

2024-07-03 08:54 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1124 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0rnJ0j74mn5xKLrdNG:-O0rnJ0j74mn5xKLrdNH:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/6e2321a019da27d72dcd0136c9180078b5a9c4b3/crates/cairo-lang-lowering/src/lower/mod.rs#L1124)):*
> ```XML
>     if expr.ty == lowered.ty(ctx) {
>         return Ok(lowered);
>     }
> ```

remove



_Code quote:_
```XML
    if expr.ty == lowered.ty(ctx) {
        return Ok(lowered);
    }
```


<!-- Sent from Reviewable.io -->

2024-07-03 09:00 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1126 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0roAGq4MmRLQdeTO1g:-O0roAGr92DUqnTy-BkS:b-f7wevb) ([raw file](https://github.com/starkware-libs/cairo/blob/6e2321a019da27d72dcd0136c9180078b5a9c4b3/crates/cairo-lang-lowering/src/lower/mod.rs#L1126)):*
> ```XML
>     }
>     if let LoweredExpr::Member(member_path, _) = &lowered {
>         if let Some(var) = builder.get_ref(ctx, member_path) {
> ```

add something like:



_Suggestion:_
```XML
  // Inside a closure, 'member\_path' might refer to a snapshot of the original variable.
  // If a snapshot is requested inside the closure, we should ignore it.
  if let Some(var) = builder.get_ref(ctx, member_path) {
```


<!-- Sent from Reviewable.io -->

2024-07-03 09:02 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/test_data/loop` line 1009 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0rpBN412oGPsoYuvcg:-O0rpBN412oGPsoYuvch:bqmknuy) ([raw file](https://github.com/starkware-libs/cairo/blob/6e2321a019da27d72dcd0136c9180078b5a9c4b3/crates/cairo-lang-lowering/src/lower/test_data/loop#L1009)):*
> ```
>     let t = T { s: S {} };
>     loop {
>         t.s.f1oo();
> ```

use(@t.s)



_Code quote:_
```
 t.s.f1oo();
```


<!-- Sent from Reviewable.io -->

2024-07-03 09:03 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/test_data/loop` line 1008 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0rpSpy7kU8y4mEv90G:-O0rpSpy7kU8y4mEv90H:bukcrgj) ([raw file](https://github.com/starkware-libs/cairo/blob/6e2321a019da27d72dcd0136c9180078b5a9c4b3/crates/cairo-lang-lowering/src/lower/test_data/loop#L1008)):*
> ```
> fn foo() {
>     let t = T { s: S {} };
>     loop {
> ```

add a test where u use T inside the loop



_Code quote:_
```
 loop {
```


<!-- Sent from Reviewable.io -->

2024-07-04 14:23 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: 7 of 23 files reviewed, 8 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @t)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0oEuQx6SAoJJuC0IxY:-O0y5ws-1po_OOsazuiX:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

as discussed f2f - some parts are still missing.
</blockquote></details>

Done.

___
___
*[`crates/cairo-lang-lowering/src/lower/context.rs` line 306 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0rf5Pz3Xh2qAJRTXHZ:-O0y3OZP5niVJLhEN9HJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6e2321a019da27d72dcd0136c9180078b5a9c4b3/crates/cairo-lang-lowering/src/lower/context.rs#L306)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why skip_diagnostic?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1121 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0rier363tJ7-AVzEFF:-O0y3llO1crj-uWERJXx:b-n9tkhd) ([raw file](https://github.com/starkware-libs/cairo/blob/6e2321a019da27d72dcd0136c9180078b5a9c4b3/crates/cairo-lang-lowering/src/lower/mod.rs#L1121)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why?
explain that this happens because in the loop we change the type of the member path variable.
</blockquote></details>

changed
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1124 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0rnJ0j74mn5xKLrdNG:-O0y3mCN0z0oCLbytXR5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6e2321a019da27d72dcd0136c9180078b5a9c4b3/crates/cairo-lang-lowering/src/lower/mod.rs#L1124)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1126 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0roAGq4MmRLQdeTO1g:-O0y4974DYFC5tr7LhDW:b-qpoz87) ([raw file](https://github.com/starkware-libs/cairo/blob/6e2321a019da27d72dcd0136c9180078b5a9c4b3/crates/cairo-lang-lowering/src/lower/mod.rs#L1126)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

add something like:
</blockquote></details>

added a comment for other solution.
___
*[`crates/cairo-lang-lowering/src/lower/test_data/loop` line 1008 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0rpSpy7kU8y4mEv90G:-O0y5c_BAo_5h7KGjADZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6e2321a019da27d72dcd0136c9180078b5a9c4b3/crates/cairo-lang-lowering/src/lower/test_data/loop#L1008)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

add a test where u use T inside the loop
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/test_data/loop` line 1009 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0rpBN412oGPsoYuvcg:-O0y5mBVDer0IWU7pJ2L:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6e2321a019da27d72dcd0136c9180078b5a9c4b3/crates/cairo-lang-lowering/src/lower/test_data/loop#L1009)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

use(@t.s)
</blockquote></details>

Done.
___
*[`tests/bug_samples/issue2816.cairo` line 2 at r3](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0rm8-313TE9lVfF0UQ:-O0y5tXC1ecyc2QLan0o:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6e2321a019da27d72dcd0136c9180078b5a9c4b3/tests/bug_samples/issue2816.cairo#L2)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do note that cairo fmt still fails.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-04 14:44 UTC, orizi requested changes
> Reviewed 11 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: 18 of 23 files reviewed, 9 unresolved discussions (waiting on @ilyalesokhin-starkware, @t, and @TomerStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0yBhAq90U-GqsTIvHK:-O0yBhAq90U-GqsTIvHL:b-mtcnqm) (no related file):*
Why were the contract improvements reverted? (What changed algorithmically)

___
___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 128 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0yB1s28dHD_Mx2680z:-O0yB1s28dHD_Mx2681-:b2nhdkj) ([raw file](https://github.com/starkware-libs/cairo/blob/1af40c61ecf5b66344ddf5f74eda28cec6212943/crates/cairo-lang-lowering/src/lower/block_builder.rs#L128)):*
> ```XML
>     }
> 
>     pub fn update_snap_ref(&mut self, member_path: &ExprVarMemberPath, var: VariableId) {
> ```

Doc
___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 131 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0yB3Q361_PfD3_pOzi:-O0yB3Q361_PfD3_pOzj:b2nhdkj) ([raw file](https://github.com/starkware-libs/cairo/blob/1af40c61ecf5b66344ddf5f74eda28cec6212943/crates/cairo-lang-lowering/src/lower/block_builder.rs#L131)):*
> ```XML
>         self.snapped_semantics.insert(member_path.into(), var);
>     }
>     pub fn get_snap_ref(
> ```

Doc


<!-- Sent from Reviewable.io -->

2024-07-04 14:50 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: 17 of 23 files reviewed, 9 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @t)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0yBhAq90U-GqsTIvHK:-O0yCnaF70-QILitu47d:b-q1y6wr) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Why were the contract improvements reverted? (What changed algorithmically)
</blockquote></details>

which contract?

___
___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 128 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0yB1s28dHD_Mx2680z:-O0yDNmY8MG46H6yYAoR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1af40c61ecf5b66344ddf5f74eda28cec6212943/crates/cairo-lang-lowering/src/lower/block_builder.rs#L128)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 131 at r4](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0yB3Q361_PfD3_pOzi:-O0yDNVH2Gbkahh7s54s:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1af40c61ecf5b66344ddf5f74eda28cec6212943/crates/cairo-lang-lowering/src/lower/block_builder.rs#L131)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Doc
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-04 15:16 UTC, orizi requested changes
> Reviewed 4 of 16 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: 22 of 23 files reviewed, 9 unresolved discussions (waiting on @ilyalesokhin-starkware, @t, and @TomerStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0yBhAq90U-GqsTIvHK:-O0yJBOR4hLy2zUpchjx:b6vb1tb) (no related file):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

which contract?
</blockquote></details>

all the reverted ones. (all the erc20 based)

___
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1478 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0yIXRV-rBPVPCpqbLF:-O0yIXRV-rBPVPCpqbLG:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8e1f5d279eafcfda6d1f08be93412dc2ac654876/crates/cairo-lang-lowering/src/lower/mod.rs#L1478)):*
> ```XML
>                 .and_then(
>                     |var| {
>                         if ctx.variables[var.var_id].ty == param.ty() { Some(var) } else { None }
> ```





_Suggestion:_
```XML
                        (ctx.variables[var.var_id].ty == param.ty()).then_some(var)
```
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1486 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0yIidv7evW_GVZyhnN:-O0yIidv7evW_GVZyhnO:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8e1f5d279eafcfda6d1f08be93412dc2ac654876/crates/cairo-lang-lowering/src/lower/mod.rs#L1486)):*
> ```XML
>                     } else {
>                         None
>                     }
> ```





_Suggestion:_
```XML
                    let var = builder.get_snap_ref(ctx, &param)?;
                    (ctx.variables[var.var_id].ty == param.ty()).then_some(var)
```


<!-- Sent from Reviewable.io -->

2024-07-05 13:52 UTC, orizi reviewed
> Reviewed 1 of 16 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware, @t, and @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-07-07 07:46 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1418 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1B8yqgCOveITMp4NSa:-O1B8yqgCOveITMp4NSb:b2o7ebo) ([raw file](https://github.com/starkware-libs/cairo/blob/11bae10c64643aada26ef5b9b3e877ad31a627c2/crates/cairo-lang-lowering/src/lower/mod.rs#L1418)):*
> ```XML
>     .intern(ctx.db);
> 
>     let snap_usage = ctx.block_usages.block_usages[&loop_expr_id].snap_usage.clone();
> ```

do you need the clone here?



_Suggestion:_
```XML
 let snap_usage = &ctx.block_usages.block_usages[&loop_expr_id].snap_usage;
```


<!-- Sent from Reviewable.io -->

2024-07-07 07:47 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1445 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1B9OSR-4zxpJGCKiGX:-O1B9OSR-4zxpJGCKiGY:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/11bae10c64643aada26ef5b9b3e877ad31a627c2/crates/cairo-lang-lowering/src/lower/mod.rs#L1445)):*
> ```XML
>             builder.update_snap_ref(snapshot_param, snapped);
>             builder.update_ref(ctx, snapshot_param, original);
>             continue;
> ```

remove



_Code quote:_
```XML
  continue;
```


<!-- Sent from Reviewable.io -->

2024-07-07 07:49 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1436 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1B9j9e9aLn54JCiOPZ:-O1B9j9e9aLn54JCiOP_:bvilam4) ([raw file](https://github.com/starkware-libs/cairo/blob/11bae10c64643aada26ef5b9b3e877ad31a627c2/crates/cairo-lang-lowering/src/lower/mod.rs#L1436)):*
> ```XML
>     for snapshot_param in snap_usage.values() {
>         // if we have access to the real member we generate a snapshot, otherwise it should be
>         // accessible with `builder.get_snap_ref`
> ```

consider adding an assert



_Code quote:_
```XML
// accessible with `builder.get_snap_ref`
```


<!-- Sent from Reviewable.io -->

2024-07-07 11:20 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: 19 of 23 files reviewed, 10 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @t)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1478 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0yIXRV-rBPVPCpqbLF:-O127qasCCkmkMzhQwb7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8e1f5d279eafcfda6d1f08be93412dc2ac654876/crates/cairo-lang-lowering/src/lower/mod.rs#L1478)):*
> ```XML
>                 .and_then(
>                     |var| {
>                         if ctx.variables[var.var_id].ty == param.ty() { Some(var) } else { None }
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1486 at r5](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O0yIidv7evW_GVZyhnN:-O127rPG-oZroOZ_Jibo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8e1f5d279eafcfda6d1f08be93412dc2ac654876/crates/cairo-lang-lowering/src/lower/mod.rs#L1486)):*
> ```XML
>                     } else {
>                         None
>                     }
> ```

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1418 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1B8yqgCOveITMp4NSa:-O1Bth_68XDTJ_0v-z_0:br9vt06) ([raw file](https://github.com/starkware-libs/cairo/blob/11bae10c64643aada26ef5b9b3e877ad31a627c2/crates/cairo-lang-lowering/src/lower/mod.rs#L1418)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

do you need the clone here?
</blockquote></details>

I mutably borrow ctx later 
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1436 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1B9j9e9aLn54JCiOPZ:-O1BA3vE-CEezmYcFOin:bui29mb) ([raw file](https://github.com/starkware-libs/cairo/blob/11bae10c64643aada26ef5b9b3e877ad31a627c2/crates/cairo-lang-lowering/src/lower/mod.rs#L1436)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

consider adding an assert
</blockquote></details>

 if the var is a member of another variable in snap_ref, then asserting will add destructure statements ( maybe I can clone builder but this seems like performance overhead) 
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1445 at r6](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1B9OSR-4zxpJGCKiGX:-O1BsoPP4J9G1M2xRLzL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/11bae10c64643aada26ef5b9b3e877ad31a627c2/crates/cairo-lang-lowering/src/lower/mod.rs#L1445)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-07 12:29 UTC, orizi requested changes
> Reviewed 1 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: 20 of 23 files reviewed, 11 unresolved discussions (waiting on @ilyalesokhin-starkware, @t, and @TomerStarkware)

___
*[`corelib/src/test/language_features/while_test.cairo` line 52 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1C9eStBWrL5oIjpyef:-O1C9eStBWrL5oIjpyeg:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d0dc67c7451c430cb6a757997f8156a6ef8d2e40/corelib/src/test/language_features/while_test.cairo#L52)):*
> ```Cairo
>         i += 1;
>     };
> }
> ```





_Suggestion:_
```Cairo
    assert_eq!(arr.len(), 4);
}

#[derive(Drop)]
struct NonCopy {
    x: felt252,
}

fn assert_x_eq(a: @NonCopy, x: felt252) {
    assert_eq!(a.x, @x);
}

#[test]
fn test_borrow_with_inner_change() {
    let mut a = NonCopy { x: 0 };
    let mut i = 0;
    while i != 5 {
        a.x = i;
        assert_x_eq(@a, i);
        i += 1;
    };
}
```


<!-- Sent from Reviewable.io -->

2024-07-07 13:01 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: 19 of 23 files reviewed, 11 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @t)

___
*[`corelib/src/test/language_features/while_test.cairo` line 52 at r7](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1C9eStBWrL5oIjpyef:-O1CHFC_DOjwddtZCwB1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d0dc67c7451c430cb6a757997f8156a6ef8d2e40/corelib/src/test/language_features/while_test.cairo#L52)):*
> ```Cairo
>         i += 1;
>     };
> }
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-07-07 13:13 UTC, orizi reviewed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: 20 of 23 files reviewed, 10 unresolved discussions (waiting on @ilyalesokhin-starkware, @t, and @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-07-07 13:21 UTC, orizi reviewed
> Reviewed 1 of 4 files at r7, 1 of 2 files at r8, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: 22 of 23 files reviewed, 10 unresolved discussions (waiting on @ilyalesokhin-starkware, @t, and @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-07-08 06:07 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 141 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1Fwy2X5MkSS1zxCrSx:-O1Fwy2Y28hWAfG1YVLe:bu4vruc) ([raw file](https://github.com/starkware-libs/cairo/blob/18de882d1f31d910e25d4362e5f5956fede0ce8e/crates/cairo-lang-lowering/src/lower/block_builder.rs#L141)):*
> ```XML
>     ) -> Option<VarUsage> {
>         let location = ctx.get_location(member_path.stable_ptr().untyped());
>         if let Some(var_id) = self.snapped_semantics.get::<MemberPath>(&member_path.into()) {
> ```

Where is this generic function defined? why is it generic?



_Code quote:_
```XML
get::<MemberPath>
```


<!-- Sent from Reviewable.io -->

2024-07-08 06:11 UTC, ilyalesokhin-starkware reviewed
> Reviewed 1 of 20 files at r1, 1 of 2 files at r2, 1 of 16 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: 22 of 23 files reviewed, 9 unresolved discussions (waiting on @orizi, @t, and @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-07-08 06:41 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: 22 of 23 files reviewed, 10 unresolved discussions (waiting on @ilyalesokhin-starkware, @t, and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/test_data/loop` line 1350 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1G3Wsf95Aldzd-WCvd:-O1G3Wsf95Aldzd-WCve:brieky2) ([raw file](https://github.com/starkware-libs/cairo/blob/18de882d1f31d910e25d4362e5f5956fede0ce8e/crates/cairo-lang-lowering/src/lower/test_data/loop#L1350)):*
> ```
>     x: felt252,
> }
> extern fn assertA(a: @A, x: felt252) nopanic;
> ```

simplify (as you don't actually assert for this test)



_Suggestion:_
```
        a.x = i;
        use_a(@a);
        i += 1;
    };
}

//! > function_name
foo

//! > module_code
#[derive(Drop)]
struct A {
    x: felt252,
}
extern fn use_a(a: @A) nopanic;
```


<!-- Sent from Reviewable.io -->

2024-07-08 06:45 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1150 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1G4far3Dn39G3BoiBQ:-O1G4far3Dn39G3BoiBR:ba2tinj) ([raw file](https://github.com/starkware-libs/cairo/blob/18de882d1f31d910e25d4362e5f5956fede0ce8e/crates/cairo-lang-lowering/src/lower/mod.rs#L1150)):*
> ```XML
>     let location = ctx.get_location(expr.stable_ptr.untyped());
>     let expr = Box::new(lowered);
>     Ok(LoweredExpr::Snapshot { expr, location })
> ```

consider moving inside the match and removing the early returns.



_Code quote:_
```XML
    let lowered = lower_expr(ctx, builder, expr.inner)?;

    let location = ctx.get_location(expr.stable_ptr.untyped());
    let expr = Box::new(lowered);
    Ok(LoweredExpr::Snapshot { expr, location })
```


<!-- Sent from Reviewable.io -->

2024-07-08 06:53 UTC, orizi reviewed
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: all files reviewed, 11 unresolved discussions (waiting on @ilyalesokhin-starkware, @t, and @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-07-08 07:07 UTC, ilyalesokhin-starkware reviewed
> Reviewed 3 of 20 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, 11 of 16 files at r4, 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: all files reviewed, 7 unresolved discussions (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-07-08 07:16 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: 22 of 23 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 141 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1Fwy2X5MkSS1zxCrSx:-O1GA9gX0gpZ40BG1JRS:bq23464) ([raw file](https://github.com/starkware-libs/cairo/blob/18de882d1f31d910e25d4362e5f5956fede0ce8e/crates/cairo-lang-lowering/src/lower/block_builder.rs#L141)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Where is this generic function defined? why is it generic?
</blockquote></details>

its `get` method of `OrderedHashMap`
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1150 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1G4far3Dn39G3BoiBQ:-O1GAfvX1x6Q8h-c10iS:bfmz2b2) ([raw file](https://github.com/starkware-libs/cairo/blob/18de882d1f31d910e25d4362e5f5956fede0ce8e/crates/cairo-lang-lowering/src/lower/mod.rs#L1150)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

consider moving inside the match and removing the early returns.
</blockquote></details>

but the other arms of the match should also reach this part if get_snap_ref fails
___
*[`crates/cairo-lang-lowering/src/lower/test_data/loop` line 1350 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1G3Wsf95Aldzd-WCvd:-O1GBUKg5qDiyJv415sD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/18de882d1f31d910e25d4362e5f5956fede0ce8e/crates/cairo-lang-lowering/src/lower/test_data/loop#L1350)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

simplify (as you don't actually assert for this test)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-08 07:18 UTC, orizi reviewed
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: all files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-07-09 05:11 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 141 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1Fwy2X5MkSS1zxCrSx:-O1Ktd7p9n0TUOlvq0WV:b-lvql3c) ([raw file](https://github.com/starkware-libs/cairo/blob/18de882d1f31d910e25d4362e5f5956fede0ce8e/crates/cairo-lang-lowering/src/lower/block_builder.rs#L141)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

its `get` method of `OrderedHashMap`
</blockquote></details>

Why do you need to generic param: isn't the type of `self.snapped_semantics` known here?


<!-- Sent from Reviewable.io -->

2024-07-09 05:27 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1481 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1KxH6O6qOwbx8drSqx:-O1KxH6O6qOwbx8drSqy:b-lhh7px) ([raw file](https://github.com/starkware-libs/cairo/blob/f3d16c52f8f3396aed2dce1ef841e3a1d6cee35f/crates/cairo-lang-lowering/src/lower/mod.rs#L1481)):*
> ```XML
>                 })
>                 .ok_or_else(|| {
>                     LoweringFlowError::Failed(ctx.diagnostics.report(stable_ptr, MemberPathLoop))
> ```

when does this happen do we have a test for that?



_Code quote:_
```XML
LoweringFlowError::Failed(ctx.diagnostics.report(stable_ptr, MemberPathLoop))
```


<!-- Sent from Reviewable.io -->

2024-07-09 07:09 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/cairo-lang-lowering/src/lower/block_builder.rs` line 141 at r11](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1Fwy2X5MkSS1zxCrSx:-O1LH8WEEt-iNs-wKtYj:b-v84pwu) ([raw file](https://github.com/starkware-libs/cairo/blob/18de882d1f31d910e25d4362e5f5956fede0ce8e/crates/cairo-lang-lowering/src/lower/block_builder.rs#L141)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why do you need to generic param: isn't the type of `self.snapped_semantics` known here?
</blockquote></details>

yes but the `get` method receives a generic argument that only needs to be Equivalent<Key> so `into` alone does not solve it
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1481 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1KxH6O6qOwbx8drSqx:-O1LJV6Z3nURr39Lt6bP:b-d6ez0s) ([raw file](https://github.com/starkware-libs/cairo/blob/f3d16c52f8f3396aed2dce1ef841e3a1d6cee35f/crates/cairo-lang-lowering/src/lower/mod.rs#L1481)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

when does this happen do we have a test for that?
</blockquote></details>

We do not have a test, I think it can only happen if a compiler bug occurs


<!-- Sent from Reviewable.io -->

2024-07-10 12:53 UTC, ilyalesokhin-starkware approved these changes
> Reviewed 1 of 4 files at r7, 1 of 1 files at r11, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1481 at r13](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1KxH6O6qOwbx8drSqx:-O1RdjCX1rOZgi5fmK-7:bei43ru) ([raw file](https://github.com/starkware-libs/cairo/blob/f3d16c52f8f3396aed2dce1ef841e3a1d6cee35f/crates/cairo-lang-lowering/src/lower/mod.rs#L1481)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

We do not have a test, I think it can only happen if a compiler bug occurs
</blockquote></details>

Add a todo to remove this error.


<!-- Sent from Reviewable.io -->

2024-07-10 12:53 UTC, ilyalesokhin-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-07-10 12:54 UTC, ilyalesokhin-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934#-:-O1RhJAv3c-k_psBmniq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-07-11 09:16 UTC, orizi requested changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1481 at r14](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1W45X96sdv1IpbFaVz:-O1W45X96sdv1IpbFaW-:b-p5m515) ([raw file](https://github.com/starkware-libs/cairo/blob/ed3d7712f015226a85032ee7ba1d4c1b4e7020f9/crates/cairo-lang-lowering/src/lower/mod.rs#L1481)):*
> ```XML
>                 })
>                 .ok_or_else(|| {
>                     // TODO(TomerStaskware): remove this error.
> ```

if so - why does it exist?


<!-- Sent from Reviewable.io -->

2024-07-11 13:28 UTC, orizi reviewed
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-07-11 13:28 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`-- commits` line 5 at r15](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1WyqkMEIv2AZFK69C7):*
rebase


<!-- Sent from Reviewable.io -->

2024-07-11 13:29 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`-- commits` line 5 at r15](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1WyqkMEIv2AZFK69C7):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rebase
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1481 at r14](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1W45X96sdv1IpbFaVz:-O1WyzmB3Ra2s-LIk3JV:b-d7f7zr) ([raw file](https://github.com/starkware-libs/cairo/blob/ed3d7712f015226a85032ee7ba1d4c1b4e7020f9/crates/cairo-lang-lowering/src/lower/mod.rs#L1481)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if so - why does it exist?
</blockquote></details>

looks like legacy error


<!-- Sent from Reviewable.io -->

2024-07-11 13:40 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`-- commits` line 5 at r15](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1WyqkMEIv2AZFK69C7):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

i still see 2 commits.
___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1481 at r14](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1W45X96sdv1IpbFaVz:-O1X0RYkAOOG4lImsxNi:b2814p0) ([raw file](https://github.com/starkware-libs/cairo/blob/ed3d7712f015226a85032ee7ba1d4c1b4e7020f9/crates/cairo-lang-lowering/src/lower/mod.rs#L1481)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

looks like legacy error
</blockquote></details>

make the TODO more operative.


<!-- Sent from Reviewable.io -->

2024-07-11 13:43 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: 22 of 23 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-lowering/src/lower/mod.rs` line 1481 at r14](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1W45X96sdv1IpbFaVz:-O1X18KQ90penlQ6tE-r:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ed3d7712f015226a85032ee7ba1d4c1b4e7020f9/crates/cairo-lang-lowering/src/lower/mod.rs#L1481)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

make the TODO more operative.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-11 13:44 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934#-:-O1X1Su44EBO12nmKW11:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-07-11 13:44 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`-- commits` line 5 at r15](https://reviewable.io/reviews/starkware-libs/cairo/5934#-O1WyqkMEIv2AZFK69C7):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i still see 2 commits.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-11 13:44 UTC, orizi approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/5934)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-07-14 07:23 UTC, merged