added closure expression to semantic
starkware-libs/cairo pull request #6015
Opened 2024-07-11 13:30 UTC by TomerStarkware

2024-07-11 13:54 UTC, orizi requested changes
> Reviewed 10 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: 10 of 21 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 1103 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1X1qhcCWVi5mw-lKcI:-O1X1qhdDHiU8Llg4DWf:b-uu2ycn) ([raw file](https://github.com/starkware-libs/cairo/blob/21ee0f202bf935ad433091c04e9305864912a3ac/crates/cairo-lang-defs/src/ids.rs#L1103)):*
> ```XML
>     lookup_intern_closure,
>     intern_closure
> );
> ```

maybe put closer to impl definition?



_Code quote:_
```XML
define_language_element_id_basic!(
    ClosureId,
    ClosureLongId,
    ast::ExprClosure,
    lookup_intern_closure,
    intern_closure
);
```
___
*[`crates/cairo-lang-lowering/src/db.rs` line 775 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1X22UH21U-KtbakS22:-O1X22UH21U-KtbakS23:b1kpyju) ([raw file](https://github.com/starkware-libs/cairo/blob/21ee0f202bf935ad433091c04e9305864912a3ac/crates/cairo-lang-lowering/src/db.rs#L775)):*
> ```XML
>                     .unwrap()
>         }
>         TypeLongId::Closure(_) => panic!("unsupported"),
> ```

or todo! or whatever more specific panic trait.



_Suggestion:_
```XML
                    .unwrap()
        }
        TypeLongId::Closure(_) => unimplemented!("unsupported"),
```
___
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1X2GZg8KIMLuJ__nhR:-O1X2GZh0pZl3nWK6MYY:b-7ropln) ([raw file](https://github.com/starkware-libs/cairo/blob/21ee0f202bf935ad433091c04e9305864912a3ac/crates/cairo-lang-lowering/src/lower/usage.rs#L227)):*
> ```XML
>                 self.block_usages.insert(expr_id, usage);
>             }
>             Expr::ExprClosure(_) => panic!("Closure not supported"),
> ```

ditto
___
*[`crates/cairo-lang-semantic/src/types.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1X2XU10jum5PDXFJw0:-O1X2XU10jum5PDXFJw1:b-3z5hzj) ([raw file](https://github.com/starkware-libs/cairo/blob/21ee0f202bf935ad433091c04e9305864912a3ac/crates/cairo-lang-semantic/src/types.rs#L145)):*
> ```XML
>             TypeLongId::Closure(closure) => {
>                 format!(
>                     "fn({}) -> {}",
> ```

this is a bad print - as it does not actually point to the specific type.
A containing function path + [expr_id] (similar to generated functions) would probably be better.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 403 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1X34uX0T4_G3IuKmEn:-O1X34uX0T4_G3IuKmEo:b4nm7e1) ([raw file](https://github.com/starkware-libs/cairo/blob/21ee0f202bf935ad433091c04e9305864912a3ac/crates/cairo-lang-semantic/src/types.rs#L403)):*
> ```XML
> #[derive(Clone, Debug, Hash, PartialEq, Eq, SemanticObject)]
> pub struct ClosureTypeLongId {
>     pub generics: Vec<GenericParamId>,
> ```

possibly change params to just be the concrete function id + expr.



_Code quote:_
```XML
    pub generics: Vec<GenericParamId>,
```


<!-- Sent from Reviewable.io -->

2024-07-14 07:20 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: 10 of 21 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 1103 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1X1qhcCWVi5mw-lKcI:-O1k6JGTAalmfnFiUsyz:b-7x843t) ([raw file](https://github.com/starkware-libs/cairo/blob/21ee0f202bf935ad433091c04e9305864912a3ac/crates/cairo-lang-defs/src/ids.rs#L1103)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe put closer to impl definition?
</blockquote></details>

which impl?
___
*[`crates/cairo-lang-lowering/src/db.rs` line 775 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1X22UH21U-KtbakS22:-O1k50h69ifNqN78HaBq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/21ee0f202bf935ad433091c04e9305864912a3ac/crates/cairo-lang-lowering/src/db.rs#L775)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

or todo! or whatever more specific panic trait.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1X2GZg8KIMLuJ__nhR:-O1k5-zw8BSzfTCBRi7V:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/21ee0f202bf935ad433091c04e9305864912a3ac/crates/cairo-lang-lowering/src/lower/usage.rs#L227)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1X2XU10jum5PDXFJw0:-O1k5Kuf3XH5gmR9OhZf:bqsrkt2) ([raw file](https://github.com/starkware-libs/cairo/blob/21ee0f202bf935ad433091c04e9305864912a3ac/crates/cairo-lang-semantic/src/types.rs#L145)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is a bad print - as it does not actually point to the specific type.
A containing function path + [expr_id] (similar to generated functions) would probably be better.
</blockquote></details>

Its not possible for closuretype to contain its own expr_id, and the expr_id to contain the closuretype id
___
*[`crates/cairo-lang-semantic/src/types.rs` line 403 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1X34uX0T4_G3IuKmEn:-O1k5uAK46bGPsKBEA2R:b-dp0yk4) ([raw file](https://github.com/starkware-libs/cairo/blob/21ee0f202bf935ad433091c04e9305864912a3ac/crates/cairo-lang-semantic/src/types.rs#L403)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

possibly change params to just be the concrete function id + expr.
</blockquote></details>

you mean the generic params?


<!-- Sent from Reviewable.io -->

2024-07-14 07:41 UTC, orizi requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: 10 of 21 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 1103 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1X1qhcCWVi5mw-lKcI:-O1kAZAhERkSlNb3USxO:b-2bzsm5) ([raw file](https://github.com/starkware-libs/cairo/blob/21ee0f202bf935ad433091c04e9305864912a3ac/crates/cairo-lang-defs/src/ids.rs#L1103)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

which impl?
</blockquote></details>

impl def id and so on.
___
*[`crates/cairo-lang-lowering/src/db.rs` line 775 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1X22UH21U-KtbakS22:-O1kAiWjBJycLiX2Ze5P:b-qdkss8) ([raw file](https://github.com/starkware-libs/cairo/blob/21ee0f202bf935ad433091c04e9305864912a3ac/crates/cairo-lang-lowering/src/db.rs#L775)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

be consistent here.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1X2XU10jum5PDXFJw0:-O1kB5991uW6G4oPdBQe:bpb486l) ([raw file](https://github.com/starkware-libs/cairo/blob/21ee0f202bf935ad433091c04e9305864912a3ac/crates/cairo-lang-semantic/src/types.rs#L145)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

Its not possible for closuretype to contain its own expr_id, and the expr_id to contain the closuretype id
</blockquote></details>

it is - it would just be the id of the body expr.


<!-- Sent from Reviewable.io -->

2024-07-14 07:43 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: 10 of 21 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-lowering/src/db.rs` line 775 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1X22UH21U-KtbakS22:-O1kBHhg6kgr0ZJcmz0g:b2zrfij) ([raw file](https://github.com/starkware-libs/cairo/blob/21ee0f202bf935ad433091c04e9305864912a3ac/crates/cairo-lang-lowering/src/db.rs#L775)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

be consistent here.
</blockquote></details>

(with the other `unimplemented!`)
___
*[`crates/cairo-lang-semantic/src/types.rs` line 403 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1X34uX0T4_G3IuKmEn:-O1kBE3s1AimmaBxauaB:bpa9ksa) ([raw file](https://github.com/starkware-libs/cairo/blob/21ee0f202bf935ad433091c04e9305864912a3ac/crates/cairo-lang-semantic/src/types.rs#L403)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

you mean the generic params?
</blockquote></details>

nope - same idea as the print above.


<!-- Sent from Reviewable.io -->

2024-07-14 13:00 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: 6 of 25 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 1103 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1X1qhcCWVi5mw-lKcI:-O1kD98i5xwSNupoQJ3R:b-ekvjm7) ([raw file](https://github.com/starkware-libs/cairo/blob/21ee0f202bf935ad433091c04e9305864912a3ac/crates/cairo-lang-defs/src/ids.rs#L1103)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

impl def id and so on.
</blockquote></details>

placed after GenericParamLongId 
___
*[`crates/cairo-lang-lowering/src/db.rs` line 775 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1X22UH21U-KtbakS22:-O1kDqdTEiSScbffmk_i:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/21ee0f202bf935ad433091c04e9305864912a3ac/crates/cairo-lang-lowering/src/db.rs#L775)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

(with the other `unimplemented!`)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1X2XU10jum5PDXFJw0:-O1lJgjUBEd84adAV8KP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/21ee0f202bf935ad433091c04e9305864912a3ac/crates/cairo-lang-semantic/src/types.rs#L145)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it is - it would just be the id of the body expr.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 403 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1X34uX0T4_G3IuKmEn:-O1kGZg883cKN8bxlFJg:b-z03c08) ([raw file](https://github.com/starkware-libs/cairo/blob/21ee0f202bf935ad433091c04e9305864912a3ac/crates/cairo-lang-semantic/src/types.rs#L403)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

nope - same idea as the print above.
</blockquote></details>

but i need the the closure params


<!-- Sent from Reviewable.io -->

2024-07-14 13:45 UTC, orizi requested changes
> Reviewed 2 of 21 files at r1, 5 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: 13 of 25 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 405 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1lUAsaDN_f3BDG6R_h:-O1lUAsaDN_f3BDG6R_i:b-bxw1ho) ([raw file](https://github.com/starkware-libs/cairo/blob/6f0f5472c2bf3da4ed27901ae5173800402b4335/crates/cairo-lang-semantic/src/types.rs#L405)):*
> ```XML
> #[derive(Clone, Debug, Hash, PartialEq, Eq, SemanticObject)]
> pub struct ClosureTypeLongId {
>     pub containing_function: Option<FunctionId>,
> ```

doc why option.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 407 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1lU3XI7kIXdQ_DHZlJ:-O1lU3XI7kIXdQ_DHZlK:b-mpile) ([raw file](https://github.com/starkware-libs/cairo/blob/6f0f5472c2bf3da4ed27901ae5173800402b4335/crates/cairo-lang-semantic/src/types.rs#L407)):*
> ```XML
>     pub containing_function: Option<FunctionId>,
>     pub body_id: ExprId,
>     pub closure: ClosureId,
> ```

do we actually need ClosureId anywhere?
won't the expr suffice?



_Code quote:_
```XML
    pub closure: ClosureId,
```


<!-- Sent from Reviewable.io -->

2024-07-14 14:08 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: 7 of 25 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 405 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1lUAsaDN_f3BDG6R_h:-O1lYwkN9TAIKV4cKu39:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6f0f5472c2bf3da4ed27901ae5173800402b4335/crates/cairo-lang-semantic/src/types.rs#L405)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc why option.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 407 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1lU3XI7kIXdQ_DHZlJ:-O1lYxGVBsEewaOik7XZ:b2nign6) ([raw file](https://github.com/starkware-libs/cairo/blob/6f0f5472c2bf3da4ed27901ae5173800402b4335/crates/cairo-lang-semantic/src/types.rs#L407)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do we actually need ClosureId anywhere?
won't the expr suffice?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2024-07-15 07:38 UTC, orizi requested changes
> Reviewed 4 of 21 files at r1, 6 of 12 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 407 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1pEI23AoAbWfEFqYMC:-O1pEI23AoAbWfEFqYMD:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0a444563f46818bb8588781c099f4c29b2201f92/crates/cairo-lang-semantic/src/types.rs#L407)):*
> ```XML
>     // The function containing the closure.
>     // It is `None` if we do not have the function id of the containing function (for example, if
>     // there is a semantic error).
> ```





_Suggestion:_
```XML
    /// The function containing the closure.
    /// It is `None` if we do not have the function id of the containing function (for example, if
    /// there is a semantic error).
```
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 3017 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1pItkw198oKo-o2cqk:-O1pItkw198oKo-o2cql:b-jfgkz0) ([raw file](https://github.com/starkware-libs/cairo/blob/0a444563f46818bb8588781c099f4c29b2201f92/crates/cairo-lang-semantic/src/items/imp.rs#L3017)):*
> ```XML
>             }
>             .intern(db),
>         )
> ```

this part should be a function (and might already be).
you use this concept of `generic_function` --> `FunctionId` 3 times here.



_Code quote:_
```XML
        let generic_params: Vec<_> = generic_function.generic_params(db).ok()?;

        Some(
            FunctionLongId {
                function: ConcreteFunction {
                    generic_function,
                    generic_args: generic_params_to_args(&generic_params, db),
                },
            }
            .intern(db),
        )
```
___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 162 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1pJMgfEujP80S-E3hB:-O1pJMgfEujP80S-E3hC:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/0a444563f46818bb8588781c099f4c29b2201f92/crates/cairo-lang-sierra-generator/src/types.rs#L162)):*
> ```XML
>         }
>         semantic::TypeLongId::Closure(_) => {
>             panic!("Function types are not supported.");
> ```





_Suggestion:_
```XML
        semantic::TypeLongId::Closure(_) => {
            todo!("Handle Closure types.");
```
___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 210 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1pJhOqAtBY1h9dE7L9:-O1pJhOqAtBY1h9dE7LA:b-jphh2u) ([raw file](https://github.com/starkware-libs/cairo/blob/0a444563f46818bb8588781c099f4c29b2201f92/crates/cairo-lang-sierra-generator/src/types.rs#L210)):*
> ```XML
>         semantic::TypeLongId::Closure(closure) => {
>             chain!(closure.params.into_iter(), Some(closure.ret_ty)).collect()
>         }
> ```

This should probably only be reached by function calls - so this should be `unreachable!` instead.



_Code quote:_
```XML
        semantic::TypeLongId::Closure(closure) => {
            chain!(closure.params.into_iter(), Some(closure.ret_ty)).collect()
        }
```


<!-- Sent from Reviewable.io -->

2024-07-15 08:50 UTC, orizi requested changes
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 209 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1p_JCXATvBZZOp4ziK:-O1p_JCXATvBZZOp4ziL:b-nzr8rc) ([raw file](https://github.com/starkware-libs/cairo/blob/15b570a50b2e83d636a6754f94e1e02f8b690e84/crates/cairo-lang-sierra-generator/src/types.rs#L209)):*
> ```XML
>         semantic::TypeLongId::Coupon(_) => vec![],
>         semantic::TypeLongId::Closure(closure) => {
>             unreachable!("Closure types are not supported.");
> ```

this is not about not being supported - this is about not being around at this point.
should have been handled elsewhere.


<!-- Sent from Reviewable.io -->

2024-07-15 08:58 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 407 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1pEI23AoAbWfEFqYMC:-O1pTgur6e6_vS_SdAMt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0a444563f46818bb8588781c099f4c29b2201f92/crates/cairo-lang-semantic/src/types.rs#L407)):*
> ```XML
>     // The function containing the closure.
>     // It is `None` if we do not have the function id of the containing function (for example, if
>     // there is a semantic error).
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/items/imp.rs` line 3017 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1pItkw198oKo-o2cqk:-O1pY-B-3GiYcv4TK1cr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0a444563f46818bb8588781c099f4c29b2201f92/crates/cairo-lang-semantic/src/items/imp.rs#L3017)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this part should be a function (and might already be).
you use this concept of `generic_function` --> `FunctionId` 3 times here.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 162 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1pJMgfEujP80S-E3hB:-O1pKPA29Qe0Wol6GhIm:bbxfl66) ([raw file](https://github.com/starkware-libs/cairo/blob/0a444563f46818bb8588781c099f4c29b2201f92/crates/cairo-lang-sierra-generator/src/types.rs#L162)):*
> ```XML
>         }
>         semantic::TypeLongId::Closure(_) => {
>             panic!("Function types are not supported.");
> ```

wouldn't the closure type disappear in the lowering?
___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 210 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1pJhOqAtBY1h9dE7L9:-O1pZGBZ70h8WD880gbc:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0a444563f46818bb8588781c099f4c29b2201f92/crates/cairo-lang-sierra-generator/src/types.rs#L210)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

This should probably only be reached by function calls - so this should be `unreachable!` instead.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-15 09:00 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: 24 of 25 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 209 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1p_JCXATvBZZOp4ziK:-O1pbklU2YgUUhE7X5RL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/15b570a50b2e83d636a6754f94e1e02f8b690e84/crates/cairo-lang-sierra-generator/src/types.rs#L209)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is not about not being supported - this is about not being around at this point.
should have been handled elsewhere.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-15 09:02 UTC, orizi requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @TomerStarkware)

___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 162 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1pJMgfEujP80S-E3hB:-O1pbx9xCYjFCH2Vggcw:bs1pcdr) ([raw file](https://github.com/starkware-libs/cairo/blob/0a444563f46818bb8588781c099f4c29b2201f92/crates/cairo-lang-sierra-generator/src/types.rs#L162)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

wouldn't the closure type disappear in the lowering?
</blockquote></details>

it should - you are correct - make `unreachable!`.


<!-- Sent from Reviewable.io -->

2024-07-15 09:08 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-sierra-generator/src/types.rs` line 162 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1pJMgfEujP80S-E3hB:-O1pdXkf2ZKAxE-QsQh4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0a444563f46818bb8588781c099f4c29b2201f92/crates/cairo-lang-sierra-generator/src/types.rs#L162)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it should - you are correct - make `unreachable!`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-15 09:29 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015#-:-O1piJykBICDpQb1Csme:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-07-16 07:40 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 153 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1uTv7b-wGzzV4DSeoZ:-O1uTv7b-wGzzV4DSeo_:b-6h6eoq) ([raw file](https://github.com/starkware-libs/cairo/blob/b9385a73d61b03a1cd46b534d6525179d0e35560/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L153)):*
> ```XML
>                     return Err(self.set_error(InferenceError::TypeKindMismatch { ty0, ty1 }));
>                 };
>                 if closure0.body_id != closure1.body_id {
> ```

can't closure with different bodies have the same type?



_Code quote:_
```XML
closure0.body_id != closure1.body_id
```


<!-- Sent from Reviewable.io -->

2024-07-16 07:41 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-semantic/src/expr/test_data/closure` line 23 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1uUEqYANWLnhMp1NDZ:-O1uUEqYANWLnhMp1ND_:b-cupl60) ([raw file](https://github.com/starkware-libs/cairo/blob/b9385a73d61b03a1cd46b534d6525179d0e35560/crates/cairo-lang-semantic/src/expr/test_data/closure#L23)):*
> ```
>  --> lib.cairo:1:10
> fn foo() {
>          ^
> ```

the error location is wrong.



_Code quote:_
```
fn foo() {
         ^
```


<!-- Sent from Reviewable.io -->

2024-07-16 07:42 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 827 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1uU_5l0S6FkPa08WHo:-O1uU_5l0S6FkPa08WHp:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/b9385a73d61b03a1cd46b534d6525179d0e35560/crates/cairo-lang-semantic/src/items/functions.rs#L827)):*
> ```XML
>         db,
>         resolver,
>         params, //&sig.parameters(syntax_db).elements(syntax_db),
> ```

?



_Code quote:_
```XML
 //&sig.parameters(syntax_db).elements(syntax_db),
```


<!-- Sent from Reviewable.io -->

2024-07-16 07:43 UTC, ilyalesokhin-starkware reviewed
> Reviewed 5 of 21 files at r1, 2 of 12 files at r3, 6 of 10 files at r4, 4 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: all files reviewed, 4 unresolved discussions (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-07-16 07:44 UTC, ilyalesokhin-starkware reviewed
> Reviewed 1 of 21 files at r1, 2 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: all files reviewed, 4 unresolved discussions (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-07-16 07:51 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-semantic/src/types.rs` line 408 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1uWTS0E1tM8tvw7pEP:-O1uWTS0E1tM8tvw7pEQ:b-7gtqu) ([raw file](https://github.com/starkware-libs/cairo/blob/b9385a73d61b03a1cd46b534d6525179d0e35560/crates/cairo-lang-semantic/src/types.rs#L408)):*
> ```XML
>     /// It is `None` if we do not have the function id of the containing function (for example, if
>     /// there is a semantic error).
>     pub containing_function: Option<FunctionId>,
> ```

why does the type of the closure depend on the containing functions?



_Code quote:_
```XML
  pub containing_function: Option<FunctionId>,
```


<!-- Sent from Reviewable.io -->

2024-07-16 08:49 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: 20 of 25 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 408 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1uWTS0E1tM8tvw7pEP:-O1uY1bT02Uy7xRWxffA:b-6c396o) ([raw file](https://github.com/starkware-libs/cairo/blob/b9385a73d61b03a1cd46b534d6525179d0e35560/crates/cairo-lang-semantic/src/types.rs#L408)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why does the type of the closure depend on the containing functions?
</blockquote></details>

it is dependent on the containing function generics (and containing trait or impl id they exist)
___
*[`crates/cairo-lang-semantic/src/types.rs` line 803 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1uSIrf9NLWwuvmGESg:-O1uYMbYDzGuMYzTSfre:b-wk3qod) ([raw file](https://github.com/starkware-libs/cairo/blob/b9385a73d61b03a1cd46b534d6525179d0e35560/crates/cairo-lang-semantic/src/types.rs#L803)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why true?
</blockquote></details>

the closure it self does not create genric context
___
*[`crates/cairo-lang-semantic/src/expr/inference/conform.rs` line 153 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1uTv7b-wGzzV4DSeoZ:-O1uYTtB6F8Cz5iK8JUl:bz32v6k) ([raw file](https://github.com/starkware-libs/cairo/blob/b9385a73d61b03a1cd46b534d6525179d0e35560/crates/cairo-lang-semantic/src/expr/inference/conform.rs#L153)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can't closure with different bodies have the same type?
</blockquote></details>

no, they may implement the same Fn trait, but the type is different
___
*[`crates/cairo-lang-semantic/src/expr/test_data/closure` line 23 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1uUEqYANWLnhMp1NDZ:-O1uhbgtCEDDOq42dzFd:bjy12k0) ([raw file](https://github.com/starkware-libs/cairo/blob/b9385a73d61b03a1cd46b534d6525179d0e35560/crates/cairo-lang-semantic/src/expr/test_data/closure#L23)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

the error location is wrong.
</blockquote></details>

done, now the error is now on the entire closure expression
___
*[`crates/cairo-lang-semantic/src/items/functions.rs` line 827 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1uU_5l0S6FkPa08WHo:-O1udBKN3HauyCGN4I3p:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b9385a73d61b03a1cd46b534d6525179d0e35560/crates/cairo-lang-semantic/src/items/functions.rs#L827)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-16 08:49 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: 20 of 25 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/test_data/closure` line 23 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1uUEqYANWLnhMp1NDZ:-O1uipG70Ww5WR1yUqzd:b-rs28ed) ([raw file](https://github.com/starkware-libs/cairo/blob/b9385a73d61b03a1cd46b534d6525179d0e35560/crates/cairo-lang-semantic/src/expr/test_data/closure#L23)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

done, now the error is now on the entire closure expression
</blockquote></details>

entire closure expression body


<!-- Sent from Reviewable.io -->

2024-07-16 10:07 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-lowering/src/lower/usage.rs` line 227 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1v-g946tUeYIig85xJ:-O1v-g946tUeYIig85xK:beocsek) ([raw file](https://github.com/starkware-libs/cairo/blob/a070ce5657c55ce1e5c94f3d874882468110681b/crates/cairo-lang-lowering/src/lower/usage.rs#L227)):*
> ```XML
>                 self.block_usages.insert(expr_id, usage);
>             }
>             Expr::ExprClosure(_) => unimplemented!(),
> ```

Make sure we have a diagnostic semantic before reaching this point.



_Code quote:_
```XML
  Expr::ExprClosure(_) => unimplemented!(),
```


<!-- Sent from Reviewable.io -->

2024-07-17 06:07 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-semantic/src/types.rs` line 827 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1zIPWz7ZI46AkZbGtd:-O1zIPWz7ZI46AkZbGte:blnhanv) ([raw file](https://github.com/starkware-libs/cairo/blob/a070ce5657c55ce1e5c94f3d874882468110681b/crates/cairo-lang-semantic/src/types.rs#L827)):*
> ```XML
>             closure.params.iter().all(|param| param.is_var_free(db))
>                 && closure.ret_ty.is_var_free(db)
>         }
> ```

It can have variables in the generic params of the calling function, right?



_Code quote:_
```XML
        TypeLongId::Closure(closure) => {
            closure.params.iter().all(|param| param.is_var_free(db))
                && closure.ret_ty.is_var_free(db)
        }
```


<!-- Sent from Reviewable.io -->

2024-07-17 06:09 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-semantic/src/types.rs` line 408 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1uWTS0E1tM8tvw7pEP:-O1zIZs-6RFIfAXbA38O:b-7pj27n) ([raw file](https://github.com/starkware-libs/cairo/blob/b9385a73d61b03a1cd46b534d6525179d0e35560/crates/cairo-lang-semantic/src/types.rs#L408)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

it is dependent on the containing function generics (and containing trait or impl id they exist)
</blockquote></details>

closure.containing_function is an error case,
I think we should say that the function is not fully_concrete in this case.


<!-- Sent from Reviewable.io -->

2024-07-17 09:55 UTC, ilyalesokhin-starkware reviewed
> Reviewed 1 of 12 files at r3, 1 of 10 files at r4, 1 of 1 files at r7, 5 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: 22 of 25 files reviewed, 4 unresolved discussions (waiting on @orizi and @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-07-17 09:58 UTC, orizi approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: all files reviewed, 4 unresolved discussions (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-07-17 11:15 UTC, ilyalesokhin-starkware commented
*[`crates/cairo-lang-semantic/src/expr/test_data/closure` line 11 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O2-Ohk04ir5cMhONGMJ:-O2-Ohk04ir5cMhONGMK:bs7rivf) ([raw file](https://github.com/starkware-libs/cairo/blob/a070ce5657c55ce1e5c94f3d874882468110681b/crates/cairo-lang-semantic/src/expr/test_data/closure#L11)):*
> ```
>         let d: u32 = 3;
>         d
>     };
> ```

add paramaters with and without type annotations.



_Suggestion:_
```
    |a| -> i32 {
        let d: u32 = 3;
        d
    };
```


<!-- Sent from Reviewable.io -->

2024-07-17 11:53 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: 16 of 25 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 408 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1uWTS0E1tM8tvw7pEP:-O2-S2HB6-Gqmh98h4HR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b9385a73d61b03a1cd46b534d6525179d0e35560/crates/cairo-lang-semantic/src/types.rs#L408)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

closure.containing_function is an error case,
I think we should say that the function is not fully_concrete in this case.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 408 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1zImBC7K7QZa7MNG1L:-O2-S3P0E7d5m4ViToxH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a070ce5657c55ce1e5c94f3d874882468110681b/crates/cairo-lang-semantic/src/types.rs#L408)):*
> ```XML
>     /// It is `None` if we do not have the function id of the containing function (for example, if
>     /// there is a semantic error).
>     pub containing_function: Option<FunctionId>,
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 827 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O1zIPWz7ZI46AkZbGtd:-O2-Tl-3E8iNS0wN0Q5S:brawtna) ([raw file](https://github.com/starkware-libs/cairo/blob/a070ce5657c55ce1e5c94f3d874882468110681b/crates/cairo-lang-semantic/src/types.rs#L827)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It can have variables in the generic params of the calling function, right?
</blockquote></details>

I think generic params are all var_free
___
*[`crates/cairo-lang-semantic/src/expr/test_data/closure` line 11 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6015#-O2-Ohk04ir5cMhONGMJ:-O2-XauF-vjpTnBl1QSP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a070ce5657c55ce1e5c94f3d874882468110681b/crates/cairo-lang-semantic/src/expr/test_data/closure#L11)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

add paramaters with and without type annotations.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-17 12:31 UTC, orizi reviewed
> Reviewed 3 of 9 files at r10, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: 19 of 25 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-07-17 12:36 UTC, ilyalesokhin-starkware reviewed
> Reviewed 1 of 3 files at r9, 7 of 9 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-07-17 12:39 UTC, ilyalesokhin-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015#-:-O2-hCXbCGUfeRn4AmRG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-07-18 06:02 UTC, ilyalesokhin-starkware reviewed
> Reviewed 2 of 3 files at r9, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-07-18 06:08 UTC, orizi approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6015)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-07-18 09:01 UTC, merged