Tomerc/corelib array doc
starkware-libs/cairo pull request #6051
Opened 2024-07-23 09:50 UTC by Tomer-StarkWare

2024-07-23 10:14 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6051)* status: 0 of 260 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2U4YUQCpoKiM8Yq1B3):*
fix rebase


<!-- Sent from Reviewable.io -->

2024-07-23 10:16 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6051)* status: 0 of 260 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2U4YUQCpoKiM8Yq1B3):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix rebase
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-23 10:26 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6051)* status: 0 of 260 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`corelib/src/array.cairo` line 37 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2U5TK5EhPfVZ3-Etwo:-O2U5TK60TuQo8mN0bxD:b-wh9p2s) ([raw file](https://github.com/starkware-libs/cairo/blob/c9f316878687c9e247d3d8afb10acc7c9cbf65db/corelib/src/array.cairo#L37)):*
> ```Cairo
> extern fn array_len<T>(arr: @Array<T>) -> usize nopanic;
> 
> /// Implementation of the `FixedSizedArrayInfo` trait for arrays.
> ```

this is just not correct.
___
*[`corelib/src/array.cairo` line 53 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2U7Awo07QCkCVig0PE:-O2U7Awo07QCkCVig0PF:b473kg6) ([raw file](https://github.com/starkware-libs/cairo/blob/c9f316878687c9e247d3d8afb10acc7c9cbf65db/corelib/src/array.cairo#L53)):*
> ```Cairo
> /// assert!(arr.len() == 3);
> /// assert!(!arr.is_empty());
> /// assert!(arr.pop_front_consume() == Option::Some((array![4, 5], 3)));
> ```

examples should be for the methods. all around.



_Code quote:_
```Cairo
///
/// ```
/// let mut arr = array![];
/// arr.append(1);
/// arr.append(2);
/// assert!(arr.pop_front() == Option::Some(1));
/// assert!(arr.pop_front() == Option::Some(2));
/// assert!(arr.pop_front() == Option::None);
/// arr.append_span(array![3, 4, 5].span());
/// assert!(arr.get(1) == Option::Some(@4));
/// assert!(arr.at(1) == @4);
/// assert!(arr.len() == 3);
/// assert!(!arr.is_empty());
/// assert!(arr.pop_front_consume() == Option::Some((array![4, 5], 3)));
```


<!-- Sent from Reviewable.io -->

2024-07-23 12:13 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6051)* status: 0 of 260 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/array.cairo` line 37 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2U5TK5EhPfVZ3-Etwo:-O2UDpYP-PtN5iNBYL5g:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c9f316878687c9e247d3d8afb10acc7c9cbf65db/corelib/src/array.cairo#L37)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is just not correct.
</blockquote></details>

Done.
___
*[`corelib/src/array.cairo` line 53 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2U7Awo07QCkCVig0PE:-O2UVkRp8ls2jOVMxwnD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c9f316878687c9e247d3d8afb10acc7c9cbf65db/corelib/src/array.cairo#L53)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

examples should be for the methods. all around.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-23 12:36 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6051)* status: 0 of 260 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`corelib/src/array.cairo` line 267 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2U_G_Q4nEECk9_bz5F:-O2U_G_Q4nEECk9_bz5G:b-wiqgc6) ([raw file](https://github.com/starkware-libs/cairo/blob/663ad76e08406df85b19d063dc424fc3667fea58/corelib/src/array.cairo#L267)):*
> ```Cairo
> }
> 
> /// Implementation of the `SpanTrait` trait for spans.
> ```

this includes the definition of the trait itself - and the doc should be for the trait (both here and above).



_Suggestion:_
```Cairo
/// Basic trait for the `Span` type.
```
___
*[`corelib/src/array.cairo` line 270 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2U_nU52Gbk7-lhUrJ_:-O2U_nU52Gbk7-lhUrJa:b-ph44yr) ([raw file](https://github.com/starkware-libs/cairo/blob/663ad76e08406df85b19d063dc424fc3667fea58/corelib/src/array.cairo#L270)):*
> ```Cairo
> #[generate_trait]
> pub impl SpanImpl<T> of SpanTrait<T> {
>     /// # Examples
> ```

everywhere.



_Suggestion:_
```Cairo
    /// Example:
```


<!-- Sent from Reviewable.io -->

2024-07-23 12:46 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6051)* status: 0 of 260 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/array.cairo` line 267 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2U_G_Q4nEECk9_bz5F:-O2UbrIe8ioz_oFF3ByO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/663ad76e08406df85b19d063dc424fc3667fea58/corelib/src/array.cairo#L267)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this includes the definition of the trait itself - and the doc should be for the trait (both here and above).
</blockquote></details>

Done.
___
*[`corelib/src/array.cairo` line 270 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2U_nU52Gbk7-lhUrJ_:-O2UbrlIDrs7dj6JV52l:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/663ad76e08406df85b19d063dc424fc3667fea58/corelib/src/array.cairo#L270)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

everywhere.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-23 12:55 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6051)* status: 0 of 260 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`corelib/src/array.cairo` line 12 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2UeIdxDaRCI41xiCx4:-O2UeIdxDaRCI41xiCx5:b2ni8o8) ([raw file](https://github.com/starkware-libs/cairo/blob/523ff1316652f7eefc6389fac44fab05102d19ee/corelib/src/array.cairo#L12)):*
> ```Cairo
> use core::RangeCheck;
> 
> /// A macro to create an array.
> ```

no.
___
*[`corelib/src/array.cairo` line 40 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2UeCf_5qK8YRI4lz9u:-O2UeCf_5qK8YRI4lz9v:b-a11a8y) ([raw file](https://github.com/starkware-libs/cairo/blob/523ff1316652f7eefc6389fac44fab05102d19ee/corelib/src/array.cairo#L40)):*
> ```Cairo
> #[generate_trait]
> pub impl ArrayImpl<T> of ArrayTrait<T> {
>     /// Example:
> ```

you miss the actual doc - and have only an example everywhere.


<!-- Sent from Reviewable.io -->

2024-07-24 04:28 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6051)* status: 0 of 260 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/array.cairo` line 12 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2UeIdxDaRCI41xiCx4:-O2Xz_Us2WbzoWnN_p-G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/523ff1316652f7eefc6389fac44fab05102d19ee/corelib/src/array.cairo#L12)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no.
</blockquote></details>

Done.
___
*[`corelib/src/array.cairo` line 40 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2UeCf_5qK8YRI4lz9u:-O2Xydz469fvI02svXkf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/523ff1316652f7eefc6389fac44fab05102d19ee/corelib/src/array.cairo#L40)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you miss the actual doc - and have only an example everywhere.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-24 04:40 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6051)* status: 0 of 260 files reviewed, 19 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`corelib/src/array.cairo` line 12 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2UeIdxDaRCI41xiCx4:-O2Y-ELG7u2reueljgIb:b-c0igyr) ([raw file](https://github.com/starkware-libs/cairo/blob/523ff1316652f7eefc6389fac44fab05102d19ee/corelib/src/array.cairo#L12)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

A collection of elements of the same type continuous in memory.
___
*[`corelib/src/array.cairo` line 46 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y0L5p9KXMyEroIa7e:-O2Y0L5p9KXMyEroIa7f:beo8fy5) ([raw file](https://github.com/starkware-libs/cairo/blob/045ecd8e69cab8d301d1646fa95bf99ac1bd1770/corelib/src/array.cairo#L46)):*
> ```Cairo
>     /// ```
>     /// let mut arr = ArrayTrait::new();
>     /// ```
> ```

this example has no information - remove.



_Code quote:_
```Cairo
    /// Example:
    ///
    /// ```
    /// let mut arr = ArrayTrait::new();
    /// ```
```
___
*[`corelib/src/array.cairo` line 64 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y-Ymh0s9jvr7kMrve:-O2Y-Ymh0s9jvr7kMrvf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/045ecd8e69cab8d301d1646fa95bf99ac1bd1770/corelib/src/array.cairo#L64)):*
> ```Cairo
>         array_append(ref self, value)
>     }
>     /// Adds a span to the back of the array.
> ```





_Suggestion:_
```Cairo
    /// Adds a span to the end of the array.
```
___
*[`corelib/src/array.cairo` line 90 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y-z3M7M6b_pQkDPdz:-O2Y-z3M7M6b_pQkDPe-:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/045ecd8e69cab8d301d1646fa95bf99ac1bd1770/corelib/src/array.cairo#L90)):*
> ```Cairo
>     /// assert!(arr.pop_front() == Option::Some(2));
>     /// assert!(arr.pop_front() == Option::Some(3));
>     /// assert!(arr.pop_front() == Option::Some(4));
> ```





_Suggestion:_
```Cairo
    /// assert!(arr.pop_front() == Option::Some(4));
    /// assert!(arr.pop_front() == Option::None);
```
___
*[`corelib/src/array.cairo` line 101 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y-k3z1qfmKKCif95q:-O2Y-k3z1qfmKKCif95r:b-gaqzus) ([raw file](https://github.com/starkware-libs/cairo/blob/045ecd8e69cab8d301d1646fa95bf99ac1bd1770/corelib/src/array.cairo#L101)):*
> ```Cairo
>     /// Pops a value from the front of the array.
>     /// Return `Option::Some` containing the remaining array and
>     /// the value removed if the array is not empty, `Option::None` otherwise.
> ```

and rerun cairo-fmt.



_Suggestion:_
```Cairo
    /// Pops a value from the front of the array.
    /// Return `Option::Some` containing the remaining array and the value removed if the array is not empty, `Option::None` otherwise.
```
___
*[`corelib/src/array.cairo` line 106 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y-vvu2TF3_1ecI6Qt:-O2Y-vvu2TF3_1ecI6Qu:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/045ecd8e69cab8d301d1646fa95bf99ac1bd1770/corelib/src/array.cairo#L106)):*
> ```Cairo
>     ///
>     /// ```
>     /// let mut arr = array![2, 3, 4];
> ```





_Suggestion:_
```Cairo
    /// let arr = array![2, 3, 4];
```
___
*[`corelib/src/array.cairo` line 122 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y02bg4F9LuoPX5cl4:-O2Y02bg4F9LuoPX5cl5:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/045ecd8e69cab8d301d1646fa95bf99ac1bd1770/corelib/src/array.cairo#L122)):*
> ```Cairo
>     ///
>     /// ```
>     /// let mut arr = array![2, 3, 4];
> ```





_Suggestion:_
```Cairo
    /// let arr = array![2, 3, 4];
```
___
*[`corelib/src/array.cairo` line 135 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y04KZDDB8LDTX1fhR:-O2Y04KZDDB8LDTX1fhS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/045ecd8e69cab8d301d1646fa95bf99ac1bd1770/corelib/src/array.cairo#L135)):*
> ```Cairo
>     /// ```
>     /// let mut arr = array![2, 3, 4];
>     /// assert!(arr.at(1) == @4);
> ```





_Suggestion:_
```Cairo
    /// let arr = array![2, 3, 4];
    /// assert!(arr.at(1) == @4);
```
___
*[`corelib/src/array.cairo` line 145 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y08iG-pFTcwXlkQCo:-O2Y08iG-pFTcwXlkQCp:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/045ecd8e69cab8d301d1646fa95bf99ac1bd1770/corelib/src/array.cairo#L145)):*
> ```Cairo
>     ///
>     /// ```
>     /// let mut arr = array![2, 3, 4];
> ```





_Suggestion:_
```Cairo
    /// let arr = array![2, 3, 4];
```
___
*[`corelib/src/array.cairo` line 179 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y0D6AESQZt_lz96jb:-O2Y0D6AESQZt_lz96jc:beo8fy5) ([raw file](https://github.com/starkware-libs/cairo/blob/045ecd8e69cab8d301d1646fa95bf99ac1bd1770/corelib/src/array.cairo#L179)):*
> ```Cairo
>     /// let mut arr = array![1, 2, 3];
>     /// let span = arr.span();
>     /// ```
> ```

this example has no information - remove.



_Code quote:_
```Cairo
    ///
    /// Example:
    ///
    /// ```
    /// let mut arr = array![1, 2, 3];
    /// let span = arr.span();
    /// ```
```
___
*[`corelib/src/array.cairo` line 233 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y0YZQ83WjBCeSy-U1:-O2Y0YZR-rhX8WWoesuu:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/045ecd8e69cab8d301d1646fa95bf99ac1bd1770/corelib/src/array.cairo#L233)):*
> ```Cairo
> 
> /// A span is a view into a collection, which allows for safe and efficient access to the elements.
> pub struct Span<T> {
> ```





_Suggestion:_
```Cairo
/// A span is a view into a continuous collection of the same type - such as `Array`.
pub struct Span<T> {
```
___
*[`corelib/src/array.cairo` line 241 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y0T9Q75f09L7yP2TC:-O2Y0T9Q75f09L7yP2TD:beo8fy5) ([raw file](https://github.com/starkware-libs/cairo/blob/045ecd8e69cab8d301d1646fa95bf99ac1bd1770/corelib/src/array.cairo#L241)):*
> ```Cairo
>     /// ```
>     pub(crate) snapshot: @Array<T>
> }
> ```

this example has no information - remove.



_Suggestion:_
```Cairo
pub struct Span<T> {
    /// The snapshot of the array.
    pub(crate) snapshot: @Array<T>
}
```
___
*[`corelib/src/array.cairo` line 362 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y1P2z2fZTbj11y-Pl:-O2Y1P2z2fZTbj11y-Pm:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/045ecd8e69cab8d301d1646fa95bf99ac1bd1770/corelib/src/array.cairo#L362)):*
> ```Cairo
>     /// let mut span = array![1, 2, 3].span();
>     /// assert!(span.get(1) == Option::Some(@2));
>     /// ```
> ```





_Suggestion:_
```Cairo
    /// Example:
    /// ```
    /// let span = array![1, 2, 3].span();
    /// assert!(span.get(1) == Option::Some(@2));
    /// ```
```
___
*[`corelib/src/array.cairo` line 373 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y1NR19tzg4vuflCzR:-O2Y1NR19tzg4vuflCzS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/045ecd8e69cab8d301d1646fa95bf99ac1bd1770/corelib/src/array.cairo#L373)):*
> ```Cairo
>     /// let mut span = array![1, 2, 3].span();
>     /// assert!(span.at(1) == @2);
>     /// ```
> ```





_Suggestion:_
```Cairo
    /// Example:
    /// ```
    /// let span = array![1, 2, 3].span();
    /// assert!(span.at(1) == @2);
    /// ```
```
___
*[`corelib/src/array.cairo` line 385 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y1LQ_2bZeSwzsud3Q:-O2Y1LQ_2bZeSwzsud3R:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/045ecd8e69cab8d301d1646fa95bf99ac1bd1770/corelib/src/array.cairo#L385)):*
> ```Cairo
>     / [...]

2024-07-24 04:40 UTC, orizi requested changes
> Reviewed 258 of 258 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6051)* status: 258 of 260 files reviewed, 20 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`corelib/src/lib.cairo` line 240 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y1ZMc8OZiDmMb42Ms:-O2Y1ZMc8OZiDmMb42Mt:b-b6zgxf) ([raw file](https://github.com/starkware-libs/cairo/blob/045ecd8e69cab8d301d1646fa95bf99ac1bd1770/corelib/src/lib.cairo#L240)):*
> ```Cairo
> /// Implementation of the Span trait for Array.
> /// Implementation of the SpanIndexView trait for Span.
> /// Implementation of the SpanIter and ArrayIter traits.
> ```

don't write what it contains describe it in general instead.



_Code quote:_
```Cairo
/// Array.
/// Implementation of the ArrayTrait trait for Array.
/// Implementation of the Span trait for Array.
/// Implementation of the SpanIndexView trait for Span.
/// Implementation of the SpanIter and ArrayIter traits.
```


<!-- Sent from Reviewable.io -->

2024-07-24 07:02 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6051)* status: 258 of 260 files reviewed, 20 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/array.cairo` line 12 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2UeIdxDaRCI41xiCx4:-O2Y6PSn8Gacw8kDTcTn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/523ff1316652f7eefc6389fac44fab05102d19ee/corelib/src/array.cairo#L12)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

A collection of elements of the same type continuous in memory.
</blockquote></details>

Done.
___
*[`corelib/src/array.cairo` line 46 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y0L5p9KXMyEroIa7e:-O2Y6SvW4j8Gbz9rhU1Z:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7ee135f983ce36b5f4d62401f10e726dd8c21c/corelib/src/array.cairo#L46)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this example has no information - remove.
</blockquote></details>

Done.
___
*[`corelib/src/array.cairo` line 64 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y-Ymh0s9jvr7kMrve:-O2Y6_2S4D22Qxi2SN1u:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7ee135f983ce36b5f4d62401f10e726dd8c21c/corelib/src/array.cairo#L64)):*
> ```Cairo
>         array_append(ref self, value)
>     }
>     /// Adds a span to the back of the array.
> ```

Done.
___
*[`corelib/src/array.cairo` line 90 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y-z3M7M6b_pQkDPdz:-O2Y6eET8CEVzSOVT9Uo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7ee135f983ce36b5f4d62401f10e726dd8c21c/corelib/src/array.cairo#L90)):*
> ```Cairo
>     /// assert!(arr.pop_front() == Option::Some(2));
>     /// assert!(arr.pop_front() == Option::Some(3));
>     /// assert!(arr.pop_front() == Option::Some(4));
> ```

Done.
___
*[`corelib/src/array.cairo` line 101 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y-k3z1qfmKKCif95q:-O2Y73E6Dg39Wf2mVMrN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7ee135f983ce36b5f4d62401f10e726dd8c21c/corelib/src/array.cairo#L101)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and rerun cairo-fmt.
</blockquote></details>

Done.
___
*[`corelib/src/array.cairo` line 106 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y-vvu2TF3_1ecI6Qt:-O2Y72n-4FbHUqfETTDX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7ee135f983ce36b5f4d62401f10e726dd8c21c/corelib/src/array.cairo#L106)):*
> ```Cairo
>     ///
>     /// ```
>     /// let mut arr = array![2, 3, 4];
> ```

Done.
___
*[`corelib/src/array.cairo` line 122 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y02bg4F9LuoPX5cl4:-O2Y73n28CtDGSFHawu3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7ee135f983ce36b5f4d62401f10e726dd8c21c/corelib/src/array.cairo#L122)):*
> ```Cairo
>     ///
>     /// ```
>     /// let mut arr = array![2, 3, 4];
> ```

Done.
___
*[`corelib/src/array.cairo` line 135 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y04KZDDB8LDTX1fhR:-O2Y7PsM5u4TLhWULJ4X:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7ee135f983ce36b5f4d62401f10e726dd8c21c/corelib/src/array.cairo#L135)):*
> ```Cairo
>     /// ```
>     /// let mut arr = array![2, 3, 4];
>     /// assert!(arr.at(1) == @4);
> ```

Done.
___
*[`corelib/src/array.cairo` line 145 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y08iG-pFTcwXlkQCo:-O2Y7PJm4PnW31oS2mGb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7ee135f983ce36b5f4d62401f10e726dd8c21c/corelib/src/array.cairo#L145)):*
> ```Cairo
>     ///
>     /// ```
>     /// let mut arr = array![2, 3, 4];
> ```

Done.
___
*[`corelib/src/array.cairo` line 179 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y0D6AESQZt_lz96jb:-O2Y7Qfo3zugw18hA5jJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7ee135f983ce36b5f4d62401f10e726dd8c21c/corelib/src/array.cairo#L179)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this example has no information - remove.
</blockquote></details>

Done.
___
*[`corelib/src/array.cairo` line 233 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y0YZQ83WjBCeSy-U1:-O2Y7Uqe8w4dLeeAC1_Y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7ee135f983ce36b5f4d62401f10e726dd8c21c/corelib/src/array.cairo#L233)):*
> ```Cairo
> 
> /// A span is a view into a collection, which allows for safe and efficient access to the elements.
> pub struct Span<T> {
> ```

Done.
___
*[`corelib/src/array.cairo` line 241 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y0T9Q75f09L7yP2TC:-O2Y7YfM8L0nJoqi7qvh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7ee135f983ce36b5f4d62401f10e726dd8c21c/corelib/src/array.cairo#L241)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this example has no information - remove.
</blockquote></details>

Done.
___
*[`corelib/src/array.cairo` line 362 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y1P2z2fZTbj11y-Pl:-O2Y7fKg5NLY31TOCO60:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7ee135f983ce36b5f4d62401f10e726dd8c21c/corelib/src/array.cairo#L362)):*
> ```Cairo
>     /// let mut span = array![1, 2, 3].span();
>     /// assert!(span.get(1) == Option::Some(@2));
>     /// ```
> ```

Done.
___
*[`corelib/src/array.cairo` line 373 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y1NR19tzg4vuflCzR:-O2Y7i0j92oS-fQJdILz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7ee135f983ce36b5f4d62401f10e726dd8c21c/corelib/src/array.cairo#L373)):*
> ```Cairo
>     /// let mut span = array![1, 2, 3].span();
>     /// assert!(span.at(1) == @2);
>     /// ```
> ```

Done.
___
*[`corelib/src/array.cairo` line 385 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y1LQ_2bZeSwzsud3Q:-O2Y7j-EDlwL1pQrEp2t:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7ee135f983ce36b5f4d62401f10e726dd8c21c/corelib/src/array.cairo#L385)):*
> ```Cairo
>     /// let mut span = array![1, 2, 3].span();
>     /// assert!(span.slice(1, 2) == array![2, 3].span());
>     /// ```
> ```

Done.
___
*[`corelib/src/array.cairo` line 396 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y1JHr3EKcSDvd5FEv:-O2Y7jp18JxiyzXJ15yX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7ee135f983ce36b5f4d62401f10e726dd8c21c/corelib/src/array.cairo#L396)):*
> ```Cairo
>     /// let mut span = array![1, 2, 3].span();
>     /// assert!(span.len() == 3);
>     /// ```
> ```

Done.
___
*[`corelib/src/array.cairo` line 408 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y1HQr5BX5ZrDBVCmH:-O2Y7kCe136XdwjWHCDB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7ee135f983ce36b5f4d62401f10e726dd8c21c/corelib/src/array.cairo#L408)):*
> ```Cairo
>     /// let mut span = array![1, 2, 3].span();
>     /// assert!(!span.is_empty());
>     /// ```
> ```

Done.
___
*[`corelib/src/array.cairo` line 431 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y1AVY-CqYn5CCRZ8d:-O2Y87m88avsMFuGoWSl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7ee135f983ce36b5f4d62401f10e726dd8c21c/corelib/src/array.cairo#L431)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Can remove doc of impl fns.
</blockquote></details>

Done.
___
*[`corelib/src/array.cairo` line 446 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2Y1-YXCoXDkrjqhAKV:-O2Y8Glo71cSyhUZmBkz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cb7ee135f983ce36b5f4d62401f10e726dd8c21c/corelib/src/array.cairo#L446)):*
<details><sum [...]

2024-07-24 07:30 UTC, orizi requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6051)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`corelib/src/lib.cairo` line 238 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2YdR6o7bbeVheSqa3d:-O2YdR6o7bbeVheSqa3e:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/6d0f9f49d6005261c790fd50ee4eaca9477b182f/corelib/src/lib.cairo#L238)):*
> ```Cairo
> /// Array.
> /// contains Basic trait for the `Array` and 'Span' type, which are contintues collections of the
> /// same elements.
> ```





_Suggestion:_
```Cairo
/// Module for `Array` and other continuous same type collections.
```


<!-- Sent from Reviewable.io -->

2024-07-24 07:40 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6051)* status: 259 of 260 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/lib.cairo` line 238 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6051#-O2YdR6o7bbeVheSqa3d:-O2Yflk93xZHlL_ouhv0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6d0f9f49d6005261c790fd50ee4eaca9477b182f/corelib/src/lib.cairo#L238)):*
> ```Cairo
> /// Array.
> /// contains Basic trait for the `Array` and 'Span' type, which are contintues collections of the
> /// same elements.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-07-24 10:31 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6051#-:-O2ZHsVsC_Kkydp00-XQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2024-07-24 11:09 UTC, merged