diagnosting same paths storage
starkware-libs/cairo pull request #6099
Opened 2024-07-31 09:46 UTC by Tomer-StarkWare

2024-07-31 10:35 UTC, orizi requested changes
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O37LXtn7BlHxG8gpF6n:-O37LXtn7BlHxG8gpF6o:b-za70z6) ([raw file](https://github.com/starkware-libs/cairo/blob/2cc980010aa18c9bfc1d496a1a922fc67dbf6c6f/crates/cairo-lang-starknet/src/analyzer.rs#L83)):*
> ```XML
>     }
> }
> #[derive(Default, Debug)]
> ```

doc everything.
___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O37LuDb6VAbdh0WDPLx:-O37LuDb6VAbdh0WDPLy:b-jgkqwk) ([raw file](https://github.com/starkware-libs/cairo/blob/2cc980010aa18c9bfc1d496a1a922fc67dbf6c6f/crates/cairo-lang-starknet/src/analyzer.rs#L86)):*
> ```XML
> pub struct StorageAnalyzer;
> 
> impl AnalyzerPlugin for StorageAnalyzer {
> ```

any reason to be its own analyzer?
and not just an additional function for the existing analyzer?


<!-- Sent from Reviewable.io -->

2024-07-31 13:28 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O37LXtn7BlHxG8gpF6n:-O37yayW7gVG7JEY3OhT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2cc980010aa18c9bfc1d496a1a922fc67dbf6c6f/crates/cairo-lang-starknet/src/analyzer.rs#L83)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc everything.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O37LuDb6VAbdh0WDPLx:-O37ybY_Bi9eSqmUEFs-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2cc980010aa18c9bfc1d496a1a922fc67dbf6c6f/crates/cairo-lang-starknet/src/analyzer.rs#L86)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

any reason to be its own analyzer?
and not just an additional function for the existing analyzer?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-31 14:23 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 1 of 6 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O3875xI-o-k9ydUR1dj:-O3875xI-o-k9ydUR1dk:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b2ec97ba9b2119d0bdd76326ab2ec71f9a7f54c2/crates/cairo-lang-starknet/src/analyzer.rs#L84)):*
> ```XML
> }
> 
> /// Plugin to add diagnostics for contracts with multiple paths to the same place in the memory.
> ```





_Suggestion:_
```XML
/// Plugin to add diagnostics for contracts with multiple paths to the same location in storage.
```
___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O387LsZD8jj6_fat2ZD:-O387LsZD8jj6_fat2ZE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b2ec97ba9b2119d0bdd76326ab2ec71f9a7f54c2/crates/cairo-lang-starknet/src/analyzer.rs#L97)):*
> ```XML
>         // Analyze all the members of the struct.
>         for (id, item) in module_structs.iter() {
>             if !item.has_attr(db.upcast(), STORAGE_NODE_ATTR) {
> ```





_Suggestion:_
```XML
            if !item.has_attr(db.upcast(), STORAGE_NODE_ATTR) && !item.has_attr(db.upcast(), STORAGE_ATTR) {
```
___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O387oODEPiVbtjxICKj:-O387oODEPiVbtjxICKk:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b2ec97ba9b2119d0bdd76326ab2ec71f9a7f54c2/crates/cairo-lang-starknet/src/analyzer.rs#L123)):*
> ```XML
> pub struct StorageAnalyzerStatus {
>     pub term_to_virtual_paths: OrderedHashMap<SmolStr, (Vec<Vec<SmolStr>>, SyntaxStablePtrId)>,
> }
> ```





_Suggestion:_
```XML
/// Helper for the storage analyzer.
pub struct StorageStructMembers {
    /// Maps the name in actual storage to the path in actual user code.
    pub name_to_paths: OrderedHashMap<SmolStr, (Vec<Vec<SmolStr>>, SyntaxStablePtrId)>,
}
```
___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O388ZTjA9hnZa8m7MLY:-O388ZTjA9hnZa8m7MLZ:b3tmz53) ([raw file](https://github.com/starkware-libs/cairo/blob/b2ec97ba9b2119d0bdd76326ab2ec71f9a7f54c2/crates/cairo-lang-starknet/src/analyzer.rs#L160)):*
> ```XML
>         }
>     }
> }
> ```

add path and add diagnostic in the same function.

(the code changes are not exact - but that is the direction).



_Suggestion:_
```XML
    fn handle(
        &mut self,
        member_name: SmolStr,
        path_to_member: Vec<SmolStr>,
        pointer_to_code: SyntaxStablePtrId,
        diagnostics: &mut Vec<PluginDiagnostic>,
    ) {
        if let Some(existing_path) = name_to_paths.get(&member_name) {
            diagnostics.push(PluginDiagnostic::warning(
                *pointer_to_code,
                format!(
                    "{} different paths mapped to one actual path in memory.\n",
                    user_data_paths.len(),
                ) + user_data_paths
                    .iter()
                    .enumerate()
                    .map(|(index, path)| {
                        format!("                    {} path is: {}", index + 1, path.join("."))
                    })
                    .collect::<Vec<_>>()
                    .join("\n")
                    .as_str(),
            ));
        } else {
            self.term_to_virtual_paths.insert(member_name.clone(), (vec![], pointer_to_code));
        }
        self.term_to_virtual_paths.get_mut(&member_name).unwrap().0.push(user_data_path);
    }
}
```
___
*[`crates/cairo-lang-starknet/src/plugin/storage_test.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O389yXtEIPNXAdkFmXD:-O389yXtEIPNXAdkFmXE:b-haatkx) ([raw file](https://github.com/starkware-libs/cairo/blob/b2ec97ba9b2119d0bdd76326ab2ec71f9a7f54c2/crates/cairo-lang-starknet/src/plugin/storage_test.rs#L1)):*
> ```XML
> use cairo_lang_compiler::db::RootDatabase;
> ```

use same diagnostics test - no need for new file.
___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 55 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38A4LXAXqhMnEXNR8n:-O38A4LXAXqhMnEXNR8o:brijyrv) ([raw file](https://github.com/starkware-libs/cairo/blob/b2ec97ba9b2119d0bdd76326ab2ec71f9a7f54c2/crates/cairo-lang-starknet/src/test_data/storage_path_check#L55)):*
> ```
>                     2 path is: has_a.a
>  --> lib.cairo:39:5
>     a: felt252,
> ```

error should not be here - as this struct has no error.


<!-- Sent from Reviewable.io -->

2024-07-31 14:50 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 1 of 6 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O3875xI-o-k9ydUR1dj:-O38BDHD8Kkdi9TqwhQK:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2ec97ba9b2119d0bdd76326ab2ec71f9a7f54c2/crates/cairo-lang-starknet/src/analyzer.rs#L84)):*
> ```XML
> }
> 
> /// Plugin to add diagnostics for contracts with multiple paths to the same place in the memory.
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O387LsZD8jj6_fat2ZD:-O38BKz_0RFdFzVzWS0L:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2ec97ba9b2119d0bdd76326ab2ec71f9a7f54c2/crates/cairo-lang-starknet/src/analyzer.rs#L97)):*
> ```XML
>         // Analyze all the members of the struct.
>         for (id, item) in module_structs.iter() {
>             if !item.has_attr(db.upcast(), STORAGE_NODE_ATTR) {
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O387oODEPiVbtjxICKj:-O38BZ-EDGrOhcpisU01:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2ec97ba9b2119d0bdd76326ab2ec71f9a7f54c2/crates/cairo-lang-starknet/src/analyzer.rs#L123)):*
> ```XML
> pub struct StorageAnalyzerStatus {
>     pub term_to_virtual_paths: OrderedHashMap<SmolStr, (Vec<Vec<SmolStr>>, SyntaxStablePtrId)>,
> }
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O388ZTjA9hnZa8m7MLY:-O38BrbJ7X3-FzlGHCDa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b2ec97ba9b2119d0bdd76326ab2ec71f9a7f54c2/crates/cairo-lang-starknet/src/analyzer.rs#L160)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add path and add diagnostic in the same function.

(the code changes are not exact - but that is the direction).
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/storage_test.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O389yXtEIPNXAdkFmXD:-O38FqUF5550Dd9JqOMr:bq1ss6c) ([raw file](https://github.com/starkware-libs/cairo/blob/b2ec97ba9b2119d0bdd76326ab2ec71f9a7f54c2/crates/cairo-lang-starknet/src/plugin/storage_test.rs#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use same diagnostics test - no need for new file.
</blockquote></details>

I am not sure I understand; what is the other diagnostic test file? abi_test.rs?
___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 55 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38A4LXAXqhMnEXNR8n:-O38AvwF95vwd8SCxDNN:b-3zbdv9) ([raw file](https://github.com/starkware-libs/cairo/blob/b2ec97ba9b2119d0bdd76326ab2ec71f9a7f54c2/crates/cairo-lang-starknet/src/test_data/storage_path_check#L55)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

error should not be here - as this struct has no error.
</blockquote></details>

Isn't it from the beginning of the cairo code? meaning +6 rows?


<!-- Sent from Reviewable.io -->

2024-07-31 14:57 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 123 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38HoDo18youoclD6Dl:-O38HoDo18youoclD6Dm:bezfylo) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/analyzer.rs#L123)):*
> ```XML
> pub struct StorageStructMembers {
>     /// Maps the name in actual storage to the path in actual user code.
>     pub name_to_paths: OrderedHashSet<SmolStr>,
> ```

make this map to the path, so you'd point to it in the diag (as shown below)



_Code quote:_
```XML
    /// Maps the name in actual storage to the path in actual user code.
    pub name_to_paths: OrderedHashSet<SmolStr>,
```
___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 137 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38HS2DCJ1khm7800H0:-O38HS2DCJ1khm7800H1:b1sw8q4) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/analyzer.rs#L137)):*
> ```XML
>             diagnostics.push(PluginDiagnostic::warning(
>                 pointer_to_code,
>                 format!("The path {} collides with another path.", path_to_member.join("."),),
> ```

use the `path` from path to member.



_Suggestion:_
```XML
        if Some(existing_path) = self.name_to_paths.get(&member_name) {
            diagnostics.push(PluginDiagnostic::warning(
                pointer_to_code,
                format!("The path `{}` collides with existing path `{existing_path}`.", path_to_member.join("."),),
```


<!-- Sent from Reviewable.io -->

2024-07-31 15:06 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 1 of 6 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38JXgv1JXQuoQ128Pq:-O38JXgv1JXQuoQ128Pr:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/analyzer.rs#L99)):*
> ```XML
>             if !item.has_attr(db.upcast(), STORAGE_NODE_ATTR)
>                 && !item.has_attr(db.upcast(), STORAGE_ATTR)
>             {
> ```





_Suggestion:_
```XML
            if !item.has_attr(db.upcast(), STORAGE_NODE_ATTR)
                && !item.has_attr(db.upcast(), STORAGE_ATTR)
                && (item.name() == "Storage"
            {
```
___
*[`crates/cairo-lang-starknet/src/plugin/storage_test.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O389yXtEIPNXAdkFmXD:-O38I5iMCicO37-Svgpk:b2shaux) ([raw file](https://github.com/starkware-libs/cairo/blob/b2ec97ba9b2119d0bdd76326ab2ec71f9a7f54c2/crates/cairo-lang-starknet/src/plugin/storage_test.rs#L1)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

I am not sure I understand; what is the other diagnostic test file? abi_test.rs?
</blockquote></details>

thought to combine with general plugin diagnostics - but fine.
___
*[`crates/cairo-lang-starknet/src/plugin/storage_test.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38I_2tBnkGd5sGwnQ-:-O38I_2tBnkGd5sGwnQ0:bljob9k) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/plugin/storage_test.rs#L14)):*
> ```XML
> use crate::starknet_plugin_suite;
> 
> /// Helper function for testing ABI failures.
> ```

fix doc
___
*[`crates/cairo-lang-starknet/src/plugin/storage_test.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38Jr7I9lcIVSB_8ZCG:-O38Jr7I9lcIVSB_8ZCH:bnwl98i) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/plugin/storage_test.rs#L41)):*
> ```XML
>             ("expected_diagnostics".into(), diagnostics),
>             ("diagnostics".into(), diagnostic_string),
>         ]),
> ```

what are the different diag types?



_Code quote:_
```XML
        outputs: OrderedHashMap::from([
            ("expected_diagnostics".into(), diagnostics),
            ("diagnostics".into(), diagnostic_string),
        ]),
```
___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 55 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38A4LXAXqhMnEXNR8n:-O38JCab9pzCTEdKA3DQ:b-9fcttb) ([raw file](https://github.com/starkware-libs/cairo/blob/b2ec97ba9b2119d0bdd76326ab2ec71f9a7f54c2/crates/cairo-lang-starknet/src/test_data/storage_path_check#L55)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

Isn't it from the beginning of the cairo code? meaning +6 rows?
</blockquote></details>

probably - ok now.
___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 35 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38JHsJ3LhPvU6cOjkY:-O38JHsJ3LhPvU6cOjkZ:b-xqa1ur) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/test_data/storage_path_check#L35)):*
> ```
>         #[flat]
>         pub y: Struct0,
>     }
> ```

at least manually check with newest edition (where this should work properly).



_Code quote:_
```
    pub struct Storage {
        #[flat]
        pub x: IgnoredMemberStruct,
        #[flat]
        pub y: Struct0,
    }
```


<!-- Sent from Reviewable.io -->

2024-07-31 15:13 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 1 of 6 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38KhfS3UrQDLCP8PvG:-O38KhfS3UrQDLCP8PvH:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/analyzer.rs#L99)):*
> ```XML
>             if !item.has_attr(db.upcast(), STORAGE_NODE_ATTR)
>                 && !item.has_attr(db.upcast(), STORAGE_ATTR)
>             {
> ```





_Suggestion:_
```XML
            if !item.has_attr(db.upcast(), STORAGE_NODE_ATTR)
                && !item.has_attr(db.upcast(), STORAGE_ATTR)
                && (item.name(db.upcast()) != STORAGE_STRUCT_NAME
                   || (!module_id.has_attr(db, CONTRACT_ATTR)
                    && !module_id.has_attr(db, COMPONENT_ATTR)))
            {
```
___
*[`crates/cairo-lang-starknet/src/plugin/storage_test.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38Jr7I9lcIVSB_8ZCG:-O38Jz8XE8YdO3haWpzg:b-3dx8hb) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/plugin/storage_test.rs#L41)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what are the different diag types?
</blockquote></details>

you probably only want a single output in `expected_diagnostics`.


<!-- Sent from Reviewable.io -->

2024-07-31 15:14 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 1 of 6 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 35 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38LgFi-TBUd_18-JfM:-O38LgFi-TBUd_18-JfN:b9xw788) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/test_data/storage_path_check#L35)):*
> ```
>         #[flat]
>         pub y: Struct0,
>     }
> ```

split into different cases and make the tests more concise (the `ignored` stuff are less interesting here)



_Code quote:_
```
#[starknet::contract]
mod without_ignored {
    use core::starknet::storage::{StoragePointerReadAccess, StoragePointerWriteAccess};
    use super::{IgnoredMemberStruct, Struct0};
    #[storage]
    pub struct Storage {
        #[flat]
        pub x: IgnoredMemberStruct,
        #[flat]
        pub y: Struct0,
    }
```


<!-- Sent from Reviewable.io -->

2024-07-31 17:00 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38JXgv1JXQuoQ128Pq:-O38KVayAoUgO7ui0vEz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/analyzer.rs#L99)):*
> ```XML
>             if !item.has_attr(db.upcast(), STORAGE_NODE_ATTR)
>                 && !item.has_attr(db.upcast(), STORAGE_ATTR)
>             {
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38KhfS3UrQDLCP8PvG:-O38Rpm32OuqoltyPohZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/analyzer.rs#L99)):*
> ```XML
>             if !item.has_attr(db.upcast(), STORAGE_NODE_ATTR)
>                 && !item.has_attr(db.upcast(), STORAGE_ATTR)
>             {
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 123 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38HoDo18youoclD6Dl:-O38SFQN6qRiwXQ7Mht5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/analyzer.rs#L123)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

make this map to the path, so you'd point to it in the diag (as shown below)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 137 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38HS2DCJ1khm7800H0:-O38SbNG6am6J4wtuEsN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/analyzer.rs#L137)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use the `path` from path to member.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/storage_test.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38I_2tBnkGd5sGwnQ-:-O38dRYJ-ERgFhF4PRch:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/plugin/storage_test.rs#L14)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/storage_test.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38Jr7I9lcIVSB_8ZCG:-O38doYRELxMHJbT1OD1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/plugin/storage_test.rs#L41)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you probably only want a single output in `expected_diagnostics`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-31 17:06 UTC, orizi requested changes
> Reviewed 1 of 6 files at r1, 3 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 4 of 7 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/abi_test.rs` line 88 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38kHtQBa3ZejmGKExE:-O38kHtQBa3ZejmGKExF:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9aa7267b5d9950075a9587a8a42fa6b663a81a72/crates/cairo-lang-starknet/src/abi_test.rs#L88)):*
> ```XML
>         outputs: OrderedHashMap::from([("diagnostics".into(), diagnostic_string)]),
>         error: test_error,
>     }
> ```





_Suggestion:_
```XML
    let db = &mut RootDatabase::builder()
        .detect_corelib()
        .with_plugin_suite(starknet_plugin_suite())
        .build()
        .unwrap();
    let (_, cairo_code) = get_direct_or_file_content(&inputs["cairo_code"]);
    let (_, diagnostics) = setup_test_module(db, &cairo_code).split();
    let test_error = verify_diagnostics_expectation(args, &diagnostics);
    let diagnostic_string = diagnostics.format(db);

    TestRunnerResult {
        outputs: OrderedHashMap::from([("diagnostics".into(), diagnostic_string)]),
        error: test_error,
    }
```
___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38KhfS3UrQDLCP8PvG:-O38jrj57UX2ZiH3y39B:b-4d0lxq) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/analyzer.rs#L99)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you have the condition flipped.
___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 155 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38k0HVC035DI-qKqFa:-O38k0HVC035DI-qKqFb:bjjt57c) ([raw file](https://github.com/starkware-libs/cairo/blob/9aa7267b5d9950075a9587a8a42fa6b663a81a72/crates/cairo-lang-starknet/src/analyzer.rs#L155)):*
> ```XML
> }
> 
> /// Traverse the members of a struct and analyze them.
> ```

this doc means nothing.


<!-- Sent from Reviewable.io -->

2024-07-31 17:26 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 4 of 7 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/abi_test.rs` line 88 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38kHtQBa3ZejmGKExE:-O38ml5bEU6R7EqRaC4V:b-h1ga4v) ([raw file](https://github.com/starkware-libs/cairo/blob/9aa7267b5d9950075a9587a8a42fa6b663a81a72/crates/cairo-lang-starknet/src/abi_test.rs#L88)):*
> ```XML
>         outputs: OrderedHashMap::from([("diagnostics".into(), diagnostic_string)]),
>         error: test_error,
>     }
> ```

I didn't add diagnostic_string; I put diagnostics instead. 
___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38KhfS3UrQDLCP8PvG:-O38mRVg9-lU3aM2lfpr:bgp4xah) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/analyzer.rs#L99)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you have the condition flipped.
</blockquote></details>

But then it will go over struct Storage outside of contracts, components... I though it shouldn't, should it?
___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 155 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38k0HVC035DI-qKqFa:-O38om6RAvRoh5NwBRC3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9aa7267b5d9950075a9587a8a42fa6b663a81a72/crates/cairo-lang-starknet/src/analyzer.rs#L155)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this doc means nothing.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 35 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38LgFi-TBUd_18-JfM:-O38orAM5sjTGYp_xoxd:b-6xiay3) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/test_data/storage_path_check#L35)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

split into different cases and make the tests more concise (the `ignored` stuff are less interesting here)
</blockquote></details>

I'm not sure I follow, I added a component mod, fill like I'm missing the point there


<!-- Sent from Reviewable.io -->

2024-07-31 17:27 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 4 of 7 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/abi_test.rs` line 88 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38kHtQBa3ZejmGKExE:-O38p9Bp5U-CLvIVlaiC:b-1sbtpo) ([raw file](https://github.com/starkware-libs/cairo/blob/9aa7267b5d9950075a9587a8a42fa6b663a81a72/crates/cairo-lang-starknet/src/abi_test.rs#L88)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

I didn't add diagnostic_string; I put diagnostics instead.
</blockquote></details>

you shouldn't need to find any contract modules. remove it.


<!-- Sent from Reviewable.io -->

2024-07-31 17:29 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38KhfS3UrQDLCP8PvG:-O38pN8w1Yhn8jwJLU6e:bxe6y86) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/analyzer.rs#L99)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

But then it will go over struct Storage outside of contracts, components... I though it shouldn't, should it?
</blockquote></details>

look at the actual condition. this is the continue code.
___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 35 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38LgFi-TBUd_18-JfM:-O38piL_AMNnvHlJboVz:bll64bv) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/test_data/storage_path_check#L35)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

I'm not sure I follow, I added a component mod, fill like I'm missing the point there
</blockquote></details>

split into tests, and make it actually readable.
i cannot understand anything.


<!-- Sent from Reviewable.io -->

2024-07-31 17:34 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38KhfS3UrQDLCP8PvG:-O38qRX78D9GqWnMxFXH:bffezdm) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/analyzer.rs#L99)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

look at the actual condition. this is the continue code.
</blockquote></details>

Yea, we want it to continue to the next one if it equals by name to Storage (and not under contract and component), not sure why to put it as != instead of ==


<!-- Sent from Reviewable.io -->

2024-07-31 17:35 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/abi_test.rs` line 88 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38kHtQBa3ZejmGKExE:-O38r5iz0fcHbQJ4HzCE:b-slz0sd) ([raw file](https://github.com/starkware-libs/cairo/blob/9aa7267b5d9950075a9587a8a42fa6b663a81a72/crates/cairo-lang-starknet/src/abi_test.rs#L88)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you shouldn't need to find any contract modules. remove it.
</blockquote></details>

To remove what? the diagnostics?


<!-- Sent from Reviewable.io -->

2024-07-31 17:37 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 104 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38rCGK3Ogc6fir60IX:-O38rCGK3Ogc6fir60IY:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e3d9d43ca0fb98b5eb0631586c7492c3e92953d0/crates/cairo-lang-starknet/src/analyzer.rs#L104)):*
> ```XML
>                 && (item.name(db.upcast()).text(db.upcast()) != STORAGE_STRUCT_NAME
>                     || (!module_id.has_attr(db, CONTRACT_ATTR).unwrap()
>                         && !module_id.has_attr(db, COMPONENT_ATTR).unwrap()))
> ```





_Suggestion:_
```XML
                    || (!module_id.has_attr(db, CONTRACT_ATTR).unwrap_or_default()
                        && !module_id.has_attr(db, COMPONENT_ATTR).unwrap_or_default()))
```


<!-- Sent from Reviewable.io -->

2024-07-31 17:38 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/abi_test.rs` line 88 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38kHtQBa3ZejmGKExE:-O38rhGB8XSIWwTk1n0N:b1mp2wb) ([raw file](https://github.com/starkware-libs/cairo/blob/9aa7267b5d9950075a9587a8a42fa6b663a81a72/crates/cairo-lang-starknet/src/abi_test.rs#L88)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

To remove what? the diagnostics?
</blockquote></details>

now its ok.


<!-- Sent from Reviewable.io -->

2024-07-31 17:51 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 104 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38rCGK3Ogc6fir60IX:-O38uqvZAXluhUYTAOG6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e3d9d43ca0fb98b5eb0631586c7492c3e92953d0/crates/cairo-lang-starknet/src/analyzer.rs#L104)):*
> ```XML
>                 && (item.name(db.upcast()).text(db.upcast()) != STORAGE_STRUCT_NAME
>                     || (!module_id.has_attr(db, CONTRACT_ATTR).unwrap()
>                         && !module_id.has_attr(db, COMPONENT_ATTR).unwrap()))
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 35 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O38LgFi-TBUd_18-JfM:-O38uoC4AaWOghuSkZVn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4b02936ed6f03500fa3e8dbf3c8bba5d65549e1e/crates/cairo-lang-starknet/src/test_data/storage_path_check#L35)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

split into tests, and make it actually readable.
i cannot understand anything.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-31 19:47 UTC, orizi requested changes
> Reviewed 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 91 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O39KFnc7mkaNQAyCpiw:-O39KFnc7mkaNQAyCpix:b-4dpxd7) ([raw file](https://github.com/starkware-libs/cairo/blob/5f843f0ec831191ed739e17e97d20f595f13d102/crates/cairo-lang-starknet/src/test_data/storage_path_check#L91)):*
> ```
> }
> 
> //! > expected_error
> ```

Remove the expected_error field everywhere 
___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 93 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O39JzWF6FogNm9mjQny:-O39JzWF6FogNm9mjQnz:b-5xhdmx) ([raw file](https://github.com/starkware-libs/cairo/blob/5f843f0ec831191ed739e17e97d20f595f13d102/crates/cairo-lang-starknet/src/test_data/storage_path_check#L93)):*
> ```
> //! > expected_error
> 
> //! > diagnostics
> ```

Where's the diagnostic?
___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 133 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O39K3q95ze9agDCVzEC:-O39K3q95ze9agDCVzED:bb73xfv) ([raw file](https://github.com/starkware-libs/cairo/blob/5f843f0ec831191ed739e17e97d20f595f13d102/crates/cairo-lang-starknet/src/test_data/storage_path_check#L133)):*
> ```
> //! > expected_diagnostics
> 
> //! > diagnostics
> ```

Same


<!-- Sent from Reviewable.io -->

2024-07-31 20:25 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 93 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O39JzWF6FogNm9mjQny:-O39T0zuESL-5PyBvx2i:bas6wxt) ([raw file](https://github.com/starkware-libs/cairo/blob/5f843f0ec831191ed739e17e97d20f595f13d102/crates/cairo-lang-starknet/src/test_data/storage_path_check#L93)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

There aren't since that attributes in the storage are not considered flat (even with the flat attribute)
</blockquote></details>

Because....


<!-- Sent from Reviewable.io -->

2024-07-31 20:31 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 93 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O39JzWF6FogNm9mjQny:-O39TrUd8QiECAwCeMNp:b-k88dd2) ([raw file](https://github.com/starkware-libs/cairo/blob/5f843f0ec831191ed739e17e97d20f595f13d102/crates/cairo-lang-starknet/src/test_data/storage_path_check#L93)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Because....
</blockquote></details>

Because of what you told me in the office, it is a bit problematic to check it now, and I should only check it manually in the cargo toml. I'm not sure what was the exact reason, something with copying the struct and discards the flat attributes.


<!-- Sent from Reviewable.io -->

2024-07-31 21:12 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 174 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O39c_an2AH7orwbuP8h:-O39c_an2AH7orwbuP8i:b-u8dqs1) ([raw file](https://github.com/starkware-libs/cairo/blob/5f843f0ec831191ed739e17e97d20f595f13d102/crates/cairo-lang-starknet/src/analyzer.rs#L174)):*
> ```XML
> ) {
>     user_data_path.push(member_name.clone());
>     if !member.id.stable_ptr(db.upcast()).lookup(db.upcast()).has_attr(db.upcast(), FLAT_ATTR) {
> ```

handle substorage attr as well.



_Code quote:_
```XML
    if !member.id.stable_ptr(db.upcast()).lookup(db.upcast()).has_attr(db.upcast(), FLAT_ATTR) {
```
___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 93 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O39JzWF6FogNm9mjQny:-O39c0aBC-0JFnwZ_kWT:b-vmq608) ([raw file](https://github.com/starkware-libs/cairo/blob/5f843f0ec831191ed739e17e97d20f595f13d102/crates/cairo-lang-starknet/src/test_data/storage_path_check#L93)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

Because of what you told me in the office, it is a bit problematic to check it now, and I should only check it manually in the cargo toml. I'm not sure what was the exact reason, something with copying the struct and discards the flat attributes.
</blockquote></details>

i was talking about the fact that we couldn't recognize the struct, but we now managed to properly recognize it.
https://reviewable.io/reviews/starkware-libs/cairo/6106 this fixes the reexport of the attributes on the struct so you'd have them for the check.


<!-- Sent from Reviewable.io -->

2024-08-01 05:23 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 174 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O39c_an2AH7orwbuP8h:-O3BM_mo0HW5RsVmNnZJ:b-8ui0ob) ([raw file](https://github.com/starkware-libs/cairo/blob/5f843f0ec831191ed739e17e97d20f595f13d102/crates/cairo-lang-starknet/src/analyzer.rs#L174)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

handle substorage attr as well.
</blockquote></details>

Doesn't substorage work the same way? If it is flat, then continue, and if not, then stop.
___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 91 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O39KFnc7mkaNQAyCpiw:-O3BMNcL6MKybVHnxybu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5f843f0ec831191ed739e17e97d20f595f13d102/crates/cairo-lang-starknet/src/test_data/storage_path_check#L91)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Remove the expected_error field everywhere
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 93 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O39JzWF6FogNm9mjQny:-O3BMks0B-q-j324JQnt:bmh2udv) ([raw file](https://github.com/starkware-libs/cairo/blob/5f843f0ec831191ed739e17e97d20f595f13d102/crates/cairo-lang-starknet/src/test_data/storage_path_check#L93)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i was talking about the fact that we couldn't recognize the struct, but we now managed to properly recognize it.
https://reviewable.io/reviews/starkware-libs/cairo/6106 this fixes the reexport of the attributes on the struct so you'd have them for the check.
</blockquote></details>

Alright, I will rebase above it


<!-- Sent from Reviewable.io -->

2024-08-01 05:31 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 133 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O39K3q95ze9agDCVzEC:-O3BPx6n9DFxqbgMgWMk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5f843f0ec831191ed739e17e97d20f595f13d102/crates/cairo-lang-starknet/src/test_data/storage_path_check#L133)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-01 05:42 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 174 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O39c_an2AH7orwbuP8h:-O3BRqjd21yUmVlgTFbq:ba5fkr) ([raw file](https://github.com/starkware-libs/cairo/blob/5f843f0ec831191ed739e17e97d20f595f13d102/crates/cairo-lang-starknet/src/analyzer.rs#L174)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

Doesn't substorage work the same way? If it is flat, then continue, and if not, then stop.
</blockquote></details>

it does - but you don't check it here.
___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 21 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O3BSAVqAAnooetdGX9q:-O3BSAVqAAnooetdGX9r:b-hfpv23) ([raw file](https://github.com/starkware-libs/cairo/blob/8f30967cb1fa8a07794b571e03c630ce57fc3db5/crates/cairo-lang-starknet/src/test_data/storage_path_check#L21)):*
> ```
>     #[flat]
>     pub ignored_member: Struct0,
> }
> ```

remove.



_Code quote:_
```
#[starknet::storage_node]
struct Struct1 {
    pub member1: felt252,
}

#[starknet::storage_node]
struct Struct0 {
    pub member0: Struct1,
}

#[starknet::storage_node]
struct IgnoredMemberStruct {
    #[flat]
    pub ignored_member: Struct0,
}
```
___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 31 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O3BSHJI-dHi7oW2Zh-q:-O3BSHJI-dHi7oW2Zh-r:b-eke65k) ([raw file](https://github.com/starkware-libs/cairo/blob/8f30967cb1fa8a07794b571e03c630ce57fc3db5/crates/cairo-lang-starknet/src/test_data/storage_path_check#L31)):*
> ```
> struct ComponentNewStorage {
>     a: felt252,
>     #[flat]
> ```

add a similar test with a `HasHasA` struct (which has `HasA` as a flat member)


<!-- Sent from Reviewable.io -->

2024-08-01 05:50 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 174 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O39c_an2AH7orwbuP8h:-O3BUFZxBw4No-fhzr7i:bokgygr) ([raw file](https://github.com/starkware-libs/cairo/blob/5f843f0ec831191ed739e17e97d20f595f13d102/crates/cairo-lang-starknet/src/analyzer.rs#L174)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it does - but you don't check it here.
</blockquote></details>

Then I'm not sure why it needs special attention, it only depends on the flat attribute, what am I missing?


<!-- Sent from Reviewable.io -->

2024-08-01 05:53 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 174 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O39c_an2AH7orwbuP8h:-O3BUsRb8fKNJ2dvga3q:bh1iff1) ([raw file](https://github.com/starkware-libs/cairo/blob/5f843f0ec831191ed739e17e97d20f595f13d102/crates/cairo-lang-starknet/src/analyzer.rs#L174)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

Then I'm not sure why it needs special attention, it only depends on the flat attribute, what am I missing?
</blockquote></details>

what do you mean?
you need to check the substorage attribute - not just the flat attribute.


<!-- Sent from Reviewable.io -->

2024-08-01 06:12 UTC, orizi reviewed
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)



<!-- Sent from Reviewable.io -->

2024-08-01 06:29 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 174 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O39c_an2AH7orwbuP8h:-O3BYc8x8JfQD7W9aEKe:bs7wumb) ([raw file](https://github.com/starkware-libs/cairo/blob/5f843f0ec831191ed739e17e97d20f595f13d102/crates/cairo-lang-starknet/src/analyzer.rs#L174)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what do you mean?
you need to check the substorage attribute - not just the flat attribute.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 21 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O3BSAVqAAnooetdGX9q:-O3BcBrK7NSSoMXk2sFi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8f30967cb1fa8a07794b571e03c630ce57fc3db5/crates/cairo-lang-starknet/src/test_data/storage_path_check#L21)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-starknet/src/test_data/storage_path_check` line 31 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O3BSHJI-dHi7oW2Zh-q:-O3Bc9YD1roQ1uqWQDcy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8f30967cb1fa8a07794b571e03c630ce57fc3db5/crates/cairo-lang-starknet/src/test_data/storage_path_check#L31)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add a similar test with a `HasHasA` struct (which has `HasA` as a flat member)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-01 06:41 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/analyzer.rs` line 117 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O3BeImhEZiSCPH4d3dm:-O3Beg-S4OoldEPW20AS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a7e5404b045fc79333a5c01338feb461896ce9e2/crates/cairo-lang-starknet/src/analyzer.rs#L117)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this would make the diags point to better places.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-01 06:42 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099#-:-O3BfIu09Ft-5ieVWqfG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2024-08-01 06:54 UTC, orizi requested changes
> Reviewed 1 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_component` line 436 at r11](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O3Bi1fRD-UFu4Q0z5ku:-O3Bi1fRD-UFu4Q0z5kv:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/80481ef55e6f2066cbc4c8528a37d63ca2706dcf/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_component#L436)):*
> ```
> 
> //! > test_runner_name
> ExpandContractTestRunner(expect_diagnostics: true)
> ```





_Suggestion:_
```
ExpandContractTestRunner(expect_diagnostics: warnings_only)
```
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_component` line 1058 at r11](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O3Bi3eF-2FZG0YZC_Q9:-O3Bi3eF-2FZG0YZC_QA:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/80481ef55e6f2066cbc4c8528a37d63ca2706dcf/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_component#L1058)):*
> ```
> 
> //! > test_runner_name
> ExpandContractTestRunner(expect_diagnostics: true)
> ```





_Suggestion:_
```
ExpandContractTestRunner(expect_diagnostics: warnings_only)
```


<!-- Sent from Reviewable.io -->

2024-08-01 06:56 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_component` line 436 at r11](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O3Bi1fRD-UFu4Q0z5ku:-O3BiWmf93_O6QE8UqHO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/80481ef55e6f2066cbc4c8528a37d63ca2706dcf/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_component#L436)):*
> ```
> 
> //! > test_runner_name
> ExpandContractTestRunner(expect_diagnostics: true)
> ```

Done.
___
*[`crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_component` line 1058 at r11](https://reviewable.io/reviews/starkware-libs/cairo/6099#-O3Bi3eF-2FZG0YZC_Q9:-O3BiWVL7TyqQu8ugoJ5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/80481ef55e6f2066cbc4c8528a37d63ca2706dcf/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/with_component#L1058)):*
> ```
> 
> //! > test_runner_name
> ExpandContractTestRunner(expect_diagnostics: true)
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-08-01 07:03 UTC, orizi approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6099)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2024-08-01 07:23 UTC, merged