LS: fix panic in `lsp_helper` and move its logic to `LsSemanticGroup`
starkware-libs/cairo pull request #6159
Opened 2024-08-06 20:51 UTC by piotmag769

Code in `semantic/semantic_extension.rs` is the same as in previous `semantic.rs` besides trait name change `LsSemanticGroup` -> `LsSemanticGroupExtension`. Code in `semantic/mod.rs` is code from `lsp_helper.rs` + some code from trait definition `crates/cairo-lang-semantic/src/db.rs` wrapped into new salsa query group

2024-08-06 20:56 UTC, piotmag769 reviewed
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6159)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)



<!-- Sent from Reviewable.io -->

2024-08-07 04:35 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6159)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6159#-O3f6ekP9KcaU3VbBYxM:-O3f6ekP9KcaU3VbBYxN:bn8ws9v) (no related file):*
can you please split the fix and the move to different PRs?

___


<!-- Sent from Reviewable.io -->

2024-08-07 07:40 UTC, mkaput reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6159)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6159#-O3f6ekP9KcaU3VbBYxM:-O3flw0i8Owh-yypZWZr:bryldrj) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you please split the fix and the move to different PRs?
</blockquote></details>

also please just focus on adding stuff to LsSemanticGroup as it was. Please do not rush converting this trait into query group proper

___


<!-- Sent from Reviewable.io -->

2024-08-07 07:40 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6159)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @orizi)



<!-- Sent from Reviewable.io -->

2024-08-07 15:02 UTC, piotmag769 commented
Closing in favour of split PRs

2024-08-07 15:02 UTC, closed without merging