Added `WidePow2` trait.
starkware-libs/cairo pull request #6194
Opened 2024-08-12 11:12 UTC by orizi

Allowing optimized implementaion of WideMul squaring.

2024-08-13 07:13 UTC, gilbens-starkware approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6194)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-08-13 07:57 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6194)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/num/traits/ops/widepow2.cairo` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6194#-O49jVhc8Ctb-U7C82R1:-O49jVhc8Ctb-U7C82R2:broxpsm) ([raw file](https://github.com/starkware-libs/cairo/blob/6786aab2b94f1f1d88516b5e451a227ab594b44f/corelib/src/num/traits/ops/widepow2.cairo#L4)):*
> ```Cairo
> 
> /// A trait for a type that can be squared to produce a wider type.
> pub trait WidePow2<T> {
> ```

`WideSqr`. Pow2 is `2**x`


<!-- Sent from Reviewable.io -->

2024-08-13 07:59 UTC, TomerStarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6194#-:-O49jvfD-ZVpAzHIdO4Y:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-08-13 08:11 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6194)* status: all files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`corelib/src/num/traits/ops/widepow2.cairo` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6194#-O49jVhc8Ctb-U7C82R1:-O49mOun8D0QtUnmo074:burhk2a) ([raw file](https://github.com/starkware-libs/cairo/blob/6786aab2b94f1f1d88516b5e451a227ab594b44f/corelib/src/num/traits/ops/widepow2.cairo#L4)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

`WideSqr`. Pow2 is `2**x`
</blockquote></details>

`WideSqr` anywhere i found on the internet was still a square root.

more options?


<!-- Sent from Reviewable.io -->

2024-08-13 10:58 UTC, liorgold2 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6194)* status: 1 of 5 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

___
*[`corelib/src/num/traits/ops/widepow2.cairo` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6194#-O49jVhc8Ctb-U7C82R1:-O4ANbzO6bs_dnfOym_n:bpgvw0e) ([raw file](https://github.com/starkware-libs/cairo/blob/6786aab2b94f1f1d88516b5e451a227ab594b44f/corelib/src/num/traits/ops/widepow2.cairo#L4)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

`WideSqr` anywhere i found on the internet was still a square root.

more options?
</blockquote></details>

`WideSquare` is good
(BTW, from what I know `sqr` is square, `sqrt` is square root.)


<!-- Sent from Reviewable.io -->

2024-08-13 11:02 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6194)* status: 1 of 5 files reviewed, all discussions resolved (waiting on @gilbens-starkware)

___
*[`corelib/src/num/traits/ops/widepow2.cairo` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6194#-O49jVhc8Ctb-U7C82R1:-O4AOYoV1ecc-1Cldb_N:bo4vcev) ([raw file](https://github.com/starkware-libs/cairo/blob/6786aab2b94f1f1d88516b5e451a227ab594b44f/corelib/src/num/traits/ops/widepow2.cairo#L4)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

`WideSquare` is good
(BTW, from what I know `sqr` is square, `sqrt` is square root.)
</blockquote></details>

in general - true.
in microsoft SQL - Sqr == Square root :(
(and that was the only thing i actually found looking around).


<!-- Sent from Reviewable.io -->

2024-08-20 14:13 UTC, gilbens-starkware approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6194)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)



<!-- Sent from Reviewable.io -->

2024-08-20 14:13 UTC, gilbens-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6194)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @liorgold2)



<!-- Sent from Reviewable.io -->

2024-08-20 14:14 UTC, liorgold2 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6194)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-08-20 14:24 UTC, merged