LS: Consider empty strings in `workspace/configuration` as `None`
starkware-libs/cairo pull request #6247
Opened 2024-08-20 14:42 UTC by mkaput

It occurs that the `workspace/configuration`
request returns `Some("")` for the `cairo1.corelibPath`
field even if it is not set anywhere.
This fact blocked any logic that happened in the ` find_unmanaged_core `
function,
as it always assumed
that the user explicitly set the path in their config to `""`.
By nullifying empty configuration values, this change fixes
`find_unmanaged_core`.

2024-08-20 14:53 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6247)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/config.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6247#-O4kGVtC8KhzMu2zuvvT:-O4kGVtD8OLhsgKpnj7p:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/773f54ad2d8a2581c0363531e42c50478ff5a7f9/crates/cairo-lang-language-server/src/config.rs#L83)):*
> ```XML
> fn nullify_empty_str(value: &str) -> Option<&str> {
>     (!value.is_empty()).then_some(value)
> }
> ```





_Suggestion:_
```XML
            self.unmanaged_core_path = response
                .pop_front()
                .as_ref()
                .and_then(Value::as_str)
                .filter(|v|!v.is_empty())
                .map(Into::into);

            debug!("reloaded configuration: {self:#?}");
        }
    }
}
```


<!-- Sent from Reviewable.io -->

2024-08-21 07:27 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6247)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/config.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6247#-O4kGVtC8KhzMu2zuvvT:-O4npGK72ZjXvE--aSPJ:bdxsszt) ([raw file](https://github.com/starkware-libs/cairo/blob/773f54ad2d8a2581c0363531e42c50478ff5a7f9/crates/cairo-lang-language-server/src/config.rs#L83)):*
> ```XML
> fn nullify_empty_str(value: &str) -> Option<&str> {
>     (!value.is_empty()).then_some(value)
> }
> ```

:brain: 

Done


<!-- Sent from Reviewable.io -->

2024-08-21 08:51 UTC, Draggu approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6247#-:-O4o7Qiq1m-c8ZlW5gJV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @orizi, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-08-21 09:46 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6247#-:-O4oK37mC_38j9y1AE8B:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-08-21 18:13 UTC, piotmag769 approved these changes
>returns `Some("")` for the `cairo1.corelibPath`

Do you know why this happens? Isn't it an issue with our extension? Does it happen for other fields that are strings as well?

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6247#-:-O4q7fv27u7ys-PXjajq:b13r03u)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)



<!-- Sent from Reviewable.io -->

2024-08-22 09:46 UTC, mkaput reviewed
I tried to find a reason but couldn't conclude anything in reasonable time.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6247#-:-O4tTWMq0d1rcvx3phSG:bscopub)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)



<!-- Sent from Reviewable.io -->

2024-08-22 10:03 UTC, Arcticae approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6247#-:-O4tXi0T3txj8btHM47x:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkaput)



<!-- Sent from Reviewable.io -->

2024-08-22 10:40 UTC, merged