VSCode: Minor improvements in LS setup logic
starkware-libs/cairo pull request #6253
Opened 2024-08-21 12:34 UTC by mkaput

1. Moved `scarb cache clean` invocation into `Scarb` class and started
using its `execWithOutput` method for starting process
2. Moved `workspaceFolder` and `scarb`
initialization out of `getServerOptions`.
3. In the `cairo/corelib-version-mismatch ` notification,
changed the _clean scarb cache_ action to also reload the window
(as cleaning the cache itself is not causing immediate effects).
4. Various cosmetic changes.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6253)

2024-08-21 16:57 UTC, piotmag769 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6253#-:-O4pp9iQ1RiE4X3i6o8T:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @orizi)



<!-- Sent from Reviewable.io -->

2024-08-22 05:56 UTC, orizi approved these changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6253)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)



<!-- Sent from Reviewable.io -->

2024-08-22 09:54 UTC, Arcticae requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6253)* status: all files reviewed, 2 unresolved discussions (waiting on @Draggu and @mkaput)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6253#-O4tVLNr7_dsA4mSuElm):*
This seems like a nuclear option, shouldn't we do something else here instead?
___
*[`vscode-cairo/src/cairols.ts` line 122 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6253#-O4tVEzP1QMIR_kjuQUA:-O4tVEzP1QMIR_kjuQUB:b-3p9jpt) ([raw file](https://github.com/starkware-libs/cairo/blob/1c8a3508e9b4e468a9d5cb84066d892e61ccd665/vscode-cairo/src/cairols.ts#L122)):*
> ```XML
>   workspaceFolder: vscode.WorkspaceFolder | undefined,
>   ctx: Context,
> ): Promise<Scarb | undefined> {
> ```

Why not use `Option`? 


<!-- Sent from Reviewable.io -->

2024-08-22 14:05 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6253)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae and @Draggu)

___
*[`vscode-cairo/src/cairols.ts` line 122 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6253#-O4tVEzP1QMIR_kjuQUA:-O4uP-TD9eJD-d2det8d:b-8g0i3o) ([raw file](https://github.com/starkware-libs/cairo/blob/1c8a3508e9b4e468a9d5cb84066d892e61ccd665/vscode-cairo/src/cairols.ts#L122)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Why not use `Option`?
</blockquote></details>

This is TypeScript. We have no `Option` here


<!-- Sent from Reviewable.io -->

2024-08-22 14:20 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6253)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae and @Draggu)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6253#-O4tVLNr7_dsA4mSuElm):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

This seems like a nuclear option, shouldn't we do something else here instead?
</blockquote></details>

Hmm I think it could be possible to restart just the language client within the extension. Good catch but let's address this in separate task/PR for it: #6262 


<!-- Sent from Reviewable.io -->

2024-08-26 11:58 UTC, Arcticae approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6253#-:-O5DYFEl9QzLh_1rjWcz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu)



<!-- Sent from Reviewable.io -->

2024-08-26 13:35 UTC, merged