[LS]: Fix repeated diagnostics
starkware-libs/cairo pull request #6302
Opened 2024-08-28 09:02 UTC by Arcticae

This also remodels them to be fetched on a module basis instead on a file basis, which avoids fetching them twice for the same module

2024-08-28 10:11 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6302)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5NT0PxDfByHsNVhWuT:-O5NT0PyC4hWPDqqr_Z3:bw45mxa) (no related file):*
plz replace `[LS]:` with `LS:` for uniformity in commit messages

___


<!-- Sent from Reviewable.io -->

2024-08-28 10:16 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6302)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, and @piotmag769)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 275 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5NTQM9CHLaSis-VoqT:-O5NTQM9CHLaSis-VoqU:b6oowt9) ([raw file](https://github.com/starkware-libs/cairo/blob/f53a97cefe6e5bb7a6e46a4d5a70dcd89fcb1f83/crates/cairo-lang-diagnostics/src/diagnostics.rs#L275)):*
> ```XML
>     pub fn is_empty(&self) -> bool {
>         self.0.leaves.is_empty()
>     }
> ```

doc - also - note that this is quite likely not actually what you mean.



_Code quote:_
```XML
    pub fn is_empty(&self) -> bool {
        self.0.leaves.is_empty()
    }
```
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 271 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5NU4ssAMtsQJolaYD-:-O5NU4ssAMtsQJolaYD0:b-5pk7tc) ([raw file](https://github.com/starkware-libs/cairo/blob/f53a97cefe6e5bb7a6e46a4d5a70dcd89fcb1f83/crates/cairo-lang-language-server/src/lib.rs#L271)):*
> ```XML
> 
> impl FileDiagnostics {
>     fn is_empty(&self) -> bool {
> ```

this is *definitely* not what you actually mean.


<!-- Sent from Reviewable.io -->

2024-08-28 23:16 UTC, Arcticae reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6302)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @Draggu, @mkaput, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5NT0PxDfByHsNVhWuT:-O5QGgiKEqK9MOxaacqz:b-896fix) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

plz replace `[LS]:` with `LS:` for uniformity in commit messages
</blockquote></details>

Done.

___
___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 275 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5NTQM9CHLaSis-VoqT:-O5QEFh7DBWjFy-yXxaB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f53a97cefe6e5bb7a6e46a4d5a70dcd89fcb1f83/crates/cairo-lang-diagnostics/src/diagnostics.rs#L275)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc - also - note that this is quite likely not actually what you mean.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 271 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5NU4ssAMtsQJolaYD-:-O5QEISa4lcnEqGCcARJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f53a97cefe6e5bb7a6e46a4d5a70dcd89fcb1f83/crates/cairo-lang-language-server/src/lib.rs#L271)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is *definitely* not what you actually mean.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 570 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5O1J2V2dYobL9eKbIe:-O5QGcNE8MvJg8j1SSQV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f53a97cefe6e5bb7a6e46a4d5a70dcd89fcb1f83/crates/cairo-lang-language-server/src/lib.rs#L570)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

with this you won't pollute the scope with ambiguous `Iter` item.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-29 03:53 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6302)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 270 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5RFlXwDWu9bgLtKRmT:-O5RFlXxCljutzn6CooB:b4m75cz) ([raw file](https://github.com/starkware-libs/cairo/blob/9e57d80b5e218724a342bdc92075fb281478048f/crates/cairo-lang-language-server/src/lib.rs#L270)):*
> ```XML
> #[derive(Clone, Default)]
> struct State {
>     file_diagnostics: HashMap<Url, FileDiagnostics>,
> ```

Is the db double buffering removed?
If so, this will break it.


<!-- Sent from Reviewable.io -->

2024-08-29 09:31 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6302)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 270 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5RFlXwDWu9bgLtKRmT:-O5STKv-5Jg4n2oqX8iP:b-ynaf6l) ([raw file](https://github.com/starkware-libs/cairo/blob/9e57d80b5e218724a342bdc92075fb281478048f/crates/cairo-lang-language-server/src/lib.rs#L270)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

(as uris are stable - buf file-ids are not.
</blockquote></details>

db swap procedure should simply wipe this structure and this should be fine


<!-- Sent from Reviewable.io -->

2024-08-29 09:48 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6302)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 270 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5RFlXwDWu9bgLtKRmT:-O5SW_Gy4qr6ZHTWAQdP:b-lmfco) ([raw file](https://github.com/starkware-libs/cairo/blob/9e57d80b5e218724a342bdc92075fb281478048f/crates/cairo-lang-language-server/src/lib.rs#L270)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

db swap procedure should simply wipe this structure and this should be fine
</blockquote></details>


please make sure  - and further doc this state structure to contain the information and the difference between the two members (one FileId based, the other uri based)


<!-- Sent from Reviewable.io -->

2024-08-29 11:18 UTC, Arcticae reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6302)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 283 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5RjeHX9P9HLjxwE1gm:-O5SqwWM5iG7AFOgVJSz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c367b7f2d50f9b84e843a4196d70b81eadca769c/crates/cairo-lang-diagnostics/src/diagnostics.rs#L283)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

chain!(
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 270 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5RFlXwDWu9bgLtKRmT:-O5Snb349zRbSU1JKhaZ:bjxt0ec) ([raw file](https://github.com/starkware-libs/cairo/blob/9e57d80b5e218724a342bdc92075fb281478048f/crates/cairo-lang-language-server/src/lib.rs#L270)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

please make sure  - and further doc this state structure to contain the information and the difference between the two members (one FileId based, the other uri based)
</blockquote></details>

I will revert this to be URI based, i thought this storing salsa IDs would be necessary but it seems that it's not. Since wiping this struct is extra effort and not necessary right now, i won't be introducing it.


<!-- Sent from Reviewable.io -->

2024-08-29 11:39 UTC, orizi approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6302)* status: all files reviewed, 2 unresolved discussions (waiting on @Draggu, @mkaput, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-08-29 12:40 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6302#-:-O5T8hZzArOtyfzs_yXS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-08-29 13:36 UTC, piotmag769 requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6302#-:-O5TJ4dL92NomPCKUboE:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae and @Draggu)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 386 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5TJj_81xanmMqSZN7W:-O5TJj_95ZvY1FQjoltc:b72o2sa) ([raw file](https://github.com/starkware-libs/cairo/blob/f7681d58f46a1fa3020063f8c413de1fd75ec5c3/crates/cairo-lang-language-server/src/lib.rs#L386)):*
> ```XML
>         let mut processed_modules: HashSet<ModuleId> = HashSet::default();
> 
>         // Refresh open files modules
> ```

Inaccurate comment, you don't refresh anything here, you collect open files modules
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 433 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5TLKfp00uPPY6i6Edf:-O5TLKfp00uPPY6i6Edg:b-ocmt8u) ([raw file](https://github.com/starkware-libs/cairo/blob/f7681d58f46a1fa3020063f8c413de1fd75ec5c3/crates/cairo-lang-language-server/src/lib.rs#L433)):*
> ```XML
>         async {
>             for (file, file_modules_ids) in rest_of_files_modules {
>                 self.refresh_file_diagnostics(
> ```

Is there any point of doing it separately for the rest of the files? Seems like the logic is the same :thinking: 
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 567 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5TKPAU-0Pjl-FVMn5P:-O5TK9KtAFf7SUcj44fw:b2ni1b8) ([raw file](https://github.com/starkware-libs/cairo/blob/f7681d58f46a1fa3020063f8c413de1fd75ec5c3/crates/cairo-lang-language-server/src/lib.rs#L567)):*
> ```XML
>     }
> 
>     /// Gets the mapping of files to their respective modules
> ```

dot



_Suggestion:_
```XML
/// Gets the mapping of files to their respective modules.
```


<!-- Sent from Reviewable.io -->

2024-08-29 13:46 UTC, piotmag769 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6302)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae and @Draggu)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 480 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5TNk2D10Yztzc5OlzC:-O5TNk2D10Yztzc5OlzD:bud054e) ([raw file](https://github.com/starkware-libs/cairo/blob/f7681d58f46a1fa3020063f8c413de1fd75ec5c3/crates/cairo-lang-language-server/src/lib.rs#L480)):*
> ```XML
>         modules_ids: &Vec<ModuleId>,
>         processed_modules: &mut HashSet<ModuleId>,
>         files_set: &mut HashSet<Url>,
> ```

What are these, processed files?


<!-- Sent from Reviewable.io -->

2024-08-29 15:50 UTC, Draggu approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6302#-:-O5Toy3YCA7zSWG4PwHZ:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @piotmag769)



<!-- Sent from Reviewable.io -->

2024-08-29 15:51 UTC, mkaput approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6302)* status: all files reviewed, 4 unresolved discussions (waiting on @piotmag769)



<!-- Sent from Reviewable.io -->

2024-08-29 17:45 UTC, piotmag769 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6302#-:-O5UE1UO6BE5ybW8tXOL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 480 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5TNk2D10Yztzc5OlzC:-O5UEF1T5jOJ-rfMRQ-b:bd4e12y) ([raw file](https://github.com/starkware-libs/cairo/blob/f7681d58f46a1fa3020063f8c413de1fd75ec5c3/crates/cairo-lang-language-server/src/lib.rs#L480)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Those are files that actually do contain diagnostics after an update
</blockquote></details>

Can we name the arg and the variable in the function above so it is clear? I know it was there before, but I had to look for the context to get what this actually is


<!-- Sent from Reviewable.io -->

2024-08-30 09:08 UTC, mkaput approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6302)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae)



<!-- Sent from Reviewable.io -->

2024-08-30 12:57 UTC, mkaput requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6302)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 384 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5YLh1e9v4E7tByZeSB:-O5YLh1e9v4E7tByZeSC:bcvf6nc) ([raw file](https://github.com/starkware-libs/cairo/blob/ba98d14dfae999231491a48071346bd739a747eb/crates/cairo-lang-language-server/src/lib.rs#L384)):*
> ```XML
> 
>             self.with_state_mut(|state| {
>                 open_files.filter_map(|url| state.db.file_for_url(url)).collect()
> ```

file_for_url should work very fine on db snapshot
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 578 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5YLysc3F_nDdV10eXJ:-O5YLysc3F_nDdV10eXK:b-jyj675) ([raw file](https://github.com/starkware-libs/cairo/blob/ba98d14dfae999231491a48071346bd739a747eb/crates/cairo-lang-language-server/src/lib.rs#L578)):*
> ```XML
>             let mut result = HashMap::default();
>             for file_id in files_ids {
>                 if let Ok(file_modules) = state.db.file_modules(*file_id) {
> ```

again, I don't understand why you need owned state here


<!-- Sent from Reviewable.io -->

2024-08-30 13:15 UTC, Arcticae reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6302)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 384 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5YLh1e9v4E7tByZeSB:-O5YQ3QcCL67DBG6_oWp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ba98d14dfae999231491a48071346bd739a747eb/crates/cairo-lang-language-server/src/lib.rs#L384)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

file_for_url should work very fine on db snapshot
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 578 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5YLysc3F_nDdV10eXJ:-O5YQ4dj7SAZMGlpPcWy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ba98d14dfae999231491a48071346bd739a747eb/crates/cairo-lang-language-server/src/lib.rs#L578)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

again, I don't understand why you need owned state here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-30 13:23 UTC, mkaput approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6302)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)



<!-- Sent from Reviewable.io -->

2024-08-30 16:32 UTC, Arcticae reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6302)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 380 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6302#-O5YZBEZBQ8SZc1jVBgh:-O5Z7FsdEhQCYe_n_3nE:b3p07rb) ([raw file](https://github.com/starkware-libs/cairo/blob/1830036531bc79e6e5db53b796ba3b0f10663c95/crates/cairo-lang-language-server/src/lib.rs#L380)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I am not sure it is correct that you're taking state snapshots several times here. Won't this bring consistency problems? Shouldn't diagnostics be computed on **one** state snapshot in a single go?
</blockquote></details>

It's:
- Out of scope for this PR
- Not possible right now since the snapshot cannot be moved between threads 


<!-- Sent from Reviewable.io -->

2024-09-02 07:53 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6302#-:-O5liGjc-v1XXDNc-RMo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)



<!-- Sent from Reviewable.io -->

2024-09-02 08:50 UTC, merged