Doc comments/support module level comments
starkware-libs/cairo pull request #6317
Opened 2024-08-30 08:46 UTC by wawel37

2024-08-30 09:44 UTC, mkaput requested changes
> Reviewed 7 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: 7 of 17 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 728 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5Xe4jY75cv5BVkhstZ:-O5Xe4jY75cv5BVkhst_:bpca89l) ([raw file](https://github.com/starkware-libs/cairo/blob/bd77cb8e5877a44f5de8e31851b039294df46fd4/crates/cairo-lang-defs/src/ids.rs#L728)):*
> ```XML
>         let long_ids = self.lookup_intern(db);
>         let SyntaxStablePtr::Child { key_fields, kind, .. } = long_ids.1.0.lookup_intern(db)
>         else {
> ```

formatter issue? try running `scripts/rustfmt`
___
*[`crates/cairo-lang-language-server/tests/test_data/hover/basic.txt` line 137 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5XeOY-4y946a_DkDQr:-O5XeOY-4y946a_DkDQs:b-p75gbe) ([raw file](https://github.com/starkware-libs/cairo/blob/bd77cb8e5877a44f5de8e31851b039294df46fd4/crates/cairo-lang-language-server/tests/test_data/hover/basic.txt#L137)):*
> ```help
> ```
> ---
> `add_two` documentation. Adds 2 to an unsigned argument.
> ```

shouldn't these land in separate lines? what does Rust do?



_Suggestion:_
```help
`add_two` documentation.
Adds 2 to an unsigned argument.
```


<!-- Sent from Reviewable.io -->

2024-08-30 10:16 UTC, wawel37 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: 7 of 17 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 728 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5Xe4jY75cv5BVkhstZ:-O5XmBzV8GIc4nekYujp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bd77cb8e5877a44f5de8e31851b039294df46fd4/crates/cairo-lang-defs/src/ids.rs#L728)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

formatter issue? try running `scripts/rustfmt`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/tests/test_data/hover/basic.txt` line 137 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5XeOY-4y946a_DkDQr:-O5Xm-L6-2EUttWWVC7f:ba9hmhq) ([raw file](https://github.com/starkware-libs/cairo/blob/bd77cb8e5877a44f5de8e31851b039294df46fd4/crates/cairo-lang-language-server/tests/test_data/hover/basic.txt#L137)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

shouldn't these land in separate lines? what does Rust do?
</blockquote></details>

I've checked it in the rust-analyzer, and it actually just appends it in the same line


<!-- Sent from Reviewable.io -->

2024-08-30 10:51 UTC, mkaput requested changes
> Reviewed 2 of 17 files at r1, 7 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: 14 of 17 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-doc/src/documentable_item.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5XtESNAK4paXPJKT3q:-O5XtESNAK4paXPJKT3r:bq9569b) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/documentable_item.rs#L7)):*
> ```XML
> 
> #[derive(Copy, Clone, Debug, Hash, Eq, PartialEq)]
> pub enum DocumentableItemId {
> ```

I'm not sure if we need to provide special handling for crates, that would make DocumentableItemId separate from DocumentatbleModuleItemId a good thing.

1. we can assume some synthetic signature of a crate. say: `crate foobar`
2. we can easily short-circuit prefix comments logic for crates to always return `None`

why can't just just put everything in DocumentableItemId?
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5XttHW1Okff75yZP4I:-O5XttHW1Okff75yZP4J:b-cq29bw) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L64)):*
> ```XML
> }
> 
> fn parse_and_concat_documentation(mut md: String, item_documentation: Documentation) -> String {
> ```

I don't think we are interested in differentiating what parts are prefix, what are inner and what are module-level.

I see you're putting `---` between these parts, but why do you do this? Shouldn't we just glue everything into a single `String`? Can't this be done as low-level as possible?
___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 295 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5XsXRb1zeubBSmoNSB:-O5XsXRb1zeubBSmoNSC:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-syntax/src/node/mod.rs#L295)):*
> ```XML
>     /// The syntax db.
>     pub db: &'a dyn SyntaxGroup,
> }
> ```





_Suggestion:_
```XML
struct NodeInnerCommentFormatter<'a> {
    /// The node to format.
    node: &'a SyntaxNode,
    /// The syntax db.
    db: &'a dyn SyntaxGroup,
}
```


<!-- Sent from Reviewable.io -->

2024-08-30 11:02 UTC, mkaput reviewed
> Reviewed 1 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: 15 of 17 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, @piotmag769, and @wawel37)



<!-- Sent from Reviewable.io -->

2024-08-30 12:21 UTC, Draggu requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: 15 of 17 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @orizi, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-defs/src/db.rs` line 301 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5YAiWl-bYq41JvK9bu:-O5YAiWl-bYq41JvK9bv:bos8aes) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-defs/src/db.rs#L301)):*
> ```XML
>         ModuleId::Submodule(submodule_id) => {
>             let parent = submodule_id.parent_module(db);
>             if is_submodule_inline(db, submodule_id)? {
> ```

this should be called as `db.is_submodule_inline(submodule_id)`
___
*[`crates/cairo-lang-doc/src/db.rs` line 189 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5YD60qApQLKyNf9_uH:-O5YD60qApQLKyNf9_uI:b-7tehc7) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L189)):*
> ```XML
>         .lines()
>         .take_while_ref(|line| {
>             !line.trim_start().chars().next().map_or(false, |c| c.is_alphabetic())
> ```

Whats happening here?
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5YDpVg-eKzZiC5Xb2k:-O5YDpVg-eKzZiC5Xb2l:b-w5ttbz) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L73)):*
> ```XML
>         (prefix_comments, inner_comments, module_level_comments) => {
>             md += RULE;
>             let mut comments: Vec<String> = Vec::new();
> ```

Can we extend string directly instead?


<!-- Sent from Reviewable.io -->

2024-08-30 12:23 UTC, piotmag769 requested changes
> Reviewed 8 of 17 files at r1, 5 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 8 unresolved discussions (waiting on @Arcticae, @mkaput, @orizi, and @wawel37)

___
*[`crates/cairo-lang-doc/src/documentable_item.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5XtESNAK4paXPJKT3q:-O5YC_x22beX7_-cSWxX:b-yuypqv) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/documentable_item.rs#L7)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I'm not sure if we need to provide special handling for crates, that would make DocumentableItemId separate from DocumentatbleModuleItemId a good thing.

1. we can assume some synthetic signature of a crate. say: `crate foobar`
2. we can easily short-circuit prefix comments logic for crates to always return `None`

why can't just just put everything in DocumentableItemId?
</blockquote></details>

I think the struct should look like this

```rs
enum DocumentableItemId<'a> {
  Item(&'a dyn LanguageElementId),
  Crate(CrateId),
}
```

I know it is my struct, but I believe this is a cleaner way - every variant of variants of `LookupItemId` should implement `LangaugeElementId` (to be verified)
___
*[`crates/cairo-lang-doc/src/tests/test.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5YBv0b9YWEG9FshmFG:-O5YBv0b9YWEG9FshmFH:bd6ptp1) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/tests/test.rs#L17)):*
> ```XML
> 
> #[test]
> fn test_module_level_documentation() {
> ```

I believe this should be done using snapshot testing machinery from compiler tests, this will become unmaintainable very fast
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5YCHIb7s_DtyOKjnFJ:-O5YCHIb7s_DtyOKjnFK:b4iyjxk) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L50)):*
> ```XML
>             md += &fenced_code_block(&structure.signature(db));
>             let item_documentation = db.get_item_documentation((*member).into());
>             parse_and_concat_documentation(md, item_documentation)
> ```

Imo it should still return `Some(String)`, the code is clearer this way. No reason to distinguish between different parts of comments


<!-- Sent from Reviewable.io -->

2024-08-30 12:24 UTC, piotmag769 reviewed
> Reviewed 1 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 8 unresolved discussions (waiting on @Arcticae, @mkaput, @orizi, and @wawel37)



<!-- Sent from Reviewable.io -->

2024-08-30 12:44 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 8 unresolved discussions (waiting on @Arcticae, @orizi, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-doc/src/documentable_item.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5XtESNAK4paXPJKT3q:-O5YJ6Uv2BuK1ByPY2R9:bb590ea) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/documentable_item.rs#L7)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

I think the struct should look like this

```rs
enum DocumentableItemId<'a> {
  Item(&'a dyn LanguageElementId),
  Crate(CrateId),
}
```

I know it is my struct, but I believe this is a cleaner way - every variant of variants of `LookupItemId` should implement `LangaugeElementId` (to be verified)
</blockquote></details>

with dyn traits you loose strict typing, wouldn't do that


<!-- Sent from Reviewable.io -->

2024-09-01 05:53 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 9 unresolved discussions (waiting on @Arcticae, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-doc/src/db.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5g87k6BJy8u_NU06Iw:-O5g87k6BJy8u_NU06Ix:b-lw24iu) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L16)):*
> ```XML
> 
> #[derive(PartialEq, Eq, Debug, Clone, Serialize)]
> pub struct Documentation {
> ```

doc all.


<!-- Sent from Reviewable.io -->

2024-09-01 05:56 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 10 unresolved discussions (waiting on @Arcticae, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5g8ZrJBfZr_3Ysy8RG:-O5g8ZrJBfZr_3Ysy8RH:b3kqx) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L84)):*
> ```XML
>             }
>             md += &comments.join(" ");
>         }
> ```

.



_Suggestion:_
```XML
        (prefix_comments, inner_comments, module_level_comments) => {
            md += RULE;
            for comments in chain!(prefix_comments, inner_comments, module_level_comments) {
                md += comments.trim_end();
            }
        }
```


<!-- Sent from Reviewable.io -->

2024-09-01 06:06 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 21 unresolved discussions (waiting on @Arcticae, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-doc/src/db.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5g9M3M9lggwNFzPyad:-O5g9M3M9lggwNFzPyae:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L59)):*
> ```XML
> }
> 
> // Gets the crate level comments
> ```





_Suggestion:_
```XML
/// Gets the crate level documentation.
```
___
*[`crates/cairo-lang-doc/src/db.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5g9Ui50AG4WIjVJ97l:-O5g9Ui50AG4WIjVJ97m:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L65)):*
> ```XML
>         Ok(module_file_id) => extract_module_level_comments_from_file(db, module_file_id),
>         Err(_) => None,
>     }
> ```





_Suggestion:_
```XML
    let module_file_id = db.module_main_file(ModuleId::CrateRoot(crate_id)).ok()?;
    extract_module_level_comments_from_file(db, module_file_id)
```
___
*[`crates/cairo-lang-doc/src/db.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5g9i6WAIKvvDsRTavx:-O5g9i6WAIKvvDsRTavy:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L68)):*
> ```XML
> }
> 
> // Gets the "//!" inner comment of the item (if only item supports inner comments).
> ```





_Suggestion:_
```XML
/// Gets the "//!" inner comment of the item (if only item supports inner comments).
```
___
*[`crates/cairo-lang-doc/src/db.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5g9nIUCvjCgexUyHgR:-O5g9nIUCvjCgexUyHgS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L87)):*
> ```XML
>         }
>         _ => None,
>     }
> ```





_Suggestion:_
```XML
    if matches!(item_id, DocumentableModuleItemId::LookupItem(
        LookupItemId::ModuleItem(
            ModuleItemId::FreeFunction(_) | ModuleItemId::Submodule(_)
        ) | LookupItemId::ImplItem(ImplItemId::Function(_))
          | LookupItemId::TraitItem(TraitItemId::Function(_))
    ) {
        let raw_text = item_id
            .stable_location(db.upcast())
            .syntax_node(db.upcast())
            .get_shallow_inner_comments_text(db.upcast());
        extract_inner_comments_from_raw_text(raw_text, &["//!"])
    } else {
        None,
    }
```
___
*[`crates/cairo-lang-doc/src/db.rs` line 177 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5gB7g-9ZXFHBltlZ5T:-O5gB7g-9ZXFHBltlZ5U:b6p5sni) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L177)):*
> ```XML
>         .to_owned()
> }
> ```

all 3 functions seems to have considerable shared logic.
___
*[`crates/cairo-lang-doc/src/db.rs` line 178 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5gAO317dOzPlIeOSxy:-O5gAO317dOzPlIeOSxz:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L178)):*
> ```XML
> }
> 
> // Only gets the doc comments above the item.
> ```





_Suggestion:_
```XML
/// Only gets the doc comments above the item.
```
___
*[`crates/cairo-lang-doc/src/db.rs` line 201 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5gAQFu2gf-LR-MOljd:-O5gAQFu2gf-LR-MOlje:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L201)):*
> ```XML
> }
> 
> // Only gets the comments inside the item.
> ```





_Suggestion:_
```XML
/// Only gets the comments inside the item.
```
___
*[`crates/cairo-lang-doc/src/db.rs` line 219 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5gASbvBEIy6UJ2J3gf:-O5gASbvBEIy6UJ2J3gg:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L219)):*
> ```XML
> }
> 
> // Gets the module level comments of certain file.
> ```





_Suggestion:_
```XML
/// Gets the module level comments of certain file.
```
___
*[`crates/cairo-lang-doc/src/db.rs` line 242 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5gAVFJ7vx4YowBbGTC:-O5gAVFJ7vx4YowBbGTD:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L242)):*
> ```XML
> }
> 
> // Gets the module level comments of the item.
> ```





_Suggestion:_
```XML
/// Gets the module level comments of the item.
```
___
*[`crates/cairo-lang-doc/src/db.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5gAdAl4R0RQ87j8IY0:-O5gAdAl4R0RQ87j8IY1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L258)):*
> ```XML
>                 Ok(module_file_id) => extract_module_level_comments_from_file(db, module_file_id),
>                 Err(_) => None,
>             }
> ```





_Suggestion:_
```XML
            let module_file_id = db.module_main_file(ModuleId::Submodule(submodule_id)).ok()?;
            extract_module_level_comments_from_file(db, module_file_id)
```
___
*[`crates/cairo-lang-doc/src/db.rs` line 264 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5gAUEB85cNNChTBij3:-O5gAUEB85cNNChTBij4:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L264)):*
> ```XML
> }
> 
> fn map_raw_text_line_to_comment(line: &str, prefixes: &[&'static str]) -> Option<String> {
> ```

doc


<!-- Sent from Reviewable.io -->

2024-09-02 07:34 UTC, mkaput reviewed
> Reviewed 1 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 21 unresolved discussions (waiting on @Arcticae, @piotmag769, and @wawel37)



<!-- Sent from Reviewable.io -->

2024-09-02 14:39 UTC, wawel37 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: 5 of 20 files reviewed, 21 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-defs/src/db.rs` line 301 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5YAiWl-bYq41JvK9bu:-O5lrNxv5Km83yRb-rkL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-defs/src/db.rs#L301)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

this should be called as `db.is_submodule_inline(submodule_id)`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-doc/src/db.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5g87k6BJy8u_NU06Iw:-O5lquUcDltmtqyrixso:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L16)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc all.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-doc/src/db.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5g9M3M9lggwNFzPyad:-O5lqu2GBVCaAov0kFUb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L59)):*
> ```XML
> }
> 
> // Gets the crate level comments
> ```

Done.
___
*[`crates/cairo-lang-doc/src/db.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5g9Ui50AG4WIjVJ97l:-O5lqtcPE8TGfgPK6RxR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L65)):*
> ```XML
>         Ok(module_file_id) => extract_module_level_comments_from_file(db, module_file_id),
>         Err(_) => None,
>     }
> ```

Done.
___
*[`crates/cairo-lang-doc/src/db.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5g9i6WAIKvvDsRTavx:-O5lqt7N4Nmz1MTsKwFM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L68)):*
> ```XML
> }
> 
> // Gets the "//!" inner comment of the item (if only item supports inner comments).
> ```

Done.
___
*[`crates/cairo-lang-doc/src/db.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5g9nIUCvjCgexUyHgR:-O5lqsg03MbFE1H_n85z:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L87)):*
> ```XML
>         }
>         _ => None,
>     }
> ```

Done.
___
*[`crates/cairo-lang-doc/src/db.rs` line 177 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5gB7g-9ZXFHBltlZ5T:-O5ltvKJDVf2N4Jyzcpe:bjypyex) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L177)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

all 3 functions seems to have considerable shared logic.
</blockquote></details>

Done. I moved the cleanup part to separate function. The rest of the functions logic is imho better to leave separate, as each of them got a little bit different logic here and there.
___
*[`crates/cairo-lang-doc/src/db.rs` line 178 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5gAO317dOzPlIeOSxy:-O5lqrtjB10CFx8pYayB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L178)):*
> ```XML
> }
> 
> // Only gets the doc comments above the item.
> ```

Done.
___
*[`crates/cairo-lang-doc/src/db.rs` line 189 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5YD60qApQLKyNf9_uH:-O5lqg5nEecSbi7TWy5a:bgw5cyo) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L189)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Whats happening here?
</blockquote></details>

Takes the lines from the beginning that doesn't start with alphabetic characters ("/" isn't alphabetic). Added comments to each of the `take_while_ref` and `skip_while`
___
*[`crates/cairo-lang-doc/src/db.rs` line 201 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5gAQFu2gf-LR-MOljd:-O5lrVV3AM9-HtdbeZfa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L201)):*
> ```XML
> }
> 
> // Only gets the comments inside the item.
> ```

Done.
___
*[`crates/cairo-lang-doc/src/db.rs` line 219 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5gASbvBEIy6UJ2J3gf:-O5lsIixEQQ4aZJY_5BX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L219)):*
> ```XML
> }
> 
> // Gets the module level comments of certain file.
> ```

Done.
___
*[`crates/cairo-lang-doc/src/db.rs` line 242 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5gAVFJ7vx4YowBbGTC:-O5lsK0WC2_jiqzrD22r:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L242)):*
> ```XML
> }
> 
> // Gets the module level comments of the item.
> ```

Done.
___
*[`crates/cairo-lang-doc/src/db.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5gAdAl4R0RQ87j8IY0:-O5lsWCW1xUyeccmUDMW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L258)):*
> ```XML
>                 Ok(module_file_id) => extract_module_level_comments_from_file(db, module_file_id),
>                 Err(_) => None,
>             }
> ```

Done.
___
*[`crates/cairo-lang-doc/src/db.rs` line 264 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5gAUEB85cNNChTBij3:-O5lsYHI4JbbEgETe_Zx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L264)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-doc/src/documentable_item.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5XtESNAK4paXPJKT3q:-O5m3W7sE5jvVRbluH72:b-5i6a2g) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/documentable_item.rs#L7)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

with dyn traits you loose strict typing, wouldn't do that
</blockquote></details>

Ok, moved crate id to old DocumentableItemId and now there's only single enum left. The initial reason for creating separate enum was CrateId not having a `stable_location` impl. But now the stable_location just returns Option<String>.
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5YCHIb7s_DtyOKjnFJ:-O5lyC--5yiiKWFjArgz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L50)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Imo it should still return `Some(String)`, the code is clearer this way. No reason to distinguish between different parts of comments
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5XttHW1Okff75yZP4I:-O5m-FZY9h4EqhJFYWsE:b-5cubgm) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b690 [...]

2024-09-02 15:48 UTC, orizi requested changes
> Reviewed 4 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: 9 of 20 files reviewed, 12 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-doc/src/db.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5nOjNbDEzdRhkzmpoD:-O5nOjNbDEzdRhkzmpoE:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/178994fdc1763f7aaa2687a61545e6589faf776c/crates/cairo-lang-doc/src/db.rs#L44)):*
> ```XML
>             return write!(f, "");
>         }
>         write!(f, "{}", comments.join(""))
> ```





_Suggestion:_
```XML
        for (title, comment) in chain!(
            self.prefix_comments.as_ref().map(|c| ("Prefix", c),
            self.prefix_comments.as_ref().map(|c| ("Inner", c),
            self.prefix_comments.as_ref().map(|c| ("Module level", c),
        ) {
            writeln!("{title}:")?;
            write!("{comment}")?;
        }
        Ok(())
```
___
*[`crates/cairo-lang-doc/src/db.rs` line 256 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5nPsTs8Hqn9J1CmU1x:-O5nPsTs8Hqn9J1CmU1y:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/178994fdc1763f7aaa2687a61545e6589faf776c/crates/cairo-lang-doc/src/db.rs#L256)):*
> ```XML
> }
> 
> fn cleanup_doc(doc: String) -> Option<String> {
> ```

doc


<!-- Sent from Reviewable.io -->

2024-09-03 08:27 UTC, wawel37 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: 9 of 20 files reviewed, 11 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-doc/src/db.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5nOjNbDEzdRhkzmpoD:-O5qyjoa89B4jkSvNHQM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/178994fdc1763f7aaa2687a61545e6589faf776c/crates/cairo-lang-doc/src/db.rs#L44)):*
> ```XML
>             return write!(f, "");
>         }
>         write!(f, "{}", comments.join(""))
> ```

Done.
___
*[`crates/cairo-lang-doc/src/db.rs` line 256 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5nPsTs8Hqn9J1CmU1x:-O5qzlgi1Pj3Kvze96DB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/178994fdc1763f7aaa2687a61545e6589faf776c/crates/cairo-lang-doc/src/db.rs#L256)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-03 09:00 UTC, orizi requested changes
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: 10 of 20 files reviewed, 8 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 95 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5r5XsV9c6SbCWHWV_y:-O5r5XsV9c6SbCWHWV_z:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4c8ab901dfeb62fd3d2cc8b6c6a9024c516c98be/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L95)):*
> ```XML
>         return None;
>     }
>     Some(comments.join(" "))
> ```





_Suggestion:_
```XML
    match (
        item_documentation.prefix_comments,
        item_documentation.inner_comments,
        item_documentation.module_level_comments,
    ) {
        (None, None, None) => None,
        (prefix_comments, inner_comments, module_level_comments) => {
            Some(chain!(prefix_comments, inner_comments, module_level_comments).map(|c| c.trim_end()).join(" "))
        }
    } 
```


<!-- Sent from Reviewable.io -->

2024-09-03 10:21 UTC, wawel37 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: 10 of 20 files reviewed, 8 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 95 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5r5XsV9c6SbCWHWV_y:-O5rOiP0ChhbRJ4jXd8f:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4c8ab901dfeb62fd3d2cc8b6c6a9024c516c98be/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L95)):*
> ```XML
>         return None;
>     }
>     Some(comments.join(" "))
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-09-03 14:40 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: 10 of 20 files reviewed, 10 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 78 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5sIf3N6J4y0u5S9nAC:-O5sIf3N6J4y0u5S9nAD:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/e82bc39c408a3f71dfd99729e0b9e77d90845c78/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L78)):*
> ```XML
> }
> 
> fn parse_and_concat_documentation(item_documentation: Documentation) -> Option<String> {
> ```

doc
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 87 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5sJt4LCpL-ObquS7w8:-O5sJt4LCpL-ObquS7w9:b-rgrtki) ([raw file](https://github.com/starkware-libs/cairo/blob/e82bc39c408a3f71dfd99729e0b9e77d90845c78/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L87)):*
> ```XML
>         (prefix_comments, inner_comments, module_level_comments) => Some(
>             chain!(prefix_comments, inner_comments, module_level_comments)
>                 .map(|comment| comment.trim_end().to_string())
> ```

no need for the `to_string` if we are ref based.



_Suggestion:_
```XML
            chain!(&prefix_comments, &inner_comments, &module_level_comments)
                .map(|comment| comment.trim_end())
```
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 88 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5sJn8HCCbb6WACG9T_:-O5sJn8HCCbb6WACG9Ta:b-8mam7b) ([raw file](https://github.com/starkware-libs/cairo/blob/e82bc39c408a3f71dfd99729e0b9e77d90845c78/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L88)):*
> ```XML
>             chain!(prefix_comments, inner_comments, module_level_comments)
>                 .map(|comment| comment.trim_end().to_string())
>                 .collect::<Vec<_>>()
> ```

no need to collect.



_Code quote:_
```XML
                .collect::<Vec<_>>()
```


<!-- Sent from Reviewable.io -->

2024-09-03 15:06 UTC, mkaput requested changes
> Reviewed 1 of 8 files at r2, 12 of 15 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 12 unresolved discussions (waiting on @Arcticae, @Draggu, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-doc/src/db.rs` line 52 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5sG9s8-T_RA_fnKK-t:-O5sG9s8-T_RA_fnKK-u:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e82bc39c408a3f71dfd99729e0b9e77d90845c78/crates/cairo-lang-doc/src/db.rs#L52)):*
> ```XML
>     + DefsGroup
> {
>     // TODO(mkaput): Add tests.
> ```


___
*[`crates/cairo-lang-doc/src/db.rs` line 57 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5sOwVU4RCSNy3Yrcut:-O5sOwVU4RCSNy3Yrcuu:b-qkge0l) ([raw file](https://github.com/starkware-libs/cairo/blob/e82bc39c408a3f71dfd99729e0b9e77d90845c78/crates/cairo-lang-doc/src/db.rs#L57)):*
> ```XML
>     //   so that plugins would get a nice and clean syntax of documentation to manipulate further.
>     /// Gets the documentation above an item definition.
>     fn get_item_documentation(&self, item_id: DocumentableItemId) -> Documentation;
> ```

As far as I see, you're only making use of these separate fields in tests.

But do you really need to consider these fields as separate in fixtures? I think you can simply return a `String` from this query, and write tests in such a way, that each section will have a different content => you'll still preserve an ability to assert whether all sections are extracted properly.



_Suggestion:_
```XML
fn get_item_documentation(&self, item_id: DocumentableItemId) -> Option<String>;
```
___
*[`crates/cairo-lang-doc/src/db.rs` line 59 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5sGAx1-T3AMPeRRluJ:-O5sGAx1-T3AMPeRRluK:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/e82bc39c408a3f71dfd99729e0b9e77d90845c78/crates/cairo-lang-doc/src/db.rs#L59)):*
> ```XML
>     fn get_item_documentation(&self, item_id: DocumentableItemId) -> Documentation;
> 
>     // TODO(mkaput): Add tests.
> ```


___
*[`crates/cairo-lang-doc/src/db.rs` line 61 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5sO6OX3fQT5j9ukZdS:-O5sO6OX3fQT5j9ukZdT:b-4ocvus) ([raw file](https://github.com/starkware-libs/cairo/blob/e82bc39c408a3f71dfd99729e0b9e77d90845c78/crates/cairo-lang-doc/src/db.rs#L61)):*
> ```XML
>     // TODO(mkaput): Add tests.
>     /// Gets the signature of an item (i.e., item without its body).
>     fn get_item_signature(&self, item_id: DocumentableItemId) -> Option<String>;
> ```

IMHO Crates can have a following “synthetic” signature:

```rust
crate my_crate
```

It is semantically weird that something documentable has no signature.



_Suggestion:_
```XML
fn get_item_signature(&self, item_id: DocumentableItemId) -> String;
```
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5XttHW1Okff75yZP4I:-O5sNQgQ4-5IluiuvUWX:b-dhyvsq) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L64)):*
<details><summary><i>Previously, wawel37 (Mateusz Kowalski) wrote…</i></summary><blockquote>

The "---" is put only at the beginning to separate documentation comments from previous parts of hover content. The are actually glued to a single string right now, just separated with a single "---" before the docs are glued to the hover content as a whole.

Also, decided to move the "---" logic back to the `definition` function logic, as I think it's more related to this function rather than parsing the doc comments.
</blockquote></details>

I still don't get it, why all this logic lands in LS instead of being an internal detail of `DocGroup`?
___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 145 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5sPJpV3mdmzegXs_v9:-O5sPJpV3mdmzegXs_vA:b-z8a8g9) ([raw file](https://github.com/starkware-libs/cairo/blob/e82bc39c408a3f71dfd99729e0b9e77d90845c78/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L145)):*
> ```XML
>         let result: Vec<_> =
>             contexts.chain(this).filter_map(|item| db.get_item_signature(item.into())).collect();
>         if result.is_empty() {
> ```

it's surprising me that anything changes in this file


<!-- Sent from Reviewable.io -->

2024-09-04 09:25 UTC, wawel37 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: 17 of 21 files reviewed, 12 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-doc/src/db.rs` line 52 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5sG9s8-T_RA_fnKK-t:-O5wCtIb2-qqSk62NG3b:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e82bc39c408a3f71dfd99729e0b9e77d90845c78/crates/cairo-lang-doc/src/db.rs#L52)):*
> ```XML
>     + DefsGroup
> {
>     // TODO(mkaput): Add tests.
> ```

Done.
___
*[`crates/cairo-lang-doc/src/db.rs` line 57 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5sOwVU4RCSNy3Yrcut:-O5wD0P-6qtSL5axVH5O:brvunfi) ([raw file](https://github.com/starkware-libs/cairo/blob/e82bc39c408a3f71dfd99729e0b9e77d90845c78/crates/cairo-lang-doc/src/db.rs#L57)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

As far as I see, you're only making use of these separate fields in tests.

But do you really need to consider these fields as separate in fixtures? I think you can simply return a `String` from this query, and write tests in such a way, that each section will have a different content => you'll still preserve an ability to assert whether all sections are extracted properly.
</blockquote></details>

The thing about that return type of this query is:
1. Imho this group responsibility is just to provide a doc for an item. Actually parsing it in a certain way should be done on the behalf of the module using it. This way, it's up to module how it want to parse the docs.
2. Actually, the LS documentation displaying is a little bit different than for example Scarb doc. We could return the String from that function, but it would force LS and Scarb to be parsing those strings separately in their own different ways.
___
*[`crates/cairo-lang-doc/src/db.rs` line 59 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5sGAx1-T3AMPeRRluJ:-O5wDstr7XolIR7Z36Pa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e82bc39c408a3f71dfd99729e0b9e77d90845c78/crates/cairo-lang-doc/src/db.rs#L59)):*
> ```XML
>     fn get_item_documentation(&self, item_id: DocumentableItemId) -> Documentation;
> 
>     // TODO(mkaput): Add tests.
> ```

Done.
___
*[`crates/cairo-lang-doc/src/db.rs` line 61 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5sO6OX3fQT5j9ukZdS:-O5wHHPRA9VyDS2TxHy-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e82bc39c408a3f71dfd99729e0b9e77d90845c78/crates/cairo-lang-doc/src/db.rs#L61)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

IMHO Crates can have a following “synthetic” signature:

```rust
crate my_crate
```

It is semantically weird that something documentable has no signature.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5XttHW1Okff75yZP4I:-O5wHQpvE7aZn_lS21SC:br9u1r4) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L64)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I still don't get it, why all this logic lands in LS instead of being an internal detail of `DocGroup`?
</blockquote></details>

It's the same reason as above (return type of `get_item_documentation`). It's not like I'm 100% sure it's a ideal approach, but I think having doc type returned this way, gives everybody more flexibility when it comes to other modules using it.
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 78 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5sIf3N6J4y0u5S9nAC:-O5wIR7b4CuHGbEfJ46t:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e82bc39c408a3f71dfd99729e0b9e77d90845c78/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L78)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 87 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5sJt4LCpL-ObquS7w8:-O5wIYR05Ck1F7WPfajY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e82bc39c408a3f71dfd99729e0b9e77d90845c78/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L87)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no need for the `to_string` if we are ref based.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 88 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5sJn8HCCbb6WACG9T_:-O5wI_QHBwEB7DXgRoR4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e82bc39c408a3f71dfd99729e0b9e77d90845c78/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L88)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no need to collect.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 145 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5sPJpV3mdmzegXs_v9:-O5wJAskCJXnxnaG-Ftr:b-due4cg) ([raw file](https://github.com/starkware-libs/cairo/blob/e82bc39c408a3f71dfd99729e0b9e77d90845c78/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L145)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

it's surprising me that anything changes in this file
</blockquote></details>

As we go back to `get_item_signature` returning just `String`, i reverted all the changes to the `signature` function here.


<!-- Sent from Reviewable.io -->

2024-09-04 10:10 UTC, orizi requested changes
> Reviewed 1 of 8 files at r2, 3 of 15 files at r3, 1 of 2 files at r4, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 11 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 175 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5wVcTj39n7b--w62_3:-O5wVcTj39n7b--w62_4:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/da7215cc1821e116af3af2bfb20ca48775a67cdd/crates/cairo-lang-syntax/src/node/mod.rs#L175)):*
> ```XML
>     }
> 
>     pub fn get_shallow_inner_comments_text(&self, db: &dyn SyntaxGroup) -> String {
> ```

doc


<!-- Sent from Reviewable.io -->

2024-09-04 12:56 UTC, Draggu requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 10 unresolved discussions (waiting on @Arcticae, @mkaput, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-doc/src/db.rs` line 189 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5YD60qApQLKyNf9_uH:-O5x2sgx2_0fDaHDv20x:bexw2k3) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L189)):*
<details><summary><i>Previously, wawel37 (Mateusz Kowalski) wrote…</i></summary><blockquote>

Takes the lines from the beginning that doesn't start with alphabetic characters ("/" isn't alphabetic). Added comments to each of the `take_while_ref` and `skip_while`
</blockquote></details>

So this is to match non `/` chars? If so this should be `!= '/'`, or maybe i'm missing something? Also can we reuse this instead of copy-pasting?
___
*[`crates/cairo-lang-doc/src/db.rs` line 259 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5x3FRP56HdcL6tWQj_:-O5x3FRP56HdcL6tWQja:b-1m5n7s) ([raw file](https://github.com/starkware-libs/cairo/blob/da7215cc1821e116af3af2bfb20ca48775a67cdd/crates/cairo-lang-doc/src/db.rs#L259)):*
> ```XML
> 
>     // Nullify empty or just-whitespace documentation strings as they are not useful.
>     (!doc.trim().is_empty()).then_some(doc)
> ```

Use `.not()`
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5YDpVg-eKzZiC5Xb2k:-O5x5n4s1GcnwEq1dlIi:bsyxm6x) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L73)):*
<details><summary><i>Previously, wawel37 (Mateusz Kowalski) wrote…</i></summary><blockquote>

Needed to have a " " separator. We collet them into a vector, to put the separator only between the existing parts. We don't want this separator to be placed at the end of the whole string.
</blockquote></details>

Removing last char would be faster, but i don't have strong opinion on this.
___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 309 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5x42MKCo7YIs7Bn3_D:-O5x42ML6zKQ-khwV0g5:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/da7215cc1821e116af3af2bfb20ca48775a67cdd/crates/cairo-lang-syntax/src/node/mod.rs#L309)):*
> ```XML
>                     if kind != SyntaxKind::FunctionWithBody
>                         && kind != SyntaxKind::ItemModule
>                         && kind != SyntaxKind::TraitItemFunction
> ```





_Suggestion:_
```XML
                    if !matches(kind, SyntaxKind::FunctionWithBody | SyntaxKind::ItemModule | SyntaxKind::TraitItemFunction)
```


<!-- Sent from Reviewable.io -->

2024-09-04 13:05 UTC, piotmag769 requested changes
> Reviewed 4 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 14 unresolved discussions (waiting on @Arcticae, @mkaput, and @wawel37)

___
*[`crates/cairo-lang-doc/src/db.rs` line 26 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5x2niT3fgo6GU1-Bqq:-O5x2niT3fgo6GU1-Bqr:bi7t592) ([raw file](https://github.com/starkware-libs/cairo/blob/da7215cc1821e116af3af2bfb20ca48775a67cdd/crates/cairo-lang-doc/src/db.rs#L26)):*
> ```XML
>     /// It's a comment that's on the top of the file starting with "//!".
>     /// It can relate either to module or a crate.
>     pub module_level_comments: Option<String>,
> ```

It is basically an inner comment, I believe this distinction is superficial
___
*[`crates/cairo-lang-doc/src/db.rs` line 79 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5x6uxH2zLykyOXztAZ:-O5x6uxH2zLykyOXztA_:b1iwmss) ([raw file](https://github.com/starkware-libs/cairo/blob/da7215cc1821e116af3af2bfb20ca48775a67cdd/crates/cairo-lang-doc/src/db.rs#L79)):*
> ```XML
> 
> /// Gets the crate level documentation.
> fn get_crate_documentation(db: &dyn DocGroup, crate_id: CrateId) -> Option<String> {
> ```

In cairo: crate == package without metadata



_Suggestion:_
```XML
fn get_crate_root_module_documentation(db: &dyn DocGroup, crate_id: CrateId) -> Option<String> {
```
___
*[`crates/cairo-lang-doc/src/db.rs` line 95 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5x7_6J9D1sEV7DygTZ:-O5x7_6J9D1sEV7DygT_:bk0nzvi) ([raw file](https://github.com/starkware-libs/cairo/blob/da7215cc1821e116af3af2bfb20ca48775a67cdd/crates/cairo-lang-doc/src/db.rs#L95)):*
> ```XML
>     ) {
>         let raw_text = item_id
>             .stable_location(db.upcast())?
> ```

I believe this can just be unwrapped, it should never fail and we have it tested. Same in other places.
cc @mkaput since he may have sth against it
___
*[`crates/cairo-lang-doc/src/db.rs` line 282 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5x5Vn641HTU8XNnCZj:-O5x5Vn641HTU8XNnCZk:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/da7215cc1821e116af3af2bfb20ca48775a67cdd/crates/cairo-lang-doc/src/db.rs#L282)):*
> ```XML
> /// 2. If it starts with one of the passed prefixes, removes the given prefixes (including the space
> ///    after the prefix).
> fn map_raw_text_line_to_comment(line: &str, prefixes: &[&'static str]) -> Option<String> {
> ```





_Suggestion:_
```XML
fn extract_comment_from_code_line(line: &str, comment_markers: &[&'static str]) -> Option<String> {
```
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5XttHW1Okff75yZP4I:-O5x2YMm6wMN2DgbRTPT:bmezr4e) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L64)):*
<details><summary><i>Previously, wawel37 (Mateusz Kowalski) wrote…</i></summary><blockquote>

It's the same reason as above (return type of `get_item_documentation`). It's not like I'm 100% sure it's a ideal approach, but I think having doc type returned this way, gives everybody more flexibility when it comes to other modules using it.
</blockquote></details>

I agree with @mkaput here


<!-- Sent from Reviewable.io -->

2024-09-04 13:09 UTC, piotmag769 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 14 unresolved discussions (waiting on @Arcticae, @mkaput, and @wawel37)

___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 290 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5x8OwM-ELDgccy97ux:-O5x8OwM-ELDgccy97uy:bg35y9k) ([raw file](https://github.com/starkware-libs/cairo/blob/da7215cc1821e116af3af2bfb20ca48775a67cdd/crates/cairo-lang-syntax/src/node/mod.rs#L290)):*
> ```XML
> }
> 
> struct NodeInnerCommentFormatter<'a> {
> ```

I don't understand what it does. Does it really format comments? I believe it doesn't format anything, it is just for displaying sth, I'm not sure what exactly


<!-- Sent from Reviewable.io -->

2024-09-04 14:08 UTC, mkaput requested changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 12 unresolved discussions (waiting on @Arcticae, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-doc/src/db.rs` line 57 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5sOwVU4RCSNy3Yrcut:-O5xKimC6mnYN1rmTxQu:b-5cqmdi) ([raw file](https://github.com/starkware-libs/cairo/blob/e82bc39c408a3f71dfd99729e0b9e77d90845c78/crates/cairo-lang-doc/src/db.rs#L57)):*
<details><summary><i>Previously, wawel37 (Mateusz Kowalski) wrote…</i></summary><blockquote>

The thing about that return type of this query is:
1. Imho this group responsibility is just to provide a doc for an item. Actually parsing it in a certain way should be done on the behalf of the module using it. This way, it's up to module how it want to parse the docs.
2. Actually, the LS documentation displaying is a little bit different than for example Scarb doc. We could return the String from that function, but it would force LS and Scarb to be parsing those strings separately in their own different ways.
</blockquote></details>

Yes, you outlined the responsibility correctly. But, the definition of item doc is that it is a concatenation of all parts. I am 100% sure no tool will ever need to consider what parts are in `///` or what are in `//!`. What's more, as I'd like to have the `#[doc]` attribute, things would become much harder because you'd have to express cases like this:

```rust
/// Docs line 1
#[doc = "Docs line 2\n"]
/// Docs line 3
fn foo() {
    //! Docs line 4
    #![doc = "Docs line 5\n"]
    //! Docs line 6
}
```

Keeping the process of joining all of this as low as possible will make everyone's life easier.


---

What are the differences between LS and `scarb doc`? I expected both to render the same things.
___
*[`crates/cairo-lang-doc/src/db.rs` line 95 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5x7_6J9D1sEV7DygTZ:-O5xLp_DAklyFgQMhkyz:b-59u6tc) ([raw file](https://github.com/starkware-libs/cairo/blob/da7215cc1821e116af3af2bfb20ca48775a67cdd/crates/cairo-lang-doc/src/db.rs#L95)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

I believe this can just be unwrapped, it should never fail and we have it tested. Same in other places.
cc @mkaput since he may have sth against it
</blockquote></details>

I would avoid `unwrap` at all cost. Doing `let Some(...) = ... else { unreachable!(...) }` is preferable to me, but here? I'd stay with this `?` for simplicity sake.
___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 18 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5xMDSc5-prOW8ZH16z:-O5xMDSc5-prOW8ZH17-:bpcwtdo) ([raw file](https://github.com/starkware-libs/cairo/blob/da7215cc1821e116af3af2bfb20ca48775a67cdd/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L18)):*
> ```XML
> use cairo_lang_syntax::node::{SyntaxNode, Terminal, TypedSyntaxNode};
> use cairo_lang_utils::Upcast;
> use itertools::Itertools;
> ```

dead import


<!-- Sent from Reviewable.io -->

2024-09-05 10:56 UTC, wawel37 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: 13 of 20 files reviewed, 12 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-doc/src/db.rs` line 189 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5YD60qApQLKyNf9_uH:-O60QT0f0DiR5x4kLRGk:b-bqeufu) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-doc/src/db.rs#L189)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

So this is to match non `/` chars? If so this should be `!= '/'`, or maybe i'm missing something? Also can we reuse this instead of copy-pasting?
</blockquote></details>

Done. Moved it to a separate function and changed the logic to only check the "//" line prefixes.
___
*[`crates/cairo-lang-doc/src/db.rs` line 57 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5sOwVU4RCSNy3Yrcut:-O60n-i2Dy8dhVYQu4dt:b-v2bt6u) ([raw file](https://github.com/starkware-libs/cairo/blob/e82bc39c408a3f71dfd99729e0b9e77d90845c78/crates/cairo-lang-doc/src/db.rs#L57)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Yes, you outlined the responsibility correctly. But, the definition of item doc is that it is a concatenation of all parts. I am 100% sure no tool will ever need to consider what parts are in `///` or what are in `//!`. What's more, as I'd like to have the `#[doc]` attribute, things would become much harder because you'd have to express cases like this:

```rust
/// Docs line 1
#[doc = "Docs line 2\n"]
/// Docs line 3
fn foo() {
    //! Docs line 4
    #![doc = "Docs line 5\n"]
    //! Docs line 6
}
```

Keeping the process of joining all of this as low as possible will make everyone's life easier.


---

What are the differences between LS and `scarb doc`? I expected both to render the same things.
</blockquote></details>

Done. You're right. As i thought more about that, it's better to make the LS and scarb-doc display docs in the same way. So now, we don't need `Documentation` struct, and we just return already formatted documentation ready to be displayed.
___
*[`crates/cairo-lang-doc/src/db.rs` line 26 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5x2niT3fgo6GU1-Bqq:-O60mtB0D23uaWGYXRdg:bwdpjqi) ([raw file](https://github.com/starkware-libs/cairo/blob/da7215cc1821e116af3af2bfb20ca48775a67cdd/crates/cairo-lang-doc/src/db.rs#L26)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

It is basically an inner comment, I believe this distinction is superficial
</blockquote></details>

Done. Removed the Documentation struct completly, as we return `Option<String>` from the `get_item_documentation`.
___
*[`crates/cairo-lang-doc/src/db.rs` line 79 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5x6uxH2zLykyOXztAZ:-O60IWtY0fkzu4nidLL8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/da7215cc1821e116af3af2bfb20ca48775a67cdd/crates/cairo-lang-doc/src/db.rs#L79)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

In cairo: crate == package without metadata
</blockquote></details>

Done.
___
*[`crates/cairo-lang-doc/src/db.rs` line 259 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5x3FRP56HdcL6tWQj_:-O60RJ-T0Ke63e2ofs0g:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/da7215cc1821e116af3af2bfb20ca48775a67cdd/crates/cairo-lang-doc/src/db.rs#L259)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Use `.not()`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-doc/src/db.rs` line 282 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5x5Vn641HTU8XNnCZj:-O60RSaV03a_QxMMFyVB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/da7215cc1821e116af3af2bfb20ca48775a67cdd/crates/cairo-lang-doc/src/db.rs#L282)):*
> ```XML
> /// 2. If it starts with one of the passed prefixes, removes the given prefixes (including the space
> ///    after the prefix).
> fn map_raw_text_line_to_comment(line: &str, prefixes: &[&'static str]) -> Option<String> {
> ```

Done.
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5XttHW1Okff75yZP4I:-O60mdD68KicWRcA0w7R:bpqgj19) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L64)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

I agree with @mkaput here
</blockquote></details>

Done. I changed it completely. Now the get_item_documentation returns already formatted and ready to be displayed string (Optional, because there's a possibility, that the item doesn't have any docs).
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5YDpVg-eKzZiC5Xb2k:-O60TOmM7Sb-WNskAo6d:byjfl1e) ([raw file](https://github.com/starkware-libs/cairo/blob/9c81798ce2f2b69050e163831787fb8eba71b466/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L73)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Removing last char would be faster, but i don't have strong opinion on this.
</blockquote></details>

I think for the sake of readability, it's better to leave the `.trim_end()` here.
___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 175 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5wVcTj39n7b--w62_3:-O60g3sN77w9AWsEt_qs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/da7215cc1821e116af3af2bfb20ca48775a67cdd/crates/cairo-lang-syntax/src/node/mod.rs#L175)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 290 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5x8OwM-ELDgccy97ux:-O60exfR9X5AIdxDPH0A:bs93bvi) ([raw file](https://github.com/starkware-libs/cairo/blob/da7215cc1821e116af3af2bfb20ca48775a67cdd/crates/cairo-lang-syntax/src/node/mod.rs#L290)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

I don't understand what it does. Does it really format comments? I believe it doesn't format anything, it is just for displaying sth, I'm not sure what exactly
</blockquote></details>

Done. Changed the formatter to just a function.
___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 309 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5x42MKCo7YIs7Bn3_D:-O60gutI3oNKIQ7mVvqg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/da7215cc1821e116af3af2bfb20ca48775a67cdd/crates/cairo-lang-syntax/src/node/mod.rs#L309)):*
> ```XML
>                     if kind != SyntaxKind::FunctionWithBody
>                         && kind != SyntaxKind::ItemModule
>                         && kind != SyntaxKind::TraitItemFunction
> ```

Done.
___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 18 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5xMDSc5-prOW8ZH16z:-O60UBt5CXxSvYtc3pFT:bej86eb) ([raw file](https://github.com/starkware-libs/cairo/blob/da7215cc1821e116af3af2bfb20ca48775a67cdd/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L18)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

dead import
</blockquote></details>

Extends the Iterator trait. Can't use `join` fn on the `Map` object without it.


<!-- Sent from Reviewable.io -->

2024-09-05 12:09 UTC, orizi approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 10 unresolved discussions (waiting on @Arcticae, @Draggu, @piotmag769, and @wawel37)



<!-- Sent from Reviewable.io -->

2024-09-05 12:19 UTC, Draggu requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 13 unresolved discussions (waiting on @Arcticae, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-doc/src/db.rs` line 282 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5x5Vn641HTU8XNnCZj:-O616Wce9Ec2fke43DMQ:b3c46g4) ([raw file](https://github.com/starkware-libs/cairo/blob/da7215cc1821e116af3af2bfb20ca48775a67cdd/crates/cairo-lang-doc/src/db.rs#L282)):*
<details><summary><i>Previously, wawel37 (Mateusz Kowalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done. (`comment_markers`)
___
*[`crates/cairo-lang-doc/src/db.rs` line 198 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O616Jt08s3Xaw3G-uws:-O616Jt08s3Xaw3G-uwt:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/db.rs#L198)):*
> ```XML
>         .lines()
>         .filter(|line| !line.trim().is_empty())
>         .skip_while(|line| is_comment_line(line) || line.is_empty())
> ```


___
*[`crates/cairo-lang-doc/src/db.rs` line 212 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O615spv62ih3f_Wg-et:-O615spv62ih3f_Wg-eu:bcuk3fz) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/db.rs#L212)):*
> ```XML
>         .lines()
>         .filter(|line| !line.trim().is_empty())
>         .take_while_ref(|line| is_comment_line(line) || line.trim().is_empty())
> ```

First we filter non empty lines, this cannot happen.
___
*[`crates/cairo-lang-doc/src/db.rs` line 230 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O6150HwDdGmc2ya0OEY:-O6150HwDdGmc2ya0OEZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/db.rs#L230)):*
> ```XML
> 
>     // Nullify empty or just-whitespace documentation strings as they are not useful.
>     (doc.trim().is_empty().not()).then_some(doc)
> ```





_Suggestion:_
```XML
doc.trim().is_empty().not()
```
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 30 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O614LBPEvsteIsQrC9h:-O616s-c9Wg0rnAusy_t:bhemtwl) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L30)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

and now you'd make no changes in this file in this PR
</blockquote></details>

@wawel37 this `ln` is good but not in this PR


<!-- Sent from Reviewable.io -->

2024-09-05 16:25 UTC, piotmag769 requested changes
> Reviewed 3 of 15 files at r3, 1 of 2 files at r4, 2 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 12 unresolved discussions (waiting on @Arcticae, @Draggu, and @wawel37)

___
*[`crates/cairo-lang-doc/src/db.rs` line 39 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O61uxJsBnpdo-EuBb3l:-O61uxJsBnpdo-EuBb3m:brqy7hx) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/db.rs#L39)):*
> ```XML
>         DocumentableItemId::Crate(crate_id) => get_crate_root_module_documentation(db, crate_id),
>         item_id => {
>             let prefix_comments = extract_prefixed_comments_from_raw_text(db, item_id);
> ```

Naming is inconsistent - I would name the functions starting with `extract` everywhere
___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 178 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O61yA_UB1XWILlOCS1-:-O61yA_UB1XWILlOCS10:buu2onq) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-syntax/src/node/mod.rs#L178)):*
> ```XML
>     /// It ignores all the inner elements, that can contain their own inner comments (functions and
>     /// modules).
>     pub fn get_shallow_inner_comments_text(&self, db: &dyn SyntaxGroup) -> String {
> ```

You could just return `String` from the func before and delete this one. I would merge comments from both funcs and name it a bit better - I don't think this name says really well what this func does
___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 301 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O61xwV1BLmh_EJSCmcb:-O61xwV1BLmh_EJSCmcc:b-u1ujtc) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-syntax/src/node/mod.rs#L301)):*
> ```XML
>     node: &SyntaxNode,
>     buffer: &mut String,
> ) -> std::fmt::Result {
> ```

Isn't it better to just return a String here? You wouldn't need the func above


<!-- Sent from Reviewable.io -->

2024-09-05 16:26 UTC, piotmag769 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 13 unresolved discussions (waiting on @Arcticae, @Draggu, and @wawel37)

___
*[`crates/cairo-lang-doc/src/db.rs` line 173 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O62-NCZ3OhVVz2a1JbG:-O62-NCZ3OhVVz2a1JbH:bjef4jh) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/db.rs#L173)):*
> ```XML
> 
> /// Only gets the doc comments above the item.
> fn extract_prefixed_comments_from_raw_text(
> ```

This is the naming convention in Rust I believe



_Suggestion:_
```XML
fn extract_outer_comments_from_raw_text(
```


<!-- Sent from Reviewable.io -->

2024-09-05 16:43 UTC, piotmag769 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 16 unresolved discussions (waiting on @Arcticae, @Draggu, and @wawel37)

___
*[`crates/cairo-lang-doc/src/db.rs` line 41 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O6210btE0bGRhHseWx-:-O6210bu0OTFal_lAgpS:b-suz5r8) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/db.rs#L41)):*
> ```XML
>             let prefix_comments = extract_prefixed_comments_from_raw_text(db, item_id);
>             let inner_comments = get_item_inner_documentation(db, item_id);
>             let module_level_comments = extract_module_level_comments(db.upcast(), item_id);
> ```

It is just an inner comment for a module, right? Couldn't we have a function that extracts submodule_id if possible/checks if the item is a module and do

```rs
let inner_comments = if is_module(item_id) {
    get_item_inner_documentation(db, item_id)
} else {
    extract_module_level_comments(db.upcast(), item_id)
};
```
___
*[`crates/cairo-lang-doc/src/db.rs` line 74 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O623FBm9lyRJ11F3lnc:-O623FBm9lyRJ11F3lnd:bszfjd7) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/db.rs#L74)):*
> ```XML
>             .syntax_node(db.upcast())
>             .get_shallow_inner_comments_text(db.upcast());
>         extract_inner_comments_from_raw_text(raw_text, &["//!"])
> ```

Shouldn't `"//!"` be encoded in the function logic if it is just for inner comments?
___
*[`crates/cairo-lang-doc/src/db.rs` line 184 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O62-gSq3r2-YQv_EGmE:-O62-gSq3r2-YQv_EGmF:b-nh3rzq) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/db.rs#L184)):*
> ```XML
>         .filter(|line| !line.trim().is_empty())
>         .take_while_ref(|line| is_comment_line(line))
>         .filter_map(|line| extract_comment_from_code_line(line, &["///", "//!"]))
> ```

Why do we have `"//!"` here if we want to only extract outer comments? :thinking:


<!-- Sent from Reviewable.io -->

2024-09-05 21:50 UTC, piotmag769 requested changes
> Reviewed 1 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 17 unresolved discussions (waiting on @Arcticae, @Draggu, and @wawel37)

___
*[`crates/cairo-lang-doc/src/db.rs` line 41 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O6210btE0bGRhHseWx-:-O637zAxEueF1NrRwVJQ:bcjyowu) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/db.rs#L41)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

It is just an inner comment for a module, right? Couldn't we have a function that extracts submodule_id if possible/checks if the item is a module and do

```rs
let inner_comments = if is_module(item_id) {
    get_item_inner_documentation(db, item_id)
} else {
    extract_module_level_comments(db.upcast(), item_id)
};
```
</blockquote></details>

Alternatively (probably better, typesfe, function name up to debate)

```rs
let inner_comments = if let Some(submodule_id) = maybe_extract_submodule_id(item_id) { 
    extract_module_level_comments(db.upcast(), submodule_id) 
} else { 
    get_item_inner_documentation(db, item_id) 
};
```
___
*[`crates/cairo-lang-doc/src/db.rs` line 81 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O636uAx5f7axZoADfMM:-O636uAx5f7axZoADfMN:b-f0jsxs) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/db.rs#L81)):*
> ```XML
> 
> fn get_item_signature(db: &dyn DocGroup, item_id: DocumentableItemId) -> String {
>     if let DocumentableItemId::Crate(crate_id) = item_id {
> ```

I know that @mkaput said otherwise, but I don't think an item being documentable means it also has a signature. I don't see a reason where the API user would actually want a crate signature. What about creating a separate struct e.g. `SignaturableItemId` (name up to debate)?


<!-- Sent from Reviewable.io -->

2024-09-06 07:41 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 17 unresolved discussions (waiting on @Arcticae, @Draggu, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-doc/src/db.rs` line 81 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O636uAx5f7axZoADfMM:-O65Ggum62cqQnY_5OsD:bdqpc7h) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/db.rs#L81)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

I know that @mkaput said otherwise, but I don't think an item being documentable means it also has a signature. I don't see a reason where the API user would actually want a crate signature. What about creating a separate struct e.g. `SignaturableItemId` (name up to debate)?
</blockquote></details>

trick is I actually want signatures for crates :upside_down_face: 

from LS perspective, if I hover here:

```rust
use snforge_<caret>std::foobar;
```

I'd welcome the following hover:

```markdown
crate snforge_std
---
Docs for snforge_std
```


<!-- Sent from Reviewable.io -->

2024-09-06 10:41 UTC, wawel37 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: 12 of 20 files reviewed, 17 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-doc/src/db.rs` line 282 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O5x5Vn641HTU8XNnCZj:-O65idXuCoyRdJqiHSXE:bnuf9xg) ([raw file](https://github.com/starkware-libs/cairo/blob/da7215cc1821e116af3af2bfb20ca48775a67cdd/crates/cairo-lang-doc/src/db.rs#L282)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Not done. (`comment_markers`)
</blockquote></details>

Done. Sorry, haven't noticed it
___
*[`crates/cairo-lang-doc/src/db.rs` line 39 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O61uxJsBnpdo-EuBb3l:-O65aE8q4OFWgtFnV0oW:b-h133qf) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/db.rs#L39)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Naming is inconsistent - I would name the functions starting with `extract` everywhere
</blockquote></details>

Done. The `get_item_documentation` and `get_item_signature` are left as they are. The extract functions are private ones.
___
*[`crates/cairo-lang-doc/src/db.rs` line 41 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O6210btE0bGRhHseWx-:-O65dNUwB4AwVnrUdZ5L:b-eom8bz) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/db.rs#L41)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Alternatively (probably better, typesfe, function name up to debate)

```rs
let inner_comments = if let Some(submodule_id) = maybe_extract_submodule_id(item_id) { 
    extract_module_level_comments(db.upcast(), submodule_id) 
} else { 
    get_item_inner_documentation(db, item_id) 
};
```
</blockquote></details>

Checking whether the item is a module is insufficient. Module can have either an inner_comment of module_level_comment, based on whether it's an inline module. I know we can check if the item is a module + if module is inline, but wouldn't that make the logic here more complicated? Whether the module is inline or not, we will get a correct docs, because certain functions will just return None.
___
*[`crates/cairo-lang-doc/src/db.rs` line 74 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O623FBm9lyRJ11F3lnc:-O65eSUSB3TygKGJSsbt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/db.rs#L74)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Shouldn't `"//!"` be encoded in the function logic if it is just for inner comments?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-doc/src/db.rs` line 173 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O62-NCZ3OhVVz2a1JbG:-O65f-YI1XftytIJ8No4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/db.rs#L173)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

This is the naming convention in Rust I believe
</blockquote></details>

Done.
___
*[`crates/cairo-lang-doc/src/db.rs` line 184 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O62-gSq3r2-YQv_EGmE:-O65f9Y60YljjLhuuN9g:b4jbvmi) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/db.rs#L184)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Why do we have `"//!"` here if we want to only extract outer comments? :thinking:
</blockquote></details>

Done. At the beginning there was "///" and "//!" parsed for outer comments. I just thought that we want to have it different than Rust.
___
*[`crates/cairo-lang-doc/src/db.rs` line 198 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O616Jt08s3Xaw3G-uws:-O65hzAbAct2TCPM-t9W:b-861sjz) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/db.rs#L198)):*
> ```XML
>         .lines()
>         .filter(|line| !line.trim().is_empty())
>         .skip_while(|line| is_comment_line(line) || line.is_empty())
> ```

Done. Sorry, leftover. Haven't noticed it
___
*[`crates/cairo-lang-doc/src/db.rs` line 212 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O615spv62ih3f_Wg-et:-O65i1dgB2yY6CMT0Vso:b-qvea4m) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/db.rs#L212)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

First we filter non empty lines, this cannot happen.
</blockquote></details>

Done. yup, same as above
___
*[`crates/cairo-lang-doc/src/db.rs` line 230 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O6150HwDdGmc2ya0OEY:-O65iSVb0e5Z8d9SA7Xj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/db.rs#L230)):*
> ```XML
> 
>     // Nullify empty or just-whitespace documentation strings as they are not useful.
>     (doc.trim().is_empty().not()).then_some(doc)
> ```

Done.
___
*[`crates/cairo-lang-doc/src/tests/test.rs` line 206 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O613IIB5Hqqixf_XI65:-O65kkGx62-GNBXuqDbR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/tests/test.rs#L206)):*
> ```XML
>     output.insert(
>         "Item #".to_string() + &item_number.to_string(),
>         documentation.map_or(String::from(""), |doc| doc),
> ```

Done.
___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 178 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O61yA_UB1XWILlOCS1-:-O65ns-L6wr6Qwk6WLXk:b-9v02c3) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-syntax/src/node/mod.rs#L178)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

You could just return `String` from the func before and delete this one. I would merge comments from both funcs and name it a bit better - I don't think this name says really well what this func does
</blockquote></details>

This function is a wrapper. The function below is a recursive one, it need some wrapper that will create a new string that it will write results to. We don't want to make this function to take a default string
___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 301 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O61xwV1BLmh_EJSCmcb:-O65r7fH3l4ZdnE_on_M:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-syntax/src/node/mod.rs#L301)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Isn't it better to just return a String here? You wouldn't need the func above
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 30 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O614LBPEvsteIsQrC9h:-O65kpLv9f_GOlwuEMuO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L30)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

@wawel37 this `ln` is good but not in this PR
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-06 10:53 UTC, Draggu requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: 11 of 20 files reviewed, 18 unresolved discussions (waiting on @Arcticae, @mkaput, @orizi, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 177 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O65wrum0NtPo9YoTG0K:-O65wrunASIV7rhXVNBj:b-v1fyc8) ([raw file](https://github.com/starkware-libs/cairo/blob/03d9d8bd613cdfe0280632df8eed0a00c2e82ec2/crates/cairo-lang-syntax/src/node/mod.rs#L177)):*
> ```XML
>     /// Returns all the text under the syntax node.
>     /// It traverses all the syntax tree of the node, but ignores functions and modules.
>     pub fn get_syntax_tree_text_without_functions_and_modules(
> ```

Please add comment describing this, current one is not explaining why we skip functions and modules.



_Suggestion:_
```XML
get_text_without_inner_commentable_children
```


<!-- Sent from Reviewable.io -->

2024-09-06 11:29 UTC, piotmag769 reviewed
> Reviewed 4 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: 15 of 20 files reviewed, 11 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @wawel37)



<!-- Sent from Reviewable.io -->

2024-09-06 11:31 UTC, Draggu reviewed
> Reviewed 2 of 17 files at r1, 3 of 8 files at r2, 5 of 15 files at r3, 1 of 2 files at r4, 9 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae, @mkaput, @piotmag769, and @wawel37)



<!-- Sent from Reviewable.io -->

2024-09-06 11:46 UTC, piotmag769 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae, @mkaput, and @wawel37)

___
*[`crates/cairo-lang-doc/src/db.rs` line 41 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O6210btE0bGRhHseWx-:-O665UQE3ZeguyXRaMDb:b3i0ret) ([raw file](https://github.com/starkware-libs/cairo/blob/a95aab31652ece25e8545f2523ce65f80ef8fa1d/crates/cairo-lang-doc/src/db.rs#L41)):*
<details><summary><i>Previously, wawel37 (Mateusz Kowalski) wrote…</i></summary><blockquote>

Checking whether the item is a module is insufficient. Module can have either an inner_comment of module_level_comment, based on whether it's an inline module. I know we can check if the item is a module + if module is inline, but wouldn't that make the logic here more complicated? Whether the module is inline or not, we will get a correct docs, because certain functions will just return None.
</blockquote></details>

Good catch, didn't see that. I feel like doing the check here is better, it makes the logic more clear instead of making guesses about what is actually what. Also a comment explaining that would be nice
___
*[`crates/cairo-lang-doc/src/db.rs` line 214 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O666Wtz6sjsMz4E5HiG:-O666Wtz6sjsMz4E5HiH:br8tz5r) ([raw file](https://github.com/starkware-libs/cairo/blob/03d9d8bd613cdfe0280632df8eed0a00c2e82ec2/crates/cairo-lang-doc/src/db.rs#L214)):*
> ```XML
>         .take_while_ref(|line| is_comment_line(line))
>         .filter_map(|line| {
>             if line.is_empty() {
> ```

This cannot happen, we filter empty lines before


<!-- Sent from Reviewable.io -->

2024-09-06 15:13 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 9 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317#-:-O66tO9i0FA06R-HQj8w:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae and @wawel37)



<!-- Sent from Reviewable.io -->

2024-09-09 08:01 UTC, wawel37 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317)* status: 18 of 20 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-doc/src/db.rs` line 214 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O666Wtz6sjsMz4E5HiG:-O6KlctY7HC4kTa8aDtW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/03d9d8bd613cdfe0280632df8eed0a00c2e82ec2/crates/cairo-lang-doc/src/db.rs#L214)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

This cannot happen, we filter empty lines before
</blockquote></details>

Done.
___
*[`crates/cairo-lang-syntax/src/node/mod.rs` line 177 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6317#-O65wrum0NtPo9YoTG0K:-O6KlkNx2X7VHZZlVH2I:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/03d9d8bd613cdfe0280632df8eed0a00c2e82ec2/crates/cairo-lang-syntax/src/node/mod.rs#L177)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Please add comment describing this, current one is not explaining why we skip functions and modules.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-09 08:58 UTC, Draggu approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317#-:-O6L-CRg0BJFYHGw-KD8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-09-09 11:37 UTC, piotmag769 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 9 files at r8, 5 of 6 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6317#-:-O6LYzUN4sg29hrKpXI9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)



<!-- Sent from Reviewable.io -->

2024-09-09 12:47 UTC, merged