Insert right paren after cursor when completing funciton/method calls
starkware-libs/cairo pull request #6320
Opened 2024-08-31 07:49 UTC by RuneRogue

I have first check whethere function have parameters or not . If it have parameter then it will place curser after the '()' . If function have parameters then the it will place curser between the parenthesis like this '(l)' . Also i have added space between paranthesis so curser appears properly .

Fixed #5935

2024-09-01 06:27 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @RuneRogue)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 308 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5gDXR_7CkrgEfW65Wk:-O5gDXR_7CkrgEfW65Wl:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7da521a1b7a1d383a92e9de83b9501288a4bc19d/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L308)):*
> ```XML
>             new_text: " ".to_string(), // Add a space to place cursor
>         });
>     }
> ```





_Suggestion:_
```XML

    let call_signature = format!("{name}()");
    let completion = CompletionItem {
        // TODO: Display the full method signature. (I think? otherwise i didn't understand the comment).
        label: call_signature.clone(),
        insert_text: Some(call_signature),
        detail: Some(detail),
        kind: Some(CompletionItemKind::METHOD),
        additional_text_edits: Some(additional_text_edits),
        ..CompletionItem::default()
    };

    if !signature.params.is_empty() {
        let insert_position = Position {
            line: position.line,
            // Position cursor inside the parentheses.
            character: position.character + name.len() + 1,
        }
        completion.additional_text_edits.push(TextEdit {
            range: Range::new(insert_position, insert_position),
            // Add a space to place cursor.
            new_text: " ".to_string(),
        });
    }
```


<!-- Sent from Reviewable.io -->

2024-09-01 06:45 UTC, RuneRogue commented
@orizi I have made changes as you have suggested.

2024-09-01 06:49 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @RuneRogue)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 285 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5gL4yd5f1O8L6fBCpo:-O5gL4ye1Qd-GQyJ8ht_:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/402ab6315051563a480cc95cffe0ee218fddda6f/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L285)):*
> ```XML
>     
>     let call_signature = format!("{name}()");
>     let completion = CompletionItem {
> ```





_Suggestion:_
```XML
    let call_signature = format!("{name}()");
    let completion = CompletionItem {
```


<!-- Sent from Reviewable.io -->

2024-09-01 06:56 UTC, RuneRogue commented
@orizi  sorry I am not getting what you are suggesting. It's exactly like what you have suggested.

2024-09-01 07:01 UTC, orizi reviewed
please look at comments at https://reviewable.io/reviews/starkware-libs/cairo/6320#-.
and not directly on github.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320#-:-O5gNiarDCDNTb18uK06:buwjvlm)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @RuneRogue)



<!-- Sent from Reviewable.io -->

2024-09-01 07:02 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @RuneRogue)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5gO05q41agFCgxLy93:-O5gO05q41agFCgxLy94:b-lkpfuo) (no related file):*
add tests at crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt

___


<!-- Sent from Reviewable.io -->

2024-09-01 07:38 UTC, orizi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @RuneRogue)



<!-- Sent from Reviewable.io -->

2024-09-01 08:01 UTC, RuneRogue commented
@orizi I have added test for completion of method . Also I have added full signature method.

2024-09-01 08:13 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @RuneRogue)

___
*[`crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt` line 30 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5gdJr3CDCyQhgcuGzk:-O5gdJr3CDCyQhgcuGzl:b-c4c2uo) ([raw file](https://github.com/starkware-libs/cairo/blob/fd4284f6e456a6f12c69a3ab85be6a026cf4ce99/crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt#L30)):*
> ```help
>         x.some_method<caret>
>     }
> }
> ```

probably requires now showing additional info in the test for a completion entry.
@mkaput 


<!-- Sent from Reviewable.io -->

2024-09-01 08:20 UTC, RuneRogue commented
@orizi is that good?

2024-09-01 08:27 UTC, orizi requested changes
awaiting on @mkaput 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320#-:-O5ggZv04UH4tcb42MI3:b4c7eo6)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @RuneRogue)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 294 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5ggI5Q7mDGhtEUx1IL:-O5ggI5Q7mDGhtEUx1IM:b-o2g2hh) ([raw file](https://github.com/starkware-libs/cairo/blob/896dbd5e86bd1677b60d1f68899beba90528c176/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L294)):*
> ```XML
>         // Display the full method signature.
>         label: call_signature.clone(),
>         insert_text: Some(call_signature),
> ```

do we actually want to add all of this?
unless it auto-deletes when a user writes it - it is going to be very annoying.



_Code quote:_
```XML
        insert_text: Some(call_signature),
```


<!-- Sent from Reviewable.io -->

2024-09-01 08:38 UTC, RuneRogue commented
@orizi then should I completely remove full method signature?

2024-09-01 08:56 UTC, orizi reviewed
again - look at review and comment only on [https://reviewable.io/reviews/starkware-libs/cairo/6320#-](https://reviewable.io/reviews/starkware-libs/cairo/6320#-).

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320#-:-O5gn4O3AB0EuBeczafF:b-nse4hy)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @RuneRogue)



<!-- Sent from Reviewable.io -->

2024-09-01 09:16 UTC, RuneRogue commented
@orizi reach me out if any changes you want to do.

2024-09-01 09:53 UTC, orizi reviewed
please stop replying on github. reply to all threads on reviewable at https://reviewable.io/reviews/starkware-libs/cairo/6320#-

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320#-:-O5gzyN6CDlWAu6AhNed:buamc5s)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @RuneRogue)



<!-- Sent from Reviewable.io -->

2024-09-02 08:46 UTC, mkaput requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, @piotmag769, and @RuneRogue)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5luVCYCdk8dDU4D4l-:-O5luVCZ-_7bBVHciFGX:b53vsrd) (no related file):*
please fix build errors

___
___
*[`crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt` line 91 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5lnbcz5G8VRD2Vf-6n:-O5lnbcz5G8VRD2Vf-6o:b1aksqa) ([raw file](https://github.com/starkware-libs/cairo/blob/094ea4c3a2a016cf2a3d87746d85f85d86919541/crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt#L91)):*
> ```help
>     Signature: `fn no_param_method(self: @felt252)`
>     Documentation: `Executes a method that doesn't require parameters.`
> --------------------------
> ```

please ensure there's trailing newline in this file


<!-- Sent from Reviewable.io -->

2024-09-02 09:37 UTC, RuneRogue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt` line 91 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5lnbcz5G8VRD2Vf-6n:-O5m4y9D9s-AZm2SDoFI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/094ea4c3a2a016cf2a3d87746d85f85d86919541/crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt#L91)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

please ensure there's trailing newline in this file
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-02 09:37 UTC, RuneRogue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5luVCYCdk8dDU4D4l-:-O5m5FrvC7x00R2tGiz8:b-896fix) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

please fix build errors
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2024-09-02 09:43 UTC, orizi reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-09-02 10:51 UTC, RuneRogue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5luVCYCdk8dDU4D4l-:-O5mLzOa9SR3hZOs9cfX:b-896fix) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

not done, check out CI reports
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2024-09-02 10:54 UTC, orizi approved these changes
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-09-02 11:22 UTC, RuneRogue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5luVCYCdk8dDU4D4l-:-O5mTAfzCaKEELZSUBPi:b-bu91xm) (no related file):*
<details><summary><i>Previously, RuneRogue (Priyank Makwana) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Updated

___


<!-- Sent from Reviewable.io -->

2024-09-02 12:05 UTC, orizi approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-09-02 12:17 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5luVCYCdk8dDU4D4l-:-O5mefNb64khAgHubQ5E:b-4alzax) (no related file):*
<details><summary><i>Previously, RuneRogue (Priyank Makwana) wrote…</i></summary><blockquote>

updated
</blockquote></details>

still broken.
please make sure to run full test fixer before your next push.

___


<!-- Sent from Reviewable.io -->

2024-09-02 14:16 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @piotmag769, and @RuneRogue)



<!-- Sent from Reviewable.io -->

2024-09-02 19:14 UTC, RuneRogue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5luVCYCdk8dDU4D4l-:-O5o96WP7dPa-_0uOLhT:b-896fix) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

still broken.
please make sure to run full test fixer before your next push.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2024-09-03 06:05 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320#-:-O5qU9u90V9WMlzZwE7c:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-09-03 07:21 UTC, RuneRogue reviewed
Fixed Test issue.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320#-:-O5qkda-Dtkz_BdiJBRS:b-myjym)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-09-03 09:05 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @RuneRogue)

___
*[`crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt` line 43 at r12](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5r7DUm95cX5p7DrakW:-O5r7DUn3qtVYKWkgIFs:b-jlaq9p) ([raw file](https://github.com/starkware-libs/cairo/blob/34d04242a89100c7d65253c4a94b9b7a2cfbb74d/crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt#L43)):*
> ```help
> Completion: add_eq()
> Text edit: use core::traits::AddEq;
> Text edit:  --------------------------
> ```

what are all the new `Text edit:  ` all around?



_Code quote:_
```help
Text edit:  --------------------------
```


<!-- Sent from Reviewable.io -->

2024-09-03 09:30 UTC, RuneRogue reviewed
> Reviewed 1 of 1 files at r10, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt` line 43 at r12](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5r7DUm95cX5p7DrakW:-O5rCv7LAupEAoot4FQi:bmfkffp) ([raw file](https://github.com/starkware-libs/cairo/blob/34d04242a89100c7d65253c4a94b9b7a2cfbb74d/crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt#L43)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what are all the new `Text edit:  ` all around?
</blockquote></details>

It's added by CAIRO\_FIX\_TESTS=1 cargo test. 


<!-- Sent from Reviewable.io -->

2024-09-03 11:08 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @RuneRogue)

___
*[`crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt` line 43 at r12](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5r7DUm95cX5p7DrakW:-O5rZSJfD19MynxvFysG:b-mjbub) ([raw file](https://github.com/starkware-libs/cairo/blob/34d04242a89100c7d65253c4a94b9b7a2cfbb74d/crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt#L43)):*
<details><summary><i>Previously, RuneRogue (Priyank Makwana) wrote…</i></summary><blockquote>

It's added by CAIRO\_FIX\_TESTS=1 cargo test.
</blockquote></details>

i know - i don't understand why the difference from base in this case.
@mkaput 


<!-- Sent from Reviewable.io -->

2024-09-03 11:11 UTC, RuneRogue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt` line 43 at r12](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5r7DUm95cX5p7DrakW:-O5r_5G50HNLhM7kSh33:b-a4wuqr) ([raw file](https://github.com/starkware-libs/cairo/blob/34d04242a89100c7d65253c4a94b9b7a2cfbb74d/crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt#L43)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i know - i don't understand why the difference from base in this case.
@mkaput
</blockquote></details>

I have fixed it by some changes in e2e completion.rs


<!-- Sent from Reviewable.io -->

2024-09-03 11:38 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @RuneRogue)

___
*[`crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt` line 43 at r12](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5r7DUm95cX5p7DrakW:-O5rfPn61iICmZ7s5g39:b-5xg72t) ([raw file](https://github.com/starkware-libs/cairo/blob/34d04242a89100c7d65253c4a94b9b7a2cfbb74d/crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt#L43)):*
<details><summary><i>Previously, RuneRogue (Priyank Makwana) wrote…</i></summary><blockquote>

I have fixed it by some changes in e2e completion.rs
</blockquote></details>

leaving this for @mkaput in any case.


<!-- Sent from Reviewable.io -->

2024-09-03 15:15 UTC, mkaput requested changes
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, @piotmag769, and @RuneRogue)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 283 at r13](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5sRsqP1pFlulklgoLd:-O5sRsqP1pFlulklgoLe:b-5rux8r) ([raw file](https://github.com/starkware-libs/cairo/blob/e6e35959d3719c8785a6037b36309fc8d2ab3b6c/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L283)):*
> ```XML
> 
>     // Determine the insert text based on whether the function has parameters.
>     let call_signature = format!("{name}()");
> ```

I don't see how this resolves the linked issue. I will test this PR manually.
___
*[`crates/cairo-lang-language-server/tests/e2e/completions.rs` line 67 at r13](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5sQfce1JsvMzwzhmQx:-O5sQfce1JsvMzwzhmQy:byt4p26) ([raw file](https://github.com/starkware-libs/cairo/blob/e6e35959d3719c8785a6037b36309fc8d2ab3b6c/crates/cairo-lang-language-server/tests/e2e/completions.rs#L67)):*
> ```XML
>                     report.push_str(format!("Completion: {}\n", completion.label).as_str());
>                     for edit in text_edit {
>                         report.push_str(edit.new_text.as_str());
> ```

Can you please revert this change? I know it's not the highest beauty, but it generated quite a lot of nose in PR diff, that is out of scope and will pollute commit history.

If you wish, you work on separate PR that will make these tests beautiful. I have some ideas worth considering. :smiley: 
___
*[`crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt` line 30 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5gdJr3CDCyQhgcuGzk:-O5sRgIP7K2dic1pgGGX:b-96es17) ([raw file](https://github.com/starkware-libs/cairo/blob/fd4284f6e456a6f12c69a3ab85be6a026cf4ce99/crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt#L30)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

probably requires now showing additional info in the test for a completion entry.
@mkaput
</blockquote></details>

agree, please dump the entire completion item here, perhaps just printing debug repr could be enough?
___
*[`crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt` line 43 at r12](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5r7DUm95cX5p7DrakW:-O5sR-V7738F9-j9tNjt:b-6srede) ([raw file](https://github.com/starkware-libs/cairo/blob/34d04242a89100c7d65253c4a94b9b7a2cfbb74d/crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt#L43)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

leaving this for @mkaput in any case.
</blockquote></details>

I have started a new discussion at the code that triggers these diffs. I think we can conclude this discussion.
___
*[`crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt` line 1 at r13](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5sRHyL6uJvP7n6eWaC:-O5sRHyL6uJvP7n6eWaD:bqvg4ut) ([raw file](https://github.com/starkware-libs/cairo/blob/e6e35959d3719c8785a6037b36309fc8d2ab3b6c/crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt#L1)):*
> ```help
> //! > Test completion for methods with parameters showing additional info.
> ```

could you please leave these tests as they were and instead create new ones specifically for the changes you do, please? this way we will separately test for auto imports and for stuff you're adding :)

I think you're use cases also need much simpler examples than the one present here


<!-- Sent from Reviewable.io -->

2024-09-03 19:45 UTC, RuneRogue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/e2e/completions.rs` line 67 at r13](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5sQfce1JsvMzwzhmQx:-O5tOa2VDDcRdihoD2GF:b-yrudr5) ([raw file](https://github.com/starkware-libs/cairo/blob/e6e35959d3719c8785a6037b36309fc8d2ab3b6c/crates/cairo-lang-language-server/tests/e2e/completions.rs#L67)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Can you please revert this change? I know it's not the highest beauty, but it generated quite a lot of nose in PR diff, that is out of scope and will pollute commit history.

If you wish, you work on separate PR that will make these tests beautiful. I have some ideas worth considering. :smiley:
</blockquote></details>

I am considering to make new PR . I have figured out something to solve the test data problem. I am gonna push all the updates over new PR.


<!-- Sent from Reviewable.io -->

2024-09-04 15:38 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @piotmag769, and @RuneRogue)

___
*[`crates/cairo-lang-language-server/tests/e2e/completions.rs` line 67 at r13](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5sQfce1JsvMzwzhmQx:-O5xfxR39JfuMN7k54zX:bg7z3oe) ([raw file](https://github.com/starkware-libs/cairo/blob/e6e35959d3719c8785a6037b36309fc8d2ab3b6c/crates/cairo-lang-language-server/tests/e2e/completions.rs#L67)):*
<details><summary><i>Previously, RuneRogue (Priyank Makwana) wrote…</i></summary><blockquote>

I am considering to make new PR . I have figured out something to solve the test data problem. I am gonna push all the updates over new PR.
</blockquote></details>

Please do these changes here, this will make reviewing process much more effective :pray: 


<!-- Sent from Reviewable.io -->

2024-09-04 17:02 UTC, RuneRogue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/e2e/completions.rs` line 67 at r13](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5sQfce1JsvMzwzhmQx:-O5xz6Wp6shmYhFnTVNP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/874e72221db0581ae81f6a0021689c6a9f83defe/crates/cairo-lang-language-server/tests/e2e/completions.rs#L67)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Please do these changes here, this will make reviewing process much more effective :pray:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-06 05:20 UTC, RuneRogue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/e2e/completions.rs` line 67 at r13](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5sQfce1JsvMzwzhmQx:-O64l2r-DMQFejS1X7nT:br4zp97) ([raw file](https://github.com/starkware-libs/cairo/blob/874e72221db0581ae81f6a0021689c6a9f83defe/crates/cairo-lang-language-server/tests/e2e/completions.rs#L67)):*
<details><summary><i>Previously, RuneRogue (Priyank Makwana) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@mkaput  is this perfect?


<!-- Sent from Reviewable.io -->

2024-09-06 15:29 UTC, RuneRogue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/e2e/completions.rs` line 67 at r13](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5sQfce1JsvMzwzhmQx:-O66wsBk1m6iHbgKVr0V:bmpw14h) ([raw file](https://github.com/starkware-libs/cairo/blob/874e72221db0581ae81f6a0021689c6a9f83defe/crates/cairo-lang-language-server/tests/e2e/completions.rs#L67)):*
<details><summary><i>Previously, RuneRogue (Priyank Makwana) wrote…</i></summary><blockquote>

@mkaput  is this perfect?
</blockquote></details>

@mkaput please review the code and tell me if there are any changes. 


<!-- Sent from Reviewable.io -->

2024-09-06 16:48 UTC, mkaput requested changes
> Reviewed 1 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, @piotmag769, and @RuneRogue)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O67E-uK0iFG6FN-FX0J:-O67E-uK0iFG6FN-FX0K:by5okqn) (no related file):*
@RuneRogue FYI I'm going to be offline until the end of the month. My team will continue reviewing this.

___
___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 283 at r13](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5sRsqP1pFlulklgoLd:-O67DWBF6hZCpAVEYw4I:b-3ihrg2) ([raw file](https://github.com/starkware-libs/cairo/blob/874e72221db0581ae81f6a0021689c6a9f83defe/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L283)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I don't see how this resolves the linked issue. I will test this PR manually.
</blockquote></details>

have you tested this code manually? this doesn't seem to work:

[Nagranie z ekranu 2024-09-6 o 18.46.42.mov](https://files.reviewableusercontent.io/images/reviewable/3450050/qE8En8dRp7rnZbclNnLowJjq/Nagranie%20z%20ekranu%202024-09-6%20o%2018.46.42.mov)
___
*[`crates/cairo-lang-language-server/tests/e2e/completions.rs` line 67 at r13](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5sQfce1JsvMzwzhmQx:-O67DJnS7IvwTmy0gYM0:b-ulnlh2) ([raw file](https://github.com/starkware-libs/cairo/blob/874e72221db0581ae81f6a0021689c6a9f83defe/crates/cairo-lang-language-server/tests/e2e/completions.rs#L67)):*
<details><summary><i>Previously, RuneRogue (Priyank Makwana) wrote…</i></summary><blockquote>

Formating issue solved
</blockquote></details>

please address this discussion: https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5gdJr3CDCyQhgcuGzk and all the other that are open


<!-- Sent from Reviewable.io -->

2024-09-06 18:52 UTC, RuneRogue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 283 at r13](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5sRsqP1pFlulklgoLd:-O67egbCADMdpqYKiiyC:b-twcqxf) ([raw file](https://github.com/starkware-libs/cairo/blob/874e72221db0581ae81f6a0021689c6a9f83defe/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L283)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

have you tested this code manually? this doesn't seem to work:

[Nagranie z ekranu 2024-09-6 o 18.46.42.mov](https://files.reviewableusercontent.io/images/reviewable/3450050/qE8En8dRp7rnZbclNnLowJjq/Nagranie%20z%20ekranu%202024-09-6%20o%2018.46.42.mov)
</blockquote></details>

@orizi @mkaput I didn't test it manually . But in test data it is giving the correct output . Even for same function you have used in video is giving the correct ouput . May I know how can I test it manually as same as video ? It'll be helpful for me for more testing .


<!-- Sent from Reviewable.io -->

2024-09-07 04:33 UTC, RuneRogue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 283 at r13](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5sRsqP1pFlulklgoLd:-O69ighSDPVvVMIDHLyL:b5yqqkq) ([raw file](https://github.com/starkware-libs/cairo/blob/874e72221db0581ae81f6a0021689c6a9f83defe/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L283)):*
<details><summary><i>Previously, RuneRogue (Priyank Makwana) wrote…</i></summary><blockquote>

@orizi @mkaput I didn't test it manually . But in test data it is giving the correct output . Even for same function you have used in video is giving the correct ouput . May I know how can I test it manually as same as video ? It'll be helpful for me for more testing .
</blockquote></details>

@orizi @mkaput . You were saying 'arg' is missing . If we add parameters between the parentheses then there is no need to place cursor between the parentheses . am I right ?

Also Can you help me find the method in cairo-lang-semantic /src / db.rs  that returns the documentation about the method ? I don't know where that method is located but I expect it to be in ' cairo-lang-semantic /src / db.rs' code.


<!-- Sent from Reviewable.io -->

2024-09-08 08:04 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @RuneRogue)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 294 at r16](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O6FeBz7DbOB9Ou68JXl:-O6FeBz7DbOB9Ou68JXm:b-w3xz80) ([raw file](https://github.com/starkware-libs/cairo/blob/32a259f89ddcd7018a2f96306e6f7dc9a7d5c47a/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L294)):*
> ```XML
>     };
> 
>     if !signature.params.is_empty() && signature.params.iter().any(|param| param.name != "self") {
> ```

what does this mean?

also - `self` is always the first param - otherwise it doesn't mean anything.



_Code quote:_
```XML
 && signature.params.iter().any(|param| param.name != "self")
```


<!-- Sent from Reviewable.io -->

2024-09-08 09:17 UTC, RuneRogue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 294 at r16](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O6FeBz7DbOB9Ou68JXl:-O6FuAD_BiGRt6M6Dy65:b-1djudd) ([raw file](https://github.com/starkware-libs/cairo/blob/32a259f89ddcd7018a2f96306e6f7dc9a7d5c47a/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L294)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what does this mean?

also - `self` is always the first param - otherwise it doesn't mean anything.
</blockquote></details>

It means whether function have parameters other than 'self' or not? I tried to implement what you have said but It's not giving correct output. 


This code gives the perfect output as we want .
first It checks whether function having parameter or not . If it does then it should be other that 'self'. 



_Code snippet:_
```XML
if !signature.params.is_empty() && signature.params.iter().any(|param| param.name != "self")
```


<!-- Sent from Reviewable.io -->

2024-09-08 09:28 UTC, RuneRogue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt` line 30 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O5gdJr3CDCyQhgcuGzk:-O6FxXLO4d7siRakhScO:bq1enui) ([raw file](https://github.com/starkware-libs/cairo/blob/fd4284f6e456a6f12c69a3ab85be6a026cf4ce99/crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt#L30)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

agree, please dump the entire completion item here, perhaps just printing debug repr could be enough?
</blockquote></details>

Done. I have dumped whole completion item in test data.


<!-- Sent from Reviewable.io -->

2024-09-08 10:00 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @RuneRogue)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 294 at r16](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O6FeBz7DbOB9Ou68JXl:-O6G3NQ9Dc_FmfxusGDh:b9yzqgs) ([raw file](https://github.com/starkware-libs/cairo/blob/32a259f89ddcd7018a2f96306e6f7dc9a7d5c47a/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L294)):*
<details><summary><i>Previously, RuneRogue (Priyank Makwana) wrote…</i></summary><blockquote>

It means whether function have parameters other than 'self' or not? I tried to implemented that you have said but It's not giving correct output. 


This code gives the perfect output as we want .
first It checks whether function having parameter or not . If it does then it should be other that 'self'.
</blockquote></details>

it was because it wasn't clear what you wanted to acheive.

note that you give this as a suggestion ONLY if you have a self param.

therefore what you wanted to check is just that the function has at least 2 parameters.

also - make sure to actually have a short comment explaining this.


<!-- Sent from Reviewable.io -->

2024-09-08 10:54 UTC, RuneRogue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 294 at r16](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O6FeBz7DbOB9Ou68JXl:-O6GFHGX55v2dTO4PbNR:b-c6r6iw) ([raw file](https://github.com/starkware-libs/cairo/blob/32a259f89ddcd7018a2f96306e6f7dc9a7d5c47a/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L294)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it was because it wasn't clear what you wanted to acheive.

note that you give this as a suggestion ONLY if you have a self param.

therefore what you wanted to check is just that the function has at least 2 parameters.

also - make sure to actually have a short comment explaining this.
</blockquote></details>

@orizi I am really sorry to say this but i am not getting what you are saying . can you pleaase quote the code where you want to change and then also give suggestion code quote that you want to add.


<!-- Sent from Reviewable.io -->

2024-09-08 11:00 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @RuneRogue)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 312 at r17](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O6GHaT88KCrN2xtvTfj:-O6GHaT88KCrN2xtvTfk:bvxb5b3) ([raw file](https://github.com/starkware-libs/cairo/blob/2d306d16f77bafe50bb0efb42b6d6ea3959c1bdd/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L312)):*
> ```XML
>     };
> 
>     if !signature.params.is_empty() && signature.params.iter().any(|param| param.name != "self") {
> ```

your entire code tries to ask this question.



_Suggestion:_
```XML
if !signature.params.len() >= 2 {
```


<!-- Sent from Reviewable.io -->

2024-09-08 11:01 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @RuneRogue)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 312 at r17](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O6GHoKk78IVKn_bitSs:-O6GHoKk78IVKn_bitSt:bvxb5b3) ([raw file](https://github.com/starkware-libs/cairo/blob/2d306d16f77bafe50bb0efb42b6d6ea3959c1bdd/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L312)):*
> ```XML
>     };
> 
>     if !signature.params.is_empty() && signature.params.iter().any(|param| param.name != "self") {
> ```

your entire code tries to ask this question.



_Suggestion:_
```XML
if signature.params.len() >= 2 {
```


<!-- Sent from Reviewable.io -->

2024-09-08 11:54 UTC, RuneRogue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 312 at r17](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O6GHoKk78IVKn_bitSs:-O6GTlHg6ymxnNZ3x7f7:bbgf5v3) ([raw file](https://github.com/starkware-libs/cairo/blob/2d306d16f77bafe50bb0efb42b6d6ea3959c1bdd/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L312)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

your entire code tries to ask this question.
</blockquote></details>

Done. I have also added detailed test data . Now it should work properly . Please review it tell me if there are any changes.


<!-- Sent from Reviewable.io -->

2024-09-08 13:58 UTC, RuneRogue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 312 at r17](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O6GHoKk78IVKn_bitSs:-O6Guj3I0hr6cSLBg1bD:b4ivmjc) ([raw file](https://github.com/starkware-libs/cairo/blob/2d306d16f77bafe50bb0efb42b6d6ea3959c1bdd/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L312)):*
<details><summary><i>Previously, RuneRogue (Priyank Makwana) wrote…</i></summary><blockquote>

Done. I have also added detailed test data . Now it should work properly . Please review it tell me if there are any changes.
</blockquote></details>

@orizi Can you conduct manually testing of this code? then let me know if this code is working or not?
or Tell me how to do manual testing.


<!-- Sent from Reviewable.io -->

2024-09-08 14:11 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @RuneRogue)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 312 at r17](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O6GHoKk78IVKn_bitSs:-O6Gy1Y8AsaU7VO41hHG:b-pj39m2) ([raw file](https://github.com/starkware-libs/cairo/blob/2d306d16f77bafe50bb0efb42b6d6ea3959c1bdd/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L312)):*
<details><summary><i>Previously, RuneRogue (Priyank Makwana) wrote…</i></summary><blockquote>

@orizi Can you conduct manually testing of this code? then let me know if this code is working or not?
or Tell me how to do manual testing.
</blockquote></details>

Please wait for @mkaput for that - as he is responsible for most of the LS side of things.

I mostly just watch externally to follow what is going on on the LS side.


<!-- Sent from Reviewable.io -->

2024-09-08 14:17 UTC, RuneRogue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 312 at r17](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O6GHoKk78IVKn_bitSs:-O6GywFu9odJvc6GuIb0:bd0bqut) ([raw file](https://github.com/starkware-libs/cairo/blob/2d306d16f77bafe50bb0efb42b6d6ea3959c1bdd/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L312)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Please wait for @mkaput for that - as he is responsible for most of the LS side of things.

I mostly just watch externally to follow what is going on on the LS side.
</blockquote></details>

@orizi I want one more help . @mkaput told me to add documentation . refer to this video. I have tried to find function that give me documentation about the function but I didn't get it . can you help me to find that method so i can add documentation .


[Nagranie z ekranu 2024-09-6 o 18.46.42.mov](https://files.reviewableusercontent.io/images/reviewable/117025290/uSS5oc4GsqEOxamtNQnZ9w0g/Nagranie%20z%20ekranu%202024-09-6%20o%2018.46.42.mov)


<!-- Sent from Reviewable.io -->

2024-09-08 14:25 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6320)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @piotmag769, and @RuneRogue)

___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 294 at r16](https://reviewable.io/reviews/starkware-libs/cairo/6320#-O6FeBz7DbOB9Ou68JXl:-O6H0MLlAhn_9pncgXNM:b-f8shng) ([raw file](https://github.com/starkware-libs/cairo/blob/32a259f89ddcd7018a2f96306e6f7dc9a7d5c47a/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L294)):*
<details><summary><i>Previously, RuneRogue (Priyank Makwana) wrote…</i></summary><blockquote>

@orizi I am really sorry to say this but i am not getting what you are saying . can you pleaase quote the code where you want to change and then also give suggestion code quote that you want to add.
</blockquote></details>

probably something like `get_item_documentation` - but you'll have to wait for @mkaput for him to explain what he wanted.


<!-- Sent from Reviewable.io -->

2024-09-19 14:22 UTC, Draggu commented
Done in #6380

2024-09-19 14:22 UTC, closed without merging