Change macro syntax to be token tree based and fix legacy macros.
starkware-libs/cairo pull request #6388
Opened 2024-09-18 06:47 UTC by gilbens-starkware

commit-id:09f12638

2024-09-18 06:53 UTC, orizi requested changes
> Reviewed 3 of 41 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: 3 of 41 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/test_data/macro_expand/simple_inline.txt` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O72tsqE0QQYtGKVhx2y:-O72tsqF1t88DP3UKjps:b-qqm3jf) ([raw file](https://github.com/starkware-libs/cairo/blob/09c0a97996ca259fef85b8b52847de551dd81a09/crates/cairo-lang-language-server/tests/test_data/macro_expand/simple_inline.txt#L72)):*
> ```help
>     core::result::ResultTrait::<
>         (), core::fmt::Error
>     >::unwrap(writeln!(__formatter_for_print_macros__, "some text"));
> ```

shouldn't it still expand?
___
*[`crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check` line 888 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O72txo69hE2eyv6T6We:-O72txo69hE2eyv6T6Wf:b-6o7vza) ([raw file](https://github.com/starkware-libs/cairo/blob/09c0a97996ca259fef85b8b52847de551dd81a09/crates/cairo-lang-lowering/src/borrow_check/test_data/borrow_check#L888)):*
> ```
> note: the variable needs to be dropped due to the potential panic here:
>   --> lib.cairo:3:14
> struct MyStruct {
> ```

mapping is broken.


<!-- Sent from Reviewable.io -->

2024-09-18 12:30 UTC, piotmag769 submitted a review, later dismissed
> Reviewed 4 of 41 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: 5 of 41 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/tests/e2e/support/mock_client.rs` line 269 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O746Abw4jWTZR-6gkKV:-O746Abw4jWTZR-6gkKW:bb76mu4) ([raw file](https://github.com/starkware-libs/cairo/blob/09c0a97996ca259fef85b8b52847de551dd81a09/crates/cairo-lang-language-server/tests/e2e/support/mock_client.rs#L269)):*
> ```XML
>     /// Receives a message from the server.
>     async fn recv(&mut self) -> Result<Option<Message>, RecvError> {
>         const TIMEOUT: Duration = Duration::from_secs(4 * 60);
> ```

Why?
___
*[`crates/cairo-lang-language-server/tests/test_data/macro_expand/attribute.txt` line 109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O746BayB4B3uvdDsSyq:-O746BayB4B3uvdDsSyr:bw1jay) ([raw file](https://github.com/starkware-libs/cairo/blob/09c0a97996ca259fef85b8b52847de551dd81a09/crates/cairo-lang-language-server/tests/test_data/macro_expand/attribute.txt#L109)):*
> ```help
>     core::result::ResultTrait::<
>         (), core::fmt::Error
>     >::unwrap(writeln!(__formatter_for_print_macros__, "a"));
> ```

It shouldn't have changed, this PR seems to break this features.
___
*[`crates/cairo-lang-language-server/tests/test_data/macro_expand/simple_inline.txt` line 72 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O72tsqE0QQYtGKVhx2y:-O746Hik9j9GSkLgMqeP:b-w4m4ot) ([raw file](https://github.com/starkware-libs/cairo/blob/09c0a97996ca259fef85b8b52847de551dd81a09/crates/cairo-lang-language-server/tests/test_data/macro_expand/simple_inline.txt#L72)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

shouldn't it still expand?
</blockquote></details>

It should


<!-- Sent from Reviewable.io -->

2024-10-14 23:35 UTC, piotmag769 reviewed
> Reviewed 7 of 41 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: 7 of 50 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @maciektr, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 283 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O9CNDozDHCBoKziWZhb:-O9CNDozDHCBoKziWZhc:b-ufi52m) ([raw file](https://github.com/starkware-libs/cairo/blob/0665387267a0b0bff25960ac75f6f5e28c155a8f/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L283)):*
> ```XML
>             content: config.content.into(),
>             code_mappings: Default::default(),
>             kind: match top_level_macro_kind {
> ```

@Draggu please verify this


<!-- Sent from Reviewable.io -->

2024-10-15 13:22 UTC, Draggu reviewed
> Reviewed 1 of 41 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: 7 of 50 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @gilbens-starkware, @maciektr, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/ide/macros/expand.rs` line 283 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O9CNDozDHCBoKziWZhb:-O9FL2JEDiIAfWbwHU6z:b-njc1i3) ([raw file](https://github.com/starkware-libs/cairo/blob/0665387267a0b0bff25960ac75f6f5e28c155a8f/crates/cairo-lang-language-server/src/ide/macros/expand.rs#L283)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

@Draggu please verify this
</blockquote></details>

This works


<!-- Sent from Reviewable.io -->

2024-10-15 16:55 UTC, orizi requested changes
> Reviewed 5 of 41 files at r1, 13 of 41 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: 22 of 50 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @gilbens-starkware, @maciektr, and @mkaput)

___
*[`crates/cairo-lang-defs/src/diagnostic_utils.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O9G5K242iXmyY06MF07:-O9G5K25CokyoYxxqUSm:b-wrye8j) ([raw file](https://github.com/starkware-libs/cairo/blob/fdbb03f50439d0d633d1ca5ec96a0101415a6381/crates/cairo-lang-defs/src/diagnostic_utils.rs#L16)):*
> ```XML
> pub struct StableLocation {
>     stable_ptr: SyntaxStablePtrId,
>     inner_span: Option<(TextWidth, TextWidth)>,
> ```

doc - and especially explain the inner_span.



_Code quote:_
```XML
    stable_ptr: SyntaxStablePtrId,
    inner_span: Option<(TextWidth, TextWidth)>,
```
___
*[`crates/cairo-lang-parser/src/macro_helpers.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O9G5X_v2458vZFeWtGV:-O9G5X_v2458vZFeWtGW:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/fdbb03f50439d0d633d1ca5ec96a0101415a6381/crates/cairo-lang-parser/src/macro_helpers.rs#L17)):*
> ```XML
> use crate::recovery::is_of_kind;
> 
> pub fn token_tree_as_wrapped_arg_list(
> ```

doc
___
*[`crates/cairo-lang-parser/src/macro_helpers.rs` line 54 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O9G5YqlAo97VRmH3Q8j:-O9G5YqlAo97VRmH3Q8k:b-lw24iu) ([raw file](https://github.com/starkware-libs/cairo/blob/fdbb03f50439d0d633d1ca5ec96a0101415a6381/crates/cairo-lang-parser/src/macro_helpers.rs#L54)):*
> ```XML
> }
> 
> pub trait AsLegacyInlineMacro {
> ```

doc all.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O9G5fy_Afqgp-u1RhRC:-O9G5fy_Afqgp-u1RhRD:bqvnqt0) ([raw file](https://github.com/starkware-libs/cairo/blob/fdbb03f50439d0d633d1ca5ec96a0101415a6381/crates/cairo-lang-parser/src/parser.rs#L44)):*
> ```XML
>     /// An accumulating vector of pending skipped tokens diagnostics.
>     pub(crate) pending_skipped_token_diagnostics: Vec<PendingParserDiagnostic>,
> }
> ```

can't you add accessors for partial parsing instead of having `pub(crate)` all around?



_Code quote:_
```XML
pub struct Parser<'a> {
    pub(crate) db: &'a dyn SyntaxGroup,
    pub(crate) file_id: FileId,
    pub(crate) lexer: Lexer<'a>,
    /// The next terminal to handle.
    pub(crate) next_terminal: LexerTerminal,
    /// A vector of pending trivia to be added as leading trivia to the next valid terminal.
    pub(crate) pending_trivia: Vec<TriviumGreen>,
    /// The current offset, excluding the current terminal.
    pub(crate) offset: TextOffset,
    /// The width of the current terminal being handled (excluding the trivia length of this
    /// terminal).
    pub(crate) current_width: TextWidth,
    /// The length of the trailing trivia following the last read token.
    pub(crate) last_trivia_length: TextWidth,
    pub(crate) diagnostics: &'a mut DiagnosticsBuilder<ParserDiagnostic>,
    /// An accumulating vector of pending skipped tokens diagnostics.
    pub(crate) pending_skipped_token_diagnostics: Vec<PendingParserDiagnostic>,
}
```


<!-- Sent from Reviewable.io -->

2024-10-15 17:01 UTC, orizi requested changes
> Reviewed 2 of 41 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: 24 of 50 files reviewed, 8 unresolved discussions (waiting on @Arcticae, @gilbens-starkware, @maciektr, and @mkaput)

___
*[`crates/cairo-lang-runner/src/profiling_test_data/major_test_cases` line 149 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O9G5w29CiDCSwmxKyCb:-O9G5w29CiDCSwmxKyCc:b-7ygmzk) ([raw file](https://github.com/starkware-libs/cairo/blob/fdbb03f50439d0d633d1ca5ec96a0101415a6381/crates/cairo-lang-runner/src/profiling_test_data/major_test_cases#L149)):*
> ```
>         0x54767f773cc172172c3afc5265bd0a76089c24cdef409635d27ac1a1fa96ca8, // calldata 7.
>         0x65586264, // calldata 8.
>     ].span();
> ```

this seems unrelated.
___
*[`crates/cairo-lang-semantic/src/db.rs` line 1606 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O9G61yG6yUPl3TlIvX9:-O9G61yG6yUPl3TlIvXA:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/fdbb03f50439d0d633d1ca5ec96a0101415a6381/crates/cairo-lang-semantic/src/db.rs#L1606)):*
> ```XML
>                 ));
>             }
>         }
> ```





_Suggestion:_
```XML
        diagnostics.add(SemanticDiagnostic::new(
            match plugin_diag.inner_span {
                None => StableLocation::new(plugin_diag.stable_ptr),
                Some(inner_span) => StableLocation::with_inner_span(plugin_diag.stable_ptr, inner_span),
            },
            SemanticDiagnosticKind::PluginDiagnostic(plugin_diag),
        )
```
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 46 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O9G6VyICSBt2BHhIdbW:-O9G6VyICSBt2BHhIdbX:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/fdbb03f50439d0d633d1ca5ec96a0101415a6381/crates/cairo-lang-semantic/src/diagnostic.rs#L46)):*
> ```XML
>         kind: SemanticDiagnosticKind,
>     ) -> DiagnosticAdded;
>     fn report_with_inner_span(
> ```

doc
___
*[`crates/cairo-lang-semantic/src/expr/expansion_test_data/inline_macros` line 198 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O9G6stV4-GQELX4p1lH:-O9G6stV4-GQELX4p1lI:b98vlty) ([raw file](https://github.com/starkware-libs/cairo/blob/fdbb03f50439d0d633d1ca5ec96a0101415a6381/crates/cairo-lang-semantic/src/expr/expansion_test_data/inline_macros#L198)):*
> ```
> 
> //! > diagnostics
> error: Plugin diagnostic: Macro can not be parsed as legacy macro.
> ```

this seems like a degradation - probably requires more info in the diag.



_Code quote:_
```
lugin diagnostic: Macro can not be parsed as legacy macro.
```


<!-- Sent from Reviewable.io -->

2024-10-16 09:04 UTC, wawel37 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: 24 of 50 files reviewed, 9 unresolved discussions (waiting on @Arcticae, @gilbens-starkware, @maciektr, and @mkaput)

___
*[`crates/cairo-lang-parser/src/macro_helpers.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O9JZPdc2ki3uZnyPLeu:-O9JZPdc2ki3uZnyPLev:b-ncbhhd) ([raw file](https://github.com/starkware-libs/cairo/blob/fdbb03f50439d0d633d1ca5ec96a0101415a6381/crates/cairo-lang-parser/src/macro_helpers.rs#L26)):*
> ```XML
>     let mut lexer = Lexer::from_text(db, &node_text);
>     let next_terminal = lexer.next().unwrap();
>     // println!("Offset: {:?}", token_tree.stable_ptr().0.lookup(db).offset());
> ```

Leftover?


<!-- Sent from Reviewable.io -->

2024-10-31 09:23 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: 17 of 51 files reviewed, 8 unresolved discussions (waiting on @Arcticae, @Draggu, @maciektr, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-defs/src/diagnostic_utils.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O9G5K242iXmyY06MF07:-OANcKbP0lFq03Bm9N9V:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fdbb03f50439d0d633d1ca5ec96a0101415a6381/crates/cairo-lang-defs/src/diagnostic_utils.rs#L16)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc - and especially explain the inner_span.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/macro_helpers.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O9G5X_v2458vZFeWtGV:-OANch_GCQaMvVBBKQKM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fdbb03f50439d0d633d1ca5ec96a0101415a6381/crates/cairo-lang-parser/src/macro_helpers.rs#L17)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/macro_helpers.rs` line 54 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O9G5YqlAo97VRmH3Q8j:-OANdBQj4gF4j79DzSQy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fdbb03f50439d0d633d1ca5ec96a0101415a6381/crates/cairo-lang-parser/src/macro_helpers.rs#L54)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc all.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O9G5fy_Afqgp-u1RhRC:-OAWdO-j7A6bQH3xmZx0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fdbb03f50439d0d633d1ca5ec96a0101415a6381/crates/cairo-lang-parser/src/parser.rs#L44)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can't you add accessors for partial parsing instead of having `pub(crate)` all around?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/db.rs` line 1606 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O9G61yG6yUPl3TlIvX9:-OAWmNbH-rh5mnlUatHo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fdbb03f50439d0d633d1ca5ec96a0101415a6381/crates/cairo-lang-semantic/src/db.rs#L1606)):*
> ```XML
>                 ));
>             }
>         }
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 46 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O9G6VyICSBt2BHhIdbW:-OAWmp9OBbJKC_NxonPx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fdbb03f50439d0d633d1ca5ec96a0101415a6381/crates/cairo-lang-semantic/src/diagnostic.rs#L46)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/expansion_test_data/inline_macros` line 198 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O9G6stV4-GQELX4p1lH:-OAWosNS9w3thDvcmqPb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fdbb03f50439d0d633d1ca5ec96a0101415a6381/crates/cairo-lang-semantic/src/expr/expansion_test_data/inline_macros#L198)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this seems like a degradation - probably requires more info in the diag.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-runner/src/profiling_test_data/major_test_cases` line 149 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6388#-O9G5w29CiDCSwmxKyCb:-OAWmAKf4R38StvyxemU:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fdbb03f50439d0d633d1ca5ec96a0101415a6381/crates/cairo-lang-runner/src/profiling_test_data/major_test_cases#L149)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this seems unrelated.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-31 11:26 UTC, orizi requested changes
> Reviewed 2 of 41 files at r1, 16 of 41 files at r2, 1 of 1 files at r3, 7 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @gilbens-starkware, and @maciektr)

___
*[`crates/cairo-lang-defs/src/plugin_utils.rs` line 83 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6388#-OAWyZ2zB-MJVdIKthrn:-OAXJba7EFWz3l-Cj_Xu:b-alnres) ([raw file](https://github.com/starkware-libs/cairo/blob/24c52fc63bc03583bd46ddd90c43790f05b722ce/crates/cairo-lang-defs/src/plugin_utils.rs#L83)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Why the 2 tabs? this is not a code formatting.
probably use indoc! as well.
</blockquote></details>

just remove the `\n` you don't know what would format your error message.


<!-- Sent from Reviewable.io -->

2024-10-31 12:28 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: 47 of 51 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @maciektr, and @orizi)

___
*[`crates/cairo-lang-defs/src/plugin_utils.rs` line 83 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6388#-OAWyZ2zB-MJVdIKthrn:-OAXXz2f0Fdjnk5EQlZu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/24c52fc63bc03583bd46ddd90c43790f05b722ce/crates/cairo-lang-defs/src/plugin_utils.rs#L83)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

just remove the `\n` you don't know what would format your error message.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 796 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6388#-OAXHUGnCYetD11aWGnO:-OAXXybt1l-mbqMtg-o0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/24c52fc63bc03583bd46ddd90c43790f05b722ce/crates/cairo-lang-formatter/src/formatter_impl.rs#L796)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc the hell out of this - as well as  add a todo - as it WOULD break upon the first non arg_list conforming macro.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-parser/src/parser.rs` line 2960 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6388#-OAXHiKm27TGDtO7RKVm:-OAXXzkkACXPwx4wAyF9:b-4xc9cs) ([raw file](https://github.com/starkware-libs/cairo/blob/24c52fc63bc03583bd46ddd90c43790f05b722ce/crates/cairo-lang-parser/src/parser.rs#L2960)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why the  `pub(crate)`s all around?
</blockquote></details>

It is used in the macro helpers


<!-- Sent from Reviewable.io -->

2024-10-31 12:31 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388#-:-OAXYrSn8utk3T-0GNsx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae and @maciektr)



<!-- Sent from Reviewable.io -->

2024-10-31 12:32 UTC, orizi approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @maciektr)



<!-- Sent from Reviewable.io -->

2024-10-31 12:32 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @gilbens-starkware, and @maciektr)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6388#-OAXYzzj6nvvP4RcQq_P:-OAXYzzj6nvvP4RcQq_Q:b-bo0p7r) (no related file):*
blocking - so won't be merged until additional parts are implemented.

consider moving to a feature branch.

___


<!-- Sent from Reviewable.io -->

2024-10-31 13:37 UTC, orizi approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @maciektr)



<!-- Sent from Reviewable.io -->

2024-11-03 14:02 UTC, orizi approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @maciektr)



<!-- Sent from Reviewable.io -->

2024-11-04 08:53 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 41 files at r1, 24 of 41 files at r2, 1 of 1 files at r3, 10 of 15 files at r4, 3 of 4 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388#-:-OAqNEL6BUJnVKMZ7gky:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @maciektr)



<!-- Sent from Reviewable.io -->

2024-11-04 10:28 UTC, Draggu requested changes
> Reviewed 7 of 41 files at r1, 28 of 41 files at r2, 1 of 1 files at r3, 10 of 15 files at r4, 3 of 4 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @gilbens-starkware, and @maciektr)

___
*[`crates/cairo-lang-defs/src/diagnostic_utils.rs` line 49 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6388#-OAqhyut2UAxTT6b8gZx:-OAqhyut2UAxTT6b8gZy:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/e8b43ac592d2fe704c8acf7a2a4301b046a77e6c/crates/cairo-lang-defs/src/diagnostic_utils.rs#L49)):*
> ```XML
>     pub fn diagnostic_location(&self, db: &dyn DefsGroup) -> DiagnosticLocation {
>         if self.inner_span.is_some() {
>             println!("Diagnostic location: {:?}", self.inner_span);
> ```

remove
___
*[`crates/cairo-lang-defs/src/diagnostic_utils.rs` line 74 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6388#-OAqi02X0SxXPzM9Efw5:-OAqi02X0SxXPzM9Efw6:b-l6mwxj) ([raw file](https://github.com/starkware-libs/cairo/blob/e8b43ac592d2fe704c8acf7a2a4301b046a77e6c/crates/cairo-lang-defs/src/diagnostic_utils.rs#L74)):*
> ```XML
>     ) -> DiagnosticLocation {
>         if self.inner_span.is_some() {
>             println!("Diagnostic location until: {:?}", self.inner_span);
> ```

remove


<!-- Sent from Reviewable.io -->

2024-11-07 09:58 UTC, orizi approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @gilbens-starkware, and @maciektr)



<!-- Sent from Reviewable.io -->

2025-01-04 20:27 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: 50 of 51 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @maciektr, @mkaput, and @orizi)

___
*[`crates/cairo-lang-defs/src/diagnostic_utils.rs` line 49 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6388#-OAqhyut2UAxTT6b8gZx:-OEmn9yRAl_jhTwOp4r2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e8b43ac592d2fe704c8acf7a2a4301b046a77e6c/crates/cairo-lang-defs/src/diagnostic_utils.rs#L49)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`crates/cairo-lang-defs/src/diagnostic_utils.rs` line 74 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6388#-OAqi02X0SxXPzM9Efw5:-OEmnACG0XmuEOeLrquj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e8b43ac592d2fe704c8acf7a2a4301b046a77e6c/crates/cairo-lang-defs/src/diagnostic_utils.rs#L74)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-05 09:04 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: 50 of 51 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @maciektr, and @mkaput)

___
*[`crates/cairo-lang-defs/src/diagnostic_utils.rs` line 22 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6388#-OFphH_vEm2pTtNHm9sO:-OFphH_vEm2pTtNHm9sP:bhuxksv) ([raw file](https://github.com/starkware-libs/cairo/blob/e55e6f4c9e4b52d41f6f30e26f30f45fa37be153/crates/cairo-lang-defs/src/diagnostic_utils.rs#L22)):*
> ```XML
>     inner_span: Option<(TextWidth, TextWidth)>,
> }
> pub struct StableLocation {
> ```

remove new duplicates.


<!-- Sent from Reviewable.io -->

2025-01-07 09:36 UTC, Draggu requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: 50 of 51 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @gilbens-starkware, @maciektr, @mkaput, and @orizi)

___
*[`crates/cairo-lang-defs/src/diagnostic_utils.rs` line 74 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6388#-OAqi02X0SxXPzM9Efw5:-OG-6gXA1XvyE7Xr1go0:bfhqml6) ([raw file](https://github.com/starkware-libs/cairo/blob/e8b43ac592d2fe704c8acf7a2a4301b046a77e6c/crates/cairo-lang-defs/src/diagnostic_utils.rs#L74)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done.


<!-- Sent from Reviewable.io -->

2025-01-07 10:07 UTC, orizi reviewed
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @gilbens-starkware, and @maciektr)



<!-- Sent from Reviewable.io -->

2025-01-07 20:52 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: 50 of 52 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @maciektr, and @orizi)

___
*[`crates/cairo-lang-defs/src/diagnostic_utils.rs` line 74 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6388#-OAqi02X0SxXPzM9Efw5:-OG1UkEu8Qwge9YNFm23:b97br10) ([raw file](https://github.com/starkware-libs/cairo/blob/e8b43ac592d2fe704c8acf7a2a4301b046a77e6c/crates/cairo-lang-defs/src/diagnostic_utils.rs#L74)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

Bad rebase, done.
___
*[`crates/cairo-lang-defs/src/diagnostic_utils.rs` line 22 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6388#-OFphH_vEm2pTtNHm9sO:-OG1VX6S73Lv52QPa47D:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/e55e6f4c9e4b52d41f6f30e26f30f45fa37be153/crates/cairo-lang-defs/src/diagnostic_utils.rs#L22)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove new duplicates.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-07 22:26 UTC, orizi requested changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, and @maciektr)

___
*[`corelib/src/test/language_features/for_test.cairo` line 24 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6388#-OG1rTRg5TmhUhmcDit0:-OG1rTRg5TmhUhmcDit1:b-l6hdjr) ([raw file](https://github.com/starkware-libs/cairo/blob/b3281faf998007cb22399f8a53755cb6bc920dec/corelib/src/test/language_features/for_test.cairo#L24)):*
> ```Cairo
> fn test_for_loop_array_tuples() {
>     let mut i = 10;
>     for (x, y) in array![(10, 10), (11, 11), (12, 12)] {
> ```

revert


<!-- Sent from Reviewable.io -->

2025-01-08 10:37 UTC, Draggu approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @gilbens-starkware, and @maciektr)



<!-- Sent from Reviewable.io -->

2025-01-08 11:56 UTC, mkaput approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @gilbens-starkware, and @maciektr)



<!-- Sent from Reviewable.io -->

2025-01-09 09:40 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @maciektr, and @orizi)

___
*[`corelib/src/test/language_features/for_test.cairo` line 24 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6388#-OG1rTRg5TmhUhmcDit0:-OG9QuBN-HINU9M9XHwh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b3281faf998007cb22399f8a53755cb6bc920dec/corelib/src/test/language_features/for_test.cairo#L24)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-09 10:45 UTC, orizi approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6388)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @maciektr)



<!-- Sent from Reviewable.io -->

2025-01-09 12:48 UTC, merged