statement types in resolver
starkware-libs/cairo pull request #6408
Opened 2024-09-23 13:36 UTC by Tomer-StarkWare

2024-09-24 07:39 UTC, gilbens-starkware requested changes
> Reviewed 1 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6408)* status: 1 of 9 files reviewed, 6 unresolved discussions (waiting on @orizi and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 496 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7XtyRX0T-LvyZD55RY:-O7XtyRX0T-LvyZD55RZ:b-5mfkbu) ([raw file](https://github.com/starkware-libs/cairo/blob/b045efc03903dca75e81f90b6555466bd7ae63f0/crates/cairo-lang-semantic/src/diagnostic.rs#L496)):*
> ```XML
>                 format!(r#"Multiple definitions of type "{}"."#, type_name)
>             }
>             SemanticDiagnosticKind::UnusedType => "Unused type.".into(),
> ```

You haven't actually added support of type definition in functions, just importing them, so the correct diagnostic is `UnsedUse`. 
And for the multiple types, I think we want one diagnostic type, for multiple items with the same name, and as Ori mentioned there should be two groups of items, variable like (e.g.) and proper items, so probably one diagnostic for each group.



_Code quote:_
```XML
            SemanticDiagnosticKind::MultipleTypeDefinition(type_name) => {
                format!(r#"Multiple definitions of type "{}"."#, type_name)
            }
            SemanticDiagnosticKind::UnusedType => "Unused type.".into(),
```
___
*[`crates/cairo-lang-semantic/src/types.rs` line 480 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7XuhCi9YnoGC6yWr1M:-O7XuhCi9YnoGC6yWr1N:bqqf53i) ([raw file](https://github.com/starkware-libs/cairo/blob/b045efc03903dca75e81f90b6555466bd7ae63f0/crates/cairo-lang-semantic/src/types.rs#L480)):*
> ```XML
> // TODO(spapini): add a query wrapper.
> /// Resolves a type given a module and a path.
> /// Type called not inside a statement
> ```

Let the formatter break the lines.



_Suggestion:_
```XML
/// Resolves a type given a module and a path. Used for resolving from non-statement context.
```
___
*[`crates/cairo-lang-semantic/src/types.rs` line 489 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7Xv0397Mn8PHOxLKde:-O7Xv0397Mn8PHOxLKdf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b045efc03903dca75e81f90b6555466bd7ae63f0/crates/cairo-lang-semantic/src/types.rs#L489)):*
> ```XML
>     resolve_type_ex(db, diagnostics, resolver, ty_syntax, None)
> }
> /// Resolves a type given a module and a path.
> ```





_Suggestion:_
```XML
/// Resolves a type given a module and a path. `statement_env` should be provided if called from statement context.
```
___
*[`crates/cairo-lang-semantic/src/types.rs` line 490 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7XwDi2AmBm3__KNlur:-O7XwDi2AmBm3__KNlus:b-aahrvs) ([raw file](https://github.com/starkware-libs/cairo/blob/b045efc03903dca75e81f90b6555466bd7ae63f0/crates/cairo-lang-semantic/src/types.rs#L490)):*
> ```XML
> }
> /// Resolves a type given a module and a path.
> pub fn resolve_type_ex(
> ```

Consider changing this function to `resolve_type_with_enviorment` and make the above function call directly to `maybe_resolve_type`.



_Code quote:_
```XML
/// Resolves a type given a module and a path.
pub fn resolve_type_ex(
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 238 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7Xx3nV-5JP04-ypyKI:-O7Xx3nV-5JP04-ypyKJ:b8r7tzh) ([raw file](https://github.com/starkware-libs/cairo/blob/b045efc03903dca75e81f90b6555466bd7ae63f0/crates/cairo-lang-semantic/src/expr/compute.rs#L238)):*
> ```XML
>             self.diagnostics.report(statement_ty.stable_ptr, UnusedType);
>         }
>     }
> ```

This function is called only once, inline it.



_Code quote:_
```XML
    /// Adds warning for unused types if required.
    fn add_unused_types_warning(&mut self, ty_name: &str, statement_ty: &StatementType) {
        if !self.environment.used_types.contains(ty_name) && !ty_name.starts_with('_') {
            self.diagnostics.report(statement_ty.stable_ptr, UnusedType);
        }
    }
```
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 297 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7XxDjmD08u4Vna19dD:-O7XxDjmD08u4Vna19dE:bh7sps0) ([raw file](https://github.com/starkware-libs/cairo/blob/b045efc03903dca75e81f90b6555466bd7ae63f0/crates/cairo-lang-semantic/src/expr/compute.rs#L297)):*
> ```XML
> #[derive(Clone, Debug, PartialEq, Eq, DebugWithDb)]
> #[debug_db(dyn SemanticGroup + 'static)]
> struct StatementType {
> ```

It isn't necessarily a type, 



_Code quote:_
```XML
struct StatementType {
```


<!-- Sent from Reviewable.io -->

2024-09-24 08:24 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6408)* status: 1 of 9 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 496 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7XtyRX0T-LvyZD55RY:-O7Y6ubV8rNG1DkMZjJh:bjrjt0b) ([raw file](https://github.com/starkware-libs/cairo/blob/b045efc03903dca75e81f90b6555466bd7ae63f0/crates/cairo-lang-semantic/src/diagnostic.rs#L496)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

You haven't actually added support of type definition in functions, just importing them, so the correct diagnostic is `UnsedUse`. 
And for the multiple types, I think we want one diagnostic type, for multiple items with the same name, and as Ori mentioned there should be two groups of items, variable like (e.g.) and proper items, so probably one diagnostic for each group.
</blockquote></details>

I'll set the Unused Type in use to Unused Use, but regarding the variables and proper items, Rust allows both use X::R, Y::R for:
mod X {
      type R = ...;
}
mod Y {
      const R = ...;
}
Meaning Const and Types don't collide, to do the same here?


<!-- Sent from Reviewable.io -->

2024-09-24 08:35 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6408)* status: 1 of 9 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`corelib/src/test/language_features/block_level_items_test.cairo` line 51 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7Y9eM4DmTkZytcEnnq:-O7Y9eM8E3lVrDgIoggK:b8tqdbk) ([raw file](https://github.com/starkware-libs/cairo/blob/b045efc03903dca75e81f90b6555466bd7ae63f0/corelib/src/test/language_features/block_level_items_test.cairo#L51)):*
> ```Cairo
> pub mod SingleConstMod {
>     pub const A: u8 = 1;
> }
> ```

snake case all `mod`s - and don't have the work `Mod` as part of it.



_Suggestion:_
```Cairo
pub mod single_const {
    pub const A: u8 = 1;
}
```


<!-- Sent from Reviewable.io -->

2024-09-24 09:58 UTC, gilbens-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6408)* status: 1 of 9 files reviewed, 7 unresolved discussions (waiting on @orizi and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 496 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7XtyRX0T-LvyZD55RY:-O7YKDux7LTf29dE8mtx:b8cpnvv) ([raw file](https://github.com/starkware-libs/cairo/blob/b045efc03903dca75e81f90b6555466bd7ae63f0/crates/cairo-lang-semantic/src/diagnostic.rs#L496)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

I'll set the Unused Type in use to Unused Use, but regarding the variables and proper items, Rust allows both use X::R, Y::R for:
mod X {
      type R = ...;
}
mod Y {
      const R = ...;
}
Meaning Const and Types don't collide, to do the same here?
</blockquote></details>

Yes, const and types shouldn't collide.


<!-- Sent from Reviewable.io -->

2024-09-24 11:13 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6408)* status: 1 of 9 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/test/language_features/block_level_items_test.cairo` line 51 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7Y9eM4DmTkZytcEnnq:-O7YAmXq1W6atlX3I-Ob:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b045efc03903dca75e81f90b6555466bd7ae63f0/corelib/src/test/language_features/block_level_items_test.cairo#L51)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

snake case all `mod`s - and don't have the work `Mod` as part of it.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 496 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7XtyRX0T-LvyZD55RY:-O7YVnCA0P1_qenqF_y8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b045efc03903dca75e81f90b6555466bd7ae63f0/crates/cairo-lang-semantic/src/diagnostic.rs#L496)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Yes, const and types shouldn't collide.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 480 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7XuhCi9YnoGC6yWr1M:-O7YAuR_2tP8rDz6ZD0w:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b045efc03903dca75e81f90b6555466bd7ae63f0/crates/cairo-lang-semantic/src/types.rs#L480)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Let the formatter break the lines.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 489 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7Xv0397Mn8PHOxLKde:-O7YAy_r5sQgdUp33au5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b045efc03903dca75e81f90b6555466bd7ae63f0/crates/cairo-lang-semantic/src/types.rs#L489)):*
> ```XML
>     resolve_type_ex(db, diagnostics, resolver, ty_syntax, None)
> }
> /// Resolves a type given a module and a path.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 490 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7XwDi2AmBm3__KNlur:-O7YBtBG2b4mOOHkcFw4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b045efc03903dca75e81f90b6555466bd7ae63f0/crates/cairo-lang-semantic/src/types.rs#L490)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Consider changing this function to `resolve_type_with_enviorment` and make the above function call directly to `maybe_resolve_type`.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 238 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7Xx3nV-5JP04-ypyKI:-O7YHRbr1TKtzgZjCyqj:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b045efc03903dca75e81f90b6555466bd7ae63f0/crates/cairo-lang-semantic/src/expr/compute.rs#L238)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

This function is called only once, inline it.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 297 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7XxDjmD08u4Vna19dD:-O7YGWA91sJTdItK7RKi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b045efc03903dca75e81f90b6555466bd7ae63f0/crates/cairo-lang-semantic/src/expr/compute.rs#L297)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

It isn't necessarily a type,
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-24 11:54 UTC, orizi requested changes
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6408)* status: 3 of 9 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 293 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7YsSdM6S50th_KCPkD:-O7YsSdM6S50th_KCPkE:b-r68v8n) ([raw file](https://github.com/starkware-libs/cairo/blob/1c2d11ee94c2653bd11c35fe80379d9c20e55163/crates/cairo-lang-semantic/src/expr/compute.rs#L293)):*
> ```XML
> #[derive(Clone, Debug, PartialEq, Eq, DebugWithDb)]
> #[debug_db(dyn SemanticGroup + 'static)]
> struct StatementGeneric {
> ```

rename both `EnvTypes` and `StatementGeneric` to relevant names.



_Code quote:_
```XML
type EnvTypes = OrderedHashMap<SmolStr, StatementGeneric>;

/// Struct that holds the resolved generic type of a statement item.
#[derive(Clone, Debug, PartialEq, Eq, DebugWithDb)]
#[debug_db(dyn SemanticGroup + 'static)]
struct StatementGeneric {
```


<!-- Sent from Reviewable.io -->

2024-09-24 13:23 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6408)* status: 3 of 9 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 293 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7YsSdM6S50th_KCPkD:-O7ZBp4W-7ZPvudnWQpM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1c2d11ee94c2653bd11c35fe80379d9c20e55163/crates/cairo-lang-semantic/src/expr/compute.rs#L293)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rename both `EnvTypes` and `StatementGeneric` to relevant names.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-24 13:47 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6408)* status: 3 of 9 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 494 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7ZE1be7g7fP56iT48t:-O7ZG73kC508L08_C6rK:bvskcdq) ([raw file](https://github.com/starkware-libs/cairo/blob/1c2d11ee94c2653bd11c35fe80379d9c20e55163/crates/cairo-lang-semantic/src/diagnostic.rs#L494)):*
> ```XML
>             }
>             SemanticDiagnosticKind::MultipleGenericItemDefinition(type_name) => {
>                 format!(r#"Multiple definitions of generic item "{}"."#, type_name)
> ```

There is also a Multiple Binding Definition, and Bindings are also Items. Should I merge them together?


<!-- Sent from Reviewable.io -->

2024-09-25 07:49 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6408)* status: 3 of 9 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 491 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7ZDVFO7NIbY9W1I3tR:-O7c9-ypCnUN1Zvo3zOy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1c2d11ee94c2653bd11c35fe80379d9c20e55163/crates/cairo-lang-semantic/src/types.rs#L491)):*
> ```XML
> /// Resolves a type given a module and a path. `statement_env` should be provided if called from
> /// statement context.
> pub fn resolve_type_with_statement(
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-09-30 08:04 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6408#-:-O80xQGBDf_FqoFl7J-5:bnfp4nl)* status: 3 of 12 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @orizi, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-09-30 08:53 UTC, orizi requested changes
> Reviewed 1 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6408)* status: 4 of 12 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @piotmag769, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 307 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O817VRxCgNMIvcFL3th:-O817VRyDAmVMz8grq0Y:b-1d3jed) ([raw file](https://github.com/starkware-libs/cairo/blob/0bfb95d2ab66460a46fe9fe3c0b91fa908aac344/crates/cairo-lang-semantic/src/expr/compute.rs#L307)):*
> ```XML
>     used_variables: UnorderedHashSet<semantic::VarId>,
>     use_types: EnvGenericItems,
>     used_use_types: UnorderedHashSet<SmolStr>,
> ```

these aren't types.

i think you should use the word - `Item` all around - probably also drop the "generic".



_Code quote:_
```XML
    use_types: EnvGenericItems,
    used_use_types: UnorderedHashSet<SmolStr>,
```


<!-- Sent from Reviewable.io -->

2024-09-30 11:56 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6408)* status: 4 of 12 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 307 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O817VRxCgNMIvcFL3th:-O81mMpR8JffZOcbLUcy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/0bfb95d2ab66460a46fe9fe3c0b91fa908aac344/crates/cairo-lang-semantic/src/expr/compute.rs#L307)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

these aren't types.

i think you should use the word - `Item` all around - probably also drop the "generic".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-01 07:41 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6408)* status: 4 of 12 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 343 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O860ZXv4cgruPE9WauH:-O860ZXw4a0miehuE6dN:b-akq6l1) ([raw file](https://github.com/starkware-libs/cairo/blob/22587d4daed684455008ce9bc4750653df24893b/crates/cairo-lang-semantic/src/expr/compute.rs#L343)):*
> ```XML
> 
> /// Returns the requested type from the environment if it exists. Returns None otherwise.
> pub fn get_statement_type_by_name(
> ```

fix name - type --> item.


<!-- Sent from Reviewable.io -->

2024-10-01 08:41 UTC, orizi requested changes
> Reviewed 3 of 9 files at r1, 1 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6408)* status: 8 of 13 files reviewed, 10 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 207 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O86CUSI6L1IQ9-QjZ3v:-O86CUSI6L1IQ9-QjZ3w:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8396451da5b5f0c11482d0590fbe193f323ae5cd/crates/cairo-lang-semantic/src/expr/compute.rs#L207)):*
> ```XML
>             self.add_unused_binding_warning(&var_name, &var);
>         }
>         // Adds warning for unused types if required.
> ```





_Suggestion:_
```XML
// Adds warning for unused items if required.
```
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 201 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O86Ck6LBVHnSrKcUVys:-O86Ck6LBVHnSrKcUVyt:b967jun) ([raw file](https://github.com/starkware-libs/cairo/blob/8396451da5b5f0c11482d0590fbe193f323ae5cd/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L201)):*
> ```
> warning[E0001]: Unused variable. Consider ignoring by prefixing with `_`.
>  --> lib.cairo:11:9
>     let x = R { a: 4 }; 
> ```

add `_` remove irrelevant diagnostics.

everywhere.



_Code quote:_
```
warning[E0001]: Unused variable. Consider ignoring by prefixing with `_`.
 --> lib.cairo:9:9
    let y = RR { a: 3 };
        ^

warning[E0001]: Unused variable. Consider ignoring by prefixing with `_`.
 --> lib.cairo:11:9
    let x = R { a: 4 };
```
___
*[`crates/cairo-lang-semantic/src/resolve/item.rs` line 97 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O86Df772sphgYzLq9Pp:-O86Df772sphgYzLq9Pq:b-hfpv23) ([raw file](https://github.com/starkware-libs/cairo/blob/8396451da5b5f0c11482d0590fbe193f323ae5cd/crates/cairo-lang-semantic/src/resolve/item.rs#L97)):*
> ```XML
>     Trait(ConcreteTraitId),
>     Impl(ImplId),
>     Statement(ResolvedGenericItem),
> ```

remove.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 423 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O86Dk1l8dqJlu56WIta:-O86Dk1l8dqJlu56WItb:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8396451da5b5f0c11482d0590fbe193f323ae5cd/crates/cairo-lang-semantic/src/resolve/mod.rs#L423)):*
> ```XML
>                     }
>                     ResolvedBase::StatementEnvironment(generic_item) => {
>                         ResolvedConcreteItem::Statement(generic_item)
> ```





_Suggestion:_
```XML
                        segments.next();
                        function_that_adds_generic_args_to_concretize(generic_item, generics)
```
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 450 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O86EG_S8bsDdJlKVo6n:-O86EG_TBaZ1BoxRzAUT:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/8396451da5b5f0c11482d0590fbe193f323ae5cd/crates/cairo-lang-semantic/src/resolve/mod.rs#L450)):*
> ```XML
>                         ),
>                         ResolvedBase::StatementEnvironment(generic_item) => {
>                             ResolvedConcreteItem::Statement(generic_item)
> ```





_Suggestion:_
```XML
                        segments.next();
                        function_that_adds_generic_args_to_concretize(generic_item, generics)
```
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 673 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O86EOCK-dpLbUjfGZsb:-O86EOCL-WoiHmjmh2KY:b-6y3f5a) ([raw file](https://github.com/starkware-libs/cairo/blob/8396451da5b5f0c11482d0590fbe193f323ae5cd/crates/cairo-lang-semantic/src/resolve/mod.rs#L673)):*
> ```XML
>                     segment_stable_ptr,
>                 );
>                 Ok(specialized_item)
> ```

this is the logic of the function described above.



_Code quote:_
```XML
            ResolvedConcreteItem::Statement(inner_generic_item) => {
                let segment_stable_ptr = segment.stable_ptr().untyped();
                let specialized_item = self.specialize_generic_module_item(
                    diagnostics,
                    identifier,
                    inner_generic_item.clone(),
                    generic_args_syntax.clone(),
                )?;
                self.warn_same_impl_trait(
                    diagnostics,
                    &specialized_item,
                    &generic_args_syntax.unwrap_or_default(),
                    segment_stable_ptr,
                );
                Ok(specialized_item)
```


<!-- Sent from Reviewable.io -->

2024-10-01 11:45 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6408)* status: 6 of 15 files reviewed, 10 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 207 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O86CUSI6L1IQ9-QjZ3v:-O86t-ug69asRqA2bsaZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8396451da5b5f0c11482d0590fbe193f323ae5cd/crates/cairo-lang-semantic/src/expr/compute.rs#L207)):*
> ```XML
>             self.add_unused_binding_warning(&var_name, &var);
>         }
>         // Adds warning for unused types if required.
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 201 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O86Ck6LBVHnSrKcUVys:-O86s6y098bBrhjpovwR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8396451da5b5f0c11482d0590fbe193f323ae5cd/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L201)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add `_` remove irrelevant diagnostics.

everywhere.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 423 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O86Dk1l8dqJlu56WIta:-O86rUWH7uFSutUlaXO5:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8396451da5b5f0c11482d0590fbe193f323ae5cd/crates/cairo-lang-semantic/src/resolve/mod.rs#L423)):*
> ```XML
>                     }
>                     ResolvedBase::StatementEnvironment(generic_item) => {
>                         ResolvedConcreteItem::Statement(generic_item)
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 450 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O86EG_S8bsDdJlKVo6n:-O86rTjf3yaFr3wjuyof:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8396451da5b5f0c11482d0590fbe193f323ae5cd/crates/cairo-lang-semantic/src/resolve/mod.rs#L450)):*
> ```XML
>                         ),
>                         ResolvedBase::StatementEnvironment(generic_item) => {
>                             ResolvedConcreteItem::Statement(generic_item)
> ```

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 673 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O86EOCK-dpLbUjfGZsb:-O86rT-Q5EqatlJEPM8-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8396451da5b5f0c11482d0590fbe193f323ae5cd/crates/cairo-lang-semantic/src/resolve/mod.rs#L673)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this is the logic of the function described above.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/item.rs` line 97 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O86Df772sphgYzLq9Pp:-O86Uglz6THmfuGGG-5s:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8396451da5b5f0c11482d0590fbe193f323ae5cd/crates/cairo-lang-semantic/src/resolve/item.rs#L97)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

remove.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-01 14:49 UTC, mkaput approved these changes
> Reviewed 3 of 9 files at r1, 1 of 4 files at r3, 1 of 3 files at r5, 8 of 8 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6408)* status: all files reviewed, 10 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, and @orizi)



<!-- Sent from Reviewable.io -->

2024-10-02 08:51 UTC, orizi requested changes
> Reviewed 2 of 8 files at r11, 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6408)* status: all files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 667 at r12](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O8BPp3C5TQruisJ35BD:-O8BPp3C5TQruisJ35BE:bncfutz) ([raw file](https://github.com/starkware-libs/cairo/blob/15774a6b4e70afd3a274e380ac8577c1e725bf10/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L667)):*
> ```
> //! > ==========================================================================
> 
> //! > Test use type enum and const together
> ```

i don't understand the test.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 397 at r12](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O8BQ0S55NcEvzQiHgW2:-O8BQ0S55NcEvzQiHgW3:b-1ipit) ([raw file](https://github.com/starkware-libs/cairo/blob/15774a6b4e70afd3a274e380ac8577c1e725bf10/crates/cairo-lang-semantic/src/resolve/mod.rs#L397)):*
> ```XML
>     }
> 
>     fn generic_arg_to_concrete(
> ```

doc.
move to the end - as this is a helper.


<!-- Sent from Reviewable.io -->

2024-10-06 07:34 UTC, Tomer-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6408)* status: 13 of 15 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 667 at r12](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O8BPp3C5TQruisJ35BD:-O8Vk1ul6syn_XnyzKde:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/15774a6b4e70afd3a274e380ac8577c1e725bf10/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L667)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't understand the test.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 397 at r12](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O8BQ0S55NcEvzQiHgW2:-O8Vi9S-0wc0SKcvctrF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/15774a6b4e70afd3a274e380ac8577c1e725bf10/crates/cairo-lang-semantic/src/resolve/mod.rs#L397)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc.
move to the end - as this is a helper.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-06 07:49 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 8 files at r11, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6408#-:-O8VnXNu2A4x7r49Kt0F:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, and @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2024-10-08 06:49 UTC, gilbens-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 9 files at r1, 1 of 4 files at r3, 1 of 3 files at r5, 6 of 8 files at r11, 2 of 2 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6408#-:-O8es_Gc7GeQagG1BAtA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @Tomer-StarkWare)

___
*[`crates/cairo-lang-semantic/src/diagnostic.rs` line 494 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6408#-O7ZE1be7g7fP56iT48t:-O8escDUEM_QzAMTOYGi:b1ci09n) ([raw file](https://github.com/starkware-libs/cairo/blob/1c2d11ee94c2653bd11c35fe80379d9c20e55163/crates/cairo-lang-semantic/src/diagnostic.rs#L494)):*
<details><summary><i>Previously, Tomer-StarkWare (TomerC-StarkWare) wrote…</i></summary><blockquote>

There is also a Multiple Binding Definition, and Bindings are also Items. Should I merge them together?
</blockquote></details>

That's fine for now, maybe it'll need refining in your next PRs.


<!-- Sent from Reviewable.io -->

2024-10-08 07:41 UTC, merged