LS: Rewrite from `tower_lsp` to `lsp_server`
starkware-libs/cairo pull request #6431
Opened 2024-09-27 11:30 UTC by Draggu

Closes #6132
Closes #6330

Rewrite done by @piotmag769 with additional test fixes.

2024-09-30 08:57 UTC, orizi requested changes
> Reviewed 5 of 61 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: 5 of 61 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`clippy.toml` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O817smv6eW5-CuHS7Wm:-O817smv6eW5-CuHS7Wn:b-4ymqxc) ([raw file](https://github.com/starkware-libs/cairo/blob/f72fedf3feb6d2a1ba2e496c2f3b3a15979dac3d/clippy.toml#L2)):*
> ```TOML
> enum-variant-name-threshold = 1
> ignore-interior-mutability = ["lsp_types::Uri"]
> ```

is the issue is very local?
if so - i'd rather have `#[allow(clippy::ignore_interior_mutability)]` in that area.



_Code quote:_
```TOML
ignore-interior-mutability = ["lsp_types::Uri"]
```


<!-- Sent from Reviewable.io -->

2024-09-30 15:16 UTC, Arcticae requested changes
> Reviewed 10 of 61 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: 10 of 61 files reviewed, 10 unresolved discussions (waiting on @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 264 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O81vd2P0JcyaObFFNlK:-O81vd2P0JcyaObFFNlL:b80urfh) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L264)):*
> ```XML
> 
>         (init, client)
>     }
> ```

Shouldn't this be wrapped in `cfg[test]` ? 



_Code quote:_
```XML
    fn new_for_testing(
        tricks: Tricks,
    ) -> (Box<dyn FnOnce() -> Self + Send>, lsp_server::Connection) {
        let (connection_initializer, client) = ConnectionInitializer::memory();

        let init = Box::new(|| Self::new_inner(tricks, connection_initializer).unwrap());

        (init, client)
    }
```
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 309 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O81ynUN08-QubOzQiqx:-O81ynUN08-QubOzQiqy:bu4nv40) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L309)):*
> ```XML
>         let dynamic_registrations = collect_dynamic_registrations(&state.client_capabilities);
> 
>         let mut scheduler = Scheduler::new(&mut state, worker_threads, connection.make_sender());
> ```

[nit]: Wouldn't it make sense to extract it higher up so this loop only handles execution?
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 317 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O820T794mh1mIa7CAPm:-O820T794mh1mIa7CAPn:b-26z4kk) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L317)):*
> ```XML
>         };
> 
>         scheduler.request::<lsp_types::request::RegisterCapability>(
> ```

Is this happening before the whole handling loop? I think that was the assumption here?
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 367 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O82-pr68OsL8jGw3EQZ:-O82-pr68OsL8jGw3EQ_:biagdm5) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L367)):*
> ```XML
>     #[tracing::instrument(level = "debug", skip_all)]
>     fn refresh_diagnostics(state: &mut State, notifier: &Notifier) -> LSPResult<()> {
>         // TODO: implement a pop queue of size 1 for diags
> ```

Can we mark it with an issue number if it's not something we want to address here?
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 686 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O823Kr9BaGlezAHE14i:-O823Kr9BaGlezAHE14j:b-iomak1) ([raw file](https://github.com/starkware-libs/cairo/blob/e4136a412b03aff3ba1dec3eb8d8d22356cd67ae/crates/cairo-lang-language-server/src/lib.rs#L686)):*
> ```XML
>         })
>         .await
>     }
> ```

What happened to those?



_Code quote:_
```XML
    #[tracing::instrument(level = "trace", skip_all)]
    async fn view_analyzed_crates(&self) -> LSPResult<String> {
        let db = self.db_snapshot().await;
        self.catch_panics(move || lang::inspect::crates::inspect_analyzed_crates(&db)).await
    }

    #[tracing::instrument(level = "trace", skip_all)]
    async fn expand_macro(&self, params: TextDocumentPositionParams) -> LSPResult<Option<String>> {
        let db = self.db_snapshot().await;
        self.catch_panics(move || ide::macros::expand::expand_macro(&db, &params)).await
    }

    #[tracing::instrument(level = "trace", skip_all)]
    async fn vfs_provide(
        &self,
        params: ProvideVirtualFileRequest,
    ) -> LSPResult<ProvideVirtualFileResponse> {
        let db = self.db_snapshot().await;
        self.catch_panics(move || {
            let content = db
                .file_for_url(&params.uri)
                .and_then(|file_id| db.file_content(file_id))
                .map(|content| content.to_string());
            ProvideVirtualFileResponse { content }
        })
        .await
    }
```
___
*[`crates/cairo-lang-language-server/src/state.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O8239gAA5NfdLo2Ncm-:-O8239gAA5NfdLo2Ncm0:b-41sp4r) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/state.rs#L82)):*
> ```XML
>     pub _config: Snapshot<Config>,
>     pub _client_capabilities: Snapshot<ClientCapabilities>,
>     pub _tricks: Snapshot<Tricks>,
> ```

What's the point here?



_Code quote:_
```XML
    pub _open_files: Snapshot<HashSet<Uri>>,
    pub _config: Snapshot<Config>,
    pub _client_capabilities: Snapshot<ClientCapabilities>,
    pub _tricks: Snapshot<Tricks>,
```
___
*[`crates/cairo-lang-language-server/src/lsp/controller.rs` line 102 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O824VNT5EGsmSC_UWvt:-O824VNT5EGsmSC_UWvu:b-g44347) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lsp/controller.rs#L102)):*
> ```XML
>         _params: CancelParams,
>     ) -> LSPResult<()> {
>         Ok(())
> ```

This is a cancellation request that we were not handling, right?
___
*[`crates/cairo-lang-language-server/src/lsp/controller.rs` line 140 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O824h8L1J856sqIVsaG:-O824h8L1J856sqIVsaH:b-cc4uki) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lsp/controller.rs#L140)):*
> ```XML
>         _params: DidChangeConfigurationParams,
>     ) -> LSPResult<()> {
>         // TODO it was this way but we shouldn't reload here, just read changes from params
> ```

Is this addressable? 
___
*[`crates/cairo-lang-language-server/tests/e2e/support/mock_client.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O82VIhUAkGD9QwYX7P6:-O82VIhUAkGD9QwYX7P7:b-80z19o) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/tests/e2e/support/mock_client.rs#L131)):*
> ```XML
>                     assert_eq!(res_id, id);
> 
>                     // TODO
> ```

TODO?


<!-- Sent from Reviewable.io -->

2024-09-30 15:43 UTC, mkaput requested changes
> Reviewed 4 of 61 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: 10 of 61 files reviewed, 13 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`clippy.toml` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O817smv6eW5-CuHS7Wm:-O82_0PfA11m5Jac4adh:b-w2jvoa) ([raw file](https://github.com/starkware-libs/cairo/blob/f72fedf3feb6d2a1ba2e496c2f3b3a15979dac3d/clippy.toml#L2)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

is the issue is very local?
if so - i'd rather have `#[allow(clippy::ignore_interior_mutability)]` in that area.
</blockquote></details>

Tip: since 1.81 it's better to use `#[expect(clippy::ignore_interior_mutability)]` so we can track obsolete lint allows
___
*[`crates/bin/cairo-language-server/src/main.rs` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O82_PCu2-Y-KirK1rBO:-O82_PCu2-Y-KirK1rBP:b-ddy6sg) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/bin/cairo-language-server/src/main.rs#L2)):*
> ```XML
> fn main() {
>     cairo_lang_language_server::start();
> ```

unnecessary change?
___
*[`crates/cairo-lang-language-server/Cargo.toml` line 46 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O82_SB61Xqnd9qhmi8d:-O82_SB61Xqnd9qhmi8e:bk7vbxg) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/Cargo.toml#L46)):*
> ```TOML
> libc = "0.2.155"
> jod-thread = "0.1.2"
> url = "2.5.2"
> ```

sort deps alphabetically
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 143 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O82_jxb3OmArUDtVUXj:-O82_jxb3OmArUDtVUXk:b-gtovgi) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L143)):*
> ```XML
>         Ok(backend) => {
>             if let Err(err) = backend.run().map(|handle| handle.join()) {
>                 error!("language server encountered an unrecoverable error: {err}")
> ```

you should set exit code here

spec: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#exit
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O82a6xe06GdSQFN3uC0:-O82a6xe06GdSQFN3uC1:b-50xylo) ([raw file](https://github.com/starkware-libs/cairo/blob/e4136a412b03aff3ba1dec3eb8d8d22356cd67ae/crates/cairo-lang-language-server/src/lib.rs#L209)):*
> ```XML
>         let (profile_layer, profile_layer_guard) = ChromeLayerBuilder::new()
>             .writer(profile_file)
>             .trace_style(TraceStyle::Async)
> ```

awesome that you caught this :ok_hand: 
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 264 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O81vd2P0JcyaObFFNlK:-O82aIEZ6UAQcGVXMzci:bkq5jhf) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L264)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Shouldn't this be wrapped in `cfg[test]` ?
</blockquote></details>

yes it should, but in `#[cfg(feature = "testing")]`


<!-- Sent from Reviewable.io -->

2024-09-30 16:01 UTC, mkaput requested changes
> Reviewed 28 of 61 files at r1, 5 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: 42 of 61 files reviewed, 14 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`Cargo.lock` line 2423 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O82dOWZCxsix0_fohI5:-O82dOWZCxsix0_fohI6:b-v1h5tp) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/Cargo.lock#L2423)):*
> ```TOML
> [[package]]
> name = "lsp-types"
> version = "0.97.0"
> ```

I see a lot of stuff is being changed here just because of upgrading this crate.

For example, see that there is quite a fuss about Url -> Uri change upstream: https://github.com/gluon-lang/lsp-types/issues/284

Also, this is a minefield for sneaking a breaking change if you think about this.

Please, let's just stay with 0.94.1 for now.


<!-- Sent from Reviewable.io -->

2024-09-30 16:09 UTC, mkaput reviewed
> Reviewed 1 of 61 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: 43 of 61 files reviewed, 14 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-10-01 05:47 UTC, mkaput requested changes
> Reviewed 3 of 61 files at r1, 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: 46 of 61 files reviewed, 15 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/Cargo.toml` line 44 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O82i0JQEtbJOYgexprE:-O82i0JQEtbJOYgexprF:b-wk5gsc) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/Cargo.toml#L44)):*
> ```TOML
> lsp-types = "0.97.0"
> rustc-hash = "1.1.0"
> libc = "0.2.155"
> ```

this is a target-specific dependency so please pull this one only on targets that actually do use it


<!-- Sent from Reviewable.io -->

2024-10-01 06:01 UTC, mkaput reviewed
> Reviewed 4 of 61 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: 50 of 61 files reviewed, 15 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-10-01 06:01 UTC, mkaput requested changes
> Reviewed 1 of 61 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: 51 of 61 files reviewed, 16 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lsp/mod.rs` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O85eqkW1U1zqNRdsPrk:-O85eqkX7y2i4utG2AyF:b-mixvap) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lsp/mod.rs#L2)):*
> ```XML
> pub(crate) mod capabilities;
> pub mod controller;
> ```

why is this becoming `pub`?


<!-- Sent from Reviewable.io -->

2024-10-01 06:10 UTC, mkaput requested changes
> Reviewed 2 of 61 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: 52 of 61 files reviewed, 21 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/server/client.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O85ghAi3hGUZJFaIe1d:-O85ghAi3hGUZJFaIe1e:b2bbfi7) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/client.rs#L55)):*
> ```XML
> 
> impl Notifier {
>     pub fn notify<N>(&self, params: N::Params) -> Result<()>
> ```

is this result used anywhere? can't we just log the error? this is making usage quite uglier (see `ScarbToolchain` changes)
___
*[`crates/cairo-lang-language-server/src/server/client.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O85gAgh5z8BmhBCWp9F:-O85gAgi9xyBP-dV1som:bb7ft0f) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/client.rs#L151)):*
> ```XML
>             handler(response)
>         } else {
>             tracing::error!("Received a response with ID {}, which was not expected", response.id);
> ```

etc.



_Suggestion:_
```XML
error!("received a response with ID {}, which was not expected", response.id);
```
___
*[`crates/cairo-lang-language-server/src/server/connection.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O85fiRj4x6sPVnx_4Fz:-O85fiRj4x6sPVnx_4G-:b-y51wju) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/connection.rs#L82)):*
> ```XML
>             {
>                 self.sender.send(lsp::Response::new_ok(id.clone(), ()).into())?;
>                 tracing::info!("Shutdown request received. Waiting for an exit notification...");
> ```

etc. everywhere in this file



_Suggestion:_
```XML
info!("shutdown request received. waiting for an exit notification");
```
___
*[`crates/cairo-lang-language-server/src/server/schedule/task.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O85f26W8vgU4WB4Frmq:-O85f26W8vgU4WB4Frmr:boxgg12) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/schedule/task.rs#L19)):*
> ```XML
>     /// The task should be run on the background thread designated
>     /// for formatting actions. This is a high priority thread.
>     Fmt,
> ```

seems like a blind copy-paste from ruff?

1. can you add source credit comments everywhere applicable?
2. drop this, we're not ruff
___
*[`crates/cairo-lang-language-server/src/server/schedule/task.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O85fIsw4DLmh_7wAf2R:-O85fIsw4DLmh_7wAf2S:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/schedule/task.rs#L81)):*
> ```XML
>         Self::local(move |_, _, _, responder| {
>             if let Err(err) = responder.respond(id, result) {
>                 tracing::error!("Unable to send immediate response: {err}");
> ```





_Suggestion:_
```XML
tracing::error!("unable to send immediate response: {err}");
```


<!-- Sent from Reviewable.io -->

2024-10-01 08:04 UTC, mkaput requested changes
> Reviewed 4 of 61 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: 56 of 61 files reviewed, 39 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/Cargo.toml` line 45 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O860gfkAYWoxJZvuvZA:-O860gfkAYWoxJZvuvZB:buzc58k) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/Cargo.toml#L45)):*
> ```TOML
> rustc-hash = "1.1.0"
> libc = "0.2.155"
> jod-thread = "0.1.2"
> ```

unused?
___
*[`crates/cairo-lang-language-server/src/server/connection.rs` line 3 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86-hVt4ubBpDkC-dPk:-O86-hVt4ubBpDkC-dPl:bw8pv30) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/connection.rs#L3)):*
> ```XML
> use std::sync::{Arc, Weak};
> 
> use lsp_server as lsp;
> ```

why this rename?
___
*[`crates/cairo-lang-language-server/src/server/connection.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86-mWY7-7BTD7pgsWP:-O86-mWY7-7BTD7pgsWQ:b-cwsqqd) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/connection.rs#L43)):*
> ```XML
>     pub fn initialize_start(
>         &self,
>     ) -> anyhow::Result<(lsp::RequestId, lsp_types::InitializeParams)> {
> ```

`use anyhow::Result`
___
*[`crates/cairo-lang-language-server/src/server/connection.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O860YK2-9UV4SCm02Tm:-O860YK2-9UV4SCm02Tn:b2ni25r) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/connection.rs#L82)):*
> ```XML
>             {
>                 self.sender.send(lsp::Response::new_ok(id.clone(), ()).into())?;
>                 tracing::info!("Shutdown request received. Waiting for an exit notification...");
> ```

etc



_Suggestion:_
```XML
info!("shutdown request received, waiting for an exit notification");
```
___
*[`crates/cairo-lang-language-server/src/server/connection.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O860V9Z4W93zHT4dZZJ:-O860V9Z4W93zHT4dZZK:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/connection.rs#L90)):*
> ```XML
>                         Ok(true)
>                     }
>                     message => anyhow::bail!(
> ```





_Suggestion:_
```XML
bail!
```
___
*[`crates/cairo-lang-language-server/src/server/api/mod.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O8615JeEUDp7MmoGbQl:-O8615JeEUDp7MmoGbQm:b2nif8j) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/api/mod.rs#L1)):*
> ```XML
> use lsp_server as server;
> ```

why
___
*[`crates/cairo-lang-language-server/src/server/api/mod.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O861FCj8iTfkYGOE-oR:-O861FCj8iTfkYGOE-oS:b-r1vu9l) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/api/mod.rs#L21)):*
> ```XML
> use crate::state::State;
> 
> pub(crate) fn request<'a>(req: server::Request) -> Task<'a> {
> ```

this routing seems to be hidden quite deep in lsp implementation internals. shouldn't it be in `lib.rs` or somewhere nearby?
___
*[`crates/cairo-lang-language-server/src/server/api/mod.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O861PKyCGT1TojBqD_d:-O861PKyCGT1TojBqD_e:bb7ft0f) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/api/mod.rs#L53)):*
> ```XML
> 
>         method => {
>             tracing::warn!("Received request {method} which does not have a handler");
> ```

etc.



_Suggestion:_
```XML
warn!("received request {method} which does not have a handler");
```
___
*[`crates/cairo-lang-language-server/src/server/api/mod.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O861TM0BoS33zt2H71b:-O861TM0BoS33zt2H71c:bwc47) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/api/mod.rs#L58)):*
> ```XML
>     }
>     .unwrap_or_else(|err| {
>         tracing::error!("Encountered error when routing request with ID {id}: {err}");
> ```

always use debug impls for anyhow errors, their `Display` impl does not show error cause stack



_Suggestion:_
```XML
{err:?}
```
___
*[`crates/cairo-lang-language-server/src/server/api/mod.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O861nYV3PaAVxNGyAve:-O861nYV3PaAVxNGyAvf:b-mz6dmy) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/api/mod.rs#L64)):*
> ```XML
> }
> 
> pub(crate) fn notification<'a>(notif: server::Notification) -> Task<'a> {
> ```

same applies to this routing proc
___
*[`crates/cairo-lang-language-server/src/server/api/mod.rs` line 191 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O863Sgw00VxaNFj8HiS:-O863Sgw00VxaNFj8HiT:b-38gv1r) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/api/mod.rs#L191)):*
> ```XML
> 
> /// A trait to convert result types into the server result type, [`LSPResult`].
> pub trait LSPResultConversionTrait<T> {
> ```

I like the contention of using `Ex` suffix for extension traits (because this is one, definitely it's not _conversion_)



_Suggestion:_
```XML
LSPResultEx
```
___
*[`crates/cairo-lang-language-server/src/server/api/mod.rs` line 219 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O863k-r7r5t8lgDATvB:-O863k-r7r5t8lgDATvC:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/api/mod.rs#L219)):*
> ```XML
>         self.error.fmt(f)
>     }
> }
> ```





_Suggestion:_
```XML
// Right now, we treat the error code as invisible data that won't
// be printed.
impl fmt::Debug for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.error.fmt(f)
    }
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.error.fmt(f)
    }
}
```
___
*[`crates/cairo-lang-language-server/src/server/schedule/mod.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O863ujj91yiBiSWIOQI:-O863ujj91yiBiSWIOQJ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/schedule/mod.rs#L20)):*
> ```XML
> pub(crate) fn event_loop_thread(
>     func: impl FnOnce() -> anyhow::Result<()> + Send + 'static,
> ) -> anyhow::Result<thread::JoinHandle<anyhow::Result<()>>> {
> ```





_Suggestion:_
```XML
pub(crate) fn event_loop_thread(
    func: impl FnOnce() -> Result<()> + Send + 'static,
) -> Result<thread::JoinHandle<Result<()>>> {
```
___
*[`crates/cairo-lang-language-server/src/server/schedule/mod.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86429W-GmtS_RM1bue:-O86429W-GmtS_RM1buf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/schedule/mod.rs#L23)):*
> ```XML
>     // Override OS defaults to avoid stack overflows on pla [...]

2024-10-01 08:30 UTC, mkaput requested changes
> Reviewed 5 of 61 files at r1, 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: 60 of 61 files reviewed, 40 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/state.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O8239gAA5NfdLo2Ncm-:-O868I6F4b0oj5c9S3BE:b51cpu0) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/state.rs#L82)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

What's the point here?
</blockquote></details>

agree, if this is not used by snapshot then these fields should just disappear
___
*[`crates/cairo-lang-language-server/src/lsp/controller.rs` line 0 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O868anE4vhlilYxSI9f:-O868anE4vhlilYxSI9g:b-238ory) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lsp/controller.rs#L0)):*
shouldn't this code lie closed to `lib.rs`?
___
*[`crates/cairo-lang-language-server/src/lsp/controller.rs` line 102 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O824VNT5EGsmSC_UWvt:-O86B7JH-vjJ76OSSXgD:b85j4f) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lsp/controller.rs#L102)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

This is a cancellation request that we were not handling, right?
</blockquote></details>

I think this should be a TODO

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#cancelRequest
___
*[`crates/cairo-lang-language-server/src/lsp/controller.rs` line 140 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O824h8L1J856sqIVsaG:-O86BN8_2goqCbLnWYqI:b-c0xyy4) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lsp/controller.rs#L140)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Is this addressable?
</blockquote></details>

this comment is wrong, params of this request are deprecated and the recommendation is to request back for full or partial config


<!-- Sent from Reviewable.io -->

2024-10-01 10:19 UTC, mkaput requested changes
> Reviewed 1 of 61 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: 60 of 61 files reviewed, 48 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86WKt28jZCD_-0w2dU:-O86WKt28jZCD_-0w2dV:b-4z30yk) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L244)):*
> ```XML
> }
> 
> pub struct Backend {
> ```

why is this becoming `pub`? we want to limit amount of stuff that is publicly available from the crate

https://docs.rs/cairo-lang-language-server/latest/cairo_lang_language_server/
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 290 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86Wk0I9EP_EsQaNAzA:-O86Wk0I9EP_EsQaNAzB:b-bsrg6f) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L290)):*
> ```XML
>     }
> 
>     pub fn run(self) -> Result<JoinHandle<Result<()>>> {
> ```

why `pub`?
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 297 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86XNjZC9uWKqOvfO9N:-O86XNjZC9uWKqOvfO9O:b-gcu27l) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L297)):*
> ```XML
>         event_loop_thread(move || {
>             Self::event_loop(&self.connection, self.state, worker_threads)?;
>             self.connection.close()?;
> ```

shouldn't we close the connection always, regardless of what `Self::event_loop` returns?
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 309 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O81ynUN08-QubOzQiqx:-O86ZLUDD4SUznNy3vl4:b-8fx2u7) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L309)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

[nit]: Wouldn't it make sense to extract it higher up so this loop only handles execution?
</blockquote></details>

:+1: 
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 313 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86YdJg96RlWQiawqUZ:-O86YdJg96RlWQiawqU_:b56purq) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L313)):*
> ```XML
>         // Register dynamic capabilities.
>         let response_handler = |()| {
>             info!("Configuration file watcher successfully registered");
> ```

no need to be so verbose



_Suggestion:_
```XML
debug!("configuration file watcher successfully registered");
```
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 317 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O820T794mh1mIa7CAPm:-O86ZBQJD0A-BDFok_nn:b-6ue9bn) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L317)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Is this happening before the whole handling loop? I think that was the assumption here?
</blockquote></details>

I think that's part of the `initialize` procedure (this was previously done within `initialize` request handler)
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 322 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86Z2SM3Xq0KI1O3Dcf:-O86Z2SM3Xq0KI1O3Dcg:b-hleh80) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L322)):*
> ```XML
>         )?;
> 
>         scheduler.dispatch(Task::Sync(SyncTask {
> ```

please add a comment explaining why we are eagerly triggering this code path
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 454 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86_-NMBPZkkGoOejme:-O86_-NMBPZkkGoOejmf:b1sch5x) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L454)):*
> ```XML
>         // After handling of all diagnostics, attempting to swap the database to reduce memory
>         // consumption.
>         // This should be removed from here when diags are background job.
> ```

I'd rather tell here that this should be an independent job, that is maybe run periodically. Wdyt?
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 556 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86_FIp8jq5CvZKS1E8:-O86_FIp8jq5CvZKS1E9:b5py0sx) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L556)):*
> ```XML
>     fn get_files_modules<'a>(
>         db: &AnalysisDatabase,
>         files_ids: impl Iterator<Item = &'a FileId>,
> ```

I wonder: `FileId` is `Copy` so why can't we just use `.copied()` iterator here?
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 647 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86_gAU6pRplE31e-B_:-O86_gAU6pRplE31e-Ba:b-7kggtr) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L647)):*
> ```XML
>     #[tracing::instrument(level = "trace", skip_all)]
>     fn detect_crate_for(
>         scarb_toolchain: &ScarbToolchain,
> ```

move this parameter further down, so that `db` comes first by convention
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 686 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O823Kr9BaGlezAHE14i:-O86_RrS3MOKCh-MaQBj:broy505) ([raw file](https://github.com/starkware-libs/cairo/blob/e4136a412b03aff3ba1dec3eb8d8d22356cd67ae/crates/cairo-lang-language-server/src/lib.rs#L686)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

What happened to those?
</blockquote></details>

@Draggu moved them into the controller module


<!-- Sent from Reviewable.io -->

2024-10-01 10:23 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: 60 of 61 files reviewed, 48 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/server/connection.rs` line 3 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86-hVt4ubBpDkC-dPk:-O86aXV20as5gShq3ELH:b-2gps9i) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/connection.rs#L3)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

i quite like it tbh
</blockquote></details>

imho it obfuscates paths further down, and also I don't like that this rename is not uniform. sometimes there's `lsp`, sometimes there's `server`


<!-- Sent from Reviewable.io -->

2024-10-01 14:43 UTC, mkaput requested changes
> Reviewed 1 of 61 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: all files reviewed, 52 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/e2e/support/mock_client.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O87X7rt7OYnO2gmm_EJ:-O87X7rt7OYnO2gmm_EK:b-o935d5) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/tests/e2e/support/mock_client.rs#L56)):*
> ```XML
>         };
> 
>         std::thread::spawn(|| init().run());
> ```

don't we want to join this thread while dropping the client? can this thread become zombie?
___
*[`crates/cairo-lang-language-server/tests/e2e/support/mock_client.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O87X4osABketDdl3Z7J:-O87X4osABketDdl3Z7K:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/tests/e2e/support/mock_client.rs#L82)):*
> ```XML
>         });
> 
>         self.expect_request::<RegisterCapability>(|_req| {});
> ```

?
___
*[`crates/cairo-lang-language-server/tests/e2e/support/mock_client.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O87UhRhA6YMwA0t14Y7:-O87UhRhA6YMwA0t14Y8:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/tests/e2e/support/mock_client.rs#L109)):*
> ```XML
>             match response_message {
>                 Message::Notification(_) => {
>                     // This looks like a notification, skip it.
> ```





_Suggestion:_
```XML
// Skip notifications.
```
___
*[`crates/cairo-lang-language-server/tests/e2e/support/mock_client.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O87WtrA5Bs6J2c-G33Z:-O87WtrA5Bs6J2c-G33_:b-847e0i) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/tests/e2e/support/mock_client.rs#L141)):*
> ```XML
>                     //     "expected more requests to be received from the client while \
>                     //          processing the current server one: {expect_request_handlers:?}"
>                     // );
> ```

if lsp_server is reordering messages, then I don't think it's possible to rewrite this assertion in a meaningful way. it's safe to drop it imo


<!-- Sent from Reviewable.io -->

2024-10-02 20:40 UTC, piotmag769 reviewed
> Reviewed 39 of 61 files at r1, 1 of 7 files at r2, 5 of 26 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: 33 of 61 files reviewed, 52 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`Cargo.lock` line 2423 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O82dOWZCxsix0_fohI5:-O8DdRtIEkHXPlrIi2zR:bf5znfm) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/Cargo.lock#L2423)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I see a lot of stuff is being changed here just because of upgrading this crate.

For example, see that there is quite a fuss about Url -> Uri change upstream: https://github.com/gluon-lang/lsp-types/issues/284

Also, this is a minefield for sneaking a breaking change if you think about this.

Please, let's just stay with 0.94.1 for now.
</blockquote></details>

Changed to 0.95.0 since I need `Request::Params` to enforce `Send` which is not done in 0.94.1
___
*[`crates/cairo-lang-language-server/Cargo.toml` line 44 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O82i0JQEtbJOYgexprE:-O8Dpb_h2blQVpPjbYVR:b-l2tt7p) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/Cargo.toml#L44)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

this is a target-specific dependency so please pull this one only on targets that actually do use it
</blockquote></details>

Done, good catch.
___
*[`crates/cairo-lang-language-server/Cargo.toml` line 45 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O860gfkAYWoxJZvuvZA:-O86qQE80UvsrUVv-3AH:b-82v6yb) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/Cargo.toml#L45)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Nope, it is used
___
*[`crates/cairo-lang-language-server/Cargo.toml` line 46 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O82_SB61Xqnd9qhmi8d:-O8DoJo32RaUZxgf8h02:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/Cargo.toml#L46)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

sort deps alphabetically
</blockquote></details>

Done
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 264 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O81vd2P0JcyaObFFNlK:-O8DqQUvBftV3p7ub4Ho:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L264)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

yes it should, but in `#[cfg(feature = "testing")]`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 290 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86Wk0I9EP_EsQaNAzA:-O8DrD4o0siFo7koyhav:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L290)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

why `pub`?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 313 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86YdJg96RlWQiawqUZ:-O8DsCVdB8PKhU1lxx_6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L313)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

no need to be so verbose
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 317 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O820T794mh1mIa7CAPm:-O8DsH3h-R9RXz9liabV:blqkpph) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L317)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I think that's part of the `initialize` procedure (this was previously done within `initialize` request handler)
</blockquote></details>

Not neccessarily.
___
*[`crates/cairo-lang-language-server/src/state.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O8239gAA5NfdLo2Ncm-:-O86oLpT7D3yjsfOkKZl:b-1h0mkf) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/state.rs#L82)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

agree, if this is not used by snapshot then these fields should just disappear
</blockquote></details>

If we remove them there is no point of our custom `Snapshot` struct even existing. I believe @Draggu wanted me to leave these to do some magic with diagnostics, but I am not sure if it is still relevant?
___
*[`crates/cairo-lang-language-server/src/lsp/controller.rs` line 102 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O824VNT5EGsmSC_UWvt:-O86oz2V1sIpg6w3hNh9:bmovpzz) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lsp/controller.rs#L102)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I think this should be a TODO

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#cancelRequest
</blockquote></details>

@Draggu told me that he discussed it with @mkaput some time ago and that you told him this is the way it should be
___
*[`crates/cairo-lang-language-server/src/lsp/controller.rs` line 140 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O824h8L1J856sqIVsaG:-O8DgkXJ2Lqst2DLQiZ9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lsp/controller.rs#L140)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

this comment is wrong, params of this request are deprecated and the recommendation is to request back for full or partial config
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lsp/controller.rs` line  at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O868anE4vhlilYxSI9f:-O86on2U5oRnP562MWm4:b-8tqek0) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lsp/controller.rs#L)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

shouldn't this code lie closed to `lib.rs`?
</blockquote></details>

It should be in `server.rs` to be fair, but I didn't want to move this in this PR, will be done in a separate one
___
*[`crates/cairo-lang-language-server/src/server/connection.rs` line 3 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86-hVt4ubBpDkC-dPk:-O86pZgg3C2iqK2AaT6x:b-glwiv7) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/connection.rs#L3)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

imho it obfuscates paths further down, and also I don't like that this rename is not uniform. sometimes there's `lsp`, sometimes there's `server`
</blockquote></details>

This file is copied almost 1:1 from ruff, will change it
___
*[`crates/cairo-lang-language-server/src/server/connection.rs` line 43 at r2](https://reviewable.io/r [...]

2024-10-02 20:47 UTC, orizi reviewed
> Reviewed 3 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: 36 of 61 files reviewed, 51 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-10-03 10:49 UTC, piotmag769 reviewed
> Reviewed 3 of 61 files at r1, 17 of 26 files at r3, 7 of 10 files at r4, 7 of 7 files at r5, all commit messages.
> Dismissed @Arcticae and @mkaput from 30 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: all files reviewed, 19 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 454 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86_-NMBPZkkGoOejme:-O8GuK3WA3ADvODbCPj_:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L454)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I'd rather tell here that this should be an independent job, that is maybe run periodically. Wdyt?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 556 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86_FIp8jq5CvZKS1E8:-O8DyKjW3yvxHQMw2lKw:b-oh7wt) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L556)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I wonder: `FileId` is `Copy` so why can't we just use `.copied()` iterator here?
</blockquote></details>

Done, good catch
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 647 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86_gAU6pRplE31e-B_:-O8DyG_B2g2nxzSSn1hZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L647)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

move this parameter further down, so that `db` comes first by convention
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 686 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O823Kr9BaGlezAHE14i:-O8Dy3Vx5U_RlHnSh73x:b2nhswv) ([raw file](https://github.com/starkware-libs/cairo/blob/e4136a412b03aff3ba1dec3eb8d8d22356cd67ae/crates/cairo-lang-language-server/src/lib.rs#L686)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

@Draggu moved them into the controller module
</blockquote></details>

Yep
___
*[`crates/cairo-lang-language-server/src/server/client.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O85ghAi3hGUZJFaIe1d:-O8DyimA0z6B5ZjG8ndV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/client.rs#L55)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

is this result used anywhere? can't we just log the error? this is making usage quite uglier (see `ScarbToolchain` changes)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/server/client.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O85gAgh5z8BmhBCWp9F:-O8Dyk0-6M2IXvengqml:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/client.rs#L151)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

etc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/server/connection.rs` line 3 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86-hVt4ubBpDkC-dPk:-O8DykwK6IxIpOajL17U:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/connection.rs#L3)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

This file is copied almost 1:1 from ruff, will change it
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/server/api/mod.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O861TM0BoS33zt2H71b:-O8DyukL09PmkkVVgLtr:b7r8ddj) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/api/mod.rs#L58)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

This isn't an anyhow error but this
```rs
pub(crate) struct LSPError {  
    pub(crate) code: ErrorCode,  
    pub(crate) error: anyhow::Error,  
}
```
</blockquote></details>

Done anyways.
___
*[`crates/cairo-lang-language-server/src/server/schedule/task.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O85f26W8vgU4WB4Frmq:-O8GzekL-rxfejRPNhaA:bo85t3s) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/schedule/task.rs#L19)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Sure
</blockquote></details>

Done, will add sources after everything looks good
___
*[`crates/cairo-lang-language-server/src/toolchain/scarb.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O864iNH2E2ZAq3Wew6j:-O8Dz0hq4DzNuymvn3pc:bbhnqj2) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/toolchain/scarb.rs#L59)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Logging now happens in `notify` method


<!-- Sent from Reviewable.io -->

2024-10-03 10:56 UTC, piotmag769 reviewed
> Reviewed 9 of 9 files at r6, all commit messages.
> Dismissed @Arcticae and @mkaput from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: all files reviewed, 16 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 367 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O82-pr68OsL8jGw3EQZ:-O8H-bAzAVoFvoz_aw8g:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L367)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Can we mark it with an issue number if it's not something we want to address here?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lsp/mod.rs` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O85eqkW1U1zqNRdsPrk:-O8H-IUP7658hTa_6rJC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lsp/mod.rs#L2)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

why is this becoming `pub`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-03 11:03 UTC, orizi approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: all files reviewed, 16 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)



<!-- Sent from Reviewable.io -->

2024-10-03 11:07 UTC, piotmag769 reviewed
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: all files reviewed, 16 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)



<!-- Sent from Reviewable.io -->

2024-10-03 12:40 UTC, Draggu reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: all files reviewed, 16 unresolved discussions (waiting on @Arcticae and @mkaput)

___
*[`crates/cairo-lang-language-server/src/state.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O8239gAA5NfdLo2Ncm-:-O8HMq1-24GuJxk_G0Ox:b-xmo2vu) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/state.rs#L82)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

If we remove them there is no point of our custom `Snapshot` struct even existing. I believe @Draggu wanted me to leave these to do some magic with diagnostics, but I am not sure if it is still relevant?
</blockquote></details>

Part of it will be used when changing way we calculate diagnostics. Please leave it as is now.
___
*[`crates/cairo-lang-language-server/src/lsp/controller.rs` line 102 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O824VNT5EGsmSC_UWvt:-O8HN1w02UVvaESaBN9s:b-95qoxh) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lsp/controller.rs#L102)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

@Draggu told me that he discussed it with @mkaput some time ago and that you told him this is the way it should be
</blockquote></details>

@mkaput actually we don't need to support this handler as we know on server when something should be canceled so returning `Ok` make sense here. We discussed this earlier and stated that this is not important.
___
*[`crates/cairo-lang-language-server/tests/e2e/support/mock_client.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O87X7rt7OYnO2gmm_EJ:-O8HNuB2AEnMVuDdC_Gj:buffmv8) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/tests/e2e/support/mock_client.rs#L56)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

```rs
pub struct JoinHandle<T = ()> { 
    // `inner` is an `Option` so that we can
    // take ownership of the contained `JoinHandle`. 
    inner: Option<jod_thread::JoinHandle<T>>,  
    allow_leak: bool,  
}
```
Don't think so, it should join itself on drop considering this struct has jod_thread's `JoinHandle`
</blockquote></details>

Yep, threads join on drop
___
*[`crates/cairo-lang-language-server/tests/e2e/support/mock_client.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O87X4osABketDdl3Z7J:-O8HNxfA4MFmDlv2-Yp4:bdeurg5) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/tests/e2e/support/mock_client.rs#L82)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

@Draggu ?
</blockquote></details>

Was required to pass assert that is commented out later but since we remove it anyway this should be possibly to remove.


<!-- Sent from Reviewable.io -->

2024-10-03 12:45 UTC, piotmag769 reviewed
> Dismissed @Arcticae and @mkaput from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: all files reviewed, 13 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/tests/e2e/support/mock_client.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O87X4osABketDdl3Z7J:-O8HP69w1uzPxWb48MM5:bhykix7) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/tests/e2e/support/mock_client.rs#L82)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Was required to pass assert that is commented out later but since we remove it anyway this should be possibly to remove.
</blockquote></details>

It is needed, without it tests fail


<!-- Sent from Reviewable.io -->

2024-10-03 13:59 UTC, piotmag769 reviewed
> Reviewed 9 of 9 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: all files reviewed, 14 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 143 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O82_jxb3OmArUDtVUXj:-O8HRlGV476acdPyld9e:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L143)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

you should set exit code here

spec: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#exit
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86WKt28jZCD_-0w2dU:-O8HR1lz3yZK1VeJP-Pf:b-1o9m6) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L244)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

why is this becoming `pub`? we want to limit amount of stuff that is publicly available from the crate

https://docs.rs/cairo-lang-language-server/latest/cairo_lang_language_server/
</blockquote></details>

Done, but it's ugly, probably can be refactored more, but I don't think it's worth it now
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 297 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86XNjZC9uWKqOvfO9N:-O8HT3PX7LJTA5RzwEIB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L297)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

shouldn't we close the connection always, regardless of what `Self::event_loop` returns?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 309 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O81ynUN08-QubOzQiqx:-O8HeE4o6n1G43n86UfM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L309)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

:+1:
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 322 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86Z2SM3Xq0KI1O3Dcf:-O8HeFK32JrXQ4Wy38BB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L322)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

please add a comment explaining why we are eagerly triggering this code path
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lsp/controller.rs` line  at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O868anE4vhlilYxSI9f:-O8Hf3yx5SRnC1fWRsQF:b-rg0d54) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lsp/controller.rs#L)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

It should be in `server.rs` to be fair, but I didn't want to move this in this PR, will be done in a separate one
</blockquote></details>

Moved to `api/traits.rs`


<!-- Sent from Reviewable.io -->

2024-10-03 14:23 UTC, piotmag769 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: all files reviewed, 14 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 317 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O820T794mh1mIa7CAPm:-O8HjT2OBfjCIaaYJQBm:b-f0xmbp) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L317)):*
>Is it happening before the whole handling loop?

It is not guaranteed that the response handler executes before every other request from client, but @Draggu investigated it and found no way to guarantee it.

>I think that's part of the `initalize` prodecure

Was previously done as a reaction to `initialized` notification, but do to the same way I would have to do it in `initialize_finish` which is quite inconvenient. It doesn't really matter that we do it here instead imo


<!-- Sent from Reviewable.io -->

2024-10-03 14:32 UTC, piotmag769 reviewed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: all files reviewed, 14 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)



<!-- Sent from Reviewable.io -->

2024-10-05 00:25 UTC, piotmag769 reviewed
> Reviewed 1 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: all files reviewed, 14 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lsp/controller.rs` line  at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O868anE4vhlilYxSI9f:-O8P2otd5IUofd-T_W86:b-dhp56h) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lsp/controller.rs#L)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Moved to `api/traits.rs`
</blockquote></details>

Now in `routing/traits.rs` and made the traits only visible in their super module
___
*[`crates/cairo-lang-language-server/src/server/api/mod.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O861FCj8iTfkYGOE-oR:-O8P11wt59KoXLHpUIZR:b2rd4cx) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/api/mod.rs#L21)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

this routing seems to be hidden quite deep in lsp implementation internals. shouldn't it be in `lib.rs` or somewhere nearby?
</blockquote></details>

I changed the module name to `routing` so now it is in the `server::routing`. I made the module private and did a pub re-export of the two functions

```rs
mod routing; 
pub use routing::{notification, request};
```
___
*[`crates/cairo-lang-language-server/src/server/api/mod.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O861nYV3PaAVxNGyAve:-O8P3CXC25nqMW0cWdsk:bglglrq) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/server/api/mod.rs#L64)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

same applies to this routing proc
</blockquote></details>

Vide supra


<!-- Sent from Reviewable.io -->

2024-10-05 00:31 UTC, piotmag769 reviewed
> Reviewed 1 of 2 files at r7, 12 of 12 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: all files reviewed, 15 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/server/api/mod.rs` line 195 at r10](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O8P4SDH-IMNMDXY3s3U:-O8P4SDH-IMNMDXY3s3V:b-r6zw67) ([raw file](https://github.com/starkware-libs/cairo/blob/45618a16fdef622c59438d352ce0f5c34cdda9e9/crates/cairo-lang-language-server/src/server/api/mod.rs#L195)):*
> ```XML
> }
> 
> pub(crate) struct LSPError {
> ```

Moved to `lsp/result.rs`


<!-- Sent from Reviewable.io -->

2024-10-05 01:02 UTC, piotmag769 reviewed
> Reviewed 11 of 11 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: all files reviewed, 16 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O8PBC0X9SraHQPPyzvZ:-O8PBC0X9SraHQPPyzv_:bspb36d) (no related file):*
Limited the visibility of items, generated new docs with `cargo doc` and compared with current live docs - nothing has changed

___


<!-- Sent from Reviewable.io -->

2024-10-08 18:17 UTC, piotmag769 reviewed
> Reviewed 11 of 11 files at r13, all commit messages.
> Dismissed @Arcticae from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: all files reviewed, 8 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86WKt28jZCD_-0w2dU:-O8hKyfwAQPQA41uAdB2:b-d2co0z) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L244)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

you can use a newtype wrapper which I think will be pretty clean

```rs
#[cfg(feature = "testing")]
pub struct BackendForTesting(Backend);

#[cfg(feature = "testing")]
impl BackendForTesting {
    pub fn new_for_testing(...) { ... }
}
```
</blockquote></details>

But then I lose the impl of other methods of `Backend`, so I have to duplicate a couple hundred lines of code
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 143 at r12](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O8fuURuB06Ri48UQWEz:-O8hJvepA891jhXnLvg_:b-3cg38o) ([raw file](https://github.com/starkware-libs/cairo/blob/71bd87cc5f90ddb5b0fab5078f91279554971ada/crates/cairo-lang-language-server/src/lib.rs#L143)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Prefer using [`ExitCode`](https://doc.rust-lang.org/stable/std/process/struct.ExitCode.html) instead of hardcoded numbers
</blockquote></details>

You still have to hardcode it since `ExitCode` returns platform specific exit codes for failure etc.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 155 at r12](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O8fuXBjAsC3calCyQUA:-O8hKh4kCJCeDicpL-gE:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/71bd87cc5f90ddb5b0fab5078f91279554971ada/crates/cairo-lang-language-server/src/lib.rs#L155)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

It's not totally safe to call `process::exit` (or related functions) from anywhere deeper in the codebase, as this might skip destructors, which may be expected to be called (like file locks). See relevant documentation: https://doc.rust-lang.org/stable/std/process/fn.exit.html

It's much better to return `ExitCode` from `start_*` functions and expect `main` functions to relay it back to Rust, like [this](https://doc.rust-lang.org/stable/std/process/struct.ExitCode.html#examples):

```rs
use std::process::ExitCode;

fn main() -> ExitCode {
    if !check_foo() {
        return ExitCode::from(42);
    }

    ExitCode::SUCCESS

```
</blockquote></details>

Done
___
*[`crates/cairo-lang-language-server/src/state.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O8239gAA5NfdLo2Ncm-:-O8hLJ8L9U16WD6vIH7r:b-bpb2cr) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/state.rs#L82)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Part of it will be used when changing way we calculate diagnostics. Please leave it as is now.
</blockquote></details>

Removed, discussed offline with @Draggu


<!-- Sent from Reviewable.io -->

2024-10-08 18:20 UTC, piotmag769 reviewed
> Reviewed 2 of 2 files at r14, all commit messages.
> Dismissed @Arcticae from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, and @mkaput)



<!-- Sent from Reviewable.io -->

2024-10-09 07:04 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431#-:-O8k5--d0owIMmr7nfDU:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae and @Draggu)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86WKt28jZCD_-0w2dU:-O8k48Lr5dKz3LAF_U5Y:b-8eymzc) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L244)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

But then I lose the impl of other methods of `Backend`, so I have to duplicate a couple hundred lines of code
</blockquote></details>

are you sure? as far as I see you only depend on `build_service_for_e2e_tests` in tests and everything else is private. or am I missing something right now?

nonetheless unblocking, we can solve this as separate task -- please make an issue for that


<!-- Sent from Reviewable.io -->

2024-10-09 08:46 UTC, mkaput approved these changes
> Dismissed @Arcticae from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)



<!-- Sent from Reviewable.io -->

2024-10-09 11:10 UTC, piotmag769 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: 61 of 62 files reviewed, all discussions resolved (waiting on @Arcticae and @mkaput)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O86WKt28jZCD_-0w2dU:-O8kuZIZ8TkxSht7w5GZ:bl9wfnc) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L244)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

are you sure? as far as I see you only depend on `build_service_for_e2e_tests` in tests and everything else is private. or am I missing something right now?

nonetheless unblocking, we can solve this as separate task -- please make an issue for that
</blockquote></details>

True, misread your code, done.
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 317 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O820T794mh1mIa7CAPm:-O8kvviFECMo0meqgyJH:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c88b6319b4f6bb7c5be3d52710952196532e659a/crates/cairo-lang-language-server/src/lib.rs#L317)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I think it's fine when you put this, but I think it's worth adding a comment that this is happening after processing `initialize` flow, which is being run in `Backend::new_inner`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-09 11:16 UTC, piotmag769 approved these changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)



<!-- Sent from Reviewable.io -->

2024-10-09 12:20 UTC, mkaput requested changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae and @Draggu)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 346 at r15](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O8lCpoIDyognlcVKy7v:-O8lCpoIDyognlcVKy7w:bvuv81o) ([raw file](https://github.com/starkware-libs/cairo/blob/c70f3e4ffe210901b1d375db29bd7cce6d3e4cc5/crates/cairo-lang-language-server/src/lib.rs#L346)):*
> ```XML
>         // `initialized` notification as it is more convenient implementation-wise.
>         // Ideally, we would wait for responses to these requests here instead of in the event loop,
>         // but we did not find a suitable way to do that.
> ```

`connection_initializer.initialize_finish(..)` which we call in `Backend::new` waits for the `initialized` notification, so actually this part is done correctly :upside_down_face: 

plz rephrase this comment so it's not misleading.


<!-- Sent from Reviewable.io -->

2024-10-11 06:37 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae and @mkaput)



<!-- Sent from Reviewable.io -->

2024-10-11 07:30 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431#-:-O8uU6-kEn1dfXMNgi8p:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 346 at r15](https://reviewable.io/reviews/starkware-libs/cairo/6431#-O8lCpoIDyognlcVKy7v:-O8uU5-j-jnkXPv4Y4q9:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/c70f3e4ffe210901b1d375db29bd7cce6d3e4cc5/crates/cairo-lang-language-server/src/lib.rs#L346)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

`connection_initializer.initialize_finish(..)` which we call in `Backend::new` waits for the `initialized` notification, so actually this part is done correctly :upside_down_face: 

plz rephrase this comment so it's not misleading.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-10-11 07:43 UTC, Draggu reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 21 of 61 files at r1, 7 of 26 files at r3, 1 of 10 files at r4, 4 of 7 files at r5, 5 of 9 files at r6, 2 of 2 files at r7, 4 of 4 files at r8, 3 of 12 files at r11, 3 of 11 files at r12, 10 of 11 files at r13, 1 of 2 files at r14, 1 of 1 files at r15, 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431#-:-O8uX1AlBjGtBnawOVYt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)



<!-- Sent from Reviewable.io -->

2024-10-11 09:27 UTC, mkaput approved these changes
> Reviewed 1 of 2 files at r16, 24 of 24 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)



<!-- Sent from Reviewable.io -->

2024-10-11 09:55 UTC, merged

2024-10-11 11:11 UTC, piotmag769 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r16, 24 of 24 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6431#-:-O8vF2oQA93alvHJcX1B:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->