fixed sort (use & mod) method in formatter
starkware-libs/cairo pull request #6438
Opened 2024-09-30 12:56 UTC by dean-starkware

2024-09-30 13:13 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @dean-starkware, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 828 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O822cro8kcAFz8Oyn5N:-O822cro8kcAFz8Oyn5O:bb7f2bf) ([raw file](https://github.com/starkware-libs/cairo/blob/d311d3bc5b9b9af7d3264ac412f1b78d747fd6a9/crates/cairo-lang-formatter/src/formatter_impl.rs#L828)):*
> ```XML
>     }
> 
>     fn sort_inner_use_paths_in_place(multi_path: &ast::UsePathMulti, db: &dyn SyntaxGroup) {
> ```

doc.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 863 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O822qaj0mObdWx7Zv0M:-O822qaj0mObdWx7Zv0N:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/d311d3bc5b9b9af7d3264ac412f1b78d747fd6a9/crates/cairo-lang-formatter/src/formatter_impl.rs#L863)):*
> ```XML
>     }
> 
>     fn sort_and_append_group<'b>(
> ```

doc
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 914 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8231vr81Qwi1bHr0Jr:-O8231vr81Qwi1bHr0Js:b-hfaq3o) ([raw file](https://github.com/starkware-libs/cairo/blob/d311d3bc5b9b9af7d3264ac412f1b78d747fd6a9/crates/cairo-lang-formatter/src/formatter_impl.rs#L914)):*
> ```XML
>         let allowed_empty_between = syntax_node.allowed_empty_between(self.db);
>         let internal_break_line_points_positions =
>             syntax_node.get_internal_break_line_point_properties(self.db);
> ```

if used only in branch - init in branch.



_Code quote:_
```XML
        let allowed_empty_between = syntax_node.allowed_empty_between(self.db);
        let internal_break_line_points_positions =
            syntax_node.get_internal_break_line_point_properties(self.db);
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 918 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O822vn30IuCX_azf5yP:-O822vn30IuCX_azf5yQ:b-z83ivf) ([raw file](https://github.com/starkware-libs/cairo/blob/d311d3bc5b9b9af7d3264ac412f1b78d747fd6a9/crates/cairo-lang-formatter/src/formatter_impl.rs#L918)):*
> ```XML
>         let n_children = children.len();
>         if self.config.sort_module_level_items {
>             let mut sorted_children = Vec::new();
> ```

extract to function.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1038 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O823BGS6u76W1VrVaHA:-O823BGS6u76W1VrVaHB:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/d311d3bc5b9b9af7d3264ac412f1b78d747fd6a9/crates/cairo-lang-formatter/src/formatter_impl.rs#L1038)):*
> ```XML
>             // Replace the children with the sorted result:
>             // children = sorted_children.into_iter().cloned().collect();
>             children.sort_by_key(|c| MovableNode::new(self.db, c));
> ```

?



_Code quote:_
```XML
            // Replace the children with the sorted result:
            // children = sorted_children.into_iter().cloned().collect();
            children.sort_by_key(|c| MovableNode::new(self.db, c));
```


<!-- Sent from Reviewable.io -->

2024-09-30 13:20 UTC, dean-starkware reviewed
It's not ready for review yet.
This is why there isn't any reviewer...
It's for debugging purposes only.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438#-:-O824UEQ6mhr6Mh-x7V0:b-dlyc4k)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-10-06 06:10 UTC, orizi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 0 of 11 files reviewed, 9 unresolved discussions (waiting on @Arcticae, @dean-starkware, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 830 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8VQv_u6AtY8QVST37B:-O8VQv_v-cfKSqTXI2TQ:bqm695f) ([raw file](https://github.com/starkware-libs/cairo/blob/2ec6d1894bb76b5d342d628d9e5c9378031a37e8/crates/cairo-lang-formatter/src/formatter_impl.rs#L830)):*
> ```XML
>             let mut start_idx = 0;
>             while start_idx < children.len() {
>                 let kind = Self::sort_kind(self.db, &children[start_idx]);
> ```

put non `self` receiving functions out of the `impl` or simply use `self.db` in the function, and call it as `self.sort_kind(&children[start_idx])`



_Code quote:_
```XML
                let kind = Self::sort_kind(self.db, &children[start_idx]);
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 891 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8VROQR5rDI8Y3YcrcQ:-O8VROQR5rDI8Y3YcrcR:b5xm7fz) ([raw file](https://github.com/starkware-libs/cairo/blob/2ec6d1894bb76b5d342d628d9e5c9378031a37e8/crates/cairo-lang-formatter/src/formatter_impl.rs#L891)):*
> ```XML
>     fn match_sort_kind(db: &dyn SyntaxGroup, node: &SyntaxNode, kind: SyntaxKind) -> bool {
>         node.kind(db) == kind
>     }
> ```

these are short and clear functions - inline.



_Code quote:_
```XML
    /// Determines the "kind" for sorting (e.g., mod, use)
    fn sort_kind(db: &dyn SyntaxGroup, node: &SyntaxNode) -> SyntaxKind {
        node.kind(db)
    }
    /// Matches the current node's kind with the given kind
    fn match_sort_kind(db: &dyn SyntaxGroup, node: &SyntaxNode, kind: SyntaxKind) -> bool {
        node.kind(db) == kind
    }
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 972 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8VRkEt3Izzd2haSoBD:-O8VRkEu-gAUZyiIrwFd:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2ec6d1894bb76b5d342d628d9e5c9378031a37e8/crates/cairo-lang-formatter/src/formatter_impl.rs#L972)):*
> ```XML
> 
> /// Represents a sortable SyntaxNode.
> #[derive(Debug, PartialEq, Eq, Clone)]
> ```





_Suggestion:_
```XML
/// Represents a sortable SyntaxNode.
#[derive(PartialEq, Eq)]
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 992 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8VRaI0DqogxcAf00Z-:-O8VRaI0DqogxcAf00Z0:b-ob61g3) ([raw file](https://github.com/starkware-libs/cairo/blob/2ec6d1894bb76b5d342d628d9e5c9378031a37e8/crates/cairo-lang-formatter/src/formatter_impl.rs#L992)):*
> ```XML
>             SyntaxKind::ItemUse => {
>                 // Step 1: Extract the text without trivia (whitespace/comments)
>                 let original_text: SmolStr = node.clone().get_text_without_trivia(db).into();
> ```

find the specific name node and sort by it.



_Code quote:_
```XML
                let original_text: SmolStr = node.clone().get_text_without_trivia(db).into();
```


<!-- Sent from Reviewable.io -->

2024-10-06 13:37 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 0 of 11 files reviewed, 9 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 828 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O822cro8kcAFz8Oyn5N:-O8X1tNs60Y_3cinKTvO:b-92jkou) ([raw file](https://github.com/starkware-libs/cairo/blob/d311d3bc5b9b9af7d3264ac412f1b78d747fd6a9/crates/cairo-lang-formatter/src/formatter_impl.rs#L828)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc.
</blockquote></details>

What exactly?
The append_break_line_point function?
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 863 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O822qaj0mObdWx7Zv0M:-O8X23kRBIxcE93Cq-TX:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/d311d3bc5b9b9af7d3264ac412f1b78d747fd6a9/crates/cairo-lang-formatter/src/formatter_impl.rs#L863)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

?
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1038 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O823BGS6u76W1VrVaHA:-O8X1SWo3jSnq0Bmozcz:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d311d3bc5b9b9af7d3264ac412f1b78d747fd6a9/crates/cairo-lang-formatter/src/formatter_impl.rs#L1038)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 830 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8VQv_u6AtY8QVST37B:-O8X1U6QAVy4910hqLrO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2ec6d1894bb76b5d342d628d9e5c9378031a37e8/crates/cairo-lang-formatter/src/formatter_impl.rs#L830)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

put non `self` receiving functions out of the `impl` or simply use `self.db` in the function, and call it as `self.sort_kind(&children[start_idx])`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 891 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8VROQR5rDI8Y3YcrcQ:-O8X1QvV7ILobUbMcUMb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2ec6d1894bb76b5d342d628d9e5c9378031a37e8/crates/cairo-lang-formatter/src/formatter_impl.rs#L891)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

these are short and clear functions - inline.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 972 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8VRkEt3Izzd2haSoBD:-O8X1Pj17eL16lN3P9X9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2ec6d1894bb76b5d342d628d9e5c9378031a37e8/crates/cairo-lang-formatter/src/formatter_impl.rs#L972)):*
> ```XML
> 
> /// Represents a sortable SyntaxNode.
> #[derive(Debug, PartialEq, Eq, Clone)]
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-10-06 13:58 UTC, dean-starkware reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438#-:-O8X6rHJ0cRULJ2IZbKv:bnfp4nl)* status: 0 of 11 files reviewed, 9 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)



<!-- Sent from Reviewable.io -->

2024-10-06 13:59 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 0 of 11 files reviewed, 9 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 914 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8231vr81Qwi1bHr0Jr:-O8X77EJ6ifJeeeh6WkP:b-qv33b9) ([raw file](https://github.com/starkware-libs/cairo/blob/d311d3bc5b9b9af7d3264ac412f1b78d747fd6a9/crates/cairo-lang-formatter/src/formatter_impl.rs#L914)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if used only in branch - init in branch.
</blockquote></details>

Don't understand what you mean here with "branch".
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 918 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O822vn30IuCX_azf5yP:-O8X6yNTDSWU3cBHt1YR:b-kdom69) ([raw file](https://github.com/starkware-libs/cairo/blob/d311d3bc5b9b9af7d3264ac412f1b78d747fd6a9/crates/cairo-lang-formatter/src/formatter_impl.rs#L918)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

extract to function.
</blockquote></details>

The partition to sections?
I.e. the while loop?


<!-- Sent from Reviewable.io -->

2024-10-06 14:05 UTC, orizi requested changes
> Reviewed 3 of 11 files at r1, 1 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 4 of 11 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @dean-starkware, @Draggu, @gilbens-starkware, and @mkaput)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 858 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8X7oWXDLAIDYNfWNZk:-O8X7oWXDLAIDYNfWNZl:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/73db5cd8caa75290e199bdaf38759787cc4caee5/crates/cairo-lang-formatter/src/formatter_impl.rs#L858)):*
> ```XML
>                         });
>                     }
>                     _ => {} // Do nothing for other cases
> ```





_Suggestion:_
```XML
                    _ => {}
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 862 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8X7viL9U4joZ8uzald:-O8X7viL9U4joZ8uzale:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/73db5cd8caa75290e199bdaf38759787cc4caee5/crates/cairo-lang-formatter/src/formatter_impl.rs#L862)):*
> ```XML
> 
>                 // Move to the next section
>                 start_idx = end_idx + 1;
> ```





_Suggestion:_
```XML
                // Move past the sorted section.
                start_idx = end_idx;
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 865 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8X8Bbi16Z-jwxgVP4L:-O8X8Bbi16Z-jwxgVP4M:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/73db5cd8caa75290e199bdaf38759787cc4caee5/crates/cairo-lang-formatter/src/formatter_impl.rs#L865)):*
> ```XML
>             }
>         }
>         // Format each child node
> ```


___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 960 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8X8Erc8ID0DuuIZoS3:-O8X8Erc8ID0DuuIZoS4:bcrrasx) ([raw file](https://github.com/starkware-libs/cairo/blob/73db5cd8caa75290e199bdaf38759787cc4caee5/crates/cairo-lang-formatter/src/formatter_impl.rs#L960)):*
> ```XML
> }
> 
> /// Represents a sortable section
> ```

fix doc.
addditionally - remember to always have a `.` at the end of sentences.



_Code quote:_
```XML
/// Represents a sortable section
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 966 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8X8QdGDnmzijlKWxF3:-O8X8QdGDnmzijlKWxF4:b-uwgbmk) ([raw file](https://github.com/starkware-libs/cairo/blob/73db5cd8caa75290e199bdaf38759787cc4caee5/crates/cairo-lang-formatter/src/formatter_impl.rs#L966)):*
> ```XML
>     UseItem,
>     Immovable,
> }
> ```

doc the variants.



_Code quote:_
```XML
enum SortKind {
    Module,
    UseItem,
    Immovable,
}
```
___
*[`crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt` line 36 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8X8Z2CCl1cx439zK5m:-O8X8Z2CCl1cx439zK5n:b-8i8cft) ([raw file](https://github.com/starkware-libs/cairo/blob/73db5cd8caa75290e199bdaf38759787cc4caee5/crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt#L36)):*
> ```help
> --------------------------
> Completion: add_eq()
> Insert text: add_eq($0)
> ```

probably rebase  - this shouldn't have changed.


<!-- Sent from Reviewable.io -->

2024-10-06 14:13 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 3 of 11 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 992 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8VRaI0DqogxcAf00Z-:-O8XAISjBhoECLZRWLaW:b9dr7j7) ([raw file](https://github.com/starkware-libs/cairo/blob/2ec6d1894bb76b5d342d628d9e5c9378031a37e8/crates/cairo-lang-formatter/src/formatter_impl.rs#L992)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

find the specific name node and sort by it.
</blockquote></details>

Do you mean spesifically to the ItemUse?
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 858 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8X7oWXDLAIDYNfWNZk:-O8X9IzEDuAlBs19_RlG:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/73db5cd8caa75290e199bdaf38759787cc4caee5/crates/cairo-lang-formatter/src/formatter_impl.rs#L858)):*
> ```XML
>                         });
>                     }
>                     _ => {} // Do nothing for other cases
> ```

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 862 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8X7viL9U4joZ8uzald:-O8X9IkHC8FyfQ0-RcnJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/73db5cd8caa75290e199bdaf38759787cc4caee5/crates/cairo-lang-formatter/src/formatter_impl.rs#L862)):*
> ```XML
> 
>                 // Move to the next section
>                 start_idx = end_idx + 1;
> ```

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 865 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8X8Bbi16Z-jwxgVP4L:-O8X9IZkB2IAYMYbf5Ks:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/73db5cd8caa75290e199bdaf38759787cc4caee5/crates/cairo-lang-formatter/src/formatter_impl.rs#L865)):*
> ```XML
>             }
>         }
>         // Format each child node
> ```

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 960 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8X8Erc8ID0DuuIZoS3:-O8X9SKx3qATbbVl6saf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/73db5cd8caa75290e199bdaf38759787cc4caee5/crates/cairo-lang-formatter/src/formatter_impl.rs#L960)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix doc.
addditionally - remember to always have a `.` at the end of sentences.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 966 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8X8QdGDnmzijlKWxF3:-O8X9nK-02fWdX06-7HT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/73db5cd8caa75290e199bdaf38759787cc4caee5/crates/cairo-lang-formatter/src/formatter_impl.rs#L966)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc the variants.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-06 14:15 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 3 of 11 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt` line 36 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8X8Z2CCl1cx439zK5m:-O8XAow19TjZnxVn4ogy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/73db5cd8caa75290e199bdaf38759787cc4caee5/crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt#L36)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

probably rebase  - this shouldn't have changed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-06 14:18 UTC, orizi requested changes
> Reviewed 1 of 11 files at r1, 1 of 2 files at r3, 5 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @dean-starkware, @Draggu, @gilbens-starkware, and @mkaput)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 992 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8VRaI0DqogxcAf00Z-:-O8XBJrp83VrZtPtkjNP:baxoicg) ([raw file](https://github.com/starkware-libs/cairo/blob/2ec6d1894bb76b5d342d628d9e5c9378031a37e8/crates/cairo-lang-formatter/src/formatter_impl.rs#L992)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

Do you mean spesifically to the ItemUse?
</blockquote></details>

no - relevant for the actual sorting.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 862 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8X7viL9U4joZ8uzald:-O8XAzDoA7MosZ-Cz-SN:bm5r6fq) ([raw file](https://github.com/starkware-libs/cairo/blob/73db5cd8caa75290e199bdaf38759787cc4caee5/crates/cairo-lang-formatter/src/formatter_impl.rs#L862)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not fully.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 960 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8X8Erc8ID0DuuIZoS3:-O8XB52y9cLMNQ_d4dNb:b7n04w) ([raw file](https://github.com/starkware-libs/cairo/blob/73db5cd8caa75290e199bdaf38759787cc4caee5/crates/cairo-lang-formatter/src/formatter_impl.rs#L960)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no it doesn't - what is the meaning of a `kind`?

make the variants doc match it as well.
___
*[`crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt` line 36 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8X8Z2CCl1cx439zK5m:-O8XBQp_ENho1_vf06OJ:blyl5jb) ([raw file](https://github.com/starkware-libs/cairo/blob/73db5cd8caa75290e199bdaf38759787cc4caee5/crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt#L36)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

still there.


<!-- Sent from Reviewable.io -->

2024-10-06 14:47 UTC, gilbens-starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: all files reviewed, 7 unresolved discussions (waiting on @Arcticae, @dean-starkware, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 832 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8XDq6B4rv0ohQXpEfX:-O8XDq6B4rv0ohQXpEfY:b-g30843) ([raw file](https://github.com/starkware-libs/cairo/blob/8d47c069fe103e0e8c0bd07d81a3dd834efa6bdf/crates/cairo-lang-formatter/src/formatter_impl.rs#L832)):*
> ```XML
>             let mut start_idx = 0;
>             while start_idx < children.len() {
>                 let kind = SortKind::new(self.db, &children[start_idx]);
> ```

Consider adding a function called `as_sort_kind` to the `SyntaxNodeFormat` trait, and add the logic of `SortKind::new` there. This will keep the formatter (almost) independent of syntax kind specific decisions.



_Code quote:_
```XML
SortKind::new(self.db, &children[start_idx]);
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 848 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8XErm82NRwvW6Gvqr8:-O8XErm82NRwvW6Gvqr9:b-sduw2p) ([raw file](https://github.com/starkware-libs/cairo/blob/8d47c069fe103e0e8c0bd07d81a3dd834efa6bdf/crates/cairo-lang-formatter/src/formatter_impl.rs#L848)):*
> ```XML
>                                 .name(self.db)
>                                 .text(self.db)
>                         });
> ```

Consider getting the comparison function from another helper function, either in the `SyntaxNodeFormat` trait (if it's a function getting a `SyntaxNode`, or from `impl SortKind` (if it's a function getting a `SortKind`)



_Code quote:_
```XML
                    SortKind::Module => {
                        children[start_idx..end_idx].sort_by_key(|node| {
                            ast::ItemModule::from_syntax_node(self.db, node.clone())
                                .name(self.db)
                                .text(self.db)
                        });
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 858 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8XCYK6C7KmsaDr1E8N:-O8XCYK6C7KmsaDr1E8O:b-3he83z) ([raw file](https://github.com/starkware-libs/cairo/blob/8d47c069fe103e0e8c0bd07d81a3dd834efa6bdf/crates/cairo-lang-formatter/src/formatter_impl.rs#L858)):*
> ```XML
>                         });
>                     }
>                     _ => {}
> ```

As any new non-immovable kind will need to be added here.



_Suggestion:_
```XML
Immovable => {}
```
___
*[`crates/cairo-lang-formatter/test_data/expected_results/sorted_mod_use.cairo` line 4 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8XC-MaESpjABNKcutH:-O8XC-Mb1NjhJblBBM3O:b-7n5ays) ([raw file](https://github.com/starkware-libs/cairo/blob/8d47c069fe103e0e8c0bd07d81a3dd834efa6bdf/crates/cairo-lang-formatter/test_data/expected_results/sorted_mod_use.cairo#L4)):*
> ```Cairo
> mod beta;
> mod gamma;
> mod zeta;
> ```

This isn't the expected result (`beta` shouldn't be here).



_Code quote:_
```Cairo
mod alpha;
mod beta;
mod gamma;
mod zeta;
```


<!-- Sent from Reviewable.io -->

2024-10-07 06:14 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 9 of 11 files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 992 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8VRaI0DqogxcAf00Z-:-O8_agDUEZNC8EQup-7H:boal6k8) ([raw file](https://github.com/starkware-libs/cairo/blob/2ec6d1894bb76b5d342d628d9e5c9378031a37e8/crates/cairo-lang-formatter/src/formatter_impl.rs#L992)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no - relevant for the actual sorting.
</blockquote></details>

I believe this should be a part of a different PR.  Please correct me if I'm wrong.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 862 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8X7viL9U4joZ8uzald:-O8__aZx3fH9svXKr2rt:b-m3hgsl) ([raw file](https://github.com/starkware-libs/cairo/blob/73db5cd8caa75290e199bdaf38759787cc4caee5/crates/cairo-lang-formatter/src/formatter_impl.rs#L862)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

not fully.
</blockquote></details>

Correct. My bad.
Now Done (hopefully).
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 960 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8X8Erc8ID0DuuIZoS3:-O8_aJ1x3tY2rgRuCBSg:b-4h3dvr) ([raw file](https://github.com/starkware-libs/cairo/blob/73db5cd8caa75290e199bdaf38759787cc4caee5/crates/cairo-lang-formatter/src/formatter_impl.rs#L960)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no it doesn't - what is the meaning of a `kind`?

make the variants doc match it as well.
</blockquote></details>

I agree we need to have a better doc here. But please help me understand what exactly you want me to mention here- should it be the motivation for creating this enum? Should it an explanation about the sifferent kinds of items we want to sort (i.e. mod, use)?
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 858 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8XCYK6C7KmsaDr1E8N:-O8__xAe0x6MgEmlL8XU:b-s2rc75) ([raw file](https://github.com/starkware-libs/cairo/blob/8d47c069fe103e0e8c0bd07d81a3dd834efa6bdf/crates/cairo-lang-formatter/src/formatter_impl.rs#L858)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

As any new non-immovable kind will need to be added here.
</blockquote></details>

Good point, thanks.
___
*[`crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt` line 36 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8X8Z2CCl1cx439zK5m:-O8_aqgz55VIWHgPzqMP:b-pyzydj) ([raw file](https://github.com/starkware-libs/cairo/blob/73db5cd8caa75290e199bdaf38759787cc4caee5/crates/cairo-lang-language-server/tests/test_data/completions/methods_text_edits.txt#L36)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

still there.
</blockquote></details>

Done. (?)


<!-- Sent from Reviewable.io -->

2024-10-07 06:19 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 8 of 11 files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-formatter/test_data/expected_results/sorted_mod_use.cairo` line 4 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8XC-MaESpjABNKcutH:-O8_cB6ACDTTDgDWOJ8T:btqm9d3) ([raw file](https://github.com/starkware-libs/cairo/blob/8d47c069fe103e0e8c0bd07d81a3dd834efa6bdf/crates/cairo-lang-formatter/test_data/expected_results/sorted_mod_use.cairo#L4)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

This isn't the expected result (`beta` shouldn't be here).
</blockquote></details>

You are completely right. I'm a total id**t.


<!-- Sent from Reviewable.io -->

2024-10-07 06:21 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 8 of 11 files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 848 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8XErm82NRwvW6Gvqr8:-O8_cswA8wxq-RrtiPwF:b-egwpq4) ([raw file](https://github.com/starkware-libs/cairo/blob/8d47c069fe103e0e8c0bd07d81a3dd834efa6bdf/crates/cairo-lang-formatter/src/formatter_impl.rs#L848)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Consider getting the comparison function from another helper function, either in the `SyntaxNodeFormat` trait (if it's a function getting a `SyntaxNode`, or from `impl SortKind` (if it's a function getting a `SortKind`)
</blockquote></details>

I thought about it, but believe that it should be a part of a different PR. Correct me if I'm wrong.


<!-- Sent from Reviewable.io -->

2024-10-07 06:23 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 8 of 11 files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 832 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8XDq6B4rv0ohQXpEfX:-O8_dDP00k8LEbzBwVSC:b15e7ac) ([raw file](https://github.com/starkware-libs/cairo/blob/8d47c069fe103e0e8c0bd07d81a3dd834efa6bdf/crates/cairo-lang-formatter/src/formatter_impl.rs#L832)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Consider adding a function called `as_sort_kind` to the `SyntaxNodeFormat` trait, and add the logic of `SortKind::new` there. This will keep the formatter (almost) independent of syntax kind specific decisions.
</blockquote></details>

I did it at first, but thought it's not really necessary and maybe the better way to do that is just write it inline (due to its short content). What do you think?


<!-- Sent from Reviewable.io -->

2024-10-07 06:34 UTC, orizi requested changes
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 9 of 11 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @dean-starkware, @Draggu, @gilbens-starkware, and @mkaput)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 992 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8VRaI0DqogxcAf00Z-:-O8_ewnn8NWHax3v_bs7:b16yutw) ([raw file](https://github.com/starkware-libs/cairo/blob/2ec6d1894bb76b5d342d628d9e5c9378031a37e8/crates/cairo-lang-formatter/src/formatter_impl.rs#L992)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

I believe this should be a part of a different PR.  Please correct me if I'm wrong.
</blockquote></details>

this comment was pointing at old code - this why it is resolved.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 960 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8X8Erc8ID0DuuIZoS3:-O8_ehFl-2Kf1PT1d4gX:bchi7dr) ([raw file](https://github.com/starkware-libs/cairo/blob/73db5cd8caa75290e199bdaf38759787cc4caee5/crates/cairo-lang-formatter/src/formatter_impl.rs#L960)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

I agree we need to have a better doc here. But please help me understand what exactly you want me to mention here- should it be the motivation for creating this enum? Should it an explanation about the sifferent kinds of items we want to sort (i.e. mod, use)?
</blockquote></details>

what is it? this does not represent a section at all - this represents the *kind* of section that we can sort.
doc should actually reflect that.


<!-- Sent from Reviewable.io -->

2024-10-07 06:34 UTC, orizi reviewed
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @dean-starkware, @Draggu, @gilbens-starkware, and @mkaput)



<!-- Sent from Reviewable.io -->

2024-10-07 07:06 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 9 of 11 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 992 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8VRaI0DqogxcAf00Z-:-O8_kpbU3EtGm5Duj12Z:b-46pn3n) ([raw file](https://github.com/starkware-libs/cairo/blob/2ec6d1894bb76b5d342d628d9e5c9378031a37e8/crates/cairo-lang-formatter/src/formatter_impl.rs#L992)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this comment was pointing at old code - this why it is resolved.
</blockquote></details>

I see it now. I'm not used to work with Reviewable so I didn't see it was marked as resolved.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 960 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8X8Erc8ID0DuuIZoS3:-O8_nAZ1ErGB3nGkoGOy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/73db5cd8caa75290e199bdaf38759787cc4caee5/crates/cairo-lang-formatter/src/formatter_impl.rs#L960)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what is it? this does not represent a section at all - this represents the *kind* of section that we can sort.
doc should actually reflect that.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-07 07:12 UTC, orizi requested changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @dean-starkware, @Draggu, @gilbens-starkware, and @mkaput)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 975 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8_np1pCiVf2IOtEvTY:-O8_np1pCiVf2IOtEvTZ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/506c1d0ea508aea490e3f503fd551263c7abea3b/crates/cairo-lang-formatter/src/formatter_impl.rs#L975)):*
> ```XML
>     /// This variant acts as a boundary, indicating that sorting should stop at this point.
>     Immovable,
> }
> ```





_Suggestion:_
```XML
/// Represents the kind of sections in the syntax tree that can be sorted.
/// Classify consecutive nodes into sections that are eligible for sorting.
#[derive(PartialEq, Eq)]
enum SortKind {
    /// Module items without body, e.g. `mod a;`.
    Module,
    /// Use items, e.g. `use a::b;` or `use c::{d, e as f};`.
    UseItem,
    /// Items that cannot be moved - would be skipped and not included in any sorted segment.
    Immovable,
}
```


<!-- Sent from Reviewable.io -->

2024-10-07 08:06 UTC, orizi approved these changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, and @mkaput)



<!-- Sent from Reviewable.io -->

2024-10-07 14:19 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @dean-starkware, @Draggu, @gilbens-starkware, and @mkaput)

___
*[`crates/cairo-lang-formatter/test_data/expected_results/sorted_mod_use.cairo` line 12 at r10](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8bLE6p5vTD-oGdRYR-:-O8bLE6p5vTD-oGdRYR0:b-792dqh) ([raw file](https://github.com/starkware-libs/cairo/blob/642d7960f415283252470cbff55d16c0c89e96ac/crates/cairo-lang-formatter/test_data/expected_results/sorted_mod_use.cairo#L12)):*
> ```Cairo
> 
> mod beta;
> use crate::utils::{a, b, c, d};
> ```

That seems like it is from a following PR


<!-- Sent from Reviewable.io -->

2024-10-07 16:10 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 9 of 11 files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-formatter/test_data/expected_results/sorted_mod_use.cairo` line 12 at r10](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8bLE6p5vTD-oGdRYR-:-O8bja4L9YhkX5n9wHyo:bf0g3n1) ([raw file](https://github.com/starkware-libs/cairo/blob/642d7960f415283252470cbff55d16c0c89e96ac/crates/cairo-lang-formatter/test_data/expected_results/sorted_mod_use.cairo#L12)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

That seems like it is from a following PR
</blockquote></details>

It was a part of this PR, but I agree that it should be a part of the following one.


<!-- Sent from Reviewable.io -->

2024-10-07 16:13 UTC, orizi approved these changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, and @mkaput)



<!-- Sent from Reviewable.io -->

2024-10-08 06:51 UTC, gilbens-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438#-:-O8etPN86Q5UE6V0-T2a:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @dean-starkware, @Draggu, and @mkaput)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 832 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8XDq6B4rv0ohQXpEfX:-O8et7ba5TnIoeoGdwdS:bni72di) ([raw file](https://github.com/starkware-libs/cairo/blob/8d47c069fe103e0e8c0bd07d81a3dd834efa6bdf/crates/cairo-lang-formatter/src/formatter_impl.rs#L832)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

I did it at first, but thought it's not really necessary and maybe the better way to do that is just write it inline (due to its short content). What do you think?
</blockquote></details>

Still, i'd move it, it'll be easier in the future to add stuff.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 848 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8XErm82NRwvW6Gvqr8:-O8etDTUDvOm4OMRX6Qn:bqqnoai) ([raw file](https://github.com/starkware-libs/cairo/blob/8d47c069fe103e0e8c0bd07d81a3dd834efa6bdf/crates/cairo-lang-formatter/src/formatter_impl.rs#L848)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

I thought about it, but believe that it should be a part of a different PR. Correct me if I'm wrong.
</blockquote></details>

Another PR is fine.
___
*[`crates/cairo-lang-formatter/test_data/expected_results/sorted_mod_use.cairo` line 4 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8XC-MaESpjABNKcutH:-O8etJpHCEsnyJ1c7Lr9:bdcferb) ([raw file](https://github.com/starkware-libs/cairo/blob/8d47c069fe103e0e8c0bd07d81a3dd834efa6bdf/crates/cairo-lang-formatter/test_data/expected_results/sorted_mod_use.cairo#L4)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

You are completely right. I'm a total id**t.
</blockquote></details>

A bit harsh...


<!-- Sent from Reviewable.io -->

2024-10-08 08:20 UTC, mkaput approved these changes
> Reviewed 1 of 11 files at r1, 1 of 2 files at r3, 5 of 6 files at r4, 1 of 2 files at r6, 1 of 1 files at r9, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @dean-starkware, and @Draggu)



<!-- Sent from Reviewable.io -->

2024-10-08 08:20 UTC, mkaput approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @dean-starkware, and @Draggu)



<!-- Sent from Reviewable.io -->

2024-10-08 14:05 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 832 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8XDq6B4rv0ohQXpEfX:-O8gRi6L7tmrpLIpFmMw:b-ltl0lc) ([raw file](https://github.com/starkware-libs/cairo/blob/8d47c069fe103e0e8c0bd07d81a3dd834efa6bdf/crates/cairo-lang-formatter/src/formatter_impl.rs#L832)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Still, i'd move it, it'll be easier in the future to add stuff.
</blockquote></details>

Tell me if it's okay now.


<!-- Sent from Reviewable.io -->

2024-10-08 15:43 UTC, orizi approved these changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, and @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2024-10-09 07:04 UTC, orizi approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @dean-starkware, @Draggu, and @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2024-10-09 07:25 UTC, orizi approved these changes
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @dean-starkware, @Draggu, and @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2024-10-09 08:12 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/test_data/expected_results/sorted_mod_use.cairo` line 4 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8XC-MaESpjABNKcutH:-O8kKNMv4TmIsvdncLkx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/8d47c069fe103e0e8c0bd07d81a3dd834efa6bdf/crates/cairo-lang-formatter/test_data/expected_results/sorted_mod_use.cairo#L4)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

A bit harsh...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-09 08:29 UTC, gilbens-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @dean-starkware, and @Draggu)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 838 at r16](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8kORZo80TP096KZB3X:-O8kORZo80TP096KZB3Y:b-rip8q) ([raw file](https://github.com/starkware-libs/cairo/blob/20503339d60cb0b25cbe6fb4fa553dd6a17f27f5/crates/cairo-lang-formatter/src/formatter_impl.rs#L838)):*
> ```XML
>                 // Find the end of the current section.
>                 while end_idx < children.len() {
>                     if kind != SortKind::new(self.db, &children[end_idx]) {
> ```

use `as_sort_kind`



_Code quote:_
```XML
 SortKind::new(self.db, &children[end_idx])
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 989 at r16](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8kOOMrERbZpzhVcTAb:-O8kOOMrERbZpzhVcTAc:byp18fd) ([raw file](https://github.com/starkware-libs/cairo/blob/20503339d60cb0b25cbe6fb4fa553dd6a17f27f5/crates/cairo-lang-formatter/src/formatter_impl.rs#L989)):*
> ```XML
>         }
>     }
> }
> ```

Remove



_Code quote:_
```XML
impl SortKind {
    fn new(db: &dyn SyntaxGroup, node: &SyntaxNode) -> Self {
        match node.kind(db) {
            SyntaxKind::ItemModule => {
                let item = ast::ItemModule::from_syntax_node(db, node.clone());
                if matches!(item.body(db), MaybeModuleBody::None(_)) {
                    Self::Module
                } else {
                    Self::Immovable
                }
            }
            SyntaxKind::ItemUse => Self::UseItem,
            _ => Self::Immovable,
        }
    }
}
```


<!-- Sent from Reviewable.io -->

2024-10-09 08:47 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 838 at r16](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8kORZo80TP096KZB3X:-O8kSM3a3ZYjb4Pf_wyL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/20503339d60cb0b25cbe6fb4fa553dd6a17f27f5/crates/cairo-lang-formatter/src/formatter_impl.rs#L838)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

use `as_sort_kind`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 989 at r16](https://reviewable.io/reviews/starkware-libs/cairo/6438#-O8kOOMrERbZpzhVcTAb:-O8kSLjV1SIFTHGF1JQ1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/20503339d60cb0b25cbe6fb4fa553dd6a17f27f5/crates/cairo-lang-formatter/src/formatter_impl.rs#L989)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-09 09:45 UTC, gilbens-starkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6438)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)



<!-- Sent from Reviewable.io -->

2024-10-09 10:11 UTC, merged