feat(profiler): allow to preserve original stack trace order
starkware-libs/cairo pull request #6441
Opened 2024-09-30 14:41 UTC by m-kus

This PR allows to preserve the original order of the stack trace as opposed to the current approach when items are sorted by weight (and stack entry).

Backwards compatible.

2024-10-06 08:51 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6441#-:-O8W0kol2qrGAlx7tePw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @m-kus)



<!-- Sent from Reviewable.io -->

2024-10-07 06:41 UTC, orizi approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6441)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @m-kus)



<!-- Sent from Reviewable.io -->

2024-10-07 06:42 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6441)* status: all files reviewed, 1 unresolved discussion (waiting on @m-kus)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6441#-O8_hgN4DFNbd3MIQzx2:-O8_hgN4DFNbd3MIQzx3:b-2pfjt5) (no related file):*
why is this required?

___


<!-- Sent from Reviewable.io -->

2024-10-07 09:22 UTC, m-kus reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6441)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6441#-O8_hgN4DFNbd3MIQzx2:-O8aGByS9_smxblY8saz:b-x2icwg) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is this required?
</blockquote></details>

It is useful to be able to iterate through the stack trace in the execution order both for troubleshooting and post-processing purposes. In particular I need this to be able to collapse loops (and recursive calls in general) which make flame charts hard to analyze.

If you mean the most recent push, that was clippy fix + rebase.

___


<!-- Sent from Reviewable.io -->

2024-10-07 12:33 UTC, orizi approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6441)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @m-kus)



<!-- Sent from Reviewable.io -->

2024-10-07 12:43 UTC, merged