LS: Fix duplicated and misplaced diagnostics
starkware-libs/cairo pull request #6446
Opened 2024-10-01 17:26 UTC by Arcticae

The diagnostics were not sorted properly, because of lack of including their kind in sorting before deduplication
(`.format()` is a derivative of that)

Also added a check for file relevance, so that vfs-based diagnostics aren't included in the mapping phase

2024-10-02 06:09 UTC, mkaput requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6446)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-diagnostics/src/diagnostics.rs` line 335 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6446#-O8ApxiMAhCmzw42cZHv:-O8ApxiNA7Gkr7udaLVF:b-4n6fe7) ([raw file](https://github.com/starkware-libs/cairo/blob/ce865eaa7a0e1eb31585205d51d32fce2860933d/crates/cairo-lang-diagnostics/src/diagnostics.rs#L335)):*
> ```XML
>         let files_db = db.upcast();
>         let mut indexed_dup_diagnostic =
>             diagnostic_with_dup.iter().enumerate().sorted_by_key(|(idx, diag)| {
> ```

if you're opting for heavy weapons here, then consider using https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.sorted_by_cached_key0


<!-- Sent from Reviewable.io -->

2024-10-02 13:17 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6446#-:-O8CNCkT4kWugP6sZBk3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu, @orizi, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-10-04 12:23 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6446#-:-O8MTwVa6EXBqcrVIHxr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @piotmag769)



<!-- Sent from Reviewable.io -->

2024-10-04 16:24 UTC, piotmag769 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6446#-:-O8NKOKV9bTMUmWhZnjv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae)



<!-- Sent from Reviewable.io -->

2024-10-04 16:44 UTC, merged