dean/formatter sort inner use
starkware-libs/cairo pull request #6467
Opened 2024-10-08 10:35 UTC by dean-starkware

2024-10-08 12:18 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @gilbens-starkware, @mkaput, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8frslL3yGIYvxxteQ_:-O8g3Bcv7Urhk1KdXm12:b-4s1lih) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Quite a lot of unrelated (to me) changes is going on here. Can you please fill issue title & description and outline what are you changing, please?
</blockquote></details>

In this pull request, we implemented sorting of the inner paths of `use` statements. Specifically, we now handle cases like `use a::{a, b, c}`, where the items inside the braces are sorted alphabetically. This ensures a consistent and readable structure for `use` paths across the codebase.

___


<!-- Sent from Reviewable.io -->

2024-10-08 12:27 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @dean-starkware, @Draggu, @gilbens-starkware, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8frslL3yGIYvxxteQ_:-O8g5DevCexXH-nr1-Oo:b-n8arh9) (no related file):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

In this pull request, we implemented sorting of the inner paths of `use` statements. Specifically, we now handle cases like `use a::{a, b, c}`, where the items inside the braces are sorted alphabetically. This ensures a consistent and readable structure for `use` paths across the codebase.
</blockquote></details>

1. Please put this description in PR description & update title so that the commit that will land on `main` will make sense
2. Why is this touching LS (and thus asking my team for review) then?

___


<!-- Sent from Reviewable.io -->

2024-10-08 13:14 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @dean-starkware, @Draggu, @gilbens-starkware, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8gFrWnAVN0FMGqGAUZ:-O8gFrWnAVN0FMGqGAU_:bb9918m) (no related file):*
rebase PR to be into the other branch - to avoid irrelevant changes.

___
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 831 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8gFi4U12My3bgDOInw:-O8gFi4U12My3bgDOInx:b-wgv4fz) ([raw file](https://github.com/starkware-libs/cairo/blob/db7d88d3da733f412b502ec8a0fd4cf267114182/crates/cairo-lang-formatter/src/formatter_impl.rs#L831)):*
> ```XML
>         // or UsePathLeaf.
>         if self.config.sort_module_level_items {
>             // We sort the inner path segments of the UsePathMulti node.
> ```

use functions please.


<!-- Sent from Reviewable.io -->

2024-10-09 11:02 UTC, dean-starkware commented
In this PR, we implemented sorting of the inner paths of use statements. Specifically, we now handle cases like use a::{a, b, c}, where the items inside the braces are sorted alphabetically. This ensures a consistent and readable structure for use paths across the codebase.

2024-10-09 11:42 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 0 of 14 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 831 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8gFi4U12My3bgDOInw:-O8l4URt1XiFSPID2qs-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/db7d88d3da733f412b502ec8a0fd4cf267114182/crates/cairo-lang-formatter/src/formatter_impl.rs#L831)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use functions please.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-09 12:09 UTC, orizi requested changes
> Reviewed 1 of 12 files at r1, 1 of 2 files at r3, 3 of 4 files at r4, 3 of 5 files at r5, 2 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 10 of 14 files reviewed, 7 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 853 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8l8oxJ5MF2MJfav_v-:-O8l8oxJ5MF2MJfav_v0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b8b7f565da3eecf7559e0e1f1e39564a7791fdea/crates/cairo-lang-formatter/src/formatter_impl.rs#L853)):*
> ```XML
>     }
>     // Sorting function for UsePathMulti.
>     fn sort_inner_use_path(&self, children: &mut Vec<SyntaxNode>) {
> ```





_Suggestion:_
```XML
    }
    
    /// Sorting function for `UsePathMulti` children.
    fn sort_inner_use_path(&self, children: &mut Vec<SyntaxNode>) {
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 884 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8l9etxA_3c9ywRmlCX:-O8l9etxA_3c9ywRmlCY:b-f4blun) ([raw file](https://github.com/starkware-libs/cairo/blob/b8b7f565da3eecf7559e0e1f1e39564a7791fdea/crates/cairo-lang-formatter/src/formatter_impl.rs#L884)):*
> ```XML
>         });
> 
>         // Filter and collect the other node types (like commas).
> ```

also test what happens with extra comments.



_Suggestion:_
```XML
        // Filter and collect the other node types (specifically commas).
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 908 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8l9BAt2Mx-9tO9jFtR:-O8l9BAt2Mx-9tO9jFtS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b8b7f565da3eecf7559e0e1f1e39564a7791fdea/crates/cairo-lang-formatter/src/formatter_impl.rs#L908)):*
> ```XML
>     }
> 
>     // Sorting function for module-level items.
> ```





_Suggestion:_
```XML
    /// Sorting function for module-level items.
```
___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 285 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8l8f_j3bz8yYs2J0tC:-O8l8f_k6CypNbcHGDNt:b-lzepp2) ([raw file](https://github.com/starkware-libs/cairo/blob/b8b7f565da3eecf7559e0e1f1e39564a7791fdea/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L285)):*
> ```XML
>         label: format!("{}()", name),
>         insert_text: Some(format!("{}($0)", name)),
>         insert_text_format: Some(tower_lsp::lsp_types::InsertTextFormat::SNIPPET),
> ```

rebase - not part of the PR.


<!-- Sent from Reviewable.io -->

2024-10-09 12:33 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 10 of 14 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 853 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8l8oxJ5MF2MJfav_v-:-O8lFsYa5ja7kNGp5p3K:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b8b7f565da3eecf7559e0e1f1e39564a7791fdea/crates/cairo-lang-formatter/src/formatter_impl.rs#L853)):*
> ```XML
>     }
>     // Sorting function for UsePathMulti.
>     fn sort_inner_use_path(&self, children: &mut Vec<SyntaxNode>) {
> ```

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 908 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8l9BAt2Mx-9tO9jFtR:-O8lFcxDDqo7t_yFEaBF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b8b7f565da3eecf7559e0e1f1e39564a7791fdea/crates/cairo-lang-formatter/src/formatter_impl.rs#L908)):*
> ```XML
>     }
> 
>     // Sorting function for module-level items.
> ```

Done.
___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 285 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8l8f_j3bz8yYs2J0tC:-O8lFZiz3DfEcpnxlUvW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b8b7f565da3eecf7559e0e1f1e39564a7791fdea/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L285)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

rebase - not part of the PR.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-09 12:39 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 10 of 14 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 884 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8l9etxA_3c9ywRmlCX:-O8lHXdJ9AT8VJj7XUyX:b-jobw8m) ([raw file](https://github.com/starkware-libs/cairo/blob/b8b7f565da3eecf7559e0e1f1e39564a7791fdea/crates/cairo-lang-formatter/src/formatter_impl.rs#L884)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

Do you mean something like that:
use a::{d, b/**/, /**/a, c};
</blockquote></details>

use a::{d, b/\*\*/, /\*\*/a, c};


<!-- Sent from Reviewable.io -->

2024-10-09 13:11 UTC, orizi requested changes
> Reviewed 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 3 of 16 files reviewed, 4 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 884 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8l9etxA_3c9ywRmlCX:-O8lP1sY2GrdKqiL9dOe:b-yonhax) ([raw file](https://github.com/starkware-libs/cairo/blob/b8b7f565da3eecf7559e0e1f1e39564a7791fdea/crates/cairo-lang-formatter/src/formatter_impl.rs#L884)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

use a::{d, b/\*\*/, /\*\*/a, c};
</blockquote></details>

yes - but in the tests.
___
*[`crates/cairo-lang-language-server/src/ide/completion/completions.rs` line 285 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8l8f_j3bz8yYs2J0tC:-O8lOt9ZD67b1_V42poV:b2t3i1j) ([raw file](https://github.com/starkware-libs/cairo/blob/b8b7f565da3eecf7559e0e1f1e39564a7791fdea/crates/cairo-lang-language-server/src/ide/completion/completions.rs#L285)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

i still see a change from base.


<!-- Sent from Reviewable.io -->

2024-10-09 13:23 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 3 of 16 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 884 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8l9etxA_3c9ywRmlCX:-O8lRhO68BHfsEI-Sskv:bvgfc1b) ([raw file](https://github.com/starkware-libs/cairo/blob/b8b7f565da3eecf7559e0e1f1e39564a7791fdea/crates/cairo-lang-formatter/src/formatter_impl.rs#L884)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

yes - but in the tests.
</blockquote></details>

Are you sure this is possible? I don't think the parser allows that.


<!-- Sent from Reviewable.io -->

2024-10-09 13:30 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 3 of 17 files reviewed, 5 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`-- commits` line 2 at r11](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8lSyUD3Cr_MLa23c4Q):*
broke again.

make sure to fix your local copy to have exactly one commit over `origin/main`.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 884 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8l9etxA_3c9ywRmlCX:-O8lT7dW69t7InJbp62U:btadalo) ([raw file](https://github.com/starkware-libs/cairo/blob/b8b7f565da3eecf7559e0e1f1e39564a7791fdea/crates/cairo-lang-formatter/src/formatter_impl.rs#L884)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

Are you sure this is possible? I don't think the parser allows that.
</blockquote></details>

why not?
```
use a::{
   d,
   b // some comment.
   ,  // some comment.
  a, c
};
```


<!-- Sent from Reviewable.io -->

2024-10-09 13:31 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 3 of 17 files reviewed, 5 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`-- commits` line 2 at r11](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8lSyUD3Cr_MLa23c4Q):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

broke again.

make sure to fix your local copy to have exactly one commit over `origin/main`.
</blockquote></details>

Yes, I'm on it.


<!-- Sent from Reviewable.io -->

2024-10-09 13:50 UTC, orizi reviewed
> Reviewed 1 of 14 files at r12, 6 of 7 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 16 of 17 files reviewed, 3 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2024-10-09 14:02 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 16 of 17 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 884 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8l9etxA_3c9ywRmlCX:-O8l_YHbBolXgHLdOaTN:bu4yxnh) ([raw file](https://github.com/starkware-libs/cairo/blob/b8b7f565da3eecf7559e0e1f1e39564a7791fdea/crates/cairo-lang-formatter/src/formatter_impl.rs#L884)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why not?
```
use a::{
   d,
   b // some comment.
   ,  // some comment.
  a, c
};
```
</blockquote></details>

Yes, it works just fine.


<!-- Sent from Reviewable.io -->

2024-10-09 14:56 UTC, orizi requested changes
> Reviewed 1 of 7 files at r15.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: all files reviewed, 2 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 884 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8l9etxA_3c9ywRmlCX:-O8lm-HD57w4meDXcaWb:bvu8u2d) ([raw file](https://github.com/starkware-libs/cairo/blob/b8b7f565da3eecf7559e0e1f1e39564a7791fdea/crates/cairo-lang-formatter/src/formatter_impl.rs#L884)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

Yes, it works just fine.
</blockquote></details>

have it in the tests.


<!-- Sent from Reviewable.io -->

2024-10-13 06:52 UTC, orizi requested changes
> Reviewed 2 of 8 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 12 of 18 files reviewed, 4 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 884 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8l9etxA_3c9ywRmlCX:-O93WN6540DvjaVFLfdf:bhggco) ([raw file](https://github.com/starkware-libs/cairo/blob/b8b7f565da3eecf7559e0e1f1e39564a7791fdea/crates/cairo-lang-formatter/src/formatter_impl.rs#L884)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

We decided not to deal with comments within the inner use, so it was not added.
</blockquote></details>

add a test it is ignored.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 864 at r19](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O93ddeiE_-RgWwzqBqZ:-O93ddeiE_-RgWwzqBq_:b-map51s) ([raw file](https://github.com/starkware-libs/cairo/blob/2701fa7da9a83d14084a00c0830705352105b7de/crates/cairo-lang-formatter/src/formatter_impl.rs#L864)):*
> ```XML
> 
>         // Sort the filtered nodes by their ident (text).
>         sorted_leaf_and_single.sort_by_key(|node| {
> ```

apply recursive comparison here as well.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 923 at r19](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O93dZRW5wdP-bt3_fpv:-O93dZRXDm4FdMXE8TfH:biyiz3e) ([raw file](https://github.com/starkware-libs/cairo/blob/2701fa7da9a83d14084a00c0830705352105b7de/crates/cairo-lang-formatter/src/formatter_impl.rs#L923)):*
> ```XML
>                     children[start_idx..end_idx].sort_by(|first_node, second_node| {
>                         let mut first_path = Some(
>                             ast::ItemUse::from_syntax_node(self.db, first_node.clone())
> ```

refactor as discussed f2f.


<!-- Sent from Reviewable.io -->

2024-10-13 07:39 UTC, orizi requested changes
> Reviewed 3 of 8 files at r19, 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 15 of 18 files reviewed, 5 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`Cargo.lock` line 1 at r20](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O93o9F_5p3yOg1n64uw:-O93o9Fa9GNW9PDUorlj:b-4eof09) ([raw file](https://github.com/starkware-libs/cairo/blob/ed191253a6452eeed96288d46a0bf7eb444712d2/Cargo.lock#L1)):*
> ```TOML
> # This file is automatically @generated by Cargo.
> ```

you probably ran a `cargo update` or something - please revert (as this is not a toml updating PR)


<!-- Sent from Reviewable.io -->

2024-10-14 06:26 UTC, mkaput reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 15 of 18 files reviewed, 4 unresolved discussions (waiting on @dean-starkware, @gilbens-starkware, and @orizi)



<!-- Sent from Reviewable.io -->

2024-10-14 06:27 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 15 of 18 files reviewed, 4 unresolved discussions (waiting on @dean-starkware, @gilbens-starkware, and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O8frslL3yGIYvxxteQ_:-O98hESC1sMoKym1LyUy:bd8zfj6) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

1. Please put this description in PR description & update title so that the commit that will land on `main` will make sense
2. Why is this touching LS (and thus asking my team for review) then?
</blockquote></details>

ACK, but it'd be much better to put this description in the **PR description** field, so that this text will land in the commit that will land on main :wink: 

___


<!-- Sent from Reviewable.io -->

2024-10-14 06:28 UTC, mkaput approved these changes
> Reviewed 2 of 14 files at r12, 2 of 7 files at r15.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 15 of 18 files reviewed, 4 unresolved discussions (waiting on @dean-starkware, @gilbens-starkware, and @orizi)



<!-- Sent from Reviewable.io -->

2024-10-14 09:41 UTC, orizi reviewed
> Reviewed 3 of 8 files at r19.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: all files reviewed, 4 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2024-10-15 14:12 UTC, orizi requested changes
> Reviewed 3 of 4 files at r21.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 16 of 18 files reviewed, 10 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 872 at r21](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9FR0rt7LY6RXfbNXzi:-O9FR0ruBhN5r2eECzx_:bwojfcg) ([raw file](https://github.com/starkware-libs/cairo/blob/cc856182819d2a6f8a617a583d4caa50d5c76565/crates/cairo-lang-formatter/src/formatter_impl.rs#L872)):*
> ```XML
>             let a_use_path = match extract_use_path(a_node, self.db) {
>                 Some(path) => path,
>                 None => return Ordering::Equal,
> ```

why `Equal`?



_Code quote:_
```XML
                None => return Ordering::Equal,
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 879 at r21](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9FRG8y3YXKkBnM8WVV:-O9FRG8y3YXKkBnM8WVW:b-nlutic) ([raw file](https://github.com/starkware-libs/cairo/blob/cc856182819d2a6f8a617a583d4caa50d5c76565/crates/cairo-lang-formatter/src/formatter_impl.rs#L879)):*
> ```XML
>                 None => return Ordering::Equal,
>             };
>             compare_use_paths(&a_use_path, &b_use_path, self.db)
> ```

maybe?



_Suggestion:_
```XML
            match (extract_use_path(a_node, self.db), extract_use_path(b_node, self.db)) {
                (None, None) => Ordering::Equal,
                (None, Some(_)) => Ordering::Less,
                (Some(_), None) => Ordering::Grater,
                (Some(a_path), Some(b_path)) => compare_use_paths(&a_path, &b_path, self.db),
            }
            
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 927 at r21](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9FS-Zk5vJA1KuZ1IdF:-O9FS-Zk5vJA1KuZ1IdG:b-l159rv) ([raw file](https://github.com/starkware-libs/cairo/blob/cc856182819d2a6f8a617a583d4caa50d5c76565/crates/cairo-lang-formatter/src/formatter_impl.rs#L927)):*
> ```XML
>                         let b =
>                             ast::ItemUse::from_syntax_node(self.db, b.clone()).use_path(self.db);
>                         compare_use_paths(&a, &b, self.db)
> ```

probably just inline `a` and `b`.



_Code quote:_
```XML
 compare_use_paths(&a, &b, self.db)
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1052 at r21](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9FT_EJ9HZmILaM9zec:-O9FT_EJ9HZmILaM9zed:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cc856182819d2a6f8a617a583d4caa50d5c76565/crates/cairo-lang-formatter/src/formatter_impl.rs#L1052)):*
> ```XML
>         (UsePath::Leaf(a_leaf), UsePath::Single(b_single)) => {
>             let a_str = extract_ident(a_leaf, db);
>             let b_str = extract_ident(b_single, db);
> ```





_Suggestion:_
```XML
            let a_str = a_leaf.ident(db).as_syntax_node().get_text_without_trivia(db);
            let b_str = b_single.ident(db).as_syntax_node().get_text_without_trivia(db);
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1064 at r21](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9FTkR38zWw_yoZilFU:-O9FTkR38zWw_yoZilFV:b3ov3zo) ([raw file](https://github.com/starkware-libs/cairo/blob/cc856182819d2a6f8a617a583d4caa50d5c76565/crates/cairo-lang-formatter/src/formatter_impl.rs#L1064)):*
> ```XML
>         (UsePath::Single(a_single), UsePath::Leaf(b_leaf)) => {
>             let a_str = extract_ident(a_single, db);
>             let b_str = extract_ident(b_leaf, db);
> ```

and later as well.



_Suggestion:_
```XML
            let a_str = a_single.ident(db).as_syntax_node().get_text_without_trivia(db);
            let b_str = b_leaf.ident(db).as_syntax_node().get_text_without_trivia(db);
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1077 at r21](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9FTx17BjK_jDHjV9it:-O9FTx17BjK_jDHjV9iu:bw61elo) ([raw file](https://github.com/starkware-libs/cairo/blob/cc856182819d2a6f8a617a583d4caa50d5c76565/crates/cairo-lang-formatter/src/formatter_impl.rs#L1077)):*
> ```XML
>             let a_str = extract_ident(a_leaf, db);
>             let b_str = extract_ident(b_leaf, db);
>             a_str.cmp(&b_str)
> ```

fix tie break as well.
and add tests.



_Suggestion:_
```XML
            match a_leaf.extract_ident(db).cmp(&b_leaf.extract_ident(db)) {
                Ordering::Equal => match (a_leaf.alias_clause(db), b_leaf.alias_clause(db)) {
                    (OptionAliasClause::Empty(_), OptionAliasClause::Empty(_)) => Ordering::Equal,
                    (OptionAliasClause::Empty(_), OptionAliasClause::AliasClause(_)) => Ordering::Less,
                    (OptionAliasClause::AliasClause(_), OptionAliasClause::Empty(_)) => Ordering::Greater,
                    (OptionAliasClause::AliasClause(a_alias), OptionAliasClause::AliasClause(b_alias)) => {
                        a_alias.alias(db).text(db).cmp(&b_alias.alias(db).text(db))
                    }
                }
                other => other,
            }
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1128 at r21](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9FUoP2E0S-gyS4zFq5:-O9FUoP2E0S-gyS4zFq6:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/cc856182819d2a6f8a617a583d4caa50d5c76565/crates/cairo-lang-formatter/src/formatter_impl.rs#L1128)):*
> ```XML
>                     .iter()
>                     .min_by_key(|x| extract_ident(*x, db)) // Dereference `&UsePath` to `UsePath`
>                     .cloned() // Convert &UsePath to UsePath            }
> ```





_Suggestion:_
```XML
                    .min_by_key(|x| extract_ident(*x, db))
                    .cloned()            }
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1160 at r21](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9FSreCDH9xVpovBe0z:-O9FSreCDH9xVpovBe1-:bjmjd6m) ([raw file](https://github.com/starkware-libs/cairo/blob/cc856182819d2a6f8a617a583d4caa50d5c76565/crates/cairo-lang-formatter/src/formatter_impl.rs#L1160)):*
> ```XML
>         _ => "".to_string(),
>     }
> }
> ```

this function should be replaced with simple calls to:

```
node.ident(db).as_syntax_node().get_text_without_trivia(db)
```
the updated code is written above.

if you do want it:
```
trait IdentExtractor {
    fn extract_ident(&self, db: &dyn SyntaxGroup) -> String;
}
impl IdentExtractor for ast::UsePathLeaf {
    fn extract_ident(&self, db: &dyn SyntaxGroup) -> String {
        node.ident(db).as_syntax_node().get_text_without_trivia(db)
    }
}
impl IdentExtractor for ast::UsePathSingle {
    fn extract_ident(&self, db: &dyn SyntaxGroup) -> String {
        node.ident(db).as_syntax_node().get_text_without_trivia(db)
    }
}
```



_Code quote:_
```XML
/// Helper function to extract the first segment identifier for comparison.
fn extract_ident(path: &impl TypedSyntaxNode, db: &dyn SyntaxGroup) -> String {
    let syntax_node = path.as_syntax_node();

    match syntax_node.kind(db) {
        SyntaxKind::UsePathSingle => {
            let path_segment = ast::UsePathSingle::from_syntax_node(db, syntax_node).ident(db);
            match path_segment {
                PathSegment::Simple(simple_segment) => {
                    simple_segment.as_syntax_node().get_text_without_trivia(db)
                }
                PathSegment::WithGenericArgs(_) => "".to_string(),
            }
        }
        SyntaxKind::UsePathLeaf => {
            let path_segment = ast::UsePathLeaf::from_syntax_node(db, syntax_node).ident(db);
            match path_segment {
                PathSegment::Simple(simple_segment) => {
                    simple_segment.as_syntax_node().get_text_without_trivia(db)
                }
                PathSegment::WithGenericArgs(_) => "".to_string(),
            }
        }
        _ = [...]

2024-10-16 11:11 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 15 of 18 files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 872 at r21](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9FR0rt7LY6RXfbNXzi:-O9JtFx_DOwItZyXruHV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cc856182819d2a6f8a617a583d4caa50d5c76565/crates/cairo-lang-formatter/src/formatter_impl.rs#L872)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why `Equal`?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 879 at r21](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9FRG8y3YXKkBnM8WVV:-O9JtNxS5OJlJz3tW5gq:b-4chaor) ([raw file](https://github.com/starkware-libs/cairo/blob/cc856182819d2a6f8a617a583d4caa50d5c76565/crates/cairo-lang-formatter/src/formatter_impl.rs#L879)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe?
</blockquote></details>

Yes, this is exactly what I did :)
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 927 at r21](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9FS-Zk5vJA1KuZ1IdF:-O9JtiJl3Pwq_JF74hxe:bvb3z0y) ([raw file](https://github.com/starkware-libs/cairo/blob/cc856182819d2a6f8a617a583d4caa50d5c76565/crates/cairo-lang-formatter/src/formatter_impl.rs#L927)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

probably just inline `a` and `b`.
</blockquote></details>

After the lsat implementation update (according to the related CR comment), it shouldn't be inlined now.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1052 at r21](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9FT_EJ9HZmILaM9zec:-O9JwfEeBMV4P9SERxyo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cc856182819d2a6f8a617a583d4caa50d5c76565/crates/cairo-lang-formatter/src/formatter_impl.rs#L1052)):*
> ```XML
>         (UsePath::Leaf(a_leaf), UsePath::Single(b_single)) => {
>             let a_str = extract_ident(a_leaf, db);
>             let b_str = extract_ident(b_single, db);
> ```

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1064 at r21](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9FTkR38zWw_yoZilFU:-O9JwquNAJkXRkbhzXMs:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cc856182819d2a6f8a617a583d4caa50d5c76565/crates/cairo-lang-formatter/src/formatter_impl.rs#L1064)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and later as well.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1077 at r21](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9FTx17BjK_jDHjV9it:-O9JzuM0C6CUcdWvjceP:b-8lc04m) ([raw file](https://github.com/starkware-libs/cairo/blob/cc856182819d2a6f8a617a583d4caa50d5c76565/crates/cairo-lang-formatter/src/formatter_impl.rs#L1077)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

fix tie break as well.
and add tests.
</blockquote></details>

I decided that in case of tie breaks (between leaves) we do not sort by the aliases.
This rust doesn't sort by aliases:
use a::{a as bc, a as ab};
remains:
use a::{a as bc, a as ab};
and not:
use a::{a as ab, a as bc};
I forgot to add a doc about it- added now, thanks.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1128 at r21](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9FUoP2E0S-gyS4zFq5:-O9JvcJlCECNtOcZscSa:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cc856182819d2a6f8a617a583d4caa50d5c76565/crates/cairo-lang-formatter/src/formatter_impl.rs#L1128)):*
> ```XML
>                     .iter()
>                     .min_by_key(|x| extract_ident(*x, db)) // Dereference `&UsePath` to `UsePath`
>                     .cloned() // Convert &UsePath to UsePath            }
> ```

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1160 at r21](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9FSreCDH9xVpovBe0z:-O9Jx2yO2hCz-7eoRdAr:bu9i3hf) ([raw file](https://github.com/starkware-libs/cairo/blob/cc856182819d2a6f8a617a583d4caa50d5c76565/crates/cairo-lang-formatter/src/formatter_impl.rs#L1160)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this function should be replaced with simple calls to:

```
node.ident(db).as_syntax_node().get_text_without_trivia(db)
```
the updated code is written above.

if you do want it:
```
trait IdentExtractor {
    fn extract_ident(&self, db: &dyn SyntaxGroup) -> String;
}
impl IdentExtractor for ast::UsePathLeaf {
    fn extract_ident(&self, db: &dyn SyntaxGroup) -> String {
        node.ident(db).as_syntax_node().get_text_without_trivia(db)
    }
}
impl IdentExtractor for ast::UsePathSingle {
    fn extract_ident(&self, db: &dyn SyntaxGroup) -> String {
        node.ident(db).as_syntax_node().get_text_without_trivia(db)
    }
}
```
</blockquote></details>

Great thanks.
Would like to know why this implementation (via traits) is considered to be better than using the extract_ident function.
___
*[`crates/cairo-lang-formatter/test_data/expected_results/sort_inner_use.cairo` line 4 at r22](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9FWISc7EMIsnGkF47J:-O9JvuiO8VxRjrYrP4Ok:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/075beb6378206c2171eb23297c420343d043e9a0/crates/cairo-lang-formatter/test_data/expected_results/sort_inner_use.cairo#L4)):*
> ```Cairo
> 
> use a::{a, b as bee, c as cee, d};
> use a::{a as bc, a as ab};
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-10-16 14:58 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 15 of 18 files reviewed, 9 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 927 at r21](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9FS-Zk5vJA1KuZ1IdF:-O9KpbRc2Elm0K7W15Zr:b-xw2z94) ([raw file](https://github.com/starkware-libs/cairo/blob/cc856182819d2a6f8a617a583d4caa50d5c76565/crates/cairo-lang-formatter/src/formatter_impl.rs#L927)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

After the lsat implementation update (according to the related CR comment), it shouldn't be inlined now.
</blockquote></details>

it still should - the `let` statement don't shorted anything or add information.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1160 at r21](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9FSreCDH9xVpovBe0z:-O9KosnA2QAYFRUt_PSr:b-3zmml3) ([raw file](https://github.com/starkware-libs/cairo/blob/cc856182819d2a6f8a617a583d4caa50d5c76565/crates/cairo-lang-formatter/src/formatter_impl.rs#L1160)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

Great thanks.
Would like to know why this implementation (via traits) is considered to be better than using the extract_ident function.
</blockquote></details>

because it had  a specific implementation per type - your implementation was less efficient and lost information.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 733 at r24](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9KoG2wEhWAGo4RVTTl:-O9KoG2wEhWAGo4RVTTm:b-8awrvv) ([raw file](https://github.com/starkware-libs/cairo/blob/a805cdb9f23de5552eefd5fb55351167750303c0/crates/cairo-lang-formatter/src/formatter_impl.rs#L733)):*
> ```XML
>     }
> }
> ```

doc all.
and please move below (in general - helper functions should be below the using functions.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 885 at r24](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9KodzB2F-mO-0bMd3k:-O9KodzB2F-mO-0bMd3l:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a805cdb9f23de5552eefd5fb55351167750303c0/crates/cairo-lang-formatter/src/formatter_impl.rs#L885)):*
> ```XML
>             match (a_use_path, b_use_path) {
>                 (Some(a_path), Some(b_path)) => {
>                     // Compare the extracted `UsePath`s.
> ```


___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1159 at r24](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9KpI_B1G_K9j2BiLEW:-O9KpI_B1G_K9j2BiLEX:bvkefls) ([raw file](https://github.com/starkware-libs/cairo/blob/a805cdb9f23de5552eefd5fb55351167750303c0/crates/cairo-lang-formatter/src/formatter_impl.rs#L1159)):*
> ```XML
>                             UsePath::Single(single) => single.extract_ident(db),
>                             _ => "".to_string(), /* Return an empty string if it's not Single or
>                                                   * Leaf */
> ```

what if the child is a `Multi`?
test.



_Code quote:_
```XML
                            _ => "".to_string(), /* Return an empty string if it's not Single or
                                                  * Leaf */
```


<!-- Sent from Reviewable.io -->

2024-10-18 11:49 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 15 of 18 files reviewed, 9 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 927 at r21](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9FS-Zk5vJA1KuZ1IdF:-O9NZl87E500LpD5zhPb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/cc856182819d2a6f8a617a583d4caa50d5c76565/crates/cairo-lang-formatter/src/formatter_impl.rs#L927)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

it still should - the `let` statement don't shorted anything or add information.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 733 at r24](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9KoG2wEhWAGo4RVTTl:-O9NYq25AVAZTuqYhIyP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a805cdb9f23de5552eefd5fb55351167750303c0/crates/cairo-lang-formatter/src/formatter_impl.rs#L733)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc all.
and please move below (in general - helper functions should be below the using functions.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 885 at r24](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9KodzB2F-mO-0bMd3k:-O9NYxQ46nsOWdi1mmAA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a805cdb9f23de5552eefd5fb55351167750303c0/crates/cairo-lang-formatter/src/formatter_impl.rs#L885)):*
> ```XML
>             match (a_use_path, b_use_path) {
>                 (Some(a_path), Some(b_path)) => {
>                     // Compare the extracted `UsePath`s.
> ```

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1159 at r24](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9KpI_B1G_K9j2BiLEW:-O9UQqSF2_Y7WkeausaM:b-l3u68y) ([raw file](https://github.com/starkware-libs/cairo/blob/a805cdb9f23de5552eefd5fb55351167750303c0/crates/cairo-lang-formatter/src/formatter_impl.rs#L1159)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what if the child is a `Multi`?
test.
</blockquote></details>

Here's my insights after examining the alternatives, including implementation and different edge cases:

I decided that the `multi` should be placed first, regardless of what's inside. Therefore, we return `"".to_string()`.
The reasons for this are:

1.  It's complex to implement– a recursive function is required to handle a `path` of type `multi` in this case. The implementation would be similar to `sort_inner_use`. It's a complicated implementation with a long computation. This is in contrast to our approach– not sorting the entire `{}` but simply selecting the first element. I decided that, across the board, we will place the `multi` first. I also added an appropriate test to verify this.
2.  We will deal with this when we implement the `use merge`. This is one of the reasons why the issue doesn’t exist in Rust and will be resolved with merging.

However, during debugging and reviewing various cases, I discovered a bug and an edge case that I hadn’t checked before. I added a test and adjusted the `sort_inner_use` function accordingly. (we ignored a `multi` within a `multi` and removed it from the final sorted result.)

I’d be happy to elaborate if necessary– but I’m confident this is the right approach, both in terms of implementation and the correctness of the code.


<!-- Sent from Reviewable.io -->

2024-10-20 08:27 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 15 of 18 files reviewed, 9 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1159 at r24](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9KpI_B1G_K9j2BiLEW:-O9d0hn96Kjkh3v-7C4S:b-jw38bu) ([raw file](https://github.com/starkware-libs/cairo/blob/a805cdb9f23de5552eefd5fb55351167750303c0/crates/cairo-lang-formatter/src/formatter_impl.rs#L1159)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

Here's my insights after examining the alternatives, including implementation and different edge cases:

I decided that the `multi` should be placed first, regardless of what's inside. Therefore, we return `"".to_string()`.
The reasons for this are:

1.  It's complex to implement– a recursive function is required to handle a `path` of type `multi` in this case. The implementation would be similar to `sort_inner_use`. It's a complicated implementation with a long computation. This is in contrast to our approach– not sorting the entire `{}` but simply selecting the first element. I decided that, across the board, we will place the `multi` first. I also added an appropriate test to verify this.
2.  We will deal with this when we implement the `use merge`. This is one of the reasons why the issue doesn’t exist in Rust and will be resolved with merging.

However, during debugging and reviewing various cases, I discovered a bug and an edge case that I hadn’t checked before. I added a test and adjusted the `sort_inner_use` function accordingly. (we ignored a `multi` within a `multi` and removed it from the final sorted result.)

I’d be happy to elaborate if necessary– but I’m confident this is the right approach, both in terms of implementation and the correctness of the code.
</blockquote></details>

properly doc - not as a n "after" multi line comment - but as a comment above ``_` => "".string()`

in any case - multi seems way more likely to always be last than first.
`a::{b, {c, d}}` seems nicer than `a::{{c, d}, b}`.

in any case - can probably wait for node merging (as this sort of multi should just be dropped entirely)
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1044 at r25](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9d0AHj1Mb7yY2BN8As:-O9d0AHj1Mb7yY2BN8At:bcv9my3) ([raw file](https://github.com/starkware-libs/cairo/blob/45a87f66b06f5a237591be3c627d2b414560a33a/crates/cairo-lang-formatter/src/formatter_impl.rs#L1044)):*
> ```XML
>                     UsePath::Single(single) => single.extract_ident(db),
>                     _ => "".to_string(), // Handle cases where it's neither leaf nor single
>                 }
> ```

doc adds nothing.
if you wish to doc something there - it should be the "why" not the "what"



_Suggestion:_
```XML
            let a_min = a_elements.iter().min_by_key(|path| {
                match path {
                    UsePath::Leaf(leaf) => leaf.extract_ident(db),
                    UsePath::Single(single) => single.extract_ident(db),
                    _ => "".to_string(),
                }
            });
            let b_min = b_elements.iter().min_by_key(|path| {
                match path {
                    UsePath::Leaf(leaf) => leaf.extract_ident(db),
                    UsePath::Single(single) => single.extract_ident(db),
                    _ => "".to_string(),
                }
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1068 at r25](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9d0OwL9WhH7OUmTAQp:-O9d0OwM6Kdf_eF3k-Av:b-hhai18) ([raw file](https://github.com/starkware-libs/cairo/blob/45a87f66b06f5a237591be3c627d2b414560a33a/crates/cairo-lang-formatter/src/formatter_impl.rs#L1068)):*
> ```XML
>             let b_str = b_single.extract_ident(db);
> 
>             // Compare the extracted identifiers.
> ```

useless comment.



_Code quote:_
```XML
            // Compare the extracted identifiers.
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1092 at r25](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9d0WKy-bTOz7UbhPBl:-O9d0WKy-bTOz7UbhPBm:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/45a87f66b06f5a237591be3c627d2b414560a33a/crates/cairo-lang-formatter/src/formatter_impl.rs#L1092)):*
> ```XML
>             let b_str = b_leaf.extract_ident(db);
> 
>             // In case of tie breaks we do not sort by aliases (same methodology as Rust).
> ```





_Suggestion:_
```XML
            // Note that in case of tie breaks we do not sort by aliases.
```


<!-- Sent from Reviewable.io -->

2024-10-20 13:04 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 15 of 18 files reviewed, 9 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1159 at r24](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9KpI_B1G_K9j2BiLEW:-O9e01oR9iC52ylnB1v3:b-e032wp) ([raw file](https://github.com/starkware-libs/cairo/blob/a805cdb9f23de5552eefd5fb55351167750303c0/crates/cairo-lang-formatter/src/formatter_impl.rs#L1159)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

properly doc - not as a n "after" multi line comment - but as a comment above ``_` => "".string()`

in any case - multi seems way more likely to always be last than first.
`a::{b, {c, d}}` seems nicer than `a::{{c, d}, b}`.

in any case - can probably wait for node merging (as this sort of multi should just be dropped entirely)
</blockquote></details>

- Changed doc.
- multi changed to be last.
- Added sort by aliases (+tests).
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1044 at r25](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9d0AHj1Mb7yY2BN8As:-O9daJap5jON5buHSYF-:bg3wdzv) ([raw file](https://github.com/starkware-libs/cairo/blob/45a87f66b06f5a237591be3c627d2b414560a33a/crates/cairo-lang-formatter/src/formatter_impl.rs#L1044)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc adds nothing.
if you wish to doc something there - it should be the "why" not the "what"
</blockquote></details>

Yes, I agree. It was a comment I made for myself and forgot to delete before pushing.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1068 at r25](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9d0OwL9WhH7OUmTAQp:-O9dA0cA8GSzI556Vz7d:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/45a87f66b06f5a237591be3c627d2b414560a33a/crates/cairo-lang-formatter/src/formatter_impl.rs#L1068)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

useless comment.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1092 at r25](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9d0WKy-bTOz7UbhPBl:-O9da_RGAZt1PP_WiGR8:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/45a87f66b06f5a237591be3c627d2b414560a33a/crates/cairo-lang-formatter/src/formatter_impl.rs#L1092)):*
> ```XML
>             let b_str = b_leaf.extract_ident(db);
> 
>             // In case of tie breaks we do not sort by aliases (same methodology as Rust).
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-10-20 14:11 UTC, orizi requested changes
> Reviewed 3 of 3 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: all files reviewed, 2 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1088 at r26](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9eG4JW5lRp-z9GXBYp:-O9eG4JW5lRp-z9GXBYq:b89hgi3) ([raw file](https://github.com/starkware-libs/cairo/blob/331324fa4d9c823116210c859efe63b47947688a/crates/cairo-lang-formatter/src/formatter_impl.rs#L1088)):*
> ```XML
>             let a_alias = a_leaf.extract_alias(db);
>             let b_alias = b_leaf.extract_alias(db);
>             a_str.cmp(&b_str).then(a_alias.cmp(&b_alias))
> ```

extract alias only on the case of equality.



_Code quote:_
```XML
            a_str.cmp(&b_str).then(a_alias.cmp(&b_alias))
```


<!-- Sent from Reviewable.io -->

2024-10-20 14:44 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1088 at r26](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9eG4JW5lRp-z9GXBYp:-O9eNhluCwSqgRokqiQx:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/331324fa4d9c823116210c859efe63b47947688a/crates/cairo-lang-formatter/src/formatter_impl.rs#L1088)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

extract alias only on the case of equality.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-21 09:06 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 17 of 18 files reviewed, 2 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1094 at r27](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9iJRI00ug0mdYm6ktU:-O9iJRI00ug0mdYm6ktV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5af968e8c9b3af282eb9463fbee3d33f52d3eb2f/crates/cairo-lang-formatter/src/formatter_impl.rs#L1094)):*
> ```XML
>             } else {
>                 result
>             }
> ```





_Suggestion:_
```XML
            match a_leaf.extract_ident(db).cmp(&b_leaf.extract_ident(db)) {
                Ordering::Equal => a_leaf.extract_alias(db).cmp(&b_leaf.extract_alias(db)),
                other => other,
            }
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1151 at r27](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9iJmIb0jHo0czqNWfm:-O9iJmIb0jHo0czqNWfn:bjxti9y) ([raw file](https://github.com/starkware-libs/cairo/blob/5af968e8c9b3af282eb9463fbee3d33f52d3eb2f/crates/cairo-lang-formatter/src/formatter_impl.rs#L1151)):*
> ```XML
>                     // needed to avoid
>                     // complex computation involved in recursively
>                     // processing nested `multi` paths.
> ```

use all 100 chars of a line in the comment.



_Suggestion:_
```XML
                    // We return an empty string (`""`) to ensure that `multi` paths
                    // are always placed first in the sorted order. This is
                    // needed to avoid
                    // complex computation involved in recursively
                    // processing nested `multi` paths.
```


<!-- Sent from Reviewable.io -->

2024-10-21 09:41 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467)* status: 17 of 18 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1094 at r27](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9iJRI00ug0mdYm6ktU:-O9iRh4VBv-jhnaackgR:b-83sjo4) ([raw file](https://github.com/starkware-libs/cairo/blob/5af968e8c9b3af282eb9463fbee3d33f52d3eb2f/crates/cairo-lang-formatter/src/formatter_impl.rs#L1094)):*
> ```XML
>             } else {
>                 result
>             }
> ```

Nice.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1151 at r27](https://reviewable.io/reviews/starkware-libs/cairo/6467#-O9iJmIb0jHo0czqNWfm:-O9iRSNF6ot82XCT18z1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5af968e8c9b3af282eb9463fbee3d33f52d3eb2f/crates/cairo-lang-formatter/src/formatter_impl.rs#L1151)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

use all 100 chars of a line in the comment.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-21 11:21 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r28, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6467#-:-O9inqAQ5f2Lzu-u3Q4S:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2024-10-21 11:39 UTC, merged