LS: Calculate diagnostics on background
starkware-libs/cairo pull request #6469
Opened 2024-10-09 09:34 UTC by Draggu

Fix #6318

2024-10-09 14:53 UTC, mkaput requested changes
> Reviewed 2 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: 2 of 11 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8lfykVAXHKlwKtTFDy:-O8lfykVAXHKlwKtTFDz:b-qggek0) ([raw file](https://github.com/starkware-libs/cairo/blob/cca55849a10fccf6179a4ff83afff02af5b21523/crates/cairo-lang-language-server/src/lib.rs#L87)):*
> ```XML
> 
> mod config;
> mod diagnostics;
> ```

move this into `lang`, i.e. -> `crate::lang::diagnostics`
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 347 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8lkGuE3H4MOSV71sJh:-O8lkGuFACdFLRsRbzh9:b-wwu8rw) ([raw file](https://github.com/starkware-libs/cairo/blob/cca55849a10fccf6179a4ff83afff02af5b21523/crates/cairo-lang-language-server/src/lib.rs#L347)):*
> ```XML
>         });
> 
>         let (diags_sender, diags_handle) = Diagnostics::handler()?;
> ```

I wonder if you can just return an object that you can register as a post hook directly, say

```rs
let (diags_post_hook, _) = Diagnostics::handler()?;

scheduler.sync_task_post_hook(diags_post_hook);
```
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 354 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8lggQWB0HdAB-0g8OO:-O8lggQWB0HdAB-0g8OP:b-9m59e2) ([raw file](https://github.com/starkware-libs/cairo/blob/cca55849a10fccf6179a4ff83afff02af5b21523/crates/cairo-lang-language-server/src/lib.rs#L354)):*
> ```XML
>         // Important: swap should occur before using snapshots in diagnostics.
>         scheduler
>             .sync_task_post_hook(|state, notifier| Self::maybe_swap_database(state, &notifier));
> ```

wdyt about such refactoring of `maybe_swap_database`? this sounds like a sensible design pattern we could establish



_Suggestion:_
```XML
.sync_task_post_hook(Self::swap_database_hook);
```
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 361 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8lkVoY-lIH7aif7dUu:-O8lkVoY-lIH7aif7dUv:b1v1trf) ([raw file](https://github.com/starkware-libs/cairo/blob/cca55849a10fccf6179a4ff83afff02af5b21523/crates/cairo-lang-language-server/src/lib.rs#L361)):*
> ```XML
>             // currently private in salsa. In case DB have not changed currently sended
>             // snapshots are still valid so there is no need to send them again.
>             diags_sender.try_send(StateSnapshotForDiagnostics::from_state(state)).ok();
> ```

Hmm sounds to me like you need a bounded(1)-style data structure that just allows force pushing like a ring buffer :thinking: 

If this is true, then I think you could be better by using a nicely-wrapped `(Mutex<Option<T>>, CondVar)` instead of bounded(1) channel here. wdyt?


<!-- Sent from Reviewable.io -->

2024-10-10 05:16 UTC, mkaput reviewed
> Reviewed 3 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: 5 of 11 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-10-10 10:11 UTC, mkaput requested changes
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: 6 of 11 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 405 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8pthNO10E2J5QX3UD0:-O8pthNO10E2J5QX3UD1:b-c37mt2) ([raw file](https://github.com/starkware-libs/cairo/blob/cca55849a10fccf6179a4ff83afff02af5b21523/crates/cairo-lang-language-server/src/lib.rs#L405)):*
> ```XML
> 
>     /// Catches panics and returns Err.
>     fn catch_cancellation<T>(f: impl FnOnce() -> T) -> Result<T, UnwindErrorKind> {
> ```

actually, these two `catch_*` funcitons don't have to live in `Backend`. consider moving them + related types to, say, `crate::server::panic` (following `std::panic` name)
___
*[`crates/cairo-lang-language-server/src/lib.rs` line 457 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8puDGr2oQyLMmLh5nC:-O8puDGr2oQyLMmLh5nD:b-xrb6m4) ([raw file](https://github.com/starkware-libs/cairo/blob/cca55849a10fccf6179a4ff83afff02af5b21523/crates/cairo-lang-language-server/src/lib.rs#L457)):*
> ```XML
>     /// Perform database swap
>     #[tracing::instrument(level = "debug", skip_all)]
>     fn swap_database(state: &mut State, notifier: &Notifier) -> LSPResult<()> {
> ```

this return value is meaningless now so just drop it



_Suggestion:_
```XML
fn swap_database(state: &mut State, notifier: &Notifier) {
```


<!-- Sent from Reviewable.io -->

2024-10-10 10:42 UTC, mkaput requested changes
> Reviewed 1 of 11 files at r1, 6 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: 11 of 16 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q-vWpAwdVJ79ThxS4:-O8q-vWpAwdVJ79ThxS5:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lib.rs#L65)):*
> ```XML
> use lsp_types::{ClientCapabilities, Registration, RegistrationParams, Url};
> use server::connection::ClientSender;
> use server::panic::catch_cancellation;
> ```





_Suggestion:_
```XML
use crate::server::connection::ClientSender;
use crate::server::panic::catch_cancellation;
```
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/state.rs` line 0 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q0OB59q7scpMVTmqR:-O8q0OB59q7scpMVTmqS:b-bzogir) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics/state.rs#L0)):*
rename to `state/mod.rs`


<!-- Sent from Reviewable.io -->

2024-10-10 11:00 UTC, mkaput requested changes
> Reviewed 1 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: 12 of 16 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/force_write_buffer.rs` line 4 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q2Yo003nqjECpyBFR:-O8q2Yo003nqjECpyBFS:b5vedqn) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics/force_write_buffer.rs#L4)):*
> ```XML
> 
> /// Single element buffer that allows force pushing into it.
> pub struct ForceWriteBuffer<T>(Arc<ForceWriteBufferInner<T>>);
> ```

some unit tests for this would be handy
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/force_write_buffer.rs` line 4 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q3lzSBTmI0Pe8Uvvv:-O8q3lzT33RXA7HLmtuf:b-7hbpla) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics/force_write_buffer.rs#L4)):*
> ```XML
> 
> /// Single element buffer that allows force pushing into it.
> pub struct ForceWriteBuffer<T>(Arc<ForceWriteBufferInner<T>>);
> ```

wdyt?



_Suggestion:_
```XML
pub struct Slot<T>(Arc<SlotInner<T>>);
```
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/force_write_buffer.rs` line 22 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q3qND0zDzAU9FuF2K:-O8q3qND0zDzAU9FuF2L:b-7hbpla) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics/force_write_buffer.rs#L22)):*
> ```XML
> 
>     /// Forcefully pushes into buffer.
>     pub fn force_push(&self, value: T) {
> ```

wdyt?



_Suggestion:_
```XML
pub fn set(&self, value: T) {
```
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/state.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q40YT8gXT07Zhtx1Y:-O8q40YT8gXT07Zhtx1Z:bclhd2a) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics/state.rs#L17)):*
> ```XML
> 
> mod diff;
> #[derive(Clone, Debug, Default, PartialEq, Eq)]
> ```

rustfmt plz



_Suggestion:_
```XML
mod diff;

#[derive(Clone, Debug, Default, PartialEq, Eq)]
```


<!-- Sent from Reviewable.io -->

2024-10-10 11:00 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: 12 of 16 files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/diagnostics.rs` line 0 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q4a3A1y2C4MlhdrQw:-O8q4a3A1y2C4MlhdrQx:b-uy8xja) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics.rs#L0)):*
rename to `.../mod.rs`


<!-- Sent from Reviewable.io -->

2024-10-10 11:02 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: 12 of 16 files reviewed, 8 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/diagnostics.rs` line 29 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q4pbw4UF45srQywRR:-O8q4pbw4UF45srQywRS:b-7hnzpx) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics.rs#L29)):*
> ```XML
> use crate::state::State;
> 
> const WORKERS_THREAD_POOL_SIZE: usize = 4;
> ```

imo this should be based off https://doc.rust-lang.org/stable/std/thread/fn.available_parallelism.html a not be a constant


<!-- Sent from Reviewable.io -->

2024-10-10 11:03 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: 12 of 16 files reviewed, 8 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/force_write_buffer.rs` line 4 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q3lzSBTmI0Pe8Uvvv:-O8q59Qn1I6ljZaAoV9W:boegk1i) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics/force_write_buffer.rs#L4)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

wdyt?
</blockquote></details>

or perhaps `Trigger`, leaving up to you


<!-- Sent from Reviewable.io -->

2024-10-10 11:06 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: 12 of 16 files reviewed, 8 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/force_write_buffer.rs` line 4 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q3lzSBTmI0Pe8Uvvv:-O8q5S0z03FyF9oXLrb7:bmfrbfr) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics/force_write_buffer.rs#L4)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

or perhaps `Trigger`, leaving up to you
</blockquote></details>

and consider having 2 types like channels do, say: `Trigger, Actuator`


<!-- Sent from Reviewable.io -->

2024-10-10 11:15 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: 12 of 16 files reviewed, 9 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/diagnostics.rs` line 45 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q7TS50YeHFd_6nLNn:-O8q7TS50YeHFd_6nLNo:b-i33cjs) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics.rs#L45)):*
> ```XML
> 
> impl Diagnostics {
>     pub fn tasks() -> Result<(impl Fn(&mut State, Notifier), impl FnOnce(Notifier, Responder))> {
> ```

this is infallible, so `Result` is unnecessary here


<!-- Sent from Reviewable.io -->

2024-10-10 13:06 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: 12 of 16 files reviewed, 13 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/diagnostics.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q87viC5Y9xR9Z_M2O:-O8q87viC5Y9xR9Z_M2P:b-4j2qtc) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics.rs#L80)):*
> ```XML
>         let Ok((open_files, rest_of_files)) = catch_cancellation(|| {
>             Self::get_files(
>                 &message.db_snapshots[0], // Safe because there is always more than 0 workers.
> ```

consider encapsulating this as a method 
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics.rs` line 103 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8qULfL6UFXMEy4WPEv:-O8qULfL6UFXMEy4WPEw:besdng1) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics.rs#L103)):*
> ```XML
>         // For some reason rx is not disconnected after all threads completed.
>         let state_diff =
>             receiver.into_iter().take(WORKERS_THREAD_POOL_SIZE).reduce(Add::add).unwrap();
> ```

https://doc.rust-lang.org/stable/std/iter/trait.Sum.html



_Suggestion:_
```XML
.sum()
```
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics.rs` line 233 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8qUmlL5MMD53U1xiwk:-O8qUmlL5MMD53U1xiwl:bg1s5u9) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics.rs#L233)):*
> ```XML
>     }
> 
>     #[tracing::instrument(skip_all)]
> ```

level is missing
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/file.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8qVCEI3-YbyhVQm1je:-O8qVCEI3-YbyhVQm1jf:b-w8lyds) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics/file.rs#L36)):*
> ```XML
> 
>         // TODO should we catch here? Currently cancellation can happen on next iteration
>         // db.file_modules() only, we should not catch it here too.
> ```

we're catching compiler bugs here


<!-- Sent from Reviewable.io -->

2024-10-10 13:47 UTC, mkaput requested changes
> Reviewed 3 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: 15 of 16 files reviewed, 14 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/file.rs` line 31 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8qfOcv3OBS4QJLcnOx:-O8qfOcv3OBS4QJLcnOy:bqxmh80) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics/file.rs#L31)):*
> ```XML
>     /// Refresh diagnostics for a single file.
>     pub fn refresh_diagnostics(&self, db: &AnalysisDatabase) -> FileDiagnostics {
>         let modules_ids = db.file_modules(self.id).unwrap_or_default();
> ```

@Arcticae please verify correctness of this logic
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/state/diff.rs` line 10 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8qcRcJ78f0IraYy_P8:-O8qcRcK6Ycjq0ziTJLC:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics/state/diff.rs#L10)):*
> ```XML
> pub struct StateDiff {
>     changes: HashMap<Url, FileDiagnosticsChange>,
>     calculated_all: bool,
> ```

doc


<!-- Sent from Reviewable.io -->

2024-10-10 13:54 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: 15 of 16 files reviewed, 17 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/diagnostics.rs` line 113 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8qgF1k6SY10EZB5CO2:-O8qgF1l6TBatG7ixL8e:b-jvfkfc) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics.rs#L113)):*
> ```XML
>         db: &AnalysisDatabase,
>         open_files: HashSet<Url>,
>     ) -> (Vec<FileBothFormats>, HashSet<FileBothFormats>) {
> ```

would be nice to use a named structure here, say: `FilesQueue`
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics.rs` line 146 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8qgOCY46KYsC8-wfOk:-O8qgOCY46KYsC8-wfOl:b7vvqj6) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics.rs#L146)):*
> ```XML
>     }
> 
>     fn worker_files_partition(
> ```

this can be a method of the aforementioned `FilesQueue`
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/state/diff.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8qh9i_E393-sUlmxdJ:-O8qh9i_E393-sUlmxdK:b6fp9ah) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics/state/diff.rs#L25)):*
> ```XML
>     }
> 
>     pub fn consume(&mut self, url: &Url) -> Option<FileDiagnosticsChange> {
> ```

try to re-use standard Rust collection method names, it'd be easier to read that way



_Suggestion:_
```XML
remove
```


<!-- Sent from Reviewable.io -->

2024-10-10 14:03 UTC, mkaput reviewed
> Reviewed 1 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: all files reviewed, 18 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-10-10 15:46 UTC, Draggu reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: all files reviewed, 18 unresolved discussions (waiting on @Arcticae, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q-vWpAwdVJ79ThxS4:-O8qZqD481gkOYauACdb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lib.rs#L65)):*
> ```XML
> use lsp_types::{ClientCapabilities, Registration, RegistrationParams, Url};
> use server::connection::ClientSender;
> use server::panic::catch_cancellation;
> ```

Done.
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/force_write_buffer.rs` line 4 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q3lzSBTmI0Pe8Uvvv:-O8qpZXN0yggBi93j5fi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics/force_write_buffer.rs#L4)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

and consider having 2 types like channels do, say: `Trigger, Actuator`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/force_write_buffer.rs` line 22 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q3qND0zDzAU9FuF2K:-O8q_wU41Pl2oRz1q7JX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics/force_write_buffer.rs#L22)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

wdyt?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics.rs` line 29 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q4pbw4UF45srQywRR:-O8r5llaAkZeNePvUoBS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics.rs#L29)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

imo this should be based off https://doc.rust-lang.org/stable/std/thread/fn.available_parallelism.html a not be a constant
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics.rs` line 45 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q7TS50YeHFd_6nLNn:-O8q_MS_1FbbGuUDF_DP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics.rs#L45)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

this is infallible, so `Result` is unnecessary here
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q87viC5Y9xR9Z_M2O:-O8qoljx7EarJmfwgbuO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics.rs#L80)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

consider encapsulating this as a method
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics.rs` line 103 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8qULfL6UFXMEy4WPEv:-O8q_WEN2u93Kp-2uj0X:b-86omm) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics.rs#L103)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

https://doc.rust-lang.org/stable/std/iter/trait.Sum.html
</blockquote></details>

I thought about this and i think it is less readable.
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics.rs` line 113 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8qgF1k6SY10EZB5CO2:-O8qyvJt4oIs-DRK21wB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics.rs#L113)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

would be nice to use a named structure here, say: `FilesQueue`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics.rs` line 146 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8qgOCY46KYsC8-wfOk:-O8qyuQn45UuVooCQnaI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics.rs#L146)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

this can be a method of the aforementioned `FilesQueue`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics.rs` line 229 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8qiXdI0v0CgTBAwUu2:-O8qpKM16xEn9ww8stZo:b-npuqnf) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics.rs#L229)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

won't we halt the world if this send fails? you're expecting exact amount of messages on the channel on the receiver side
</blockquote></details>

Changed to `.unwrap()` don't see the case where this can fail.
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics.rs` line 233 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8qUmlL5MMD53U1xiwk:-O8q_iIg45G10jKgtJSM:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics.rs#L233)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

level is missing
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q4a3A1y2C4MlhdrQw:-O8q_2kS8Ae0E7zfLgtf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics.rs#L)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

rename to `.../mod.rs`
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/file.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8qVCEI3-YbyhVQm1je:-O8r5jay9s7VnzDB34jI:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics/file.rs#L36)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

we're catching compiler bugs here
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/state.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q40YT8gXT07Zhtx1Y:-O8qaE3C4fMhiHZOc1H9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics/state.rs#L17)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

rustfmt plz
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/state.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8q0OB59q7scpMVTmqR:-O8qa-PqBvPPYNqRy_Zy:b-tm0vds) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6 [...]

2024-10-10 20:54 UTC, piotmag769 reviewed
> Reviewed 2 of 11 files at r1, 3 of 11 files at r3, 4 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: 10 of 19 files reviewed, 19 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 327 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8sAjpL-q6_Mhm08SVt:-O8sAjpL-q6_Mhm08SVu:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lib.rs#L327)):*
> ```XML
>     fn initial_setup<'a>(state: &'a mut State, connection: &'_ Connection) -> Scheduler<'a> {
>         let four = NonZeroUsize::new(4).unwrap();
>         // If this is not set we can deadlock.
> ```





_Suggestion:_
```XML
// If we have less threads, we may deadlock.
```


<!-- Sent from Reviewable.io -->

2024-10-11 10:10 UTC, mkaput reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: 10 of 19 files reviewed, 18 unresolved discussions (waiting on @Arcticae, @Draggu, and @orizi)



<!-- Sent from Reviewable.io -->

2024-10-11 11:07 UTC, mkaput requested changes
> Reviewed 9 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: all files reviewed, 9 unresolved discussions (waiting on @Arcticae, @Draggu, and @orizi)

___
*[`crates/cairo-lang-language-server/src/lib.rs` line 336 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8v4Cr369aE0FFmM58k:-O8v4Cr42V-1406j6DY5:b-ubzaxb) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lib.rs#L336)):*
> ```XML
> 
>         let worker_threads =
>             std::thread::available_parallelism().unwrap_or(four).max(four).min(min_threads);
> ```

weird, this gives us either 3 or 4 threads. don't we want to make use of more?
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/files_queue.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8vEoNMEXgWhyGkzgQB:-O8vEoNMEXgWhyGkzgQC:bo0ad0t) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/files_queue.rs#L17)):*
> ```XML
> pub struct FilesQueue(Vec<FileBothFormats>);
> 
> impl IntoIterator for FilesQueue {
> ```

reorder: impl goes first, impl traits second
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/files_queue.rs` line 67 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8vFLcD8-hXGw9JFpoC:-O8vFLcD8-hXGw9JFpoD:bu5i1za) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/files_queue.rs#L67)):*
> ```XML
>     }
> 
>     pub fn worker_files_partition(&self, worker: usize, jobs_number: usize) -> Self {
> ```

doc all of these
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 65 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8vFggMBpGr7M3YfW4N:-O8vFggMBpGr7M3YfW4O:bd3f69v) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L65)):*
> ```XML
>         let size = thread_pool.size();
> 
>         (size / 2).max(size - 2)
> ```

why these shenanigangs?
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/slot.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8vCwAp1wncEWeDKCZ1:-O8vCwAqCjNY7WhD8q01:bd6iewf) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/slot.rs#L3)):*
> ```XML
> use std::sync::{Arc, Condvar, Mutex};
> 
> /// Single element buffer that allows force pushing into it.
> ```

this doc is not descriptive except it says that it can contain a single element. please rephrase this so that it tells that this is 0/1, it overrides on set and popping waits
___
*[`crates/cairo-lang-language-server/src/server/schedule/thread/pool.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8vC5D6CPkBIvGd7vhf:-O8vC2zk23WXPmgQ668A:b-qdiflo) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/server/schedule/thread/pool.rs#L34)):*
> ```XML
> 
> #[derive(Clone)]
> pub struct SharedPool(Arc<Pool>);
> ```

this type is kinda superfluous? it doesn't bring anything and the name is a bit mysterious comparing to it being just an Arc
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics.rs` line 103 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8qULfL6UFXMEy4WPEv:-O8vCJKu1JH7Sv3sXYnh:b-d7v5ff) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics.rs#L103)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

I thought about this and i think it is less readable.
</blockquote></details>

but it's potentially more performant because it can merge all items at once


<!-- Sent from Reviewable.io -->

2024-10-14 09:02 UTC, Draggu reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: all files reviewed, 10 unresolved discussions (waiting on @Arcticae and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/slot.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O99Fve8BnHIlvWYrG5L:-O99Fve8BnHIlvWYrG5M:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/slot.rs#L9)):*
> ```XML
> impl<T> SlotReader<T> {
>     /// Read from buffer leaving it empty. If it is currently empty waits for push first.
>     pub fn pop(&self) -> T {
> ```





_Suggestion:_
```XML
take
```


<!-- Sent from Reviewable.io -->

2024-10-14 14:29 UTC, piotmag769 reviewed
> Reviewed 1 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: all files reviewed, 10 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/server/schedule/thread/pool.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8vC5D6CPkBIvGd7vhf:-O9AQpxP-q4l5QrmYEwa:bejorv9) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/server/schedule/thread/pool.rs#L34)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Now when i think about this i would rather not share it but pass `type JobSender = Sender<Job>` to background task handler
</blockquote></details>

Agree with @mkaput 


<!-- Sent from Reviewable.io -->

2024-10-14 14:30 UTC, piotmag769 reviewed
> Reviewed 1 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: all files reviewed, 10 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)



<!-- Sent from Reviewable.io -->

2024-10-14 23:37 UTC, piotmag769 requested changes
> Reviewed 1 of 11 files at r1, 5 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: all files reviewed, 29 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9Ac44kA60yw_jrXEad:-O9Ac44kA60yw_jrXEae:bolfwf2) (no related file):*
Please document it properly

___
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/files_queue.rs` line 66 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9AU8ij2UTBc0ptgrlt:-O9AU8ij2UTBc0ptgrlu:b-r1wz1r) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/files_queue.rs#L66)):*
> ```XML
>         self.0.iter().map(|file| file.url.clone())
>     }
> ```

This heavily relies on the caller using this function properly (passing proper `worker` and `jobs_number` every time), it should instead take `jobs_number` and return `Vec<Self>`, then the caller should distribute each element of the vector to each worker
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/files_queue.rs` line 81 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9AVgVU7nqRNzomNZ1G:-O9AVgVV7OxCVZTKLJze:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/files_queue.rs#L81)):*
> ```XML
>     pub fn previous_generation_file_diagnostics(
>         &self,
>         diagnostics_for_file: &HashMap<Url, FileDiagnostics>,
> ```





_Suggestion:_
```XML
previous_diagnostics
```
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 42 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9AcIPx3K11usUCeQ7I:-O9AcIPx3K11usUCeQ7J:bqxp7m5) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L42)):*
> ```XML
>             let mut diagnostics = Self::new(notifier, thread_pool);
> 
>             while let Some(message) = slot_reader.pop() {
> ```

This is not a message but diagnostic_state_snapshot



_Code quote:_
```XML
message
```
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 50 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9AX4EwBgncGmHcpYDI:-O9AX4EwBgncGmHcpYDJ:bb7462z) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L50)):*
> ```XML
>             let message = StateSnapshotForDiagnostics::from_state(state, jobs_number);
> 
>             // TODO check if server is closing and send None to allow thread pool to be dropped.
> ```

TODO
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 89 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9AYBFlCzww__18wGMJ:-O9AYBFlCzww__18wGMK:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L89)):*
> ```XML
> 
>         // For some reason rx is not disconnected after all threads completed.
>         let state_diff = receiver.into_iter().take(jobs_number).reduce(Add::add).unwrap();
> ```





_Suggestion:_
```XML
        drop(sender);
        
        let state_diff = receiver.into_iter().reduce(Add::add).unwrap();
```
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 96 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9AXjH-D5bzhspKX5JR:-O9AXjH-D5bzhspKX5JS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L96)):*
> ```XML
>     }
> 
>     fn spawn_worker_tasks(
> ```





_Suggestion:_
```XML
spawn_worker
```
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 104 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9AfHxM3b9QgzRRTxcU:-O9AfHxM3b9QgzRRTxcV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L104)):*
> ```XML
>     ) {
>         let notifier = self.notifier.clone();
>         let file_diagnostics =
> ```





_Suggestion:_
```XML
previous_generation_file_diagnostics
```
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 122 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9AfvNJ0zoj6xI5G2KP:-O9AfvNJ0zoj6xI5G2KQ:bzicsz) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L122)):*
> ```XML
>                         diff.update_for(&file.url, FileDiagnosticsChange::Unchanged);
> 
>                         // No need to send same diagnostics twice.
> ```

Comment should be just after the else if
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 170 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9Ae1aLEyN32YD9oP2B:-O9Ae1aLEyN32YD9oP2C:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L170)):*
> ```XML
>                     // Unset diagnostics for files that are no longer relevant only if we calculated
>                     // all diagnostics (ie. no cancellation during this work
>                     // happened) to make UX better.
> ```





_Suggestion:_
```XML
                    // Make sure to unset diagnostics for files that are no longer relevant. Do it only if we calculated
                    // all diagnostics (i. e., no cancellation during this work
                    // happened). This is done to prevent constant setting and unsetting diagnostics better to UX
```
___
*[`crates/cairo-lang-language-server/src/server/schedule/mod.rs` line 45 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9AWIod5T-qBvHZ3x_1:-O9AWIod5T-qBvHZ3x_2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/server/schedule/mod.rs#L45)):*
> ```XML
>     client: Client<'s>,
>     background_pool: thread::SharedPool,
>     sync_task_post_hooks: Vec<Box<PostHook>>,
> ```





_Suggestion:_
```XML
post_sync_task_hooks
```
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/file.rs` line 16 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9ASLfA6HCFYGUYpUFg:-O9ASLfA6HCFYGUYpUFh:b6c2dhe) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/file.rs#L16)):*
> ```XML
> 
> /// In LSP context [`Url`] is required and in [`salsa`], [`FileId`] but conversion is fallible as it
> /// requires [`salsa`] query and snapshot can be already cancelled.
> ```

Please rephrase it so it is stated that's bcs we still want to send calculated diagnostics even when cancellation happened
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/file.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9AReYJBdYZ9y_EzCeA:-O9AReYJBdYZ9y_EzCeB:b-2ipyzg) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/file.rs#L18)):*
> ```XML
> /// requires [`salsa`] query and snapshot can be already cancelled.
> #[derive(Debug, Clone, PartialEq, Eq, Hash)]
> pub struct FileBothFormats {
> ```

This name is bad imo, I had not idea what it meant without the comment
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/state/diff.rs` line 34 at r4](h [...]

2024-10-14 23:37 UTC, piotmag769 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: all files reviewed, 29 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9Ac44kA60yw_jrXEad:-O9COF2-BYNNQc7CgDCt:bieqf7q) (no related file):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Please document it properly
</blockquote></details>

Did a partial review, will finish tomorrow in the morning

___


<!-- Sent from Reviewable.io -->

2024-10-15 14:51 UTC, Arcticae requested changes
> Reviewed 1 of 11 files at r1, 2 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6469)* status: all files reviewed, 40 unresolved discussions (waiting on @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/files_queue.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9FcfxR5p98x3RlPlQW:-O9FcfxR5p98x3RlPlQX:b-6fp3u4) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/files_queue.rs#L79)):*
> ```XML
>     }
> 
>     pub fn previous_generation_file_diagnostics(
> ```

Nowhere in the implementation is the concept of `generations` explained 
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 32 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9Fb1Ah9T6QxbeKTn4u:-O9Fb1Ah9T6QxbeKTn4v:b-6altd8) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L32)):*
> ```XML
> }
> 
> impl Diagnostics {
> ```

I kind of dislike different abstraction levels and concerns being mixed in this struct and its' implementation
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9Fd-GL1fkgf9uhH7LB:-O9Fd-GL1fkgf9uhH7LC:b-4kh8pl) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L33)):*
> ```XML
> 
> impl Diagnostics {
>     pub fn tasks(
> ```

why pack creating 2 tasks into same method? Instead it could be 2 different methods on this struct 
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 96 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9Fc85n5iCmbLTtSvOO:-O9Fc85n5iCmbLTtSvOP:b924pcz) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L96)):*
> ```XML
>     }
> 
>     fn spawn_worker_tasks(
> ```

It does much more than stated
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/slot.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8vCwAp1wncEWeDKCZ1:-O9FP6Nl3aLcbCuvfkzc:bcdtj4y) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/slot.rs#L3)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

this doc is not descriptive except it says that it can contain a single element. please rephrase this so that it tells that this is 0/1, it overrides on set and popping waits
</blockquote></details>

I would gladly also accept the purpose of this so it can be easily reused
___
*[`crates/cairo-lang-language-server/src/server/schedule/mod.rs` line 62 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9FLsY28YghbYSDA-ve:-O9FLsY28YghbYSDA-vf:b-v5kkas) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/server/schedule/mod.rs#L62)):*
> ```XML
>     }
> 
>     // Executes after every local `task`. Meaning this will happen after every possible state
> ```

Please elaborate, which state change? It's unclear why it's implemented like that and what it's for
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/file.rs` line 31 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O8qfOcv3OBS4QJLcnOx:-O9Fdq9CBvVDXfZNTIoz:bub9d17) ([raw file](https://github.com/starkware-libs/cairo/blob/4319a1e5a23d760b4172f1e91ceba5af3287d6ae/crates/cairo-lang-language-server/src/lang/diagnostics/file.rs#L31)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

@Arcticae please verify correctness of this logic
</blockquote></details>

Should be OK from what we discussed offline 
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/file.rs` line 24 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9FeDWYDtZjKJqGYveb:-O9FeDWYDtZjKJqGYvec:b-h0yfou) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/file.rs#L24)):*
> ```XML
> 
> impl FileBothFormats {
>     pub fn new(id: FileId, url: Url) -> Self {
> ```

why do we need the pairing though
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/state/diff.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9FOn-k9PHEZGV-FolQ:-O9FOn-k9PHEZGV-FolR:bykwd91) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/state/diff.rs#L9)):*
> ```XML
> 
> /// Diff in state calculated by single worker.
> pub struct StateDiff {
> ```

Why introduce this statediff logic instead of just providing the newest diags for the file?
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/state/mod.rs` line 72 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9FNmj67ZPsiQImEtm9:-O9FNmj67ZPsiQImEtmA:b-wvvdnd) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/state/mod.rs#L72)):*
> ```XML
> 
> #[derive(Debug, Default)]
> pub struct DiagnosticsState {
> ```

What's the point of this struct?
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/state/mod.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9A_1hf7Un_2RVqIyPr:-O9FOPU56IGH9nP0fuNU:b-8ayu6x) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/state/mod.rs#L76)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

It doesn't bring anything but boilerplate code
</blockquote></details>

Agree
___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/state/mod.rs` line 103 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6469#-O9FOMQhARWLrIP0EJUn:-O9FOMQhARWLrIP0EJUo:b-6tnb4l) ([raw file](https://github.com/starkware-libs/cairo/blob/10d589dc849cb8d49547c7d0098881d762bc58e5/crates/cairo-lang-language-server/src/lang/diagnostics/state/mod.rs#L103)):*
> ```XML
>     pub fn from_state(state: &mut State, workers_num: usize) -> Self {
>         Self {
>             db_snapshots: DbSnapshots((0..workers_num).map(|_| state.db.snapshot()).collect()),
> ```

Why is it needed to take multiple snapshots here (and i.e. not open files?)


<!-- Sent from Reviewable.io -->

2024-10-16 08:26 UTC, mkaput commented
replacing this PR with a stack that starts here: https://github.com/starkware-libs/cairo/pull/6492

2024-10-16 08:26 UTC, closed without merging