Implemented hovers for literals
starkware-libs/cairo pull request #6478
Opened 2024-10-11 10:13 UTC by integraledelebesgue

Introduced changes:
* LS now displays hovers with descriptions above literal expressions
* Descriptions contain information about the type and possible values in available representations

2024-10-11 11:16 UTC, mkaput reviewed
> Reviewed 6 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @integraledelebesgue)

___
*[`crates/cairo-lang-language-server/src/ide/hover/mod.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O8vGhKAAAAwtEoTyffe:-O8vGhKAAAAwtEoTyfff:b-srahzo) ([raw file](https://github.com/starkware-libs/cairo/blob/f56f475d4d249575f503faa8c4c7768ddba6dc80/crates/cairo-lang-language-server/src/ide/hover/mod.rs#L22)):*
> ```XML
>     let position = params.text_document_position_params.position.to_cairo();
> 
>     db.find_hover_target_at_position(file_id, position)?.render(db, file_id)
> ```

ok, this is basically the exact opposite of what renderers were meant for :D 

each renderer's responsibility is to find its exact target **inside** and return `None` if they had no target. by chaining renders, we formed a chain of fallbacks. this allows treating each hover kind as some kind of a black box, each renderer being completely separate from each other.

that should happen here is that:
1. you try to show a hover for a literal, it would quickly return None if hovering over non-literal terminal
2. then try showing a definition of _something_
3. finally try legacy hovers which we want to eradicate
___
*[`crates/cairo-lang-language-server/src/ide/hover/range.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O8vGRKW27YniaybZbtj:-O8vGRKW27YniaybZbtk:b-4p2etf) ([raw file](https://github.com/starkware-libs/cairo/blob/f56f475d4d249575f503faa8c4c7768ddba6dc80/crates/cairo-lang-language-server/src/ide/hover/range.rs#L18)):*
> ```XML
>             .span_without_trivia(db.upcast())
>             .position_in_file(db.upcast(), file_id)
>             .map(|p| p.to_lsp())
> ```

TBH this isn't a chain of method calls that is worth deduplicating. It is long, but clearly leads to the result and has no complex logic.
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/legacy.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O8vG5J61Bf9Oeqi76a6:-O8vG5J61Bf9Oeqi76a7:b7sr664) ([raw file](https://github.com/starkware-libs/cairo/blob/f56f475d4d249575f503faa8c4c7768ddba6dc80/crates/cairo-lang-language-server/src/ide/hover/render/legacy.rs#L95)):*
> ```XML
>             s
>         }
>         other => format!("Type: {}", other.ty().format(db)),
> ```

please do not touch legacy hovers
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/mod.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O8vG-v-5J35RSigU6VT:-O8vG-v-5J35RSigU6VU:betat3q) ([raw file](https://github.com/starkware-libs/cairo/blob/f56f475d4d249575f503faa8c4c7768ddba6dc80/crates/cairo-lang-language-server/src/ide/hover/render/mod.rs#L3)):*
> ```XML
> pub(super) use self::definition::*;
> pub(super) use self::legacy::*;
> pub(super) use self::literal::*;
> ```

all these `(super)` are unnecessary, the bring no value


<!-- Sent from Reviewable.io -->

2024-10-14 15:14 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: 1 of 10 files reviewed, 4 unresolved discussions (waiting on @mkaput)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/mod.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O8vG-v-5J35RSigU6VT:-O9A_rxF0OQOj6msLYQm:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f56f475d4d249575f503faa8c4c7768ddba6dc80/crates/cairo-lang-language-server/src/ide/hover/render/mod.rs#L3)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

all these `(super)` are unnecessary, the bring no value
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-15 00:16 UTC, piotmag769 requested changes
> Reviewed 1 of 9 files at r1, 6 of 8 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: all files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, and @orizi)

___
*[`crates/cairo-lang-language-server/src/ide/hover/mod.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9CP5n04Ymey98_zLnd:-O9CP5n04Ymey98_zLne:b-p4zu8g) ([raw file](https://github.com/starkware-libs/cairo/blob/737cc88d14a17e1e8b46a6d2d4061aa4b6984980/crates/cairo-lang-language-server/src/ide/hover/mod.rs#L21)):*
> ```XML
>     render::definition(db, &identifier, file_id).or_else(|| render::legacy(db, &identifier))
> 
>     // TODO(mkaput): If client only supports plaintext, strip markdown formatting here like RA.
> ```

Why did we remove that?
___
*[`crates/cairo-lang-language-server/src/ide/hover/range.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O8vGRKW27YniaybZbtj:-O9CPb6k12blBAPZfkIJ:b-6vgdx0) ([raw file](https://github.com/starkware-libs/cairo/blob/f56f475d4d249575f503faa8c4c7768ddba6dc80/crates/cairo-lang-language-server/src/ide/hover/range.rs#L18)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

TBH this isn't a chain of method calls that is worth deduplicating. It is long, but clearly leads to the result and has no complex logic.
</blockquote></details>

Agree, overengineering here
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9CR0T42duRfsM5whRw:-O9CR0T42duRfsM5whRx:b-x8zblz) ([raw file](https://github.com/starkware-libs/cairo/blob/18e189c141025bde19daa719f628a68516ac4fe3/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L43)):*
> ```XML
> 
>     let number_type = type_suffix.as_ref().map(SmolStr::as_str).unwrap_or("felt252");
>     let type_path = if number_type == "felt252" { "core" } else { "core::integer" };
> ```

You should get the type from semantic resolver (you would have to travel deeper like in e.g. `missing_traits_actions`), this will result in wrong result e.g. for 

```rs
let _: u8 = 60;
```

alternatively you can just drop the type if it is too much work since it will get pretty complex, wdyt @mkaput?
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 93 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9CX8Eq8LZHiC0jj9rU:-O9CX8Eq8LZHiC0jj9rV:b19wsjm) ([raw file](https://github.com/starkware-libs/cairo/blob/18e189c141025bde19daa719f628a68516ac4fe3/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L93)):*
> ```XML
>             {TITLE}: `'{string}' ({numeric:#x})`
>             {RULER}
>             Type: `core::felt252`
> ```

I can do sth like `let _: u8 = 'a';` and it will work, you cannot assume a type this way here


<!-- Sent from Reviewable.io -->

2024-10-15 07:52 UTC, mkaput requested changes
> Reviewed 6 of 8 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: all files reviewed, 11 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9E9OJY98Vsa8KALPAG:-O9E9OJY98Vsa8KALPAH:b-x1gpw7) (no related file):*
please cover this feature thoroughly in e2e test. don't forget about unhappy cases!

___
___
*[`crates/cairo-lang-language-server/src/ide/hover/mod.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9CP5n04Ymey98_zLnd:-O9E8R_515WzkL2VAjVL:b-36khvw) ([raw file](https://github.com/starkware-libs/cairo/blob/737cc88d14a17e1e8b46a6d2d4061aa4b6984980/crates/cairo-lang-language-server/src/ide/hover/mod.rs#L21)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Why did we remove that?
</blockquote></details>

yeah, this comment is still relevant
___
*[`crates/cairo-lang-language-server/src/ide/hover/mod.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9E8l7R7jikRyCncxKL:-O9E8l7R7jikRyCncxKM:b2hoer9) ([raw file](https://github.com/starkware-libs/cairo/blob/18e189c141025bde19daa719f628a68516ac4fe3/crates/cairo-lang-language-server/src/ide/hover/mod.rs#L22)):*
> ```XML
> 
>     if let Some(hover) =
>         db.find_literal_at_position(file_id, position).map(|literal| literal.render(db, file_id))
> ```

use `find_syntax_node_at_position` here and narrow it down to literal within `render::literal` function
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/definition.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9E7T5b-3GzNDMYnXv9:-O9E7T5b-3GzNDMYnXvA:b-a5jkve) ([raw file](https://github.com/starkware-libs/cairo/blob/18e189c141025bde19daa719f628a68516ac4fe3/crates/cairo-lang-language-server/src/ide/hover/render/definition.rs#L9)):*
> ```XML
> use crate::ide::hover::markdown_contents;
> use crate::ide::hover::range::HoverRange;
> use crate::ide::hover::render::markdown::{RULE, fenced_code_block};
> ```

run `scripts/rust_fmt.sh`. you may need to merge latest `main` changes
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/legacy.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O8vG5J61Bf9Oeqi76a6:-O9E7eu73IwyvoX1FoaU:b-37dods) ([raw file](https://github.com/starkware-libs/cairo/blob/f56f475d4d249575f503faa8c4c7768ddba6dc80/crates/cairo-lang-language-server/src/ide/hover/render/legacy.rs#L95)):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

Sure, I restored the old snippet and also added one branch that makes the `legacy` rendered ignore literals.
</blockquote></details>

no need for doing this given that you catch literals before even attempting to try rendering `legacy`, isn't it?
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 24 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9E8vesEd__OM6S3ASw:-O9E8vesEd__OM6S3ASx:b-mb8rcn) ([raw file](https://github.com/starkware-libs/cairo/blob/18e189c141025bde19daa719f628a68516ac4fe3/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L24)):*
> ```XML
> impl Literal {
>     /// Generate a hover containing value of the literal and its type.
>     pub fn render(&self, db: &AnalysisDatabase, file_id: FileId) -> Option<Hover> {
> ```

please make this a free-standing function as other render ones are written. let's keep code uniform :smiley: 
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9CR0T42duRfsM5whRw:-O9E9693EZB_FDinQddD:b1z4q4k) ([raw file](https://github.com/starkware-libs/cairo/blob/18e189c141025bde19daa719f628a68516ac4fe3/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L43)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

You should get the type from semantic resolver (you would have to travel deeper like in e.g. `missing_traits_actions`), this will result in wrong result e.g. for 

```rs
let _: u8 = 60;
```

alternatively you can just drop the type if it is too much work since it will get pretty complex, wdyt @mkaput?
</blockquote></details>

I think the only correct path here is to use type information from the semantic model. Any heuristic attempts will be doomed to fail + we would have to spend time keeping them up to date with any type inference changes that may happen in the future.
___
*[`crates/cairo-lang-language-server/src/lang/db/syntax.rs` line 62 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9E7uNQ8QUpTg3DiLfb:-O9E7uNQ8QUpTg3DiLfc:b-gjohw3) ([raw file](https://github.com/starkware-libs/cairo/blob/18e189c141025bde19daa719f628a68516ac4fe3/crates/cairo-lang-language-server/src/lang/db/syntax.rs#L62)):*
> ```XML
>     /// [`TerminalLiteralNumber`], [`TerminalString`] or [`TerminalShortString`]
>     /// at the given [`TextPosition`] in file.
>     fn find_literal_at_position(&self, file: FileId, position: TextPosition) -> Option<Literal> {
> ```

in general we have an unspoken rule that no `ide` stuff should be used from `lang` side -- this always means that things are wrongly architected because we have a backward dependency in code

the code you're doing here is 100% fine to be kept within `ide::hover::literal` module, as private logic
___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 23 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9E8E445SVxBmZyZfIN:-O9E8E445SVxBmZyZfIO:b7swn7) ([raw file](https://github.com/starkware-libs/cairo/blob/18e189c141025bde19daa719f628a68516ac4fe3/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L23)):*
> ```XML
> use cairo_lang_syntax::node::kind::SyntaxKind;
> use cairo_lang_syntax::node::utils::is_grandparent_of_kind;
> use cairo_lang_syntax::node::{ast, SyntaxNode, Terminal, TypedStablePtr, TypedSyntaxNode};
> ```

old formatting


<!-- Sent from Reviewable.io -->

2024-10-16 10:04 UTC, mkaput reviewed
> Reviewed 6 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: 8 of 10 files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @orizi, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-10-16 10:36 UTC, piotmag769 reviewed
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: all files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @orizi)



<!-- Sent from Reviewable.io -->

2024-10-16 10:57 UTC, mkaput requested changes
> Reviewed 1 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 17 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9JyN50Bgd0KBML-NgC:-O9JyN50Bgd0KBML-NgD:b-i5p9pz) ([raw file](https://github.com/starkware-libs/cairo/blob/7af072903c546aa3ac75e1d0010f21edac61cc89/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L17)):*
> ```XML
> const RULER: &str = "***";
> 
> /// Narrow down [`SyntaxNode`] to [`TerminalLiteralNumber`], [`TermialString`] or
> ```

that's the form we should use in docs. see how rust's `std` is documented



_Suggestion:_
```XML
/// Narrows
```


<!-- Sent from Reviewable.io -->

2024-10-16 12:47 UTC, mkaput requested changes
> Reviewed 1 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: all files reviewed, 8 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 15 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9KKxGFEq9EM0LRdTep:-O9KKxGFEq9EM0LRdTeq:b-i4l2aw) ([raw file](https://github.com/starkware-libs/cairo/blob/7af072903c546aa3ac75e1d0010f21edac61cc89/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L15)):*
> ```XML
> 
> const TITLE: &str = "value of literal";
> const RULER: &str = "***";
> ```

I would personally inline both of these constants because they make “templates” less readable to me. wdyt?
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 56 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9KL_Yn9vsueTk8Ip4C:-O9KL_Yn9vsueTk8Ip4D:b1533zu) ([raw file](https://github.com/starkware-libs/cairo/blob/7af072903c546aa3ac75e1d0010f21edac61cc89/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L56)):*
> ```XML
>         {TITLE}: `{value} ({value:#x} | {value:#b})`
>         {RULER}
>         Type: `{type_path}::{number_type}`
> ```

I don't like this `Type: ` part, let's just put it as-is first, like RA:
![image.png](https://files.reviewableusercontent.io/images/reviewable/3450050/gG6HNC4uGYobX_Oo9re0W8S2/image.png)
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 57 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9KM-hB5FPGiUJD-KBC:-O9KM-hB5FPGiUJD-KBD:b-lea5y5) ([raw file](https://github.com/starkware-libs/cairo/blob/7af072903c546aa3ac75e1d0010f21edac61cc89/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L57)):*
> ```XML
>         {RULER}
>         Type: `{type_path}::{number_type}`
>         "
> ```

can you add all the nice conversions that https://www.stark-utils.xyz/converter does?


<!-- Sent from Reviewable.io -->

2024-10-17 20:07 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: 9 of 10 files reviewed, 8 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/hover/mod.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9CP5n04Ymey98_zLnd:-O9J5pX-DLsCJRX9757W:b-5g54iy) ([raw file](https://github.com/starkware-libs/cairo/blob/737cc88d14a17e1e8b46a6d2d4061aa4b6984980/crates/cairo-lang-language-server/src/ide/hover/mod.rs#L21)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

yeah, this comment is still relevant
</blockquote></details>

I removed it by accident :skull:
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9CR0T42duRfsM5whRw:-O9R4MIA15VjZaGaevwC:bmbho3y) ([raw file](https://github.com/starkware-libs/cairo/blob/18e189c141025bde19daa719f628a68516ac4fe3/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L43)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I think the only correct path here is to use type information from the semantic model. Any heuristic attempts will be doomed to fail + we would have to spend time keeping them up to date with any type inference changes that may happen in the future.
</blockquote></details>

I implemented a new type acquisition logic. It works fine when applied to literals in a function context. However, my method doesn't apply to const definitons because they have no associated `FunctionWithBodyId`.
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 93 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9CX8Eq8LZHiC0jj9rU:-O9R4kzO8hf-o53UNxUd:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/18e189c141025bde19daa719f628a68516ac4fe3/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L93)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

I can do sth like `let _: u8 = 'a';` and it will work, you cannot assume a type this way here
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 15 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9KKxGFEq9EM0LRdTep:-O9R451i6hdETE5VjkNS:b-jww2j3) ([raw file](https://github.com/starkware-libs/cairo/blob/7af072903c546aa3ac75e1d0010f21edac61cc89/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L15)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I would personally inline both of these constants because they make “templates” less readable to me. wdyt?
</blockquote></details>

Sure, not much gain from making them constant :) 
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 56 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9KL_Yn9vsueTk8Ip4C:-O9R4jE_1faYQAOv8VNN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7af072903c546aa3ac75e1d0010f21edac61cc89/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L56)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I don't like this `Type: ` part, let's just put it as-is first, like RA:
![image.png](https://files.reviewableusercontent.io/images/reviewable/3450050/gG6HNC4uGYobX_Oo9re0W8S2/image.png)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 23 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9E8E445SVxBmZyZfIN:-O9R4q1-DDZJaFSw4zsZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/18e189c141025bde19daa719f628a68516ac4fe3/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L23)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

old formatting
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-17 20:14 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: 9 of 10 files reviewed, 8 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 17 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9JyN50Bgd0KBML-NgC:-O9R5lFk-Y6jle88T3at:b-rry47u) ([raw file](https://github.com/starkware-libs/cairo/blob/7af072903c546aa3ac75e1d0010f21edac61cc89/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L17)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

that's the form we should use in docs. see how rust's `std` is documented
</blockquote></details>

Sure, I changed it. Both `hover::mod` and `hover::render::definition` have docstrings in an imperative form. Should I correct them too?


<!-- Sent from Reviewable.io -->

2024-10-18 08:22 UTC, mkaput requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: all files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9CR0T42duRfsM5whRw:-O9ThEmIDnaMzppZVUsQ:bae784m) ([raw file](https://github.com/starkware-libs/cairo/blob/18e189c141025bde19daa719f628a68516ac4fe3/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L43)):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

I implemented a new type acquisition logic. It works fine when applied to literals in a function context. However, my method doesn't apply to const definitons because they have no associated `FunctionWithBodyId`.
</blockquote></details>

But I see you've fixed that obstacle anyway, haven't you? :)
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 17 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9JyN50Bgd0KBML-NgC:-O9TglTuDuvUYstDxBk9:bf9m5tg) ([raw file](https://github.com/starkware-libs/cairo/blob/7af072903c546aa3ac75e1d0010f21edac61cc89/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L17)):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

Sure, I changed it. Both `hover::mod` and `hover::render::definition` have docstrings in an imperative form. Should I correct them too?
</blockquote></details>

the rule of thumb is don't touch the code that you don't have to :upside_down_face: 

yeah we all tend to mix these forms everywhere, and it sometimes slip review :sad:
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 69 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9Ti-zG9D_1OIkhZWCO:-O9Ti-zG9D_1OIkhZWCP:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/06dfadb159d9558694f3222a8f380fc2e3580b60/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L69)):*
> ```XML
> }
> 
> // TODO: think about something better
> ```

?
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 116 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9ThpRD5BfGfPx-qG5S:-O9ThpRD5BfGfPx-qG5T:b-9p36r6) ([raw file](https://github.com/starkware-libs/cairo/blob/06dfadb159d9558694f3222a8f380fc2e3580b60/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L116)):*
> ```XML
>     db: &AnalysisDatabase,
>     literal: &TerminalString,
>     r#type: &str,
> ```

that's the convention we have everywhere, so it's fine name



_Suggestion:_
```XML
ty
```


<!-- Sent from Reviewable.io -->

2024-10-18 15:43 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: all files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9CR0T42duRfsM5whRw:-O9VG222CkjwglQkaCsh:b3x8i9h) ([raw file](https://github.com/starkware-libs/cairo/blob/18e189c141025bde19daa719f628a68516ac4fe3/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L43)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

But I see you've fixed that obstacle anyway, haven't you? :)
</blockquote></details>

A solution the [TODO you noticed](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9Ti-zG9D_1OIkhZWCO) refers to works, but not exactly as I would like. I described the problem in that discussion.
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 69 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9Ti-zG9D_1OIkhZWCO:-O9VHDCZBR4WpcYrvGeU:bhjl090) ([raw file](https://github.com/starkware-libs/cairo/blob/06dfadb159d9558694f3222a8f380fc2e3580b60/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L69)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

?
</blockquote></details>

The problem with that solution is that it returns only a type name without the full path. That's because how `SyntaxNode::get_text` works. I can't use the semantic analysis machinery I utilise in `find_type_in_function_context` because, as I understand, it works only in function context :(
That's why I left `TODO` :))


<!-- Sent from Reviewable.io -->

2024-10-21 09:22 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: all files reviewed, 8 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 80 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9iMxElAs9wBUsh7NLw:-O9iMxElAs9wBUsh7NLx:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/06dfadb159d9558694f3222a8f380fc2e3580b60/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L80)):*
> ```XML
>     let declaration = ItemConstant::from_syntax_node(db, node);
>     let r#type = declaration.type_clause(db).ty(db).as_syntax_node().get_text(db);
>     Some(r#type)
> ```





_Suggestion:_
```XML
    Some(declaration.type_clause(db).ty(db).as_syntax_node().get_text(db))
```
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 116 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9ThpRD5BfGfPx-qG5S:-O9iN4WlDU5Gs77qBJQe:b-tjot59) ([raw file](https://github.com/starkware-libs/cairo/blob/06dfadb159d9558694f3222a8f380fc2e3580b60/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L116)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

that's the convention we have everywhere, so it's fine name
</blockquote></details>

agreed - and everywhere else in this PR.
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 143 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9iNN6K7oDlkyIG4OOB:-O9iNN6K7oDlkyIG4OOC:b-bvakyc) ([raw file](https://github.com/starkware-libs/cairo/blob/06dfadb159d9558694f3222a8f380fc2e3580b60/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L143)):*
> ```XML
> /// Formats the short string literal writing its textual and numeric value along with the
> /// `core::felt252` type.
> fn short_string(
> ```

i think this would be better (for the other 2 functions as well) - as I find the lack of context in the call itself confusing.



_Suggestion:_
```XML
fn short_string_hover(
```


<!-- Sent from Reviewable.io -->

2024-10-21 14:19 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: 8 of 11 files reviewed, 8 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 80 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9iMxElAs9wBUsh7NLw:-O9jQxYs2nXVUgyRYi-l:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/06dfadb159d9558694f3222a8f380fc2e3580b60/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L80)):*
> ```XML
>     let declaration = ItemConstant::from_syntax_node(db, node);
>     let r#type = declaration.type_clause(db).ty(db).as_syntax_node().get_text(db);
>     Some(r#type)
> ```

Done.
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 116 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9ThpRD5BfGfPx-qG5S:-O9jQzTCAq0rg6hfBw0i:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/06dfadb159d9558694f3222a8f380fc2e3580b60/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L116)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

agreed - and everywhere else in this PR.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 143 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9iNN6K7oDlkyIG4OOB:-O9jR-LkEISPdVEeTUHa:b-3jp52o) ([raw file](https://github.com/starkware-libs/cairo/blob/06dfadb159d9558694f3222a8f380fc2e3580b60/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L143)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think this would be better (for the other 2 functions as well) - as I find the lack of context in the call itself confusing.
</blockquote></details>

Indeed, the call itself does not carry the whole context. However, it's easily discoverable via return type, so I think it's no use duplicating that informaton in the name.


<!-- Sent from Reviewable.io -->

2024-10-21 16:59 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: 8 of 11 files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 143 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9iNN6K7oDlkyIG4OOB:-O9k-xcz1rqk_UhKrRcE:bq7d51e) ([raw file](https://github.com/starkware-libs/cairo/blob/06dfadb159d9558694f3222a8f380fc2e3580b60/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L143)):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

Indeed, the call itself does not carry the whole context. However, it's easily discoverable via return type, so I think it's no use duplicating that informaton in the name.
</blockquote></details>

the return type does not appear in the callsite - my issue it is that the callsite of this function seems very weird - it sounds like construction - but it is a very specific function call.
`Hover::short_string` would have been ok - but this seems unclear to me.


<!-- Sent from Reviewable.io -->

2024-10-21 17:05 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: 8 of 11 files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 143 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9iNN6K7oDlkyIG4OOB:-O9k1ATeClPCb--oLA0M:bqlchop) ([raw file](https://github.com/starkware-libs/cairo/blob/06dfadb159d9558694f3222a8f380fc2e3580b60/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L143)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

the return type does not appear in the callsite - my issue it is that the callsite of this function seems very weird - it sounds like construction - but it is a very specific function call.
`Hover::short_string` would have been ok - but this seems unclear to me.
</blockquote></details>

Sure, I see your point. I changed the names. I've only kept the top level function name - `render::literal` - the same to keep it consistent with already existing renderers.


<!-- Sent from Reviewable.io -->

2024-10-21 17:09 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: 8 of 11 files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9E9OJY98Vsa8KALPAG:-O9k1paB7jT0gLDDeG_Y:b-9jwxo7) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

please cover this feature thoroughly in e2e test. don't forget about unhappy cases!
</blockquote></details>

I added some tests for various scenarios. Please have a look at them. I don't know whether I can assert some error messages in them. In my implementation, hovers appear even when e.g. types are mismatched (see the example [here](https://github.com/starkware-libs/cairo/blob/c3b177279a9e8382bb74b71ce1692925d82d9dbd/crates/cairo-lang-language-server/tests/test_data/hover/basic.txt#L676)).

___


<!-- Sent from Reviewable.io -->

2024-10-21 17:43 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478#-:-O9kAD6T75Ro5oRqNYvF:bnfp4nl)* status: 9 of 11 files reviewed, 6 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @mkaput, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-10-21 21:44 UTC, piotmag769 reviewed
> Reviewed 1 of 3 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: all files reviewed, 8 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @mkaput)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 69 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9Ti-zG9D_1OIkhZWCO:-O9kztXT1pXOkuxaIUVt:b-gslqdh) ([raw file](https://github.com/starkware-libs/cairo/blob/06dfadb159d9558694f3222a8f380fc2e3580b60/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L69)):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

The problem with that solution is that it returns only a type name without the full path. That's because how `SyntaxNode::get_text` works. I can't use the semantic analysis machinery I utilise in `find_type_in_function_context` because, as I understand, it works only in function context :(
That's why I left `TODO` :))
</blockquote></details>

Create an issue and mark it with issue number pls
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 43 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9l16HA2nDAUfcNbs8b:-O9l16HA2nDAUfcNbs8c:b-pxmbhs) ([raw file](https://github.com/starkware-libs/cairo/blob/c3b177279a9e8382bb74b71ce1692925d82d9dbd/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L43)):*
> ```XML
>             short_string_hover(db, &literal, &ty, file_id)
>         }
>         _ => None,
> ```

It may be out of scope, but what about fixed size arrays? `let x: [u8; 2] = [1, 2]` cc @mkaput 
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 111 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9l0oTM7_vVinAUgsub:-O9l0oTM7_vVinAUgsuc:bcv1v6l) ([raw file](https://github.com/starkware-libs/cairo/blob/c3b177279a9e8382bb74b71ce1692925d82d9dbd/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L111)):*
> ```XML
> 
> /// Formats the number literal writing it along with the `core::byte_array::ByteArray` type.
> fn string_hover(
> ```

Should we support that? Are there plans for byte array consts? cc @orizi
___
*[`crates/cairo-lang-language-server/tests/test_data/hover/basic.txt` line 695 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9kzR4O0y1GyuODFudi:-O9kzR4O0y1GyuODFudj:bag7uus) ([raw file](https://github.com/starkware-libs/cairo/blob/c3b177279a9e8382bb74b71ce1692925d82d9dbd/crates/cairo-lang-language-server/tests/test_data/hover/basic.txt#L695)):*
> ```help
> // = popover
> ```cairo
> core::integer::u8
> ```

This doesn't work, there are not ByteArray literals rn


<!-- Sent from Reviewable.io -->

2024-10-22 07:46 UTC, mkaput requested changes
> Reviewed 1 of 3 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: all files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9E9OJY98Vsa8KALPAG:-O9n9Cfa2XL7ZHDJHUHm:b-40fbja) (no related file):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

I added some tests for various scenarios. Please have a look at them. I don't know whether I can assert some error messages in them. In my implementation, hovers appear even when e.g. types are mismatched (see the example [here](https://github.com/starkware-libs/cairo/blob/c3b177279a9e8382bb74b71ce1692925d82d9dbd/crates/cairo-lang-language-server/tests/test_data/hover/basic.txt#L676)).
</blockquote></details>

We're only interested in hovers in these tests, so it is very very fine not to assert on diagnostics :)

___
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 69 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9Ti-zG9D_1OIkhZWCO:-O9nAnvv4kwUGsMPPyNe:b-s1qbt3) ([raw file](https://github.com/starkware-libs/cairo/blob/06dfadb159d9558694f3222a8f380fc2e3580b60/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L69)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Create an issue and mark it with issue number pls
</blockquote></details>

I would rather fix this here. Shipping incorrect & misleading logic is worse than not shipping it at all.
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 43 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9l16HA2nDAUfcNbs8b:-O9n9QPd0XOGuWq5CotK:bfzze2x) ([raw file](https://github.com/starkware-libs/cairo/blob/c3b177279a9e8382bb74b71ce1692925d82d9dbd/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L43)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

It may be out of scope, but what about fixed size arrays? `let x: [u8; 2] = [1, 2]` cc @mkaput
</blockquote></details>

1. out of scope, this is not a literal
2. what would you like to see in these hovers?

anyway, make a separate task for these if you wish :)
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 95 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9nAXZFARIWYA2YSPz2:-O9nAXZFARIWYA2YSPz3:b-bkjs7t) ([raw file](https://github.com/starkware-libs/cairo/blob/c3b177279a9e8382bb74b71ce1692925d82d9dbd/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L95)):*
> ```XML
>         {ty}
>         ```
>         ***
> ```

shouldn't this be dashes?



_Suggestion:_
```XML
---
```
___
*[`crates/cairo-lang-language-server/tests/test_data/hover/basic.txt` line 81 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9n9mAMDTU9T-bn2sjO:-O9n9mAMDTU9T-bn2sjP:b-poft5d) ([raw file](https://github.com/starkware-libs/cairo/blob/c3b177279a9e8382bb74b71ce1692925d82d9dbd/crates/cairo-lang-language-server/tests/test_data/hover/basic.txt#L81)):*
> ```help
> }
> 
> const SOME_CONST: felt252 = 0x<caret>2137;
> ```

please move these tests to a new fixture, say `literals.txt`

we don't want to grow fixtures horizontally because they quickly become unreadable
___
*[`crates/cairo-lang-language-server/tests/test_data/hover/basic.txt` line 680 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9nA0zQ659kqCy5Gw90:-O9nA0zQ659kqCy5Gw91:b-llii9a) ([raw file](https://github.com/starkware-libs/cairo/blob/c3b177279a9e8382bb74b71ce1692925d82d9dbd/crates/cairo-lang-language-server/tests/test_data/hover/basic.txt#L680)):*
> ```help
>     let a: u32 = 0x2<caret>137_felt252;
> // = highlight
>     let a: u32 = <sel>0x2137_felt252</sel>;
> ```

this is code, do not use memes (esp. controversial) here


<!-- Sent from Reviewable.io -->

2024-10-22 08:21 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: 8 of 13 files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/tests/test_data/hover/basic.txt` line 81 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9n9mAMDTU9T-bn2sjO:-O9nJCVPDQbA6fhy7Erh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c3b177279a9e8382bb74b71ce1692925d82d9dbd/crates/cairo-lang-language-server/tests/test_data/hover/basic.txt#L81)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

please move these tests to a new fixture, say `literals.txt`

we don't want to grow fixtures horizontally because they quickly become unreadable
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-22 08:35 UTC, orizi reviewed
> Reviewed 1 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: 9 of 13 files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-10-22 08:36 UTC, mkaput reviewed
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-10-23 09:30 UTC, piotmag769 reviewed
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, and @integraledelebesgue)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 43 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9l16HA2nDAUfcNbs8b:-O9shTqkCDwqqXPh933O:bmcmkc7) ([raw file](https://github.com/starkware-libs/cairo/blob/c3b177279a9e8382bb74b71ce1692925d82d9dbd/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L43)):*
>what would you like to see in these hovers?

Actually no idea, I would check what RA does here ;p would leave it for now though


<!-- Sent from Reviewable.io -->

2024-10-28 17:05 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 69 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9Ti-zG9D_1OIkhZWCO:-OAJ4b5EEQVLYGtVk7KQ:b3qs3u6) ([raw file](https://github.com/starkware-libs/cairo/blob/06dfadb159d9558694f3222a8f380fc2e3580b60/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L69)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I would rather fix this here. Shipping incorrect & misleading logic is worse than not shipping it at all.
</blockquote></details>

We improved this logic. Please have a look @mkaput :)


<!-- Sent from Reviewable.io -->

2024-10-28 17:57 UTC, piotmag769 reviewed
> Reviewed 2 of 2 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @mkaput)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6478#-OAJGf2N2kRChTP2v48B:-OAJGf2N2kRChTP2v48C:b-tztmwa) (no related file):*
Please add tests for consts

___
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 111 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9l0oTM7_vVinAUgsub:-OAJGRdI6MS03gmItQas:bvx92y2) ([raw file](https://github.com/starkware-libs/cairo/blob/c3b177279a9e8382bb74b71ce1692925d82d9dbd/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L111)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Should we support that? Are there plans for byte array consts? cc @orizi
</blockquote></details>

Still stand by the point that we shouldn't display anything there cc @mkaput 
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 78 at r12](https://reviewable.io/reviews/starkware-libs/cairo/6478#-OAJGD--64QAZk8RqkTI:-OAJGD--64QAZk8RqkTJ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/d6b9dc63903ee851167f75184e318d02c38c821b/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L78)):*
> ```XML
>     while node.kind(db) != SyntaxKind::ItemConstant {
>         node = node.parent()?;
>     }
> ```





_Suggestion:_
```XML
    let const_node = db.first_ancestor_of_kind(node, SyntaxKinda::ItemConstant);
```


<!-- Sent from Reviewable.io -->

2024-10-29 11:46 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: 11 of 13 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6478#-OAJGf2N2kRChTP2v48B:-OAN2Vwh9LyDiztRSxfI:bgbzpnz) (no related file):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Please add tests for consts
</blockquote></details>

I have one happy and one unhappy case at the moment. Please let me know if this is enough

___
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 43 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9l16HA2nDAUfcNbs8b:-OAN-2Pz3ucmsppYZrpF:b-dw26c6) ([raw file](https://github.com/starkware-libs/cairo/blob/c3b177279a9e8382bb74b71ce1692925d82d9dbd/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L43)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

>what would you like to see in these hovers?

Actually no idea, I would check what RA does here ;p would leave it for now though
</blockquote></details>

RA simply shows values of particular elements, as my implementation does at the moment
___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 111 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9l0oTM7_vVinAUgsub:-OAN2J2I-uQptFsXtohn:b-1541a0) ([raw file](https://github.com/starkware-libs/cairo/blob/c3b177279a9e8382bb74b71ce1692925d82d9dbd/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L111)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I think we can simply show the type? Indeed, the value of the literal is not informative here as I think now :thinking:
</blockquote></details>

Sure, I show only types now. However, in case of mismatch:
```rs
let x: u8 = "0";
```
hover shows the declared type - `u8`.
I don't know whether it's very problematic. Please let me know @mkaput @piotmag769 


<!-- Sent from Reviewable.io -->

2024-10-29 11:48 UTC, piotmag769 reviewed
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @orizi)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 111 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9l0oTM7_vVinAUgsub:-OAN57VYBY1lUKtv1Lh8:bihbnmh) ([raw file](https://github.com/starkware-libs/cairo/blob/c3b177279a9e8382bb74b71ce1692925d82d9dbd/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L111)):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

Sure, I show only types now. However, in case of mismatch:
```rs
let x: u8 = "0";
```
hover shows the declared type - `u8`.
I don't know whether it's very problematic. Please let me know @mkaput @piotmag769
</blockquote></details>

It's fine for me. Literals don't have types by themselves


<!-- Sent from Reviewable.io -->

2024-10-29 11:55 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: 12 of 13 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/ide/hover/render/literal.rs` line 78 at r12](https://reviewable.io/reviews/starkware-libs/cairo/6478#-OAJGD--64QAZk8RqkTI:-OAN6d7V83nWhOu05djv:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d6b9dc63903ee851167f75184e318d02c38c821b/crates/cairo-lang-language-server/src/ide/hover/render/literal.rs#L78)):*
> ```XML
>     while node.kind(db) != SyntaxKind::ItemConstant {
>         node = node.parent()?;
>     }
> ```

Done.
___
*[`crates/cairo-lang-language-server/tests/test_data/hover/basic.txt` line 695 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6478#-O9kzR4O0y1GyuODFudi:-OAN76lT1sinWO-f7TPM:b-u7iqi1) ([raw file](https://github.com/starkware-libs/cairo/blob/c3b177279a9e8382bb74b71ce1692925d82d9dbd/crates/cairo-lang-language-server/tests/test_data/hover/basic.txt#L695)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

This doesn't work, there are not ByteArray literals rn
</blockquote></details>

Is it still relevant since we only display types for string literals?


<!-- Sent from Reviewable.io -->

2024-10-29 12:00 UTC, piotmag769 reviewed
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, and @orizi)



<!-- Sent from Reviewable.io -->

2024-10-29 12:01 UTC, piotmag769 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478#-:-OAN8eoz2u4fsLj64cua:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @orizi)



<!-- Sent from Reviewable.io -->

2024-10-30 10:48 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478#-:-OAS1RQyBRSoagjfijWz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @orizi)



<!-- Sent from Reviewable.io -->

2024-10-31 08:46 UTC, orizi approved these changes
> Reviewed 1 of 8 files at r2, 6 of 8 files at r5, 1 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6478)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)



<!-- Sent from Reviewable.io -->

2024-11-04 10:26 UTC, merged