feat: add config change + version check
starkware-libs/cairo pull request #6497
Opened 2024-10-17 06:12 UTC by marcuspang

2024-10-17 06:12 UTC, lotem-starkware commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6497)
<!-- Reviewable:end -->

2024-10-17 11:01 UTC, mkaput requested changes
> Reviewed 1 of 3 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6497)* status: all files reviewed, 5 unresolved discussions (waiting on @Arcticae, @Draggu, @marcuspang, @mkaput, @orizi, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9P5cJWDUD7viYhgoWD:-O9P5cJWDUD7viYhgoWE:be5ck22) (no related file):*
:star_struck: 

___
___
*[`vscode-cairo/package.json` line 144 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9P3Q17-GxIMKlEe5Qk:-O9P3Q17-GxIMKlEe5Ql:bswabs9) ([raw file](https://github.com/starkware-libs/cairo/blob/c9cc6237cbf82812f76a7a50f23494a9039026a6/vscode-cairo/package.json#L144)):*
> ```JSON
>             "description": "Show Cairo Language Server information",
>             "scope": "window"
>           }
> ```

I did a quick search in popular extensions and these name & description pattern seem to be a convergent style used by most of them.



_Suggestion:_
```JSON
          "cairo1.showInStatusBar": {
            "type": "boolean",
            "default": true,
            "description": "Show CairoLS information in the status bar.",
            "scope": "window"
          }
```
___
*[`vscode-cairo/src/context.ts` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9P6L39EdK43lbJhxX8:-O9P6L39EdK43lbJhxX9:bfpbdut) ([raw file](https://github.com/starkware-libs/cairo/blob/c9cc6237cbf82812f76a7a50f23494a9039026a6/vscode-cairo/src/context.ts#L12)):*
> ```XML
>       }),
>     );
>     const statusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left, 100);
> ```

Consider encapsulating all the logic and state in a `StatusBar` class, that is:
1. Move `statusBarItem` instance inside it, and keep `StatusBar` instance as a field in this `Context`. You should be able to use [definite assignment assertion](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#strict-class-initialization) to resolve cyclic dependency.
2. Make `setupStatusBar` etc. plain methods there.
___
*[`vscode-cairo/src/extension.ts` line 24 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9P4CECAxyA9tKdo_WP:-O9P4CECAxyA9tKdo_WQ:b-3xyncn) ([raw file](https://github.com/starkware-libs/cairo/blob/c9cc6237cbf82812f76a7a50f23494a9039026a6/vscode-cairo/src/extension.ts#L24)):*
> ```XML
>     ctx.log.warn("status bar is disabled");
>     ctx.log.warn("note: set `cairo1.enableStatusBar` to `true` to enable it");
>   }
> ```

imo no need to pollute logs about this



_Suggestion:_
```XML
  if (ctx.config.get("enableStatusBar")) {
    await setupStatusBar(ctx, client);
  }
```
___
*[`vscode-cairo/src/statusBar.ts` line 40 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9P7abAANMKWI5PAd6y:-O9P7abAANMKWI5PAd6z:bnqh8kn) ([raw file](https://github.com/starkware-libs/cairo/blob/c9cc6237cbf82812f76a7a50f23494a9039026a6/vscode-cairo/src/statusBar.ts#L40)):*
> ```XML
> 
>     try {
>       const scarb = await Scarb.find(vscode.workspace.workspaceFolders?.[0], ctx);
> ```

We will probably want to query CairoLS (via custom request type) because it might have more context than the extension. But this is definitely a topic for separate PR, though. I'll make a separate issue for this.


<!-- Sent from Reviewable.io -->

2024-10-17 18:26 UTC, mkaput reviewed
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6497)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @marcuspang, @orizi, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-10-17 18:33 UTC, marcuspang reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6497)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`vscode-cairo/package.json` line 144 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9P3Q17-GxIMKlEe5Qk:-O9QgcDuDoJs-73HbPAi:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c9cc6237cbf82812f76a7a50f23494a9039026a6/vscode-cairo/package.json#L144)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I did a quick search in popular extensions and these name & description pattern seem to be a convergent style used by most of them.
</blockquote></details>

Done.
___
*[`vscode-cairo/src/context.ts` line 12 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9P6L39EdK43lbJhxX8:-O9QkNxiAvLXba4zDE2y:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c9cc6237cbf82812f76a7a50f23494a9039026a6/vscode-cairo/src/context.ts#L12)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Consider encapsulating all the logic and state in a `StatusBar` class, that is:
1. Move `statusBarItem` instance inside it, and keep `StatusBar` instance as a field in this `Context`. You should be able to use [definite assignment assertion](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#strict-class-initialization) to resolve cyclic dependency.
2. Make `setupStatusBar` etc. plain methods there.
</blockquote></details>

Done.
___
*[`vscode-cairo/src/extension.ts` line 24 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9P4CECAxyA9tKdo_WP:-O9QgitJ0OiqAVeHOfRZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c9cc6237cbf82812f76a7a50f23494a9039026a6/vscode-cairo/src/extension.ts#L24)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

imo no need to pollute logs about this
</blockquote></details>

Done.
___
*[`vscode-cairo/src/statusBar.ts` line 40 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9P7abAANMKWI5PAd6y:-O9Qgth0EzoT1ZJP0HmE:bf9te0h) ([raw file](https://github.com/starkware-libs/cairo/blob/c9cc6237cbf82812f76a7a50f23494a9039026a6/vscode-cairo/src/statusBar.ts#L40)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

We will probably want to query CairoLS (via custom request type) because it might have more context than the extension. But this is definitely a topic for separate PR, though. I'll make a separate issue for this.
</blockquote></details>

Gotcha Ill copy over the TODO in cairols.ts


<!-- Sent from Reviewable.io -->

2024-10-21 08:23 UTC, mkaput requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6497)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @marcuspang, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/extension.ts` line 20 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9i9hsb-qPaIsY-Gbg7:-O9i9hsb-qPaIsY-Gbg8:b-vdwraf) ([raw file](https://github.com/starkware-libs/cairo/blob/be66ce3793341b62f249be4482ccd95ceea7dc63/vscode-cairo/src/extension.ts#L20)):*
> ```XML
>   if (ctx.config.get("showInStatusBar")) {
>     ctx.statusBar.setupStatusBar(client);
>   }
> ```

`setupStatusBar` does this internally so we don't have to repeat this condition here



_Suggestion:_
```XML
  ctx.statusBar.setupStatusBar(client);
```
___
*[`vscode-cairo/src/statusBar.ts` line 40 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9P7abAANMKWI5PAd6y:-O9iABAZDW-MlVKyg1Wv:b-x3nnme) ([raw file](https://github.com/starkware-libs/cairo/blob/c9cc6237cbf82812f76a7a50f23494a9039026a6/vscode-cairo/src/statusBar.ts#L40)):*
<details><summary><i>Previously, marcuspang (Marcus) wrote…</i></summary><blockquote>

Gotcha Ill copy over the TODO in cairols.ts
</blockquote></details>

https://github.com/starkware-libs/cairo/issues/6502
___
*[`vscode-cairo/src/statusBar.ts` line 16 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9i9VdK30ADbX1sspY1:-O9i9VdK30ADbX1sspY2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/be66ce3793341b62f249be4482ccd95ceea7dc63/vscode-cairo/src/statusBar.ts#L16)):*
> ```XML
>   }
> 
>   public setupStatusBar(client?: lc.LanguageClient): void {
> ```





_Suggestion:_
```XML
public setup(client?: lc.LanguageClient): void {
```
___
*[`vscode-cairo/src/statusBar.ts` line 39 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9i9Ivu9OBX8HpQ6go4:-O9i9Ivu9OBX8HpQ6go5:b-kwcbvm) ([raw file](https://github.com/starkware-libs/cairo/blob/be66ce3793341b62f249be4482ccd95ceea7dc63/vscode-cairo/src/statusBar.ts#L39)):*
> ```XML
>   }
> 
>   public async updateStatusBar(): Promise<void> {
> ```

this doesn't have to be public


<!-- Sent from Reviewable.io -->

2024-10-21 11:29 UTC, Draggu approved these changes
> Reviewed 1 of 3 files at r1, 2 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6497)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @marcuspang, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-10-21 12:25 UTC, marcuspang reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6497)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @mkaput, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/extension.ts` line 20 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9i9hsb-qPaIsY-Gbg7:-O9j1ChHD6RejdJETb07:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/be66ce3793341b62f249be4482ccd95ceea7dc63/vscode-cairo/src/extension.ts#L20)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

`setupStatusBar` does this internally so we don't have to repeat this condition here
</blockquote></details>

Done.
___
*[`vscode-cairo/src/statusBar.ts` line 16 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9i9VdK30ADbX1sspY1:-O9j1IlX5LXoRPbEIiUl:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/be66ce3793341b62f249be4482ccd95ceea7dc63/vscode-cairo/src/statusBar.ts#L16)):*
> ```XML
>   }
> 
>   public setupStatusBar(client?: lc.LanguageClient): void {
> ```

Done.
___
*[`vscode-cairo/src/statusBar.ts` line 39 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9i9Ivu9OBX8HpQ6go4:-O9j1LDCDRGpz5lmyHrZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/be66ce3793341b62f249be4482ccd95ceea7dc63/vscode-cairo/src/statusBar.ts#L39)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

this doesn't have to be public
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-21 15:27 UTC, Arcticae requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6497)* status: all files reviewed, 4 unresolved discussions (waiting on @marcuspang, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/context.ts` line 23 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9jg3g-700mk51VzCC8:-O9jg3g-700mk51VzCC9:b-8ykexl) ([raw file](https://github.com/starkware-libs/cairo/blob/5547465c001f9cfe6d902acbd71acd4c184fa7c1/vscode-cairo/src/context.ts#L23)):*
> ```XML
> 
>   public readonly config: Config = new Config();
>   public statusBar!: StatusBar;
> ```

I don't know why it's a non-nullable reference if it's not enforced (Context is created and only later is the `statusBar` being set
___
*[`vscode-cairo/src/statusBar.ts` line 20 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9jfCQ_2wtyVzb1Q7q7:-O9jfCQ_2wtyVzb1Q7q8:b-i25p6c) ([raw file](https://github.com/starkware-libs/cairo/blob/5547465c001f9cfe6d902acbd71acd4c184fa7c1/vscode-cairo/src/statusBar.ts#L20)):*
> ```XML
>       vscode.workspace.onDidChangeConfiguration((e) => {
>         if (e.affectsConfiguration("cairo1.showInStatusBar")) {
>           this.update();
> ```

This should figure out if the change is to hide or show it (and perform it), because it needlessly queries for version and looks for scarb once again
___
*[`vscode-cairo/src/statusBar.ts` line 43 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9jfTAE6Ak5dw0yqios:-O9jfTAE6Ak5dw0yqiot:bnr957p) ([raw file](https://github.com/starkware-libs/cairo/blob/5547465c001f9cfe6d902acbd71acd4c184fa7c1/vscode-cairo/src/statusBar.ts#L43)):*
> ```XML
>     const showInStatusBar = config.get<boolean>("showInStatusBar", true);
> 
>     if (showInStatusBar) {
> ```

This function probably should be split into: 
1. Looking for scarb
2. Refreshing the version 
3. Showing/hiding the statusbar

Right now it does a bit much
___
*[`vscode-cairo/src/statusBar.ts` line 61 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9jeyCD3B_yfOERZX55:-O9jeyCD3B_yfOERZX56:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5547465c001f9cfe6d902acbd71acd4c184fa7c1/vscode-cairo/src/statusBar.ts#L61)):*
> ```XML
>     } else {
>       this.statusBarItem.hide();
>     }
> ```





_Suggestion:_
```XML
      this.showStatusBarItem();
    } else {
      this.closeStatusBarItem();
    }
```


<!-- Sent from Reviewable.io -->

2024-10-22 08:56 UTC, marcuspang reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6497)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @Arcticae, @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/context.ts` line 23 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9jg3g-700mk51VzCC8:-O9nQeXB8Q48LrVyNAqb:b9bvl7s) ([raw file](https://github.com/starkware-libs/cairo/blob/5547465c001f9cfe6d902acbd71acd4c184fa7c1/vscode-cairo/src/context.ts#L23)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

I don't know why it's a non-nullable reference if it's not enforced (Context is created and only later is the `statusBar` being set
</blockquote></details>

I think what you said made sense. I decided to move the creation to the constructor. Not sure if it would be better to take it in as an optional parameter in the constructor instead
___
*[`vscode-cairo/src/statusBar.ts` line 20 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9jfCQ_2wtyVzb1Q7q7:-O9nQE9r-cuMnw8z3W0s:b3jscvf) ([raw file](https://github.com/starkware-libs/cairo/blob/5547465c001f9cfe6d902acbd71acd4c184fa7c1/vscode-cairo/src/statusBar.ts#L20)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

This should figure out if the change is to hide or show it (and perform it), because it needlessly queries for version and looks for scarb once again
</blockquote></details>

Gotcha, I remove this check, update() still checks it when called
___
*[`vscode-cairo/src/statusBar.ts` line 43 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9jfTAE6Ak5dw0yqios:-O9nQMZZ8FWGA-TLnIoe:bcarjla) ([raw file](https://github.com/starkware-libs/cairo/blob/5547465c001f9cfe6d902acbd71acd4c184fa7c1/vscode-cairo/src/statusBar.ts#L43)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

This function probably should be split into: 
1. Looking for scarb
2. Refreshing the version 
3. Showing/hiding the statusbar

Right now it does a bit much
</blockquote></details>

Separated into different methods. Currently, I always call `this.updateScarbVersion()` whenever the `StatusBar` is setup. Not sure if I should only call this when the config has the `showInStatusBar` value as true
___
*[`vscode-cairo/src/statusBar.ts` line 61 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9jeyCD3B_yfOERZX55:-O9nE4OyBHDFYvsvforB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5547465c001f9cfe6d902acbd71acd4c184fa7c1/vscode-cairo/src/statusBar.ts#L61)):*
> ```XML
>     } else {
>       this.statusBarItem.hide();
>     }
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-10-23 07:45 UTC, mkaput approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6497)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @orizi, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-10-24 15:42 UTC, Arcticae approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6497#-:-O9zBN-7-2DkBjNPlWeh:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @marcuspang, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/statusBar.ts` line 43 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6497#-O9jfTAE6Ak5dw0yqios:-O9zBCoj3SNkPMuNiZIZ:be2x7xt) ([raw file](https://github.com/starkware-libs/cairo/blob/5547465c001f9cfe6d902acbd71acd4c184fa7c1/vscode-cairo/src/statusBar.ts#L43)):*
<details><summary><i>Previously, marcuspang (Marcus) wrote…</i></summary><blockquote>

Separated into different methods. Currently, I always call `this.updateScarbVersion()` whenever the `StatusBar` is setup. Not sure if I should only call this when the config has the `showInStatusBar` value as true
</blockquote></details>

I think it would be a good optimization but you can do it in a separate PR if you want :) It's not crucial


<!-- Sent from Reviewable.io -->

2024-10-24 15:47 UTC, mkaput approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6497)* status: all files reviewed, 2 unresolved discussions (waiting on @marcuspang, @orizi, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-10-24 15:47 UTC, mkaput commented
Thank you! ❤️❤️❤️❤️❤️

2024-10-24 16:07 UTC, merged