Adjust `ProjectConfig` to remove implicit assumption that `discriminator == version`
starkware-libs/cairo pull request #6503
Opened 2024-10-22 00:36 UTC by piotmag769

Currently there is no way to specify the discriminator for a crate itself, so we do a wild guess and assume that it is equal to version. I also removed the `ProjectConfig.corelib` field that seems obsolete: API user can pass this information via `ProjectConfigContent.content_roots`.

2024-10-22 00:36 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6503)
<!-- Reviewable:end -->

2024-10-22 06:25 UTC, orizi requested changes
> Reviewed 2 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6503)* status: 2 of 10 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @maciektr, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6503#-O9mtKAL0zfFfzfX9tdI:-O9mtKAL0zfFfzfX9tdJ:brozlhu) ([raw file](https://github.com/starkware-libs/cairo/blob/7a005b43e74eada9434aec73a0d85ba8a4676093/crates/cairo-lang-filesystem/src/db.rs#L31)):*
> ```XML
> /// This directly translates to [`DependencySettings.discriminator`] expect the discriminator
> /// **must** be `None` for the core crate.
> pub type CrateIdentifier = SmolStr;
> ```

either do a type wrapper - or remove the alias.
`pub struct CrateIdentifier(SmolStr);



_Code quote:_
```XML
pub type CrateIdentifier = SmolStr;
```


<!-- Sent from Reviewable.io -->

2024-10-22 07:36 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6503)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @maciektr, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6503#-O9n8_Bp84jRL0U4J09-:-O9n8_Bp84jRL0U4J090:b14olx5) (no related file):*
I don't understand these changes. Why do you need these?

As far as I know things, the discriminator == version equality is used because this is a model that `cairo_project.toml` uses. There's open path to skip this requirement by directly interning things in `*Database`, which we do everywhere we want to, don't we?

___


<!-- Sent from Reviewable.io -->

2024-10-22 07:49 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6503)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @maciektr, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6503#-O9nBsBj7zijwUXRXm3I:-O9nBsBj7zijwUXRXm3J:bk3b3ec) (no related file):*
You're mixing two changes in a single PR here, please make a stack

___


<!-- Sent from Reviewable.io -->

2024-10-22 08:40 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6503)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @Arcticae, @Draggu, @maciektr, and @piotmag769)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6503#-O9n8_Bp84jRL0U4J09-:-O9nNXuqC4aQ8tDXwsPH:btzum3y) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I don't understand these changes. Why do you need these?

As far as I know things, the discriminator == version equality is used because this is a model that `cairo_project.toml` uses. There's open path to skip this requirement by directly interning things in `*Database`, which we do everywhere we want to, don't we?
</blockquote></details>

discussed offline. we need these changes anyway for `scarb eject` to be possible

___


<!-- Sent from Reviewable.io -->

2024-10-22 09:23 UTC, Draggu approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 7 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6503#-:-O9nXUmCC7KGmE1Qvfhz:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @maciektr, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-10-22 10:41 UTC, piotmag769 reviewed
> Reviewed 1 of 7 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6503)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @maciektr, and @orizi)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6503#-O9mtKAL0zfFfzfX9tdI:-O9nkGpvEsye79GRN7DY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7a005b43e74eada9434aec73a0d85ba8a4676093/crates/cairo-lang-filesystem/src/db.rs#L31)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

either do a type wrapper - or remove the alias.
`pub struct CrateIdentifier(SmolStr);
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-22 10:42 UTC, piotmag769 reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6503)* status: all files reviewed, 2 unresolved discussions (waiting on @Arcticae, @maciektr, and @orizi)



<!-- Sent from Reviewable.io -->

2024-10-22 13:30 UTC, orizi approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6503)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @maciektr, @mkaput, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-10-23 15:25 UTC, piotmag769 commented
Closing in favour of PR stack starting with: #6511

2024-10-23 15:25 UTC, closed without merging

2024-10-23 15:32 UTC, piotmag769 commented
Closing in favour of PR stack: #6511 #6512