merge use paths in the formatter.
starkware-libs/cairo pull request #6571
Opened 2024-11-02 14:38 UTC by dean-starkware

2024-11-02 14:38 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6571)
<!-- Reviewable:end -->

2024-11-16 17:16 UTC, orizi requested changes
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/lib.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OBpkh4U97fHNeY58Ks3:-OBpkh4U97fHNeY58Ks4:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c821595778f75b61aea18528916af8ae64429d87/crates/cairo-lang-formatter/src/lib.rs#L100)):*
> ```XML
>     ) -> Self {
>         Self {
>             tab_size,
> ```





_Suggestion:_
```XML
    pub fn new(
        tab_size: usize,
        max_line_length: usize,
        sort_module_level_items: bool,
        tuple_breaking_behavior: CollectionsBreakingBehavior,
        fixed_array_breaking_behavior: CollectionsBreakingBehavior,
        merge_use_statements: bool,
    ) -> Self {
        Self {
            tab_size,
```
___
*[`crates/cairo-lang-formatter/test_data/expected_results/use_merge.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OBpy5L_-XKS59J60loi:-OBpy5L_-XKS59J60loj:b-hi3h21) ([raw file](https://github.com/starkware-libs/cairo/blob/c821595778f75b61aea18528916af8ae64429d87/crates/cairo-lang-formatter/test_data/expected_results/use_merge.cairo#L1)):*
> ```Cairo
> use a::{a, b, c};
> ```

i don't think you should dedup - as this actually changes the semantics of the program.

(imagine i duplicate a line in order to change the last element, and then run the formatter in the middle, it would basically delete the line)



_Code quote:_
```Cairo
use a::{a, b, c};
```
___
*[`crates/bin/cairo-format/src/main.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OBpiOic6sXvf5Qs9ecv:-OBpiOic6sXvf5Qs9ecw:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/c821595778f75b61aea18528916af8ae64429d87/crates/bin/cairo-format/src/main.rs#L58)):*
> ```XML
>     merge_use_statements: bool,
>     /// Enable merging of `use` statements.
>     files: Vec<String>,
> ```





_Suggestion:_
```XML
    fixed_array_line_breaking: bool,
    /// Enable merging of `use` statements.
    #[arg(long, default_value_t = false)]
    merge_use_statements: bool,
    /// A list of files and directories to format. Use "-" for stdin.
    files: Vec<String>,
```


<!-- Sent from Reviewable.io -->

2024-11-17 07:42 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 3 of 6 files reviewed, 7 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OBszRqC2g6rFZfZWny2:-OBszRqC2g6rFZfZWny3:bfosz47) ([raw file](https://github.com/starkware-libs/cairo/blob/c821595778f75b61aea18528916af8ae64429d87/crates/cairo-lang-formatter/src/formatter_impl.rs#L24)):*
> ```XML
> 
> /// Represents a tree structure for organizing and merging `use` statements.
> struct UseTree(OrderedHashMap<String, UseTree>);
> ```

and add a test ensuring failure.



_Suggestion:_
```XML
struct UseTree {
    children: OrderedHashMap<String, UseTree>,
    leaf_count: usize,
};
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OBt1PcI-mmw9RHFunfD:-OBt1PcI-mmw9RHFunfE:bt3pga2) ([raw file](https://github.com/starkware-libs/cairo/blob/c821595778f75b61aea18528916af8ae64429d87/crates/cairo-lang-formatter/src/formatter_impl.rs#L47)):*
> ```XML
> 
>     /// Formats and returns use statements based on the content.
>     pub fn format_use_statements(&self) -> Vec<String> {
> ```

probably remove all the `format` from function names - and makes them describe creating the `merged use code ` or something.



_Code quote:_
```XML
   pub fn format_use_statements(&self) -> Vec<String> {
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OBt0vJ42kfBMlXtU2Bx:-OBt0vJ42kfBMlXtU2By:bxx05om) ([raw file](https://github.com/starkware-libs/cairo/blob/c821595778f75b61aea18528916af8ae64429d87/crates/cairo-lang-formatter/src/formatter_impl.rs#L87)):*
> ```XML
>         .intern(db);
>         let mut diagnostics = DiagnosticsBuilder::<ParserDiagnostic>::default();
>         let syntax_file = Parser::parse_file(db, &mut diagnostics, file_id, &formatted_statements);
> ```

consider refactoring into using `parse_token_stream`.



_Code quote:_
```XML
        let syntax_file = Parser::parse_file(db, &mut diagnostics, file_id, &formatted_statements);
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1013 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OBt3VCM2tessqlfOm6n:-OBt3VCM2tessqlfOm6o:b-z0u1jh) ([raw file](https://github.com/starkware-libs/cairo/blob/c821595778f75b61aea18528916af8ae64429d87/crates/cairo-lang-formatter/src/formatter_impl.rs#L1013)):*
> ```XML
> 
>             // Collect and merge `use` items within this section.
>             for (index, node) in section_nodes.iter().enumerate() {
> ```

note that nodes with different `#[attributes]` or visibility (`pub`, `pub(crate)`) must not be merged.



_Code quote:_
```XML
            for (index, node) in section_nodes.iter().enumerate() {
```


<!-- Sent from Reviewable.io -->

2024-11-19 14:35 UTC, orizi requested changes
> Reviewed 1 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1013 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OBt3VCM2tessqlfOm6n:-OC3qGnVCv1FYKjXMo3N:b-zh776w) ([raw file](https://github.com/starkware-libs/cairo/blob/c821595778f75b61aea18528916af8ae64429d87/crates/cairo-lang-formatter/src/formatter_impl.rs#L1013)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

and what about visibility?

please do as discussed - and just have tree for every visibility + attributes configuration.


<!-- Sent from Reviewable.io -->

2024-11-20 13:43 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 0 of 10 files reviewed, 7 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/bin/cairo-format/src/main.rs` line 52 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8IlIN-UkziNWflNrN:-OC8IlIN-UkziNWflNrO:b-onan2u) ([raw file](https://github.com/starkware-libs/cairo/blob/08e5cb8aeb74ed70df41aa4b3f0fce199a46b680/crates/bin/cairo-format/src/main.rs#L52)):*
> ```XML
>     /// each array item on a new line, or 'line-by-line' to keep as many items as possible on the
>     /// same line (as space permits). Defaults to single line.
>     #[arg(long, default_value_t = false)]
> ```

another PR.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 49 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8lNOG9kohLlVkju6g:-OC8lNOHCKQvtz1otRt7:b-54vlvc) ([raw file](https://github.com/starkware-libs/cairo/blob/08e5cb8aeb74ed70df41aa4b3f0fce199a46b680/crates/cairo-lang-formatter/src/formatter_impl.rs#L49)):*
> ```XML
> #[derive(Default, Debug)]
> struct UseTree {
>     children: OrderedHashMap<String, UseTree>,
> ```

doc fields.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8nzDr3Xcfr4fRMJvz:-OC8nzDr3Xcfr4fRMJw-:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/08e5cb8aeb74ed70df41aa4b3f0fce199a46b680/crates/cairo-lang-formatter/src/formatter_impl.rs#L93)):*
> ```XML
>                     .collect();
> 
>                 if !allow_duplicate_uses {
> ```





_Suggestion:_
```XML
if dedup_uses {
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1025 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8l3w58y4_W-UGOqlS:-OC8l3w58y4_W-UGOqlT:byo9s0q) ([raw file](https://github.com/starkware-libs/cairo/blob/08e5cb8aeb74ed70df41aa4b3f0fce199a46b680/crates/cairo-lang-formatter/src/formatter_impl.rs#L1025)):*
> ```XML
>             if let SyntaxKind::UsePathList = syntax_node.kind(self.db) {
>                 self.sort_inner_use_path(&mut children);
>             }
> ```

make the comments not just describe the next line.



_Code quote:_
```XML
        if self.config.sort_module_level_items {
            // Sort items by sections, then merge and sort use items.
            self.sort_items_sections(&mut children);

            // Additionally, sort inner use paths if this is a `UsePathList` node.
            if let SyntaxKind::UsePathList = syntax_node.kind(self.db) {
                self.sort_inner_use_path(&mut children);
            }
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1093 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8k_rM2aawy5xLC-5P:-OC8k_rM2aawy5xLC-5Q:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/08e5cb8aeb74ed70df41aa4b3f0fce199a46b680/crates/cairo-lang-formatter/src/formatter_impl.rs#L1093)):*
> ```XML
>     //     }
>     //     *children = new_children;
>     // }
> ```

?



_Code quote:_
```XML
    // /// Merges `use` items within each section of the module, replacing them with a unified
    // syntax /// node.
    // fn merge_use_items(&mut self, children: &mut Vec<SyntaxNode>) {
    //     let mut new_children = Vec::new();

    //     for (_section_kind, section_nodes) in extract_sections(children, self.db) {
    //         let mut use_tree = UseTree::new();
    //         let mut skip_merge = Vec::new();

    //         // Collect and merge `use` items within this section.
    //         for node in section_nodes {
    //             if node.kind(self.db) == SyntaxKind::ItemUse {
    //                 let use_item = ast::ItemUse::from_syntax_node(self.db, node.clone());

    //                 // Check for attributes and skip merging for nodes with attributes.
    //                 if !use_item.attributes(self.db).elements(self.db).is_empty() {
    //                     skip_merge.push(node.clone());
    //                 } else {
    //                     use_tree.insert_path(self.db, use_item.use_path(self.db));
    //                 }
    //             } else {
    //                 new_children.push(node.clone());
    //             }
    //         }

    //         new_children.extend(skip_merge);

    //         // If there are `use` items in the section, format and add the merged result.
    //         if !use_tree.children.is_empty() {
    //             let merged_node = use_tree
    //                 .generate_syntax_node_from_use(self.db, self.config.allow_duplicate_uses);
    //             let children = self.db.get_children(merged_node.clone()).to_vec();
    //             if !children.is_empty() {
    //                 let grandchildren = self.db.get_children(children[0].clone()).to_vec();
    //                 for child in grandchildren {
    //                     new_children.push(child.clone());
    //                 }
    //             }
    //         }
    //     }
    //     *children = new_children;
    // }
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1126 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8RbLNBFVp4eAJApEg:-OC8RbLNBFVp4eAJApEh:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/08e5cb8aeb74ed70df41aa4b3f0fce199a46b680/crates/cairo-lang-formatter/src/formatter_impl.rs#L1126)):*
> ```XML
>                     new_children.push(node.clone());
>                 }
>             }
> ```





_Suggestion:_
```XML
            let mut use_tree_map: HashMap<(String, Vec<String>), UseTree> = HashMap::new();

            // Collect and merge `use` items within this section.
            for node in section_nodes {
                if node.kind(self.db) != SyntaxKind::ItemUse {
                    new_children.extend(section_nodes.cloned());
                    break;
                }
                let use_item = ast::ItemUse::from_syntax_node(self.db, node.clone());                    
                let visibility = use_item
                    .visibility(self.db)
                    .as_syntax_node()
                    .get_text_without_trivia(self.db);
                let attributes = use_item
                    .attributes(self.db)
                    .elements(self.db)
                    .iter()
                    .map(|attr| attr.as_syntax_node().get_text_without_trivia(self.db))
                    .collect::<Vec<String>>();
                let key = (visibility.clone(), attributes.clone());
                let tree = use_tree_map.entry(key).or_default();
                tree.insert_path(self.db, use_item.use_path(self.db));
            }
```


<!-- Sent from Reviewable.io -->

2024-11-20 14:06 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 0 of 10 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/bin/cairo-format/src/main.rs` line 52 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8IlIN-UkziNWflNrN:-OC8r6G36aqLMp0DaG4z:b-q4xq7f) ([raw file](https://github.com/starkware-libs/cairo/blob/08e5cb8aeb74ed70df41aa4b3f0fce199a46b680/crates/bin/cairo-format/src/main.rs#L52)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

another PR.
</blockquote></details>

Changed it by mistake.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1013 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OBt3VCM2tessqlfOm6n:-OC8qNv85xmT3rRR6AfJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c821595778f75b61aea18528916af8ae64429d87/crates/cairo-lang-formatter/src/formatter_impl.rs#L1013)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and what about visibility?

please do as discussed - and just have tree for every visibility + attributes configuration.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 49 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8lNOG9kohLlVkju6g:-OC8rgzQ-7RHH4d0rMt-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/08e5cb8aeb74ed70df41aa4b3f0fce199a46b680/crates/cairo-lang-formatter/src/formatter_impl.rs#L49)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc fields.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1025 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8l3w58y4_W-UGOqlS:-OC8s5EW7CTuQh84BGk0:brgxjyh) ([raw file](https://github.com/starkware-libs/cairo/blob/08e5cb8aeb74ed70df41aa4b3f0fce199a46b680/crates/cairo-lang-formatter/src/formatter_impl.rs#L1025)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

make the comments not just describe the next line.
</blockquote></details>

Tell me if it's good enough now.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1093 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8k_rM2aawy5xLC-5P:-OC8qNZTE2co6hAs1ZvQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/08e5cb8aeb74ed70df41aa4b3f0fce199a46b680/crates/cairo-lang-formatter/src/formatter_impl.rs#L1093)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8nzDr3Xcfr4fRMJvz:-OC8rqog9NcFMPRW0b-O:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/08e5cb8aeb74ed70df41aa4b3f0fce199a46b680/crates/cairo-lang-formatter/src/formatter_impl.rs#L93)):*
> ```XML
>                     .collect();
> 
>                 if !allow_duplicate_uses {
> ```

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1126 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8RbLNBFVp4eAJApEg:-OC8t6TkDoFWJ2M2jlqP:b-9m78gx) ([raw file](https://github.com/starkware-libs/cairo/blob/08e5cb8aeb74ed70df41aa4b3f0fce199a46b680/crates/cairo-lang-formatter/src/formatter_impl.rs#L1126)):*
> ```XML
>                     new_children.push(node.clone());
>                 }
>             }
> ```

It doesn't work...
Please explain what you tried to do here.


<!-- Sent from Reviewable.io -->

2024-11-20 14:15 UTC, orizi requested changes
> Reviewed 1 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 1 of 10 files reviewed, 5 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1126 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8RbLNBFVp4eAJApEg:-OC8v8AUCOLEPL2rmMxf:b-j47o4z) ([raw file](https://github.com/starkware-libs/cairo/blob/08e5cb8aeb74ed70df41aa4b3f0fce199a46b680/crates/cairo-lang-formatter/src/formatter_impl.rs#L1126)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

It doesn't work...
Please explain what you tried to do here.
</blockquote></details>

you don't need any "skip_merge" nodes.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 148 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8u_j23wcH2-DSp_3Q:-OC8u_j23wcH2-DSp_3R:b-w9hyjt) ([raw file](https://github.com/starkware-libs/cairo/blob/eec7174617ddb457d22a057b625acf14fde6bd5b/crates/cairo-lang-formatter/src/formatter_impl.rs#L148)):*
> ```XML
>             })
>             .collect::<Vec<_>>()
>             .join("\n");
> ```

no reason to note directly create this string.

the intermediate strings don't seem to be required.



_Code quote:_
```XML
            .create_merged_use_items(allow_duplicate_uses)
            .into_iter()
            .map(|statement| {
                // Prepend decorations if provided
                if let Some(ref deco) = decorations {
                    format!("{}use {};", deco, statement)
                } else {
                    format!("use {};", statement)
                }
            })
            .collect::<Vec<_>>()
            .join("\n");
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 225 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8umFNB-_2fw9fk7W1:-OC8umFNB-_2fw9fk7W2:bglkcp5) ([raw file](https://github.com/starkware-libs/cairo/blob/eec7174617ddb457d22a057b625acf14fde6bd5b/crates/cairo-lang-formatter/src/formatter_impl.rs#L225)):*
> ```XML
>         match self.is_empty_line_breakpoint.cmp(&other.is_empty_line_breakpoint) {
>             Ordering::Equal => self.precedence.cmp(&other.precedence),
>             other => other,
> ```

why is this connected to the PR?



_Code quote:_
```XML
        match self.is_empty_line_breakpoint.cmp(&other.is_empty_line_breakpoint) {
            Ordering::Equal => self.precedence.cmp(&other.precedence),
            other => other,
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1051 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8uxtS56v9TvBtVP5K:-OC8uxtS56v9TvBtVP5L:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/eec7174617ddb457d22a057b625acf14fde6bd5b/crates/cairo-lang-formatter/src/formatter_impl.rs#L1051)):*
> ```XML
>     }
> 
>     fn merge_use_items(&mut self, children: &mut Vec<SyntaxNode>) {
> ```

doc


<!-- Sent from Reviewable.io -->

2024-11-20 14:16 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 1 of 10 files reviewed, 6 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/test_data/cairo_files/use_merge_with_dup.cairo` line 25 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8vPa5-fBix9ZlRZkE:-OC8vPa5-fBix9ZlRZkF:b-iia7n2) ([raw file](https://github.com/starkware-libs/cairo/blob/eec7174617ddb457d22a057b625acf14fde6bd5b/crates/cairo-lang-formatter/test_data/cairo_files/use_merge_with_dup.cairo#L25)):*
> ```Cairo
> pub use a::{a, b};
> use e::e;
> pub use a::b;
> ```

if the `mod`s are used to create a section - give a doc above each one to describe what you are testing.



_Code quote:_
```Cairo
use a::a;
use a::a;
use a::b;
use a::c;
mod a;
use a::e;
use a::n;
use v::t;
use v::{a, b};
mod b;
use z::a;
mod b;
use a::a;
#[cfg(test)]
use a::a;
use a::b;
use a::c;
mod c;
use a;
use a::a as c;
use a::b as d;
mod d;
pub use a::{a, b};
use e::e;
pub use a::b;
```


<!-- Sent from Reviewable.io -->

2024-11-20 15:18 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 1 of 10 files reviewed, 6 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1126 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8RbLNBFVp4eAJApEg:-OC96Aof7m1-tJZLAoZV:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/08e5cb8aeb74ed70df41aa4b3f0fce199a46b680/crates/cairo-lang-formatter/src/formatter_impl.rs#L1126)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you don't need any "skip_merge" nodes.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 148 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8u_j23wcH2-DSp_3Q:-OC97yYGC6oIdWVZLpMF:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eec7174617ddb457d22a057b625acf14fde6bd5b/crates/cairo-lang-formatter/src/formatter_impl.rs#L148)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no reason to note directly create this string.

the intermediate strings don't seem to be required.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 225 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8umFNB-_2fw9fk7W1:-OC97IcY9cl1C6Xk2TyD:b-uokq3s) ([raw file](https://github.com/starkware-libs/cairo/blob/eec7174617ddb457d22a057b625acf14fde6bd5b/crates/cairo-lang-formatter/src/formatter_impl.rs#L225)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why is this connected to the PR?
</blockquote></details>

Just changed a few unnecessary indentations.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1051 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8uxtS56v9TvBtVP5K:-OC98eniA-888a_uBqYE:bzg0r5d) ([raw file](https://github.com/starkware-libs/cairo/blob/eec7174617ddb457d22a057b625acf14fde6bd5b/crates/cairo-lang-formatter/src/formatter_impl.rs#L1051)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Removed it by mistake. Fixed.
___
*[`crates/cairo-lang-formatter/test_data/cairo_files/use_merge_with_dup.cairo` line 25 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC8vPa5-fBix9ZlRZkE:-OC977kxENBReZfmwjFf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/eec7174617ddb457d22a057b625acf14fde6bd5b/crates/cairo-lang-formatter/test_data/cairo_files/use_merge_with_dup.cairo#L25)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if the `mod`s are used to create a section - give a doc above each one to describe what you are testing.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-20 15:31 UTC, orizi requested changes
> Reviewed 1 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 2 of 10 files reviewed, 7 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/test_data/cairo_files/use_merge_with_dup.cairo` line 14 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC9BXqiA1x0c1bPUeW2:-OC9BXqiA1x0c1bPUeW3:b-6dp3xz) ([raw file](https://github.com/starkware-libs/cairo/blob/6460cb4c4f01639bbe3afbed6c962e29e1af8928/crates/cairo-lang-formatter/test_data/cairo_files/use_merge_with_dup.cairo#L14)):*
> ```Cairo
> use z::a;
> mod b;
> /// Testing attributes.
> ```

these seems to have disappeared in the results.

we probably *do* need a skipped node list - but it would be about having documentation :)



_Code quote:_
```Cairo
/// Testing attributes.
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC9A0ltC_F9alayZUZg:-OC9A0ltC_F9alayZUZh:b-p6xcfb) ([raw file](https://github.com/starkware-libs/cairo/blob/6460cb4c4f01639bbe3afbed6c962e29e1af8928/crates/cairo-lang-formatter/src/formatter_impl.rs#L24)):*
> ```XML
> struct Leaf {
>     alias: Option<String>,
> }
> ```

move defintition to under `UseTree` and add doc.



_Code quote:_
```XML
#[derive(Default, Debug, Clone)]
struct Leaf {
    alias: Option<String>,
}
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1024 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC9ARsa1AssjIEjxIUt:-OC9ARsa1AssjIEjxIUu:b-t3h1wt) ([raw file](https://github.com/starkware-libs/cairo/blob/6460cb4c4f01639bbe3afbed6c962e29e1af8928/crates/cairo-lang-formatter/src/formatter_impl.rs#L1024)):*
> ```XML
>         if self.config.merge_use_items {
>             self.merge_use_items(&mut children);
>         }
> ```

merge should probably be before sort - otherwise if a merge cause a change of text, we would get a different result after an additional formatter run.



_Code quote:_
```XML
        if self.config.merge_use_items {
            self.merge_use_items(&mut children);
        }
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1057 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC9BEW79HKAMWErhHjU:-OC9BEW79HKAMWErhHjV:buz572v) ([raw file](https://github.com/starkware-libs/cairo/blob/6460cb4c4f01639bbe3afbed6c962e29e1af8928/crates/cairo-lang-formatter/src/formatter_impl.rs#L1057)):*
> ```XML
>             // Collect and merge `use` items within this section.
>             for node in section_nodes {
>                 if node.kind(self.db) == SyntaxKind::ItemUse {
> ```

invert if - short arm first.



_Code quote:_
```XML
                if node.kind(self.db) == SyntaxKind::ItemUse {
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1074 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC9B-JL479qk0HFrsnF:-OC9B-JL479qk0HFrsnG:b-h4fw7a) ([raw file](https://github.com/starkware-libs/cairo/blob/6460cb4c4f01639bbe3afbed6c962e29e1af8928/crates/cairo-lang-formatter/src/formatter_impl.rs#L1074)):*
> ```XML
>                 } else {
>                     has_non_use_items = true;
>                     break;
> ```

won't it always be the first?
if so - doc it.



_Code quote:_
```XML
                    has_non_use_items = true;
                    break;
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1080 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC9B81H1FKv2KtafCl9:-OC9B81H1FKv2KtafClA:bqxx7hy) ([raw file](https://github.com/starkware-libs/cairo/blob/6460cb4c4f01639bbe3afbed6c962e29e1af8928/crates/cairo-lang-formatter/src/formatter_impl.rs#L1080)):*
> ```XML
>                 new_children.extend(section_nodes.iter().cloned());
>                 continue;
>             }
> ```

can't it go into the loop before the `break`?



_Code quote:_
```XML
            }
            if has_non_use_items {
                new_children.extend(section_nodes.iter().cloned());
                continue;
            }
```


<!-- Sent from Reviewable.io -->

2024-11-21 11:59 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 2 of 10 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC9A0ltC_F9alayZUZg:-OCClgIc6zSJJW_SLVj7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6460cb4c4f01639bbe3afbed6c962e29e1af8928/crates/cairo-lang-formatter/src/formatter_impl.rs#L24)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

move defintition to under `UseTree` and add doc.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1024 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC9ARsa1AssjIEjxIUt:-OCCm_yR7vp3lcebklNR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6460cb4c4f01639bbe3afbed6c962e29e1af8928/crates/cairo-lang-formatter/src/formatter_impl.rs#L1024)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

merge should probably be before sort - otherwise if a merge cause a change of text, we would get a different result after an additional formatter run.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1057 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC9BEW79HKAMWErhHjU:-OCCm2hW3_dFymVkGZ-G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6460cb4c4f01639bbe3afbed6c962e29e1af8928/crates/cairo-lang-formatter/src/formatter_impl.rs#L1057)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

invert if - short arm first.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1074 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC9B-JL479qk0HFrsnF:-OCCmlALDY-hQap6vf1-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6460cb4c4f01639bbe3afbed6c962e29e1af8928/crates/cairo-lang-formatter/src/formatter_impl.rs#L1074)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

won't it always be the first?
if so - doc it.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1080 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC9B81H1FKv2KtafCl9:-OCCmGG-EJLkzqbdr9_b:b-r4yfn0) ([raw file](https://github.com/starkware-libs/cairo/blob/6460cb4c4f01639bbe3afbed6c962e29e1af8928/crates/cairo-lang-formatter/src/formatter_impl.rs#L1080)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can't it go into the loop before the `break`?
</blockquote></details>

I'm not sure I understand what you mean here.
Tell me if it's still relevant after the last refactor.
___
*[`crates/cairo-lang-formatter/test_data/cairo_files/use_merge_with_dup.cairo` line 14 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OC9BXqiA1x0c1bPUeW2:-OCCmQMc4oyVbrIBFaSA:b-by8328) ([raw file](https://github.com/starkware-libs/cairo/blob/6460cb4c4f01639bbe3afbed6c962e29e1af8928/crates/cairo-lang-formatter/test_data/cairo_files/use_merge_with_dup.cairo#L14)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

these seems to have disappeared in the results.

we probably *do* need a skipped node list - but it would be about having documentation :)
</blockquote></details>

Agree.
What do you want to do with it now?
Leave it like that and take care of it in a different PR?


<!-- Sent from Reviewable.io -->

2024-11-21 12:08 UTC, orizi requested changes
> Reviewed 2 of 8 files at r2, 1 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 4 of 10 files reviewed, 2 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/test_data/cairo_files/use_merge.cairo` line 28 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCDbPhP5QWIJZID5Wdp:-OCDbPhP5QWIJZID5Wdq:b-ef1u7y) ([raw file](https://github.com/starkware-libs/cairo/blob/7b27c484e7dd213bb054cdcfca7d758c193a4fc8/crates/cairo-lang-formatter/test_data/cairo_files/use_merge.cairo#L28)):*
> ```Cairo
> pub use a::c;
> pub use a::{a, b};
> use e::e;
> ```

seems like an interesting test as well.



_Suggestion:_
```Cairo
use e::e;
mod e;
use a::b;
use a::b::c;
use a::b::c::d;
use a::b::c::d::e;
use a::b::c::d::f::g;
```


<!-- Sent from Reviewable.io -->

2024-11-21 12:09 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 4 of 10 files reviewed, 2 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/test_data/cairo_files/use_merge.cairo` line 20 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCDc2Em1SvwPo2x5Ybp:-OCDc2Em1SvwPo2x5Ybq:bmy7393) ([raw file](https://github.com/starkware-libs/cairo/blob/7b27c484e7dd213bb054cdcfca7d758c193a4fc8/crates/cairo-lang-formatter/test_data/cairo_files/use_merge.cairo#L20)):*
> ```Cairo
> use a::c;
> /// Testing aliases.
> mod c;
> ```

test documentation blocking merges.


<!-- Sent from Reviewable.io -->

2024-11-21 12:15 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 4 of 10 files reviewed, 3 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 126 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCDcTbzDkMOm3Sv-Xve:-OCDcTbzDkMOm3Sv-Xvf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/7b27c484e7dd213bb054cdcfca7d758c193a4fc8/crates/cairo-lang-formatter/src/formatter_impl.rs#L126)):*
> ```XML
>                         combined
>                     }
>                 }
> ```





_Suggestion:_
```XML
                let formatted_children = subtree.create_merged_use_items(dedup_uses);
                let tree_state =
                    TreeState::resolve;

                match (formatted_leaves.is_empty(), formatted_children.is_empty()) {
                    (true, true) => vec![segment.clone()],
                    (false, true) => formatted_leaves,
                    (true, false) => {
                        if formatted_children.len() == 1 {
                            vec![format!("{segment}::{}", formatted_children[0])]
                        } else {
                            vec![format!("{segment}::{{{}}}", formatted_children.join(", "))]
                        }
                    }
                    (false, false) => {
                        let mut combined = formatted_leaves;
                        combined.push(format!(
                            "{}::{{{}}}",
                            segment,
                            formatted_children.join(", ")
                        ));
                        combined
                    }
                }
```


<!-- Sent from Reviewable.io -->

2024-11-21 12:25 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 4 of 10 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/test_data/cairo_files/use_merge.cairo` line 20 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCDc2Em1SvwPo2x5Ybp:-OCDedDF4IIf4VPpQnTD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7b27c484e7dd213bb054cdcfca7d758c193a4fc8/crates/cairo-lang-formatter/test_data/cairo_files/use_merge.cairo#L20)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

test documentation blocking merges.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/test_data/cairo_files/use_merge.cairo` line 28 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCDbPhP5QWIJZID5Wdp:-OCDebEX4cluBYJ-Lyvf:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7b27c484e7dd213bb054cdcfca7d758c193a4fc8/crates/cairo-lang-formatter/test_data/cairo_files/use_merge.cairo#L28)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

seems like an interesting test as well.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 126 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCDcTbzDkMOm3Sv-Xve:-OCDfubY9Zb_2nAdOtRW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7b27c484e7dd213bb054cdcfca7d758c193a4fc8/crates/cairo-lang-formatter/src/formatter_impl.rs#L126)):*
> ```XML
>                         combined
>                     }
>                 }
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-11-21 13:07 UTC, orizi requested changes
> Reviewed 1 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 63 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCDpIrX-1I3LGSOywWa:-OCDpIrX-1I3LGSOywWb:b-4bj8u3) ([raw file](https://github.com/starkware-libs/cairo/blob/3fb89e7fdbbf392fa7204d18675c4ce2c18b0ef4/crates/cairo-lang-formatter/src/formatter_impl.rs#L63)):*
> ```XML
> 
>     /// Formats and returns use items based on the content.
>     pub fn create_merged_use_items(&self, dedup_uses: bool) -> Vec<String> {
> ```

improve algorithm as discussed f2f.


<!-- Sent from Reviewable.io -->

2024-11-21 13:07 UTC, orizi reviewed
> Reviewed 2 of 4 files at r4, 4 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: all files reviewed, 1 unresolved discussion (waiting on @dean-starkware and @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2024-11-22 11:48 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 63 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCDpIrX-1I3LGSOywWa:-OCE-DhEB_Th7lqW379R:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3fb89e7fdbbf392fa7204d18675c4ce2c18b0ef4/crates/cairo-lang-formatter/src/formatter_impl.rs#L63)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

improve algorithm as discussed f2f.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-22 13:27 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 5 of 10 files reviewed, 8 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 63 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCIyEID2M2gi3VL0v_T:-OCIyEID2M2gi3VL0v_U:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2a6633f95035cecf4987f39c66fa22c7a8046d25/crates/cairo-lang-formatter/src/formatter_impl.rs#L63)):*
> ```XML
> 
>     /// Merge and organize the `use` paths in a hierarchical structure.
>     pub fn create_merged_use_items(self, dedup_uses: bool) -> (Option<String>, Vec<String>) {
> ```





_Suggestion:_
```XML
    /// Merge and organize the `use` paths in a hierarchical structure.
    /// Additionally returns whether the returned elements are a single leaf.
    pub fn create_merged_use_items(self, dedup_uses: bool) -> (Vec<String>, bool) {
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 84 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCIyVECBmP8izPcWHSC:-OCIyVECBmP8izPcWHSD:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2a6633f95035cecf4987f39c66fa22c7a8046d25/crates/cairo-lang-formatter/src/formatter_impl.rs#L84)):*
> ```XML
>             nested_paths
>                 .extend(completed_children.into_iter().map(|child| format!("{segment}::{child}")));
>         }
> ```





_Suggestion:_
```XML
        for (segment, subtree) in self.children {
            let (subtree_merged_used_items, is_single_leaf) = subtree.create_merged_use_items(dedup_uses);
            if is_single_leaf { leaf_paths } else { nested_paths }
                .extend(subtree_merged_used_items.into_iter().map(|child| format!("{segment}::{child}")));
        }
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 103 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCIz0BEEgTm2a5WubSi:-OCIz0BEEgTm2a5WubSj:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2a6633f95035cecf4987f39c66fa22c7a8046d25/crates/cairo-lang-formatter/src/formatter_impl.rs#L103)):*
> ```XML
>             nested_paths.push(format!("{{{}}}", leaf_paths.join(", ")));
>             (None, nested_paths)
>         }
> ```





_Suggestion:_
```XML
        if leaf_paths.len() == 1 {
            if nested_paths.is_empty() {
                return (leaf_paths, true);
            }
            nested_paths.extend(leaf_paths);
        } else if if leaf_paths.len() > 1 {
            nested_paths.push(format!("{{{}}}", leaf_paths.join(", ")));
        }
        (nested_paths, false)
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 111 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCJ2WuxAAqZ8zvoEBr-:-OCJ2WuxAAqZ8zvoEBr0:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2a6633f95035cecf4987f39c66fa22c7a8046d25/crates/cairo-lang-formatter/src/formatter_impl.rs#L111)):*
> ```XML
>         db: &dyn SyntaxGroup,
>         allow_duplicate_uses: bool,
>         decorations: Option<String>,
> ```





_Suggestion:_
```XML
        decorations: String,
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 122 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCJ-LyZ8uvmQoLPh2Lv:-OCJ-LyZ8uvmQoLPh2Lw:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2a6633f95035cecf4987f39c66fa22c7a8046d25/crates/cairo-lang-formatter/src/formatter_impl.rs#L122)):*
> ```XML
>                 formatted_use_items.push_str(&format!("use {};\n", statement));
>             }
>         }
> ```





_Suggestion:_
```XML
        for statement in self.create_merged_use_items(allow_duplicate_uses).0 {
            formatted_use_items.push_str(&format!("{deco}use {statement};\n"));
        }
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1072 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCJ-klT6hZC1fLOZOX_:-OCJ-klT6hZC1fLOZOXa:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/2a6633f95035cecf4987f39c66fa22c7a8046d25/crates/cairo-lang-formatter/src/formatter_impl.rs#L1072)):*
> ```XML
>                     .map(|attr| attr.as_syntax_node().get_text(self.db))
>                     .collect::<Vec<String>>();
>                 let key = (visibility.clone(), attributes.clone());
> ```





_Suggestion:_
```XML
                let key = chain!(
                    use_item
                    .attributes(self.db)
                    .elements(self.db)
                    .iter()
                    .map(|attr| attr.as_syntax_node().get_text_without_trivia(self.db)),
                    [use_item.visibility(self.db).as_syntax_node().get_text(self.db)],
                ).join("\n");
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1091 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCJ2D0YCnDuwQQMEU3W:-OCJ2D0YCnDuwQQMEU3X:bims1ox) ([raw file](https://github.com/starkware-libs/cairo/blob/2a6633f95035cecf4987f39c66fa22c7a8046d25/crates/cairo-lang-formatter/src/formatter_impl.rs#L1091)):*
> ```XML
>                         self.db,
>                         self.config.allow_duplicate_uses,
>                         Some(decorations),
> ```

this seems to never be optional (neither should it be - as the empty string should be good enough for now)



_Suggestion:_
```XML
                        decorations,
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1103 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCJ118TEFvpsQP9kXhV:-OCJ118TEFvpsQP9kXhW:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/2a6633f95035cecf4987f39c66fa22c7a8046d25/crates/cairo-lang-formatter/src/formatter_impl.rs#L1103)):*
> ```XML
>                     }
>                 }
>             }
> ```





_Suggestion:_
```XML
            // Generate merged syntax nodes from the `use_tree_map`.
            for (attrs_and_visibility, tree) in use_tree_map {
                let merged_node = tree.generate_syntax_node_from_use(
                    self.db,
                    self.config.allow_duplicate_uses,
                    Some(decorations),
                );

                // Add merged children to the new_children list.
                let children = self.db.get_children(merged_node.clone()).to_vec();
                if !children.is_empty() {
                    let grandchildren = self.db.get_children(children[0].clone()).to_vec();
                    for child in grandchildren {
                        new_children.push(child.clone());
                    }
                }
            }
```


<!-- Sent from Reviewable.io -->

2024-11-23 13:32 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 5 of 10 files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1091 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCJ2D0YCnDuwQQMEU3W:-OCOBBt25vCxheoaeMTh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2a6633f95035cecf4987f39c66fa22c7a8046d25/crates/cairo-lang-formatter/src/formatter_impl.rs#L1091)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this seems to never be optional (neither should it be - as the empty string should be good enough for now)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 63 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCIyEID2M2gi3VL0v_T:-OCJ4z7K3NKtyv3D_VLL:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2a6633f95035cecf4987f39c66fa22c7a8046d25/crates/cairo-lang-formatter/src/formatter_impl.rs#L63)):*
> ```XML
> 
>     /// Merge and organize the `use` paths in a hierarchical structure.
>     pub fn create_merged_use_items(self, dedup_uses: bool) -> (Option<String>, Vec<String>) {
> ```

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 84 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCIyVECBmP8izPcWHSC:-OCJ56-P3i1KdoFQtGlX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2a6633f95035cecf4987f39c66fa22c7a8046d25/crates/cairo-lang-formatter/src/formatter_impl.rs#L84)):*
> ```XML
>             nested_paths
>                 .extend(completed_children.into_iter().map(|child| format!("{segment}::{child}")));
>         }
> ```

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 103 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCIz0BEEgTm2a5WubSi:-OCOAuu-8ICO-vUazUuo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2a6633f95035cecf4987f39c66fa22c7a8046d25/crates/cairo-lang-formatter/src/formatter_impl.rs#L103)):*
> ```XML
>             nested_paths.push(format!("{{{}}}", leaf_paths.join(", ")));
>             (None, nested_paths)
>         }
> ```

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 111 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCJ2WuxAAqZ8zvoEBr-:-OCOAwot1mIlDFwJq3CT:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2a6633f95035cecf4987f39c66fa22c7a8046d25/crates/cairo-lang-formatter/src/formatter_impl.rs#L111)):*
> ```XML
>         db: &dyn SyntaxGroup,
>         allow_duplicate_uses: bool,
>         decorations: Option<String>,
> ```

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 122 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCJ-LyZ8uvmQoLPh2Lv:-OCOB-Xu37tTh1GSNncD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2a6633f95035cecf4987f39c66fa22c7a8046d25/crates/cairo-lang-formatter/src/formatter_impl.rs#L122)):*
> ```XML
>                 formatted_use_items.push_str(&format!("use {};\n", statement));
>             }
>         }
> ```

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1072 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCJ-klT6hZC1fLOZOX_:-OCOBBVi-pIykQ3MJrbS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2a6633f95035cecf4987f39c66fa22c7a8046d25/crates/cairo-lang-formatter/src/formatter_impl.rs#L1072)):*
> ```XML
>                     .map(|attr| attr.as_syntax_node().get_text(self.db))
>                     .collect::<Vec<String>>();
>                 let key = (visibility.clone(), attributes.clone());
> ```

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1103 at r8](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCJ118TEFvpsQP9kXhV:-OCOBCZF2_W9O7anioPQ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/2a6633f95035cecf4987f39c66fa22c7a8046d25/crates/cairo-lang-formatter/src/formatter_impl.rs#L1103)):*
> ```XML
>                     }
>                 }
>             }
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-11-23 14:24 UTC, orizi requested changes
> Reviewed 3 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 8 of 10 files reviewed, 5 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 90 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCOO-TH1RODE1z7ad_s:-OCOO-TH1RODE1z7ad_t:bhkv3k4) ([raw file](https://github.com/starkware-libs/cairo/blob/1f31f6eee45afdc47f1a5d11818e56a0a70f3b07/crates/cairo-lang-formatter/src/formatter_impl.rs#L90)):*
> ```XML
>                     subtree_merged_use_items.into_iter().map(|child| format!("{segment}::{child}")),
>                 );
>             }
> ```

at the very least:



_Suggestion:_
```XML
            let iter_with_good_name = subtree_merged_use_items.into_iter().map(|child| format!("{segment}::{child}"));
            if is_single_leaf {
                leaf_paths.extend(iter_with_good_name);
            } else {
                nested_paths.extend(iter_with_good_name);
            }
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 108 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCOOSfu0iCsuQFX4u4v:-OCOOSfu0iCsuQFX4u4w:b-83t58f) ([raw file](https://github.com/starkware-libs/cairo/blob/1f31f6eee45afdc47f1a5d11818e56a0a70f3b07/crates/cairo-lang-formatter/src/formatter_impl.rs#L108)):*
> ```XML
>                 nested_paths.push(format!("{{{}}}", leaf_paths.join(", ")));
>             }
>             _ => {}
> ```

weird match.



_Suggestion:_
```XML
        if leaf_paths.len() == 1 {
            if nested_paths.is_empty() {
                return (leaf_paths, true);
            }
            nested_paths.extend(leaf_paths);
        } else if n > 1 => {
            nested_paths.push(format!("{{{}}}", leaf_paths.join(", ")));
        }
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1064 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCOOhaCC_xJXGcF4DmH:-OCOOhaCC_xJXGcF4DmI:byimtm1) ([raw file](https://github.com/starkware-libs/cairo/blob/1f31f6eee45afdc47f1a5d11818e56a0a70f3b07/crates/cairo-lang-formatter/src/formatter_impl.rs#L1064)):*
> ```XML
>                 }
> 
>                 // Process `use` items and group them into `UseTree`.
> ```

this doc does not seem to add a lot.



_Code quote:_
```XML
                // Process `use` items and group them into `UseTree`.
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1076 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCOPA3p924_MfzWWW9B:-OCOPA3q1aFSVnHA2Td6:bma34u9) ([raw file](https://github.com/starkware-libs/cairo/blob/1f31f6eee45afdc47f1a5d11818e56a0a70f3b07/crates/cairo-lang-formatter/src/formatter_impl.rs#L1076)):*
> ```XML
>                     [visibility_text],
>                 )
>                 .join("\n");
> ```

why not inline `attributes` and `visibility_test`?



_Code quote:_
```XML
                let attributes = use_item.attributes(self.db).elements(self.db);
                let visibility_text =
                    use_item.visibility(self.db).as_syntax_node().get_text(self.db);

                let key = chain!(
                    attributes
                        .iter()
                        .map(|attr| attr.as_syntax_node().get_text_without_trivia(self.db)),
                    [visibility_text],
                )
                .join("\n");
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1098 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCOOtu861dRQp8LvaWP:-OCOOtu861dRQp8LvaWQ:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1f31f6eee45afdc47f1a5d11818e56a0a70f3b07/crates/cairo-lang-formatter/src/formatter_impl.rs#L1098)):*
> ```XML
>                     self.db,
>                     self.config.allow_duplicate_uses,
>                     decorations, // Pass the constructed decorations.
> ```





_Suggestion:_
```XML
                    decorations,
```


<!-- Sent from Reviewable.io -->

2024-11-23 14:26 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 8 of 10 files reviewed, 7 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1078 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCOPL_47Yg0VLXEacwi:-OCOPL_47Yg0VLXEacwj:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/1f31f6eee45afdc47f1a5d11818e56a0a70f3b07/crates/cairo-lang-formatter/src/formatter_impl.rs#L1078)):*
> ```XML
>                 .join("\n");
> 
>                 let tree = use_tree_map.entry((key, vec![])).or_default();
> ```





_Suggestion:_
```XML
use_tree_map.entry(key).or_default();
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1094 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCOPQFUEr7llZbh8ILZ:-OCOPQFUEr7llZbh8IL_:bv3f69r) ([raw file](https://github.com/starkware-libs/cairo/blob/1f31f6eee45afdc47f1a5d11818e56a0a70f3b07/crates/cairo-lang-formatter/src/formatter_impl.rs#L1094)):*
> ```XML
>                 }
> 
>                 // Generate the merged syntax node.
> ```

you create the string you required before this - `attrs_and_visibility` should be the prepended string to the item.



_Code quote:_
```XML
            for (attrs_and_visibility, tree) in use_tree_map {
                let (visibility, attributes) = attrs_and_visibility;
                let mut decorations = String::new();
                for attr in &attributes {
                    decorations.push_str(&format!("{} ", attr));
                }
                if !visibility.is_empty() {
                    decorations.push_str(&visibility);
                    decorations.push(' ');
                }

                // Generate the merged syntax node.
```


<!-- Sent from Reviewable.io -->

2024-11-24 13:16 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 8 of 10 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 90 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCOO-TH1RODE1z7ad_s:-OCTG1eV47D7nTy554k1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1f31f6eee45afdc47f1a5d11818e56a0a70f3b07/crates/cairo-lang-formatter/src/formatter_impl.rs#L90)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

at the very least:
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 108 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCOOSfu0iCsuQFX4u4v:-OCTGFlD2cVDn2IcR6kP:bi202q9) ([raw file](https://github.com/starkware-libs/cairo/blob/1f31f6eee45afdc47f1a5d11818e56a0a70f3b07/crates/cairo-lang-formatter/src/formatter_impl.rs#L108)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

weird match.
</blockquote></details>

That what I had in mind also at first.
Had to change it to match due to a Clippy error.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1064 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCOOhaCC_xJXGcF4DmH:-OCTB6k-ELL-ehv14wOW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1f31f6eee45afdc47f1a5d11818e56a0a70f3b07/crates/cairo-lang-formatter/src/formatter_impl.rs#L1064)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this doc does not seem to add a lot.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1076 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCOPA3p924_MfzWWW9B:-OCTGZTb-REF6Ny5SZxM:bfnbdni) ([raw file](https://github.com/starkware-libs/cairo/blob/1f31f6eee45afdc47f1a5d11818e56a0a70f3b07/crates/cairo-lang-formatter/src/formatter_impl.rs#L1076)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why not inline `attributes` and `visibility_test`?
</blockquote></details>

Because of this:

error[E0716]: temporary value dropped while borrowed
    --> crates/cairo-lang-formatter/src/formatter_impl.rs:1061:21
     |
1060 |                    let key = chain!(
     |  ____________________________-
1061 | |/                     use_item
1062 | ||                         .attributes(self.db)
1063 | ||                         .elements(self.db)
     | ||__________________________________________^ creates a temporary value which is freed while still in use
...    |
1066 | |                      [use_item.visibility(self.db).as_syntax_node().get_text(self.db)],
1067 | |                  )
     | |                  -
     | |                  |
     | |__________________temporary value is freed at the end of this statement
     |                    borrow later used here
     |
     = note: consider using a `let` binding to create a longer lived value
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1094 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCOPQFUEr7llZbh8ILZ:-OCTHvTI0tW8VWab3pWh:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1f31f6eee45afdc47f1a5d11818e56a0a70f3b07/crates/cairo-lang-formatter/src/formatter_impl.rs#L1094)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you create the string you required before this - `attrs_and_visibility` should be the prepended string to the item.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1078 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCOPL_47Yg0VLXEacwi:-OCTGaMI737A-ozUDrm9:bul9n82) ([raw file](https://github.com/starkware-libs/cairo/blob/1f31f6eee45afdc47f1a5d11818e56a0a70f3b07/crates/cairo-lang-formatter/src/formatter_impl.rs#L1078)):*
> ```XML
>                 .join("\n");
> 
>                 let tree = use_tree_map.entry((key, vec![])).or_default();
> ```

expected tuple `(std::string::String, Vec<std::string::String>)`
 found struct `std::string::String`
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1098 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCOOtu861dRQp8LvaWP:-OCTH7GICRP5gnpOCsy0:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1f31f6eee45afdc47f1a5d11818e56a0a70f3b07/crates/cairo-lang-formatter/src/formatter_impl.rs#L1098)):*
> ```XML
>                     self.db,
>                     self.config.allow_duplicate_uses,
>                     decorations, // Pass the constructed decorations.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-11-24 15:01 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: all files reviewed, 4 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 107 at r10](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCTfmFS8_HzUwiQnPRF:-OCTfmFS8_HzUwiQnPRG:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b72af50b4c41fa12f0866c61b4a76012f29f9659/crates/cairo-lang-formatter/src/formatter_impl.rs#L107)):*
> ```XML
>             }
>             _ => {}
>         }
> ```





_Suggestion:_
```XML
        match leaf_paths.len() {
            0 => {},
            1 if nested_paths.is_empty() => return (leaf_paths, true),
            1 => nested_paths.extend(leaf_paths),
            _ => nested_paths.push(format!("{{{}}}", leaf_paths.join(", "))),
        }
```


<!-- Sent from Reviewable.io -->

2024-11-24 15:40 UTC, orizi requested changes
> Reviewed 14 of 14 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 10 of 19 files reviewed, 2 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 100 at r11](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCToZ9y9m3C9OjR_WDy:-OCToZ9y9m3C9OjR_WDz:b-45ljvk) ([raw file](https://github.com/starkware-libs/cairo/blob/1fbfba6e21c79e14594fbac1bc594e05f733b3e4/crates/cairo-lang-formatter/src/formatter_impl.rs#L100)):*
> ```XML
>         }
> 
>         // Join leaf paths into a single merged string with proper formatting.
> ```

doesn't really add anything - and specifically not really correct - as this doesn't properly describe the match.



_Code quote:_
```XML
        // Join leaf paths into a single merged string with proper formatting.
```
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1082 at r11](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCTouYFCReFzVhrh1rF:-OCTouYFCReFzVhrh1rG:b-iahrpw) ([raw file](https://github.com/starkware-libs/cairo/blob/1fbfba6e21c79e14594fbac1bc594e05f733b3e4/crates/cairo-lang-formatter/src/formatter_impl.rs#L1082)):*
> ```XML
>                     self.db,
>                     self.config.allow_duplicate_uses,
>                     key, // Use the string key directly here as the decorations.
> ```

if so - just rename `key` to `decorations` and remove the doc.

and call it `decorations` all around.

and call the map `decoration_to_use_tree` 



_Code quote:_
```XML
                    key, // Use the string key directly here as the decorations.
```


<!-- Sent from Reviewable.io -->

2024-11-24 16:13 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571)* status: 18 of 19 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1076 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCOPA3p924_MfzWWW9B:-OCTf8DWEenCym8bYfuJ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1f31f6eee45afdc47f1a5d11818e56a0a70f3b07/crates/cairo-lang-formatter/src/formatter_impl.rs#L1076)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

just use `into_iter` instead of `iter`.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1078 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCOPL_47Yg0VLXEacwi:-OCTfqqy4re9zOmfEKM1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1f31f6eee45afdc47f1a5d11818e56a0a70f3b07/crates/cairo-lang-formatter/src/formatter_impl.rs#L1078)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

indeed - don't expect a tuple - change the type of the map.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1094 at r9](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCOPQFUEr7llZbh8ILZ:-OCTfr8oBQmPzIdfDXm4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1f31f6eee45afdc47f1a5d11818e56a0a70f3b07/crates/cairo-lang-formatter/src/formatter_impl.rs#L1094)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

same issue - the map should just be from a string.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 100 at r11](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCToZ9y9m3C9OjR_WDy:-OCTw0Hi4qeIqSURhFe6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1fbfba6e21c79e14594fbac1bc594e05f733b3e4/crates/cairo-lang-formatter/src/formatter_impl.rs#L100)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doesn't really add anything - and specifically not really correct - as this doesn't properly describe the match.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 1082 at r11](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCTouYFCReFzVhrh1rF:-OCTwDTx2mhyzbKYnRsB:bqfaxja) ([raw file](https://github.com/starkware-libs/cairo/blob/1fbfba6e21c79e14594fbac1bc594e05f733b3e4/crates/cairo-lang-formatter/src/formatter_impl.rs#L1082)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if so - just rename `key` to `decorations` and remove the doc.

and call it `decorations` all around.

and call the map `decoration_to_use_tree`
</blockquote></details>

It was my bad, forgot to do that..
Fixed now.
___
*[`crates/cairo-lang-formatter/src/formatter_impl.rs` line 107 at r10](https://reviewable.io/reviews/starkware-libs/cairo/6571#-OCTfmFS8_HzUwiQnPRF:-OCTgfy-EWWHd5DGKZwt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/b72af50b4c41fa12f0866c61b4a76012f29f9659/crates/cairo-lang-formatter/src/formatter_impl.rs#L107)):*
> ```XML
>             }
>             _ => {}
>         }
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-11-24 16:20 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6571#-:-OCTyQ-P-b6TQSnjhfHf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2024-11-24 16:55 UTC, merged