Moved logic of building runnable to runnable-builder.
starkware-libs/cairo pull request #6575
Opened 2024-11-03 13:08 UTC by orizi

2024-11-03 13:08 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6575)
<!-- Reviewable:end -->

2024-11-03 13:13 UTC, gilbens-starkware requested changes
> Reviewed 3 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6575)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @orizi)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6575#-OAm8pQc7Vu4BAg7nHIY:-OAm8pQc7Vu4BAg7nHIZ:b-h2nslk) (no related file):*
Add to publish_crates and ci.yml

___


<!-- Sent from Reviewable.io -->

2024-11-03 14:02 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6575)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6575#-OAm8pQc7Vu4BAg7nHIY:-OAmKH6w0ukR8Ht7jwCt:b-896fix) (no related file):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Add to publish_crates and ci.yml
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2024-11-04 07:45 UTC, gilbens-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6575#-:-OAq6n5UAq-HnzK3kuR3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-11-04 10:47 UTC, merged