Adding docstrings for array, assert and panic macros
starkware-libs/cairo pull request #6627
Opened 2024-11-11 17:58 UTC by Gerson2102

## Changes Made

This PR is adding the docstrings for some macros in the basecode. Specifically for `assert!`, `panic!`, `array!` macros.

## Status

This PR still work in progress. But I would like to receive some feedback about the work so far.

## Errors

I dont know why I'm getting these errors for some of the macros related to format. Look these screenshots:

![image](https://github.com/user-attachments/assets/4dca2e54-2781-49f8-993f-ee5292ae6f68)
![image](https://github.com/user-attachments/assets/01c82af0-a9f1-461b-abd1-9693c4e6620f)

In many places in the code of the macros I'm getting those weird errors.

2024-11-11 17:58 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6627)
<!-- Reviewable:end -->

2024-11-11 22:24 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6627)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Gerson2102)

___
*[`crates/cairo-lang-semantic/src/inline_macros/array.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6627#-OBSJtuk7B0ASgoFdyEW:-OBSJtuk7B0ASgoFdyEX:ba7cer8) ([raw file](https://github.com/starkware-libs/cairo/blob/fc7c1f31065a19259f5043fd6517ae9cd9f25fc5/crates/cairo-lang-semantic/src/inline_macros/array.rs#L90)):*
> ```XML
> 
>             "#}
>             .to_string(),
> ```

remove whitespace lines, and shorten lines longer than 100 chars.



_Code quote:_
```XML
    fn documentation(&self) -> Option<String> {
        Some(
            indoc! {r#"
            Creates a new array containing the provided elements.

            The `array!` macro allows you to create an array by specifying a list of elements. \
            The elements are added to a new array in the order they are provided.

            # Syntax

            ```cairo
            array![element1, element2, element3, ...]
            ```

            # Returns

            An array containing the specified elements.

            # Examples

            ```cairo
            let arr = array![]; // Creates an empty array.

            let arr = array![1, 2, 3]; // Creates an array containing 1, 2, and 3.

            let x = 5;
            let y = 10;
            let arr = array![x, y, x + y]; // Creates an array containing 5, 10, and 15.
            ```

            # Notes

            - All elements must be of the same type or compatible types that can be coerced to a common type.
            - The macro internally uses `ArrayTrait::new()` to create a new array and `ArrayTrait::append()` to add each element.
            - The order of the elements in the array is the same as the order they are provided in the macro.

            "#}
            .to_string(),
```


<!-- Sent from Reviewable.io -->

2024-11-11 23:09 UTC, Gerson2102 commented
Lmk what you think now sir.

2024-11-12 06:34 UTC, orizi requested changes
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6627)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @Gerson2102)

___
*[`crates/cairo-lang-semantic/src/inline_macros/assert.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6627#-OBU411Q4OLVdxf70bLQ:-OBU411Q4OLVdxf70bLR:blctf2m) ([raw file](https://github.com/starkware-libs/cairo/blob/25427e034594dbb97d4eafa2df85203f35b57de0/crates/cairo-lang-semantic/src/inline_macros/assert.rs#L11)):*
> ```XML
> use cairo_lang_syntax::node::ast::WrappedArgList;
> use cairo_lang_syntax::node::db::SyntaxGroup;
> use cairo_lang_syntax::node::{ast, TypedStablePtr, TypedSyntaxNode};
> ```

Please rebase to use the latest rust fmt version.


<!-- Sent from Reviewable.io -->

2024-11-12 10:08 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6627)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @Gerson2102 and @orizi)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6627#-OBUq4II6g3kttRIprBu:-OBUq4II6g3kttRIprBv:b-yzvydy) (no related file):*
1. Please use Reviewable for commenting

2.
> I dont know why I'm getting these errors for some of the macros related to format. Look these screenshots:

You need to import the indoc macro, add `use indoc::indoc` 


<!-- Sent from Reviewable.io -->

2024-11-12 10:20 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6627)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @Gerson2102 and @mkaput)

___
*[`crates/cairo-lang-semantic/src/inline_macros/array.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6627#-OBUsUaN54kogBso3iM1:-OBUsUaO2RH9BU1KhNGP:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/25427e034594dbb97d4eafa2df85203f35b57de0/crates/cairo-lang-semantic/src/inline_macros/array.rs#L80)):*
> ```XML
>             - Elements are added in the order provided.
>             "#}
>             .to_string(),
> ```





_Suggestion:_
```XML
    fn documentation(&self) -> Option<String> {
        Some(
            indoc! {r#"
            Creates a new array containing the provided elements.
            The `array!` macro allows you to create an array by specifying a list of elements. \
            The elements are added to a new array in the order they are provided.

            # Syntax
            ```cairo
            array![element1, element2, element3, ...]
            ```
            # Returns
            An array containing the specified elements.

            # Examples
            ```cairo
            let arr = array![]; // Creates an empty array.
            let arr = array![1, 2, 3]; // Creates an array containing 1, 2, and 3.
            let x = 5;
            let y = 10;
            let arr = array![x, y, x + y]; // Creates an array containing 5, 10, and 15.
            ```
            # Notes
            - Elements must be of the same type or convertible to a common type.
            - Uses `ArrayTrait::new()` to create the array and `ArrayTrait::append()` to add \
            elements.
            - Elements are added in the order provided.
            "#}
            .to_string(),
```


<!-- Sent from Reviewable.io -->

2024-11-12 23:01 UTC, Gerson2102 commented
I was inside of the Reviewable but I did not find a way to comment through that tool, sorry. Is my first time using it.

2024-11-12 23:03 UTC, Gerson2102 commented
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

1. Please use Reviewable for commenting

2.
> I dont know why I'm getting these errors for some of the macros related to format. Look these screenshots:

You need to import the indoc macro, add `use indoc::indoc`
</blockquote></details>

Got it sir. Now I know how to comment through reviewable. Thanks.


<!-- Sent from Reviewable.io -->

2024-11-12 23:04 UTC, Gerson2102 commented
*[`crates/cairo-lang-semantic/src/inline_macros/assert.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6627#-OBU411Q4OLVdxf70bLQ:-OBXbjIXDJplzU9WSBK9:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/7f576c0b137159e5f2d1b7f1ad108df760718a96/crates/cairo-lang-semantic/src/inline_macros/assert.rs#L11)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Please rebase to use the latest rust fmt version.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-12 23:04 UTC, Gerson2102 commented
*[`crates/cairo-lang-semantic/src/inline_macros/array.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6627#-OBUsUaN54kogBso3iM1:-OBXblZECyf-X0JNMzAQ:bqqfrjk) ([raw file](https://github.com/starkware-libs/cairo/blob/7f576c0b137159e5f2d1b7f1ad108df760718a96/crates/cairo-lang-semantic/src/inline_macros/array.rs#L80)):*
> ```XML
>             - Elements are added in the order provided.
>             "#}
>             .to_string(),
> ```

I think I addressed what you suggested. If not, please lmk.


<!-- Sent from Reviewable.io -->

2024-11-13 05:30 UTC, orizi requested changes
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6627)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @Gerson2102 and @mkaput)

___
*[`crates/cairo-lang-semantic/src/inline_macros/assert.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6627#-OBU411Q4OLVdxf70bLQ:-OBYzsVr9MAe0Mm7YhMZ:b-w3kgqe) ([raw file](https://github.com/starkware-libs/cairo/blob/7f576c0b137159e5f2d1b7f1ad108df760718a96/crates/cairo-lang-semantic/src/inline_macros/assert.rs#L11)):*
<details><summary><i>Previously, Gerson2102 (Gerson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

now also run `./scripts/rust_fmt.sh` before pushing.

this should revert the bad formatting changes.
___
*[`crates/cairo-lang-semantic/src/inline_macros/assert.rs` line 132 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6627#-OBYzWXB-2PWoFy8KJe6:-OBYzWXB-2PWoFy8KJe7:b-mb06pk) ([raw file](https://github.com/starkware-libs/cairo/blob/a5e69d2c70e5458f96c8de1f4e99beb59c858f90/crates/cairo-lang-semantic/src/inline_macros/assert.rs#L132)):*
> ```XML
>             - `condition`: A boolean expression to evaluate.
>             - `format_string` (optional): A string literal for format placeholders.
>             - `args` (optional): Arguments corresponding to the format placeholders in the `format_string`.
> ```

shorten or split line. (under `100` rust chars) 
also elsewhere if still exists.



_Code quote:_
```XML
            - `args` (optional): Arguments corresponding to the format placeholders in the `format_string`.
```
___
*[`crates/cairo-lang-semantic/src/inline_macros/assert.rs` line 142 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6627#-OBYzNX98kSj4stWLjcU:-OBYzNXAEbhKe19FMoYm:bfs5s55) ([raw file](https://github.com/starkware-libs/cairo/blob/a5e69d2c70e5458f96c8de1f4e99beb59c858f90/crates/cairo-lang-semantic/src/inline_macros/assert.rs#L142)):*
> ```XML
>             // Panics with "Age must be at least 21, found 18."
>             let x = -1;
>             assert!(x >= 0, "Invalid value: x = {}", x);
> ```

maybe we should have an example with this style?
in `panic` as well.



_Suggestion:_
```XML
            assert!(x >= 0, "Invalid value: x = {x}");
```


<!-- Sent from Reviewable.io -->

2024-11-13 14:40 UTC, Gerson2102 commented
*[`crates/cairo-lang-semantic/src/inline_macros/assert.rs` line 142 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6627#-OBYzNX98kSj4stWLjcU:-OB_y0tp-loRLY0Y5LKW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a5e69d2c70e5458f96c8de1f4e99beb59c858f90/crates/cairo-lang-semantic/src/inline_macros/assert.rs#L142)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe we should have an example with this style?
in `panic` as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-13 14:53 UTC, Gerson2102 commented
*[`crates/cairo-lang-semantic/src/inline_macros/assert.rs` line 132 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6627#-OBYzWXB-2PWoFy8KJe6:-OBa-vxW5Kp3pi4a63Wr:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a5e69d2c70e5458f96c8de1f4e99beb59c858f90/crates/cairo-lang-semantic/src/inline_macros/assert.rs#L132)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

shorten or split line. (under `100` rust chars) 
also elsewhere if still exists.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-13 17:46 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6627#-:-OBacUeK0hIAWZaIWMPi:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Gerson2102)



<!-- Sent from Reviewable.io -->

2024-11-13 22:47 UTC, Gerson2102 commented
I dont find the `assert_eq!` macro, it doesn't exist on the basecode?





<!-- Sent from Reviewable.io -->

2024-11-14 05:34 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6627)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @Gerson2102 and @mkaput)

___
*[`crates/cairo-lang-semantic/src/inline_macros/consteval_int.rs` line 69 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6627#-OBd9RzuD0c82r1MAKEg:-OBd9RzuD0c82r1MAKEh:bj73zip) ([raw file](https://github.com/starkware-libs/cairo/blob/35422d1006d838aea65eefbe52d54b902fccd999/crates/cairo-lang-semantic/src/inline_macros/consteval_int.rs#L69)):*
> ```XML
>         Some(
>             indoc! {r#"
>             Evaluates an integer expression at compile time.
> ```

State the fact or is deprecated, as can be done with normal consts.
___
*[`crates/cairo-lang-semantic/src/inline_macros/consteval_int.rs` line 86 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6627#-OBd9dFUCbq7a9jFBt01:-OBd9dFUCbq7a9jFBt02:bfwb4mi) ([raw file](https://github.com/starkware-libs/cairo/blob/35422d1006d838aea65eefbe52d54b902fccd999/crates/cairo-lang-semantic/src/inline_macros/consteval_int.rs#L86)):*
> ```XML
>             ```
>             # Notes
>             - Useful for compile-time computations when const expressions were not fully supported.
> ```

It no longer is useful.


<!-- Sent from Reviewable.io -->

2024-11-14 05:35 UTC, orizi reviewed
It is in the test plugin, and not the general plugin

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6627#-:-OBd9nNv63N2JdejoyNK:bpwv4xt)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @Gerson2102 and @mkaput)



<!-- Sent from Reviewable.io -->

2024-11-14 05:43 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6627#-:-OBdBg1K0FtjawpGMyLA:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Gerson2102)



<!-- Sent from Reviewable.io -->

2024-11-14 16:07 UTC, mkaput approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6627)* status: all files reviewed, 2 unresolved discussions (waiting on @Gerson2102)



<!-- Sent from Reviewable.io -->

2024-11-14 16:08 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6627#-:-OBfQl-2DwlpAVENi3Ko:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Gerson2102)



<!-- Sent from Reviewable.io -->

2024-11-14 16:29 UTC, Gerson2102 commented
I found the `assert_eq!` macro in `cairo-lang-test-plugin`. And inside of the assert.rs file is not too clear for me where to add the function. Do I add it just next to the `generate_code`function and thats it?





<!-- Sent from Reviewable.io -->

2024-11-15 06:20 UTC, mkaput approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6627)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Gerson2102)



<!-- Sent from Reviewable.io -->

2024-11-19 08:18 UTC, merged