LS: Discover struct members in constructor
starkware-libs/cairo pull request #6632
Opened 2024-11-12 10:49 UTC by integraledelebesgue

Closes #6537

## Changes
* Struct members in constructors are properly recognized and generate hovers identical as members in any other context (e.g. `struct_var.member`)
* New test fixture - `structs.txt` - covers all struct member hovers scenarios

2024-11-12 10:49 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6632)
<!-- Reviewable:end -->

2024-11-14 08:14 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6632#-:-OBdjIEL0_fSxHdT4_j2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-11-14 14:41 UTC, mkaput approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6632)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-11-14 15:57 UTC, piotmag769 requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6632)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @integraledelebesgue)

___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 383 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6632#-OBfMkal7H9MLYONiiH6:-OBfMkal7H9MLYONiiH7:b-m1tgmf) ([raw file](https://github.com/starkware-libs/cairo/blob/64a30c38957d6b08cf1f8e84b4dd71b9e338636e/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L383)):*
> ```XML
>     let struct_member = ast::StructArgSingle::from_syntax_node(db, struct_member);
> 
>     let ast::OptionStructArgExpr::StructArgExpr(struct_member_expr) = struct_member.arg_expr(db)
> ```

`OptionStructArgExpr::Empty` is also a valid path here, it mean that the expression looks like this:
```cairo
let my_field = 5;

MyStruct {
   my_field,
}
```
I think we want to handle it as well


<!-- Sent from Reviewable.io -->

2024-11-15 13:11 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6632)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, @mkaput, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 383 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6632#-OBfMkal7H9MLYONiiH6:-OBjwY6p1iebctcrA2z2:b-ih474u) ([raw file](https://github.com/starkware-libs/cairo/blob/64a30c38957d6b08cf1f8e84b4dd71b9e338636e/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L383)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

`OptionStructArgExpr::Empty` is also a valid path here, it mean that the expression looks like this:
```cairo
let my_field = 5;

MyStruct {
   my_field,
}
```
I think we want to handle it as well
</blockquote></details>

I changed the implementation to handle this case. However, `OptionStructArgExpr::Empty` doesn't have any useful functions to retrieve `ExprId`s etc. thus I had to change the whole implementation to match members by names. Please have a look


<!-- Sent from Reviewable.io -->

2024-11-18 05:04 UTC, mkaput approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6632)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-11-18 08:37 UTC, piotmag769 requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6632)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @integraledelebesgue)

___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 383 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6632#-OBfMkal7H9MLYONiiH6:-OByPuf4A2aoWGNj3vce:b-q2ifu8) ([raw file](https://github.com/starkware-libs/cairo/blob/64a30c38957d6b08cf1f8e84b4dd71b9e338636e/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L383)):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

I changed the implementation to handle this case. However, `OptionStructArgExpr::Empty` doesn't have any useful functions to retrieve `ExprId`s etc. thus I had to change the whole implementation to match members by names. Please have a look
</blockquote></details>

Can you add a relevant test case?


<!-- Sent from Reviewable.io -->

2024-11-18 08:39 UTC, piotmag769 reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6632)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @integraledelebesgue)



<!-- Sent from Reviewable.io -->

2024-11-18 08:47 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6632)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae, @Draggu, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/inspect/defs.rs` line 383 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6632#-OBfMkal7H9MLYONiiH6:-OByS1zRE0m-mlTCH8So:bmfxgaw) ([raw file](https://github.com/starkware-libs/cairo/blob/64a30c38957d6b08cf1f8e84b4dd71b9e338636e/crates/cairo-lang-language-server/src/lang/inspect/defs.rs#L383)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Can you add a relevant test case?
</blockquote></details>

Done :)


<!-- Sent from Reviewable.io -->

2024-11-18 08:57 UTC, piotmag769 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6632#-:-OBySLsK--4-9mN4C7yz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Arcticae and @Draggu)



<!-- Sent from Reviewable.io -->

2024-11-18 08:57 UTC, piotmag769 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6632)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae and @Draggu)



<!-- Sent from Reviewable.io -->

2024-11-18 09:36 UTC, merged