Made builder inject output-ptr for provable mode.
starkware-libs/cairo pull request #6643
Opened 2024-11-12 14:13 UTC by orizi

**Stack**:
- #6643 ⬅
- #6642
- #6641
- #6640
- #6639

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-11-12 14:13 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6643)
<!-- Reviewable:end -->

2024-11-17 20:02 UTC, gilbens-starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6643)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-runnable-utils/src/builder.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6643#-OBvhz2r0MKhm7sFJ62y:-OBvhz2r0MKhm7sFJ62z:bxgg06y) ([raw file](https://github.com/starkware-libs/cairo/blob/452e65bcb066d697f55be82c33615da06a9861f7/crates/cairo-lang-runnable-utils/src/builder.rs#L249)):*
> ```XML
>     ///
>     /// If true, will expect the function signature to be `(Span<felt252>, Array<felt252>) ->
>     /// Array<felt252>`. And will inject the output builtin to be the supplied array input, and
> ```

Why 2 arrays?



_Code quote:_
```XML
    /// If true, will expect the function signature to be `(Span<felt252>, Array<felt252>) ->
    /// Array<felt252>`. And will inject the output builtin to be the supplied array input, and
```


<!-- Sent from Reviewable.io -->

2024-11-18 07:04 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6643)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-runnable-utils/src/builder.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6643#-OBvhz2r0MKhm7sFJ62y:-OBy4a_c13WDCblw1O6I:b-9dib2o) ([raw file](https://github.com/starkware-libs/cairo/blob/452e65bcb066d697f55be82c33615da06a9861f7/crates/cairo-lang-runnable-utils/src/builder.rs#L249)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Why 2 arrays?
</blockquote></details>

it is an input-output parameter which is the output-ptr.


<!-- Sent from Reviewable.io -->

2024-11-18 08:51 UTC, gilbens-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6643#-:-OBySx-KEtmiep4xQKLu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-11-18 10:22 UTC, merged