Added validation for `runnable_raw` attribute.
starkware-libs/cairo pull request #6648
Opened 2024-11-13 10:31 UTC by orizi

**Stack**:
- #6643
- #6648 ⬅
- #6642
- #6640
- #6641

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-11-13 10:32 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6648)
<!-- Reviewable:end -->

2024-11-17 20:01 UTC, gilbens-starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6648)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-runnable/src/plugin.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6648#-OBvhiHQ53bok_bMEKo9:-OBvhiHQ53bok_bMEKoA:bbgojyq) ([raw file](https://github.com/starkware-libs/cairo/blob/26906d5f4320432e17f46f4f803351c619a95b27/crates/cairo-lang-runnable/src/plugin.rs#L187)):*
> ```XML
>                     input.stable_ptr.untyped(),
>                     "Invalid first param mutability for `#[runnable_raw]` function, got \
>                      unexpected `ref`."
> ```

Is immutable valid?



_Code quote:_
```XML
                    "Invalid first param mutability for `#[runnable_raw]` function, got \
                     unexpected `ref`."
```


<!-- Sent from Reviewable.io -->

2024-11-18 07:04 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6648)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-runnable/src/plugin.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6648#-OBvhiHQ53bok_bMEKo9:-OBy4SIk3MLSnKRDCWCx:bmspwud) ([raw file](https://github.com/starkware-libs/cairo/blob/26906d5f4320432e17f46f4f803351c619a95b27/crates/cairo-lang-runnable/src/plugin.rs#L187)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Is immutable valid?
</blockquote></details>

yes - if you don't use the input it is totally valid.
only ref is bad.


<!-- Sent from Reviewable.io -->

2024-11-18 08:19 UTC, closed without merging

2024-11-18 08:53 UTC, gilbens-starkware reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6648#-:-OByTN9jDoosF_YQtoEN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->