LS: Refactor `DiagnosticsController`
starkware-libs/cairo pull request #6657
Opened 2024-11-14 06:37 UTC by mkaput

This commit prepares `DiagnosticsController`
for adding multithreaded processing.

1. `DiagnosticsController::refresh` takes shared reference to owned
state and makes snapshots internally. It needs it to create `N`
snapshots for many threads.
2. Encapsulated controller thread state into a struct.
3. `Notifier` and `file_diagnostics` are now stored in controller's
state instead of being passed around.
4. Some minor renames and doc rewordings.

---

**Stack**:
- #6631
- #6615

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-11-14 06:37 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6657)
<!-- Reviewable:end -->

2024-11-14 08:14 UTC, piotmag769 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6657#-:-OBdiseDDqg2qBcwiBlk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @Draggu, and @orizi)



<!-- Sent from Reviewable.io -->

2024-11-14 10:06 UTC, Arcticae reviewed
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6657)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu and @orizi)



<!-- Sent from Reviewable.io -->

2024-11-14 10:07 UTC, Arcticae approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6657#-:-OBe87f766GRCJAiWlYN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Draggu and @orizi)



<!-- Sent from Reviewable.io -->

2024-11-14 12:13 UTC, Draggu requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6657)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6657#-OBe_R7819M1GJDUAVcR:-OBe_R7819M1GJDUAVcS:bwqtx7m) ([raw file](https://github.com/starkware-libs/cairo/blob/77e2b06d9c51819f9d8a737bcaaf04c60e8c9040/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L32)):*
> ```XML
>     //   Otherwise, the controller thread will never be requested to stop, and the controller's
>     //   JoinHandle will never terminate.
>     trigger: trigger::Sender<StateSnapshot>,
> ```

How do you plan making multiple snapshots from this? `salsa` snapshot is `!Clone` and can only be made from db itself, not another snapshot, as so we must prepare `N` snapshots on LS main thread so we can distribute them here.


<!-- Sent from Reviewable.io -->

2024-11-14 13:50 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6657)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Draggu, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6657#-OBe_R7819M1GJDUAVcR:-OBevyC16Jd-Ui9vA65H:bn4mjru) ([raw file](https://github.com/starkware-libs/cairo/blob/77e2b06d9c51819f9d8a737bcaaf04c60e8c9040/crates/cairo-lang-language-server/src/lang/diagnostics/mod.rs#L32)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

How do you plan making multiple snapshots from this? `salsa` snapshot is `!Clone` and can only be made from db itself, not another snapshot, as so we must prepare `N` snapshots on LS main thread so we can distribute them here.
</blockquote></details>

See how I did it in #6658 


<!-- Sent from Reviewable.io -->

2024-11-14 14:29 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6657)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @orizi and @piotmag769)

___
*[`-- commits` line 9 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6657#-OBewThJCVAZxPx2koME:-OBf3rLS2BEpAZgarf9l:b-teyna0):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

If you are doing this in next PR please move it to mentioned PR.
</blockquote></details>

you mean moving the description?

i changed signature here because it breaks diff for next PR (marks too much code as diffing)


<!-- Sent from Reviewable.io -->

2024-11-14 14:46 UTC, Draggu reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6657)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @mkaput, @orizi, and @piotmag769)

___
*[`-- commits` line 9 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6657#-OBewThJCVAZxPx2koME:-OBf7T270FZeapILWE3V:b-ip3lbv):*
> you mean moving the description?

Yes, it states that making `N` snapshots is done here while it is not.


<!-- Sent from Reviewable.io -->

2024-11-18 06:37 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6657)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @orizi and @piotmag769)

___
*[`-- commits` line 9 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6657#-OBewThJCVAZxPx2koME:-OBxeOnKDnHV8p8cEmPS:bb6un1j):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

> you mean moving the description?

Yes, it states that making `N` snapshots is done here while it is not.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-11-18 09:36 UTC, merged