LS: React to adding/deleting workspace folders
starkware-libs/cairo pull request #6715
Opened 2024-11-21 10:44 UTC by Arcticae

Additions and deletions of folders should cause the client to be stopped/restarted/started and assessed which action is necessary, based on some prerequisites. We don't want to stop it when it's not necessary, mostly because of diagnostics and wasted time on waiting (sometimes stopping is simply not required).

The rough idea can be described with those graphs:

![Multi-Root Workspaces flow drawio](https://github.com/user-attachments/assets/c91875c0-3462-4640-9777-21d31ed3c33b)

2024-11-22 13:33 UTC, mkaput requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6715)* status: all files reviewed, 8 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/extension.ts` line 24 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCJ3UxxDQKFGxzWm0bS:-OCJ3UxxDQKFGxzWm0bT:b-kl0csc) ([raw file](https://github.com/starkware-libs/cairo/blob/3dcf78ad9e624e7db54598a9ee47bfc3b94c2113/vscode-cairo/src/extension.ts#L24)):*
> ```XML
>   client = undefined;
>   runningExecutable = undefined;
> }
> ```

consider extracting a separate module with this. in general this code grew to a level I would encapsulate it into some kind of _Manager_ module or singleton, along all these command equality checks and event handlers

I have an impression that this PR smears added logic significantly. :(



_Code quote:_
```XML
let runningExecutable: LSExecutable | undefined;

export async function startClient(ctx: Context) {
  const setupResult = await setupLanguageServer(ctx);
  if (!setupResult) {
    return;
  }
  const [newClient, newExecutable] = setupResult;
  client = newClient;
  runningExecutable = newExecutable;
}

export async function stopClient() {
  await client?.stop();
  client = undefined;
  runningExecutable = undefined;
}
```
___
*[`vscode-cairo/src/extension.ts` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCJ3PTPBtT9biWKoAN3:-OCJ3PTPBtT9biWKoAN4:bo00ncv) ([raw file](https://github.com/starkware-libs/cairo/blob/3dcf78ad9e624e7db54598a9ee47bfc3b94c2113/vscode-cairo/src/extension.ts#L46)):*
> ```XML
>         ctx.extension.subscriptions,
>       ),
>     );
> ```

could you please explain this fragment to me? why do you need this?



_Code quote:_
```XML
    // Notify the server when the client configuration changes.
    // CairoLS pulls configuration properties it is interested in by itself, so it
    // is unnecessary to attach any details in the notification payload.
    ctx.extension.subscriptions.push(
      vscode.workspace.onDidChangeConfiguration(
        async () => {
          if (client != undefined) {
            await client.sendNotification(lc.DidChangeConfigurationNotification.type, {
              settings: "",
            });
          }
        },
        null,
        ctx.extension.subscriptions,
      ),
    );
```
___
*[`vscode-cairo/src/statusBar.ts` line 45 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCJ14Sw9SYkY4-Dlq98:-OCJ14Sw9SYkY4-Dlq99:bbapc5v) ([raw file](https://github.com/starkware-libs/cairo/blob/3dcf78ad9e624e7db54598a9ee47bfc3b94c2113/vscode-cairo/src/statusBar.ts#L45)):*
> ```XML
>   }
> 
>   async updateScarbVersion(): Promise<void> {
> ```

you do not use this method anyway so please revert this change
___
*[`vscode-cairo/src/workspace.ts` line 8 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCJ2QSO4hacizVcIs35:-OCJ2QSO4hacizVcIs36:b88quu6) ([raw file](https://github.com/starkware-libs/cairo/blob/3dcf78ad9e624e7db54598a9ee47bfc3b94c2113/vscode-cairo/src/workspace.ts#L8)):*
> ```XML
> export async function handleWorkspaceFoldersAdded(
>   newWorkspaceFolders: readonly vscode.WorkspaceFolder[],
>   runningExecutable: LSExecutable | undefined,
> ```

it is weird that you're passing this global as argument here. you won't need this if you extract the `if(!runningExecutable) startClient()` pattern to a function
___
*[`vscode-cairo/src/workspace.ts` line 23 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCJ2Jt3ALit1SLpQ915:-OCJ2Jt3ALit1SLpQ916:b-s64bcp) ([raw file](https://github.com/starkware-libs/cairo/blob/3dcf78ad9e624e7db54598a9ee47bfc3b94c2113/vscode-cairo/src/workspace.ts#L23)):*
> ```XML
>     if (!runningExecutable) {
>       ctx.log.debug(
>         `Added folder(s) (${newWorkspaceFolders.map((x) => x.uri.fsPath)} ) have same provider - starting the client`,
> ```

logs start lowercase
___
*[`vscode-cairo/src/workspace.ts` line 25 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCJ1itpBR-CsliuUUSs:-OCJ1itpBR-CsliuUUSt:b-w9ud2j) ([raw file](https://github.com/starkware-libs/cairo/blob/3dcf78ad9e624e7db54598a9ee47bfc3b94c2113/vscode-cairo/src/workspace.ts#L25)):*
> ```XML
>         `Added folder(s) (${newWorkspaceFolders.map((x) => x.uri.fsPath)} ) have same provider - starting the client`,
>       );
>       await startClient(ctx);
> ```

It looks like you're not respecting the `enableLanguageServer` config here. In general, this pattern is pretty repetitive, consider extracting a function.
___
*[`vscode-cairo/src/workspace.ts` line 34 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCJ2v25Bua9_u3CeGWu:-OCJ2v25Bua9_u3CeGWv:b-wljh6d) ([raw file](https://github.com/starkware-libs/cairo/blob/3dcf78ad9e624e7db54598a9ee47bfc3b94c2113/vscode-cairo/src/workspace.ts#L34)):*
> ```XML
>       ctx,
>     );
>     // If it's not, we need to stop LS and show an error
> ```

I am very much missing a doc why you're stopping the client in this scenario. It took me a while to realise that you're doing this because it's better to stop analysis than do broken analysis. And this behaviour explains stuff like why you're starting new clients in weird places like `handleWorkspaceFoldersRemoved`, so in general, this little context could explain a lot.
___
*[`vscode-cairo/src/workspace.ts` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCJ28qT-PA-ov97uFaf:-OCJ28qT-PA-ov97uFag:bveksc7) ([raw file](https://github.com/starkware-libs/cairo/blob/3dcf78ad9e624e7db54598a9ee47bfc3b94c2113/vscode-cairo/src/workspace.ts#L38)):*
> ```XML
>       await stopClient();
>       vscode.window.showErrorMessage(
>         "Added folder does not have the same scarb version. Please remove it from the workspace, or adjust the used scarb version.",
> ```

Scarb uppercase, also TBH this is a bit broken english to me, and also it'd be good to notify the user that analysis will stop until they fix the problem.


<!-- Sent from Reviewable.io -->

2024-11-26 09:10 UTC, mkaput reviewed
> Reviewed 3 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6715)* status: 3 of 8 files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/extension.ts` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCJ3PTPBtT9biWKoAN3:-OCbiwEA6En4d_BR0U-T:b-iqq7r3) ([raw file](https://github.com/starkware-libs/cairo/blob/3dcf78ad9e624e7db54598a9ee47bfc3b94c2113/vscode-cairo/src/extension.ts#L46)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

could you please explain this fragment to me? why do you need this?
</blockquote></details>

I'm dumb. I wrote this code and forgot about it


<!-- Sent from Reviewable.io -->

2024-11-26 09:32 UTC, mkaput requested changes
> Reviewed 5 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6715)* status: all files reviewed, 8 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 46 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCbl35RETx1hIl4lWrl:-OCbl35RETx1hIl4lWrm:b-amkcsx) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/cairols.ts#L46)):*
> ```XML
> 
>   const run = lsExecutable.preparedInvocation;
>   const scarb = lsExecutable.scarb;
> ```

nit, wdyt?



_Suggestion:_
```XML
  assert(executables[0], "executable should be present at this point");
  const [{ preparedInvocation: run, scarb }] = executables;
```
___
*[`vscode-cairo/src/extensionManager.ts` line 8 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCbnePQDZaNHmbutbxK:-OCbnePQDZaNHmbutbxL:b-txhhoa) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/extensionManager.ts#L8)):*
> ```XML
> import assert from "node:assert";
> 
> export class CairoExtensionManager {
> ```

please document here why we are maintaining only one client
___
*[`vscode-cairo/src/extensionManager.ts` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCbnGIZ0B3vDxlKUaq_:-OCbnGI_3EBsOLY01Ge-:b-7ipy8c) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/extensionManager.ts#L20)):*
> ```XML
> 
>   // Starts the server, sets up the client and returns status
>   public async tryStartClient(): Promise<boolean> {
> ```

tsdoc



_Suggestion:_
```XML
  /**
   * Starts the server, sets up the client and returns status.
   */
  public async tryStartClient(): Promise<boolean> {
```
___
*[`vscode-cairo/src/extensionManager.ts` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCbnwt7CnUdLrNbOoZK:-OCbnwt7CnUdLrNbOoZL:b-wnoop4) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/extensionManager.ts#L20)):*
> ```XML
> 
>   // Starts the server, sets up the client and returns status
>   public async tryStartClient(): Promise<boolean> {
> ```

It looks like you're not respecting the `enableLanguageServer` config here. Mind that it can change in the runtime and I even think we should listen for this config changes and start/restart LS appropriately (though this is a topic for separate PR)
___
*[`vscode-cairo/src/extensionManager.ts` line 43 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCbnXaEEYaLn3chzMST:-OCbnXaEEYaLn3chzMSU:bhbuqeu) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/extensionManager.ts#L43)):*
> ```XML
>   public getClient(): lc.LanguageClient | undefined {
>     return this.client;
>   }
> ```

this can easily be a `public readonly` property



_Code quote:_
```XML
  public getClient(): lc.LanguageClient | undefined {
    return this.client;
  }
```
___
*[`vscode-cairo/src/extensionManager.ts` line 57 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCboAOX9mK8F2CCyYYS:-OCboAOY6q77F4a9BXlM:b-a0dr9h) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/extensionManager.ts#L57)):*
> ```XML
>     }
> 
>     // Check if new ones are of same provider
> ```

all these comments are missing dots
___
*[`vscode-cairo/src/extension.ts` line 44 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCbjZV03cZLh79zCQWB:-OCbjZV03cZLh79zCQWC:b-qx8kee) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/extension.ts#L44)):*
> ```XML
>         null,
>         ctx.extension.subscriptions,
>       ),
> ```

wdyt about extracting entire logic into `extensionManager`



_Suggestion:_
```XML
      vscode.workspace.onDidChangeWorkspaceFolders(
        extensionManager.onDidChangeWorkspaceFolders,
        extensionManager // this argument sets proper `this` in the callback
        ctx.extension.subscriptions,
      ),
```
___
*[`vscode-cairo/src/extension.ts` line 46 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCbjpD25ep4xKSEZ_sw:-OCbjpD25ep4xKSEZ_sx:b-f98hx7) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/extension.ts#L46)):*
> ```XML
>       ),
>     );
>     ctx.extension.subscriptions.push({ dispose: extensionManager.stopClient });
> ```

I think `extensionManager` should just be a disposable directly


<!-- Sent from Reviewable.io -->

2024-11-26 09:42 UTC, Arcticae reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6715)* status: all files reviewed, 8 unresolved discussions (waiting on @Draggu, @integraledelebesgue, @mkaput, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/extension.ts` line 46 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCJ3PTPBtT9biWKoAN3:-OCJE4Pb1Eu5yT8feRkH:bxqs1up) ([raw file](https://github.com/starkware-libs/cairo/blob/3dcf78ad9e624e7db54598a9ee47bfc3b94c2113/vscode-cairo/src/extension.ts#L46)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I'm dumb. I wrote this code and forgot about it
</blockquote></details>

Forgot to reply, but yes. It was just copied over 
___
*[`vscode-cairo/src/extension.ts` line 44 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCbjZV03cZLh79zCQWB:-OCboxBaCvtkEWcaqOMx:b-pbgiqq) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/extension.ts#L44)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

wdyt about extracting entire logic into `extensionManager`
</blockquote></details>

Can do, perhaps it's better
___
*[`vscode-cairo/src/extension.ts` line 46 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCbjpD25ep4xKSEZ_sw:-OCbp-zBAEc7WxwkWUiX:b-tltirk) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/extension.ts#L46)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I think `extensionManager` should just be a disposable directly
</blockquote></details>

Matter of taste but i think that rather pollutes the `extensionManager`, and the logic here is not much anyways
___
*[`vscode-cairo/src/extensionManager.ts` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCbnwt7CnUdLrNbOoZK:-OCbpQEH-_cUEC22bxr9:blp50d6) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/extensionManager.ts#L20)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

It looks like you're not respecting the `enableLanguageServer` config here. Mind that it can change in the runtime and I even think we should listen for this config changes and start/restart LS appropriately (though this is a topic for separate PR)
</blockquote></details>

It wasn't supported before so it's def out of scope here - new issue: #6737  
___
*[`vscode-cairo/src/extensionManager.ts` line 43 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCbnXaEEYaLn3chzMST:-OCbq8aQ475r9aCMWILe:buv6e6u) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/extensionManager.ts#L43)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

this can easily be a `public readonly` property
</blockquote></details>

No it cannot because i want to mutate it during the course of the object lifetime (turning the client off and on again results in this behavior)


<!-- Sent from Reviewable.io -->

2024-11-26 10:10 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6715)* status: all files reviewed, 7 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/extension.ts` line 46 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCbjpD25ep4xKSEZ_sw:-OCbwTAs-fL54xpwnEwk:b-lno7ox) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/extension.ts#L46)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Matter of taste but i think that rather pollutes the `extensionManager`, and the logic here is not much anyways
</blockquote></details>

slightly disagree because I find the fact that something is treated as a disposable pretty important
___
*[`vscode-cairo/src/extensionManager.ts` line 43 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCbnXaEEYaLn3chzMST:-OCbwlvvDl4Uou6Rbq7U:bc36i6v) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/extensionManager.ts#L43)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

No it cannot because i want to mutate it during the course of the object lifetime (turning the client off and on again results in this behavior)
</blockquote></details>

so perhaps rename this to `currentClient` that could be a getter (computed property) anyway?


<!-- Sent from Reviewable.io -->

2024-11-26 10:31 UTC, Arcticae reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6715)* status: 4 of 8 files reviewed, 6 unresolved discussions (waiting on @Draggu, @integraledelebesgue, @mkaput, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 46 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCbl35RETx1hIl4lWrl:-OCc0fIREtQ0lvP7R3tD:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/cairols.ts#L46)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

nit, wdyt?
</blockquote></details>

Done
___
*[`vscode-cairo/src/extension.ts` line 44 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCbjZV03cZLh79zCQWB:-OCc0ccU653iajrU14WN:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/extension.ts#L44)):*
<details><summary><i>Previously, Arcticae (Tomasz Rejowski) wrote…</i></summary><blockquote>

Can do, perhaps it's better
</blockquote></details>

Done
___
*[`vscode-cairo/src/extension.ts` line 46 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCbjpD25ep4xKSEZ_sw:-OCbwyY6E8mtiINxc4cn:bww3nmn) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/extension.ts#L46)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

slightly disagree because I find the fact that something is treated as a disposable pretty important
</blockquote></details>

I don't mind it but it'd be more confusing to read (to me). Done.
___
*[`vscode-cairo/src/extensionManager.ts` line 8 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCbnePQDZaNHmbutbxK:-OCc-Y7rBS42wkMrta8Z:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/extensionManager.ts#L8)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

please document here why we are maintaining only one client
</blockquote></details>

Done
___
*[`vscode-cairo/src/extensionManager.ts` line 20 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCbnGIZ0B3vDxlKUaq_:-OCc-YgNACpSb06LnPxg:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/extensionManager.ts#L20)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

tsdoc
</blockquote></details>

Done
___
*[`vscode-cairo/src/extensionManager.ts` line 43 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCbnXaEEYaLn3chzMST:-OCc-45KAOnzCDLdg1gM:bvqzwl4) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/extensionManager.ts#L43)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

so perhaps rename this to `currentClient` that could be a getter (computed property) anyway?
</blockquote></details>

I don't see anything wrong with the getter pattern i applied here. It's pretty much textbook
___
*[`vscode-cairo/src/extensionManager.ts` line 57 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OCboAOX9mK8F2CCyYYS:-OCc-_KF8bMfMMRma29C:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/57dbc5a2423641fba3da0291bf16e9b026bda876/vscode-cairo/src/extensionManager.ts#L57)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

all these comments are missing dots
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-11-27 13:04 UTC, Draggu requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6715)* status: all files reviewed, 4 unresolved discussions (waiting on @Arcticae, @integraledelebesgue, @orizi, and @piotmag769)

___
*[`vscode-cairo/src/cairols.ts` line 147 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OChg38N8x_gr5W2oUF1:-OChg38O4VbPauAzlZHk:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/89b4d9a7144ecf02bf784361011ae5f17334bbee/vscode-cairo/src/cairols.ts#L147)):*
> ```XML
>   await client.start();
> 
>   return [client, executables[0]];
> ```





_Suggestion:_
```XML
{client, executable: executables[0]}
```
___
*[`vscode-cairo/src/extension.ts` line 22 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OChhv3L6YhYOj04j17F:-OChhv3M9XJpYa-qvr_G:bqpxzuv) ([raw file](https://github.com/starkware-libs/cairo/blob/89b4d9a7144ecf02bf784361011ae5f17334bbee/vscode-cairo/src/extension.ts#L22)):*
> ```XML
>             .getClient()
>             ?.sendNotification(lc.DidChangeConfigurationNotification.type, {
>               settings: "",
> ```

Do we need to pass `string` here? will `null` not be more explicit?
___
*[`vscode-cairo/src/scarb.ts` line 96 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OChgryJ4SaVQ1Ol6PbU:-OChgryJ4SaVQ1Ol6PbV:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/89b4d9a7144ecf02bf784361011ae5f17334bbee/vscode-cairo/src/scarb.ts#L96)):*
> ```XML
>       return this.version;
>     }
>     this.version = (await this.execWithOutput(["--version"], ctx)).trim();
> ```





_Suggestion:_
```XML
    this.version ??= (await this.execWithOutput(["--version"], ctx)).trim();
```
___
*[`vscode-cairo/src/extensionManager.ts` line 56 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6715#-OChgE5V3aMgh8YxDI5A:-OChgE5V3aMgh8YxDI5B:bbagmoc) ([raw file](https://github.com/starkware-libs/cairo/blob/89b4d9a7144ecf02bf784361011ae5f17334bbee/vscode-cairo/src/extensionManager.ts#L56)):*
> ```XML
> 
>   public async handleDidChangeWorkspaceFolders(event: vscode.WorkspaceFoldersChangeEvent) {
>     if (event.added.length) {
> ```

Can we make explicit `!== 0` checks?


<!-- Sent from Reviewable.io -->

2024-11-27 16:36 UTC, Arcticae commented
Moving to https://github.com/software-mansion/vscode-cairo/pull/6

2024-11-28 08:21 UTC, closed without merging