Allow translating locations through a sum of  consecutive mappings
starkware-libs/cairo pull request #6717
Opened 2024-11-21 14:17 UTC by maciektr

2024-11-21 14:17 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6717)
<!-- Reviewable:end -->

2024-11-22 11:59 UTC, mkaput requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6717)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr and @orizi)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6717#-OCIjQDC4vbe7EGf6m0J:-OCIjQDC4vbe7EGf6m0K:b-kvyvgc) (no related file):*
Are you able to write a test that didn't work previously but works now? I recall it was something related to expressions...


<!-- Sent from Reviewable.io -->

2024-11-22 13:29 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6717)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr)

___
*[`crates/cairo-lang-defs/src/db.rs` line 663 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6717#-OCJ2rE40BbP77Mf_ELh:-OCJ2rE40BbP77Mf_ELi:b9os46d) ([raw file](https://github.com/starkware-libs/cairo/blob/a3151f95fd9378a3deaececb1d91e862aee6674c/crates/cairo-lang-defs/src/db.rs#L663)):*
> ```XML
>                 .intern(db);
>                 let mut code_mappings = generated.code_mappings;
>                 code_mappings.sort_by_key(|mapping| mapping.span.end);
> ```

this is wrong.

the order of the mappings is important - as we use them at the order they are given.



_Code quote:_
```XML
                let mut code_mappings = generated.code_mappings;
                code_mappings.sort_by_key(|mapping| mapping.span.end);
```


<!-- Sent from Reviewable.io -->

2024-11-23 16:15 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6717)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @maciektr, @mkaput, and @wawel37)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 358 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6717#-OCOnG312_nR7jkLXBb9:-OCOnG312_nR7jkLXBbA:b-w1nh7h) ([raw file](https://github.com/starkware-libs/cairo/blob/06533707e88fe22696a9ffab592794b54660765a/crates/cairo-lang-filesystem/src/db.rs#L358)):*
> ```XML
> }
> 
> fn translate_location(code_mapping: &[CodeMapping], span: TextSpan) -> Option<TextSpan> {
> ```

please doc - and somewhere doc the algorithm here - as i don't undersatnd it.


<!-- Sent from Reviewable.io -->

2024-11-25 08:54 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6717)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @maciektr, @mkaput, and @wawel37)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 358 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6717#-OCOnG312_nR7jkLXBb9:-OCXWTSs8cg6FT6EpVaE:b-mtl8vc) ([raw file](https://github.com/starkware-libs/cairo/blob/06533707e88fe22696a9ffab592794b54660765a/crates/cairo-lang-filesystem/src/db.rs#L358)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

please doc - and somewhere doc the algorithm here - as i don't undersatnd it.
</blockquote></details>

thanks - for the elaboration - are we sure we actually want to do this?
specifically - the new patch-builder basically almost never allows you to not have a containing span for all generated code - so the only thing that makes sense to me is to add some ordering to improve the lookups.

this currently seems to just hide possible issues from us actually finding them.


<!-- Sent from Reviewable.io -->

2024-11-25 08:57 UTC, mkaput approved these changes
> Reviewed 2 of 5 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6717)* status: all files reviewed, 1 unresolved discussion (waiting on @maciektr and @wawel37)



<!-- Sent from Reviewable.io -->

2024-11-25 14:16 UTC, wawel37 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6717)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr)

___
*[`crates/cairo-lang-filesystem/src/span.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6717#-OCYc1oTAm3ZZ71grDiM:-OCYc1oTAm3ZZ71grDiN:b-f7oso0) ([raw file](https://github.com/starkware-libs/cairo/blob/4f30b1915ea4bb1cefebe7d64fc8324bb39d88e3/crates/cairo-lang-filesystem/src/span.rs#L33)):*
> ```XML
>         self.0
>     }
>     pub fn from_u32(value: u32) -> Self {
> ```

There is a method here for a `TextWidth` that does exactly the same `new_for_testing`. Maybe we can just change the name of it instead of making the new one?


<!-- Sent from Reviewable.io -->

2024-12-02 13:42 UTC, mkaput approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6717)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr)



<!-- Sent from Reviewable.io -->

2024-12-10 06:59 UTC, mkaput approved these changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6717)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr)



<!-- Sent from Reviewable.io -->

2024-12-10 18:03 UTC, maciektr commented
*[`crates/cairo-lang-filesystem/src/db.rs` line 358 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6717#-OCOnG312_nR7jkLXBb9:-OCXXczeDolO0qChAQPt:b-abvha5) ([raw file](https://github.com/starkware-libs/cairo/blob/06533707e88fe22696a9ffab592794b54660765a/crates/cairo-lang-filesystem/src/db.rs#L358)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

thanks - for the elaboration - are we sure we actually want to do this?
specifically - the new patch-builder basically almost never allows you to not have a containing span for all generated code - so the only thing that makes sense to me is to add some ordering to improve the lookups.

this currently seems to just hide possible issues from us actually finding them.
</blockquote></details>

Yes, but we need this for procedural macros, rather than the compiler source plugins. 

While it's true using PatchBuilder will be enough to ensure appropriate code mappings are created in the compiler, we want to be able to create code mappings even without the knowledge of real compiler AST. What we do know, is where does a single token in the returned Cairo code come from. This way, we want to keep the same behavior for compiler created code mappings, which will always translate by matching some span in code mappings list, while also using the knowledge about token origin to map errors if possible. 


<!-- Sent from Reviewable.io -->

2024-12-17 12:15 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6717)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr and @wawel37)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 400 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6717#-OEJXlvEAgKl9UsouEkj:-OEJXlvEAgKl9UsouEkk:bcs3kkt) ([raw file](https://github.com/starkware-libs/cairo/blob/bd91e2358cfec51f48ae217a4c34f5a5f28b032d/crates/cairo-lang-filesystem/src/db.rs#L400)):*
> ```XML
>         // Found a span that fully contains the current one - translates it.
>         return containing.translate(span);
>     }
> ```

can you maybe mix these in the cases where the 2nd one is found?
this seems like we are creating the extra vector for no reason in most cases.



_Code quote:_
```XML
    let matched = code_mapping
        .iter()
        .filter(|mapping| {
            // Omit mappings to the left or to the right of current span.
            !(mapping.span.end < span.start || mapping.span.start > span.end)
        })
        .collect::<Vec<_>>();

    // If any of the mappings fully contains the span, return the origin span of the mapping.
    if let Some(containing) = matched.iter().find(|mapping| {
        mapping.span.contains(span) && !matches!(mapping.origin, CodeOrigin::CallSite(_))
    }) {
        // Found a span that fully contains the current one - translates it.
        return containing.translate(span);
    }
```


<!-- Sent from Reviewable.io -->

2024-12-18 11:18 UTC, wawel37 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6717#-:-OEOUCYE0PQGghbRBkzn:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @maciektr)



<!-- Sent from Reviewable.io -->

2025-01-08 12:46 UTC, maciektr reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6717)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-filesystem/src/db.rs` line 400 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6717#-OEJXlvEAgKl9UsouEkj:-OG4rJUJ30LPaLmEUtCb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/bd91e2358cfec51f48ae217a4c34f5a5f28b032d/crates/cairo-lang-filesystem/src/db.rs#L400)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

can you maybe mix these in the cases where the 2nd one is found?
this seems like we are creating the extra vector for no reason in most cases.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-08 15:46 UTC, mkaput approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6717)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2025-01-08 18:15 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6717#-:-OG67H63BX7LVgrSeQoe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @maciektr)



<!-- Sent from Reviewable.io -->

2025-01-08 18:33 UTC, merged