LS: Intern file on `FileChangeType::CREATED`
starkware-libs/cairo pull request #6719
Opened 2024-11-21 16:59 UTC by Draggu

2024-11-21 16:59 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6719)
<!-- Reviewable:end -->

2024-11-21 17:01 UTC, piotmag769 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6719#-:-OCEeuGh1bMfrBdtjNaq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arcticae, @integraledelebesgue, @mkaput, and @orizi)



<!-- Sent from Reviewable.io -->

2024-11-22 06:19 UTC, mkaput requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6719)* status: all files reviewed, 3 unresolved discussions (waiting on @Arcticae, @Draggu, @integraledelebesgue, and @orizi)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6719#-OCHWUvcDHqeCd3wPfnJ:-OCHWUvcDHqeCd3wPfnK:b-bfg7l) (no related file):*
I'm afraid this approach brings more problems than solutions. I wonder, don't we just need to intern file from url for anything we can find in `WorkspaceEdit`?
___
*[`crates/cairo-lang-language-server/src/server/routing/traits.rs` line 187 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6719#-OCHWAZjAu4F6MurclcS:-OCHWAZjAu4F6MurclcT:b-cihnqs) ([raw file](https://github.com/starkware-libs/cairo/blob/9573b6d7f5a38b9cd2cbf4164f6d698177e49d6d/crates/cairo-lang-language-server/src/server/routing/traits.rs#L187)):*
> ```XML
>         for change in &params.changes {
>             if is_cairo_file_path(&change.uri) {
>                 if change.typ == FileChangeType::CREATED {
> ```

hmm I think this has too broad blast radius

you're pulling into memory ANY file that is detected by the editor, without any project model knowledge. that is, this code will now pull any garbage the editor finds in the project which to me sounds like a risk of allocating too much memory.
___
*[`crates/cairo-lang-language-server/src/server/routing/traits.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6719#-OCHVvUh-jmOvpLfuX_M:-OCHVvUi8nmmQ70IXcG2:b-2gs7on) ([raw file](https://github.com/starkware-libs/cairo/blob/9573b6d7f5a38b9cd2cbf4164f6d698177e49d6d/crates/cairo-lang-language-server/src/server/routing/traits.rs#L191)):*
> ```XML
>                         if let Ok(text) = std::fs::read_to_string(change.uri.path()) {
>                             state.db.override_file_content(file_id, Some(text.into()));
>                         }
> ```

this is incorrect. you cannot pull file into memory if the file is not managed by the editor



_Code quote:_
```XML
                        if let Ok(text) = std::fs::read_to_string(change.uri.path()) {
                            state.db.override_file_content(file_id, Some(text.into()));
                        }
```


<!-- Sent from Reviewable.io -->

2024-12-02 10:52 UTC, Draggu commented
Closing pull request: commit has gone away

2024-12-02 10:52 UTC, closed without merging