Added option for renaming a storage varialble path.
starkware-libs/cairo pull request #6758
Opened 2024-11-27 16:01 UTC by orizi

2024-11-27 16:01 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6758)
<!-- Reviewable:end -->

2024-11-28 10:47 UTC, gilbens-starkware requested changes
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6758)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/renamed_storage_test.cairo` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6758#-OCmMCCHCqHQndZUUkq4:-OCmMCCHCqHQndZUUkq5:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/ff6815ce31c504a58cf99285fe03a69294c152eb/crates/cairo-lang-starknet/cairo_level_tests/renamed_storage_test.cairo#L38)):*
> ```Cairo
> fn rename_test() {
>     let mut state = contract::contract_state_for_testing();
>     //let state = @contract::contract_state_for_testing();
> ```




<!-- Sent from Reviewable.io -->

2024-11-28 10:57 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6758)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/renamed_storage_test.cairo` line 38 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6758#-OCmMCCHCqHQndZUUkq4:-OCmPhiw1mfaq8QcnBfS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ff6815ce31c504a58cf99285fe03a69294c152eb/crates/cairo-lang-starknet/cairo_level_tests/renamed_storage_test.cairo#L38)):*
> ```Cairo
> fn rename_test() {
>     let mut state = contract::contract_state_for_testing();
>     //let state = @contract::contract_state_for_testing();
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-11-28 11:02 UTC, gilbens-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6758#-:-OCmQu139zF-MfLPYqwZ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-11-28 11:20 UTC, merged