Renamed `runnable` -> `executable`, `prove` -> `execute`.
starkware-libs/cairo pull request #6760
Opened 2024-11-27 16:30 UTC by orizi

2024-11-27 16:30 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6760)
<!-- Reviewable:end -->

2024-11-28 10:56 UTC, gilbens-starkware requested changes
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6760)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/bin/cairo-execute/Cargo.toml` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6760#-OCmPeEZBOKt4RJuIqCs:-OCmPeEZBOKt4RJuIqCt:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f1b6a0c932958e2007b47b46a0ac7bc447005d80/crates/bin/cairo-execute/Cargo.toml#L2)):*
> ```TOML
> [package]
> name = "cairo-prove"
> ```





_Suggestion:_
```TOML
name = "cairo-execute"
```


<!-- Sent from Reviewable.io -->

2024-11-28 11:16 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6760)* status: all files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware)

___
*[`crates/bin/cairo-execute/Cargo.toml` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6760#-OCmPeEZBOKt4RJuIqCs:-OCmU44I2fE96BeNh4qn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f1b6a0c932958e2007b47b46a0ac7bc447005d80/crates/bin/cairo-execute/Cargo.toml#L2)):*
> ```TOML
> [package]
> name = "cairo-prove"
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-11-28 11:24 UTC, gilbens-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6760#-:-OCmW15dBFvfpj_S3Hec:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-11-28 11:48 UTC, merged