implement cfg not
starkware-libs/cairo pull request #6802
Opened 2024-12-02 14:59 UTC by dean-starkware

2024-12-02 14:59 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6802)
<!-- Reviewable:end -->

2024-12-02 16:02 UTC, orizi requested changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6802)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6802#-OD74JKAEO9I8L3kPfD0:-OD74JKAEO9I8L3kPfD1:b2ni1ar) ([raw file](https://github.com/starkware-libs/cairo/blob/88583552972780bcf8fd4cd38c730be68bdec2b2/crates/cairo-lang-plugins/src/plugins/config.rs#L26)):*
> ```XML
> 
> impl PredicateTree {
>     fn evaluate(&self, cfg_set: &CfgSet) -> bool {
> ```

doc
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6802#-OD74xah3yEMPbvf1XlR:-OD74xah3yEMPbvf1XlS:b-382yo0) ([raw file](https://github.com/starkware-libs/cairo/blob/88583552972780bcf8fd4cd38c730be68bdec2b2/crates/cairo-lang-plugins/src/plugins/config.rs#L220)):*
> ```XML
>         })
>         .collect();
>     if predicates.len() == 1 { Some(predicates.into_iter().next().unwrap()) } else { None }
> ```

why only one? can't we have multiple constraints?



_Code quote:_
```XML
    if predicates.len() == 1 { Some(predicates.into_iter().next().unwrap()) } else { None }
```
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 243 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6802#-OD75liw6JeKFtsdcfLD:-OD75liw6JeKFtsdcfLE:bbx6s5j) ([raw file](https://github.com/starkware-libs/cairo/blob/88583552972780bcf8fd4cd38c730be68bdec2b2/crates/cairo-lang-plugins/src/plugins/config.rs#L243)):*
> ```XML
>                 _ => {
>                     diagnostics.push(PluginDiagnostic::error(
>                         value.as_syntax_node().stable_ptr(),
> ```

any reason for this change?



_Suggestion:_
```XML
            diagnostics.push(PluginDiagnostic::error(
                &arg.arg,
                "This attribute does not support field initialization shorthands.".into(),
            ));
            None
        }
        AttributeArgVariant::Named { name, value } => {
            let value_text = match value {
                ast::Expr::ShortString(terminal) => terminal.string_value(db).unwrap_or_default(),
                ast::Expr::String(terminal) => terminal.string_value(db).unwrap_or_default(),
                _ => {
                    diagnostics.push(PluginDiagnostic::error(
                        &value,
```
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 329 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6802#-OD75Zcv82kqll6hCMUu:-OD75Zcv82kqll6hCMUv:b-17bkjc) ([raw file](https://github.com/starkware-libs/cairo/blob/88583552972780bcf8fd4cd38c730be68bdec2b2/crates/cairo-lang-plugins/src/plugins/config.rs#L329)):*
> ```XML
>                             PredicateTree::Not(Box::new(PredicateTree::Cfg(Cfg::name(
>                                 "group".to_string(),
>                             ))))
> ```

what does this mean?



_Code quote:_
```XML
                            PredicateTree::Not(Box::new(PredicateTree::Cfg(Cfg::name(
                                "group".to_string(),
                            ))))
```
___
*[`crates/cairo-lang-plugins/src/test.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6802#-OD7486sBNcEqWJ8bVgy:-OD7486t9BGS5OFj_0-o:bcpvfpu) ([raw file](https://github.com/starkware-libs/cairo/blob/88583552972780bcf8fd4cd38c730be68bdec2b2/crates/cairo-lang-plugins/src/test.rs#L40)):*
> ```XML
>         panicable: "panicable",
>         external_attributes_validation: "external_attributes_validation",
>         cfg_not: "cfg_not"
> ```

just add it in "config"



_Code quote:_
```XML
        cfg_not: "cfg_not"
```


<!-- Sent from Reviewable.io -->

2024-12-03 12:36 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6802)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-plugins/src/test.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6802#-OD7486sBNcEqWJ8bVgy:-ODAfVzU9swAJDy5nUeO:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/88583552972780bcf8fd4cd38c730be68bdec2b2/crates/cairo-lang-plugins/src/test.rs#L40)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

just add it in "config"
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6802#-OD74JKAEO9I8L3kPfD0:-ODAgLORE2BkmXV4zh7G:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/88583552972780bcf8fd4cd38c730be68bdec2b2/crates/cairo-lang-plugins/src/plugins/config.rs#L26)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6802#-OD74xah3yEMPbvf1XlR:-ODAsQFA6jnUiMHfylO9:b3wcngq) ([raw file](https://github.com/starkware-libs/cairo/blob/88583552972780bcf8fd4cd38c730be68bdec2b2/crates/cairo-lang-plugins/src/plugins/config.rs#L220)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

why only one? can't we have multiple constraints?
</blockquote></details>

The current implementation only supports a single predicate for simplicity.
If we choose to, we can also support `and` and `or` in `PredicateTree` to allow combining multiple predicates and extends the system's flexibility.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 243 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6802#-OD75liw6JeKFtsdcfLD:-ODBByxIDpHhWGswCzfM:bjpmazk) ([raw file](https://github.com/starkware-libs/cairo/blob/88583552972780bcf8fd4cd38c730be68bdec2b2/crates/cairo-lang-plugins/src/plugins/config.rs#L243)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

any reason for this change?
</blockquote></details>

I couldn't find an explanation now when I tried to justify it, so reverted back to how it was before.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 329 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6802#-OD75Zcv82kqll6hCMUu:-ODBM1Ni5Yje9En_ta7v:b-dzh8nw) ([raw file](https://github.com/starkware-libs/cairo/blob/88583552972780bcf8fd4cd38c730be68bdec2b2/crates/cairo-lang-plugins/src/plugins/config.rs#L329)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what does this mean?
</blockquote></details>

This logic is ensuring that the `Not` operator always operates on a single predicate tree.
The fallback dummy predicate (`group`) is there to handle unexpected scenarios where `Not` would otherwise have nothing valid to negate.
There are edge cases (like malformed input) where multiple predicates might sneak in, this fallback logic ensures the function doesn't crash.

For example:
``#[cfg(not(a, key = "value"))]  // Incorrect: `not` should handle one logical group.``

This could have been removed if we allowed only a single arg- but because we enable the not to support also the `Name` case- we need to handle this.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 215 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6802#-OD7tEWe2JxJQPGlpJKq:-ODB8NS60aZ5dTMeYsDe:b-qgfwnj) ([raw file](https://github.com/starkware-libs/cairo/blob/6350625402f14926fb99163128f6601fb4f70d34/crates/cairo-lang-plugins/src/plugins/config.rs#L215)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

doesn't this duplicate diagnostics?
</blockquote></details>

Good point, changed it.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6802#-OD7tT1M2-fRzO1LfQE9:-ODBLb5u1XEVPoY_c6bZ:b9vrvoq) ([raw file](https://github.com/starkware-libs/cairo/blob/6350625402f14926fb99163128f6601fb4f70d34/crates/cairo-lang-plugins/src/plugins/config.rs#L258)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

just ensure here there's a single arg here - as you expect for not.
and then probably recursively call.

if you need the same behavior for `AttributeArg` and `Arg` you probably need to add a trait here.
</blockquote></details>

But it's not the case- we infact can have more than a single arg here- if its a `named` one- thus this check is not valid.
I do undestand what you mean here- but it's not correct.


<!-- Sent from Reviewable.io -->

2024-12-03 12:49 UTC, orizi requested changes
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6802)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6802#-OD74xah3yEMPbvf1XlR:-ODBZ5O3E6mgTroFTTG7:bbd0lbf) ([raw file](https://github.com/starkware-libs/cairo/blob/88583552972780bcf8fd4cd38c730be68bdec2b2/crates/cairo-lang-plugins/src/plugins/config.rs#L220)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

The current implementation only supports a single predicate for simplicity.
If we choose to, we can also support `and` and `or` in `PredicateTree` to allow combining multiple predicates and extends the system's flexibility.
</blockquote></details>

This is not correct, previously you could have multiple constraints, you broke the current support.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 329 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6802#-OD75Zcv82kqll6hCMUu:-ODBZHU15TBSImj_DvN7:b-d88rhu) ([raw file](https://github.com/starkware-libs/cairo/blob/88583552972780bcf8fd4cd38c730be68bdec2b2/crates/cairo-lang-plugins/src/plugins/config.rs#L329)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

This logic is ensuring that the `Not` operator always operates on a single predicate tree.
The fallback dummy predicate (`group`) is there to handle unexpected scenarios where `Not` would otherwise have nothing valid to negate.
There are edge cases (like malformed input) where multiple predicates might sneak in, this fallback logic ensures the function doesn't crash.

For example:
``#[cfg(not(a, key = "value"))]  // Incorrect: `not` should handle one logical group.``

This could have been removed if we allowed only a single arg- but because we enable the not to support also the `Name` case- we need to handle this.
</blockquote></details>

Return None, and include diagnotics, this is why you have that option.


<!-- Sent from Reviewable.io -->

2024-12-03 12:50 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6802)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-plugins/src/test_data/config` line 7 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODBZVsC7kRf2HZYeWYO:-ODBZVsC7kRf2HZYeWYP:b-huemlc) ([raw file](https://github.com/starkware-libs/cairo/blob/5bf54a6c9130c58c54c62851009c0706df52695e/crates/cairo-lang-plugins/src/test_data/config#L7)):*
> ```
> 
> //! > cfg
> ["a", "b", ["k", "a"], ["k", "b"], ["key", "value"], ["not_key", "not_value"]]
> ```

In a different test within the file.


<!-- Sent from Reviewable.io -->

2024-12-03 12:53 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6802)* status: 1 of 4 files reviewed, 8 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6802#-OD7tT1M2-fRzO1LfQE9:-ODBZq643lF7u51qL0-A:b-h61ag2) ([raw file](https://github.com/starkware-libs/cairo/blob/6350625402f14926fb99163128f6601fb4f70d34/crates/cairo-lang-plugins/src/plugins/config.rs#L258)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

But it's not the case- we infact can have more than a single arg here- if its a `named` one- thus this check is not valid.
I do undestand what you mean here- but it's not correct.
</blockquote></details>

I understand both have names and unnamed options, but they remain the same, so I don't understand your point.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 318 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODBZgtJ3B5eBDWfXVro:-ODBZgtK4xxVDQl2BwT7:bqnn75t) ([raw file](https://github.com/starkware-libs/cairo/blob/5bf54a6c9130c58c54c62851009c0706df52695e/crates/cairo-lang-plugins/src/plugins/config.rs#L318)):*
> ```XML
>                             diagnostics.push(PluginDiagnostic::error(
>                                 call.as_syntax_node().stable_ptr(),
>                                 "`not` operator requires at least one argument.".into(),
> ```

Exactly one.


<!-- Sent from Reviewable.io -->

2024-12-06 13:25 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6802)* status: 1 of 4 files reviewed, 8 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6802#-OD74xah3yEMPbvf1XlR:-ODGxobd0G4lcKR8J3T2:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/88583552972780bcf8fd4cd38c730be68bdec2b2/crates/cairo-lang-plugins/src/plugins/config.rs#L220)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

This is not correct, previously you could have multiple constraints, you broke the current support.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 329 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6802#-OD75Zcv82kqll6hCMUu:-ODQuntv731usthq_3C7:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/88583552972780bcf8fd4cd38c730be68bdec2b2/crates/cairo-lang-plugins/src/plugins/config.rs#L329)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Return None, and include diagnotics, this is why you have that option.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6802#-OD7tT1M2-fRzO1LfQE9:-ODQuplcEXnv6koLYHII:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/6350625402f14926fb99163128f6601fb4f70d34/crates/cairo-lang-plugins/src/plugins/config.rs#L258)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I understand both have names and unnamed options, but they remain the same, so I don't understand your point.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 318 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODBZgtJ3B5eBDWfXVro:-ODQumPKDe2LU5SWl_2S:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5bf54a6c9130c58c54c62851009c0706df52695e/crates/cairo-lang-plugins/src/plugins/config.rs#L318)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Exactly one.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/test_data/config` line 7 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODBZVsC7kRf2HZYeWYO:-ODR-APSBwf04SLEcVzR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5bf54a6c9130c58c54c62851009c0706df52695e/crates/cairo-lang-plugins/src/test_data/config#L7)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

In a different test within the file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-06 16:02 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6802)* status: 1 of 4 files reviewed, 10 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-plugins/src/test_data/config` line 302 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRbLKO5sutUDPyQMcn:-ODRbLKO5sutUDPyQMco:b1bj5cl) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/test_data/config#L302)):*
> ```
> }
> 
> // Invalid usage examples for diagnostics
> ```

separate the diagnostics to another test.



_Code quote:_
```
// Invalid usage examples for diagnostics
```
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 157 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRd68oCBbM1AE1PoP8:-ODRd68oCBbM1AE1PoP9:by8zruq) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L157)):*
> ```XML
>             _ => None,
>         }
>     }
> ```

add the enum:
```
enum ConfigPredicatePart {
     Cfg(Cfg),
     Call(ast::FunctionCall),
}
```

same should work above.



_Suggestion:_
```XML
    
    
    fn get_part(&self, db: &dyn SyntaxGroup) -> Option<ConfigPredicatePart> {
        match self.arg_clause(db) {
            ast::ArgClause::Named(named) => match named.value(db) {
                ast::Expr::String(terminal) => Some(ConfigPredicatePart::Cfg(Cfg::kv(named.name(db).text(db).to_string(), terminal.string_value(db))),
                _ => None,
            },
            ast::ArgClause::Unnamed(unnamed) => match unnamed.value(db) {
                ast::Expr::Path(path) => {
                    let segments = path.elements(db);
                    if let [ast::PathSegment::Simple(segment)] = &segments[..] {
                        Some(ConfigPredicatePart::Cfg(Cfg::name(segment.ident(db).text(db).to_string())))
                    } else {
                        None
                    }
                }
                ast::Expr::FunctionCall(call) => ConfigPredicatePart::FunctionCall(call),
                _ => None,
            },
            _ => None,
        }
    }
```
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 160 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRcYgsAW5I-gq1e3ux:-ODRcYgsAW5I-gq1e3uy:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L160)):*
> ```XML
> 
>     fn stable_ptr(&self) -> cairo_lang_syntax::node::ids::SyntaxStablePtrId {
>         cairo_lang_syntax::node::TypedSyntaxNode::stable_ptr(self).into()
> ```





_Suggestion:_
```XML
        self.stable_ptr().untyped()
```
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 184 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRg59x50uDRPdqk3Lw:-ODRg59x50uDRPdqk3Lx:bm99a4a) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L184)):*
> ```XML
>         }
>         vec![]
>     }
> ```

and delete these.

external match should be enough now.



_Code quote:_
```XML
    fn is_function_call(&self, db: &dyn SyntaxGroup) -> bool {
        if let ast::ArgClause::Unnamed(unnamed) = self.arg_clause(db) {
            matches!(unnamed.value(db), ast::Expr::FunctionCall(_))
        } else {
            false
        }
    }

    fn get_function_call_args(&self, db: &dyn SyntaxGroup) -> Vec<Box<dyn ConfigArg>> {
        if let ast::ArgClause::Unnamed(unnamed) = self.arg_clause(db) {
            if let ast::Expr::FunctionCall(call) = unnamed.value(db) {
                return call
                    .arguments(db)
                    .arguments(db)
                    .elements(db)
                    .into_iter()
                    .map(|arg| Box::new(AttributeArg::from_ast(arg, db)) as Box<dyn ConfigArg>)
                    .collect();
            }
        }
        vec![]
    }
```
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 358 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRcIB70hzlWcy7sCCG:-ODRcIB70hzlWcy7sCCH:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L358)):*
> ```XML
>         attr.args
>             .into_iter()
>             .filter_map(|arg| parse_predicate_item(db, &arg, diagnostics))
> ```





_Suggestion:_
```XML
            .filter_map(|arg| parse_predicate_item(db, arg, diagnostics))
```
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 366 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRc0pcCdL0PhRJPL4L:-ODRc0pcCdL0PhRJPL4M:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L366)):*
> ```XML
> fn parse_predicate_item(
>     db: &dyn SyntaxGroup,
>     item: &dyn ConfigArg,
> ```





_Suggestion:_
```XML
    item: impl ConfigArg,
```
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 380 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRgE4s4LwKi-jXlnH7:-ODRgE4s4LwKi-jXlnH8:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L380)):*
> ```XML
>             return None;
>         }
>     }
> ```





_Suggestion:_
```XML
    match item.get_part(db) {
        None => {
            // add relevanat diagnostics.
            return None;
        }
        Some(ConfigPredicatePart::Cfg(cfg)) => return Some(cfg),
        Some(ConfigPredicatePart::FunctionCall(call)) => {
            // Actually extract the function call arguments and test everything.
            // No need to be in the trait implementation.
        },
    }
```
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 388 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRcEq5AoOJS9R-hAp1:-ODRcEq5AoOJS9R-hAp2:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L388)):*
> ```XML
>             .get_function_call_args(db)
>             .into_iter()
>             .filter_map(|arg| parse_predicate_item(db, arg.as_ref(), diagnostics))
> ```





_Suggestion:_
```XML
            .filter_map(|arg| parse_predicate_item(db, arg, diagnostics))
```
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 424 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRbdQQ3FSJeu6zbUyr:-ODRbdQQ3FSJeu6zbUys:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L424)):*
> ```XML
>                     Some(PredicateTree::Or(args))
>                 }
>             }
> ```





_Suggestion:_
```XML
            }
            "and" => {
                if args.len() >= 2 {
                    diagnostics.push(PluginDiagnostic::error(
                        item.stable_ptr(),
                        "`and` operator expects at least two arguments.".into(),
                    ));
                    None
                } else {
                    Some(PredicateTree::And(args))
                }
            }
            "or" => {
                if args.len() >= 2 {
                    diagnostics.push(PluginDiagnostic::error(
                        item.stable_ptr(),
                        "`or` operator expects at least two arguments.".into(),
                    ));
                    None
                } else {
                    Some(PredicateTree::Or(args))
                }
            }
```


<!-- Sent from Reviewable.io -->

2024-12-07 12:39 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6802)* status: 1 of 4 files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 157 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRd68oCBbM1AE1PoP8:-ODW7EZd4iM6_Ao7Q1yD:bfn3ux7) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L157)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add the enum:
```
enum ConfigPredicatePart {
     Cfg(Cfg),
     Call(ast::FunctionCall),
}
```

same should work above.
</blockquote></details>

I think you mean `ast::ExprFunctionCall`.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 160 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRcYgsAW5I-gq1e3ux:-ODW61fm-7G-sHoYHWNp:b-lic21p) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L160)):*
> ```XML
> 
>     fn stable_ptr(&self) -> cairo_lang_syntax::node::ids::SyntaxStablePtrId {
>         cairo_lang_syntax::node::TypedSyntaxNode::stable_ptr(self).into()
> ```

I don't get what you meant to do here.
The problem is that the method `stable_ptr` is being called recursively.
I'm sure you didn't mean that- but I can't seem to understand what were your intentions here.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 366 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRc0pcCdL0PhRJPL4L:-ODW6Nrb0jlxZQUNrns4:b-7d2dgb) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L366)):*
> ```XML
> fn parse_predicate_item(
>     db: &dyn SyntaxGroup,
>     item: &dyn ConfigArg,
> ```

Why?
I'm sure this is the right thing to do, but don't fully understand it.


<!-- Sent from Reviewable.io -->

2024-12-07 13:20 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6802)* status: 1 of 4 files reviewed, 10 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 157 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRd68oCBbM1AE1PoP8:-ODWG5iZ2k_ka-GUIRy1:b-x4prpv) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L157)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

I think you mean `ast::ExprFunctionCall`.
</blockquote></details>

yes probably.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 160 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRcYgsAW5I-gq1e3ux:-ODWG9Y-DE0nNfhVfUvh:bgr969b) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L160)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

I don't get what you meant to do here.
The problem is that the method `stable_ptr` is being called recursively.
I'm sure you didn't mean that- but I can't seem to understand what were your intentions here.
</blockquote></details>

I see no way it is recursive - you are doing something wrong.

in any case  -you can make your trait have the super trait `TypedSyntaxNode` - then you won't need this at all.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 366 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRc0pcCdL0PhRJPL4L:-ODWGaZY5CQPEHLvtsSc:bqx2sy6) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L366)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

Why?
I'm sure this is the right thing to do, but don't fully understand it.
</blockquote></details>

because you don't need dyn at all - it would just create two instances of this function, with no dynamic function calls.


<!-- Sent from Reviewable.io -->

2024-12-08 15:07 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6802)* status: 1 of 4 files reviewed, 10 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 157 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRd68oCBbM1AE1PoP8:-ODaCgNXCvvOvC_bQwBS:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L157)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

yes probably.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 160 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRcYgsAW5I-gq1e3ux:-ODWS9JgAjoOkEaJjvt4:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L160)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I see no way it is recursive - you are doing something wrong.

in any case  -you can make your trait have the super trait `TypedSyntaxNode` - then you won't need this at all.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 184 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRg59x50uDRPdqk3Lw:-ODaCcaP9Qeln92ilJR1:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L184)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and delete these.

external match should be enough now.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 366 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRc0pcCdL0PhRJPL4L:-ODaCb6k4dWpeyiC1S24:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L366)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

because you don't need dyn at all - it would just create two instances of this function, with no dynamic function calls.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/test_data/config` line 302 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRbLKO5sutUDPyQMcn:-ODabcV7CuOhXzad7iuy:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/test_data/config#L302)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

separate the diagnostics to another test.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 358 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRcIB70hzlWcy7sCCG:-ODaCbXKEoRmgQH02a1T:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L358)):*
> ```XML
>         attr.args
>             .into_iter()
>             .filter_map(|arg| parse_predicate_item(db, &arg, diagnostics))
> ```

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 380 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRgE4s4LwKi-jXlnH7:-ODabbov-bCwxL7_RxFp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L380)):*
> ```XML
>             return None;
>         }
>     }
> ```

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 388 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRcEq5AoOJS9R-hAp1:-ODaDUzK5qE6mh2MGl82:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L388)):*
> ```XML
>             .get_function_call_args(db)
>             .into_iter()
>             .filter_map(|arg| parse_predicate_item(db, arg.as_ref(), diagnostics))
> ```

Done.
___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 424 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODRbdQQ3FSJeu6zbUyr:-ODaEMGH7b1irdH1MlUB:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/5724d04c2a97663ec3995e903da44798e892433f/crates/cairo-lang-plugins/src/plugins/config.rs#L424)):*
> ```XML
>                     Some(PredicateTree::Or(args))
>                 }
>             }
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-09 06:27 UTC, orizi requested changes
> Reviewed 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6802)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 269 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODe5IKICyYasmjKnDa6:-ODe5IKICyYasmjKnDa7:b-95g2gq) ([raw file](https://github.com/starkware-libs/cairo/blob/32f1a140c9fbc4f362e06d45b83f4f2b2a2be578/crates/cairo-lang-plugins/src/plugins/config.rs#L269)):*
> ```XML
> fn parse_predicate_item(
>     db: &dyn SyntaxGroup,
>     item: impl ConfigArg,
> ```

i guess you can just pass a `AttributeArg` here if this is now the only implementer of the trait.
(and then probably remove the stable_ptr fetching function from the trait)



_Suggestion:_
```XML
    item: AttributeArg,
```


<!-- Sent from Reviewable.io -->

2024-12-09 09:17 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6802)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-plugins/src/plugins/config.rs` line 269 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODe5IKICyYasmjKnDa6:-ODedhEL8dLigW8HSexW:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/32f1a140c9fbc4f362e06d45b83f4f2b2a2be578/crates/cairo-lang-plugins/src/plugins/config.rs#L269)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i guess you can just pass a `AttributeArg` here if this is now the only implementer of the trait.
(and then probably remove the stable_ptr fetching function from the trait)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-09 09:25 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6802)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-plugins/src/test_data/config` line 1 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODej5RBCQyoGD6z7KBM:-ODej5RBCQyoGD6z7KBN:b9da69h) ([raw file](https://github.com/starkware-libs/cairo/blob/791217b404e7f52aaae374951985a577fdf1ecf1/crates/cairo-lang-plugins/src/test_data/config#L1)):*
> ```
> //! > Test ignoring of test config in the test config.
> ```

if you found the issue add a testcase for it as well.
(not same names as the actual bug, just same cause)


<!-- Sent from Reviewable.io -->

2024-12-09 09:32 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6802)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-plugins/src/test_data/config` line 1 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODej5RBCQyoGD6z7KBM:-ODekSj67OOnADNSuPzl:b-yd4yn5) ([raw file](https://github.com/starkware-libs/cairo/blob/791217b404e7f52aaae374951985a577fdf1ecf1/crates/cairo-lang-plugins/src/test_data/config#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

if you found the issue add a testcase for it as well.
(not same names as the actual bug, just same cause)
</blockquote></details>

The issue was that "'test'" became 'test', instead of test.
this fixed it:
ast::Expr::ShortString(terminal) => {
terminal.string_value(db).unwrap_or_default()
}

as documented here:
https://github.com/starkware-libs/cairo/blob/848b90f26c84a108c344adcbf88de07c4e8f71d4/crates/cairo-lang-language-server/src/lang/db/mod.rs#L70

I'm not sure a testcase is relevant for this bug. Correct me if I'm wrong.


<!-- Sent from Reviewable.io -->

2024-12-09 11:40 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6802)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-plugins/src/test_data/config` line 297 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODfCzTo23sKKzNqYsjV:-ODfCzTo23sKKzNqYsjW:b-hhzx49) ([raw file](https://github.com/starkware-libs/cairo/blob/a920abc2cfcf9500319e761ac65015f89022ce23/crates/cairo-lang-plugins/src/test_data/config#L297)):*
> ```
> }
> 
> #[cfg(or(a, x))]
> ```

add an additional more complex cfg test (or of ands of nots and so on)


<!-- Sent from Reviewable.io -->

2024-12-09 12:27 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6802)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-plugins/src/test_data/config` line 297 at r7](https://reviewable.io/reviews/starkware-libs/cairo/6802#-ODfCzTo23sKKzNqYsjV:-ODfNqP_9gB7rB1OgcQ6:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a920abc2cfcf9500319e761ac65015f89022ce23/crates/cairo-lang-plugins/src/test_data/config#L297)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add an additional more complex cfg test (or of ands of nots and so on)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-09 13:20 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6802#-:-ODfZwHYBTWoF1nhW_QZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2024-12-10 07:22 UTC, merged