Introduced queries for crate plugins in `DefsGroup` and `SemanticGroup`
starkware-libs/cairo pull request #6840
Opened 2024-12-06 12:25 UTC by integraledelebesgue

**Stack**:
- #6839
- #6838

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-12-06 12:25 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6840)
<!-- Reviewable:end -->

2024-12-06 16:08 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840#-:-ODRidOQ1ejgqrD1__fc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @integraledelebesgue)



<!-- Sent from Reviewable.io -->

2024-12-06 16:40 UTC, mkaput requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840)* status: all files reviewed, 2 unresolved discussions (waiting on @integraledelebesgue)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 359 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6840#-ODRmXs28hDJn9ltW7Bs:-ODRmXs28hDJn9ltW7Bt:b9cp8il) ([raw file](https://github.com/starkware-libs/cairo/blob/458e8d6a762ea0b5b4d54a6a1d2ce01bfd5f69b9/crates/cairo-lang-defs/src/ids.rs#L359)):*
> ```XML
> }
> 
> impl Clone for MacroPluginLongId {
> ```

why can't this be derived?
___
*[`crates/cairo-lang-defs/src/ids.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6840#-ODRoNUZ9hpMbKTWamJH:-ODRoNUZ9hpMbKTWamJI:b-h4rzt9) ([raw file](https://github.com/starkware-libs/cairo/blob/458e8d6a762ea0b5b4d54a6a1d2ce01bfd5f69b9/crates/cairo-lang-defs/src/ids.rs#L369)):*
> ```XML
> impl PartialEq for MacroPluginLongId {
>     fn eq(&self, other: &Self) -> bool {
>         *self.0 == *other.0
> ```

just pointer equality should be actually enough for us. we already rely on it in  LS :)


<!-- Sent from Reviewable.io -->

2024-12-09 21:48 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @mkaput and @orizi)

___
*[`crates/cairo-lang-defs/src/ids.rs` line 359 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6840#-ODRmXs28hDJn9ltW7Bs:-ODhNsgqEqurAMTJ32R3:b-ot40g2) ([raw file](https://github.com/starkware-libs/cairo/blob/458e8d6a762ea0b5b4d54a6a1d2ce01bfd5f69b9/crates/cairo-lang-defs/src/ids.rs#L359)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

why can't this be derived?
</blockquote></details>

It absolutely can, idk why I thought it couldn't :)
___
*[`crates/cairo-lang-defs/src/ids.rs` line 369 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6840#-ODRoNUZ9hpMbKTWamJH:-ODhNELe0hPsyd1djgqW:b-lp7rwy) ([raw file](https://github.com/starkware-libs/cairo/blob/458e8d6a762ea0b5b4d54a6a1d2ce01bfd5f69b9/crates/cairo-lang-defs/src/ids.rs#L369)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

just pointer equality should be actually enough for us. we already rely on it in  LS :)
</blockquote></details>

Done, as we've concluded


<!-- Sent from Reviewable.io -->

2024-12-10 07:01 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840#-:-ODjMwHr48zBKYLEKCQ2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-12-10 09:19 UTC, mkaput requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840)* status: all files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-defs/src/db.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6840#-ODjrVWfD3xpOkMmuGLm:-ODjrVWfD3xpOkMmuGLn:b2ni25r) ([raw file](https://github.com/starkware-libs/cairo/blob/e6bd4c0b43deb7c096a0062fab6470b54dd8cc3f/crates/cairo-lang-defs/src/db.rs#L107)):*
> ```XML
> 
>     #[salsa::input]
>     fn override_crate_macro_plugins(&self, crate_id: CrateId) -> Vec<MacroPluginId>;
> ```

etc



_Suggestion:_
```XML
    #[salsa::input]
    fn default_macro_plugins(&self) -> Arc<[MacroPluginId]>;

    #[salsa::input]
    fn override_crate_macro_plugins(&self, crate_id: CrateId) -> Arc<[MacroPluginId]>;
```


<!-- Sent from Reviewable.io -->

2024-12-10 11:45 UTC, Draggu reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840)* status: all files reviewed, 2 unresolved discussions (waiting on @integraledelebesgue, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-defs/src/db.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6840#-ODjrVWfD3xpOkMmuGLm:-ODkNlZe-wosLW-F6FBx:bdj7n81) ([raw file](https://github.com/starkware-libs/cairo/blob/e6bd4c0b43deb7c096a0062fab6470b54dd8cc3f/crates/cairo-lang-defs/src/db.rs#L107)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

etc
</blockquote></details>

Apply it to other plugins too.
___
*[`crates/cairo-lang-defs/src/db.rs` line 119 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6840#-ODkNbil0mmlfusOs-KU:-ODkNbil0mmlfusOs-KV:b-8kql6i) ([raw file](https://github.com/starkware-libs/cairo/blob/e6bd4c0b43deb7c096a0062fab6470b54dd8cc3f/crates/cairo-lang-defs/src/db.rs#L119)):*
> ```XML
> 
>     #[salsa::input]
>     fn default_inline_macro_plugins(&self) -> OrderedHashMap<String, InlineMacroExprPluginId>;
> ```

Should this be wrapped in `Arc`? @mkaput 


<!-- Sent from Reviewable.io -->

2024-12-11 06:54 UTC, mkaput reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840)* status: all files reviewed, 2 unresolved discussions (waiting on @Draggu, @integraledelebesgue, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-defs/src/db.rs` line 119 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6840#-ODkNbil0mmlfusOs-KU:-ODoUqe88vgr1h9MfIHv:b-xqj7d6) ([raw file](https://github.com/starkware-libs/cairo/blob/5d50783119c0cefc9fb2e877e0fb24d6fc92a1ac/crates/cairo-lang-defs/src/db.rs#L119)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Should this be wrapped in `Arc`? @mkaput
</blockquote></details>

yes it should 


<!-- Sent from Reviewable.io -->

2024-12-11 12:07 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-defs/src/db.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6840#-ODjrVWfD3xpOkMmuGLm:-ODpbRYX24FlZbxkzwLk:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/5d50783119c0cefc9fb2e877e0fb24d6fc92a1ac/crates/cairo-lang-defs/src/db.rs#L107)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Apply it to other plugins too.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-12-11 12:24 UTC, Draggu approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 6 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840#-:-ODpfG_O07FPt-EsUya5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mkaput, @orizi, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-12-11 14:26 UTC, mkaput approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-12-12 13:38 UTC, mkaput approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840)* status: all files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue and @orizi)



<!-- Sent from Reviewable.io -->

2024-12-13 09:07 UTC, mkaput requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840)* status: all files reviewed, 2 unresolved discussions (waiting on @integraledelebesgue, @orizi, and @wawel37)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 1625 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6840#-ODzGL6l0wJiopDtxJOA:-ODzGL6l0wJiopDtxJOB:b-omswtt) ([raw file](https://github.com/starkware-libs/cairo/blob/3a72155f6fb5183eb1777a2a13af0fe68f6c7d30/crates/cairo-lang-semantic/src/db.rs#L1625)):*
> ```XML
> 
> /// Initializes the [`SemanticGroup`] database to a proper state.
> pub fn init_semantic_group(db: &mut dyn SemanticGroup) {
> ```

you have to add calls to all these functions anywhere a database is created. we unfortuately have no compile-time checks for missing initializations, so you need to do a little witch hunt :( 


<!-- Sent from Reviewable.io -->

2024-12-13 09:29 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi, @piotmag769, and @wawel37)

___
*[`crates/cairo-lang-defs/src/db.rs` line 101 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6840#-ODu_Yqq7VAU6bdi7cYt:-ODzJ8Dv2UEUizgtxMYr:b8drdbi) ([raw file](https://github.com/starkware-libs/cairo/blob/69ac9d946a56c8631891eec5b968bf4cdd8a0773/crates/cairo-lang-defs/src/db.rs#L101)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

[nit] Move this lower to group with inline macro methods
</blockquote></details>

That's an old, already present code, that I removed in the last PR. I think it's no use touching it


<!-- Sent from Reviewable.io -->

2024-12-13 09:47 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840#-:-ODzPbuXBk8SECXU7ean:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi, @piotmag769, and @wawel37)



<!-- Sent from Reviewable.io -->

2024-12-13 15:08 UTC, orizi approved these changes
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840)* status: all files reviewed, 1 unresolved discussion (waiting on @piotmag769 and @wawel37)



<!-- Sent from Reviewable.io -->

2024-12-21 23:45 UTC, piotmag769 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840#-:-OEfb9gUCW8qP87-ha5H:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wawel37)



<!-- Sent from Reviewable.io -->

2024-12-21 23:51 UTC, piotmag769 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840)* status: all files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue and @wawel37)

___
*[`crates/cairo-lang-defs/src/db.rs` line 1219 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6840#-OEfcU1o5WkVIXqoOiXp:-OEfcU1pByhqq3DJ7dNB:b-xd6l3t) ([raw file](https://github.com/starkware-libs/cairo/blob/3a72155f6fb5183eb1777a2a13af0fe68f6c7d30/crates/cairo-lang-defs/src/db.rs#L1219)):*
> ```XML
>         plugins: Arc<[MacroPluginId]>,
>     ) {
>         let mut overrides = self.macro_plugin_overrides().as_ref().clone();
> ```

I know this is the way override_file_content is done but is it needed here? Cannot we just modify the arc? cc @mkaput @Draggu 


<!-- Sent from Reviewable.io -->

2025-01-18 08:44 UTC, orizi approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840)* status: all files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue and @wawel37)



<!-- Sent from Reviewable.io -->

2025-01-22 05:01 UTC, orizi approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840)* status: all files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue and @wawel37)



<!-- Sent from Reviewable.io -->

2025-01-29 15:25 UTC, orizi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue and @wawel37)



<!-- Sent from Reviewable.io -->

2025-01-30 06:53 UTC, mkaput approved these changes
> Reviewed 2 of 3 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840)* status: all files reviewed, 1 unresolved discussion (waiting on @Draggu and @wawel37)

___
*[`crates/cairo-lang-defs/src/db.rs` line 1219 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6840#-OEfcU1o5WkVIXqoOiXp:-OHpz2D99h9wZGonQp-A:b-46ugnm) ([raw file](https://github.com/starkware-libs/cairo/blob/3a72155f6fb5183eb1777a2a13af0fe68f6c7d30/crates/cairo-lang-defs/src/db.rs#L1219)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

I know this is the way override_file_content is done but is it needed here? Cannot we just modify the arc? cc @mkaput @Draggu
</blockquote></details>

arc is immutable, you can't mutate it


<!-- Sent from Reviewable.io -->

2025-02-03 12:11 UTC, piotmag769 approved these changes
> Reviewed 2 of 3 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6840)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wawel37)



<!-- Sent from Reviewable.io -->

2025-02-03 12:24 UTC, merged