Migrated compiler to per-crate plugin queries
starkware-libs/cairo pull request #6843
Opened 2024-12-06 12:25 UTC by integraledelebesgue

**Stack**:
- #6843 ⬅
- #6842
- #6841
- #6840
- #6839
- #6838

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-12-06 12:25 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6843)
<!-- Reviewable:end -->

2024-12-09 21:55 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6843)* status: 0 of 65 files reviewed, 1 unresolved discussion (waiting on @mkaput, @orizi, and @piotmag769)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6843#-ODhOgDP38hCWAxeGN08:-ODhOgDP38hCWAxeGN09:b7kiqdw) (no related file):*
I have two problems here which I am work on now:
1. Fallback from "override" to "default" input (e.g. `DefsGroup::default_macro_plugins` and `DefsGroup::override_crate_macro_plugins`) is tricky to implement due to the way the input getters are implemented in Salsa: they panic. Sadly, I cannot catch the panic without constraining the `DefsGroup` (and, consequently, all its subtraits) to `UnwindSafe`.
2. Tests related to circuits break because the compiler's input has `Tuple<...>` types instead of `(...)` structural types.

However, the rest of the stack is ready to be reviewed.


<!-- Sent from Reviewable.io -->

2024-12-10 07:11 UTC, mkaput reviewed
> Reviewed 58 of 64 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6843)* status: 58 of 65 files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue, @orizi, and @piotmag769)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6843#-ODhOgDP38hCWAxeGN08:-ODjNyQvEHDMzEGvMHce:b9uzy9a) (no related file):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

I have two problems here which I am work on now:
1. Fallback from "override" to "default" input (e.g. `DefsGroup::default_macro_plugins` and `DefsGroup::override_crate_macro_plugins`) is tricky to implement due to the way the input getters are implemented in Salsa: they panic. Sadly, I cannot catch the panic without constraining the `DefsGroup` (and, consequently, all its subtraits) to `UnwindSafe`.
2. Tests related to circuits break because the compiler's input has `Tuple<...>` types instead of `(...)` structural types.

However, the rest of the stack is ready to be reviewed.
</blockquote></details>

Ad 1. I believe that's the reason `file_overrides` in `FilesGroup` are implemented as two queries: one, the parameterless input, keeps an HashMap of `FileId -> override` and the other query meant for broad use does the lookup and returns `Option`


<!-- Sent from Reviewable.io -->

2024-12-10 07:20 UTC, mkaput requested changes
> Reviewed 1 of 65 files at r1, 6 of 64 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6843)* status: all files reviewed, 4 unresolved discussions (waiting on @integraledelebesgue, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6843#-ODjQNAnBraZcPhgzM5r:-ODjQNAnBraZcPhgzM5s:b-vadory) ([raw file](https://github.com/starkware-libs/cairo/blob/32cb0f9c0f7542677ddbc6253ed7c7b0e3a3d6a6/crates/cairo-lang-semantic/src/types.rs#L187)):*
> ```XML
>     /// containing it.
>     pub fn is_phantom(&self, db: &dyn SemanticGroup) -> bool {
>         let Some(module_file_id) = self.module_file_id(db) else {
> ```

I think this generalization of `module_file_id` for any `TypeId` is misleading a bit, and not really that useful outside this context. See my other comment down this file for an explanation of how I believe this should work.
___
*[`crates/cairo-lang-semantic/src/types.rs` line 205 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6843#-ODjQgvo8DEoZec1fqf6:-ODjQgvo8DEoZec1fqf7:b-8zahfq) ([raw file](https://github.com/starkware-libs/cairo/blob/32cb0f9c0f7542677ddbc6253ed7c7b0e3a3d6a6/crates/cairo-lang-semantic/src/types.rs#L205)):*
> ```XML
>                     .iter()
>                     .any(|attr| id.has_attr(db, attr).unwrap_or_default()),
>             },
> ```

I think this is the place where you should actually look for the crate and its declared phantom type attrs. Here, you know a concrete item that we're interested in, so we can always reliably ask for its crate.



_Code quote:_
```XML
            TypeLongId::Concrete(id) => match id {
                ConcreteTypeId::Struct(id) => phantom_type_attributes
                    .iter()
                    .any(|attr| id.has_attr(db, attr).unwrap_or_default()),
                ConcreteTypeId::Enum(id) => phantom_type_attributes
                    .iter()
                    .any(|attr| id.has_attr(db, attr).unwrap_or_default()),
                ConcreteTypeId::Extern(id) => phantom_type_attributes
                    .iter()
                    .any(|attr| id.has_attr(db, attr).unwrap_or_default()),
            },
```
___
*[`crates/cairo-lang-semantic/src/types.rs` line 208 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6843#-ODjQv_r13uqRABlqCRW:-ODjQv_r13uqRABlqCRX:b-ocryno) ([raw file](https://github.com/starkware-libs/cairo/blob/32cb0f9c0f7542677ddbc6253ed7c7b0e3a3d6a6/crates/cairo-lang-semantic/src/types.rs#L208)):*
> ```XML
>             TypeLongId::Tuple(inner) => inner.iter().any(|ty| ty.is_phantom(db)),
>             TypeLongId::FixedSizeArray { type_id, .. } => type_id.is_phantom(db),
>             TypeLongId::Snapshot(_)
> ```

This is an example where generalized `module_file_id` might not be a good idea: we don't need it for snapshots, yet your code attempted to look for something.


<!-- Sent from Reviewable.io -->

2024-12-10 11:56 UTC, Draggu approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6843#-:-ODkQLkQDJmGMurCUs2s:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @integraledelebesgue, @orizi, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-12-11 06:56 UTC, mkaput reviewed
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6843)* status: all files reviewed, 4 unresolved discussions (waiting on @integraledelebesgue, @orizi, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-12-11 11:57 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6843)* status: 57 of 65 files reviewed, 2 unresolved discussions (waiting on @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-semantic/src/types.rs` line 205 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6843#-ODjQgvo8DEoZec1fqf6:-ODp_8paDMyAGYh7D0b4:b-3g8eq6) ([raw file](https://github.com/starkware-libs/cairo/blob/32cb0f9c0f7542677ddbc6253ed7c7b0e3a3d6a6/crates/cairo-lang-semantic/src/types.rs#L205)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

I think this is the place where you should actually look for the crate and its declared phantom type attrs. Here, you know a concrete item that we're interested in, so we can always reliably ask for its crate.
</blockquote></details>

Done, as you said :)


<!-- Sent from Reviewable.io -->

2024-12-11 12:32 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6843)* status: 57 of 65 files reviewed, 2 unresolved discussions (waiting on @mkaput, @orizi, and @piotmag769)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6843#-ODhOgDP38hCWAxeGN08:-ODpgsMhE6HQeo28qgCd:b9fgute) (no related file):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

Ad 1. I believe that's the reason `file_overrides` in `FilesGroup` are implemented as two queries: one, the parameterless input, keeps an HashMap of `FileId -> override` and the other query meant for broad use does the lookup and returns `Option`
</blockquote></details>

Update: **2** has been fixed, now I work on **1**


<!-- Sent from Reviewable.io -->

2024-12-11 14:46 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6843#-:-ODqAvam8guhK22XDEbT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-12-13 09:16 UTC, mkaput requested changes
> Reviewed 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6843)* status: all files reviewed, 2 unresolved discussions (waiting on @integraledelebesgue, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-compiler/src/db.rs` line 57 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6843#-ODzGoW81qdpv1iSueeP:-ODzGoW81qdpv1iSueeQ:bs85jdp) ([raw file](https://github.com/starkware-libs/cairo/blob/b02b4378ceb3f44ea02510603c45b7aa9cc8b08e/crates/cairo-lang-compiler/src/db.rs#L57)):*
> ```XML
>         init_lowering_group(&mut res, inlining_strategy);
>         init_defs_group(&mut res);
>         init_semantic_group(&mut res);
> ```

this should be changed in the PR introducing these fns


<!-- Sent from Reviewable.io -->

2024-12-13 09:29 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6843)* status: all files reviewed, 2 unresolved discussions (waiting on @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-compiler/src/db.rs` line 57 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6843#-ODzGoW81qdpv1iSueeP:-ODzJiqRCS9CpD7svS4J:b-h09u50) ([raw file](https://github.com/starkware-libs/cairo/blob/b02b4378ceb3f44ea02510603c45b7aa9cc8b08e/crates/cairo-lang-compiler/src/db.rs#L57)):*
<details><summary><i>Previously, mkaput (Marek Kaput) wrote…</i></summary><blockquote>

this should be changed in the PR introducing these fns
</blockquote></details>

I know it might not be very review-friendly, but this PR, in general, introduces all the new logic I prepared in the preceding ones. Thus I decided to use these functions here too


<!-- Sent from Reviewable.io -->

2024-12-16 06:25 UTC, mkaput approved these changes
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6843)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-12-21 23:50 UTC, piotmag769 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>
Really good job (reviewed everything as full diff of the 3 PRs, everything seems fine)

> Reviewed 52 of 64 files at r3, 5 of 8 files at r5, 3 of 9 files at r6, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6843#-:-ODuvptt-7VsOEltuSLD:b-ghi00f)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @integraledelebesgue)



<!-- Sent from Reviewable.io -->

2025-01-18 08:45 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6843#-:-OGs__Ff5z1uI9kK2uaI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @integraledelebesgue)



<!-- Sent from Reviewable.io -->

2025-01-22 05:02 UTC, orizi approved these changes
> Reviewed 53 of 53 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6843)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @integraledelebesgue)



<!-- Sent from Reviewable.io -->

2025-01-29 15:30 UTC, orizi approved these changes
> Reviewed 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6843)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @integraledelebesgue)



<!-- Sent from Reviewable.io -->

2025-01-30 06:54 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 6 files at r8, 47 of 53 files at r9, 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6843#-:-OHpzPZjD0DGXGxxQ1Ug:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @integraledelebesgue)



<!-- Sent from Reviewable.io -->

2025-02-03 12:23 UTC, piotmag769 approved these changes
> Reviewed 2 of 6 files at r8, 47 of 53 files at r9, 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6843)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @integraledelebesgue)



<!-- Sent from Reviewable.io -->

2025-02-03 12:23 UTC, piotmag769 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6843)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @integraledelebesgue)



<!-- Sent from Reviewable.io -->

2025-02-03 13:07 UTC, merged