Introduced default plugin suites to the RootDatabaseBuilder
starkware-libs/cairo pull request #6852
Opened 2024-12-09 21:24 UTC by integraledelebesgue

**Stack**:
- #6843
- #6852 ⬅
- #6840

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-12-09 21:24 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6852)
<!-- Reviewable:end -->

2024-12-10 07:03 UTC, mkaput requested changes
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: all files reviewed, 2 unresolved discussions (waiting on @integraledelebesgue, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 1881 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6852#-ODjNBd47_d350g6pTLl:-ODjNBd47_d350g6pTLm:b56lkv0) ([raw file](https://github.com/starkware-libs/cairo/blob/46919f1892e45376ca171da8f4f86eb53be21222/crates/cairo-lang-semantic/src/db.rs#L1881)):*
> ```XML
>     /// Sets macro, inline macro and analyzer plugins specified in the [`PluginSuite`] as default
>     /// for all crates.
>     /// ***
> ```

this hr was not idiomatic



_Suggestion:_
```XML
    ///
```
___
*[`crates/cairo-lang-semantic/src/db.rs` line 1917 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6852#-ODjNGEuEl0DgIUnDYi0:-ODjNGEuEl0DgIUnDYi1:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/46919f1892e45376ca171da8f4f86eb53be21222/crates/cairo-lang-semantic/src/db.rs#L1917)):*
> ```XML
>     /// Sets macro, inline macro and analyzer plugins present in the [`PluginSuite`] for a crate
>     /// pointed to by the [`CrateId`], overriding the defaults for that crate.
>     /// ***
> ```





_Suggestion:_
```XML
    ///
```


<!-- Sent from Reviewable.io -->

2024-12-10 11:50 UTC, Draggu requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: all files reviewed, 3 unresolved discussions (waiting on @integraledelebesgue, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 1939 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6852#-ODkO_ssETRniO2dwfYy:-ODkO_ssETRniO2dwfYz:bfyzh6d) ([raw file](https://github.com/starkware-libs/cairo/blob/46919f1892e45376ca171da8f4f86eb53be21222/crates/cairo-lang-semantic/src/db.rs#L1939)):*
> ```XML
>             .into_iter()
>             .map(|plugin| self.intern_analyzer_plugin(AnalyzerPluginLongId(plugin)))
>             .collect();
> ```

Can we deduplicate this logic? Also, make it a public api; it will be useful in LS, too.



_Code quote:_
```XML
        let PluginSuite { plugins, inline_macro_plugins, analyzer_plugins } = suite;

        let macro_plugins = plugins
            .into_iter()
            .map(|plugin| self.intern_macro_plugin(MacroPluginLongId(plugin)))
            .collect();

        let inline_macro_plugins = inline_macro_plugins
            .into_iter()
            .map(|(name, plugin)| {
                (name, self.intern_inline_macro_plugin(InlineMacroExprPluginLongId(plugin)))
            })
            .collect();

        let analyzer_plugins = analyzer_plugins
            .into_iter()
            .map(|plugin| self.intern_analyzer_plugin(AnalyzerPluginLongId(plugin)))
            .collect();
```


<!-- Sent from Reviewable.io -->

2024-12-10 15:11 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 1939 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6852#-ODkO_ssETRniO2dwfYy:-ODl6LuwCYQBHJ7tjb7T:b-6xqr8l) ([raw file](https://github.com/starkware-libs/cairo/blob/46919f1892e45376ca171da8f4f86eb53be21222/crates/cairo-lang-semantic/src/db.rs#L1939)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Can we deduplicate this logic? Also, make it a public api; it will be useful in LS, too.
</blockquote></details>

I extracted it as another helper.
These helpers should already be public since they belong to a pub trait, mutually implemented on every type that is a `SemanticGroup`.


<!-- Sent from Reviewable.io -->

2024-12-10 16:44 UTC, Draggu requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @integraledelebesgue, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 1883 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6852#-ODlSAhj1X2lpGBmQdxA:-ODlSAhj1X2lpGBmQdxB:b-svwkps) ([raw file](https://github.com/starkware-libs/cairo/blob/629a86ef511d2a4007a06eea309e8d9f3ab2d81d/crates/cairo-lang-semantic/src/db.rs#L1883)):*
> ```XML
>         &mut self,
>         suite: PluginSuite,
>     ) -> (Vec<MacroPluginId>, OrderedHashMap<String, InlineMacroExprPluginId>, Vec<AnalyzerPluginId>)
> ```

Make struct for these.


<!-- Sent from Reviewable.io -->

2024-12-11 06:56 UTC, mkaput approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852#-:-ODoVGXA2_AnnhLWIS_g:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue, @orizi, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-12-11 12:07 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 1883 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6852#-ODlSAhj1X2lpGBmQdxA:-ODpbNbV255CcZUTG-ui:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/629a86ef511d2a4007a06eea309e8d9f3ab2d81d/crates/cairo-lang-semantic/src/db.rs#L1883)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Make struct for these.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-12-11 12:27 UTC, Draggu approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 11 of 12 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852#-:-ODpg0dCEyP0xr79Ujrv:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @integraledelebesgue, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 1916 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6852#-ODpfp-L66jLC-2sk2YW:-ODpfp-L66jLC-2sk2YX:bdq8inn) ([raw file](https://github.com/starkware-libs/cairo/blob/98416edc57782bf30fb6e19425ba23a89b97ee51/crates/cairo-lang-semantic/src/db.rs#L1916)):*
> ```XML
>     /// [`DefsGroup::default_inline_macro_plugins`], and
>     /// [`SemanticGroup::default_analyzer_plugins`].
>     fn set_default_plugins_from_suite(&mut self, suite: PluginSuite) {
> ```

Maybe inverse this? up to you



_Suggestion:_
```XML
InternedPluginSuite
```
___
*[`crates/cairo-lang-semantic/src/db.rs` line 1931 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6852#-ODpfuOFBNFUgim15x6w:-ODpfuOFBNFUgim15x6x:b-gde9ka) ([raw file](https://github.com/starkware-libs/cairo/blob/98416edc57782bf30fb6e19425ba23a89b97ee51/crates/cairo-lang-semantic/src/db.rs#L1931)):*
> ```XML
>     /// [`DefsGroup::override_crate_inline_macro_plugins`], and
>     /// [`SemanticGroup::override_crate_analyzer_plugins`].
>     fn set_override_crate_plugins_from_suite(&mut self, crate_id: CrateId, suite: PluginSuite) {
> ```

vide supra


<!-- Sent from Reviewable.io -->

2024-12-11 14:27 UTC, mkaput approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: all files reviewed, 2 unresolved discussions (waiting on @integraledelebesgue, @orizi, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-12-13 09:08 UTC, mkaput approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: all files reviewed, 2 unresolved discussions (waiting on @integraledelebesgue, @orizi, and @piotmag769)



<!-- Sent from Reviewable.io -->

2024-12-13 11:40 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: 11 of 13 files reviewed, all discussions resolved (waiting on @Draggu, @mkaput, @orizi, and @piotmag769)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 1916 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6852#-ODpfp-L66jLC-2sk2YW:-ODzoVR_8DMZUXlUdp8V:bb6un1j) ([raw file](https://github.com/starkware-libs/cairo/blob/98416edc57782bf30fb6e19425ba23a89b97ee51/crates/cairo-lang-semantic/src/db.rs#L1916)):*
<details><summary><i>Previously, Draggu (Piotr Figiela) wrote…</i></summary><blockquote>

Maybe inverse this? up to you
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-12-13 15:12 UTC, orizi requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: all files reviewed, 2 unresolved discussions (waiting on @integraledelebesgue and @piotmag769)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 1963 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6852#-OE-Zaal5VPzpYJf2-f0:-OE-Zaal5VPzpYJf2-f1:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/c49be777b9110b80ee45013006b0e06482423c4b/crates/cairo-lang-semantic/src/db.rs#L1963)):*
> ```XML
>         self.set_inline_macro_plugins(Arc::new(raw_inline_macro_plugins));
>         self.set_analyzer_plugins(raw_analyzer_plugins);
>         // ---
> ```

?



_Code quote:_
```XML
        // ---
```
___
*[`crates/cairo-lang-semantic/src/plugin.rs` line 84 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6852#-OE-Zhgu4z2WmghxzrjG:-OE-Zhgu4z2WmghxzrjH:b-u1jazq) ([raw file](https://github.com/starkware-libs/cairo/blob/c49be777b9110b80ee45013006b0e06482423c4b/crates/cairo-lang-semantic/src/plugin.rs#L84)):*
> ```XML
>     pub inline_macro_plugins: Arc<OrderedHashMap<String, InlineMacroExprPluginId>>,
>     pub analyzer_plugins: Arc<[AnalyzerPluginId]>,
> }
> ```

maybe just have these as the original PluginSuite and having the creator responsible for interning?



_Code quote:_
```XML
#[derive(Clone, Debug)]
pub struct InternedPluginSuite {
    pub macro_plugins: Arc<[MacroPluginId]>,
    pub inline_macro_plugins: Arc<OrderedHashMap<String, InlineMacroExprPluginId>>,
    pub analyzer_plugins: Arc<[AnalyzerPluginId]>,
}
```


<!-- Sent from Reviewable.io -->

2024-12-16 20:40 UTC, integraledelebesgue reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: all files reviewed, 2 unresolved discussions (waiting on @orizi and @piotmag769)

___
*[`crates/cairo-lang-semantic/src/db.rs` line 1963 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6852#-OE-Zaal5VPzpYJf2-f0:-OEG7CUM-QJ9IDe69Rv8:b-7ohu9h) ([raw file](https://github.com/starkware-libs/cairo/blob/c49be777b9110b80ee45013006b0e06482423c4b/crates/cairo-lang-semantic/src/db.rs#L1963)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

Invoking these old setters is required to keep the compiler working while shifting to the new logic with default plugins. In this PR, queries related to the default and crate-specific plugins are not introduced to the compiler yet.
___
*[`crates/cairo-lang-semantic/src/plugin.rs` line 84 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6852#-OE-Zhgu4z2WmghxzrjG:-OEG8WBw5R0_j8bQP_Ku:b-vi4cqo) ([raw file](https://github.com/starkware-libs/cairo/blob/c49be777b9110b80ee45013006b0e06482423c4b/crates/cairo-lang-semantic/src/plugin.rs#L84)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

maybe just have these as the original PluginSuite and having the creator responsible for interning?
</blockquote></details>

It's just a helper, plain-data struct reducing the boilerplate in the methods responsible for setting per-crate plugins by wrapping those `Arc`s. I think that the current logic is nicer and more flexible - we first set up the suite, modify its contents depending on our needs and eventually intern its contents all at once before setting them as a default or for a crate.


<!-- Sent from Reviewable.io -->

2024-12-17 07:38 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: all files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue and @piotmag769)

___
*[`crates/cairo-lang-semantic/src/plugin.rs` line 84 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6852#-OE-Zhgu4z2WmghxzrjG:-OEIYE_hAYOi51_SjTu0:b-v5svrp) ([raw file](https://github.com/starkware-libs/cairo/blob/c49be777b9110b80ee45013006b0e06482423c4b/crates/cairo-lang-semantic/src/plugin.rs#L84)):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

It's just a helper, plain-data struct reducing the boilerplate in the methods responsible for setting per-crate plugins by wrapping those `Arc`s. I think that the current logic is nicer and more flexible - we first set up the suite, modify its contents depending on our needs and eventually intern its contents all at once before setting them as a default or for a crate.
</blockquote></details>

this sounds like something for a testing framework - for the general purpose - i don't like this hiding of behaviour - you're going to have this interning in any case, so you should probably not have the un-interned data here.


<!-- Sent from Reviewable.io -->

2024-12-21 23:47 UTC, piotmag769 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 11 of 12 files at r1, 2 of 2 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852#-:-ODu_uLP7V-GZMNUalJg:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/plugin.rs` line 84 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6852#-OE-Zhgu4z2WmghxzrjG:-OEfbaM51Dw3HPF6AFO3:bjkn7q2) ([raw file](https://github.com/starkware-libs/cairo/blob/c49be777b9110b80ee45013006b0e06482423c4b/crates/cairo-lang-semantic/src/plugin.rs#L84)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this sounds like something for a testing framework - for the general purpose - i don't like this hiding of behaviour - you're going to have this interning in any case, so you should probably not have the un-interned data here.
</blockquote></details>

Agree with @orizi here


<!-- Sent from Reviewable.io -->

2024-12-22 07:20 UTC, orizi reviewed
> Reviewed 5 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: all files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue)



<!-- Sent from Reviewable.io -->

2025-01-07 22:16 UTC, piotmag769 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/plugin.rs` line 84 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6852#-OE-Zhgu4z2WmghxzrjG:-OG1ok7GBziSTK4aewGh:b-w70g53) ([raw file](https://github.com/starkware-libs/cairo/blob/c49be777b9110b80ee45013006b0e06482423c4b/crates/cairo-lang-semantic/src/plugin.rs#L84)):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

I think it's no use merging those two structures and getting rid of a raw `PluginSuite`. Although we usually don't want to use the raw data that eventually gets interned, plugins are an exception, since Scarb and LS rely on the manipulation of `PluginSuite`s with raw plugins. It's essential for proc macro server logic and would require a huge effort to change
</blockquote></details>

I feel convinced, if @orizi wants to have it uninterned here than I am fine with it too I guess


<!-- Sent from Reviewable.io -->

2025-01-08 11:57 UTC, mkaput approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2025-01-08 15:07 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: all files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue)

___
*[`crates/cairo-lang-semantic/src/plugin.rs` line 84 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6852#-OE-Zhgu4z2WmghxzrjG:-OG5Rv8C2DVNk9Cbf2M6:b-n5lpk6) ([raw file](https://github.com/starkware-libs/cairo/blob/c49be777b9110b80ee45013006b0e06482423c4b/crates/cairo-lang-semantic/src/plugin.rs#L84)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

I feel convinced, if @orizi wants to have it uninterned here than I am fine with it too I guess
</blockquote></details>

i didn't want to have any uninterened structure.
i'm getting more confused.


<!-- Sent from Reviewable.io -->

2025-01-08 15:49 UTC, mkaput approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: all files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue)



<!-- Sent from Reviewable.io -->

2025-01-08 16:00 UTC, piotmag769 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/plugin.rs` line 84 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6852#-OE-Zhgu4z2WmghxzrjG:-OG5dAHQ7Q5Ey-x-85Mo:b46s7vi) ([raw file](https://github.com/starkware-libs/cairo/blob/c49be777b9110b80ee45013006b0e06482423c4b/crates/cairo-lang-semantic/src/plugin.rs#L84)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i didn't want to have any uninterened structure.
i'm getting more confused.
</blockquote></details>

Yea, missed one message. Anyways I think changing `PluginSuite` requires a lot of changes in both Scarb and LS


<!-- Sent from Reviewable.io -->

2025-01-08 18:19 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: all files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue)

___
*[`crates/cairo-lang-semantic/src/plugin.rs` line 84 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6852#-OE-Zhgu4z2WmghxzrjG:-OG67QcUBhj-u7Rm9hj6:b-rljypd) ([raw file](https://github.com/starkware-libs/cairo/blob/c49be777b9110b80ee45013006b0e06482423c4b/crates/cairo-lang-semantic/src/plugin.rs#L84)):*
<details><summary><i>Previously, piotmag769 (Piotr Magiera) wrote…</i></summary><blockquote>

Yea, missed one message. Anyways I think changing `PluginSuite` requires a lot of changes in both Scarb and LS
</blockquote></details>

tough luck - that is still the correct solution.
I don't see why you can't provide a pathway for this going towards the correct solution.

assuming the `suite builder` still exists - the fix should be extremely easy.


<!-- Sent from Reviewable.io -->

2025-01-18 08:45 UTC, orizi reviewed
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: all files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue)



<!-- Sent from Reviewable.io -->

2025-01-20 21:51 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: all files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue)

___
*[`crates/cairo-lang-semantic/src/plugin.rs` line 84 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6852#-OE-Zhgu4z2WmghxzrjG:-OH4gcOy68MHygeNU9DP:b39sqcp) ([raw file](https://github.com/starkware-libs/cairo/blob/c49be777b9110b80ee45013006b0e06482423c4b/crates/cairo-lang-semantic/src/plugin.rs#L84)):*
<details><summary><i>Previously, integraledelebesgue (Jan Smółka) wrote…</i></summary><blockquote>

How would we rework, for example, the `get_default_plugin_suite` and similar functions if we want to hold the interned data in the `PluginSuite` instead of raw plugins? That's a significant breakage, both in the compiler and our tools.
</blockquote></details>

yes - they should hold that exactly - that is definitely a very minor change.


<!-- Sent from Reviewable.io -->

2025-01-22 07:43 UTC, orizi reviewed
> Reviewed 4 of 12 files at r1, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: all files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue)



<!-- Sent from Reviewable.io -->

2025-01-29 15:25 UTC, orizi reviewed
> Reviewed 1 of 2 files at r3, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: all files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue)



<!-- Sent from Reviewable.io -->

2025-01-30 06:52 UTC, mkaput approved these changes
> Reviewed 1 of 5 files at r6, 1 of 2 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: all files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue)



<!-- Sent from Reviewable.io -->

2025-01-30 13:21 UTC, orizi reviewed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: all files reviewed, 1 unresolved discussion (waiting on @integraledelebesgue)



<!-- Sent from Reviewable.io -->

2025-02-03 08:55 UTC, orizi approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @integraledelebesgue)

___
*[`crates/cairo-lang-semantic/src/plugin.rs` line 84 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6852#-OE-Zhgu4z2WmghxzrjG:-OIA0E4I6txzMl9eAZT8:b-wx5xdh) ([raw file](https://github.com/starkware-libs/cairo/blob/c49be777b9110b80ee45013006b0e06482423c4b/crates/cairo-lang-semantic/src/plugin.rs#L84)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

yes - they should hold that exactly - that is definitely a very minor change.
</blockquote></details>

unblocking - would probably update on it after the later changes.


<!-- Sent from Reviewable.io -->

2025-02-03 12:16 UTC, piotmag769 approved these changes
> Reviewed 3 of 4 files at r8, 1 of 1 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6852)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @integraledelebesgue)



<!-- Sent from Reviewable.io -->

2025-02-03 12:48 UTC, merged