typo Update compile_error.rs
starkware-libs/cairo pull request #6880
Opened 2024-12-16 15:49 UTC by dimakozak228228

2024-12-16 15:49 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6880)
<!-- Reviewable:end -->

2024-12-16 18:22 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6880#-:-OEFhHxy8zWIsZxWLdjs:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dimakozak228228)



<!-- Sent from Reviewable.io -->

2024-12-17 07:45 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6880)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakozak228228)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6880#-OEIZmdk4LxQC5iNYjgD:-OEIZmdk4LxQC5iNYjgE:bsdmmyg) (no related file):*
run `./scripts/rust.fmt` as well as
`CAIRO_FIX_TESTS=1 cargo t --profile=ci-dev  -p cairo-lang-plugins`


<!-- Sent from Reviewable.io -->

2024-12-18 05:48 UTC, dimakozak228228 commented
@orizi all good ?

2024-12-18 05:58 UTC, orizi reviewed
No, your ci breaks, look at the other comment.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6880#-:-OENL1dy7QtyuWaCHG1d:bpx3n7t)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakozak228228)



<!-- Sent from Reviewable.io -->

2024-12-23 17:23 UTC, Fallengirl commented
@orizi finish ! thank you

2024-12-23 18:19 UTC, orizi approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6880)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fallengirl)



<!-- Sent from Reviewable.io -->

2025-01-03 12:12 UTC, merged