Fix output formatting in cairo-run
starkware-libs/cairo pull request #6911
Opened 2024-12-23 00:46 UTC by Hopium21

File changed: crates/bin/cairo-run/src/main.rs

Before: first = false; // After print!(", ")
After: first = false; // Before print!(", ")

This PR fixes the output formatting of panic messages in the Cairo runner by moving the first = false assignment before printing the comma separator. This ensures proper comma separation between panic values without an unnecessary leading comma.

2024-12-23 00:47 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6911)
<!-- Reviewable:end -->

2024-12-23 07:44 UTC, orizi requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6911)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @Hopium21)

___
*[`crates/bin/cairo-run/src/main.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6911#-OEmTPEF6QJYUhcfGQBT:-OEmTPEG8r4gFyV8ddeC:bx3vjst) ([raw file](https://github.com/starkware-libs/cairo/blob/d61731937f9271c19e5fcc5e34fe4df91ca52094/crates/bin/cairo-run/src/main.rs#L127)):*
> ```XML
>                     print!(", ");
>                    }
>                 first = false;
> ```

run `./scripts/rust_fmt.sh`


<!-- Sent from Reviewable.io -->

2024-12-23 16:40 UTC, Hopium21 reviewed
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6911)* status: all files reviewed, 1 unresolved discussion (waiting on @Hopium21)



<!-- Sent from Reviewable.io -->

2025-01-03 07:12 UTC, Hopium21 commented
@orizi I've tested the changes and verified that the output formatting works correctly now. Ready to be merged.

2025-01-03 07:14 UTC, orizi reviewed
Your ci is still broken, run ./scripts/rust_fmt.sh

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6911#-:-OFf-nDE9yI3XP58Vq5M:b3pp5m7)* status: all files reviewed, 1 unresolved discussion (waiting on @Hopium21)



<!-- Sent from Reviewable.io -->

2025-01-04 10:51 UTC, orizi reviewed
please do not do actions in this PR if you don't fix all issues at https://reviewable.io/reviews/starkware-libs/cairo/6911

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6911#-:-OFkw9Po3L_mAwHz3_mt:bz3dwgf)* status: all files reviewed, 1 unresolved discussion (waiting on @Hopium21)



<!-- Sent from Reviewable.io -->

2025-01-04 11:31 UTC, Hopium21 commented
@orizi done

2025-01-04 11:51 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6911#-:-OFl8rJW0LvJXaNYsBZH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Hopium21)



<!-- Sent from Reviewable.io -->

2025-01-04 12:05 UTC, merged