Fix quotation mark
starkware-libs/cairo pull request #6922
Opened 2024-12-25 04:13 UTC by wgyt

2024-12-25 04:13 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6922)
<!-- Reviewable:end -->

2024-12-25 05:02 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6922)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @wgyt)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6922#-OEwBRLl5TVWppro4M8p:-OEwBRLm9N7bzyb5t7Ch:b-nn0n88) (no related file):*
this might be correct - but please add an explanation as to why this is required.


<!-- Sent from Reviewable.io -->

2024-12-26 02:46 UTC, wgyt commented
i have added an explanation above. kindly give it a review.

2024-12-26 07:17 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6922#-:-OF0p0Vd8NqOuM3If_na:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wgyt)



<!-- Sent from Reviewable.io -->

2024-12-26 07:30 UTC, merged