feat(corelib): Impl fmt::debug for Range
starkware-libs/cairo pull request #6926
Opened 2024-12-25 16:38 UTC by julio4

Formats a `Range` type, allowing to print `Range` instances for debugging purposes.

#### Example

```
println!("{:?}", 1..5); // Result will be `1..5`
```

2024-12-25 18:14 UTC, orizi requested changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6926)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @julio4)

___
*[`corelib/src/test/range_test.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6926#-OEz0a8Y0OucamO3rhGJ:-OEz0a8Y0OucamO3rhGK:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/535bf4ce676bdd6a2a53f760a04c2bf33b1f0983/corelib/src/test/range_test.cairo#L3)):*
> ```Cairo
> #[test]
> fn test_range_format() {
>     assert(format!("{:?}", 1..5) == "1..5", 'bad range debug formatting');
> ```





_Suggestion:_
```Cairo
    assert!(format!("{:?}", 1..5) == "1..5");
```


<!-- Sent from Reviewable.io -->

2024-12-25 18:28 UTC, julio4 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6926)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/test/range_test.cairo` line 3 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6926#-OEz0a8Y0OucamO3rhGJ:-OEz3rY45x7GZtwXbZFN:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/535bf4ce676bdd6a2a53f760a04c2bf33b1f0983/corelib/src/test/range_test.cairo#L3)):*
> ```Cairo
> #[test]
> fn test_range_format() {
>     assert(format!("{:?}", 1..5) == "1..5", 'bad range debug formatting');
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-25 18:32 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6926#-:-OEz4qil3XNV6buh8Pne:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6926#-OEz4op7Dj3CMNuT3bOF:-OEz4op7Dj3CMNuT3bOG:b-uuj1x0) (no related file):*
@gilbens-starkware for 2nd eye.


<!-- Sent from Reviewable.io -->

2024-12-26 08:13 UTC, gilbens-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6926#-:-OF10RiW3bzOM_mo5BkO:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-12-26 08:18 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6926#-:-OF11nPh8vzEvETxpvU3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @julio4)



<!-- Sent from Reviewable.io -->

2024-12-26 08:26 UTC, merged