feat(corelib): OptionTrait::is_some_and
starkware-libs/cairo pull request #6927
Opened 2024-12-25 17:37 UTC by julio4

Returns `true` if the `Option` is `Option::Some` and the value inside of it matches a predicate.

#### Examples

```cairo
assert_eq!(Option::Some(2_u8).is_some_and(|x| x > 1), true);
assert_eq!(Option::Some(0_u8).is_some_and(|x| x > 1), false);

let option: Option<u8> = Option::None;
assert_eq!(option.is_some_and(|x| x > 1), false);
```

2024-12-25 18:25 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6927#-:-OEz3Gkg8HK-ywT_b2Sh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @julio4)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6927#-OEz3I6VC4BNz3Txfj7w:-OEz3I6VC4BNz3Txfj7x:bl3aonu) (no related file):*
@TomerStarkware for 2nd eye.


<!-- Sent from Reviewable.io -->

2024-12-25 18:40 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6927)* status: all files reviewed, 1 unresolved discussion (waiting on @julio4)

___
*[`corelib/src/option.cairo` line 216 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6927#-OEz6XE21Kk1XLFjPrQR:-OEz6XE21Kk1XLFjPrQS:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/f3208f1f89973fd685851094eb9adf805e77755e/corelib/src/option.cairo#L216)):*
> ```Cairo
>     fn is_some_and<F, +Drop<F>, impl func: core::ops::FnOnce<F, (T,)>[Output: bool]>(
>         self: Option<T>, f: F,
>     ) -> bool;
> ```





_Suggestion:_
```Cairo
    #[must_use]
    fn is_some_and<F, +Drop<F>, +core::ops::FnOnce<F, (T,)>[Output: bool]>(
        self: Option<T>, f: F,
    ) -> bool;
```


<!-- Sent from Reviewable.io -->

2024-12-25 22:20 UTC, julio4 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6927)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/option.cairo` line 216 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6927#-OEz6XE21Kk1XLFjPrQR:-OEztxiw0yWWX7raLlZD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/f3208f1f89973fd685851094eb9adf805e77755e/corelib/src/option.cairo#L216)):*
> ```Cairo
>     fn is_some_and<F, +Drop<F>, impl func: core::ops::FnOnce<F, (T,)>[Output: bool]>(
>         self: Option<T>, f: F,
>     ) -> bool;
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-26 07:29 UTC, orizi approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6927)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @julio4)



<!-- Sent from Reviewable.io -->

2024-12-26 11:40 UTC, TomerStarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6927#-:-OF1lB8712U9JqVS8h6O:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @julio4)



<!-- Sent from Reviewable.io -->

2024-12-26 12:45 UTC, merged