feat(corelib): OptionTrait::is_none_or
starkware-libs/cairo pull request #6928
Opened 2024-12-25 17:45 UTC by julio4

Returns `true` if the `Option` is `Option::None` or the value inside of it matches a
predicate.

#### Examples

```cairo
assert_eq!(Option::Some(2_u8).is_none_or(|x| x > 1), true);
assert_eq!(Option::Some(0_u8).is_none_or(|x| x > 1), false);

let option: Option<u8> = Option::None;
assert_eq!(option.is_none_or(|x| x > 1), true);
```

2024-12-25 17:46 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6928)
<!-- Reviewable:end -->

2024-12-25 18:27 UTC, orizi approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6928)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @julio4)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6928#-OEz3exM43CjdEwFjq5e:-OEz3exM43CjdEwFjq5f:b-gkrpvr) (no related file):*
@gilbens-starkware @TomerStarkware for 2nd eye


<!-- Sent from Reviewable.io -->

2024-12-25 18:40 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6928)* status: all files reviewed, 1 unresolved discussion (waiting on @julio4)

___
*[`corelib/src/option.cairo` line 225 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6928#-OEz6jDj4O9X7bycuJaa:-OEz6jDj4O9X7bycuJab:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/3ec40b55b35fc0bc8b2149442452a86c09cb4d9f/corelib/src/option.cairo#L225)):*
> ```Cairo
>     /// ```
>     #[must_use]
>     fn is_none_or<F, +Drop<F>, impl func: core::ops::FnOnce<F, (T,)>[Output: bool]>(
> ```





_Suggestion:_
```Cairo
    fn is_none_or<F, +Drop<F>, +core::ops::FnOnce<F, (T,)>[Output: bool]>(
```


<!-- Sent from Reviewable.io -->

2024-12-25 22:16 UTC, julio4 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6928)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/option.cairo` line 225 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6928#-OEz6jDj4O9X7bycuJaa:-OEztD5Y4ErxhoodhwdY:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3ec40b55b35fc0bc8b2149442452a86c09cb4d9f/corelib/src/option.cairo#L225)):*
> ```Cairo
>     /// ```
>     #[must_use]
>     fn is_none_or<F, +Drop<F>, impl func: core::ops::FnOnce<F, (T,)>[Output: bool]>(
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-26 07:30 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6928#-:-OF0rvnzD09YUA187KOh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @julio4)



<!-- Sent from Reviewable.io -->

2024-12-26 11:40 UTC, TomerStarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6928#-:-OF1l52t7gSDbtmQ3hI7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @julio4)



<!-- Sent from Reviewable.io -->

2024-12-26 12:45 UTC, merged