feat(corelib): add `map` to `Option`
starkware-libs/cairo pull request #6929
Opened 2024-12-25 18:14 UTC by cairolover

Adds `map` to `OptionTrait` for more functional programming features.

moved `ok_or` to be close to `map`, regrouping functions by concern (transforming contained values).

2024-12-25 18:14 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6929)
<!-- Reviewable:end -->

2024-12-25 18:18 UTC, julio4 commented
@cairolover Maybe we should coordinate to not work on the same things cf #6927 #6928 #6930

2024-12-25 18:25 UTC, enitrat commented
sure, why not. I was planning on adding commonly used functional programing methods

2024-12-25 18:43 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6929)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @cairolover)

___
*[`corelib/src/option.cairo` line 179 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6929#-OEz7H1hESNCXhYGY3nu:-OEz7H1hESNCXhYGY3nv:bvi0lfm) ([raw file](https://github.com/starkware-libs/cairo/blob/809dfef02117734ba7271fba03c117dded8db11f/corelib/src/option.cairo#L179)):*
> ```Cairo
> 
>     /// Transforms the `Option<T>` into a `Result<T, E>`, mapping `Option::Some(v)` to
>     /// `Result::Ok(v)` and `Option::None` to `Result::Err(err)`.
> ```

why move it?


<!-- Sent from Reviewable.io -->

2024-12-25 21:50 UTC, cairolover reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6929)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/option.cairo` line 179 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6929#-OEz7H1hESNCXhYGY3nu:-OEzm6ag3vuSNjEKSwrO:b-dxrpkj) ([raw file](https://github.com/starkware-libs/cairo/blob/809dfef02117734ba7271fba03c117dded8db11f/corelib/src/option.cairo#L179)):*
> moved `ok_or` to be close to `map`, regrouping functions by concern (transforming contained values).

As we're adding methods to the corelib, I think it's good that we ensure that they're grouped by concern. In that case, `ok_or` is should be grouped with `map`. 

I would even go as far as moving `unwrap` with `unwrap_or`, `unwrap_or_default` and `unwrap_or_else`, but that can be for another PR if you agree. It's minor stuff but makes the difference at the end.

Also: if you prefer that I make 1 change per PR instead of adding scout commits, please let me know 😁


<!-- Sent from Reviewable.io -->

2024-12-26 07:34 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6929)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @cairolover)

___
*[`corelib/src/option.cairo` line 179 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6929#-OEz7H1hESNCXhYGY3nu:-OF0smNv6hNQNtcyYKcT:bw22hsb) ([raw file](https://github.com/starkware-libs/cairo/blob/809dfef02117734ba7271fba03c117dded8db11f/corelib/src/option.cairo#L179)):*
<details><summary><i>Previously, cairolover (cairolover) wrote…</i></summary><blockquote>

> moved `ok_or` to be close to `map`, regrouping functions by concern (transforming contained values).

As we're adding methods to the corelib, I think it's good that we ensure that they're grouped by concern. In that case, `ok_or` is should be grouped with `map`. 

I would even go as far as moving `unwrap` with `unwrap_or`, `unwrap_or_default` and `unwrap_or_else`, but that can be for another PR if you agree. It's minor stuff but makes the difference at the end.

Also: if you prefer that I make 1 change per PR instead of adding scout commits, please let me know 😁
</blockquote></details>

reordering in a different PR would be appreciated - this is more difficult to review this way.

thanks!


<!-- Sent from Reviewable.io -->

2024-12-26 07:35 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6929)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @cairolover)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6929#-OF0t17B164wFQuwFjbv:-OF0t17B164wFQuwFjbw:bl3aonu) (no related file):*
@TomerStarkware for 2nd eye.


<!-- Sent from Reviewable.io -->

2024-12-26 07:57 UTC, cairolover reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6929)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/option.cairo` line 179 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6929#-OEz7H1hESNCXhYGY3nu:-OF0y7n22MW81onKc5bn:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/809dfef02117734ba7271fba03c117dded8db11f/corelib/src/option.cairo#L179)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

reordering in a different PR would be appreciated - this is more difficult to review this way.

thanks!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-26 07:59 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6929)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @cairolover)

___
*[`corelib/src/option.cairo` line 265 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6929#-OF0yYYO8YhoiPd4hXph:-OF0yYYO8YhoiPd4hXpi:bgz8oa8) ([raw file](https://github.com/starkware-libs/cairo/blob/62947da5f34e3fb26db49006ae62b3c6ce61be87/corelib/src/option.cairo#L265)):*
> ```Cairo
>     /////////////////////////////////////////////////////////////////////////
>     // Transforming contained values
>     /////////////////////////////////////////////////////////////////////////
> ```

@enitrat should we have such headlines?



_Code quote:_
```Cairo
    /////////////////////////////////////////////////////////////////////////
    // Transforming contained values
    /////////////////////////////////////////////////////////////////////////
```


<!-- Sent from Reviewable.io -->

2024-12-26 10:17 UTC, enitrat reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6929)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/option.cairo` line 265 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6929#-OF0yYYO8YhoiPd4hXph:-OF1T49YDWRrfwwY4fDL:bgu4hc4) ([raw file](https://github.com/starkware-libs/cairo/blob/62947da5f34e3fb26db49006ae62b3c6ce61be87/corelib/src/option.cairo#L265)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

@enitrat should we have such headlines?
</blockquote></details>

This has no impact on the generated doc site, but helps when navigating the source code. I think we could.


<!-- Sent from Reviewable.io -->

2024-12-26 10:20 UTC, enitrat reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6929)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/option.cairo` line 265 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6929#-OF0yYYO8YhoiPd4hXph:-OF1Tr6u20FBEb_3QXc1:b-otqsit) ([raw file](https://github.com/starkware-libs/cairo/blob/62947da5f34e3fb26db49006ae62b3c6ce61be87/corelib/src/option.cairo#L265)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

This has no impact on the generated doc site, but helps when navigating the source code. I think we could.
</blockquote></details>

Rust has this


<!-- Sent from Reviewable.io -->

2024-12-26 11:39 UTC, TomerStarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6929#-:-OF1koNv5luwNbDw8ijP:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @enitrat and @orizi)



<!-- Sent from Reviewable.io -->

2024-12-26 11:45 UTC, orizi approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6929)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cairolover)



<!-- Sent from Reviewable.io -->

2024-12-26 11:45 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6929#-:-OF1mOxV8LYba6RbHVdZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cairolover)



<!-- Sent from Reviewable.io -->

2024-12-26 11:49 UTC, TomerStarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6929#-:-OF1nH158xP35UunEucW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cairolover)



<!-- Sent from Reviewable.io -->

2024-12-26 12:00 UTC, merged