feat(corelib): add 'map' methods to 'Result'
starkware-libs/cairo pull request #6932
Opened 2024-12-26 11:18 UTC by cairolover

Adds `map`, `map_or`, `map_or_else` and `map_err` to `Result`.

2024-12-26 11:18 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6932)
<!-- Reviewable:end -->

2024-12-26 11:48 UTC, orizi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6932)* status: 0 of 2 files reviewed, all discussions resolved

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6932#-OF1mjKx-wRPrEkh_Wag:-OF1mjKx-wRPrEkh_Wah:bu9hjyc) (no related file):*
@TomerStarkware for 2nd eye.
@eni for doc 2nd eye.


<!-- Sent from Reviewable.io -->

2024-12-26 11:49 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6932)* status: 0 of 2 files reviewed, all discussions resolved

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6932#-OF1mjKx-wRPrEkh_Wag:-OF1n-9r3j2TK_43-iGi:by48v6p) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

@TomerStarkware for 2nd eye.
@eni for doc 2nd eye.
</blockquote></details>

sorry - wrong eni @enitrat 


<!-- Sent from Reviewable.io -->

2024-12-26 11:54 UTC, enitrat reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6932)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @cairolover and @orizi)

___
*[`corelib/src/result.cairo` line 615 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6932#-OF1oGfZ8a9K7cEFxhSl:-OF1oGfZ8a9K7cEFxhSm:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/a7a5e7321ec710170404a005827d20b8664ae8f3/corelib/src/result.cairo#L615)):*
> ```Cairo
>     ///
>     /// let x: Result<_, ByteArray> = Result::Err("bar");
>     /// assert!(x.map_or(42, |v: ByteArray| v.len()) == 42);
> ```





_Suggestion:_
```Cairo
    /// let x: Result<ByteArray, ByteArray> = Result::Ok("foo");
    /// assert!(x.map_or(42, |v: ByteArray| v.len()) == 3);
    ///
    /// let x: Result<ByteArray, ByteArray> = Result::Err("bar");
    /// assert!(x.map_or(42, |v: ByteArray| v.len()) == 42);
```


<!-- Sent from Reviewable.io -->

2024-12-26 12:08 UTC, enitrat reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6932)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @cairolover and @orizi)

___
*[`corelib/src/result.cairo` line 644 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6932#-OF1r7DtD1pQ9FJyFhKv:-OF1r7DtD1pQ9FJyFhKw:b45h) ([raw file](https://github.com/starkware-libs/cairo/blob/a7a5e7321ec710170404a005827d20b8664ae8f3/corelib/src/result.cairo#L644)):*
> ```Cairo
>     /// let x : Result<ByteArray, ByteArray> = Result::Err("bar");
>     /// assert!(x.map_or_else(|e: ByteArray| k * 2, |v: ByteArray| v.len()) == 42);
>     /// ```
> ```





_Suggestion:_
```Cairo
    /// let x : Result<ByteArray, _> = Result::Ok("foo");
    /// assert!(x.map_or_else(|e: ByteArray| k * 2, |v: ByteArray| v.len()) == 3);
    ///
    /// let x : Result<_, ByteArray> = Result::Err("bar");
    /// assert!(x.map_or_else(|e: ByteArray| k * 2, |v: ByteArray| v.len()) == 42);
    /// ```
```


<!-- Sent from Reviewable.io -->

2024-12-26 12:13 UTC, cairolover reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6932)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @enitrat and @orizi)

___
*[`corelib/src/result.cairo` line 644 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6932#-OF1r7DtD1pQ9FJyFhKv:-OF1saMN9S17tQd0IIni:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/a7a5e7321ec710170404a005827d20b8664ae8f3/corelib/src/result.cairo#L644)):*
> ```Cairo
>     /// let x : Result<ByteArray, ByteArray> = Result::Err("bar");
>     /// assert!(x.map_or_else(|e: ByteArray| k * 2, |v: ByteArray| v.len()) == 42);
>     /// ```
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-26 12:15 UTC, enitrat reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6932#-:-OF1smVL75QtkGs3r27O:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2024-12-26 12:37 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6932#-:-OF1yDrlEonfAT61zlA7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cairolover)



<!-- Sent from Reviewable.io -->

2024-12-27 01:16 UTC, TomerStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6932)* status: all files reviewed, 1 unresolved discussion (waiting on @cairolover)

___
*[`corelib/src/result.cairo` line 681 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6932#-OF4fRm7E1i91YwR6VRG:-OF4fRm7E1i91YwR6VRH:b-sguac8) ([raw file](https://github.com/starkware-libs/cairo/blob/84864eb636442b53ad87de9fb87a17c812de7d71/corelib/src/result.cairo#L681)):*
> ```Cairo
>     /// ```
>     fn map_err<F, O, +Drop<O>, +core::ops::FnOnce<O, (E,)>[Output: F]>(
>         self: Result<T, E>, op: O,
> ```

make the parameters name consistent with the rest of functions



_Suggestion:_
```Cairo
    fn map_err<F, U, +Drop<F>, +core::ops::FnOnce<F, (E,)>[Output: U]>(
        self: Result<T, E>, f: F,
```


<!-- Sent from Reviewable.io -->

2024-12-27 20:26 UTC, cairolover reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6932)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)

___
*[`corelib/src/result.cairo` line 681 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6932#-OF4fRm7E1i91YwR6VRG:-OF8mjgWANahhre-q-re:b-55i753) ([raw file](https://github.com/starkware-libs/cairo/blob/84864eb636442b53ad87de9fb87a17c812de7d71/corelib/src/result.cairo#L681)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

make the parameters name consistent with the rest of functions
</blockquote></details>

Error types - `E -> F`
Return types - `T -> U`
Function types - `F` (fn), `O` (op)

There's a "conflict" here between `F` as the second candidate for error type and `F` the function. Thus `O` and `op` seems more logical to me than assigning `U` to an Error type


<!-- Sent from Reviewable.io -->

2024-12-27 20:35 UTC, cairolover reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6932)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi and @TomerStarkware)

___
*[`corelib/src/result.cairo` line 681 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6932#-OF4fRm7E1i91YwR6VRG:-OF8oy63A9v3X3DIsDyQ:b-dgjxin) ([raw file](https://github.com/starkware-libs/cairo/blob/84864eb636442b53ad87de9fb87a17c812de7d71/corelib/src/result.cairo#L681)):*
<details><summary><i>Previously, cairolover (cairolover) wrote…</i></summary><blockquote>

Error types - `E -> F`
Return types - `T -> U`
Function types - `F` (fn), `O` (op)

There's a "conflict" here between `F` as the second candidate for error type and `F` the function. Thus `O` and `op` seems more logical to me than assigning `U` to an Error type
</blockquote></details>

Done.
used `G` for the second error type


<!-- Sent from Reviewable.io -->

2024-12-28 00:56 UTC, TomerStarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6932#-:-OF9krKe8q2aijaCE_3E:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cairolover)



<!-- Sent from Reviewable.io -->

2025-01-03 17:49 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6932)* status: all files reviewed, 1 unresolved discussion (waiting on @cairolover)

___
*[`corelib/src/result.cairo` line 682 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6932#-OFhGyTaCFALZjI8fFTk:-OFhGyTb0sU-bDL7qO-Y:b-noz3ei) ([raw file](https://github.com/starkware-libs/cairo/blob/796bf6f17b88ee161e0552e3e0766b0a1b7de922/corelib/src/result.cairo#L682)):*
> ```Cairo
>     fn map_err<F, G, +Drop<F>, +core::ops::FnOnce<F, (E,)>[Output: G]>(
>         self: Result<T, E>, f: F,
>     ) -> Result<T, G> {
> ```

let's stick to rust's signature - and more so to the first param being the output type.



_Suggestion:_
```Cairo
    fn map_err<F, O, +Drop<F>, +core::ops::FnOnce<O, (E,)>[Output: F]>(
        self: Result<T, E>, op: O,
    ) -> Result<T, F> {
```


<!-- Sent from Reviewable.io -->

2025-01-03 18:22 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6932#-:-OFhOmxUATFPHSuGEgqM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cairolover)



<!-- Sent from Reviewable.io -->

2025-01-04 07:56 UTC, merged