feat(corelib): Result iterator
starkware-libs/cairo pull request #6933
Opened 2024-12-26 15:58 UTC by cairolover

Adds `IntoIter` and `Iter` implementations for `Result<T, E>`.
Follows a format similar to `SpanIter` and `ArrayIter`, with a new `ResultIter` struct.

2024-12-26 15:58 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6933)
<!-- Reviewable:end -->

2024-12-26 20:52 UTC, cairolover reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6933)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`corelib/src/test/result_test.cairo` line 2 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6933#-OF3jNzx4JG0Ucyf9iIa:-OF3jNzx4JG0Ucyf9iIb:bg20mtt) ([raw file](https://github.com/starkware-libs/cairo/blob/9b67600241f54db19cfc782fa2763a49a16bf269/corelib/src/test/result_test.cairo#L2)):*
> ```Cairo
> use crate::result::{Result, ResultTraitImpl};
> use crate::iter::{IntoIterator, Iterator};
> ```

should this not be included automatically in the prelude?


<!-- Sent from Reviewable.io -->

2024-12-28 13:40 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6933)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cairolover)

___
*[`corelib/src/result.cairo` line 577 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6933#-OFCUeYi0lxAxvXXZTkS:-OFCUeYi0lxAxvXXZTkT:b77kg4s) ([raw file](https://github.com/starkware-libs/cairo/blob/9b67600241f54db19cfc782fa2763a49a16bf269/corelib/src/result.cairo#L577)):*
> ```Cairo
> 
> impl ResultIntoIterator<T, E, +Copy<T>, +Destruct<T>, +Destruct<E>> of IntoIterator<Result<T, E>> {
>     type IntoIter = ResultIter<T>;
> ```

consider just using `OptionIter` here after it is merged.



_Suggestion:_
```Cairo
impl ResultIntoIterator<T, E, +Copy<T>, +Destruct<T>, +Destruct<E>> of IntoIterator<Result<T, E>> {
    type IntoIter = OptionIter<T>;
```
___
*[`corelib/src/test/result_test.cairo` line 265 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6933#-OFCUYKE4dl7uZPtFWMO:-OFCUYKF12QyS_1QYNf8:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/9b67600241f54db19cfc782fa2763a49a16bf269/corelib/src/test/result_test.cairo#L265)):*
> ```Cairo
>     let x: Result<u32, ByteArray> = Result::Ok(5);
>     let mut x_iter = x.into_iter();
>     assert!(x_iter.next() == Option::Some(5));
> ```





_Suggestion:_
```Cairo
    assert!(x_iter.next() == Option::Some(5));
    assert!(x_iter.next() == Option::None);
```


<!-- Sent from Reviewable.io -->

2025-01-02 13:23 UTC, cairolover reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6933)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/result.cairo` line 577 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6933#-OFCUeYi0lxAxvXXZTkS:-OFbAdBYDbgOn-QoxwJu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9b67600241f54db19cfc782fa2763a49a16bf269/corelib/src/result.cairo#L577)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

consider just using `OptionIter` here after it is merged.
</blockquote></details>

Done.
___
*[`corelib/src/test/result_test.cairo` line 265 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6933#-OFCUYKE4dl7uZPtFWMO:-OFbAtosD-ryNG65ZMvu:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/9b67600241f54db19cfc782fa2763a49a16bf269/corelib/src/test/result_test.cairo#L265)):*
> ```Cairo
>     let x: Result<u32, ByteArray> = Result::Ok(5);
>     let mut x_iter = x.into_iter();
>     assert!(x_iter.next() == Option::Some(5));
> ```

Done.


<!-- Sent from Reviewable.io -->

2025-01-02 17:49 UTC, orizi requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6933)* status: all files reviewed, 2 unresolved discussions (waiting on @cairolover)

___
*[`corelib/src/result.cairo` line 557 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6933#-OFc7ZkUDTG2LcVkqbCO:-OFc7ZkVAc83BtpPaMQ6:b-x5yfgp) ([raw file](https://github.com/starkware-libs/cairo/blob/40e182afe2f34d4797d2104e1d1bb66717b284c1/corelib/src/result.cairo#L557)):*
> ```Cairo
> 
> impl ResultIntoIterator<
>     T, E, +Copy<T>, +Destruct<T>, +Destruct<E>,
> ```

I don't think this should be required.



_Suggestion:_
```Cairo
    T, E, +Destruct<T>, +Destruct<E>,
```


<!-- Sent from Reviewable.io -->

2025-01-02 19:26 UTC, cairolover reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6933)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/result.cairo` line 578 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6933#-OFbl82eBagYXdTu9hGs:-OFcTeoq1Ci9wxDaagic:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/3f8b3ff24f8a55e7a21abfbbcb0f32db2e861963/corelib/src/result.cairo#L578)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

and remove the `pub(crate)`.
</blockquote></details>

Done.
___
*[`corelib/src/result.cairo` line 557 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6933#-OFc7ZkUDTG2LcVkqbCO:-OFcTcpYAusLILyXNC73:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/40e182afe2f34d4797d2104e1d1bb66717b284c1/corelib/src/result.cairo#L557)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

I don't think this should be required.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-02 20:05 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6933#-:-OFcbrg--laNoztqaGgp:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @cairolover)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6933#-OFcbsBD5IN7L0y1mbv9:-OFcbsBD5IN7L0y1mbvA:b-uuj1x0) (no related file):*
@gilbens-starkware for 2nd eye.


<!-- Sent from Reviewable.io -->

2025-01-05 05:24 UTC, orizi approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6933)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cairolover)



<!-- Sent from Reviewable.io -->

2025-01-05 19:19 UTC, orizi approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6933)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cairolover)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6933#-OFcbsBD5IN7L0y1mbv9:-OFru67eBKwhB3wqRg1s:bb7mm0n) (no related file):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

@gilbens-starkware for 2nd eye.
</blockquote></details>

ping


<!-- Sent from Reviewable.io -->

2025-01-06 10:05 UTC, gilbens-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6933#-:-OFv3nCv875QTs60o8hh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cairolover)



<!-- Sent from Reviewable.io -->

2025-01-06 11:04 UTC, orizi approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6933)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cairolover)



<!-- Sent from Reviewable.io -->

2025-01-06 11:18 UTC, merged