feat(corelib): ByteArrayIterator
starkware-libs/cairo pull request #6938
Opened 2024-12-27 10:50 UTC by julio4

Close #6817

Implement `iter::IntoIterator<ByteArray>` following `ByteArrayTrait::len()` and `ByteArrayTrait::at() -> Option<u8>`

#### Example

```cairo
let ba: ByteArray = "hello";
let expected = array!['h', 'e', 'l', 'l', 'o'];
let mut i = 0;
for c in ba {
    assert_eq!(c, *expected[i]);
    i += 1;
}
```

2024-12-28 13:56 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6938)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @julio4)

___
*[`corelib/src/ops.cairo` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6938#-OFCY2QKEqsL5UaAIHi9:-OFCY2QKEqsL5UaAIHiA:bkkpzjd) ([raw file](https://github.com/starkware-libs/cairo/blob/149dcea7791fb50678d78029e58d47b41d2a0219/corelib/src/ops.cairo#L14)):*
> ```Cairo
> #[allow(unused_imports)]
> use range::RangeOp;
> pub use range::{Range, RangeTrait};
> ```

making it public sounds more sensible for me.



_Suggestion:_
```Cairo
mod range;
// `RangeOp` is used internally by the compiler.
#[allow(unused_imports)]
use range::RangeOp;
pub use range::{Range, RangeTrait, RangeIterator};
```
___
*[`corelib/src/byte_array.cairo` line 498 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6938#-OFCXw-89UlLl-c1ioCc:-OFCXw-89UlLl-c1ioCd:b-t4mco9) ([raw file](https://github.com/starkware-libs/cairo/blob/149dcea7791fb50678d78029e58d47b41d2a0219/corelib/src/byte_array.cairo#L498)):*
> ```Cairo
> pub struct ByteArrayIter {
>     ba: ByteArray,
>     alive: crate::ops::range::RangeIterator<usize>,
> ```

alive?



_Code quote:_
```Cairo
    alive: crate::ops::range::RangeIterator<usize>,
```
___
*[`corelib/src/byte_array.cairo` line 498 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6938#-OFCYJu03jET6VnEyjjs:-OFCYJu03jET6VnEyjjt:b-e440qc) ([raw file](https://github.com/starkware-libs/cairo/blob/149dcea7791fb50678d78029e58d47b41d2a0219/corelib/src/byte_array.cairo#L498)):*
> ```Cairo
> pub struct ByteArrayIter {
>     ba: ByteArray,
>     alive: crate::ops::range::RangeIterator<usize>,
> ```

add a todo to do an actual efficient implementation (as something more intrusive would obviously be more efficient)



_Code quote:_
```Cairo
pub struct ByteArrayIter {
    ba: ByteArray,
    alive: crate::ops::range::RangeIterator<usize>,
```


<!-- Sent from Reviewable.io -->

2024-12-28 14:55 UTC, julio4 commented
*[`corelib/src/byte_array.cairo` line 498 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6938#-OFCXw-89UlLl-c1ioCc:-OFCkR8OEJay73U-M19m:b-iv4ec8) ([raw file](https://github.com/starkware-libs/cairo/blob/d8034f3b370c9920714fe6044ae2a6647351a304/corelib/src/byte_array.cairo#L498)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

alive?
</blockquote></details>

Alive kind of represent the elements that are not yet yielded, so the range of active/valid elements in the iterator lifecycle, with the previous ones being "dead"/consumed. 
Maybe there's a better name, feel free to make suggestion.


<!-- Sent from Reviewable.io -->

2024-12-28 15:05 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6938)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @julio4)

___
*[`corelib/src/byte_array.cairo` line 498 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6938#-OFCXw-89UlLl-c1ioCc:-OFCn3SM6ur1ygwU-aUo:bmazxz6) ([raw file](https://github.com/starkware-libs/cairo/blob/d8034f3b370c9920714fe6044ae2a6647351a304/corelib/src/byte_array.cairo#L498)):*
<details><summary><i>Previously, julio4 (Julio) wrote…</i></summary><blockquote>

Alive kind of represent the elements that are not yet yielded, so the range of active/valid elements in the iterator lifecycle, with the previous ones being "dead"/consumed. 
Maybe there's a better name, feel free to make suggestion.
</blockquote></details>

even `current_index` sounds better in my mind.


<!-- Sent from Reviewable.io -->

2024-12-28 15:22 UTC, julio4 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6938)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/byte_array.cairo` line 498 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6938#-OFCYJu03jET6VnEyjjs:-OFCr37S7dFn8UO4DtzZ:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d8034f3b370c9920714fe6044ae2a6647351a304/corelib/src/byte_array.cairo#L498)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

add a todo to do an actual efficient implementation (as something more intrusive would obviously be more efficient)
</blockquote></details>

Done.
___
*[`corelib/src/byte_array.cairo` line 498 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6938#-OFCXw-89UlLl-c1ioCc:-OFCr3cS7P3p5SL-b9zD:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d8034f3b370c9920714fe6044ae2a6647351a304/corelib/src/byte_array.cairo#L498)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

even `current_index` sounds better in my mind.
</blockquote></details>

Done.
___
*[`corelib/src/ops.cairo` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6938#-OFCY2QKEqsL5UaAIHi9:-OFCr0vK76pPtnL6rfOo:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/d8034f3b370c9920714fe6044ae2a6647351a304/corelib/src/ops.cairo#L14)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

making it public sounds more sensible for me.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-28 17:49 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6938)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @julio4)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6938#-OFDNoMy4-_esT71Qvco:-OFDNoMy4-_esT71Qvcp:b-uuj1x0) (no related file):*
@gilbens-starkware for 2nd eye.
___
*[`corelib/src/test/byte_array_test.cairo` line 495 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6938#-OFDN4KH-dw6vWzCZ_T9:-OFDN4KI8IrIieewlXyb:bhhj8e3) ([raw file](https://github.com/starkware-libs/cairo/blob/1b658626888cc799de081953a63723e3f75cdd35/corelib/src/test/byte_array_test.cairo#L495)):*
> ```Cairo
>         i += 1;
>     };
>     assert_eq!(iter.next(), Option::None);
> ```

feels more direct for me.



_Suggestion:_
```Cairo
    let ba: ByteArray = "hello";
    let mut iter = ba.into_iter();
    assert_eq!(iter.next(), Option::Some('h');
    assert_eq!(iter.next(), Option::Some('e');
    assert_eq!(iter.next(), Option::Some('l');
    assert_eq!(iter.next(), Option::Some('l');
    assert_eq!(iter.next(), Option::Some('o');
    assert_eq!(iter.next(), Option::None);
```


<!-- Sent from Reviewable.io -->

2024-12-28 18:27 UTC, julio4 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6938)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/test/byte_array_test.cairo` line 495 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6938#-OFDN4KH-dw6vWzCZ_T9:-OFDWQsZ1oUQZoiuiVMP:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1b658626888cc799de081953a63723e3f75cdd35/corelib/src/test/byte_array_test.cairo#L495)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

feels more direct for me.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-29 09:45 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6938)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @julio4)

___
*[`corelib/src/test/language_features/for_test.cairo` line 78 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6938#-OFGnRFSEXM7sYxdndAM:-OFGnRFSEXM7sYxdndAN:bqotpix) ([raw file](https://github.com/starkware-libs/cairo/blob/ccb32b56a6e6338dd7e8936e25f9dd81d74ae531/corelib/src/test/language_features/for_test.cairo#L78)):*
> ```Cairo
>         i += 1;
>     }
> }
> ```

no need for this test - this is for `for` tests - not for iterators.



_Code quote:_
```Cairo
#[test]
fn test_for_loop_ba() {
    let ba: ByteArray = "hello";
    let expected = array!['h', 'e', 'l', 'l', 'o'];
    let mut i = 0;
    for c in ba {
        assert_eq!(c, *expected[i]);
        i += 1;
    }
}
```


<!-- Sent from Reviewable.io -->

2024-12-29 13:40 UTC, julio4 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6938)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/test/language_features/for_test.cairo` line 78 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6938#-OFGnRFSEXM7sYxdndAM:-OFHdJAVCxNEksKpAyvq:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ccb32b56a6e6338dd7e8936e25f9dd81d74ae531/corelib/src/test/language_features/for_test.cairo#L78)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

no need for this test - this is for `for` tests - not for iterators.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-29 13:53 UTC, gilbens-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6938)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @julio4 and @orizi)

___
*[`corelib/src/byte_array.cairo` line 505 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6938#-OFHg6Dy8VdpYBdVDUxf:-OFHg6Dy8VdpYBdVDUxg:b-4fsm2d) ([raw file](https://github.com/starkware-libs/cairo/blob/ccb32b56a6e6338dd7e8936e25f9dd81d74ae531/corelib/src/byte_array.cairo#L505)):*
> ```Cairo
>     type Item = u8;
>     /// Advances the iterator and returns the next value. Returns `Option::None` when iteration is
>     /// finished.
> ```

The trait function is documented, and this isn't adding anything specific to the impl


<!-- Sent from Reviewable.io -->

2024-12-29 14:09 UTC, orizi reviewed
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6938)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @julio4)



<!-- Sent from Reviewable.io -->

2024-12-29 15:33 UTC, julio4 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6938)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/byte_array.cairo` line 505 at r3](https://reviewable.io/reviews/starkware-libs/cairo/6938#-OFHg6Dy8VdpYBdVDUxf:-OFI2I3627T651Z0fAg3:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/ccb32b56a6e6338dd7e8936e25f9dd81d74ae531/corelib/src/byte_array.cairo#L505)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

The trait function is documented, and this isn't adding anything specific to the impl
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-30 03:40 UTC, orizi reviewed
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6938)* status: all files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2024-12-31 09:34 UTC, gilbens-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6938#-:-OFR3DnW9bHpy0yADkgX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @julio4)



<!-- Sent from Reviewable.io -->

2025-01-02 20:53 UTC, orizi approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6938)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @julio4)



<!-- Sent from Reviewable.io -->

2025-01-03 09:41 UTC, julio4 reviewed
fixed small typo

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6938#-:-OFfX9e4E6qJyeFVuwFI:b7iyium)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @gilbens-starkware and @orizi)



<!-- Sent from Reviewable.io -->

2025-01-03 17:42 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6938#-:-OFhFj1C96iGcQBoicPN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @julio4)



<!-- Sent from Reviewable.io -->

2025-01-03 17:56 UTC, merged