feat(corelib): storage vectors iterators
starkware-libs/cairo pull request #6941
Opened 2024-12-27 17:22 UTC by julio4

Add `IntoIterator` implementations for storage vectors to enable iterator syntax, in `for` loops for example.

1. `VecIntoIterator` and `MutableVecIntoIterator` for direct iteration over `StoragePath<Vec<T>>` and `StoragePath<Mutable<Vec<T>>>`
2. `PathableVecIntoIterator` and `PathableMutableVecIntoIterator` for iteration over types implementing `StorageAsPath` into storage vectors (such as Vecs in Starknet contract storage structs)

Before:
```cairo
for i in 0..vec.len() {
    let entry = vec.at(i);
}
```

After:
```cairo
for entry in vec {
    // entry: StoragePath<T> or StoragePath<Mutable<T>>
}
```

#### Examples

```cairo
use starknet::storage::{
    MutableVecTrait, PathableMutableVecIntoIterator, PathableVecIntoIterator, StoragePathEntry,
    StoragePointerReadAccess, StoragePointerWriteAccess,
};

#[starknet::contract]
mod contract_with_vec {
    use starknet::storage::Vec;
    #[storage]
    pub struct Storage {
        pub simple: Vec<u32>,
    }
}

fn vec_iter() {
    let mut mut_state = contract_with_vec::contract_state_for_testing();
    for i in 0..3_usize {
        mut_state.simple.append().write(i);
    };

    let state = @contract_with_vec::contract_state_for_testing();
    let mut i = 0;
    for entry in state.simple {
        assert_eq!(entry.read(), i);
        i += 1;
    };
    
    for entry in mut_state.simple {
        entry.write(0);
    };
}
```

2024-12-27 17:22 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6941)
<!-- Reviewable:end -->

2024-12-28 14:00 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6941)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @julio4)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6941#-OFCYeGOBWdvR0bmq_TM:-OFCYeGOBWdvR0bmq_TN:bjaw6e4) (no related file):*
i'm not sure this is actually a good idea for the time being - as this sort of hides the fact that the result vector may be very very large.

the original code at least very specifically needs to specifiy the fact that iteration over a whole section of a vector is required.
Maybe iterating over a specific range of the storage is a bit more sensible? - so both (mostly) easy but still very explicit?


<!-- Sent from Reviewable.io -->

2024-12-28 14:48 UTC, julio4 commented
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i'm not sure this is actually a good idea for the time being - as this sort of hides the fact that the result vector may be very very large.

the original code at least very specifically needs to specifiy the fact that iteration over a whole section of a vector is required.
Maybe iterating over a specific range of the storage is a bit more sensible? - so both (mostly) easy but still very explicit?
</blockquote></details>

True. But I would argue that the cognitive difference between `0..vec.len()` and `vec.into_iter()` is not that big.
Also iterators provide benefits not only loop syntax sugar, they enable interesting functional patterns and composition.

Maybe we could make size-bounded operations more clear and explicit in the code, for example by forcing iterator instanciation with explicit bound with new patterns like `vec.into_iter().take(vec.len())`/`vec.into_bounded_iter(vec.len())`?

Thoughts?


<!-- Sent from Reviewable.io -->

2024-12-28 15:08 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6941)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @julio4)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6941#-OFCYeGOBWdvR0bmq_TM:-OFCnPuF8Ust-xeGA1Rj:b-utkbot) (no related file):*
<details><summary><i>Previously, julio4 (Julio) wrote…</i></summary><blockquote>

True. But I would argue that the cognitive difference between `0..vec.len()` and `vec.into_iter()` is not that big.
Also iterators provide benefits not only loop syntax sugar, they enable interesting functional patterns and composition.

Maybe we could make size-bounded operations more clear and explicit in the code, for example by forcing iterator instanciation with explicit bound with new patterns like `vec.into_iter().take(vec.len())`/`vec.into_bounded_iter(vec.len())`?

Thoughts?
</blockquote></details>

do note that `for x in vec` would work as well - whish isn't as clear as `.into_vec` to most people probably.

the `vec.into_bounded_iter(vec.len())` sound pretty close to the idea i suggested - `vec.iter_range(4..89)` and `vec.into_full_iter_range()` style thing.

So - not providing `IntoIterator` just specific functions providing iterators sound much better to my mind.


<!-- Sent from Reviewable.io -->

2024-12-28 15:14 UTC, julio4 commented
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

do note that `for x in vec` would work as well - whish isn't as clear as `.into_vec` to most people probably.

the `vec.into_bounded_iter(vec.len())` sound pretty close to the idea i suggested - `vec.iter_range(4..89)` and `vec.into_full_iter_range()` style thing.

So - not providing `IntoIterator` just specific functions providing iterators sound much better to my mind.
</blockquote></details>

Will do, this makes sense.


<!-- Sent from Reviewable.io -->

2024-12-28 17:59 UTC, orizi requested changes
> Reviewed 2 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6941)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @julio4)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6941#-OFDPBKS2uNFirOgXRgF:-OFDPBKS2uNFirOgXRgG:b-rfpwr) (no related file):*
@gilbens-starkware 2nd eye.
___
*[`corelib/src/iter/traits/iterator.cairo` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6941#-OFDPjyy1axVZeE5nzxN:-OFDPjyy1axVZeE5nzxO:bpbnrsx) ([raw file](https://github.com/starkware-libs/cairo/blob/b57049593a7b9e8fb47d83c9ce339b82d5a00de3/corelib/src/iter/traits/iterator.cairo#L22)):*
> ```Cairo
> 
> /// Turn a collection of values into an iterator over a specific range.
> pub trait IntoIterRange<T, I> {
> ```

not sure this trait is required - why not add directly to the `VecTrait`.



_Code quote:_
```Cairo
/// Turn a collection of values into an iterator over a specific range.
pub trait IntoIterRange<T, I> {
```


<!-- Sent from Reviewable.io -->

2024-12-28 18:26 UTC, julio4 commented
*[`corelib/src/iter/traits/iterator.cairo` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6941#-OFDPjyy1axVZeE5nzxN:-OFDVxj-6cwuZjtwJaIY:buh01lr) ([raw file](https://github.com/starkware-libs/cairo/blob/b57049593a7b9e8fb47d83c9ce339b82d5a00de3/corelib/src/iter/traits/iterator.cairo#L22)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

not sure this trait is required - why not add directly to the `VecTrait`.
</blockquote></details>

I thought it could be potentially implemented by other types. If you think it's useless I can move it in `VecTrait`, or a separate `VecIterTrait`


<!-- Sent from Reviewable.io -->

2024-12-29 10:32 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6941)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @julio4)

___
*[`corelib/src/iter/traits/iterator.cairo` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6941#-OFDPjyy1axVZeE5nzxN:-OFGy0cREbdu6ca5Lql5:b-em8a3i) ([raw file](https://github.com/starkware-libs/cairo/blob/b57049593a7b9e8fb47d83c9ce339b82d5a00de3/corelib/src/iter/traits/iterator.cairo#L22)):*
<details><summary><i>Previously, julio4 (Julio) wrote…</i></summary><blockquote>

I thought it could be potentially implemented by other types. If you think it's useless I can move it in `VecTrait`, or a separate `VecIterTrait`
</blockquote></details>

i think this is more relvant specifically for storage stuff - since in the usual case probably some combination of `into_iter().skip(10).take(20)` makes more sense.


<!-- Sent from Reviewable.io -->

2024-12-29 15:28 UTC, julio4 commented
*[`corelib/src/iter/traits/iterator.cairo` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6941#-OFDPjyy1axVZeE5nzxN:-OFI0tx64r_fPgo337X_:bhhf4v9) ([raw file](https://github.com/starkware-libs/cairo/blob/b57049593a7b9e8fb47d83c9ce339b82d5a00de3/corelib/src/iter/traits/iterator.cairo#L22)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i think this is more relvant specifically for storage stuff - since in the usual case probably some combination of `into_iter().skip(10).take(20)` makes more sense.
</blockquote></details>

Should I move the IntoIterRange trait to the vec module and rename it to VecIntoIterRange, or should I extend VecTrait and MutableVecTrait directly with the new iterators methods?


<!-- Sent from Reviewable.io -->

2024-12-30 03:41 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6941)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @julio4)

___
*[`corelib/src/iter/traits/iterator.cairo` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6941#-OFDPjyy1axVZeE5nzxN:-OFKdpdz0QH4P9fkuzwo:b-hr2tdk) ([raw file](https://github.com/starkware-libs/cairo/blob/b57049593a7b9e8fb47d83c9ce339b82d5a00de3/corelib/src/iter/traits/iterator.cairo#L22)):*
<details><summary><i>Previously, julio4 (Julio) wrote…</i></summary><blockquote>

Should I move the IntoIterRange trait to the vec module and rename it to VecIntoIterRange, or should I extend VecTrait and MutableVecTrait directly with the new iterators methods?
</blockquote></details>

oh - adding one trait and using it for both is probably nicer and opens more options later - so i like it all and all.


<!-- Sent from Reviewable.io -->

2024-12-31 10:26 UTC, julio4 commented
*[`corelib/src/iter/traits/iterator.cairo` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6941#-OFDPjyy1axVZeE5nzxN:-OFREtaU9ZLKRmDE936o:b55hrje) ([raw file](https://github.com/starkware-libs/cairo/blob/b57049593a7b9e8fb47d83c9ce339b82d5a00de3/corelib/src/iter/traits/iterator.cairo#L22)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

Notice that this means that the impls will not be automatically found (is not near the trait nor the generic type) and thus it needs to be whereever it is used.
</blockquote></details>

I also think it is nicer but yes the trait need to be used. Is there any pattern to "bring" automatically the trait in the scope of VecTrait? 


<!-- Sent from Reviewable.io -->

2025-01-01 18:39 UTC, gilbens-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6941)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @julio4 and @orizi)

___
*[`corelib/src/iter/traits/iterator.cairo` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6941#-OFDPjyy1axVZeE5nzxN:-OFY7KU40RXJUDnJJoEg:b-d0wdxr) ([raw file](https://github.com/starkware-libs/cairo/blob/b57049593a7b9e8fb47d83c9ce339b82d5a00de3/corelib/src/iter/traits/iterator.cairo#L22)):*
<details><summary><i>Previously, julio4 (Julio) wrote…</i></summary><blockquote>

I also think it is nicer but yes the trait need to be used. Is there any pattern to "bring" automatically the trait in the scope of VecTrait?
</blockquote></details>

Importing another trait is fine in this case. The problem is if we need to import the impls as well, but your code seems fine in this regard, does it work if you remove the imported impls from the tests (marked in another comment)?
___
*[`crates/cairo-lang-starknet/cairo_level_tests/collections_test.cairo` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6941#-OFY9Jny4DUeIvJ7nZSs:-OFY9Jny4DUeIvJ7nZSt:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/b57049593a7b9e8fb47d83c9ce339b82d5a00de3/crates/cairo-lang-starknet/cairo_level_tests/collections_test.cairo#L4)):*
> ```Cairo
>     MutableVecTrait, PathableMutableVecIntoIterRange, PathableVecIntoIterRange, StoragePathEntry,
>     StoragePointerReadAccess, StoragePointerWriteAccess,
> };
> ```





_Suggestion:_
```Cairo
use starknet::storage::{
    MutableVecTrait, StoragePathEntry,
    StoragePointerReadAccess, StoragePointerWriteAccess,
};
use core::iter::IntoIterRange;
```


<!-- Sent from Reviewable.io -->

2025-01-03 13:12 UTC, julio4 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6941)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-starknet/cairo_level_tests/collections_test.cairo` line 4 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6941#-OFY9Jny4DUeIvJ7nZSs:-OFgHkIy-HCPQYIKXYyC:bb6tru7) ([raw file](https://github.com/starkware-libs/cairo/blob/d27581f22bc6e013c26549f1ea824f97d2d7cd0b/crates/cairo-lang-starknet/cairo_level_tests/collections_test.cairo#L4)):*
> ```Cairo
>     MutableVecTrait, PathableMutableVecIntoIterRange, PathableVecIntoIterRange, StoragePathEntry,
>     StoragePointerReadAccess, StoragePointerWriteAccess,
> };
> ```

See other comment, :done:


<!-- Sent from Reviewable.io -->

2025-01-05 16:14 UTC, orizi reviewed
> Reviewed 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6941)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @julio4)



<!-- Sent from Reviewable.io -->

2025-01-09 09:38 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6941)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @julio4 and @orizi)

___
*[`corelib/src/iter/traits/iterator.cairo` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6941#-OFDPjyy1axVZeE5nzxN:-OFv3ZgG-pRL8irr4r3d:bpl33sq) ([raw file](https://github.com/starkware-libs/cairo/blob/d27581f22bc6e013c26549f1ea824f97d2d7cd0b/corelib/src/iter/traits/iterator.cairo#L22)):*
<details><summary><i>Previously, julio4 (Julio) wrote…</i></summary><blockquote>

When not explicitly importing impls there was an error of duplicated impl.
By making `VecIntoIter` impl less generic it works correctly as it can resolved the correct impl:
```cairo
impl VecIntoIterRange<
    T, impl VecTraitImpl: VecTrait<StoragePath<Vec<T>>>,
> of IntoIterRange<StoragePath<Vec<T>>> { //... }
```

But then I have to edit `PathableVecIntoIterRange` to be able to delegate, and I didn't found a way to correctly bound `Vec<T>` to the `StorageAsPath<Vec<T>>::Value`. I tried something like this but it's not working:
```cairo
impl PathableVecIntoIterRange<
    T,
    impl PathImpl: StorageAsPath<Vec<T>>,
    impl VecTraitImpl: VecTrait<StoragePath<PathImpl::Value>>,
> of IntoIterRange<Vec<T>> {
    type IntoIter = VecIter<StoragePath<PathImpl::Value>, VecTraitImpl>;
    #[inline]
    fn into_iter_range(self: Vec<T>, range: Range<u64>) -> Self::IntoIter {
        VecIntoIterRange::<T, VecTraitImpl>::into_iter_range(self.as_path(), range)
    }
    #[inline]
    fn into_iter_full_range(self: Vec<T>) -> Self::IntoIter {
        VecIntoIterRange::<T, VecTraitImpl>::into_iter_full_range(self.as_path())
    }
}
```

In the end, it was more easy to just duplicate the implementation and not delegate, that's what I did and updated the PR. But if there's any way to correctly do trait bounds I would be curious to know!
</blockquote></details>

That's good.
But in order to implement this trait for future storage object i'd move this trait to `storage.cairo` and import the impls there too (in order for them to be automatically found).


<!-- Sent from Reviewable.io -->

2025-01-09 12:21 UTC, julio4 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6941)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/iter/traits/iterator.cairo` line 22 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6941#-OFDPjyy1axVZeE5nzxN:-OGA-_Z00rLCdXUQQw7M:b-i0xh62) ([raw file](https://github.com/starkware-libs/cairo/blob/d27581f22bc6e013c26549f1ea824f97d2d7cd0b/corelib/src/iter/traits/iterator.cairo#L22)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

That's good.
But in order to implement this trait for future storage object i'd move this trait to `storage.cairo` and import the impls there too (in order for them to be automatically found).
</blockquote></details>

I moved IntoIterRange to starknet::storage


<!-- Sent from Reviewable.io -->

2025-01-09 13:16 UTC, gilbens-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6941#-:-OGACGJ87lYvkvyk74VJ:bnfp4nl)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @julio4 and @orizi)



<!-- Sent from Reviewable.io -->

2025-01-12 09:03 UTC, orizi requested changes
> Reviewed 3 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6941)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @julio4)

___
*[`corelib/src/starknet/storage/vec.cairo` line 445 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6941#-OGOjnix34skFp8yZbTx:-OGOjnix34skFp8yZbTy:b-gx2d5r) ([raw file](https://github.com/starkware-libs/cairo/blob/23c32ab10fe9849a5d48d30c14b5a41e46f34616/corelib/src/starknet/storage/vec.cairo#L445)):*
> ```Cairo
>     fn into_iter_full_range(self: T) -> Self::IntoIter {
>         let vec = self.as_path();
>         VecIter { current_index: (0..vec.len()).into_iter(), vec }
> ```

we currently range check every access - so no need for the length read.

alternatively  - check ranges here - and use `update` instead of `get` in the iterator implementation.
(probably better)



_Suggestion:_
```Cairo
        VecIter { current_index: (0..core::num::traits::Bounded::MAX).into_iter(), vec }
```


<!-- Sent from Reviewable.io -->

2025-01-12 22:37 UTC, julio4 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6941)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/starknet/storage/vec.cairo` line 445 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6941#-OGOjnix34skFp8yZbTx:-OGRcdYy3yWcHH6lDMeF:b-9wp9rb) ([raw file](https://github.com/starkware-libs/cairo/blob/23c32ab10fe9849a5d48d30c14b5a41e46f34616/corelib/src/starknet/storage/vec.cairo#L445)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

we currently range check every access - so no need for the length read.

alternatively  - check ranges here - and use `update` instead of `get` in the iterator implementation.
(probably better)
</blockquote></details>

I'm not sure I understand what you mean by using `update`?
`get` return `None` on out of bound, so I agree we don't need to actually call `len` there.

Then, is there even a need for a range?  We could simply use `cur: u64`, to not have to create a `RangeIterator` struct.

Also range end are exclusive, so technically it can only iterate until `core::num::traits::Bounded::MAX - 1` if not mistaken, not a big issue but still maybe not exactly the specification.


<!-- Sent from Reviewable.io -->

2025-01-13 12:48 UTC, orizi requested changes
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6941)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @julio4)

___
*[`corelib/src/starknet/storage/vec.cairo` line 445 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6941#-OGOjnix34skFp8yZbTx:-OGUgkPA-963gmq_BpMX:b-i5t2hp) ([raw file](https://github.com/starkware-libs/cairo/blob/23c32ab10fe9849a5d48d30c14b5a41e46f34616/corelib/src/starknet/storage/vec.cairo#L445)):*
<details><summary><i>Previously, julio4 (Julio) wrote…</i></summary><blockquote>

I'm not sure I understand what you mean by using `update`?
`get` return `None` on out of bound, so I agree we don't need to actually call `len` there.

Then, is there even a need for a range?  We could simply use `cur: u64`, to not have to create a `RangeIterator` struct.

Also range end are exclusive, so technically it can only iterate until `core::num::traits::Bounded::MAX - 1` if not mistaken, not a big issue but still maybe not exactly the specification.
</blockquote></details>

testing the len in construction allows to not check the length on iteration.
instead of using `get` to get the entry - skipping the length check, by calling `update` instead of `get` (which just updates the hash-state without checking ranges).

about the overflow thing - i don;t see this becoming an actual issue.


<!-- Sent from Reviewable.io -->

2025-01-13 18:26 UTC, julio4 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6941)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @orizi)

___
*[`corelib/src/starknet/storage/vec.cairo` line 445 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6941#-OGOjnix34skFp8yZbTx:-OGVq3KCDt8P8mybJq60:boyzr7t) ([raw file](https://github.com/starkware-libs/cairo/blob/23c32ab10fe9849a5d48d30c14b5a41e46f34616/corelib/src/starknet/storage/vec.cairo#L445)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

testing the len in construction allows to not check the length on iteration.
instead of using `get` to get the entry - skipping the length check, by calling `update` instead of `get` (which just updates the hash-state without checking ranges).

about the overflow thing - i don;t see this becoming an actual issue.
</blockquote></details>

I see, so keeping `(0..vec.len())` in the iterator construction and directly using `update` from StoragePath. 

But do we have guarantee that the range check holds because it's an append only vec?

Consider this:
```cairo
let mut vec = [];
let mut iter = vec.into_iter_full_range();
vec.append().write(1);
assert!(iter.next().is_some());
```
This should work with `(0..core::num::traits::Bounded::MAX)`/`cur: u64` and  `get` range check at every access, but with `(0..vec.len())` and `update` it would not as the len would be 0 when the iterator is instantiated.


<!-- Sent from Reviewable.io -->

2025-01-13 19:59 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6941)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @gilbens-starkware and @julio4)

___
*[`corelib/src/starknet/storage/vec.cairo` line 445 at r6](https://reviewable.io/reviews/starkware-libs/cairo/6941#-OGOjnix34skFp8yZbTx:-OGWEa_X2CEbrpbO3zzx:bizgki0) ([raw file](https://github.com/starkware-libs/cairo/blob/23c32ab10fe9849a5d48d30c14b5a41e46f34616/corelib/src/starknet/storage/vec.cairo#L445)):*
<details><summary><i>Previously, julio4 (Julio) wrote…</i></summary><blockquote>

I see, so keeping `(0..vec.len())` in the iterator construction and directly using `update` from StoragePath. 

But do we have guarantee that the range check holds because it's an append only vec?

Consider this:
```cairo
let mut vec = [];
let mut iter = vec.into_iter_full_range();
vec.append().write(1);
assert!(iter.next().is_some());
```
This should work with `(0..core::num::traits::Bounded::MAX)`/`cur: u64` and  `get` range check at every access, but with `(0..vec.len())` and `update` it would not as the len would be 0 when the iterator is instantiated.
</blockquote></details>

so the way it is now is probably better.

in any case, i would expect the `into_iter...` to be consuming, or at least borrowing (which doesn't exist yet) - so that you won't be able to append during the iteration - but maybe sometime in the future.


<!-- Sent from Reviewable.io -->

2025-01-14 17:01 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 5 files at r3, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6941#-:-OG_klIc91jRqSoS7avK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @julio4)



<!-- Sent from Reviewable.io -->

2025-01-16 07:19 UTC, gilbens-starkware approved these changes
> Reviewed 1 of 5 files at r3, 2 of 5 files at r5, 1 of 2 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6941)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @julio4)



<!-- Sent from Reviewable.io -->

2025-01-16 07:26 UTC, merged