feat(corelib): Option iterator
starkware-libs/cairo pull request #6942
Opened 2024-12-27 20:49 UTC by cairolover

Adds `IntoIter` and `Iterator` implementations for `Option<T>`

2024-12-27 20:49 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6942)
<!-- Reviewable:end -->

2024-12-28 13:38 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6942)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cairolover)

___
*[`corelib/src/test/option_test.cairo` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6942#-OFCTWfb2QRaZOX4f0Mn:-OFCTWfb2QRaZOX4f0Mo:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/54d94778c5c032a9ab9141a25e77029b917ec3be/corelib/src/test/option_test.cairo#L146)):*
> ```Cairo
>     let x: Option<u32> = Option::Some(5);
>     let mut x_iter = x.into_iter();
>     assert!(x_iter.next() == Option::Some(5));
> ```





_Suggestion:_
```Cairo
    assert!(x_iter.next() == Option::Some(5));
    assert!(x_iter.next() == Option::None);
```
___
*[`corelib/src/option.cairo` line 479 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6942#-OFCTkio4D62sdnabxxO:-OFCTkio4D62sdnabxxP:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/54d94778c5c032a9ab9141a25e77029b917ec3be/corelib/src/option.cairo#L479)):*
> ```Cairo
>     fn next(ref self: OptionIter<T>) -> Option<T> {
>         self.inner
>     }
> ```





_Suggestion:_
```Cairo
impl OptionIterator<T> of Iterator<OptionIter<T>> {
    type Item = T;
    fn next(ref self: OptionIter<T>) -> Option<T> {
        let item = self.inner;
        self.inner = Option::None;
        item
    }
```
___
*[`corelib/src/option.cairo` line 489 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6942#-OFCU7cz5aaB4KfcuzAe:-OFCU7cz5aaB4KfcuzAf:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/54d94778c5c032a9ab9141a25e77029b917ec3be/corelib/src/option.cairo#L489)):*
> ```Cairo
>         OptionIter { inner: self }
>     }
> }
> ```





_Suggestion:_
```Cairo
impl OptionIntoIterator<T> of IntoIterator<Option<T>> {
    type IntoIter = OptionIter<T>;

    #[inline]
    fn into_iter(self: Option<T>) -> OptionIter<T> {
        OptionIter { inner: self }
    }
}
```


<!-- Sent from Reviewable.io -->

2024-12-28 13:44 UTC, cairolover reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6942)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/test/option_test.cairo` line 146 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6942#-OFCTWfb2QRaZOX4f0Mn:-OFCVRPdC27WbhSVzBDw:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/54d94778c5c032a9ab9141a25e77029b917ec3be/corelib/src/test/option_test.cairo#L146)):*
> ```Cairo
>     let x: Option<u32> = Option::Some(5);
>     let mut x_iter = x.into_iter();
>     assert!(x_iter.next() == Option::Some(5));
> ```

Done.
___
*[`corelib/src/option.cairo` line 479 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6942#-OFCTkio4D62sdnabxxO:-OFCVM_fBwm8y9rsaUqC:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/54d94778c5c032a9ab9141a25e77029b917ec3be/corelib/src/option.cairo#L479)):*
> ```Cairo
>     fn next(ref self: OptionIter<T>) -> Option<T> {
>         self.inner
>     }
> ```

Done.
___
*[`corelib/src/option.cairo` line 489 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6942#-OFCU7cz5aaB4KfcuzAe:-OFCVMuH0SfWy4bjnWFt:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/54d94778c5c032a9ab9141a25e77029b917ec3be/corelib/src/option.cairo#L489)):*
> ```Cairo
>         OptionIter { inner: self }
>     }
> }
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-28 13:48 UTC, orizi requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6942)* status: all files reviewed, 1 unresolved discussion (waiting on @cairolover)

___
*[`corelib/src/option.cairo` line 147 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6942#-OFCWBLzCJ7iIpLYBRIW:-OFCWBLzCJ7iIpLYBRIX:b-axhb2c) ([raw file](https://github.com/starkware-libs/cairo/blob/1aa81b21d4035a5cc3bc66f3e1603c7565254217/corelib/src/option.cairo#L147)):*
> ```Cairo
> //! [`into_iter`]: IntoIterator::into_iter
> 
> use crate::iter::{IntoIterator, Iterator};
> ```

probably remove the import itself - for the time being - in general until we break version 2023_01 where visibility modifiers will be ignored, we attempt to reduce the number of `use`s - as they add an actual viewable item in that case. (and here you use these still only once) 



_Code quote:_
```Cairo
use crate::iter::{IntoIterator, Iterator};
```


<!-- Sent from Reviewable.io -->

2024-12-28 14:12 UTC, cairolover reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6942)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/option.cairo` line 147 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6942#-OFCWBLzCJ7iIpLYBRIW:-OFCb8je1hUYYOME-nrX:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/1aa81b21d4035a5cc3bc66f3e1603c7565254217/corelib/src/option.cairo#L147)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

probably remove the import itself - for the time being - in general until we break version 2023_01 where visibility modifiers will be ignored, we attempt to reduce the number of `use`s - as they add an actual viewable item in that case. (and here you use these still only once)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-28 14:21 UTC, cairolover reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6942)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`corelib/src/option.cairo` line 147 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6942#-OFCWBLzCJ7iIpLYBRIW:-OFCd8ZM-UShc9IWehzR:b-67mtdq) ([raw file](https://github.com/starkware-libs/cairo/blob/1aa81b21d4035a5cc3bc66f3e1603c7565254217/corelib/src/option.cairo#L147)):*
<details><summary><i>Previously, cairolover (cairolover) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

by the way - shouldn't iterator traits be part of the prelude?


<!-- Sent from Reviewable.io -->

2024-12-28 14:42 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6942#-:-OFChsRSAdEDds93cQHq:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @cairolover)

___
*[`corelib/src/option.cairo` line 147 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6942#-OFCWBLzCJ7iIpLYBRIW:-OFChJAaAJGNfORpiQUw:b6ib13h) ([raw file](https://github.com/starkware-libs/cairo/blob/1aa81b21d4035a5cc3bc66f3e1603c7565254217/corelib/src/option.cairo#L147)):*
<details><summary><i>Previously, cairolover (cairolover) wrote…</i></summary><blockquote>

by the way - shouldn't iterator traits be part of the prelude?
</blockquote></details>

quite possibly it would make more sense.
___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6942#-OFChe61B285k5FUfFom:-OFChe61B285k5FUfFon:b-nnjwzm) (no related file):*
@enitrat for 2nd eye doc.


<!-- Sent from Reviewable.io -->

2024-12-28 15:41 UTC, enitrat reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6942#-:-OFCvJWHCFXDL_OuzJYR:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @cairolover)



<!-- Sent from Reviewable.io -->

2024-12-31 13:58 UTC, orizi requested changes
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6942)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @cairolover)

___
*[`corelib/src/test/option_test.cairo` line 1 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6942#-OFS-aZo4q2FBGJhtIpI:-OFS-aZp954X3bDM31IF:b-e0dhem) ([raw file](https://github.com/starkware-libs/cairo/blob/b554749dee4c36614aa95f8f019459ae2488f8cc/corelib/src/test/option_test.cairo#L1)):*
> ```Cairo
> use crate::iter::{IntoIterator, Iterator};
> ```

i believe shouldn't be required after rebase.



_Code quote:_
```Cairo
use crate::iter::{IntoIterator, Iterator};
```


<!-- Sent from Reviewable.io -->

2024-12-31 15:27 UTC, cairolover reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6942)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @orizi)

___
*[`corelib/src/test/option_test.cairo` line 1 at r4](https://reviewable.io/reviews/starkware-libs/cairo/6942#-OFS-aZo4q2FBGJhtIpI:-OFSJzhK8igk4MA0cpU8:bp13wxt) ([raw file](https://github.com/starkware-libs/cairo/blob/b554749dee4c36614aa95f8f019459ae2488f8cc/corelib/src/test/option_test.cairo#L1)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i believe shouldn't be required after rebase.
</blockquote></details>

The other one has not been merged yet. I'll revisit once it is


<!-- Sent from Reviewable.io -->

2025-01-01 07:06 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6942)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @cairolover)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6942#-OFVfoMm-PG5HbOAIxtZ:-OFVfoMm-PG5HbOAIxt_:b-uuj1x0) (no related file):*
@gilbens-starkware for 2nd eye.


<!-- Sent from Reviewable.io -->

2025-01-01 18:29 UTC, gilbens-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6942#-:-OFY6wdg1amqCUlPaXt0:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2025-01-02 12:39 UTC, merged