feat(corelib): add iterator traits to prelude
starkware-libs/cairo pull request #6948
Opened 2024-12-28 15:40 UTC by cairolover

2024-12-28 15:40 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6948)
<!-- Reviewable:end -->

2024-12-28 18:02 UTC, orizi requested changes
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6948)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @cairolover)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6948#-OFDQfkl6IotgZS9VksS:-OFDQfkl6IotgZS9VksT:b-uuj1x0) (no related file):*
@gilbens-starkware for 2nd eye.
___
*[`corelib/src/lib.cairo` line 392 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6948#-OFDQZosAQc_Ku6JlPZ3:-OFDQZosAQc_Ku6JlPZ4:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/5a1d39e77792ac2a13d5111b69c080867f3429ad/corelib/src/lib.cairo#L392)):*
> ```Cairo
> pub mod iter;
> #[allow(unused_imports)]
> use iter::{IntoIterator, Iterator};
> ```




<!-- Sent from Reviewable.io -->

2024-12-28 18:24 UTC, orizi reviewed
> Reviewed 4 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6948)* status: all files reviewed, 1 unresolved discussion (waiting on @cairolover)



<!-- Sent from Reviewable.io -->

2024-12-29 14:02 UTC, gilbens-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6948#-:-OFHiVCB-n8AV3jqJseJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @cairolover)



<!-- Sent from Reviewable.io -->

2025-01-02 16:14 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6948#-:-OFbms1N0IAnyqCux1mH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cairolover)



<!-- Sent from Reviewable.io -->

2025-01-02 16:28 UTC, merged