updated semantic to handle variants
starkware-libs/cairo pull request #6951
Opened 2024-12-29 11:09 UTC by dean-starkware

2024-12-29 11:10 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6951)
<!-- Reviewable:end -->

2024-12-30 03:40 UTC, orizi requested changes
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6951)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFKdNvb9ugQxL3Fh5W0:-OFKdNvcB_Y5hQ7TjiUD:b3kre) ([raw file](https://github.com/starkware-libs/cairo/blob/fcf51dab16b7b06b5fa89e9179b3446983abd8c7/crates/cairo-lang-semantic/src/expr/compute.rs#L2109)):*
> ```XML
>                 }
>             }
>             // TODO: clarify.
> ```

?



_Code quote:_
```XML
            // TODO: clarify.
```
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1383 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFHkHz02VFJS_7tGYcm:-OFHkHz19sS_VvZyQhMK:byprqdp) ([raw file](https://github.com/starkware-libs/cairo/blob/fcf51dab16b7b06b5fa89e9179b3446983abd8c7/crates/cairo-lang-semantic/src/resolve/mod.rs#L1383)):*
> ```XML
>         stable_ptr: SyntaxStablePtrId,
>         variant_id: VariantId,
>         _generic_args: &[ast::GenericArg],
> ```

Why keep this arg?
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement` line 126 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFKdaPYBkVuvbMcwihb:-OFKdaPYBkVuvbMcwihc:bbr0q2c) ([raw file](https://github.com/starkware-libs/cairo/blob/fcf51dab16b7b06b5fa89e9179b3446983abd8c7/crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement#L126)):*
> ```
>     let another_value = Var1;
>     another_value
> }
> ```

i don't understand this test mix.



_Code quote:_
```
//! > function_body
let _value: TestEnum = Var2;

//! > expr_code
{
    let another_value = Var1;
    another_value
}
```


<!-- Sent from Reviewable.io -->

2024-12-30 07:19 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6951)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFKdNvb9ugQxL3Fh5W0:-OFLQm32DcSrFeQ8Wiky:bs5ptr4) ([raw file](https://github.com/starkware-libs/cairo/blob/fcf51dab16b7b06b5fa89e9179b3446983abd8c7/crates/cairo-lang-semantic/src/expr/compute.rs#L2109)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

?
</blockquote></details>

@gilbens-starkware  


<!-- Sent from Reviewable.io -->

2024-12-30 08:03 UTC, orizi requested changes
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6951)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFKdNvb9ugQxL3Fh5W0:-OFL_ZYs4xD8rb3-WggD:b-lw386f) ([raw file](https://github.com/starkware-libs/cairo/blob/fcf51dab16b7b06b5fa89e9179b3446983abd8c7/crates/cairo-lang-semantic/src/expr/compute.rs#L2109)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

@gilbens-starkware
</blockquote></details>

You should have an assignee in the Todo, and it should be more specific in any case.


<!-- Sent from Reviewable.io -->

2024-12-30 08:07 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6951)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFKdNvb9ugQxL3Fh5W0:-OFLaKPb46zBgnagnlSb:b270na1) ([raw file](https://github.com/starkware-libs/cairo/blob/fcf51dab16b7b06b5fa89e9179b3446983abd8c7/crates/cairo-lang-semantic/src/expr/compute.rs#L2109)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

You should have an assignee in the Todo, and it should be more specific in any case.
</blockquote></details>

Yes, I agree.
But in this case- @gilbens-starkware asked to marked it as is for now.
I'm not sure why though- I'm giving him the chance to explain it before removing it.


<!-- Sent from Reviewable.io -->

2024-12-30 13:21 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6951)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement` line 126 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFKdaPYBkVuvbMcwihb:-OFMhqVz-AO10mDd5UGA:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fcf51dab16b7b06b5fa89e9179b3446983abd8c7/crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement#L126)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

i don't understand this test mix.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1383 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFHkHz02VFJS_7tGYcm:-OFMhq1T-o6VKmo8Gpvp:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fcf51dab16b7b06b5fa89e9179b3446983abd8c7/crates/cairo-lang-semantic/src/resolve/mod.rs#L1383)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

Why keep this arg?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-31 08:22 UTC, gilbens-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6951)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFKdNvb9ugQxL3Fh5W0:-OFQnAWe2ZhVbA6GrRQ0:b-qewkz8) ([raw file](https://github.com/starkware-libs/cairo/blob/fcf51dab16b7b06b5fa89e9179b3446983abd8c7/crates/cairo-lang-semantic/src/expr/compute.rs#L2109)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

Yes, I agree.
But in this case- @gilbens-starkware asked to marked it as is for now.
I'm not sure why though- I'm giving him the chance to explain it before removing it.
</blockquote></details>

The comment below is now outdated due to your changes, so update it according to your changes.


<!-- Sent from Reviewable.io -->

2024-12-31 09:13 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6951)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFQzIy_BVQckVbWsLfO:-OFQzIy_BVQckVbWsLfP:bwp2iqd) ([raw file](https://github.com/starkware-libs/cairo/blob/112cdcd01448c626a7de68574f74467ecfbffa41/crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement#L107)):*
> ```
> //! > ==========================================================================
> 
> //! > Test let statement with imported variants.
> ```

what is the `let` statement related to here?
the only thing you seem to be checking is the creation of the variant and the matching on it.
and if so - also separate into 2 tests.



_Code quote:_
```
//! > Test let statement with imported variants.
```
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement` line 129 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFQz6lb-Xe_4NByJk13:-OFQz6lb-Xe_4NByJk14:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/112cdcd01448c626a7de68574f74467ecfbffa41/crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement#L129)):*
> ```
>     };
> another_value
> }
> ```





_Suggestion:_
```
match value {
    Var2(3_u32) => Var1,
    _ => Var2(0_u32),
}
```


<!-- Sent from Reviewable.io -->

2024-12-31 11:16 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6951)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/compute.rs` line 2109 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFKdNvb9ugQxL3Fh5W0:-OFRO7xNACkki8HQyos-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fcf51dab16b7b06b5fa89e9179b3446983abd8c7/crates/cairo-lang-semantic/src/expr/compute.rs#L2109)):*
<details><summary><i>Previously, gilbens-starkware (Gil Ben-Shachar) wrote…</i></summary><blockquote>

The comment below is now outdated due to your changes, so update it according to your changes.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFQzIy_BVQckVbWsLfO:-OFRPqbiCQ3wcG3qToTk:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/112cdcd01448c626a7de68574f74467ecfbffa41/crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement#L107)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what is the `let` statement related to here?
the only thing you seem to be checking is the creation of the variant and the matching on it.
and if so - also separate into 2 tests.
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement` line 129 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFQz6lb-Xe_4NByJk13:-OFROJNO9ZAifFYs7wtR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/112cdcd01448c626a7de68574f74467ecfbffa41/crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement#L129)):*
> ```
>     };
> another_value
> }
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-31 14:01 UTC, orizi requested changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6951)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFQzIy_BVQckVbWsLfO:-OFS-v-KC0YbOP7aegff:b-guin33) ([raw file](https://github.com/starkware-libs/cairo/blob/112cdcd01448c626a7de68574f74467ecfbffa41/crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement#L107)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

again - i don't see what this has to be with a let statement - this should just include the match, and all these tests should just not be in this file.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1122 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFS0CqB7bC5BkmgD7B9:-OFS0CqB7bC5BkmgD7BA:bspjc0y) ([raw file](https://github.com/starkware-libs/cairo/blob/fcf51dab16b7b06b5fa89e9179b3446983abd8c7/crates/cairo-lang-semantic/src/resolve/mod.rs#L1122)):*
> ```XML
>                     identifier.stable_ptr().untyped(),
>                     var.id,
>                     &generic_args_syntax.unwrap_or_default(),
> ```

what happens if anyone actually tries to supply generics after?
add a test to see the relevant diagnostics.



_Code quote:_
```XML
                    &generic_args_syntax.unwrap_or_default(),
```


<!-- Sent from Reviewable.io -->

2024-12-31 14:16 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6951)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFQzIy_BVQckVbWsLfO:-OFS2Cof-wOrfs42CY8o:bcolke0) ([raw file](https://github.com/starkware-libs/cairo/blob/112cdcd01448c626a7de68574f74467ecfbffa41/crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement#L107)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

again - i don't see what this has to be with a let statement - this should just include the match, and all these tests should just not be in this file.
</blockquote></details>

I want to test the creation of a variant. That's the reasoning behind the first test, which I do believe should be here.
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1122 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFS0CqB7bC5BkmgD7B9:-OFS3ZHrEttLbE8L4aPo:b-fmdzrt) ([raw file](https://github.com/starkware-libs/cairo/blob/fcf51dab16b7b06b5fa89e9179b3446983abd8c7/crates/cairo-lang-semantic/src/resolve/mod.rs#L1122)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

what happens if anyone actually tries to supply generics after?
add a test to see the relevant diagnostics.
</blockquote></details>

Can you please explain what do you mean by "generics after"?
A short example would be helpful.


<!-- Sent from Reviewable.io -->

2024-12-31 14:25 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6951)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFQzIy_BVQckVbWsLfO:-OFS5ffy9DNgpscKShlE:b8fd3ud) ([raw file](https://github.com/starkware-libs/cairo/blob/112cdcd01448c626a7de68574f74467ecfbffa41/crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement#L107)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

I want to test the creation of a variant. That's the reasoning behind the first test, which I do believe should be here.
</blockquote></details>

you can create a variant without a let statement - just have your expression a creation of a variant.

but this means it should be tested here.


<!-- Sent from Reviewable.io -->

2024-12-31 14:36 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6951)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1122 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFS0CqB7bC5BkmgD7B9:-OFS7snB95jYoX93uJ9R:b-7bqmbk) ([raw file](https://github.com/starkware-libs/cairo/blob/fcf51dab16b7b06b5fa89e9179b3446983abd8c7/crates/cairo-lang-semantic/src/resolve/mod.rs#L1122)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

Can you please explain what do you mean by "generics after"?
A short example would be helpful.
</blockquote></details>

this code ignored its given generic args for variants - so you need to tell me where these should come from and why can you ignore them.

so - it really depends on the context you are getting the variant here.

It is probably at something like: `Some<u8>` which obviously shouldn't work - but i'm not sure what is going to happen.


<!-- Sent from Reviewable.io -->

2025-01-01 12:26 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6951)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFQzIy_BVQckVbWsLfO:-OFWmVNh5nIB3AH01_Mj:b-l39y40) ([raw file](https://github.com/starkware-libs/cairo/blob/112cdcd01448c626a7de68574f74467ecfbffa41/crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement#L107)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

you can create a variant without a let statement - just have your expression a creation of a variant.

but this means it should be tested here.
</blockquote></details>

Done. (+ kept it here as requested)
___
*[`crates/cairo-lang-semantic/src/resolve/mod.rs` line 1122 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFS0CqB7bC5BkmgD7B9:-OFWmWIn2c9D8anqM61R:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/fcf51dab16b7b06b5fa89e9179b3446983abd8c7/crates/cairo-lang-semantic/src/resolve/mod.rs#L1122)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

this code ignored its given generic args for variants - so you need to tell me where these should come from and why can you ignore them.

so - it really depends on the context you are getting the variant here.

It is probably at something like: `Some<u8>` which obviously shouldn't work - but i'm not sure what is going to happen.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-02 12:23 UTC, orizi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6951)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement` line 107 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFQzIy_BVQckVbWsLfO:-OFaxooG-Qci9Spw64v3:b-4ebwfa) ([raw file](https://github.com/starkware-libs/cairo/blob/112cdcd01448c626a7de68574f74467ecfbffa41/crates/cairo-lang-semantic/src/expr/semantic_test_data/let_statement#L107)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

Done. (+ kept it here as requested)
</blockquote></details>

You misunderstood - non of the test should be in this file, this does not test the let statements features.

But the added test are important.


<!-- Sent from Reviewable.io -->

2025-01-02 16:09 UTC, orizi requested changes
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6951)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1388 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFbleJV37IiIn7gDFQ6:-OFbleJV37IiIn7gDFQ7:b-74quhb) ([raw file](https://github.com/starkware-libs/cairo/blob/79cdda32065e9b4a261f723b5bfccb691934c8dd/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1388)):*
> ```
> 
> //! > function_body
> let value = Variant::<u32>(3);
> ```

should this compile? i don't really think so.
what happens in rust?



_Code quote:_
```
let value = Variant::<u32>(3);
```


<!-- Sent from Reviewable.io -->

2025-01-02 16:10 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6951)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1414 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFblphSEHkfJ_VW3x6N:-OFblphSEHkfJ_VW3x6O:bgtay0z) ([raw file](https://github.com/starkware-libs/cairo/blob/79cdda32065e9b4a261f723b5bfccb691934c8dd/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1414)):*
> ```
> 
> //! > expr_code
> value
> ```

also should probably not compile - variant shouldn't have generic parameters (unlike the enum itself)



_Suggestion:_
```
//! > function_body

//! > expr_code
Some::<i64>(3_u32)
```
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1446 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFbm0pQ4INUNfm9pl4a:-OFbm0pRC_Rb7D1cNPs3:b-7ropln) ([raw file](https://github.com/starkware-libs/cairo/blob/79cdda32065e9b4a261f723b5bfccb691934c8dd/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1446)):*
> ```
> 
> //! > expr_code
> value
> ```

ditto



_Suggestion:_
```

//! > expr_code
test::Variant::<u32>(3)
```


<!-- Sent from Reviewable.io -->

2025-01-02 16:25 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6951)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware, @orizi, and @TomerStarkware)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1388 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFbleJV37IiIn7gDFQ6:-OFbp9Yl1YZj2FvVYapy:b-idpxhk) ([raw file](https://github.com/starkware-libs/cairo/blob/79cdda32065e9b4a261f723b5bfccb691934c8dd/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1388)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

should this compile? i don't really think so.
what happens in rust?
</blockquote></details>

It does compile!
@TomerStarkware , @gilbens-starkware , and I had fun playing with that.
All of the tests are valid.


<!-- Sent from Reviewable.io -->

2025-01-02 16:31 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6951)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @dean-starkware and @gilbens-starkware)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1388 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFbleJV37IiIn7gDFQ6:-OFbqnql1Ez4h30O_Guy:b-gi32qv) ([raw file](https://github.com/starkware-libs/cairo/blob/79cdda32065e9b4a261f723b5bfccb691934c8dd/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1388)):*
<details><summary><i>Previously, dean-starkware wrote…</i></summary><blockquote>

It does compile!
@TomerStarkware , @gilbens-starkware , and I had fun playing with that.
All of the tests are valid.
</blockquote></details>

surprising - but true.
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1391 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFbquCz4kFtNIu-dI1c:-OFbquCz4kFtNIu-dI1d:undefined) ([raw file](https://github.com/starkware-libs/cairo/blob/79cdda32065e9b4a261f723b5bfccb691934c8dd/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1391)):*
> ```
> 
> //! > expr_code
> value
> ```





_Suggestion:_
```
//! > function_body

//! > expr_code
Variant::<u32>(3)
```


<!-- Sent from Reviewable.io -->

2025-01-04 04:41 UTC, dean-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6951)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @gilbens-starkware and @orizi)

___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1414 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFblphSEHkfJ_VW3x6N:-OFjbHXI2IxE70tHZ171:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/79cdda32065e9b4a261f723b5bfccb691934c8dd/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1414)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

also should probably not compile - variant shouldn't have generic parameters (unlike the enum itself)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1446 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFbm0pQ4INUNfm9pl4a:-OFjbT8V6xoBKFFWMtZb:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/79cdda32065e9b4a261f723b5bfccb691934c8dd/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1446)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`crates/cairo-lang-semantic/src/expr/semantic_test_data/use` line 1391 at r5](https://reviewable.io/reviews/starkware-libs/cairo/6951#-OFbquCz4kFtNIu-dI1c:-OFjbDpo8ozpbPyDaskg:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/79cdda32065e9b4a261f723b5bfccb691934c8dd/crates/cairo-lang-semantic/src/expr/semantic_test_data/use#L1391)):*
> ```
> 
> //! > expr_code
> value
> ```

Done.


<!-- Sent from Reviewable.io -->

2025-01-04 04:48 UTC, orizi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6951#-:-OFjd7s1AALm60sx62OG:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @gilbens-starkware)



<!-- Sent from Reviewable.io -->

2025-01-04 05:00 UTC, merged