Added const for starknet types.
starkware-libs/cairo pull request #6961
Opened 2024-12-31 09:50 UTC by orizi

2024-12-31 09:50 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/cairo/6961)
<!-- Reviewable:end -->

2025-01-02 11:38 UTC, liorgold2 requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6961)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @orizi)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6961#-OFamq-nAQ5buq-Nzqzg:-OFamq-o95-JtnL9gkzj:bebf8ny) (no related file):*
Missing failure test (initializing with an invalid value)
___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6961#-OFan66qD9aHC9Gfhl6P:-OFan66qD9aHC9Gfhl6Q:b-rfm7wq) ([raw file](https://github.com/starkware-libs/cairo/blob/c7d7e1e7c60106a0a371492d4b4397959ce04606/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L12)):*
> ```XML
> use super::int::unsigned128::Uint128Type;
> use super::non_zero::NonZeroType;
> use super::starknet::interoperability::{ClassHashType, ContractAddressType};
> ```

Are we ok with this dependency? (I guess we are)
___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6961#-OFanSt4D8slgL4l4HBT:-OFanSt4D8slgL4l4HBU:b67hcjw) ([raw file](https://github.com/starkware-libs/cairo/blob/c7d7e1e7c60106a0a371492d4b4397959ce04606/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L74)):*
> ```XML
> ) -> Result<(), SpecializationError> {
>     let inner_type_info = context.get_type_info(inner_ty.clone())?;
>     let type_range = if inner_type_info.long_id.generic_id == StructType::ID {
> ```

This is slightly confusing.
Split to two paragraphs:
```
if ... {
    return validate...(...);
} else if ... {
    return validate...(...);
} else if ... {
    return validate...(...);
}

let type_range = if ... {
    ...
} else {
    ...
}
...
```


<!-- Sent from Reviewable.io -->

2025-01-02 11:39 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6961)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6961#-OFao1zeEXg_FjR2FTwj:-OFao1zeEXg_FjR2FTwk:b-xm7ii0) ([raw file](https://github.com/starkware-libs/cairo/blob/c7d7e1e7c60106a0a371492d4b4397959ce04606/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L81)):*
> ```XML
>         return validate_const_nz_data(context, &inner_type_info, inner_data);
>     } else if [ContractAddressType::id(), ClassHashType::id()]
>         .contains(&inner_type_info.long_id.generic_id)
> ```

Move this to a variable. It appears many times in this function and will make this particular line shorter.



_Code quote:_
```XML
inner_type_info.long_id.generic_id
```


<!-- Sent from Reviewable.io -->

2025-01-02 11:41 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6961)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6961#-OFaoUEo0VIIg44AO2PL:-OFaoUEo0VIIg44AO2PM:b-w1e5cv) ([raw file](https://github.com/starkware-libs/cairo/blob/c7d7e1e7c60106a0a371492d4b4397959ce04606/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L83)):*
> ```XML
>         .contains(&inner_type_info.long_id.generic_id)
>     {
>         Range::half_open(0, BigInt::one().shl(251))
> ```

I guess this appears in the libfunc as well, so I prefer to have it defined once, in a starknet module and not here.



_Code quote:_
```XML
BigInt::one().shl(251)
```


<!-- Sent from Reviewable.io -->

2025-01-02 12:00 UTC, liorgold2 reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6961)* status: all files reviewed, 5 unresolved discussions (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2025-01-02 17:16 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6961)* status: all files reviewed, 5 unresolved discussions (waiting on @liorgold2)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo/6961#-OFamq-nAQ5buq-Nzqzg:-OFc05NL3Ps2DWBEnvIo:b-896fix) (no related file):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Missing failure test (initializing with an invalid value)
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6961#-OFan66qD9aHC9Gfhl6P:-OFayEob246zWwisQLFb:b-vqlfsh) ([raw file](https://github.com/starkware-libs/cairo/blob/c7d7e1e7c60106a0a371492d4b4397959ce04606/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L12)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Are we ok with this dependency? (I guess we are)
</blockquote></details>

Don't think we have much of a choice.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6961#-OFanSt4D8slgL4l4HBT:-OFbsTUo2E68_nFnjNw-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c7d7e1e7c60106a0a371492d4b4397959ce04606/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L74)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

This is slightly confusing.
Split to two paragraphs:
```
if ... {
    return validate...(...);
} else if ... {
    return validate...(...);
} else if ... {
    return validate...(...);
}

let type_range = if ... {
    ...
} else {
    ...
}
...
```
</blockquote></details>

Done.
___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6961#-OFao1zeEXg_FjR2FTwj:-OFbsVyu5yu0fJmW1N7-:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c7d7e1e7c60106a0a371492d4b4397959ce04606/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L81)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Move this to a variable. It appears many times in this function and will make this particular line shorter.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-12 17:59 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6961)* status: all files reviewed, 5 unresolved discussions (waiting on @liorgold2)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/cairo/6961#-OFaoUEo0VIIg44AO2PL:-OGQf-TS5T915-FXLkWR:b-896fix) ([raw file](https://github.com/starkware-libs/cairo/blob/c7d7e1e7c60106a0a371492d4b4397959ce04606/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L83)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I guess this appears in the libfunc as well, so I prefer to have it defined once, in a starknet module and not here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-14 08:40 UTC, liorgold2 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6961)* status: 1 of 3 files reviewed, 3 unresolved discussions



<!-- Sent from Reviewable.io -->

2025-01-14 08:51 UTC, liorgold2 approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6961)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)



<!-- Sent from Reviewable.io -->

2025-01-14 08:52 UTC, shaharsamocha7 requested changes
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6961)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6961#-OGZ-6epElcYbPZrUVvY:-OGZ-6epElcYbPZrUVvZ:byj6j6x) ([raw file](https://github.com/starkware-libs/cairo/blob/df567768292de59437d2a7e7230121bfd7f919de/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L83)):*
> ```XML
>         return validate_const_nz_data(context, &inner_type_info, inner_data);
>     }
>     let type_range = if *inner_generic_id == ContractAddressType::id() {
> ```

Why these cases are not in from_type_info



_Code quote:_
```XML
    let type_range = if *inner_generic_id == ContractAddressType::id() {
```


<!-- Sent from Reviewable.io -->

2025-01-14 08:55 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6961)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6961#-OGZ-6epElcYbPZrUVvY:-OGZ0UJiD5VoEW_5POjJ:b6c21zx) ([raw file](https://github.com/starkware-libs/cairo/blob/df567768292de59437d2a7e7230121bfd7f919de/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L83)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why these cases are not in from_type_info
</blockquote></details>

they'd be considered a valid BoundedInt in that case, and this is probably bad.


<!-- Sent from Reviewable.io -->

2025-01-15 10:54 UTC, liorgold2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6961#-:-OGdaJsu2pFgqEFxI1KM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)



<!-- Sent from Reviewable.io -->

2025-01-15 10:58 UTC, shaharsamocha7 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6961)* status: all files reviewed, 1 unresolved discussion (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6961#-OGZ-6epElcYbPZrUVvY:-OGdbFYxDyPEclK7Beml:b-4obglq) ([raw file](https://github.com/starkware-libs/cairo/blob/df567768292de59437d2a7e7230121bfd7f919de/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L83)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

they'd be considered a valid BoundedInt in that case, and this is probably bad.
</blockquote></details>

you also have bytes31 there.
Unblocking


<!-- Sent from Reviewable.io -->

2025-01-15 11:02 UTC, orizi reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo/6961)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @orizi)

___
*[`crates/cairo-lang-sierra/src/extensions/modules/const_type.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/cairo/6961#-OGZ-6epElcYbPZrUVvY:-OGdc-_PBBuT2--lvjcP:b-f1m40t) ([raw file](https://github.com/starkware-libs/cairo/blob/df567768292de59437d2a7e7230121bfd7f919de/crates/cairo-lang-sierra/src/extensions/modules/const_type.rs#L83)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

you also have bytes31 there.
Unblocking
</blockquote></details>

I consider Bytes31 as u248, more than i consider ContractAddress and ClassHash as u251.


<!-- Sent from Reviewable.io -->

2025-01-15 11:08 UTC, merged